### ISSUE TITLE
[BUG] SVG Icons in navbar broken in touch mode

### ISSUE THREAD

**Issue by MeikelLP** [buefy/buefy#1000]
### Overview of the problem

**Buefy** version: 0.6.7
**Vuejs** version: 2.5.17
**OS/Browser**: Fedora 28/Firefox 62.0

### Description

The SVG icons from [vue-fontawesome](https://www.npmjs.com/package/@fortawesome/vue-fontawesome) in the navbar in touch mode are have too much padding.

### Steps to reproduce

https://codepen.io/anon/pen/gdZYLm (only in touch / mobile mode / window width)

### Expected behavior

![buefy bug expected](https://user-images.githubusercontent.com/11669846/45734983-a5015400-bbe6-11e8-8950-838b895eee38.png)

### Actual behavior

![buefy bug actual](https://user-images.githubusercontent.com/11669846/45734974-a0d53680-bbe6-11e8-826c-34d91ba71c14.png)

**Comment by jtommy** [comment]
@MeikelLP We don't support svg icon at the moment
