### ISSUE TITLE
Timepicker is not closing when clicking on other input fields

### ISSUE THREAD

**Issue by dasmikko** [buefy/buefy#1001]
### Overview of the problem
Update: I just refreshed the home page, and now I cannot reproduce on the docs.

Is it then fixed in the next versoin?

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.17]
**OS/Browser**: Windows 10 / Chrome 69

### Description
When clicking on timepicker field, the picker opens as expected, but when you click on another field, it does not close the first one.

It only closes if you click on the field again, or outside the field (Not on other fields)

### Steps to reproduce
1. Click on timepicker 1 (It opens)
2. Click on timpicker 2 (it opens too)
3. Timepicker 1 does not close
4. Click outside of fields
5, Both timerpicker 1 and 2 closes now

### Expected behavior
Timepicker should close if clicked on other fields

### Actual behavior
Does not close until clicked on again or outside the field

![2018-09-19_10-46-08](https://user-images.githubusercontent.com/4254869/45742010-4396b080-bbf9-11e8-88f9-b6b77f77f3d3.gif)

**Comment by ais-one** [comment]
Datepicker has same problem as well

**Comment by jtommy** [comment]
@dasmikko Clean cache, because i think you're seeing an old version of buefy docs and in the last release 0.6.7 it was fixed.
