### ISSUE TITLE
Feature Request: timeline component

### ISSUE THREAD

**Issue by cvgeldern** [buefy/buefy#1003]
As I'm working on a project where an overview of past events is a requirement, a timeline would be very nice. For now I need an vertical overview, but an horizontal overview might become handy too, later.

Example:
https://i.redd.it/06icnq45zuh11.png

**Comment by nextgensparx** [comment]
@cvgeldern You might be interested in this Bulma extension https://wikiki.github.io/components/timeline/

**Comment by cvgeldern** [comment]
@nextgensparx OMG how could I have missed that... I'll try that one out first.
