### ISSUE TITLE
Can't use components outside of Vue instance in v0.6.7

### ISSUE THREAD

**Issue by nextgensparx** [buefy/buefy#1004]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.17]
**OS/Browser**: Linux Mint 19 / Chrome 61.0.3163.100

### Description

In v0.6.7 programmatic components can no longer be imported. This includes: 
- Dialog
- LoadingProgrammatic
- ModalProgrammatic
- Snackbar
- Toast

It seems like they are no longer exported at all. Is this intentional? I saw no mention of this in the [changelog](https://github.com/buefy/buefy/releases/tag/v0.6.7). If this is intentional, wouldn't it be better to bump the version to 0.7 since this is a breaking change?

### Steps to reproduce

Import and use `ModalProgrammatic` according to the [docs](https://buefy.github.io/#/documentation/modal)
```js
// From outside Vue instance
import { ModalProgrammatic } from 'buefy'
ModalProgrammatic.open(props)
```

### Expected behavior

A modal should appear.

### Actual behavior

A modal does not appear and the following error is logged:
```
Uncaught TypeError: Cannot read property 'open' of undefined
```

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/990

**Comment by nextgensparx** [comment]
My apologies. I somehow missed all the other issues.
