### ISSUE TITLE
Help wanted to handle several tabs exceeding window size

### ISSUE THREAD

**Issue by robertotru** [buefy/buefy#1005]
This is not an issue, it instead fits into the _help wanted_ category.

So, let's say you want to use the Buefy [tabs ](https://buefy.github.io/#/documentation/tabs) and that the amount of tabs you have or just the length of the headers exceed the available space. How should I handle this?

In my IDE, for instance, I do see a solution consisting in a buttons showing a dropdown with the list of hidden tabs (i.e. those not fitting the window size. Should I implement such a feature or is Buefy providing any alternative?

**Comment by jtommy** [comment]
@robertotru Buefy tabs are like Bulma style and we aren't going to add any special feature at the moment.
