### ISSUE TITLE
Icons on website are not loading correctly.

### ISSUE THREAD

**Issue by nmihaica** [buefy/buefy#1007]
![buefybug](https://user-images.githubusercontent.com/12017390/45914246-7d0e2c80-be42-11e8-8c4e-e1db511b9ec8.gif)

### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**: Google Chrome 67.0.3396.87

### Expected behavior

Icons loaded.

### Actual behavior

Icons not loading.

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/995

**Comment by gvdp** [comment]
Getting the same kind of behaviour currently on the documentation site:

![image](https://user-images.githubusercontent.com/11733084/51280318-a3eb0280-19df-11e9-9735-0d5037d14052.png)

Clearing chache etc. doesn't work. I noticed in devtools that the calls to fetch the icons are returning a http 404, e.g.

https://buefy.github.io/static/fonts/materialdesignicons-webfont.13621ea.ttf

**Comment by jtommy** [comment]
@gvdp clean your browser cache. The new docs link is without #, https://buefy.github.io
