### ISSUE TITLE
b-table, date not displayed in Safari

### ISSUE THREAD

**Issue by WalkingInTheDarkness** [buefy/buefy#1008]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.17]
**Laravel** version: [5.7.4]
** hosted on Linux shared server **
**OS X/Safari.  OS X/Firefox**:

### Description

I am using Buefy Table component to display list of resources in admin panel. One of the columns is "Registered" column displaying date when resource has been created (it is "created_at" column in database, type: timestamp):

![b-table-mysql](https://user-images.githubusercontent.com/34058704/45928928-f0976300-bf42-11e8-93db-a493ad8e9a47.png)

```
<b-table-column 
       field="created_at" 
       label="Registered at" 
       centered
>
       <span class="tag is-success">
                {{ new Date(props.row.created_at).toLocaleDateString() }}
       </span>
</b-table-column>
```

![b-table-vue](https://user-images.githubusercontent.com/34058704/45928891-5800e300-bf42-11e8-8daa-cdbf16f7c477.png)

### Expected behavior

date should be displayed correctly regardless of the browser

### Actual behavior

In Firefox - date is displayed correctly:

![b-table-firefox](https://user-images.githubusercontent.com/34058704/45928817-a82b7580-bf41-11e8-9c87-2e32b0d675d2.png)

In Safari - instead of date "Invalid date" text is displayed:

![b-table-safari](https://user-images.githubusercontent.com/34058704/45928822-b4173780-bf41-11e8-8b80-91dc7aed6b3e.png)

**Comment by jtommy** [comment]
@WalkingInTheDarkness It's no Buefy issue. Check if that function is compatible with Safari otherwise you might use a your method to show the date

**Comment by WalkingInTheDarkness** [comment]
will check this then, but to be honest this line is copied from Buefy documentation

**Comment by jtommy** [comment]
@WalkingInTheDarkness Is buefy doc working with Safari ?

**Comment by WalkingInTheDarkness** [comment]
@jtommy what do you mean?
