### ISSUE TITLE
font awesome 5.2.0 with buefy 0.6.7 from cdn defaultIconPack

### ISSUE THREAD

**Issue by romikforest** [buefy/buefy#1009]
Is it possible to use defaultIconPack: 'fas' with buefy loaded from cdn. I init it as:

```
 Vue.use(Buefy, {
     defaultIconPack: 'fas',
 });
```

or as

```
 Vue.use(Buefy.default, {
     defaultIconPack: 'fas',
 });
```

but b-icons use material design. The font awesome is loaded and it's icons can be shown like:

`<span class="icon "><i class="fas fa-cog "></i></span>`

or with explicit `pack='fas'`

vue@2.5.17
buefy@0.6.7
fa@5.2.0

**Comment by jtommy** [comment]
@romikforest In 0.6.7 you haven't to add nothing and so you cannot use constructor options. But we are working to a solution adding a new programmatic component https://github.com/buefy/buefy/commit/455462ad8de23647460816f803f0dbe44ae8c7a1
