### ISSUE TITLE
Buefy Sketch files - UI Workflow

### ISSUE THREAD

**Issue by f3r** [buefy/buefy#1013]
Hi guys,

We super excited that we are starting our new project using Buefy! After sharing with our UI designers, they asked us if there is any plan or current sketch design for the framework to use as a baseline for the styleguide.

I found https://github.com/joachimesque/Bulma.sketch and looks pretty neat, but it doesn't have all the amazing buefy components. Can anyone point us in the right direction?

Thanks a lot!!
/f3r

**Comment by jtommy** [comment]
@f3r We are very happy!
About sketch I don't know but you could ask to the author of Bulma sketch to add Buefy components.
