### ISSUE TITLE
Bug: Select, native-size

### ISSUE THREAD

**Issue by Esquimor** [buefy/buefy#1014]
### Version

**Buefy** version: 0.6.7

### Description

If we add native-size to b-select, the component doesn't work anymore

### jsfiddle

https://jsfiddle.net/eywraw8t/405014/

**Comment by jtommy** [comment]
@Esquiro69 We added `native-size` prop related to `multiple` prop, but anyway it's a Bulma issue.
 Did you open an issue to Bulma repository ?

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy ? close.
