### ISSUE TITLE
b-columns / b-column

### ISSUE THREAD

**Issue by blowsie** [buefy/buefy#1016]
Sorry if this has been asked before i did check the comments but couldn't find anything.

### Description

Whats is Beufy's philosophy on creating components?
Coming from other UI kits I found it very strange that `<b-columns>` and `<b-column>` components do not exist.

Are they planned or was there a design decision not to create them?

Thanks

**Comment by jtommy** [comment]
See roadmap https://github.com/buefy/buefy/issues/458 to know our idea but anyway we are open to improve it.
