### ISSUE TITLE
The table header disappears in the last page.

### ISSUE THREAD

**Issue by shihao7i** [buefy/buefy#1018]
The table header disappears in the last page.

Buefy version: [0.6.7]
Vuejs version: [2.5.17]
OS/Browser: Chrome/Windows

### Description

One question here. Based on the example you provide in Codepen. https://codepen.io/pen?&editors=101

I removed one item from the data array, now it has 59 items, then went to the last page, the table header disappeared, it seems that header will disappear if a number of items in the last page is less than a number we define in perPage. Is it a bug or a normal behavior which is designed by default as you intended? Just want to know this.

Thank you for your great work for this project!

![table_header_issue](https://user-images.githubusercontent.com/7623006/46513519-74c6e000-c88b-11e8-8645-2d48ee795e5f.PNG)
[](url)
### Steps to reproduce

https://codepen.io/pen?&editors=101
1. Removing the last item from the data array.
2. Going to the last page. 
3. You can see the table header disappears.

### Expected behavior
I expected the table header will show even the last page doesn't have 5 items if we set up 
`perPage: 5
`

### Actual behavior
If the last page contains a number of items which is less than the number of perPage. The table header disappears.

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/994
