### ISSUE TITLE
Change icon of detailed arrow in table

### ISSUE THREAD

**Issue by Japangeek** [buefy/buefy#1022]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.17]
**OS/Browser**: Mac OS / Chrome

### Description

Is there any way to change the b-table's detailed arrow-icon? As example to fontawesome and other type of icon instead arrow, like circle?
I tried to put icon-pack="fas" attribute on b-table but somehow it still choose the mdi icon-pack. Am I doing it wrong?

**Comment by Japangeek** [comment]
okay, using defaultIconPack from Vue.use does works and choose fontawesome. But it would be better if you could change the icon/pack directly in b-table.

**Comment by jtommy** [comment]
@Japangeek There was an issue but it's just fixed https://github.com/buefy/buefy/commit/317ac9672073b15c3fb2135f45865942039741fb
