### ISSUE TITLE
Upload component is not SSR friendly

### ISSUE THREAD

**Issue by cesasol** [buefy/buefy#1024]
**Buefy** version: [0.7.0]
**Vuejs** version: [2.5.17]
**OS/Browser**: Node Js / Nuxt

### Description
Latest update broke SSR compatibility by checking for File in a prop without making sure is defined if not available globally

### Steps to reproduce

Just use buefy as a plugin on nuxt with universal mode

### Expected behaviour

Fake the File property if not available on the global scope

### Actual behaviour

`ReferenceError: File is not defined`

**Comment by willhoyle** [comment]
Can confirm. Got the same error

**Comment by jtommy** [comment]
@cesasol,  the fix will be available in the next version (`v0.7.1`).  But as workaround add this line to your file nuxt.config.js

```js
// nuxt.config.js

global.File= typeof window === 'undefined' ? Object : window.File

...
```

**Comment by nnfans** [comment]
> @cesasol, the fix will be available in the next version (`v0.7.1`). But as workaround add this line to your file nuxt.config.js
> 
> ```js
> // nuxt.config.js
> 
> global.File= typeof window === 'undefined' ? Object : window.File
> 
> ...
> ```

Hope it will be fixed in v0.7.1 because someone said it will be fixed in the v0.6.4 back then

> @azeranex , the fix will be available in the next version (`v0.6.4`). But for you to continue your tasks add this line to your file nuxt.config.js
> 
> ```js
> // nuxt.config.js
> 
> global.HTMLElement = typeof window === 'undefined' ? Object : window.HTMLElement
> 
> ...
> ```

**Comment by rikoz** [comment]
Is there a fix for this yet, experiencing the same issue

**Comment by jtommy** [comment]
https://github.com/buefy/nuxt-buefy/issues/32

**Comment by shawnlauzon** [comment]
I've verified, this solves the problem.
