### ISSUE TITLE
tabs nav is not active by v-model

### ISSUE THREAD

**Issue by pakkaparn** [buefy/buefy#1026]
### Overview of the problem

**Buefy** version: [0.7.0]
**Vuejs** version: [2.5.16]
**OS/Browser**:
MacOs/Chrome
### Description

tab nav is not active by v-model

![alt text](https://i.imgur.com/fsYvB3G.png)

```
<b-tabs type="is-boxed" class="column" v-model="tabIndex">
```
```
computed: {
    tabIndex: {
      get() {
        return this.$route.query.tab;
      },
      set(index) {
        this.$router.replace({ query: { tab: index } });
      },
    },
}
```

**Comment by jtommy** [comment]
@pakkaparn The component accepts string value but it's no the correct way, we'll fix it.
Try to use `parseInt `function in the `get `of `tabIndex`
