### ISSUE TITLE
Remove chevron cell in detailed table

### ISSUE THREAD

**Issue by jayehernandez** [buefy/buefy#1028]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.17]
**OS/Browser**: Mac

### Description

I'm using the detailed table and I was wondering if there is a way to remove the chevron cell on the left side?

For context, all the detailed rows are open from the start.

### Steps to reproduce

I tried to manipulate the `.chevron-cell` class to have `display: none` or `visibility: none` and but this made the row weird.

**Comment by jtommy** [comment]
@wanxe What do you think ?

**Comment by wanxe** [comment]
@jayehernandez @jtommy We have a prop already to do this:
```https://buefy.github.io/#/documentation/table```
`has-detailed-visible`

**Comment by jayehernandez** [comment]
@jtommy @wanxe I completely missed that! Thank you!

**Comment by oldcastor** [comment]
`has-detailed-visible` removes the chevron icon, but don't affect the column itself.

Using your detailed table example [codepen](https://codepen.io/pen?&editable=true&editors=101)
Just add `:has-detailed-visible="()=>false"` to table definition and you will see empty column. Is there any chance to get rid of it too?

**Comment by oldcastor** [comment]
@jtommy Sorry, maybe i'm getting something wrong, but looks like `:has-detailed-visible="()=>false"` is not equivalent to `:detailed="false"`
[here](https://codepen.io/oldcastor/pen/EGxdpr) is standard detaild table (+ bordered). 
![def-1](https://user-images.githubusercontent.com/21212418/49714061-1f74c980-fc54-11e8-9555-7fa1935e8139.png)

Having `:detailed="false"` leads to 
![def-2](https://user-images.githubusercontent.com/21212418/49714129-6f539080-fc54-11e8-9327-a7cd6a8feb03.png)
(no 'chevron' column)

Now adding `:has-detailed-visible="()=>false"` or  `:has-detailed-visible="(row)=>false"` giving this result 
![def-3](https://user-images.githubusercontent.com/21212418/49714912-687a4d00-fc57-11e8-9510-b1d7561fdfa6.png).
I understand that this made for hiding individual rows details view, my bad in previous post. But if i want to use detailed prop and take care of opening and closing details by myself (opening rows by select, for example) i don't need the chevron column at all. Is there any way to get rid of it?

**Comment by jtommy** [comment]
@oldcastor now I understand but please a new issue. It will be a feature request

**Comment by oldcastor** [comment]
@jtommy https://github.com/buefy/buefy/issues/1140
