### ISSUE TITLE
Unexpected behavior when two autocompletes are linked

### ISSUE THREAD

**Issue by jmgilmour** [buefy/buefy#1030]
### Overview of the problem

**Buefy** version: 0.7.0
**Vuejs** version: 2.5.17
**OS/Browser**: Windows/Chrome 69, Firefox 62

### Description
I setup two autocompletes so that when a value is selected in one it updates the other.  While this functionality works, it causes some unexpected behavior after selection.

[Example](https://codepen.io/anon/pen/wYegej?editors=1010)

### Steps to reproduce

1. Set up two autocompletes as in the example provided above
2. Select an option from one autocomplete
3. Click the other autocomplete.  This behaves as expected
4. Click the autocomplete where selection was made.  The entire text is selected and does not allow for deletion of single characters.  The entire selection is deleted.

![image](https://i.imgur.com/SmnVDYg.gif)

### Expected behavior
I expect both autocompletes to allow deleting of individual characters.

### Actual behavior
The autocomplete where selection was made does not allow for deleting individual characters.

**Comment by jtommy** [comment]
@jmgilmour Could you provide your example code?

**Comment by jmgilmour** [comment]
The example is linked under the description.

**Comment by jtommy** [comment]
Oh I'm sorry :)
