### ISSUE TITLE
b-taginput error when using nested data property as v-model

### ISSUE THREAD

**Issue by lunfel** [buefy/buefy#1031]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Ubuntu/Chrome Version 69.0.3497.81 (Official Build) (64-bit)

### Description

When you using a nested vue data property for v-model, the taginput crashes. But using root level data property works fine.

`Cannot read property 'indexOf' of null`

### Steps to reproduce
This code does not work
```
<template>
   <b-taginput v-model="form.tags" />
</template>

export default {
  name: 'VueComponent',
  data () {
    return {
      form: {
        tags: []
      }
    }
  }
}
```
1. Put the above code in a Vue Single File component
2. Type a tag
3. Press enter/comma

Note that the following code works fine:

```
<template>
   <b-taginput v-model="tags" />
</template>

export default {
  name: 'VueComponent',
  data () {
    return {
      tags: []
    }
  }
}
```

### Expected behavior

It should transform text to a tag and update the v-model

### Actual behavior

Nothing happens

Error from the log
`Cannot read property 'indexOf' of null`

**Comment by lunfel** [comment]
[https://imgur.com/a/hZlAluv](url)

**Comment by jtommy** [comment]
@lunfel I replicated it https://codepen.io/anon/pen/rqdBoO?&editors=101 but it's all ok

**Comment by lunfel** [comment]
I might have made a typo, because I tried again today and it worked fine.
