### ISSUE TITLE
Taginput with autocomplete and add-new: addtag on blur

### ISSUE THREAD

**Issue by wrabit** [buefy/buefy#1032]
**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: OSX / chrome latest

### Description

When taginput is without autocomplete - tags are added on blur. With autocomplete and add-new - its bottle necking form filling

### Expected behavior

To behave just like the taginput without autocomplete

In the short term - any hack to get around this?

**Comment by williamabbott** [comment]
The confusion, in my eyes, is that if the user arrives at the form with an empty taginput field, it looks and behaves exactly like a standard input and he or she may just tab / click to the next field and assume everything's fine. But, the tag isn't actually added so the data is skipped on submission.

**Comment by jtommy** [comment]
@williamabbott Autocomplete mode has a different behaviour and you should select the current option because it usually a object and not a simple text.

**Comment by WilliamMayo11** [comment]
@williamabbott did you find a workaround? I'm encountering the exact same issue.

**Comment by wrabit** [comment]
@WilliamMayo11 nope, just come up against it again, did you resolve it?

**Comment by wrabit** [comment]
@jtommy 

Is there a reason that a blur event on a Taginput with Autocomplete doesn't trigger addTag()?

Taginput.vue
```
        customOnBlur($event) {
            // Add tag on-blur if not select only
            if (!this.autocomplete) this.addTag()

            this.onBlur($event)
        },
```

It is working fine for me if I:

```
        customOnBlur($event) {
            // Add tag on-blur if not select only
            if (this.autocomplete && this.allowNew) this.addTag()

            this.onBlur($event)
        },
```

After all, later in the Taginput.vue we have:

```
        keydown(event) {
            if (this.removeOnKeys.indexOf(event.keyCode) !== -1 && !this.newTag.length) {
                this.removeLastTag()
            }
            // Stop if is to accept select only
            if (this.autocomplete && !this.allowNew) return <---------

            if (this.confirmKeyCodes.indexOf(event.keyCode) >= 0) {
                event.preventDefault()
                this.addTag() <--------
            }
        },
```

**Comment by wrabit** [comment]
@WilliamMayo11 for now, I have a wrapper around Taginput and do this:

```
<b-taginput
    ref="taginput"
    @blur="onBlur"
    ....
/>

...
methods: {
    onBlur() {
        if(this.allowNew) this.$refs.taginput.addTag()
    }
}
````
