### ISSUE TITLE
Make icons availible to table "columns" prop

### ISSUE THREAD

**Issue by s0nic12** [buefy/buefy#1033]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.16]
**OSX/Firefox**:

### Description

I want more options availible when using the columns prop to define my tables. For example, I would like to define a column to use an icon on the basis of the row data for a given field.

### Expected behavior

columns: [
                    {
                        field: 'favorite',
                        label: 'Fav',
                        width: '40',
                        icon: (props.row.favorite === true ? 'star' : 'star-outline')
                    },
                    ...
                  ]

**Comment by jtommy** [comment]
@s0nic12 `Columns` prop accepts the same props of `bTableColumn` and there is no `icon` prop.
Take a look at "Custom Headers" example https://buefy.github.io/documentation/table.

**Comment by s0nic12** [comment]
To clarify, there is no possability to display icons in the table while using the columns prop?
