### ISSUE TITLE
E2E test framework for Buefy development?

### ISSUE THREAD

**Issue by afifsohaili** [buefy/buefy#1037]
I'm currently working on #1017 and the components are becoming quite complicated with the multiple behaviors to support. I was thinking of rewriting that component from ground up so that it's more extensible in the future, but there aren't any E2E tests to ensure I cover all the previous behaviors. It's also going to pave a way towards the library's stability and will help when we wanna rewrite some components as we go along.

Should we consider adding E2E test right now?
I'm thinking of either Testcafe or Cypress. What's your opinion? @jtommy @rafaelpimpa 

If you guys are okay, I'll put the work on #1017 on hold and start the ground works on E2E tests for the project and that Date component first, and then continue working on #1017 afterwards.

**Comment by jtommy** [comment]
@afifsohaili E2E tests are good thing but at the moment we prefer finish all unit test as you can read in the roadmap.
So if you have time you could finish to update date picker components.
