### ISSUE TITLE
Select v-model only works with one select box

### ISSUE THREAD

**Issue by RTK99** [buefy/buefy#1039]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.1
**OS/Browser**: Chrome

### Description
If you use v-model on more than one select box on the page, it will only show the binding value for one of the select boxes. Essentially, Two way binding only works for one select box a page.

### Steps to reproduce
1. Create Two select boxes with v-model of variables containing "test1" and "test2".

### Expected behavior
"test1" and "test2" should show on both select boxes.

### Actual behavior
Either "test1" or "test2" will show. the latter select box will be blank.
![image](https://user-images.githubusercontent.com/15255678/47191976-349a3f80-d318-11e8-8221-f4d79aa1ea22.png)
(In the picture, the first v-model is blank, the second one works.)

**Comment by HZooly** [comment]
Hello, I'm unable to reproduce this issue.

What I tried : https://codesandbox.io/s/w2p6yqj10w

```html
    <section>
        <b-field>
            <b-select v-model="test1">
                <option value="flint">Flint</option>
                <option value="silver">Silver</option>
                <option value="vane">Vane</option>
            </b-select>
        </b-field>
        <b-field>
            <b-select v-model="test2">
                <option value="flint">Flint</option>
                <option value="silver">Silver</option>
                <option value="vane">Vane</option>
            </b-select>
        </b-field>
    </section>
```

My component data : 

```js
data: () => {
  return {
    test1: '',
    test2: ''
  }
}
```

You say you are using Buefy version **0.7.1**, are you sure about that ? Current Buefy version is **0.7.0**, 0.7.1 is the **Bulma** one.

**Comment by RTK99** [comment]
Oh, my bad. Buefy 0.7.0.
And test1 and test2 have a default value. I'm getting the defaults from a
database.

**Comment by HZooly** [comment]
No problem!

Even with default values on both model, I can't reproduce your issue.

Could you reproduce it in Sandbox or elsewhere?

**Comment by RTK99** [comment]
Been trying for hours on csb to reproduce this issue. No luck whatsoever.
I'm going to try and recreate my steps in my app code, will let you know.
