### ISSUE TITLE
Squashed radios on standard css

### ISSUE THREAD

**Issue by williamabbott** [buefy/buefy#1040]
Latest Buefy + Bulma, Latest Chrome & OSX

![image](https://user-images.githubusercontent.com/5918271/47222398-eb4cfd00-d3b6-11e8-9aee-1bc6723be622.png)

**Comment by williamabbott** [comment]
Fixed with:

`.b-radio { flex-shrink: 0 }`

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/commit/4e67557bbb94372df75ccc42380c6ea467037741
