### ISSUE TITLE
Validation does not work for datepicker (and others)

### ISSUE THREAD

**Issue by danielclariondoor** [buefy/buefy#1041]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.7]
**OS/Browser**: OS X HighSierra / Chrome

### Description

Inputs validation works, but datepicker does not. A simple attribute like "required" is ignored.

### Steps to reproduce

1. Create a buefy datepicker component with attribute required="required"
2. Place cursor in input but do not type. Then click somewhere else.

### Expected behavior

Error message appears, telling me to fill in the input.

### Actual behavior

No error message.

**Comment by jtommy** [comment]
@danielclariondoor Because the component is readonly as default, you might add `editable` prop (but the input will be editable) or validate it with external lib o a custom submit function.
