### ISSUE TITLE
BIcon error webpack

### ISSUE THREAD

**Issue by shak18** [buefy/buefy#1042]
### Overview of the problem

**Buefy** version: [0.6.7] and [0.7.0]
**Vuejs** version: [2.5.13] and [2.5..17]
**OS/Browser**: chrome, firefox

### Description

Im not able to use BIcon or any component that uses b-icon because it raise the follow messege

[Vue warn]: data functions should return an object:
https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function

found in

---> <BIcon>
       <App> at src/assets/components/App.vue
         <Root>
warn @ vue.esm.js:578
initData @ vue.esm.js:3349
initState @ vue.esm.js:3284
Vue._init @ vue.esm.js:4558
VueComponent @ vue.esm.js:4728
createComponentInstanceForVnode @ vue.esm.js:4242
init @ vue.esm.js:4059
createComponent @ vue.esm.js:5512
createElm @ vue.esm.js:5460
createChildren @ vue.esm.js:5586
createElm @ vue.esm.js:5488
patch @ vue.esm.js:5995
Vue._update @ vue.esm.js:2637
updateComponent @ vue.esm.js:2765
get @ vue.esm.js:3115
Watcher @ vue.esm.js:3104
mountComponent @ vue.esm.js:2772
49.Vue$3.$mount @ vue.esm.js:8429
49.Vue$3.$mount @ vue.esm.js:10790
init @ vue.esm.js:4065
createComponent @ vue.esm.js:5512
createElm @ vue.esm.js:5460
patch @ vue.esm.js:6034
Vue._update @ vue.esm.js:2637
updateComponent @ vue.esm.js:2765
get @ vue.esm.js:3115
Watcher @ vue.esm.js:3104
mountComponent @ vue.esm.js:2772
49.Vue$3.$mount @ vue.esm.js:8429
49.Vue$3.$mount @ vue.esm.js:10790
Vue._init @ vue.esm.js:4570
Vue$3 @ vue.esm.js:4659
(anonymous) @ main.js:28
_typeof2 @ app.js:9578
__webpack_require__ @ bootstrap 20824b6998489de1abee:54
(anonymous) @ app.js:4361
__webpack_require__ @ bootstrap 20824b6998489de1abee:54
webpackJsonpCallback @ bootstrap 20824b6998489de1abee:25
(anonymous) @ app.js:1
vue.esm.js:3427 Uncaught TypeError: Cannot use 'in' operator to search for 'newIcon' in undefined
    at initComputed (vue.esm.js:3427)
    at initState (vue.esm.js:3288)
    at VueComponent.Vue._init (vue.esm.js:4558)
    at new VueComponent (vue.esm.js:4728)
    at createComponentInstanceForVnode (vue.esm.js:4242)
    at init (vue.esm.js:4059)
    at createComponent (vue.esm.js:5512)
    at createElm (vue.esm.js:5460)
    at createChildren (vue.esm.js:5586)
    at createElm (vue.esm.js:5488)
initComputed @ vue.esm.js:3427
initState @ vue.esm.js:3288
Vue._init @ vue.esm.js:4558
VueComponent @ vue.esm.js:4728
createComponentInstanceForVnode @ vue.esm.js:4242
init @ vue.esm.js:4059
createComponent @ vue.esm.js:5512
createElm @ vue.esm.js:5460
createChildren @ vue.esm.js:5586
createElm @ vue.esm.js:5488
patch @ vue.esm.js:5995
Vue._update @ vue.esm.js:2637
updateComponent @ vue.esm.js:2765
get @ vue.esm.js:3115
Watcher @ vue.esm.js:3104
mountComponent @ vue.esm.js:2772
49.Vue$3.$mount @ vue.esm.js:8429
49.Vue$3.$mount @ vue.esm.js:10790
init @ vue.esm.js:4065
createComponent @ vue.esm.js:5512
createElm @ vue.esm.js:5460
patch @ vue.esm.js:6034
Vue._update @ vue.esm.js:2637
updateComponent @ vue.esm.js:2765
get @ vue.esm.js:3115
Watcher @ vue.esm.js:3104
mountComponent @ vue.esm.js:2772
49.Vue$3.$mount @ vue.esm.js:8429
49.Vue$3.$mount @ vue.esm.js:10790
Vue._init @ vue.esm.js:4570
Vue$3 @ vue.esm.js:4659
(anonymous) @ main.js:28
_typeof2 @ app.js:9578
__webpack_require__ @ bootstrap 20824b6998489de1abee:54
(anonymous) @ app.js:4361
__webpack_require__ @ bootstrap 20824b6998489de1abee:54
webpackJsonpCallback @ bootstrap 20824b6998489de1abee:25
(anonymous) @ app.js:1

all other components seem to be fine, its my first app with buefy  i  really dont know what im doing wrong this is my main js

/*  3rd Party Assets */
import Vue from 'vue'
import axios from 'axios'
import Buefy from 'buefy'

/* App Assets */
import App from './assets/components/App.vue'
import Routes from './assets/js/routes'
import Store from './assets/js/store'
import './assets/styles/main.scss'
import '@mdi/font/css/materialdesignicons.min.css'
/* Globals */
window.Vue = Vue;
window.axios = axios;

Vue.mixin({
    data: function() { }
});

Vue.use(Buefy, {
    defaultDayNames: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
    defaultMonthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Augosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    defaultDialogCancelText: 'Cancelar',
    defaultIconPack: 'fa'
});

window.vueApp = new Vue({
    el:'#app',
    delimiters: ['${', '}$'], 
    components: { App },
    render: h => h(App),
    data: {
        //bus: new Vue(),
    },
    router: Routes,
    //store: Store //Habilitar si tu proyecto requeire utilizar el store
});

**Comment by jtommy** [comment]
@shak18 It's a Buefy issue. Please read the link in the warning message to fix it

**Comment by jtommy** [comment]
Please paste your App.vue file

**Comment by shak18** [comment]
Here it is

<template>
    <div class = "">
        <top></top>
        <router-view />
        <bottom></bottom><b-icon icon="account"></b-icon>
    </div>
</template>

<script>
//Top y bottom son componentes vue ejemplificatorios para una cabecera y pie de pagina 
import Top from './Top.vue'
import Bottom from './Bottom.vue'
import appData from '../app-data.json'


export default {
    name: 'app',
    components: {  
        'top': Top, 
        'bottom': Bottom 
    },
    data () {
        return {
            loading: true,
            appData: appData,

        }
    },
    mounted() {
        
    },
    methods: {
        
    }
}
</script>

**Comment by shak18** [comment]
Here it is
 ````
<template>
    <div class = "">
        <top></top>
        <router-view />
        <bottom></bottom><b-icon icon="account"></b-icon>
    </div>
</template>

<script>
//Top y bottom son componentes vue ejemplificatorios para una cabecera y pie de pagina 
import Top from './Top.vue'
import Bottom from './Bottom.vue'
import appData from '../app-data.json'


export default {
    name: 'app',
    components: {  
        'top': Top, 
        'bottom': Bottom 
    },
    data () {
        return {
            loading: true,
            appData: appData,

        }
    },
    mounted() {
        
    },
    methods: {
        
    }
}
</script>

**Comment by shak18** [comment]
> Please paste your App.vue file

Here it is
 ````
<template>
    <div class = "">
        <top></top>
        <router-view />
        <bottom></bottom><b-icon icon="account"></b-icon>
    </div>
</template>

<script>
//Top y bottom son componentes vue ejemplificatorios para una cabecera y pie de pagina 
import Top from './Top.vue'
import Bottom from './Bottom.vue'
import appData from '../app-data.json'


export default {
    name: 'app',
    components: {  
        'top': Top, 
        'bottom': Bottom 
    },
    data () {
        return {
            loading: true,
            appData: appData,

        }
    },
    mounted() {
        
    },
    methods: {
        
    }
}
</script>

**Comment by shak18** [comment]
Nevermind the error esa un muy nose the whole tome and un the first post, i leave uncommented the  global mixin and leave a data función empty

**Comment by jtommy** [comment]
@shak18 can you share your project ?
