### ISSUE TITLE
Select with image on <option> line

### ISSUE THREAD

**Issue by titoff002** [buefy/buefy#1046]
Hello,

Is it possible in the `<option> `area of ​​a `SELECT `list to add an image (they are not images marterial design nor others: they are images a custom icons/images)?

If so, how do I get visible images in the SELECT list lines?

Thank you.

**Comment by titoff002** [comment]
**I would like to do something like this :**
```

<b-select @input="updModels()" id="field" name="field" v-model="field" expanded placeholder="Sélectionner ...">
                    <option v-for="option in this.list" :key="option.field1" :value="option.field2">
                     <span><img src="/static/img/logo.jpg" /> {{ option.field2 }}</span>
                    </option>
</b-select>
```

**Comment by jtommy** [comment]
No but you could use bDropdown or bAutocomplete with open-on-focus prop
