### ISSUE TITLE
Table Headers Still Disappear with Pagination or updating table

### ISSUE THREAD

**Issue by jonathanmzf** [buefy/buefy#1048]
### Overview of the problem

**Buefy** version: [0.7.0]
**Vuejs** version: [2.5.17]
**OS/Browser**: Windows / Chrome

### Description

The table loses it's headers when you reload it, for example when change the page of a paginated table.

### Steps to reproduce

This is similar to issue [992](https://github.com/buefy/buefy/issues/992).
However it occurs using a slot-scope with the <b-table-column> elements and customize headers as shown in this [codepen](https://codepen.io/jonathan_mf/pen/OBweKw?editors=1010)

### Expected behavior

The headers to not disappear when updating the table.

### Actual behavior

The headers disappear

**Comment by jtommy** [comment]
@jonathanmzf Why are using `columns` props and default slot ? 
Anyway we'll investigate about it.

**Comment by jonathanmzf** [comment]
> @jonathanmzf Why are using `columns` props and default slot ?
> Anyway we'll investigate about it.

@jtommy the goal is a table with both: custom headers and custom row template

**Comment by jtommy** [comment]
Yes but you could use only default template and bTableColumn with label, ... .

**Comment by jonathanmzf** [comment]
> Yes but you could use only default template and `bTableColumn` with `label`, etc props .

But it is not possible to have a customized header using only default template and bTableColumn with label, etc props, Isn't it?

If it is possible, do you have an example? I'd appreciate it.

In the codepen, I just put an icon with a label in the headers, but in fact i need to put a b-select inside the headers.

**Comment by jtommy** [comment]
https://codepen.io/anon/pen/MPqrGK?editors=1010

**Comment by jonathanmzf** [comment]
> https://codepen.io/anon/pen/MPqrGK?editors=1010

Great, this is what i needed. Thanks and btw thanks for the great job with buefy.

**Comment by kraucy** [comment]
This is still happening in 0.7.2

**Comment by aleks989** [comment]
for my case this solved the problem

don't do this:
> <b-table-column
>     label="Kooperant"
>     v-text="props.row.client.name">
> </b-table-column>

do this
> <b-table-column
>     label="Kooperant">
>     {{ props.row.client.name }}
> </b-table-column>
