### ISSUE TITLE
Group Folders and Files separately in b-table-column

### ISSUE THREAD

**Issue by AishwaryaMaheshwari** [buefy/buefy#1050]
## Overview of the problem

**Buefy** version: "0.5.3"
**Vuejs** version: "2.4.4"
**OS/Browser**: Windows-7 / Google Chrome

### Description

I have a b-table component on my webpage which contains items of type files and folders. I want these files and folders to be grouped separately as it works for windows or dropbox.

![image](https://user-images.githubusercontent.com/41947924/47414510-c4177680-d78e-11e8-9ea0-3ce2c7c24a9c.png)

**Comment by jtommy** [comment]
@AishwaryaMaheshwari What do you mean? You might add a custom sort

**Comment by AishwaryaMaheshwari** [comment]
I tried adding custom sort. but it is not reading 'isAsc' value.

**Comment by jtommy** [comment]
@AishwaryaMaheshwari `custom-sort` is a function prop to sort a column and you might check last boolean parameter
