### ISSUE TITLE
Failure "File is not defined" after upgrading to Buefy 0.7.0

### ISSUE THREAD

**Issue by shawnlauzon** [buefy/buefy#1052]
### Overview of the problem

**Buefy** version: 0.7.0
**Vuejs** version: 2.5.17
**OS/Browser**: Mac OS / Chrome

### Description

After upgrading to 0.7.0, my app fails to launch with the failure "File is not defined" in the `buefy.js` file. I've seen the breaking changes in the readme, and I don't see anything which I need to change

### Steps to reproduce

1. Change `package.json` to 
2. Run `npm install`
3. Launch with `npm run dev`
4. See failure

### Expected behavior

Successful launch of application.

### Actual behavior

![image](https://user-images.githubusercontent.com/611529/47439080-bc010c00-d779-11e8-959e-c40616b8d36f.png)

**Comment by jtommy** [comment]
Are you using nuxt? The fix will be available in the next release but please take a look https://github.com/buefy/nuxt-buefy/issues/32

**Comment by shawnlauzon** [comment]
Yes, I am using Nuxt. Thanks for that pointer, it looks exactly like my problem. Nice catch!
