### ISSUE TITLE
Feature request: Add support for panel tabs

### ISSUE THREAD

**Issue by blowsie** [buefy/buefy#1053]
Add support for panel tabs as found here;
https://bulma.io/documentation/components/panel/

Ive tried the following with undesired results
```
 <nav class="panel">
        <p class="panel-heading">
          repositories
        </p>
        <div class="panel-block">
          <p class="control has-icons-left">
            <input 
              class="input is-small" 
              type="text" 
              placeholder="search">
            <span class="icon is-small is-left">
              <i 
                class="fas fa-search" 
                aria-hidden="true"/>
            </span>
          </p>
        </div>
        <b-tabs
          position="is-centered"
          class="panel-tabs">
          <b-tab-item label="Form"><pre>{{ form }}</pre></b-tab-item>
          <b-tab-item label="Errors"><pre>{{ errors }}</pre></b-tab-item>
          <b-tab-item label="Field"><pre>{{ fields }}</pre></b-tab-item>
        </b-tabs>
        .....
</nav>
```

Result
> ![image](https://user-images.githubusercontent.com/308572/47442729-bec82500-d7aa-11e8-9278-17cdfbdb2a8b.png)

**Comment by jtommy** [comment]
@blowsie We removed panel component in the last version because it's only a CSS and HTML code

**Comment by blowsie** [comment]
@jtommy yes but tabs in buefy are not compatible with bulma panels, as per the bulma docs see screenshot

**Comment by jtommy** [comment]
@blowsie yes but `panel-tabs` aren't buefy tabs. BTabs component is the equivalent of Bulma Tabs.

**Comment by blowsie** [comment]
@jtommy indeed, thats why this is a feature request to support panel tabs

**Comment by blowsie** [comment]
@jtommy Thank you kindly
