### ISSUE TITLE
Add to docs a VeeValidate example for required b-checkbox

### ISSUE THREAD

**Issue by mkstix6** [buefy/buefy#1054]
[This docs page](https://buefy.github.io/extensions/veevalidate/) shows how to use VeeValidate with Buefy `b-input`.

Could an example be added showing how to validate a checkbox that I need to be required — i.e. checkbox must be checked.

## Setup
From yarn.lock:
nuxt-buefy@^0.3:
  version "0.3.1"
  dependencies:
    buefy "0.7.0"

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/f933ca2c0b450534639e5714ca2645932a948f8f

**Comment by mkstix6** [comment]
Thank you.
