### ISSUE TITLE
Add type class to autocomplete input

### ISSUE THREAD

**Issue by Livijn** [buefy/buefy#1055]
Please add support for switching type (e.g. is-light, is-dark) of the autocomplete input. Right now I have to do this ugly way:

        mounted() {
            let autocomplete = this.$refs.autocomplete;
            console.log(autocomplete);
            autocomplete.$refs.input.$refs.input.classList.add('is-light');
        },

**Comment by jtommy** [comment]
@Livijn Are you wrapping it into a `bField` ? You might use `type` prop in `bField` ('is-light', 'is-dark').

**Comment by Livijn** [comment]
Oh, did not realize that would work. Thanks!
