### ISSUE TITLE
Buefy Datatable shows columns for each rows when hasMobileCards is set to true. This is happening for only iOS (iphone 8,X/iPad Air 2).

### ISSUE THREAD

**Issue by dipuarun** [buefy/buefy#1058]
### Overview of the problem

For iOS (iphone 8,X/iPad Air 2), when I am using hasMobileCards to true, Buefy Datatable shows columns for each rows, without the device specific card view.

**Buefy** version: 0.7.0
**Vuejs** version: 2.5.15
**OS/Browser**: iOS - Safari & Chrome (Mobile/Tablet)

### Description

There is no issues with the browsers in Android or Desktop. Only the issue is appearing for iOS Mobile/Tablets.

When I use, chrome developers tool & Toggle device to iPhone/iPad, I couldn't see any issue. However the issue is appeared when the exact device is used (I am using browserstack to test).

I tried to add the meta tag in header, that didn't help.
meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"

### Expected behavior

Card view should be appear as appearing in Android.

### Actual behavior

Card view doesn't appear with duplicate column headings for each row.

![buefyissue](https://user-images.githubusercontent.com/12948685/47652790-e48b6a80-dbac-11e8-85c6-abcb15f0cdf1.png)

**Comment by adrlen** [comment]
I didn't have your issue with iPhone 8/X on buefy website, can you reproduce it outside of Browserstack ?

**Comment by dipuarun** [comment]
Yeah, I couldn't see any issue with buefy website as well when using Browserstack - with iPhone 8/X.

This is probably something to do with some CSS conflict in our site. I will re-check & confirm.

Thanks Adrlen.
