### ISSUE TITLE
Add openOnFocus property to tag input component

### ISSUE THREAD

**Issue by jamesburrow23** [buefy/buefy#1059]
### Overview of the problem

**Buefy** version: [0.6.7]

### Description

When using the tag input component with autocomplete enabled there is no option to specify that the dropdown list of available tags should appear when the input is focused.  That's because the openOnFocus property is missing from the tag input component

**Comment by jtommy** [comment]
@jamesburrow23 Did you try? When is autocomplete all props are binded to it
