### ISSUE TITLE
Autocomplete: Header slot not in documentation

### ISSUE THREAD

**Issue by hpolthof** [buefy/buefy#1061]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 0.7.1
**OS/Browser**: irrelevant

### Description

In the documentation at https://buefy.github.io/#/documentation/autocomplete the slot ```header``` is not documented. Probably forgotten.

**Comment by jtommy** [comment]
@hpolthof You're right! Anyway the correct link is without #, https://buefy.github.io/documentation/autocomplete
