### ISSUE TITLE
it is possible to change the colors programmatically

### ISSUE THREAD

**Issue by Akhail** [buefy/buefy#1062]
### Overview of the problem
I love buefy, but have a question is possible customize buefy programmatically?
 
### Description
I want to be able to change colors and customize buefy from js

### Expected behavior
Customize buefy with js

### Actual behavior
i can't change color with js

**Comment by jtommy** [comment]
@Akhail No, you can't because all variables are in SASS/SCSS files.

**Comment by kostia7alania** [comment]
is it still unposible ?
