### ISSUE TITLE
How to change the color of the "Cancel" button of Confirm dialog box?

### ISSUE THREAD

**Issue by singhankit4652** [buefy/buefy#1063]
### Overview of the problem

**Buefy** version: [0.5.4]
**Vuejs** version: [2.3.0]
**OS/Browser**:

### Description
https://buefy.github.io/documentation/dialog
I can see there is a property _type_ to change the color of the confirm button. But what is the way to change the color of the cancel button?

Thank you!

**Comment by jtommy** [comment]
@singhankit4652 it's no possible at the moment
