### ISSUE TITLE
opacity:0 of tooltip makes its children invisible

### ISSUE THREAD

**Issue by fmmajd** [buefy/buefy#1066]
**Buefy** version: [0.70]
**Vuejs** version: [2.5.17]
**OS/Browser**:Ubuntu/Chrome

it seems that when putting stuff in b-tooltip component, they become invisible due to opacity:0 of tooltip class. any attempt to change the opacity of any inner element will result in the tooltip text becoming visible. 
To be specific, I am using b-icon in the b-tooltip component, but even a simple text had the same problem.

Steps to recreate:
1. create a component and import needed components from Buefy
2. add: 
```js
<b-tooltip label="Tooltip right"
                               position="is-right">
                        <button class="button is-dark">
                            Right
                        </button>
                    </b-tooltip>
```
it is the exact ly the same as one of the examples in the documentation.

**Comment by Loruz** [comment]
@fmmajd but in this example everything works fine. https://codepen.io/anon/pen/ErozXW. I added components inside tooltip. Event nested ones. It works fine.
