### ISSUE TITLE
Arrowless Dropdown is being overridden by Buefy

### ISSUE THREAD

**Issue by CoreyT355** [buefy/buefy#1070]
### Overview of the problem

**Buefy** version: [0.7.0]
**Vuejs** version: [2.5.17]
**OS/Browser**: MacOS Mojave, Chrome 70.0.3538.77

### Description

When using the Navbar styles provided by Bulma in a component with Buefy, the `is-arrowless` class is not preserved from Bulma. This removes the ability to have a dropdown without an arrow. 

I have created 3 CodePens to illustrate this.
Working as expected: [Working with Bulma](https://codepen.io/CoreyT355/pen/jQbVNK)
Not working with Buefy itself: [Not working with Buefy](https://codepen.io/CoreyT355/pen/xQwRXZ)
Not working with Buefy and Bulma together: [Not working with both](https://codepen.io/CoreyT355/pen/yQYVpW)

### Steps to reproduce

1 - Create a test component importing the 0.7.0 version of Buefy
2 - Copy the navbar HTML from the example on the Bulma site, https://bulma.io/documentation/components/navbar/#basic-navbar
3 - On the "More" menu option add the `is-arrowless` class
4 - The arrow will still be preset on the dropdown. If you repeat these steps using the Bulma css itself, the arrow will go away.

### Expected behavior

The expected behavior is that when `is-arrowless` is added to the correct element in a navbar, the Bulma CSS is not overridden and the arrow goes away.

### Actual behavior

The arrow is still visible on the dropdown in the navbar.

**Comment by kaidjohnson** [comment]
Looks like `is-arrowless` was introduced in bulma 0.7.2 (https://github.com/jgthms/bulma/blob/master/CHANGELOG.md), but the master branch of buefy is using 0.7.1. I would assume this issue will get resolved once buefy gets a new cut since the dev buefy branch defines the bulma dependency at 0.7.2.

@rafaelpimpa, Any thoughts on when that might be happening?

**Comment by jtommy** [comment]
@kaidjohnson We should to release a new version very soon.
