### ISSUE TITLE
Feature Request: Add a clear button to Autocomplete

### ISSUE THREAD

**Issue by Livijn** [buefy/buefy#1071]
I would like for you to add a clear-button to the Autocomplete component. You could use the `type="search"`, that would be fine with me.

**Comment by duffte** [comment]
i am using @focus="name = '' ", but it will also delete your prior selection, which is a bummer in my case.

**Comment by dmitry-gerasimov** [comment]
Yes, having an active clear icon on the right when one of the options is selected would be great.

**Comment by service-paradis** [comment]
Why not use a button addons. Something like this:
https://codepen.io/anon/pen/MNJxBy?&editable=true&editors=101

**Comment by service-paradis** [comment]
Similar request: https://github.com/buefy/buefy/issues/676
