### ISSUE TITLE
Fresh install with Nuxt having issues compiling.

### ISSUE THREAD

**Issue by byrnecode** [buefy/buefy#1074]
### I'm getting compiling error when using Buefy with Nuxt (create-nuxt-app), fresh install.

**Buefy** version: 0.7.0
**Nuxtjs** version: 2.0.0
**OS/Browser**: All browser, Windows

### Description

Please see screenshot below, this is what I get after running **npm run dev**
![image](https://user-images.githubusercontent.com/14091662/48215558-81d66380-e350-11e8-9d62-840f10143157.png)

### Steps to reproduce

Fresh install of Nuxt 2.0.0 (followed all installation steps on docs)
Fresh install of Buefy 0.7.0 (followed all installation steps on docs)
npm run dev

**Comment by jtommy** [comment]
https://github.com/buefy/nuxt-buefy/issues/32

**Comment by byrnecode** [comment]
Thank you! =D
