### ISSUE TITLE
Pagination: Simple style does not yet utilise the Order option

### ISSUE THREAD

**Issue by mkstix6** [buefy/buefy#1078]
I would like to use the simple pagination style but move the prev/next buttons over to the right hand  side of the page.

I have tried using the **Order** option but this has no effect I can see on the **Simple** pagination style.

This can be replicated in the [pagination docs](https://buefy.github.io/documentation/pagination/).

**Comment by jtommy** [comment]
@mkstix6 Simple pagination is not a Bulma style and so it doesn't follow `is-centered` and `is-right` class.
What do you think about it https://codepen.io/anon/pen/MzmWMQ ?

**Comment by jtommy** [comment]
@mkstix6 Is it ok ? We should add that implementation in the next release

**Comment by mkstix6** [comment]
Ye that looks good. Thanks.

I ended up adding to my global CSS:

```
.pagination.is-simple .info {
    margin-right: auto;
}
```

Which pushed the buttons over and gave me the split layout, as per our design. "1/20" on the left, Previous & Next buttons on the right.
