### ISSUE TITLE
Tag Input component does not allow specificity of icon pack

### ISSUE THREAD

**Issue by shanejykerr** [buefy/buefy#1079]
### Overview of the problem

**Buefy** version: [0.7.0]
**Vuejs** version: [2.5.17]
**OS/Browser**: MacOS v10.13.6/Chrome v70.0.3538.77

### Description

I attempted to insert a label icon into the input for a tag input component. However, when the component is rendered, the icon does not display even though space is still being used. I've had this problem with datepicker and timepicker, which was solved by changing the icon collection from "mdi" to "fa". Instead of pulling icons from Material Design Icons, I would like utilize Font Awesome icons. However, unlike the datepicker and timepicker components, tag input does not have this option.

### Steps to reproduce

1. Add b-taginput component to the template.
2. Alter component to `b-taginput icon="label"`.

### Expected behavior

When `icon="label"` is added to "b-taginput", the icon is properly displayed on component render. 

### Actual behavior

All that is displayed for the icon when the tag input is rendered is an empty space, with any placeholder seemingly indented as though the icon is being added.

<img width="432" alt="screen shot 2018-11-12 at 4 27 24 pm" src="https://user-images.githubusercontent.com/39527122/48376961-7b225600-e69a-11e8-8f1e-f4f9d0fefecf.png">

**Comment by jtommy** [comment]
@shanejykerr Are you sure that "label" icon name is correct ?
Anyway you can use `icon` and `icon-pack` props as you want, for example:
`<b-taginput icon-pack="fa" icon="tag" `
