### ISSUE TITLE
Documentation is not up-to-date

### ISSUE THREAD

**Issue by guillaume-g** [buefy/buefy#1081]
### Overview of the problem

**Buefy** version: [^0.7.0]
**Vuejs** version: [^2.5.11]
**OS/Browser**: Chrome latest

### Description

https://buefy.github.io/#/documentation/start

In the start documentation, it is not accurate.
The path in the documentation to include css (both in yarn and CDN) is ***/lib/buefy.min.css*** but looks like it's now ***/dist/buefy.min.css***

**Comment by jtommy** [comment]
@guillaume-g This is the correct link https://buefy.github.io/documentation/start/.
Clean your cache if you can't see the new docs.
