### ISSUE TITLE
<b-select> shows placeholder instead of <option :value="null">

### ISSUE THREAD

**Issue by mk-relax** [buefy/buefy#1084]
### Overview of the problem

**Buefy** version: 0.7.0
**Vue** version: 2.5.3
**OS/Browser**: Windows 10 / 70.0.3538.77 (Official Build) (64-bit)

### b-select: Placeholder shown instead of option :value="null". 

When an option with `:value="null"` is selected, the `<b-select>` shows the placeholder instead of the selected option. This does work properly for plain `<select>` elements.

### Steps to reproduce

See: https://jsfiddle.net/Lyegqxja/46/

### Expected behavior

If the bound value is NULL and NULL is a valid option value, then that option should be selected. `<b-select>` should be compatible with the plain `<select>` element in this respect.

### Actual behavior

The placeholder is shown instead. Also, the 'null' option needs to be clicked twice to become selected.

**Comment by mk-relax** [comment]
Better, but still not solved. On initial load, the component still shows 'placeholder' instead of the null option, so it still incorrectly represents the state of the data. Again, see the jsfiddle (above).

**Comment by jtommy** [comment]
@mk-relax In your example if you want select the first option, `selected` data should be `'null'` and not `null`

**Comment by mk-relax** [comment]
Indeed there was an error in my jsfiddle, it said `:value="'null'"` instead of `:value="null"`. I fixed it, but unfortunately the bug still seems to be there in Buefy v0.8.12. Please reopen.

https://jsfiddle.net/MHfdle93ds/8buL6q5s/9/

**Comment by patrickschroeter** [comment]
Any news? We are having the same issue in our project.

**Comment by kerrpeter** [comment]
Still an issue
