### ISSUE TITLE
Audio element using vue-audio-visual controls don't display.

### ISSUE THREAD

**Issue by CromonMS** [buefy/buefy#1088]
### Overview of the problem

**Buefy** version: 0.7.0
**Vuejs** version: 2.5.7
**OS/Browser**: Win 10 Vivaldi: 2.1.1337.47 / Chrome: 70.0.3538.102

### Description

Using https://github.com/staskobzar/vue-audio-visual for displaying and playing audio, however there is a clash with your / bulma's audio tags css height: auto; it ends up hiding the controls on the audio element.

Removing audio / video from the following (buefy.css:353/354) fixes the problem:

img {
  height: auto;
  max-width: 100%; }

### Expected behaviour

Audio controls render normally.

### Actual behaviour

Audio controls are hidden.

**Comment by jtommy** [comment]
It's Bulma css reset as you can see https://github.com/jgthms/bulma/blob/1083f017a06b44d6f1e315de2b384798e69aeb35/sass/base/minireset.sass
