### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by algha** [buefy/buefy#1093]
Hello Guys.
Icon is not showing.
here is my code
`import Buefy from 'buefy'
import 'buefy/dist/buefy.css'
import 'font-awesome/css/font-awesome.min.css'
Vue.use(Buefy)`

and 
`  <b-icon
                     pack="fas"
                     icon="globe"
                     size="is-medium">
                </b-icon>`

and rendered code is 
`<span class="icon is-medium"><i class="fas fa-globe fa-2x"></i></span>`

i have updated 7.0 version of buefy.

what should i do?

**Comment by jtommy** [comment]
@algha You imported FontAwesome 4.7.0 and so the icon pack is "fa"
