### ISSUE TITLE
Taginput: Add way to clear input

### ISSUE THREAD

**Issue by philipithomas** [buefy/buefy#1096]
### Overview of the problem

I request the ability to clear the query in a taginput component!

### Description

I'm working on some autocomplete logic that leverages Taginput. Right now, if the user has entered a query, I cannot seem to remove it. I would like to do it so that I can reset our form. 

### Steps to reproduce

1. User types query into Taginput without making a selection
2. I would like a way to delete the query from outside of the component

**Comment by adrlen** [comment]
Hey @philipithomas, you can clear TagInput with a ref.

Example : https://codepen.io/adrlen/pen/GwOjVK?editors=1010

**Comment by philipithomas** [comment]
Thanks so much @adrlen  - that resolves it! I had no idea that this was possible with refs.
