### ISSUE TITLE
Group headers in table

### ISSUE THREAD

**Issue by Diaskhan** [buefy/buefy#1099]
Its possble to make header grouping in Table ?
Col and colgroup  tags?

https://www.w3.org/WAI/tutorials/tables/irregular/

![image](https://user-images.githubusercontent.com/15046677/48821409-62452f00-ed83-11e8-9660-3516a2819d00.png)

`<table>
  <col>
  <colgroup span="2"></colgroup>
  <colgroup span="2"></colgroup>
  <tr>
    <td rowspan="2"></td>
    <th colspan="2" scope="colgroup">Mars</th>
    <th colspan="2" scope="colgroup">Venus</th>
  </tr>
  <tr>
    <th scope="col">Produced</th>
    <th scope="col">Sold</th>
    <th scope="col">Produced</th>
    <th scope="col">Sold</th>
  </tr>
  <tr>
    <th scope="row">Teddy Bears</th>
    <td>50,000</td>
    <td>30,000</td>
    <td>100,000</td>
    <td>80,000</td>
  </tr>
  <tr>
    <th scope="row">Board Games</th>
    <td>10,000</td>
    <td>5,000</td>
    <td>12,000</td>
    <td>9,000</td>
  </tr>
</table>`

**Comment by jtommy** [comment]
@Diaskhan No, you can't make a header group
