### ISSUE TITLE
Autocomplete Taginput with Allow New - Can't add similar items

### ISSUE THREAD

**Issue by williamabbott** [buefy/buefy#1100]
**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: osx chrome latest

Reproduce:

1. Buefy TagInput docs, Autocomplete example (https://buefy.github.io/documentation/taginput/)
2. Set "Allow new"
3. Try and add a new tag "Jess", "Clare", "Ron" etc.

Suggestion:

Much how the Autocomplete / Header example uses a slot to create an 'add new' action (https://buefy.github.io/documentation/autocomplete)

**Comment by jtommy** [comment]
@williamabbott You're rigth!
 I'm adding header slot and the internal `keep-first` prop (now always 'true') will be enabled when `allow-new` is `false` and vice versa.

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/a335392910683ab10b27f05e40e1ffbe2f7e7adc

**Comment by williamabbott** [comment]
@jtommy thanks for quick fix. It would be cleaner to have something more natively included when allow new is turned on, to always prefix the list with an option to add the new item. Check out the vue-multiselect plugin demo here to see what I mean and start typing a new tag: https://vue-multiselect.js.org/#sub-tagging

I realise it will take more than a quick fix but this would be ideal IMO
