### ISSUE TITLE
BTable select event with action buttons

### ISSUE THREAD

**Issue by williamabbott** [buefy/buefy#1103]
Latest Buefy, OSX, Chrome

I am using the select event to navigate to a record. I also have an action button in the row. When clicking the action button, both, the rowClick and delete is called

**b-table**
```
      <b-table
        @select="rowClick">
            <b-table-column custom-key="actions" class="has-text-right">
                <button @click="delete(props.row.id, props.index)">Delete</button>
            </b-table-column>      
      </b-table>
```

**methods**
```
    /**
     * table row selected event
     */
    rowClick(item,event) {
      this.$router.push({ path: '/processes/' + item.id })
    },
    /**
     * delete action
     */
    delete(id, index) {
    }
```

What happens - both are called

What I expect - rowClick not to be called when clicking in a button

**Comment by jtommy** [comment]
@williamabbott Did you try `stop` modifier to button click event ?
For example: `<button @click.stop="delete(props.row.id, props.index)">Delete</button>`
