### ISSUE TITLE
BTable feature - sorting by numeric string

### ISSUE THREAD

**Issue by williamabbott** [buefy/buefy#1104]
Latest on Chrome / OSX

It's probably quite normal people are dealing with numbers straight from a JSON API source. Is there a quick workaround to specify the column is a numeric string?

function isNumeric(num){
  return !isNaN(num)
}
val = isNumeric(field) ? parseInt(field) : null;

I am sorting on an ID, numbers 1, 2, 10. The sort result is giving me:

1
10
2

```
      <b-table
        default-sort-direction="asc"
        default-sort="pid"
        hoverable>

        <template slot-scope="props">
            <b-table-column field="pid" label="#" sortable>
              {{ props.row.pid }}
            </b-table-column>
```

**Comment by jtommy** [comment]
@williamabbott You might define a custom sort for that column
