### ISSUE TITLE
Tab item shows an extra underline

### ISSUE THREAD

**Issue by gppam** [buefy/buefy#1105]
### Overview of the problem

**Buefy** version: 0.7.0
**Vuejs** version: 3.0.5
**OS/Browser**: OSX 10.11/Firefox

### Description

The first tab item shows an underline, active or not. This only happens at the first tab item.

![dud tab item](https://user-images.githubusercontent.com/14272390/48930657-f7375c00-ef2c-11e8-83c0-41caf773f59a.gif)

I did what the manual says.

**Comment by jtommy** [comment]
@gppam Can you provide us the code?

**Comment by gppam** [comment]
```
<div class="media">
    <div class="media-content">
        <div class="content">
            <b-tabs>                                
                <b-tab-item label="Personal">
                //Stuff
                </b-tab-item>
                <b-tab-item label="Contact">
                </b-tab-item>
                <b-tab-item label="Other">
                </b-tab-item>
            </b-tabs>
        </div>
    </div>
</div>
```
Omitted other code. I just noticed the line only shows up inside the `content` class.

**Comment by lifenautjoe** [comment]
I have the same issue. Not sure its on bulmas side as the styles get added inline. 


![image](https://user-images.githubusercontent.com/12737509/83140462-69729900-a0ee-11ea-919f-ff1fe9972af5.png)


![image](https://user-images.githubusercontent.com/12737509/83140486-72636a80-a0ee-11ea-828a-6550dd552d71.png)
