### ISSUE TITLE
Taginput how to add HTML autocomplete attribute?

### ISSUE THREAD

**Issue by williamabbott** [buefy/buefy#1106]
How can we add HTML's [autocomplete](https://www.w3.org/TR/html52/sec-forms.html#element-attrdef-autocompleteelements-autocomplete) attribute to the underlying input when using TagInput?

In this case, chrome is peppering a lot of inputs with it's autocomplete / auto form & password filling with dialogs and overlaying inputs.

Adding autocomplete obviously clashes with TagInput's autocomplete attribute. 

`Expected Boolean, got String.`

**Comment by jtommy** [comment]
Autocomplete prop add an autocomplete component instead of input text.
We should add new prop or a way to see autocomplete attribute

**Comment by Loruz** [comment]
@jtommy Can we just change it to `auto-complete` ?

**Comment by williamabbott** [comment]
It will introduce a bit of a breaking change. Maybe a `native-autocomplete`?

**Comment by jtommy** [comment]
@williamabbott I'm thinking the same name :thumbsup:
