### ISSUE TITLE
@blur-event triggers falsely on <b-taginput>

### ISSUE THREAD

**Issue by Gnopps** [buefy/buefy#1109]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**: Windows 10 / Firefox 63.0.03

### Description

When using `<b-taginput>` together with a `@blur-event` then the event is called upon selecting a tag in the dropdown, instead of calling the event when the user clicks outside the tag input-field. 

### Steps to reproduce

1. Create tag input field like this:  
```
 <b-taginput
   @blur="function(value)"
       v-model="list.tags"
       :data="tagList"
       size="is-small"
       icon="label"
       placeholder="Tags"
       @add="addTagsToTagList">>
     </b-taginput>
```

2. Click to focus on tag field and type a tag available for selection. Dropdown-list of suggested tags will open. 

3. Select any of these tags. Blur-event is executed. Tag input-field is still focused.

### Expected behavior

In step 3, blur event should be not be executed. The blur-event should be executed only when user clicks outside of the tag input-field. 

### Actual behavior

In step 3 the blur-event should not be executed, as the user is still in the tag-editing phase.

**Comment by yxngl** [comment]
blur event is not documented for taginput. There is an internal function to handle it.
