### ISSUE TITLE
Buefy with other css framework

### ISSUE THREAD

**Issue by AlessandroFallco** [buefy/buefy#1111]
Hello, I'm using some buefy (v. 0.7.1) components in a vue app. This app will be injected in some sites that have already some css. One in particular is developed using bootstrap and some bulma's classes generate conflicts because of equal names.
So, vue scoping is not a solution but css modules could be (https://vue-loader.vuejs.org/guide/css-modules.html).. but i see using css modules the problem persist because i can't set manually buefy components classes name. Buefy components still not working.
There are any ideas? How i can "isolate" my app css from parent site?
Thank you

**Comment by jtommy** [comment]
We cannot isolate all because there is Bulma CSS too. I think you should migrate to Bulma only or import only as you want
