### ISSUE TITLE
Table opened-detailed with detail-key

### ISSUE THREAD

**Issue by CriimBow** [buefy/buefy#1112]
Hi everyone,

### Description
Is it normal that I can't assemble "opened-detailed" and "default-sort", if my detail-key and default key do not have the value of the first column.

### Steps to reproduce 
Here you can find the code :
https://codepen.io/anon/pen/jQQZVw

### Expected behavior
Open the details of the first two values by sorting my table by date.

### Actual behavior
Details do not open by default.

Thanks,

NB: I take the opportunity to have opened a GitHub Issue to know if it is possible with Buefy to put under each cell a description for a cell. Because what I'm doing right now is opening up every detail of every cell.

**Comment by jtommy** [comment]
@CriimBow In your example the `opened-detailed` prop should contains an array of string date because you 're using `date` field as key, for example https://codepen.io/anon/pen/jQJbLa
