### ISSUE TITLE
Autocomplete example "Async with custom template" refreshes content after moving through the items using keyup / keydown on keyboard

### ISSUE THREAD

**Issue by stas-kh** [buefy/buefy#1113]
### Overview of the problem

**Buefy version**: Buefy website
**Vuejs version**: Buefy website
**OS/Browser**: Chrome

### Description

After merging #875 there is an extra issue appeared - when we navigate through the items using arrow up / arrow down keys the infromation gets updated and it is impossible to select an item

### Steps to reproduce
1. Open https://buefy.github.io/documentation/autocomplete
2. Move to "Async with custom template" (without custom template works the same way)
3. Move to the nearest items by pressing arrow down on the keyboard

### Expected behavior
I expect that arrow up / down / left / right and possibly Enter will not cause extra call to the backend

### Actual behavior
The focus on the selected item disappears, the new request goes to backend and the content refreshes

**Comment by mesutgok** [comment]
hi, same problem here :(

**Comment by motzel** [comment]
It's just a standard keyup.native event. Just change getAsyncData() to:
```
getAsyncData: debounce(function (e) {
  if([37,38,39,40].indexOf(e.keyCode) >= 0) return;
  
  // ...
}, 500)
```

Those magic numbers above are just arrows key codes.

**Comment by mesutgok** [comment]
i solve problem, use change instead of input. for example: @input="getAutoCompleteService('company')"

**Comment by motzel** [comment]
I do not consider it to be a workaround. It’s just an example how to interact with a component. Official yes, but still an example.

**Comment by stas-kh** [comment]
Thank you for the fix!
