### ISSUE TITLE
Border color of TagInput component always purple

### ISSUE THREAD

**Issue by agcty** [buefy/buefy#1116]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**:

### Description

Border color of TagInput component is always purple when focused - should be user-defined

### Steps to reproduce

Just use TagInput and focus it

**Comment by jtommy** [comment]
@agcty You should override it using CSS o customize your theme changing Bulma SASS variable (https://bulma.io/documentation/form/input/)
