### ISSUE TITLE
b-input's password-reveal eye is not clickable and doesn't change password visibility

### ISSUE THREAD

**Issue by anzemur** [buefy/buefy#1117]
### Overview of the problem

**Buefy** version: [0.7.1]
**OS/Browser**: Microsoft Windows/Google Chrome

### Description

When I was trying to add password-reveal to my component the eye icon shows, but it is not clickable. When you try to click it doesnt change the password visibility or anything.
### Steps to reproduce

I created my own component with boolean value and when this value is set to true the password-reveal should show. But this didn't work as it should. So I copied the example code from the official website and that didn't work too. What could cause such behavour?

### Expected behavior

It should change visibility of the password and change the eye icon.
### Actual behavior

The eye icon is not clickable and nothing happens if you click it.

**Comment by jtommy** [comment]
@anzemur It's no easy help you without your component code.
Can you provide us the code?

**Comment by anzemur** [comment]
This is my component code. I left out some of the properties. Variable "showPass" determines if password-reveal shoud be on the component.

`<template>
  <b-field :label="label"
           :type="{'is-danger': errors.has(name)}"
           :message="errors.first(name)" >
      <b-input :id="name"
               :name="name"
               :value="value"
               :password-reveal="showPass">
      </b-input>
  </b-field>
</template>`

**Comment by anzemur** [comment]
I found the problem. Bulma overwrote Buefy properties, so when I deleted Bulma from modules it started working correctly.

The problem was that Bulma owerwrote this attribute and set it as "none".

```
.control.has-icons-left .icon, .control.has-icons-right .icon {
  pointer-events: auto;
}
```

**Comment by dbaba** [comment]
I used `<style>` tag with `!important` in order to override `none` as follows, which worked for me.
```html
<style scoped>
.control.has-icons-left .icon,
.control.has-icons-right .icon {
  pointer-events: auto !important;
}
</style>
```
