### ISSUE TITLE
Focusable table received default focus when row is selected

### ISSUE THREAD

**Issue by gtalarico** [buefy/buefy#1119]
### Overview of the problem

**Buefy** version: 0.6.6 (current released docs show this behavior) 
**Vuejs** version: 3.2.1
**OS/Browser**:  Chrome 70.0.3538.110

### Description
Table with `focusable` property gets highlighted when row is selected

### Steps to reproduce
* add `focusable` property to table
* select row

### Expected behavior
row is selected, table maintains apperance

### Actual behavior
row is selected, table gets a think blue border

### Workaround
```sass
.b-table .table:focus
    outline: none !important
```

## Gif

See table border after row is selected:

![dec-10-2018 17-42-09](https://user-images.githubusercontent.com/9513968/49766339-fa5b7780-fca2-11e8-93a2-30b3dc739185.gif)

https://github.com/buefy/buefy/blob/dev/src/scss/components/_table.scss#L106

**Comment by gtalarico** [comment]
Updated workaround `border` > `outline`

**Comment by jtommy** [comment]
@gtalarico Please clean browser cache and go to https://buefy.github.io (last version is 0.7.1).
Anyway default border color is link color.
