### ISSUE TITLE
Feature request: HTML element inside Tooltip

### ISSUE THREAD

**Issue by suparodi** [buefy/buefy#1122]
Hello dear community, hope the title is clear enough, thank you in advance for the consideration.

**Comment by MeikelLP** [comment]
I'd love to see an option to set the output HTML tag. I want an `<a>` tag instead of a `<span>` like what you can do with `router-link`.

**Comment by jtommy** [comment]
Duplicate https://github.com/buefy/buefy/issues/972

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/f0cfa37b064b4aa43d4aa698ffdeffa30a85b0fd

**Comment by Colorfulstan** [comment]
Looking for exactly this :)
I see it's in the commits for 0.9.
Any Idea when this will be published?

Btw: Thanks a lot for this library :muscle:

**Comment by jtommy** [comment]
@Colorfulstan I'm going to release a 0.8.18 and after that I should finish 0.9.0 (a couple of weeks?!!)
