### ISSUE TITLE
Computed tabs does not respect the array order

### ISSUE THREAD

**Issue by Gomah** [buefy/buefy#1124]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**: OS X/Chrome 71

### Steps to reproduce

https://codepen.io/anon/pen/JwGOpw

Try to change the inputs model

### Expected behavior

The tabs should keep the array order

### Actual behavior

The changed tab goes to the end of the array

**Comment by jtommy** [comment]
@Gomah Why are you using label as key ? Did you tried using an index ?

**Comment by Gomah** [comment]
My bad, adding a unique index solves the issue: https://codepen.io/anon/pen/OrNpjg

Thanks!
