### ISSUE TITLE
Infinited loop with a grouped checkox and a computed v-model

### ISSUE THREAD

**Issue by erwanpoupard** [buefy/buefy#1125]
### Overview of the problem

**Buefy** version: 0.7.0
**Vuejs** version: 2.5.17
**OS/Browser**: Any

### Description

when i click on a checkbox, and change my computed value, i have an error in the console : 

> vue.runtime.esm.js?2b0e:587 [Vue warn]: You may have an infinite update loop in watcher with expression "newValue" found in ---> <BCheckbox>

here is my code : 

```javascript 
 computed: {
    ...mapGetters([
      'agendaSettings'
    ]),
    daysToShow: {
      get() {
        return this.agendaSettings.daysToShow
      },
      set(val) {
        this.$store.commit('UPDATE_SETTINGS', { daysToShow: val.sort() })
      }
    },
  },
```

```html
  <b-checkbox :native-value="1" v-model="daysToShow">1</b-checkbox>
   <b-checkbox :native-value="2" v-model="daysToShow"> 2</b-checkbox>         
```

Without the sort() function in the computed setter, all works fine. 

What should i do ?

**Comment by jtommy** [comment]
@erwanpoupard it should be fixed in 0.7.1 version.
