### ISSUE TITLE
Inner circle of Radio not pixel perfect

### ISSUE THREAD

**Issue by anat** [buefy/buefy#1128]
From the docs,
The inner circle of the <b-radio component is not sized properly.

**OS/Browser**:
Latest Chrome

### Steps to reproduce

Go to the docs 
https://buefy.github.io/documentation/radio

Look at the component in the size part.

See that the smaller size has a broken appearance.

### Expected behavior

The radio button should have a circle rightly placed.

### Actual behavior

![image](https://user-images.githubusercontent.com/652592/50079228-52393780-01e9-11e9-92e7-c885f087169a.png)

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/817
