### ISSUE TITLE
How to properly customize to modify internal CSS of components

### ISSUE THREAD

**Issue by tejashah88** [buefy/buefy#1130]
### Overview of the problem

**Buefy** version: [0.7.1]
**Vuejs** version: [2.5.21]
**OS/Browser**: Windows 10 / Google Chrome v71.0.3578.98

### Description
I'm not sure if this is a bug or if there's a better way to implement the requested functionality but here it goes...

I wanted to use a group of checkbox buttons but one thing that's really tricky to do is have them shown with an equal width. I'm able to change the button width but it just spaces out the buttons, and doesn't fill in those spaces. Upon inspection of the CheckboxButton component, it seems that setting the width of the inner `label` tag yields the desired output.

There's two ways to circumvent this issue as far as I know:
1. Create a copy of [CheckboxButton.vue](https://github.com/buefy/buefy/blob/dev/src/components/checkbox/CheckboxButton.vue) and set the width of the `label` tag to 100% (i.e. add `style="width: 100%"`)
2. Use a reference to modify the style when the component is mounted. This is the code that I used:
```javascript
mounted() {
  this.$refs.styleCheckboxBtn.forEach(btn => btn.$el.children[0].style.setProperty('width', '100%'));
  this.$refs.typeCheckboxBtn.forEach(btn => btn.$el.children[0].style.setProperty('width', '100%'));
}
```

**Before Style modifications**:
![image](https://user-images.githubusercontent.com/11187343/50084498-0b791c80-01ac-11e9-8115-0cfec3ad4e39.png)
Corresponding JSFiddle: https://jsfiddle.net/tejashah88/ozj3yL6p/

**After Style modifications**:
![image](https://user-images.githubusercontent.com/11187343/50086661-965d1580-01b2-11e9-87e6-b1c36cb398a7.png)
Corresponding JSFiddle: https://jsfiddle.net/tejashah88/mo4tq670/

FYI:
- Change the view of the JSFiddles in 'Settings' to 'Buttom results' to see the space filling problem.
- The button won't change colors when clicking until you open developer tools (at least on Chrome).

Both solutions seem really hacky, and as I'm new to Vue (just started a week ago), I'm wondering if there's a better solution to modify the CSS. Thank you!

### Steps to reproduce
Just use any of the JSFiddles as mentioned above.

### Expected behavior
The buttons should be equally spaced and fill in those spaces.

### Actual behavior
The buttons are only be equally spaced but do not fill in those spaces.

**Comment by tejashah88** [comment]
Nevermind, I found the solution! There's a stupidly simple way to change the style as shown below.

```css
.b-checkbox.checkbox.button {
  width: 100%;
}
```

You'll still need to apply the 100% width on the `b-checkbox-button` components in order to make it work.

It might still be helpful to add some documentation about what the user can do as far as the customization of individual components, so that noobs like me won't have to raise similar issues about CSS.

**Comment by barclayd** [comment]
This is a great help, thank you very much @tejashah88 😊
