### ISSUE TITLE
Modal component width issue

### ISSUE THREAD

**Issue by serzhiio** [buefy/buefy#1135]
When set up 'width' property of **modal** component, it sets **style="max-width: XXXpx"**.
Why not simple **width**?

P.S.: btw thx for outstanding work, well done!

**Comment by yxngl** [comment]
The pull request failed to close multiple issues. For your question, simply using width is not responsive and will fail on mobile or in a narrower browser window.

**Comment by Youdaman** [comment]
You can fix the width param not working by setting the width of .modal-card to auto, see https://github.com/buefy/buefy/issues/519#issuecomment-356127796

**Comment by sookoll** [comment]
It is not working. I set modal width=1200 but it still produce modal with 640px and if I set .modal-card width=auto, it even more narrows modal width to 460px.

**Comment by yxngl** [comment]
@sookoll You should use either `:width="1200"` or `width="1200px"`
It will be taken as a number only with a colon (as a JS expression).
