### ISSUE TITLE
[Docs] This dependency was not found:  buefy in ./src/main.js

### ISSUE THREAD

**Issue by MatiasOlivera** [buefy/buefy#1136]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**: Windows 10 / Chrome

### Description

The [ NPM/Webpack usage section](https://buefy.github.io/#/documentation/start) in the documentation is outdated.

```js
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/lib/buefy.css' // lib must be dist

Vue.use(Buefy)
```

The [repo guide](https://github.com/buefy/buefy#2-import-and-use-buefy) is updated.

### Steps to reproduce

Follow the web guide to install and configure buefy.

### Expected behavior

I want to the app compile without errors.

### Actual behavior

```
ERROR  Failed to compile with 1 errors
This dependency was not found:

* buefy/lib/buefy.css in ./src/main.js
```

**Comment by jtommy** [comment]
What repo link ?

**Comment by MatiasOlivera** [comment]
Documentation > Start > Usage > NPM / Webpack

**Comment by jtommy** [comment]
https://buefy.github.io/documentation/start

I think you're seeing the old docs, please clean cache

**Comment by Noxiess** [comment]
> https://buefy.github.io/documentation/start
> 
> I think you're seeing the old docs, please clean cache

site down lol
