### ISSUE TITLE
Hide hoverable dropdown menu after the user click

### ISSUE THREAD

**Issue by Kevin-Jian** [buefy/buefy#1137]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.17
**OS/Browser**: windows/chrome

### Description
When user click hoverable dropdown menu, it still displayed util the user moves out of it. 

### Steps to reproduce
1. Write a hoverable dropdown menu.
2. Mouse over it.
3. It will show dropdown menu, click menu and not move out of it. 

### Expected behavior
When user click dropdown menu, menu should not displayed(hidden).

### Actual behavior
When user click dropdown menu, the menu still displayed, and the toggle method also not working on hoverable dropdown menu.

(I use v-show to hidden the menu after user click menu for workaround, but not convenient.)

**Comment by SDJeff** [comment]
Yes. Please fix it. The same for me

**Comment by Kevin-Jian** [comment]
Finally I modified my feature, I found the original behavior is what I need. Maybe consider adding a new config to control this behavior is a solution.

**Comment by SDJeff** [comment]
Can you share your solution with me?

**Comment by Kevin-Jian** [comment]
This is my workaround, but not a good solution, because of the div wrapper of b-dropdown component, it has a screen flash problem and can't be resolved.

```
<b-dropdown hoverable>
	<span slot="trigger">
		<a href="#">Menu</a>
	</span>
	<div v-show="isShowDropDownMenu">
		<b-dropdown-item>A</b-dropdown-item>
		<b-dropdown-item>B</b-dropdown-item>
		<b-dropdown-item>C</b-dropdown-item>
	</div>
</b-dropdown>
```

```
handleClick: function(){
	this.isShowDropDownMenu = false;
	//do something...
	setTimeout(function () { this.isShowDropDownMenu = true;}, 50);
},
```

**Comment by yxngl** [comment]
I think some people may prefer this as the default behavior, but at least it should allow it to be changed. Currently `toggle` method explicitly skips when the dropdown is hoverable (mentioned in #142 and #543). It seems to me the skipping logic is only designed to prevent toggling when trigger is clicked. I think it could be modified to keep the behavior but allows programmatic calling of `toggle` on hoverable dropdown directly through `$parent` or `$refs` when a dropdown menu is clicked.

**Comment by jtommy** [comment]
I've just enabled `toggle` method when `hoverable` too; in the next breaking change it will be close on click as default behaivour

**Comment by service-paradis** [comment]
@jtommy 
Will the default behavior be changed on the next release?

**Comment by jtommy** [comment]
Yes there is a commented part in the  code to remove :)
