### ISSUE TITLE
How to pass default config in standalone mode?

### ISSUE THREAD

**Issue by ebutusov** [buefy/buefy#1138]
### Overview of the problem

**Buefy** version: v0.7.1
**Vuejs** version: v2.5.7
**OS/Browser**: Chrome 71

### Description

I'm using Buefy in standalone mode:
<script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>

I'm trying to pass some default options then:

Vue.use(Buefy, {
defaultIconPack: 'fas', ....
});

But it seems like Buefy is already registered and these options have no effect.
Is there a way to configure Buefy after it was registered?

**Comment by oldcastor** [comment]
try
```html
<script>
  Vue.use(Buefy.default, {
    defaultIconPack: 'fas',
  })
</script>
```

**Comment by ebutusov** [comment]
This doesn't work either.

I found a way to pass the options, but it is not so elegant... Anyways:

Vue.prototype["$buefy"].setOptions(
  {
    defaultIconPack: 'fas',
    defaultMonthNames: [...]
    defaultFirstDayOfWeek: 1,
    defaultDayNames: [...]
  }
);

**Comment by jtommy** [comment]
We added `$buefy` component, for example:
```
new Vue({
 el: '#app'.
 beforeMount() {
   this.$buefy.setOptions(...)
 }
})
```
