### ISSUE TITLE
Fixed height on date-picker

### ISSUE THREAD

**Issue by Namchee** [buefy/buefy#1139]
### Overview

**Buefy** version: [0.7.1]
**Bulma** version: [0.7.2]
**Vuejs** version: [2.5.17]

### Description

First of all, thanks for the hard work on this UI component.

I would like request a fixed-height feature on `inline` date-picker. Currently, the date-picker doesn't have fixed height, so it will grow / shrink accordingly based on the rendered dates.

### Steps to reproduce

![asdasda](https://user-images.githubusercontent.com/32661241/50371206-c8261000-05e8-11e9-9a55-3b0396fcd0b2.png)

### Expected behavior

Fixed date-picker height, as I have a parent container

### Actual behavior

![asdasda](https://user-images.githubusercontent.com/32661241/50371223-1affc780-05e9-11e9-95ba-7b3f7788a70a.png)

As you can see, the date-picker shrinks because Juni (June) has fewer dates to render.

**Comment by jtommy** [comment]
@Namchee Thanks. About your request you might set the height by CSS, for example https://codepen.io/anon/pen/BvRgOw

**Comment by Namchee** [comment]
Thank you for the reply!

It fixed most of the issues but, having a blank space below the datepicker is (IMO) kind of ugly. Is it possible to add an option for the datepicker to ALWAYS render 6 rows of date?

For example, at month Juni (June), the datepicker stopped rendering dates at 3rd day of next month (July) which make it only having 5 rows in total. Enabling the option will render 4th, 5th (and so on...) date until it fills the 6th row.

**Comment by jtommy** [comment]
Maybe you're right we should fix the height but about fixed 6 rows with next month days I don't think it's a good solution.
