### ISSUE TITLE
Feature request: Hide chevron column in detailed table

### ISSUE THREAD

**Issue by oldcastor** [buefy/buefy#1140]
### Overview of the problem

**Buefy** version: [0.7.1]
**Vuejs** version: [2.5.17]
**OS/Browser**:any

### Description
This is the feature request to get an option to **completely hide** chevron **column** (not only chevron icon) in case of using alternative way to open row details (on select row, for example)

### Steps to reproduce

[here](https://codepen.io/oldcastor/pen/EGxdpr) is standard detaild table (+ bordered). 
![def-1](https://user-images.githubusercontent.com/21212418/49714061-1f74c980-fc54-11e8-9555-7fa1935e8139.png)

Having `:detailed="false"` leads to 
![def-2](https://user-images.githubusercontent.com/21212418/49714129-6f539080-fc54-11e8-9327-a7cd6a8feb03.png)
(no 'chevron' column)

Now adding `:has-detailed-visible="()=>false"` or  `:has-detailed-visible="(row)=>false"` giving this result 
![def-3](https://user-images.githubusercontent.com/21212418/49714912-687a4d00-fc57-11e8-9510-b1d7561fdfa6.png).

### Expected behavior
keep detailed table functionality without chevron column
![def-2](https://user-images.githubusercontent.com/21212418/49714129-6f539080-fc54-11e8-9327-a7cd6a8feb03.png)

### Actual behavior
![def-3](https://user-images.githubusercontent.com/21212418/49714912-687a4d00-fc57-11e8-9510-b1d7561fdfa6.png).

**Comment by omer2500** [comment]
if you font mind i will give it a try! @jtommy  @oldcastor

**Comment by omer2500** [comment]
#1155 done
you can take a look @jtommy @oldcastor
