### ISSUE TITLE
Status icon not displaying correctly when using a font-awesome brand icon

### ISSUE THREAD

**Issue by EvanBarbour3** [buefy/buefy#1144]
### Overview of the problem

**Buefy** version: [0.7.1]
**Vuejs** version: [2.5.17]
**OS/Browser**: Mac OS Mojave 10.14.1 / 71.0.3578.98 

### Description

Using the font-awesome 'brand' icon set with a field that has a type of `is-danger` or `is-success` doesn't show the icon on the right hand side, as the icon pack evaluates to be `fab` instead of `fa` or `fas` (whichever is the default).

### Steps to reproduce

1. Create an input that uses an icon from the font-awesome 'brand' icon set

![capture_1](https://user-images.githubusercontent.com/7600557/50513641-e8464b00-0a90-11e9-9c46-d4310d96e17a.png)

2. Add the `is-danger` or `is-success` to the outer `b-field` type

```html
<div class="column is-half-desktop is-full-tablet">
    <b-field
        label="Dropbox Link"
        :type="is-danger"
        :message="The dropbox link must be a valid url"
    >
        <b-input
            v-model="dropbox link"
            placeholder="Paste Dropbox file link here"
            icon="dropbox"
            icon-pack="fab"
        ></b-input>
    </b-field>
</div>
```

### Expected behaviour

The right hand side icon will display the corresponding icon correctly (tick / exclamation)

### Actual behaviour

Icon cannot be found, and displays a square instead

![capture_2](https://user-images.githubusercontent.com/7600557/50513778-b71a4a80-0a91-11e9-86f0-9beb16828b1c.png)
![capture_3](https://user-images.githubusercontent.com/7600557/50513779-ba153b00-0a91-11e9-93c8-5cd6d13fb3c1.png)

**Comment by jtommy** [comment]
@EvanBarbour3 At the moment the icon pack of internal icons must be fas or far or fal.
