### ISSUE TITLE
buefy.github.io icons are missing

### ISSUE THREAD

**Issue by SharpSeeEr** [buefy/buefy#1145]
### Overview of the problem

The main buefy homepage, https://buefy.github.io/, is missing all icons.
![image](https://user-images.githubusercontent.com/4459909/50529386-b72a4280-0ab1-11e9-96b2-d97777c6b3e4.png)
![image](https://user-images.githubusercontent.com/4459909/50529394-d1642080-0ab1-11e9-9441-ec1b53550099.png)

**buefy.github.io** version: v0.6.6
**Buefy** version: N/A
**Vuejs** version: N/A
**OS/Browser**: Windows 10 1803, Chrome 71.0.3578.98 64-bit

### Description

The font files for material design and font awesome are returning a 404.  Perhaps unrelated (perhaps not) the service-worker.js is also returning a 404.  Network requests from Chrome:

![image](https://user-images.githubusercontent.com/4459909/50529481-59e2c100-0ab2-11e9-9b06-5321290fb525.png)

### Expected behavior

&lt;sarcasm&gt;I _expect_ to see the icons gosh darn it.&lt;/sarcasm&gt;  

### Actual behavior

I see a bunch of empty rectangles where the icons should be.

**Comment by jtommy** [comment]
Did you try to clean browser cache and go to official docs site without # ?

**Comment by SharpSeeEr** [comment]
I disabled the cache and loaded the site without the #.  It automatically redirects me to `https://buefy.github.io/#/`.  If I navigate to another page, such as documentation, it takes me to `https://buefy.github.io/#/documentation/start`.  If I manually remove the # from the url, it stays gone and the icons all appear as expected.  

So I guess the question is, why is it redirecting me to `/#/`?
