### ISSUE TITLE
Mobile navbar above black mask

### ISSUE THREAD

**Issue by TheTrigger** [buefy/buefy#1150]
![image](https://user-images.githubusercontent.com/6072718/50560858-277cd200-0d05-11e9-83f3-78c0610b6c46.png)

![image](https://user-images.githubusercontent.com/6072718/50560916-bab60780-0d05-11e9-9e6d-805f547f77e8.png)

### Overview of the problem

**Buefy** version: [0.7.1]
**OS/Browser**: Android 9 - OnePlus6 - Chrome 71.0.3578.99

### Steps to reproduce

1. Navigate https://buefy.github.io/documentation/dropdown/ with Android Phone
2. Open full screen Dropdown (purple Click me!)

### Expected behavior

The bar should not be on top

### Actual behavior

The navbar is visible above on the black mask

## EDIT
Same behavior with desktop, just resize the window

**Comment by yxngl** [comment]
https://github.com/buefy/buefy/blob/a06eed4b2753d31a8082be68397b643b922e2cd8/src/scss/components/_dropdown.scss#L9
Bulma navbar has z-index of 30 and modal has 40. Probably should be larger than that.
Tooltip in Buefy uses 888.
