### ISSUE TITLE
Small Tables?

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#1160]
I need a smaller b-table, smaller font, less spacing between rows, etc. This is important in viewing large datasets (more rows per page) or more columns.

Something like size="is-small"

**Comment by jtommy** [comment]
Take a look https://bulma.io/documentation/elements/table/ or you have to customize using CSS.

**Comment by kerbo** [comment]
Yes, I looked at the Bulma table docs before posting this issue. Nothing is mentioned about resizing a table. And I have no idea how to make a b-table smaller with css. This is why I posted this request.

Smaller components are supported in the rest of the framework. Why not b-tables? This would be a very useful enhancement. Not sure why the issue was closed.

**Comment by kerbo** [comment]
I posted a request in the Bulma repository and they suggested "is-narrow" would help with the spacing but not with the font size.

I tried class="is-narrow" on b-table and it had no effect.

**Comment by jtommy** [comment]
There is narrow prop!

**Comment by edkim8** [comment]
> I need a smaller b-table, smaller font, less spacing between rows, etc. This is important in viewing large datasets (more rows per page) or more columns.
> 
> Something like size="is-small"

Did you find out how to reduce the font size?
I used "narrow" prop but what if I would like to reduce the font size smaller.

**Comment by kerbo** [comment]
You have add is-size-6 or is-size-7 (Bulma font size classes) to each column or cell content to go smaller.

**Comment by momander** [comment]
Here is what I did to make b-tables use automatic width (instead of the default 100%):

```
<style>
  .b-table .table {
    width: auto !important;
  }
</style>
```
