### ISSUE TITLE
How to pass helper classes to input element?

### ISSUE THREAD

**Issue by Uninen** [buefy/buefy#1162]
### Overview of the problem

**Buefy** version: 0.7.1

### Description

Is there a way to pass helper classes to input field? The documentation for `field` says that `custom-class` attribute denotes "CSS classes to be applied on field label" but there's no mention on how to pass for example `is-radiusless` class to input element.

I currently have following and it only works for the control-side of the element:
```
    <b-field>
      <p class="control">
        <span class="button is-static is-radiusless">
          <span v-html="nick"></span>
        </span>
      </p>
      <b-input class="is-radiusless"></b-input>
    </b-field>
```

**Comment by jtommy** [comment]
It will be available in the next release https://github.com/buefy/buefy/pull/1149
