### ISSUE TITLE
b-taginput with autocomplete is clipped inside modal

### ISSUE THREAD

**Issue by dahof1** [buefy/buefy#1163]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**: mojave / firefox / chrome

### Description

Taginput with autocomplete is clipped within modal

![screenshot_2019-01-09 coffee-order-webapp2](https://user-images.githubusercontent.com/46201601/50919636-a11e6980-1443-11e9-8506-29f5896270f3.png)

### Steps to reproduce

1. Create Modal
2. Add b-tag-input with filteredlist / autocomplete

### Expected behavior

No clipping within modal

### Actual behavior

See screenshot

**Comment by jtommy** [comment]
Related to https://github.com/buefy/buefy/issues/292

**Comment by toreyheinz** [comment]
Both issues have to do with the dropdown menu extending beyond the bounds of a parent element with `overflow: hidden` 

Looks like the only "good" way to solve this is to have the dropdown render outside the element with `overflow: hidden` and postion it with JS.

I've been working around this by adding padding to the parent element.

**Comment by jtommy** [comment]
I'm thinking to append the dropdown menu to body with JS but it's no easy because all CSS styles depends on parent dropdown class

**Comment by toreyheinz** [comment]
Another workaround is to set the dropdown position to 'relative' if it's greater than the container with `overflow: hidden`

Not fully tested...
```javascript
@focus="ensureDropDownVisibility"
```

```javascript
ensureDropDownVisibility() {
  var container = document.querySelector('div.modal-card-body')
  var dropdown = container.querySelector('.dropdown-menu')
  if (container.offsetHeight < menu.offsetHeight) {
    dropdown.style.position = 'relative'
  }
}
```

it forces things to get shifted around, but it's better than having the content be hidden.

**Comment by wrabit** [comment]
Just came up against this myself, this seems to be working for me:

```
.modal.has-overflow {
  position: fixed !important;
  overflow: auto !important;
  .modal-background {
    position: fixed !important;
  }
  .modal-content {
    overflow: visible !important;
  }
  .modal-card {
    overflow: visible !important;
  }
  .modal-card-body {
    overflow: visible !important;
  }
}
```

https://codepen.io/will-abbott/pen/zgEOmW

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy should be closed as css issue, not related to buefy at all.

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/1c71da209fb26e94d0cdba7b02f159dae8c42800

**Comment by afwn90cj93201nixr2e1re** [comment]
hm, stop, you have implemented clear appending to body? Or it's just 'fix'? So, if not, then you should start making new tooltips!

**Comment by jtommy** [comment]
Soon tooltip but it will be a breaking change
