### ISSUE TITLE
b-table pressing checkbox on checkable and selectable table

### ISSUE THREAD

**Issue by asadhshujau** [buefy/buefy#1164]
### Overview of the problem

**Buefy** version: [0.7.1]
**Vuejs** version: [2.5.17]
**OS/Browser**: Ubuntu 18.04 LTS / Google Chrome 71.0.3578.98 (Official Build) (64-bit)

### Description

On a checkable b-table with selectable rows. if a checkbox is pressed, it is checking the box and selecting the row as well. This might be a use case but I want only the checkbox to be checked without selecting the row.

### Steps to reproduce

1. create a **b-table** that is __checkable__ and __selectable__
2. use ```:checked-rows.sync="checkedRows"``` and ```:selected.sync="selected"```
3. click on a single checkbox of any row

### Expected behavior

Check the checkbox without selecting the row

### Actual behavior

Checked the checkbox and selected the row

Here's a preview:
![myimage](https://user-images.githubusercontent.com/16648185/50951373-c99f7580-14ce-11e9-8d4a-b9c06032b6c9.gif)

**Comment by ijunaid8989** [comment]
@asadhshujau can you give the codepen to that gif? datatable?
