### ISSUE TITLE
[Safari] Autocomplete dropdown border does not disappear

### ISSUE THREAD

**Issue by cuong-nguyen** [buefy/buefy#1166]
### Overview of the problem
Autocomplete dropdown border does not disappear when dropdown closes

**Buefy** version: [0.7.1]
**Vuejs** version: [3.1.3]
**OS/Browser**: MacOS/Safari

### Description
Autocomplete dropdown border does not disappear when dropdown closes

### Steps to reproduce
(It happens with our site, I just use your homepage for reproducing purpose)

1. Open Safari browser and go to https://buefy.github.io/documentation/autocomplete
2. Scroll to **Object array** section & enable **Open dropdown on focus** option
3. Focus on the input & select the first option on the list

### Expected behavior
There is no border rending on the page

### Actual behavior
<img width="1058" alt="screen shot 2019-01-10 at 6 31 13 pm" src="https://user-images.githubusercontent.com/5061591/50962843-16eb0980-1506-11e9-9413-2c98347b32f8.png">

**Comment by jtommy** [comment]
@cuong-nguyen I just realized that your're seeing old docs (broken icon), please clear cache and try again.

**Comment by yxngl** [comment]
I was able to saw the same problem only in Safari the same day when the issue was reported. But now I cannot reproduce it.

**Comment by jtommy** [comment]
It's ok in the last release, no issue on Safari.
