### ISSUE TITLE
readonly tab item

### ISSUE THREAD

**Issue by heregoesnoth** [buefy/buefy#1167]
How can i set my tab item to readonly? I need to change the tabs only by my controls (buttons)

I don't want to use the disable property here because the appearence its not what i'm looking for.

For now, im setting the `<li>` with pointer-events: none.

There is a better way to do this? 
We have a disable property, maybe a readonly property would be nice?

**Comment by jtommy** [comment]
You might use disabled and then customize the style.
Read-only is a weird - edge case I think to be honest.

**Comment by heregoesnoth** [comment]
Yea, i get it.

In this case im gonna customize the style _(override the opacity property, basically)_
Thanks for the reply @jtommy
