### ISSUE TITLE
Table is not appearing when I do Vue.use(Buefy)

### ISSUE THREAD

**Issue by ijunaid8989** [buefy/buefy#1170]
### Overview of the problem

**Buefy** version: [0.7.1]
**Vuejs** version: [2.5.21]
**OS/Browser**: Ubuntu/Chrome

### Description

Buefy tables are not working.

### Steps to reproduce
Add Buefy to your package.json file
```
{
  "name": "evercam_admin",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "3.5",
    "vue": "^2.5.21",
    "vue-loader": "14.2.2",
    "vue-template-compiler": "^2.5.21",
    "vue-router": "^3.0.1",
    "vue-resource": "^1.5.1",
    "vue-gravatar": "^1.3.0",
    "@coreui/coreui": "^2.1.4",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.2.0",
    "@coreui/icons": "0.3.0",
    "@coreui/vue": "^2.1.0",
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.0.0-rc.11",
    "chart.js": "^2.7.3",
    "core-js": "^2.6.0",
    "css-vars-ponyfill": "^1.15.3",
    "flag-icon-css": "^3.2.0",
    "font-awesome": "^4.7.0",
    "perfect-scrollbar": "^1.4.0",
    "simple-line-icons": "^2.4.1",
    "jquery": "^3.3.1",
    "popper.js": "^1.14.4",
    "css-loader": "^0.28.1",
    "buefy": "0.7.1"
  },
  "devDependencies": {
    "webpack-dev-server": "2.11.2"
  }
}
```
then 
```
import "buefy/dist/buefy.css"
import Buefy from "buefy";
Vue.use(Buefy)
```

Add table.
```
<template>
    <b-table
        :data="data"
        :columns="columns"
        :row-class="(row, index) => row.id === 1 && 'is-info'">
    </b-table>
</template>

<script>
    export default {
        data() {
            return {
                data: [
                    { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016-10-15 13:43:27', 'gender': 'Male' },
                    { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016-12-15 06:00:53', 'gender': 'Male' },
                    { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016-04-26 06:26:28', 'gender': 'Female' },
                    { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016-04-10 10:28:46', 'gender': 'Male' },
                    { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016-12-06 14:38:38', 'gender': 'Female' }
                ],
                columns: [
                    {
                        field: 'id',
                        label: 'ID',
                        width: '40',
                        numeric: true
                    },
                    {
                        field: 'first_name',
                        label: 'First Name',
                    },
                    {
                        field: 'last_name',
                        label: 'Last Name',
                    },
                    {
                        field: 'date',
                        label: 'Date',
                        centered: true
                    },
                    {
                        field: 'gender',
                        label: 'Gender',
                    }
                ]
            }
        }
    }
</script>

<style>
    tr.is-info {
        background: #167df0;
        color: #fff;
    }
</style>
```

### Expected behavior

Table should appear

### Actual behavior

![image](https://user-images.githubusercontent.com/13561999/51048280-61df4c80-15ec-11e9-8c54-fdae01031b32.png)

no table appeared just blank divs.

If I do this way
```
import { Table } from 'buefy/dist/components/table'
import { Input } from 'buefy/dist/components/input'
import 'buefy/dist/buefy.css'

Vue.component('b-table', Table)
Vue.component('b-input', Input)
```
then a few tables work but Async data give 100 errors of <b-table-column>

What I am missing here?? I want to use the full buefy.

**Comment by ijunaid8989** [comment]
@buefy anyone can please help? I stuck on this for 2 days. And I need to get it work now

**Comment by bhavesh-786** [comment]
@ijunaid8989 I am also having same issue how you resolve this can you please suggest I am also using coreui + buefy in vue js application and not able to get table and imported buefy css also effecting another pages.

**Comment by ijunaid8989** [comment]
@bhavesh-786 are you using VueBootstrap as well? I was using that when I removed it table appeared

**Comment by bhavesh-786** [comment]
@ijunaid8989 Yes I am using but while we remove this vueBootstrap then all css will be gone then how we can apply css for this.?

**Comment by bhavesh-786** [comment]
@ijunaid8989 So you also having this same issue still there is not any suggestion for this things

**Comment by ijunaid8989** [comment]
@bhavesh-786 Buefy has its own CSS.

**Comment by bhavesh-786** [comment]
@ijunaid8989 so is there any other why using we can do this?

**Comment by ijunaid8989** [comment]
Yeah, you can don't use Buefy use, https://www.vuetable.com/#current-version, Its better than this.

**Comment by bhavesh-786** [comment]
@ijunaid8989 Ok man thank I will use this bcoz  I already spent 2 days on the same issue.

**Comment by ijunaid8989** [comment]
@bhavesh-786 Yeah I also wasted much time on that, and then switched to that one. If you need any help regarding Vuetable please do ask me.

**Comment by bhavesh-786** [comment]
@ijunaid8989 here no proper document for vuetable can you please help me

**Comment by ijunaid8989** [comment]
@bhavesh-786 please check those examples https://codesandbox.io/u/ratiw/sandboxes

**Comment by bhavesh-786** [comment]
@ijunaid8989 this vue table having look like a Buefy on mobile scree bcoz I check one example and it's showing table in mobile scree also.

**Comment by AhmedelheGery** [comment]
Hey @ijunaid8989 
I have the same issue using BootstrapVue with Buefy make one of them only work depending on which imported first on your main.js file 

I fixed it by using Individual components instead of importing the Full bundle

And here is how you can do this from Buefy doc
https://buefy.org/documentation/start/

**Comment by felipepodolan** [comment]
Was this ever addressed? Can I import Buefy table using a different name than "b-table" ?
