### ISSUE TITLE
Disabled radio button is not displaying its value

### ISSUE THREAD

**Issue by kdekooter** [buefy/buefy#1171]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**: latest Chrome

### Description

If the user clicks a radio button and later on the radio buttons are disabled the selected value is not visible anymore. The widget is grayed out - which is as expected. However the middle of the radio button turns white.

![image](https://user-images.githubusercontent.com/508983/51103445-03c88a00-17e3-11e9-8aef-7303b5269bc6.png)

### Expected behavior
The selected & disabled radio should still display its selected state, like so:

![image](https://user-images.githubusercontent.com/508983/51103585-a1bc5480-17e3-11e9-9f2e-8afe5a306c34.png)

**Comment by jtommy** [comment]
@kdekooter I think i don't understand well, please take a look https://codepen.io/anon/pen/VqgwwW?&editable=true&editors=101. Is it your case ?

**Comment by kdekooter** [comment]
It is working for you apparently! One slight difference though: I am not using v-model because my app uses vuex.

**Comment by jtommy** [comment]
@kdekooter Why aren't you using `value` prop instead of `checked` ? 
https://codepen.io/anon/pen/VqgwwW?&editable=true&editors=101

**Comment by kdekooter** [comment]
That fixes things. Thanks!

**Comment by LarBearrr** [comment]
Is it not possible to just pass a checked prop to the radio button? I don't want to bind it to anything.

I'm trying to convert this:
```
<input
                id="<?= $fieldId ?>"
                name="<?= $field->getName() ?>"
                value="<?= $value ?>"
                type="radio"
                <?= $field->isSelected($value) ? 'checked="checked"' : '' ?>
                <?= $this->previewMode ? 'disabled="disabled"' : '' ?>
                <?= $field->getAttributes() ?>>
```

to the Buefy radio:
```
<b-radio
                native-value="<?= $value ?>"
                id="<?= $fieldId ?>"
                name="<?= $field->getName() ?>"
                <?= $this->previewMode ? 'disabled' : '' ?>
                <?= $field->getAttributes() ?>
            >
                <?= e(trans($option[0])) ?>
                <?php if (isset($option[1])): ?>
                    <p class="is-size-7"><?= e(trans($option[1])) ?></p>
                <?php endif ?>
            </b-radio>
```
Everything is working except showing the selected radio button based on the value from the DB.
