### ISSUE TITLE
Request: b-table: option to have 'perPage' in the table footer, near to the table pagination

### ISSUE THREAD

**Issue by mkstix6** [buefy/buefy#1174]
nuxt@2.3.2
nuxt-buefy@0.3.2

Perhaps this is possible already, if so, apologies.

Mostly, when our designs need pagination we have the 'per-page' option nearby the pagination-pages buttons at the bottom of whatever is paginating. I think simply because we think of the two things being heavily related.

I'm not sure if it's possible to add more items to the b-table footer where the pagination buttons are.
Or whether the b-table component would have to be modified to enable me to add the 'per-page' option at the bottom.

Advice or thoughts would both be appreciated.

I also wanted to add, thanks very much for saving me so much time with a well thought out table component. It's very flexible and reassuringly reliable.

![table___buefy](https://user-images.githubusercontent.com/1573136/51245241-006a0580-197f-11e9-91fd-e576f165815c.png)

**Comment by jtommy** [comment]
@mkstix6 Have you tried adding a select in the `bottom-left` slot ?

**Comment by mkstix6** [comment]
I hadn't realised! Wonderful. Thanks.
Thanks also for the speedy response.
Will close now.
Apologies for missing it.

**Comment by mkstix6** [comment]
Just came back to this to implement and couldn't see anything about slots in the pagination documentation.
Happy to try to work this out now that I know the slot option exists but perhaps a note in the documentation would point more people in the right direction.

**Comment by jtommy** [comment]
Do you want add a slot to pagination component ?

**Comment by mkstix6** [comment]
Oh! Yup, you're right. I'd forgotten that the pagination was actually part of the `b-table`. My bad. Thanks as always for your lightning-fast help.

**Comment by juanjoDiaz** [comment]
I am trying to do the exact same thing as described by @mkstix6 .

Is there any way to add the `items per page` selector to the pagination component (at the bottom right)??
