### ISSUE TITLE
Feature Request: Multiple Dates on Date Picker

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#1175]
Provide a multiple date option for date-picker. Return selected dates to v-model in an array.

**Comment by jtommy** [comment]
There is already a PR https://github.com/buefy/buefy/pull/1017.
I'm waiting changes that I requested some time ago

**Comment by jtommy** [comment]
I'm sorry, you're right. 
@kerbo Contributions are always welcome 😃

**Comment by afifsohaili** [comment]
I think the DatePicker component is worth refactoring. It's already quite complicated as of now. To support this behavior on top of single date and a range of date, it'll be quite a mess.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/1865
