### ISSUE TITLE
IE11/Edge datepicker sizing

### ISSUE THREAD

**Issue by anthrogan** [buefy/buefy#1177]
### Overview of the problem

**Buefy** version: v7.2
**OS/Browser**:
IE11/Edge
### Description
Datepicker min-height row height issue 

![image](https://user-images.githubusercontent.com/30973884/51311893-e5ac9500-1a41-11e9-8ecb-af53d85e0870.png)

caused by min-height on datepicker-body being set to 260px

**Comment by bonfinnk** [comment]
When to expect the fix in the master?

**Comment by jtommy** [comment]
I think this week
