### ISSUE TITLE
Is table cell merge available?

### ISSUE THREAD

**Issue by hados99** [buefy/buefy#1178]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

Really thanks for good library.

Is there any way to merge cells? - especially vertically.

I read document and roadmap but couldn't find any one.

**Comment by jtommy** [comment]
No it isn't in the roadmap.
There are so many things to do or improve and this isn't a primary thing at the moment
