### ISSUE TITLE
n IOS mobile/tablet device the b-table sort dropdown keeps popping up, if i place my b-table inside b-upload

### ISSUE THREAD

**Issue by krupa-shah** [buefy/buefy#1181]
### Overview of the problem

**Buefy** version: [0.5.3]
**Vuejs** version: [2.4.4]
**OS/Browser**:iphone-mobile and tablet/Safari and chrome

### Description
In IOS mobile/tablet device the b-table sort dropdown keeps popping up, if i place my b-table inside b-upload

### Expected behavior

Sort dropdown should appear only on click of dropdown, not when clicked anywhere on the screen.

### Actual behavior

I click or touch on screen the sort dropdown keeps popping up.

**Comment by lordfuoco** [comment]
@krupa-shah Out of curiosity why b-table inside a b-upload? I mean, it's rather unconventional use, also both vue and buefy are very old version, did you try to upgrade?
