### ISSUE TITLE
Setting icon on b-tab-item with defaultIconPack doesn't render

### ISSUE THREAD

**Issue by rcoundon** [buefy/buefy#1182]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.22]
**OS/Browser**: MacOS Mojave Chrome

When using defaultIconPack with b-tab-time the rendered html doesn't result in an icon getting shown:

I.e. setting:

```
Vue.use(Buefy, {
  defaultIconPack: 'fas'
});

```
and

```
<template>
  <div class="container">
    <b-tabs
      size="is-large"
      is-boxed>
        <b-tab-item label="Search" icon="search"></b-tab-item>
        <b-tab-item label="Music" icon="library-music"></b-tab-item>
        <b-tab-item label="Videos" icon="video"></b-tab-item>
    </b-tabs>
  </div>
</template>

```
Results in the rendered html:

    <i class="fas fa-search fa-3x"></i>

Which doesn't resolve to a fontawesome icon

**Comment by rcoundon** [comment]
Thanks for quick reply.  I was importing from a CDN, I've used

   yarn add @fortawesome/fontawesome-free

and then imported using:

    import '../node_modules/@fortawesome/fontawesome-free/js/all.js'

and it now works.  Should it work via a CDN?

**Comment by jtommy** [comment]
It works as you want but you are importing js file and it's wrong.

```
// FontAwesome 5
$fa-font-path: "~@fortawesome/fontawesome-free/webfonts";
@import "~@fortawesome/fontawesome-free/scss/fontawesome";
@import "~@fortawesome/fontawesome-free/scss/regular";
@import "~@fortawesome/fontawesome-free/scss/solid";
@import "~@fortawesome/fontawesome-free/scss/brands";
```

**Comment by rcoundon** [comment]
A couple of things.

Firstly, if you use only a CDN, the icons don't render, this is the original problem I experienced.  Is this by design or is this a defect?

Secondly, the FontAwesome documentation here:

https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

States:
"Reference either the /css/all.css **or the /js/all.js**..."

Your advice above seems to be contrary to what FA recommends.

**Comment by jtommy** [comment]
Maybe it works but old way was that.
Anyway CDN is ok

**Comment by rcoundon** [comment]
The CDN way doesn't work for me.  That's the original defect I reported.  The rendered HTML becomes:
<i class="fas fa-search fa-3x"></i>

**Comment by rcoundon** [comment]
I've started from scratch and it's now working, comparing before and after I can't yet see what the difference is but it's working with a CDN.
