### ISSUE TITLE
b-datepicker / placeholder text not shown on Safari @ iPhone

### ISSUE THREAD

**Issue by bonfinnk** [buefy/buefy#1183]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.5.22
**OS/Browser**: iOS/Safari

### Description

Placeholder text not shown on Safari @ iPhone

### Steps to reproduce

Open https://buefy.github.io/documentation/datepicker on Safari on an iPhone and compare to desktop Safari or i.e. Chrome.

### Expected behavior

Placeholder text is shown also on Safari on an iPhone.

### Actual behavior

Placeholder text is not shown. Datepicker icon is shown. 

**If `mobile-native=false`, the Placeholder text is shown!**

**Comment by bonfinnk** [comment]
Edit: If mobile-native=true, the Placeholder text is shown!

**Comment by jtommy** [comment]
@bonfinnk It's a limit using `type="date"` (in this way Buefy provide native picker) and the moment i didn't find a good hack.

**Comment by Jenpaulino3** [comment]
> Edit: If mobile-native=false, the Placeholder text is shown!

Thanks! I was stuck on this for hours 🙌🙌🙌
