### ISSUE TITLE
TypeScript missing close() definition for Modal component

### ISSUE THREAD

**Issue by RandomErrorMessage** [buefy/buefy#1184]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.5.22
**OS/Browser**: N/A

### Description

TypeScript complains about missing definition when using this.$parent.close() under a B-Modal component.

### Steps to reproduce

1. Install VueJS with TypeScript using VueCLI3
2. Install Buefy
3. Create implement example modal from documentation
4. Attempt to build

### Expected behavior

Working type definitions

### Actual behavior

I have to disable strict mode to get VueJS to build

**Comment by oliver-ni** [comment]
This is still an issue – any updates?

**Comment by RandomErrorMessage** [comment]
I found a solution through an example created by someone else, specifically this file: https://github.com/yoski/VueSample/blob/master/src/ts/buefy.ts

Adding the following variable to my Vue TypeScript component will allow compiling in strict mode while using "this.$parent.close()".
`public $parent: any;`

**Comment by gutisalex** [comment]
You can also do:
`(this.$parent as any).close(); `

kr

**Comment by kaangokdemir** [comment]
This is my solution:

(this.$parent as BModalComponent).close()
