### ISSUE TITLE
Tooltip usage

### ISSUE THREAD

**Issue by Wulfheart** [buefy/buefy#1185]
Hello,

is it possible to display a diagram made with chartjs in a tooltip? Can I fill the tooltip with different contents which can be formatted with a grid?

Thank you in advance

**Comment by lordfuoco** [comment]
@Wulfheart Hi I think that ATM is not possible but why a chart inside a tooltip ? if I may ask

**Comment by Wulfheart** [comment]
@lordfuoco It's a matter of UX Design of the project.

**Comment by MRR0GERS** [comment]
The tooltip itself isn't a dom node even though in Buefy it's a wrapper for one.  If you're looking to have a chart displayed in an object that's hidden until hovered over would a dropdown (or dropup) work in its stead?

**Comment by Wulfheart** [comment]
I just want a simple text in a table.

**Comment by MRR0GERS** [comment]
@Wulfheart I'd recommend looking at vue-popper, the dropdown or writing a custom component that does what you're looking for. The tooltip component doesn't support that option.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/1122
