### ISSUE TITLE
Feature Request: Add vertical align option to b-table-columns

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#1186]
It would nice if there was a easier way to add vertical alignment to table columns. This is an issue if a row contains a mix of fields and static text. The static text aligns to the top of the cell and doesn't align to the text in the field (e.g., input, button, etc)

Currently, I can add style="vertical-align: middle;" to the b-table-columns with static text and that works but I have to do that for every text column. I've tried using css for the whole table but can't get it to work.

An ideal option (if this is possible) is the b-table figuring out there are fields in some cells and making the vertical spacing adjustment on the static text cells automatically.

**Comment by jtommy** [comment]
@kerbo Using css you just set alignment to all `td`, for example:
```
.b-table {
  .table {
    td {
      vertical-align: middle;
    }
  }
}
```
Otherwise if you want apply it to a `b-table-column`, for example:
```
<b-table-column class="my-class"... > ... </b-table-column>

.b-table {
  .table {
    td.my-class {
      vertical-align: middle;
    }
  }
}
```
