### ISSUE TITLE
Change default behavior in TagInput element?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [buefy/buefy#1188]
In my `Vue.js` (`version 2.5.22`) application I use taginput element. If I have limit of 5 tags as in example below, borders dissapear when input has 5 tags.

**QUESTION**: Is it possible to change this behavior? I want to show borders.

P.S. Thank you for this wonderful library! :)

```
<b-field label="Limited to 10 characters and 5 tags">
    <b-taginput maxtags="5":value="['Red', 'Green', 'Blue', 'White']">
    </b-taginput>
</b-field>
```

**Comment by jtommy** [comment]
@NogerbekNurzhan There isn't a prop at the moment but you might add a custom class.
For example https://codepen.io/anon/pen/daovmL
