### ISSUE TITLE
Buefy Mobile card view doesn't work with iPad Air2

### ISSUE THREAD

**Issue by dipuarun** [buefy/buefy#1189]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description
Buefy Mobile card view doesn't work with iPad Air2 for both Chrome & safari.
I am getting a similar issue as of Buefy documentation site.
https://buefy.github.io/documentation/table/

### Steps to reproduce

Move to Buefy documentation tables (https://buefy.github.io/documentation/table/) in a iPad Air2 device for any browser. There are UI issues
![buefy_28](https://user-images.githubusercontent.com/12948685/51599660-316dab80-1f26-11e9-8b3e-5bec848c65e9.png)

**Comment by MRR0GERS** [comment]
Are you on the latest version of Chrome?  I checked my iPad as well as my iPhone and both devices are rendering the tables fine in Chrome, Safari and Firefox.

**Comment by dipuarun** [comment]
Are you using an iPad Air2 device ?
I have seen it is working with latest iPhones and iPads. This issue is device specific to iPad Air2 only. I think the browser is native Safari and chrome.

**Comment by jtommy** [comment]
@dipuarun Unfortunately I cannot test on that device but it's very weird especially using Chrome.

**Comment by MRR0GERS** [comment]
@jtommy I may be able to check with an iPad Air 2 at work on Monday.. I'll follow up then.

**Comment by MRR0GERS** [comment]
@dipuarun @jtommy I was able to check on an iPad Air 2 at work and found that both Chrome and Safari were displaying the tables properly.

![img_20190128_100552](https://user-images.githubusercontent.com/33129628/51845142-ef0ceb80-22e4-11e9-92af-f8cf0e0d0aa2.jpg)
![img_20190128_100608](https://user-images.githubusercontent.com/33129628/51845143-ef0ceb80-22e4-11e9-9d42-3b968efa64b8.jpg)

**Comment by jtommy** [comment]
@MRR0GERS Thanks a lot

**Comment by dipuarun** [comment]
Thank you @MRR0GERS
