### ISSUE TITLE
showDetailIcon doesn't work on b-table

### ISSUE THREAD

**Issue by flibustier** [buefy/buefy#1191]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.17]
**OS/Browser**: Firefox

### Description

I try to had a detailed table without the chevron, but when I use this code:
```
<b-table
      :style="`margin-bottom: 2${loading ? '0' : ''}0px`"
      :data="requests"
      ref="table"
      :striped="true"
      :selected.sync="selected"
      :paginated="true"
      :per-page="perPage"
      focusable
      :loading="loading"
      pagination-size="is-small"
      detailed
      detail-key="id"
      :show-detail-icon="false"
      @details-open="(row, index) => $toast.open(`expended ${row}`)"
      @select="option => $emit('select', option)"
    >
```
`:show-detail-icon="false"` doesn't work at all, nothing happens when the value is true or false, the chevron is still there…

### Expected behavior

The chevron need to be hidden with the column… 

### Actual behavior
The chevron continue to live…
![image](https://user-images.githubusercontent.com/9994935/51633327-b326fe80-1f51-11e9-8037-32feaef93148.png)

If I use `:has-detailed-visible="() => false"` the chevron disappear but not the column

By the way, in the documentation, the showDetailIcon is the only prop in camelCase instead of kebab-case

Thank you my lords!

**Comment by jtommy** [comment]
@flibustier I don't see any issues and i'm following your code, https://codepen.io/anon/pen/VgLPqd?editors=1010

**Comment by flibustier** [comment]
It seems to come from my Buefy version! My colleague solved it with the latest version of Buefy!
Thanks for your quick response !!
