### ISSUE TITLE
Problem using datepicker :date-parser

### ISSUE THREAD

**Issue by odesmet** [buefy/buefy#1193]
### Overview of the problem

**Buefy** version: [0.7.1]
**Vuejs** version: [2.5.17]
**OS/Browser**: Google Chrome

### Description

How do I parse a string "2019-01-24" to a dateformat that can be handled by the datepicker? And parse the selected date back to a string?

I'm trying with the following code, but this seems not to work

### Steps to reproduce
```
<template>
...
          <b-datepicker
            :date-formatter="(d) => {$moment(d).format('YYYY-MM-DD')}"
            :date-parser="(d) => {new Date(d)}"
            v-model="selectedDate"
            inline
            class="has-text-left"
            :first-day-of-week="1"
            :events="events"
            indicators="bars"
          ></b-datepicker>
...
</template>
<script>
export default {
...
  data() {
    return {
      selectedDate: "2019-01-24",
      ...
    }
  }
...
}
</script>
```

### Expected behavior

Give a string to the b-datepicker, and get one back

### Actual behavior

[Vue warn]: Invalid prop: type check failed for prop "value". Expected Date, got String.

**Comment by jtommy** [comment]
selectedData has to be a Date object.

**Comment by tsangaris** [comment]
@odesmet Did you find a solution for that? I am trying to populate the Buefy datepicker with Laravel/Carbon date that has the format "2019-02-01 00:00:00". Then i get the error "**Invalid prop: type check failed for prop "value". Expected Date, got String**" which is normal since i am providing a string.

I am trying to use:

`<b-datepicker
                  :date-parser="parser"
                  v-model="fields.received_date"
                  :first-day-of-week="1"
                  placeholder="DD/MM/YYYY"
                  editable>
 </b-datepicker>`

and the parser method:

`parser(d) {
      return new Date(Date.parse(d))
    },`

But nothing changes.

Any help will be much appreciated!

**Comment by jtommy** [comment]
@tsangaris The component accepts only Date object. You have to parse it from string to Date before using it as v-model.
Parser function give you the correct Date object during user date selection.

**Comment by tsangaris** [comment]
> @tsangaris The component accepts only Date object. You have to parse it from string to Date before using it as v-model.
> Parser function give you the correct Date object during user date selection.

@jtommy Thank you so much for clearing this out. It was in front of me the whole time!

For people stacking on this like me, what I did to fix it was to get the string date ("2017-06-23") and new up a new Date instance using the string:

`new Date("2017-06-23")`

then pass this into v-model.

As jtommy said, :date-parser is for when the user selects the date.
