### ISSUE TITLE
Table.vue doesn't have prop for 'is-fullwidth' 

### ISSUE THREAD

**Issue by a-vilmin** [buefy/buefy#1196]
### Overview of the problem

**Buefy** version: [^0.7.0]
**Vuejs** version: [^2.5.17]
**OS/Browser**: Firefox RHEL7

### Description
`Table.vue` has a prop for every Bulma class but `is-fullwidth`

### Expected behavior
Should be able to recreate each Bulma class but cannot pass the attribute currently to internal `tableClasses` computed value in `Table.vue`. Can easily be fixed in 2 lines of code.

**Comment by jtommy** [comment]
You're right but Buefy table is already fullwidth. Please take a look at table.scss
