### ISSUE TITLE
Pagination buttons missing icons

### ISSUE THREAD

**Issue by LarBearrr** [buefy/buefy#1198]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.17]
**OS/Browser**: Windows 10 Chrome

### Description

The pagination icons for tables are missing.

### Steps to reproduce

1. Create a new table component
2. Set the isPaginated prop to true
3. Insert the component into a page
4. Notice the missing carets for moving between pages

### Expected behavior

The pagination buttons for moving between pages should show a left and right caret/arrow.

Note: Changing the default icon pack to font awesome fixes the issue:
`Vue.use(Buefy, { defaultIconPack: 'fa'})`
### Actual behavior

![image](https://user-images.githubusercontent.com/28734844/51944092-c2d69500-23e0-11e9-8d0d-39809fb61be3.png)

**Comment by jtommy** [comment]
What font icon pack are you importing ?

**Comment by LarBearrr** [comment]
By default, Font Awesome. I thought the other packs would be included with the package.

**Comment by jtommy** [comment]
No Buefy doesn't provide any font pack

**Comment by LarBearrr** [comment]
Right on, thank you. Sorry for the confusion.

**Comment by rahulmomentum** [comment]
@LarryBarker I am facing the same issue. How did you sort out this issue? Thanks in advance.
