### ISSUE TITLE
Programmatic Child Component Instance

### ISSUE THREAD

**Issue by manofthefort** [buefy/buefy#1200]
### How to close a programmatic modal instance from the parent

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.17]
**OS/Browser**: Chrome [71.0.3578.98]

### Description

What is the best way to trigger an event on a programmatic child component instance in VueJS 2.x?

For example:
Within a Vue component, I create an instance of a programmatic modal component.  How does one close the child modal component instance from the parent?

**Parent Component (Distilled):**

	<template>
		<div>
			<p>Do some stuff...</p>
		</div>
	</template>
	<script>
		import waitModal from '../components/wait-modal'

		export default {
			name: 'parent-comp',
			methods: {
				waitModal () {
					this.$modal.open({
						parent: this,
						component: waitModal,
						hasModalCard: true,
						canCancel: false
					})
				}
			}
		}
	</script>

**Child Component:**

	<template>
		<div class="modal-card">
			
			<header class="modal-card-head center-content">
				<h3 class="modal-card-title">{{waitHeader}}</h3>
			</header>
			
			<section class="modal-card-body">
				<div class="center-content margin-bottom">
					<font-awesome-icon class="fa-spin" :icon="['fas', 'circle-notch']"></font-awesome-icon>
				</div>
			</section>
		</div>
	</template>

	<script>
		import { mapState } from 'vuex'

		export default {
			name: 'wait-modal',
			computed: {
				...mapState({
					waitHeader: 'waitHeader'
				})
			},
			methods: {
				closeModal () {
					this.$emit('close')
				}
			}
		}
	</script>

**Comment by jtommy** [comment]
@manofthefort You have to add `events` prop when you call `open` method, for example:
```
this.$modal.open({
  parent: this,
  component: waitModal,
  hasModalCard: true,
  canCancel: false,
  events: {
    close: function() { .... }
  }
})
```

**Comment by manofthefort** [comment]
@jtommy  Per the documentation, that occurs after the event has already been triggered.  I am needing to trigger the event from the parent.

https://buefy.github.io/documentation/modal

![image](https://user-images.githubusercontent.com/5873908/52015562-457a5580-24b0-11e9-939b-429c173cd1ae.png)

**Comment by jtommy** [comment]
I don't understand your question. What do you wanto to do ?

**Comment by manofthefort** [comment]
The parent component opens a child modal component.  Then the parent calls a Vuex action and I want the parent to close the child modal when the promise is resolved.

**Comment by jtommy** [comment]
`open` method return an instance of modal component then you might call `close` method, for example:
```
this.modal = this.$modal.open({
  parent: this,
  component: waitModal,
  hasModalCard: true,
  canCancel: false
})
...
this.modal.close()
```

**Comment by manofthefort** [comment]
That worked, thank you.  I was over complicating it.
