### ISSUE TITLE
Add icon to end of table columns

### ISSUE THREAD

**Issue by LarBearrr** [buefy/buefy#1201]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [0.7.2]
**OS/Browser**: Windows 10 Chrome

### Description

Would like to be able to add custom header to table without adding an entire column.

### Steps to reproduce

Following the documentation, it is possible to modify the column header values:
```
<template slot-scope="props" slot="header">
       <b-icon v-if="props.column.field === 'user.first_name'" pack="fa" icon="user"></b-icon>
{{props.column.label}}
</template>
```

However, I do not see a way to slot in a custom header without adding an entire column.

### Expected behavior

![image](https://user-images.githubusercontent.com/28734844/52009117-bc572480-2497-11e9-91bc-e46b8200d8e4.png)

Clicking this icon would then open a modal to allow the user to configure the list dynamically (set records per page, hide/show columns, etc.)

### Actual behavior

N/A

**Comment by jtommy** [comment]
@LarBearrr At the moment `header` slot it's only a way to customize the column header and you have add an "empty" column.
