### ISSUE TITLE
Icons on my page disappear when toast disappears.

### ISSUE THREAD

**Issue by anzemur** [buefy/buefy#1202]
### Description

I trigger a toast with some info message. I used the same syntax as in provided example in the documantation to show toast message. Toast shows and everything works great, but then toast disappears and when it does,  all of the icons on the page disappear too. I use [Buefy Material Design Icons](https://buefy.github.io/documentation/icon).

### Steps to reproduce

1.  Have some icons in your components/view.
2. Open toast the same way that is shown in [example](https://buefy.github.io/documentation/toast).
3. Watch the icon disappear when the toast closes.

### Expected behavior

Icons should not disapperar.

### Actual behavior

Icons dissapear and come back when I click on some button or refresh the page.

**Comment by jtommy** [comment]
Could provide an example using codepen or your repository?

**Comment by anzemur** [comment]
I cannot provide repository and I couldn't replicate this problem in a codepen. The problem is still there and it happens too if I open Buefy's dialog.

**Comment by anzemur** [comment]
I found out that it canceles all of the ::before classes.

**Comment by chrislaive** [comment]
@anzemur did you fix it?

**Comment by anzemur** [comment]
@chrislaive No, sadly I couldn't find the way to fix it. I used another package for showing toasts and it worked fine.

**Comment by jtommy** [comment]
Unfortunately I cannot replicate it. @chrislaive are you using Nuxt ?

**Comment by chrislaive** [comment]
@jtommy Yes, I'm using nuxt. I also can not replicate it in sandbox but the problem is the same, when the toast disappears it removes the :: before inside the icons and these disappear

**Comment by imfaber** [comment]
I can confirm the issue using nuxt.
Also, it happens when I open toasts/dialogs. It doesn't matter what you press after opening because the icons are already gone

**Comment by imfaber** [comment]
An update on this...

It turned out that in my case I was misusing vue-meta and the `head` method.  
Basically it was wiping all the head section including the material design CSS and all the other meta tags injected by nuxt.

Not sure why that would happen only when dialogs get opened. 
Could it have to do with the fact that the dialog is appended out the nuxt root element `<div id="__nuxt">`?

Would it be worth adding a prop to dialogs, notifications etc. (and anything that gets appended to the body) to control where to append the new elements?

**Comment by kuzne** [comment]
+1

**Comment by DonNicoJs** [comment]
@imfaber @kuzne and for anyone else having this problem.
This issue is known in other frameworks too with vue-meta.

This snipet of code it's the suggested workaround

https://github.com/ElemeFE/element/issues/4207#issuecomment-462612793

```
export default function watchTitle () {
  let isRefreshing = false;

  const observer = new MutationObserver(function (mutations) {
    const newValue = mutations[0].target.nodeValue;
    if (newValue || isRefreshing) {
      isRefreshing = false;
      return;
    }
    isRefreshing = true;
    $nuxt.$meta().refresh();
  });

  const target = document.querySelector('head > title');
  const config = { subtree: true, characterData: true, childList: true };
  observer.observe(target, config);
}
```
