### ISSUE TITLE
Readonly tags shouldn't be removable

### ISSUE THREAD

**Issue by szmarczak** [buefy/buefy#1203]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.5.22
**OS/Browser**: Chrome/71.0.3578.98 (Windows 10)

### Steps to reproduce

https://codepen.io/anon/pen/omZVWo

### Expected behavior

Immutable tags.

### Actual behavior

New tags aren't accepted, but other tags can be removed.

**Comment by jtommy** [comment]
@szmarczak There is `closeable` prop, you have to set it to false.

**Comment by szmarczak** [comment]
That's an anti-pattern, not a solution.

**Comment by jtommy** [comment]
Why? read-only it's for input or autocomplete not for the tags

**Comment by jtommy** [comment]
Yes but using a different props you can have multiple ways to use it.
I think I'll update docs, thanks
