### ISSUE TITLE
Autocomplete data object vs array

### ISSUE THREAD

**Issue by LarBearrr** [buefy/buefy#1204]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [0.7.2]
**OS/Browser**: Windows 10 Chrome

### Description
I am using a PHP controller to pass options to my autocomplete component wrapper. I won't get into the details of why or how to save space and time. Anyhow, I am able to successfully pass the variable, but I am concerned about the values and keys. Here is an example of the options:

```
'options' => [
    'draft' => 'Draft',
    'published' => 'Published',
    'archived' => 'Archived',
]
```
I then pass this to the component like so:
`<my-autocomplete :items='<?php echo json_encode($fieldOptions); ?>'></my-autocomplete>`

Which will render:
![image](https://user-images.githubusercontent.com/28734844/52151980-725a7400-263a-11e9-9b7a-9a219d86fe75.png)

Inspecting the Vue component shows these values:
![image](https://user-images.githubusercontent.com/28734844/52152081-cbc2a300-263a-11e9-9f05-9f49d30e845c.png)

### Steps to reproduce

1. Create a custom Autocomplete wrapper:
```
<template>
    <section>
        <b-autocomplete
            rounded
            v-model="name"
            :data="filteredDataArray"
            field="title"
            placeholder="e.g. Draft"
            icon="magnify"
            @select="option => selected = option">
            <template slot="empty">No results found...</template>
        </b-autocomplete>
    </section>
</template>

<script>
    export default {
        props: {
            items: [Array, Object]
        },
        data() {
            return {
                data: this.items,
                name: '',
                selected: null
            }
        },
        computed: {
            filteredDataArray() {
                const arrayOfObjects =  Object.keys(this.items).map((key) => {
                    return this.items[key]
                })

                return arrayOfObjects.filter((option) => {
                    return option
                        .toString()
                        .toLowerCase()
                        .indexOf(this.name.toLowerCase()) >= 0
                })
            }
        }
    }
</script>

2. Return an array object from a PHP controller such that:
    `$options = ['go'=>'Green','slow'=>'Yellow','stop'=>'Red']`

3. Inject the custom wrapper into a php page like so:
   `<my-autocomplete :items='<?php echo json_encode($options); ?>'></my-autocomplete>


### Expected behavior

Ideally, this will be used as part of a form submission. In these situations, the preferred key to be submitted would be the custom key (i.e. go, slow, stop or draft, published, archived) so that is what will be stored in the database column for the field. 

### Actual behavior

I'm concerned that the actual value that will be stored will be the index/key (i.e. 0, 1, 2, ...)

**Comment by jtommy** [comment]
You should use a simple string array or an array of objects with the same structure, for example { value: "draft", label: "Draft" }

**Comment by LarBearrr** [comment]
Is that possible from the PHP controller?

**Comment by jtommy** [comment]
I think it's a simple an array of class that contains value and label field or you might create it in your Vue/JavaScript code before using it as data prop

**Comment by LarBearrr** [comment]
@jtommy How can I set the autocomplete value to the index of the selected item instead of the value? 
![image](https://user-images.githubusercontent.com/28734844/52866648-bd798a00-3104-11e9-97fd-b1a5e49bf4d2.png)
![image](https://user-images.githubusercontent.com/28734844/52866717-e26dfd00-3104-11e9-8b37-7981d9c820ac.png)
![image](https://user-images.githubusercontent.com/28734844/52866833-26610200-3105-11e9-9f8d-500f4fc4c31c.png)

Note, I need the original index of the selected item, not the index after it has been filtered as this would always return 0.

**Comment by LarBearrr** [comment]
> You should use a simple string array or an array of objects with the same structure, for example { value: "draft", label: "Draft" }

What I'm not understanding is how to bind the actual field value to the field. I need the label to be displayed and searchable while maintaining the value (index, key, etc.) to be stored in the database. 

I've managed to get an array of objects from the backend, and how the value (i.e. index) is showing up in the options instead of the label:

![image](https://user-images.githubusercontent.com/28734844/52880017-6be1f700-3126-11e9-8f55-8655012a004d.png)

The database field represented here is an integer reference for a relationship so I cannot store the actual label value in the database. I need to store the ID. 

Any further assistance is greatly appreciated! Thank you.

**Comment by yxngl** [comment]
See "Object array" example in autocomplete documentation. The "Selected" shows a complex data structure underneath. But the example just uses `user.first_name` both in `field` for display, and also the key for filtering/autocomplete in `filteredDataObj`.

All these could be different keys in the objects in the array. You could create something just for displaying as the label and use something else for autocomplete or eventually storing in the database. Depending on the type of data fetched and needed for saving, say you simply get array ['Draft', 'Published', 'Archived']. It could be preprocessed into:
```
[
  {
    "label": "0: Draft",
    "index": 0,
    "value": "Draft"
  },
  ...
]
```
While label is fed to `field` for display, value used for autocomplete, and maybe index for persistence, for example.

**Comment by LarBearrr** [comment]
@yxngl Thank you for the reply. Here is an example of the object string I am sending to the component:
`"[{"id":1,"value":"Corporate","desc":"Corporate user accounts."},{"id":2,"value":"Distributorship","desc":"Distributorship accounts."}]"`

I'm still not seeing how to actually change the value of what is submitted with the form since `v-model` is the bound value that is being submitted?

**Comment by yxngl** [comment]
v-model binds to text in the text field (usually just what is being typed in) and you can see it is used for filtering. Refer to the example I mentioned above, which has a @select event handler for getting the selected object.

**Comment by LarBearrr** [comment]
I guess I'm completely inept at basic Vue/JS because I can't seem to follow along. I can either get the ID or the Label to be searchable, but I cannot seem to display the label and submit the ID. I should maybe mention I am not submitting the form with Vue, but through a basic <form> element. 

I have managed to work around this by including a hidden field for the time being and using a watcher to get the index of the selected value from my data array/object. 

One last example:

Here is the JSON object string I am sending to the component:
`"{"1":"Corporate","2":"Distributorship"}"`

and my component:
```
<template>
<div>
    <b-autocomplete
        v-model="name"
        :data="filteredDataArray"
        :placeholder="emptyOption"
        icon="search"
        :open-on-focus="true"
        @select="option => selected = option">
        <template slot="header">
            <a @click="showAddNew">
                <span> Add new... </span>
            </a>
        </template>
        <template slot="empty">No results for {{name}}</template>
    </b-autocomplete>
    <input type="hidden" :value="this.value" :name="fieldName">
</div>
</template>

<script>
    export default {
        props: {
            fieldName: String,
            items: [Array, Object],
            emptyOption: {
                type: String,
                default: 'Select an option...'
            }
        },
        data() {
            return {
                data: this.items,
                name: '',
                selected: null,
                value: null,
            }
        },
        computed: {
            filteredDataArray() {
                const arrayOfObjects =  Object.keys(this.items).map((key) => {
                    return this.items[key]
                })
                return arrayOfObjects.filter((option) => {
                    return option
                        .toString()
                        .toLowerCase()
                        .indexOf(this.name.toLowerCase()) >= 0
                })
            }
        },
        methods: {
            showAddNew() {
                this.$dialog.prompt({
                    message: `New item`,
                    inputAttrs: {
                        placeholder: 'e.g. Pending',
                        maxlength: 20,
                        value: this.name
                    },
                    confirmText: 'Add',
                    onConfirm: (value) => {
                        this.data.push(value)
                        this.$refs.autocomplete.setSelected(value)
                    }
                })
            }
        },
        watch: {
            selected: function (newSelected) {
                this.value = Object.keys(this.items).find(key => this.items[key] === newSelected)
            }
        },
    }
</script>
```

![image](https://user-images.githubusercontent.com/28734844/52885553-3d204c80-3137-11e9-952d-02dbeea62774.png)

![image](https://user-images.githubusercontent.com/28734844/52885582-532e0d00-3137-11e9-8ce6-ac6d8fd03931.png)

**Comment by yxngl** [comment]
Form submission is fine. Your current approach may work practically. The watch is not needed though, and the function watching `selected` can be defined in methods and directly assigned to `@select` event handler in b-autocomplete.

Because the data is converted to a plain array to pass to b-autocomplete, that is why you said you can only get ID or label and have to use an extra step to find the ID based on label. The header for adding new items is broken but probably a step further.

We were basically talking about using one attribute in the object as the searchable label and set the other to the value of your hidden input.

Your `arrayOfObjects` should be converted like `[{"id": 1, "label": "Corporate"}, {"id": 2, "label": "Distributorship"}]`. Then field prop in b-autocomplete would be "label" and filteredDataArray needs to be modified accordingly. `@select` in b-autocomplete would be `option => value = option.id`.
