### ISSUE TITLE
Invalid `type` attribute when using <b-input> and v-else-if

### ISSUE THREAD

**Issue by szmarczak** [buefy/buefy#1205]
**Buefy** version: 0.7.2
**Vuejs** version: 2.5.22
**OS/Browser**: Chrome/71.0.3578.98 (Windows 10)

### Steps to reproduce

https://codepen.io/anon/pen/qgjbRY

### Expected behavior

The `type` attribute of `input` should be `number` after changing `$data.type` to `number`.

### Actual behavior

The `type` attribute of `input` is still `textarea` after changing `$data.type` to `number`.

**Comment by oldcastor** [comment]
In this case its a Vue things. Check [this](https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key). You need to add a unique `key` attribute to every control that needs to be excluded from reusing.
Code taken from link above 
```html
<template v-if="loginType === 'username'">
  <label>Username</label>
  <input placeholder="Enter your username" key="username-input">
</template>
<template v-else>
  <label>Email</label>
  <input placeholder="Enter your email address" key="email-input">
</template>
```

**Comment by szmarczak** [comment]
Hmm, Interesting. I tried it with different tags and it worked fine...
