### ISSUE TITLE
How to show empty slot on autocomplete only when the data from api is fetched?

### ISSUE THREAD

**Issue by notabc** [buefy/buefy#1207]
### Description
Empty slot on autocomplete component is displayed while typing, but the data is not fetched yet, but might be available in returned response.

### Steps to reproduce
1. Go to https://codepen.io/anon/pen/pGwRZz
2. Start typing 'movie'.
3. 'No results found' will be displayed while we typing.
4. Api returned response and we got a list of movies, but moment ago message was 'No results found'.

### My attempt to fix that
https://codepen.io/anon/pen/PVjpYV

I added new variable `fetched: false` and set it to true when i get the data. Then i added `v-if="fetched"` for empty slot.  Now empty slot is not displayed when typing, but if we got no data from api, empty slot is hidden (maybe mistake in v-if).
  
### Expected behavior
Empty slot should be displayed only when the data is fetched and is empty, not while we still typing.

### Actual behavior
![autocomplete](https://user-images.githubusercontent.com/31017698/52185527-a7c0b680-2820-11e9-86ee-91e525776a95.gif)

**Comment by oldcastor** [comment]
https://codepen.io/anon/pen/PVjpYV
Try change empty slot block like this 

```html
<template slot="empty">
  <div v-if="fetched">No results found</div>
  <div v-else>Searching...</div>
</template>
```
