### ISSUE TITLE
Buefy table sortable and visible

### ISSUE THREAD

**Issue by kennethdu** [buefy/buefy#1208]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.21]
**OS/Browser*Google Chrome*:

### Description

Table should be able to toggle and sortable through column properties (boolean)

### Expected behavior

The columns should be able hide/show and be able to sort ascending and descending order

### Actual behavior

Sortable property does not toggle boolean

### Example Code

 ```
<template slot-scope="props">
              <b-table-column
                v-for="(column, index) in columns"
                :key="index"
                :label="column.title"
                :visible="column.visible"
                :sortable="column.sortable"
              >{{ props.row[column.field] }}</b-table-column>
</template>
```
Column Template Code

 `{ title: 'Name', field: 'name', visible: true, sortable: true }`

**Comment by jtommy** [comment]
@kennethdu I don't understand your issue. Sortable and visible are reactive prop and you can show/hide a column as you want

**Comment by kennethdu** [comment]
@jtommy Yes, you can show/hide, but I am unable to show/hide + make my tables sortable. The issue I am facing is doing a combination of both of those, sorry for the confusion

**Comment by jtommy** [comment]
Could you provide a full example?

**Comment by kennethdu** [comment]
HTML

```
   <template slot-scope="props">
              <b-table-column
                v-for="(column, index) in columns"
                :key="index"
                :label="column.title"
                :visible="column.visible"
                :sortable="column.sortable"
              >{{ props.row[column.field] }}</b-table-column>

```

Javascript

```
 data () {
    return {
      tableLoading: false,
      paginationAmount: 50,
      allMmes: [],
      columns: [
        { title: 'Name', field: 'name', visible: true, sortable: true },
        { title: 'License', field: 'code', visible: true, sortable: true },
        { title: 'Ubi', field: 'ubi', visible: true, sortable: true },
        { title: 'Global Id', field: 'globalId', visible: true, sortable: true },
        { title: 'MME TYPE', field: 'mmeType', visible: true, sortable: true },
        { title: 'Address', field: 'address1', visible: true, sortable: true },
        { title: 'City', field: 'city', visible: true, sortable: true },
        { title: 'Zip', field: 'postalCode', visible: true, sortable: true },
        { title: 'Phone', field: 'phone', visible: true, sortable: true }
      ]
    }
  }
```

**Comment by kennethdu** [comment]
Here is a code pen that follows the same Buefy example, this is probably a better full example

[https://codepen.io/anon/pen/JxOJox?editors=1010](url)

**Comment by jtommy** [comment]
@kennethdu You have to add `:field="column.field"` to `bTableColumn` otherwise the component doesn't know the field of your data
