### ISSUE TITLE
B-field and b-input not redering on IE

### ISSUE THREAD

**Issue by vinodMS** [buefy/buefy#1209]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.6.0]
**OS/Browser**: IE 11

### Description

Creating a form using Buefy's b-input and b-field results in a empty/broken form. I read a related post, where there was a solution to this problem using bluebirdjs. Should I be using it myself or is it already part of Buefy package?
I am currently using buefy as stadalone. 
`<script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>`

### Steps to reproduce

Here is the sample code,
```
<b-field label="{{ form.email.label.text }}">
	<b-input id="{{ form.email.id }}"
		 name="{{ form.email.name }}"
		 type="email"
		 autofocus=''
		 size="is-large"
		 pattern="{{ form.email.render_kw.pattern }}"
		 oninvalid="setCustomValidity('{{ form.email.render_kw.oninvalid }}')"
		 oninput="setCustomValidity('')"
		 title="{{ form.email.render_kw.placeholder }}"
		 placeholder="{{ form.email.render_kw.placeholder }}"
		 required>
	</b-input>
</b-field>
```

### Expected behaviour

Preview on Chrome/Brave browser
<img width="453" alt="screenshot 2019-02-04 at 21 44 02" src="https://user-images.githubusercontent.com/2227036/52236037-03914b00-28c6-11e9-9b61-61a4636c144f.png">

### Actual behavior

Preview on IE11
<img width="375" alt="screenshot 2019-02-04 at 21 43 19" src="https://user-images.githubusercontent.com/2227036/52235995-e9f00380-28c5-11e9-9b74-af2d040d6767.png">

**Comment by jtommy** [comment]
@vinodMS The official docs website works well on IE11 and i just tried your code and it's ok

**Comment by vinodMS** [comment]
@jtommy I figured out that the issue was unrelated to Buefy or Vue. It's my own Vue js code that had a problem in IE. I was able to fix this using babel with polyfill.
