### ISSUE TITLE
Discrepancy between state data and rendered view in b-table with dynamic indices

### ISSUE THREAD

**Issue by jvalle** [buefy/buefy#1211]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.5.17
**OS/Browser**:

### Description

[`src/components/Table.vue:65` ](https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L65)

Table component uses `index` as key for `tr`.  When used in conjunction with [sortablejs](https://buefy.github.io/extensions/sortablejs/), this makes the `index` a dynamic property. If the indices are re-ordered, and a re-render is triggered, this results in a discrepancy between state data, and what is rendered, specifically, the correct order of the array in the sorted table.

### Steps to reproduce

1. Set up a b-table with some functionality that allows re-ordering of the table entries by way of mutating the `data` array indices.
2. Re-order table entries and observe correct order in rendered template.
3. Trigger a re-render by way of local state data update.
4. Observe table entries incorrectly reverted to original order.

### Expected behavior

Expect `tr` to use a static, unique property as a key.

### Actual behavior

`tr` uses dynamic index as key leading to discrepancy between state data array, and rendered template.

If deemed a legitimate bug, I'd be happy to pursue a solution. Cheers.

**Comment by amandaporto** [comment]
Running into the same issue - glad to know there is a PR open for it. Hope it doesnt take long to get it merged.

**Comment by jtommy** [comment]
I'm going to merge it but I'm thinking if only a row field is enough as key.
