### ISSUE TITLE
Timepicker increment-minutes works wrong

### ISSUE THREAD

**Issue by kasperkamperman** [buefy/buefy#1214]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.6.2]
**OS/Browser**: Chrome 71 / Safari 12.0.3 MacOS 10.12

### Description

The increment-minutes doesn't work. I think the screenshot shows the problem clearly. In this
one I used ```increment-minutes="2"```

<img width="239" alt="screen shot 2019-02-07 at 08 15 29" src="https://user-images.githubusercontent.com/1760616/52396069-ae655d00-2ab0-11e9-99ec-2ae09a81a56a.png">

### Steps to reproduce

Just add the timepicker component:
```
  <b-field label="Select timepicker">
        <b-timepicker
            placeholder="Type or select a date..."
            icon="clock"
            increment-minutes="2"
            editable>
        </b-timepicker>
    </b-field>
```

I've tested also like: `increment-minutes=2` however it gives the same result.

### Expected behavior

To see something like 00, 02, 04, 06, 08, 10, 12, ...

### Actual behavior

I see 00, 002, 022.

**Comment by jtommy** [comment]
@kasperkamperman You are using a string prop while the component accepts only number.
You have to change your code from `increment-minutes="2"` to `:increment-minutes="2"`
