### ISSUE TITLE
b-autocomplete search results don't display

### ISSUE THREAD

**Issue by SSebigo** [buefy/buefy#1215]
### Overview of the problem
I use b-autocomplete tag for an Electron + Vue application. Issue is that the results' dropdown doesn't show.

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.16]
**OS/Browser**: Windows 10/Electron 4.0.4 (Chromium 69)

### Description

I use an api to retrieve data as shown on Buefy website, interesting thing is that b-autocomplete actually work but doesn't display the results in a dropdown like it does on the website in fact it doesn't display any result.

Even when using the first and simplest example on the website I have the same issue.

After twitching some things I've found that if I had the Bulma class 'dropdown' to 'dropdown-content' in Electron inspector, results' dropdown magically appears.

Before:
![buefy1](https://user-images.githubusercontent.com/25211395/52420340-30c24100-2af2-11e9-84e4-c96661ffee23.PNG)
![buefy2](https://user-images.githubusercontent.com/25211395/52420420-551e1d80-2af2-11e9-8440-19933c5ef9d8.PNG)

After:
![buefy3](https://user-images.githubusercontent.com/25211395/52420371-43d51100-2af2-11e9-958a-b5ff32007cae.PNG)
![buefy4](https://user-images.githubusercontent.com/25211395/52420436-5c452b80-2af2-11e9-82a0-0d0dba7bbd10.PNG)

### Steps to reproduce

1. Use Electron-vue boilerplate to initialize an Electron + Vue project
2. Copy+Past Buefy b-autocomplete first example (website) in any disponible component

3. Now open element inspector and add .dropdown to .dropdown-content element for the dropdown to appear.

### Expected behavior

![buefy4](https://user-images.githubusercontent.com/25211395/52420436-5c452b80-2af2-11e9-82a0-0d0dba7bbd10.PNG)
I expect a dropdown with results to appear.
### Actual behavior

![buefy2](https://user-images.githubusercontent.com/25211395/52420420-551e1d80-2af2-11e9-8440-19933c5ef9d8.PNG)
There's no dropdown appearing.

**Comment by jtommy** [comment]
@SSebigo Where are you adding the autocomplete ? Modal, tabs, table ?

**Comment by SSebigo** [comment]
Sorry, should have closed the issue.
Turned out that there was a problem with my node modules.
It works now, I removed and reinstalled the package a few times.

**Comment by gsvavarsson** [comment]
I'm having the same problem.
@SSebigo did you only remove and reinstall the package a few times or did you rollback on anything?
