### ISSUE TITLE
Upload component, reset and v-model

### ISSUE THREAD

**Issue by jlebras** [buefy/buefy#1216]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.17]
**OS/Browser**: Archlinux/Chromium

### Description

I use the upload component with html5 validation, a v-model binding and the required attribute.

When a file is already added, if I open again the file explorer but cancel the selection, the field is considered invalid (as per the html5 validation), but the model value do not change, it is still the last selected file.

So the form is in a weird state where the field is invalid but the filename is still displayed (in my template) because the model value contains the last selected file.

### Steps to reproduce

1. Use an upload component with v-model and required attributes
2. Select a first file
3. Open the file explorer again but cancel the selection

### Expected behavior

When I cancel the file selection, the field is considered invalid and the model value is reset.

### Actual behavior

When I cancel the file selection, the field is considered invalid and the model value is not changed.

**Comment by yxngl** [comment]
It seems the fix only works in Chrome.

**Comment by jtommy** [comment]
Firefox doesn't emit an event when you click on cancel
