### ISSUE TITLE
How to style loading component?

### ISSUE THREAD

**Issue by syahnur197** [buefy/buefy#1217]
please help, dont see any where in the documentation on how to style it

**Comment by evilandfox** [comment]
I recommend to learn sources (https://github.com/buefy/buefy/tree/dev/src/components/loading and https://github.com/buefy/buefy/blob/dev/src/scss/components/_loading.scss), then decide to style component by rewriting styles (https://buefy.github.io/documentation/customization) or forking this repo for fully customize
