### ISSUE TITLE
Infinite update loop when accessing an object or array "meta" prop defined on a BTableColumn

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#1222]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.6.4
**OS/Browser**: any

### Description

Attempting to access an object or array `meta` prop defined on a `BTableColumn` results in an infinite Vue update loop.

### Steps to reproduce

Minimal working example (`meta` prop defined on a column and accessed in the `header` slot):

```
<script>
export default {
    data() {
        return {
            myData: [
                { value: 'A' },
                { value: 'B' },
                { value: 'C' }
            ]
        }
    }
}
</script>

<template>
    <b-table :data="myData">

        <template v-slot="{ row }">
            <!-- Meta prop defined here -->
            <b-table-column field="value" label="Value" :meta="{ someProperty: 5 }">
                {{ row.value }}
            </b-table-column>
        </template>

        <template v-slot:header="{ column }">
            <!-- Accessing column.meta generates the loop -->
            {{ column.meta.someProperty }} <!-- Removing this line removes the loop -->
            {{ column.label }}
        </template>

    </b-table>
</template>
```

### Actual behavior

Vue's loop detection forcefully terminates the loop after 200 iterations and prints the following:

```
You may have an infinite update loop in a component render function.

found in

---> <BTable>
       <Test> at src/Test.vue
       [...]
```

The loop can potentially break other stuff; I noticed the problem after the table's pagination suddenly stopped working.

**Comment by alphabravo8** [comment]
Any idea on how to fix? I met the exact same issue

**Comment by jtommy** [comment]
@tecaz I have to investigate more but you shouldn't create meta into template.
Try using a component data or a row field

**Comment by jtommy** [comment]
Did you try the new header slot in table column component?

**Comment by deeDude** [comment]
> @tecaz I have to investigate more but you shouldn't create meta into template.
> Try using a component data or a row field

Can you explain why cant we use  the meta property when the docs state "Meta prop to add anything, useful when creating custom headers"???

**Comment by jtommy** [comment]
It works using the "new" header slot of table column. Please, take a look at the docs.
