### ISSUE TITLE
Custom switch values affecting native value

### ISSUE THREAD

**Issue by LarBearrr** [buefy/buefy#1223]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [0.7.2]
**OS/Browser**:

### Description

When trying to use custom switch values for true/false, I'm having trouble maintaining a boolean value such as 0/1 when submitting the form. 

The reason is that I am using a wrapper that allows for custom true/false values. For example, one instance of the switch may use Yes/No for these values while another uses On/Off.

When trying to compute the native value, it is problematic that the native value of the field is changed to the corresponding true/false values when it would be better to use those values as a display value only while maintaining a 0/1 native value for processing on the backend.

### Steps to reproduce

1. Create a wrapper component with the following code:
```
<template>
<b-switch
    true-value="Yes"
    false-value="No"
    v-model="isSwitched"
    :native-value="realValue"
    :name="name">
    {{ isSwitched }}
</b-switch>
</template>

<script>
export default {
    props: {
        name: String,
        checked: Boolean
    },
    data() {
        return {
            isSwitched: this.checked,
            realValue: 0
        }
    },
    watch: {
        isSwitched() {
            this.realValue = this.isSwitched == true ? 1 : 0;
        }
    }
}
</script>
```

 

### Expected behavior

It would be preferable for the field label/display value to show the true/false values while maintaining a 0/1 native value in some way. Rather than overriding the bound model to the true/false value, maintain true/false so that the native value can be computed/watched based on an expected value while labeling the field with the true/false values.

### Actual behavior

2. See that the default display value is `false` per the `isSwitched` watcher:
![image](https://user-images.githubusercontent.com/28734844/52568046-56da3080-2dd3-11e9-84e1-6edd71a6b144.png)
3. See that the `value` of the field is `false`:
![image](https://user-images.githubusercontent.com/28734844/52568074-68bbd380-2dd3-11e9-9c43-c82ed292bb23.png)
4. Switch the field and notice that the display value updates to the true-value of `Yes` while also changing the value of the field to 'Yes' and the native value remains unchanged because of the watcher:
![image](https://user-images.githubusercontent.com/28734844/52568302-fdbecc80-2dd3-11e9-87c5-ae4337745d2e.png)
![image](https://user-images.githubusercontent.com/28734844/52568314-044d4400-2dd4-11e9-8b35-aea857d84efa.png)

It seems that the true/false values override the bound model. This makes it difficult/impossible to watch for custom true/false values because you may not know what the value will be. Think of localization or whatnot.

**Comment by jtommy** [comment]
@LarBearrr Why don't you use 1 and 0 as `true-value` and `false-value` ?
For example: 
```
<b-switch
    :true-value="1"
    :false-value="0"
    v-model="isSwitched"
    :name="name">
    {{ isSwitched === 1 ? 'Yes' : 'No'}}
</b-switch>
```

**Comment by LarBearrr** [comment]
Very interesting idea. Let me see if I can get it to work properly. Thank you for the quick reply.

**Comment by LarBearrr** [comment]
Ok, I think I got it figured out for the most part. My implementation still seems a bit bloated but it seems to be working:
```
<template>
<b-switch
    true-value="1"
    false-value="0"
    v-model="isSwitched"
    :native-value="realValue"
    :name="name">
    {{ realValue === 1 ? this.customTrue : this.customFalse }}
</b-switch>
</template>

<script>
export default {
    props: {
        name: String,
        checked: Boolean,
        customTrue: String,
        customFalse: String
    },
    data() {
        return {
            isSwitched: this.checked == true ? 1 : 0,
            realValue: this.checked == true ? 1 : 0
        }
    },
    watch: {
        isSwitched() {
            this.realValue = this.isSwitched == 1 ? 1 : 0;
        }
    }
}
</script>
```

Now I can pass in custom true/false values:
```
<custom-switch custom-true="On" custom-false="Off"></custom-switch>
or
<custom-switch custom-true="Yes" custom-false="No"></custom-switch>
etc.
```
