### ISSUE TITLE
b-autocomplete focus method won't open dropdown in vue 2.6.*

### ISSUE THREAD

**Issue by TMantas** [buefy/buefy#1224]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.6.5]
**OS/Browser**: any (most likely) - tested with firefox, chrome and safari in MacOS

### Description

After upgradint to vue 2.6.* I noticed that focus method only triggers focus on autocomplete input but won't show the dropdown. It worked fine with vue 2.5.*

### Steps to reproduce

1. open [codepen](https://codepen.io/mantas-t/pen/pGVadG)
2. click on button (with chevron)

### Expected behavior

Dropdown should open.
Working version in vue 2.5.22: [codepen](https://codepen.io/mantas-t/pen/xMjYYZ)

### Actual behavior

Focuses on input but won't open dropdown

**Comment by oldcastor** [comment]
Looks like here is the problem
![vue2 6 target](https://user-images.githubusercontent.com/21212418/52626096-22da3a80-2ebb-11e9-8af4-6ffa5b86e590.png)

I must notice that with vue 2.5 `@click` performs same as `@click.prevent` and `@click.stop`.
As a workaround you can use `@click.stop` - in this case autocomplete works as expected.

**Comment by jtommy** [comment]
@oldcastor thanks

**Comment by agm1984** [comment]
I was initially confused by where this thread ended up, but I can confirm that as of today with Vue 2.6+ and Buefy 0.8.3~ that `@click.stop` both works and is required.

To illustrate, given:

``` javascript
<b-autocomplete
    ref="autocompleteInput"
></b-autocomplete>
```

If you want to programmatically open the dropdown:

``` javascript
<button type="button" @click.stop="$refs.autocompleteInput.focus()">
    Open it
</button>
```

Here is a more qualified example:

``` javascript
<div class="flex flex-row">
    <b-autocomplete
        ref="autocompleteInput"
        open-on-focus
    ></b-autocomplete>

    <p class="control">
        <button class="button" type="button" @click.stop="$refs.autocompleteInput.focus()">
            <b-icon icon="chevron-down" type="is-primary"></b-icon>
        </button>
    </p>
</div>
```

**Note** that if BAutocomplete's `data` prop is empty, such as `<b-autocomplete :data="[]">`, the dropdown will not appear because there is no list to render in it.

**Comment by andresespinosapc** [comment]
I'm trying to open the dropdown again on select event but it's not working. In this case I'm not using a button, so this wokaround doesn't work.
