### ISSUE TITLE
b-field message and addon styling

### ISSUE THREAD

**Issue by TMantas** [buefy/buefy#1226]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.5.*]
**OS/Browser**: 

### Description

The styling of `b-field` breaks when using message prop and addon next to input. 

### Steps to reproduce

1. Create b-field
2. Add any input and .control next to it
3. Add `message` prop with some value

### Expected behavior

The message will be displayed in next line. And border radius should stay.

### [Codepen examples](https://codepen.io/mantas-t/pen/GzGRWX)

This issue is very similar to #506 but in that case (when using nested `b-field`) the inner `b-field` will keep margin bottom and so the message will be displayed incorrectly.

**Comment by service-paradis** [comment]
This is kind of broken using Bulma only also...

This is a hack i found while playing around with your pen and checking Bulma doc:
```
<b-field message="nested b-fields (note margin-bottom)">
  <div class="field-body">
    <b-field>
      <b-input placeholder="Search..." type="search" icon="magnify">
      </b-input>
      <p class="control">
        <button class="button is-primary">Search</button>
      </p>
    </b-field>
  </div>
</b-field>
```

Wrapping the inner fild with a `<div class="field-body">` will reset the `margin-bottom`.

**Comment by zedrdave** [comment]
Sorry to reopen this topic, but for form validation purposes we need to have a way to force the message below the b-field, even when it has add-ons.

The fix suggested above only works if the message is statically created and not related to the control's validation…
