### ISSUE TITLE
Feature request: Default options for Buefy methods

### ISSUE THREAD

**Issue by ffxsam** [buefy/buefy#1229]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.6.4
**OS/Browser**: Chrome 72

### Description

It would be great if Snackbar (and other similar components that have properties attached to the Vue instance) could be given default values. E.g.:

```js
Vue.prototype.$snackbar.defaults = {
  position: 'is-top',
};
```

Currently I'm working around this by defining my own property:

```ts
Vue.prototype.$msg = {
  open: (options: SnackbarConfig) =>
    Vue.prototype.$snackbar.open({
      actionText: null,
      position: 'is-top',
      queue: false,
      ...options,
    }),
};
```

**Comment by jtommy** [comment]
I could add it to the constructor options, what do you think?

**Comment by ffxsam** [comment]
@jtommy You mean like this?

```js
Vue.use(Buefy, {
  defaultIconPack: 'fal',
  snackbarDefaults: {
    position: 'is-top',
  },
});
```
Yes, that's even better. Thanks!

**Comment by jtommy** [comment]
Yes, something similar

**Comment by ffxsam** [comment]
@jtommy Thanks! Any reason you didn't allow for more flexibility, like setting defaults for `queue` and `actionText`? I could open a PR for this, but it seems like maybe this was an intentional design decision.

**Comment by jtommy** [comment]
I think I'll change constructor options in the future but you are free make a PR adding other default settings
