### ISSUE TITLE
linting error: using reserved key

### ISSUE THREAD

**Issue by yakovyarmo** [buefy/buefy#1230]
error: Keys starting with with '_' are reserved in '_elementRef' group (vue/no-reserved-keys) at src\lib\buefy\src\components\input\Input.vue:90:17:
  88 |                 newAutocomplete: this.autocomplete || config.defaultInputAutocomplete,
  89 |                 isPasswordVisible: false,
 90 |                 _elementRef: this.type === 'textarea'
     |                 ^
  91 |                     ? 'textarea'
  92 |                     : 'input'
  93 |             }

**Comment by jtommy** [comment]
Why are you importing the src ?

**Comment by yakovyarmo** [comment]
I find it easier to work like that and I needed to do some customizations
since rtl is not supported

**Comment by jtommy** [comment]
Did you see the docs ? You might import single components

**Comment by yakovyarmo** [comment]
I know, but I like to use the single file Vue files. Feels less bloated for
me. Is there a reason not to do it this way?
