### ISSUE TITLE
Icon on autocomplete

### ISSUE THREAD

**Issue by Livijn** [buefy/buefy#1231]
It is impossible to render a default sized autocomplete component without getting `fa-lg`. Even when I enter `none` it appends `fa-lg` to the icon. Extremely annoying.

Why not just let me disable the *icon-pack* setting?

**Comment by lordfuoco** [comment]
@Livijn hiding the icon with css ?

**Comment by Livijn** [comment]
I am not looking to hide the icon, i just wanted it to retain the default size. I ended up creating a `fa-md` class just for this then using it like `icon="calendar-day fa-md"` which really defeats the purpose of even having an icon-pack setting.

**Comment by jtommy** [comment]
@Livijn At the moment the icon size depends on input size.
I should think to add a new prop to override the default behaviour if you need it.

**Comment by francoism90** [comment]
@jtommy I have the same question - what prop should be needed to overrule this behavior?

**Comment by jtommy** [comment]
There isn't at the moment
