### ISSUE TITLE
table not rendering columns or data

### ISSUE THREAD

**Issue by LarBearrr** [buefy/buefy#1235]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [0.7.2]
**OS/Browser**: Windows 10 Chrome

### Description

When using the table component as a child, data is being passed in but not rendered. 

### Steps to reproduce
1. Create a wrapper component for the b-table per the documentation
2. Pass some data and columns in as a json string

### Expected behavior

The columns and data should be rendering.

### Actual behavior

If I inspect my wrapper component, I see the data and columns. However, the child <b-table> does not have any columns listed.

My parent list that works:
![image](https://user-images.githubusercontent.com/28734844/53190836-0ed7bc80-35d0-11e9-8b1c-b2356dcbf741.png)

Opening one of these records to show the child list of related records:
![image](https://user-images.githubusercontent.com/28734844/53190903-2fa01200-35d0-11e9-9a46-72f50abde5e6.png)

You can see the data and columns are being passed in. However, inspecting the child <b-table> component does not show the same as the working example:
![image](https://user-images.githubusercontent.com/28734844/53190993-5b22fc80-35d0-11e9-8d3f-380898e24495.png)

Notice that the `newColumns` value is empty here. 

Here is a dump of the data:
![image](https://user-images.githubusercontent.com/28734844/53191047-74c44400-35d0-11e9-8220-2941a4b2eaf4.png)

**Comment by jtommy** [comment]
@LarBearrr Could you provide a code example ?

**Comment by LarBearrr** [comment]
Sure, sorry for the delay here, I missed your reply. Just a quick overview, I have a `ListBehavior` that is responsible for configuring and rendering a `ListWidget.` I am able to successfully render a "table" directly in the `ListBehavior` using the Vue component:
```
`_container.htm` partial that is rendered by my PHP controller
<list-widget
        :data='<?= json_encode($list->records, JSON_HEX_APOS) ?>'
        :fields='<?= json_encode($list->columns, JSON_HEX_APOS) ?>'
        :records-per-page='<?= json_encode($list->recordsPerPage) ?>'
        :show-setup='<?= json_encode($list->showSetup) ?>'
        :show-checkboxes='<?= json_encode($list->showCheckboxes) ?>'
        :show-search='<?= isset($toolbar->search) ? json_encode(true) : json_encode(false) ?>'
        :record-url='<?= json_encode($list->recordUrl) ?>'
        :alias='<?= json_encode($list->alias) ?>'>
        <?php if ($toolbar): ?>
        <template slot="toolbar" slot-scope="data">
        <?= $toolbar->render() ?>
        </template>
        <?php endif ?>
</list-widget>
```
which produces this:
![image](https://user-images.githubusercontent.com/28734844/53669101-8db99e80-3c3b-11e9-8f3b-5610b66d4846.png)
![image](https://user-images.githubusercontent.com/28734844/53669308-47b10a80-3c3c-11e9-9988-ade76aa9344b.png)

I am also rendering the Vue component in the `ListWidget` which you can see here just above the version rendered by the `ListBehavior`:
```
`_list.htm` partial that is rendered by the `ListWidget` class
<bg-list-widget
        :data='<?= json_encode($this->records, JSON_HEX_APOS) ?>'
        :fields='<?= json_encode($this->columns, JSON_HEX_APOS) ?>'
        :records-per-page='<?= json_encode($this->recordsPerPage) ?>'
        :show-setup='<?= json_encode($this->showSetup) ?>'
        :show-checkboxes='<?= json_encode($this->showCheckboxes) ?>'
        :show-search='<?= isset($this->toolbar->search) ? json_encode(true) : json_encode(false) ?>'
        :record-url='<?= json_encode($this->recordUrl) ?>'
        :alias='<?= json_encode($this->alias) ?>'>
</bg-list-widget>
```
![image](https://user-images.githubusercontent.com/28734844/53669134-afb32100-3c3b-11e9-97d8-2889c5724da6.png)
![image](https://user-images.githubusercontent.com/28734844/53669234-0de00400-3c3c-11e9-80f6-40cc5d0beab6.png)

These two implementations are working as expected and producing the same result. What I am working on is a `RelationBehavior` that will render lists of related records when editing a parent record. For example, a `User` may belong to many `Addresses`:
![image](https://user-images.githubusercontent.com/28734844/53669498-e6d60200-3c3c-11e9-884b-432f7972750b.png)
`_list.htm` partial rendered by the `ListWidget` class:
```
<div class="control-list list-scrollable" data-control="listwidget">
    <table class="table data" data-control="rowlink">
        <thead>
            <?= $this->makePartial('list_head_row') ?>
        </thead>
        <tbody>
            <?php if (count($records)): ?>
            <?= $this->makePartial('list_body_rows') ?>
            <?php else: ?>
            <tr class="no-data">
                <td colspan="<?= $columnTotal ?>" class="nolink">
                    <p class="no-data"><?= $noRecordsMessage ?></p>
                </td>
            </tr>
            <?php endif ?>
        </tbody>
    </table>
</div>

<bg-list-widget
        :data='<?= json_encode($this->records, JSON_HEX_APOS) ?>'
        :fields='<?= json_encode($this->columns, JSON_HEX_APOS) ?>'
        :records-per-page='<?= json_encode($this->recordsPerPage) ?>'
        :show-setup='<?= json_encode($this->showSetup) ?>'
        :show-checkboxes='<?= json_encode($this->showCheckboxes) ?>'
        :show-search='<?= isset($this->toolbar->search) ? json_encode(true) : json_encode(false) ?>'
        :record-url='<?= json_encode($this->recordUrl) ?>'
        :alias='<?= json_encode($this->alias) ?>'>
</bg-list-widget>
```
What you are seeing here at the top is a plain HTML/PHP version of the list that is working as expected. You see the related addresses. Below it is the Vue component that is rendering, but not displaying the records properly. Here you can see that the data is being passed to the component:
![image](https://user-images.githubusercontent.com/28734844/53669581-2bfa3400-3c3d-11e9-81c0-8766f02956cc.png)

However, this is where I believe the issue is, the `newColumns` value is empty:
![image](https://user-images.githubusercontent.com/28734844/53669619-50561080-3c3d-11e9-9957-892515dd0e54.png)

My problem is that I cannot figure out why it is working at the parent list view level but not after pulling up an individual record.

I certainly appreciate your time and any thoughts you may have. Look forward to your reply.

**Comment by LarBearrr** [comment]
Also, here is the code for my `ListWidget.vue` file:
```
<template>
<div>
    <slot name="toolbar" :confirmDelete="confirmDelete" :computed="deleteIsDisabled"></slot>
    <div class="box">
        <b-tooltip label="Setup list configuration..." position="is-top" class="is-pulled-right is-info">
        <a class="button" v-if="showSetup === true" @click="isSetupModalActive = true">
            <span class="icon is-small">
                <i class="fas fa-list"></i>
            </span>
        </a>
        </b-tooltip>

        <list-filters :show-search="showSearch"></list-filters>

        <b-table
            :data="items"
            :column="fields"
            :checked-rows.sync="checkedRows"
            :paginated="isPaginated"
            :per-page="perPage"
            :current-page.sync="currentPage"
            :pagination-simple="isPaginationSimple"
            :default-sort-direction="defaultSortDirection"
            :hoverable="isHoverable"
            default-sort="first_name"
            @click="handleRowClick"
            checkable>
            <template slot-scope="props">
                <b-table-column v-for="(column, index) in columns"
                    :key="index"
                    :label="column.label"
                    :visible="column.visible">
                    {{ props.row[column.field] }}
                </b-table-column>
            </template>
            <template slot="bottom-left">
                <b>Total checked</b>: {{ checkedRows.length }}
            </template>
        </b-table>
        <b-modal :active.sync="isSetupModalActive" has-modal-card>
            <list-setup-modal></list-setup-modal>
        </b-modal>
    </div>
</div>
</template>

<script>
    import ListSetupModal from './ListSetupModal'
    import ListFilters from './ListFilters'
    export default {
        props: {
            data: Array, default: [],
            fields: [Array, Object], default: [],
            recordsPerPage: Number, default: 20,
            showSetup: Boolean, default: true,
            showSearch: Boolean, default: true,
            showCheckboxes: Boolean, default: true,
            recordUrl: String, default: null,
            alias: String, default: null,
            dialogTitle: String,
            dialogMessage: String,
            confirmText: String
        },
        components: {
            ListSetupModal,
            ListFilters
        },
        data() {
            return {
                items: this.data,
                checkedRows: [],
                columns: this.fields,
                isPaginated: true,
                isPaginationSimple: false,
                defaultSortDirection: 'asc',
                isHoverable: true,
                currentPage: 1,
                perPage: this.recordsPerPage,
                isSetupModalActive: false,
            }
        },
        methods: {
            closeSetupModal() {
                this.$emit('close')
            },
            handleRowClick(row) {
                window.location.href = this.recordUrl.replace(':id', row.id)
            },
            confirmDelete() {
                this.$dialog.confirm({
                    title: this.dialogTitle,
                    message: this.dialogMessage,
                    confirmText: this.confirmText,
                    type: 'is-danger',
                    hasIcon: true,
                    onConfirm: () => this.onDelete(),
                })
            },
            onDelete() {
                axios.delete('/' + this.alias, {
                    data: {
                        checked: this.checkedIds
                    }
                }).then(response => {
                    // JSON responses are automatically parsed.
                    this.items = response.data;
                    this.checkedRows = [];
                }).then(response => {
                    this.$toast.open({
                        message: 'Successfully deleted ' + this.alias,
                        type: 'is-success'
                    });
                }).catch(e => {
                    this.errors.push(e)
                });


            }
        },
        computed: {
            deleteIsDisabled() {
                return this.checkedRows.length === 0;
            },
            checkedIds: function () {
                return this.checkedRows.map(function(item) {
                    return item.id;
                });
            }
        }
    }
</script>
```

**Comment by jtommy** [comment]
@LarBearrr I'm sorry but it's no easy replicate all your code

**Comment by LarBearrr** [comment]
Yes, I know. Fairly complicated requirements here. Basically I'm trying to use Buefy with a Laravel app. My Laravel app is responsible for passing data and columns to my views which have the Buefy components. 

The reason for this is that I am trying to create reusable behaviors (forms, lists, etc.) that can be implemented in multiple places. This means I am trying to dynamically generate the Buefy table with by using a component that takes in the columns and data as props.

I've ended up just doing async calls for the table configuration and build it that way. Seems to be working so far. Thank you for your replies.
