### ISSUE TITLE
Enable next & previous month's days in datepicker

### ISSUE THREAD

**Issue by Livijn** [buefy/buefy#1239]
When using the `datepicker`, the previous month's days are disabled/greyed out. I would like them to be enabled as well. Maybe we should add a `boolean` prop called `nearby-monthly-days` with the default to `false`. 

[Screenshot of unwanted behavior](https://i.gyazo.com/476ec69658a7f2c86a53fdef92299fb1.png)

What do you think?

**Comment by jtommy** [comment]
You're right but I'm thinking to review that behaviour.
For example a prop to show/hide prev and next month days and if visible the days are selectable.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/28ede601953d68f871102c02eeaa09b179caff0d

**Comment by dusanlukic404** [comment]
Hey @jtommy, I’m facing an issue where users can’t select dates from other months. Is there a way to allow users to change the month and select the date they want, without first needing to manually switch months?

Thanks!
