### ISSUE TITLE
Can buefy.css backed into individual component?

### ISSUE THREAD

**Issue by lihan** [buefy/buefy#1240]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.5.17
**OS/Browser**: all

### Description

There are much of css name overlapping from `buefy.css` to my project. Just wondering why the CSS isn't backed into each individual component so they are properly scoped and not to import global CSS?

### Steps to reproduce

N/A

**Comment by yxngl** [comment]
Because most styles are from Bulma, which has been discussing about prefixing for a long time. https://github.com/jgthms/bulma/issues/302
Not sure if it is easy/feasible to import relevant styles in each component and scope it in Buefy.

**Comment by jtommy** [comment]
Some Buefy components depend on several bulma components/elements.
At the moment you are able to import individual components but you have to import all Bulma codebase.
