### ISSUE TITLE
Duplicate styles

### ISSUE THREAD

**Issue by suit0r** [buefy/buefy#1241]
Hi there.

I'm getting a little confused if I'm doing something wrong. It feels like I am. I noticed that with the setup listed on the customization page, I am duplicating a lot of the styles. I've attached a [screenshot](https://imgur.com/a/pRnKuo7), and this happens for a lot of other elements. I feel like I'm importing bulma and buefy, and they have a lot of the same code.

I noticed in the buefy _variables scss file, i can just make the two changes i want to the color variables, but i can't seem to get it to work. I npm installed buefy in the node_modules, and none of the scripts will run. I added some off the missing directories (build and another) from buefy-simple and still no go.

here's my App.vue
``` 
@import "~bulma/sass/utilities/_all";

  $primary: #167df0;
  $info: #35cdab;
  $primary-invert: findColorInvert($primary);
  $info-invert: findColorInvert($info);
  $colors: (
    "primary": (
      $primary,
      $primary-invert
    ),
    "info": (
      $info,
      $info-invert
    )
  );
  $progress-bar-background-color: rgba(22, 124, 240, 0.1);

  @import "~bulma";
  @import "~buefy/src/scss/buefy";
```

and in main.js

```
import Buefy from 'buefy'
import 'buefy/dist/buefy.css'
```

How can simply update a few variables to buefy styles?

**Comment by yxngl** [comment]
The built buefy.css includes all Bulma's styles. That's why you are getting duplicates. For customization, this is not needed.
```
import 'buefy/dist/buefy.css'
```
And I think I put my color definition before
```
@import "~bulma/sass/utilities/_all";
```
because it works by setting the variables to defaults if not defined previously. The docs may need some clarification.
