### ISSUE TITLE
Id property for Datatable.

### ISSUE THREAD

**Issue by vinaykumarkota** [buefy/buefy#1245]
Hi,

Is there any way to add id property to Datatable i mean to  b-table  which helps running some test scripts that work on id's of components ?

If there is a way to add Id property anyone please update how to do that else please tell some tentative date from when it will be available ?

**Comment by jtommy** [comment]
@vinaykumarkota adding `id="myTable"` to `b-table` you'll get `<div class="b-table" id="myTable"> ... `

**Comment by vinaykumarkota** [comment]
@jtommy  I already tried and I achieved that but i need id for table tag not for div tag like below.
`<table class="table has-mobile-cards" id="myTable">`
