### ISSUE TITLE
Datepicker CSS issue

### ISSUE THREAD

**Issue by Teja21780** [buefy/buefy#1247]
### Overview of the problem
The width of the datepicker is looking good when the app is running in localhost. but when I push the code to production server the width changes as follows.

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.17
**OS/Browser**: Windows/Chrome & IE

#### Problem
<img width="354" alt="screenshot 2019-02-27 at 1 08 00 am" src="https://user-images.githubusercontent.com/38671438/53442267-f08a1a80-3a2e-11e9-8f4a-392e6950fac6.png">

#### Expected

![image](https://user-images.githubusercontent.com/38671438/53442964-90688980-39d8-11e9-9da0-55d38ca72ac3.png)

**Comment by jtommy** [comment]
@Teja21780 please check your production code using inspector console
