### ISSUE TITLE
"Unknown custom element" in tests

### ISSUE THREAD

**Issue by yereby** [buefy/buefy#1249]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.6.7
**Nuxt** versions: 2.4.5

### Description

Hi,

I use buefy with nuxt, and i got an issue with the tests.
There is no problem with my component, i got it on the UI.
But when i want to test it with Jest, i have this warn, while the test pass :

```
console.error node_modules/vue/dist/vue.common.dev.js:630
    [Vue warn]: Unknown custom element: <b-field> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    found in
    ---> <Anonymous>
           <Root>
```

my small component : 
```vue
<template>
  <b-field>
    <b-input type="text" />
  </b-field>
</template>
```

and my small test :
```js
import { createLocalVue, shallowMount } from '@vue/test-utils'
import Card from '@/components/Card.vue'
import NuxtBuefy from 'nuxt-buefy'

describe('Card', () => {
  test('is a Vue instance', () => {
    const localVue = createLocalVue()
    localVue.use(NuxtBuefy)

    const wrapper = shallowMount(Card, { localVue })
    expect(wrapper.isVueInstance()).toBeTruthy()
  })
})
```

Thanks.

**Comment by yereby** [comment]
I found a solution by ignoring those elements in my tests :
```js
import Vue from 'vue'
Vue.config.ignoredElements = ['b-field', 'b-autocomplete']
```

**Comment by daundkarmangesh1109** [comment]
@yereby,  If element ignored, how can we write test on this elements. I'm trying to set value of b-input.
 **wrapper.find('b-input[type="number"]').setValue('080710000038');**
 But getting error, '[vue-test-utils]: wrapper.setValue() cannot be called on this element'.

**Comment by yereby** [comment]
Hi,
That was not the purpose of my test so i didn't see that.
But you can perhaps try to use `wrapper.setData()` before your submit

**Comment by daundkarmangesh1109** [comment]
@yereby  Ok thanks.

**Comment by GopherJ** [comment]
![Screenshot from 2019-04-21 21-35-48](https://user-images.githubusercontent.com/33961674/56470831-2eae2400-644b-11e9-84c7-87d9f8a2ec56.png)

**Comment by GopherJ** [comment]
still get this error, anyone knows how to solve it and what's the cause?

**Comment by ManuLintz** [comment]
I registered Buefy globally in my tests with [Jest setupFilesAfterEnv option:](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) 

In  jest.config.js I refer to a file that will run before the tests:

```javascript
module.exports = {
    ...,
   setupFilesAfterEnv: ['<rootDir>/tests/unit/vueSetup.js']
   // or
   setupTestFrameworkScriptFile: '<rootDir>/tests/unit/vueSetup.js' // this is deprecated
}
```

and in vueSetup.js file I registered Buefy: 
```javascript
import Vue from 'vue'
import Buefy from 'buefy'
 
Vue.use(Buefy)
 
```

That worked for me

**Comment by daundkarmangesh1109** [comment]
This worked for me..

```
import { shallowMount, createLocalVue } from '@vue/test-utils';
import Buefy from 'buefy';

const localVue = createLocalVue();
localVue.use(Buefy);

wrapper = shallowMount(Component, {
 localVue
});
```

**Comment by barclayd** [comment]
> This worked for me..
> 
> ```
> import { shallowMount, createLocalVue } from '@vue/test-utils';
> import Buefy from 'buefy';
> 
> const localVue = createLocalVue();
> localVue.use(Buefy);
> 
> wrapper = shallowMount(Component, {
>  localVue
> });
> ```

Great solution @daundkarmangesh1109, thank you!

**Comment by jcorry** [comment]
`setupTestFrameworkScriptFile` is deprecated, use `setupFilesAfterEnv`
