### ISSUE TITLE
Datepicker closing when page back to min-date month

### ISSUE THREAD

**Issue by davedoesdev** [buefy/buefy#1251]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.6.4
**OS/Browser**: Ubuntu 18.10/Chrome 72

### Description

Datepicker closes when page back to month of min-date.

### Steps to reproduce

1. Set min-date to now
2. Open the datepicker
3. Page forward
4. Page back

### Expected behavior

Dropdown should remain open

### Actual behavior

Dropdown closes

### Solution

Cause is:

https://github.com/buefy/buefy/blob/dev/src/components/datepicker/Datepicker.vue#L38

This should use `v-show`, not `v-if`, because `isInWhiteList()` needs to find it.

**Comment by zcuric** [comment]
When can we expect this to be released? Thank you.

**Comment by jtommy** [comment]
I think today or tomorrow

**Comment by zcuric** [comment]
👍
