### ISSUE TITLE
Feature request: class prefixes

### ISSUE THREAD

**Issue by Christilut** [buefy/buefy#1253]
For a project I'm doing I need to prefix everything because the websites I'm inserting my embeddable app into will either override my styles (since Bulma has very generic classnames) or my bulma css will override the existing website styles.

Currently my workaround is to include a bulma.css version that has class prefixes everywhere and I'm handpicking the Buefy components and changing the classnames to match.

It would be great if Buefy could support prefixes, also because Bulma doesn't seem to want to do that and you have to resort to webpack tricks to create the prefixes.

**Comment by DonNicoJs** [comment]
Scoped on the style did not help you?

**Comment by Christilut** [comment]
No because the bulma css is using the very generic classnames like `.title` and `.label` and they are global so are applied to the existing website.

**Comment by DonNicoJs** [comment]
If you import bulma sass inside your root component and then apply scoped it should scope the full bulma CSS.

If I am not mistaken

**Comment by Christilut** [comment]
I thought so too.

But the other problem can't be fixed so easily I think, because Bulma uses these classnames like `.title` and they might already exist in the website. And often these websites don't scope their css properly. Which is why I think the only real solution for my problem is prefixes for everything.

I don't expect Buefy to implement this to be honest, but I just wanted to make my use case known.

**Comment by coreyworrell** [comment]
Not sure why this was closed, but I also have the same use case.. Building an embeddable "widget" and using three Buefy components (Autocomplete, Slider, and Switch). It's great to have one library for all these components, and Buefy's are very well done and the "a-la-carte" method of including only what I needs works great, but the generic classes in the HTML output makes it prone to inheriting styles from the website the app is embedded in.

**Comment by jtommy** [comment]
@coreyworrell Buefy depends on Bulma so a similar request should start by Bulma itself.
I don't want speak about my other project here but you might take a look at https://oruga.io (the code base starts from Buefy).

**Comment by coreyworrell** [comment]
@jtommy Thanks, Oruga looks great! Should be easy to migrate too as the API is similar.
