### ISSUE TITLE
How-To/Feature Request: Autocomplete custom selected "field/label" text

### ISSUE THREAD

**Issue by luecano** [buefy/buefy#1254]
**Buefy** version: 0.7.3

### Description

**Autocomplete form control**
Is it posibble to set a custom **selected** option label when using object array out ot the box (slot, prop)?

`@select` updates `field` to one property like `field="user.name"` but I need to display two or more properties from my object for the selected option like:
`field="country.name + country.code"` or `field="product.name + product.color + product.size"`

![image](https://user-images.githubusercontent.com/5108807/53684981-8dc0a980-3ce2-11e9-813c-761b4dbbee45.png)

**Comment by jtommy** [comment]
Look at the last example https://buefy.org/documentation/autocomplete

**Comment by luecano** [comment]
Yeah I know DefaultSlot works for the options dropdown but not for the **input label** after you select (click) an option

`<template slot-scope="props">{{ props.option.code}} - {{ props.option.name}}</template>`

![image](https://user-images.githubusercontent.com/5108807/53685638-53a7d580-3ceb-11e9-8de0-9cefcfaa84ec.png)

![image](https://user-images.githubusercontent.com/5108807/53685645-70dca400-3ceb-11e9-97a7-e1df5fbbc115.png)

Something like this [component](https://vue-multiselect.js.org/#sub-custom-option-template)

I'll be using open-on-focus="true" or {{selected.title}}  {{selected.release_date | filter}} for now so the user will be able to visually check which "The Lion King" he clicked (1994 or 2019) instead of just displaying "The Lion King" label on the input, thanks.

**Comment by jtommy** [comment]
Ok, I understand better now.
I might add a new prop `custom-formatter` (function, object -> string), what do you think ?

**Comment by luecano** [comment]
either a prop or slot would be a nice option to have

**Comment by yuuhic** [comment]
I hope this feature will also be enabled for `taginput` with `autocomplete`.
In this case, even if `:custom-formatter` is set, the form will display the value set in `field`.
