### ISSUE TITLE
[B-Table] Multi tr in thead and tfoot

### ISSUE THREAD

**Issue by Heziode** [buefy/buefy#1255]
### Description

Curently, the `header` [only show columns added with `b-table-column`](https://github.com/buefy/buefy/blob/46b7eb9775d78de6bbcbaa67a936039428efef9d/src/components/table/Table.vue#L20), and [`tfoot` only contains a single `tr`](https://github.com/buefy/buefy/blob/46b7eb9775d78de6bbcbaa67a936039428efef9d/src/components/table/Table.vue#L145).

It could be nice to have the possibility to add more `tr` in `thead` and `tfoot`.
For example:

![gb-investment_put-investment-value](https://user-images.githubusercontent.com/16735076/53687975-6e566a80-3d3c-11e9-95dc-a6ffeabefe25.png)

This array was generated in Bulma with Vue.

**Comment by jtommy** [comment]
Thead maybe in the future while footer pleace check the example https://codepen.io/anon/pen/KExvPW?&editable=true&editors=101

**Comment by Heziode** [comment]
> only one row at the moment

I know that…

I have developed my own implementation of the card view for this use case (multi row in the footer and header) but without Buefy, because it c'ant (juste pure Vue+Bulma).

Futhermore, B-Table is to slow for my use case… I need information quickly but when we update the data, waiting for the table to be updated is very visible…

**Comment by jtommy** [comment]
Slow, could provide me an example?

**Comment by Heziode** [comment]
@jtommy 
I can't reprodruce it, so do not take it in account…

**Comment by markdark154** [comment]
I would suggest to append the tfoot and then call it every time to the back-end request is being fetch.

Here's the sample
var foot = $("#inbounds-table > .table-wrapper > .table").find('tfoot');

            if (!foot.length) {
                foot = $('<tfoot>').appendTo("#inbounds-table > .table-wrapper > .table"); 
            }

             foot.html($(`
                <th></th>
                <th>Total</th>
                <th>${this.totalCount.following_up.inbounds}</th>
                <th>${this.totalCount.following_up.facebookAds}</th>
                <th>${this.totalCount.closed.inbounds}</th>
                <th>${this.totalCount.closed.facebookAds}</th>
            `));

**Comment by amrullohrobbani** [comment]
for the addition of tr in THead, is it already implemented?
