### ISSUE TITLE
Unknown custom element: <vue-fontawesome>

### ISSUE THREAD

**Issue by JivanRoquet** [buefy/buefy#1256]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.6.8
**OS/Browser**: macOS 10.14.1 / Chrome 72.0

### Description

When trying to display an icon using `<b-icon>`, an error is produced:

```
Unknown custom element: <vue-fontawesome> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <BIcon>
       <TableChart> at src/components/TableChart.vue
         <App> at src/App.vue
           <Root>
```

Content of `main.js`:
```js
import Vue from 'vue'
import App from './App.vue'
import Buefy from 'buefy'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faCoffee)
Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.use(Buefy, {
  defaultIconPack: 'fa',
  defaultContainerElement: '#content',
  defaultIconComponent: 'vue-fontawesome'
})

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

And the content of the component from which `<b-icon>` is invoked:
```vue
<template>
  <div class="column table-chart-container">
    <b-icon icon="account" size="is-small"></b-icon>
  </div>
</template>

<script>
export default {
  name: 'TableChart',
  props: {
      data: Object
  }
}
</script>
```

### Expected behavior

Icon would be displayed properly and not produce an error.

### Actual behavior

Trying to display the icon produces the error described above.

Note: the issue happens is any component, anywhere in the app. The specific component shown here is just for illustration.

**Comment by jtommy** [comment]
```
Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.use(Buefy, {
  defaultIconPack: 'fa',
  defaultContainerElement: '#content',
  defaultIconComponent: 'vue-fontawesome'
})
```

@JivanRoquet Why component name in `Vue.component(...)` and `defaultIconComponent` are different ?

**Comment by francoism90** [comment]
@JivanRoquet @jtommy I have the same problem: **Unknown custom element: <vue-fontawesome> - did you register the component correctly?**

```
library.add(faCoffee)

Vue.component('font-awesome-icon', FontAwesomeIcon)
Vue.component('font-awesome-layers', FontAwesomeLayers)
Vue.component('font-awesome-layers-text', FontAwesomeLayersText)

Vue.use(Buefy, {
  defaultIconPack: 'fas',
  defaultIconComponent: 'vue-fontawesome'
})
```

**Comment by JivanRoquet** [comment]
I ended up not using Buefy's icons and resort to a proper (and working) solution instead.

**Comment by camillo777** [comment]
> I ended up not using Buefy's icons and resort to a proper (and working) solution instead.
> 
> I actually believe this is not a bug, but the consequence of shortcomings in the documentation, in particular a lack of alignment between the docs for Buefy and for Vue-Fontawesome.

Hello, I have the same problem.
What solution did you find in the end?
Thank you!

**Comment by altunyurt** [comment]
@francoism90  

``` 
defaultIconComponent: 'vue-fontawesome'
```
  should be
``` 
defaultIconComponent: 'font-awesome-icon'
```
like the name you use in 

```
Vue.component('font-awesome-icon', FontAwesomeIcon)
```
