### ISSUE TITLE
Could not find one or more icon(s) {prefix: "fa", iconName: "menu-down"} {}

### ISSUE THREAD

**Issue by JivanRoquet** [buefy/buefy#1258]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.6.8
**OS/Browser**: macOS 10.14.1 / Chrome 72.0

### Description

When trying to display a Buefy component using icons, the following error is triggered:

```
Could not find one or more icon(s) {prefix: "fa", iconName: "menu-down"} {}
```

Content of `main.js`:
```js
import Vue from 'vue'
import App from './App.vue'
import Buefy from 'buefy'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faCoffee)
Vue.component('vue-fontawesome', FontAwesomeIcon)

Vue.use(Buefy, {
  defaultIconPack: 'fa',
  defaultContainerElement: '#content',
  defaultIconComponent: 'vue-fontawesome'
})

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

### Expected behavior

Icons would be displayed properly and not produce an error.

### Actual behavior

Displaying icons in Buefy components triggers the aforementioned error.

### Feedback

Congratulations for the great work on Buefy, overall it's massively helpful and works very well.

However, I didn't find the documentation to be perfectly clear on how to use vue-fontawesome together with Buefy. [This page states](https://buefy.org/documentation/constructor-options) that `defaultIconComponent : 'vue-fontawesome'` along with `defaultIconPack: 'fa'` should be used in the constructor, but what actually needs to be done is not explicit.

I'm still probably doing something wrong, hence the behaviour posted above.

**Comment by jtommy** [comment]
@JivanRoquet Maybe you should use `fas` instead of `fa`

**Comment by JivanRoquet** [comment]
Thanks — I've tried that (along with `fad` and `fal` as well) with no success.

**Comment by jtommy** [comment]
You are importing only faCoffe icon, why?

**Comment by JivanRoquet** [comment]
Good question. I followed the instructions provided here: https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs, and tried to combine them with Buefy's own documentation.

**Comment by JivanRoquet** [comment]
Alright, silly me. The faCoffee thing refers to a single icon. Any idea how can I import the whole thing at once?

**Comment by jtommy** [comment]
I think importing all package, for example 
import faSolid from '@fortawesome/free-solid-svg-icons'

**Comment by JivanRoquet** [comment]
Nope. No matter how I try to follow the [docs on npm](https://www.npmjs.com/package/@fortawesome/vue-fontawesome), there's no way to put it right.

There might be a confusion between the standard way to import them in a pure Vue context (as they state in the doc), and how they are supposed to be used by Buefy, which is not documented.

**Comment by JivanRoquet** [comment]
Actually, I've just realised that the icons which Buefy fails to use are:
- `fas-menu-down`
- `fas-account`

Both of them do not seem to exist in font-awesome, and I can't even import them one by one by using `import { faMenuDown } from ...` (contrarily to `faCoffee` for instance).

**Comment by g0d0** [comment]
I've the same problem.
I did import `import { faUserSecret } from '@fortawesome/free-solid-svg-icons'` and `import { library } from '@fortawesome/fontawesome-svg-core'`, add with `library.add(faUserSecret)`...

The usage has been like this `<font-awesome-icon :icon="['fas' 'fire']" class="icon alt" />` why I did verified that `fire` icon is contained inside solid icon collection (https://fontawesome.com/icons/fire?style=solid).

**Comment by kissu** [comment]
Easiest way is to import some same looking icons taken from the [free solid icons](https://fontawesome.com/icons?d=gallery&p=2&q=menu%20down&s=solid&m=free) like `caret-down`.
