### ISSUE TITLE
b-autocomplete with textarea

### ISSUE THREAD

**Issue by gecheru** [buefy/buefy#1260]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.6.8
**OS/Browser**: Windows 10 / Chrome 72.0.3626.119

### Description

b-autocomplete type="textarea" doesn't select text on re-focus causing error in browser console

### Steps to reproduce

1. Focus on textarea
2. Type some text or choose from dropdown
3. Loose focus from textarea
4. Focus on textarea again

https://jsfiddle.net/gecheru/oygjkxmq/2/

### Expected behavior

Textarea data shall be selected in the same way as it is for input 

### Actual behavior

Console error: Error in v-on handler: "TypeError: Cannot read property 'select' of null"
This happens due to event handler that works with input only: this.$el.querySelector("input").select()

**Comment by jtommy** [comment]
Textarea?? 
I'm going to disable this possibility and only text type will be allowed

**Comment by gecheru** [comment]
What is problem with textarea? I have results that should be multilined and 
not cliped. Textarea can help me. Autocomplete is already working. Only selection on focus is not enough.

**Comment by jtommy** [comment]
@gecheru I'm sorry but the component works only as text input and in the next release you can't use a textarea.

**Comment by Atullohia** [comment]
@gecheru
