### ISSUE TITLE
Bulma Navbar hamburger menu not working

### ISSUE THREAD

**Issue by ffxsam** [buefy/buefy#1261]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.6.8
**OS/Browser**: macOS 10.14.3 / Chrome 72

### Description

Bulma Navbar hamburger menu doesn't work

### Steps to reproduce

1. Clone https://github.com/ffxsam/repro-buefy-navbar
1. `yarn && yarn serve`
1. Go to app
1. Shrink browser width so hamburger menu shows up
1. Click hamburger menu

### Expected behavior

Menu should be visible

### Actual behavior

Nothing happens

**Comment by ffxsam** [comment]
Just realized this is intended behavior, there's no JS wired up to the navbar.
Would be cool to have a `<b-navbar>` component that took care of this, though.

**Comment by jtommy** [comment]
It's already in the roadmap
