### ISSUE TITLE
[b-select] How to keep the old value in laravel ?

### ISSUE THREAD

**Issue by Ahmad-Fathy** [buefy/buefy#1263]
### Overview of the problem

**Buefy** version: [0.7.3]
**Vuejs** version: [2.5.17]
**OS/Browser**: Firefox

### Description
question

I'm in Laravel project and trying to use  b-select

### Steps to reproduce
```
<b-field>
    <b-select name="city_id" 
          placeholder="{{__('site.city')}}" 
          icon="globe"
          icon-pack="fas" 
          expanded>
          @foreach ($provinces as $province)
             <optgroup label="{{ $province->name }}">
                 @foreach ($province->cities as $city)
                    <option value="{{ $city->id }}" {{(old('city_id')==$city->id)? 'selected':''}}>{{ $city->name}}</option>
                  @endforeach
              </optgroup>
         @endforeach
    </b-select>
</b-field>
```

### Expected behavior
When there is an validation error the select box keep the old value

### Actual behavior

The select box repopulate all data and show the place holder

**Comment by jtommy** [comment]
@Ahmad-Fathy server side or client side validation ?

**Comment by Ahmad-Fathy** [comment]
Server side validation

**Comment by jtommy** [comment]
Try setting `:value` prop
