### ISSUE TITLE
custom-class prop in b-field component appear not to be working. 

### ISSUE THREAD

**Issue by erwanpoupard** [buefy/buefy#1277]
### custom-class prop in b-field component appear not to be working. 

**Buefy** version: 0.7.3
**Vuejs** version: 2.5.17
**OS/Browser**:  windows10/chrome

### Description
b-field component doesnt care about custom-class prop. 

### Steps to reproduce
i add a <b-field /> component to my form with a custom class prop : 
<b-field custom-class="is-time">
                <b-input></b-input>
              </b-field>
i can see in vue dev tool the prop is ok : 
![buefy_customclass1](https://user-images.githubusercontent.com/5172790/54204216-0e965700-44d4-11e9-831f-eb5d5b954296.png)
but no class in html : 
![buefy_customclass2](https://user-images.githubusercontent.com/5172790/54204232-1655fb80-44d4-11e9-8c45-7f299cf6ea40.png)

### Expected behavior
adding the "is-time" class declared with the custom-class prop to the .field div

### Actual behavior
no class added

**Comment by yxngl** [comment]
Please check doc and example carefully. The class is on the label.
