### ISSUE TITLE
[Snackbar] Inconsistent use of variable

### ISSUE THREAD

**Issue by Heziode** [buefy/buefy#1278]
https://github.com/buefy/buefy/blob/9170ec901a0c7643e080e9c5d171e0a088c6468d/src/scss/components/_notices.scss#L43

It should be like `$snackbar-background-color: $dark !default;`.
Maybe: `$snackbar-color: $dark-invert !default;`

This can be useful when we create a dark theme and want to display snackbar with light background.

**Comment by jtommy** [comment]
@Heziode You could override the variable, don't you ?

**Comment by Heziode** [comment]
I can do that:

```scss
.snackbar {
    color: $light-invert !important;
  }
```

But is "shitty" opposite to the use of `$snackbar-color`.

**Comment by Heziode** [comment]
I can do the change now if you want.

**Comment by jtommy** [comment]
You're right, i didn't read well your request.
Ok about your PR, thanks

**Comment by Heziode** [comment]
@jtommy, background color of the action button should have the same background of the rest of the snackbar, isn'it ? 

Currently it is hardcoded here:
https://github.com/buefy/buefy/blob/78afa0f7dace863cdf8c4c8e6bd8838fbb70d2d9/src/components/snackbar/Snackbar.vue#L15

This give something like that if we change the color 😂:
![buefy-snackbar-update](https://user-images.githubusercontent.com/16735076/54495481-7db0e880-48e4-11e9-8b7d-d12f7ca4534b.png)

**Comment by jtommy** [comment]
Yes, button too

**Comment by Heziode** [comment]
PR open.
