### ISSUE TITLE
[forms] Add floating label style to inputs

### ISSUE THREAD

**Issue by tipsy** [buefy/buefy#1280]
It would be nice to have the option to enable [floating labels](https://uxplanet.org/float-label-pattern-in-ux-form-design-7ab5e33010ab) on the inputs:

![labels](https://user-images.githubusercontent.com/1521451/54300535-593fce00-45bd-11e9-88bc-96e41a8f67ee.png)

It's very simple to add to the basic inputs fields, but there might be some challenges with tags, select boxes, etc. I supposed they don't have to be supported, but it would be nice.

**Comment by service-paradis** [comment]
I would love to have an option to enable floating labels on focus where the lable is displayed as a placeholder at start. 
Something like the outlined version of this:
https://material.io/design/components/text-fields.html#

**Comment by gutisalex** [comment]
That feature would be great!

**Comment by jtommy** [comment]
0.7.8 allows to show label in a different way like floating label but without animation or similar

**Comment by szydloit** [comment]
this will do the trick
`        <b-field
          label="status"
          label-position="on-border"
          v-bind:class="{ activeLabel: status }"
          :type="{'is-danger': errors.has('status')}"
          :message="errors.first('status')"
        >
          <b-input type="text" v-model="status" name="status" placeholder="status" />
        </b-field>`

`
.is-floating-label {
    label {
        opacity: 0;
        transition: opacity 0.5s ease-in;
    }
    &.activeLabel {
        label {
            opacity: 1;
        }
    }
}
`
