### ISSUE TITLE
Unknown custom element: <vue-fontawesome> - did you register the component correctly?

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#1283]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.5.17
**OS/Browser**: Arch Linux/Chrome

### Description

It doesn't seem to register `vue-fontawesome` as  `defaultIconComponent`.

This works fine: `font-awesome-icon(icon="user-secret")`, seems to be fault in `b-icon`.

### Steps to reproduce

1. Set `defaultIconComponent` to `vue-fontawesome`
2. Import icons
3. ..

### Expected behavior

Render icons

Config:
```
import Buefy from 'buefy'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

Vue.use(Buefy, {
  defaultIconPack: 'fas',
  defaultIconComponent: 'vue-fontawesome'
})

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
})
```

### Actual behavior

`Unknown custom element: <vue-fontawesome> - did you register the component correctly?`

**Comment by Healios** [comment]
Give my config a go, I have the following setup in two different projects:

```
import { library } from "@fortawesome/fontawesome-svg-core";
import { faTimes } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(faTimes);
Vue.component("font-awesome-icon", FontAwesomeIcon);

import Buefy from 'buefy'
Vue.use(Buefy, {defaultIconComponent: "vue-fontawesome", defaultIconPack: "fas"});
```

**Comment by francoism90** [comment]
@Healios Thanks for your config. :)

I'm aware of using `dom.watch()`, but if I'm not mistaken this should no longer be needed.

**Comment by jtommy** [comment]
You have to set the same name between `Vue.component("font-awesome-icon", FontAwesomeIcon);`  and `Vue.use(Buefy, {defaultIconComponent: "vue-fontawesome");`

Anyway i'll improve the docs

**Comment by francoism90** [comment]
@jtommy This crashes the Vue instance. Is it useful to provide you with debug info?

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/d9d507450f266fd43c88a5f5bf0ebb7138566d17
