### ISSUE TITLE
Taginput should open clicking anywhere within container

### ISSUE THREAD

**Issue by wrabit** [buefy/buefy#1286]
Latest Buefy, Chrome, Osx
Taginput with autocomplete and open-on-focus

When clicking inside the visual boundaries you would expect the dropdown to appear, however the @focus listener is on the input contained within and not on the `.taginput-container.is-focusable` container. The input has no visual boundary so it simulates buggy behaviour and not useful if the user needs to know there is data they can choose from:

Example 1:

<img src="https://user-images.githubusercontent.com/5918271/54416814-bf813980-4700-11e9-8b5c-039542a0df72.png" width="300">

<img src="https://user-images.githubusercontent.com/5918271/54416926-15ee7800-4701-11e9-8769-4b145ac3d6f8.png" width="300">

Example 2:

![image](https://user-images.githubusercontent.com/5918271/54417252-ec821c00-4701-11e9-9eac-189f9668cf94.png)

![image](https://user-images.githubusercontent.com/5918271/54417352-3539d500-4702-11e9-9a26-29a95e85872c.png)

Related to this is: when someone deletes a tag, the input gains focus, but the dropdown does not appear.

Would be really great if this could be fixed.

**Comment by rkacenski** [comment]
Might have a quick fix here:
https://github.com/buefy/buefy/pull/1293

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/d4dfb2a8b9b25e6c48963d7088142e383bf3502e

**Comment by williamabbott** [comment]
You're right, it's working in the dev branch. Must be something local to my code doh. Thanks for the help though.

**Comment by williamabbott** [comment]
@jtommy can this be reopened? Here's a minimal repro [https://github.com/williamabbott/BuefyTaginput](https://github.com/williamabbott/BuefyTaginput) using a fresh vue-cli install.

**Comment by williamabbott** [comment]
Dropdown should open when clicking inside the container element, like in the docs version, but it doesn't.

![image](https://user-images.githubusercontent.com/5918271/54783211-131fe580-4c21-11e9-8f15-e767c542a08d.png)

p.s. docs version I use the ExAutocomplete of taginput and add the `open-on-focus`

**Comment by williamabbott** [comment]
![image](https://user-images.githubusercontent.com/5918271/54838729-9dbc1f80-4cc9-11e9-80f7-1ecd8e6cb2da.png)

**Comment by williamabbott** [comment]
Ok so the issue is to do with the computed `whiteList` in Autocomplete. It's not factoring in that the parent could be a TagInput and therefore that too should be in the whitelist. 

Original code:

```
            /**
             * White-listed items to not close when clicked.
             * Add input, dropdown and all children.
             */
            whiteList() {
                const whiteList = []
                whiteList.push(this.$refs.input.$el.querySelector('input'))
                whiteList.push(this.$refs.dropdown)
                // Add all chidren from dropdown
                if (this.$refs.dropdown !== undefined) {
                    const children = this.$refs.dropdown.querySelectorAll('*')
                    for (const child of children) {
                        whiteList.push(child)
                    }
                }

                return whiteList
            },
```

What I have patched:

```
            /**
             * White-listed items to not close when clicked.
             * Add input, dropdown and all children.
             */
            whiteList() {
                const whiteList = []
                if( this.$parent.$options.name === 'BTaginput' ) {
                    // Add taginput container
                    const tagInputChildren = this.$parent.$el.querySelectorAll('*')
                    for (const tagInputChild of tagInputChildren) {
                        whiteList.push(tagInputChild)
                    }
                    // Add tags too
                    const tags = this.$parent.$el.querySelectorAll('.tag')
                    for (const tag of tags) {
                        whiteList.push(tag)
                    }
                }
                whiteList.push(this.$refs.input.$el.querySelector('input'))
                whiteList.push(this.$refs.dropdown)
                // Add all chidren from dropdown
                if (this.$refs.dropdown !== undefined) {
                    const children = this.$refs.dropdown.querySelectorAll('*')
                    for (const child of children) {
                        whiteList.push(child)
                    }
                }

                return whiteList
            },
```

This allows the dropdown to appear when:

- [x]  Clicking anywhere in taginput container
- [x]  Click on tags (including delete icon on a tag)

But not:

- [ ]  Clicking on tags which have been just created of chosen (only works for selected tags present on load)

**Comment by wrabit** [comment]
Another test case: https://codepen.io/will-abbott/pen/eYOommQ?&editable=true&editors=101

Reproduce: Click on the outer edge of the taginput i.e. border or area as indicated here in green:

![image](https://user-images.githubusercontent.com/5918271/65675547-a57cc800-e04e-11e9-877e-81e14a092214.png)

This pen is fresh from the docs with open-on-focus.
