### ISSUE TITLE
Native event listener is applied on the wrapper of Select

### ISSUE THREAD

**Issue by yxngl** [buefy/buefy#1291]
### Overview of the problem

**Buefy** version: [0.7.3]

### Description
Several form components support adding native events and some of them are wrapped in a `control` div, where the native event listener is actually applied. Most components like Input and Checkbox Button uses 100% width of the control wrapper and it appears fine. But for `select`, clicking on the empty space to the right will also trigger `click` event, for example.

### Steps to reproduce
Add a \@click.native handler and click to the right of the `select` element.

### Expected behavior
Only clicking on the select triggers the event

### Actual behavior
Clicking on the wrapper will trigger the event

### Solution
Use $listeners to pass the native event listeners down to the input element.
https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

**Comment by jtommy** [comment]
Yes you're right but it could be a breaking change at the moment

**Comment by yxngl** [comment]
Could be considered for 0.8.0. Now the event.target is not the input, and some event-related problems are hard to deal with.

**Comment by jtommy** [comment]
Sure!

**Comment by yxngl** [comment]
Bringing this up for the upcoming 0.8.0. Bind `$listeners` to the actual input element like `$attrs`.
