### ISSUE TITLE
Right aligned icon is enabled when using "type" in b-field

### ISSUE THREAD

**Issue by Livijn** [buefy/buefy#1296]
[The docs](https://buefy.org/documentation/field) instructs using `<b-field>` to specify the type / color of the input. However, using it also enables the right aligned icon. Very strange behavior. 

It is based of this: https://github.com/buefy/buefy/blob/d9d507450f266fd43c88a5f5bf0ebb7138566d17/src/utils/FormElementMixin.js#L43

**Comment by service-paradis** [comment]
Buefy [automatically adds icons](
https://buefy.org/documentation/input#types-and-states) for some types:

- Success
- Error
- Info
- Warning
-Loading

**Comment by jtommy** [comment]
I will be possible add a right icon in the next release
