### ISSUE TITLE
b-table enhancement: indicate clickable rows

### ISSUE THREAD

**Issue by Niels-NTG** [buefy/buefy#1299]
### Overview of the problem

**Buefy** version: [0.7.3]
**Vuejs** version: [2.6.10]
**OS/Browser**: Mac OS 10.14.3, Chrome 73

### Description

Enhancement request: When b-table has the `click` event listener, automatically add styling for each row such that it becomes apparent the row is clickable. This styling should be the same as `hoverable` except is also has `cursor: pointer`. This way it's easier to indicate that interaction by clicking the row is possible for the user.

**Comment by jtommy** [comment]
At the moment i don't think to add a specific style because you can simple set a custom class to `b-table` adding pointer cursor style.
