### ISSUE TITLE
b-loading error state

### ISSUE THREAD

**Issue by Niels-NTG** [buefy/buefy#1300]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.6.10
**OS/Browser**: Mac OS 10.14.3, Chrome 73

### Description

The `b-loading` component is often use as a placeholder when waiting for a response from the backend. There is currently no build-in way this component can react if a request fails. You can only turn it on or off. I think it would be neat if `b-loading` has an error state that appears whenever the `:error` property is true. This would be especially valuable to me for the spinner that's used in `b-table` with backend pagination, where my custom solution doesn't work.

### Expected behaviour
Idea on how this could be implemented:
```vue
<b-loading
      :is-full-page="false"
      :active="isLoading"
      :error="error"
 >
    <template v-slot:error-message="error">
        <span class="tag is-danger">{{ error.status }}</span>
        {{ error.data.description }}
    </template>
</b-loading>
```

### Actual behaviour
My current solution:
```vue
        <b-message
            v-if="isError"
            :closable="false"
            type="is-danger"
            has-icon
        >
            <span class="tag is-danger">
                {{ error.status }}
            </span>
            {{ error.data.description }}
        </b-message>
        <b-loading
            v-else-if="isLoading"
            :is-full-page="false"
            :active="isLoading"
        />
        <slot v-else="!isLoading" />
```

![Schermafbeelding 2019-03-25 om 17 06 58](https://user-images.githubusercontent.com/6061595/54935342-685d3f00-4f20-11e9-95fe-a56f5ba04440.png)

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/6ce1405e6847eed3b88064931a7167cdfa9f1d9d
