### ISSUE TITLE
Component Modal error: You are using the runtime-only build of Vue

### ISSUE THREAD

**Issue by fayazara** [buefy/buefy#1302]
### Overview of the problem
I have copied the exact same snippet for Modal > Component from the Buefy docs, but it does not work

**Buefy** version: [0.7.3]
**Vuejs** version: [2.6.6]
**OS/Browser**: Ubuntu 18.04/Chrome

### Description

Error in console after I click on button to open the Modal
```
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <ModalForm>
       <BModal>
         <Modal>
           <App> at src/App.vue
             <Root>
```

### Expected behavior

Component modal needs to be shown
### Actual behavior

Error mentioned above in the description

**Comment by fayazara** [comment]
![image](https://user-images.githubusercontent.com/15716057/55051311-8c349800-507a-11e9-8f60-d57569821bbb.png)

Here is what happens when I click on the modal.

**Comment by yxngl** [comment]
https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

The error already explains you need to use the full build for templates that are not precompiled.

**Comment by italomaia** [comment]
Could this be packaging problem? https://github.com/nuxt/nuxt.js/issues/1142
