### ISSUE TITLE
[buttons] Spacing issue with icons in buttons

### ISSUE THREAD

**Issue by david-wg2** [buefy/buefy#1303]
It should be possible to create a button with an icon inside. The code should probably look like this: 

```html
<button class="button">
    <b-icon icon="plus"></b-icon>
    Add new
</button>
```

This code results in a broken UI currently (text/icon overlap):

![Screenshot 2019-03-28 at 16 50 34](https://user-images.githubusercontent.com/36410074/55171986-a1dcb700-5179-11e9-9fee-df4b83f48feb.png)

Code to reproduce:
https://codepen.io/anon/pen/VRJoEe?&editable=true&editors=101

**Comment by yxngl** [comment]
Wrap "Add new" with <span>.
Maybe that's why some people want Button component to handle things like this.

**Comment by david-wg2** [comment]
Thanks. I'm definitely in favor of simple components like `<b-button>`.

Writing: 

```html
<b-button icon-left="plus">Add new</button>
```

Is a lot nicer than:

```html
<button class="button">
    <b-icon icon="plus"></b-icon>
    <span>Add new</span>
</button>
```

**Comment by jtommy** [comment]
Ok, i'm going to add simple Button component

**Comment by shelru** [comment]
> Ok, i'm going to add simple Button component

Why doc haven't any examples bout hooking event's via buefy?
`showModal() {
                this.$modal.open({
                    parent: this,
                    component: ModalForm,
                    hasModalCard: true,
                    // canCancel: false,
                    events:{
                        'close': this._OnClose(),
                    }
                    // onCancel: this._OnClose(),
                })
            },
            _OnClose() {
                console.log('Closing Stage Modal');
            },`
_OnClose calling on modal opening :/

**Comment by GopherJ** [comment]
Exciting! We also need `b-button`.

**Comment by jtommy** [comment]
New button component!! https://github.com/buefy/buefy/commit/c73c5daa97dd2c028ead59adb0c29ca389737b4a
