### ISSUE TITLE
b-datepicker enhancement

### ISSUE THREAD

**Issue by bathyscaaf** [buefy/buefy#1305]
### Description

This is a feature request.  I would like the option of being able to open the b-datepicker via a custom button --  the trigger would contain a slot which I could use to replace the input field.

**Comment by yxngl** [comment]
I think you could just implement it by using a button to toggle the state of `v-show` of an inline datapicker.

**Comment by bathyscaaf** [comment]
That works well for desktop, but by setting the b-datepicker to "inline" you lose the modal-style calendar on mobile, which I definitely need.

**Comment by jtommy** [comment]
#1248

**Comment by MelvinFrohike** [comment]
Sorry for resurrecting this feature request. I would very much like to see this enhancement and don't see how #1248 addresses this.
