### ISSUE TITLE
v-model

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1308]
add .trim support.
It's not instantly update b-input, only after start typing.

**Comment by jtommy** [comment]
Modifiers don't work using custom components https://github.com/vuejs/vue/issues/3666

**Comment by shelru** [comment]
Work's.
But there are lil bug.
They work always, but input doesnt update instantly, only when i start typing another text.
Check it:
```
{{szPassword}}
<b-field>
                            <b-input placeholder="Пароль" password-reveal v-model.trim="szPassword" type="password" autocomplete="off" novalidate></b-input>
                        </b-field>
```
@jtommy

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/55290851-8d9ef100-53e9-11e9-98be-f1ee2a02b00b.png)
After typing it's gonna trim.
![image](https://user-images.githubusercontent.com/9306996/55290857-9bed0d00-53e9-11e9-8bdc-903887cdcbe8.png)
