### ISSUE TITLE
b-switch label `margin-right` missing with other controls

### ISSUE THREAD

**Issue by GopherJ** [buefy/buefy#1309]
### Overview of the problem

I set already `grouped: true` for `b-field`, we can see the margin if b-switch doesn't have a label, but cannot see the margin if we add the label text.

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: firefox

### Steps to reproduce

```vue
<b-field grouped>
    ...
    <b-switch
          true-value="allow"
          false-value="deny">
          Status <!---we cannot see the margin-right to BInput if we have this text label-->
    </b-switch>
    <b-input type="text" expanded></b-input>
</b-field>
```

### Expected behavior

margin-right

### Actual behavior

no margin-right

**Comment by GopherJ** [comment]
I know it's a small problem and I can fix it on my side, but for improving `buefy` which is highly used in my company for differents projects. I still post it here.

Great thanks for this framework.

**Comment by jtommy** [comment]
@GopherJ Did you try to wrap `b-switch` into `<b-field>` or `<div clas="control">` ?

**Comment by GopherJ** [comment]
```vue
<b-field grouped>
    ...
    <div class="control">
    <b-switch
          true-value="allow"
          false-value="deny">
          Status <!---we cannot see the margin-right to BInput if we have this text label-->
    </b-switch>
    </div>
    <b-input type="text" expanded></b-input>
</b-field>
```
@jtommy like this? there is still no margin-right, I mean when I remove the text `Status` it works fine but when I add it there is no margin-right anymore.

**Comment by jtommy** [comment]
There is margin-right now https://codepen.io/anon/pen/zXYNrv?&editable=true&editors=101

**Comment by GopherJ** [comment]
@jtommy Sorry, my bad, this time it works but another problem occurs, `BInput` and `BSwitch` are not at the same baseline and also it's not elegant enougth to write a `div.control`.

Thanks for your reply!

**Comment by GopherJ** [comment]
My temporary fix is to add:

```scss
.switch + .control {
    margin-left: 0.75rem !important;
}
```
