### ISSUE TITLE
Always show detailed table?

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#1310]
### Overview of the problem

**Buefy** version: 0.7.3
**Vuejs** version: 2.5.17
**OS/Browser**: Chromium (latest)

### Description

`opened-detailed = []` needs to be filled with keys, is it possible to always show the detail template for each entry without the need of specifying each 'ID' (`detail-always-shown`)?

Thanks!

### Steps to reproduce

1. Add `detailed` and `detail-key="id"`
2. Fill `:opened-detailed`

### Expected behavior

Always show entry details

### Actual behavior

You need to fill an array

**Comment by wanxe** [comment]
Now only can be possible providing an array of ids. I'm not sure if it is the most common use case. We can consider to add this feature on the future, but I think that there are too much props on the tables right now. By the moment you just simply use a map of your ID's or just change the design of the rows if you want to keep the rows opened all the time.

**Comment by francoism90** [comment]
As workaround I simple took `is_published` (bool -> always true) of each data-entry and simple use the following as `b-table` props:
```
:opened-detailed="[true]"
detailed
detail-key="is_published"
```

It works fine, every entry is being shown, exactly what I wanted. :)
I haven't tried that many data-entries, but so far it seems to work/load fine.

However I do agree using ID's would be more suitable.

**Comment by wanxe** [comment]
Yest that is possible, but not intentional so may be I'm gonna fix the detailed rows to break this "feature" and bother you a little haha

**Comment by francoism90** [comment]
@wanxe Hopefully not for a while. :smile:

**Comment by FlorianChretien** [comment]
Hi ! 

It will be great to have this feature if possible "openDetailSRow()" and closeDetailSRow()"

Thank you <3

**Comment by jtommy** [comment]
@FlorianChretien there is already a method that you can use by refs

**Comment by FlorianChretien** [comment]
@jtommy For open all details and close all details ?

**Comment by jtommy** [comment]
Only one, you should loop for each row

**Comment by bearkfear** [comment]
I have a table that is dinamic. I need to props all the sub-tables to open that?
