### ISSUE TITLE
b-icon not rendering icons

### ISSUE THREAD

**Issue by amineharbaoui** [buefy/buefy#1312]
**Buefy** version: [0.7.3]
**Vuejs** version: [2.6.6]
**FontAwesome** version [5.8.1]
**OS/Browser**: Chrome/Firefox

When I try using the code example from the documentation to display some icons, nothing to show but when I use directly a fontAwesome icon it works fine . is this a bug or i missing a part here ?

**Comment by jtommy** [comment]
@amineharbaoui Are you setting the icon pack in the constructor options ?

**Comment by amineharbaoui** [comment]
No, Thank you for the quick reply, that was the problem
