### ISSUE TITLE
[Feature Request] Add change sequence of confirm button

### ISSUE THREAD

**Issue by smparkgw** [buefy/buefy#1315]
Are you willing to add change sequence of confirm button?

Now, buefy confirm button is 'NO | YES'.
I want to change 'YES | NO'.

Can you do this?
Or, is there a way I can do it?

**Comment by shelru** [comment]
Open sources, node_modules/buefy/src/components/dialog/Dialog.vue, find `<footer class="modal-card-foot">` and change order.
