### ISSUE TITLE
New icon pack support or empty icon pack support

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1317]
Add support for https://www.npmjs.com/package/flag-icon-css
or add support for empty pack for a custom class only use.

```
<b-icon pack=" " class="media-left" size="is-medium" :custom-class="`flag-icon flag-icon-${lang.flag}`"></b-icon>
```

like dat

**Comment by shelru** [comment]
Also i can't get why sizes of icon's is different on button and on media.
![image](https://user-images.githubusercontent.com/9306996/55675767-1204de80-58d8-11e9-9365-9a8cee0bc891.png)
```
 <div class="media">
                                    <b-icon pack=" " class="media-left" size="is-medium" :custom-class="`flag-icon flag-icon-${lang.flag}`"></b-icon>
                                    <div class="media-content">{{lang.title}}</div>
                                </div>
```

```
 <button class="button is-primary" type="button" slot="trigger">
                            <b-icon size="is-medium" :custom-class="`flag-icon flag-icon-${language[$i18n.locale].flag}`"></b-icon>
                            <span>{{language[$i18n.locale].title}}</span>
                            <b-icon icon="caret-down"></b-icon>
                        </button>
```

**Comment by jtommy** [comment]
@shelru At the moment i don't think to support that specific pack. About icon size please check new button component https://github.com/buefy/buefy/blob/dev/src/components/button/Button.vue

**Comment by shelru** [comment]
@jtommy it's dev pack, can u release it, for npm.
