### ISSUE TITLE
Fix for position validator

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1318]
```
position: {
                type: String,
                validator(value) {
                    return [
                        'is-top-right',
                        'is-top-left',
                        'is-bottom-left'
                    ].indexOf(value) > -1
                }
            },
```

must be 

```
position: {
                type: String,
                validator(value) {
                    return [
                        'is-top-right',
                        'is-top-left',
                        'is-bottom-left',
                        'is-bottom-right',
                    ].indexOf(value) > -1
                }
            },
```

i know that by default it is bottom-right, but i lost 10 minutes with this little typo :/

**Comment by shelru** [comment]
That's dropdown component.

**Comment by jtommy** [comment]
Please you should follow dropdown docs

**Comment by JMDC-SUN** [comment]
I set  dropdown's position dynamic.

> :position="position" 

how to set position to default (bottom-right)?
When I set position to 'is-bottom-right', the warning accrued

>[Vue warn]: Invalid prop: custom validator check failed for prop "position".

**Comment by jtommy** [comment]
Bottom right is the default (null value) but I might add it in the validator anyway
