### ISSUE TITLE
An container property for Dialog

### ISSUE THREAD

**Issue by sowrensen** [buefy/buefy#1319]
This is more of a feature request. Dialog component should have an `element` property to customize like **Snackbar** and **Loading**.

**Comment by jtommy** [comment]
What element do you mean ?

**Comment by sowrensen** [comment]
My bad. I intended to write `container`, wrote `element` instead. :(

**Comment by jtommy** [comment]
Why do you need it ?

**Comment by sowrensen** [comment]
Exactly for the same purpose the container property serves for *Snackbar* and *Loading* component. I want to show the *Dialog* on a particular element, not on the whole viewport.

**Comment by zeevin** [comment]
@jtommy need the same option to avoid css conflicts

**Comment by aembler** [comment]
I need this for CSS scoping: want to include influence the z-index of the .dialog class – but only if it comes within my custom container. 

FWIW, a global `defaultDialogCustomClass` config option would also solve this (if the default custom class could be appended to all modal/dialog boxes automatically.)

**Comment by pappu687** [comment]
@jtommy Currently the Dialog component is appended to <body>. This becomes a problem when you want to use buefy in Wordpress plugin development for example. If you have scoped css wrapper for plugin's view, the dialog does not render within the view, rather goes outside of the view - making it unusable. 

So a parent element or container property will be really useful. 

Let me know if you need a screenshot of the problem, i can supply.
