### ISSUE TITLE
Pagination bad behavior

### ISSUE THREAD

**Issue by TheTrigger** [buefy/buefy#1321]
Making 4 pages in a b-table we loose the third button. This is not smart since it occupies the same space. So to show the page n 3 i have to first load the second or fourth page. That's annoying if it's async table.

![image](https://user-images.githubusercontent.com/6072718/56042802-2f083a00-5d3c-11e9-843c-06de26ff819c.png)
![image](https://user-images.githubusercontent.com/6072718/56042827-3deeec80-5d3c-11e9-916e-0a3e2dc983bf.png)

Please make buttons hide only if there are only 2 or more pages to hide.
Thanks mate.

**Buefy** version: [0.7.3]

**Comment by service-paradis** [comment]
@TheTrigger 
Created a PR for this (#1529). Maybe it will be part of 0.8.0 since it is a breaking change.

**Comment by service-paradis** [comment]
@jtommy 
This issue can be closed. Fixed in the next release.
