### ISSUE TITLE
Table inline editing

### ISSUE THREAD

**Issue by schantanu** [buefy/buefy#1322]
**Overview of the Feature**
Buefy version: 0.7.1
Vuejs version: 2.9.6
OS/Browser: Chrome

**Description**
In tables, is there a way to do inline editing on a cell, something similar to Vuetify?
https://vuetifyjs.com/en/components/data-tables#inline-editing

**Comment by jtommy** [comment]
You might listen click event on row or wrap your column in a container and listen on click. After that you'll open a dialog or as you want

**Comment by camillo777** [comment]
> You might listen click event on row or wrap your column in a container and listen on click. After that you'll open a dialog or other component

Hello, is it possible to have a little sample?
Is it possible to detect click on a single cell instead on the entire row?
Thank you

**Comment by ab623** [comment]
Do you think it's worth me building this directly into the table component, as a new feature?

**Comment by billingb** [comment]
> Do you think it's worth me building this directly into the table component, as a new feature?

Can't speak for maintainers, but I just came here looking for this feature.

**Comment by Webarkitekt** [comment]
Yeah it would be an awesome feature :)

**Comment by hshrews** [comment]
> Do you think it's worth me building this directly into the table component, as a new feature?

Also wanting this feature!

**Comment by jtommy** [comment]
@hshrews you can using the default scoped slot

**Comment by stumpin** [comment]
@ab623 This would be a great feature

**Comment by MentalGear** [comment]
Would be awesome.

**Comment by BillelSahouli** [comment]
Hello, Buefy have native methods for edit() delete() update() in the b-table ? 
Thanks

**Comment by stumpin** [comment]
Huh
