### ISSUE TITLE
Container on toast

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1323]
Seems doesnt work properly.
Also doesn't clean div after close.
![image](https://user-images.githubusercontent.com/9306996/56109800-26457d00-5f63-11e9-8618-d46f8b2f9ffb.png)

Also loading page component isFullPage doesn't work with modal's. Overlay take all all page.
![image](https://user-images.githubusercontent.com/9306996/56110036-0cf10080-5f64-11e9-99bf-2c5cf32efe16.png)

**Comment by shelru** [comment]
https://u.to/q00gFQ code

**Comment by shelru** [comment]
Loading doesn't work with custom element's, like forms.
But work's with button.
E.x: `js <button ref="lmd" `

**Comment by shelru** [comment]
Ok, now 
```HTML 
<div class="modal-card" style="width: auto;" ref="lmd">
```
work, but 
![image](https://user-images.githubusercontent.com/9306996/56110553-0499c500-5f66-11e9-9f06-1afed5c9136d.png)
this button is clickable

**Comment by shelru** [comment]
So.
Can you implementate ToastProgrammatic?

**Comment by shelru** [comment]
We need closable(programatic) snackbar.
https://github.com/buefy/buefy/issues/505

Also if you can fix dom el removing after snackbar query is end.
@rafaelpimpa

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/56111127-f3ea4e80-5f67-11e9-8464-5f5ddd7737a8.png)
Removing z-index - fix loading button's clickable.

**Comment by shelru** [comment]
So.
It's must be normal style.
some thing like this:
```js
let ptr = this.toast.create();
ptr.config({isFullPage:...,anotherprop:...})
ptr.open();
ptr.close();
ptr.destroy();
```
That better than now.

**Comment by shelru** [comment]
Lol. No comment's, no fixes, ok. Nice maintainer. @rafaelpimpa check it out.

**Comment by jtommy** [comment]
@shelru I'm sorry, I wrote a comment but maybe I didn't confirm.
Anyway you ask about programmatic toast and there is already that component, don't you ?

**Comment by shelru** [comment]
Also 'bout z-index on eye icon and Loading component, xD

**Comment by jtommy** [comment]
Your issue describe a toast issue at the start, you cannot open an issue for more problems because it's no easy for us check all.
