### ISSUE TITLE
Rounded input with addon is not rounded in 0.7.4

### ISSUE THREAD

**Issue by duckness** [buefy/buefy#1324]
### Overview of the problem

**Buefy** version: 0.7.4
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10/Chrome

### Description

Rounded input with addon is not rounded in 0.7.4, 0.7.3 does not have this issue.

![chrome_2019-04-15_14-21-56](https://user-images.githubusercontent.com/6380270/56111470-ab905800-5f8a-11e9-9939-13152696e264.png)

This is caused by 0.7.4 having a `<p class="help">` for some reason.

![vivaldi_2019-04-15_14-29-53](https://user-images.githubusercontent.com/6380270/56111579-117cdf80-5f8b-11e9-8031-4f722b214867.png)

### Steps to reproduce

0.7.3 https://codepen.io/anon/pen/JVrLBz
0.7.4 https://codepen.io/anon/pen/pBWLZd

**Comment by jtommy** [comment]
@duckness Yes I fixed it yesterday, i'll release soon

**Comment by irongollem** [comment]
I encountered this same issue. Not just for input fields, all grouped items such as buttons etc. lost their rounding on the right side.

**Comment by jtommy** [comment]
Next week I think to release the new version
