### ISSUE TITLE
error when i put the element <b-button>

### ISSUE THREAD

**Issue by helderjnpinto** [buefy/buefy#1326]
### Overview of the problem

**Buefy** version: [^0.7.3]
**Vuejs** version: [^2.6.6]
**OS/Browser**: ubuntu 18, chrome Version 73.0.3683.103 (Official Build) (64-bit)

### Description
i can add all components but     \"<b-button   not
i get this error, 

vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <b-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <GlobalState> at src/views/GlobalState.vue
       <App> at src/App.vue
         <Root>

### Expected behavior

show the component 

### Actual behavior

get the error above

**Comment by jtommy** [comment]
You have to update to 0.7.4
