### ISSUE TITLE
Double instance of Vue when importing buefy

### ISSUE THREAD

**Issue by Livijn** [buefy/buefy#1327]
### Overview of the problem
Importing buefy cause double instances of Vue.

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: macOS + Chrome

### Description
When I import buefy using `import Buefy from 'buefy';` my console gets double outputs of `You are running Vue in development mode.`. This leads me to believe that Vue is somehow loaded two times.

![](https://i.gyazo.com/42d06e575bcf6fb49eb814e733b4fc9f.png)

I am importing it globally and applying it with `Vue.use(Buefy);`.

**Comment by jtommy** [comment]
I don't understand well, why should it a Buefy issue ?

**Comment by Livijn** [comment]
Well, without Buefy there is only one output in the log. So it's only happening when I import Buefy.

**Comment by adrlen** [comment]
That's because buefy's vue dependency is 2.5 and you must be having 2.6 in your project.

**Comment by Livijn** [comment]
That is true, I have `"vue": "^2.6.10"` in my `package.json`. Then I import them in this order:

    import Vue from 'vue';
    // ...
    import Buefy from 'buefy';
