### ISSUE TITLE
table pagination icon size

### ISSUE THREAD

**Issue by patie** [buefy/buefy#1329]
### Overview of the problem

**Buefy** version: 0.7.4
**Vuejs** version: 1.2
**OS/Browser**: MacOS

### Description

Its possible to set fontawesome size for pagination icon? i see there fa-lg always.. i need fa-md

**Comment by jtommy** [comment]
@patie At the moment there is only `size` prop but it'll change all pagination component size (buttons, text, etc...)

**Comment by patie** [comment]
@jtommy this will not be a problem in this case, can you show me example how to use this so also table paginations will be changed? thank you

**Comment by jtommy** [comment]
Did you try pagination-size prop?

**Comment by patie** [comment]
i think this prop is only about padding of pagination buttons

**Comment by patie** [comment]
this is not problem of table or pagination, but icons, which default size for fontawesome is lg and can be only larger, not smaller, see https://github.com/buefy/buefy/blob/dev/src/components/icon/Icon.vue#L68

**Comment by francoism90** [comment]
@patie Why not simple remove `this.addFAPrefix('lg')`? Would that fix the problem?
