### ISSUE TITLE
Tooltip on low resolution

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1330]
![image](https://user-images.githubusercontent.com/9306996/56282815-11aee380-6121-11e9-8fd0-5f374feebf85.png)
![image](https://user-images.githubusercontent.com/9306996/56282845-268b7700-6121-11e9-9eb5-6e19e2da4c12.png)

From official example.
https://buefy.org/documentation/table/
Custom header's.

**Comment by shelru** [comment]
So, i think you must refactor some code, because original tooltips(also from buefy work's well).
https://github.com/buefy/buefy/pull/1328 also.
Create new branch, where we can download beta .js for testing.

**Comment by jtommy** [comment]
I close it because I have to refactor tooltip component soon I hope https://github.com/buefy/buefy/issues/1316

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/56340102-e8925f80-61c1-11e9-95e5-aed7503ffe73.png)
Also if you can, refactor this too.
