### ISSUE TITLE
destroy all component in <b-tab-item>

### ISSUE THREAD

**Issue by virtuOS1** [buefy/buefy#1331]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.5.16]
**OS/Browser**: Windows10

### Steps to reproduce

https://codepen.io/virtuos/pen/wZyJNd
1. input any text in tab "One"
2. set tab "Two"
3. set tab "One". Input is clear.

In version 0.7, internal components are preserved.

**Comment by jtommy** [comment]
@virtuOS1 What's the expected behaviour ?

**Comment by virtuOS1** [comment]
@jtommy 
I expect that component data inside <b-tab> to be saved when switching tabs, as it happens in version 0.7.3
Example: https://www.youtube.com/watch?v=fQRbv-okFeE

**Comment by jtommy** [comment]
You're right, I'll add a prop to choose the  behaviour (default like previous version)

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/863ab274d76e549db647cda3f3a89ad6edb80f23
