### ISSUE TITLE
Question - Horisontal scroll bar for b-table

### ISSUE THREAD

**Issue by vnt-83** [buefy/buefy#1333]
### Overview of the problem

**Buefy** version: [0.7.3]
**Vuejs** version: [2.5.2]
**OS/Browser**:

### Description

How can add horisontal scroll bar on bottom b-table?

**Comment by jtommy** [comment]
@vnt-83 Add a your custom class to table `class="my-table` and the `.my-table.table-wrapper {
    overflow: auto !important;
}`

**Comment by kenichii** [comment]
how about adding scroll on the tbody?
