### ISSUE TITLE
Could not find a declacation file for module buefy/dist/components/notification

### ISSUE THREAD

**Issue by patie** [buefy/buefy#1334]
### Overview of the problem

**Buefy** version: 0.7.4
**Vuejs** version: 2.6.10
**OS/Browser**: MacOS

### Description

Im using typescript, when i try use notification programmatically i get `Could not find a declacation file for module buefy/dist/components/notification`

![](https://i.paste.pics/05d15fba210dda646edbb5985e4b905f.png)

**Comment by jtommy** [comment]
Take a look at https://github.com/buefy/buefy/issues/990

**Comment by patie** [comment]
probably doesnt work, or im doing something wrong.. can you please tell which comment is relevant and if this can be fixed in soon future please? thank you

**Comment by rajsinghUSA** [comment]
@patie Did you manage to figure out a way to accomplish this? I am running into the exact same issue in trying to use a Buefy component with `axios.interterceptors`.
