### ISSUE TITLE
Datapicker

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1337]
Set 

month-names to September, or another one. 
`month_names:["September"],`
```JS
 <b-field label="Select a date">
                            <b-datepicker
                                    placeholder="Click to select..."
                                    :min-date="minDate"
                                    :month-names="month_names"
                                    :max-date="maxDate">
                            </b-datepicker>
                        </b-field>
```
Select some date on september, it will be january.
![image](https://user-images.githubusercontent.com/9306996/56362034-eb10ab80-61f9-11e9-97cb-a5dac8d7a7f9.png)

**Comment by shelru** [comment]
To fix add selectable months, selectable days, selectable years.
min/max dates doesn't work as this.

**Comment by jtommy** [comment]
@shelru What are the values of month_names variable?

**Comment by shelru** [comment]
Stop. It's not for months? It's just names?
So, can you improve it, with this?

>To fix add selectable months, selectable days, selectable years.
min/max dates doesn't work as this.

**Comment by shelru** [comment]
Also why it's must be Date?
![image](https://user-images.githubusercontent.com/9306996/56383589-3b543180-622b-11e9-87c5-e0d4b7eefd5e.png)
Why i can't put string(e.x 03-03-1993, 03.03.1993, 03/03/1993 etc)?

**Comment by jtommy** [comment]
I already told you, please you don't open a issue with different questions, there is a Discord channel.

**Comment by shelru** [comment]
F8ck. It's not a question, it's a bug report's :/
One more bug.
https://buefy.org/documentation/datepicker
Go to #Editable (non readonly)
Select some date. Ex. 04.01.2020, then change year, by inputting, to 2022, date changes to 01.04.2022, then write 2023, date changes to 04.01.2023 ...

**Comment by jtommy** [comment]
You have to write a custom formatter e parerser, please read api docs

**Comment by shelru** [comment]
There are no example of formater in doc's.

**Comment by jtommy** [comment]
@shelru https://codepen.io/anon/pen/pBVKjr?editors=1010, it's a simple example

**Comment by shelru** [comment]
i think you must add it into doc's
