### ISSUE TITLE
unselect Radio Button on click

### ISSUE THREAD

**Issue by erwanpoupard** [buefy/buefy#1338]
### Overview of the problem
how I could unselect a b-radio-button on click (if the v-model is the clicked b-radio-button value) ?

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: windows10/chrome

### Description

i would like ton unselect the radio button on click. But we have only the input event. So when i click on a radio button already selected, nothing happen. 
With a native.click, i can reach the input value, but its quite random : 
- if i click on text i need to test target.parent, 
- if i click outside text, i need to test target.children

Have you any clever idea ?

**Comment by shelru** [comment]
Can you show codepen?

**Comment by shelru** [comment]
```js
<b-button type="is-danger" @click="inputvmodel = null"
            :disabled="!inputvmodel" class="field" icon-left="close">
            <span>Clear selected</span>
        </b-button>
```
I think it's must work.

**Comment by shelru** [comment]
Or if you wanna radio button, which gonna clear current v-model value, there an strategy example:
```html
<b-radio v-model="radio" native-value="value" @input="clicked">
   Clear
</b-radio>
```
```js
methods:{
    clicked(){
      this.$nextTick(() => {
	this.radio = null;
    });
}
```

**Comment by shelru** [comment]
https://codepen.io/anon/pen/ZZojRE
example.

Add this to docs.

**Comment by shelru** [comment]
One more
https://codepen.io/anon/pen/MRGdqB

**Comment by erwanpoupard** [comment]
thank you @shelru, but thats not what i want :) 
i've made a pen to illustrate : 

https://codepen.io/erwanpoupard/pen/ROyRyQ

as you can see, the component is the **b-radio-button**, not the b-radio. 

i would like to unselect and reset the v-model value on click on the b-radio-button if the value equal v-model. 

But with the native click event, its pretty hard, and random because the dom could be change in futur.

**Comment by shelru** [comment]
> reset the v-model value on click on the b-radio-button **if the value equal v-model**

Can you show pseudo code?

**Comment by erwanpoupard** [comment]
@shelru sure,

imagine 3 b-radio-button with a value as v-model , 
- each b-radio-button has a native value : val1, val2, val3
- initial value = val1
```
@click on b-radio-button(nativeValue) {
  if (nativeValue === value) {
    value = ''
  }
}
```
so, if i click on val2, or val3, the value change for the native-value (val2 or val3)
But if i click on val1 the value is set to null, and the b-radio-button is unselect.

**Comment by shelru** [comment]
Yes, that's strange.

**Comment by shelru** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/radio/RadioButton.vue#L28
Seem's like casting problem.

**Comment by erwanpoupard** [comment]
Sorry but what i need is actually a checkbox button ! thank you for your help

**Comment by RenanRSilva** [comment]
@erwanpoupard Did you find a solution?

**Comment by slidenerd** [comment]
None of the above solutions work, anyone got an idea how to reset the radio button? Taking it as b-radio-button, which event to use @input or @click or @click.native?
