### ISSUE TITLE
Upload with file name addon: border radius and alignment

### ISSUE THREAD

**Issue by yxngl** [buefy/buefy#1339]
### Overview of the problem

**Buefy** version: [0.7.0 - 0.7.4]

### Description

The file name addon after selecting a file for upload has border radius on the left and does not perfectly align.

### Steps to reproduce

Select a file in upload, using first example in the doc.

### Expected behavior

**Red border** is added below for clarity.
![image](https://user-images.githubusercontent.com/1696853/56434930-498e6600-629c-11e9-8c03-8616fe3d3b3e.png)

With temp fix
```css
.file-name {
  margin-left: 1px;
  border-radius: 0 4px 4px 0;
}
```

### Actual behavior
![image](https://user-images.githubusercontent.com/1696853/56434956-5e6af980-629c-11e9-9b6c-11e827a0a7a9.png)

**Comment by jtommy** [comment]
It is only an example in the docs and anyway it is a Bulma class

**Comment by yxngl** [comment]
Alright. I see that is not really part of b-upload.

Then I tried to set it up like Bulma does. But it seems file upload is not wrapped in a field in Bulma, and it uses a `.file .has-name` wrapper for the file name addon. While in Buefy field wrapper brings `.has-addons`.  I could get the desired result without a `b-field` wrapper: https://codepen.io/yxngl/pen/xejQZb?&editable=true&editors=101

But I would also like to set the upload smaller by adding `.is-small` to the `.file` wrapper. Currently the `b-upload` has a `control` class, which sets `font-size` and cancels out the effect of `.is-small`.

So, is it necessary to put `b-upload` in `b-field`? and then is the class `control` useful?

**Comment by jtommy** [comment]
A refactor could be a breaking change yet
