### ISSUE TITLE
ClockPicker doesn't display on mobile.

### ISSUE THREAD

**Issue by hungnv132** [buefy/buefy#1340]
### Overview of the problem

**Buefy** version: v0.7.4
**Vuejs** version: ^2.6.6
**OS/Browser**: Chrome

### Description

ClockPicker doesn't display on mobile.

**Comment by jtommy** [comment]
It's been fixed https://github.com/buefy/buefy/commit/2697c63a5baddda835a6a06b84671603fbfff44c.
