### ISSUE TITLE
b-input doesn't work with vue-the-mask in safari

### ISSUE THREAD

**Issue by amstiel** [buefy/buefy#1342]
### Overview of the problem

**Buefy** version: [0.7.3]
**Vuejs** version: [2.6.10]
**OS/Browser**: 
macOS v. 10.13.6
Safari v.12.1 (13607.1.40.1.5)

### Description

V-mask directive doesn't work properly on b-input element in Safari. 
Other browsers are fine. 
You can see vue-the-mask in event listeners at screenshot below, but if you set breakpoint on it and start debugging, you'll see masked value first, but after `flushSchedulerQueue` function in `vue.runtime` it's remain unmasked.
Using native `<input>` instead of `<b-input>` element with v-mask works great. Mb problem in passing attributes to `<b-input>`'s internal native `<input>`.

![Screen Shot 2019-04-24 at 17 04 46](https://user-images.githubusercontent.com/9428948/56639092-31ab4d80-66b3-11e9-8e70-1847c4ad5821.png)

### Steps to reproduce

1. Install latest `vue-the-mask` package
1. Import `mask` as directive or register it globally
1. Pass `v-mask` attribute to `<b-input>`
1. Try to input smth in Safari

### Expected behavior

Input masks works fine in all browsers

### Actual behavior

Input masks works fine in all browsers except Safari

**Comment by jtommy** [comment]
Did you try using a native input instead of bInput ?

**Comment by amstiel** [comment]
@jtommy So i did :) But I thought it would be nice to report a bug

**Comment by jtommy** [comment]
Unfortunately I cannot test it on Safari so any public fix is welcome ;)

**Comment by bfabbri** [comment]
@amstiel have you solved this issue?

**Comment by amstiel** [comment]
@bfabbri Nope. Just used native input with bulma classes and added my custom handlers on it.
