### ISSUE TITLE
b-table checkable disable or hide check-all

### ISSUE THREAD

**Issue by cvgeldern** [buefy/buefy#1344]
I would like to have the option to disable or hide the check-all checkbox in a `b-table` that has the `checkable` property set to `true`.

My use case is that checked rows exclude other rows from being checked using `is-row-checkable`.
![afbeelding](https://user-images.githubusercontent.com/8122437/56651614-bd0fe900-6689-11e9-89ac-d08f0dec5ad8.png)
I got that working, no problem, but the select-all checkbox does not play with this construction.
![afbeelding](https://user-images.githubusercontent.com/8122437/56651798-22fc7080-668a-11e9-95bb-44e85b3c4570.png)
Off course it works if checkable rows are disabled beforehand, but will often not be the case.

To prevent this from happening, I'd like to be able to disable or hide the check-all checkbox in the header of the checkable column.

**Comment by jtommy** [comment]
@cvgeldern I'll add a new prop `header-checkable` (default true) so you can hide it
