### ISSUE TITLE
Datepicker dropdown is opened when v-model is changed

### ISSUE THREAD

**Issue by musashimm** [buefy/buefy#1347]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.10]
**OS/Browser**:

### Description

When v-model is changed the dropdown is opened.

### Steps to reproduce

             <b-datepicker
                v-model="date"
                placeholder="Kliknij, aby wybrać..."
                icon="calendar-day"
                :first-day-of-week="1"
                :day-names="dayNames"
                :month-names="monthNames"
              />

1. Set date in data to null
2. Change date via Vue DevTools

### Expected behavior

DatePicker dropdown should stay closed.

### Actual behavior

DatePicker dropdown is opening.

**Comment by musashimm** [comment]
I think the problem is in watchers:

            dateSelected(value) {
                const currentDate = !value ? this.dateCreator() : value
                this.focusedDateData = {
                    month: currentDate.getMonth(),
                    year: currentDate.getFullYear()
                }
                this.$emit('input', value)
                this.toggle()
            },
            /**
             * When v-model is changed:
             *   1. Update internal value.
             *   2. If it's invalid, validate again.
             */
            value(value) {
                this.dateSelected = value
                !this.isValid && this.$refs.input.checkHtml5Validity()
            },

When value is changed dropdown is toggled without checking if its active or not.

**Comment by pflirae** [comment]
I also observ that problem with a simple code as this:
          <BField class="column is-2 is-marginless" label="Fecha">
            <BDatepicker v-model="fecha_recepcion_flt_rec" />
          </BField>

where fecha_recepcion_flt_rec = new Date() is the initialization value for the variable

**Comment by robtesch** [comment]
I'm having the same issue. Could be related to the new `open-on-focus` prop, even though i explicitly set it to false (the default, but figured it might help).

**Comment by jtommy** [comment]
@musashimm @pflirae I think there is something to check and fix but i'm not able to replicate your issues https://codepen.io/anon/pen/MRxEOz?editors=1010

**Comment by musashimm** [comment]
You used version 0.7.4, so I checked it, and it works.
So it seems that bug came with 0.7.5 version.

**Comment by zedrdave** [comment]
@jtommy FWIW: I am also experiencing this issue. My use-case is a little complex (involves vuex and `computed` variables) and I'm still working on reducing it…

**Comment by musashimm** [comment]
So in 0.7.4 after date  setting we had:

    this.$refs.dropdown.isActive = false

In 0.7.5 we have: 

    this.toggle()

And if there is no arument the dropdown is activated:

     toggle(active) {
               if (this.$refs.dropdown) {
                   this.$refs.dropdown.isActive = typeof active === 'boolean'
                       ? active
                       : !this.$refs.dropdown.isActive
               }
           },

So toggle should be:

     toggle(active) {
               if (this.$refs.dropdown) {
                   this.$refs.dropdown.isActive = !!active
               }
           },

Please somebody confirm

**Comment by jtommy** [comment]
@musashimm there is an issue in the version number but it is the 0.7.5

**Comment by musashimm** [comment]
So I checked and in both versions changing value from template works (dropdown stays closed):

         <b-button @click="entry_at = new Date(Date.parse('2001-12-12'))">
         Change
         </b-button>

But in 0.7.5 does not, if I changing value from method fired after api request:

         methods: {
              updateForm(response) {
                 this.entry_at = new Date(Date.parse('2001-12-12'));
              }
          }

**Comment by cvgeldern** [comment]
Same issue here. After fetching data for date models, the datepicker is opened. Only in 0.7.5. Since my form contains multiple datepickers, it becomes a visual mess, because they are all opened, overlaying other elements.

**Comment by musashimm** [comment]
So in 0.7.4 its only one event: 

       input $emit by <BDatepicker>

In 0.7.5 are two more emit events 'active-change'. One with false payload next with true.

When you change from tamplete, there is only one event with false, so dropdown stays closed. 

I dont know why there is difference in handling.

Meybe its connected to isseue #1361

**Comment by jtommy** [comment]
Ok i'll fix it and input event management

**Comment by redpitbull** [comment]
You should change a this.toggle() to this.toggle(false)
it is affects for 
/*
            * Toggle datepicker
            */
            toggle(active) {
                if (this.$refs.dropdown) {
                    this.$refs.dropdown.isActive = typeof active === 'boolean'
                        ? active
                        : !this.$refs.dropdown.isActive
                }
            },
where active isn't boolean by default

**Comment by paudepaus** [comment]
Hi,

seems that in version v0.9.5 there's a regression bug and this happens again.

**Comment by aarongot** [comment]
https://github.com/buefy/buefy/pull/3257/commits/00694387da4e0505ddc84d415056007111d2762d
