### ISSUE TITLE
Column may disappear when sorting by b-table

### ISSUE THREAD

**Issue by akicho8** [buefy/buefy#1348]
### Overview of the problem

The header disappears when sorting.

![ng mov](https://user-images.githubusercontent.com/808955/56784845-8ffc3b80-682d-11e9-945f-d6be5b821c6a.gif)

**Buefy** version: 0.7.4
**Vuejs** version: 2.6.10
**OS/Browser**: macOS High Sierra / Google Chrome

### Description

This is the template part of index.vue.
I referred to the documentation of Buefy.

```
<template lang="pug">
.section
  b-table(
    :data="data"

    backend-sorting
    :default-sort="[sortField, sortOrder]"
    @sort="onSort"
    )

    template(slot-scope="props")
      b-table-column(field="title"      label="Title" sortable v-text="props.row.title")
      b-table-column(field="vote_count" label="Vote"  sortable v-text="props.row.vote_count")
      b-table-column(label="Operation") show, edit
</template>
```

This is the whole of index.vue.
https://github.com/akicho8/buefy_table_app/blob/master/pages/index.vue

However, clicking on the **Title**, **Vote** column makes the behavior strange.

```
b-table-column(label="Operation") show, edit
```

If delete the line above.
It will work normally.

![ok mov](https://user-images.githubusercontent.com/808955/56784858-98ed0d00-682d-11e9-8aff-a30878a6f48a.gif)

### Steps to reproduce

```shell
git clone https://github.com/akicho8/buefy_table_app
cd buefy_table_app
yarn
nuxt --open
```

Click the **Title** or **Vote** of the table.

### Expected behavior

Sort by clicked column.
The header column does not disappear.

### Actual behavior

Header **Title** and **Vote** columns disappear.

It will operate normally if the **Operation** column is deleted.

**Comment by jtommy** [comment]
@akicho8 please avoid v-text as you can see in the docs

**Comment by akicho8** [comment]
Thanks.
I didn't think there was a cause like that.
