### ISSUE TITLE
Date picker week number [QUESTION]

### ISSUE THREAD

**Issue by quentinlebars** [buefy/buefy#1349]
### Description

Hy,

Is it possible to view the week numberson the datepicker of buefy?
For example I post this message on April 26 and we are the week 17 of the year 2019

I would like to be able to view the week numbers on the datepicker

Thank you in advance

**Comment by omer2500** [comment]
Hi @quentinlebars  where do you exactly want to see it? next to the year and the month?
can you post an image with that addon? 
thanks!

**Comment by quentinlebars** [comment]
Hi @omer2500 personally I thought to put the number of week next week with a different writing.

Here is a screen of my idea : 

<img width="300" alt="Capture d’écran 2019-05-05 à 12 45 03" src="https://user-images.githubusercontent.com/45590817/57192774-582f7b00-6f34-11e9-96b7-69afda47b70a.png">

What do you think about my idea ?

**Comment by omer2500** [comment]
@quentinlebars it could be confusing a little bit with the dates.
@jtommy what to you think?

**Comment by jtommy** [comment]
For me it's ok but it will be disabled as default

**Comment by quentinlebars** [comment]
@omer2500 otherwise a vertical line between the week numbers of the year and the days of the month, but i think the first idea with a different color of writing is better (red font ?)

**Comment by jtommy** [comment]
Sure! I think it's enough a different colour and maybe size or style

**Comment by omer2500** [comment]
@quentinlebars funny thing! i just checked the date on my ubuntu pc
and they have that exact feature :P  https://ibb.co/sQbsbP6
i might start to work on this on this week, i hope i will be able to do that.

**Comment by jtommy** [comment]
@omer2500 cool, thanks!

**Comment by quentinlebars** [comment]
@omer2500 some news about this feature ?

**Comment by omer2500** [comment]
@quentinlebars  i almost done! im just having a bit of issues with the css of it.
if i will not get it to be ok until tomorrow i will post here what ive done maybe others will assist!

**Comment by omer2500** [comment]
Hi, so this is what i've done so far(the week numbers are in purple):

![Screenshot from 2019-05-18 02-58-43](https://user-images.githubusercontent.com/29802207/57961853-7a54d000-791a-11e9-825f-42ce57c3a2d3.png)

but as you can see i have an issue with the css and the days row,
i cant get it align correctly no matter what im doing.
also feel free to review my code! that would help me a lot.

also
these are my relevant commits for that:
[https://github.com/omer2500/buefy/commit/ee88d1ebe46e9faa04178750d5b48d834aa2f55c](url)
[https://github.com/omer2500/buefy/commit/d7b416e7d92735ea9bf4ef9f4fe2520756f3008c](url)

maybe you can help @quentinlebars @jtommy

**Comment by supportQuadra** [comment]
hi @omer2500, how are you ? Have you finished this feature? How can I help you ? When I click on your commits, i can't access.
Thanks for your answer

**Comment by service-paradis** [comment]
Hello @omer2500,
Can you create a PR with what you have done so far? I could maybe take a look it!
