### ISSUE TITLE
unpkg buefy.min.js  is not  0.7.5

### ISSUE THREAD

**Issue by hados99** [buefy/buefy#1350]
https://unpkg.com/buefy@0.7.5/dist/buefy.min.js
starts  with 'Buefy 0.7.4'

Is it right?

!-- PLEASE READ THE FOLLOWING INSTRUCTIONS -->

### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

**Comment by jtommy** [comment]
You're right but don't worry it's the 0.7.5 version! :)
