### ISSUE TITLE
Datapicker

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1354]
Read comment

**Comment by shelru** [comment]
How make datapicker disabled? Ex. no click's, no changes e.t.c.
```html
<b-datepicker readonly placeholder="Click to select..." v-model="end_date">
</b-datepicker>
```

Doesn't work.

![image](https://user-images.githubusercontent.com/9306996/56847682-4d029c80-68ef-11e9-9390-b9978194c57a.png)

When disabled='disabled' added.
```html
<b-datepicker disabled="disabled" placeholder="Click to select..." v-model="end_date" >
                        </b-datepicker>
```

Is there normal way's to styling this too?
![image](https://user-images.githubusercontent.com/9306996/56847725-f5186580-68ef-11e9-98ef-7ed3b8ee252e.png)

**Comment by jtommy** [comment]
Disabled is a Boolean prop anyway the style is the same
