### ISSUE TITLE
Password reveal icon state incorrect

### ISSUE THREAD

**Issue by Henry-W** [buefy/buefy#1355]
### Overview of the problem
Looking at other websites, it appears the icon (eye) is the wrong way round for the state of the input.

For example:

- Google shows a crossed out eye icon when the password is masked with the standard dots.
- Buefy shows a normal eye icon when the password is masked with the standard dots.

I have identified that the following line will need changing:
https://github.com/buefy/buefy/blob/fec335898e7b1e5c03847a9fae801f45c5548c3e/src/components/input/Input.vue#L164

to

`return this.isPasswordVisible ? 'eye' : 'eye-off'`

### Expected behavior

Icon to display as crossed out eye (eye-off) when password is masked.

### Actual behavior

Icon displays as normal eye (eye) when password is masked.

This is important to be consistent with other websites and to provide a good user experience.

**Comment by jtommy** [comment]
@Henry-W I think there isn't a correct or incorrect state.
For example you take a look at Adobe login, it follows same pattern of buefy

**Comment by shelru** [comment]
reveal ico z-index value must be lower than LoadingComponent z-index, i described it on https://github.com/buefy/buefy/issues/1323#issuecomment-483121923

**Comment by Henry-W** [comment]
> @Henry-W I think there isn't a correct or incorrect state.
> For example you take a look at Adobe login, it follows same pattern of buefy

Fair enough, but I think Google's version makes more sense, considering a strike out shows it's not normal and hence masked.

**Comment by service-paradis** [comment]
We could maybe add a prop `password-reveal-icons` with `['eye' : 'eye-off']` as default?
This way, someone who want to reverse the icon could change this prop without adding a breaking change to Buefy. What do you think?
