### ISSUE TITLE
<figure> padding

### ISSUE THREAD

**Issue by nordbit** [buefy/buefy#1357]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: Firefox 66.0.3

### Description

Card example from original bulma.io:
https://bulma.io/documentation/components/card/

figure element in buefy has margins added: 0 2em;

```
.content figure {
  margin-left: 2em;
  margin-right: 2em;
  text-align: center; } 
```
Now image in card has margins on both sides.

**Comment by jtommy** [comment]
It isn't a Buefy style, where did you find it?

**Comment by nordbit** [comment]
![Screen Shot 2019-04-30 at 00 26 38](https://user-images.githubusercontent.com/1248229/56930937-a7ae1b00-6ade-11e9-93d8-2c077551d6a5.png)

**Comment by jtommy** [comment]
It's a Bulma style https://github.com/jgthms/bulma/blob/ee8e0a497e59d7008ff0d49894a59f82741b92e3/sass/elements/content.sass#L98
