### ISSUE TITLE
Datepicker input 

### ISSUE THREAD

**Issue by shelru** [buefy/buefy#1358]
Comment.

**Comment by shelru** [comment]
Add support for is-static readonly provided by bulma.
![image](https://user-images.githubusercontent.com/9306996/56867415-f764e780-69f5-11e9-9b56-b8731bbe61ab.png)

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/56867462-7823e380-69f6-11e9-8f09-22b67fb77b1a.png)

No changes.
https://bulma.io/documentation/form/input/.
![image](https://user-images.githubusercontent.com/9306996/56867437-41e66400-69f6-11e9-88e0-9bca3ee7bc91.png)


https://buefy.org/documentation/datepicker/
There no optional styles support.

**Comment by jtommy** [comment]
Please can you explain your issue or request in a one message with more detail? It's no the first time that I told you about and there a few rules to follow, thanks

**Comment by shelru** [comment]
What type of details you want?
There html code and pointer to bulma doc's.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by shelru** [comment]
Overview of the problem
Buefy version: always last Vuejs version: doesn't depend on vue OS/Browser: doesn't depen on browser

Description: https://github.com/buefy/buefy/issues/1358#issuecomment-487395215
Steps to reproduce: https://github.com/buefy/buefy/issues/1358#issuecomment-487395215, https://github.com/buefy/buefy/issues/1358#issuecomment-487395215
Expected behavior: https://github.com/buefy/buefy/issues/1358#issuecomment-487395215
Actual behavior: idk, i send a screenshot's.
Try to add some another class to b-datapicker input. There no way's. I described it in https://github.com/buefy/buefy/issues/1358#issuecomment-487395520

**Comment by mikeerickson** [comment]
Yikes! I am a lurker here, but the response from @sherlu is surely terse.  I can understand his desire to have it all in one simple message, but my goodness.

**Comment by jtommy** [comment]
@mikeerickson It's no the first time and I explained to @shelru the correct behaviour here.
At least it's a free support and I'm trying the best to improve/fix/answer any request and i'm only asking to be respectful to me

**Comment by mikeerickson** [comment]
Makes good sense to me. It is unfortunate that this open source world is so “free” and those who can’t appreciate that are the ones that are often the toughest to deal with.  I took time to read through everything and I can sure see why you are reacting this way.  I should have taken the time to do so before replying, my apologies for that.

**Comment by shelru** [comment]
I only report and dont need fixes right now, although the fixes in my cases are elementary and didn't covered when designed (why?) and it is strange.

It is necessary to fix as many minor bugs between builds as possible, this is the correct way to make it perfect.

I can only suggest to create a few discussions for each of the component's, fix them and we would throw out all the errors that we notice.

**Comment by jtommy** [comment]
You could make PRs but it's no a problem if you open new issues it's more the spirit in which you used

**Comment by shelru** [comment]
You doesn't give some advice for you microclimat.
But i can just advice create general issue for each component. It's better.

**Comment by shelru** [comment]
I can't just write some shitty code for fix some issue, as you said, and that's rigth way. But idk which way of fix you can prefer.

**Comment by shelru** [comment]
Also you can configure circleci for posting artefact's after builds. (ex. for 5 minutes)
With them, we could test the finished fix without having to download gigabytes of dependencies on our PC's, it would increase the flow of those who want to fix bugs-several times.

I don't know why you or @rafaelpimpa  haven't done it so far.

**Comment by shelru** [comment]
After all, CIRCLECLI still runs the process of checking the build on the server, why not just save the result in the directory or post them to the repository on the GIT or in any branch, builds for example?
