### ISSUE TITLE
b-input changes type using v-if on mounted 

### ISSUE THREAD

**Issue by mdabydeen** [buefy/buefy#1363]
### Overview of the problem

Conditional rendering based on the `mounted` hook causes fields to change type.  

**Buefy** version: [X.X.X] 0.7.5
**Vuejs** version: [X.X.X] 2.6.10
**OS/Browser**: 

[OS]
macOS 10.14.4 Mojave

[Browser]
Google Chrome
Version 74.0.3729.108 (Official Build) (64-bit)

### Description

In my component, I've tried to inject a `hidden` field on my form, however, all the field types seems to shift in a +1 manner. Example 

```
<b-input type="email" />
<b-input type="password" />
```
became
```
<b-input type="hidden" />
<b-input type="email" />
<b-input type="password" />
```
however, on my page when I tried to enter the `email` field, it showed up as a password type. T

### Steps to reproduce

```
<template>
  <section="section"
   <b-field label="team" v-if="this.team">
     <b-input type="hidden" disabled></b-input>
   </b-field>
   <b-field label="Email">
      <b-input type="text" v-model="email"></b-input>
   </b-field>
    <b-field label="Password">
       <b-input type="password" v-model="password"/>
    </b-field>
</template>
<script>
export default {
  name: "team-user",
  data() {
    return {
       email: "",
       password: "",
       team: false
     }
  },
 mounted() {
    // do some kind of lookup 
    this.team = this.$store.getters.teamId
 }
}
</script>
```
### Expected behavior

Field is injected and works great! 

### Actual behavior

It didn't work, my email field became a password field.

**Comment by yxngl** [comment]
Can you try to add a `key` to the b-field with `v-if`?

**Comment by mdabydeen** [comment]
> Can you try to add a `key` to the b-field with `v-if`?

I did, same behaviour.

**Comment by mdabydeen** [comment]
I've found a work around for now, is to add the check to `created()` instead of `mounted()`. That works well. 

However I would still like for it to work on the `mounted` hook

**Comment by yxngl** [comment]
I couldn't reproduce your problem, maybe because the template you pasted above has some errors like the broken `section` tag and `type="text"` for the email input.
It would be great if you can have an example on CodePen or something similar.

**Comment by jtommy** [comment]
@mdabydeen Any news ?

**Comment by mdabydeen** [comment]
> @mdabydeen Any news ?

I've provided an example below

> I couldn't reproduce your problem, maybe because the template you pasted above has some errors like the broken `section` tag and `type="text"` for the email input.
> It would be great if you can have an example on CodePen or something similar

https://codepen.io/anon/pen/wbdBjd

**Comment by yxngl** [comment]
So as I expected, if you add an unique key like `key="1"` to the team `b-field`, it will solve the problem.
See https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key
https://vuejs.org/v2/style-guide/#v-if-v-else-if-v-else-without-key-use-with-caution

**Comment by mdabydeen** [comment]
@yxngl this works! thank you
