### ISSUE TITLE
customDetailRow codepen example is different from document

### ISSUE THREAD

**Issue by hados99** [buefy/buefy#1366]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [X.X.X]
**OS/Browser**: codepen example

### Description

codepen example - customDetailRow is a little different from documentation
it seems like just detail row example.
I tried by myself and I saw custom detail row works fine.

### Steps to reproduce

1. go to link - https://buefy.org/documentation/table
2. find customDetailRow section
3. click codepen
4. see customDetailRows on screen

### Expected behavior

- customDetailRow should align in table as below (document capture)

![스크린샷 2019-04-30 오전 8 09 31](https://user-images.githubusercontent.com/7829222/56932592-5a9e6900-6b1f-11e9-9c73-e8f0abcbfb3e.png)

### Actual behavior

- customDetailRow does not align in table. it is just detail row. (codepen capture)

![스크린샷 2019-04-30 오전 8 09 49](https://user-images.githubusercontent.com/7829222/56932596-5c682c80-6b1f-11e9-882b-3c1ae9d93c5b.png)

**Comment by yxngl** [comment]
Change `customDetailRow` to `custom-detail-row`
In-DOM template need to use kebab-case.
