### ISSUE TITLE
Timepicker with no picker ability

### ISSUE THREAD

**Issue by amirhkhadem** [buefy/buefy#1370]
I need the timepicker to be a time picker with no picker. I know i can use an input and set type to "time" but I would have to change lots of code. the picker option is annoying when trying to use a fast form, people rather just type in a time and not worry about the mouse click and picker option. no-picker option maybe on the time picker?

**Comment by jtommy** [comment]
I understand your need but a timepicker without a picker doesn't sound good, don't you ? You might use a input mask lib, for example cleave.js.

**Comment by amirhkhadem** [comment]
so i used an input and just passed data to an api call as a string and i didn't have to deal with that big timestamp and retrieving hour and minute and seconds. It seems like for users with fast data input the picker is cumbersome.

**Comment by amirhkhadem** [comment]
there is also an option to use input with "time" type for those who want this ability

**Comment by jtommy** [comment]
@amirhkhadem Can you provide an example ? I'm sorry but I don't undestand your request

**Comment by amirhkhadem** [comment]
This is what i used: 
` <b-input
            @keyup.native.enter="getData()"
            editable
            v-model="startTime"
            placeholder="ex. 11:22"
            icon="clock"
          ></b-input>`

this is what i should be using: 
<b-timepicker
                rounded
                placeholder="Click to select..."
                icon="clock"
                :hour-format="format">
            </b-timepicker>

with the option to not have the dropdown picker because its not a fast process for some one who wants to fill out my form on a daily basis.

code 1 gives me a string, code 2 gives me a date.

I guess since date is a hassle in javascript its better to have a string. You can close this if you want.

**Comment by jtommy** [comment]
The question is a timepicker has to contains a picker in some way so you should create a own custom component to meet your requirements
