### ISSUE TITLE
Error in the Autocomplete documentation with the custom-formatter prop.

### ISSUE THREAD

**Issue by ebreisman** [buefy/buefy#1371]
The document for the props for the Autocomplete component incorrectly describes the custom-formatter prop. It looks like the props description was copy/pasted from the Datetime prop of the same name without the description being updated.

<img width="815" alt="Screen Shot 2019-05-01 at 3 24 41 PM" src="https://user-images.githubusercontent.com/7997428/57037511-5a889100-6c25-11e9-8bd3-1e348dab54a4.png">

**Comment by jtommy** [comment]
Thanks, it will be updated
