### ISSUE TITLE
Button component not rendering correctly

### ISSUE THREAD

**Issue by husstahn** [buefy/buefy#1373]
**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**OS/Browser**: Chrome

### Description

The new button component renders an unstyled button

### Steps to reproduce

Add a button `<b-button type="is-success">Success</b-button>`

### Expected behavior

`<button type="submit" class="button is-success">Success</button>`

### Actual behavior

`<button type="submit" class="btn is-is-success">Success</button>`

Class is btn should be button is-is-success should be is-success

**Comment by jtommy** [comment]
@husstahn Are you sure to use Buefy ? https://codepen.io/anon/pen/MRNaaV?&editable=true&editors=101
`btn` class is Bootstrap class

**Comment by husstahn** [comment]
Yes I am sure I’m using buefy I know btn class is a bootstrap class that’s why it doesn’t render correctly

**Comment by jtommy** [comment]
I cannot reproduce it as you can see in the example

**Comment by husstahn** [comment]
I checked my app and there was a Button.vue component which was adding the wrong class. I am pretty sure I didn't create that component, did buefy ship with it in a previous release?

**Comment by jtommy** [comment]
No i didn't touch it in the last version
