### ISSUE TITLE
Feature request: Slider / range input

### ISSUE THREAD

**Issue by imfaber** [buefy/buefy#1374]
Hello community, 

I think a "slider/input range" component could be a nice addition to the form controls.

Any thoughts?

Thank you in advance for the consideration.

**Comment by jtommy** [comment]
@imfaber Sure! Slider component is in the roadmap

**Comment by yxngl** [comment]
I am working on it, but it still need some work.

**Comment by jtommy** [comment]
@yxngl Cool!

**Comment by yxngl** [comment]
An update:
- Basic functionality for (range) slider with a few minor problems
- Bulma styling is yet to be done
- Vertical slider will be saved for later

Now I am thinking about the API to let users to customize the labels, something like below from Element. What Element does is a prop of a complex object like  `{position: label, position: {style: '', label: ''}}`
![image](https://user-images.githubusercontent.com/1696853/59370526-519cdc00-8d08-11e9-8c3e-9a0739adb126.png)

Currently I am thinking something similar to `b-table-column`.
```
<b-slider :min="1" :max="100">
  <b-slider-tick :position="10">10</b-slider-tick>
  <b-slider-tick :position="50"><strong>50%</strong></b-slider-tick>
</b-slider>
```
There could be a Boolean prop to trigger showing all ticks and like `tick-labels` in Vuetify to take labels from an array for simple use cases.

**Comment by jtommy** [comment]
@yxngl First all, thanks :)
I agree with you and I would avoid a complex object as prop.
