### ISSUE TITLE
Add `stop` modifier to Dropdown trigger `click` event

### ISSUE THREAD

**Issue by zzyyxxww** [buefy/buefy#1379]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome/Linux

### Description

I'm trying to have a dropdown inside an element that listens to the onclick event.

In my case, it's a dropdown inside a Table `sortable` header. When clicking the `trigger` of the dropdown, it also triggers the sort.

Regardless of this case, I don't think it makes much sense having the dropdown trigger click bubble up. It should just open the dropdown and not cause any other effect in the page.

In any case, users can always use `@active-change` for adding behaviour when the dropdown becomes visible, or even adding `@click` to an element inside `trigger` custom slot.

I understand that this could potentially be a breaking change for some users, but this is still pre 1.0, and it should be coded like this anyways.

I implemented the change here: https://github.com/zzyyxxww/buefy/commit/5037f02d8107ff188092477199702bf05a877b86

### Steps to reproduce

Go to codepen https://codepen.io/erandros/pen/PvYjoo
1. Click button. Said button is the trigger of dropdown and is also the child of a div that has an onclick alert bound.

### Expected behavior

To not see the alert pop up.

### Actual behavior

The alert pops up.

Thank you for considering this.

**Comment by yxngl** [comment]
I think native event bubbling is just the default. User could add `@click.native.stop` to stop it like in your case. Could you find any UI library preventing it for any reason?

**Comment by zzyyxxww** [comment]
Yes, native event bubbling is the default.

It is true that the user could add `@click.native.stop="$refs.dropdown.toggle()"` to the dropdown to open it and not bubble up, but that means adding a `ref` just for that dropdown, and it's extra work for something that shouldn't be that way anyway.

And I insist, it does not make sense to bubble up the click of a dropdown button from a UI perspective. I understand though the need to not change this so as to not break live applications.

Thank you for reading.

**Comment by zzyyxxww** [comment]
Thanks, that works.
I still think that the opt in behaviour should be that it didn't bubble up.
