### ISSUE TITLE
Datepicker icon 'calendar-today' doesnt exist in Fontawesome

### ISSUE THREAD

**Issue by jol92** [buefy/buefy#1380]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.10]

### Description

I'm working with de FA icons in my buefy project without any problem until now.
When i use the datepicker input he throw me this error: 

> Could not find one or more icon(s) {prefix: "fa", iconName: "calendar-today"}

I search in Fontawesome any icon with that name and there's no one.

### Steps to reproduce

1. Add font awesome as default icon pack in your buefy project
2. Add datepicker input in your template

### Expected behavior

![image](https://user-images.githubusercontent.com/43551770/57193243-3e446700-6f39-11e9-9627-d9d75e2f4965.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/43551770/57193250-5320fa80-6f39-11e9-8678-2487a9548925.png)
![image](https://user-images.githubusercontent.com/43551770/57193252-5916db80-6f39-11e9-8ca9-039d592eeb76.png)

**Comment by jtommy** [comment]
@jol92 That icon is only an example but anyway there's something wrong in your import

**Comment by MitchellBouwman** [comment]
Is that so @jtommy?
[https://fontawesome.com/icons?d=gallery&q=calendar-today](https://fontawesome.com/icons?d=gallery&q=calendar-today)

**Comment by jtommy** [comment]
Yes, but it's only an example
