### ISSUE TITLE
How to handle row click in Table Component

### ISSUE THREAD

**Issue by mikeerickson** [buefy/buefy#1381]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6]
**OS/Browser**: macOS / Firefox | Chrome

### Description

Curious, how does one go about responding to a double click on a row.  I am using the simple method (access from data, not creating the various column blocks)

is there a callback or something that can be assigned to `@doubleclick` on a given row in Table Component

I have scoured the docs and the only thing that can come close would be the expanded row, but I need to do quite a bit more (standard table | detail view)

Is this possible without creating a wrapped row etc and having to define all columns with more detailed markup

**Comment by jtommy** [comment]
@mikeerickson Did you try ` dblclick` event ?

**Comment by mikeerickson** [comment]
@jtommy I am using the `<b-table>` component to build up the table, thus I am not creating each row/column using markup.   Is there a prop on the `<b-table>` component for defining double click, I am not finding one?

```html
            <b-table
                class="mb-4"
                v-bind:data="data"
                v-bind:columns="columns"
                v-bind:bordered="true"
                v-bind:stripped="true"
                v-bind:narrowed="true"
                v-bind:hoverable="false"
                v-bind:loading="true"
                v-bind:paginated="true"
                v-bind:current-page.sync="currentPage"
                v-bind:pagination-simple="false"
                v-bind:per-page="perPage"
                default-sort="first_name"
                v-bind:default-sort-direction="sortDirection"
            >
```

**Comment by jtommy** [comment]
Sure, `@dbclick="myEvent"` or `v-on:dbclick="myEvent"`

**Comment by mikeerickson** [comment]
Ahhh, is this documented and I missed this?  I read all the docs as thoroughly as possible Sunday evening (I figured it would be good evening reading) and didn’t see this. I guess I could have read the source as well.

**Comment by mikeerickson** [comment]
Oh, and FTR, I just use `v:bind` or `v:on` As opposed to shortcuts so that `VSCode` syntax highlighting is better looking 🤓

**Comment by jtommy** [comment]
Take a look at events tab in https://buefy.org/documentation/table

**Comment by mikeerickson** [comment]
@jtommy I have tested using the above format and I am unable to get `dbclick` event to fire, however, other events such as `select` and `click` events are firing as documented.

So, after re-reading this (and the documentation, I copy/pasted your example and it was defined as `dbclick` where it should be `dblclick` (missing `l` after `db`)   Harmless typo, but figured I would document for brevity sake in case someone stumbles upon this in the future

```html
<bt-table>
    ...
    @dblclick="dblClickEvent"
    ...
</bt-table>
