### ISSUE TITLE
Improvement: icons in table column label

### ISSUE THREAD

**Issue by Niels-NTG** [buefy/buefy#1383]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**OS/Browser**: Mac OS 10.14.4/Google Chrome 74.0

### Description
To indicate the type of data of a table column it is sometimes helpful to use an icon instead or in addition to label text. See image below for an example on how this could look like:
![Schermafbeelding 2019-05-06 om 15 50 34](https://user-images.githubusercontent.com/6061595/57229561-b2087180-7016-11e9-8d73-403e1ddb1d1f.png)

In the API `b-column` should get a property `icon` which expects a string with the name of the icon in the iconpack defined by the `icon-pack` property.

**Comment by jtommy** [comment]
You might use header slot (soon I'll add it in b-table-column)
