### ISSUE TITLE
Assigning dynamic array to v-model

### ISSUE THREAD

**Issue by tanhs** [buefy/buefy#1384]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.7]
**OS/Browser**:

### Steps to reproduce

I am trying to use dynamic array to assign as v-model but not able get it working.
I have tried :v-model or v-model, both doesn't work.

### Expected behavior

formdata: ['t1', 't2', 't3']

### Actual behavior

formdata no value with :v-model, if i use v-model(without ":") all 3 checkbox will checked when i click one checkbox only and formdata also not showing anything

**Comment by tanhs** [comment]
Here is the sample https://codepen.io/tan-hai-shi/pen/arOJaM

**Comment by yxngl** [comment]
- There is no such thing `:v-model`
- Your data is one way from the app to the checkbox factory. Need to `emit` or use another `v-model`.
- Why not just use grouped checkboxes in the doc?

**Comment by tanhs** [comment]
@yxngl Thanks.
I like to know more on how to do bullet 3.  My understanding is this is already a group checkbox where all v-model="formdata[control.fieldName]".  Can you show an example in the codepen.  Thanks in advanced.

**Comment by yxngl** [comment]
@tanhs See [example](https://codepen.io/yxngl/pen/arOYLw?editors=1011)

**Comment by tanhs** [comment]
@yxngl 
How can I get the v-model to be an associative array like v-model="chk1data[control.fieldName]"
I have made some changes to the code but fail to get it right
[https://codepen.io/tan-hai-shi/pen/vwGRve?editors=1010]

**Comment by yxngl** [comment]
@tanhs It's just javascript. Organize your data structure and set v-model to bind to one element in the object.
Change to `chk1data: {f1: [], f2: []},`

You could ask questions for code help in the Discord channel.

**Comment by tanhs** [comment]
@yxngl forgive my ignorance.  can you let me know the url for Discord.  I will post further question over there.  thanks for your help.

**Comment by yxngl** [comment]
It is in the navbar of the doc website.
https://discordapp.com/invite/ZkdFJMr
