### ISSUE TITLE
Field horizontal with checkboxes or checkbox button

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1385]
comment

**Comment by shelru** [comment]
https://codepen.io/anon/pen/mYJMVN?editors=1010
Try to remove horizontal prop of field.
![image](https://user-images.githubusercontent.com/9306996/57313764-51099800-7101-11e9-9224-3b079b6c1690.png)
![image](https://user-images.githubusercontent.com/9306996/57313777-59fa6980-7101-11e9-8cd3-8659e9749c05.png)

**Comment by shelru** [comment]
Same with https://codepen.io/anon/pen/BeNmjv?&editable=true&editors=101 fields and inputs.

**Comment by jtommy** [comment]
What's the issue?

**Comment by shelru** [comment]
Align beetween checkbox button GROUP.

**Comment by shelru** [comment]
Check screenshots.

**Comment by shelru** [comment]
It's not grouped.

**Comment by jtommy** [comment]
Did you try to wrap bField or field class into an other bField ?
`<b-field horizontal> <b-field> ...`

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy as you can see, the same result.
https://codepen.io/anon/pen/gJvwpR?editors=1010

**Comment by afwn90cj93201nixr2e1re** [comment]
Works.
