### ISSUE TITLE
TabItem Does Not Obey Ordering with v-for and key

### ISSUE THREAD

**Issue by Skinner927** [buefy/buefy#1387]
### Overview of the problem

**Buefy** version: v0.7.5
**Vuejs** version: v2.6.10
**OS/Browser**: MacOS 10.14.4/Chrome 73.0.3683.103

### Description

When using `v-for` with `key` on `b-tab-item` the order of the tabs is incorrect if items are removed and added back.

### Steps to reproduce

I've made a demo: https://codepen.io/Skinner927/pen/vwNYLp

1. Observe the proper sorted order of the tabs: "April, Bob, Stan".
1. Click the "Remove Bob" button
1. Click the "Add Bob Back" button
1. Observe the order of the tabs is now "April, Stan, Bob" which is incorrect. The `ul` list (at the top under "Sorted:") uses the same `key` mechanism and is properly sorted.

### Expected behavior

For the order of tabs to be in the same order as the underlying array.

### Actual behavior

Because `v-for` is only adding the missing elements, `b-tab-item`'s `created()` method [always appends new items](https://github.com/buefy/buefy/blob/dev/src/components/tabs/TabItem.vue#L46) to the end of the tab list.

**Comment by service-paradis** [comment]
We get the same thing if we use `v-if` on `tab-item`. 

ex.
```
<div id="app" class="container">
    
    <section>
        <div class="block">
            <button class="button" @click="activeTab = 1">Set Music</button>
        </div>
        <div class="block">
            <b-switch v-model="showBooks"> Show Books item </b-switch>
        </div>
        <b-tabs v-model="activeTab">
            <b-tab-item label="Pictures">
Lorem ipsum dolor sit amet.
            </b-tab-item>

            <b-tab-item label="Music">
Lorem <br>
ipsum <br>
dolor <br>
sit <br>
amet.
            </b-tab-item>

            <b-tab-item v-if="showBooks" label="Books">
What light is light, if Silvia be not seen? <br>
What joy is joy, if Silvia be not by— <br>
Unless it be to think that she is by <br>
And feed upon the shadow of perfection? <br>
Except I be by Silvia in the night, <br>
There is no music in the nightingale.
            </b-tab-item>

            <b-tab-item label="Videos" disabled>
Nunc nec velit nec libero vestibulum eleifend.
Curabitur pulvinar congue luctus.
Nullam hendrerit iaculis augue vitae ornare.
Maecenas vehicula pulvinar tellus, id sodales felis lobortis eget.
            </b-tab-item>
        </b-tabs>
    </section>

</div>
```

I'm working on it right now. I'm doing some tests, but should be able to make a PR tomorrow!

**Comment by service-paradis** [comment]
Created a PR that should solve this problem (#1535)
