### ISSUE TITLE
Feature Request: Accept "router-link" as button tag

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1389]
### Overview

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10

### Description

In some places, i'm using buttons for navigation using `router-link`. I would like to use `b-button` component like every buttons in my app. It would be great to accept `router-link` in `tag` props.

### Steps to reproduce

<b-button class="is-fullwidth"
                             type="is-primary"
                             size="is-medium"
                             tag="router-link">
              Start
</b-button>

### Expected behavior

A link styled as a button to navigate like:
`<a data-v-02cf5aca="" href="/" class="is-primary is-medium button router-link-active">test</a>`

### Actual behavior

Error in console without any rendered element:
```
[Vue warn]: Invalid prop: custom validator check failed for prop "tag".
```

**Comment by jtommy** [comment]
At the moment button component doesn't allow it. 
You might wrap it into router-link component or listen click event and programmatically push a to new route

**Comment by service-paradis** [comment]
Thanks for your answer (and thanks for your work on this package!). 

I used a workaround. It was more a feature request than a bug report.

**Comment by jtommy** [comment]
Sure but my first idea was just to avoid a dependency with vue-router lib

**Comment by service-paradis** [comment]
Yeah, I understand, thanks!

**Comment by service-paradis** [comment]
I know this issue is close now, but I was just asking myself it it could work without having direct dependency on vue-router.

If the button tag validator could accept 'router-link':
```
tag: {
                type: String,
                default: 'button',
                validator: (value) => {
                    return [
                        'button',
                        'a',
                        'input',
                        'router-link',
                    ].indexOf(value) >= 0
                }
            }
```
And if the component could accept any attributes with something like `v-bind="$attrs"`, it could maybe work.

This way, if someone use vue-router, the tag `router-link` would be accepted and any attributes would be passed along the subcomponent. ex. `to="/"`.

Maybe I'm wrong.

**Comment by jtommy** [comment]
You're right, i've just enabled router-link

**Comment by service-paradis** [comment]
Thanks!

**Comment by patrickse** [comment]
Just having the same problem with `nuxt-link`. Would it be possible to also allow `nuxt-link` tag??

**Comment by gigioSouza** [comment]
@patrickse just created a PR for this #1488
