### ISSUE TITLE
Table hover color

### ISSUE THREAD

**Issue by Haga14** [buefy/buefy#1392]
I have a table that needs to be hoverable and I used the hoverable table feature of Buefy and it works fine. However, the color of the row that is hovered over, is barely different from the color of the surrounding rows. How could I change the color that color. 

Also, when the table is striped, the stripe color is also barely different from the surrounding rows. Below is a screenshot of the a striped table, which is pretty much the same problem with hoverable table...

![Capturesdf](https://user-images.githubusercontent.com/32829650/57477017-6f84a600-725d-11e9-8e42-17e5a73d2792.PNG)

**Comment by yxngl** [comment]
See customization doc of [Buefy](https://buefy.org/documentation/customization) and [Bulma](https://bulma.io/documentation/customize/concepts/).

The relevant variables are `$table-row-hover-background-color`, `$table-striped-row-even-background-color` and `$table-striped-row-even-hover-background-color` from https://bulma.io/documentation/elements/table/
