### ISSUE TITLE
b-input should emit change event

### ISSUE THREAD

**Issue by bejohu** [buefy/buefy#1393]
The [change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) fired by the textarea / input should be passed on to the component-level via `$this.emit('change')`. As of fec335898e7b1e5c03847a9fae801f45c5548c3e this is not the case.

**Comment by yxngl** [comment]
The native event and Vue event are two different things. Use `@change.native` on Vue components and `@change` on DOM elements for it.
https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

**Comment by bejohu** [comment]
Thanks for pointing that out. However, since the `input` element is wrapped in a `div` using `@change.native`. See the example where `input` is wrapped in `label` here: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components.

**Comment by yxngl** [comment]
That is what I said. On DOM element, use `@change`.

From Vue API https://vuejs.org/v2/api/#v-on
> When used on a normal element, it listens to native DOM events only. When used on a custom element component, it listens to custom events emitted on that child component.

**Comment by bejohu** [comment]
@yxngl Listening for `@change.native` on `<b-input>` works. Apparently, the native `change` event [bubbles up](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) in the DOM, so it can be caught on the `<div>` which encloses the `<input>` element in buefy's `<b-input>` component.
