### ISSUE TITLE
[table] draggable rows feature not working in Firefox & Safari

### ISSUE THREAD

**Issue by scheinercc** [buefy/buefy#1398]
### Overview of the problem

**Buefy** version: [X.X.X]*
**Vuejs** version: [X.X.X]*
\* as per Buefy Docs (11/05/19) https://buefy.org/documentation/table

**OS/Browser**: 
- Browsers tested:
-- Firefox Nightly 68.0a1 (2019-05-10), 
-- FF Stable 66, 
-- Safari 12.1, 
-- Vivaldi 2.5.1525.40 (based on Chrome/74.0.3729.134)
- on macOS 10.14.4

### Description

It seems that the "Draggable rows" table feature (https://buefy.org/documentation/table) only works in Chromium-based browsers. I just tested it in Firefox Nightly, Safari and Vivaldi. 
1) Only in Vivaldi I was able to test the full feature. 
2) In Safari the event seems to happen, but the row doesn't actually move. When pressing down with the mouse the row background color changes, the mouse cursor changes and when "dropping" a row a bit further down, the info appears e.g. "Moved Jess from row 1 to 4" - though "Jess" doesn't visually move.
3) In Firefox **nothing** happens.

### Steps to reproduce
with Firefox on macOS (& with Safari on macOS
1. Open https://buefy.org/documentation/table
2. Scroll to "Draggable rows"
3. try to grab and move a row up or down

### Expected behavior

Table rows can be draggged/dropped with all current browsers, for me mainly Firefox. 
Alternatively (but much less favoured) it gives a clear indicator stating that this is a Chromium-only feature.

### Actual behavior

Table rows can be draggged/dropped only with Chromium-based browsers.

**Comment by yxngl** [comment]
Buefy just uses HTML Drag and Drop API directly. This is a bug in Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=725156
Adding some fake data like below as suggested in the link to `dragstart` method in the example fixes it.
```
payload.event.dataTransfer.setData('application/x-workaround', "- data to make Firefox start drag -");
```
Need to check Safari tomorrow.

**Comment by scheinercc** [comment]
Heya, maybe a link to this ticket or a note could be added to the documentation?
https://buefy.org/documentation/table#draggable-rows
https://github.com/buefy/buefy/blob/d0f40adc56e401dd438df1d5363b6b1e730860fd/docs/pages/components/table/Table.vue#L86
