### ISSUE TITLE
Radio buttons not rendered correctly in IE11

### ISSUE THREAD

**Issue by timEulitz** [buefy/buefy#1401]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.6
**OS/Browser**: Windows 7, Internet Explorer 11.0.120

### Description

The Buefy radio buttons are not rendered correctly on Internet Explorer 11. Specifically, when they are selected, the circle in the center does not appear which makes it very hard to see if the selection has actually occurred.

Since it is somewhat related, I would also like to point out issue #817 where the inner circle of the radio buttons is not always positioned correctly. I am bringing this up because maybe the way in which the circle inside the radio button is achieved should get a general overhaul with IE11 in mind.

For reference, this Bulma extension has similar looking radio buttons which work well on IE11 and do not appear to have issue with the centering of the circle inside the radio buttons:

https://github.com/Wikiki/bulma-checkradio

### Steps to reproduce

Open up Internet Explorer 11 and view the Buefy Radio button documentation (or any other site that uses the radio buttons):
https://buefy.org/documentation/radio

### Expected behavior

Selected radio buttons are clearly selected with a circle in the center.

### Actual behavior

Selected radio buttons do not have a visible circle inside of them and it's barely visible that they are selected.

![ie11](https://user-images.githubusercontent.com/4571512/57680675-72e9aa00-762e-11e9-8767-04c534910643.png)

**Comment by yxngl** [comment]
Radio renders fine for me on IE11...

**Comment by timEulitz** [comment]
I just double-checked, it looks like this issue does not occur on Windows 10 even when the IE11 version is exactly the same (11.0.120). I can reliably reproduce it on Windows 7, for example.

I guess this is some sort of bug in IE because what I did in my PR should not be doing anything but it does. It would still be great if this could be fixed even if W10 users are apparently not affected.

**Comment by jtommy** [comment]
You're right, in the past another components lacks only Windows 7.
I need to check the PR in all browsers

**Comment by yxngl** [comment]
OK. This is the bug and workaround: https://github.com/philipwalton/flexbugs#flexbug-12
I tested with emulating IE10 in IE11 of Win10.

**Comment by jtommy** [comment]
Thanks @timEulitz and @yxngl
