### ISSUE TITLE
[table] Align table checkbox to the right

### ISSUE THREAD

**Issue by IamIdan** [buefy/buefy#1403]
### Overview of the problem

**Buefy** version: 0.7.4
**Vuejs** version: 5.6.0
**OS/Browser**: not relevant

### Description

I want to be able to make the checkbox column in buefy into the right side, as I am using right-to-left language in my site.

I think it may be implemented by adding a new prop, `checkable-right`, as an alternative to the existing `checkable `prop.

An example code:
`		<b-table
			:data="data"
			checkable-right
			:checked-rows="checkedRows"
		>
</b-table>
`

I am willing to implement it myself, as it is not an hard feature :) if so assign me to it an I'll create it.

### Steps to reproduce
Not relevant
### Expected behavior
checkable column will be aligned to the right.
### Actual behavior
checkable column is aligned to the left.

**Comment by jtommy** [comment]
@IamIdan Ok, i'll review your PR
