### ISSUE TITLE
A horizontal label takes space when not specified for b-field

### ISSUE THREAD

**Issue by Rednas83** [buefy/buefy#1405]
### Version
Buefy: 0.7.5
Vuejs: 2.6.10
### Steps to reproduce
```
<b-field label="" horizontal>Content</b-field>
```
### Expected behavior
Label takes no space when undefined just like with the vertical label or when a message is undefined
```
<b-field label="">Content</b-field>
<b-field message="">Content</b-field>
```

**Comment by jtommy** [comment]
@Rednas83 What's the `vertical` prop ?

**Comment by Rednas83** [comment]
@jtommy My bad. I assumed it existed because of the horizontal property. I removed it from the code in the expected behaviour.

**Comment by jtommy** [comment]
Your request is beaking change because I should remove the label space when is empty or null. 
At the moment you might apply a CSS class that hides the label container

**Comment by Rednas83** [comment]
Would it not be more consistent that way? 
In the scenarios below the label or message is also removed when empty or null!
```
<b-field label="">Content</b-field>
<b-field message="">Content</b-field>
```
Can you provide an example how to remove the horizontal label in css when empty or null?

**Comment by jtommy** [comment]
https://codepen.io/anon/pen/MdoPxx

**Comment by Rednas83** [comment]
Thanx for the pen, but unfortunately this does't work for me! Because the label should only be removed when null/unspecified. Is it not possible to make a fix for this in a new release?

**Comment by jtommy** [comment]
Your might apply the class dynamically

**Comment by Rednas83** [comment]
It works. Thanks a lot
