### ISSUE TITLE
Numberinput  input digit only

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1406]
Numberinput  can input  'e' or 'eeeee'.  
I need Numberinput  input digit number only.

**Comment by jtommy** [comment]
Are you using Firefox?

**Comment by JMDC-SUN** [comment]
I am using chrome.
![image](https://user-images.githubusercontent.com/49149068/57827856-0adcc480-77e4-11e9-8b41-ca018415583e.png)

**Comment by yxngl** [comment]
Firefox does not prohibit characters in `input type="number"`.
Chrome allows "e" and "-" as it could be part of scientific notation.
https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in

**Comment by JMDC-SUN** [comment]
@yxngl  Thank you  for your infomation. 
As a number input with spinner,  it input digit number only on any browser like [Vue Number Input Spinner](https://krystalcampioni.github.io/vue-number-input-spinner/) .
