### ISSUE TITLE
Add possibility to add a unit to b-input / b-field

### ISSUE THREAD

**Issue by Rednas83** [buefy/buefy#1407]
### Overview of the problem
**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.10]

### Description
For lots of inputs it is also required to add a unit.

### Expected behavior
Unit displayed to the right of the input. Something similar as label or message.
```
    <b-field **unit="sec"**>
      <b-input type="number"></b-input>
    </b-field>
```
or:
```
    <b-numberinput **unit="sec"**>
    </b-numberinput>
```

**Comment by jtommy** [comment]
You might add it in the label prop of bField

**Comment by Rednas83** [comment]
Thanx, I will consider that for now. 
Currently I implemented "unit" like this. 
```
     <!-- Type1: Decimal input -->
    <b-field v-if="GetType(1)" :type="ccolor" :label="label" message horizontal>
      <b-field>
        <b-numberinput
          v-model="value"
          :min="valuemin"
          :max="valuemax"
          :step="valuestep"
          controls-position="compact"
          controls-rounded
          expanded
          @keyup.native.enter="SetValue()"
        ></b-numberinput>
        <div
          v-if="unit!=''"
          style="width: 40px; text-align: center; vertical-align: middle"
        >{{unit}}</div>
      </b-field>
    </b-field>
```
Will the new "label" slot allow to place a label to the right?
![image](https://user-images.githubusercontent.com/25219229/57850276-d239ec80-77dd-11e9-961a-1a6251310e27.png)
Or perhaps directly behind the value?
![image](https://user-images.githubusercontent.com/25219229/57850544-6f952080-77de-11e9-94f4-06ac81765509.png)
Can you please consider re-opening?

**Comment by jtommy** [comment]
No, the new label slot allows to add html or other component as label.
At the moment I don't think to add similar feature
