### ISSUE TITLE
Datepicker: years list after pick year

### ISSUE THREAD

**Issue by gecheru** [buefy/buefy#1410]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.6
**OS/Browser**: windows 10, chrome 74.0.3729.131

### Description

List of available years in select is changed after pick any year to "picked year + 3".
If set max-date the years list will increase to max-date value by 3 year after many picks..

### Steps to reproduce

1. Click on years select
2. Pick year
3. Click on years select again

You can try it on docs page. It happens in all datepickers
https://buefy.org/documentation/datepicker/

### Expected behavior

Years list will be not changed

### Actual behavior

Years list is changed to picked year + 3

**Comment by jtommy** [comment]
At the moment the year select contains only a max number of options in order to be light.
Maybe I might add a new prop to change default increment value (+3)

**Comment by gecheru** [comment]
Sorry for my english. I'll try to explain with screenshots:
1. Click on years select. There max year option is 2022.
![image](https://user-images.githubusercontent.com/41947777/57968191-e44b9480-796f-11e9-82f4-2e1aebf4b9ad.png)
2. Pick for example 2014. And click on years select again. There max year option is 2017. It's not previous max value 2022
![image](https://user-images.githubusercontent.com/41947777/57968241-6f2c8f00-7970-11e9-8fb9-f68910821154.png)
3. Pick for example 2017. And max year value is 2020. 
![image](https://user-images.githubusercontent.com/41947777/57968302-f417a880-7970-11e9-8dc5-bc98740472cf.png)

**Comment by jtommy** [comment]
@gecheru because it shows current year + 3 as max value in order to contains about only 100 options in the year select

**Comment by gecheru** [comment]
@jtommy but if I want always to show +- 10 years in select. What I should to do? 
https://codepen.io/gecheru/pen/qGjQda

**Comment by jtommy** [comment]
I might add a new prop or new behaviour (breaking change) in the next releases

**Comment by adriflorence** [comment]
@gecheru not sure if still needed but for that purpose you can just set in your data: 
`data() {
            const today = new Date()
            return {
                date: new Date(),
                minDate: new Date(today.getFullYear() - 10, today.getMonth(), today.getDate()), // ten years ago today
                maxDate: new Date(today.getFullYear() + 10, today.getMonth(), today.getDate()) // ten years from today
            }
}`

and reference minimum and maximum in your datepicker component like so:

`<b-datepicker :min-date="minDate"
                         :max-date="maxDate">`

**Comment by adriflorence** [comment]
@gecheru not sure if still needed but for that purpose you can just set in your data: 
```
data() {
            const today = new Date()
            return {
                date: new Date(),
                minDate: new Date(today.getFullYear() - 10, today.getMonth(), today.getDate()), // ten years ago today
                maxDate: new Date(today.getFullYear() + 10, today.getMonth(), today.getDate()) // ten years from today
            }
}
```

and reference minimum and maximum in your datepicker component like so:
```
<b-datepicker :min-date="minDate"
                         :max-date="maxDate">
```

**Comment by mcmule** [comment]
Last answer doesn't fix the problem, widget won't provide more than 3 years in the future, even if min and max dates are provided.

**Comment by jtommy** [comment]
@mcmule there is a new prop `years-range`

**Comment by mcmule** [comment]
> @mcmule there is a new prop `years-range`

Many thanks !
