### ISSUE TITLE
Support HTML in notification message

### ISSUE THREAD

**Issue by imfaber** [buefy/buefy#1414]
At the moment the message in the notification component is printed as plain text.
It would be handy if it used `v-html` as the toast component does.

I can open a PR if it's ok

**Comment by jtommy** [comment]
I think I'll remove it in order to use default slot

**Comment by imfaber** [comment]
All right, I can close this issue then 😄 

Thank you @jtommy

**Comment by jtommy** [comment]
For the moment i've just added the same way of toast

**Comment by imfaber** [comment]
Cool!
I think that will suffice 😄 

Thank you @jtommy
