### ISSUE TITLE
Tab animation does not work

### ISSUE THREAD

**Issue by alalfakawma** [buefy/buefy#1415]
### Overview of the problem

**Buefy** version: [0.7.6]
**Vuejs** version: [2.5.17]
**OS/Browser**: Firefox/Chrome

### Description

Tab animation does not work, it just changes like as if animated is turned off.

### Steps to reproduce

Just add the tabs to a component.

### Expected behavior

Tabs should animate left or right.

### Actual behavior

Tabs are not animating, just changing like normal, and sometimes does a little flicker like thing. I added background color to one element to see what is happening and it looks like the tab item is coming up from the bottom, really fast. That is causing the flicker like thing.

**Comment by cwilby** [comment]
@alalfakawma did you happen to find a solution for this?  Just starting to look into it now

**Comment by cwilby** [comment]
Oh hey look at that, just removed the `:visible` prop and the animation is waaaay smoother now.

**Comment by alalfakawma** [comment]
Sorry but I don't remember how I fixed this anymore, it's been really long since I last used Buefy.
