### ISSUE TITLE
 When reset the datepicker input, the datepicker window automatically appears.

### ISSUE THREAD

**Issue by sangyeol-kim** [buefy/buefy#1416]
<img width="925" alt="스크린샷 2019-05-20 오전 1 24 40" src="https://user-images.githubusercontent.com/26738287/57985222-c7ae7a00-7a9f-11e9-9142-6f3b9988f85a.png">

**Buefy** version: [0.7.5]
**Vuejs** version: [2.9.6]
**OS/Browser**: MacOS / Chrome

### Description

I used a custom resetField() method to reset the input field after a Submit event via the Button. However, if the input field is reset after an event occurs, the datepicker window will open automatically.

```
methods: {
  resetField () {
     this.todo.title = ""
      this.todo.datefield = ""
  },
}
```

### Steps to reproduce

1. The form has a title and datefield input field.
2. Raise the button's v-on:click.prevent event.
3. When the event occurs, save the title and datefield, and call this.resetField() to reset the field value. (The application is a SPA and needs to be reset)
4. After the input field is reset, the datepicker window opens automatically.

### Expected behavior

I expected an action that only reset the input field.
I did not expect the datepicker to open automatically.

### Actual behavior

After the click event occurs as shown in the picture, the input field value is reset, but the datepicker window opens automatically. This is a harmful component to UX.

**Comment by jtommy** [comment]
It fixed in the last release, please update to 0.7.6 version
