### ISSUE TITLE
[Datepicker] Datepicker and MongoDB Compatibility Issues

### ISSUE THREAD

**Issue by sangyeol-kim** [buefy/buefy#1417]
<img width="859" alt="스크린샷 2019-05-20 오전 2 13 53" src="https://user-images.githubusercontent.com/26738287/57985586-f5e28880-7aa4-11e9-89c8-9f2d580a6ea1.png">

**Buefy** version: [0.7.6]
**Vuejs** version: [2.9.6]

I can not see the Datepicker's input via v-model after saving Datepicker's Date to MongoDB's Date Field.

I have looked for all similar issues but have not found a solution.

**Comment by jtommy** [comment]
Datepicker accepts only date object, are you sure to set it and not a string value?

**Comment by sangyeol-kim** [comment]
Date values ​​entered via Datepicker are saved as "new Date (" Wed, 22 May 2019 15:00:00 GMT ")".

This does not show the value in the input field as v-model.

**Comment by jtommy** [comment]
Could you provide a code example ?

**Comment by sangyeol-kim** [comment]
```
 // datapicker input
<b-input 
  v-model="todo.title"
  value="todo.title"
  icon="fas fa-list-ul"
  size="is-large">
</b-input>

<script>
  export default {
    ...
    data () {
      return todo: {}
    },
    created () {
      let id = this.$route.params.id
      axios.get(`/api/todos/edit/${id}`)
      .then((response) => {
      this.todo = response.data
      })
  },
  }
</script>
```

**Comment by jtommy** [comment]
Is it `response.data.date` a date object?
