### ISSUE TITLE
Timepicker doesn't work anymore

### ISSUE THREAD

**Issue by Heziode** [buefy/buefy#1418]
### Overview of the problem

**Buefy** version: 0.7.6

### Description

`v-model` has not set anymore when we change the value in the timepicker.

### Steps to reproduce

See [this pen](https://codepen.io/anon/pen/OYjjYy?&editable=true&editors=101).

1. try to change the value of hours or minutes
2. Note that the value use in v-model is not changing

This working in `0.7.5`.

### Expected behavior

When we change the values in the timepicker, the variable used for `v-model` should be updated

### Actual behavior

Value of `v-model` not changed when we change the value in timepicker.

**Comment by kerbo** [comment]
is the problem fixed? If so, any idea when the fix will be released?

**Comment by jtommy** [comment]
I'm sorry but I'm going to release a new version next week

**Comment by GopherJ** [comment]
same problem here

**Comment by Heziode** [comment]
@GopherJ this has been fixed in `0.7.7`. Which version do you use ?

**Comment by GopherJ** [comment]
@Heziode 
![peekKPDK3Z](https://user-images.githubusercontent.com/33961674/59561763-766db800-9056-11e9-8b3e-2ea0ccdee617.gif)

**Comment by jtommy** [comment]
@GopherJ can you shoe your code ?

**Comment by GopherJ** [comment]
vue template
```vue
  <!--dateTimeStart picker-->
                            <div class="columns field has-addons is-gapless">
                                <b-datepicker
                                    v-model="SD"
                                    id="b-datepicker-start"
                                    icon="calendar-today"
                                    class="control column is-three-fifths"
                                    indicators="dots"
                                    :date-formatter="dateFormatter"
                                    :date-parser="dateParser"
                                    :events="eventsStart"
                                    :max-date="maxDate"
                                    rounded>
                                </b-datepicker>
                                <b-timepicker
                                    v-model="ST"
                                    icon="clock"
                                    :editable="false"
                                    class="control column is-two-fifths"
                                    :max-time="maxTime"
                                    rounded
                                    hour-format="24">
                                </b-timepicker>
                            </div>
```

```js
ST: {
                get() {
                    console.log(this.dateTimeStart)
                    return this.dateTimeStart;
                },
                set(n) {
                    const h = n.getHours();
                    const m = n.getMinutes();

                    console.log(n)
                    if (
                        h === this.hourStart &&
                        m === this.minuteStart
                    ) {
                        return;
                    }

                    const s = new Date(
                        this.yearStart,
                        this.monthStart,
                        this.dayStart,
                        h,
                        m,
                        0
                    );

                    const e = new Date(
                        this.yearEnd,
                        this.monthEnd,
                        this.dayEnd,
                        this.hourEnd,
                        this.minuteEnd,
                        0
                    );

                    if (s < e) {
                        this.EDIT_DATE_TIME_START(s);
                    } else {
                        this.warningStart();
                    }
                },
            },
```

**Comment by GopherJ** [comment]
actually you can access it from here: 
```
https://github.com/GopherJ/TimeRange
```

**Comment by GopherJ** [comment]
here a similar example:
```
<div id="app" class="container">
    
    <b-field label="Select time">
        <b-timepicker v-model="time"
            :editable="true"
            placeholder="Click to select...">

            <button class="button is-primary"
@click="time = new Date()">
<b-icon icon="clock"></b-icon>
<span>Now</span>
            </button>

            <button class="button is-danger"
@click="time = null">
<b-icon icon="close"></b-icon>
<span>Clear</span>
            </button>
        </b-timepicker>
    </b-field>

</div>
```

```
const example = {
    data() {
        return {
            test: new Date()
        }

    },
    computed: {
        time: {
            get() {
                return this.test;
            },
            set(n) {
                console.log(n)
                this.test = n;
            }
        }
    }
}


const app = new Vue(example)

app.$mount('#app')
```

**Comment by jtommy** [comment]
https://codepen.io/anon/pen/OeNPgR is your last simple example and as you can see it works.
I took a quick look at your code and I think you're not updating the variable of getter computed prop

**Comment by kerbo** [comment]
The dropdown is being cutoff. This looks like a duplicate of #292 You can try the css in #292 to fix it.

**Comment by GopherJ** [comment]
@jtommy actually the problem is when I see the log in `console`, it's different with what I choose, here is the gif to show that.

![peekAZQ92Z](https://user-images.githubusercontent.com/33961674/59564299-99f52a80-9077-11e9-9a76-082d3fa4c4c2.gif)

**Comment by jtommy** [comment]
@GopherJ You're right! It's like vue doesn't listen changes (`setMinutes`, ...) on a date object.
By the way i'm fixing it just now!

**Comment by GopherJ** [comment]
hello @jtommy, thanks for your quick fix, can I know how to this commit?

I tried something like: `git+https://github.com/buefy/buefy.git#96258c4`, seems doesn't compile

**Comment by jtommy** [comment]
git://github.com/buefy/buefy.git#dev

**Comment by GopherJ** [comment]
@jtommy  I'm wondering if we can have a release for this, because the problem I'm encountering is that I'll need to change `import buefy from 'buefy'` to `import buefy from 'buefy/src/index'`

**Comment by GopherJ** [comment]
@jtommy Sorry for disturbing you so much, I changed manually the `main` field in `package.json` to avoid change too much code, but still I get some errors:

```
Module build failed: 
@import "~bulma/sass/utilities/initial-variables";
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in /home/cheng/Project/Ubudu/rt_positions_server/real_time_tracker_ui/node_modules/buefy/src/scss/buefy-build.scss (line 1, column 1)

 @ ./~/buefy/src/scss/buefy-build.scss 4:14-277 18:2-22:4 19:20-283
 @ ./~/buefy/src/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```
How can I fix it? When can we have a new release for this fix? Thanks!

**Comment by jtommy** [comment]
You might build the dev version and use it in your project.
I think to make a new release this week

**Comment by GopherJ** [comment]
@jtommy sadlly if I download it using npm, I don't even have `build` directory~

**Comment by jtommy** [comment]
For general questions, please join official Discord server.
