### ISSUE TITLE
Autocomplete stopped working 

### ISSUE THREAD

**Issue by ilbonte** [buefy/buefy#1421]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**OS/Browser**: osx chrome

### Description

Autocomplete stopped working (probably after a nuxt/nuxt-buetify update)

### Steps to reproduce

1. Create a project with latest version of nuxt and nuxt-buetify
2. add a page with an autocomplete
3. type

Here is a demo: https://codesandbox.io/embed/codesandboxnuxt-6nq73
Here is a repo with the issue:  https://github.com/ilbonte/autocomplete-issue
### Expected behavior

Autocomplete suggests while typing:
![image](https://user-images.githubusercontent.com/7412876/58036831-4ea93400-7b2c-11e9-9efd-f06dc86a3e25.png)

### Actual behavior
Autocomplete don't give any suggestion:

![image](https://user-images.githubusercontent.com/7412876/58036890-6c769900-7b2c-11e9-8c4c-1880e4a2e214.png)

**Comment by jtommy** [comment]
The example is different from Buefy docs because you doesn't filter by current text.

**Comment by ilbonte** [comment]
🤦‍♂ you are right! 


I'm stupid, I spent an hour on this :D
