### ISSUE TITLE
dynamic row.props with b-table-column

### ISSUE THREAD

**Issue by vcml10** [buefy/buefy#1422]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**OS/Browser**: Linux/Mozilla Firefox 66

### Description
I'm trying to create a Table component that could handle different type of data dynamically. Is it possible? I tried the following way:

```html
<b-table
   :data="content">

    <template slot-scope="props">
    <b-table-column
      v-for="(column, index) in columns"
      :key="index"
      :field="column.field"
      :label="column.label">
         {{ props.row.pk }} <!-- what should I put here? -->
    </b-table-column>

    <b-table-column 
      field="actions" 
      label="Actions">
         <a href="#">edit</a>
         <a href="#"> remove</a>
     </b-table-column>
     </template>

</b-table>
```

Is it possible? Or should I need to handle each column separately?

**Comment by vcml10** [comment]
I found the answer in other issue (#1235).

**Comment by nani-nandu** [comment]
Hi Coders,

I need to update the rows dynaically in buefy table

![image](https://user-images.githubusercontent.com/8005799/87922763-11c32f00-ca9a-11ea-98ab-749140346adc.png)
