### ISSUE TITLE
Is there any way to stop the b-dropdown propagation?

### ISSUE THREAD

**Issue by akicho8** [buefy/buefy#1423]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.5.16
**OS/Browser**: Google Chrome

### Description

If click b-dropdown, @click on b-table also responds together.

```pug
b-table(
  @click="() => { $toast.open('row click') }"
  )
  template(slot-scope="props")
    b-table-column(label="")
      b-dropdown(@click.stop)
        button.button(slot="trigger")
          b-icon(icon="menu-up")
        b-dropdown-item
          | (any_item)
```

### Steps to reproduce

1. click on b-dropdown

### Expected behavior

b-dropdown opens

### Actual behavior

b-dropdown opens followed by b-table @click

**Comment by yxngl** [comment]
Try `@click.native.stop`

**Comment by akicho8** [comment]
@yxngl After changing to `@click.native.stop` , it worked correctly.  Thanks!!
