### ISSUE TITLE
Feature Request: Optionsto prevent close when selecting values

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1424]
### Overview of the problem

**Buefy** version: 0.7.6
**Vuejs** version: 2.6.10

### Description

I'm using Buefy Dropdown to select multiple values. I would love to have an option that prevent the dropdown from closing when selecting multiple values. Right now, it requires multiple click if we want to select multiple values.

### Steps to reproduce

1. Click the dropdown trigger
2. Select a value (the dropdown close)
3. Click again the dropdown trigger
4 . ...

### Expected behavior

The dropdown stays open after we select (or unselect) an item. It could be an additional property.

### Actual behavior

The dropdown is closed once we select a value.

**Comment by jtommy** [comment]
You're right, I thought it after new release.
I'll add a new prop to manage it

**Comment by yxngl** [comment]
Related to #1137. I think it could also apply to hoverable dropdown.

**Comment by jtommy** [comment]
@yxngl @service-paradis I'm thinking to add this behaviour as default when `multiple` without adding a new prop

**Comment by service-paradis** [comment]
@jtommy You are right, I think it is the (most often) desired behavior when using `multiple`.
