### ISSUE TITLE
B-collapse hidden content blinking

### ISSUE THREAD

**Issue by Sogl** [buefy/buefy#1426]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Docker Ubuntu 16, latest Chrome 

### Description

I use collapse component: https://buefy.org/documentation/collapse

I have this html sidebar part in blade file:
```blade
<li>
  <b-collapse :open="false" aria-id="contentIdForA11y1">
  <a slot="trigger" aria-controls="contentIdForA11y1">Роли и разрешения</a>
    <ul>
      <li><a href="{{ route('roles.index') }}">Роли</a></li>
      <li><a href="{{ route('permissions.index') }}">Разрешения</a></li>
    </ul>
  </b-collapse>
</li>
```

And it becomes this DOM:
![image](https://user-images.githubusercontent.com/7556290/58192634-dd06ec80-7cc9-11e9-8727-aa803587fae0.png)

My app isn't SPA. I have blink problem on page reload (0.5 sec I see non-visible menu part):
![menu](https://user-images.githubusercontent.com/7556290/58193149-0e33ec80-7ccb-11e9-9572-7887b4726b7c.gif)

I think this happens because b-collapse component put `display: none` after the DOM creation.

p.s. I also tried to use this css workaround without success:
```css
.collapse-content {
  display: none;
}

.collapse-content[aria-expanded="true"] {
  display: inherit;
}
```

### Steps to reproduce

1. Put same part of code with `b-collapse` as sidebar or something different.
2. Reload the page or click on links.
3. Hidden part is blinking.

### Expected behavior

Menu should not blink after page reload.

### Actual behavior

Menu is blinking after reload.

**Comment by DonNicoJs** [comment]
@Sogl usually this kind of behaviour only happens in dev mode, have you tried if it happens in production mode too ( with css extracted ? ) 
Or maybe you can try with https://medium.com/vuejs-tips/v-cloak-45a05da28dc4

**Comment by Sogl** [comment]
@DonNicoJs Same problem in production mode.

`v-cloak` solved my problem:
```blade
<ul v-cloak>
    <li><a href="{{ route('roles.index') }}">Роли</a></li>
    <li><a href="{{ route('permissions.index') }}">Разрешения</a></li>
</ul>
```

But I think it's just a workarond and I can't control div's that `b-collapse` is append to my DOM.

@jtommy Any thoughts?

**Comment by jtommy** [comment]
No I don't. 
To be honest I prefer to use v-show because it a best practice in this case (toggle). 
Are you able to reproduce the issue in a little repo ?

**Comment by Sogl** [comment]
@jtommy Ok, I go deeper and found more info about problem.

This problem occurs of 2 conditions:
1. On 1st load or on every load/refresh without cache.
2. When you use `b-collapse` code in plain HTML. No blinks in Vue components (but full component is blinking 🤣 ).

First you need to open DevTools in Chrome and disable cache in [...] —> Settings:
![image](https://user-images.githubusercontent.com/7556290/58596041-444d0f80-827b-11e9-9066-de195df4f298.png)

Second, open my Pen: https://codepen.io/anon/pen/OYBXLj
You can see hidden content blinking every time you click on sidebar links.

Also you can uncomment this CSS code `/*[v-cloak] { display:none; }*/` for workaround.

@afwn90cj93201nixr2e1re if you want to comment, please use English. Thx 😉

**Comment by afwn90cj93201nixr2e1re** [comment]
You can try to use keep-alive, but this is just a workaround.
```html
<keep-alive>
                <b-collapse :open="false" aria-id="contentIdForA11y1">
                  <a slot="trigger" aria-controls="contentIdForA11y1">Роли и разрешения</a>
                  <ul v-cloak>
                    <li><a href="#">Роли</a></li>
                    <li><a href="#">Разрешения</a></li>
                  </ul>
                </b-collapse>
                  </keep-alive>
```

**Comment by afwn90cj93201nixr2e1re** [comment]
В общем у меня перестал работать пример.
Cloudflare пишет что хост упал.

**Comment by afwn90cj93201nixr2e1re** [comment]
Как ни странно я тоже столкнулся с подобной проблемой. Буду смотреть что можно сделать.

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re  Please use English! You can chat with me in any messenger, here other developers need to understand what you mean.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, i fixed it.
https://github.com/afwn90cj93201nixr2e1re/buefy/commit/1d906e346884c6ec1f066168a3cc4f180e0e390a

**Comment by afwn90cj93201nixr2e1re** [comment]
http://rgho.st/69SkyQDLl
Проверь, возможно это то, что тебе нужно. По краней мере у меня больше не моргает так. Вроде.

**Comment by Sogl** [comment]
> So, i fixed it.
> [afwn90cj93201nixr2e1re@1d906e3](https://github.com/afwn90cj93201nixr2e1re/buefy/commit/1d906e346884c6ec1f066168a3cc4f180e0e390a)

I think this is not fix, just specific workaround. Did you try it with situation where you need to see open menu by default?

**Comment by afwn90cj93201nixr2e1re** [comment]
So, you can create some bool variable in data, and bind it with .sync.
```data(){
            return{
                isOpen:true
            }
        }```

```
... b collapse :open.sync="isOpen"
```

Tested.

**Comment by Sogl** [comment]
Can you add a PR for this?

**Comment by jtommy** [comment]
I'll try that fix but if it's ok it's a breaking change anyway

**Comment by afwn90cj93201nixr2e1re** [comment]
https://jsfiddle.net/m6z0dspo/
Check.
Не совсем понятно о каком в твоем случае blink'е шла речь.
Но я думаю исправилось.
https://github.com/afwn90cj93201nixr2e1re/buefy/commit/ed08cf325e293048c81c64c13606198cd851db5f
named slot's 'r better than anonymous.

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re See my 1st issuecomment to see gif with blinking.

**Comment by afwn90cj93201nixr2e1re** [comment]
Seem's like still blinking.

**Comment by afwn90cj93201nixr2e1re** [comment]
Can't reproduce any blinking now with default buefy.
with/without v-cloak.
But it can be reproduce on phone chrome.
history.go(0) just refresh page, and there no blinking with your code.

**Comment by afwn90cj93201nixr2e1re** [comment]
v-cloak doesn't help.

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re add this code to your css:
```css
[v-cloak] {display: none}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
Yeah. I know. But this doesn't help. Sometime's blink again.
