### ISSUE TITLE
datepicker show in modal

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1427]
I am using the Datepicker, but it is show in modal when tablet size.
The Dropdown's prop mobile-modal is work for this. 
Can I set global Dropdown's  mobile-modal to false?

**Comment by jtommy** [comment]
No you don't but I might add a new prop in the config

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/5cfc66d36878d698b80f6b648d136852dc8b706c
