### ISSUE TITLE
Pagination href

### ISSUE THREAD

**Issue by TheNoim** [buefy/buefy#1430]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome 74

### Description

Currently it is only possible to navigate with the pagination component via javascript. It would be awesome if you could add an option to custom render the href attribute of the a tags. This could get handy in server side rendered env like nuxt.

### Expected behavior

A fallback method for non javascript users.

### Actual behavior

JavaScript is fully required.

**Comment by DonNicoJs** [comment]
@TheNoim this would impact the pagination component itself or only inside the table component?

**Comment by TheNoim** [comment]
Pagination itself
