### ISSUE TITLE
b-icon default size is large with FontAwesome 5

### ISSUE THREAD

**Issue by Sogl** [buefy/buefy#1434]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Docker Ubuntu 16, latest Chrome

### Description

I use FontAwesome 5:
```js
import { library } from '@fortawesome/fontawesome-svg-core';
import { faEdit, faFrown } from '@fortawesome/free-regular-svg-icons';
library.add(faEdit, faFrown);
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
Vue.component('vue-fontawesome', FontAwesomeIcon);

//buefy
import Buefy from 'buefy';
Vue.use(Buefy, {
    defaultIconComponent: 'vue-fontawesome',
    defaultIconPack: 'fas',
});

const app = new Vue({
    el: '#app',
    data: {
        isNavbarOpen: false
    }
});
```

And this part of code:
```vue
<a :href="route('permissions.create')" class="button is-link">
    <b-icon
        icon="plus">
     </b-icon>
    <span>Создать разрешение</span>
</a>
```

becomes button with large icon:
![image](https://user-images.githubusercontent.com/7556290/58439535-40838680-80dd-11e9-8654-2526453fcddc.png)

You can see `fa-lg` class in svg DOM element by default:
![image](https://user-images.githubusercontent.com/7556290/58439628-abcd5880-80dd-11e9-9fc0-4d62c54c84ce.png)

It's not normal behavior when I use standard `dom.watch()` function to replace any `<i>` tag with `<svg>`.
So only when I put `size="is-small"` to `b-icon`:
```vue
<b-icon
    size="is-small"
    icon="plus">
</b-icon>
```
my button looks like it should (without `fa-lg` class):
![image](https://user-images.githubusercontent.com/7556290/58439741-75440d80-80de-11e9-8bcb-4a332108e4cf.png)

### Steps to reproduce

1. Put my code into your project.
2. See button with big icon.

### Expected behavior

Button is normal (`is-small`) by default.

### Actual behavior

Icon is large by default.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/icon/Icon.vue#L66

**Comment by afwn90cj93201nixr2e1re** [comment]
Те68е пpoIII,e c03gaT' cBoй фopk, меинтейнер очень ленивый и редко исправляет b@gи.

Либо закинь PR, с реализацией defaultIconSize.

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re я видел ваше сообщение в другом PR —  понятное дело, хочется исправить быстрее, а меинтенер не одобрят. Что ж, бывает, он же двигает этот проект.

Can you add a PR with fix for this ussue?

**Comment by afwn90cj93201nixr2e1re** [comment]
К сожалению не в курсе как здесь форкать репозиторий второй раз. А разбираться с консолькой чтобы вынести n'ое количество коммитов в PR не особо хочется.
Попробуй выкачать папку dist и к себе в node_modules закинуть. Если это, то что тебе нужно, то форкни и закинь ему PR.
[https://github.com/afwn90cj93201nixr2e1re/buefy/tree/Fix](dist.)
[https://github.com/afwn90cj93201nixr2e1re/buefy/commit/dd36f3e20fc62dc4be9e4fa5e7cc28e25180b3ac](Сам коммит для PR.)

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re 
https://github.com/afwn90cj93201nixr2e1re/buefy/commit/dd36f3e20fc62dc4be9e4fa5e7cc28e25180b3ac

этих изменений достаточно для исправлений? я тогда могу их ручками внести в свой код и протестировать

**Comment by afwn90cj93201nixr2e1re** [comment]
Ага. Это все что нужно.
Можно конечно еще лучше, но я не понимаю стратегий меинтейнера, так что это самое простое решение.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/issues/1426
Кстати, можешь сразу попробовать и collapse исправить себе.

Пример использования из моей dev, либо же fix ветки.
Дополнительный слот header, который просто принимает в себя slot.
Так же по умолчанию отключен trigger слот, который лишь мешал.
```html
 <b-collapse class="card c" ref="thisCollapse">
                <div class="card-header" slot="header" slot-scope="props">
                    <p class="card-header-title">#{{index}}</p>
                    <div class="card-header-icon"><b-button :icon-right="props.open123 ? 'angle-up' : 'angle-down'" @click="changeState"></b-button></div>
                </div>
                <div class="card-content">
                    <div class="content_">
                        <b-field horizontal label="Test">
                            <b-input name="test" placeholder="test" :value="text" @input="updatetext($event)"></b-input>
                        </b-field>
                    </div>
                </div>
            </b-collapse>
```

```js
methods:{
     changeState(){
          this.$refs.thisCollapse.toggle();
     }
},
mounted(){
     this.changeState();//Вызывает открытие/закрытие карточки.
}
```

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re давайте по поводу `b-collapse` перейдем в тот issue и будем писать на английском, чтобы и автор понимал о чем речь )

**Comment by afwn90cj93201nixr2e1re** [comment]
Да он бесполезный. Он никогда не 'догоняет' и нифига не будет исправить. Даже если ему в глаза ткнуть баг.

**Comment by afwn90cj93201nixr2e1re** [comment]
Кстати, если ты уже скомпилировал что-либо.
То попробуй заменить v-show на v-if в Collapse. Может быть поможет. Так как меинтейнер очень часто использует v-show там где он не нужен. Хотя в этом случае скорее всего правильно.
Либое же тебе нужен https://bulma.io/documentation/components/navbar/ с dropdown'ом.

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re вы есть в slack / gitter / discord / telegram ? Неудобно тут писать да и эфир засоряем.

**Comment by afwn90cj93201nixr2e1re** [comment]
Неа.
Есть чаты всякие по vue.
@vuejs_ru возможно там дополнительно чем-то помогут.
Можете прям ссылки туда кидать на компоненты и писать что не так.
Да и я тоже недавно в js, поэтому особыми знаниями не обладаю.

**Comment by jtommy** [comment]
@Sogl @afwn90cj93201nixr2e1re please english!
@Sogl Did you try using b-button component ? At the moment it's a breaking change review all icon sizes

**Comment by Sogl** [comment]
@jtommy Ok, 3 examples.

Code:
```vue
<a :href="route('permissions.create')" class="button is-link">
    <b-icon
        icon="plus">
     </b-icon>
     <span>Создать разрешение</span>
</a>

<button class="button is-link">
    <b-icon
        icon="plus">
    </b-icon>
    <span>Создать разрешение</span>
</button>

<b-button
    type="is-link"
    icon-left="plus">
    Создать разрешение
</b-button>
```

Result:
![image](https://user-images.githubusercontent.com/7556290/58599710-17542900-828a-11e9-9acd-97f821660e7d.png)

Only `b-button` component has a normal icon.
But sometimes I want to use only one icon without components.

**Comment by jtommy** [comment]
At the moment you have to use is-small to icon componen

**Comment by Sogl** [comment]
I understand that. Would it change in the near future?

**Comment by jtommy** [comment]
It's an important change, maybe in the 0.8.0 or 1.0.0 so I should think about it

**Comment by service-paradis** [comment]
`customIconPacks` from the next release could be used to customize the default icon pack (#1681).

Using something like this should work:
```
customIconPacks: {
  fas: {
    sizes: {
        'default': '',
        'is-small': faIconPrefix + 'xs',
        'is-medium': faIconPrefix + '2x',
        'is-large': faIconPrefix + '3x'
    },
  }
}
```

**Comment by Sogl** [comment]
@service-paradis Glad to hear!

**Comment by Sogl** [comment]
Finally got to fix the icons in the project. I use this configuration for now where normal size in 1em is `default` (no need to add +1 line definition):
```php
Vue.use(Buefy, {
    defaultIconComponent: 'vue-fontawesome',
    defaultIconPack: 'fas',
    customIconPacks: {
        'fas': {
            sizes: {
                'is-xsmall': 'xs',
                'is-small': 'sm',
                default: '',
                'is-large': 'lg',
                'is-xlarge': '2x'
            }
        },
        'far': {
            sizes: {
                'is-xsmall': 'xs',
                'is-small': 'sm',
                default: '',
                'is-large': 'lg',
                'is-xlarge': '2x'
            }
        },
        'fab': {
            sizes: {
                'is-xsmall': 'xs',
                'is-small': 'sm',
                default: '',
                'is-large': 'lg',
                'is-xlarge': '2x'
            }
        }
    }
});
```

Sizes based on [icon scale list](https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons#scale).

**Comment by afwn90cj93201nixr2e1re** [comment]
А можешь объяснить немного о преимуществах использования svg вместо шрифтов и общего .svg файла и css вместо этого? Цвет менять? Меньше бандл?(можно вроде пересобрать fa)

**Comment by service-paradis** [comment]
@Sogl 
Will also be fixed in the next breaking release (#1776)

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re You can join Buefy Discord channel by this link: https://discordapp.com/invite/ZkdFJMr and DM to me (I have the same nick there) in Russian. Here please use English as the main language.
