### ISSUE TITLE
Add keypress event to b-input

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1435]
I want check input value from keyborad.
Can you add keypress event to b-input?

**Comment by 1nchHigh** [comment]
You can use this:
`@keyup.native.enter="methodName($event)`

Then in your methods:
```
        methodName ($event) {
            alert('On Key Press')
        }

```
'enter' being your key: https://vuejs.org/v2/guide/events.html#Key-Codes
'methodName' being the name of your method

$event must be passed as keyup fires an event rather than method.

**Comment by JMDC-SUN** [comment]
Thank you for your code, but it is not my target.
I want to create a input element can limit some input character like under blow sample.
I need keypress event to judge typed character.

```
<template>
  <div>
    <input type="number" @keypress="validateInput" />
  </div>
</template>

<script>
export default {
  methods: {
    isNumber(evt) {
      evt = evt ? evt : window.event
      var charCode = evt.which ? evt.which : evt.keyCode
      if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode !== 46) {
        evt.preventDefault()
      } else {
        return true
      }
    },
    validateInput(evt) {
      this.isNumber(evt)
    },
  },
}
</script>

<style lang="scss" scoped></style>
```

**Comment by yxngl** [comment]
`<b-numberinput v-model="number" @keyup.native="validateInput"></b-numberinput>`
Native event and access to keyCode are still there.

**Comment by JMDC-SUN** [comment]
@yxngl  Thank you for the code.
