### ISSUE TITLE
[Question] Any way to have fixed columns on horizontal scroll?

### ISSUE THREAD

**Issue by utkarsh-rg** [buefy/buefy#1438]
Is there any way to get a table to have horizontal scroll and have the first N columns be fixed? I checked documentation but I couldn't find anything related to it.

 Something like [this codepen](https://codepen.io/paulobrien/pen/gWoVzN)

**Comment by jtommy** [comment]
I have in mind to add header fixed and then column fixed but with low priority at the moment

**Comment by apolokaklab** [comment]
Maybe adding max height for table or like [bulma table scroll](https://codepen.io/wikiki/pen/JyMYLd)
