### ISSUE TITLE
How to set defaultDateFormatter format to YYYY-MM-DD

### ISSUE THREAD

**Issue by azeemgujjar** [buefy/buefy#1439]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome

### Description

I want to set defaultDateFormatter format to YYYY-MM-DD
and want to parse defaultDateParser YYYY-MM-DD

How can i set in global, please help me with complete steps i look into other available topics but no clear answer i found.
If i need any third party module like moment, how can import and use

**Comment by jtommy** [comment]
Did you see https://github.com/buefy/buefy/issues/1337 ? You can change my example using moment but with same input and output for each functions

**Comment by azeemgujjar** [comment]
yes already seen, but that ticket is not fit in my requirement..
i actually want to set formatting globally with syntax example.
i tried `defaultDateFormatter: (date) => Moment(date).format("DD/MM/YYYY")`
but getting error `ReferenceError: moment is not defined`
using it like this:
`moment = require('moment')
Vue.use(Buefy, {
    defaultIconPack: 'fas',
    defaultDateFormatter: (date) => moment(date).format('YYYY-MM-DD')
})`

**Comment by azeemgujjar** [comment]
> Did you see #1337 ? You can change my example using moment but with same input and output for each functions

yes already seen, but that ticket is not fit in my requirement..
i actually want to set formatting globally with syntax example.
i tried `defaultDateFormatter: (date) => Moment(date).format("DD/MM/YYYY")`
but getting error `ReferenceError: moment is not defined`
using it like this:
`moment = require('moment')
Vue.use(Buefy, {
    defaultIconPack: 'fas',
    defaultDateFormatter: (date) => moment(date).format('YYYY-MM-DD')
})`

Also please don't close unless ticket opener do or issue really resolved

**Comment by jtommy** [comment]
I think you are importing moment incorrectly, please try my full example https://codesandbox.io/s/vue-template-1jhfw
