### ISSUE TITLE
add footer slot to Autocomplete of Taginput component

### ISSUE THREAD

**Issue by Prashanth-Primaseller** [buefy/buefy#1441]
Buefy version: latest
Vuejs version: latest
OS/Browser: osx chrome latest

Suggestion:
Itseems that slot footer has been not included in autocomplete of taginput. It would be very helpful if it could be included.

**Comment by jtommy** [comment]
You're right!

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/3354e046902fd2a5d95f74758e3040e2977351b2
