### ISSUE TITLE
Placeholder not displayed for b-select component

### ISSUE THREAD

**Issue by Rednas83** [buefy/buefy#1442]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser** : Windows10/Chrome

### Description

Placeholder not displayed when value is empty string or when not part of the option list. Would it not be better to display the placeholder instead?

### Steps to reproduce

```
    <!-- Placeholder not displayed -->
    <b-select v-model="value" placeholder="Selecteer element">
      <option>element1</option>
      <option>element2</option>
      <option>element3</option>
    </b-select>
```
### Expected behavior

Placeholder is displayed on empty string or when the value is not part of the options list.

### Actual behavior

![image](https://user-images.githubusercontent.com/25219229/58795171-41934700-85fa-11e9-99ac-fac7d415801c.png)

**Comment by jtommy** [comment]
The component doesn't make assumptions about options value. You should set it to null as default value

**Comment by Rednas83** [comment]
That makes perfect sense, but in my case the default value is an empty string. Is there a way how the empty string could be interpreted the same as a null or undefined?

**Comment by service-paradis** [comment]
@Rednas83 
You can manage this yourself by using a computed property.
I made a pen showing you how to manage this. The first example is using the direct value. The second one is using a computed value.
https://codepen.io/anon/pen/zgOjqa

**Comment by Rednas83** [comment]
Thanks for the response.

That will work for me, but I don’t think that makes much sense.

Should it not be the initial value as long the value is not set already?


Van: Alexandre Paradis
Verzonden: woensdag 17 juli 2019 16:54
Aan: buefy/buefy
CC: Rednas; Mention
Onderwerp: Re: [buefy/buefy] Placeholder not displayed for b-select component(#1442)

@Rednas83
You can manage this yourself by using a computed property.
I made a pen showing you how to manage this. The first example is using the direct value. The second one is using a computed value.
https://codepen.io/anon/pen/zgOjqa

**Comment by germain-receeve** [comment]
Any update on this one, we encountered the same issue 😅  ?

**Comment by jtommy** [comment]
What's the problem?

**Comment by germain-receeve** [comment]
@jtommy I would expect the placeholder to be displayed when no option is currently selected but as @Rednas83 mentioned it rightfully, it only appears when we add it as an option to the list. However, we do not want to have it as part of the selectable option in our case.

**Comment by jtommy** [comment]
As I said I don't want to make assumptions about options, you should set it to null to show the placeholder
