### ISSUE TITLE
b-field type does not show related icon using Font-Awesome 5

### ISSUE THREAD

**Issue by BlueFrog130** [buefy/buefy#1443]
**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**Browser**: Firefox, Google Chrome

### Description

When using `<b-field>` tag and specifying `:type="is-danger"`(is-warning, is-success, etc) , the corresponding icon does not appear correctly.

My code:
```
<b-field label="Name" :type="{'is-danger': NameError}" :message="{ 'Required' : NameError}">
    <b-input placeholder="Name" icon-pack="far" icon="user"></b-input>
</b-field>
```
From my understanding, Buefy automatically recognizes the default Icon pack and assigns icons to each default `is-` element.
Within my main.js, I designated the default icon pack as per the documentation:
```
Vue.use(Buefy, {
    deafultIconPack: 'fas',
    defaultConainerElement: '#content',
})
```
I am using font awesome 5, so the solution to the related issue #259 does not apply to my configuration.
Import statement:
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
```
I feel as if I am missing something simple, but I cannot pin it down.

### Expected behavior
![expected](https://user-images.githubusercontent.com/50666443/58828635-81165f00-860b-11e9-991f-84ba1c49c152.PNG)

### Actual behavior
![actual](https://user-images.githubusercontent.com/50666443/58828688-9ee3c400-860b-11e9-9d50-e1ffdd3305c8.PNG)

**Comment by BlueFrog130** [comment]
The icons appear as intended when using MDI icon pack, but only when no font awesome 5 icons are present, sort of strange, as I thought the b-field and b-input were separate elements.

![comp](https://user-images.githubusercontent.com/50666443/58829841-75786780-860e-11e9-88b4-44c004bb5196.PNG)

the top field has a font-awesome 5 icon, whereas the bottom one has no mention of font awesome icons and works fine.

```
<b-field label="Name" :type="{'is-warning': NameError}" :message="{ 'Required' : NameError}">
    <b-input placeholder="Name" icon-pack="far" icon="user"></b-input>
</b-field>
<b-field label="Email" :type="{'is-warning': EmailError}" :message="[{'Required' : EmailError},{'Formatting Error' : EmailFormatError}]" >
    <b-input placeholder="Email" type="email"></b-input>
</b-field>
```

**Comment by yxngl** [comment]
Did you actually include the icons besides the configuration? Like through CDN or Webpack.

**Comment by BlueFrog130** [comment]
> 
> 
> Did you actually include the icons besides the configuration? Like through CDN or Webpack.

Yes, I included both font-aweomse 5 and MDI in my index.html via CDN, but my "default pack" is font-awesome 5

**Comment by jtommy** [comment]
Can you provide the code about FA import?

**Comment by BlueFrog130** [comment]
I imported it using:
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
```

**Comment by BlueFrog130** [comment]
I fixed the issue by using [Vue-Fontawesome](https://github.com/FortAwesome/vue-fontawesome) and constructing it as per the documenation:
```
import Buefy from 'buefy'
import { library } from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Don't do this... I'm just lazy :P
library.add(far, fas, fab)

Vue.component('vue-fontawesome', FontAwesomeIcon)

Vue.use(Buefy,
    {
        defaultIconComponent: 'vue-fontawesome',
        defaultIconPack: 'fas',
    })
```
