### ISSUE TITLE
How to edit custom-formatter or field dynamically ?

### ISSUE THREAD

**Issue by MatthD** [buefy/buefy#1446]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.5.17]
**ubuntu/Firefox**:

### Description

How to modify dynamically the shown field ? For example I have a case to switch two autocomplete , I have no difficulty to do it for the data but the string show keep .

It seems not possible that  `custom-formatter`or `field" could be a computed value 

### Expected behavior

Should be able to have a computed or v-model variable into field / custom-formatter

**Comment by yxngl** [comment]
It should. Can you show some code?
