### ISSUE TITLE
[Datepicker] Always display six rows

### ISSUE THREAD

**Issue by artjomheinz** [buefy/buefy#1447]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Ubuntu 18.04, Firefox 67.0

### Description

Layout jumps between 5 and 6 rows depending on the selected month. Is it possible to display 6 rows always?

### Steps to reproduce

1. Go [here](https://buefy.org/documentation/datepicker)
2. Change months on the inline example
3. Observe how the number of rows jumps between 5 and 6

### Expected behavior

Always display 6 rows for all months.

### Actual behavior

Sometimes, only 5 rows are shown.

**Comment by jtommy** [comment]
There is already a similar request https://github.com/buefy/buefy/issues/1239 and I think to add a prop to show/hide prev and next month days and a prop to disable/enable them

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/28ede601953d68f871102c02eeaa09b179caff0d
