### ISSUE TITLE
Numberinput still editable when editable is false

### ISSUE THREAD

**Issue by rmelloni** [buefy/buefy#1448]
### Overview of the problem

**Buefy** version: 0.7.7
**Vuejs** version: 2.6.10
**OS/Browser**: Win 10 / Firefox 67.0

### Description

If you set editable false for numberinput, the input field is like expected not mutable but you can still edit the input over the control buttons.

### Steps to reproduce

Inside the docs on https://buefy.org/documentation/numberinput
Try to edit the input withe the control buttons.

![numberinput](https://user-images.githubusercontent.com/36957244/58878149-dff2db80-86d2-11e9-9b57-d88e87116f07.gif)

### Expected behavior

The value of numberinput is not mutable if editable is false.

### Actual behavior

The value of numberinput is mutable over the buttons.

**Comment by jtommy** [comment]
It refers to input otherwise you should use disabled prop

**Comment by rmelloni** [comment]
Okay, I get it. A little confusing. I will use disabled now. Thanks
