### ISSUE TITLE
"buefy" has no ES "module" entrypoint.

### ISSUE THREAD

**Issue by jet10000** [buefy/buefy#1449]
npx @pika/web
npx: installed 74 in 4.371s
⠼ @pika/web installing... buefy
× dependency "buefy" has no ES "module" entrypoint.
Tip: Find modern, web-ready packages at https://pikapkg.com/packages

**Comment by jtommy** [comment]
I'm working on a new build using rollup

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/1cc2e84eb5c8d72e051150a920d7ff3f3bd09cb5
