### ISSUE TITLE
Clockpicker no border-radius (style inconsistency)

### ISSUE THREAD

**Issue by atinybeardedman** [buefy/buefy#1450]
### Overview of the problem

Clockpicker doesn't have rounded corners (no border-radius) where as other similar components do, such as datepicker.

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: All

### Description

See above

### Steps to reproduce
See documentation examples.
### Expected behavior

Style should be consistent across components

### Actual behavior

Style is inconsistent.

**Comment by jtommy** [comment]
@atinybeardedman you're right, I think it's a padding issue

**Comment by atinybeardedman** [comment]
I'm actually opening a pull request with the fix.

**Comment by jtommy** [comment]
Close cf0c9c8a17d0c6d5be23cb548a2bc44ceaa182df
