### ISSUE TITLE
b-icon not support custom type

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1452]
I use a custom type as pink-76 in my sass. 
It work very well in b-radio, b-button, b-checkbox etc, but b-icon.

At b-icon, The default type(like is-white, is-black, is-light, is-dark, is-primary, is-info, is-success, is-warning, is-danger) work well, but custom tyke (like pink-76 ) not work.

` <b-icon icon="tag" type="is-pink-76"> </b-icon>`

**Comment by jtommy** [comment]
You should define `has-text-xxx` class as well
