### ISSUE TITLE
Weird styling with b-field grouped, b-input, control

### ISSUE THREAD

**Issue by agcty** [buefy/buefy#1453]
### Overview of the problem

**Buefy** version: 0.7.7
**Nuxtjs** version: 2.8.1
**OS/Browser**: Chrome 74

### Steps to reproduce

```html
<b-field grouped>
      <b-input
        placeholder="Email"
        expanded
        custom-class="is-medium"
        type="email"
        icon="envelope"
        icon-pack="fa"
      />
      <p class="control">
        <button class="button is-medium is-accent">Go</button>
      </p>
</b-field>
```

### Expected behavior

When an invalid email is provided, the error message should be displayed below the input/field

### Actual behavior

Instead it is shown to the right of the input field
![image](https://user-images.githubusercontent.com/12101091/58956515-c3bc7080-879e-11e9-8bc4-f4f79e0e55a8.png)

**Comment by yxngl** [comment]
Wrap b-input in a b-field, in this case `<b-field expanded></b-field>`

**Comment by yxngl** [comment]
`text-align: center;` is defined on your app.

For the button alignment, if there is label (not horizontal), the ugly workaround I would do it to use Bulma to construct an empty label. 

```
      <div class="field">
        <label class="label">&nbsp</label>
        <p class="control">
          <button class="button is-medium is-accent">Go</button>
        </p>
      </div>
```
