### ISSUE TITLE
I cannot import css

### ISSUE THREAD

**Issue by freenetwork** [buefy/buefy#1454]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.6]
**OS/Browser**: ALL

### Description

My main.js

```
import Buefy from 'buefy'
import 'buefy/dist/buefy.css'
Vue.use(Buefy, {
  defaultIconComponent: 'vue-fontawesome',
  defaultIconPack: 'fas',
});
```

In dev buefy/dist/buefy.css working.
But before build vue-cli-service build, 
After assembly, it turns out the result is as if I do not connect styles. Other colors. 

dev
![image](https://user-images.githubusercontent.com/3347236/59084299-d496ee80-8924-11e9-9bd3-49f91b8a0c48.png)

build
![image](https://user-images.githubusercontent.com/3347236/59084246-a9140400-8924-11e9-8d09-9601ef0e50e5.png)

### Steps to reproduce
????

### Expected behavior

![image](https://user-images.githubusercontent.com/3347236/59084299-d496ee80-8924-11e9-9bd3-49f91b8a0c48.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/3347236/59084246-a9140400-8924-11e9-8d09-9601ef0e50e5.png)

**Comment by jtommy** [comment]
Are you using only import 'buefy/dist/buefy.css' ?
