### ISSUE TITLE
Datepicker not receiving is-active class

### ISSUE THREAD

**Issue by Propaganistas** [buefy/buefy#1457]
### Overview of the problem

**Buefy** version: 0.7.7
**Vuejs** version: 2.6.10
**OS/Browser**: Mac 10.14 ; Chrome

### Description

In Buefy 0.7.7, the datepicker dropdown isn't receiving an `is-active` class upon clicking the input field, resulting in the datepicker to remain hidden.

Reverting to Buefy 0.7.6 makes it work again, so I guess it'll be some sort of regression.

**Comment by jtommy** [comment]
When does it happen ?

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy 
https://github.com/buefy/buefy/blob/dev/src/components/field/Field.vue#L80
maybe it should be is-grouped is-grouped-multiline? or we must use grouped group-multiline, coz group-multiline by default doesn't make any sense. Seem's like typo.

**Comment by Propaganistas** [comment]
I'm so sorry. I traced this back to a plugin I wrote that interferes with Bulma's `.dropdown` class. Seems it was counteracting the datepicker.
