### ISSUE TITLE
b-dropdown not visible, but present in html

### ISSUE THREAD

**Issue by Avrgebro** [buefy/buefy#1458]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome

### Description

Hi guys, I'm making a web application and in one of my pages i need to have a few b-datepicker and b-dropdown, everything works fine until I try to open the b-datepicker (which uses the class dropdown-menu) i can see it present in the html for the page, however the little widget with the days and months is not visible at all, the same issue happens with b-dropdown, i can see the control, but when i click on it, the widget that should open is invisible, but i can see it in the html.

For this project im using vue-material-dashboard, which already comes with vue-material component framework, but i've grown fond of buefy so i prefer to use it

### Steps to reproduce

1. setup b-collapse
2. setup 2 b-datepickers inside of b-collapse

![Screenshot from 2019-06-07 22-05-04](https://user-images.githubusercontent.com/22529106/59141321-5829fd00-8970-11e9-9bed-dfc94e29e488.png)

I can see the widget present:
![Screenshot from 2019-06-07 22-07-34](https://user-images.githubusercontent.com/22529106/59141342-c969b000-8970-11e9-9a24-2199d4dad509.png)

### Expected behavior

I should be able to se the dropdown when i click in the datepicker control

### Actual behavior

When i click in the datepicker control, the panel is present in the html but invisible and unclickable in the page.

Thanks a lot for your help

**Comment by jtommy** [comment]
@Avrgebro I've just replicated your example but I dont'see any issue (except of dropdown but I think it's  a vue-material - buefy conflict)
