### ISSUE TITLE
Date and time picker together

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1459]
Comment

**Comment by afwn90cj93201nixr2e1re** [comment]
### Overview of the problem

**Buefy** version: latest

### Description
 How use date and time picker's together?
For example with one v-model.
Like: 
`data(){return {first_date: new Date(),second_date: new Date()}}`
and in template just:
https://codepen.io/anon/pen/pXzvvv?editors=1010

So and second question: why there no second's select?

As you can see after select date, time is nulled.

@jtommy  @bartboy011

**Comment by afwn90cj93201nixr2e1re** [comment]
https://codesandbox.io/s/rw3l109yzo

**Comment by jtommy** [comment]
I think i'll make a new component.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, if you can add seconds parsing to timepicker too, coz we need it sometimes.

**Comment by jtommy** [comment]
You can already customize parser and formatter

**Comment by afwn90cj93201nixr2e1re** [comment]
Mixin can't work with seconds as you can see in src.
Can you show an example with timepicker where we can set seconds in dropdown list?

**Comment by jtommy** [comment]
No you can't at the moment

**Comment by afwn90cj93201nixr2e1re** [comment]
Yep, im' talking  'bout this.

**Comment by service-paradis** [comment]
Ref: https://github.com/buefy/buefy/pull/1866
