### ISSUE TITLE
Number input emits two input events and updates by 2

### ISSUE THREAD

**Issue by collerek** [buefy/buefy#1460]
Hi,

The Numberinput field emits two input events and increases by 2 with each button click. 
I suppose it's not configuration related as in docs page https://buefy.org/documentation/numberinput/ you have the same behavior.

Regards,
collerek

**Comment by jtommy** [comment]
What docs example do you mean ?

**Comment by collerek** [comment]
I have this for every example on the page. Try clicking few times on random ones.

**Comment by jtommy** [comment]
Browser? Other info to replicate it ..

**Comment by collerek** [comment]
Chrome Version 74.0.3729.169 (64-bit)

**Comment by jtommy** [comment]
I'm not able to replicate it by the way I could increase the delay of long press check

**Comment by collerek** [comment]
I have it also on Edge:  42.17134.1.0
and IE: 11.765.17134.0 (so basically on all browsers).
I'm right now on a weak internet connection, might it be that's somehow influencing the behavior?

**Comment by jtommy** [comment]
I'll investigate about it

**Comment by afwn90cj93201nixr2e1re** [comment]
Can confirm some bug's with buttons, but not only in this component.
b-buttons have similar issue, sometimes we need to click 2 times on it to activate.

**Comment by jtommy** [comment]
Can you provide an example?

**Comment by afwn90cj93201nixr2e1re** [comment]
For example same b-numberinput. (`Anyway` ... that's strange)
I can click it fast(no long click), and sometime's value not increase.
Also issue - seem's like not issue, you realy need to increase delay, but, now, delay is perfect, add constructor option for other users.

**Comment by collerek** [comment]
OK I identified that if I click on the button with mouse button it works fine, but if I click it with touchpad it behaves as a longer click(?) and increases the value by 2.

**Comment by jtommy** [comment]
All right, thanks

**Comment by yxngl** [comment]
I found another problem when the interval is increased from 100 to 250. If you move the mouse out quickly after a click, it will change by 2. I think it is because I can trigger both `mouseup` and `mouse leave`.
