### ISSUE TITLE
Tab order is not working as expected on table pagination

### ISSUE THREAD

**Issue by Teja21780** [buefy/buefy#1461]
### Overview of the problem

While tabbing on the last page number in the pagination list, actually the **previous button** should get focus (if not disabled) otherwise **next button** should get focus, but don't know which element is getting focused here.

Here is the fiddle please check 

https://jsfiddle.net/zu8x09k2/

**Buefy** version: 0.7.7
**Vuejs** version: 2.5.17
**OS/Browser**: Chrome & IE

**Comment by yxngl** [comment]
Prev and Next buttons actually come before pagination numbers in tabbing order, which is based on source order. It may look counter-intuitively, but the visual order could change based on media query and modifier class. From Bulma,

> By default on tablet, the list is located on the left, and the previous/next buttons on the right. But you can change the order of these elements by using the is-centered and is-right modifiers.

On mobile, the list is on the right.

[Flexbox doc](https://www.w3.org/TR/css-flexbox-1/#order-accessibility) says the flexbox order should not affect the traversal order. Potentially the buttons could be put after the number list, but it will still be one fixed order.
