### ISSUE TITLE
Implement "open on focus" on taginput elements

### ISSUE THREAD

**Issue by kartsims** [buefy/buefy#1463]
### Overview of the problem

The `taginput` component doesn't have a `openOnFocus` property.

### Description

It would be nice to implement the same feature as for `autocomplete`, ie. when clicking the `taginput` element, the dropdown can be displayed automatically.

I can give it a try if need be, but is it something you would like to see implemented?

**Comment by jtommy** [comment]
You can already use that prop

**Comment by kartsims** [comment]
Shouldn't it be documented then? PR sent for approval

**Comment by jtommy** [comment]
It Is already in the docs, take a look at the bottom

**Comment by kartsims** [comment]
You are right, it is definitely not clear to me, and I bet it is for others too...

Proposals to make it clearer:
- link to the autocomplete props ("Any other native attribute or [Autocomplete prop](#)")
- state it next to the `autocomplete` prop description (ie. "Add autocomplete feature (if `true`, Autocomplete props may be used too)")

**Comment by jtommy** [comment]
Ok, you might make a PR to improve it.
Thanks

**Comment by kartsims** [comment]
Done, thank you for the great library, happy to contribute to this slight improvement 👍
