### ISSUE TITLE
Implementing sliders and additional functionality from "Bulma-Extensions" 

### ISSUE THREAD

**Issue by iamsanteri** [buefy/buefy#1464]
### Overview of the problem

Hi, I really like Buefy and was wondering if it would be relevant to add Bulma-Extensions (https://wikiki.github.io/) as a component to Buefy itself? 

I mean here especially the slider which is very relevant for devs building applications: https://wikiki.github.io/form/slider/ 

### Description

I was looking for a such slider component in Buefy but realized that it is not there. It should not be so difficult to implement separately but it being included as a standard component within Buefy itself would make a lot of sense. Do you disagree? 

### Expected behavior

Add slider component to your project which is already here: https://wikiki.github.io/form/slider/ while working with standard Buefy.

**Comment by yxngl** [comment]
See https://github.com/buefy/buefy/issues/1374
