### ISSUE TITLE
b-autocomplete and @blur dont seem to be working

### ISSUE THREAD

**Issue by rgnanase** [buefy/buefy#1466]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome

### Description

I am using b-autocomplete for a couple of input fields. all i want to do is call some method when an input was chosen from the autocomplete dropdown or some text has been entered and tabbed to the next input. I tried to use @input but the method was called for every character entered, I don't want that to happen. I want the user to complete entering and either by tabbing or choosing an option from the autocomplete dropdown, and then call my method. I researched and found @blur may do this, but with this handler, the same thing is happening as with @input, the method is getting called for each letter or character the user is typing, and its also called as soon as the user chooses a value from dropdown. 

### Expected behavior
I want the user to be able to enter the data or choose an option and then only call the method mentioned with @blur 
### Actual behavior
method is getting called for every letter user is typing.

**Comment by yxngl** [comment]
`@blur` is triggered as expected when tabbing away or clicking on an option for me. Can you show some code?

**Comment by rgnanase** [comment]
template:
....   
                 </b-field> -->
                    <b-field label="MAJOR" is-normal>
                        <b-autocomplete
                            ref = "major" tabindex="0" v-focus required v-model="admitstudent.major" 
                            :data="getMajorData" 
                            placeholder="e.g. 66FCP" 
                            open-on-focus = true
                            :loading="isFetchingMajor"
                            @select="option => selected = option"                                                     
                            @blur="onMajorChange($event)"                  
                            icon="magnify">
                            <template slot="empty">No results found</template>
                        </b-autocomplete>
                    </b-field>     
.....
script:
export default {
.....
  methods: {
....
    onMajorChange: function(event){
        console.log("Inside major change" + event)
        if (!(this.admitstudent.major in this.majordump)){
            this.$dialog.alert({
                title: 'Error with Major!',
                message: '<p> Please select a valid major from type-ahead dropdown. </p>',
                confirmText: 'OK',
                type: 'is-danger',
                hasIcon: true,
                icon: 'times-circle',
                iconPack: 'fa',                    
                onConfirm: () => { 
                    this.$nextTick(() => this.$refs.major.focus())
                    return
                }                         
            })
        }

**Comment by yxngl** [comment]
Nothing seems wrong from what you pasted, and it works for me.

**Comment by mickorj** [comment]
yes. works for me to.
