### ISSUE TITLE
openOnFocus/onBlur/click conflict  in Dropdown 

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1467]
**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: win10/chrome

I use Dropdown with Input as tigger.  
I use openOnFocus/onBlur/click to active/inactive the dropdown menu.
When I click Dropdown, the  dropdown menu not be visible.

I check vue event in chrome. When I click Dropdown,  OnFocus and Click will work at same time. 
1.  The first:  OnFocus event is dispatched, to active dropdown menu.
2.  next: click event is dispatched,  but click event will inactive dropdown menu when dropdown menu is actived.
![image](https://user-images.githubusercontent.com/49149068/59393326-135df600-8db6-11e9-9379-820207d410f1.png)

It is my code. How can I resolved this?

`<template>
  <div class="control">
    <b-dropdown ref="dropdown" :mobile-modal="false">
      <b-input
        ref="input"
        type="text"
        slot="trigger"
        autocomplete="off"
        :has-counter="false"
        @focus="handleOnFocus"
        @blur="onBlur"
      ></b-input>
      <b-dropdown-item custom>
        <div>
          test
        </div>
      </b-dropdown-item>
    </b-dropdown>
  </div>
</template>

<script>
import mixins from '../mixin'
export default {
  mixins: [mixins],
  data() {
    return {
      _elementRef: 'input',
    }
  },
  methods: {
    toggle(active) {
      console.log('show:' + active)
      if (this.$refs.dropdown) {
        this.$refs.dropdown.isActive = typeof active === 'boolean' ? active : !this.$refs.dropdown.isActive
      }
    },
  },
}
</script>

<style lang="scss" scoped></style>
`
mixin.js
`export default {
  props: {
    size: String,
    expanded: Boolean,
    loading: Boolean,
    rounded: Boolean,
    icon: String,
    iconPack: String,
    // Native options to use in HTML5 validation
    autocomplete: String,
    maxlength: [Number, String],
    useHtml5Validation: {
      type: Boolean,
      default: () => true,
    },
    openOnFocus: { type: Boolean, default: true },
  },
  data() {
    return {
      isValid: true,
      isFocused: false,
      newIconPack: this.iconPack,
      errMsg: '',
    }
  },
  computed: {
    /**
     * Find parent Field, max 3 levels deep.
     */
    parentField() {
      let parent = this.$parent
      for (let i = 0; i < 3; i++) {
        if (parent && !parent.$data._isField) {
          parent = parent.$parent
        }
      }
      return parent
    },

    /**
     * Get the type prop from parent if it's a Field.
     */
    statusType() {
      if (!this.parentField) return
      if (!this.parentField.newType) return
      if (typeof this.parentField.newType === 'string') {
        return this.parentField.newType
      } else {
        for (let key in this.parentField.newType) {
          if (this.parentField.newType[key]) {
            return key
          }
        }
      }
    },

    /**
     * Get the message prop from parent if it's a Field.
     */
    statusMessage() {
      if (!this.parentField) return

      return this.parentField.newMessage
    },

    /**
     * Fix icon size for inputs, large was too big
     */
    iconSize() {
      switch (this.size) {
        case 'is-small':
          return this.size
        case 'is-medium':
          return
        case 'is-large':
          return this.newIconPack === 'mdi' ? 'is-medium' : ''
      }
    },
  },
  methods: {
    /**
     * Focus method that work dynamically depending on the component.
     */
    focus() {
      if (this.$data._elementRef === undefined) return

      this.$nextTick(() => {
        const el = this.$el.querySelector(this.$data._elementRef)
        if (el) el.focus()
      })
    },

    onBlur($event) {
      this.isFocused = false
      this.$emit('blur', $event)
      console.log('onBlur')
     },

    onFocus($event) {
      this.isFocused = true
      this.$emit('focus', $event)
    },
    handleOnFocus(e) {
      this.onFocus(e)
      if (this.openOnFocus) {
        this.toggle(true)
      }
    },

    /**
     * Check HTML5 validation, set isValid property.
     * If validation fail, send 'is-danger' type,
     * and error message to parent if it's a Field.
     */
    checkHtml5Validity() {
      if (!this.useHtml5Validation) return true

      if (this.$refs[this.$data._elementRef] === undefined) return true

      const el = this.$el.querySelector(this.$data._elementRef)

      let type = null
      let message = null
      let isValid = true
      if (!el.checkValidity()) {
        type = 'is-danger'
        message = el.validationMessage
        isValid = false
      }
      this.isValid = isValid

      this.$nextTick(() => {
        if (this.parentField) {
          // Set type only if not defined
          console.log('checkHtml5Validity' + type + message)
          if (!this.parentField.type) {
            this.parentField.newType = type
          }
          // Set message only if not defined
          if (!this.parentField.message) {
            this.parentField.newMessage = message
          }
        }
      })

      return this.isValid
    },

  
  },
}
`

**Comment by yxngl** [comment]
Having a hard time trying to figure out what you want. Input as the Dropdown trigger like the Autocomplete layout and implement the open-on-focus function? Because except for open-on-focus, it seems working for me.

And you tried to modify the form mixin to add a open-on-focus prop... Autocomplete has more code to make it actually work. Assuming that is the aim, I think you could capture the focus on b-input and use `ref` of b-dropdown to `toggle` it.

**Comment by JMDC-SUN** [comment]
As you pointed out, it work well  except for openOnFocus/click conflicting.
I try to toggle b-input  and a span tag.
Thank you for your reply.
