### ISSUE TITLE
.label font-weight erroneous redefinition

### ISSUE THREAD

**Issue by tiramiseb** [buefy/buefy#1470]
The `components/_form.scss` file redefines the `.label` font weight to `$weight-semibold`, with no possibility to change it.

https://github.com/buefy/buefy/blob/cf1991c90af4ad7e736cff6def30a3a32f774b58/src/scss/components/_form.scss#L2

It should at least use `$label-weight`, or even not have this definition, because it already exists in bulma itself.

**Comment by jtommy** [comment]
Default value of Bulma variable `$label-weight` is `$weight-semibold` but not you are able to override it

**Comment by tiramiseb** [comment]
Yes you are able to override it:
https://bulma.io/documentation/form/general/#variables

**Comment by jtommy** [comment]
Sure but the default value is semibold (600)

**Comment by tiramiseb** [comment]
(sorry I misread your comment, I thought you were writing « you are not able to override it ». I have removed my answer)
