### ISSUE TITLE
Undefined icon when using custom type for b-field

### ISSUE THREAD

**Issue by agcty** [buefy/buefy#1472]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**OS/Browser**: Chrome 74

### Description

When using custom statusTypes and **fontawesome**, you cannot use it with b-field elements as it derives the icon from the statusType in a hard-coded manner resulting in this error message: 

Could not find one or more icon(s) 
Object {prefix: "fas", iconName: undefined}
Object {}

### Steps to reproduce

```html
<b-field position="is-centered" type="is-accent">
      <b-input
        placeholder="Search..."
        expanded
        custom-class="is-medium"
        type="text"
        icon-pack="fas"
        icon="heart"
      />
</b-field>
```

CodeSandbox: https://codesandbox.io/s/vue-template-vy5qx

Corresponding lines in buefy source code: 134-141

### Solution

If the community wants to use custom status types like "is-accent", b-field (and probably other components too) need to be rewritten. However, just returning an empty string as a default will result in the same error as above. A solution could be to handle a default disabling icons when no default status type is used or or allowing to set a custom icon and custom status type.

**Comment by yxngl** [comment]
I think it needs some clarification, as your sandbox is missing proper CSS and I cannot see the error.

Are you asking about the icon on the right, which is currently non-configurable and only automatically derived for success, warning, info, danger and password? The `icon` prop is for the icon on the left and it is always grey. I think you can set the left icon and a custom color for the field boundary with the `type` prop on `b-field`. 

Below the first is using custom `twitter` color as defined in the customization doc.
```
    <b-field position="is-centered" type="is-twitter">
      <b-input placeholder="Search..." expanded custom-class="is-medium" type="text" icon-pack="fas" icon="heart"/>
    </b-field>
```
![image](https://user-images.githubusercontent.com/1696853/59454350-7613b980-8dd7-11e9-9b77-433198d2010b.png)


Asking for customization of the right icon is a feature request.

**Comment by agcty** [comment]
@yxngl sorry, updated the sandbox and issue accordingly, the main problem in my opinion is that there is an error when using b-field with custom colors/status types and fontawesome. The error comes from vue-fontawesome and is always thrown when using custom colors because it is hardcoded in the buefy source.

![image](https://user-images.githubusercontent.com/12101091/59489390-56859b00-8e82-11e9-8e99-4f1fba42b28b.png)

**Comment by luixal** [comment]
Got here having the same problem. Every time b-field gets rendered, throws out the same error about an undefined icon. It's really annoying.

Any way to avoid this?

**Comment by jtommy** [comment]
@agcty Sure, you have to import all icons that Buefy hardcoded in the source or all icons that you think to show related to statuses.

Please take a look at official docs and you'll find an example with all icons to include
