### ISSUE TITLE
Tooltip  using  'always'  is Overlay on modal

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1473]
I set a tooltip using  'always' props in my main view, it work very well. 

` <b-tooltip
              label="開始年齢より終了年齢が大きい"
              :active="errCheck.age"
              type="is-danger"
              :always="errCheck.age"
            >`
![image](https://user-images.githubusercontent.com/49149068/59478271-afa9fa80-8e93-11e9-844e-aaa33edd7121.png)

But When I show a modal over my main view,  the tooltip overlay on the modal.
How can I resoled it?
![image](https://user-images.githubusercontent.com/49149068/59478412-2646f800-8e94-11e9-9e05-79a7804ed734.png)

**Comment by service-paradis** [comment]
You are right. `z-index` is 888 for the tooltip and 40 for the modal.
We should probably decrease the tooltip `z-index` to 38 or something like this. We sould also add a condition when a tooltip is inside a modal to increase the value.

This would be a breaking change.

**Comment by juanfabrega** [comment]
Hi @service-paradis I recently ran into a related issue whereby a tooltip inside the modal appears cutoff by the modal card body. In your view is this expected and requiring a PR to fix (happy to contribute), or perhaps user error on my part?

**Comment by rolandschuetz** [comment]
@service-paradis Since the tooltip inside a modal is already inside the modal "stack", no need to have a higher `z-index`. The `z-index` is only compared to other elements inside the modal for ordering.

So this fixes the issue:
https://github.com/buefy/buefy/pull/2139
