### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1474]
Comment.

**Comment by afwn90cj93201nixr2e1re** [comment]
latest version of buefy

![GIF](https://user-images.githubusercontent.com/9306996/59485188-c9444580-8e85-11e9-95c2-00f06056816f.gif)


Im just moving mouse and select scroll's. Every select's scroll's, native too.
How i can disable it?

**Comment by jtommy** [comment]
I'don't understand the issue and anyway i think it's a generic select issue
