### ISSUE TITLE
Paging number is not in 1 line

### ISSUE THREAD

**Issue by dangbh1002** [buefy/buefy#1476]
Paging number is not in 1 line. You can see the image bellow, number 10 have problem, it's break-line.

<img width="301" alt="Screen Shot 2019-06-15 at 9 55 28 AM" src="https://user-images.githubusercontent.com/37328524/59546211-0414af00-8f54-11e9-9f73-2d59d9d0a3aa.png">

**Comment by jtommy** [comment]
Are you customize something ?

**Comment by service-paradis** [comment]
Also unable to reproduce.

@dangbh1002 can ou create a codepen with the minimal code required to get this behavior?
Can you also specify:
- Which version of Vue do you use?
- Which version of Buefy is installed?
- Which Browser do you use?

**Comment by dangbh1002** [comment]
I just open debug mode in buefy website and choose iPhone device.
Small width device will show that problem.

**Comment by service-paradis** [comment]
I can reproduce the issue since 0.8.1.
There are new props now to control how many buttons are displayed. Maybe Buefy will need some conditions for mobile.
