### ISSUE TITLE
b-pagination current page value issue

### ISSUE THREAD

**Issue by Alvazz** [buefy/buefy#1478]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.1]
**OS/Browser**: Chrome 75.0.3770.80

### Description

I follow the instructions in the documentation exactly. use like this

```
<template>

.....

<b-pagination :total="total" :current.sync="current" :per-page="perPage" @change="onPageChange(current)" aria-next-label="Next page" aria-previous-label="Previous page" aria-page-label="Page" aria-current-label="Current page">
            </b-pagination>
...

export default {
     ...
     data() {
        return {
            total: 50,
            perPage: 20,
            current: 1,
        } 
    }

}
```

when I click (onPageChange) No.2 button 

![1560611186331](https://user-images.githubusercontent.com/50744096/59553069-4379e480-8fc2-11e9-86dc-f89e35a06340.jpg)

get the current is 1, when I click No.3 button get the current is 2. 

Why is this?

Shouldn't the value of currentPage obtained by clicking the second button be 2?

**Comment by Alvazz** [comment]
```
onPageChange(val){
            
            this.current = val;

            console.log('manager.vue onPageChange event', this.current);
        },
```

**Comment by jtommy** [comment]
Why are using .sync and page change event ? You should use .sync + watch or change event without .sync

**Comment by Alvazz** [comment]
@jtommy Sorry, I am a newbie and I am bothered by you, sorry!
If you don't add .sync, like this: current.sync = "current", it seems that when I click the second button, I can't select it. Sir, can you give me an instance code? I just learned js, thank you very much.

**Comment by Alvazz** [comment]
i want use as you said or change event without .sync, so how can i do sir. pls.

**Comment by Alvazz** [comment]
I just want when i click the page button ,get the correct page number from the page button in onPageChange

**Comment by jtommy** [comment]
https://codepen.io/anon/pen/RzaGMr?editors=1010
