### ISSUE TITLE
Feature Request: Rotate Checkbox (Material Design)

### ISSUE THREAD

**Issue by Sogl** [buefy/buefy#1479]
Would like to see this effect on checkboxes:
![check](https://user-images.githubusercontent.com/7556290/59711442-ce055280-9213-11e9-8e31-e8c9713f1b4f.gif)

For example, it's used in Material Design:
https://codepen.io/rkchauhan/pen/ONJEYL

**Comment by jtommy** [comment]
@Sogl at the moment I don't think to add any animations on checkboxes
