### ISSUE TITLE
NumberInput does not stay set to required value when v-model changes

### ISSUE THREAD

**Issue by beelinda05** [buefy/buefy#1480]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**:
MacOS and Windows 10/Chrome

### Description
The number input control relies on a mouse event to stop decrementing/incrementing of values. This allows users to long press the control to change values efficiently, however, it also causes a problem when changing values programmatically as a change event gets called but no stop event seems to be triggered when a button is disabled.

https://codepen.io/anon/pen/YopXRw?&editable=true&editors=101

![numInputBug](https://user-images.githubusercontent.com/7684227/59773046-de194280-92a4-11e9-85cc-28cd61a23d78.gif)

### Steps to reproduce
1. Set max and min for the number input (e.g. 1 and 7) and bind value using v-model
2. Long press the minus button to decrease the value of the number to the min value (e.g. 1) so the decrement button is disabled
3. Try to set the bound v-model value to a different number (e.g. 3) without using the number input control

**Result:** The number input will change to the new value but then decrement all the way back down to the min value.

~~(May need to repeat steps 1-3 a few times as results aren't super consistent but should be easy enough to reproduce)~~ EDIT - can consistently reproduce results when long pressing to increment/decrement values

Same thing happens when incrementing all the way to max (instead of min) and then changing values. The number will change and increment all the way to the max value.

### Expected behavior

When the v-model value is changed, the number input value will be set to the required value without incrementing/decrementing to the max/min value by itself.

### Actual behavior
When the v-model value is changed, the number input value is set to the required value but then auto increments/decrements all the way to the max/min value

**Comment by yxngl** [comment]
Long press to the min/max disables the button, which does not trigger mouse leave to clean up on Chrome. 
https://bugs.chromium.org/p/chromium/issues/detail?id=120132
