### ISSUE TITLE
Buefy Virtual Scroll

### ISSUE THREAD

**Issue by amirhkhadem** [buefy/buefy#1481]
I have a big json data set (20,000 rows in 14 columns) which gets injected into the buefy table. I display 250 rows per page, with paging enabled on the b-table.

There is validation involved with vee-validate on blur. All this makes my input fields a bit laggy, so I'm looking to implement virtual scroll on the table items.

I would like to note that there is no lag effect on 80 rows per page but I need to show 250 per page for sure, or no pagination would be my ideal situation.

What is the best way to do this?

**Comment by afwn90cj93201nixr2e1re** [comment]
> There is validation involved with vee-validate on blur. All this makes my input fields a bit laggy, so I'm looking to implement virtual scroll on the table items.

1) You can make extra dialog/modal where you gonna provide some input label's(without v-model/v-bind), and on action just update table row.

2) You can use additional page, like edit or smthng like 'dat.

3) Just split dataset, from arr[], to arr[pages][].

Then at first page you got
250 rows from array first cell, on second from second cell etc.
```
[
   [{}.{}.{}.{}.{}...],//page 1
   [{},{},{},{},{}...]//page2
]
```
also seem's you need to read 'bout seek pagination method if 'u'r using databases.

**Comment by jtommy** [comment]
Table component needs improvments but they are really so much data.
Anyway for general questions, please join [official Discord server](https://discordapp.com/invite/ZkdFJMr).

**Comment by slidenerd** [comment]
@amirhkhadem your backend needs to enable search filter and sort for the table data, if you are loading 20000 rows into your frontend and then filtering you are not doing it right

**Comment by pedrosimao** [comment]
Virtual scroller would actually solve performance issues on the Table component without the need for pagination (which is not the best UX design in most cases)
