### ISSUE TITLE
Option 'button' in prop 'canCancel' on Modal component

### ISSUE THREAD

**Issue by VictorOtavio** [buefy/buefy#1482]
Modal component has, by default, an array [with 4 options in prop `canCancel`](https://github.com/buefy/buefy/blob/80cff6eb21eb66f520c4fc1279445dcba8d8fe28/src/components/modal/Modal.vue#L59). However, the `'button'` option does not represent any action within the component. Is this a bug? Or this option isn't implemented yet?

**Comment by jtommy** [comment]
It's no necessary but it's a way to close dialog (subcomponent of modal).
Anyway I'm going to improve it, thanks

**Comment by jtommy** [comment]
close https://github.com/buefy/buefy/commit/319e29f65693fc64a957c6125cbccaae6264b98f
