### ISSUE TITLE
Feature Request: Language Agnostic DatePicker by using Intl

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1486]
### Overview of the problem

**Buefy** version: 0.7.7
**Vuejs** version: 2.6.10

### Description

Right now, the values for days and month name are hardcoded directly in the component as prop default. We can use this prop if we want to localize into another language, but we need to keep or generate arrays for different supported languages.

I Think it would be great to use [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) instead.
> The Intl object is the namespace for the ECMAScript Internationalization API, which provides language sensitive string comparison, number formatting, and date and time formatting.

This way, the component could use the browser detected language by default instead of using english. We could also used one prop (ex. `locale`) to support localization. We should accept a [Bcp47](https://tools.ietf.org/html/bcp47) language tag as accepted by `Intl.DateTimeFormat`.

This is how [v-calendar](https://github.com/nathanreyes/v-calendar) is working right now. You can see `getMonthNames` and `getDayNames` functions in this [file](https://github.com/nathanreyes/v-calendar/blob/6a6d9f82e737044acfe68d960cc33b0246796e02/src/utils/locales.js).
[Bootstrap-Vue](https://bootstrap-vue.js.org/docs/components/form-datepicker#internationalization) is also using this in their Datepicker.

I know it is a breaking change, but wanted to start a discussion about this. I could probably work on it if it is something you would find useful.

### Expected behavior

I expect to use only one prop to specify a locale for this component.
ex. `:locale="currentLocale"` where `currentLocale` could be any values like "en-US", "fr-CA", ...

It would be easier to manage than generating 2 arrays depending on the current language to send them as props. The component would also become language agnostic.

### Actual behavior

We need to generate `month-names` and `day-names` each time we change the locale.

**Comment by afwn90cj93201nixr2e1re** [comment]
Same with toast/messages and other component's which accept's hard coded string's which can't be changed with computed stuff.

**Comment by service-paradis** [comment]
Intl could aso be used to format number accordingly (ex. in progress component):
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

This way, decimal separator and thousand separator could be formatted using a specified locale.

**Comment by jtommy** [comment]
@service-paradis we might follow your idea

**Comment by service-paradis** [comment]
This would be a breaking change for sure. We would need to accept a new options in Buefy for the locale (ex. `en-US`). Every component where we use Date/Time/DateTime would also need to be changed.

We could use this to format the date, but even to have the localized string needed (ex. month names).

I dont know, if this will really solve the problem mentioned in #1957 though. Would need to make some tests before since it looks to be related to Timezone more than Locale...

**Comment by jtommy** [comment]
@service-paradis we could use a default value, for example getting it from `navigator` object

**Comment by service-paradis** [comment]
The only problem I see with using the browser locale (ex. `navigator`) is when a website does not support multi language. Some components would then be displayed in the user component language, but not the other element of the website.

For example, I would loo a the Buefy documentation pages where everything is in english, but then I will see month names in french when using the Datepicker.

**Comment by service-paradis** [comment]
https://github.com/buefy/buefy/pull/2581
