### ISSUE TITLE
Autocomplete async load more button

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1489]

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you implement loadmore button for autocomplete?
Or add some footer slot for it, where i can just add button for seek pagination method?

@yxngl | @jtommy

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59891396-08264e00-93e6-11e9-8849-531b8b42cef6.png)
Ok, i get it.

**Comment by jtommy** [comment]
There is already footer slot, you might use it

**Comment by afwn90cj93201nixr2e1re** [comment]
@yxngl  |  @jtommy there a bug in autocomlpete click handler.

**Comment by afwn90cj93201nixr2e1re** [comment]
```
            /**
             * Close dropdown if clicked outside.
             */
            clickedOutside(event) {
				console.log(this.whiteList);
				console.log(event.target);
                if (this.whiteList.indexOf(event.target) < 0) this.isActive = false
            },
```

Just try to debug it.
As you can see it's gonna close every click, not only outside.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59903612-754fd880-9412-11e9-9e2a-1b3645dedc52.png)
For example add footer slot, or click on some option in autocomplete. And isActive gonna false.

![изображение](https://user-images.githubusercontent.com/9306996/59903661-a03a2c80-9412-11e9-84a8-51b1f403d30c.png)
Clicking on option. There no meda-content in whiteList array.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59903740-ceb80780-9412-11e9-8d08-403ef1c68bbb.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
Seem's like ref="dropdown" should be on dropdown-content.

**Comment by afwn90cj93201nixr2e1re** [comment]
Im gonna try to check it.

**Comment by afwn90cj93201nixr2e1re** [comment]
Seem's like  ref="dropdown" should be on dropdown-content, and then we must refactor whiteList function in computed, coz.
