### ISSUE TITLE
Broken UI if using an expanded and required in <b-input>

### ISSUE THREAD

**Issue by nakorndev** [buefy/buefy#1490]
### Overview of the problem

**Buefy** version: 0.7.7
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10, Google Chrome latest version

### Description

```
<b-field>
  <p class="control>
    <span class="button is-static"> @
  </p>
  <b-input v-model="username" expanded required>
</b-field>
```

As example, on `b-input` if there contains `expanded` with `required` then a message "Please fill out this field." will be shown at same line and cause a UI problem.

GIF: https://gfycat.com/offensivequalifiedgypsymoth

To fix this `p.help.is-danger` should nest inside `div.control` below of `input`

**Comment by jtommy** [comment]
Take a look at https://github.com/buefy/buefy/issues/1453
