### ISSUE TITLE
Unknown custom element: <b-table-column>

### ISSUE THREAD

**Issue by Olegars** [buefy/buefy#1491]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: linux/firefox

I try to register the component "table"  as described here
[https://buefy.org/documentation/start/](https://buefy.org/documentation/start/)

>import Vue from 'vue'
>import { Table } from 'buefy/dist/components/table'
>import 'buefy/dist/buefy.css'
>Vue.component('b-table', Table)

but I get error
`"[Vue warn]: Unknown custom element: <b-table-column> - did you register the component correctly?"`
How to fix it?

**Comment by service-paradis** [comment]
You need to import `TableColumn` and add it as a Vue component.
```
import Vue from 'vue'
import { Table, TableColumn } from 'buefy/dist/components/table'
import 'buefy/dist/buefy.css'
Vue.component('b-table', Table)
Vue.component('b-table-column', TableColumn )
```

**Comment by slidenerd** [comment]
If i dont write import 'buefy/dist/buefy.css' and then directly @import "~buefy/src/scss/buefy" the styles are not getting applied, this scss file is being included globally in nuxt.config.js

**Comment by subins2000** [comment]
Another way to do is :

```
import Table from 'buefy/dist/components/table'
Vue.use(Table)
```
