### ISSUE TITLE
Timepicker with a getter and setter computed value doesnt work

### ISSUE THREAD

**Issue by erwanpoupard** [buefy/buefy#1492]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: win 10 / Chrome

### Description
A timepicker with a computed value (getter and setter) doesnt work properly. Here is a pen : 
https://codepen.io/erwanpoupard/pen/mZWEPV

### Steps to reproduce
1. change the hour or minute

### Expected behavior
the setter of computed value should update the data

### Actual behavior
the data isnt updated. But if i change again the timepicker hour or minute, my data is updated with the previous timepicker value

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/1418#issuecomment-502449012.
It will be available in the next release
