### ISSUE TITLE
Dropdown creating extra space inside container

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1494]
Comment

**Comment by afwn90cj93201nixr2e1re** [comment]
Latest bulma
Latest buefy.
![изображение](https://user-images.githubusercontent.com/9306996/59966110-4f1c5c80-9528-11e9-8362-5712e6eb86e0.png)
https://codepen.io/anon/pen/vqxorp?editors=1000

Same with autocomplete dropdown.
When i remove position absolute - everything work's well.

Fix it asap.
Very anoying.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59966254-d965c000-952a-11e9-88a4-2231075aead8.png)
Maybe we should add max-height + overflow-x: auto for creating scrollbar instead overflow fullpage?

autocomplete already have it this css rules.
https://github.com/buefy/buefy/blob/dev/src/scss/components/_autocomplete.scss#L12

**Comment by afwn90cj93201nixr2e1re** [comment]
So.
![изображение](https://user-images.githubusercontent.com/9306996/59966313-d6b79a80-952b-11e9-94a9-b33b39395dff.png)
is-inline is workaround it.
But if i use inline - it's remove trigger. So, can you add new prop for custom class?

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59966166-57c16280-9529-11e9-8d20-4337d66f21ee.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59966424-a96bec00-952d-11e9-89d1-c8622c794e6e.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
Also seem's you must remove it.
https://github.com/buefy/buefy/blob/a06eed4b2753d31a8082be68397b643b922e2cd8/src/components/dropdown/DropdownItem.vue#L67

or add check if $parent.$parent not dropdown.
Coz there can be blank dropdown item(custom prop) which isn't clickable.

**Comment by afwn90cj93201nixr2e1re** [comment]
Add to roadmap - refactor dropdown.

**Comment by jtommy** [comment]
You should use autocomplete when you have to show so many options
Please you don't open an issue for many questions and respect the template

**Comment by afwn90cj93201nixr2e1re** [comment]
Why are you closing issues everytime without investigate?
Autocomplete doesn't have multiplie choice.
How i should use it?
 Damn boi.
@jtommy

**Comment by jtommy** [comment]
The multiple version of autocomplete is taginput

**Comment by afwn90cj93201nixr2e1re** [comment]
Taginput is taginput, coz there no multiplie choice, select list is select list, autocomplete dropdown also create extra space, taginput dropdown also create extra space. This is overflow issues.
