### ISSUE TITLE
Programatically opening autocomplete via taginput

### ISSUE THREAD

**Issue by wrabit** [buefy/buefy#1498]
Latest Buefy, Chrome, OSX

In the example:

`<b-taginput ref="taginput" autocomplete />`

We can read the value of autocomplete's isActive with either

`this.$refs.taginput.$refs.autocomplete.isActive`
or `this.$refs.taginput.$children[0].isActive`

but when trying to set it (to programatically control opening / closing of the autocomplete dropdown) it does not update and the value remains false and dropdown closed.

Should this be possible? Anything I am missing that's preventing it?

**Comment by cuong-nguyen** [comment]
@wrabit This is a bit hacky but works
```
this.$refs.taginput.$refs.autocomplete.$el.querySelector('input').focus()
this.$nextTick(() => { this.$refs.taginput.$refs.autocomplete.isActive = true })
```

**Comment by wrabit** [comment]
@cuong-nguyen that focuses it but still no dropdown :confused:

**Comment by jtommy** [comment]
@wrabit are you using vue 2.6.x ?

**Comment by wrabit** [comment]
@jtommy yes v2.6.7

**Comment by jtommy** [comment]
Because `$nextTick` was ok on 2.5.x but there is a change in 2.6.x

**Comment by wrabit** [comment]
@jtommy never knew, thanks

Thanks @cuong-nguyen for the insight, it's working with:

`setTimeout(() => { this.$refs.taginput.$refs.autocomplete.isActive = true },0)`
