### ISSUE TITLE
How to use material icons from this package

### ISSUE THREAD

**Issue by prsolucoes** [buefy/buefy#1500]
### Overview of the problem

**Buefy** version: 0.7.7
**Vuejs** version: 2.5.2
**OS/Browser**: chrome

### Description

I need use material design icons offline. So, im using this package:
https://www.npmjs.com/package/material-design-icons-iconfont

The problem is that package don't work with buefy and table sort icons don't appear.

There is any way to use it with this package? Or there is any way to use the buefy material design icons offline without need put the head link for it?

```
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.5.94/css/materialdesignicons.min.css">
```

Screenshot:
![image](https://user-images.githubusercontent.com/395096/60106990-7a779500-973c-11e9-95cb-0d7a5822b388.png)

Thanks.

**Comment by prsolucoes** [comment]
Hi,

I solved it using this package (@mdi/font) and importing it on main.js:

```
import '@mdi/font/css/materialdesignicons.css'
```

Thanks.

**Comment by jtommy** [comment]
All right!

**Comment by robertpro** [comment]
I think this should be in docs, I didn't found how to do it in the icon documentation: https://buefy.org/documentation/icon

**Comment by robertpro** [comment]
I think I am wrong, it is documented on the start page... https://buefy.org/documentation/start

**Comment by parzibyte** [comment]
First:
`npm install --save @mdi/font`
Then, in your **main.js** import it. For example:
```js
import Vue from 'vue'
import App from './App.vue'
import '@mdi/font/css/materialdesignicons.css' // <-- Just here
import Buefy from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Buefy);
Vue.config.productionTip = false;

new Vue({
    render: h => h(App),
}).$mount('#app');

```
Buefy will use the material icons by default, so no extra configuration is needed ;)

**Comment by lgarczyn** [comment]
That works for basic icons, for for some reason many icons on the material design websites are unavailable, such as `category` and `room`.

**Comment by peterarends** [comment]
When you use Buefy with Nuxt, you can add this line at the top of app.scss:

`@import '@mdi/font/css/materialdesignicons.css';`

@lgarczyn only the icons listed at https://materialdesignicons.com/ are included I think.
