### ISSUE TITLE
TimePicker Editable not that useful

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#1501]
I wanted my TimePicker to be Editable but there are few issues that make this option not usable.

1. The popup picker still appears even though I can directly edit the field. This is extremely confusing to the user. The popup picker should not pop up.

2. Entry into the field should be masked so I can only type in the time numbers and am/pm. RIght now, I can type in anything.

**Comment by jtommy** [comment]
@kerbo
2) you should be able to set a id to the component and apply on it your logic (for example cleave.js, etc)
1) without picker it is a simple input, don't you ?

**Comment by kerbo** [comment]
Yes, configuring my own masked input is the answer.
