### ISSUE TITLE
Snackbar type doesnt work

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1504]
https://github.com/buefy/buefy/blob/dev/src/components/snackbar/Snackbar.vue#L8

As you can see type is not needed there.
![изображение](https://user-images.githubusercontent.com/9306996/60173568-19c18880-9820-11e9-9a07-0d792cf5aff6.png)
maybe you should delete it on line # 8?
Or maybe you should fix it in css styles?

Coz toast have notice type.
![изображение](https://user-images.githubusercontent.com/9306996/60173667-52616200-9820-11e9-8e7d-3d19209a48b4.png)

As you can see:
https://github.com/buefy/buefy/blob/a6f57b4182bf6445d59455defc7b3d7226d003d6/src/scss/components/_notices.scss#L25

https://github.com/buefy/buefy/blob/a6f57b4182bf6445d59455defc7b3d7226d003d6/src/scss/components/_notices.scss#L43

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/afwn90cj93201nixr2e1re/buefy/commit/5ae198d974d2774d99b10bd2abb40e0d34986549#diff-7bf4989d443c881bb9a1086ebe9580c5L1

https://github.com/afwn90cj93201nixr2e1re/buefy/commit/5ae198d974d2774d99b10bd2abb40e0d34986549#diff-a67dc5335d172c658ed7c3260d6029b6R38
https://github.com/afwn90cj93201nixr2e1re/buefy/commit/dbde94e40c0cc722245cca703326f8f8fdee0fee



![изображение](https://user-images.githubusercontent.com/9306996/60245325-6f07a380-98cd-11e9-9891-4761fde3b670.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245342-75961b00-98cd-11e9-8cce-16d0adcfafeb.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245387-93fc1680-98cd-11e9-8fc5-61d251271f01.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245401-99596100-98cd-11e9-9110-052626f05378.png)
etc.
@jtommy can you merge it into buefy?

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/60245707-31574a80-98ce-11e9-9ab2-51861426eeca.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245720-3916ef00-98ce-11e9-9873-428130971fa5.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245761-4b912880-98ce-11e9-9165-a73073a57661.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245770-51870980-98ce-11e9-9131-617f5ac519ab.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245802-62d01600-98ce-11e9-8496-daeaadf12062.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245811-682d6080-98ce-11e9-9e03-c67c81d6db14.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245851-81cea800-98ce-11e9-9485-2ade53a8fecb.png)
![изображение](https://user-images.githubusercontent.com/9306996/60245866-87c48900-98ce-11e9-96b4-9a413cbc04e5.png)

**Comment by service-paradis** [comment]
I'm not sure, but I think the goal of the Snackbar was to only color the buttons (like the one used in Gmail). Maybe @jtommy could confirm this.

Also, you should follow the template when you open Issues.
You could also open a PR when you make changes instead of copying links to commit. This way your changes could be reviewed there and merged if accepted.

**Comment by jtommy** [comment]
@service-paradis, you're right all along, thanks!

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems like no one read issue topic fully. Damn. Again.
Why he add type into classes of snackbar? Maybe he should just remove it if is it only one color at all?

@service-paradis especially for you.

There no restrictions bout colours in spec. Is that breakable change? Seems like no. https://material.io/design/components/snackbars.html#implementation

Also https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/snackbars/contextual.vue

> You could also open a PR when you make changes instead of copying links to commit. This way your changes could be reviewed there and merged if accepted.

I know how to use pr's. But he doesn't accept any bug fixes, coz doesn't understand how it's work.

It also seems that jtommy ruins a project more than its development.  this is evident from its activity in pr.

Don't ask him bout advice, seems like he never heard bout automerging. 
https://github.com/buefy/buefy/pull/1488#issuecomment-504359072

**Comment by afwn90cj93201nixr2e1re** [comment]
@rafaelpimpa

Read all my comments and pr's and made 
 conclusions about jtomy's work on improving the project’s user customization.

**Comment by service-paradis** [comment]
@afwn90cj93201nixr2e1re

I read your issue even if you were not using the **template** and that you were splitting it into multiple comments and commits.

 You are right that the class added directly to the snackbar is not in use, but my previous answer was correct. If you want it to be removed, feel free to make a PR.

About your commit and the color spec, yes it is a breakable change. If someone use snackbar right now with a type (ex. is-danger). The expected behavior is to only have the buttons to be colored. The behavior would change for those who uses it if your changes are merged.

**Comment by afwn90cj93201nixr2e1re** [comment]
> If you want it to be removed, feel free to make a PR.
I made some pr's, but no one accepted.

> About your commit and the color spec, yes it is a breakable change.
So it's just an example, rename buttonColor -> snackBarColor, add type to button class, add snackBarColor to to snackbar. and etc. It's just example.

**Comment by service-paradis** [comment]
Yeah, you made 4 exactly: https://github.com/buefy/buefy/pulls?utf8=%E2%9C%93&q=author%3Aafwn90cj93201nixr2e1re+

There was always a reason why it didnt get accepted.

Also, if you were able to respect the issue template and if you were able to show some respect, it would be easier to try to understand you an to help you out.

You are there always complaining about everything without showing respect to Buefy Guidelines and to everybody that contribute to it.

What you ask is to add a possibility to add color to the snack bar. It is easy to ask this simple thing using the Issue Template.

**Comment by afwn90cj93201nixr2e1re** [comment]
Actually nothing on the case.
