### ISSUE TITLE
Feature Request: Allow Sync with button states

### ISSUE THREAD

**Issue by BlueFrog130** [buefy/buefy#1506]
### Description
I would like to be able to sync data to `b-button` props such as focused, hovered and so on. My goal I'm trying to accomplish is animate an element when hovering over my `b-button` element. I can my own props to fill the hovered value, but it seems that doing what I would like would be very complex going off of current features. 
I was hoping that something like the `b-table` `:selected.sync` could be added for some button elements.

**Comment by jtommy** [comment]
I don't understand well, by the way you decide the state of button so you can propagate it to other components

**Comment by BlueFrog130** [comment]
I really didn't explain well... All I'm trying to do is set a conditional class based off of the hover state of `b-button`.

Turns out doing what I was trying was fairly simple using vue's `@mouseover` and `@mouseleave` events, but it would be nice to be able to set `custom-class` for icons in buttons.

**Comment by jtommy** [comment]
Are the icons in the button? You should be able to do using CSS
