### ISSUE TITLE
buefy b-radio button showing wierd shape after selection

### ISSUE THREAD

**Issue by rgnanase** [buefy/buefy#1509]
Overview of the problem
Buefy version: [0.7.4]
Vuejs version: [2.6.10]
OS/Browser: Chrome

Description
I am using b-radio in a modal and when I select any of the values from the radio, the selected value looks in a wierd shape. Please look at the image attached.
![image](https://user-images.githubusercontent.com/11338828/60288136-8cdf0380-98e1-11e9-96b4-c28bfb5aa38e.png)

Expected behavior
I want the selected value to show normal.

Actual behavior
Shape and size of the dot changes.

**Comment by afwn90cj93201nixr2e1re** [comment]
Provide fiddle.

**Comment by service-paradis** [comment]
@rgnanase 
Not able to reproduce on my side. Can you provide a minimal codepen where we can see this behavior?

**Comment by rgnanase** [comment]
I updated the version of Buefy to the latest version and the error went away
