### ISSUE TITLE
Feature Request: New props to have a colored snackbar

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1510]
### Overview of the problem

**Buefy** version: 0.7.8
**Vuejs** version: 2.6.10
**OS/Browser**: any

### Description

Right now, there is a prop to style the button of the snackbar component. I would appreciate if there was a prop that could be used to also color the component itself (like toast where the background color can change).

### Expected behavior

I would appreciate if we could style the background color of the component and/or the button

### Actual behavior

Only the snackbar cutton can be colored.

**Comment by service-paradis** [comment]
@afwn90cj93201nixr2e1re
Is this what you want? You see, a simple title, the template usage, no insults!

**Comment by afwn90cj93201nixr2e1re** [comment]
For what are you writing the tonn of text if you can just shoe the line where os issue?

**Comment by jtommy** [comment]
@service-paradis I don't think to improve snackbar and toast to be honest because I would like empower notification component

**Comment by jtommy** [comment]
@service-paradis I don't think to improve snackbar and toast to be honest because I would like empower notification component

**Comment by afwn90cj93201nixr2e1re** [comment]
They must be separate, coz they are already implemented.

**Comment by service-paradis** [comment]
@jtommy 
I think a single component could be made for notification/snackbar/toast behaviors. It would need a little more props to customize the behavior.
It would need to be made on a major release for sure.

You could maybe open an issue for discussing about this?

**Comment by jtommy** [comment]
At the moment toast and snackbar respect the material design concepts, so I don't think to agree with this feature request

**Comment by service-paradis** [comment]
You're right. I don't need this specific PR anyway to be honest ;)

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems like he doesn't read specs, lol.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, can we just add new prop for buttonType which gonna be same as type by default?
Coz i really need customize it, but i don't wanna copy some of buefy code.
https://github.com/buefy/buefy/blob/dev/src/components/snackbar/Snackbar.vue#L14 change it to `newButtonType`

https://github.com/buefy/buefy/blob/dev/src/components/snackbar/Snackbar.vue#L28
add here
```
buttonType; ''
```

In `data()` add
```
newButtonType: this.buttonType || this.type
```

Then we gonna have ability to change colors via using custom scss.
https://github.com/afwn90cj93201nixr2e1re/buefy/blob/a7c1b1d41fc65802ee30f83d8e7feb106e8af774/src/scss/components/_notices.scss#L40


I think it's not brekable change, but it's useful for users.

@jtommy, @service-paradis 

https://github.com/buefy/buefy/issues/1504#issuecomment-506225727
