### ISSUE TITLE
Buefy modal dialog breaks on zoom level 150 and above

### ISSUE THREAD

**Issue by krupa-shah** [buefy/buefy#1511]
### Overview of the problem

**Buefy** version: [0.7.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: windows/Chrome

### Description

I have a modal dialog, on zoom level 150 my footer is hidden on screen

### Steps to reproduce

clone repo: https://github.com/krupa-shah/buefyDialog
Click on dialog button.
Increase browser zoom level to 150.

Observe footer is hidden.

### Expected behavior

A scroll should be displayed to user if zoom level increases.

### Actual behavior

Footer is hidden.
![zoom150](https://user-images.githubusercontent.com/31436792/60334893-3265a600-99ba-11e9-983a-5635f87d1687.PNG)

**Comment by jtommy** [comment]
@krupa-shah Please remove the div after `modal-card`
