### ISSUE TITLE
DatePicker doesn't open programmatically

### ISSUE THREAD

**Issue by MelvinFrohike** [buefy/buefy#1515]
### Overview of the problem

**Buefy** version: [0.7.8]
**Vuejs** version: [0.7.5]
**OS/Browser**: macOS Chrome & iOS Safari

### Description

Opening the Datepicker programmatically like described in the docs doesn't work.
Visually, nothing happens at all. There seem to be two different issues for mobile (<= 768px) and larger windows: 

**Mobile**
In iOS Safari, the reference cannot be found: 

> Error in v-on handler: "TypeError: Cannot read property 'toggle' of undefined"

On larger browser windows, when watching the DOM and the Vue Events it becomes apparent, that the Datepicker actually is opened and triggers an _active-change_ event, but is then closed immediately with another _active-change_ event triggered.

### Steps to reproduce

Copy the example from the docs and click the button.
Alternatively, open the codepen link from the docs. It doesn't work either. Curiously, the embedded example in the docs works just fine.

### Expected behavior

The Datepicker selector should open

### Actual behavior

The Datepicker selector does not open.

**Comment by jtommy** [comment]
I think it's related to vue version 2.6.x
