### ISSUE TITLE
Month picker sets invalid date on iOS Safari

### ISSUE THREAD

**Issue by MelvinFrohike** [buefy/buefy#1516]
### Overview of the problem

**Buefy** version: [0.7.8]
**Vuejs** version: [2.6.10]
**OS/Browser**: iOS Safari

### Description

Selecting a month with a month picker in iOS Safari sets an invalid date.
It works fine on macOS Safari and macOS Chrome. A normal Datepicker works fine on iOS as well.

### Steps to reproduce

```
<b-datepicker
          type="month"
          ref="datepicker"
          :value="currentDate"
          @input="onDateChanged"
         />

onDateChanged (newDate: Date) {
    alert(newDate)
}
```

### Expected behavior

The output should show the date for the first of the selected month.

### Actual behavior

the output shows "invalid date"

**Comment by afwn90cj93201nixr2e1re** [comment]
` Vuejs version: [0.7.5]`
tf?

**Comment by MelvinFrohike** [comment]
> `Vuejs version: [0.7.5]`
> tf?

Sorry about that, somehow I got this confused with the Burma version. I've corrected my post to show the correct Vuejs version 2.6.10

**Comment by afwn90cj93201nixr2e1re** [comment]
```
onDateChanged (newDate: Date) {
    alert(newDate)
}
```
So, maybe problem in `newDate: Date` (typescript)?
Can you try write it without TS?
For example check this code on IOS device.
https://codepen.io/anon/pen/pXawox?&editable=true&editors=101

**Comment by MelvinFrohike** [comment]
This is indeed typescript code, however JS code has the same problem.
In fact, while your example works on iOS as written, it gives the same error once I change it to `type="month"`.

**Comment by jtommy** [comment]
I'll investigate about it
