### ISSUE TITLE
Hard revert

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1519]
You should hard revert this commit, instead soft revert.
https://github.com/buefy/buefy/commit/201692497c290445bb993d6630eb0ea5de81e135

Coz it's breakable change, and i cant merge update's into my fork.

**Comment by jtommy** [comment]
Please merge your branch with last commit

**Comment by afwn90cj93201nixr2e1re** [comment]
But i said that this is breakble change.

**Comment by jtommy** [comment]
What do you mean?
The current dev branch is ok at the moment

**Comment by afwn90cj93201nixr2e1re** [comment]
So, if i merge it, im gonna loose some of my changes, coz he used old branch, and i have some new commit's on it.
So, ok, im gonna try to merge manually commit by commit.
