### ISSUE TITLE
Feature request - responsive tabs -> accordion

### ISSUE THREAD

**Issue by wrabit** [buefy/buefy#1522]
I would really like to see tabs collapse to accordion so for mobile they become much more usable. I am working on a branch that adds this just wanted to check the likelihood something like this would be merged before I continue:

Animation:

![Screen Recording 2019-07-01 at 15 30 40 (2)](https://user-images.githubusercontent.com/5918271/60441144-aac8a300-9c16-11e9-93fb-9ca11a5a6eb4.gif)

**Comment by jtommy** [comment]
@wrabit Really nice!
I'll review your PR when you are ready
