### ISSUE TITLE
Native timepicker won't set value

### ISSUE THREAD

**Issue by TMantas** [buefy/buefy#1528]
### Overview of the problem

**Buefy** version: [0.7.8]
**Vuejs** version: [2.6.10]
**OS/Browser**: mobile (tested on iOS)

### Description

Very similar to #1418 but only on native mobile input.
In short: on native mobile input the timepicker's value won't change.
This worked with Buefy 0.7.7 and a few earlier versions.

### Steps to reproduce

1. Open [https://codepen.io/mantas-t/pen/wLXdYB](https://codepen.io/mantas-t/pen/wLXdYB) on mobile.
2. Try changing values on both inputs.

### Expected behavior

You should see both `value1` and `value2` changed and printed below input.

### Actual behavior

Only `Native disabled` value has changed and visible.

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/35019af69860e2b4bea7f00ec159f62412ead65e
