### ISSUE TITLE
When a b-button has a tag="router-link" the click event does not fire

### ISSUE THREAD

**Issue by three60** [buefy/buefy#1530]
### Overview of the problem

When a b-button has a tag="router-link" the click event does not fire

**Buefy** version: 0.7.8
**Vuejs** version: 3.1.3
**OS/Browser**: Mac/Chrome

### Description
When a b-button has a tag="router-link" the click event does not fire

### Steps to reproduce

<b-button @click="donaldSays" tag="router-link" to='/'>Click Me</b-button>

  donaldSays() {
    console.log("You're Fired!")
  }

### Expected behavior

click event fires

### Actual behavior
click event does not fire

**Comment by jtommy** [comment]
Using router-link you have to listen click.native event
