### ISSUE TITLE
Buefy constructor defaultIconPack seems not working?

### ISSUE THREAD

**Issue by ZendyLim** [buefy/buefy#1531]
### Overview of the problem

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: Firefox

### Description
When using Buefy constructor to set defaultIconPack to `fa`, `<b-button>` still not using `fa` as `icon-pack`

### Steps to reproduce
```
import Buefy from 'buefy';
import 'buefy/dist/buefy.css';
import '@fortawesome/fontawesome-free/js/all';

Vue.use(Buefy, {
  defaultIconPack: 'fa'
});
```

Then use `<b-button>`
```
<b-button class="is-primary" icon-left="save">
  <span>Submit</span>
</b-button>
```
### Expected behavior
`b-button` will use `fa` as `icon-pack` and display icon correctly

### Actual behavior
Icon not displayed
<img width="109" alt="image" src="https://user-images.githubusercontent.com/13291929/60636164-5577d600-9e50-11e9-91a4-d7a4f3ff1176.png">

Unless I misunderstood the `defaultIconPack` purpose, I think this is a bug?

**Comment by jtommy** [comment]
@ZendyLim you're importing FA5 so you have to use new conventions, for example `fas`
