### ISSUE TITLE
Icons do not work with web components build

### ISSUE THREAD

**Issue by PeteyRev** [buefy/buefy#1534]
### Overview of the problem
When targeting the web component build of the Vue CLI, font awesome icons do not show up

**Buefy** version: [0.7.8]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome 75 on macOS (Mojave)

### Description

I am not totally sure how to utilize the [fix for web components on vue-fontawesome ](https://github.com/FortAwesome/vue-fontawesome#web-components-with-vue-web-component-wrapper) in relation to Buefy, or if it is even possible.

### Steps
Using the default component in the constructor, I am importing this file on the root of my web component. All styling and JS works, but on build the icons are coming up empty:

```
import Vue from 'vue';
import Buefy from 'buefy';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faAngleRight, faAngleLeft, faAngleDown} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(faAngleRight, faAngleLeft, faAngleDown);
Vue.component('vue-fontawesome', FontAwesomeIcon);
Vue.use(Buefy, {
  defaultIconComponent: 'vue-fontawesome',
  defaultIconPack: 'fas',
});

```
### Expected behavior

https://screencast.com/t/JFkhsgYLRlpk

### Actual behavior

https://screencast.com/t/qQ1ghpLu0

**Comment by kyoukhana** [comment]
I am having the same issue 

## Main.js
```
import Vue from 'vue';
import App from './App.vue';

/*Vue FORM GENERATOR */
import VueFormGenerator from 'vue-form-generator';
Vue.use(VueFormGenerator);
import '../node_modules/vue-form-generator/dist/vfg.css';

/*Buefy */
import Buefy from 'buefy';
import 'buefy/dist/buefy.css';
Vue.use(Buefy);

/*Vue Router */
import VueRouter from 'vue-router';

Vue.config.productionTip = false;


Vue.use(VueRouter);


/*Define Routing */
import siteRoutes from './routes/site';
import customer from './routes/customer';

/*Define Routes Object */
const loadRoutes = [
  ...siteRoutes,
  ...customer
];


/*Define Router */
const router = new VueRouter({
  hashbang: false,
  linkActiveClass: 'active',
  mode: 'history',
  routes: loadRoutes,
});

Vue.router = router;
App.router = router;

new Vue({
  render: h => h(App)
}).$mount('#app')

```

## App.js

```
<template>
    <div id="main">
     
            <transition>
                 <router-view></router-view>
            </transition>
    
    </div>
</template>
<script>
    /*Import Header Footer */
    import hdr from './components/headerfooter/header.vue'
    import ftr from './components/headerfooter/footer.vue'

    export default {
        components:{
            hdr,ftr
        },
        
        mounted () {
         
        },
        created () {
        
        }
    }
</script>


<style lang="scss">
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

@import "./assets/scss/core";
@import "./assets/scss/forms";
@import "./assets/scss/custom";
</style>
```

**Comment by jtommy** [comment]
Did you check docs https://buefy.org/documentation/icon?

**Comment by kyoukhana** [comment]
I tried this but didn't work 

```
/*Font Awesome ICONS */
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {
  faCheck, faCheckCircle, faInfoCircle, faExclamationTriangle, faExclamationCircle,
  faArrowUp, faAngleRight, faAngleLeft, faAngleDown,
  faEye, faEyeSlash, faCaretDown, faCaretUp, faUpload
} from "@fortawesome/free-solid-svg-icons";


library.add(faCheck, faCheckCircle, faInfoCircle, faExclamationTriangle, faExclamationCircle,
  faArrowUp, faAngleRight, faAngleLeft, faAngleDown,
  faEye, faEyeSlash, faCaretDown, faCaretUp, faUpload);
Vue.component('vue-fontawesome', FontAwesomeIcon);

/*Buefy */
import Buefy from 'buefy';
import 'buefy/dist/buefy.css';
Vue.use(Buefy, {
  defaultIconComponent: 'vue-fontawesome',
  defaultIconPack: 'fas',
});

**Comment by kyoukhana** [comment]
I figured out what the issue is I needed to include faCalendarPlus to use it like this 
```
  <b-datepicker
                                    placeholder="Click to select..."
                                    icon="calendar-plus">
                                </b-datepicker>
```

**Comment by jtommy** [comment]
You might remove icon props if you don't need it

**Comment by PeteyRev** [comment]
@jtommy why is this closed? None of these answers relate to my question, this has to do when building as a web component

**Comment by jtommy** [comment]
@PeteyRev https://codesandbox.io/s/vue-template-4z39o

**Comment by PeteyRev** [comment]
@jtommy The icons work completely fine locally, and when I build out in either an app or library. It is only when I [build the as a web component](https://cli.vuejs.org/guide/build-targets.html#web-component) where they stop working.

**Comment by jtommy** [comment]
Are you sure about a Buefy issue ? Did you try a simple project with Vue-Fontawesome ?
Btw i haven't a good knowledge about web-component build

**Comment by PeteyRev** [comment]
@jtommy It seems to be a [known issue for vue-font-awesome](https://github.com/FortAwesome/vue-fontawesome#web-components-with-vue-web-component-wrapper) that requires a work around, and this works when you are importing as a component.

However, the buefy syntax for adding in the global config: 
```
Vue.use(Buefy, {
    defaultIconPack: 'fas',
    defaultContainerElement: '#content',
    // ...
})
```
So you can add as an attribute, to say buttons or inputs:
```
            <b-input placeholder="Search..."
                type="search"
                icon="magnify">
            </b-input> 
```
Will not work. So that makes me believe this may be an issue with Buefy.

**Comment by jtommy** [comment]
Did you find out a solution?

**Comment by service-paradis** [comment]
The config part seems to be the problem here. Any global default are not kept in individual Buefy component.

Most of the needed value can be managed using props. The problem in this specific example is `defaultIconComponent` that cannot be defined as a prop.

**Comment by service-paradis** [comment]
Maybe this [workaround](https://github.com/buefy/buefy/issues/1955#issuecomment-576144659) could work?

**Comment by jtommy** [comment]
@PeteyRev any news?

**Comment by ulf1** [comment]
@jtommy The docs are not working (https://buefy.org/documentation/icon/#fontawesome).
Basically what @kyoukhana  said (https://github.com/buefy/buefy/issues/1534#issuecomment-509796174)

I installed with yarn
```
yarn add @fortawesome/fontawesome-svg-core
yarn add @fortawesome/free-solid-svg-icons
yarn add @fortawesome/vue-fontawesome
```

and followed the Buefy docs.

## this fails
`<b-icon pack="fas" icon="user" size="is-large" type="is-success">  </b-icon>`

will generate

```
<span class="icon has-text-success is-large"><vue-fontawesome icon="fas,user" size="2x" class=""></vue-fontawesome></span>
```

## this works
`<font-awesome-icon icon="coffee"></font-awesome-icon>`

generates

```
<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="coffee" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" class="svg-inline--fa fa-coffee fa-w-20"><path fill="currentColor" d="M192 384h192c53 0 96-43 96-96h32c70.6 0 128-57.4 128-128S582.6 32 512 32H120c-13.3 0-24 10.7-24 24v232c0 53 43 96 96 96zM512 96c35.3 0 64 28.7 64 64s-28.7 64-64 64h-32V96h32zm47.7 384H48.3c-47.6 0-61-64-36-64h583.3c25 0 11.8 64-35.9 64z" class=""></path></svg>
```

**Comment by groundfloorwebb** [comment]
I hit this issue today and was completely mystified. The symptoms for me are as described above, I was passing in my usual buefy config which includes font awesome, but when I examined the output it was displaying material icon classes. I tried adding props to force the icon pack, and that helped but it only switched me over to webfont-style fontawesome classes. It still didn't use the font awesome icon component.

After reading the workaround suggested above, I discovered that I could resolve the issue by using ConfigProgrammatic. Here's an abbreviated version of the solution.

```
import {library} from '@fortawesome/fontawesome-svg-core';
import {faUserCircle} from '@fortawesome/free-solid-svg-icons';
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';
import Buefy, {ConfigProgrammatic} from 'buefy';
import Vue from 'vue';

library.add(
    faUserCircle,
);
Vue.component('font-awesome-icon', FontAwesomeIcon);

Vue.use(Buefy);
ConfigProgrammatic.setOptions({
    defaultIconPack: 'fas',
    defaultIconComponent: 'font-awesome-icon',
});
```

Thanks to @service-paradis for pointing me in the right direct and to @jtommy for the excellent library!

**Comment by 1shaked** [comment]
I can not get it to work with the CSS event when I include <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/cs0s/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/buefy@0.9.8/dist/buefy.min.css"> 
The icons are working but the css classes are not when I a, building as wc
