### ISSUE TITLE
Compilation error with version 0.7.9

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1536]
# Overview of the problem

**Buefy** version: 0.7.9
**Vuejs** version: 2.6.10

### Description

Problem to serve / build a project using Buefy 0.7.9:
```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

                transition: background $speed-slow $easing;
                                      ^
      Undefined variable: "$speed-slow".
      in node_modules\buefy\src\scss\components\_checkbox.scss (line 25, column 40)

 @ ./src/assets/scss/App.scss 4:14-231 14:3-18:5 15:22-239
 @ ./src/plugins/buefy.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.0.177:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

### Steps to reproduce

1. Update Buefy to 0.7.9
2. Serve a project
3. Watch what happens

### Expected behavior

No serve nor build errors

### Actual behavior

The error detailed above is showing in console

**Comment by service-paradis** [comment]
Maybe related to https://github.com/buefy/buefy/commit/e8601d6501f0100afeade1cee086ad877e373a68

**Comment by service-paradis** [comment]
Right now, the workaround is to import `utils/_all` right before importinf Buefy styles:
```
@import "~buefy/src/scss/utils/_all";
@import "~buefy/src/scss/buefy";
```

**Comment by jtommy** [comment]
@service-paradis you're right, my fault

**Comment by Yonaro** [comment]
Not working for me. Will revert back to 0.7.8!

**Comment by jtommy** [comment]
I released a new version anyway
