### ISSUE TITLE
Feature request: focus first focusable element in tab content after switching tabs

### ISSUE THREAD

**Issue by tychenjiajun** [buefy/buefy#1539]
### Overview of the problem

**Buefy** version: 0.7.5
**Vuejs** version: 2.6.10
**OS/Browser**: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

### Description

Add a prop to allow automatical focus first focusable element in tab content after switching tabs

**Comment by jtommy** [comment]
You might do it on change or input event, don't you ?
