### ISSUE TITLE
ref attribute input hardcoded

### ISSUE THREAD

**Issue by cdekok** [buefy/buefy#1540]
### Overview of the problem

Password confirm on vee-validate works with ref but the ref can't be set on the password input:
https://baianat.github.io/vee-validate/guide/rules.html#confirmed

**Buefy** version: [0.7.1]
**VeeValidate** version: [2.2.12]

### Description

It would be nice if the password confirm functionality would work with buefy. Currently it looks like the ref is already used and set to input: https://github.com/buefy/buefy/blob/dev/src/components/input/Input.vue#L5

### Steps to reproduce

```
<b-field          
          :label="$t('views.userJoin.password')"
          :type="{ 'is-danger': errors.has('password') }"
          :message="errors.first('password')"
        >
          <b-input
            name="password"
            type="password"            
            passwordReveal="true"
            v-model="password"
            v-validate="'required|min:5'"
            :ref="password"
            :class="{ 'is-danger': errors.has('password') }"
            :placeholder="$t('views.userJoin.password')"
          ></b-input>
        </b-field>
        <b-field
          :label="$t('views.userJoin.confirmPassword')"
          :type="{ 'is-danger': errors.has('password_confirm') }"
          :message="errors.first('password_confirm')"
        >
          <b-input
            name="password_confirm"
            type="password"
            v-validate="'required|confirmed:password'"
            :placeholder="$t('views.userJoin.password')"
            :class="{ 'is-danger': errors.has('password_confirm') }"
            data-vv-as="password"
          ></b-input>
        </b-field>
```

### Expected behavior

A working password confirm field

### Actual behavior

Always a non matching password.

**Comment by jtommy** [comment]
@cdekok Did you take a look at https://baianat.github.io/vee-validate/concepts/components.html#component-constructor-options ?
