### ISSUE TITLE
Steps v-model not updating binded property "activeStep" when navigation is used

### ISSUE THREAD

**Issue by luisjoserivera** [buefy/buefy#1541]
### Overview of the problem

**Buefy** version: [0.7.10]
**Vuejs** version: [2.6.10]

### Description

Steps v-model binded property "activeStep" not updating when changing steps using steps navigation.

### Steps to reproduce

```html
<script>
  export default {
    data() {
      return {
        activeStep: 0
      };
    }
  };
</script>

<template>
  <b-steps v-model="activeStep">
    <b-step-item>
      <p>Step 0</p>
    </b-step-item>
    <b-step-item>
      <p>Step 1</p>
    </b-step-item>
  </b-steps>
</template>
```

### Expected behavior

Navigation clicks should update v-model binded property.

### Actual behavior

Navigation clicks are not updating v-model binded property.

**Comment by service-paradis** [comment]
You are right, my mistake!
I just created a PR (#1543) to fix this behavior!

**Comment by luisjoserivera** [comment]
Release please!

**Comment by ekntrtmz** [comment]
This seems to be still an issue.
v-model not updating.

**Comment by service-paradis** [comment]
@ekntrtmz 
Which version of Buefy are you using.
This is working fine:
https://codepen.io/service-paradis/pen/LYYjvoR?&editable=true&editors=101

**Comment by ekntrtmz** [comment]
yea sorry did not update. (0.7.10)
