### ISSUE TITLE
Completed step item is not clickable on default

### ISSUE THREAD

**Issue by yxngl** [buefy/buefy#1542]
### Overview of the problem

**Buefy** version: [0.7.10]

### Description

The `clickable` API of step item says 

> Item can be used directly to navigate. If undefined, completed steps are clickable while the others are not.

But even if `clickable` is left unspecified, it will still be `false` not `undefined`. https://github.com/vuejs/vue/issues/8704

### Steps to reproduce

Any example in the doc page.

### Expected behavior

Completed step item is clickable.

### Actual behavior

Completed step item is disabled.

**Comment by service-paradis** [comment]
Right now, a previous step is not necessarily considered as completed. There is prop `completed` for the step item.
When I created this component for myself, i needed this behavior. I needed to make a difference between a "passed" step vs a completed step.
For a Buefy component, it is probably not the smartest behavior and we should probably consider any step preceding the active one to be completed (and clickable). I will try to work on a change soon.
