### ISSUE TITLE
Datepicker v-model with null value

### ISSUE THREAD

**Issue by sookoll** [buefy/buefy#1544]
### Overview of the problem

**Buefy** version: 0.7.10
**Vuejs** version: 2.6.8
**OS/Browser**: OSX, Chrome 76.0.3809.46

### Description

Datepicker bug: if v-model value is null, datepicker year is not selected, see picture.

<img width="340" alt="Screenshot 2019-07-10 at 22 08 02" src="https://user-images.githubusercontent.com/1793122/60997626-f0484700-a35f-11e9-976f-7f9efbc2ea45.png">

### Steps to reproduce

Set v-model to data that initial value is null.

### Expected behavior

Should show current month in datepicker.

### Actual behavior

Show unknown month in datepicker as year is not selected. If I select year, then it is working again.

**Comment by jtommy** [comment]
@sookoll Could you provide an example ?

**Comment by sookoll** [comment]
I have no clue how to do that with reasonable effort. Do you have a jsfiddle with vue, buefy that I can use as a base? I tried one but it produces completely unstyled datepicker

**Comment by service-paradis** [comment]
@sookoll 
You can click on the "codepen" tab on any example from the doc:
![image](https://user-images.githubusercontent.com/12817388/61000465-7ac28380-a32b-11e9-9b7f-c922285d14ec.png)

**Comment by jtommy** [comment]
@sookoll https://codepen.io/anon/pen/LKqBPV?&editable=true&editors=101, i'm not able to replicate your issue as you wrote in the issue

**Comment by sookoll** [comment]
Ah, thanks for the tip, @service-paradis.
@jtommy I was able to figure it out why it happens. It happens when current date (or month) is out of min/max dates. I still belive, that it shouldn't act like that it does.

https://codepen.io/anon/pen/wLNxrX?editors=1010

**Comment by jtommy** [comment]
@sookoll Ok, at the moment you migh use ` :focused-date="maxDate" or "minDate"` in order to show max or min month/year

**Comment by jtommy** [comment]
To be honest i don't know if it's really an issue.
What default date should the dapicker show ?

**Comment by sookoll** [comment]
True, it is quite edge case without good solution. Currently it displays current month and even current day is bordered but no year is selected. Perhaps it still should display also current year despite date is out of range. It seems logical for me. If user wants to different date, then focused-date can be used as You pointed out.

**Comment by jtommy** [comment]
It's true that you won't be able to but show current year is not really correct.

**Comment by sookoll** [comment]
Not correct? Showing current date and month is correct but year is not? Really can't follow You here. Current situation is not correct, whatever solution is better than this. One option is to show min date month if min date is in future and  max date month if max date is in past.

**Comment by jtommy** [comment]
It's not correct because at the moment the datepicker show only the years between min and max date.
Maybe your last solution is better
