### ISSUE TITLE
Timepicker: Initialize min as 0

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1551]
Hello, may i request for this feature to initialize the minutes? Because I encounter some scenarios that the user only wants to insert the minutes, then after clicking it, i just click outside to reflect on my time picker.  but when i'm clicking the time(hours) then clicking outside without clicking the minutes, it doesn't reflect on my timepicker unless i clicked the minutes. 

I don't think if the timepicker feature have that kind of action or that thing. 
I hope you can help me to solve that :)
Thank you! Good Day!

**Comment by jtommy** [comment]
At the first time you have to select hours and minutes but after that you might select only one of the two

**Comment by kenichii** [comment]
Actually I'm actually pointing about the user who's not really good in technology, cause' some users will only put hours, like 4:00 , Some users is not aware that you must need to click 00 so that it will reflect on the timepicker?

**Comment by kenichii** [comment]
Is there any way so that the 00 will show after I click hours?

**Comment by kenichii** [comment]
Cause' im trying to make it user friendly, like. When inserting time, i only want to inser is hours. then the 00 mins will automatically follow.

**Comment by jtommy** [comment]
@kenichii I might add `change-hour` and `change-minute` event, what do you think ?

**Comment by jtommy** [comment]
Maybe I could add a prop that allow to automatically set minutes and seconds after hour selection, what do you think ?

**Comment by kenichii** [comment]
Yup, I think that’s a good idea. So that I can initialize the minutes like, i want to set it as 00 min. So that when a user tries to insert a hr. Like “4” then I clicked outside of the timepicker, it will automatically shown as 4:00.

**Comment by kenichii** [comment]
It’s more user friendly actually :) , but actually im trying to do it using javascript/typescript. But it doesn't work at all hahaha.

**Comment by jtommy** [comment]
Added a new prop `default-minutes` (Number) and in your case you'll have to set `:default-minutes="0"`

**Comment by kenichii** [comment]
Thank you for the improvement :)

**Comment by kenichii** [comment]
Thanks for the improvement :) Godbless

**Comment by kenichii** [comment]
Did you already updated your master branch sir? :D

**Comment by jtommy** [comment]
No, please wait new release 0.8.0

**Comment by kenichii** [comment]
![image](https://user-images.githubusercontent.com/42717688/62685787-ea449500-b9f5-11e9-81fe-9b25fff70fea.png)

am i doing it correctly??

**Comment by kenichii** [comment]
can I initialize it 0?

**Comment by jtommy** [comment]
My fault!!

**Comment by kenichii** [comment]
Okay thanks :)
- I'm sorry for the late reply Godbless
