### ISSUE TITLE
recent version of vee-validate no longer works with data-vv-delay on buefy components

### ISSUE THREAD

**Issue by sebmor** [buefy/buefy#1553]
As per this example https://buefy.org/extensions/veevalidate

This example is running an older version of vee-validate ```https://cdn.jsdelivr.net/npm/vee-validate@2.1.0-beta.9/dist/vee-validate.min.js```
```data-vv-delay``` as described here https://baianat.github.io/vee-validate/examples/debounce.html works perfectly.

However if I update this package to the latest vee-validate 2.2.12, the ```data-vv-delay``` no longer works with Buefy.

This is an adapted pen from your example with the latest vee-validate version (2.2.12). Debounce does not work.
https://codepen.io/anon/pen/NZmOZb

This is the original pen. Debounce does work but its using an older version of vee-validate (2.1.0-beta.9)
https://codepen.io/anon/pen/NZmOZb

**Comment by sebmor** [comment]
The breaking version seems to be vee-validate 2.2.3 and onwards. Everything 2.2.2 and below seems to work.

**Comment by jtommy** [comment]
I'll investigate about it

**Comment by service-paradis** [comment]
I just made a few tests with 2.2.12 (https://codepen.io/service-paradis/pen/qBWRZpx).
I dont know if you have the same behavior than me. The debounce does not work the first time I use the input field (the error is displayed after 1 second even if I'm typing). But after that, if I clear the field and start again, the debounce works...

**Comment by sebmor** [comment]
vee-validate released a new major version 3.0.0 which deprecates the directive and also the lazy option for a component wrapper. So this might not be worth it investigating further.
