### ISSUE TITLE
How to use Local MaterialDesignIcon

### ISSUE THREAD

**Issue by bestony** [buefy/buefy#1556]
Hi,
How can i use local MaterialDesignIcon like [Vueify](https://vuetifyjs.com/en/framework/icons#installing-fonts)

**Comment by jtommy** [comment]
Did you see the docs?

**Comment by bestony** [comment]
yes, but https://buefy.org/documentation/icon/ here only how to use icon component, didn't have how to use it locally.

**Comment by jtommy** [comment]
https://buefy.org/documentation/start

**Comment by bestony** [comment]
Here tell me, i can use cdn. but i want to know, how can i use npm install it locally, and replace default cdn.

**Comment by jtommy** [comment]
In the docs we're using npm, take a look at https://github.com/buefy/buefy/blob/dev/docs/assets/scss/main.scss

**Comment by bestony** [comment]
If already use npm, why my page also request   

- https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css
- https://cdn.materialdesignicons.com/2.0.46/fonts/materialdesignicons-webfont.woff2?v=2.0.46

**Comment by jtommy** [comment]
I don't know without see the project :)
Maybe something in the index.html ?

**Comment by bestony** [comment]
yes, you are right. i found it at my index.html, but if i delete it, my icon couldn't work well.

**Comment by jtommy** [comment]
I don't know, you should check how to are you importing from npm

**Comment by bestony** [comment]
but here no doc for me to install material design icon and use it ?

**Comment by bestony** [comment]
for vuetify, i should do this.
1. install icon  by ` yarn add material-design-icons-iconfont -D`
2. use it in code.

```
import 'material-design-icons-iconfont/dist/material-design-icons.css' // Ensure you are using css-loader
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify, {
  iconfont: 'md'
})
```

**Comment by bestony** [comment]
I try to do this，but no effect.

```
import 'material-design-icons-iconfont/dist/material-design-icons.css' // Ensure you are using css-loader
import Vue from 'vue'
import App from './App.vue'
import store from './store'
import router from './router'
import Buefy from 'buefy'
import './assets/scss/app.scss'

Vue.use(Buefy)

Vue.config.productionTip = false

new Vue({
  store,
  router,
  render: h => h(App)
}).$mount('#app')

```

**Comment by jtommy** [comment]
Did you see it https://github.com/buefy/buefy/issues/1556#issuecomment-511188162?

**Comment by bestony** [comment]
yes, in code, it should auto input. but i remove link in index.html ,here no icon show.

**Comment by jtommy** [comment]
Please share your code otherwise it's no easy help you

**Comment by bestony** [comment]
Hi, @jtommy you can find my code at https://github.com/bestony/OpenSourceMenu

**Comment by jtommy** [comment]
@bestony I don't see any mdi icon package in the package.json :)

**Comment by bestony** [comment]
@jtommy yes, i test it on my local ,but no effect. and in document ,i only need install by run `npm install buefy` no docs tell me i should install which.

**Comment by bestony** [comment]
but here is no docs for people who want to use local icon.

**Comment by jtommy** [comment]
There is no docs because you are free to import as you want.
By the way I told you to see how we are using in the docs

**Comment by bestony** [comment]
OK, Let me make a summary.
First, you need install mdi  by `yarn add  @mdi/font`  or `npm install --save @mdi/font`

Then add these code into your `app.scss` or `_variables.scss`

```
// MDI
$mdi-font-path: "~@mdi/font/fonts";
@import "~@mdi/font/scss/materialdesignicons";
```

**Comment by jtommy** [comment]
It's correct
