### ISSUE TITLE
buefy b-autocomplete - easy way to validate it

### ISSUE THREAD

**Issue by rgnanase** [buefy/buefy#1560]
Whats the easy way to let the users to not type in values that are not shown in the dropdown of b-autocomplete?

**Comment by jtommy** [comment]
You might reset input value on blur if the user didn't select an option

**Comment by rgnanase** [comment]
thank you so much, that helped fix this issue!

**Comment by balendrang** [comment]
If i'm not selected dropdown items then if im select outside entered keyword reset, how we can do in b-autocomplete

**Comment by balendrang** [comment]
> You might reset input value on blur if the user didn't select an option

Can i get sample piece how to do ?
