### ISSUE TITLE
Buefy Datepicker typeable swaps month and day

### ISSUE THREAD

**Issue by jstr14** [buefy/buefy#1562]
Hi i don't know if it's because i have to add a custom parser but when using the buefy datepicker typeable everytime i set a new date month and date are swapped

**Comment by jtommy** [comment]
Could you provide an example on codepen or similar ?

**Comment by jstr14** [comment]
https://buefy.org/documentation/datepicker the documentation one has that issue, the Editable one when you change the date typing, month and day swap

**Comment by jtommy** [comment]
When you use editable you should define formatter and parser functions

**Comment by service-paradis** [comment]
This gives a good explanation why it does not work as intended:
https://stackoverflow.com/a/29989142/2774496

The default Buefy Formatter use `toLocaleDateString` to display the value inside the input. If you use this format to enter a new value, Buefy default parser will use `Date.parse` which is not locale dependent.

You will need to use custom formatter and/or parser depending on you need.

**Comment by jtommy** [comment]
@service-paradis, do you think there is a better way to parse a date without external dependencies ?

**Comment by service-paradis** [comment]
@jtommy 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Timestamp_string

> Note: Parsing of date strings with the Date constructor (and Date.parse(), which works the same way) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

Intl add a new standardize way of formatting dates: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat. Unfortunately, no intl parser. There is also a huge discussion about this:
https://github.com/tc39/ecma402/issues/342

It is really hard to have a consistent way to format/parse date using locale without external dependency. The best way I could think of to be consistent by default is to force a specific format. The downside is every locale as its own date format. So every user using Buefy in another locale would need to define a new parser/formatter.

**Comment by jtommy** [comment]
Ok, I'll think about it

**Comment by elC0mpa** [comment]
I am having the same issue but what I don't understand is that I am using a date-formatter
```javascript
<b-datepicker
        v-model="innerValue"
        :date-formatter="dateFormatter"
      >
</b-datepicker>

dateFormatter(dt) {
      // Formats a date to a string to display it in the input
      return dayjs(dt).format("DD/MM/YYYY");
    },
```
Normal behavior should be that each time a date is selected it should be formatted using the dateFormatter method. The problem is that in some cellphones it swaps month and day.

This is the way it should always look:

![2](https://user-images.githubusercontent.com/53531665/96666926-6e9ae380-132e-11eb-9c35-6b7504a6f91e.jpg)

However, in some cellphones it looks like this:

![1](https://user-images.githubusercontent.com/53531665/96667024-9c802800-132e-11eb-9b7f-05a153a7d6a0.jpg)

Any idea about why is this happening if I am using a date-formatter?

**Comment by jtommy** [comment]
Because it's the native input and I don't think Buefy can manage it.
@service-paradis am I missing something?

**Comment by service-paradis** [comment]
You're right. Without setting `mobile-native` to `false`, we have no control over the native input date format (https://stackoverflow.com/a/9519493/2774496).

**Comment by elC0mpa** [comment]
Thanks very much @service-paradis @jtommy I didn't know that
