### ISSUE TITLE
Buefy Table options sometimes contain value="[object Object]"

### ISSUE THREAD

**Issue by danmandel** [buefy/buefy#1563]
### Overview of the problem
The option elements for Buefy tables are sometimes rendered with the attribute `value="[object Object]"`. This does not seem to provide any useful information for the client and is likely to be unintentional behavior related to casting an object to a string.

**Buefy** version: Latest
**Vuejs** version: Latest
**OS/Browser**: MacOS Mojave, latest Google Chrome

### Steps to reproduce
I am not entirely sure how to reproduce this bug, however examples of it can be found within Buefy's Table documentation. I have also encountered it in other unrelated projects when using Buefy tables.

1. Visit https://buefy.org/documentation/table/
2. Open Chrome dev tools, go to the `Elements` tab.
3. Press `cmd + f` or your browser's search equivalent.
3. Search for [object Object].
4. Notice that there are 14 occurrences in the DOM tree.

### Expected behavior
The option's value should equal either the option text, some other relevant value, or not be visible at all. In my opinion it should just not be there because the option text is already being shown.

### Actual behavior

The option is being displayed on the DOM as `<option value="[object Object]">option text</option>`

**Comment by jtommy** [comment]
Table or option in select ? 
What's the issue? I'm sorry but I don't understand well

**Comment by yxngl** [comment]
Just talking about the select in TableMobileSort which directly binds column object as value. It is OK as b-select can use anything as value.

**Comment by jtommy** [comment]
Sure
