### ISSUE TITLE
DatePicker doesn't open programmatically on iOS

### ISSUE THREAD

**Issue by MelvinFrohike** [buefy/buefy#1565]
**Buefy version:** [0.7.10]
**Vuejs version:** [2.6.10]
**OS/Browser:** iOS Safari
### Description
Opening the Datepicker programmatically on iOS Safari doesn't work.
Nothing at all happens. This might related to #1515 or perhaps a new issue.
### Steps to reproduce
Using iOS Safari, go to the the date picker [documentation page](https://buefy.org/documentation/datepicker). Scroll to the "Programmatically opening" example and click the button. Nothing happens.
It works fine on macOS Safari, even when resizing the window to a "mobile" width.

**Comment by afwn90cj93201nixr2e1re** [comment]
There many bugs on mobile devices.

On android chrome too.

@jtommy just check every buefy doc's page. And then you gonna see a lot of bug's.

**Comment by jtommy** [comment]
For example?

**Comment by afwn90cj93201nixr2e1re** [comment]
Just open some page.
For example field's and other's and check.
On fields with position we getting overflow on left.
Or check some grouped fields with error's, then you gonna see some wrong positioning on messages 'bout error.
Just check every doc page. I checked from phone with latest chrome/chrome dev on GP store.

**Comment by jtommy** [comment]
You're right because at the moment we didn't improve docs on mobile. They aren't a Buefy or Bulma issues

**Comment by MelvinFrohike** [comment]
> You're right because at the moment we didn't improve docs on mobile. They aren't a Buefy or Bulma issues

Please note that my specific bug report is not just a docs issue. The codepen doesn't work either and the issue also occurs in my own code.

**Comment by jtommy** [comment]
@MelvinFrohike that message wasn't for you. I know that I have to improve programmatically way on mobile if possible

**Comment by afwn90cj93201nixr2e1re** [comment]
Maybe you should make some modal or dropdown (show/hide, like collapse) for mobile?
@jtommy
