### ISSUE TITLE
Improvement: Tooltip

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1566]
May I ask if how can I display a text that have HTML Tags?
I'm trying to give tooltip on my data's with the html tags, im trying to insert the v-html in the
<b-tooltip> but its not working. is there any way so that i can use the v-html?

**Comment by afwn90cj93201nixr2e1re** [comment]
Recompile buefy with your preferences.
As @jtommy said he working on tooltip rewrite.

**Comment by service-paradis** [comment]
Duplicate: #1122
