### ISSUE TITLE
Disabled attribute for b-autocomplete

### ISSUE THREAD

**Issue by fdrcslv** [buefy/buefy#1570]
Hi everyone, thank you for your amazing work. I noticed that b-autocomplete misses a prop to disable the underlying b-input.

### Description
A prop to pass to b-autocomplete that disables the nested b-input
```
<b-autocomplete
        v-model="field.value"
        :data="field.options"
        :disabled="field.is_disabled"
</b-autocomplete>
```

### Why Buefy need this feature
Would add a needed and useful functionality to the Autocomplete

Thanks!

**Comment by jtommy** [comment]
@fdrcslv There is already a `disabled` prop because you can attach all `b-input` props on autocomplete

**Comment by fdrcslv** [comment]
Thanks, I've missed it completely!
