### ISSUE TITLE
How to make buefy alert dialog to cancel by pressing esc without having the cancel button

### ISSUE THREAD

**Issue by rgnanase** [buefy/buefy#1571]
I have a situation where I am showing the users the buefy dialog alert box, I want it to close by pressing esc or any key on the keyboard rather than pressing OK. When I add canCancel=true, it shows the Cancel button along with OK button, but I don't need the Cancel button. Is there another way to handle this situation.

**Comment by service-paradis** [comment]
`canCancel` prop can be a `boolean` or an `array`. In your case, you want to set the value as an array like this:
`canCancel: ['escape', 'outside'],`
or
`canCancel: ['escape'],`

FYI, the default value for this is:
`canCancel: ['escape', 'button', 'outside'],`
