### ISSUE TITLE
Improve the pagination component flexibility

### ISSUE THREAD

**Issue by modularcoder** [buefy/buefy#1573]
### Description

The current pagination component doesn't have much customization options. I think we can improve the customization by adding slots support. So the component consumer can leverage of the dynamic pages range generation (which again might be customized e.g. user might want to display different number of pages nearby the active page), but be able to pass into the pagination the desired class buttons/components.

@jtommy  what do you think about this?

### Why Buefy need this feature

Will improve the pagination component reusability

**Comment by jtommy** [comment]
It's so simple component. What do you need to customize?

**Comment by modularcoder** [comment]
@jtommy here are the use cases that come to my mind

- someone might not want having pagination-previous / pagination-previous buttons. 
- use custom icons for the pagination items
- instead of showing only 2 page numbers around the active page, show more pages
- use custom classes for button components or other tags

I think slots can solve this use cases with keeping the backwards compatibility

**Comment by jtommy** [comment]
Ok, I think the major part of these use cases might be fulfilled using new props. 
By the way I'm waiting your PR 😃

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/issues/1575
