### ISSUE TITLE
label-position prop is incorrect using Number Input Component.

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1576]
### Overview of the problem

**Buefy** version: 0.7.10
**Vuejs** version: 2.6.10

### Description

`label-position` prop is not displayed correctly using Number Input Component.

### Steps to reproduce

1. Create a `b-field` component having `label-position="on-border"` or `label-position="inside"`
2. Create a `b-numberinput` component inside
3. Check the label position

Here is a codepen: https://codepen.io/anon/pen/OKJqrG?&editable=true&editors=101
![captured (1)](https://user-images.githubusercontent.com/12817388/61481788-fe512580-a966-11e9-9da9-fd6957c87f63.png)
![captured](https://user-images.githubusercontent.com/12817388/61536673-2e4e0680-aa03-11e9-98b2-711d14bb2686.png)

### Expected behavior

The label should be displayed above the input only and not over the controls.

### Actual behavior

The label is starting above the controls

**Comment by jtommy** [comment]
That style is not applicable to number input component.
I should avoid to apply it on number input

**Comment by service-paradis** [comment]
When we change the default label position, it is also applied to number input.
Personnaly, I just forced some left margin to keep the the same look as the other input.

**Comment by jtommy** [comment]
You are free to make a PR, I'll review it

**Comment by service-paradis** [comment]
Sure, I will try to look at this at the end of the week :)

**Comment by service-paradis** [comment]
I could probably use the `fieldType` method from the Field component to add a class when the rendered node is a `b-numberinput`.
This way, I could add CSS to push the label to the left. But I also need to know the size from the Number Input component.

**Comment by jtommy** [comment]
After you add margin left you might use em and rem units as I did in field component style

**Comment by service-paradis** [comment]
Sure, I will use em or rem.
But, I need to style the label who comes before the number input component (the one where we can define size). I need to know the size set to the child prop in order to adjust the label.
