### ISSUE TITLE
Sorting of numbers in the table doesn't always work

### ISSUE THREAD

**Issue by jcroucher** [buefy/buefy#1579]
I found an issue where sometimes numbers come through as a string which breaks the sorting.
Since JS is weakly typed, I think the value should be checked rather than relying on the type.

Table.vue Line 503.

`newA = (typeof newA === 'string') ? newA.toUpperCase() : newA` 
`newB = (typeof newB === 'string') ? newB.toUpperCase() : newB`

I think should be changed to

`newA = (isNaN(newA)) ? newA.toUpperCase() : newA`
`newB = (isNaN(newB)) ? newB.toUpperCase() : newB`

**Comment by service-paradis** [comment]
`isNan` will return `true` for everything that is not a number. `toUpperCase` is valid only on string.
The proposed solution could potentially be problematic.

If you want your numeric value to be sorted accordingly as numbers, you should make sure too keep the correct type in your data array.
