### ISSUE TITLE
Some community icons from materialdesignicons.com don't work

### ISSUE THREAD

**Issue by thebspin** [buefy/buefy#1580]
### Overview of the problem

**Buefy** version: [0.3.8] (nuxt)
**Vuejs** version: [2.8.1] (nuxt)
**OS/Browser**: All i've tested so far

### Description
Using some font's found on materialdesignicons.com don't work. I think i've narrowed it down to only community added fonts but i am not sure on this. It's not all community font's but for example: send-circle, target-account and tablet-dashboard don't work. 

### Steps to reproduce
This this pen: https://codepen.io/anon/pen/YmyVaK

**Comment by jtommy** [comment]
Buefy dosn't provide material design icons in the bundle.
For example docs is using https://www.npmjs.com/package/@mdi/font

**Comment by thebspin** [comment]
Ah i've spotted the "@mdi/font": "2.7.94", in the package.json of buefy so i assumed it was for the build, not the docs haha. So standard icons that work are provided then by bulma itself? And if i want to use more i could use a package like the one you just provided is that correct?

**Comment by jtommy** [comment]
You are free to use mdi icon pack as you want but it has to respect name convention and it has to contain the icon used in Buefy (for example arrow icon of table)
