### ISSUE TITLE
Docs: Context menu for b-menu-item

### ISSUE THREAD

**Issue by korpa** [buefy/buefy#1583]
I created a context menu for b-menu-item. Should we add this example to the menu documentation? Will be happy to send a merge request.

https://codepen.io/anon/pen/YmwVrg

![image](https://user-images.githubusercontent.com/2982785/61697405-80f72d80-ad37-11e9-8f50-0a3b28fba6c8.png)

**Comment by jtommy** [comment]
Sure!
