### ISSUE TITLE
Date Range in one datepicker

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1584]
Hello, may I ask if I can request for a datepicker than can handle 2 dates? To avoid also inserting invalid date range when using 2 date pickers. 
If its possible, then I'll use that date picker than can handle 2 dates at the same time. thanks Godbless

**Comment by jtommy** [comment]
Do you mean it https://github.com/buefy/buefy/pull/1017 ?

**Comment by afwn90cj93201nixr2e1re** [comment]
Yes.

**Comment by kenichii** [comment]
Yup :D

**Comment by kenichii** [comment]
Hello sir @jtommym , may i request another enhancement of the date range? can u add the (X) button at the right side of the date instead of putting it inside the calendar? so that i can easily see the clear button. I think this will be more user-friendly.

**Comment by kenichii** [comment]
I actually override the UI of the calendar button by removing the right border and add my custom button, but i think its a bad idea to do it.

**Comment by jtommy** [comment]
To clear all you can put a button in the footer slot for example

**Comment by kenichii** [comment]
hmmm. okay, i'll override it anyway hehe. I'm just actually asking if it is possible to add on ur datepicker :D hehe. thanks sir Godbless

**Comment by afwn90cj93201nixr2e1re** [comment]
@kenichii you can create copy of component and just compile it for yourselft, and import thru es6 import's for example, xD.

**Comment by kenichii** [comment]
@afwn90cj93201nixr2e1re  actually i just created my own button and attach it on my date range hehe, so I can easily override it.

**Comment by kenichii** [comment]
can i ask if it has a properties like this?
![image](https://user-images.githubusercontent.com/42717688/62683769-d7c85c80-b9f1-11e9-8277-ab93939f0dd1.png)

instead of displaying like 08/08/2019 so i can choose what to display.

**Comment by kenichii** [comment]
so I can choose what to display like (August 08, 2019) or (08/08/2019) ??

**Comment by service-paradis** [comment]
To add a button at the right of the datepicker, you can wrap your datepicker and a control element into a field. Something like this:
```
<div id="app" class="container">
    
    <section>
        <b-field>
            <b-datepicker
                placeholder="Click to select..."
                icon="calendar-today">
            </b-datepicker>
            <p class="control">
                <b-button class="button is-danger" icon-right="delete"></b-button>
            </p>
        </b-field>

    </section>

</div>
```

For the format, there is a prop named `date-formatter` where you can use your own function to format the date the way you want.

**Comment by kenichii** [comment]
I tried that actually, but when I add a label on b-field, instead the label is on its top. The label is displaying horizontally

**Comment by service-paradis** [comment]
The hack for this is to wrap your bfield into another bfield:
```
<div id="app" class="container">
    
    <section>
        <b-field label="From">
          <b-field>
              <b-datepicker
                  placeholder="Click to select..."
                  icon="calendar-today">
              </b-datepicker>
              <p class="control">
                  <b-button class="button is-danger" icon-right="delete"></b-button>
              </p>
          </b-field>
        </b-field>

    </section>

</div>
```

See this issue to better understand:
https://github.com/buefy/buefy/issues/1420

**Comment by kenichii** [comment]
Okay, I'll check it. thanks :D

**Comment by kenichii** [comment]
> can i ask if it has a properties like this?
> ![image](https://user-images.githubusercontent.com/42717688/62683769-d7c85c80-b9f1-11e9-8277-ab93939f0dd1.png)
> 
> instead of displaying like 08/08/2019 so i can choose what to display.

is there any update?

**Comment by jtommy** [comment]
You can format the date as you want using date-formatter prop
