### ISSUE TITLE
Icon Size is 0 x 0

### ISSUE THREAD

**Issue by robertmarney** [buefy/buefy#1585]
### Overview of the problem

**Buefy** version: 0.7.10
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10:  Brave and Firefox

### Description

Icon is 0 x 0 when instantiated by b-icon or :icon, if class is manually called the icon is visible.

### Steps to reproduce

`<b-steps>
       <b-step-item label="Account" icon="account-key"></b-step-item>
       <b-step-item label="Profile" icon="account"></b-step-item>
       <b-step-item label="Social" icon="account-plus"></b-step-item>
</b-steps>`

### Expected behavior

Icon will be visible

### Actual behavior

Icon is 0 x 0 when instantiated by b-icon or :icon, if class is manually called the icon is visible

![image](https://user-images.githubusercontent.com/48888686/61741903-1e119080-ad4f-11e9-9bfe-b81efa4f412c.png)

**Comment by oz-** [comment]
I have the same problem with Material Design icons.
Something strange: if I launch a b-notification object, the icon displays correctly...
Any clue on this one?
Thank you!
