### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1589]
Where we should write something about improvment's for new version? (which is gonna be with breakable changes)

**Comment by jtommy** [comment]
Take a look at changelog ;)

**Comment by afwn90cj93201nixr2e1re** [comment]
No, im talking about ideas. Where we should write it?

**Comment by jtommy** [comment]
There is roadmap issue, don't you ?

**Comment by afwn90cj93201nixr2e1re** [comment]
ok, get you.
