### ISSUE TITLE
VeeValidate: ignore disabled field not working with b-input

### ISSUE THREAD

**Issue by MetaBureau** [buefy/buefy#1592]
### Overview of the problem

VeeValidate and b-input not working with disabled fields.

**Buefy** version: [0.3.10]
**Nuxt** version: [2.4.0]
**OS/Browser**: Mac/Chrome

### Description

Form fields marked-up with <b-input ...> are validated by VeeValidate when disabled. (Bad)
Form fields marked-up with <input ...> are not validated by VeeValidate when disabled. (Good)

### Steps to reproduce

      <b-field
        label="Client's Business, Organisation or Event Name"
        :type="{ 'is-danger': errors.has('busname') }"
        :message="errors.first('busname')"
      >
        <b-input
          ref="busname"
          v-model="busname"
          name="busname"
          disabled
          icon="label"
        />
      </b-field>

      <b-field
        label="Client's Business, Organisation or Event Name"
        :type="{ 'is-danger': errors.has('busname') }"
        :message="errors.first('busname')"
      >
        <input
          ref="busname"
          v-model="busname"
          name="busname"
          :disabled="jobtype == 'Residential'"
          icon="label"
        />
      </b-field>

  methods: {
    validateBeforeSubmit() {
      this.$validator.validateAll().then(result => {
        if (result) {
          this.$toast.open({
            message: 'Form is valid!',
            type: 'is-success',
            position: 'is-bottom'
          })
          return
        }
        this.$toast.open({
          message: 'Form is not valid! Please check the fields.',
          type: 'is-danger',
          position: 'is-bottom'
        })
      })
    },

### Expected behavior

Field to not be validated.

### Actual behavior

Field was validated.

**Comment by afwn90cj93201nixr2e1re** [comment]
maybe it's nuxt bug?

**Comment by kenichii** [comment]
I can suggest you to use v-validate, so you can use like this
 <b-field label="Start Time"
                                     :type="{'is-danger': errors.has('sunStart')}"
                                     :message="{'Please fill this date to proceed' : errors.firstByRule('sunStart', 'required')}"
                                     expanded>
                                <b-timepicker
                                        rounded
                                        placeholder="Click to select..."
                                        icon="clock"
                                        :hour-format="format"
                                        v-validate="'required'"
                                        name="sunStart"
                                        v-model="editEmployeeSchedule.sundayStartTime"
                                        :disabled="(noWorkSunday || isFlexible === true)"
                                >
                                </b-timepicker>
                            </b-field>

**Comment by felaugmar** [comment]
I found the error, it's actually a `VeeValidate` behavior.
The fact is that VeeValidate checks the `$el` directly for the `disabled` attribute.
But the `$el` of `<b-input />` points to his first element that is a div, not the input.
