### ISSUE TITLE
v-model for b-tag-input is modified inside component

### ISSUE THREAD

**Issue by lunfel** [buefy/buefy#1596]
### Overview of the problem
For TagInput, v-model is passed by reference and has sides effets.

**Buefy** version: [0.7.7]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome 75/Ubuntu 18.04

### Description
For the TagInput component, v-model is always an Array. When the v-model is passed to the TagInput component, the `value` prop is copied into the `tags` data in the component. Though the prop is not [cloned by referenced](https://github.com/buefy/buefy/blob/dev/src/components/taginput/Taginput.vue#L148) since an Array is an object in javascript. This lead to child component modifying the parent data.

This is more of a problem when using v-model from vuex. The passed vuex property is modified inside the TagInput component even if we use :value="myTags". We get the warning from vuex that we should not modify the state outside of the mutation handlers.

### Steps to reproduce

1. Create a vue.js Buefy project
2. In a component, use the TagInput component and use the :value @input notation instead of the v-model and omit the @input (<b-tag-input :value="myTags" />)
3. Go in your browser and use the TagInput to add a few tags
4. In Vue DevTools, see that myTags have been modified, but should not have been modified

### Expected behavior

Using only :value, I would expect my data variable not to have changed. The variable should only change when using @input.

`myTags` should not be modified inside TagInput

### Actual behavior

`myTags` were modified inside the child component TagInput.

**Comment by dominikg** [comment]
This is not fixed completely. 
the value watcher sets tags to model instead of a clone
https://github.com/buefy/buefy/blob/59ca07b14fe305ec447c3118637762502ddd7994/src/components/taginput/Taginput.vue#L237

any subsequent calls to addTag modify that model directly
https://github.com/buefy/buefy/blob/59ca07b14fe305ec447c3118637762502ddd7994/src/components/taginput/Taginput.vue#L264
