### ISSUE TITLE
Numberinput steps not accepting dots

### ISSUE THREAD

**Issue by bpuig** [buefy/buefy#1599]
### Overview of the problem

**Buefy** version: [0.7.10]
**Vuejs** version: [2.6.10] , but I'd say any
**OS/Browser**: Windows 10, Mac Mojave, Lubuntu / Chrome

### Description

Numberinput steps do not accept writing `.` as decimal separator. Pressing `.` removes current input and returns to `0`. It only behaves correctly with `,`
I've tried in Firefox and Safari seem OK, Chrome no.
In Lubuntu's Chrome, it directly does not let you press `,`

### Steps to reproduce

1. Create numberinput with steps (step = 0.1, 0.01… all behave the same)
2. Introduce any decimal number with dot separation, like `10.2`

### Expected behavior

Write `10.2` in the input and ending up being `10.2`

### Actual behavior

Clears the input to 0 at the moment `.` is pressed.
Write `10.2` and the input ends up being `2`

**Comment by afwn90cj93201nixr2e1re** [comment]
Same with minus character (-) instantly change to min value if there min prop setted.

Seem's like we need debounce right here.

**Comment by yxngl** [comment]
What is your locale?

Currently, b-Numberinput is just a wrapper of native number input without custom parsing. Take the doc website as example, it sets `lang="en"` and only works with dot as the decimal mark for me. Changing it manually to `lang="fr-FR"` makes comma work on Firefox and used for display. But Chrome always parses it as a floating number.

More on [this](https://www.ctrl.blog/entry/html5-input-number-localization.html)

**Comment by bpuig** [comment]
> What is your locale?

Spanish, but regular html <input type="number"> give me no issues :/
