### ISSUE TITLE
Removed needless <span> from BTableColumn

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#1601]
Is there any reason why the [unnamed slot](https://github.com/buefy/buefy/blob/201692497c290445bb993d6630eb0ea5de81e135/src/components/table/TableColumn.vue#L6) in BTableColumn is wrapped inside a span? It seems to serve no specific purpose from what I can tell.

I have a pretty big table (~16 columns, ~50 rows) that I need to display and removing the span would shave ~800 DOM elements off of the page (Google/Lighthouse [suggests](https://developers.google.com/web/tools/lighthouse/audits/dom-size) having DOM tree with 1500 nodes or fewer for optimal performance).

**Comment by afwn90cj93201nixr2e1re** [comment]
Here a lot of trash in table component, we should rework it in new version.
