### ISSUE TITLE
Pagination event onNextpage onPrevPage

### ISSUE THREAD

**Issue by nongtiny** [buefy/buefy#1602]
Thank you for the wonderful css library for vuejs with Buefy!. I have tried to use the pagination, and I saw that it doesn't have an event for checking next page or previous page. I know that. I can watch the bind data on current.sync prop or use on @chage event, but the problem is when I click next button it triggers event and return increasing page, but the back button also triggers the same event. If I want to specify this is next and back, so I have to check by the data whether it is increasing or decreasing. I think you should emit "next" or "prev" instead of a number of the page because we already know the page number on current prop. I just want to modify it more, so can you please add this feature. It will be beneficial for all users for sure.

Regards,
Nongtiny

**Comment by nongtiny** [comment]
I will try to create the PR for this feature.

**Comment by afwn90cj93201nixr2e1re** [comment]
This is good idea too.
Now you can store old value and make some check's.

**Comment by wanxe** [comment]
By the moment you can check if the parameter of the **@change** event is greater or not than the current page. 

Sometimes it's more flexible and lightweight for the library to use your own logic, instead of covering all cases

**Comment by jtommy** [comment]
I agree with @wanxe at the moment

**Comment by nongtiny** [comment]
Got it. Thank you.
