### ISSUE TITLE
自动完成 是否有 不受父级菜单影响的功能

### ISSUE THREAD

**Issue by viaisi** [buefy/buefy#1610]
### 自动完成 是否有 不受父级菜单影响的功能
####Function Autocomplete also can not affected by the parent menu ? it's like iview's transfer=true

**Comment by yxngl** [comment]
No. There is not an overlay component for that function yet.

**Comment by viaisi** [comment]
well ，I know now ,thanks for your email,my english bad ,please put up with


| |
陈建强
|
|
viaisi@163.com
|
签名由网易邮箱大师定制
在2019年7月30日 22:36，Yuxing Liao<notifications@github.com> 写道：

No. There is not an overlay component for that function yet.
