### ISSUE TITLE
Switch works strange with vuex

### ISSUE THREAD

**Issue by potykion** [buefy/buefy#1612]
### Overview of the problem

**Buefy** version: 0.7.10
**Vuejs** version: 2.6.10
**OS/Browser**: Windows/Chrome

### Description

I have vuex store with items. Items have active flag which bound to b-switch v-model. 
Also I have b-switch which filters items with active = true.

When I toggle filter-switch and change state of first switch, next switch state becomes inactive (visually):

![issue](https://i.imgur.com/orndEmR.gif)

How to deal with it? Is this is a bug or misuse of b-switch?

### Steps to reproduce

1. Create Vue and Vuex instances:

```js
import Vue from 'vue'
import Vuex from 'vuex'
import App from './App.vue'

import Buefy from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Buefy);
Vue.use(Vuex);

const store = new Vuex.Store({
  state: {
    items: [
      {"active": true, "id": 1},
      {"active": false, "id": 2},
      {"active": true, "id": 3},
    ]
  },
  mutations: {
    setActive(state, activeChange){
      const itemToChange = state.items.find(i => i.id === activeChange.id);
      itemToChange.active = activeChange.active;

      state.items = [
        ...state.items.filter(i => i.id !== activeChange.id),
        itemToChange
      ]
    }
  },
  actions: {

  }
});

new Vue({
  store,
  render: h => h(App)
}).$mount('#app');

```

2. Create switches and bind them to store data and mutation:

```vue
<template>
  <div class="app">
    <div>
      <b-switch v-model="showOnlyActive">Show only active</b-switch>
    </div>

    <div>
      <b-switch v-for="item in itemsToShow" v-model="item.active" @change="setActive(item.id, item.active)">
        {{ item.id }}
      </b-switch>
    </div>

  </div>
</template>

<script>
  import {mapMutations, mapState} from "vuex";

export default {
  name: 'app',
  data: () => ({
    showOnlyActive: false
  }),
  computed: {
    ...mapState(["items"]),
    itemsToShow() {
      return this.showOnlyActive ? this.items.filter(i => i.active) : this.items;
    }
  },
  methods: {
    ...mapMutations(["setActive"])
  }
}
</script>

<style>
  .app {
    margin: 20px;
  }
</style>
```

3. Click on "Show only active" switch

4. Click on switch 1

### Expected behavior

Switch 3 is still active

### Actual behavior

Switch 3 looks like inactive

**Comment by afwn90cj93201nixr2e1re** [comment]
Read something about vue :key binding on custom component's.
```js
<template>
  <div class="app">
    <div>
      <b-switch v-model="showOnlyActive">Show only active</b-switch>
    </div>

    <div>
      <b-switch v-for="item in itemsToShow" v-model="item.active" :key="item.id" @change="setActive(item.id, item.active)">
        {{ item.id }}
      </b-switch>
    </div>

  </div>
</template>

<script>
  import {mapMutations, mapState} from "vuex";

export default {
  name: 'app',
  data: () => ({
    showOnlyActive: false
  }),
  computed: {
    ...mapState(["items"]),
    itemsToShow() {
      return this.showOnlyActive ? this.items.filter(i => i.active) : this.items;
    }
  },
  methods: {
    ...mapMutations(["setActive"])
  }
}
</script>

<style>
  .app {
    margin: 20px;
  }
</style>
```
```js
import Vue from 'vue'
import Vuex from 'vuex'
import App from './App.vue'

import Buefy from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Buefy);
Vue.use(Vuex);

const store = new Vuex.Store({
  state: {
    items: [
      {active: true, id: 1},
      {active: false, id: 2},
      {active: true, id: 3},
    ]
  },
  mutations: {
    setActive(state, activeChange){
      const itemToChange = state.items.find(i => i.id === activeChange.id);
      itemToChange.active = activeChange.active;

      state.items = [
        ...state.items.filter(i => i.id !== activeChange.id),
        itemToChange
      ]
    }
  },
  actions: {

  }
});

new Vue({
  store,
  render: h => h(App)
}).$mount('#app');
```

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy not related to buefy.

**Comment by potykion** [comment]
@afwn90cj93201nixr2e1re Thanks!

If I use b-switch in table row like that:
```vue
      <b-table-column field="active" label="Active" >
        <b-switch v-model="props.row.active" size="is-small" @input="onActiveClick(props.row.id, props.row.active)"></b-switch>
      </b-table-column>
```

I should pass key prop here too? The same true for every element inside table row?

**Comment by afwn90cj93201nixr2e1re** [comment]
Здесь не нужно.
Только там где консоль советует.
Если проект создан через vue cli 3 то тебе eslint встроенный будет писать о том где у тебя ошибка.
Обычно key нужны лишь там где итерации, ты проверь просто когда пишешь, если есть баг - добавляй, нету - не нужно.

Я им пользуюсь лишь в итерациях, там где действительно требуется из-за логики работы компилятора и интерпретатора шаблонов.

https://ru.vuejs.org/v2/api/#key
![изображение](https://user-images.githubusercontent.com/9306996/62161226-b4811b80-b326-11e9-9a04-bf5cdd882954.png)


https://ru.vuejs.org/v2/guide/list.html#%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-%D0%B8-v-for
![изображение](https://user-images.githubusercontent.com/9306996/62160974-44729580-b326-11e9-8921-42c7395aea00.png)


https://ru.vuejs.org/v2/guide/conditional.html#%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%BC-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%BF%D1%80%D0%B8-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D0%B8-key
![изображение](https://user-images.githubusercontent.com/9306996/62161115-83085000-b326-11e9-876a-ecfdd8bf02a3.png)

https://ru.vuejs.org/v2/api


https://pastebin.com/v8vzv67d пример таблицы, подумай, нужна ли тебе действительно в этой таблице столбец, а не полноценный компонент(который возможно в будущем понадобится) отображающий всю информацию о записи таблицы.
