### ISSUE TITLE
Make more clear how Bulma and Buefy CSS classes relate to each other.

### ISSUE THREAD

**Issue by pawelurbanski** [buefy/buefy#1613]
### Description

Buefy customization section describes how to import Bulma and Buefy styles. There is not much information how Buefy's styles and classes overwrite core styles and classes of Bulma.
A reminder about being able to import SASS modules for the components being used wuld be also useful.
 
### Why Buefy need this feature

When someone desides to customize Bulma's core styles, it also happens that it involves a custom CSS build to reduce the final file size. Very often to inline the most crytical styles in the head of the document.
The information if Buefy's styles and classes are the absolute requirement, anf if yes which ones, would be very useful.

**Comment by jtommy** [comment]
You're right!
Next release I improved tree shaking (only js) so in the future I'll work on scss part.
I hope and I would like publish a Buefy tree dependencies about Bulma

**Comment by pawelurbanski** [comment]
How can I help? Maybe there is something you would like to get ready before you start? Looking through declarations/imports – maybe collect some ideas for naming/documentation?

**Comment by jtommy** [comment]
As first point, it's important to find all Bulma elements, components, helpers etc that Buefy are using at the moment
