### ISSUE TITLE
b-upload single file upload returns error

### ISSUE THREAD

**Issue by DevRuto** [buefy/buefy#1616]
### Overview of the problem

**Buefy** version: 0.8.0
**Vuejs** version: 2.5.22
**Browser/OS**: Windows 10, Tested on Firefox and Chrome

### Description

Using <b-upload> without the "multiple" property returns an error "this.newValue.some is not a function"
Example at [Codesandbox](https://codesandbox.io/embed/vue-template-08171)
In console, you can see the error.

With the multiple property, this does not occur.

### Steps to reproduce

1. Select a file or drag and drop (with drag-drop property) into the Upload component.

### Expected behavior

Select a (single) file

### Actual behavior

Returns an error

**Comment by DevRuto** [comment]
In a NuxtJS app, the page becomes an error 
![image](https://user-images.githubusercontent.com/20764435/62318475-ee0e6f80-b469-11e9-8f8f-abd27ae96b7e.png)

**Comment by chrislaive** [comment]
I placed a filter to see the content-type of the file and it recognizes the file; however, when choosing a correct content-type the error happen.

![image](https://user-images.githubusercontent.com/33591237/62320310-7e968100-b465-11e9-8aa0-43ac68f902ae.png)
