### ISSUE TITLE
[Idea / Discussion]: Should we use Sass for some arrow icons

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1617]
### Description

There is an arrow mixin (using borders) in Bulma that creates a kind of chevron. This is use, for example, in the select component.

IMaybe we could use this kind of mixin for next/previous in some component if no icon props is given. This way, those buttons will display an icon even if there are no icon pack defined. This would be some progress to decouple Buefy from icon pack.

It would not necessarily be a breaking change since the look and feel would be the same.

### Why Buefy need this feature

Will prevent mistakes where user does not include icon pack or do not include the needed icons. Will help decoupling Buefy from icon pack.

**Comment by modularcoder** [comment]
I guess in this case it should still be configurable, because forcing to have a mandatory arrow icon may be bit non-flexible.

**Comment by service-paradis** [comment]
@modularcoder 
Sure, I think Buefy should continue accepting icon props. But should not use external icons as default icons. This adds non-necessary dependencies in order to use Buefy and leads to many questions/issues.

**Comment by Tofandel** [comment]
We could add `false` as an icon prop to not display any icon for some special cases (eg: css background image)

**Comment by wesdevpro** [comment]
Closing as stale.
