### ISSUE TITLE
Navbar: Use of document hinders nuxt.js support

### ISSUE THREAD

**Issue by brocgailit** [buefy/buefy#1620]
### Overview of the problem

**Buefy** version: [0.8.0]
**Vuejs** version: [2.6.10]
**OS/Browser**: Any

### Description

Use of `document` in new navbar component requires use of `<no-ssr>` in nuxt projects (or throws an error).

### Steps to reproduce

1. Add navbar component to nuxt.js project

### Expected behavior

`setBodyClass` and `removeBodyClass` should avoid use of `document` or check for existance of `document` object before using it willy nilly.

Navbar needs to work server-side on nuxt.js projects for major accessibility and performance reasons.

### Actual behavior

Error or `<no-ssr>` needed to use navbar component in nuxt.js project.

**Comment by jtommy** [comment]
You're right!
