### ISSUE TITLE
Slider not working properly inside Tabs

### ISSUE THREAD

**Issue by ahsath** [buefy/buefy#1624]
### Overview of the problem

**Buefy** version: [0.8.1]
**Vuejs** version: [2.6.10]
**OS/Browser**: macOS High Sierra/Chrome 76

### Description

Everytime when refreshing the page using `b-slider` inside `b-tabs > b-tab-item` the slider will not work properly but if you resize the screen it will work as expected, the same is true if you don't have the devtools open before refreshing the page

### Steps to reproduce

1. Install Buefy
2. Add `b-tabs > b-tab-item > b-slider` to your component
3. Set `b-slider :min` and `:max` to any values 
4. Start the dev server
5. Use the dragger

### Expected behavior

It should drag between `min` and `max` one by one

### Actual behavior

It drag between `min` and `max` min by max

![buefy-b-slider-issue](https://user-images.githubusercontent.com/37009121/62334158-1ad37e80-b48c-11e9-9cb7-f76826acff5e.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/slider/Slider.vue#L205

i think problem is near getBoundingClientRect

also idk why this is implemented here, it must be parent width, not client.
https://github.com/buefy/buefy/blob/dev/src/components/slider/Slider.vue#L227

try to set it to parent.width or smthng like that.


@jtommy buefy have unminimized version on cdn?
Coz now im using 0.7x maybe and don't wanna merge it without checking what was added, but still need to debug something, xD.
