### ISSUE TITLE
Buefy global variable is buefy (lowercase) in latest

### ISSUE THREAD

**Issue by Youdaman** [buefy/buefy#1625]
### Overview of the problem

**Buefy** version: 0.8.1

### Description

Global variable "Buefy" has been changed to "buefy"

Instructions on https://buefy.org/documentation/constructor-options/ no longer work:

```
Vue.use(Buefy, {
    defaultIconPack: 'fas',
    defaultContainerElement: '#content',
    // ...
})
```

Because "Buefy" is undefined -- as the variable is defined as "buefy" instead.

See https://unpkg.com/buefy@0.8.1/dist/buefy.js line 5:
```
  (global = global || self, factory(global.buefy = {}, global.Vue));
```

### Steps to reproduce

1. Include the latest Buefy via a script tag, e.g.
```
<script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>
```

2. try the constructor options shown above.

### Expected behavior

Buefy works.

### Actual behavior

Buefy doesn't work.

Browser complains about "Buefy" being undefined.

**Comment by jtommy** [comment]
You're right but using CDN, it should add Buefy automatically and you can add config using this.$buefy.config.setOptions(..) (for example in the first mount)
