### ISSUE TITLE
Buefy not working in production mode of Nuxt after version 0.8.0

### ISSUE THREAD

**Issue by dasmikko** [buefy/buefy#1626]
### Overview of the problem

**Buefy** version: [0.8.1]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome

### Description
When running Nuxt.js in production, buefy is suddenly not included-

### Steps to reproduce

1. use Nuxt.js
2. use Buefy 0.8.0 or 0.8.1
3. build nuxt
4. start nuxt
Css is missing

### Expected behavior
That buefy css is included

### Actual behavior
Buefy css is missing

**Comment by DonNicoJs** [comment]
@dasmikko I just tried to reproduce and It works 100% for me.
How are you importing the css? can you provide a minimal reproduction case on codesandbox?

**Comment by dasmikko** [comment]
I forgot to mention that i'm using `nuxt-buefy` module to use buefy

**Comment by dasmikko** [comment]
Other people are having similar issues: https://github.com/buefy/nuxt-buefy/issues/45

**Comment by dasmikko** [comment]
From other issue:

> import pkg from './package'
> 
> export default {
>   mode: 'universal',
> 
>   /*
>   ** Headers of the page
>   */
>   head: {
>     title: pkg.name,
>     meta: [
>       { charset: 'utf-8' },
>       { name: 'viewport', content: 'width=device-width, initial-scale=1' },
>       { hid: 'description', name: 'description', content: pkg.description }
>     ],
>     link: [
>       { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
>     ]
>   },
> 
>   /*
>   ** Customize the progress-bar color
>   */
>   loading: { color: '#fff' },
> 
>   /*
>   ** Global CSS
>   */
>   css: [
>   ],
> 
>   /*
>   ** Plugins to load before mounting the App
>   */
>   plugins: [
>   ],
> 
>   /*
>   ** Nuxt.js modules
>   */
>   modules: [
>     // Doc: https://axios.nuxtjs.org/usage
>     '@nuxtjs/axios',
>     // Doc: https://buefy.github.io/#/documentation
>     'nuxt-buefy',
>     [
>       "nuxt-validate",
>       {
>         lang: "da"
>       }
>     ],
>     
>   ],
>   /*
>   ** Axios module configuration
>   */
>   axios: {
>     // See https://github.com/nuxt-community/axios-module#options
>   },
> 
>   /*
>   ** Build configuration
>   */
>   build: {
>     /*
>     ** You can extend webpack config here
>     */
>     extend(config, ctx) {
>     }
>   }
> }

**Comment by modularcoder** [comment]
I've made a PR. The issue happens because of tree-shaking during the production build.
