### ISSUE TITLE
Datepicker range - date formatting not working

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#1634]
With datepicker we can format the dates using the
```
:date-formatter="(date) => date.toLocaleDateString('en-UK',{ year: 'numeric', month: 'long', day: 'numeric' })"
```

but this doesn't work when we make the datepicker a range one.

I've tried figuring it out like this:

```
:date-formatter="formatDateRange"
...
methods: {
  formatDateRange(date) {
    console.log(date)
  }
}
```
I was hoping to get an array of dates here, but I'm getting undefined.

Am I missing something or is this not possible at this moment.

**Comment by jtommy** [comment]
Are you using range prop?

**Comment by dmcbrn** [comment]
Thanks, greatly appreciated!

**Comment by dmcbrn** [comment]
Just tried it out and it's not working with ranged datepicker if the returned date is formatted: https://codepen.io/anon/pen/bXaVGG?editors=1011

If you try it without `ranged` turned on you will see the result. I'm hoping I'm something simple here..

**Comment by jtommy** [comment]
Using range the formatter input is an array of dates

**Comment by dmcbrn** [comment]
Yes, sorry. Figured it out as you replied. The fiddle above is now updated with a working example.
