### ISSUE TITLE
Fullscreen Modal Scroll

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#1635]
I used the fullscreen option for b-modal and its works great on mobile except if the content is longer than the display. No scroll bar appears and there is no way to see the content that flowed off the bottom of the screen including the footer section.

I used a modal card with a header and footer. 

For fullscreen, the header and footer should be fixed at the top and bottom of the screen. The content should scroll between the headers and footers if necessary. Actually this should be true for all modals.

**Comment by kerbo** [comment]
Still a big issue for me. Any workarounds?

**Comment by jtommy** [comment]
I'm not able to replicate your issue, take a look at https://codepen.io/jtommy/pen/OJJzxym?&editable=true&editors=101

**Comment by kerbo** [comment]
Thanks for looking into this issue. Yes, your CodePen works correctly. My modal is much more complex (more components and columns) so I thought that was contributing to the issue but changing your CodePen to duplicate my Modal works correctly.

Examining the css properties in Chrome in my app shows the underlying problem.

.modal-card-body {
overflow: visible !important
}

If I change "visible" to "auto" in the inspector, the modal will work correctly.

I have no idea where "overflow: visible" is coming from. The page has a navbar, tabs, and lots of components. 

Is there a way to trace this problem?

**Comment by jtommy** [comment]
You should be able to see about using Chrome dev console or similar

**Comment by kerbo** [comment]
FYI, this problem is related to #292 . 292 is the issue where a datepicker calendar is clipped by the modal. To fix, I added the suggested css and while working it changed all modals in my project.

To work around this issue and only fix the modal that has a datepicker, I used  the style attribute to change the overflow:

modal-card and modal-card-body divs: style="overflow: visible !important;"
