### ISSUE TITLE
Grouped Array Checkboxes

### ISSUE THREAD

**Issue by kyoukhana** [buefy/buefy#1636]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OSX 10.14.4 **:
Firefox 68.0.1 (64-bit)
Chrome: Version 75.0.3770.142

### Description
Grouped (Array)  Checkboxes

If the checkbox value has the same value then when selected all checkboxes with the same value will be selected

### Steps to reproduce

Go here
https://codepen.io/kyoukhana/pen/PMQbVy?editors=1010

Check on Silver

### Expected behavior
If I check silver Gold is selected as well

If I check on silver Gold shouldn't be selected

### Actual behavior
Both Gold and silver are checked.

**Comment by service-paradis** [comment]
This is how checkboxes work. The value determine is it is selected or not.

You should use objects as values. This way, it will have the desired behavior. See you edited codepen:
https://codepen.io/anon/pen/jgZBZZ?editors=1010

**Comment by kyoukhana** [comment]
Thanks for the modification of the code it works now.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/62599726-07963800-b8fe-11e9-828f-f52d926f71cc.png)
just change native-value on silver, set it for example 201 or something like dat.
