### ISSUE TITLE
Allow custom font icons in Menu component

### ISSUE THREAD

**Issue by Dharmendra205111014** [buefy/buefy#1638]
### Description
Today Menu component support `icon` name `icon-pack` `fa` and `mdi` only, It would be good if we can add support for custom icons and define our own icon pack

### Why Buefy need this feature
Lot of time We do not use font awesome or material design icons for our projects rather we create our own fonts from SVGs, and we would need to support them. It will be really helpful if we can provide such customizations

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/menu/MenuItem.vue#L50

**Comment by service-paradis** [comment]
This should be possible to add simple custom icon pack in the next release (#1681)
