### ISSUE TITLE
b-dropdown data tag missing

### ISSUE THREAD

**Issue by gutisalex** [buefy/buefy#1639]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: MacOS Chrome

### Description

I am using a dropdown in a component for a language selection. The width of the dropdown-content class is supposed to be 65px. This is to be set in the component in the style tag with the scoped option. The issue is that the data tag will not be set on the class. If set globally it works.

### Steps to reproduce

1. Add a custom class to the b-dropdown tag
``` html
<template>
  <b-dropdown
    v-model="selectedLang"
    aria-role="list"
    class="custom-dropdown">
    <button
      slot="trigger"
      class="button is-primary"
      type="button">
      <span>{{ selectedLang }}</span>
      <b-icon icon="angle-down" />
    </button>

    <b-dropdown-item
      v-for="(lang, i) in langs"
      :key="`Lang${i}`"
      :value="lang"
      aria-role="listitem"
      @click="handleSetLanguage(lang)">
      {{ lang }}
    </b-dropdown-item>
  </b-dropdown>
</template>
```

2. Add css selectors to the style tag
``` css
<style lang="scss" scoped>

.custom-dropdown .dropdown-content {
  width: 65px;
}

.custom-dropdown .dropdown-item {
  padding: 6px 16px;
}
</style>
```
![buefy missing data](https://user-images.githubusercontent.com/52527652/62626824-886a2980-b928-11e9-9000-5ce86e58dec9.png)

### Expected behavior
b-dropdown content width is set to 65px

<img width="79" alt="Screenshot 2019-08-07 at 15 33 26" src="https://user-images.githubusercontent.com/52527652/62627083-00385400-b929-11e9-81ef-6050234ec8fb.png">

### Actual behavior
b-dropdown content width is set to standard

<img width="230" alt="Screenshot 2019-08-07 at 10 07 56" src="https://user-images.githubusercontent.com/52527652/62627144-13e3ba80-b929-11e9-87db-03c7c8e4700c.png">

**Comment by yxngl** [comment]
The "data" thing is added by vue-loader when you use scoped style. In this case you want to use deep selector. See https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by gutisalex** [comment]
> The "data" thing is added by vue-loader when you use scoped style. In this case you want to use deep selector. See https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

Yes that did the trick and for those who use scss its 
```css
.parent-class { 
  ::v-deep .child-class { 
    .... 
  }
}
```
