### ISSUE TITLE
Use webpack

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1641]
Should we use vue  2.6.x and webpack 4 for building project?
https://github.com/afwn90cj93201nixr2e1re/buefy/tree/dev/build/prodonly im already done it for myself, maybe you should do this too?

**Comment by jtommy** [comment]
Webpack is only to build docs, I'll be replaced by new project only for docs and I'll remove all dependencies in this project

**Comment by afwn90cj93201nixr2e1re** [comment]
Now some webpack plugins using for compressing and other stuff, not for docs.

**Comment by jtommy** [comment]
No I'm using only rollup, take a look at build:js in package.json and rollup.config.js

**Comment by afwn90cj93201nixr2e1re** [comment]
So, why u r using rollup?

**Comment by jtommy** [comment]
Because I prefer it and then i'll remove all docs here I think

**Comment by afwn90cj93201nixr2e1re** [comment]
rollup builder using auto doc gen or what? Coz i can't get why u prefer it instead webpack, xD.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy rollup builder overusing RAM.
It's taking more 512mb and raising and doesn't clear anything, where webpack use only 256 mb. and build everything(css + js) in 20s, instead > 1min on rollup.

**Comment by afwn90cj93201nixr2e1re** [comment]
Webpack minified file size is 170kb, where rollup - 183kb.
So, there more differences, we must choose webpack(4) instead rollup which is under development now.
Also rollup creating some chunks which is unused then and not deleting them.
