### ISSUE TITLE
Final b-input in b-field group has different size

### ISSUE THREAD

**Issue by rcoundon** [buefy/buefy#1645]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: Mac OS Mojave - Chrome/Firefox

### Description

When using a b-field group of text inputs with grouped and group-multiline, the last b-input has a different size - it's wider.  This is especially noticeable when the width of the browser is reduced to stack the inputs on top of one another.
I've put together a codepen that shows it happening.
https://codepen.io/rcoundon/pen/gVjNrg

### Expected behavior

I'd expect all the inputs to be the same width

### Actual behavior

Final input is wider

**Comment by yxngl** [comment]
The last one does not have a right margin. I think this is how Bulma puts it and in your case, it is probably better to use columns.
