### ISSUE TITLE
navbar and router-link

### ISSUE THREAD

**Issue by hnnweb** [buefy/buefy#1646]
### Overview of the problem

**Buefy** version: 0.8.2
**Vuejs** version: 2.6.10
**OS/Browser**: macOS 10.14.5, Chrome 75.0.3770.142 (Official Build) (64-bit)

### Description

router-link not working. Expecting the parameters to be the same as in _menu_-component.

### Steps to reproduce

```
<b-navbar>
    <template slot="brand">
      <b-navbar-item href="../">
        <img src="/assets/images/logo/logo_top_admin.svg" alt="NT Admin">
      </b-navbar-item>
    </template>
    <template slot="start">
      <b-navbar-item tag="router-link" :to="{ name: 'dashboard' }">Start</b-navbar-item>
      <b-navbar-item href="#">Documentation</b-navbar-item>
    </template>
</b-navbar>
```

### Expected behavior

To point to the correct url

### Actual behavior

![image](https://user-images.githubusercontent.com/3874960/62776468-fcccd600-baaa-11e9-97d6-78dab6f00ab0.png)

**Comment by wanxe** [comment]
Oops seems like we forget set the `inheritAttrs` to false. I'll fix this ASAP. Thanks @hnnweb so much and apologies for the bad experience.

**Comment by hnnweb** [comment]
Cool! :-)
