### ISSUE TITLE
Feature request: Slider "Lazy" option and "dragging" event

### ISSUE THREAD

**Issue by luisjoserivera** [buefy/buefy#1647]
### Description

**Lazy** option to update the value when drag finish.

Additionally: **@dragging**
If you set lazy and still need to listen for changes in the value, you can listen to the event dragging which updates the values live.

### Why Buefy need this feature

Useful whenever you need to consume a high-loss operation (e.g. Ajax).

### Reference

vue-slider-component
https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=lazy
https://nightcatsama.github.io/vue-slider-component/#/api/events?hash=dragging

**Comment by jtommy** [comment]
@yxngl please take a look at this request

**Comment by yxngl** [comment]
Makes sense. I will try to work on it next week.
