### ISSUE TITLE
The text is hidden under the loading property of the button

### ISSUE THREAD

**Issue by fly-bue** [buefy/buefy#1650]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: chrome 74.0.3729.157

### Description
Under the loading property of the button, the text is hidden. Are there other properties that allow the text to be displayed?

### Code
``` <b-button type="is-success" loading>Loading</b-button>```

![image](https://user-images.githubusercontent.com/54001753/62850354-386ad880-bd15-11e9-8b98-12f98ac99ae7.png)

**Comment by yxngl** [comment]
This is how Bulma designed it and you should post it there.

But it can be built like the following and a custom class is needed to add spacing.

```html
<button class="button">
      <span class="loader"></span>
      <span>Loading</span>
</button>
```
