### ISSUE TITLE
Tooltip does not work on tabs-item

### ISSUE THREAD

**Issue by pearson-g** [buefy/buefy#1651]
### Description
Tooltip does not work on tabs-item

`<b-tab-item disabled>
                <b-tooltip label="Tooltip Insufficient permissions, no access" position="is-right">
                <template slot="header">
                    <span> Create</span>
                </template>
                </b-tooltip>
            </b-tab-item>`
### Why Buefy need this feature

When tab-item is set to the disabled property, I want to prompt the user why this property is set. This is a more user-friendly design.

**Comment by cuong-nguyen** [comment]
@pearson-g with some CSS tweaks you can make it work
https://codesandbox.io/s/buefybuefyissues1651-hl2cl

**Comment by pearson-g** [comment]
It's a good idea of Control pointer-events， thanks

**Comment by cuong-nguyen** [comment]
I was cleaning up my dated repos so I move the code here in case people might need it
```
<template>
  <div>
    <b-tabs v-model="currentTab">
      <b-tab-item label="Vue">Vue news</b-tab-item>
      <b-tab-item label="Svelve">Svelve news</b-tab-item>
      <b-tab-item disabled>
        <b-tooltip slot="header" label="Amazing hooks!" position="is-bottom">React</b-tooltip>
      </b-tab-item>
    </b-tabs>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data() {
    return {
      currentTab: 1
    };
  },
  methods: {
    test() {
      alert();
    }
  }
};
</script>

<style>
.b-tabs .tabs {
  overflow: visible;
}

.b-tabs .tabs li.is-disabled {
  pointer-events: auto;
}

.b-tabs .tabs li.is-disabled a:active {
  pointer-events: none;
}
</style>
```

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/f0cfa37b064b4aa43d4aa698ffdeffa30a85b0fd
