### ISSUE TITLE
When creating a dialog with type = is-primary, the icon is not defaulted

### ISSUE THREAD

**Issue by serge1peshcoff** [buefy/buefy#1652]
### Overview of the problem

**Buefy** version: 0.8.2
**Vuejs** version: 2.6.10
**OS/Browser**: any

### Description

When I create a dialog with Buefy and set type as `is-primary` and don't specify an icon, it defaults to `null`, so the icon's class is `fa-null`:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/1060257/62889214-8f8aa080-bd49-11e9-8aa1-4615a5aa9250.png">

When I use FontAwesome v5 with scripts, it ends up ugly, as in this picture:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/1060257/62889324-ccef2e00-bd49-11e9-9e5a-9279c131eaa3.png">

### Steps to reproduce

Add this to your Vue/Bulma application:

```js
this.$buefy.dialog.alert({
    title: 'Error',
    message: 'Something\'s not good but I have a custom <b>icon</b> and <b>type</b>',
    type: 'is-primary',
    hasIcon: true,
    iconPack: 'fa'
})
```

### Expected behavior

A fancy icon

### Actual behavior

There's no icon or a symbol when the icon isn't loaded (see the screenshots above).

JSFiddle link: https://jsfiddle.net/b9qmj2oc/

P.S. This can be fixed by providing the icon manually with 'icon' option.

**Comment by jtommy** [comment]
`is-primary` doesn't provide a related icon so you have to specify `icon` prop when `hasIcon` is equals to true, btw i'm going to fix it in order to hide the icon space in similar case.
