### ISSUE TITLE
Pagination with vue-router

### ISSUE THREAD

**Issue by angelabad** [buefy/buefy#1654]
Hi, I dont know how to program this. I need pagination widget from buefy, but I want to have pagination in url for generating permalinks.

Its possible to do this? And without refreshing in page every url (pagination) change?

Thanks!

**Comment by modularcoder** [comment]
@jtommy I think this is also a good chance/motivation to add slots to the pagination, and make the pagination component more customizable.

So there might be a default layout/slot, but anyone can pass a custom slot template, and use the page number param in the slot. 

The dynamic pages generation (pages before current, pages after current) are still really useful feature even with customized buttons.

What would be solved

- Vue router integration possibility
- Disabling/customizing prev/next buttons
- Customizing the default button components

What do you think?

**Comment by jtommy** [comment]
Ok, I'll wait your PR ;)

**Comment by service-paradis** [comment]
I just made a minimal PR (#1692) to see if it makes sense. Hoping to have some feedback about it!
