### ISSUE TITLE
programatically adjust displayed sorted column for table 

### ISSUE THREAD

**Issue by Ashtonian** [buefy/buefy#1658]
### Description
I would like to programmatically adjust the displayed sort column. 

### Why Buefy need this feature
![sort table example](https://media.giphy.com/media/UT4M8QOTaoEIRwTAuQ/giphy.gif)
In order to allow external things to update the sort similar to paging. As you can see in the gif, the back-end is performing sorting and I can't update the table display to reflect this. This is useful for keeping url params in sync with the table as well. Additionally the current api enables server side sorting here https://buefy.org/documentation/table/#pagination-and-sorting. Additional use case is that the server overrides the client sorting request and provide the sorted column and direction. In this case the data can be sorted correctly but the table will have the wrong column displayed as sorted as the visual icon and direction will be wrong.

**Comment by Ashtonian** [comment]
added example gif showing out of sync sort columns

**Comment by jtommy** [comment]
@Ashtonian You're right! Did you try setting `default-sort` prop and calling `initSort` method (by ref) ?

**Comment by Ashtonian** [comment]
@jtommy something like 

```.js
          this.$refs.zeTable._props.defaultSort = "otherCol"
          this.$refs.zeTable.initSort()
```

I get an error about accessing props directly and it doesn't seem to work.

**Comment by jtommy** [comment]
@Ashtonian I meant something like:
```
<b-table :default-sort="sortcolumn" ref="zeTable"> ... </b-table>
...
data() {
  return {
    sortcolumn: 'firstCol'
  }
}
....
this.sortcolumn = 'otherCol'
this.$nextTick(() => {
   this.$refs.zeTable.initSort()
})

**Comment by Ashtonian** [comment]
that doesn't seem to do anything for me ?

**Comment by jtommy** [comment]
@Ashtonian this is an example https://codepen.io/jtommy/pen/NWKwRgK?&editable=true&editors=101
