### ISSUE TITLE
Taginput (button)

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1659]
May i ask if it possible to insert a button on the right side of the tag input like this?
![image](https://user-images.githubusercontent.com/42717688/62991802-b1883e00-be83-11e9-9f19-632660fd6e26.png)

**Comment by wanxe** [comment]
I think that this is just CSS mate.

**Comment by kenichii** [comment]
@wanxe actually I already did that using css hehe :D thanks mate :D , im just actually asking if this taginput have that thing so that i'm not going to do it on css :D

**Comment by jtommy** [comment]
No you have to work using css and layout elements.
Anyway for general questions, please join [official Discord server](https://discordapp.com/invite/ZkdFJMr).

**Comment by kenichii** [comment]
Okay Thanks mate @jtommy
