### ISSUE TITLE
Autocomplete object value

### ISSUE THREAD

**Issue by cdekok** [buefy/buefy#1661]
Currently it's possible to provide an array of objects in the autocomplete and use the field to show the label, but the value / v-model attribute supports only a string | number

**Buefy** version: 0.8.2

### Description

The value should also accept an object when an array of objects is used.

### Steps to reproduce

https://codepen.io/conceptme/pen/jONWjRO?editors=1010

**Comment by jtommy** [comment]
At the moment v-model is related to input and you get the current selection attaching on "select" event
