### ISSUE TITLE
Table inside a modal does not sync properly

### ISSUE THREAD

**Issue by akrz** [buefy/buefy#1663]
### Overview of the problem

**Buefy** version: 0.8.2
**Vuejs** version: 2.5.2
**OS/Browser**: Ubuntu 18.04 / Chrome 75.0.3770.142

### Description
When updating the model synced to a table inside a modal, it will not update the values.

### Steps to reproduce
Codepen showcasing the issue: https://codepen.io/csolis7L/pen/oNvxNmp
1. Press 'edit list' to open the modal
2. See the issue

### Expected behavior
- 'Ontime Deliveries' should be 'new description'
- Include Summary switch should be off for 'Class Breakdown' chart

### Actual behavior
- 'Ontime Deliveries' not changed
- Include Summary switch is on

Weirdly, the checkbox works fine.

**Comment by yxngl** [comment]
But you never updated the actual data bound to the table. The checked rows are just used to compared with table data.

**Comment by akrz** [comment]
Yep, nevermind. I don't know why, but I thought the :checked-rows.sync would handle the data change.
