### ISSUE TITLE
Observation: Select arrow not using primary color (Style inconsistency)

### ISSUE THREAD

**Issue by luisjoserivera** [buefy/buefy#1665]
### Overview of the problem

I've noticed that Buefy applies the primary color theme to all form elements but select.
I suppose this is a problem derived from Bulma defaults, but as with other elements a workaround fix should be made.

Already noticed an old issue where an attempt to fix this was made: https://github.com/buefy/buefy/issues/837

### Expected behavior

All elements should have same color styles to maintain the consistency in the UI.

**Comment by jtommy** [comment]
Probably you're right but it's a breaking change

**Comment by luisjoserivera** [comment]
@jtommy Forgive my noobinest. Kinda new to participating in this kind of stuffs.
When you tag a thread as "breaking change" does it mean it wont happen or what?

**Comment by jtommy** [comment]
It will be add in the next breaking change, for example 0.9.0

**Comment by service-paradis** [comment]
It is a Bulma issue. There is a customizable [variable](https://github.com/jgthms/bulma/blob/master/sass/form/select.sass#L11) in Bulma for the arrow color (`$input-arrow`)

This [variable defaulted](https://github.com/jgthms/bulma/blob/ddd1d28f61ad06a37e8c18a6daed28893e95fcfb/sass/form/shared.sass#L21) to `$link` which give the default [`$blue`](https://github.com/jgthms/bulma/blob/ddd1d28f61ad06a37e8c18a6daed28893e95fcfb/sass/utilities/derived-variables.sass#L54) color.

You should be able to get the desired color by customizing `$input-arrow` variable.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/797030de4b2dd8437df94ecab340c08224560dd2
