### ISSUE TITLE
How to trigger return event in b-field

### ISSUE THREAD

**Issue by mikeerickson** [buefy/buefy#1668]
### Overview of the problem

**Buefy** version: [latest]
**Vuejs** version: [latest]
**OS/Browser**: [firefox, chrome, safari]

### Description

I am unable to get `@keydown.enter` or `@keyup.enter` to fire in `<b-input>` component

### Steps to reproduce

You can see in this codepen

https://codepen.io/codedungeon/pen/KKPzrEO?editors=1010

### Expected behavior

Expecting `handleSearch` method to be triggered

### Actual behavior

Event is not triggered

**Comment by cuong-nguyen** [comment]
@mikeerickson you need `native` modifier
```
@keydown.enter.native="handleSearch"
```
