### ISSUE TITLE
Taginput (allow new)

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1669]
I dont think if its a bug or i did not properly used it.
![image](https://user-images.githubusercontent.com/42717688/63135766-9ba08780-c001-11e9-8a9b-17f58fee36a0.png)
im trying to initialize a tags v-model then i try to inser not allow new then I tried to insert again the same value.

**Comment by jtommy** [comment]
I don't understand well the issue or your requirement, please provide an example

**Comment by kenichii** [comment]
I actually initializing a tags which will be used on the 
:data
then I also included the allow-new=false on my tag input but when I selected again the same name on my filters, it allows the inserted name on the tag input.

**Comment by jtommy** [comment]
Maybe you're right but I should think about it. 
Anyway at the moment you might use `before-adding` prop, it's a function to validate the value of the tag before adding

**Comment by kenichii** [comment]
ohh let me check it :) Thanks
