### ISSUE TITLE
Dialog to select a file does not appear in IE 11 when using <b-upload>

### ISSUE THREAD

**Issue by stas-kh** [buefy/buefy#1670]
### Overview of the problem

**Buefy** version: latest 0.8.2
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10 / Internet Explorer 11

### Description
Upload dialog does not appear when user clicks on "Click to upload" file button using `<b-upload>` tag

### Steps to reproduce
1) Open Internet Explorer 11
2) Go to the docs: https://buefy.org/documentation/upload
3) Click on the button in the first example

### Expected behavior
The dialog appears where the user is able to select a file

### Actual behavior
Nothing happens

P.S. The example with multiple files selection works pretty well.

**Comment by stas-kh** [comment]
Update: As a workaround, we can set `pointer-events: none` to the `a.button`, but then we cannot make `cursor: pointer` there

**Comment by jtommy** [comment]
I didn't find a fix about it because fixing it on IE11 in the other browsers something goes wrong

**Comment by BeomyeonAndrewKim** [comment]
Could I know which code is changed for this issue?
on release 0.8.3
`Fix #1670 simple upload on IE 11`
