### ISSUE TITLE
Feature request: CheckboxTag

### ISSUE THREAD

**Issue by dejangeci** [buefy/buefy#1672]
## CheckboxTag

![image](https://user-images.githubusercontent.com/1375514/63200378-515eeb00-c081-11e9-8668-5bada9329ebc.png)

### Description

Similar to CheckboxButton, but using tags instead.

### Why Buefy need this feature

When regular checkboxes take too much space and you need a lot of options.

### PR

I've done some initial work and can create a PR, but there are more things to consider: handling attached tags, icons, focus highlight etc. CSS tweaks are also needed, so if someone can continue the work, that would be great.

**Comment by jtommy** [comment]
What are the differences between checkbox button and checkbox tag ?

**Comment by dejangeci** [comment]
Functionally, no difference. Other than that, same as between button and tag. Since it would use .tag, it would be easier to match the design with other tags used throughout an app by customizing the '$tag-xxx' variables.
