### ISSUE TITLE
Switch icons from mdi to vue-material-design-icons

### ISSUE THREAD

**Issue by RyanChristian4427** [buefy/buefy#1673]
### Description

Following the link from Buefy's Constructor Options page, you'll find that the recommended way to implement Material Design icons with Vue is to use the vue-material-design-icons package, which is a collection of single file components.

### Why Buefy need this feature

Since Buefy is Vue specific, there's no real reason to use the old webfont method, as far as I can tell. If there is an officially sanctioned collection of Vue icon components, that should be the way forward.

**Comment by claide** [comment]
Using `nuxt-material-design-icons` 

```
<b-button
    icon-left="filter-list"
>
    <span>Filters</span>
</b-button>
```

the filter-list alias is not working.

**Comment by claide** [comment]
> Using `nuxt-material-design-icons`
> 
> ```
> <b-button
>     icon-left="filter-list"
> >
>     <span>Filters</span>
> </b-button>
> ```
> 
> the `filter-list` alias is not working. Any way how to make this work?

Needs to be `filter-variant` . Sorry for a dumb question.

**Comment by service-paradis** [comment]
This would need the `breaking-change` label

**Comment by subins2000** [comment]
@service-paradis It wouldn't be breaking if <b-icon> had an option to use icon components inside it :
```
<b-icon icon="arrow-up"></b-icon>
```
should give :
```
<arrow-up-icon></arrow-up-icon>

import ArrowUpIcon from 'vue-material-design-icons/ArrowUp.vue';
Vue.component('arrow-up-icon', ArrowUpIcon);
```

**Comment by jtommy** [comment]
We cannot support all icon pack components but you can create a your component that show the icon using 'vue-material-design-icons'

**Comment by subins2000** [comment]
How would one use it for setting the sort icon in table ?

```
<b-table :sort-icon="arrow-up"></b-table>
```

**Comment by jtommy** [comment]
You have to set your custom component to constructor option like vue-fontawesome example

**Comment by subins2000** [comment]
I'm loading components individually to save bundle size, but setting defaultIconPack doesn't have any effect :thinking: 

```
import Table from 'buefy/dist/components/table'
Vue.use(Table, {
  defaultIconComponent: 'new-icon-pack',
  defaultIconPack: 'new-icon'
})
```

**Comment by jtommy** [comment]
https://buefy.org/documentation/constructor-options
