### ISSUE TITLE
Table accepting an object in data

### ISSUE THREAD

**Issue by felaugmar** [buefy/buefy#1676]
### Description

In `b-table`'s `data` prop. we need to pass an array of objects.
But I'm maintaining `data` as an object and so, transforming to array before passing to `data`.

I would like to be able to use it directly with an object and access the object attribute name.
Along with the scoped prop `row` and `index`, in that case, could be included the prop `name`.

### Why Buefy need this feature

It would facilitate the usage of the `b-table` in some cases.

**Comment by jtommy** [comment]
A table contains rows so it's normal that accepts an Array.
I don't understand well your structure to be honest

**Comment by felaugmar** [comment]
The use of an object to map 'rows' facilitates the concept of **unique values**, being the attribute name  the unique identifier, like a Dictionary.

**Comment by jtommy** [comment]
I understand but table component doesn't change it at the moment

**Comment by felaugmar** [comment]
Not even letting it open to someone send pull requests?
Why the suddenly closing?

**Comment by jtommy** [comment]
Because table needs a refactoring for general improvements and I'm sorry but your request is no a priority

**Comment by felaugmar** [comment]
I see.

**Comment by re2005** [comment]
You can try something like:

`return Object.keys(this.documents).map(o => this.documents[o]);`
