### ISSUE TITLE
Navbar with container inside.

### ISSUE THREAD

**Issue by nakorndev** [buefy/buefy#1677]
### Description

Add option to set container inside `nav` at `Navbar.vue` components

### Why Buefy need this feature

Since both bulma.io and buefy.org use `container` class inside `nav` before `navbar-brand` `navbar-menu` to space horizontal.

I suggest should add option for set `container` like `<b-navbar :hasContainer="true"></b-navbar>` then inside of `Navbar.vue` should render like this sample.

```html
<nav
    class="navbar"
    role="navigation"
    aria-label="main navigation"
    :class="computedClasses"
>
    <div class="container">
        <div class="navbar-brand">
            <slot name="brand"/>
            <slot name="burger" v-bind="{ isOpened, toggleActive }">
                <navbar-burger @click.native="toggleActive" :is-opened="isOpened"/>
            </slot>
        </div>
        <div class="navbar-menu" :class="{ 'is-active': isOpened }">
            <div class="navbar-start">
                <slot name="start" />
            </div>
            <div class="navbar-end">
                <slot name="end" />
            </div>
        </div>
    </div>
</nav>
```

Reference at: https://github.com/buefy/buefy/blob/0f7320f2e3f86a43eacd9d366bb08692418c457d/src/components/navbar/Navbar.vue#L2-L22

**Comment by wanxe** [comment]
Thanks for your suggestion @nakorndev, but why not simply add your container div instead to add more props?
Sorry, but I can't understand the motivation of this.

**Comment by germain-receeve** [comment]
I think with the current implementation, it's not possible to wrap the elements inside the navbar directly (since they are in seperate template slots: brand, start and end). I would also be interested by this feature!

**Comment by wanxe** [comment]
Ok, hands to the job then :D

**Comment by HRussellZFAC023** [comment]
![image](https://user-images.githubusercontent.com/22746105/63616449-7acaca00-c5df-11e9-8d9b-df7309a9ca19.png)
Adding colour is another example use case which would require this spacing (rather than a container on the outside).

**Comment by jtommy** [comment]
Fix 2f0d6dc1cebffab1e5845f7b3731fb30a6e5960d

**Comment by vimalmistry** [comment]
How to add <div class="container"> inside navbar?? This issue marked as fix. But can not find any proper doc for this.

**Comment by androcado** [comment]
Hey, is it closed? How can I create a container class within the navigation? Thanks

**Comment by androcado** [comment]
Hey is it closed How can I create a container class within the navigation? Thanks

**Comment by androcado** [comment]
> Hey ist es geschlossen Wie kann ich eine Containerklasse innerhalb der Navigation erstellen? Vielen Dank

<b-navbar wrapper-class="container">

Works well. Thanks!
