### ISSUE TITLE
[Navbar] On mobile, clicking on an link doesn't automatically hide the menu

### ISSUE THREAD

**Issue by germain-receeve** [buefy/buefy#1679]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome

### Description

When the navbar is in mobile mode, clicking on an item doesn't automatically hide the burger menu. Instead, it stays open after you have clicked a link and you have to reach for the cross in the top right to hide it.

### Steps to reproduce

1. Add a navbar with at least one navbar item to your page
2. Shrink your browser size so the navbar has the burger menu in the top right
3. Toggle the menu using the burger icon
4. Click on a link

### Expected behavior

The menu should close after clicking a link

### Actual behavior

The menu stays opened after clicking a link

**Comment by gbgb66** [comment]
I see the same problem. Navbar menu does not close after clicking on the menu item.

**Comment by wanxe** [comment]
Thanks @germain-receeve, we will correct this shortly.

**Comment by afwn90cj93201nixr2e1re** [comment]
> The menu should close after clicking a link

By default bulma doesn't close dropdown, why we should close it by default?

@wanxe maybe you should add additional prop to disable this feature?

**Comment by wanxe** [comment]
> > The menu should close after clicking a link
> 
> By default bulma doesn't close dropdown, why we should close it by default?
> 
> @wanxe maybe you should add additional prop to disable this feature?

Yeah sure, it's an easy fix.

**Comment by afwn90cj93201nixr2e1re** [comment]
Thx.
