### ISSUE TITLE
Open Modal Programmatically From Outside Vue

### ISSUE THREAD

**Issue by MannikJ** [buefy/buefy#1680]
**Buefy** v0.8.2
**Bulma** v0.7.5
**Vue** 2.6.10
It's a **Laravel** v5.8.29 setup using **laravel-mix** v4.0.15 (webpack)

The modal component's  [documentation](https://buefy.org/documentation/modal) explains I should be able to open a buefy modal programmatically from outside of vue like this.

```js
import { ModalProgrammatic as Modal } from 'buefy'
Modal.open(props)
```

No matter if I place the snippet in `boostrap.js` or `app.js` and no matter which position I always get 
```
Cannot read property 'open' of undefined.
```  
So how to properly import this module or why is it still undefined although the documentation lets assume it should work.
I guess the solution is quite simple, but I just couldn't figure it out.
Would be great if anyone could help.

**Comment by jtommy** [comment]
Are you sure to use 0.8.2 version ?

**Comment by MannikJ** [comment]
Lol. I have been until the moment I read your comment. Thanks it's now working. It was - as most the times - the most obvious mistake. Watcher running forever and still compiling the old version ;)
