### ISSUE TITLE
Legend (level) 

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1682]
I think it's good to add b-legends :) 
it is very useful when creating a web app like creating a user permission levels 
![image](https://user-images.githubusercontent.com/42717688/63397449-2b2ca880-c3fd-11e9-9306-52b0aa326c32.png)

**Comment by kenichii** [comment]
and you can also add a horizontal name for each legends

**Comment by jtommy** [comment]
@kenichii I'm sorry but I think it's a too personal request to a generic UI library.

**Comment by kenichii** [comment]
Well its okay sir :) I'm just actually asking if its okay :) I actually created one :)
