### ISSUE TITLE
autoClose not working on programmatically-triggered Notification 

### ISSUE THREAD

**Issue by jorgepinon** [buefy/buefy#1684]
### Overview of the problem

**Buefy** version: 0.7.4
**Vuejs** version: v2.5.17
**OS/Browser**: Tested on Safari and Chrome

### Description

When launched programmatically, a notification will auto-close by default even though the default for the prop is 'false'. Explicitly setting autoClose: false doesn't have any effect either.

You can see this on the Codepen example in the [Notification docs](https://buefy.org/documentation/notification/#programmatically-opening) (once in codepen, add `autoClose: false` to the object passed into the `open` method).

```
success() {
    this.$buefy.notification.open({
       message: 'Something happened correctly!',
       type: 'is-success',
       autoClose: false
    })
},
```

### Steps to reproduce

1. Trigger a notification modal programmatically
2. Add autoClose: false to the settings object

### Expected behavior

The notification should stay on the page until the user closes it (assuming closable is true)

### Actual behavior

The notification closes after the default timeout (as if auto-close was true)

**Comment by jtommy** [comment]
You should use indefinite prop.
I'll improve docs to avoid misunderstanding :)
