### ISSUE TITLE
How can i insert an anchor tag <a href=""></a> to the table?

### ISSUE THREAD

**Issue by GabMic** [buefy/buefy#1688]
Hello. 
I am using the `Table` component, and it is working fine... just wondering how can wrap an element in one column with an anchor tag?

For example, i have the following table:

![‏‏table](https://user-images.githubusercontent.com/11059876/63511835-ec751c00-c4ea-11e9-9de7-d5592d6e4f60.PNG)

I want to make the number under the `license number` column an anchor tag.

How can i do that? 
Thanks, hope i am clear.

**Comment by jtommy** [comment]
You have to use the default slot to add the columns, for example https://buefy.org/documentation/table#sandbox-with-custom-template.
In this way you are able to add html in each column data

**Comment by GabMic** [comment]
@jtommy  well, i have succeeded adding the anchor tag, but how do i choose the license nubber now?
i have tried `{{columns.license_number}}` and `${columns.license_number}` bot to no avail.

            <template slot-scope="columns">
                <b-table-column field="license_number" label="license number">
                   <a href="/vets/ {{ data.license_number }}"> {{ data.license_number }}</a>
                </b-table-column>

What am i missing here? Please help me, i am fairly new to this.
thanks.

**Comment by jtommy** [comment]
columns.row.license_number.
Btw use Discord channel for this requests and take a look at docs
