### ISSUE TITLE
B-Table-column Label does not clear if slot is empty

### ISSUE THREAD

**Issue by Engjell00** [buefy/buefy#1691]
**Buefy** version: ["^0.8.2"]
**Vuejs** version: ["^2.5.21"]

Description
Hello, my issue is when I first have data in my b-table, all my data displays all normals with no problem.
But the moment I have no data , My ```<div slot="empty"></div>``` is displaying. Which is the case I want!

However, the Labels of all my b-table columns remains which in this case I want them to disappear. The only way, I can make it work is by completely reloading the page.

**Comment by jtommy** [comment]
Do you mean "header" ?

**Comment by Engjell00** [comment]
@jtommy  Well it would  be the ''<th>" of the table.

**Comment by jtommy** [comment]
What? Could you provide an example?

**Comment by Engjell00** [comment]
```
 <b-table>
   <div slot="empty"> no Props yet </div>

    <b-table-column label="Task">
          {{myProps}}
    </b-table-column>
```
So , the label is displaying even if , my slot='empty' is displaying. I don't want the label to stay. It stays even if there is no props.

**Comment by lunfel** [comment]
I have a working example of the issue.

http://jsfiddle.net/sng4685w/14/

Step to reproduce:
1.  The array is empty, the empty slot appears without any headers
2. Click the add row button to add content. The empty slot disappears and the headers appear.
3. Click the clear button to remove all items from the array. The empty slot appears again, but this time the table headers are still visible.

**Comment by afwn90cj93201nixr2e1re** [comment]
#1700

**Comment by jtommy** [comment]
Fix/improvment could be a breaking change.
I'm going to refactor table component so i'll work on it too.

**Comment by wrabit** [comment]
@jtommy is there a method to keep table headers visible when using `<b-table-column>` in slot?

**Comment by jtommy** [comment]
No but in the next version I added a new prop ;)

**Comment by s207152** [comment]
When can we expect the new prop landing?
