### ISSUE TITLE
Tooltip primary class always applied 

### ISSUE THREAD

**Issue by rcoundon** [buefy/buefy#1693]
### Overview of the problem
When applying a class such as is-dark to a tooltip class, is-primary is always applied in addition to the specified class

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: Mac Mojave - Chrome

### Steps to reproduce

Create a tooltip as follows:

```
            <b-tooltip
              label="Some text"
              :active="true"
              always
              multilined
              position="is-right"
              class="is-link"
            >
```
In the following image you can see that is-link and is-primary are both applied
![image](https://user-images.githubusercontent.com/9136570/63586120-8777ff80-c598-11e9-95c5-aa7d2484d12c.png)

### Expected behavior
In this example, only is-link would be applied

### Actual behavior
Both are applied and is-link is effectively overridden by is-primary

**Comment by jtommy** [comment]
@rcoundon You have to use type prop to override it

**Comment by rcoundon** [comment]
My mistake, thanks
