### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by armanivvv** [buefy/buefy#1696]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: OSX / Chrome 

### Description

Navbar appears to be triggering a full reload at the "app" entry point as opposed to transitioning via the router and it is not respecting transitions.

### Steps to reproduce

1.Old Bulma based navbar
```
<template>
  <transition name="nav-fade" mode="out-in">
    <nav class="navbar" role="navigation">
      <div class="navbar-brand"></div>
      <div id="workaround4Tablet" class="navbar-menu">
        <div class="navbar-end">
          <router-link to="/listing" class="navbar-item">Test</router-link>
          </div>
        </div>
      </div>
    </nav>
  </transition>
</template>
```

2.Buefy based navbar
```
<template>
  <transition name="nav-fade" mode="out-in">
    <b-navbar>
      <template slot="brand">
      </template>
      <template slot="start"></template>
      <template slot="end">
        <b-navbar-item href="/listing">Test</b-navbar-item>
      </template>
    </b-navbar>
  </transition>
</template>
```

This is the css for the transitions (lesser problem but related to the skipping of router)
```
.nav-fade-enter-active,
.nav-fade-leave-active {
  transition-duration: 0.7s;
  transition-property: height, opacity;
  transition-timing-function: ease;
  overflow: hidden;
}
.nav-fade-enter,
.nav-fade-leave-active {
  opacity: 0;
}
```

### Expected behavior

Smooth transition between views and retention of history in vue devtools routing history view.

### Actual behavior

Refresh from the "app" point of entry and then transition via router to selected route.

**Comment by service-paradis** [comment]
If you use traditional `href` in your navbar item, it will use the traditional browsing experience:
```
<b-navbar-item href="/listing">Test</b-navbar-item>
```

You will need to use `router-link` if you wat to use the Vue router Way:
```
<b-navbar-item tag="router-link" to="/listing">Test</b-navbar-item>
```

**Comment by jtommy** [comment]
There was an issue about it https://github.com/buefy/buefy/issues/1646.
In the next release you are able to follow the above example

**Comment by slidenerd** [comment]
still not working even after all these years
