### ISSUE TITLE
B-table doesn't update local array on splice

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1700]
## Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: doesn't mater

### Description
Create table with binding like `:data="someArray"`.

Create some button and add to handler `this.someArray.splice(0, 1);`.

Column header's still stay, but empty slot is showing too.
Also page's value not updated too.

### Expected behavior

Create watcher which gonna update local copy too(but better use reference)

**Comment by afwn90cj93201nixr2e1re** [comment]
Related to backend pagination, **not same as previous issue**. (**_Don't close_**)

![изображение](https://user-images.githubusercontent.com/9306996/63655998-11de8000-c7a0-11e9-8714-3d976c288b6d.png)
Should be refactored.

https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L44
should be 
`<thead v-if="newColumns.length && newData.length">`

Should be updated on splices if totalcount < perPage or something like that.
`newDataTotal` and `total`


@jtommy ping.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also slot empty should replace all table, not a slot if it's possible.

**Comment by jtommy** [comment]
@afwn90cj93201nixr2e1re You're right but I would like to add a prop to choose if the header is always visible when there is no data

**Comment by afwn90cj93201nixr2e1re** [comment]
+, or we can just add something like  `<thead v-if="newColumns.length && newData.length && isEmptySlotExists">` i mean, you know, xD.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also here is extra @page-change call.
pseudocode:
```
this.someArray.splice(0, 1);
this.total--;
```

After(or before) deleting the last item it's called.

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/1691

**Comment by afwn90cj93201nixr2e1re** [comment]
'r u sure?
Did you read first comment?
![изображение](https://user-images.githubusercontent.com/9306996/63894740-7ac33380-c9fe-11e9-89e3-f0c938a02f13.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
How backend pagination bugs related to empty slot at all?

**Comment by jtommy** [comment]
Open a new issue about it there is a problem with the backend pagination

**Comment by afwn90cj93201nixr2e1re** [comment]
Damn it's issue about not updating on backend pagination.
What's wrong?
