### ISSUE TITLE
b-table-column creating extra space on header

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1703]
### Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: -

### Description

As you can see label is without space at end, but it's inside div
http://jsfiddle.net/sng4685w/14/
![изображение](https://user-images.githubusercontent.com/9306996/63689288-9c63c580-c81a-11e9-9a2b-eeda230a9668.png)

### Expected behavior

Shouldn't have extra space/caret at end

**Comment by jtommy** [comment]
You're right but is it really an issue?

**Comment by afwn90cj93201nixr2e1re** [comment]
Idk, but why it's showing? I wanna double click and copy title, but getting it with extra space on end. So, if you can, just give some advice, idk why it's happening.

**Comment by jtommy** [comment]
Maybe something about https://vue-loader.vuejs.org/options.html#compileroptions

**Comment by afwn90cj93201nixr2e1re** [comment]
no, it's not, check values with vue dev tools, they r without spaces, this issue related directly to buefy, not vue.

**Comment by jtommy** [comment]
You can check code, no extra spaces are added

**Comment by afwn90cj93201nixr2e1re** [comment]
i see, but, on other component's like field with label no issues, but still using same way, idk.
I mean, it's table issue, not all components.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, i checked it again, and there bug!
**Each component** which have two new lines symbols, (LFLF) translated to single space by loader.

You can check dist .js file. There is more 120 single spaces which is 2 newline symbols in src.

2 ways to fix it, delete all newlines in templates(but you gonna break all forks again, it's already happened once when you just start tabulating for eslint) or use vue-loader options and go to using vue 2.6.x, instead 2.5.


For example: https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L21,  https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L93 gonna be replaced by single space.

Thats totally bug.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy @service-paradis open compiled src and ypu gonna found this single space replacement's.

**Comment by afwn90cj93201nixr2e1re** [comment]
I have removed it from dist and there's no any single space overridings.
