### ISSUE TITLE
Toast/Snackbar Buefy

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1705]
is there a property for this to add icon?
![image](https://user-images.githubusercontent.com/42717688/63738231-b6a1b000-c8bb-11e9-87fb-1362f1c47e2f.png)

**Comment by jtommy** [comment]
What icon? You can use html code as message prop

**Comment by kenichii** [comment]
I'm just actually trying to insert an check icon on the left side, but i dont know if it has a prop for adding an icon'

**Comment by jtommy** [comment]
No there isn't an icon prop

**Comment by kenichii** [comment]
ohh I see :) thanks sir Godbless
