### ISSUE TITLE
Closing programmatic modals on route change

### ISSUE THREAD

**Issue by markokos01** [buefy/buefy#1711]
### Overview of the problem

**Buefy** version: 0.8.2
**Vuejs** version: 2.6.10
**OS/Browser**: Ubuntu/Chrome

### Description

When I open programmatic modal and after that, I change route (for example, click on browser back button) and modal is not closing. Is that expected behavior? If not, how can I get all modals and close them on route change?

### Steps to reproduce

1. Trigger modal programmatically
2. Do not close modal
3. Change route

### Expected behavior

The modal should close on route change.

### Actual behavior

The modal stays open after route change.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, but which case expect modal on changes?
Also you can keep modal ptr in vuex or some global var inside vue scope, and on router change handler's call close, but this gonna work only for one modal, xD.
So, there should be one more method for any programmatic cases, like .closeAll().

**Comment by xaksis** [comment]
Apologies on commenting on a closed issue but I think this ticket is very valid. Is there a reason for programmatically created modals to remain open when the user navigates away from the parent page? The default behavior should be to close the modal if the parent page has been destroyed?

**Comment by fungiboletus** [comment]
Assuming you use `vue-router`, this is how I did it:

```javascript
router.afterEach(() => {
  document.querySelectorAll('.dialog.modal').forEach((modal) => {
    modal?.__vue__?.$vnode?.context?.close();
  });
});
```
