### ISSUE TITLE
navbar has-dropdown

### ISSUE THREAD

**Issue by dan-lettusgrow** [buefy/buefy#1712]
Hi,

I've been trying to migrate from the old bulma navbar to the new buefy component in 0.8, but have been struggling to reimplement menu dropdowns similar to those in the bulma docs, as seen on https://bulma.io/documentation/components/navbar/ with the hoverable _more_ entry.

The fact that the buefy docs don't show one like the bulma makes me suspect that this isn't implemented yet - is this the case or am I simply not implementing it correctly?

**Comment by service-paradis** [comment]
You can add your own hoverabke dropdown into a navbar-item. Something like this should work:
https://codepen.io/service-paradis/pen/MWgoGYo

**Comment by dan-lettusgrow** [comment]
Thanks for the code sample! The look & feel doesn't seem to fit quite in line with what you'd expect from a navbar menu but I'll probably just override the styles myself to be more in-line with Bulma's navbar dropdown.

**Comment by service-paradis** [comment]
By adding `class="has-dropdown is-hoverable"` to the navbar-item, the look is better. But you are right that this is not exactly the same as Bulma.

**Comment by hoquangthaiholy** [comment]
![Screen Shot 2019-09-11 at 8 35 23 PM (2)](https://user-images.githubusercontent.com/614264/64697717-0e533480-d4d4-11e9-8907-512f85b1b098.png)
I also got a problem with navbar dropdown position. In this case, right menu :(

**Comment by hoquangthaiholy** [comment]
I found in source code. This component support right/boxed but it's not mentioned in document. Solved, Thanks.

**Comment by jtommy** [comment]
@hoquangthaiholy You have to wait the next release
