### ISSUE TITLE
navbar on mobile does not close automatically after clicking on item

### ISSUE THREAD

**Issue by sugacube** [buefy/buefy#1716]
### Overview of the problem
**Buefy** version: 0.8.2
**Vuejs** version: 2.6.10
**OS/Browser**: windows

### Description
I created a simple navbar, with items having a <router-link>.
Navbar works as expected. clicking links triggers navigation.
However, on mobile, navbar is hidden and opens with hamburger. clicking the item, navigates correctly, but does not close the navbar.

### Expected behavior

I'm not sure what to expect, if closing should be automatic or not.
Maybe navbar items are not supposed to be router links ?

Can an example be provided in documentation on how to add a functional navbar item ?
Maybe easiest way is to add some sort of @click to the router-link to set is-active to false, if that is the only way, maybe this could be put in documentation.
If navbar items are not supposed to be router links, maybe this to be documented ?

**Comment by jtommy** [comment]
There was an issue about router-link, please wait next release
