### ISSUE TITLE
input maxlength takes too much margin ..

### ISSUE THREAD

**Issue by sanhar** [buefy/buefy#1719]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: chrome

### Description
 ```
    <div class="grid-register ">
        <b-field  size="is-small" label="Name" custom-class="has-text-white has-text-weight-bold ">
        </b-field>
        <b-input  size="is-small"  name="name"  v-model="fields.name" maxlength="6" ></b-input>
    </div>
        <div class="grid-register ">
        <b-field  size="is-small" label="Name2" custom-class="has-text-white has-text-weight-bold ">
        </b-field>
        <b-input  size="is-small"  name="name2"  v-model="fields.name2" maxlength="6" ></b-input>
    </div>


<style>
.grid-register {
     display:grid;
    grid-template-columns: 1fr 3fr ;
    grid-column-gap:0.5rem;
}
</style>

```

### Steps to reproduce

 
if  '  maxlength="6" ' is removed their margin reduce correctly .

in the b-input tag 'maxlength' property gives too much margin 

### Expected behavior

 
even if 'maxlength' property added that should not add more margin .

### Actual behavior

adding maxlength produce margin unexpected .

**Comment by afwn90cj93201nixr2e1re** [comment]
this is truly html5 validation problems, this can be reproduced on other form components(fields) too.

**Comment by jtommy** [comment]
@sanhar It adds a margin bottom because there is character counter using `maxlength` prop.
Btw you might disable it using `:has-counter="false"` or `defaultInputHasCounter` (constructor options)
