### ISSUE TITLE
Question: Scroll to element

### ISSUE THREAD

**Issue by Nasirinejad** [buefy/buefy#1720]
Hi, Newly I'm using Buefy, 
I want to scroll to an element on page by clicking a button and also I want hide scrollbar
I didn't see anything for this in Buefy documentation, Now I want to know did Buefy have and solution for me Or I had to use something else like vue-scroll?
Thank You❤

**Comment by jtommy** [comment]
@Nasirinejad Buefy doesn't provide anything like that
