### ISSUE TITLE
Allow reordering tags in tag-input element by drag-and-drop

### ISSUE THREAD

**Issue by JivanRoquet** [buefy/buefy#1723]
### Description

This is a suggestion to implement a reordering capability in tag-input elements.

Let's say someone enters tags as `['foo', 'bar', 'baz']`.

Currently, if one wants to reorder them like so it becomes `['bar', 'baz', 'foo']`, one has to delete all the tags and re-write them in the correct order. While it is okay-ish for two or three short tags (like in this example), it very quickly gets old with say 8 or more longer tags.

Would it be feasible to implement a drag-and-drop reordering of the tags so that the user can be able to simply slide them within the input box to change the ordering?

### Why Buefy need this feature

Buefy currently doesn't have a ordered list input, and the tag-input element is the closest thing that matches this use case. The only thing that's missing is in many cases, ordering actually matters and having this capability in tag-input would make it a perfect match for this use case.

**Comment by jtommy** [comment]
@JivanRoquet do you mean something like this https://codepen.io/jtommy/pen/NWKaJoJ

**Comment by JivanRoquet** [comment]
@jtommy Exactly!

**Comment by jtommy** [comment]
I might add it in the extensions page but I don't think to add this feature (without sortable js) in the core code

**Comment by JivanRoquet** [comment]
I see, I understand that adding a dependency would be a problem, and doing it from scratch looks like a bad idea. I'll try to see what I can do taking inspiration from your codepen. Cheers.

**Comment by Lucassifoni** [comment]
Hello @jtommy , thank you for this. May I derive something of your codepen for my use ?
Pens are MIT by default but I prefer to ask.

**Comment by jtommy** [comment]
Sure!!
