### ISSUE TITLE
Autocomplete Options don't hide on blur (mobile)

### ISSUE THREAD

**Issue by signalwerk** [buefy/buefy#1726]
### Overview of the problem

**Buefy** version: latest in documentation
**OS/Browser** iOS – Safari – iPhone XR

### Description
When I use the Autocomplete (latest) on a mobile and then click outside of the Input the Options stay and don't hide anymore. 

### Steps to reproduce

![blur](https://user-images.githubusercontent.com/992878/64112257-2bc32880-cd87-11e9-86a6-f94d80111247.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
You should use new dropdown props.
Check it on dropdown page.

**Comment by signalwerk** [comment]
@afwn90cj93201nixr2e1re thank you for your answer. I was speaking about the `b-autocomplete` as far as I can see I can't use the new  `can-close` on it. right?

Here my code:
```js
      <b-autocomplete
        v-model="userInput"
        :data="filteredDataArray"
        :open-on-focus="true"
        :clear-on-select="true"
        :placeholder="placeholder"
        :can-close="true" // ←←←←← HERE
        icon="magnify"
        size="is-medium"
        field="name"
        @select="onSelect"
        @focus="onFocus"
        @blur="onBlur"
      >
```

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems like im wrong at it, coz @jtommy said that he gonna try to use dropdown inside autocomplete, but still not done.

So, i checked it from android device, and can't reproduce problem on https://buefy.org/documentation/autocomplete forms.

**Comment by jtommy** [comment]
I don't have an iPhone or similar to test it. 
It works on Android

**Comment by signalwerk** [comment]
@jtommy @afwn90cj93201nixr2e1re 
I'm currently having limited access to a https://www.browserstack.com/ account. If you are interested to get an account for a few days to test it, I could organise that. I'm not really familiar with the code-base but I could at least help you out with that.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think you can just debug it, no?
Just add some this.$buefy.toast notification's and check where is code not called.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/64575624-d4741800-d385-11e9-867e-b4af706f17be.png)
can't reproduce it on this device

**Comment by signalwerk** [comment]
I tested it on iOS 12 on a real device and on simulators.

The problem is that I don't loos the selection anymore when clicking outside:
 
Here: iPhone XR, iOS v12

![blur](https://user-images.githubusercontent.com/992878/64593494-79a2e680-d3ae-11e9-9a18-5bd3ef5c9461.gif)

**Comment by signalwerk** [comment]
I tried to find a solution and found out that iOS is handling loose focus special: https://github.com/angular/components/issues/9623
