### ISSUE TITLE
Can't set Datepicker to year less than 100

### ISSUE THREAD

**Issue by mateuswetah** [buefy/buefy#1727]
### Overview of the problem

**Buefy** version: 0.8.2
**Vuejs** version: 2.6.17
**OS/Browser**: Linux Ubuntu / Firefox

### Description 

I've been trying to insert dates with year values smaller than 100 on datepicker, using `editable` prop. The problem is that it won't work it just insert values as 1912 if I pass 12 as value, for example.

### Steps to reproduce

Try it here:
https://codepen.io/pen?&editable=true&editors=101

1. Use any Datepicker with editable prop.
2. Manually set year to a value smaller than 100. 
3. Check that the value is not actually updated and the year still the same.

### Expected behavior

Well, the obvious.

### Actual behavior

Not updating the value of year.

### Comments

From what I know, this may be related to the `new Date()` constructor, which does that by default. I'm not sure how to handle it thought. I was able to build a correct date string from breaking a string into parts and then setting `date`, `month` and `fullYear` values separately.

**Comment by mateuswetah** [comment]
To complement the information, here's a stack that seems to be related:
https://stackoverflow.com/questions/29968116/javascript-date-01-01-0001/29970069#29970069

**Comment by jtommy** [comment]
When you want use editable prop you often have to define a custom parser and formatter; probably we might improve docs
