### ISSUE TITLE
File drag and drop in Firefox not working from "File Upload" explorer window

### ISSUE THREAD

**Issue by rahulmehtasiemens** [buefy/buefy#1729]
### Overview of the problem
We have used the upload functionality of buefy where any files can be dragged for upload. This works fine in Chrome. However, I am having troubles in Firefox.

**Buefy** version: [Latest]
**Vuejs** version: [Latest]
**OS/Browser**: Windows10/Firefox

### Description
File drag and drop in Firefox not working from "File Upload" explorer window

Workflow: In Firefox, when I click on the browse button/DragAndDropSpace, a window pops up titled, "File Upload" If I click an file and click "open" it works fine, but I can't drag any files out of the "file upload" window. However, if I open my file explorer, I can drag and drop the files, just fine from the File Explorer window, but when I try to drag from the popup window titled "File Upload", I get a ghost image with a circle and red slash.

### Expected behavior
Since it is working in Crome browser so it should also work on other browser.

This issue is also reproducible with buefy "Drag and drop" example.Please find the link below.
"https://buefy.org/documentation/upload/"

Please fix the issue or suggest the workaround for the same.

If you need more details please let me know.

**Comment by jtommy** [comment]
@rahulmehtasiemens I don't understand well btw I remember that Firefox has a different behaviour using drag/drop native feature. Could you provide us an example on codepen or similar ?

**Comment by rahulmehtasiemens** [comment]
You can reproduce the issue using "Drag and drop " Code pen example.
link: https://buefy.org/documentation/upload/
 Steps:
1. Open the above link in Firefox browser
2. Open the codepen of  "Drag and drop" example
3. Click on "Drop your files here or click to upload"
4. A "File upload" dialog will pop up
5. Now try to select the file from "File upload" dialog and drop it to area
6. It will not allowed to drop a file for upload getting a ghost image with a circle and red slash.

It is doable with crome browser.

**Comment by jtommy** [comment]
@rahulmehtasiemens I'm trying on Firefox and i don't see any issues

**Comment by apolokaklab** [comment]
i'm trying too on firefox latest and chromium latest with kali linux, well i don't see any issues.

**Comment by rahulmehtasiemens** [comment]
I have upload the video of the issue what we are facing please have a look on it.

[BuefyUploadBug.zip](https://github.com/buefy/buefy/files/3574475/BuefyUploadBug.zip)

**Comment by rahulmehtasiemens** [comment]
Did you get a chance to look the uploaded video.

**Comment by rahulmehtasiemens** [comment]
@jtommy @apolokaklab 
Did you get a chance to look the uploaded video.

**Comment by apolokaklab** [comment]
@rahulmehtasiemens I have seen your video, but with me it works, have you tried drag and drop on Firefox without opening a dialog? like drag drop from expoler. if it remains the same I need more info.

**Comment by rahulmehtasiemens** [comment]
@apolokaklab I have tried a drag drop from explorer, It works for me but I want the above mentioned behavior _i.e. Drag and Drop from "File upload" dialog._

**Comment by apolokaklab** [comment]
Yes, but it's not from Buefy but Firefox. if you want it like that, please add issue to firefox.

**Comment by rahulmehtasiemens** [comment]
@apolokaklab Thanks you for your support, I will more dig in Firefox functionality and file a bug to them. but I am surprised that if its a behavior of Firefox then how other website sites handling it.

Thanks 
Rahul Mehta
