### ISSUE TITLE
0.8.3: FontAwesome duotone icons not rendering Chrome/Firefox

### ISSUE THREAD

**Issue by MarkGriffiths** [buefy/buefy#1730]
### Overview of the problem

**Buefy** version: [0.8.3]
**Vuejs** version: [2.6.10]
**OS/Browser**:
macOS/Chrome
iOS/Chrome
macOS/Firefox

### Description

After updating to Buefy 0.8.3 (nothing else was updated), both Chrome and Firefox no longer render any duotone icon.

### Steps to reproduce

```
import {
	faCheck, faCheckCircle, faInfoCircle...
} from '@fortawesome/pro-light-svg-icons'

import {
	faMoon, faLightbulb, faMailbox
} from '@fortawesome/pro-duotone-svg-icons'

import {
	faTwitter, faFacebookSquare...
} from '@fortawesome/free-brands-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faCheck, faCheckCircle, faInfoCircle, faMoon, faLightbulb, faMailbox...)

Vue.use(Buefy, {
	defaultIconPack: 'fal',
	defaultIconComponent: FontAwesomeIcon
})
```

And in the source:

`<b-icon pack="fad" size="is-small" ></b-icon>`

1. Update to Buefy 0.8.3
2. Vue: `npm run serve` in project directory
3. Open site in browser.

### Expected behavior

FontAwesome duotone icons to be rendered in all browsers. as they were in 0.8.2.

### Actual behavior

While Safari renders the icons correctly, Chrome and Firefox do not - no icon is rendered.

Console errors:
```
[Vue warn]: Invalid prop: custom validator check failed for prop "size".
warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620

Could not find one or more icon(s)
Object
iconName: "fa-mailbox"
prefix: "fad"
__proto__: Object

Object
__proto__: Object

log @ webpack-internal:///./node_modules/@fortawesome/vue-fontawesome/index.es.js:298
9
```

**Comment by jtommy** [comment]
It'll be fix soon but at the moment try adding customIconPacks for your FA (fas or fad or etc):
```
Vue.use(Buefy, {
  defaultIconComponent: "vue-fontawesome",
  defaultIconPack: "fas",
  customIconPacks: {
    fas: {
      sizes: {
        default: "lg",
        "is-small": "",
        "is-medium": "2x",
        "is-large": "3x"
      },
      iconPrefix: ""
    }
  }
});
```

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/pull/1733 but I'll close it when I'll release a new version
