### ISSUE TITLE
Tables - sortable column with custom html in header slot without triggering sort

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#1732]
I'm using buefy tables with sortable on columns and all is working well.

However I'd like to add an element (namely a dropdown) into a column header of a sortable colum. Something like:

```
<b-table-column field='name' sortable>
  <template slot="header">
    <b-dropdown ....>
        <b-dropdown-item v-for="i in items"  @click="doSomething(i)"...>{{ i }}</b-dropdown-item>
    </b-dropdown>

    Name
  </template>

  {{ props.row.name }}
</b-table>
```

I'd like to `doSomething()` (namely apply some global filters but it shouldn't matter) once I select the item in the dropdown. However whenever I select anything in the dropdown which is inside the header the sort gets triggered.

Is there a simple way to achieve this? Either prevent the sorting if clicked on `doSomething()` or better to prevent sorting on a flagged element inside the header.

Thank you all for the pretty neat library.

**Comment by jtommy** [comment]
Did you try using click.stop on dropdown item ?

**Comment by dmcbrn** [comment]
No, can you please point me to some reference as I'm not sure what you mean.

In the meantime I've dropped the `@click=doSomething()` and I'm using v-model on computed property with setter and a getter, where setter dispatches the ajax request. In short, no more `@click..`

**Comment by jtommy** [comment]
I mean @click.stop="doSomething"

**Comment by dmcbrn** [comment]
```
 <b-dropdown-item v-for="i in items"  @filter.native.stop=""...>{{ i }}</b-dropdown-item>
```

does it. No need for any value if using `v-model`

@jtommy thanks
