### ISSUE TITLE
Timepicker (Initialize  Hours)

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#1734]
Thank you for the updates on the timepicker
but I found another thing, i think its a bug, 

possible user scenario: Timepicker is formatted as 24 hrs
I want to input 00:01 in the time picker, but it doesn't have a prop for default minutes and is not automatically set as 00, like the past bug of minutes

![image](https://user-images.githubusercontent.com/42717688/64238665-6cf73c00-cf31-11e9-8a74-7ad82315eea5.png)

**Comment by jtommy** [comment]
Do you mean minutes or hours? Btw you have to set "1" and not "01"

**Comment by kenichii** [comment]
Yes, its hours. ohh i see, thanks,

i think default-hours props will be needed in that scenario :)

**Comment by jtommy** [comment]
At this point you should set v-model with the default data

**Comment by kenichii** [comment]
Am I just going to initialize my v-model as new date with 0 hrs? i think it will not affect the datepicker

**Comment by jtommy** [comment]
https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters
