### ISSUE TITLE
Customize steps button

### ISSUE THREAD

**Issue by richardfeliciano** [buefy/buefy#1737]
It will be nice if we can customize class on steps button.

**Comment by VladNeacsu** [comment]
You could always but and identifier on the containing element and select the navigation buttons specific . Can you elaborate this request?

**Comment by service-paradis** [comment]
Step buttons can be styled using `.step-navigation .pagination-previous` or `.step-navigation .pagination-next`

Which kind of customization would you want to do?

**Comment by DevGoslinga** [comment]
Maybe update the documentation showing a few examples of what @VladNeacsu suggests? Love the work you have done on the stepper service-paradis looks very nice even on mobile devices I use it in production. Maybe we could add a "ref" property to the API for the navigation buttons?

**Comment by VladNeacsu** [comment]
@DevGoslinga There's no need this is vanilla CSS and VueJS which buefy doesn't interfere with
