### ISSUE TITLE
Datepicker MaxDate Issue

### ISSUE THREAD

**Issue by itsjainrishi** [buefy/buefy#1740]
**Buefy** Version: 0.8.3
**Vuejs** Version: 2.5.17

**Description:**
maxDate option isn't working as expected. A user can cycle through any date or year without any restrictions. Although a validation check can be put. But the ideal solution would be to have year list restricted to the MaxDate.

**Steps to Reproduce:**

1. Create any datepicker. And set a maxDate.
2. Select the maxDate year and then again open the Year select. 
You will see maxDateYear + 3 also available for selection (+3 considering you haven't changed range option).

**Comment by service-paradis** [comment]
When I try it with this example from the doc:
https://buefy.org/documentation/datepicker#range

Only 2019 is available. Can you create a Codepen with your issue?

**Comment by itsjainrishi** [comment]
Oops. I was passing wrong value to max-date attribute in both the cases. Sorry.

I am so stupid.

**Comment by seyfer** [comment]
One related question to this issue.
Any way to set maxDate based on minDate selected?
I need it to be dynamic, not as a static maxDate and minDate restriction. When a user selects a first date in a range, I want to limit the range by 3 months +- based on the first date selected in the range.
