### ISSUE TITLE
when including an icon in a navbar item, the text renders too close to its icon 

### ISSUE THREAD

**Issue by sugacube** [buefy/buefy#1742]
### Overview of the problem

**Buefy** version: 0.8.3
**Vuejs** version: 2.6.10
**OS/Browser**: Windows - Firefox & Chrome

### Description
If you create a navbar item with an icon in front of the text, the text is rendered too close (overlapping) to the icon.

The syntax uses for icons is the same as for icons in normal buefy dropdown menu, where they are correctly rendered.

### Steps to reproduce

1. Create a navbar with some items containing icons in front of the text:
```
	<b-navbar>
		<template slot="brand">
		. . .
		</template>
		<template slot="start">
			<b-navbar-item tag="router-link" :to="{name: 'link'}">
			<b-icon icon="heart"></b-icon>
			Item 1
			</b-navbar-item>
			<b-navbar-dropdown label="Menu">
				<b-navbar-item tag="router-link" :to="{name: 'link'}">
				<b-icon icon="heart" size="is-small"></b-icon>
				Item 2
				</b-navbar-item>
			</b-navbar-dropdown>
		</template>
		. . .
```

2. click on "Menu" (menu opens, shows "Item 2")

### Expected behavior
Text "Item 1" and "Item 2" is rendered slightly after preceding icon with a small space.

### Actual behavior
Text "Item 1" and "Item 2" is rendered overlapping or attached to the preceding icon .
This is the case both for toplevel as drop down items, and different size icons.

### Workaround

I found a workaround by including a `<span></span>` in front of the text or other tricks like including empty icons.
```
	. . .
		<b-navbar-item tag="router-link" :to="{name: 'link'}">
		<b-icon icon="heart"></b-icon>
		<span></span>Item 1
		</b-navbar-item>
	. . .
```

**Comment by jtommy** [comment]
You should wrap text into a span

**Comment by sugacube** [comment]
Thank you for responding.
If I wrap the text in a span, the dropdown doen't close any more when clicking on the text.
Putting an empty span anywhere solves the problem though.
