### ISSUE TITLE
When including a navbar dropdown in the "brand section", the dropdown is always open on mobile

### ISSUE THREAD

**Issue by sugacube** [buefy/buefy#1743]
### Overview of the problem

**Buefy** version: 0.8.3
**Vuejs** version: 2.6.10
**OS/Browser**: Windows - Firefox & Chrome

### Description
If you create a navbar dropdown inside the "brand" section of the navbar, on mobile it is shown on top as expected, but fully open in stead of being able to close/open. Also the text is rendered next to the item in stead of in a popup.

#### Rationale
bulma / buefy navbar items automatically hide on tablet or mobile. If you have 1 or 2 small dropdown menus there is however still place on a mobile to show the menu's (tablets will fit even more).
It is a workaround with bulma in this case to put the dropdown inside the "brand" section, so these will always remain on top, even on mobile.

This works perfectly for normal navbar items.

### Steps to reproduce

1. Create a navbar with some items containing icons in front of the text:
```
	<b-navbar>
		<template slot="brand">
			<b-navbar-item>
				[ your brand stuff ]
			</b-navbar-item>
			<b-navbar-dropdown label="Menu">
				<b-navbar-item tag="router-link" :to="{name: 'link'}">
				<b-icon icon="heart" size="is-small"></b-icon>
				Item
				</b-navbar-item>
			</b-navbar-dropdown>
		</template>
		<template slot="start">
		. . .
		</template>
		. . .
```

2. resize screen to tablet / mobile version

### Expected behavior
On mobile screen, dropdown "Menu" shown on top of screen which can be clicked open/close and selected.

### Actual behavior
On mobile screen, always open dropdown is shown with menu items rendered next to it.

### Remark
I'm not sure this should be classified as a but or as a feature request. Please re-classify if you desire.

**Comment by wanxe** [comment]
Yes you're right, but while we look for a solution you can control the behaviour of the mobile menu programmatically with the is-active prop.

https://buefy.org/documentation/navbar#api-view

**Comment by sugacube** [comment]
still same problem in 0.8.4
@wanxe is-active doesn't do anything when dropdown is inside "brand" in mobile mode.

**Comment by wanxe** [comment]
Hello @sugacube could you provide us an working example? Thanks.

**Comment by sugacube** [comment]
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">
</head>
<body>
	<div id="app">
		<b-navbar>
			<template slot="brand">
				<b-navbar-item href="/">[ BRAND / ICON ]</b-navbar-item>
				<b-navbar-dropdown label="Dropdown">
					<b-navbar-item>Item 2</b-navbar-item>
					<b-navbar-item>Item 1</b-navbar-item>
				</b-navbar-dropdown>
			</template>
		</b-navbar>
	</div>

	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" type="text/javascript"></script>
	<script src="https://unpkg.com/buefy/dist/buefy.min.js" type="text/javascript"></script>
	<script>new Vue({el: '#app' })</script>
</body>
</html>
```

renders like

![image](https://user-images.githubusercontent.com/16566889/65364444-22a0db00-dc12-11e9-96d5-3d82138bb252.png)

**Comment by wanxe** [comment]
@sugacube I think that is not a Buefy problem, as you can see on the following codepen
[example](https://codepen.io/jnieto/pen/qBWLmgw). Is just the Bulma CSS "problem". This slot is designed by default to put your brand, not more items inside it. We just follow the guideline of this library.

**Comment by sugacube** [comment]
i see. makes sense. i guess i'll have to report this with bulma then.

**Comment by guestisp** [comment]
Bug still exists with latests versions of bulma and buefy
