### ISSUE TITLE
FontAwesome Pro Icons not found after upgrade to 0.8.3

### ISSUE THREAD

**Issue by paramono** [buefy/buefy#1744]
### Overview of the problem

After upgrading Buefy from 0.8.2 to 0.8.3, I noticed that Vue is reporting some icons from FontAwesome pro packages as missing (although they are present in their respective packages), and they indeed are not rendered in the browser.

**Buefy** version: [0.8.3]
**Vuejs** version: [2.6.10]
**OS/Browser**: Arch Linux, Firefox 68.0.1 and Chromium 76.0.3809.132, but it's unlikely to be relevant here

### Description

I am using Buefy with Nuxt@2.9.2 and FontAwesome@5.9.0 (Pro version, so I have access to pro icons)

After upgrading Buefy from 0.8.2 to 0.8.3, I noticed that Vue is reporting some icons from FontAwesome pro packages as missing, and they indeed are not rendered in browser.

Frankly, some free icons (for example, those from free-brands-svg-icons package) worked just fine.

However, I noticed this PR https://github.com/buefy/buefy/pull/1733, cloned it and built Buefy locally from the dev branch. After installing a locally built version of Buefy, these issues with icons disappeared, and icons are now rendering just fine.

### Steps to reproduce

1. Install buefy@0.8.3
2. Add \<b-icon\> with any icon from FontAwesome pro packages. For example, I had issues with solid version of faShieldCheck, and arrow icons from buefy's pagination component weren't displayed either, although I did include them in the FontAwesome library with library.add()
3. Icons won't be rendered, and Vue will issue a warning for every missing icon.

### Expected behavior

Icons properly being rendered

### Actual behavior

Icons not rendered, warning messages issued in console.
This doesn't happen if I downgrade back to buefy@0.8.2 or install the current dev branch locally.

### Suggested actions

It seems that FontAwesome pro icons for buefy@0.8.3 are broken, and it would be nice if PR mentioned above would be released to npm registry to fix this issue.

### Other

buefy@0.8.3 issues icon missing warnings which I mentioned above, but I also get this message:

>[Vue warn]: Invalid prop: custom validator check failed for prop "size".

This message is still present both in @0.8.3 and in the dev branch. This is probably a separate issue which will be addressed in the next version, but just wanted to report it because it might be related to the changes in the Icon component. It's hard to say from this message which component this "size" prop belongs to, though.

**Comment by jtommy** [comment]
Did you take a look at https://github.com/buefy/buefy/issues/1730?

**Comment by paramono** [comment]
@jtommy 

Oh, I thought this issue is related only to duotone icons.
Will try the suggested solution, will report back.

**Comment by paramono** [comment]
@jtommy 

Yes, the proposed workaround does work! Thank you!

I wish I noticed sooner that this other issue was regarding icons in general and not just duotone icons.

**Comment by jtommy** [comment]
It was related to vue-fontawesone.
Btw it was fixed and in the next release you won't need it
