### ISSUE TITLE
Fontawesome is too big inside b-input

### ISSUE THREAD

**Issue by nakorndev** [buefy/buefy#1745]
As image I attached at top I using `<b-input icon="at">` mean on buefy and bottom I use `<span class="icon is-left">` using native bulma. That is too big and seem no way to customize.

![image](https://user-images.githubusercontent.com/5706431/64400816-18ba9c00-d098-11e9-921c-d2a71daf4244.png)

If inspect on html an icon on buefy is rendered with `fa-lg` but bulma does not.

It seem reference here.

https://github.com/buefy/buefy/blob/68ade9eeb69df672b17073f8311589477fafeeba/src/utils/icons.js#L18

Should implement a new `props` to custom icon size in `<b-input>` or change a default?

**Comment by jtommy** [comment]
You can change the default https://buefy.org/documentation/icon#custom-icon-pack

**Comment by nakorndev** [comment]
I made my work by nuxt and set `customIconPacks` and it works. However on `[icon].sizes.default` will use prop `:size` of `vue-fontawesome` component. So it won't work if ignore to set a property of `[icon].sizes.default` or set null

I ended up by set a right of `:size` prop value and use css as sample is `.fa-10x { font-size: 1rem; }` to fix this for awhile.

```
buefy: {
  defaultIconComponent: 'v-fa',
  defaultIconPack: 'fas',
  customIconPacks: {
    fas: {
      sizes: {
        'default': '10x',
        'is-small': 'xs',
        'is-medium': 'lg',
        'is-large': '2x'
      },
      iconPrefix: ''
    }
  }
}

```
