### ISSUE TITLE
Number input is not responsive on low resolutions inside 2 b-fields.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1747]
### Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: any

### Steps to reproduce

https://codepen.io/fgdfgdfgdfg/pen/KKPZrve?editors=1010
![GIF](https://user-images.githubusercontent.com/9306996/64438344-fbf28880-d0d8-11e9-8011-7b9f26e23343.gif)

### Expected behavior

Should be responsive as well as other's

### Actual behavior

Not responsive

@yxngl ping.

**Comment by service-paradis** [comment]
html have `min-width: 300px;`

Nothing is responsive below this:
![captured](https://user-images.githubusercontent.com/12817388/64453901-a1950000-d0b7-11e9-8522-e17b411f47f9.gif)

It is from the Bulma variable `$body-min-width`:
https://github.com/jgthms/bulma/blob/565af6ddd9a5607aba117dc8124f82e3dae36b3b/sass/base/generic.sass#L37

**Comment by afwn90cj93201nixr2e1re** [comment]
As you can see it's not responsive on 400px too. But idk why.

So, also any input inside grouped b-field b-field wrapper is not repsonsive at all.
![изображение](https://user-images.githubusercontent.com/9306996/64454619-77196600-d0fc-11e9-957c-c0b5cc5d28fe.png)

Check this code too.
https://codepen.io/fgdfgdfgdfg/pen/eYOyoGp?editors=1011

**Comment by afwn90cj93201nixr2e1re** [comment]
Only one workaround which was founded, that wrap input inside the first b-field, but we should have something like that,
![изображение](https://user-images.githubusercontent.com/9306996/64454722-b778e400-d0fc-11e9-92dd-9a7fb8d47087.png)

and not like that
![изображение](https://user-images.githubusercontent.com/9306996/64454749-c95a8700-d0fc-11e9-89b8-96f66b62e61c.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems like problem is 
![изображение](https://user-images.githubusercontent.com/9306996/64454955-5bfb2600-d0fd-11e9-841f-0b4b5c68efc5.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
:/
https://github.com/buefy/buefy/issues/1656#issuecomment-521159770

Lol, i did it 23 day's ago...

@service-paradis
