### ISSUE TITLE
IE11 indeterminate progress styling has extra animation

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1748]
### Overview of the problem

**Buefy** version: 0.8.3
**OS/Browser**: IE11, Edge

### Description

There is a bug with Bulma progress bar animation when using IE11 or Edge.
Ref: https://github.com/jgthms/bulma/issues/2539

A PR is made for Bulma:
https://github.com/jgthms/bulma/pull/2540

Should we wait a Bulma update? 
Should we make a temporary fix?
Should we suggest a workaround?

**Comment by afwn90cj93201nixr2e1re** [comment]
Sometimes bulma doesnt accept PR's for 2 or more years, i think you should just write wrapper inside buefy, and then disable it on pr merge.

**Comment by service-paradis** [comment]
Yeah, Bulma is ont really reactive unfortunately.
What do you think @jtommy?

**Comment by jtommy** [comment]
Ok add it but please add a comment too
