### ISSUE TITLE
Question: How do I import components and their style individually?

### ISSUE THREAD

**Issue by xperator** [buefy/buefy#1749]
Hi,
I'm new to Buefy. And I'm sorry to ask this as an "issue", but how do I add components individually, without bringing extra and global css styles?

Like I want to use the Tooltip component, but in the [documention](https://buefy.org/documentation/customization/) it says I have to do:
```scss
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
which brings all the extra css styles that I don't wan't. It completely messes up my page layout, my font sizes and everything.
Before using buefy, I used to import bulma like this :
```scss
@import "~bulma/sass/utilities/_all";
@import "~bulma/sass/form/_all.sass";
@import "~bulma/sass/elements/button.sass";
@import "~bulma/sass/elements/icon.sass";
```
This would allow me to have control and only import necessary components I need.

Is it possible to use Buefy like I explained?

**Comment by jtommy** [comment]
Please take a look at https://github.com/buefy/buefy/issues/1613.

**Comment by xperator** [comment]
I see. So I have to wait for someone to give instructions in the future.

I wish I could figure it out myself but I can't. I tried many combinations of imports but had no luck.

**Comment by xperator** [comment]
Alright.. It appears I randomly found the solution. And it was fairly simple. Thanks god! I just had to do
```scss
@import "~bulma/sass/utilities/_all";
$speed-slow: 150ms !default;
$speed-slower: 250ms !default;

@import "~buefy/src/scss/components/_tooltip.scss";
```
This way I can only import styles I need. So far I tried it with 2 different components and it worked just fine.

Still I don't understand why in the docs, it tells you to omit
```js
import 'buefy/dist/buefy.css'
```
and change it to
```scss
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
It kinda kills the purpose of omitting the first line when it's gonna import everything either way. Well yeah you would have control over the variables, but it wouldn't be a full customized solution. And that is unlike the [Bulma's docs](https://bulma.io/documentation/customize/with-node-sass/#6-add-your-own-bulma-styles) which actually shows how to fully have control over what you add and modify

Anyway, thanks for the great library! I love it!

**Comment by jtommy** [comment]
@xperator Your solution works well because tooltip is a simple component that doesn't use so much Bulma styles.
Why should you use full Buefy CSS? You cannot change variables like primary colour for example

**Comment by xperator** [comment]
I understand your point. I decided to try the table component with the same approach and it worked.
```scss
@import "~bulma/sass/elements/table.sass";
@import "~buefy/src/scss/components/_table.scss";
```
I guess so far I got away with this approach.

**Comment by jtommy** [comment]
You might help me on it. I would like to make a doc about a lite version

**Comment by xperator** [comment]
Tell me how I can help. I'm new to this so I have to play around with Buefy, try to integrate it into my existing project see how it fits and what are the caveats of my approach I showed earlier.

**Comment by jtommy** [comment]
There are complex components, for example Datepicker depends on input, dropdown, modal and select components

**Comment by service-paradis** [comment]
Maybe, the styles should be scoped into their components instead of being part of a global scss file?
This way, the tree shaking for components would also works for styles. We could keep the specific components scss files only to define variables.

**Comment by hrobertson** [comment]
I'm just creating new Vue site and evaluating a few CSS frameworks. I found Bulma then found Buefy and was about to install it but then saw `import 'buefy/dist/buefy.css'` on the Getting Started page and thought, "surely the styles are in the components..." but no! So I came here thinking someone must have raised an issue about this and there would be some sort of explanation...

**Comment by jtommy** [comment]
Buefy CSS contain the last version of bulma and Buefy components styles.
In case you want customize please check https://buefy.org/documentation/customization/

**Comment by service-paradis** [comment]
@jtommy 
Maybe we could label this issue as a potential breaking change. We could try to scope styles in their component for the next breaking release. What do you think?

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/2235

**Comment by kalnode** [comment]
Hello, 
Anyone coming across this, know that you _can_ use Bulma in a modular fashion:

For example, if you just want Bulma's table and pager:
```
@import "bulma/sass/utilities/_all.sass";
@import "bulma/sass/elements/table.sass";
@import "bulma/sass/components/pagination.sass";
```
You'll only get what you need, without affect the rest of your app styling.

[https://bulma.io/documentation/overview/modular](https://bulma.io/documentation/overview/modular)
