### ISSUE TITLE
datepicker with events - trigger custom action on date selection

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#1750]
Hi all.

I'm building a calendar component and would like to use the buefy for this as it's already used in my app.

My ideas is as follows:

Have the datepicker always expanded.
Use **events** to mark dates which have some appointments in them.
Clicking on a date would not select that date but trigger a custom method. This method should accept the date which was clicked on.

In my scenario I'd like to populate a child component with the events which are occurring on selected date. I'd add some more data to the objects in the **events** array.

I suppose this functionality could be reused in multiple different scenarios.

For this we need:

- option to disable date selection (but not hugely important)
- option to trigger custom methods when clicking on dates

My questions are, is something like this already possible and I'm missing it?
If not, how realistic is that something like this gets implemented in some reasonable amount of time?
Worse scenario, can anyone point me where in the code could something like this be implemented?

**Comment by service-paradis** [comment]
The `input` event should work for this:
https://buefy.org/documentation/datepicker#api-view

**Comment by dmcbrn** [comment]
Works perfectly, thank you very much.

Here's some example code for anybody stumbling upon this:

````

        <b-datepicker
            ...
            :input="dateSelected(date)"
            >
        </b-datepicker>
...
methods: {
      dateSelected(date) {
        console.log(date);
        console.log(String(date.getDate()) + '.' + String(date.getMonth()+1) + '.' + String(date.getFullYear()) + '.');
      }
    },
```
