### ISSUE TITLE
inputs with left and right icon

### ISSUE THREAD

**Issue by BenjaminVockenberg** [buefy/buefy#1751]
### Description
It would be nice to have the possibility to put more than one icon into an input field. For example to show a search-icon on the left and a clear-icon on the right side of the field. In some input fields are more than one icons already (Loading, Password-reveal) but they are not customizable.
In Bulma it is possible to use the "controll"-class to add those icons:

![bulma](https://user-images.githubusercontent.com/7655131/64536222-0307d980-d319-11e9-887d-5defcac22c0c.png)

### Why Buefy need this feature
With this feature you provide more customizable form elements.

Thanks a lot and best wishes

**Comment by ashimasingla20** [comment]
I will be working on this issue

**Comment by BenjaminVockenberg** [comment]
thanks a lot and good success

**Comment by service-paradis** [comment]
#2169 will make props available to customize the Input right icon
