### ISSUE TITLE
Add a section in the docs with scss variables that can be customized

### ISSUE THREAD

**Issue by service-paradis** [buefy/buefy#1755]
### Description

It would be great to have a section in the docs listing every Buefy scss variables that can be customized. Like Bulma does (https://bulma.io/documentation/customize/variables/).

### Why Buefy need this feature

The current doc (https://buefy.org/documentation/customization) is misleading because it lists only 2 variables, but there is more.

**Comment by jtommy** [comment]
It's a good idea although there aren't so many variables :)

**Comment by service-paradis** [comment]
There are around 30 defined variables in SCSS files. Not all of them can be redefined right now, but it is more than 2 ;)

Some example:

- [checkbox](https://github.com/buefy/buefy/blob/dev/src/scss/components/_checkbox.scss)
- [form](https://github.com/buefy/buefy/blob/dev/src/scss/components/_form.scss)
- [notices](https://github.com/buefy/buefy/blob/dev/src/scss/components/_notices.scss)
- [radio](https://github.com/buefy/buefy/blob/dev/src/scss/components/_radio.scss)
- [slider](https://github.com/buefy/buefy/blob/dev/src/scss/components/_slider.scss)
- [steps](https://github.com/buefy/buefy/blob/dev/src/scss/components/_steps.scss)
- [switch](https://github.com/buefy/buefy/blob/dev/src/scss/components/_switch.scss)
- [taginput](https://github.com/buefy/buefy/blob/dev/src/scss/components/_taginput.scss)
- [tooltip](https://github.com/buefy/buefy/blob/dev/src/scss/components/_tooltip.scss)

And there could be more in the future!

**Comment by jtommy** [comment]
Sure, I didn't remember all of them :D
