### ISSUE TITLE
Adapt buttons height if we use labelPosition=inside

### ISSUE THREAD

**Issue by Ridzhi** [buefy/buefy#1758]
### Overview of the problem
**Buefy** version: ^0.8.2
**Vuejs** version: ^2.6.10
**OS/Browser**: MacOS/Chrome

### Description
Different heights for button and input 

### Steps to reproduce
```
<b-field grouped>
    <b-field label="Search" label-position="inside">
            <b-input />
    </b-field>
    <b-button>Submit</b-button>
</b-field>
```

### Expected behavior

The same height

### Actual behavior

Input have more height

**Comment by service-paradis** [comment]
You are right. The problem also occurs when using field Addons.
```
<b-field label="Search" label-position="inside">
    <b-input type="search"></b-input>
    <p class="control">
        <button class="button is-primary">Search</button>
    </p>
</b-field>
```

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/pull/1761
