### ISSUE TITLE
Feature Request: Table Export (XLSX , PDF)

### ISSUE THREAD

**Issue by robertmarney** [buefy/buefy#1759]
Many table libraries include support for export of the table contents to excel, csv, pdf ie:

Datatables:

![image](https://user-images.githubusercontent.com/48888686/64713684-9147a100-d47a-11e9-8452-d52853889924.png)

Enso:

![image](https://user-images.githubusercontent.com/48888686/64713869-e2579500-d47a-11e9-971a-883e8c0708b8.png)

Vue-Materialize:

![image](https://user-images.githubusercontent.com/48888686/64714085-3b272d80-d47b-11e9-9ae6-5a41f2c3343e.png)

### Description

Buttons enabled by prop to allow for export to various formats.

### Why Buefy need this feature

Very common feature for table libraries

**Comment by service-paradis** [comment]
Personnaly, I'm not sure it is a good idea for a generic UI library. It would add dependencies which would not be useful to every user. There are also some packages who offer this kind of behavior that should work with Buefy (https://www.npmjs.com/package/vue-excel-xlsx).
