### ISSUE TITLE
Upload:  file name in slot not be updated 

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1760]
**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.10]
**OS/Browser**:

### Description
Upload:  file name in slot not be updated 

### Steps to reproduce
I use the sample code from [the Upload document](https://buefy.org/documentation/upload), 
In sample code, "file.name" is out of  b-upload  component, it work very well. 💯 
But I changed "file.name" into b-upload as slots and upload diffrent files for **several times**,
the "file.name" not show current file name forever. 

**Worked sample:** 
```
    <b-field class="file">
        <b-upload v-model="file">
            <a class="button is-primary">
                <b-icon icon="upload"></b-icon>
                <span>Click to upload</span>
            </a>
        </b-upload>
         <span class="file-name" v-if="file">
            {{ file.name }}
        </span>
    </b-field>
```

**No Worked sample:** 
```
    <b-field class="file">
        <b-upload v-model="file">
            <a class="button is-primary">
                <b-icon icon="upload"></b-icon>
                <span>Click to upload</span>
            </a>
        <span class="file-name" v-if="file">
            {{ file.name }}
        </span>
     </b-upload>
    </b-field>
```

**Comment by JMDC-SUN** [comment]
Browser: Google Chrome を更新しています（62%）
バージョン: 76.0.3809.132（Official Build） （64 ビット）
 OS: Windows10 1903

**Comment by service-paradis** [comment]
Working fine for me with the same OS/Browser...

**Comment by jtommy** [comment]
Me too
