### ISSUE TITLE
Min-Date property in range datepickers throw errors 

### ISSUE THREAD

**Issue by kabugh** [buefy/buefy#1762]
### Overview of the problem

**Buefy** version: [0.8.3]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome

### Description

I am having a datepicker which uses range property.
I would like to disable picking certain dates. Therefore I use min-date, it accidentally works, but throws multiple errors in the console.

### Steps to reproduce
I use an example "a range of dates" provided in docs: https://buefy.org/documentation/datepicker
I add "min-date" property.
It works but I get errors in the console.

### Code
```
<b-datepicker
              v-model="dates"
              icon="calendar-today"
              range
              :min-date="minDate"
            >
</b-datepicker>
```
```
data: () => ({
    dates: [new Date(), new Date()]
}),
computed: {
    minDate() {
      const today = new Date()
      return new Date(today.getFullYear(), today.getMonth(), today.getDate())
    }
  }
```
![range](https://user-images.githubusercontent.com/51855058/64857094-e70b7d00-d623-11e9-9c37-283f96c2775d.png)
### Errors in the console
```
Invalid prop: type check failed for prop "minDate". Expected Date, got Date 

found in

---> <BDatepicker>
       <BField>
Invalid prop: type check failed for prop "minDate". Expected Date, got Date 

found in

---> <BDatepickerTable>
       <BDropdownItem>
         <BDropdown>
           <BDatepicker>
             <BField>
```
![error](https://user-images.githubusercontent.com/51855058/64857092-e70b7d00-d623-11e9-8664-1ad0f7f6de51.png)
### Expected behavior

Display no errors.
### Actual behavior

Throw errors.

**Comment by jtommy** [comment]
Are you using Nuxt ?
https://github.com/buefy/nuxt-buefy/issues/36
