### ISSUE TITLE
Different Custom Table Headers

### ISSUE THREAD

**Issue by MannikJ** [buefy/buefy#1763]
I don't understand how I am supposed to define custom table headers in later versions where the header slot of the column component has been removed.

I know I can now place the header slot one level up on the table component, but then all columns get the same header, but I need to add multiple headers that differ quite a lot. 
So I somehow need to pass custom data from the columns into the global header slot and decide from there what to display. But even if that would actually work like this, I don't like that approach. Because you will end up with some funky if else logic, where you could just add the slot to the column components.
It would be more intuitive to have the header slot on the table as well as on the column component. If column slot is provided it overwrites the global.

**Comment by jtommy** [comment]
Header slot in table component is available yet

**Comment by MannikJ** [comment]
@jtommy What do you mean? The header slot exists on the table component in my version, but as I described, I don't like (or understand) how it works.

**Comment by jtommy** [comment]
In the last version there is an header slot in table column component, did you see it in the docs?

**Comment by VasiliyRusin** [comment]
I suppose a column header and table header should use for different things. For example, I have a table head and column header. But if I use them together column header doesn't show.
![image](https://user-images.githubusercontent.com/3685852/77083885-c556dc80-6a30-11ea-8124-87a236b33c86.png)

**Comment by jtommy** [comment]
Table header slot will be removed but it the same thing of table column slot

**Comment by VasiliyRusin** [comment]
@jtommy I try to say that it's really SHOULD NOT to be the same. It makes table absolutely not customizable. Now buefy does not allow me to customize the table headers. I strongly believe that the table header is not the same as the column header. (At least while we can't get access to thead tag)
