### ISSUE TITLE
Unable to use Navbar in Electron + Vue js Project

### ISSUE THREAD

**Issue by juancampuzano** [buefy/buefy#1765]
I just install the latest version of Buefy and I am getting error trying to use Navbar. If I try with a field compoment I can use it.

Error I am getting: 
![Screen Shot 2019-09-16 at 10 00 13 AM](https://user-images.githubusercontent.com/52759609/64969049-cf710600-d868-11e9-957e-343713fc9613.png)

Npm outdate:

![Screen Shot 2019-09-16 at 9 59 47 AM](https://user-images.githubusercontent.com/52759609/64969111-ed3e6b00-d868-11e9-85aa-2507b72c9c94.png)

I checked the components in the buefy dependencies in node_modules and it is not appearing.

![Screen Shot 2019-09-16 at 9 56 58 AM](https://user-images.githubusercontent.com/52759609/64968788-57a2db80-d868-11e9-8615-c30221dbf32c.png)

**Comment by jtommy** [comment]
Are you sure to use the last version?

**Comment by juancampuzano** [comment]
That was totally my mistake.

Thanks for the help
