### ISSUE TITLE
Jagged line in table

### ISSUE THREAD

**Issue by robfordww** [buefy/buefy#1767]
On the components page for Table,  "# Sandbox with custom template" table has horizontal row lines that are jagged between "Last name" and "Date"

![image](https://user-images.githubusercontent.com/24738409/64982428-76cc5800-d8be-11e9-8420-9df6b62e683d.png)

**Comment by jrandalldemllo** [comment]
Also can see it occurring with the Detailed rows & Async Data examples. The former again in the Dates column but Async Data with the Vote Average column. All are using tags. 
However I have seen this occurring in my own project with the chevron cell in a detailed row.

**Comment by robfordww** [comment]
I can confirm that is looks like a Chrome issue. 
Even more obvious when you show the boarders:
![image](https://user-images.githubusercontent.com/24738409/65820874-6f963a00-e22e-11e9-86f5-8c6a6e488290.png)

**Comment by service-paradis** [comment]
Are you able to reproduce the issue using Bulma table wthout Buefy?

**Comment by afwn90cj93201nixr2e1re** [comment]
its Hidden css issues at chrome, should be closed.
