### ISSUE TITLE
Unable to add class to input

### ISSUE THREAD

**Issue by danielclariondoor** [buefy/buefy#1777]
### Overview of the problem

**Buefy** version: 08.3
**Vuejs** version: 2.6.6
**OS/Browser**: Mac OS mojave / chrome

### Description

CSS class cannot be applied to datepicker, making it impossible to add error classes, for example.

### Expected behavior

Class is added to input like all other Buefy inputs.

### Actual behavior

Class is added to some div

**Comment by jtommy** [comment]
Datepicker shows only input, what do you want customize ?

**Comment by danielclariondoor** [comment]
I want to customize the class on the <input>.

**Comment by jtommy** [comment]
You simply add a class to b-datepicker and it will applied to internal b-input component

**Comment by danielclariondoor** [comment]
What I meant it, in the case of <b-input> i can add "custom-class" to apply classes to the <input> element itself, but there is no way to do this for datepicker, autocomplete, and probably others.
