### ISSUE TITLE
H1 tag centered in b-step-item is not aligned with step icon

### ISSUE THREAD

**Issue by Benjamin-Lee** [buefy/buefy#1780]
### Overview of the problem

**Buefy** version: 0.8.3
**Vuejs** version: 3.8.4
**OS/Browser**: Chrome and Safari

### Description

Centered h1 tag does not align with centered step.

### Steps to reproduce

Steps.vue:
```html
  <div class="container">
    <b-steps>
      <b-step-item label="Determine Frequencies" icon="chart-bar">
        <h1 class="title has-text-centered">Hi</h1>
        <CalculateFreqs />
      </b-step-item>
      <b-step-item label="Protein Target" icon="target"></b-step-item>
      <b-step-item label="Generate DNA" icon="dna"></b-step-item>
    </b-steps>
  </div>
```

CalculateFreqs.vue:
```html
  <b-tabs position="is-centered" type="is-toggle">
    <b-tab-item label="Paste FASTA" icon="content-paste"></b-tab-item>
    <b-tab-item label="Upload FASTA" icon="file-document">
      <b-field label="Message">
        <b-input maxlength="200" type="textarea"></b-input>
      </b-field>
    </b-tab-item>
    <b-tab-item label="Videos" icon="video"></b-tab-item>
  </b-tabs>
```

### Expected behavior

The h1 tag should be centered directly below the target icon.

### Actual behavior

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/13618205/65291638-5270b580-db22-11e9-9abf-7caa156de0ed.png">

**Comment by yxngl** [comment]
It seems to me `flex-basis: 1em` of non-1st steps causes `step-item` unequal in width. Any reason for that style? @service-paradis

**Comment by service-paradis** [comment]
Thanks @yxngl, you are right about `flex-basis`. The style for this component was inspired from https://wikiki.github.io/components/steps/.

I will take a look at this to see if there is any reason for it.

**Comment by Benjamin-Lee** [comment]
Any news on this?

**Comment by service-paradis** [comment]
For the moment, there is a workaround you ca use until I made a fix:
```
.b-steps .steps .step-items .step-item {
  flex-basis: 0!important;
}
```
**OR**
```
.b-steps .steps .step-items .step-item {
  flex-basis: 1em!important;
}
```
