### ISSUE TITLE
Unable to navigate on mobile device

### ISSUE THREAD

**Issue by sergpy** [buefy/buefy#1784]
I use buefy site on Android device (OS ver. 8, google chrome)
When I click on dropdown navbar menu link, the menu panel hide, and link click ignored,

**Comment by solher** [comment]
Same here. I've been on it the whole afternoon but it may be coming from a bug then :)

**Comment by jtommy** [comment]
What link? For me it's ok

**Comment by solher** [comment]
Haha sorry. So to be more precise:

```html
<template>
  <b-navbar wrapper-class="container" fixed-top>
    <template slot="end">
      <b-navbar-item tag="div">
        <router-link :to="{ name: 'login' }">
          Log in
        </router-link>
      </b-navbar-item>
    </template>
  </b-navbar>
</template>
```

In this case for example, it behaves a bit funky for me.

The link works in desktop mode. Then when I switch to mobile, it works a bit (one or two clicks) and then it stops working forever. I have to reopen the window in incognito mode to get the link to work again.

As described by @sergpy, I click on the link, the menu panel hides but nothing happens.

**Comment by solher** [comment]
Update: I actually got it to work by downgrading to 0.8.3. It looks like a 0.8.4 regression.

**Comment by jtommy** [comment]
Fix #https://github.com/buefy/buefy/commit/5ce5a13b9811c9889d76f0e1a3e07c1073d8467d

**Comment by solher** [comment]
Thanks for the awesome work! 💪

**Comment by sergpy** [comment]
thank  all !
