### ISSUE TITLE
<b-select> broken in Safari 13?

### ISSUE THREAD

**Issue by bereciartua** [buefy/buefy#1785]
Just updated Safari to version 13 and each time I click a `<b-select>` component the browser get the beach ball of death... Using Chrome everything is just fine, any idea what could be happening?

**Comment by bereciartua** [comment]
Sorry, seems like it's a bug in Bulma :(
https://github.com/jgthms/bulma/issues/2626

**Comment by service-paradis** [comment]
@jtommy 
Maybe we could add the workaround fix `text-rendering` until Bulma fix the problem?

**Comment by bereciartua** [comment]
I fixed it on my project by adding the variable `$body-rendering: auto`. I don't know if it makes sense to add this to Buefy (ideally that change should be focused only to Safari v13 right?).
