### ISSUE TITLE
We need more functional components

### ISSUE THREAD

**Issue by Neo-Zhixing** [buefy/buefy#1789]
# Description

A lot of the components in Buefy could be converted into functional components, including Button, Icon, NavBar, Tag, and pretty much all other stateless components.

### Why Buefy need this feature

> With functional components, you get the organizational, DRY benefits of a component, without the overhead of Vue’s reactivity system. This can improve your app’s performance.

Functional components are also used in other UI libraries, including bootstrap-vue.

Buefy, being a UI library based on Bulma, a CSS library built with the philosophy of simplicity and "dryness" in mind, should also try everything to keep the performance overhead minimal.

**Comment by hoquangthaiholy** [comment]
I agree with this opinion. I also used Navbar only HTML and toggle by variables. No need to add more components like this.

**Comment by jtommy** [comment]
@Neo-Zhixing yes, you're right
@hoquangthaiholy I thought as you but we received many requests and so we added it

**Comment by service-paradis** [comment]
Would need to update some dependencies in order to use them properly with `<template>`. The current version of `vue-loader` does support functional with render function only:
> [vue-loader] Tag.vue: functional components are not supported with templates, they should use render functions.

**Comment by Neo-Zhixing** [comment]
What is blocking the update of `vue-loader`? Would love to see that updated soon, so that I can start to make pull requests 😀

**Comment by jtommy** [comment]
@Neo-Zhixing I've just updated to 13.1.0 👍

**Comment by Neo-Zhixing** [comment]
Are we 13.1.0 yet? I just found that vue-loader was still specified to be 12.1.0 in `package.json`
Ideally, can we upgrade vue-loader to the most recent version?

**Comment by jtommy** [comment]
I upgraded a month ago but it broke something.
We need to test all components before to upgrade

**Comment by Neo-Zhixing** [comment]
An alternative would be using JSX for components that can be made functional. It could in fact be easier this way.

**Comment by jtommy** [comment]
No I don't like jsx

**Comment by bender-a** [comment]
I just made a [pr for the upgrade](https://github.com/buefy/buefy/pull/2275) of vue, vue-loader, vue-template-compiler & vue-router

**Comment by Tofandel** [comment]
Functional components have been removed in vue3 as they don't offer any performance benefit anymore

This issue can be closed

**Comment by jtommy** [comment]
Yes, we'll be removed the support in order to make a only one version.
