### ISSUE TITLE
Feature Request: Custom icon fonts

### ISSUE THREAD

**Issue by AliLozano** [buefy/buefy#179]
**Buefy** version: 0.4.5
**Vuejs** version: 2.4.1
### Description

Now, there are only two icon fonts support, FontAwesome and MDI, ¿there are way to user use their custom fonts? My pull request was rejected, I can make other pull request, but I need know how it should be.

### Steps to reproduce
Components that uses b-icon inside, only get icon name, and it is concatenated with fa or showed with mdi format, there are a lot of icon fonts and now there are no way to use a custom icon with this.

This: `<b-input type="text" icon="edit"></b-input>`

Include a icon with `<i class="fa fa-edit"></i>` or `<i class="mdi">edit</i>`

### Expected behavior

This: `<b-input type="text" icon="edit"></b-input>`

Include a icon with `<i class="any_custom_prefix-edit"></i>`

### Actual behavior

Now there are two types of icons, user icons(for example de input icons) and internal icons(icons that are needed by buefy). @rafaelpimpa suggest use a svg to internal fonts and `b-icon` to other icons, we have to consider that if we only use svg to internal icons and cant' be customized it could break design(Inconsistency between user icons and internal icons), besides increment css file with a svg when I dont want use buefy default icons. 

### Solution 1:
Follow using packages:
- Create configuration to add new packages [{ packname, prefix, style(class_style[fa] vs content_style[mdi]) }].
- Convert internal icons to use svg.
- Add optional parameter to customize internal icons.

Example:

```Vue.use(Buefy, { moreFontPackages: {package1: {} ...} });```

### Solution 2:
Don't define icons packages.
- Create a configuration to use a package that not add a prefix, using `<b-icon icon="custom_prefix-edit"></b-icon>` or `<b-icon icon="fa fa-edit"></b-icon>`.
- To back compatibility, we have to leave defaultIconPack, but deprecate it.
- Convert internal icons to use svg, and leave user override icons overrides css classes.
* This way doesn't support mdi format (although there are a mdi style based in class)

Accept suggests..

**Comment by rafaelpimpa** [comment]
Hey @AliLozano sorry for the delay, the problem with that PR was the internal icons, here's the deal. I'm gonna work on those SVG internal icons I talked about and then we can add more prefix/sufix for the ``b-icon``.

**Comment by schmod** [comment]
It'd also be great to include support for the community-provided icons at
https://materialdesignicons.com/

**Comment by jtommy** [comment]
@schmod PRs are welcome!

**Comment by schmod** [comment]
@rafaelpimpa Have you given any thought about how you'd like to implement SVG icons?  Seems like those are going to require a (significantly) different set of considerations than the existing font-based icons.

**Comment by AliLozano** [comment]
I suggest to work with fontello for internal icons, it allows add new icons easly, and keep it with versions using a config file.

https://css-tricks.com/fontello-past-future-icon-font-service/

**Comment by rafaelpimpa** [comment]
@schmod I'm gonna use IcoMoon or Fontello probably, and keep all of them in a single file

**Comment by cihanzengin** [comment]
Here is not possible to add some custom font icons to **icon=""** property? eg font icon code or class of font icon which i choose to use in my project? 

```
<b-field>
                      <b-input
                          type="password"
                          :value="password"
                          password-reveal
                          placeholder="Password"
                          icon=""
                          required>
                      </b-input>
                  </b-field>
```
