### ISSUE TITLE
b-steps should provide a slot for overriding navigation

### ISSUE THREAD

**Issue by cypressious** [buefy/buefy#1795]
### Description

Please consider providing a slot in `b-steps` to override the navigation. Ideally, the slot would provide as scope

- callbacks to navigate back/forward
- validation state of the previous/next steps:
  - is the step available (i.e. is the current step the first/last one)
  - is the step enabled?

### Why Buefy need this feature

This would make implementing custom navigation for `b-steps` easier without the need to implement the step validation logic twice.

**Comment by jtommy** [comment]
@service-paradise what do you think about it? Steps was a your creation :)

**Comment by service-paradis** [comment]
Yep, will try to make a PR soon :)

**Comment by service-paradis** [comment]
Done!

@cypressious Would love to have your feedback about this [PR](#1864)!
