### ISSUE TITLE
How to disable Analytics?

### ISSUE THREAD

**Issue by daltonrooney** [buefy/buefy#1803]
I was very confused when I realized that this library was loading VueAnalytics on the project I am developing, with someone else's UA agent. I consider this a major privacy violation, and I couldn't find any documentation or configuration option to disable it. As someone working on projects that are privacy sensitive and GDPR compliant, I need to fork Buefy and disable that feature completely. 

I appreciate all the work that goes into building and maintaining a top-notch open source package like Buefy and it has saved me a lot of time, but this information needs to be disclosed and _opt-in only_. I'm sure a lot of people are using this library and don't realize how their information is being used.

**Comment by jtommy** [comment]
What?? We are using analytics only in the docs project. The library doesn't have dependencies except of Bulma

**Comment by service-paradis** [comment]
`VueAnalytics` is part of the `devDependencies` and is only used for the Buefy Documentation.

`VueAnalytics` is not part of the package and will never be loaded in any projects using Buefy properly.

**Comment by daltonrooney** [comment]
Oh no, I'm so embarrassed. I somehow had my inspector open on the Buefy doc site instead of _my_ project. Then when I did a quick search of the Buefy repo and saw the vue-analytics dependency I freaked out. 

Going to go join the Patreon now to support this project and Bulma as well. Thanks for your work.
