### ISSUE TITLE
b-upload won't expand to full width

### ISSUE THREAD

**Issue by Benjamin-Lee** [buefy/buefy#1804]
### Overview of the problem

**Buefy** version: 0.8.4
**Vuejs** version: 2.6.10
**OS/Browser**: Safari 12.1.2

### Description

Unable to create full width upload box

### Steps to reproduce

Use the following component:
```vue
<template>
  <div>
    <b-field expanded>
      <b-input type="textarea"></b-input>
    </b-field>
    <h4 class="title is-4 has-text-centered">or</h4>
    <b-field>
      <b-upload v-model="dropFiles" multiple drag-drop expanded>
        <section class="section">
          <div class="content has-text-centered">
            <p>
              <b-icon icon="upload" size="is-large"></b-icon>
            </p>
            <p>Drop your files here or click to upload</p>
          </div>
        </section>
      </b-upload>
    </b-field>
    <div class="tags">
      <span v-for="(file, index) in dropFiles" :key="index" class="tag is-primary">
        {{file.name}}
        <button class="delete is-small" type="button" @click="deleteDropFile(index)"></button>
      </span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PasteOrUpload',
  data() {
    return {
      dropFiles: [],
    }
  },
  methods: {
    deleteDropFile(index) {
      this.dropFiles.splice(index, 1)
    },
  },
}
</script>

<style>
</style>
```

### Expected behavior

The upload box will be the same width as the textarea.

### Actual behavior

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/13618205/65809596-e2d77780-e16c-11e9-8be4-4616ebee4ed3.png">

**Comment by jtommy** [comment]
You have to set width: 100% to `upload-draggable` and `upload` classes
I could add it in the next breaking changes version

**Comment by dhritzkiv** [comment]
Would supporting the `expanded` attribute like on many of the other fields make sense?
