### ISSUE TITLE
Horizontal multiselect

### ISSUE THREAD

**Issue by Benjamin-Lee** [buefy/buefy#1805]
### Description

Like [this](https://buefy.org/documentation/radio#radio-button) but allowing selection of more than one item. 

### Why Buefy need this feature

There's currently no easy way to select more than one item listed horizontally.

**Comment by Benjamin-Lee** [comment]
See [here](https://bootstrap-vue.js.org/docs/components/button) for a Bootstrap equivalent of what I'm asking for.

**Comment by jtommy** [comment]
Did you see it https://buefy.org/documentation/checkbox#checkbox-button?
