### ISSUE TITLE
Autocomplete as replacement for select input

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#1806]
I'd like for my selects to have search functionality so I'm trying to replace them with autocomplete.

This is my data:

```
data() {
 return {
    books: [
             { id: 1, title: 'Frist title' },
             { id: 2, title: 'Second title' }, 
             //and so on..
          ]
```

I'd like for my autocomplete to use a model `book` but to display the title of the book, not the ID and I can't figure it out. This is what's working:

```
<b-autocomplete
    ref="autocomplete"
    :data="books.map(b => b.title)"
    @select="option => book = books.filter(b => b.title === option)[0].id">
</b-autocomplete>
```

But I lose sync this way.
Is there a way to search the array of objects by name, but in the background save the option as that object's ID?

Edit:

Actually this above is not working. It get's listed properly but the search is not working.

**Comment by jtommy** [comment]
You have to set the original object array as data prop and add field prop or a slot to show only title field.
Take a look https://buefy.org/documentation/autocomplete#object-array
