### ISSUE TITLE
Datepicker - allow displaying of multiple months at the same time

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#1807]
It would be neat if we could enable displaying multiple months in a row instead of single month like it's the case now.

Rough spec (1st draft):

This would only affect the month element of the datepicker.
There should be a property to define number of months displayed ahead of current month.
There should be a property to define number of months displayed behind the current month.
There should be an option to attach a css class to future and past months so we could hide/show them depending on the screen size. Maybe the library could do this automatically but then agian, someone might want to have horizontal scroll.
There should be option to choose whether to stack months horizontally or vertically.

Something like the image below but with a bit more flexibility (months behind and ahead)

![MultipleMonths](https://user-images.githubusercontent.com/40859618/65813849-a93d5580-e1da-11e9-94e3-80dd44ad432e.png)

**Comment by jtommy** [comment]
No plan about it at the moment
