### ISSUE TITLE
b-navbar-dropdown is ignoring is-arrowless class

### ISSUE THREAD

**Issue by jimmyangel** [buefy/buefy#1810]
### Overview of the problem

**Buefy** version: [0.8.3]
**Vuejs** version: [2.6.10]
**OS/Browser**: MacOS 10.14.6, Chrome 77.0.3865.75

### Description

```<b-navbar-dropdown class="is-arrowless" label="XYZ">```

Still shows an arrow on the dropdown menu item.

Looking at the Buefy component NavbarDropdown.vue, there is no prop defined for 'arrowless'. There should be a prop that adds the class 'is-arrowless' to the element ```<a class="navbar-link" ...```  If I add the class to this element using the chrome 'elements' tool, the arrow indeed disappears.

### Expected behavior

I expect the arrow on the dropdown item to disappear when 'is-arrowless' is used, as described in the documentation.

### Actual behavior

Arrow stays

------

Thank you

**Comment by jtommy** [comment]
You have to update to 0.8.4 and add arrowless prop to NavbarDropdown component
