### ISSUE TITLE
Extend tag input no longer works on 0.8.4

### ISSUE THREAD

**Issue by cdekok** [buefy/buefy#1812]
### Overview of the problem

**Buefy** version: [0.8.4]
**Vuejs** version: [2.6.10]

### Description

Importing the tag input and extending it no longer works

```
import { Taginput } from 'buefy/dist/components/taginput'
```

Taginput is undefined in 0.8.4 but still works on 0.8.3

### Steps to reproduce

```
import { Taginput } from 'buefy/dist/components/taginput'
console.log(TagInput)
```
### Expected behavior

The TagInput to be exported

### Actual behavior

The tag input component is not exported

**Comment by jtommy** [comment]
Did you try importing it from buefy/src ?

**Comment by cdekok** [comment]
No I didn't I can try what it does but dependencies from node_modules won't be picked up by the build system.
In the generated js in distress it's missing an export which was in 0.8.3 now it only exports a plugin.

**Comment by jtommy** [comment]
I removed it because there was an issue using individual imports

**Comment by cdekok** [comment]
Ah ok what issue was there? and is there an alternative to extending components?

**Comment by jtommy** [comment]
@cdekok using vue-cli it looks ok, what's your code ?

**Comment by cdekok** [comment]
I am using parcel 1.11.0 the full stack trace is.

```
[1:31:00 PM]: 🚨  /node_modules/buefy/src/components/icon/Icon.vue: v-else used on element <component> without corresponding v-if.
[1:31:00 PM]:     at VueAsset.compileTemplate (/node_modules/parcel-bundler/src/assets/VueAsset.js:152:15)
    at VueAsset.postProcess (/node_modules/parcel-bundler/src/assets/VueAsset.js:100:26)
    at Pipeline.processAsset (/node_modules/parcel-bundler/src/Pipeline.js:90:31)
````

**Comment by karlisup** [comment]
Hi,
I am having a similar issue. After updating to v0.8.4 I am getting errors when trying to extend the components.  The approach of extending the Buefy component doesn't work anymore. 
```
<template><div>
    <b-table :data="this.data" :columns="this.columns"> </b-table>
    My extension to the table here
</div></template>

import { Table as BTable } from "buefy/dist/components/table"
export default {
  name: "mytable",
  components: { "b-table": BTable }
}
```

This returns error:
`Unknown custom element: <b-table> - did you register the component correctly?`

**Comment by jtommy** [comment]
@cdekok @karlisup I'm working on it, a fix will be available in the upcoming release.

**Comment by jtommy** [comment]
@cdekok for example: `import { BTaginput } from 'buefy/dist/esm/taginput'`

**Comment by ydylla** [comment]
Hi @jtommy,
I think this issue is not fixed.
Your commit https://github.com/buefy/buefy/commit/56c78dbd27f5c8413d8520944535d5cc8efae554 missed the Taginput component.
All other components have a export section but taginput is only exported as plugin:
https://github.com/buefy/buefy/blob/dev/src/components/taginput/index.js#L13

**Comment by jtommy** [comment]
@ydylla you're right, fixed!
