### ISSUE TITLE
Router-link inside burger menu fails on Firefox Android

### ISSUE THREAD

**Issue by thebignet** [buefy/buefy#1813]
### Overview of the problem

**Buefy** version: 0.8.4
**Vuejs** version: 2.6.10
**OS/Browser**: Firefox Android (works on Firefox MacOS)

### Description

Router-link does not trigger route change inside burger menu

### Steps to reproduce

Add a `b-navbar-item` with a `router-link` like so inside a start slot.

```
        <template slot="start">
          <b-navbar-item tag="router-link" :to="{ path: '/day/1' }">Day 1</b-navbar-item>
          <b-navbar-item tag="router-link" :to="{ path: '/day/2' }">Day 2</b-navbar-item>
          <b-navbar-item tag="router-link" :to="{ path: '/day/3' }">Day 3</b-navbar-item>
        </template>
```

### Expected behavior

On clic on `Day 2` menu item, navigation should go to `/#/day/2`.

### Actual behavior

Burger menu closes but there is no navigation change. Two events seem to be registered on `b-navbar-items`.

Please note that this works on Firefox MacOS but not on Firefox Android. Also, when links are not in a burger menu (`brand` for example), links work on Firefox Android.

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/1784

**Comment by thebignet** [comment]
I wasn't able to find this issue ! Thanks !
