### ISSUE TITLE
Wrong sort-icon on b-table

### ISSUE THREAD

**Issue by EJGamer21** [buefy/buefy#1814]
### Overview of the problem

**Buefy** version: [0.8.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Ubuntu 19/Google Chrome

### Description

Not showing correct icon pack for the table when it's on mobile viewport.

### Steps to reproduce

1. Step 1: Create a table.
2. Step 2: Define `icon-pack="fas"` prop for the table.
3. Step 3: Define `mobile-cards` prop for the table.

### Expected behavior
The table should shows the specified `icon-pack`.

### Actual behavior
The table shows the default `icon-pack`, which it's mdi (Material Design).

### Code
Table definition
`<b-table
        :data="(isEmpty) ? [] : users"
        :loading="isLoading"
        :per-page="perPage"
        paginated
        striped
        hoverable
        mobile-cards
        :default-sort="['fecha_creacion', 'desc']"
        icon-pack="fas"
        aria-next-label="Next Page"
        aria-previous-label="Previous Page"
        aria-page-label="Page"
        aria-current-label="Current Page"
      >
`

### Images
![Screenshot from 2019-09-30 09-57-36](https://user-images.githubusercontent.com/18016256/65885540-d9b2fa00-e368-11e9-9ed3-b9dc5e141800.png)

![Screenshot from 2019-09-30 09-58-53](https://user-images.githubusercontent.com/18016256/65885652-00713080-e369-11e9-9c60-e25518457730.png)

![Screenshot from 2019-09-30 10-00-39](https://user-images.githubusercontent.com/18016256/65885803-3b736400-e369-11e9-961e-5a3c6ba39891.png)

**Comment by service-paradis** [comment]
Good catch, you are right! The mobile version for the table is not using the icon pack from the table props.
