### ISSUE TITLE
B-Icon does not always pass a size parameter to FontAwesome components

### ISSUE THREAD

**Issue by holytrashcan** [buefy/buefy#1816]
**Issue:**
When using FontAwesome components, such as via _vue-fontawesome_ or _nuxt-fontawesome_, a `size` parameter is not always passed from the `<b-icon>` component.

Specifically, _vue-fontawesome_ requires that the icon component receives a `size` parameter equal to one of the following:

`['lg', 'xs', 'sm', '1x', '2x', '3x', '4x', '5x', '6x', '7x', '8x', '9x', '10x']`

and will throw a prop validation error if the `size` property is not equal to one of these. However,  `<b-icon>` will set `size=""` on a FontAwesome component whenever the `<b-icon>` size is equal to `"is-small"`, by using the default sizes defined in the 'utils/icons.js' file.

**Recommended Fix:**
In 'utils/icons.js', change the following:

```js
const faIcons = () => {
    const faIconPrefix = config && config.defaultIconComponent ? '' : 'fa-'
    return {
        sizes: {
            'default': faIconPrefix + 'lg',
            'is-small': '',
            'is-medium': faIconPrefix + '2x',
            'is-large': faIconPrefix + '3x'
        },
        ...
    }
}
``` 
to:
```js
const faIcons = () => {
    const faIconPrefix = config && config.defaultIconComponent ? '' : 'fa-'
    return {
        sizes: {
            'default': faIconPrefix + 'lg',
            'is-small': faIconPrefix + '1x',
            'is-medium': faIconPrefix + '2x',
            'is-large': faIconPrefix + '3x'
        },
        ...
    }
}
``` 

Similar to [https://github.com/buefy/buefy/issues/1434](https://github.com/buefy/buefy/issues/1434).

**Comment by service-paradis** [comment]
Will be fixed in the next release (https://github.com/buefy/buefy/pull/1788).

Duplicate from #1786 and #1768
