### ISSUE TITLE
navbar close-on-click misbehaving on iOS

### ISSUE THREAD

**Issue by jimmyangel** [buefy/buefy#1817]
### Overview of the problem

**Buefy** version: [v0.8.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: 
* iOS 12.4.1, both Safari and Chrome 76.0.3809.123 
* iOS 10.3.3, both Safari and Chrome 71.0.3578.89

BTW, I am also using Gridsome 0.7.6 static site generator.

### Description

When using close-on-click true (default setting), on iOS, the mobile menu closes without following the menu selection touched, i.e., page stays without navigation and menu closes immediately. It seems as if the touch event is being trapped and not propagated to the menu element. 

It works fine on desktop browsers, even with Chrome touch simulator.

Also, when using  ```:close-on-click="false"``` the menu works as expected.

### Steps to reproduce

Here is the code I am using:

```
    <b-navbar>
      <template slot="brand">
        <b-navbar-item tag="a" href="/">
          <g-image width="140" src="~/assets/images/librorojo.png" />
        </b-navbar-item>
      </template>
      <template slot="end">
        <b-navbar-item tag="a" href="/about">
          ACERCA DE
        </b-navbar-item>
        <b-navbar-item>
          MÉTODOS
        </b-navbar-item>
        <b-navbar-dropdown :arrowless="true" label="MAS INFORMACIÓN">
            <b-navbar-item>
                Unidades de paisaje
            </b-navbar-item>
            <b-navbar-item>
                Casos de estudio
            </b-navbar-item>
        </b-navbar-dropdown>
        <b-navbar-item tag="a" href="/contact">
          CONTACTO
        </b-navbar-item>
        <b-navbar-dropdown :arrowless="true" label="COMPARTIR">
            <b-navbar-item>
              <font-awesome :icon="['fab', 'facebook']"/>&nbsp;Facebook
            </b-navbar-item>
            <b-navbar-item>
              <font-awesome :icon="['fab', 'twitter']"/>&nbsp;Twitter
            </b-navbar-item>
        </b-navbar-dropdown>
      </template>
    </b-navbar>
```

### Expected behavior

I expect the menu to be closed but the menu selection link needs to be followed as well.

### Actual behavior

Mobile menu closes without following the menu selection link.

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/1784

**Comment by jimmyangel** [comment]
Ha! You are awesome! Thank you!
