### ISSUE TITLE
Buefy select not working in Safari

### ISSUE THREAD

**Issue by MartinTuroci** [buefy/buefy#1819]
### Overview of the problem

**Buefy** version: 0.8.4
**Vuejs** version: 2.6.10
**OS/Browser**:  macOs Mojave 10.14.6/ Safari 13.0.1 (14608.2.11.1.11)

### Description

b-select component freezes browser

### Steps to reproduce

1. Go to https://buefy.org/documentation/select
2. Try to open any 

### Expected behavior

Select should open.

### Actual behavior

Browser is frozen due to infinite loop.

**Comment by service-paradis** [comment]
Duplicate from:
https://github.com/buefy/buefy/issues/1785
https://github.com/jgthms/bulma/issues/2626

Will be fixed in the next release from this PR:
https://github.com/buefy/buefy/pull/1800
