### ISSUE TITLE
Error in console when deploy docs in server

### ISSUE THREAD

**Issue by alvaaz** [buefy/buefy#1823]
### Overview of the problem

**Buefy** version: [0.8.4]
**Vuejs** version: [2.5.13]
**OS/Browser**:  Mac 10.14.4

### Description

Problems to correctly view the documentation

### Steps to reproduce

1. git clone repo [buefy](https://github.com/buefy/buefy/)
2. yarn and then yarn build
3. all files in dist-docs generated upload to FTP.
4. blank site with console errors

### Expected behavior

see the documentation correctly generated

### Actual behavior

blank site with console errors

```
TypeError: "e.meta.subtitle is undefined"
    a guards.js:6
    updateRoute vue-router.esm.js:1673
    updateRoute vue-router.esm.js:1672
    transitionTo vue-router.esm.js:1580
    confirmTransition vue-router.esm.js:1658
    r vue-router.esm.js:1536
    r vue-router.esm.js:1543
    ie vue-router.esm.js:1547
    confirmTransition vue-router.esm.js:1650
    r vue-router.esm.js:1536
    r vue-router.esm.js:1543
    r vue-router.esm.js:1543
    ie vue-router.esm.js:1547
    confirmTransition vue-router.esm.js:1647
    transitionTo vue-router.esm.js:1579
    init vue-router.esm.js:2175
    beforeCreate vue-router.esm.js:446
    VueJS 3
    <anonymous> main.js:97
    <anonymous> app.0dc480adca73e7c2b2d9.js:2661
    Webpack 3
vue.esm.js:1717:12
TypeError: "l is undefined"
    render vue-router.esm.js:61
    VueJS 5
    render App.vue:6
    VueJS 18
    <anonymous> main.js:107
vue.esm.js:1717:12
```

[Screenshot](https://i.imgur.com/8tMYJXVl.png)

**Comment by jtommy** [comment]
I didn't try the current dev branch but it was on when I made the last release

**Comment by alvaaz** [comment]
I didn't try the current dev to launch production but it has this problem. In development environment this problem doesn't exist.

**Comment by jtommy** [comment]
Did you try running only build:docs ?

**Comment by alvaaz** [comment]
I've found my problem. I uploaded the files in a folder **buefy** inside the server;`www.example.com/buefy`. The routes put slash at the beginning, as `src=/static` it redirect to the root of the server and not in the current folder; `www.example.com/static`.
