### ISSUE TITLE
Can't click navbar items in hamburger menu on Android from v0.8.4

### ISSUE THREAD

**Issue by pedantic-git** [buefy/buefy#1824]
### Overview of the problem

**Buefy** version: 0.8.4
**Vuejs** version: 2.6.10
**OS/Browser**: Android 10/Chrome

### Description

Since version v0.8.4 of buefy, I can no longer click the links in the navbar on Android Chrome when they are collapsed to a hamburger menu. Clicking on an item causes the menu to close without taking the @click action of the item.

My device is a Google Pixel 2.

Behaviour is fine (as expected) on desktop (Linux) Chrome.

Behaviour was also fine in v0.8.3.

I suspect this might be related to #1741 / 0513989 

### Steps to reproduce

1. Visit my app at https://wdil.app/ on an Android device with a narrow-enough screen for the dropdown to appear in the hamburger menu.
2. Open the hamburger menu
3. Attempt to click on "log in" or "sign up"

### Expected behavior

The `@click` action runs. These are `nuxt-link` (a child of `router-link` components so they should take you to the relevant page using the Vue router).

### Actual behavior

Hamburger menu closes and `@click` action is not run. 

Let me know if it's not an obvious solution and I can provide a simpler fiddle that reproduces the issue. Thanks for your help!!

**Comment by jtommy** [comment]
Yea it's related to that issue, soon a new release

**Comment by pedantic-git** [comment]
Hi @jtommy - thanks. Is there somewhere I can track progress? Another issue I missed?

**Comment by jtommy** [comment]
Unfortunately you have only to wait the next release
