### ISSUE TITLE
Passing `autocomplete` attr to `<b-input>` doesn't work

### ISSUE THREAD

**Issue by pedantic-git** [buefy/buefy#1825]
### Overview of the problem

**Buefy** version: 0.8.4
**Vuejs** version: 2.6.10
**OS/Browser**: N/A

### Description

Passing the `autocomplete` attribute to the `<b-input>` component doesn't override it - it's always set to the value of `config.defaultInputAutocomplete`.

I think this could be fixed just by adding `autocomplete` as a named prop to the component, because there's already a line saying:

```js
newAutocomplete: this.autocomplete || config.defaultInputAutocomplete,
```

### Steps to reproduce

Add this to a component:

```vue
<b-input
  type="password"
  autocomplete="new-password"
/>
```

### Expected behavior

The rendered HTML should be an `<input type="password" autocomplete="new-password" />`

### Actual behavior

The rendered HTML is actually `<input type="password" autocomplete="on" />`

**Comment by jtommy** [comment]
I cannot reproduce it https://codepen.io/jtommy/pen/zYYOEmQ?&editable=true&editors=101.
What's wrong ?

**Comment by pedantic-git** [comment]
Hi @jtommy - I guess it only applies to types where there is a default? In your pen if you add `type="password"` you'll see buefy renders it as `autocomplete="off"` instead of `autocomplete="test"`.

**Comment by jtommy** [comment]
It applies to all types different from textarea

**Comment by pedantic-git** [comment]
Here's my fork of your pen with that attribute added: https://codepen.io/pedantic-git/pen/zYYOPvY?&editable=true&editors=101

For me that HTML has rendered as `autocomplete="off"` (Chrome)

**Comment by pedantic-git** [comment]
Oh, my fault. It's the LastPass extension that was rewriting it, not buefy. Please close this!
