### ISSUE TITLE
Checked rows is not reset when the data is refreshed

### ISSUE THREAD

**Issue by cdekok** [buefy/buefy#1826]
### Checked rows is not reset on new data

**Buefy** version: 0.8.5

### Description

When the data is refreshed the checked rows are not reset.

### Steps to reproduce
There are 2 rows checked, the data is refreshed now if you check another row it says 3 instead of 1.
https://codepen.io/conceptme/pen/bGGbORG?editors=1010

### Expected behavior

The checked rows is 1

### Actual behavior

The checked rows is 3

**Comment by jtommy** [comment]
@cdekok Table component preservers checked rows during the pagination, so you if you wanto to uncheck them you should reset the selected array on page change
