### ISSUE TITLE
Improvements to modal accessibility

### ISSUE THREAD

**Issue by mateuswetah** [buefy/buefy#1830]
### Description

Besides `trap-focus` we could add more features to improve modal accessibility for keyboard-only navigation. 

- [ ] Auto focus modal parent when opened. This could be done by invoking the element on `mounted()`. When using `<b-modal>` for example, the tag can be on a region of the html that is far from the calling element, making it difficult to reach the modal.
- [ ] Add aria-modal and role="dialog". It can be discussed if the developer might prefer to use role="alertdialog" (something I would expect to see in the Dialog component actually). When testing with screen readers, this properties help identify that the user entered a modal-like region.

There might be other ways to do it, or other improvements, this is what I can think so far. I've been simulating the use of screen readers with ChromeVox extension for GC. 

### Why Buefy need this feature

It would significantly improve overall accessibility of this component.

**Comment by service-paradis** [comment]
@mateuswetah 
Thanks for your feedback :)

Here is my input about your 2 suggestions:
- The focus could probably be given into the modal directly into the trapFocus directive (more specifically into the `bind` function). Woul only need to be cautious with dialog that uses `focusOn` prop.
- For the role, we could probably add a prop for it. Defaulting to `dialog`. We could have a validator for this prop to accept `null`, `dialog` or `alertdialog`

Does this make sense?

**Comment by mateuswetah** [comment]
@service-paradis Yes, that sounds great!

We already have a few cases where role is passed to inner parts of components, like Dropdown's `aria-role`:
https://buefy.org/documentation/dropdown/
