### ISSUE TITLE
b-navbar-link, a-link don't work on mobile 

### ISSUE THREAD

**Issue by sergpy** [buefy/buefy#1831]
Сlick on a-link, b-navbar-item link does not work on mobile device
I tested  bulma version (0,8,5 / 0,7,5)

**Comment by jtommy** [comment]
Click event or route? Can you provide an example code ?

**Comment by sergpy** [comment]
Route doesn't work.  My pug code is:

                b-navbar(shadow)
			template(slot='start')
				b-navbar-item(href='#/docs')
					| Documentation
				b-navbar-dropdown(label='Info')
					b-navbar-item(href='#/about')
						| About
					b-navbar-item(href='#/contacts') 
						| Contact

**Comment by jtommy** [comment]
Did you try using router-link as tag prop ?

**Comment by sergpy** [comment]
yes, it works ok

**Comment by jtommy** [comment]
I should investigate about but some links work and other doesn't
