### ISSUE TITLE
programatically close a dialog box 

### ISSUE THREAD

**Issue by Ashtonian** [buefy/buefy#1832]
![image](https://user-images.githubusercontent.com/4212452/66240360-13b23200-e6c2-11e9-9450-ddaacf237a60.png)

# Description
I am using a dialog box to prompt user their session is expiring so they can renew it. If the user walks away from the app, the prompt will eventually appear and shortly after no response a timeout fires logging the user out and navigating back to the login page. The prompt remains open and I'm not sure how I can close it. Currently working around by reloading the site instead of programmatic navigation. 

Additionally it may be nice to do this in case you only ever want one prompt open. Right now I don't think there is a way to only have one prompt open without manually managing that state. 

api to access and close dialog box prompt after its launched. 

### Why Buefy need this feature

- enforce single dialog
- close dialog without user interaction

**Comment by jtommy** [comment]
@Ashtonian open method returns an instance of dialog component so you might call close method on it

**Comment by Ashtonian** [comment]
thanks! didn't see that anywhere.
