### ISSUE TITLE
Navbar dropdown not working on PHP Desktop v57.0 for Windows

### ISSUE THREAD

**Issue by zikomik** [buefy/buefy#1833]
Navbar dropdown not working on PHP Desktop v57.0 for Windows

**Comment by jtommy** [comment]
Any example?

**Comment by zikomik** [comment]
How can I show an example?
It works on chrome 77+,
but not working on Chrome 57.
https://github.com/cztomczak/phpdesktop

**Comment by zikomik** [comment]
> Any example?
How can I show an example?
It works on chrome 77+,
but not working on Chrome 57.

PHP Desktop v57.0

**Comment by service-paradis** [comment]
What do you mean exactly by not working? Not displaying? Not opening? Not reactive? The links does not work? Not displayed properly? ...?

**Comment by zikomik** [comment]
dropdown  not opening in navbar .

**Comment by jtommy** [comment]
I think it's a Bulma issue, probably the same of IE

**Comment by service-paradis** [comment]
You can try using Bulma only for the navbar. If the issue is still there, you can open your issue there:
https://github.com/jgthms/bulma/issues

**Comment by zikomik** [comment]
it's a Bulma issue

**Comment by service-paradis** [comment]
Ref: https://github.com/jgthms/bulma/issues/2644
