### ISSUE TITLE
DatePicker sets invalid date on iOS Safari

### ISSUE THREAD

**Issue by MelvinFrohike** [buefy/buefy#1834]
### Overview of the problem

**Buefy** version: 0.8.5
**Vuejs** version: 2.6.10
**OS/Browser**: iOS 13 / Safari

### Description

Using a date picker on iOS with Safari always produces an "invalid date".
This happens on iOS 12 & iOS 13 but not on macOS Safari 12 & 13.
This makes date pickers unusable on iPhone/iPad.
This is similar to #1516 I reported earlier this year, that was fixed quickly.
Now both normal date pickers and month pickers don't work anymore.
I don't know in which Buefy Version this broke but 0.8.3 already has this problem.
Note that when initializing the v-model value, the date picker shows the correct date.
As soon as the date is then changed via the date picker, the date becomes invalid.

### Steps to reproduce

1. Open https://codepen.io/melvinfrohike/pen/LYYYdVV in iOS Safari.
2. Select any date

### Expected behavior
The 'selected date' label should show the selected date's string representation

### Actual behavior
The 'selected date' label shows "invalid date".

**Comment by adrienlefebvre92** [comment]
I also get the same on all browsers for iOS.

**Comment by bohdan-prylutskyi** [comment]
@adrienlefebvre92 do you have iOS 13?

**Comment by adrienlefebvre92** [comment]
> @adrienlefebvre92 do you have iOS 13?

I have iOS 11.0.3 @bohdan-prylutskyi
