### ISSUE TITLE
Adding an Accordion/Dropdown

### ISSUE THREAD

**Issue by Lunrtick** [buefy/buefy#1835]
### Description
I created an Accordion component a few years ago, and often use it alongside Buefy in my projects. I thought that it might make sense to include this component, or something similar, inside the Buefy bundle.

Here is a link to the docs [vue-bulma-accordion](https://lunrtick.github.io/vue-bulma-accordion/).

### Why Buefy need this feature

It doesn't **need** this feature, but I thought it may be nice to include.

**Comment by jtommy** [comment]
@Lunrtick Sure, it makes sense but there is already the collapse component and I don't want to add clone of it.
