### ISSUE TITLE
the queue flg in snackbar  not work

### ISSUE THREAD

**Issue by JMDC-SUN** [buefy/buefy#1837]
**Buefy** version: [0.8.5]
**Vuejs** version: [2.6.10]
**OS/Browser**:
Windows10/chrome
### Steps to reproduce
The queue flg in snackbar  not work after update to  buefy@0.8.5 from 0.8.4.
Before
 
![image](https://user-images.githubusercontent.com/49149068/66285092-02f1fe00-e906-11e9-91bc-c406491dae0b.png)

After 
 Only show One snackbar by click.

**Comment by jtommy** [comment]
Are you able to reproduce your config on codepen or similar?

**Comment by JMDC-SUN** [comment]
I use the Constructor options as same as  [Document](https://buefy.org/documentation/constructor-options), but I do not use 'content' as any element id. 

```
Vue.use(Buefy, {
    defaultIconPack: 'fas',
    defaultContainerElement: '#content',
    // ...
})
```
When I remove 'defaultContainerElement' from Constructor options, it work very well !

Thanks a lot.

**Comment by service-paradis** [comment]
If you use `defaultContainerElement: '#content',`, you need to have at least an element in your page having `id="content"`.

**Comment by cypressious** [comment]
I had the same issue, probably because I copy pasted the default config from somewhere. Maybe there should be a console warning when the `defaultContainerElement` doesn't exist?
