### ISSUE TITLE
Date picker carica le icone solo con il material desig

### ISSUE THREAD

**Issue by nicolalandro** [buefy/buefy#1838]
### Overview of the problem
**Buefy** version: [0.8.5]
**Vuejs** version: [2.5.17]
**OS/Browser**:Linux/Firefox

### Description
The icon of DatePicker are not loaded with FontAwesome, [sample on codepen](https://codepen.io/nicolalandro/pen/xxxbZgq?editors=1010) .
I expect maybe to change the icon name, or set the pack value, but it do not works.

**Comment by service-paradis** [comment]
There are some issues in your codepen.

1. You need to define the `icon-pack` for the datepicker if you want to use fontawesome. `icon-pac="fas"` (https://buefy.org/documentation/datepicker#api-view)
2. `calendar-today` is not a valid [fontawesome icon](https://fontawesome.com/icons?d=gallery&q=calendar).

This is a working datepicker example using your setup:
```
<b-datepicker
      :show-week-number="showWeekNumber"
      placeholder="Click to select..."
      icon="calendar"
      icon-pack="fas">
</b-datepicker>
```

And [here ](https://codepen.io/service-paradis/pen/poovydr?editors=1010)is your updated codepen.

**Comment by nicolalandro** [comment]
Thanks and scuse me for the issue!

________________________________
Da: Alexandre Paradis <notifications@github.com>
Inviato: lunedì 7 ottobre 2019 14:29
A: buefy/buefy <buefy@noreply.github.com>
Cc: nicolalandro <nicolaxx94@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [buefy/buefy] Date picker carica le icone solo con il material desig (#1838)


There are some issues in your codepen.

  1.  You need to define the icon-pack for the datepicker if you want to use fontawesome. icon-pac="fas" (https://buefy.org/documentation/datepicker#api-view)
  2.  calendar-today is not a valid fontawesome icon<https://fontawesome.com/icons?d=gallery&q=calendar>.

This is a working datepicker example using your setup:

<b-datepicker
      :show-week-number="showWeekNumber"
      placeholder="Click to select..."
      icon="calendar"
      icon-pack="fas">
</b-datepicker>


And here <https://codepen.io/service-paradis/pen/poovydr?editors=1010> is your updated codepen.

**Comment by service-paradis** [comment]
No problem :)
