### ISSUE TITLE
Select2 Infinite Scroll Function Suggest

### ISSUE THREAD

**Issue by bportesio** [buefy/buefy#1842]
### Description

It is in your plans to add a select component whit infinite scrolling option like http://vueinfinitescroll.clickvalley.in/?

Why does Buefy need this feature?

It is very useful and would replace one of the most used functions of select2 plugin, making the buefy2 framework a more complete option when choosing it over the others frameworks

**Comment by afwn90cj93201nixr2e1re** [comment]
you should use autocomplete with footer, with seek mode on backend.

**Comment by bportesio** [comment]
Its similar but my suggest is a select input
