### ISSUE TITLE
TagInput with open-on-focus does not show items after removing one

### ISSUE THREAD

**Issue by Leftyx** [buefy/buefy#1843]
### TagInput autocomplete with `open-on-focus` does not show items after removing one.

**Buefy** version: 0.8.5
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10 / Chrome latest

### Description

TagInput with `open-on-focus` does not show items after removing one. 
The only way to make it work is to click outside the autocomplete textbox.

### Steps to reproduce

1. Open Autocomplete sample [here](https://buefy.org/documentation/taginput/#autocomplete)
2. Set Open of focus
3. select an item from the list
4. Remove the item
5. click inside the autocomplete textbox to select

### Expected behaviour

one of the tags should show.

### Actual behaviour

no item is shown.

![TagInput gif](https://user-images.githubusercontent.com/171024/66393293-0f3f8f00-e9ca-11e9-934e-a431cd756cbe.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
Still reproduce?

**Comment by Kaisirak** [comment]
Having similar issues (https://github.com/buefy/buefy/issues/2135)

**Comment by jtommy** [comment]
It should work using keyboard, btw double https://github.com/buefy/buefy/issues/2156
