### ISSUE TITLE
Burger menu button is shown even though its empty

### ISSUE THREAD

**Issue by supermar1010** [buefy/buefy#1845]
### Overview of the problem

**Buefy** version: 0.8.5
**Vuejs** version: 2.6.10
**OS/Browser**: Linux/Firefox/Chromium

### Description

The hamburger menu link is shown even though I only have a brand section.

### Steps to reproduce

```
<template>
    <b-navbar>
        <template slot="brand">
            <b-navbar-item tag="router-link" :to="{ path: '/' }">
                <img
                    src="https://raw.githubusercontent.com/buefy/buefy/dev/static/img/buefy-logo.png"
                    alt="Lightweight UI components for Vue.js based on Bulma"
                >
            </b-navbar-item>
        </template>
    </b-navbar>
</template>
```

### Expected behavior

No burgermenu link is shown because it ill be empty, or a parameter can be set to hide it.

### Actual behavior

A burgermenu link is shown

**Comment by wanxe** [comment]
We decided to let the burger by default just to avoid write too much code. Could you try to add an empty burger slot?

**Comment by supermar1010** [comment]
I just tried it in codepen.

```
<template slot="burger">
<b-navbar-item>
<b-navbar-item>
</template>
```
This makes the burger menu button disappear, but if I remove the navbar item it appears again
Maybe you could add that behavior to the documentation?

**Comment by wanxe** [comment]
Try this instead:

```
<b-navbar>
      <template slot="burger"></template>
</b-navbar>
```

**Comment by service-paradis** [comment]
Maybe we should add some condition during the render phase of the navbar component.

Something like (only a suggestion): 

1. Display `navbar-menu` only if there is content for slot `start` or slot `end`
2. Display `navbar-burger` only if there is a `navbar-menu`

**Comment by jtommy** [comment]
@wanxe what do you think about it ?

**Comment by supermar1010** [comment]
@wanxe I tried that, taht did not work for me. It only worked when having an empty navbar-item in there

**Comment by afwn90cj93201nixr2e1re** [comment]
https://buefy.org/documentation/dropdown/

why now burger/login button now here?

Seems like you r broke smthng.

**Comment by wanxe** [comment]
@service-paradis thanks for the suggestion, I think that we can apply your solution 🤔

**Comment by afwn90cj93201nixr2e1re** [comment]
it's bulma expected behaviour, why we should overwrite it?

**Comment by wanxe** [comment]
In bulma you can remove the burger, just deleting the html. We have to cover this too :)

**Comment by service-paradis** [comment]
@supermar1010 
As a workaround for now, you can use `<template slot="burger" slot-scope="{isOpened, toggleActive}"></template>` to hide the burger.
