### ISSUE TITLE
Type definitions for Toast/Snackbar.open are missing return type with close method.

### ISSUE THREAD

**Issue by cypressious** [buefy/buefy#1849]
### Overview of the problem

**Buefy** version: 0.8.5
**Vuejs** version: 2.6.10

### Description

The type definitions for `Toast` and `Snackbar` are missing the return type for the `open` method which contains the `close` method. Without proper typing it's hard to discover that the `close` method exists at all.

**Comment by jtommy** [comment]
You're right, Types have to be improved
