### ISSUE TITLE
Constructor option to change default value of `rounded` prop on <b-button>

### ISSUE THREAD

**Issue by dstock48** [buefy/buefy#1851]
### Description

Could there be a new Constructor Option called something like `defaultButtonRounded` which can be set to `true` or `false`?

### Why Buefy need this feature

The project that I'm working on requires that all buttons be rounded. Currently this would require that I manually set the rounded prop to true on every button, or create some sort of wrapper component around b-button to set rounded to true.

I could also do a global override on the `.button` bulma class to add a large border-radius but that would have some unintended side effects, like the buttons on the b-numberinput component would become fully rounded when I would want those to stay with the normal slightly rounded corners

**Comment by jtommy** [comment]
Surely!!
