### ISSUE TITLE
Disabled button with span triggers collapse in chrome

### ISSUE THREAD

**Issue by cdekok** [buefy/buefy#1855]
### Overview of the problem
A disabled button with a span inside opens the collapse in chrome, in firefox / safari it works correctly.

**Buefy** version: 0.8.5
**OS/Browser**: OS X / Chrome

### Steps to reproduce

https://codepen.io/conceptme/pen/jOObWqe?editors=1010
Click the button

### Expected behavior

The collapse does not open

### Actual behavior

The collapse opens

**Comment by jtommy** [comment]
I'm using chrome but i'm not able to reproduce the issue using your codepen

**Comment by cdekok** [comment]
Woops forgot to save the pen the span was missing. https://codepen.io/conceptme/pen/jOObWqe?editors=1010
this is especially annoying when having an icon in the button. It might be a chrome issue though as it does seem to work correctly in the other browsers.

**Comment by yxngl** [comment]
Browsers differ in how to handle events from disabled form element. Safari should behave like Chrome in this case: the click event is propagated from the span. 

Solution would be to add
```css
button > span {
  pointer-events: none;
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
But disabled button without span also works. Strange.
