### ISSUE TITLE
Add capslock notification on password field

### ISSUE THREAD

**Issue by axtg** [buefy/buefy#1860]
### Description
I already love the password-reveal option, as it is quite reactive (needs user action), I am looking to implement a capslock is on notification. Proactively informing the user that capslock is on.

### Why Buefy need this feature
I believe it fits nicely in the list of features why I appreciate Buefy: simple but valuable UI improvements (e.g. character count on text area or the password reveal option).

**Comment by jtommy** [comment]
@axtg thanks but I don't think it's a good feature to add in the core code. There are some many way to manage it
