### ISSUE TITLE
Datepicker range of dates issue on the mobile

### ISSUE THREAD

**Issue by emrahyumuk** [buefy/buefy#1868]
### Overview of the problem

**Buefy** version: [0.8.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome 77.0.3865.120 (Official Build) (64-bit)

### Description

When I open the web page on the mobile, I can't select a range of dates on the datepicker. 

You can take a look on https://codepen.io/emrahyumuk/pen/PooZrxP?&editable=true&editors=101

![image](https://user-images.githubusercontent.com/2338849/66734812-405a0c80-ee6d-11e9-80f2-ecefe67641ce.png)

### Steps to reproduce

1. Open the web page on your mobile phone or with chrome desktop dev tools as mobile 
2. Refresh the web page
3. Try to select a range of dates

**Comment by jtommy** [comment]
Some features aren't available using native datepicker, so you have to set the prop :mobile-native="false" (of course you won't see the native picker)

**Comment by ghukill** [comment]
Though I see `mobile-native` in the API properties, I think it might be helpful to highlight this option in the examples.  Were it not for this Github issue, I may have continued to miss that configuration option, and thus, been unable to support date ranges on mobile.  Just a thought.

**Comment by tgrushka** [comment]
I really love Buefy ... it is great and I'm using it more and more to replace my HTML components! Love the datepicker. Is there any way possible to make the range picker work on mobile? Possibly pop up the native picker twice for a range? Or is there a way to force the Buefy HTML picker on mobile, and it would just fill the mobile screen and basically work the same way it works on desktop?

**Comment by jtommy** [comment]
@tgrushka if you need range mode you have to disable native using :mobile-native="false"

**Comment by tgrushka** [comment]
Yes, @jtommy, I did that. It then becomes a plain text box, right? Or is it supposed to be a Buefy control?

**Comment by jtommy** [comment]
No you'll see the datepicker into a modal

**Comment by tgrushka** [comment]
Oh, I see, you have to tap twice. Is this a UX thing or is there an option to have it pop up immediately? I'll just tell my users to tap twice in the instructions.
