### ISSUE TITLE
Get index of checked row

### ISSUE THREAD

**Issue by adriflorence** [buefy/buefy#1869]
Hi guys, 

This might seem like a fairly simple question but I have not managed to figure it out.
I have a b-table that is `checkable` and is synchronised with an array through `:checked-rows.sync="checked_rows"`. All I am trying to do is to create a function that is triggered on checking a checkbox in each row and pass in the index of that row, like so: `@check="doSomething(index)"` 

How can I get hold of the index outwith the actual row? Note, the method is on the b-table.
There are various selects in each row that should get updated behaviour / content based on checking the boxes, so it would be good to handle them in one place.

Thanks a million for your help!

**Comment by jtommy** [comment]
@adriflorence Table component already emit `check` component so you can get them `checkedList: Array, row: Object`. 
With `row` you should be able to get the index of selected row, for example: `this.mydata.indexOf(row)` or using filter
