### ISSUE TITLE
Datepicker disabled color is inconsistent with other disabled inputs

### ISSUE THREAD

**Issue by thomasraydeniscool** [buefy/buefy#1871]
**Buefy** version: 0.8.4
**Vuejs** version: 2.6.10
**OS/Browser**: Electron

### Description

![Screenshot from 2019-10-15 13-18-37](https://user-images.githubusercontent.com/28379549/66802439-ff3a2900-ef4e-11e9-9610-e5ec699ec7e5.png)

'Invoice #' is standard _disabled_ `b-input`. 'Issue Date' and 'Due Date' are _disabled_ `b-datepicker` components. 

### Steps to reproduce

1. Create disabled `b-input` & `b-datepicker` side by side.
2. See that the color is inconsistent.

It is caused by the opacity in the `.dropdown.is-disabled` class inherited by the `b-datepicker` component.

![image](https://user-images.githubusercontent.com/28379549/66802728-057cd500-ef50-11e9-895d-53f71c6e4a6b.png)

### Expected behavior

The input disabled colors should match up.

**Comment by service-paradis** [comment]
@jtommy 
Could we just remove `opacity: 0.5`? Not sure what the purpose really is...

**Comment by jtommy** [comment]
It makes sense using a single dropdown but not in the datepicker, timepicker,..
