### ISSUE TITLE
Add custom property for position in dropdown

### ISSUE THREAD

**Issue by codingsett** [buefy/buefy#1872]
### Description

I wanted to modify the margin of the menu dropdown but i cannot do that unless i use bulma directly which is inconvinient.

![image](https://user-images.githubusercontent.com/27306293/66827966-92c42780-ef58-11e9-9640-3d1eb41c2fb9.png)

Add support for custom classes for position property.

![image](https://user-images.githubusercontent.com/27306293/66828044-c4d58980-ef58-11e9-88bb-0175a64a5406.png)

### Why Buefy need this feature
Because the library components should support easy customization of different UI elements.

**Comment by service-paradis** [comment]
You can add custom class to any dropdown using `class`. Something like `<b-dropdown class="test">`.

**Comment by sgarner** [comment]
Adding `class` attribute to the Dropdown component only applies that class to the dropdown container element which wraps the trigger.

When opened, the dropdown menu gets appended elsewhere in the document (by default to the `body`), and does not receive the `class` attribute that was set on the component.

Perhaps there should be another prop like `menu-class` that applies to the opened menu element so the styling of an individual dropdown can be customised. Or the given `class` attribute should just apply in both places?

**Comment by sgarner** [comment]
Sorry I just realised this behaviour of course depends on whether the `append-to-body` prop is set. When not using that mode, the menu is rendered inside the dropdown and the class works as expected.

**Comment by service-paradis** [comment]
@sgarner You're right, the class work as expected when not using `append-to-body`. But I think, it would be great to be able to add a custom class when using this prop.

**Comment by jtommy** [comment]
@sgarner please open a new issue

**Comment by jtommy** [comment]
@sgarner @service-paradis added!
