### ISSUE TITLE
Safari 13 hangs when clicking b-select

### ISSUE THREAD

**Issue by patternoia** [buefy/buefy#1874]
### Overview of the problem

**Buefy** version: [0.7.7] - [0.7.10]
**Bulma** version: [0.7.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: macOs 10.14.6, Safari 13.0.2

### Description

Safari 13 hangs when clicking b-select.

### Steps to reproduce

First click on b-select does not expand the control, second hangs the browser

### Expected behavior

b-select is expanded (dropdown with options is shown)

### Actual behavior

Browser hangs

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/1785
