### ISSUE TITLE
Feature request: setCustomValidity method on input

### ISSUE THREAD

**Issue by htfy96** [buefy/buefy#188]
### Overview of the problem

Buefy version: 0.4.4
Vuejs version: 2.3.3
OS/Browser: Fx54 on Linux

### Description

[`setCustomValidity` API](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Constraint_API%27s_element.setCustomValidity()) introduced in HTML5 allows user to display a customized message for inputs with validation. Unfortunately, many browsers, including Edge, are [lacking the support](http://caniuse.com/#feat=constraint-validation). 

It seems that Buefy implements validation message with its own element. Is it possible to allow user to customize its message dynamically (i.e. changing `newMessage` of its parent field) by providing `setCustomValidity()` method?

**Comment by rafaelpimpa** [comment]
Actually you can add a message to field prop directly:

```html
<b-field message="Custom message" type="is-danger">[...]</b-field>
```

Is that what you need?
