### ISSUE TITLE
Use provide-inject in b-table-column instead of $parent

### ISSUE THREAD

**Issue by thomasraydeniscool** [buefy/buefy#1881]
### Description

The `b-table-column` component uses the `$parent` option internally to update the tables `newColumns` variable.

The same can be done using Vue's provide-inject options: https://vuejs.org/v2/api/#provide-inject

> Note: the provide and inject bindings are NOT reactive. This is intentional. However, if you pass down an observed object, properties on that object do remain reactive.

Because passed down properties are reactive the `newColumns` array should stay reactive when being mutated by the `splice()` and `push()` methods inside the `b-table-column` component.

### Why Buefy need this feature

```
Error: You should wrap bTableColumn on a bTable
```

Because the `b-table-column` component requires the `$parent` option it restricts the use of nested components inside the table.

My project requires me to have table cell values to be directly editable by clicking on them. Below the LineItem component is required to update a single item (or row) of an array in the Vuex state.

bTable
![image](https://user-images.githubusercontent.com/49743696/66986865-401e7300-f0f2-11e9-9686-485eae8eb2e1.png)

LineItem
![image](https://user-images.githubusercontent.com/49743696/66987872-1ebe8680-f0f4-11e9-8364-cd9a95cd7c06.png)

**Comment by jtommy** [comment]
You are completely right!
I already thought to use the injection in the table and other components :)

**Comment by anthonkendel** [comment]
Hey, @jtommy is this open for contributions or is someone else already working on it? :)

**Comment by jtommy** [comment]
Sure, you are welcome

**Comment by anthonkendel** [comment]
> Sure, you are welcome

Cool, I've submitted a PR. I couldn't find any test requirements so if anything is missing just tell me.

**Comment by dylanhru** [comment]
Closed huh. Looks like we're going to ditch Beufy then.

**Comment by jtommy** [comment]
Why ?

**Comment by adriaanmeuris** [comment]
@jtommy Is this feature still in consideration?

I'd be happy to help, or review the PR from @anthonkendel.
It would allow reusing custom column components, or even en entire custom row component.

**Comment by anthonkendel** [comment]
When I submitted my [PR](https://github.com/buefy/buefy/pull/1897) the table was supposed to be refactored. Don't know what the status is right now though.

**Comment by jtommy** [comment]
Already done, thanks

**Comment by adriaanmeuris** [comment]
> Already done, thanks

What do you mean? I don't see how this is possible with the latest version.

**Comment by jtommy** [comment]
Dev branch
