### ISSUE TITLE
B-table- Selection vanishes after few seconds

### ISSUE THREAD

**Issue by sajalsinghal7** [buefy/buefy#1884]
### Overview of the problem
I have my B-table- placed within b-tabs
Within the table I have few columns containing data like a small thumbnail file name date etc
In Firefox I am facing the issue that the selection vanishes after few seconds
**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:Mozilla & windows 10

### Description
I have a B-table- placed within b-tabs
The b table have few columns like file thumbnail, filename date 
When a user selects one or more rows, the selection vanishes after few seconds.
The issue is frequently visible on Mozilla

**Comment by jtommy** [comment]
@sajalsinghal7 can you reproduce it on codepen ?
