### ISSUE TITLE
How feasible would it be to use Bulma as a peer dependency?

### ISSUE THREAD

**Issue by kriansa** [buefy/buefy#1887]
### Description

I needed to use a feature from a more recent bulma package and it currently is not available on buefy. However, instead of asking to update the dependent package, I'd like to ask if it would be possible to turn `bulma` into a peerDependency, so that the application would be responsible for handling the underlying package, just like Vue currently is.

I'm not sure if the philosophy behind Buefy is that it should be sold as an entire package, or if it would be just an "add-on" that glues together Vue + Bulma. Please guide me towards the current thinking.

The benefits of that would be that you wouldn't need to keep updating the package.json every time Bulma releases a new version. The downsides, AFAICS, is that this would be a breaking change whereas users would need to update their dependency list.

Thank you all for your hard work maintaining this project!

**Comment by jtommy** [comment]
Bulma is not a peer dependency because a misaligned version could break Buefy.
Using scss customization you might use last version of Bulma but we cannot ensure a correct work.

**Comment by kriansa** [comment]
Hi @jtommy ! Thanks for the reply.

I understand the concern about keeping a functional package for every setup. Accepting a wide range of versions as a dependency can be risky because we need to trust the package vendor to comply with semantic versioning. 

However, I'm just thinking: we have the same risk by having Vue as a peer dependency, correct? Why did you decide differently for these two libs? Is it because you don't trust bulma that much? Is it because it's pre-1.0?

Also, have you considered keeping it as a peer dependency but with a very limited version ranges?

_I honestly don't know any of that but I'm just asking to get a better understanding of the rationale behind this decision, don't take it as a criticism or bad judgment._ 😄

**Comment by jtommy** [comment]
No, Vue 2.6.x doesn't introduce breaking changes.
Bulma uses the same versioning of Buefy and for example in the new 0.8.0 introduced some breaking changes.
Btw I'm trust Bulma :)
The bundle contains bulma too but you should be able to use last version of Bulma.
