### ISSUE TITLE
Errors and failures when running unit tests

### ISSUE THREAD

**Issue by jamenamcinteer** [buefy/buefy#1888]
**Buefy** version: 0.8.5 (master and dev branch)
**Vuejs** version: 2.5.13
**OS/Browser**: N/A - Windows 10 with VS Code

### Console errors and snapshot fails when running `yarn test`

When I run `yarn test`, I get 11 snapshot fails from snapshots that have not been updated as well as console errors thrown by vue-test-utils: 
```
console.error node_modules/@vue/test-utils/dist/vue-test-utils.js:1421
      [vue-test-utils]: Vue Test Utils runs in sync mode by default. Due to bugs, sync mode requires Vue > 2.5.18. In Vue Test Utils 1.0 sync mode will only be supported with Vue 2.5.18+ running in development mode. If you are unable to upgrade, you should rewrite your tests to run asynchronouslyyou can do this by setting the sync mounting option to false.
```

This makes it difficult to test any new development or write new unit tests as the console gets filled with all this output.

### Steps to reproduce

1. Run `yarn test`
2. Observe snapshot fails and console errors.

### Expected behavior

There shouldn't be console errors and snapshots on the master/dev branch should pass.

### Actual behavior

Snapshot fails from snapshots that have not been updated as well as console errors thrown by vue-test-utils

**Comment by jamenamcinteer** [comment]
I would be happy to work on this issue. I'm thinking the snapshots should simply be updated in a new PR, but don't want to make assumptions if they need further review.

**Comment by jtommy** [comment]
It depends on node version. At the moment snapshot are made using 8.x to be compliant with current Circle CI image

**Comment by jamenamcinteer** [comment]
I am currently on Node v8.10.0

**Comment by service-paradis** [comment]
Every tests and snapshots are working on my side when using Node v8.10.0.
They are also working on CircleCi right now.

So you have an example of a snapshot failure?
