### ISSUE TITLE
Overlap issue when using :fixed-top and :spaced options together

### ISSUE THREAD

**Issue by tzar** [buefy/buefy#1889]
### Overview of the problem

**Buefy** version: 0.8.5
**Vuejs** version: 2.6.10
**OS/Browser**: Linux/Chrome

### Description

When you use `<b-navbar :fixed-top="true" :spaced="true">` buefy adds `has-navbar-fixed-top` to `body` which causes the navbar to clip over the content at large screen widths. It should instead add `has-spaced-navbar-fixed-top` for the correct padding rules.

### Steps to reproduce

[See this codepen](https://codepen.io/tzar/pen/bGGBJGy) - make sure you're running it above 1300px wide.

### Expected behavior

Navbar does not clip over title

### Actual behavior

Above ~1300px wide, the title "Test" disappears due to the navbar overlapping it.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/c5bac1f5d5a3a0cf7e05d92ea4b8fe8f40c76a0c

**Comment by syn-zeta** [comment]
Buefy only adds `has-spaced-navbar-fixed-top` to `<body>` when using a spaced navbar, but it leads to overlap on tablet and below. Solved at jgthms/bulma#2737.
