### ISSUE TITLE
Tab header with tag is 1px higher than without

### ISSUE THREAD

**Issue by bpuig** [buefy/buefy#1891]
### Overview of the problem

**Buefy** version: [0.8.5]
**OS/Browser**: Firefox

### Description

Custom Headers tabs with a slot and a `<b-tag> `on it have 1px more in height than slots without <b-tag> so it looks weird when combined. 

### Steps to reproduce

```
<template>
    <b-tabs>
        <b-tab-item>
            <template slot="header">
                <b-icon icon="information-outline"></b-icon>
                <span> No tag </span>
            </template>
        </b-tab-item>
        <b-tab-item>
            <template slot="header">
                <b-icon icon="source-pull"></b-icon>
                <span> With tag <b-tag rounded> 2 </b-tag> </span>
            </template>
        </b-tab-item>
    </b-tabs>
</template>
```

### Expected behavior

Same height

### Actual behavior

42.5px height vs 43.5px height when having <b-tag>

**Comment by yxngl** [comment]
It is caused by the tag. Likewise, removing icon in the first tab will make them misaligned.  One workaround is  to set a `min-height` on `.tabs li > a `

**Comment by service-paradis** [comment]
@bpuig
Can you try if it also happens using native Bulma. If so, you will need to open your issue [there](https://github.com/jgthms/bulma/issues).

**Comment by bpuig** [comment]
> Can you try if it also happens using native Bulma.

Well, it's not officially documente to be a Bulma function to have `tags` in `tabs`, but anyway, height is respected:
<img src="https://i.imgur.com/pcURYTX.png">

**Comment by service-paradis** [comment]
@jtommy We could add a Breaking Change label on this issue and find a way to improve the behavior.
