### ISSUE TITLE
"Search" for the Docs

### ISSUE THREAD

**Issue by MaikelScheffer** [buefy/buefy#1893]
### Description
I'd like to suggest the addition of "Search" functionality to the Buefy docs. 
Neither Buefy nor Bulma themselves have a search on their docs and it's honestly extremely aggravating. 
It isn't uncommon for me to lose quite a bit of time browsing the docs.
The components themselves are stellar, but the absence of search is slowing down my development tremendously -- even more so because I'm new to both Bulma, Vue, and Buefy. 

From what I've gathered so far:
https://community.algolia.com/docsearch/
Is a fairly popular option. 

### Why Buefy need this feature

Including a "Search" input on the docs to easily traverse the large selection of components would allow developers to more easily find the components they're looking for.

**Comment by jtommy** [comment]
You are completely right
