### ISSUE TITLE
Allow asynchronous validation in dialog component

### ISSUE THREAD

**Issue by jessicarobins** [buefy/buefy#1896]
### Description
Currently, the dialog component allows synchronous validations. It would be useful for it to also allow async validations as part of the `onConfirm` callback.

### Why Buefy need this feature
An example of this (the one I'm currently implementing) is to prompt users for their password to confirm account deletion. If they enter the wrong password, I don't want to close the dialog box. I think it would be pretty straightforward to keep the simplicity of the dialog implementation while adding this feature.

An example implementation could be to mirror event handling - check the return value of the `onConfirm` callback and keep the dialog open if it's false, otherwise close it.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think there is should be prop, like closeOnConfirm/closeOnAbort.

**Comment by kaangokdemir** [comment]
This would be an amazing feature.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/pull/2539
