### ISSUE TITLE
Searchable prop for custom detailed Table

### ISSUE THREAD

**Issue by viralpatel380** [buefy/buefy#1898]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 3.11.0
**OS/Browser**: Win 10 [x64] / chrome

### Description
I am trying to add a searchable prop to Custom Detailed Table but it seems behaves awful,

![screencapture-codepen-io-pen-2019-10-23-10_52_28-edit](https://user-images.githubusercontent.com/25549548/67360748-51e59780-f584-11e9-806b-0087b8767ca5.jpg)

You can see the gap between arrows and columns

**Comment by jtommy** [comment]
What do you mean?

**Comment by viralpatel380** [comment]
You can see gap betweens Name column and expanding button...
