### ISSUE TITLE
Generate web-types for Buefy package for rich code assist in IDE #17823

### ISSUE THREAD

**Issue by piotrtomiak** [buefy/buefy#1899]
### Description

This is a feature request to include [web-types](https://github.com/JetBrains/web-types) metadata information with `buefy` library to provide users of WebStorm (and possibly other IDEs in the future) with precise code completion, inspections and documentation for the components.

The best solution would be to generate the file based on existing documentation JSONs during the build process and ship it with the library. This solution has been implemented in `quasar` and `bootstrap-vue` libraries and is being worked on in `vuetify`.

I can work on the transformation code itself, but it would be pretty difficult for me to hook into the build process in the correct place, so I need some help from your side, before I can create a PR for this. Additionally we can generate `web-types` for older versions of library and publish them to `@web-types/` scope so that consumers of older versions of library can also benefit from better code assist.

### Why Buefy need this feature

Here is how code completion will look like with WebStorm 2019.3 and `bootstrap-vue` 2.1.0:

![web-types1](https://user-images.githubusercontent.com/4244523/67289568-1c3aa300-f4df-11e9-9521-5f4ae9f2e9e6.gif)

I think would be a really great help for developers to have such a support for your library.

**Comment by jtommy** [comment]
@piotrtomiak Nice addition!! Make your PR and I'll help you with build
