### ISSUE TITLE
Checkable and seachable table require empty <th></th>

### ISSUE THREAD

**Issue by grandsilence** [buefy/buefy#1902]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10 1803 / Chromium 74.0.3729.169

### Description
The search field is not displayed correctly when a checkbox is set (`checkable` for table and `searchable` for column).

```vue
<b-table :data="filteredCities" :columns="citiesColumns" :checked-rows.sync="bot.cities" checkable striped default-sort="name"
                     paginated :per-page="15" :current-page.sync="citiesPage" pagination-position="bottom"
                     class="vertical-centered">
              <template slot="bottom-left">
                <b>Cities selected</b>: {{ bot.cities.length }}
              </template>
            </b-table>
```

```ts
citiesColumns = [
      {
        field: 'id',
        label: 'ID',
        width: '40',
        numeric: true,
        sortable: true,
        searchable: true,
      },
      {
        field: 'name',
        label: 'Name',
        sortable: true,
        searchable: true,
      },
    ];
```

### Bug
![Bug](https://i.imgur.com/rwPDXBY.png)

### Expected
![Expected](https://i.imgur.com/5XdYd67.png)

### Solution
Add <th></th> for checkbox column:
![Add th tag](https://i.imgur.com/HMNyRPK.png)

**Comment by TiredFalcon** [comment]
This also happens with a detailed table
