### ISSUE TITLE
Documentation for Datepicker component: examples and code not matching on mobile

### ISSUE THREAD

**Issue by bathyscaaf** [buefy/buefy#1904]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10
**OS/Browser**: All

### Description
The Datepicker description states:
"An input with a simple dropdown/modal for selecting a date, **uses native datepicker for mobile**"

The default property value for **mobile-native** is "true"

The examples on the page show the "modal" style of **:mobile-native="false"**, but the example code does not inlcude that prop set to "false".

*NOTE: I prefer the modal view over the native view.  The difference between the two shoould be called out somewhere in the docs.

### Steps to reproduce

1) Go to https://buefy.org/documentation/datepicker
2) Use your dev tools to view the page as mobile (or use an actual mobile browser)
3) toggle the calendar

### Expected behavior

The calendar should appear based on the values in the example code.  Since the default value of mobile-native is now true you should see the native calendar.

### Actual behavior

The calendar appeared as a modal, not as the native view.

**Comment by jtommy** [comment]
You'll see native picker only using Android or iOS
