### ISSUE TITLE
Request for additional Datepicker events

### ISSUE THREAD

**Issue by bathyscaaf** [buefy/buefy#1905]
### Description

Would like events emitted when a Datepicker is toggled **on** or **off**

### Why Buefy need this feature
I am using the Datepicker with the mobile modal (**:mobile-native="false"**).
I need these events to add and remove styling to prevent page scrolling while the modal view is active.

I tried a workaround based on the toggle method and the date value changing, but clicking on the background closes the modal, and since I cannot detect the close I cannot remove the styling to prevent page scrolling on close.

**Comment by superbiche** [comment]
A generic `input` event would be useful, or anything triggered when the user has selected year, month, and day, which closes the calendar. We need to detect this more easily than by watching the `v-model` binding

**Comment by jtommy** [comment]
@superbiche datepicker already provides your requirements emitting 'year', 'month' and 'input' events

**Comment by superbiche** [comment]
@jtommy oh, my bad! Should be added to the docs though, I only saw year & month
