### ISSUE TITLE
[Cleave.js] Extra symbol is added after input has lost focus (if you type more than the mask's limit)

### ISSUE THREAD

**Issue by dmtrbrl** [buefy/buefy#1907]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10
**OS/Browser**: macOS/Chrome

### Description

Extra symbol is added after input has lost focus (if you type more than the mask's limit)

![](https://media.giphy.com/media/frMXpCuViR3l8hqBXZ/giphy.gif)

### Steps to reproduce
1. Open [example from docs](https://buefy.org/extensions/cleavejs) in Codepen
2. Focus on input
3. Type more symbols than mask expects
4. Click somewhere else

The weird thing is that I can reproduce this bug on Codepen and locally.
But on docs page everything works fine.

**Comment by jtommy** [comment]
Probably is something about Vue 2.6.x because the doc is working with Vue 2.5.x

**Comment by 4KDA** [comment]
Found a solution?

**Comment by service-paradis** [comment]
It seems the problem is not only with Buefy, but with Vue in general (https://github.com/nosir/cleave.js/issues/459, https://forum.vuejs.org/t/custom-directive-not-working-well-with-last-character-cleave-js-value-sync/63990).

**Comment by hoquangthaiholy** [comment]
Hi all, I think this can fix this problem temporarily 

`Vue.directive('cleave', {
    bind(el, binding, vnode) {
        const input = el.querySelector('input')
        input._vCleave = new Cleave(input, binding.value)
        input.addEventListener('input',(e) => {
            vnode.componentInstance.newValue = e.target.value
        })
    },
    unbind(el) {
        const input = el.querySelector('input')
        input._vCleave.destroy()
    }
})`

Hope can see Cleave.js fix it in the future

**Comment by gutisalex** [comment]
> Hi all, I think this can fix this problem temporarily
> 
> ```
> Vue.directive('cleave', {
>     bind(el, binding, vnode) {
>         const input = el.querySelector('input')
>         input._vCleave = new Cleave(input, binding.value)
>         input.addEventListener('input',(e) => {
>             vnode.componentInstance.newValue = e.target.value
>         })
>     },
>     unbind(el) {
>         const input = el.querySelector('input')
>         input._vCleave.destroy()
>     }
> })
> ```
> 
> Hope can see Cleave.js fix it in the future

Aaaah, I was looking forward to see this kind of fix! But unfortunatly it doesnt really fix this issue because the extra symbol still makes it into the variable. It just is not getting displayed anymore! And that is actually even worse, because the user doesnt know about what is going on, because he doesnt see the extra symbol anymore!

You can check on that when you put a watcher on the variable you are writing to!

**Comment by gutisalex** [comment]
Just figured a workaround for this... plain simple, just dont use v-model! Use 2 way binding instead...

Example: 
In your template:
`<input
  v-cleave="mask"
  :value="someValue"
  @input.native="onInput" />`

In your script:
`onInput(event: any) {
  this.someValue= event.target._vCleave.getFormattedValue();
  }`

**Comment by harlet** [comment]
Or https://github.com/nosir/cleave.js/issues/459#issuecomment-609066084
