### ISSUE TITLE
Requests that are not yet in buefy

### ISSUE THREAD

**Issue by febrihidayan** [buefy/buefy#1912]
### Description
There are some things that might help a lot of people.
Add icon to Navbar item
Add icon to Navbar Dropdown for notification display
Add new components like Filters in laravel nova

Thank's

**Comment by apolokaklab** [comment]
@febrihidayan semua telah tersedia bro, tinggal di custom sesuai dengan format bulma, untuk carousel dan skeleton dalam pengembangan, silakan bergabung di discord jika butuh bantuan.
