### ISSUE TITLE
Table: hide header label on mobile card view

### ISSUE THREAD

**Issue by camillo777** [buefy/buefy#1913]
Hello,
Is it possible to hide a header label of a column when in card mobile for the table component?

I am trying to format the card more like a real card and labels on some columns take too much space and have no more use and could be removed.

I would like to have the label of selected columns only when in table mode.

Thank you,
Camillo

**Comment by afwn90cj93201nixr2e1re** [comment]
Now it's append thru data-label, and that's fckd up.

We should have vertical mobile cards, not horizontal, coz sometimes (if label too long for 300px) its creating overflow on page.

**Comment by afwn90cj93201nixr2e1re** [comment]
@service-paradise can you make it?

**Comment by jtommy** [comment]
You should hide it by CSS using media query on mobile
