### ISSUE TITLE
Table editing required

### ISSUE THREAD

**Issue by sergpy** [buefy/buefy#1914]
A proposal to implement a popup field editor for b-table component, similar to https://quasar.dev/vue-components/table#Popup-editing

**Comment by jtommy** [comment]
@sergpy it's could be nice to have but without high priority at the moment

**Comment by absinthetized** [comment]
I second this!

**Comment by melogustavo** [comment]
Hello, I would like to take a look at this.
Is there anyone currently working at it?

**Comment by jtommy** [comment]
You are welcome, but I think it's no good to add in the core but only an example.
Anyway you might change my idea with a good reason :)

**Comment by service-paradis** [comment]
This could be done using custom column slot and Dialog component. I made a simple example:
https://codepen.io/service-paradis/pen/zYGzXae?editors=1011

**Comment by jtommy** [comment]
I agree with @service-paradis
