### ISSUE TITLE
How to position the field label

### ISSUE THREAD

**Issue by Rednas83** [buefy/buefy#1917]
### Environment

**Buefy** version: [0.8.6]
**Vuejs** version: [2.6.10]
**Windows10/Chrome**:

### Description

Label is not vertically centered
Label is divided in two lines
![image](https://user-images.githubusercontent.com/25219229/67695458-658a6700-f9a5-11e9-9401-c260efa10d26.png)

### Steps to reproduce

1. Run the html code below
```
        <b-field label="Start with master" horizontal>
            <b-switch></b-switch>
        </b-field>
```
2. Dynamically change the width of the window

### Expected behavior
![image](https://user-images.githubusercontent.com/25219229/67695813-05e08b80-f9a6-11e9-917e-7ec12ce67840.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
And what r trying to do?
Its bulma expected behaviour.

**Comment by Rednas83** [comment]
I am trying to turn off word wrapping.
I am also trying to vertically align the text with the checkbox (when word wrapping is active)

What is the easiest way to achieve this?

**Comment by afwn90cj93201nixr2e1re** [comment]
Its can create overflow.
Create nested fields, parent shoud have grouped/grouped multiline class/prop.

**Comment by Rednas83** [comment]
Do hou perhaps have an example for this?

Op wo 30 okt. 2019 14:09 schreef shel <notifications@github.com>:

**Comment by afwn90cj93201nixr2e1re** [comment]
Idk, but try this:
https://github.com/buefy/buefy/blob/dev/src/components/field/Field.vue#L58
<b-field group-multiline grouped horizontal>
<b-field :label="blabla"/>
<b-field>switch code</b-field>
</b-field>



As i said expected bulma behaviour, see at:
https://bulma.io/documentation/form/general/
