### ISSUE TITLE
BDatetimepicker shows no placeholder

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#1925]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10
**OS/Browser**: Chromium 77.0.3865.120

### Description

The `placeholder` property of `BDatetimepicker` appears to have no effect.

### Steps to reproduce

```
<script>
    export default {
        data() {
            return {
                date: null
            };
        }
    }
</script>

<template>
    <b-datetimepicker v-model="date"
                      placeholder="can't see this" />
</template>
```

**Comment by yxngl** [comment]
This can be easily fixed. But I notice placeholder is not working on mobile for both DatePicker and DateTimePicker, at least on my Android device.  It may be due to lack of support for placerholder attribute in input with the type datetime-local.
