### ISSUE TITLE
Replacing extra new lines to nothing instead single space on compilation step.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1927]
https://github.com/buefy/buefy/issues/1703

Close when it's gonna be fixed.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think, we can just add compiler options to vue-loader plugin in webpack/rollup script's.

**Comment by jtommy** [comment]
@afwn90cj93201nixr2e1re did you test it ? is it works ?

**Comment by afwn90cj93201nixr2e1re** [comment]
I can test it on rollup, im not using it coz it's using too much memory on compilation step, im prefer webpack, and yes, with webpack there no any useless single spaces.


Im gonna try on local machine and write something about it here, just wait, merging your updates into my branch.

**Comment by afwn90cj93201nixr2e1re** [comment]
Before fix:
![изображение](https://user-images.githubusercontent.com/9306996/68069913-62fe8780-fd80-11e9-832a-74153ff87b68.png)


After fix:
![изображение](https://user-images.githubusercontent.com/9306996/68070193-9fcc7d80-fd84-11e9-879f-0117014d6ad1.png)
![изображение](https://user-images.githubusercontent.com/9306996/68070512-b96fc400-fd88-11e9-804f-d7fbf421d015.png)

Removed:
https://github.com/buefy/buefy/blob/dev/src/components/autocomplete/Autocomplete.vue#L51
beetwen `{{ }}`

This cases also removed:
https://github.com/buefy/buefy/blob/dev/src/components/autocomplete/Autocomplete.vue#L44
(two new lines(\r\n) or (\n\n))

**Comment by afwn90cj93201nixr2e1re** [comment]
@Jtommy one more thing, why are you using whitespaces here?
![изображение](https://user-images.githubusercontent.com/9306996/68070853-2b4a0c80-fd8d-11e9-896c-0686823882c1.png)
