### ISSUE TITLE
b-modal is missing 'x' when used with portal-vue for buefy version 0.8.3+

### ISSUE THREAD

**Issue by cdrandin** [buefy/buefy#1929]
### Overview of the problem

**Buefy** version: 0.8.3+
**Vuejs** version: 2.5.2
**OS/Browser**: Chrome

### Description

`b-modal` is missing an 'x' when being used with `portal-vue`. I have tested this with different versions of buefy 0.8.3+ do not work.

The element (i.e. button) is entirely missing from the DOM.

### Steps to reproduce

Here is a working version [0.8.2 (sandbox example)](https://codesandbox.io/s/buefy-portal-gs6ef)
and here is a broken version [0.8.3+ (sandbox example)](https://codesandbox.io/s/buefy-portal-hh0d7)

Click on "Open Modal"

### Expected behavior

An 'x' to show up
### Actual behavior

'x' is missing

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you show an example? On fiddle for example.

**Comment by service-paradis** [comment]
Hum...
Checking the diff right now. Probably related to #1667

**Comment by cdrandin** [comment]
@service-paradis I am not sure that is the problem. The button is missing entirely from the DOM. So just messing with the position will have no effect.

**Comment by service-paradis** [comment]
I know it is weird, but it is the only changes between the 2 versions.
Not only the position have changed but the condition to display (`!animating`) which is toggled using animation events.

**Comment by cdrandin** [comment]
Yup, I was looking at that too. That is definitely it. I removed the conditional on the portal and was working on all other versions.

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you show fix?

**Comment by cdrandin** [comment]
There are 2 options for this.

* Remove `v-if` like `<portal to="...">` 
* if conditional is required then use `:disabled`  like `<portal to="..." :disabled="true/false">`

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you try to use portal with tooltip?
Coz tooltip sometimes creating overflows.
