### ISSUE TITLE
Disabled on button does not prevent @click

### ISSUE THREAD

**Issue by axtg** [buefy/buefy#1930]
### Overview of the problem

**Buefy** version: [0.8.5]
**Vuejs** version: [2.6.17]
**OS/Browser**: Firefox 71

### Description
I have the following element in my code

```
<b-button
   :disabled="meeting.archived === 1"
   @click="confirmArchive(meeting.token)"
   type="is-primary"
   icon-right="archive"
></b-button>
```

But with meeting.archived set to 1, the button will appear to be disabled, but the @click still works.

### Steps to reproduce

1. Add code as above
2. Click disabled button
3. Notice how the @click function is still executed

### Expected behavior

I expect the @click to no longer work

### Actual behavior

@click still executes the function

**Comment by service-paradis** [comment]
Related to #1855?

**Comment by afwn90cj93201nixr2e1re** [comment]
What about click.native event?

**Comment by axtg** [comment]
> 
> 
> What about click.native event?

Unfortunately no.

**Comment by jtommy** [comment]
@axtg could you provide it on codepen or similar ?

**Comment by afwn90cj93201nixr2e1re** [comment]
> 
> 
> @axtg could you provide it on codepen or similar ?

https://github.com/buefy/buefy/issues/1855#issue-505218965

**Comment by afwn90cj93201nixr2e1re** [comment]
https://codepen.io/arina11/pen/MWWrvMX?editors=1011

**Comment by afwn90cj93201nixr2e1re** [comment]
https://codepen.io/arina11/pen/WNNdEVZ?editors=1011
No bugs.
I think that ur code reactivity problem.
Show console.log output of this.meeting.


@axtg

**Comment by axtg** [comment]
Not quite when using the tag="a" in combination with :href="", as in this forked pen below.

https://codepen.io/axtg/pen/vYYdZYm?editors=1011

I was wrong in copying the initial code, I was assuming it held everywhere, but was wrong. @click events work as desired, the link type buttons do not.

**Comment by afwn90cj93201nixr2e1re** [comment]
event.preventDefault();

**Comment by afwn90cj93201nixr2e1re** [comment]
https://codepen.io/arina11/pen/YzzeQrE?editors=1010

**Comment by axtg** [comment]
Thanks for a quick think along.
Easiest then seems to move the redirect to a function, as the function does listen to :disabled by default. So @click="doRedirect(target)" and handle in the script part via window.location.replace(target).

I'll leave it up to smarter people to decide then if the disabled attr not working when using tag="a" is actually a bug or not.

**Comment by afwn90cj93201nixr2e1re** [comment]
You can try one more think, but im not sure that this is what you want:
`pointer-events: none;` add it for example to `a.button[disabled]`
something like:
```css
a.button[disabled] {
    pointer-events: none;
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
https://caniuse.com/#feat=pointer-events
