### ISSUE TITLE
Issue with error message when input has inlined button

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#1932]
This is probably duplicate of #506 but I'm getting no response there so I'll open a new issue to get some visibility:

c/p from my last comment there:

To reproduce use the fiddle from this example:

https://buefy.org/documentation/field#addons

and replace `<section>...</section>` with

```
    <section>
        <b-field>
            <b-numberinput size="is-small" min=5 value="2">
            </b-numberinput>
            <!--comment out the p element below to show the inlined warning-->
            <!--is-small is not affecting the result-->
            <p class="control">
                <button class="button is-small is-primary">Search</button>
            </p>
        </b-field>
    </section>
```

Then click on the input, and then outside of it to trigger the error message.

![Screenshot from 2019-10-20 14-38-29](https://user-images.githubusercontent.com/40859618/67159627-5d984a80-f347-11e9-8f2e-e74bff4fc757.png)

Sorry, I don't have an account with code pen, and I have no clue how to link directly to it. 

Here's how it looks when you remove the search button.

![Screenshot from 2019-10-20 14-42-33](https://user-images.githubusercontent.com/40859618/67159662-f333da00-f347-11e9-8299-a3a9230b1936.png)

**Comment by service-paradis** [comment]
Similar to #226 and #1226

**Comment by fungiboletus** [comment]
Looks like the addons feature is not designed to take into account `.help` messages yet.

The hack described in other issues consists of having another field arround the one with addons to display the message. This does not work here because the validation message will be in the field with addons anyway.

It's possible to make it look okayish with some custom CSS, the `border-radius` are not valid but that can be fixed as well.

```css
.field.has-addons {
  flex-wrap: wrap;
}
.field.has-addons .help {
  width: 100%;
}
```

**Comment by dmcbrn** [comment]
The solution from @fungiboletus works. Thank you!
Still hadn't test on my app but I don't think there will be any conflicts.

In the meantime, I need to spend some time on flex again :(
