### ISSUE TITLE
Call loading component from vuex/vuerouter

### ISSUE THREAD

**Issue by RomainMazB** [buefy/buefy#1942]
### Description

Like [dialog component](https://buefy.org/documentation/dialog/#from-outside-vue-instance), the loading component should be callable from inside of a Vuex store or from VueRouter instance or event from outside.

### Why Buefy need this feature

So we can attach loading state to all API call like this:
```JAVASCRIPT
import axios from 'axios'
import loading from 'buefy'

const instance = axios.create({
    // baseURL: '/api'
  })

const loading = buefy.loading
  
instance.interceptors.request.use(config => {
    loading.open()
    return config
})
  
  // before a response is returned stop nprogress
  instance.interceptors.response.use(response => {
    loading.close()
    return response
})

export default instance
```

**Comment by jtommy** [comment]
Try `import { LoadingProgrammatic as Loading }` and then `Loading.open()`

**Comment by RomainMazB** [comment]
Thanks for your quick answer but... How am I supposed to close it? Uncaught (in promise) TypeError: buefy__WEBPACK_IMPORTED_MODULE_1__.LoadingProgrammatic.close is not a function at eval

```JAVASCRIPT
import axios from 'axios'
import { LoadingProgrammatic as loading} from 'buefy'

const instance = axios.create({
    baseURL: '/api'
})

  
instance.interceptors.request.use(config => {
    loading.open()
    return config
})
  
  // before a response is returned stop nprogress
  instance.interceptors.response.use(response => {
    loading.close()
    return response
})

export default instance
```

**Comment by jtommy** [comment]
Open method returns an instance of loading component, you have to use it to call close method. For example `const myloading = Loading.open()` and then `myloading.close`
