### ISSUE TITLE
Split building/test/docs process

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1943]
Im really tired to download 
![изображение](https://user-images.githubusercontent.com/9306996/68069825-10709b80-fd7f-11e9-83f2-7a0be8fbc9ea.png)
this again and again...

**Comment by jtommy** [comment]
You should download it one time

**Comment by afwn90cj93201nixr2e1re** [comment]
No, im talking about that package is using only by docs, but we should download it also, and i think we should split docs out of buefy scope, into another one repo.

There is too much useless packages in buefy which really not realated to buefy at all.

**Comment by jtommy** [comment]
Yes, I thought to move docs to an other repo or split them in two packages

**Comment by afwn90cj93201nixr2e1re** [comment]
Maybe we should do it now?
