### ISSUE TITLE
Collapse improvments/fixes.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1945]
add `<slot name="header" :open="isOpen"/>` right after div collapse, for trigger slot replacing
add v-if on trigger slot, to catching conditions where is no trigger slot is prefered by user

rename default slot to `<slot name="body"/>`

**Comment by afwn90cj93201nixr2e1re** [comment]
`
<template>
    <div class="collapse">
        <slot name="header" :open="isOpen"/>
        <div
            v-if="isTrigger"
            class="collapse-trigger"
            @click="toggle">
            <slot name="trigger" :open="isOpen" />
        </div>
        <transition :name="animation">
            <div
                :id="ariaId"
                :aria-expanded="isOpen"
                class="collapse-content"
                v-show="isOpen">
                <slot name="body"/>
            </div>
        </transition>
    </div>
</template>
`

for example

**Comment by jtommy** [comment]
Why should I rename default slot to body ? And why do you need header slot ?

**Comment by afwn90cj93201nixr2e1re** [comment]
Coz i need to rewrite it for my self, you should rename it for better accesibility but, yes, you can leave this as is.

![изображение](https://user-images.githubusercontent.com/9306996/68072988-27c27f80-fda5-11e9-81f6-e73648b075e2.png)
For example i need 2 or more icons on header, one of them is removing something, another one open it.

**Comment by afwn90cj93201nixr2e1re** [comment]
? So, you won't add it?

**Comment by afwn90cj93201nixr2e1re** [comment]
? So, you won't add it? @jtommy 
I think it's very useful.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, you won't add it? @jtommy coz you closed again without any answer
I think it's very useful, now each component have label/header/body slots.

@service-paradis what do u think?

**Comment by afwn90cj93201nixr2e1re** [comment]
No, I'm not using header slot only for that, as you can see there is 3 different things in header, so, there is 2 buttons, but if we gonna use trigger slot, any click on trigger div gonna call toggle, so, if some one wanna place some text here, on copy he gonna toggle it 2 times.


I mean idk how i can explain it in another way.

As you can see only one button is related to trigger action, another one is deleting some array item, and one of them showing array index.

**Comment by jtommy** [comment]
But a collapse without `trigger` slot it doesn't make sense at the moment

**Comment by afwn90cj93201nixr2e1re** [comment]
But we can override trigger implementation with custom header.

I think it's better to have v-if/v-else here.

But im not sure, i think you really not getting the case.

**Comment by jtommy** [comment]
Probably i should define a directive but you should be able to simulate it using `toggle` method

**Comment by afwn90cj93201nixr2e1re** [comment]
Im now doing it.
But as you can see, https://github.com/buefy/buefy/blob/dev/src/components/collapse/Collapse.vue#L50 trigger is wrapped under trigger slot, that's why each click cause toggle by default.
> Trigger slot is global now and that's the problem.


There is gif, coz i really don't know how to describe it in another vector.
![GIF](https://user-images.githubusercontent.com/9306996/68089583-c02f3180-fe83-11e9-9721-5df15e3b8b4e.gif)

**Comment by service-paradis** [comment]
Can you use something ike this?
https://codepen.io/service-paradis/pen/qBBMqeK?editors=1011

**Comment by afwn90cj93201nixr2e1re** [comment]
That's interesting but not nice, coz dropdown's have same thing, that's why i wanna get header slot on it.
Same was with button wrappers, which translated to b-button component then.

**Comment by jtommy** [comment]
I agree with @service-paradis

**Comment by afwn90cj93201nixr2e1re** [comment]
:/
It's not nice, i have 100 collapses in code with diff logic. Why we can't just add slot instead wrapping it?
Like it was in https://github.com/buefy/buefy/issues/1303#issuecomment-479664634
