### ISSUE TITLE
Close event on modal not firing on close nor on cancel

### ISSUE THREAD

**Issue by mgambill** [buefy/buefy#1947]
### Overview of the problem

**Buefy** version: [0.8.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: Windows 10/Chrome

### Description

Close event not firing when using  this.$buefy.modal.open. Per documentation it should fire on cancel or close.

example here:  https://codepen.io/mgambill/pen/wvvpYKe 

### Steps to reproduce

a) click button to open modal, then click close button.

b) click button to open modal, click on the black to cancel

### Expected behavior

a) I expected close alert.
b) I expected both alerts to fire.

### Actual behavior

cancel alert fires when cancelling but never fires close event.

### Note

When stepping through the code in browser it appears the vue runtime looks at vm._events this property is empty but I can see vm.events has the expected property. Maybe vue expects events to be registered a certain way? A possible work around would be to add an onClose property similar to onCancel.

**Comment by jtommy** [comment]
```
const modal = this.$buefy.modal.open({ ...  })
modal.$on('close', () => ...)
```
