### ISSUE TITLE
b-field with message and control(s): message and label position fails

### ISSUE THREAD

**Issue by RomainMazB** [buefy/buefy#1949]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10
**OS/Browser**: Chrome

### Description

Using div.control in a b-field with message property fails: 

- message goes to the right instead of the bottom
- the label goes the the left instead of the top
- rounded corners of the input disappear

Already tried to nest b-field like said in #500 but didn't work.

### Steps to reproduce
A sample code copied/pasted [from the docs](https://buefy.org/documentation/field#addons): I just added a label and message to b-field.
Just remove the p.control, and all is ok.
https://jsfiddle.net/RomainMazB/9uq60hwa/

**Comment by jtommy** [comment]
@RomainMazB did you try to add `:addons="false` to `b-field` ?

**Comment by RomainMazB** [comment]
I didn't but it seems not to work. Or not how it should, see this [fiddle](https://jsfiddle.net/RomainMazB/fLjvwdh9/).

Search button, which I want to be a "control" of field, is just a button on bottom of field.

### Screenshots:
### From docs
![Screenshot from docs - I want this + message of bottom](https://user-images.githubusercontent.com/53976837/68153528-ee754580-ff45-11e9-972e-4fa81120fd83.png)
### without options:
Control is "ok" (not rounded but at the place where it should be), label and message position fails
![without options](https://user-images.githubusercontent.com/53976837/68153552-f7661700-ff45-11e9-81e8-7b855269cf6c.png)
### with options: false:
Control becomes just an usual button
![with options false](https://user-images.githubusercontent.com/53976837/68153560-fb923480-ff45-11e9-91d9-302c363bf5b4.png)

**Comment by service-paradis** [comment]
The workaround right now woud be to use `b-field` in another `b-field`. Unfortunately, you will need to adjust the margin before the help message. Something like this: https://jsfiddle.net/2u8kyh9d/1/

Not the ideal solution, but should work for you short term.

**Comment by zedrdave** [comment]
Sorry to reopen this topic, but for form validation purposes we need to have a way to force the message below the `b-field`, even when it has add-ons.

The fix suggested above only works if the message is statically created and not related to the control's validation…
