### ISSUE TITLE
Trouble with trap-focus in modal

### ISSUE THREAD

**Issue by daltonrooney** [buefy/buefy#1951]
### Overview of the problem

I saw the trap-focus prop was added to the Modal component in 0.8.6, which is great! This is an accessibility win and I might even suggest enabling it by default at some point in the future. I'm having a problem, though - even when I set it to true, I don't see the correct behavior. Here's my example pen: https://codepen.io/dalton/pen/BaaYNGJ

As you can see, after you hit the button and then hit tab a couple of times, you're still focused on the background page, not in the modal. 

Am I doing something wrong, and would there be a way to focus on the close button upon opening the modal, similar to [Micromodal](https://micromodal.now.sh/)?

Cheers.

**Buefy** version: 0.8.6
**Vuejs** version: latest

**Comment by jtommy** [comment]
@daltonrooney you're not using `trap-on-focus` prop on modal

**Comment by daltonrooney** [comment]
Thanks - I updated that pen several times for testing, must have deleted the prop at some point! I added it back now and am still seeing the same problem: https://codepen.io/dalton/pen/BaaYNGJ

Any ideas?

**Comment by service-paradis** [comment]
I think it is because there are no focusable element in your modal.
Here is the list of focusable element targeted by the `trapFocus` directive:
```
                                     a[href],
                                     area[href],
                                     input:not([disabled]),
                                     select:not([disabled]),
                                     textarea:not([disabled]),
                                     button:not([disabled]),
                                     iframe,
                                     object,
                                     embed,
                                     *[tabindex],
                                     *[contenteditable]
```

**Comment by daltonrooney** [comment]
Good point - I added the href attributes to the anchor tags, but focus still remains in the background when the modal is triggered. When I tab through, the focus eventually gets to the tags in the modal and then remains trapped.

Also, any thoughts to including the close button as a focusable element?

**Comment by service-paradis** [comment]
You are right.

The focus should probably be given to the first focusable element when the open . This should be done directly into the trapFocus directive (more specifically into the bind function). Would only need to be cautious with dialog that uses focusOn prop.

You are right abot the close button also. Dont know why it is not considered focusable in fact. Will need to take a look at this.
