### ISSUE TITLE
<b-upload> problem when buefy @0.8.6 ,vuejs @ 2.5.16 in vue-electron

### ISSUE THREAD

**Issue by lvbirui** [buefy/buefy#1952]
### Overview of the problem

**Buefy** version: [0.8.6]
**Vuejs** version: [2.5.16]
**OS/Browser**:electron

### Description

The b-upload button can not work when I update buefy from 0.7.10 to 0.8.6.
In version 0.7.10 everything is ok for <b-upload>,after I update buefy to 0.8.6.
When I click the upload button, the screen becomes white and the APP refresh. Then however I click the upload button, there is no response.

##PS：I wrote the description before is the '<b-upload>',but it can not display

**Comment by afwn90cj93201nixr2e1re** [comment]
Show an example, it's form, updating page coz it's not prevent default browser behaviour.

**Comment by service-paradis** [comment]
@lvbirui Please give us more information about your case. Show your code. It would be even better if you could create a codepen where we can reproduce the issue.
