### ISSUE TITLE
Clear icon for autocomplete

### ISSUE THREAD

**Issue by MartinTuroci** [buefy/buefy#1954]
### Description
It would be great to have a way of clearing the input of an autocomplete like for example google search does:
![image](https://user-images.githubusercontent.com/44962077/68139241-1787dd00-ff2a-11e9-9685-42960cb546bb.

There exists `clear-on-select` [option](https://buefy.org/documentation/autocomplete/) but it is not exactly what I want.

### Why Buefy need this feature
UX improvement.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think you can access to ref, then create specific div with position.

**Comment by melogustavo** [comment]
Hey @MartinTuroci, I will take a look at this.
