### ISSUE TITLE
Unable to display fontawesome 5 icon when loading with individual components 

### ISSUE THREAD

**Issue by rabbidas** [buefy/buefy#1955]
**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10

### Description

When import icon component directly, and specify pack and component attributes to "fas" and "vue-fontawesome", the icon won't display, and font-awesome throw the following error message.
```
index.es.js?ad3d:295 Could not find one or more icon(s) {prefix: "fas", iconName: "fa-bullhorn"} 
```
The correct icon name should be "bullhorn" not "fa-bullhorn", it is because the icon prefix is rely on defaultIconComponent constructor option.

 **src/utils/icons.js**
```js
const faIcons = () => {
    const faIconPrefix = config && config.defaultIconComponent ? '' : 'fa-'
```
It turns out that the issue is unable to set config options for individual components.
I wish to remove unused component for smaller bundle size.

### Code to reproduce
```js
import Vue from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
Vue.component('vue-fontawesome', FontAwesomeIcon)
import { Icon } from 'buefy'
import { library } from '@fortawesome/fontawesome-svg-core';
import { faBullhorn} from "@fortawesome/free-solid-svg-icons";
library.add(faBullhorn);
Vue.use(Icon)
```

```vue
<b-icon icon="bullhorn" size="is-small" pack="fas" component="vue-fontawesome"></b-icon>```

**Comment by afwn90cj93201nixr2e1re** [comment]
Can someone explain whay is the reason of using svg in html directly instead of css ehich does same thing?

**Comment by afwn90cj93201nixr2e1re** [comment]
Just set defaultIconComponent in buefy constructor to ''.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy probably fixed in #1992

**Comment by andrei-dracea** [comment]
Same problem. Any news on this?

**Comment by afwn90cj93201nixr2e1re** [comment]
You should use constructor options :/

**Comment by andrei-dracea** [comment]
Would be nice to be able to set config options on any component or some other way, without installing the complete Buefy component

**Comment by afwn90cj93201nixr2e1re** [comment]
We should think about how we can do it, coz it's not easy by first look.

**Comment by rabbidas** [comment]
A temporary solution, create our own Buefy plugin for Vue and set the config options

```javascript
import config from 'buefy/src/utils/config';
import { Tabs, Loading, Modal, Icon } from "buefy/src/components";

const MyBuefy = {
    install(Vue, options = {}) {
        // Options        
        config.defaultIconComponent = "vue-fontawesome";
        config.defaultIconPack = "fas";
        // Components
        Vue.use(Tabs);
        Vue.use(Loading);
        Vue.use(Modal);
        Vue.use(Icon);
    }
}

export default MyBuefy;
```

Then install the plugin.

```javascript
import Vue from "vue";
import MyBuefy from "./MyBuefy";

Vue.use(MyBuefy);
```

**Comment by cwilby** [comment]
A nice benefit of that solution is cleaning up `main.js`, thanks @rabbidas!

**Comment by squareloop1** [comment]
@rabbidas solution sounds nice, but does not work unfortunately. It seems like the registered components do not get the config as my icon component is still using the default MDI pack.

**Comment by jtommy** [comment]
@squareloop1 @rabbidas @cwilby i added the export of config component https://github.com/buefy/buefy/commit/9a887a67cedbceb0a09f32c36d5e234c4b97a030, for example:

```
import { Field, Input, ConfigProgrammatic } from 'buefy'

Vue.use(Field)
Vue.use(Input)
ConfigProgrammatic.setOptions({ ... })
```

**Comment by cypressious** [comment]
@jtommy I think there TypeScript declaration for `ConfigProgrammatic` is missing.

**Comment by jtommy** [comment]
@cypressious about `ConfigProgrammatic` you're right.. there is an open issue https://github.com/buefy/buefy/issues/2057 too
