### ISSUE TITLE
Add events `changing` and `changed` in tabs and steps

### ISSUE THREAD

**Issue by tychenjiajun** [buefy/buefy#1960]
### Description

Emit event `changing` before animation and `changed` after animation in tabs and steps.

### Why Buefy need this feature

Now tabs and steps have event `change` which is actually emitted before animation. It may be useful to have an event after animation. For example, focus input element in the new tab or step after animation.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/68801765-1bc4a080-0676-11ea-9fcd-5c6f1e1e08cf.png)


Input - before
change - after

So, you should use **nextTick** in change or input events?

**Comment by tychenjiajun** [comment]
@afwn90cj93201nixr2e1re Sorry, it doesn't work.

In this [codepen example](https://codepen.io/chankcccc/pen/xxxmrQP), I don't want blue color to be seen but it fails because the `red` color class applied **before** the animation start.

**Comment by tychenjiajun** [comment]
@afwn90cj93201nixr2e1re Here is [another example](https://codepen.io/chankcccc/pen/YzzdxXB). When switching between tabs, the input within new active tab get focus and the input within the previous active tab loose focus. If the input in the previous active tab is invalid, the invalid style is applied **before** the tab switching animation, which is not expected.

**Comment by afwn90cj93201nixr2e1re** [comment]
Em... Its not related to previous tab.
1) changing tab, applying focus, now input waiting for valid rule
2) changing tab, input loose focus, validating -> wrong
3) 1 tab input focus applying.

Everything is ok. You should use extra functionality, with blur, changed and call checkhtml5validity ot something like that.

**Comment by tychenjiajun** [comment]
@afwn90cj93201nixr2e1re How about comparing these two example.

[First](https://codepen.io/chankcccc/pen/YzzdxXB)

1. Input in tab `Pictures`get focus after mounted.
2. Click on `Music`, input in tab `Pictures` loose focus and turn red (which is not what I want but it can be solved by calling checkhtml5validity as you said)
3. Now input in tab `Music` gets focus **before** the animation.
4. Focus style is applied to the input in tab `Music` **before** the animation, which is also not expected.
5. An animation bug is also noticeable.

[Second](https://codepen.io/chankcccc/pen/zYYexBP)

1. Input in tab `Pictures`get focus after mounted. (Same as the first one)
2. Click on `Music`, input in tab `Pictures` loose focus and turn red. (Also same as the first one)
3. Tab button `Music` gets focus **during** the animation.
4. **After** the animation, the input in `Music` tab get focus and focus style is applied.

The second one is expected but the code is more verbose. If an event `afterAnimation` or `changed` is added in tabs, it can be achieved easier.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

**Comment by tychenjiajun** [comment]
@afwn90cj93201nixr2e1re I know the hooks but the transition is created within the `<b-tab-item>`

https://github.com/buefy/buefy/blob/dev/src/components/tabs/TabItem.vue

```js
    render(createElement) {
        // if destroy apply v-if
        if (this.$parent.destroyOnHide) {
            if (!this.isActive || !this.visible) {
                return
            }
        }
        const vnode = createElement('div', {
            directives: [{
                name: 'show',
                value: this.isActive && this.visible
            }],
            class: 'tab-item'
        }, this.$slots.default)
        // check animated prop
        if (this.$parent.animated) {
            return createElement('transition', {
                props: {
                    'name': this.transitionName
                },
                on: {
                    'before-enter': () => { this.$parent.isTransitioning = true },
                    'after-enter': () => { this.$parent.isTransitioning = false }
                }
            }, [vnode])
        }
        return vnode
    }
```

So following code doesn't work

```html
<b-tabs @after-enter="console.log(1)">
  <b-tab-item @after-enter="console.log(1)"/>
</b-tabs>
```

Add a watcher for `isTransitioning` helps

```js
watch: {
  isTransitioning (val) {
    this.$emit(val ? 'changing' : 'changed')
  }
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
Is .native working here? If not, them we should just add transition event's, but it's can spam. So, it's should be under another prop. isTransitionEvents.

**Comment by tychenjiajun** [comment]
`.native` obviously doesn't work here. Actually only one event need to be added after animation and it's only emitted if `animated` is true. So I think it won't spam.

**Comment by afwn90cj93201nixr2e1re** [comment]
Useless for others. But you can create PR.
