### ISSUE TITLE
Autocomplete for input fields

### ISSUE THREAD

**Issue by feralheart** [buefy/buefy#1964]
### Description
I would like to see an autocomplete option for input fields.

### Why Buefy need this feature
Becouse some projects may need an option to faster add words/values to inputs and textareas.

**Comment by service-paradis** [comment]
https://buefy.org/documentation/autocomplete ?

**Comment by afwn90cj93201nixr2e1re** [comment]
Emm... just provide it.

**Comment by feralheart** [comment]
@service-paradis Yes, that's an autocomplete field, but I want an option to make a textarea with autocomplete functionality. For example here at github: You place a # sign and than you can choose from issues

@afwn90cj93201nixr2e1re tried it but it doesn't work

**Comment by afwn90cj93201nixr2e1re** [comment]
Show an example on fiddle.
