### ISSUE TITLE
Table layout issues when using Searchable columns and Detail templates

### ISSUE THREAD

**Issue by mroberts-ecr** [buefy/buefy#1966]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10
**OS/Browser**: Chrome v77/Ubuntu (bionic) 18.04

### Description

When creating a table with both searchable columns and detail templates, the inputs added for the searchable columns are not aligned with the correct column in the grid.  The first input is aligned with the expand row icon instead of the first "real" column that it should be aligned with

### Steps to reproduce

See https://codepen.io/robertsmj1/pen/RwwyWYZ

![image](https://user-images.githubusercontent.com/56033527/68336507-8e4ce380-00ac-11ea-8be6-340c44ccbec6.png)

In the image, the first input filter applies to the 'ID' column and the second input filter applies to the 'first_name' column.

### Expected behavior

The inputs added by 'searchable' are aligned with the table columns to which they apply.

### Actual behavior

The inputs added by 'searchable' are aligned by column index rather than the column they apply to.

**Comment by service-paradis** [comment]
Similar to https://github.com/buefy/buefy/issues/1898
Fixed by https://github.com/buefy/buefy/pull/1924
Will be in the next release
