### ISSUE TITLE
Menu items expanded

### ISSUE THREAD

**Issue by grigoreve** [buefy/buefy#1970]
### Overview of the problem

**Buefy** version: v0.8.6
**Vuejs** version: v2.5.16
**OS/Browser**: Windows 7/Chrome

### Description

Good day, I'm trying to configure the MENU component that would simultaneously expand several branches. The EXPANDED property of the component is responsible for this, but it does not work correctly.
Sorry if I didn't understand something.

### Steps to reproduce

`<b-menu>
    <b-menu-list label="Menu">
        <b-menu-item icon="account" :expanded.sync="isExpanded1" label="Item 1" @click="isExpanded1 = !isExpanded1">
            <b-menu-item label="Subitem 1"></b-menu-item>
            <b-menu-item label="Subitem 2"></b-menu-item>
        </b-menu-item>

        <b-menu-item icon="account" :expanded.sync="isExpanded2" label="Item 2" @click="isExpanded2 = !isExpanded2">
            <b-menu-item label="Subitem 1"></b-menu-item>
            <b-menu-item label="Subitem 2"></b-menu-item>
        </b-menu-item>

        <b-menu-item icon="account" :expanded.sync="isExpanded3" label="Item 3" @click="isExpanded3 = !isExpanded3">
            <b-menu-item label="Subitem 1"></b-menu-item>
            <b-menu-item label="Subitem 2"></b-menu-item>
        </b-menu-item>
    </b-menu-list>
</b-menu>
`

JS:
`export default {
    data() {
        return {
            isExpanded1: true,
            isExpanded2: true,
            isExpanded3: true
        };
    },
...
`

### Expected behavior
Started:
![image](https://user-images.githubusercontent.com/57630105/68647789-c8483a80-052f-11ea-8978-afd093a68050.png)
It's OK

Click:
![image](https://user-images.githubusercontent.com/57630105/68647921-25dc8700-0530-11ea-9db3-0d6cad573aea.png)
Result:
![image](https://user-images.githubusercontent.com/57630105/68648019-65a36e80-0530-11ea-8d9d-c733ddd2eefc.png)
It's wrong. Item1 and Item3 should not collapse because the property is set by different variables.
Moreover if you click on this item two more times the EXPANDED property will stop working until you click on other items.

As a result, after a few clicks on the menu items, the behavior of the `b-menu-item` components becomes unpredictable.

### Actual behavior

I think it would be logical to control the EXPANDED property of several `b-menu-item`components when they are bound to a single variable. But when a property of each component has its own variable attached, the components should not affect each other.

**Comment by jtommy** [comment]
I've just added a prop `accordion` to menu component (default true).
In the next release you'll be able to set it to false and maintain the default expanded status
