### ISSUE TITLE
How to call function of parent after child modal is closed?

### ISSUE THREAD

**Issue by VajraEX** [buefy/buefy#1971]
Hello, I want to call a function belonging to the parent "after" the child modal is closed.
I have tried different approaches but none of them seem to work.
### Overview of the problem

    "buefy": "^0.8.6",
    "vue": "^2.5.11"

The function I want to call is the `updateTodayTodos()`.
This approach calls the function before the child modal is closed.

// Code inside parent.
// The method that calls the modal
>     
      openTodoModal(){
            console.log(this.propDayObj);
            this.$buefy.modal.open({
                parent: this,
                component: Todo,
                hasModalCard: true,
                customClass: 'custom-class custom-class-2',
                props:{propDayObj: this.propDayObj,  propTodos:this.propTodos}, 
            });
            this.updateTodayTodos();
        },

// Code inside child modal.
// The method that saves and closes the modal.
>     
       saveTodo(){
            //alert(this.inputVal);
            this.propTodos.push({
                description: this.inputVal,
                isComplete: false,
                dates: [this.date],
                color: "blue",
            });
            this.$parent.close();
        }

My goal is to automatically run `updateTodayTodos()` **after** the child modal is closed.
I'm new to JS in general, and would appreciate any advice that you can give.

**Comment by jtommy** [comment]
@VajraEX you have to listen `close` event on current modal instance, for example:
```
const modal = this.$buefy.modal.open({
  parent: this,
  component: Todo,
  hasModalCard: true,
  customClass: 'custom-class custom-class-2',
  props:{propDayObj: this.propDayObj,  propTodos:this.propTodos}, 
});
modal.$on('close', () => {{
  this.updateTodayTodos();
})
```
