### ISSUE TITLE
Datepicker `date-parser` not triggered

### ISSUE THREAD

**Issue by stanislav-polishchuk** [buefy/buefy#1974]
### Datepicker `date-parser` not triggered

**Buefy** version: [0.8.6]
**Vuejs** version: [2.6.10]
**OS/Browser**: MacOS 10.15 / Google Chrome 78.0.3904.87 (Official Build) (64-bit)

### Description

I want to change the format of the date from Datepicker in my `v-model` field. As far as I get from [Documentation](https://buefy.org/documentation/datepicker/) I can use `date-parser` for this purpose. But unfortunately, for some reason, neither `date-parser` callback nor native `onChange` is triggered when I'm using Datepicker component

### Steps to reproduce

Please - check out this [Codepen](https://codepen.io/stanislavpolishchuk/pen/LYYJNMm?editors=1011)

### Expected behavior

Whenever you select a new date-range, from my understanding parser function should be called, and VM should receive pre-processed value.

### Actual behavior

Parce function never called, I have no idea how to receive non-standard value format in my VM.

**Comment by yxngl** [comment]
`date-parser` is for `editable` datepicker to parse text input. Maybe you mean `date-formatter`?

**Comment by stanislav-polishchuk** [comment]
Hi @yxngl ,

Thanks for your answer, now it makes sense why it was not working for me. No `date-formatter` is not what I am looking for, because as far as I can see -  it is used for transforming date range array to a string that is displayed inside the input.

Anyhow, what would be the right way to specify the transformer for the date that I want to receive in my VM?
Currently it returns me a `Date()` instance. And what if I want a custom formatted string in the field that I specified in my `v-model`?

Thanks in advance.

**Comment by yxngl** [comment]
@stanislav-polishchuk You should use a `computed` value to format it in that case. `v-model` is always synchronized with internal value (Date).

**Comment by stanislav-polishchuk** [comment]
In case anyone will face same problem, here is a solution that I came up with:
```javascript
<template>
    <b-datepicker
        placeholder="Date"
        icon="calendar-alt"
        v-model="model"
        :max-date="new Date()"
        range>
    </b-datepicker>
</template>

<script>
    export default {
        name: "MyDatepicker",
        props: {
            value: {
                type: Array,
            },
            formatter: {
                type: String
            }
        },
        data() {
            return {
                model: this.value
            }
        },
        watch: {
            model: {
                immediate: true,
                handler (dateRange) {
                    const [from, to] = dateRange.map((date) => {
                        return this.$options.filters.dateFormat(date)
                    });

                    this.$emit('input', [from, to]);
                }
            }
        },
    }
</script>
```
Basically I just wrap Buefy component in my own, and `$emit` preformatted date.

@yxngl thank you for your assistance!
