### ISSUE TITLE
Buefy's Vee Validate docs are no longer valid for v3

### ISSUE THREAD

**Issue by israelmuca** [buefy/buefy#1977]
### Overview of the problem
Buefy's docs are valid only for Vee Validate v2; They need to be updated for v3

**Buefy** version: [0.8.6]
**Vuejs** version: [2.6.10]
**Vee Validate** version: [3.0.11]

### Description
Vee Validate has deprecated `vee-validate` directive completely. Now relying on a `ValidationProvider` component which wraps the fields.

The current documentation for Buefy should specify that it's for Vee Validate v2, and/or update for v3

**Comment by israelmuca** [comment]
Didn't mention, but I'm willing to contribute a PR for this if no one is working on it, hopefully this weekend or next week.

**Comment by jtommy** [comment]
@israelmuca sure! Thanks

**Comment by service-paradis** [comment]
We could use the vee-validate example from https://logaretm.github.io/vee-validate/guide/3rd-party-libraries.html#buefy for inspiration

**Comment by a-kriya** [comment]
Would it not be enough to just include a link to that in the docs instead of trying to maintain two versions of the same demo (one in VeeValidate and another in Buefy)?
