### ISSUE TITLE
b-table searchable bugs

### ISSUE THREAD

**Issue by willhatchVista** [buefy/buefy#1982]
### Overview of the problem

**Buefy** version: [0.8.6]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome 78.0.3904.97 Windows 10

### Description

3 separate issues: 
1.) when laying out the table using a template to define the columns searching for a non existent value causes the table to disappear.
2.) when using the template again, the search box loses focus when the table contents are updated
3.) when searching a boolean column there is an exception thrown when we try to do pattern matching on a bool when we expected a string.

### Steps to reproduce

See `App.vue` at https://codesandbox.io/s/buefy-table-search-bug-n05i2

**Comment by jtommy** [comment]
At the moment you cannot filter Boolean field (only number and input).
The other issues have been fixed https://github.com/buefy/buefy/pull/1967

**Comment by willhatchVista** [comment]
Thanks for the info! I think this works well for the boolean filtering
