### ISSUE TITLE
Table searchable prop problems

### ISSUE THREAD

**Issue by Sogl** [buefy/buefy#1983]
### Overview of the problem

**Buefy** version: [0.8.6]
**Vuejs** version: [2.6.10]
**OS/Browser**: Docker Ubuntu 16, latest Chrome

### Description

Just updated buefy from 0.8.3 to latest 0.8.6 add `searchible` to two columns and see much errors.

1. My table definition:
```vue
    <div class="columns is-multiline">
            <div class="column">

                <b-table
                        default-sort-direction="desc"
                        default-sort="id"
                        :paginated="true"
                        :pagination-simple="false"
                        per-page="10"
                        :data="data">

                    <template slot-scope="props">
                        <b-table-column field="id" label="id" sortable numeric>
                            {{ props.row.id }}
                        </b-table-column>

                        <b-table-column field="lastname" label="Фамилия" sortable searchable>
                            {{ props.row.lastname }}
                        </b-table-column>

                        <b-table-column field="name" label="Имя" sortable searchable>
                            {{ props.row.name }}
                        </b-table-column>

                        <b-table-column field="email" label="E-mail" sortable>
                            {{ props.row.email }}
                        </b-table-column>

                        <b-table-column field="created_at" label="Дата создания" sortable>
                            {{ $dayjs(props.row.created_at).format('D MMMM YYYY HH:mm:ss') }}
                        </b-table-column>

                        <b-table-column label="Действия">
                            <a class="button is-outlined is-small m-r-5" :href="route('manage.users.show', props.row.id)">Просмотр</a><a :href="route('manage.users.edit', props.row.id)" class="button is-small is-outlined">Редактирование</a>
                        </b-table-column>
                    </template>

                    <template slot="empty">
                        <section class="section">
                            <div class="content has-text-grey has-text-centered">
                                <p>
                                    <b-icon
                                            pack="far"
                                            icon="frown"
                                            size="is-large">
                                    </b-icon>
                                </p>
                                <p>Ничего нет</p>
                            </div>
                        </section>
                    </template>

                </b-table>



            </div>
        </div>
``` 

2. My `lastname` column with empty values:
![image](https://user-images.githubusercontent.com/7556290/68908188-9adfd480-075b-11ea-8141-7bc42cf386f1.png)
3. 1st problem. On every input  (russian or english) in `firstname` row with empty cells I see an error in console ``Error in callback for watcher "filters": "TypeError: Cannot read property 'match' of null"``
4. 2nd problem. Even if cells is non-null, every type show empty template:
![search3](https://user-images.githubusercontent.com/7556290/68909799-936efa00-0760-11ea-82c0-137d17efa2cd.gif)

Ok. Disable empty template and now it works better. If any letter exists in row, it show filtered result, but if not, empty table again with no way to restore the table except refresh the full page:
![search4](https://user-images.githubusercontent.com/7556290/68909995-45a6c180-0761-11ea-8e7b-cdbe8e68ec49.gif)

5. 3rd problem. All the time search field loose focus... you can type a word and can't continue without re-clicking 😞 

### Expected behavior

Search works fine.

### Actual behavior

See description.

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/pull/1967

**Comment by DazDotOne** [comment]
@jtommy do you know when this will be released? I've just come across the same issues noted above. 

I just updated to 0.8.8
