### ISSUE TITLE
Slider component supports multi touch

### ISSUE THREAD

**Issue by chengxg** [buefy/buefy#1995]
### Description

Slider component supports multi touch

### Why Buefy need this feature

Sometimes multiple slider components need to be operated at the same time on the mobile phone.

**Comment by afwn90cj93201nixr2e1re** [comment]
And what's is restriction right now? You can create 2 sliders and use each on same time, but it's dom blocking, so, it's impossible sometimes.

**Comment by chengxg** [comment]
> And what's is restriction right now? You can create 2 sliders and use each on same time, but it's dom blocking, so, it's impossible sometimes.

It seems that it's not easy to implement. Maybe based on < input type = "range" / > it can simply implement the slider component dragged at the same time, but it may be ugly.
