### ISSUE TITLE
Switch/Checkbox state is not properly synchronized between multiple components

### ISSUE THREAD

**Issue by cypressious** [buefy/buefy#1999]
### Overview of the problem

**Buefy** version: 0.8.6
**Vuejs** version: 2.6.10

### Description

Codesandbox: https://codesandbox.io/s/buefy-playground-rp7lf?fontsize=14

When you have `b-toggle`s (same for `b-checkbox`) inside different components that share the same state, they aren't properly synchronized.

Example

#### Comp.vue
```vue
<template>
  <b-switch :value="foo" @input="$emit('input', $event)">Switch</b-switch>
</template>

<script>
export default {
  name: "Comp",
  props: {
    foo: Boolean
  }
};
</script>
```

#### App.vue

```vue
<template>
  <div id="main">
    <Comp v-model="foo"/>
    <Comp v-model="foo"/>
    <div>foo: {{ foo }}</div>
  </div>
</template>

<script>
import Comp from "./components/Comp.vue";

export default {
  name: "App",
  components: { Comp },
  data() {
    return {
      foo: false
    };
  }
};
</script>
```

### Steps to reproduce

1. Toggle one of the switches

### Expected behavior

Both of the switches have the toggled state.

![grafik](https://user-images.githubusercontent.com/1191816/69157410-28694e80-0ae5-11ea-94a2-4ddfb243a46a.png)

### Actual behavior

Only one has the toggled state.

![grafik](https://user-images.githubusercontent.com/1191816/69157402-24d5c780-0ae5-11ea-852b-6b4cfa5fdb96.png)

**Comment by cypressious** [comment]
I had a look at the components and it seems that most of them keep an internal state as `data` in addition to the `value`. I understand this is necessary if you want to have a functional switch without binding `v-model` but how often is this really necessary? Wouldn't it simplify many of the components if they just bound to the `value` prop?

**Comment by focux** [comment]
I agree with you, I'm having the same issue with the Checkbox input. I think they should disable the internal state if the value prop is not undefined.

**Comment by afwn90cj93201nixr2e1re** [comment]
#1990 maybe.

What about using :key on components?

**Comment by service-paradis** [comment]
If you use `v-model` on a custom component, you need a prop called `value`.
This is your working example:
https://codesandbox.io/s/buefy-playground-e2nxl

**Comment by focux** [comment]
Using key did the work for me.

> If you use `v-model` on a custom component, you need a prop called `value`.
> This is your working example:
> https://codesandbox.io/s/buefy-playground-e2nxl

You [shouldn't need](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components) `value` when using `v-model`

**Comment by service-paradis** [comment]
In your [link](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components), it states:
> Bind the value attribute to a value prop
And the prop is called `value` in the custom component in the example

**Comment by focux** [comment]
Yes, and that agrees with what I said before. `v-model` is equivalent to `@input` + `value`, so you can use either `v-model` or `@input` + `value`. If you use `v-model`, you don't need to use the `value` prop. Maybe we're on the same page and I misunderstood you.

**Comment by afwn90cj93201nixr2e1re** [comment]
> You shouldn't need value when using v-model

So, but u are using v-model, which is proxy for @input and value, and u r not using watch or something like that, that's why its not reactive as @service-paradis said.

**Comment by afwn90cj93201nixr2e1re** [comment]
Oops.

**Comment by cypressious** [comment]
@service-paradis You're right, my example was wrong. Here's an updated example: https://codesandbox.io/s/buefy-playground-cgxks?fontsize=14&hidenavigation=1&theme=dark

```vue
<template>
  <div id="main">
    <div>
      <b-switch :value="value" @input="onInput">Switch</b-switch>
    </div>

    <div>
      <b-switch v-model="block">Block update</b-switch>
    </div>

    <div>Value: {{ value }}</div>
  </div>
</template>


<script>
export default {
  name: "App",
  data() {
    return {
      value: false,
      block: false
    };
  },
  methods: {
    onInput(value) {
      if (!this.block) {
        this.value = value;
      }
    }
  }
};
</script>
```

The `@input` handler is now conditional. If `block` is true, the `value` update should be ignored.

To reproduce the problem, first toggle the "Block update" switch. Then toggle the main switch. 

### Expected behavior

The `value` remains `false` and the switch remains in the off state

![grafik](https://user-images.githubusercontent.com/1191816/69238642-c10cd680-0b98-11ea-9f00-60cbdd065b7d.png)


### Actual behavior

The `value` remains `false` but the switch is in the on state

![grafik](https://user-images.githubusercontent.com/1191816/69238506-80ad5880-0b98-11ea-97bd-f745ee64a5ef.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
#1900

**Comment by service-paradis** [comment]
I now understand better what you are trying to do. I do not think this is the best way to achieve it. For me, the current behavior seem to be expected. The `onInput` is called after the value is changed so you can do something with it.

Why not disabling the switch if it needs to be blocked?
like @afwn90cj93201nixr2e1re, we would need to implement callbacks or something else if you really want to cancel the behavior.

**Comment by afwn90cj93201nixr2e1re** [comment]
That's how i have done it:
https://hastebin.com/lequsawonu.cs - input component
https://hastebin.com/racegigabo.js - mixin

Only one thing that you need - just uncomment needed `$forceUpdate();` in one of them, i recommend done it right in setter, but, its to heavy, so, that's why native v-model.trim/number etc. doing it inside onBlur.

**Comment by cypressious** [comment]
@service-paradis 

For once, it would be consistens with `<input>` and many other Vue components that only bind to the prop, not any internal state.

Secondly, it's just unexpected for a user that the `value` prop and the visual representation can be out of sync. Frankly, it just looks like a bug to me.

And finally, because it can trigger other bugs. I had a case in my application that looked something like the following

```vue
<template>
<table>
    <tr @click="toggleState">
        <td><b-checkbox :value="value" /></td>
    </tr>
</table>
</template>
```

After clicking the checkbox, the `value` gets of sync with the checkbox.

Why? Because the click changes the internal state of the component but no listener is attached. Right after the `@click` handler on the table row changes the prop which somehow confuses the component and this is the final result:

![grafik](https://user-images.githubusercontent.com/1191816/69264709-23310000-0bc8-11ea-9253-69e696e79cd2.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
Bro. Its general issue. And as servis said everything is fine, but should be adapted for setters/getters in computed.

**Comment by service-paradis** [comment]
It is how Vue works. Props are never synced back by default (without using `.sync`). That is why `v-model` exists.

In the `b-checkbox` example, you should have used `v-model` instread of binding only the `value` prop.

**Comment by cypressious** [comment]
@service-paradis I understand how Vue works, but I think you're misunderstanding my point. Exactly *because* Vue is not syncing back props automatically, the component should not assume that a click always triggers a state change.

If you haven't tried out the code snippet from https://github.com/buefy/buefy/issues/1999#issuecomment-556182835, please do and see for yourself how unexpected it behaves.

**Comment by service-paradis** [comment]
I probably dont understand your point. The snippet in the mentionned comment is not complete and I dont see anything wrong with it as it is.

**Comment by afwn90cj93201nixr2e1re** [comment]
> i recommend done it right in setter

I don't recommend do it inside setter, coz for example with trim we can't write any spaces inside input, so, it's should be done onBlur/onInput.

https://hastebin.com/owalevecah.js
https://hastebin.com/asefumoyox.cs

**Comment by afwn90cj93201nixr2e1re** [comment]
One more, with trim for example we should replace @input -> @change, coz that's how v-model works.

**Comment by afwn90cj93201nixr2e1re** [comment]
so, i just replicated vue v-model, but only for trim modifier.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/vuejs/vue/issues/5847#issuecomment-557664964 check, it's done now, so, if anyones need i can replicate it for other stuff like checkboxes and other tags which are supported by v-model.

**Comment by zedrdave** [comment]
@service-paradis I have been confronted to a similar issue and not sure whether I'm missing on an existing "best-practice" or if this is a bona fide bug:

I'm using `:value` (rather than `v-model`) synced to a Vuex state, updated through a Vuex action+ajax, triggered by `@input` (not directly relevant to the problem, but explains why I *need* `:value`/`@input`, rather than `v-model`):

If for any reason, I need to reject the update on the control (eg popping a confirmation dialog after checking the box, and user cancels action), there is no easy way to put the checkbox back in sync with its `:value`. Right now, I have to intercept the input element's `newValue` directly.

Wouldn't an elegant solution be to look for an optional return value from `@input` and cancel input update accordingly? (basically similar to how `native.input` works)

**Comment by lutzklai** [comment]
:+1: I'm running into the same issue as @zedrdave. My vuex state needs to programmatically set the state of the b-switch

**Comment by zedrdave** [comment]
@lutzklai seems this issue is now closed. I posted this as a separate issue: https://github.com/buefy/buefy/issues/2899

**Comment by OrenLX** [comment]
As @zedrdave mentioned, the issue is solved in the said issue.
For anyone else stumbling upon this issue, simply add `@click.native.prevent="YOURHANDLER"` to the <b-checkbox>, and control the state yourself.

**Comment by dawiediamond** [comment]
> As @zedrdave mentioned, the issue is solved in the said issue.
> For anyone else stumbling upon this issue, simply add `@click.native.prevent="YOURHANDLER"` to the `<b-checkbox>`, and control the state yourself.

This solved my problem. Thanks!
