### ISSUE TITLE
How to use dropdown inline?

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#2002]
### Overview of the problem

**Buefy** version: 0.8.7
**Vuejs** version: 2.6.10
**OS/Browser**: Firefox Developer Edition

### Description

The documentation doesn't seem to explain how to use `inline` - I assume this is one is needed to produce a dropdown button that lines up with the content. See Reddit for example - the user button is used as trigger and is placed inside the dropdown content.

### Steps to reproduce

1. Add `inline` to `b-dropdown`
2. Remove `trigger` button
3. Add `b-dropdown-item`

### Expected behavior

Creating an inline dropdown button trigger

### Actual behavior

Dropdown keeps active, even when using a v-model on `b-dropdown`.
If this isn't possible using the provided options, please let me know. :)

Thanks for your hard work, Buefy really has gain a lot of features and it's nice to work with!

**Comment by afwn90cj93201nixr2e1re** [comment]
Inline - always active.

**Comment by francoism90** [comment]
@afwn90cj93201nixr2e1re Thanks, that means it isn't possible. :)

**Comment by afwn90cj93201nixr2e1re** [comment]
I have written css rules for that, if you wanna inline with trigger slot i can post it.

**Comment by francoism90** [comment]
@afwn90cj93201nixr2e1re Yes please. :)

**Comment by afwn90cj93201nixr2e1re** [comment]
class="is-inline"

https://hastebin.com/zajupipido.cpp i dont remember which rule is needed.

**Comment by francoism90** [comment]
@afwn90cj93201nixr2e1re Thanks!
