### ISSUE TITLE
<b-upload required> does not style as is-danger

### ISSUE THREAD

**Issue by l2aelba** [buefy/buefy#2004]
### Overview of the problem

**Buefy** version: v2.6.10
**Vuejs** version: v2.6.10
**OS/Browser**: All

### Description

When we are using ```<b-upload required>``` does not affect anything like styling

![t3OXq6VPFi](https://user-images.githubusercontent.com/983458/69249395-143d5400-0bae-11ea-8145-e582994f76c6.gif)

### Steps to reproduce

1. Add ```required``` attr in ```<b-upload>``` (or [go to this](https://codepen.io/l2aelba/pen/jOOJbNv?&editable=true&editors=101))
2. Try to add a file
3. And remove the file

### Expected behavior

Should be styled as ```is-danger```
### Actual behavior

Nothing...

**Comment by service-paradis** [comment]
The required is added as a native attribute. Does it work if you use the native `<input type='file' required />`?

**Comment by jtommy** [comment]
Upload doesn't support this way because the content is a custom slot
