### ISSUE TITLE
[Feature Request] Skeleton Loaders

### ISSUE THREAD

**Issue by nixxholas** [buefy/buefy#2005]
### Description

Skeleton loaders are Call-To-Action (CTA) delaying elements that help developers and designers to implement an interface that can sustain a user's focus while loading massive data that requires more time than usual before a CTA.

https://www.sitepoint.com/how-to-speed-up-your-ux-with-skeleton-screens/

Vuetify has this implemented:
https://vuetifyjs.com/en/components/skeleton-loaders

### Why Buefy need this feature

Unlike isLoading, Skeleton loaders allow mass content elements to load in a visually appealing way. Users will be greeted with rows of skeleton loader elements that will help the user perceive the application's layout before the content completes loading.

Tables, cards can have a significant benefit because they are mainly used for mass content, it then allows the user to know the expected layout of these elements before they fully load.

**Comment by apolokaklab** [comment]
[Demo](https://buefy-dev.netlify.com/documentation/skeleton/)

**Comment by febrihidayan** [comment]
Ada tugas bagus buat @apolokaklab untuk komponen baru TimeLine, sejauh ini belum ada di Buefy

**Comment by jtommy** [comment]
@apolokaklab Nice, it could be nice add other templates

**Comment by nixxholas** [comment]
@apolokaklab Is your demo ready for the other elements?

**Comment by apolokaklab** [comment]
@febrihidayan Silakan baca roadmap terlebih dahulu jika disetujui untuk itu.
@jtommy @nixxholas I have 2 optional:
Simple: eg `<b-skeleton width="20px" :max-width="100" />`
Custom: eg `<b-skeleton :template="media" />`

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2394

**Comment by febrihidayan** [comment]
@jtommy how to add component timeline?
I've been waiting 😀

**Comment by jtommy** [comment]
You can use vertical step at the moment

**Comment by febrihidayan** [comment]
@jtommy okey.
I hope this feature is added 👍
