### ISSUE TITLE
Question: using multiple datasets

### ISSUE THREAD

**Issue by JLobato93** [buefy/buefy#2010]
Hi,

I would like to generate a table which gets data from multiple tables from my database. So i would have something like this:
`data() {  
   return {  
       customers: [],  
       users: [],  
       products[]  
     }  
}`

and customers, users and products will be filled with what i get with a fetch from my database.
Now i saw that you can do `<b-table :data="customers" >` but how would i be able to also include users and products in this table?

Can someone point me in the right way?

**Comment by jtommy** [comment]
@JLobato93 you should merge them in a unique array
