### ISSUE TITLE
Numberinput validation based on step size

### ISSUE THREAD

**Issue by Christilut** [buefy/buefy#2015]
### Description

Numberinput seems to validate input based on steps. This could be expected behavior but it it might not be, like in my case.

I have a numberinput with `min='1'` and `step='16'`. Usually my users add or subtract 16 from the input, but they can fill in any value (above the `min='1'`) they want. But when a user fills in a value that isn't divisible by `step` then there is a validation error.

So validation is based on the step size, which was unexpected to me. Maybe this is a design choice and if I want more control, I should make my own component and that's fine too. If that's the case, then maybe the numberinput docs need a short validation explanation.

**Comment by jtommy** [comment]
@Christilut the component follows input type "number" native validation. Btw you might disable it setting the prop useHtml5Validation to false

**Comment by Christilut** [comment]
Thanks, would be perfect to disable validation in my case. But is `useHtml5Validation` already in? I'm using 0.8.8 and it doesn't work

I'll close the issue

**Comment by jtommy** [comment]
Yes, it should be already available

**Comment by Christilut** [comment]
Ah, yeah it works to remove the icon but it seems the `title` tooltip with validation error message is still visible then.

**Comment by jtommy** [comment]
I think you should add novalidate to the form tag

**Comment by Christilut** [comment]
Right sorry, makes sense. I'm not using a form at all, but I'll change it.
Thanks!
