### ISSUE TITLE
Navbar dropdown not opening on MS Edge 42

### ISSUE THREAD

**Issue by jimmyangel** [buefy/buefy#2016]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [2.6.10]
**OS/Browser**: Win 10 1803, MS Edge 42.1734.1098.0

### Description

Buefy Navbar dropdown is not opening in MS Edge (version above). You can experience this directly on the Buefy documentation site, go to the first example, Info dropdown menu does not open when clicked.

It works fine on Chrome, Firefox and Safari.

**Comment by jtommy** [comment]
There is already an issue in Bulma repository https://github.com/jgthms/bulma/issues/2710.

**Comment by jimmyangel** [comment]
Here is the workaround I am using in my apps: 

```
<style lang="scss" scoped>

...

  @media only screen and (min-width: 1024px) {
    ::v-deep .navbar-item.has-dropdown.is-active>.navbar-dropdown {
      display: block;
    }
  }

...

</style>
```

**Comment by service-paradis** [comment]
Some Workaround are also mentionned in https://github.com/jgthms/bulma/issues/2503

**Comment by wesdevpro** [comment]
Closing because a workaround was found!
