### ISSUE TITLE
b-model clips at top and bottom of browser window

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#2019]
I have a b-table inside of a b-modal. As the number of rows in the table increases, the height of the b-modal increases until it expands to the top and bottom of the browser window.

At this point, the b-modal height expands beyond the height of the browser window causing the top and bottom of the b-modal to be clipped slightly.

Is there anyway to solve this problem? 

Aside from the clipping issue, I'd rather have the b-modal height stop expanding so the b-modal doesn't actually touch the browser top and bottom and there is a bit of a buffer.

See https://codepen.io/ken-elston/pen/XWWwrXe for an example

**Comment by yxngl** [comment]
The HTML markup for card is not correct. See the Component example.
