### ISSUE TITLE
Taginput type prop doesn't work with attached prop

### ISSUE THREAD

**Issue by jonathanjameswatson** [buefy/buefy#2020]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [0.7.5]
**OS/Browser**: Firefox 70.0.1 on Windows 10

### Description

When a tag in the taginput component has the attached prop, the attached button does not share the type prop as expected.

### Steps to reproduce

Use the following code:
```html
<b-taginput
  v-model="tags"
  attached
  type="is-dark"
/>
```

### Expected behavior

![image](https://user-images.githubusercontent.com/23344719/69498110-300d6680-0edc-11ea-9e6f-3ff4ee4269f8.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/23344719/69498041-7dd59f00-0edb-11ea-951b-7fcadf800a34.png)

**Comment by service-paradis** [comment]
This is the default behavior for Tag. You can see it here:
https://buefy.org/documentation/tag#closable

Maybe we will need a new prop for this. Or a refactor in the next breaking release.

**Comment by jtommy** [comment]
It could be nice add a way to customize a single tag

**Comment by jtommy** [comment]
@jonathanjameswatson close https://github.com/buefy/buefy/commit/22f6b3c53a0bb33d55a1612f52341c063612f250
