### ISSUE TITLE
Drag-drop B-Upload preview thumbnail not name

### ISSUE THREAD

**Issue by thekrys9** [buefy/buefy#2021]
Hi!

I want to ask that how can I set in B-upload preview a thumbnail before I really upload the images.

And how can I handle it one by one? 
I want to give special ID for a selected image.

Thanks

**Comment by jtommy** [comment]
@thekrys9 upload component only emit an array of files so you have to show them as you want, for example https://codepen.io/jtommy/pen/LYEPxWJ?&editable=true&editors=101
