### ISSUE TITLE
Input field with add-on does not display label correctly

### ISSUE THREAD

**Issue by Lukasiniho** [buefy/buefy#2029]
This is my first bug report. 
### Overview of the problem

**Buefy** version: 0.8.8
**OS/Browser**: Chrome Chrome 78.0.3904.97 on Mac OS X 10.15

### Description

An input field with an add-on does not display the label assigned to it correctly. Also, the input field does not have the intended rounded edges.

### Steps to reproduce

https://codepen.io/Lukasiniho/pen/bGGPMjm

### Expected behavior

The label should have the right position, as indicated by the second input field (see Codepen) as well as the right rounded edges.

### Actual behavior

The label is on the wrong position and the input field has the wrong rounded edges on the left-hand side.

**Comment by jtommy** [comment]
@Lukasiniho you should wrap the content of `b-field` into an other `b-field`.
For example: 
```
<b-field expanded label="Faulty label position">
  <b-field>
  <b-input></b-ifieldnput>
  <p class="control">
    <span class="button is-static">Add-on</span>
  </p>
    </b-field>
</b-field>
```
