### ISSUE TITLE
Design layout for default Buefy components in Figma

### ISSUE THREAD

**Issue by HUNTERxp** [buefy/buefy#2031]
### Description

Hello guys, do you have a design layout for default Buefy components in Figma?

### Why Buefy need this feature

It would be great opportunity for the project to get contibution from Designers community and improve vizualization of default components.

**Comment by edwardbattistini** [comment]
I'm quite keen to start on that. Are there any other designers keen too? 
I've started a file https://www.figma.com/file/YBr5zjbZkPKRbFwaLwglaj/Buefy-Figma?node-id=1%3A1189

**Comment by jtommy** [comment]
@edwardbattistini i'm not expert but I hope you'll find other designers. Btw thanks :)

**Comment by edwardbattistini** [comment]
will try to keep moving this one forward

**Comment by edwardbattistini** [comment]
Sorry for a late update here. I've now discovered that Figma can have unlimited contributors in pro plans
So now anyone with this [LINK](https://www.figma.com/file/YBr5zjbZkPKRbFwaLwglaj/Buefy-Figma?node-id=0%3A1)
can contribute and EDIT the file
