### ISSUE TITLE
b-timepicker value not refreshing constantly

### ISSUE THREAD

**Issue by apocalyarts** [buefy/buefy#2032]
### Description

Some users of my app would like to type times and directly submit by pressing enter. So far so good:

`<b-timepicker @keydown.enter.native="submit" v-model="time" editable></b-timepicker>`

However, b-timepicker would only update its value after the input looses focus. I could add an input event, but this gives me inconsistent values, depending on whether the user is typing or clicking on the hour/minute selector.

### Why Buefy need this feature

It would make it possible to allow inline editing with submit or direct feedback as the user is typing, etc.

**Comment by afwn90cj93201nixr2e1re** [comment]
Can be done with #2022

**Comment by afwn90cj93201nixr2e1re** [comment]
Not clever solution to close it, i agree with you, that we should add special for enter too, so, you should reopen this and ask jtommy for that.

But ofc listener should be attached to input as you said.
