### ISSUE TITLE
Not always convenient that modal is destroyed

### ISSUE THREAD

**Issue by bosim** [buefy/buefy#2033]
Sometimes it is really appreciated to keep the state of the modal, i.e. allowing the user to open the modal again, and the contents are the same. In my particular example I have a folder structure, where folders can be expanded. Currently when the modal is closed, and the user opens the modal again the state is reset since the component is destroyed, because of the ```v-if="isActive"``` in the beginning of Modal.vue, Using ```v-show="isActive"``` solves it for my point of view, however I am not sure about the possible side effects this "breaking" change may have?

**Comment by afwn90cj93201nixr2e1re** [comment]
Not related to buefy, use keep alive wrapper with v-if.

**Comment by bosim** [comment]
For give me my lack of knowledge, the parent component of the modal is kept alive. Could you give me an example how it is supposed to work? My issue seems to be a duplicate of #466

**Comment by afwn90cj93201nixr2e1re** [comment]
at first you should create modal component with props and other stuff, then you should import it inside parent component and register, you adding something like: computedCompName(){if(!motd)return null;return ImportedMotdComponent;}

inside template you r writing something like <keep-alive><component :is="computedCompName"/></keep-alive>

so, when local motd gonna be false it's gonna show nothing.


Also im not sure about absolute position, so, you should test.

or just use
<keep-alive>compname v-if var </keep-alive>


So, you can test it with hooking destroyed inside motd comp it's should be called once on parent comp destroying event.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://ru.vuejs.org/v2/cookbook/avoiding-memory-leaks.html#%D0%90%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D1%8B

**Comment by jtommy** [comment]
@bosim We'll add it soon
