### ISSUE TITLE
Datetimepicker: Select a range

### ISSUE THREAD

**Issue by Snejj** [buefy/buefy#2034]
### Description

It would be great if the Datetimepicker supported selecting a range of dates, much like the Datepicker.

### Why Buefy need this feature

Forms that require the input of a range of dates and times using Buefy currently need to resort to the use of multiple input components. This feature would greatly simplify support for date & time range input in forms created with Buefy.

**Comment by dmcbrn** [comment]
I think this should work. I have it implemented in my app but it's possible I didn't paste all of the necessary code or deleted something crucial. Let me know.

```
<b-datepicker ref="dates" v-model="dates" range></b-datepicker>

...
data() {
  return {
        value: [
            new Date(),
            new Date();
        ],
  }
```

Not sure why it's not documented.

**Comment by Snejj** [comment]
Yes, the datepicker does have support for range, but datetimepicker does not! I, too, am currently using the datepicker range functionality in my app, though, and it works great!

**Comment by jtommy** [comment]
@Snejj It's not in my plans at the moment, maybe it's better redesign timepicker before
