### ISSUE TITLE
Question: - How to set maximum width of column in b-table?

### ISSUE THREAD

**Issue by kulkasar** [buefy/buefy#2038]
I am using b-table and setting the width property as below. 
This width is minimum width and it changes if I remove a few columns from the table. 
My requirement is to fix the first column with a specific width value, Is there any way to achieve this?

 <b-table-column
            v-if="col.property == $t('Name')"
            :key="col.property"
            :label="col.title"
            :data-type="props.row.objectType"
            :data-nodeid="props.row.nodeid"
            :class="props.row.parentId ? 'fChildTD' : ''"
            field="label"
            **width="274"**
            :custom-sort="sortMethod"
            sortable
          >

Example - 
Name column has specific width - 
![Table1](https://user-images.githubusercontent.com/31200509/69868673-65e18f00-12d0-11ea-85eb-0b72d6ef2a39.JPG)

Name column width changes 
![Table2](https://user-images.githubusercontent.com/31200509/69868723-9e816880-12d0-11ea-8642-84b6b38c5faa.JPG)

I also want to fix the checkbox column width-
I am using the checkable property for checkbox
<b-table
      :data="nodesToDisplay"
      **checkable**
      :checked-rows.sync="checkedRows"
      @check-all="emitToParentCheckAll"
      @check="emitToParentCheck"
      hoverable
      bordered
      default-sort="label"
      @sort="SortEvent"
    >

**Comment by afwn90cj93201nixr2e1re** [comment]
`computed: { widthSize(col){if(col.id == 1)return '274px'; return 'unset'/'auto'; } }`
