### ISSUE TITLE
Need help changing the theme (bulmaswatch)

### ISSUE THREAD

**Issue by flakobatako** [buefy/buefy#2043]
Here's my package.json dependencies:

"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/vue-fontawesome": "^0.1.8",
    "@vue/composition-api": "^0.3.2",
    "axios": "^0.19.0",
    "buefy": "^0.8.8",
    "bulmaswatch": "^0.7.5",
    "core-js": "^3.4.3",
    "lodash": "^4.17.15",
    "node-sass": "^4.13.0",
    "vue": "^2.6.10",
    "vue-axios": "^2.1.5",
    "vue-extend-layout": "^2.0.6",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "prettier": "^1.19.1",
    "sass": "^1.23.7",
    "sass-loader": "^8.0.0",
    "style-resources-loader": "^1.3.2",
    "vue-cli-plugin-layouts": "^1.0.2",
    "vue-cli-plugin-style-resources-loader": "^0.1.4",
    "vue-template-compiler": "^2.6.10"
  }

What i'm trying:
npm install bulmaswatch

In entryfile main.js AFTER importing buefy:
import "bulmaswatch/lumen/_variables.scss";
import "bulmaswatch/lumen/_overrides.scss";

then npm run serve

Getting error:
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
2 │ @if $bulmaswatch-import-font {
  │     ^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/diego/Data/Git/KIOSK_Site/cliente/node_modules/bulmaswatch/lumen/_overrid
es.scss 2:5  root stylesheet

 @ ./node_modules/bulmaswatch/lumen/_overrides.scss 4:14-251 14:3-18:5 15:22-259
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.100.14:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

Please  help.

**Comment by theshark-fb** [comment]
I got the same error message trying to load bulmaswatch theme (darkly) using nuxt + buefy

**Comment by service-paradis** [comment]
Can you create a simple codesandbox reflecting the issue?

**Comment by theshark-fb** [comment]
> 
> 
> Can you create a simple codesandbox reflecting the issue?

I made a repo if you want to clone it and give it a try

[https://github.com/theshark-fb/sharknament](url)

**Comment by cricketthomas** [comment]
@theshark-fb were you able to solve this? I’m also trying to add Bulma Darkly to my Vue + Buefy app

**Comment by Wobbley** [comment]
I added bulmaswatch theme overrides just fine on the 11th of February on my desktop and project has been compiling fine (last commit was 7 days ago on the 7th of March). However after setting the project up on my laptop _yarn serve_ fails with the exact same issue. I guess some update somewhere messed something up, or there are some minor differences between my laptop and desktop. Or are there some conflicts in recent versions?

**Comment by namnguyen51** [comment]
Don't know if it too late or not, but you can fix this issue by import bulmaswatch variables before bulma scss and buefy scss

**Comment by skru** [comment]
As per the bulmaswatch docs: Make sure you import bulma before the _overrides.scss for the theme to work properly.

@import "variables";
@import "bulma";
@import "overrides";
