### ISSUE TITLE
Autocomplete side effect with vee-validate

### ISSUE THREAD

**Issue by erwanpoupard** [buefy/buefy#2046]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [2.6.10]

### Description
when i click to an autocomplete option with open-on-focus option and required rule, without typing, the field is invalid for 1s. 

### Steps to reproduce
here is a pen : 
https://codepen.io/erwanpoupard/pen/gObOPqW?editors=1111

1. Click inside autocomplete without typing anything
2. Select any option with a mouse click, without releasing the click
3. as u can see the field is invalid and red with error message. 
4. release click, the field is valid

### Expected behavior
the field should never be considered as invalid at the first selection

**Comment by service-paradis** [comment]
You are right. When you are clicking on an item of the list, the input focus is lost. Since the browser validate the required attribute on focus lost, the error gets displayed until the value is officially selected...

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/359dc9e738ba3b6420786dfea6da5dbf3b09a124
