### ISSUE TITLE
Custom sort in column

### ISSUE THREAD

**Issue by ygorlazaro** [buefy/buefy#205]
### Overview of the problem

**Buefy** version: [0.4.5]
**Vuejs** version: [2.3.3]
**OS/Browser**: GoogleChrome/Windows 10

### Description
Hello, guys, I'm looking for help here, because I can't find anywhere.

I am using the b-table object in an application, and it does its work very well, but now I am facing a problem while doing a sort in a column created by v-for directive.

My example's going below:

```
  <b-table-column :custom-sort="sortTotalMes" :label="labelTotalizado(mes.Mes)" numeric sortable :key="mes.Mes" width="20" v-else>
{{mes.TotalMes.currency()}}
  </b-table-column>
```

This code adds 12 columns, one for which month of the year, and the values is a float result. I know I can't use the default-sort configuration, so I did the custom-sort one, but the documentation, sadly, isn't that helpful.

My function is this:
```
            sortTotalMes(a, b) {
                return a.Total - b.Total;
            }

```

Well, with this, the column cannot sort, it is not working. What am I missing?

Thanks!

**Comment by rafaelpimpa** [comment]
That looks alright, why can't you use the default one? If it's float, should work nicely.

**Comment by ygorlazaro** [comment]
I found out the error. The problem is since this column is being added by a v-for, the name and value I want to sort on is dynamic. I kind of solved this adding columns by hand, but the code is messy.

```
  <b-table-column field="Jan.Trabalhos" :label="trabalhosNoMes('Jan')" numeric sortable width="30" v-if="config.tipoinfo === 'Quantidade'">
                                <a href="#" @click.prevent="detalhesMes('Jan', props.row.Idx)">{{ props.row.Jan.Trabalhos }}</a>
                            </b-table-column>
                            <b-table-column field="Jan.Total" :label="totalNoMes('Jan')" numeric sortable width="30" v-else>
                                <a href="#" @click.prevent="detalhesMes('Jan', props.row.Idx)">{{ props.row.Jan.Total.currency() }}</a>
                            </b-table-column>

                            <b-table-column field="Fev.Trabalhos" :label="trabalhosNoMes('Fev')" numeric sortable width="30" v-if="config.tipoinfo === 'Quantidade'">
                                <a href="#" @click.prevent="detalhesMes('Fev', props.row.Idx)">{{ props.row.Fev.Trabalhos }}</a>
                            </b-table-column>
                            <b-table-column field="Fev.Total" :label="totalNoMes('Fev')" numeric sortable width="30" v-else>
                                <a href="#" @click.prevent="detalhesMes('Fev', props.row.Idx)">{{ props.row.Fev.Total.currency() }}</a>
                            </b-table-column>
```

and it goes on. This way is working, but I really disliked it.

**Comment by byronferguson** [comment]
I was just testing this on my own table. It includes null values and a _special_ null value so I was using a custom sort function. 

v0.4.6 did not behave at all, rolled backed to v0.3.2 for proper functionality.

**Comment by Xelia** [comment]
I tried to use custom sort and got error "[Vue warn]: You may have an infinite update loop in a component render function."    

Here is repoduction: https://jsfiddle.net/s1pzajfm/

**Comment by rafaelpimpa** [comment]
@Xelia you have to declare the method: https://jsfiddle.net/s1pzajfm/1/

@ygorlazaro can you provide a repro with jsfiddle? You can use the one mentioned before to start

**Comment by Xelia** [comment]
@rafaelpimpa ok, that works, but what if i want to generate sort function using another method like this https://jsfiddle.net/6dsgch8j/  ? Cant get in to work. I need it when i have dynamic columns generated with v-for and need to choose compare method based on column.

**Comment by rafaelpimpa** [comment]
Maybe that's a Vue limitation (not sure), couldn't get to work without declaring.

**Comment by Xelia** [comment]
Well, vue creating dependency cycle in this situation https://jsfiddle.net/1w0tj43x/4/ . I think it can be solved by either changing way table works with columns or hacking around reactivity system somehow (have no luck with that yet).

**Comment by Tirke** [comment]
By using `backend-sorting` set to true + `@sort="mySortFunc"`, you can have full control over the sorting of your table (even if you don't sort in your backend). 
We use it this way for complex sorting requirements and even if it feels a bit hacky, it works 😄

**Comment by rafaelpimpa** [comment]
That's how it's supposed to work @Tirke, ``backend-sorting`` and ``@sort`` are supposed to work together ;)

**Comment by Tirke** [comment]
Yep I know @rafaelpimpa but the fact that we use those props even though we don't sort in the backend is quite strange. We are sorting in JS but we need to use `@sort` + `backend-sorting` to have full powers.
BUT : As you merged my PR about the `$emit` order I may take a closer look on how we do custom sorting on our biggest table ...
In fact it all resolve to the fact that everything could be easier if we had access to the `sort-order` while using `custom-sort` (without using `@sort`) but I didn't find a clear way to do that when I looked over the current implementation.
