### ISSUE TITLE
te

### ISSUE THREAD

**Issue by leocheungswell** [buefy/buefy#2050]
Error when running npm run watch with Buefy v0.8.8

Here is my app.js file.
require('./bootstrap');

window.Vue = require('vue');

import Buefy from 'buefy'
import 'buefy/dist/buefy.css'
Vue.use(Buefy)

Error Messages:

ERROR in ./node_modules/buefy/dist/esm/index.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/site/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/index.js 34:0-13
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/buefy/dist/esm/loading.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/site/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/loading.js 4:0-22 143:72-75
 @ ./node_modules/buefy/dist/esm/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/buefy/dist/esm/modal.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/site/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/modal.js 6:0-22 30:72-75
 @ ./node_modules/buefy/dist/esm/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/buefy/dist/esm/notification.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/notification.js 6:0-22 121:72-75
 @ ./node_modules/buefy/dist/esm/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/buefy/dist/esm/snackbar.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/snackbar.js 5:0-22 96:72-75
 @ ./node_modules/buefy/dist/esm/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/buefy/dist/esm/toast.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/toast.js 5:0-22 71:72-75
 @ ./node_modules/buefy/dist/esm/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/buefy/dist/esm/dialog.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/node_modules/buefy/dist/esm'
 @ ./node_modules/buefy/dist/esm/dialog.js 7:0-22 215:70-73
 @ ./node_modules/buefy/dist/esm/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve 'vue' in '/home/vagrant/Code/site/resources/js'
 @ ./resources/js/app.js 30:13-27
 @ multi ./resources/js/app.js ./resources/sass/app.scss

**Comment by service-paradis** [comment]
Had the same problem. Needed to clear npm cache and to reinstall dependencies again. Solved it for me.
