### ISSUE TITLE
@click doens't work in v-for

### ISSUE THREAD

**Issue by ghk829** [buefy/buefy#2053]
### Overview of the problem

**"buefy": "^0.8.6"
**Vuejs** version:     
"vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-good-table": "^2.18.0",
    "vue-highlightjs": "^1.3.3",
    "vue-router": "^3.0.1",
    "vue-tailwind": "^0.4.2",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.0"
**OS/Browser**:
 on MacOS

### Description

I'm working on vue-electron.
And I found the bug.

### Steps to reproduce

on vue App

`<b-radio-button type="is-info" style="padding:1em;" v-for="index in range(0,10)"
                            v-on:click="show('u'+index)">{{ index }}
            </b-radio-button>`

It doens't work. But, the other tag that is not in buefy works for it.
The othter tag of buefy doens't work too.

**Comment by jtommy** [comment]
Try using `v-on:click.native`
