### ISSUE TITLE
Switch component is logging prop type validation errors when value, false-value, and true-value props receive a Date

### ISSUE THREAD

**Issue by dstock48** [buefy/buefy#2054]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.10
**OS/Browser**: MacOS 10.14.6/Chrome 78.0.3904.108

### Description

In the docs for the Switch component, the prop types for `false-value`, `true-value`, and `value` are listed as "Any", however this is not true, as it is not accepting Dates. I would like to use the switch component in a way that true holds the value `null` and false holds the value `new Date()`

This would be used alongside the DatePicker component.

The switch label is "Immediately" and is being used to say there is no start date, thus the `null` value. But switched to false, the value should be today's date.

The Switch and DatePicker components are both using the same `v-model` so that when the switch is set to false, the DatePicker becomes visible with today's date pre-filled.

### Steps to reproduce

1. use a <b-switch> component with a `false-value` set to `new Date()`
2. toggle the switch on and off and see the prop type errors in the browser console

### Expected behavior

There will be no prop type errors

### Actual behavior

Logs prop type errors for `value` and `false-value` props indicating that a `Date` is not a valid prop type

**Comment by jtommy** [comment]
@dstock48 it's no a problem for me merge your PR but you really need it? Why don't you use Boolean in order to set a date after that (maybe a compouted or before submit a form)

**Comment by afwn90cj93201nixr2e1re** [comment]
Why not?

**Comment by dstock48** [comment]
> @dstock48 it's no a problem for me merge your PR but you really need it? Why don't you use Boolean in order to set a date after that (maybe a compouted or before submit a form)

I realize that there are other ways of implementing this functionality, but for me in this moment, this is the way that made most sense and based on the docs and the expected behavior of the component, it should work without logging any errors.
