### ISSUE TITLE
Type definitions for components 

### ISSUE THREAD

**Issue by druppy** [buefy/buefy#2057]
### Description

There are some type definitions in buefy for helper functions, but there is none for any of the components. 

### Why Buefy need this feature

With vue becomming more and more typescript centric, tsx is even more relevant, not because it is nice but because of it's type safety.

**Comment by jtommy** [comment]
You're right, it's a feature to improve

**Comment by lonk** [comment]
Hey @jtommy ! Thank you for the lib, it's amazing !

Do you have any idea of when typings will be available for components ?

Thank you !

**Comment by jtommy** [comment]
For Vue 2 I don't know to be honest, probably with Vue 3 I'll add them natively

**Comment by lonk** [comment]
@jtommy thanks for the quick reply !
We currently have to stick to vue2, waiting for the vue3 ecosystem to be mature enough. I think I'll try to write some typings for our used components.
I'll open a PR if I do so :)

**Comment by jtommy** [comment]
That's great, thanks

**Comment by wesdevpro** [comment]
Hello, from three years in the future 🤣 Does anyone know if I should just close this PR or should this still be a goal for Buefy v2?
@lonk @jtommy @kikuomax @wesdevpro

**Comment by wesdevpro** [comment]
Closing because this feature is already being implemented [here](https://github.com/ntohq/buefy-next/issues/151) for Buefy Vue3. However, we will not be supporting this feature for Buefy Vue2.
