### ISSUE TITLE
Table Rows: prevent right click

### ISSUE THREAD

**Issue by mewcrazy** [buefy/buefy#2059]
Hello, I'm trying to prevent right clicks on buefy table rows. The @contextmenu property on the table element gives me the ability to catch the right click event. 

But I'm not able to use @contextmenu.prevent.stop="rightClickUser", which prevents the regular browser context menu to pop up.

`[Vue warn]: Error in v-on handler: "TypeError: $event.preventDefault is not a function"`
`TypeError: $event.preventDefault is not a function`

Can you give me a hint how I can achieve my goal with buefy table?

I already tried setting the @contextmenu.prevent.stop on b-table, template tag within b-table, b-column, but none showed any effect.

Best wishes
Dennis

**Comment by jtommy** [comment]
@mewcrazy `contextmenu` event has two arguments: current row and dom event, you should call preventDefault on the second argument:
`@contextmenu="contextClick"` -> `contextClick(row, event) { event.preventDefault() }`

**Comment by mewcrazy** [comment]
It worked, thanks. I must have missed that in the documentation.
