### ISSUE TITLE
b-table column headers shuffling order when paginating

### ISSUE THREAD

**Issue by ffxsam** [buefy/buefy#2060]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.10
**OS/Browser**: Chrome (latest)

### Description

When paging through a table, the columns are getting shuffled around for some reason.

### Steps to reproduce

https://github.com/ffxsam/repro-buefy-table-bug

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/70353481-e41cd300-1886-11ea-99ed-326503b878b5.png)
How do you think, why?

**Comment by ffxsam** [comment]
@afwn90cj93201nixr2e1re I'm not quite sure what you're trying to point out, but if you've managed to find a problem in my code and changing something fixed it, let me know.

**Comment by afwn90cj93201nixr2e1re** [comment]
Show screenshot of 'shifting'.

**Comment by afwn90cj93201nixr2e1re** [comment]
shuffled  != shifting.

**Comment by ffxsam** [comment]
Yes, shuffled then - as in, column order is changing.

![Screenshot_2019-12-06 b-table-bug](https://user-images.githubusercontent.com/12532733/70354252-b444df80-1834-11ea-9b87-711c34717090.png)

![Screenshot_2019-12-06 b-table-bug(1)](https://user-images.githubusercontent.com/12532733/70354267-ba3ac080-1834-11ea-9b83-22c05966f1c7.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
```<b-table-column centered custom-key="abcd" width="40">
          MENU
        </b-table-column>```
try.

**Comment by afwn90cj93201nixr2e1re** [comment]
```
<b-table-column label="BTN" width="40" custom-key="btncolumn">
          BTN
        </b-table-column>
```
also for sure.

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems like sortable prop causing problems, just remove it.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://codepen.io/arina11/pen/QWwjvjp?editors=1010

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L548

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L606

**Comment by ffxsam** [comment]
> https://codepen.io/arina11/pen/QWwjvjp?editors=1010

Go to page 3. It's always the last page that triggers the bug.

> Seems like sortable prop causing problems, just remove it.

No? 😄 I need the column to be sortable.

**Comment by afwn90cj93201nixr2e1re** [comment]
> Go to page 3. It's always the last page that triggers the bug.

i know

Read stuff before.

**Comment by ffxsam** [comment]
I already spoke with @jtommy about this issue offline. We went through some of these things, like `custom-key`. It didn't help.

**Comment by afwn90cj93201nixr2e1re** [comment]
No, it's causing cause table doesnt rightly recognize currentSortColumn when defaultColumnSort setted.

**Comment by afwn90cj93201nixr2e1re** [comment]
Just run vue dev tools and check what's going on data/page changes or debug it. And you gonna end up with https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L606.

**Comment by ffxsam** [comment]
Thanks. Actually, even without default column sort, `sortable` causes problems. So, as I expected, it's a bug. I'll also point out that this bug must've happened with a recent update, because it wasn't an issue before, and I haven't changed this part of my code in quite a while.
