### ISSUE TITLE
Taginput with maxtags does not properly align the last tag

### ISSUE THREAD

**Issue by andrei-dracea** [buefy/buefy#2062]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.10
**OS/Browser**: Chrome

### Description

On the Taginput, when limited with `maxtags`, the last tag is not spaced properly to the last one.

### Steps to reproduce

Go to the [docs page](https://buefy.org/documentation/taginput#limits) and try to enter more than five tags in the second example.

### Expected behavior

I expect the tag to be evenly spaced to the others

### Actual behavior

![image](https://user-images.githubusercontent.com/1102117/70369026-baca6a00-18bb-11ea-8e90-63f2d1693858.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/c4d4e4c059e50b8e75d1d908fc02909ad74cd7b9/src/scss/components/_taginput.scss#L31

**Comment by andrei-dracea** [comment]
Yes I know what's causing it and fixed it, just thought I should mention it here.

**Comment by jtommy** [comment]
Sure, please make a PR :)
