### ISSUE TITLE
Slider doesn't show correctly

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#2066]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.10
**OS/Browser**: Firefox Dev.

### Description

Slider shows additional border.

### Steps to reproduce

1. Add slider component
2. Move slider

### Expected behavior

![image](https://user-images.githubusercontent.com/5028905/70436491-b81d6f80-1a89-11ea-9fcc-c60dc5121788.png)

```
.b-slider.is-medium .b-slider-track {
   #height: 0.625rem; // default
  height: 0.6rem; // fix
}
```

I don't know why changing the [height](https://github.com/buefy/buefy/blob/a6063372cf207de727c139466bd180c8b1fd5539/src/scss/components/_slider.scss#L18) works, some values seem break it again (`0.5rem`, ..).

### Actual behavior

![image](https://user-images.githubusercontent.com/5028905/70436439-94f2c000-1a89-11ea-9cac-1d65d6cff7b4.png)

**Comment by yxngl** [comment]
The description is not sufficient to reproduce. Why is the example working as expected? I suspect your customization changes something.

**Comment by service-paradis** [comment]
@francoism90 If you could create a codepen, it would really be easier to help you out. Unable to reproduce the issue here.

**Comment by francoism90** [comment]
@yxngl @service-paradis It's a bit difficult to trigger, you may need to resize the window multiple times, but it happens when using a dark background (or any other color that makes it visible). Take the following example, using the documentation:
![image](https://user-images.githubusercontent.com/5028905/70515712-1142dd00-1b36-11ea-8d8f-f31a1a85df94.png)

**Comment by service-paradis** [comment]
Weird, unable to reproduce using Chrome nor Firefox...
![captured](https://user-images.githubusercontent.com/12817388/70544726-916b4180-1b3a-11ea-85a3-3af016e98d58.gif)

**Comment by francoism90** [comment]
@service-paradis Thanks for trying to reproduce it. What browser and platform are you testing? 

I'm starting to think this is a rendering issue and not an issue related to Buefy.
Both seem to only happen on Firefox on my desktop (Linux) and on my Android with certain screen sizes. I don't have any (weird) add-ons or CSS stuff enabled, but I do have weird rendering issues occasionally on both platforms.

**Comment by service-paradis** [comment]
I tried with Chrome (Latest version) and Firefox (Latest version) on Windows 10

**Comment by apolokaklab** [comment]
I tried to with Chromium (Latest version) and Firefox ESR (Latest version) on Kali Linux is worked.

**Comment by francoism90** [comment]
Thanks for all the testing! I'll close this issue for now as no one else seems to experience this rendering issue.

When I do find a solution or workaround, I'll update the ticket.
