### ISSUE TITLE
Tooltip overflows on mobile devices creating unexpected horizontal scroll

### ISSUE THREAD

**Issue by rogeriotaques** [buefy/buefy#2067]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [2.6.10]
**OS/Browser**: macOS/ Chrome 78.0

### Description

Using tooltip on elements close to the edges (e.g on the right side of the page), when using mobile devices (or in this case, the mobile preview from Google Chrome DevTools), will either make the tooltip be cut by an `overflow-x: hidden` or create an annoying horizontal scrolling to the page.

### Steps to reproduce

1. Go to https://buefy.org/documentation/tooltip
2. Open the DevTools (from Chrome) with `CMD+ALT+I`
3. Set the responsive preview with `CMD+SHIFT+M`
4. Choose `iPhone 6/7/8` from the devices list
5. Scroll to the first example and tap (click) on the button named `Left`
6. Scroll down again to the `multilined` examples and tap (click) on the button named `Multline (large)`.

### Expected behaviour

I'm expecting to the tooltip rendered within the viewport, without overflowing the page boundaries. For the cases when tooltips are too close to the boundaries of the page, the tooltip should be adjusted and be dislocated to the right/left (depending on its current position) to fit in the viewport.

When a position adjustment is needed, I'm expecting to see the carrot (little triangle) still pointing to the target, even if not centralized to the tooltip content area. Or, perhaps, the tooltip moved to the opposite side, assuming that there is enough space available.

### Actual behaviour

When tooltipped elements are too close to the page edges, and the tooltips are large enough, they will be redered partially outside the viewport, hiding part of its content and/or creating an annoying horizontal scrollbar.

**Comment by asdfkaba** [comment]
Yeah, would be awesome if the position changed automatically. I have encountered the same problem and don't want to add an extra library for tooltips(e.g. popperjs)

**Comment by service-paradis** [comment]
Related to #1094 and #1316

**Comment by 4KDA** [comment]
+

**Comment by 4KDA** [comment]
> Yeah, would be awesome if the position changed automatically. I have encountered the same problem and don't want to add an extra library for tooltips(e.g. popperjs)

+++

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commits/dev

**Comment by GerryWilko** [comment]
@jtommy this issue still seems to be present. I have looked through your commits to dev made around April 27th and I can't find what you tweaked to fix this? I'll take a look at fixing it but just wanted to check which fix you made.

**Comment by jtommy** [comment]
@GerryWilko next version, new tooltip ;)
