### ISSUE TITLE
Question: Change label text color

### ISSUE THREAD

**Issue by JLobato93** [buefy/buefy#2068]
How do i change the color of the label text? 
If for example i write: 

`<b-field class="foo" label="Name">`

and in my style:
`.foo{
color:red;
}`

The color doesnt change and it says label makes it black.

now if i do 
`.label{
color:red;
}`
 in style nothing changes as well.

Can someone help me out?

**Comment by service-paradis** [comment]
There are a lot of possibility why it does no work in your case.

First, where did you put this style? In a Scoped SCSS Block? In a global SCSS file? Before or after importing Buefy styles?

Secondly, if you try to change label color using a custom class on field (ex. `<b-field class="foo" label="Name">`), you will probably need to target the `label` child. Something like `.foo > .label { color: red }`.

If you are trying to assign this style in a scoped style block, you will probably need to use `/deep/` or something equivalent to target a inner child (ex. `/deep/ .foo > .label { color: red }`).

**Comment by JLobato93** [comment]
Thank you, the /deep/ did it for me.
