### ISSUE TITLE
Datepicker - disable the focus border

### ISSUE THREAD

**Issue by devlerone** [buefy/buefy#2075]
Hi 

How I disable the focusable prop in a datepicker? (yellow border) I can't read anything about it in the API documentation.
![grafik](https://user-images.githubusercontent.com/57646473/70709531-5e14e800-1cdd-11ea-8ac4-ee76207f6eb2.png)

Additional remark:
Buefy is a first class job! Please keep it up, I love it.

**Comment by jtommy** [comment]
Thanks 🎉
I'm going to add `focusable` prop
