### ISSUE TITLE
Support Bulma 0.8.0

### ISSUE THREAD

**Issue by PieterGis** [buefy/buefy#2076]
Any idea when Buefy will start supporting Bulma 0.8.0 and/or it supports it already? 

The new version of Bulma has some nice new features we want to use, but we are waiting for Buefy to be 100% that everything will work.

**Comment by jtommy** [comment]
Next 0.9.0 version will add bulma 0.8.0 and other breaking changes

**Comment by daniel-dia** [comment]
When 0.9.0 is schedule to release?

**Comment by jtommy** [comment]
I'm waiting for Bulma 0.8.2 or to know next steps because probably Bulma is going to release v1 instead of 0.9.0
