### ISSUE TITLE
Safari - Tag Input, Autocomplete dropdown border does not disappear. 

### ISSUE THREAD

**Issue by landlight** [buefy/buefy#2079]
**Overview of the problem**
Autocomplete dropdown border does not disappear when dropdown closes

Buefy version: [0.8.8]
Vuejs version: [2.6.10]
OS/Browser: MacOS/Safari

**Description**
Autocomplete dropdown border does not disappear when dropdown closes

**Related** 
Issue #2014 , #1166

**Steps to reproduce**
1. Type anything that will show the autocomplete box 
2. If the item is less than the first autocomplete, it will leave the border 
Note: Using slots does not fix it as well as mentioned in #2014 . 

**Expected Behavior**
There is no border rending on the page

**Actual Behavior** 
![safari broken2](https://user-images.githubusercontent.com/7054264/70763876-3dee3300-1d88-11ea-8006-163ca66be0ff.png)

**Comment by yxngl** [comment]
I think this is a Safari bug with box shadow in combination with max-height and overflow.
[See example](https://codepen.io/yxngl/pen/bGNeMWK). Click the button to see the shadow remains, and interestingly if scrolling down first before clicking, it behaves fine.
