### ISSUE TITLE
contenteditable div crashes Safari

### ISSUE THREAD

**Issue by momander** [buefy/buefy#2081]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.10
**OS/Browser**: MacOS 10.14.6, Safari 13.0.3

### Description

contenteditable div crashes Safari when the user tries to enter text.

### Steps to reproduce

1. Create a page or component which includes an editable div:

`<div contentEditable="true"></div>`

2. Open the page in Safari.

3. Place cursor in the div and begin to type.

### Expected behavior

The user should be able to enter text in the div.

This works in Chrome, Firefox and IE. Also, contenteditable divs work in Safari if I remove the Buefy/Bulma spreadsheet.

### Actual behavior

The beach ball of death appears and Safari becomes unresponsive.

### Investigation

Turns out this is a bug in WebKit: https://bugs.webkit.org/show_bug.cgi?id=202262

Using a contenteditable div, when text-rendering is set to `optimizeLegibility` and font-family includes `-apple-system`, the bug is triggered. This text-rendering and font-family combination is used by Buefy / Bulma. From the stylesheet:

```
html {
  background-color: white;
  font-size: 16px;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  min-width: 300px;
  overflow-x: hidden;
  overflow-y: scroll;
  text-rendering: optimizeLegibility;
  text-size-adjust: 100%;
}

...

body,
button,
input,
select,
textarea {
  font-family: BlinkMacSystemFont, -apple-system, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
}

```

### Fixing it

My fix is to override font-family for the editable div. I include the fonts from Bulma's stylesheet, **except** `-apple-system`, and Safari doesn't crash:

```
<div contentEditable="true"
  style="font-family: BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;"></div>
```

Maybe not the most elegant way of handling it, but it prevents crashes for my users.

These crashes could be prevented by modifying the Buefy/Bulma stylesheet. Or developers get to figure out a workaround like I did (but it did take me several hours to get to the bottom of it). Or maybe it's enough that this workaround is posted online, so developers can find it.

What do you think is the right way forward?

**Comment by afwn90cj93201nixr2e1re** [comment]
It's related to bulma.

**Comment by momander** [comment]
Adding some more thoughts on this matter.

There are some good reasons not to change anything in Buefy/Bulma:
* This is clearly a WebKit bug, not a Buefy/Bulma bug.
* The WebKit bug has been fixed and future versions of Safari will presumably not crash.
* Contenteditable divs are not commonly used.
* Simply removing the -apple-system font from the stylesheet would perhaps lead to a slightly worse reading experience for all Safari users, just to prevent crashes for the few users who visit web apps making use of contenteditable divs.

Reasons to modify Buefy/Bulma:
* It is within the power of Buefy/Bulma to prevent these crashes, even if the root cause is a bug in another piece of software.
* If a developer gets reports from their users about crashes and starts investigating, they will soon discover that removing the Buefy/Bulma stylesheet prevents the crashes. It would look to them like this is a Buefy/Bulma problem, even if it isn't.
* In my web app, 22.5% of users are affected by of this bug. That is a significant number.
* Perhaps there is a way to write a fix that surgically removes the -apple-system font only for cases where it would cause a crash, instead of across all elements for all Safari users? I don't know enough CSS to tell if this is possible.

**Comment by momander** [comment]
Should we close this, and I file this bug in Bulma instead?

**Comment by jtommy** [comment]
@momander yes, It the best option at the moment
