### ISSUE TITLE
Taginput with autocomplete (not templated) shows empty dropdown options

### ISSUE THREAD

**Issue by altert** [buefy/buefy#2082]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [2.6.11]
**OS/Browser**: OSX 10.13.6/Chrome Version 78.0.3904.108 (Official Build) (64-bit)/Safari 13.03

### Description

Taginput with autocomplete shows seemingly empty dropdown. In fact dropdown works normally, but options show as empty (by can be still selected)

### Steps to reproduce

Use _taginput_ with _autocomplete_ prop but without template

### Expected behavior

Taginput with autocomplete shows dropdown with display values from _field_ prop

### Actual behavior

Taginput with autocomplete shows dropdown with display empty values

https://codepen.io/altert/pen/ExagMKQ?&editable=true&editors=101
(codepen is identical to the one on official documentation page https://buefy.org/documentation/taginput)

**Comment by service-paradis** [comment]
Duplicate: https://github.com/buefy/buefy/issues/2014
