### ISSUE TITLE
Table -> When using Searchable columns, Check All only selects rows on first page

### ISSUE THREAD

**Issue by rcoundon** [buefy/buefy#2083]
**Buefy** version: 0.8.8
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS Mojave Chrome 79.0.3945.79

I have a table with multiple pages of data and searchable columns.  When the rows are filtered by something that's typed into the searchable header, check all only selects the items on the first page.  I can't find any way to get rows that should be checked on subsequent pages.
Basically, I want to be able to use the filtered data list in other methods

### Expected behaviour
All rows that meet the searchable criteria are checked on all pages

### Actual behaviour

Only the first page of rows are checked

**Comment by yxngl** [comment]
I think this is actually true for all tables. Whether it is a bug or feature is a different question.

**Comment by rcoundon** [comment]
> I think this is actually true for all tables. Whether it is a bug or feature is a different question.

There's an issue discussed [here](https://github.com/buefy/buefy/issues/924) that talks about how to achieve this when check all is used, however this doesn't work when rows are filtered using the searchable header.
It looks to me from the component's code that an event could be emitted with an array of the filtered data, then this approach could be used.

**Comment by rcoundon** [comment]
Can this be converted into a feature request please?

**Comment by jtommy** [comment]
Table should check only current page because using backend pagination it's no possible check all data and I want to maintain the same behaviour using client side pagination.
Searchable feature is a particular case, I should think it's correct manage it in a different way

**Comment by rcoundon** [comment]
I see, can you suggest a different way?

**Comment by rcoundon** [comment]
I understand what you're saying, and the reason you would want to keep this the same. Having thought about this some more, I'm wondering if this is the way it should be.  When using backend pagination the implementer has full control of this functionality.  Whereas, if using client-side pagination, the implementer has no control (unless you can suggest a way around this?) so it feels to me like they need to be different.

**Comment by jtommy** [comment]
You might listen `check-all` event and manually add all data (`$refs.mytable.newData`) into `checked-rows` array

**Comment by rcoundon** [comment]
Hi - I've gotten this working but with what feels a little, shall we say, hacky...
I can check all the rows using the method you proposed but to deal with a deselect I'm keeping a boolean that is set to true on the first select of the check all box, then toggles false/true on each click.  
Using that I can listen to the @update:checkedRows and if the boolean is false, empty the checkedRows array.  
Can you think of a better way to handle the deselect?  If not, not a big deal as this seems to work, need to think if there are any edge cases.

If you do a check all and go to the next page of search results, deselecting one of the rows unticks the check-all box at the top, but interestingly only for that page, it turns back on if you go back to the first page.  I can understand why that happens and I think it's probably explainable to a user but looks a little odd at first glance.

Here's what it looks like:

```
<template>
  <div>
    <b-table
      ref="myTable"
      checkable
      paginated
      @update:checkedRows="handleDeselect"
      @check-all="handleCheckAll"
      :data="tableData"
      :columns="columns"
      :per-page="2" >
    </b-table>
  </div>
</template>

<script>
import sourceData from "../data/input.json";

export default {
  name: "HelloWorld",
  props: {
    msg: String
  },
  data() {
    return {
      tableData: sourceData,
      checkAll: false,
      columns: [
        {
          field: "id",
          label: "ID",
          width: "10",
          numeric: true,
          searchable: false
        },
        {
          field: "name",
          label: "name",
          width: "100",
          numeric: false,
          searchable: true
        },
        {
          field: "gender",
          label: "gender",
          width: "100",
          numeric: false,
          searchable: true
        }
      ]
    };
  },
  methods: {
    handleCheckAll() {
      this.checkAll = !this.checkAll;
      const table = this.$refs.myTable;
      table.checkedRows.push(...table.newData);
    },
    handleDeselect() {
      if (!this.checkAll) {
        const table = this.$refs.myTable;
        while (table.checkedRows.length > 0) {
          table.checkedRows.pop();
        }
      }
    }
  }
};
</script>

```
If you want to have a go, the data I set up was:

```
[
  {
    "id": 1,
    "name": "Ross",
    "gender": "male"
  },
  {
    "id": 2,
    "name": "Mel",
    "gender": "female"
  },
  {
    "id": 3,
    "name": "Rowan",
    "gender": "male"
  },
  {
    "id": 4,
    "name": "Leon",
    "gender": "male"
  },
  {
    "id": 5,
    "name": "Jean",
    "gender": "female"
  },
  {
    "id": 6,
    "name": "Steph",
    "gender": "female"
  },
  {
    "id": 7,
    "name": "Paul",
    "gender": "male"
  }
]


```

**Comment by jtommy** [comment]
@rcoundon that is an example https://codepen.io/jtommy/pen/eYNerNd?editable=true&editors=101

**Comment by rcoundon** [comment]
I think the workaround is acceptable, thanks for sharing.
