### ISSUE TITLE
Add @font-display: swap

### ISSUE THREAD

**Issue by Christilut** [buefy/buefy#2084]
# Description

I performed a Lighthouse audit on my app and the Buefy homepage and it recommends using `@font-display: swap` to prevent invisible text before the font is loaded. More info [here](https://web.dev/font-display/)

### Why Buefy need this feature

I'm not a font nor a SEO expert but if this doesn't have any downsides, perhaps it can be added?

**Comment by service-paradis** [comment]
I love this property, and it is great to have text on screen really fast, but I dont know if we should assume swap as a default value. It may not be a desired behavior.

For example, I'm using some custom font for part of my website. I tried the swap properties, but it first shown the text using a really different font, and then there was a flash and the font got swapped.

If we change this default behavior to swap, it should be in a breaking release. This way, people could change this behavior when needed on specific font. Curious to see what other people think of this!

Someone already ask this for Bulma. Unfortunately, there was no answers. But maybe, you could also try to revive this discussion there also: https://github.com/jgthms/bulma/issues/2509

**Comment by Christilut** [comment]
I'll try, thanks. Should be in Bulma instead of Buefy yeah
