### ISSUE TITLE
Support Blur event in TimePicker

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#2085]
I want to get a blur event (or some event) when the time is changed and the user exits the field.

Currently @blur doesn't work as expected however its not listed as a supported event in the docs.

What happens now

1. Click into the timepicker field, popup appears, click outside the field, popup closes and blur occurs

2. Click into the timepicker field, popup appears, select hour or min and blur occurs. Click outside to close popup, no blur.

What I'd like is to get an event  after the user selects a time and exits the field.

The input event is not ideal because it fires every time a time component changes (hour, min, etc). Same with using a watcher and v-model.

https://codepen.io/ken-elston/pen/XWJNpzZ?editors=1011

**Comment by Christilut** [comment]
Looks like this is missing on Datetimepicker? Just happened to ran into the same issue but I'm using the Datetimepicker instead
