### ISSUE TITLE
b-tabs, expanded, can't be customized

### ISSUE THREAD

**Issue by jogyth** [buefy/buefy#2086]
### Overview of the problem

**Buefy** version: [8.8]
**Vuejs** version: [4.1.1]
**OS/Browser**: Chrome

Try to add "is-danger" (or any of the standard classes) to the b-tabs type. Tested only on the expanded tabs. 

### Expected behavior
Tabs should change color.

### Actual behavior
Does not change color.

**Comment by yxngl** [comment]
Coloring individual tabs is not supported in Bulma and Buefy. Active color can be customized with SASS variables.
