### ISSUE TITLE
Forking Bulma

### ISSUE THREAD

**Issue by a-kriya** [buefy/buefy#2090]
First, thank you for creating and maintaining this library.
I'd been excited to use Buefy, and in turn Bulma, for the first time a couple months ago. As my project grew, I started contributing back in the spirit of open source.

After briefly curating issues and PRs here and in Bulma, I addressed a couple of low hanging fruits, jgthms/bulma#2717 and jgthms/bulma#2718, that were merged promptly and I was glad as I appreciate responsiveness (no pun). Increasingly though, I've been running into stuff that makes it seem like things aren't really ideal in the other repo:

- jgthms/bulma#2540: two-line fix that has been sitting for over half-a-year, ultimately resulting in a workaround buefy/buefy@46f0bff31 here
- jgthms/bulma#1974, jgthms/bulma#2471, jgthms/bulma#2737, #1889: a cascading set of issues due to negligence in addressing it quickly, at best
- jgthms/bulma#1325 and its associated PR jgthms/bulma#1622: something that's been hindering the users for a couple years but has not received any response from Jeremy.

Being opposed to ideas is one thing, but ignoring contributor's work seems like an unacceptable way to manage an open-source project. I'm [not the first to feel similarly](https://github.com/jgthms/bulma/issues/2374).

As Vue rapidly gains users, Buefy stands to do so as well, but perhaps not at its full potential when it's tied to a poorly maintained upstream, hence this proposal.

**Comment by GabMic** [comment]
That's a good idea but requires some work as it is a huge repo.

**Comment by DonNicoJs** [comment]
Totally uncalled but I am chiming in here: I was once in a very similar situation, but it paid not to fork. 

Keep asking the maintainer to elevate someone to contributor, or even better open an organisation and add people to the team. Eventually it will pay off

**Comment by service-paradis** [comment]
I agree that it could be hard to maintain a fork of Bulma, and I'm not sure it is a good idea to do so.
But, @syn-zeta is not entirely wrong about Bulma lack of maintenance.

It would be a really good idea if he could elevate someone to help him out sorting issues and PR. Unfortunately, there was a [discussion](https://github.com/jgthms/bulma/issues/547) about this back in 2017, and nothing was made.

**Comment by syn-zeta** [comment]
@DonNicoJs Not uncalled; this ticket is meant for discussion, especially from existing contributors and maintainers : ] Looks like what you suggest has been tried for a while now. From 2017 at the link in the above comment, till https://github.com/jgthms/bulma/issues/1325#issuecomment-480916917

@service-paradis Hmm, seems like he has a minimalist approach, which is probably what appeals to its users, and to Buefy's users (_lightweight_ in the tagline attracted me). At what point does it become impractical and idealistic? I do not understand what's wrong with the [fix for the progress bar animation in IE](https://github.com/jgthms/bulma/pull/2540/files).

**Comment by Tofandel** [comment]
@a-kriya He didn't mean the discussion was uncalled, just that he was uncalled but left is touch of salt anyway ;)

We will see if there is more movement regarding maintenance of the lib as it's still active, but there is indeed a big number of PR and issues that are disregarded and that let's users and developers frustrated (which is understandable when sometimes there is not even a reply)

If this continue, I do believe we could start a new bulma fork using a group of maintainers (Say 5) to handle the load, PRs and feature requests, and maybe merge newer versions of the old bulma into the repo until wider adoption

**Comment by fabiofdsantos** [comment]
Check this recent discussion: https://github.com/jgthms/bulma/issues/3074

**Comment by LoopsGod** [comment]
@a-kriya Can you re-open this? 

Following issues are still not being worked on; 

> * [jgthms/bulma#2540](https://github.com/jgthms/bulma/pull/2540): two-line fix that has been sitting for over half-a-year, ultimately resulting in a workaround [46f0bff](https://github.com/buefy/buefy/commit/46f0bff31) here
> * [jgthms/bulma#1974](https://github.com/jgthms/bulma/pull/1974), [jgthms/bulma#2471](https://github.com/jgthms/bulma/issues/2471), [jgthms/bulma#2737](https://github.com/jgthms/bulma/pull/2737), #1889: a cascading set of issues due to negligence in addressing it quickly, at best
> * [jgthms/bulma#1325](https://github.com/jgthms/bulma/issues/1325) and its associated PR [jgthms/bulma#1622](https://github.com/jgthms/bulma/pull/1622): something that's been hindering the users for a couple years but has not received any response from Jeremy.
> 
> Being opposed to ideas is one thing, but ignoring contributor's work seems like an unacceptable way to manage an open-source project. I'm [not the first to feel similarly](https://github.com/jgthms/bulma/issues/2374).
> 

I hope to make a change to the Bulma foregood by opening issue: [jgthms/bulma#3074](https://github.com/jgthms/bulma/issues/3074)

The fact of the matter is that Bulma is lacking behind severely due to a terrible maintainer who's focused on the wrong things and not creating a community or actually maintaining an open source project.

**Comment by a-kriya** [comment]
@LoopsGod @jtommy I don't see much coming out from re-opening this ticket. I realize I filed this at a time of frustration, and that is probably how some of us feel, perhaps justifiably. But I've gained a better understanding of where @jgthms is coming from, over time, reading his fair responses to such tickets even when they tend to have a hostile tone.

To be specific, this is what stuck with me from his response on the above ticket that you'd filed:
>The key point is that it's easy to add features, much harder to maintain them. And while creating a PR is straightforward, there is no responsibility to maintain; I'm the only one who has that, so I need to be careful.

I'm sure the maintainers of this project can attest to the amount of time and effort it takes to _consistently_ maintain a popular project. Jeremy seems to have single-handedly created and maintained the project for over four years, upon which great projects like Buefy have been built, so I appreciate that (along with the maintainers of this project). I notice that Bulma isn't even on v1 yet after all these years, so that says to me something about the level of perfection that he's aiming for.

It'd be nice if he was just a bit more interactive with the community when there are large "contribute" buttons on bulma.io, but I suppose that's not a requirement for open-sourcing your work.

In any case, I've created a separate "overrides.scss" file for dealing with any small issues myself. And for newer projects, if I don't think Bulma provides everything that I'll need, I look in other places.

**Comment by LoopsGod** [comment]
@a-kriya Thank you for your response. I appreciate your honesty, but I do have to disagree with you on some of those things. It's simple to say that it's difficult to maintain and therefore don't merge or disregard people's hard work on PRs, bug reports or anything like that.

I think you have a duty to be an actual maintainer to an open source project, and be actively maintaining instead of simply disregarding or not replying to people's hard work because you want to build it yourself or something? There are a ton of fixes pending in the bulma repo and nothing is being done with them. That's just brutal to the community, and makes the bulma project quite obsolete if you ask me.

**Comment by a-kriya** [comment]
@LoopsGod I think a proper approach involves filing a ticket to discuss a fix/improvement/addition along with some implementation details with the maintainers and gain their approval before working on a PR. That should save everyone's time. Putting that in CONTRIBUTING.md and referencing it in README should be helpful.

In any case, if the maintainers here wanted to fork Bulma, they would have chimed in with their support (or done it by now). As that is not the case, I think it's okay to close this, and we'll follow updates on your ticket.

**Comment by Tofandel** [comment]
For information, I discussed with @jtommy 
I will fork bulma and start maintaining it in September, there is a lot of work to do in case anyone is interested in joining as I plan on refactoring the entire documentation

Buefy can then switch to it in v1 or v2 depending on the timing it takes for the first release

No major change is expected except the refactor to css variables, the rest will stay as backward compatible as possible and a lot of bugs will be fixed and the most requested features will be added (Eg: flexbox helpers)

**Comment by LoopsGod** [comment]
@Tofandel Where can I reach out to you?

**Comment by Tofandel** [comment]
@LoopsGod My professional email => my first name, or full name or github username at tukan.hu your choice all will work ;) (giving it like this to avoid spams)
