### ISSUE TITLE
Using b-menu-item, a warning appears

### ISSUE THREAD

**Issue by doox8086** [buefy/buefy#2094]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [2.6.10]
**OS/Browser**:

### Description
use component 

    <b-menu>
        <b-menu-list label="Actions">
            <b-menu-item label="Logout"></b-menu-item>
        </b-menu-list>
    </b-menu>

### Actual behavior
A vue warning occurs
```
[Vue warn]: The .native modifier for v-on is only valid on components but it was used on <a>.
found in
---> <BMenuItem>
            <BMenu>
```

**Comment by doox8086** [comment]
upgrade nodejs version to 12+, no problem

**Comment by redskyburning** [comment]
@doox8086 did you do anything else? This looks like a reproducible bug, even after upgrading to the latest node v12.

I checked out the source and with b-menu-item the default value for the tag prop is `a`, which leads to an a tag being used and the Vue warning mentioned above. If you set the tag prop to something else (I tested with router-link) the issue goes away since there's no a tag.

I'm on Buefy 0.8.9 and I can see the relevant code at node_modules/buefy/src/components/menu/MenuItem.vue:59.

This will work:
```javascript
<b-menu>
	<b-menu-list>
		<b-menu-item
			tag="router-link"
			to="foo"
			label="test"
		/>
	</b-menu-list>
</b-menu>
```

But this will throw a warning

```javascript
<b-menu>
	<b-menu-list>
		<b-menu-item
			label="test"
		/>
	</b-menu-list>
</b-menu>
```

**Comment by treykaws** [comment]
Currently experiencing this as well. Have you had any luck mitigating the issue @redskyburning?

**Comment by redskyburning** [comment]
@treykaws Sadly no, I'm just ignoring the warnings for now. I may switch to using Bulma without buefy for these elements for the moment.

**Comment by treykaws** [comment]
@redskyburning that's what I ended up doing as well.

**Comment by Christilut** [comment]
Same problem here. Seems to trigger even on `b-menu-item(label='Users' icon='users')`

**Comment by germain-receeve** [comment]
Downgrading to `vue` and `vue-template-compiler` 2.6.10 solved the issue on our side (we were on 2.6.11).

Related issue: https://github.com/vuetifyjs/vuetify/issues/9999

**Comment by sharpcodepro** [comment]
Experienced the same. For the moment, the best solution seems just to use plain Bulma for the menu component.

**Comment by jtommy** [comment]
@sharpcodepro I'll take a look but it seems a VueJS issue. Btw it's only a warning

**Comment by PaulFish-Radius** [comment]
Experiencing same issue.

**Comment by service-paradis** [comment]
Related to this Vue problem:
https://github.com/vuejs/vue/issues/10939

**Comment by yangwao** [comment]
Yes, it happens when you use tag a on vue@2.6.11. 
To solve the issue, downgrade to vue@2.6.10. 
Keep up great work @buefy team 🙏📦

![image](https://user-images.githubusercontent.com/5887929/74344568-21cd3900-4dad-11ea-8266-c8bcf1fc97d7.png)

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/4a65d76a4d543f51b02acbd3457ed4a90d580ac1
