### ISSUE TITLE
blurry/unclear font in is-mobile-modal component

### ISSUE THREAD

**Issue by devlerone** [buefy/buefy#2096]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.11
**OS/Browser**: Google Chrome

### Description

google chrome shows the complete "is-mobile-modal" component extremely unclear. (December 2019 is the best example)  If I switch off the following setting in DevTool, everything is displayed perfectly:

"section: @media screen and (max-width: 1023px) .dropdown.is-mobile-modal>.dropdown-menu": 
- transform: translate3d(-50%, -25%,0);
(- webkit-transform: translate3d(-50%, -25%,0);)

### Steps to reproduce
1. go to https://buefy.org/documentation/datepicker/
2. Select the first example to open the calender
3. resize your window until is-mobile-modal is triggered

### Expected behavior

![grafik](https://user-images.githubusercontent.com/57646473/71173293-9464e100-2262-11ea-89f5-0d0d839b79e4.png)

### Actual behavior

![grafik](https://user-images.githubusercontent.com/57646473/71173513-397fb980-2263-11ea-8bc0-fe128e17b0d0.png)

**Comment by jtommy** [comment]
@devlerone i don't understand well looking at your screenshot, what's the issue ?

**Comment by devlerone** [comment]
@jtommy: thx you for your answer. Here some comparison pictures, the sharper example (on top) is always without transform: translate3d(-50%, -25%,0):

![grafik](https://user-images.githubusercontent.com/57646473/71314103-e5cbc680-2442-11ea-8f48-d4dcc6617532.png)

![grafik](https://user-images.githubusercontent.com/57646473/71314108-fd0ab400-2442-11ea-8a5f-be3f3b76ccf8.png)

![grafik](https://user-images.githubusercontent.com/57646473/71314123-23305400-2443-11ea-9143-c95bc8e833f1.png)

![grafik](https://user-images.githubusercontent.com/57646473/71314130-3b07d800-2443-11ea-9be2-f6a42d09ec35.png)

I hope I was of some help.

**Comment by dev-roc** [comment]
Yeah, same thing in our company app which use buefy as UI, it would be nice to see this modal bug fixed. :) Hooray to jtommy

**Comment by service-paradis** [comment]
Probably related to a Chrome Bug explained there https://stackoverflow.com/a/59363865/2774496

Unfortunately, the workaround is not ideal.
