### ISSUE TITLE
Disable step in steps component?

### ISSUE THREAD

**Issue by akmadian** [buefy/buefy#2098]
### Description

I think it would be a good idea to add the option to disable a step in the steps component. Currently, we can outright remove the step, but that's not very good for keeping consistency in the UI and UX. We could also just write some js and set various attributes and style properties to achieve this effect, but that seems like a fair amount of work for something that would make sense to me as a feature in Buefy.

I looked through the docs, and couldn't find anything like this, although it's possible I just glanced over it. Something kinda like [the steps component from Ant Design Vue's error status](https://www.antdv.com/components/steps/#Error-status) would be somewhat along the lines of what I mean.

When a step is set to disabled, it would turn red by default, and the default icon could be an x, or something like the `not-allowed` CSS cursor (third column from left, second one down): 
![24_cursor_styles](https://user-images.githubusercontent.com/28791774/71277559-1f4ce680-230a-11ea-9f7b-666175560751.gif)

When a step is disabled and the user progresses to it, the next step after the disabled one could be skipped to, and of course, it wouldn't be clickable.

### Why Buefy need this feature

Buefy provides lots of freedom and options in the functionality of its components, and this (at least to me) seems like a common feature that one might find themselves wanting.

BTW, I've been loving the package for months now. Great work!

**Comment by service-paradis** [comment]
Thanks for the request. As a workaround, for now, you could probably make the step items not clickable and use a custom navigation prop to step over disabled one.

**Comment by melogustavo** [comment]
Hey, I will take a look at this and then open a PR  😃

**Comment by jtommy** [comment]
@melogustavo thanks

**Comment by melogustavo** [comment]
@jtommy Whenever the clickable prop is not set, it won't let the step be clicked (behavior expected), but then when you want to go back a step, it will let you click even if it is not set.

This happens because of the following line of code:
<img width="438" alt="Captura de Tela 2020-03-13 às 11 05 59" src="https://user-images.githubusercontent.com/49168228/76627889-a16c3600-651a-11ea-9efc-383c930ed3e7.png">

Is the behavior of "clickable" expected to occur in the steps that passed? If it is not, then I will change it too.

**Comment by service-paradis** [comment]
@melogustavo 
I dont remember exactly why this choice was made when creating this component, but this is from the doc:
> Item can be used directly to navigate. If undefined, previous steps are clickable while the others are not.

**Comment by melogustavo** [comment]
Oh, Ok.. Kinda missed that part of the doc, sorry bout that 😀 

thanks for the return.

**Comment by wesdevpro** [comment]
I am closing this PR because a workaround was found.
