### ISSUE TITLE
Column with visible prop is appended the the end after re-render

### ISSUE THREAD

**Issue by aFluxx** [buefy/buefy#2099]
## Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [2.6.11]
**OS/Browser**:
Windows/Chrome

### Description

When using `visible` with a boolean parameter, once you go to the second page or perform a search, the column is removed

### Steps to reproduce

1. Create a column with visible prop, set it to a boolean changing parameter
```
<b-table-column
                field="favoriteResult"
                class="cursor-pointer"
                :visible="canUpdate"
                v-html="getStarMarkup(props.row.favorited)"
                @click.native="toggleFavorite(props, props.row.id)"
            ></b-table-column>
```

`canUpdate` comes from a blade view, and is either `true` or `false`. In my test case it was set to `true`

2. Paginate to another page:
GIF:
https://i.gyazo.com/717a1a611ced84c23b8885792ce22e1f.mp4

3. It seems that the data of the first column which has the visible prop (in my case a font awesome star) is being put into the second column (date).

### Expected behavior

The columns to stay the same

### Actual behavior

Somehow the second column is populated with the data of the first one.

Via Vue dev tools I can see that the `favorited` (1st) column is being pushed to the end of the `newColumns` array on a new render:

Before re-render:
![](https://i.gyazo.com/f8c2d20eeaed10dd6c78294dcbfe9673.png)

After re-render:
![](https://i.gyazo.com/b607938e6e79029f5a1415a2fd1b554d.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/issues/2060

**Comment by aFluxx** [comment]
Thanks,

I even discovered that if I put the column last instead of first, that it is no langer happening.

**Comment by jtommy** [comment]
Duplicate https://github.com/buefy/buefy/issues/2060

**Comment by jtommy** [comment]
@aFluxx please don't use v-html instead of default slot

**Comment by aFluxx** [comment]
@jtommy How can I run a function in the slot? I have a function that outputs html. But if I run the function between {{ }} the html gets escaped. And I found out that triple curly braces has been deprecated and that I should use v-html instead. (https://stackoverflow.com/a/30879500/10472059)

Any idea?

**Comment by jtommy** [comment]
@aFluxx ok but don't use it on table-column.

**Comment by aFluxx** [comment]
Hello @jtommy 

I won't, but is there an alternative to run a function in table-column?

**Comment by jtommy** [comment]
@aFluxx you might call it before to render and set the result to a field row or call it in inner component (div, span, ...)
