### ISSUE TITLE
Add "onImagesLoaded" event to carousel component

### ISSUE THREAD

**Issue by akmadian** [buefy/buefy#2100]
### Description

I'm working on a project that uses the carousel component, and the images being loaded are not served with the site itself, but fetched from an other source. It would be nice to (in some way) be able to know when the images are finished loading, either for toggling a loading spinner, or for any other thing. 

I think this could be done (at least in part) with the [onload HTML event (w3schools)](https://www.w3schools.com/tags/ev_onload.asp), and I think it would be wise to have it as an event instead of using a built in loading spinner as loading spinners aren't the only use case I can think of for this feature.

### Why Buefy need this feature

I think that loading spinners are pretty essential in a good UX because they give the user feedback that something is happening behind the scenes, like a resource being loaded. This feature would make it far easier for devs using Buefy to provide that feedback to the user.

**Comment by jtommy** [comment]
@akmadian why should carousel manage it ?

**Comment by apolokaklab** [comment]
@akmadian Hello, i am author carousel.
Do you mean like placeholder but for images?
Yes, i have other plans for feedback component, they **b-skeleton**, support loaded but not same like lazy load.

**Comment by akmadian** [comment]
@apolokaklab Yes, I originally opened this feature request because I wanted to be able to use a loading spinner while images are being fetched (or some other kind of placeholder), but I imagine that there will be other use cases for this feature as well.

@jtommy 
If you are asking why the carousel component specifically should manage it, it seems (at least to me) to make the most sense in terms of scope. (If it's not managed by the user, what else would it be managed by?) 
If you are asking why it should be managed by Buefy and not the user, I think it would be much more elegant, and offer better functionality and a better dev experience if natively supported. 

Users _could_ come up with a workaround and define the behavior themselves, but my impression is that Buefy generally tends to manage a little more, rather than less, behind the scenes. It just kinda makes sense to me that this feature would be managed by the carousel component instead of the user.

**Comment by apolokaklab** [comment]
@akmadian okay, so waiting b-skeleton or use lazyload for better handle your images.
Because this is specific that related the roadmap rules, and I adhere to it.
@jtommy closed.
