### ISSUE TITLE
Theme builder page

### ISSUE THREAD

**Issue by super2ni** [buefy/buefy#2101]
### Description

The idea is to append the documentation with a page that let the user customize the Sass variables in order to build a custom theme.
User should be able update the variables and interactively overview the changes on the UI.

### Why Buefy need this feature

Documentation is already good, but better documentation = even more stars?

**Comment by jtommy** [comment]
@super2ni there is https://bulma.dev/ at the moment but probably I'll add something when Bulma'll release CSS variables feature
