### ISSUE TITLE
Taginput autocomplete not show option

### ISSUE THREAD

**Issue by NgocLinhNguyen** [buefy/buefy#2104]
### Overview of the problem
Taginput autocomplete not show option

**Buefy** version: [0.8.8]
**Vuejs** version: [X.X.X]
**OS/Browser**: MacOS/Chrome

### Expected behavior

Has option to select

### Actual behavior
![image](https://user-images.githubusercontent.com/17584634/71391950-df9f3b00-2638-11ea-9bce-a919c5309c81.png)

**Comment by jtommy** [comment]
Already fixed, please see https://github.com/buefy/buefy/issues/2014
