### ISSUE TITLE
Tooltip slot template support

### ISSUE THREAD

**Issue by kwesterfeld** [buefy/buefy#2106]
### Description 

I would like to use the b-tooltip component with arbitrary html template/content.  Suggest providing an optional ”label” slot instead of label attribute. 

### Why Buefy need this feature

Provide developer with means to utilize excellent event handling and api flexibility in the tooltip component but complete control over presentation.  Using vue-gettext would make i18n easier as well, since translating attributes like label are not supported.

**Comment by jtommy** [comment]
Duplicate https://github.com/buefy/buefy/issues/972

**Comment by lfkwtz** [comment]
@jtommy  This and #1122 were closed as duplicates, but I don't believe either are. This is requesting the ability to display rich content within a tooltip.

**Comment by jtommy** [comment]
Sure, using a slot

**Comment by lfkwtz** [comment]
?

https://github.com/buefy/buefy/blob/dev/src/components/tooltip/Tooltip.vue#L13

the slot here allows you to display rich content which is then wrapped around the context of a tooltip, so when you hover, you see the tooltip.

but, how would one insert rich content within the tooltip itself?

**Comment by jtommy** [comment]
It's no possible now, it needs of a refactoring

**Comment by lfkwtz** [comment]
yes, that's why this shouldn't be closed as a duplicate of #972

**Comment by NickeManarin** [comment]
Hi @jtommy, do you have plans in adding the support for this (template support in tooltip content)?

**Comment by jtommy** [comment]
Sure, it's the v1 roadmap

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/f0cfa37b064b4aa43d4aa698ffdeffa30a85b0fd
