### ISSUE TITLE
b-button with tag="router-link" is functional dispite being disabled

### ISSUE THREAD

**Issue by cypressious** [buefy/buefy#2109]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.11

### Description

When a b-button has `tag="router-view"` and is disabled, clicking on it navigates to the target route.

### Steps to reproduce

```vue
<b-button tag="router-link" :to="{ name: 'route-name' }" disabled>
Click me
</b-button>
```

### Expected behavior

Clicking on the button does nothing

### Actual behavior

Clicking on the button navigates to route `route-name`

**Comment by jtommy** [comment]
Because it's a link and it doesn't allow to use disabled attribute
