### ISSUE TITLE
Call buefy modal from child component

### ISSUE THREAD

**Issue by mewcrazy** [buefy/buefy#2111]
Hello,

I'm trying to call/open a buefy modal by calling it from a childcomponent. (which appears a lot of times on one page, so I rather don't place the modal in that component)

What is the preferrably way? Currently I'm trying to call it like:

`openTaskModal: function(task_id) {
	this.$parent.$parent.$parent.$options.methods.openTaskModal(task_id)
},`

The call goes through, the openTaskModal method from the parent component gets executed too, but the modal stays closed. Any ideas how to work around this?

Best wishes

**Comment by jtommy** [comment]
@mewcrazy you might open a modal in the child component and comunicate the result using a central state (ex: Vuex) or an event bus
