### ISSUE TITLE
Limit the select options of month in Datepicker with max-date

### ISSUE THREAD

**Issue by Juneezee** [buefy/buefy#2114]
### Description

Datepicker `max-date` should limit month as well. For example, `max-date` is set to `1-1-2020`, then the month selection should only have January as the only option.

### Why Buefy need this feature

Improvements to the UI / UX

**Comment by jtommy** [comment]
@Juneezee why only a month?

**Comment by Juneezee** [comment]
@jtommy For example, since the `max-date` is set to 1st January 2020, then having Febuary, March, ..., December in the select options is trivial as all the dates in these months are disabled.

**Comment by jtommy** [comment]
Yes, probably you are right

**Comment by afwn90cj93201nixr2e1re** [comment]
That's domes, but why not, every date(month and year) change we should check is here available months or not and create new array or use display none and other stuff.
