### ISSUE TITLE
b-select must keep the placeholder option after resetting the data array.

### ISSUE THREAD

**Issue by SLMNBJ** [buefy/buefy#2115]
### Overview of the problem

**Buefy** version: [0.8.9]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome 79 macOS Catalina

### Description
I have a b-select component that have a placeholder ands disable attribute based on the data array length. If I fill the array and reset it (reassign the initial value), the placeholder will not be printed.

Codepen https://codepen.io/slmnbj/pen/eYmepeP

### Steps to reproduce

1. Set empty array as initial value of countries
2. fill countries array
3. set countries as empty array

### Expected behavior

The placeholder option must be rendered (as the first render, before the refresh).

### Actual behavior

No option attribute is rendered

**Comment by jtommy** [comment]
@SLMNBJ you should reset the select value too

**Comment by SLMNBJ** [comment]
@jtommy thanks. it works.
