### ISSUE TITLE
Allow use customize tag in b-button

### ISSUE THREAD

**Issue by oanhnn** [buefy/buefy#2123]
### Description

Buefy should allow config allowedValue of `b-button`'s tag property like plugin options.

```js
import Vue from 'vue'
import { Button } from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Button, {
  allowedTags: [
    'button',
    'a',
    'inertia-link',
    'span',
  ]
})
```

### Why Buefy need this feature

When i using **buefy** with [**inertia-vue**](https://inertiajs.com/), i can't set tag to `inertia-link`.
I think some library has custom link component will has same problem.

**Comment by jtommy** [comment]
It's only a warning to be honest, but of course we might improve this behaviour
