### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by AggressivelyMeows** [buefy/buefy#2127]
### Overview of the problem

**Buefy** version: 0.8.9
**Vuejs** version: 2.3.3
**OS/Browser**: Windows/Firefox

### Description

Injection attacks are possible if the user sets a variable and it is put into a toast, notification, modal, and snackbar. For example: {message: `Hello ${this.name}! How are you?`}. If the user were to set `name` to be: `<a onmouseover=alert(document.cookies)>click me!</a>` then it would leak the cookies when the component shows and the user hovers over the a tag.

I believe that this is a feature however it is not mentioned anywhere that these components do this. If possible, it would be great to update the docs that this is a possible issue. It might also be a good idea to add a variable to enable/disable html injection for these components.

If theres anything i can do to help out, please let me know.

**Comment by Leffe108** [comment]
It would be useful if warnings are included in [./types/components.d.ts](https://github.com/buefy/buefy/blob/dev/types/components.d.ts) too.
