### ISSUE TITLE
Unit test b-select using JEST setSelected() not working

### ISSUE THREAD

**Issue by re2005** [buefy/buefy#2128]
Using **jest** to test **b-select** component.

**Buefy** version: 0.8.9
**Vuejs** version: 2.6.10

Using method setSelected(); won't trigger the option to be selected.

```
const options = wrapper.findAll('option');
options.at(1).setSelected();
```

A sample of the code:
https://codesandbox.io/s/dry-wildflower-p93f9

Any help is appreciated.

Same implementation not using b-select works just fine:
https://gist.github.com/re2005/9aac2293bd3e65554d81a5640093caaf

**Comment by jtommy** [comment]
@re2005 can you provide the full test code ?

**Comment by re2005** [comment]
Thanks for replying @jtommy 
Here it goes:
https://gist.github.com/re2005/739dc9b30c7ba0665dc08a3be6df3186

**Comment by re2005** [comment]
Hey @jtommy any update on this one?

I'm also not able to test trigger('click) on "**b-**" elements. like <b-button>  and so on.

Anyone any please help ?

**Comment by jtommy** [comment]
I don't understand your code.. are there some missing part compare to the native select?

**Comment by re2005** [comment]
Finally I've found the problem.

I was mocking the component <b-select> 

Instead I've created a file importing and telling Vue to use the plugin and added that as reference on the "jest.config.js" file

Problem solved.

Check the files:
https://gist.github.com/re2005/739dc9b30c7ba0665dc08a3be6df3186
