### ISSUE TITLE
Feature request - b-table row select can check the checkbox of that row.

### ISSUE THREAD

**Issue by rahulmehtasiemens** [buefy/buefy#2130]
Hello Sir,

Problem : 1
Is there any direct way to check the checkbox of row of b-table on selecting anywhere on the row.
and selecting another row should deselect earlier checkbox of row .

Problem: 2
Select row and then press Shift+ Another row, All rows between these two rows should be checked/selected. 
Select row and then press CTRL+ Another row, all selection should stay.
Similar to Windows behavior.

Please let me know is this possible with b-table or another way we can achieve this behavior.

**Comment by jtommy** [comment]
1. You have to add current row into `checked-rows` prop (.sync) when you want

2. Only shift key it's enabled
