### ISSUE TITLE
Please support Badge

### ISSUE THREAD

**Issue by dangminhtruong** [buefy/buefy#2144]
### Description

Please support badge like Bootstrap. This is a small feature, but helpful sometimes :)
https://getbootstrap.com/docs/4.4/components/badge/

### Why Buefy need this feature

I need this while developing my application.

**Comment by yxngl** [comment]
It is called Tag here.

**Comment by pachiraDIG** [comment]
@yxngl  In order for this to be true, the Tag component's going to need to allow the `is-small` size option. Or a `badge` property added to the API to adjust the size and add an offset. Or both.

https://bulma.io/extensions/
![image](https://user-images.githubusercontent.com/46540659/84690243-0149f280-aef7-11ea-9ca4-1da4b44f7ff3.png)

**Comment by pachiraDIG** [comment]
Worth re-opening?

**Comment by slidenerd** [comment]
if someone can kindly post how to achieve the above notiication red dot thingy in buefy then no need to reopen the issue
