### ISSUE TITLE
Allow tabs nav element to have a custom class

### ISSUE THREAD

**Issue by FernFerret** [buefy/buefy#2149]
### Description

I'd like to be able to specify a custom class for the tabs nav element to enable better responsive designs. I've found that with the added width of the desktop, it's really cool to be able to use the vertical tabs for a slim layout I'm building, but on mobile it looks... not great and there isn't a good way that I see to hide the `nav` element of the `<b-tabs>` component. I'm requesting the class be able to be passed to the underlying `<nav class="tabs"...>` element.

I've worked around this pretty easily for now with the following snippet, but everything else I've wanted to do has been super easy within Buefy so I haven't needed to build my own components or even these little hacks. It feels a bit dirty as here I didn't need to use another tabs element, but If I had, this hack would affect other tab elements (without some more work) since it won't work scoped.
```vue
...
<style lang="scss">
@media (max-width: 1023px) {
  .tabs {
    display: none;
  }
}
...
</style>
```

This allows me to use something like these vertical tabs on desktop (where there will be many more than I want to show horizontally):

![image](https://user-images.githubusercontent.com/72811/72645401-7ecefe00-396b-11ea-9512-77300453e04c.png)

And the following on mobile:

![image](https://user-images.githubusercontent.com/72811/72645681-19c7d800-396c-11ea-8f7d-85d276678eef.png)

### Why Buefy need this feature

Buefy excels at providing insanely good responsive components out of the box and I think being able to hide the tabs to abstract them (much like the table does natively) or do other crazy customizations to the tabs component would be awesome.

**Comment by jtommy** [comment]
@FernFerret you can add a custom class to `b-tabs` and with it you are able to customize inner nav, for example `.myclass nav.tabs { ... }`
