### ISSUE TITLE
[TABS] Icons aren't in same line as the header in Custom Headers

### ISSUE THREAD

**Issue by nainardev** [buefy/buefy#2152]
### Overview of the problem

**Buefy** version: 0.8.10
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 79

### Description

Icons don't align with the Headers in Custom Headers [TABS]

### Steps to reproduce
https://buefy.org/documentation/tabs#custom-headers

### Expected behavior
Icons should be in same line as the Header

### Actual behavior
Icons not aligning with Headers

**Comment by service-paradis** [comment]
I think it is related to the issue #1891. Buefy is adding a span around slot content when using the slot `header`.

The rendered element right now looks like this:
```
<li class="is-active">
  <a>
    <span>
      <span class="icon"><i class="mdi mdi-information-outline mdi-24px"></i></span> 
      <span> Issues <span class="tag is-rounded"><span class=""> 3 </span> </span></span>
    </a>
  </span>
</li>
```
instead of:
```
<li class="is-active">
  <a>
    <span class="icon"><i class="mdi mdi-information-outline mdi-24px"></i></span> 
    <span> Issues <span class="tag is-rounded"><span class=""> 3 </span> </span></span>
  </a>
</li>
```
Not sure why exactly this is the current behavior. Would probably be a breaking change to fix it.

**Comment by nainardev** [comment]
So it would be fixed?

**Comment by service-paradis** [comment]
Will see with @jtommy what he is thinking about this and we could fix it in the next breaking release.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2171
