### ISSUE TITLE
Radio selection delay

### ISSUE THREAD

**Issue by miguelzapaton** [buefy/buefy#2154]
### Overview of the problem

**Buefy** version: 0.8.10
**Vuejs** version: 2.6.11
**OS/Browser**: Firefox 72.x on Windows

### Description

When I click on the Radio elements e.g. at the Radio component documentation page:

https://buefy.org/documentation/radio

the selection of the value und the start of the animation ist like 300-500ms delayed.

Imo it feels a bit laggy when you use a lot of Radio items in a larger form.

Is this an intended behaviour, a bug or a feature? 

I already tried to change the following variables:

$speed-slow
$speed-slower
$easing

However it seems that the delay happens before the animation starts.

Any hints?

### Expected behavior

I would expect the delay to either disappear or being configurable.

Many thanks for buefy!

**Comment by service-paradis** [comment]
I just tried to change `$speed-slow` to 0s. Does not look to be too laggy.
![captured (1)](https://user-images.githubusercontent.com/12817388/72846577-de305500-3c6e-11ea-917f-d3fb85d5e320.gif)

**Comment by jtommy** [comment]
@miguelzapaton what do you mean with "a lot of Radio items in a larger form" ? An example code ?

**Comment by miguelzapaton** [comment]
Thank you for looking at this. I'm still not sure if this is an intended behaviour.

I was using Muse-UI before and when I compare the perception of switching following radio buttons:

https://muse-ui.org/#/en-US/select-control
(Radio 1, Radio 2, Radio 3)

and

https://buefy.org/documentation/radio
(Flint, Silver, Jack)

Especially in Firefox on Windows I notice a delay before the radio animation starts in Buefy.
In Chrome on Windows both run faster but there's still a difference.

**Comment by service-paradis** [comment]
Just tried on Firefox, and you're right that it does not look as reactive. Weird...
