### ISSUE TITLE
Taginput with Autocomplete dropdown and OpenOnFocus closes on removing Tag, clicking Tag and sometimes on adding Tag

### ISSUE THREAD

**Issue by Kaisirak** [buefy/buefy#2156]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.11] and [3.0.0-alpha2]
**OS/Browser**: OSX Chrome

### Description

**Taginput** and **AutoComplete** with **OpenOnFocus** doesn't work when clicking on a **Tag**, closing a **Tag** and sporadically on adding a **Tag**.
The documentation page seems to work as intended, but when copying similar code the behavior is different.

(Issue #2135 was closed but the behavior still isn't fixed in 0.8.10)

Sandbox: https://codesandbox.io/s/tender-lumiere-kijux

<img width="665" alt="1" src="https://user-images.githubusercontent.com/5866233/72829500-bff93380-3c33-11ea-9684-b1ab7f4c5188.png">
<img width="680" alt="3" src="https://user-images.githubusercontent.com/5866233/72829515-c8ea0500-3c33-11ea-8cfd-8af5cc66e124.png">

### Steps to reproduce

1. Turn on OpenOnFocus
2. Add 2 Tags
3. Click on existing Tag or delete a Tag

### Expected behavior

Autocomplete dropdown stays open

### Actual behavior

Autocomplete dropdown closes and fires blur and focus events

**Comment by jtommy** [comment]
Tested on Chrome windows and Android without issues.

**Comment by Kaisirak** [comment]
I just tested it on Firefox and Chrome on Windows 7, and I experience the same behavior. Did you try the codesandbox link @jtommy ?

**Comment by Kaisirak** [comment]
I've now also tested it on Android Pie with Chrome and same behavior, on removing a Tag the Autocomplete closes even though the Taginput is still focused. I tried without any extensions to see if somehow that could affect it, and again same result.
Would it help if I made a video ?

**Comment by jtommy** [comment]
@Kaisirak ok

**Comment by Kaisirak** [comment]
@jtommy https://www.youtube.com/watch?v=M4WS9teHxRg&feature=youtu.be

**Comment by jtommy** [comment]
It's really strange I'm not able to replicate it, are you to use the last version?

**Comment by Kaisirak** [comment]
I tried it on another computer running Windows 10 and Chrome, and I get the same behavior.

If Codesandbox tells the truth, I believe it is running the latest version of Buefy (0.8.10).

<img width="267" alt="Screen Shot 2020-01-22 at 4 26 05 PM" src="https://user-images.githubusercontent.com/5866233/72946550-206f9a00-3d34-11ea-8722-1a01c0bd4473.png">

And I get the same behavior with my local version.

When you say you're not able to replicate it, do you mean on running my Codesandbox(https://codesandbox.io/s/tender-lumiere-kijux) or your own use case ?

**Comment by HughVolpe** [comment]
I'm experiencing the same issue, both on the codesandbox and locally. 
Buefy version: [0.8.10]
Vuejs version: [2.6.10]
OS/Browser: OSX Chrome and Firefox

**Comment by Kaisirak** [comment]
@jtommy The issue is still present on 0.8.11. It seems like it now also affects the Buefy documentation. https://buefy.org/documentation/taginput#autocomplete

Here is the updated code sandbox : https://codesandbox.io/s/relaxed-rgb-pq0lk?fontsize=14&hidenavigation=1&theme=dark

I also opened #2250 which seems unrelated, but worth noting

**Comment by DazDotOne** [comment]
I spent some time looking into this, it's pretty frustrating.

for some reason for me, adding tags always gets rid of the dropdown list (the input remains focused).

However, If I make some changes to the component using the taginput and let it hot reload, everything works.

the biggest difference I can see is this:

when inspecting:
`console.log(this.$refs.myTagInput.$refs.autocomplete.$refs.dropdown)`

with a full page refresh after my tag filter function runs:
`<div class=​"dropdown-menu fade-leave-active fade-leave-to" style>​`

with a hot reload:
`<div class=​"dropdown-menu fade-enter-active fade-enter-to" style>​`

I guess it could be something to do with the transition being out of whack?

**Comment by jtommy** [comment]
Probably, I hope to fix it soon
