### ISSUE TITLE
Checkbox Button works conversely when not in grouped mode.

### ISSUE THREAD

**Issue by UnluckyNinja** [buefy/buefy#2159]
### Overview of the problem

**Buefy** version: [0.8.10]

### Description

In the api description of [Checkbox Button](https://buefy.org/documentation/checkbox), it says:

> type - Type (color) of the button **when checked**

But it actually works "**when not checked**" when using only one of it.

(It works correctly when in grouped(array) mode.)

### Steps to reproduce

Demo: https://codesandbox.io/s/staging-darkness-1cgwt

### Expected behavior

When v-model is true, display as specified in prop "type" (e.g. "is-danger").

### Actual behavior

It displays the style when v-model is false, which is exactly opposite to expected behavior.

###### BTW, it may be very helpful to allow something like "checked-type" & "unchecked-type".

**Comment by jtommy** [comment]
Try using `:native-value="true"`
