### ISSUE TITLE
Table alignment issue. If two or more toggled column's labels are null.

### ISSUE THREAD

**Issue by taracha-r** [buefy/buefy#2161]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.11]
**OS/Browser**: macOS Catalina/Chrome

### Description
If two or more column labels are null, and both can be toggled. This causes a alignment issue between the column titles and data. 

I'll try to fix the issue. 

### Steps to reproduce
https://jsfiddle.net/53z8o6ym/12/
Notice that the **Percentages** column title is not in the correct spot

1. In the jsfiddle above in the js section go to line 21 `columnsVisible`. 
2. Add a value to title in either `name` or `cleared`.
3. Rerun the jsfiddle and you should see the columns aligned properly. 

### Expected behavior

Expected to have columns aligned properly with two columns not having a label. 

### Actual behavior

Columns do not align correctly

**Comment by jtommy** [comment]
@taracha-r `b-table-column` needs a key (probably in the future I'll add an autogenerated id) so when you have two or more columns without a label you should use `custom-key` prop in order to identify a column, take a look at https://jsfiddle.net/6bu4pg1q/

**Comment by taracha-r** [comment]
Awesome, thanks!
