### ISSUE TITLE
b-field doesn't associate label with nested b-input in resulting markup

### ISSUE THREAD

**Issue by exchgr** [buefy/buefy#2162]
### Overview of the problem

**Buefy** version: 0.8.8
**Vuejs** version: 2.6.10
**OS/Browser**: macOS Catalina 10.5.2 / Safari 13.0.4

### Description

When nesting a `b-input` inside a `b-field` with a label, the resulting markup doesn't associate the label with the input, constituting an accessibility problem and an automated e2e testing problem.

### Steps to reproduce

```vue
<b-field label="Name">
  <b-input id="name" ... />
</b-field>
```

### Expected behavior
something like:

using `for`:
```html
<label for="name" class="label">Name</label>
<div ...>
  <input id="name" ...>
  </input>
</div>
```

or

nested:
```html
<label class="label">
  Name
  <div ...>
    <input ...>
    </input>
  </div>
</label>
```

### Actual behavior
```html
<label class="label">Name</label>
<div ...>
  <input ...>
  </input>
</div>
```

**Comment by jtommy** [comment]
@exchgr you might use `label-for` prop on `b-field`

**Comment by exchgr** [comment]
Thanks!

**Comment by unikitty37** [comment]
`label-for` isn't really a fix for components, as it requires an ID, which must be unique in the whole page. That means things will break if a component is used more than once on a page.

Please could `b-field` actually nest the generated `input` inside the `label`?
