### ISSUE TITLE
Add autofocus to b-input

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#2166]
### Description

https://www.w3schools.com/tags/att_input_autofocus.asp

```
b-input(
    v-model.trim="query"
    placeholder="Enter keywords"
    type="search"
    minlength="1"
    maxlength="255"
    name="query"
    autofocus
)
```

### Why Buefy need this feature

It seems this isn't work at the moment. It's really useful on forms, e.g. authenticate, search, etc.

**Comment by francoism90** [comment]
Turns out this is Vue specific(?), it doesn't work on input - you have to use `.focus()`.

```
<template>
b-input(ref="email" type="email")
</template>

<script>
export default {
  mounted () {
    this.$refs.email.focus()
  }
}
</script>
```

Maybe it would be cool to have this as property on `b-input`, otherwise I'll close this ticket. :)

**Comment by service-paradis** [comment]
Works for me when I use `:autofocus="true"`

**Comment by francoism90** [comment]
@service-paradis Hmm, it doesn't work for me, you set this on `b-input` or on `input`?

**Comment by service-paradis** [comment]
I'm using `b-input`. I tried to make a [codepen](https://codepen.io/service-paradis/pen/LYEqBgq?editors=1010), but unfortunately, Chrome gives me this error in console (`vue.min.js:6 Blocked autofocusing on a form control in a cross-origin subframe.`).

But as you can see, it tried to apply the autofocus.

**Comment by francoism90** [comment]
@service-paradis I've tried using autofocus in Firefox and Chrome (both Linux), including different `b-input` elements, but non seems to focus. Weird, I really need to use `focus()` with `ref`.

The codepen indeed seems to be getting blocked, any alternatives for online testing?

**Comment by service-paradis** [comment]
Online testing always imply iframe unfortunately, so Chrome will always block autofocus.

I dont know why it wont work for you, just tried Chrome/Firefox and Edge on my side and it is working

**Comment by jtommy** [comment]
@francoism90 i've just tested a new project (vue 2.6+ and buefy 0.8.10) and it works well. Please share a part of code in order to test in the deep.

**Comment by francoism90** [comment]
@jtommy This is the full code: https://github.com/francoism90/mediadb/tree/master/src/resources/js

I'm using this inside a modal: https://github.com/francoism90/mediadb/blob/master/src/resources/js/components/modal/Search.vue

Thanks for taking a look into this, it doesn't work for me and I need to use the `.focus()` in `mounted ()`.

**Comment by jtommy** [comment]
@francoism90 I think `.focus` is the only one solution at the moment using it in a modal.
There is a similar issue https://github.com/vuejs/vue/issues/10976 but as you can see in buefy dialog component we are using `.focus` on input element (prompt) https://github.com/buefy/buefy/blob/39e918aa1fe574bcc8096436080d99a7029f8279/src/components/dialog/Dialog.vue#L232

**Comment by francoism90** [comment]
@jtommy OK, thanks again for the help. :)

**Comment by soundar-sapaad** [comment]
> :autofocus="true"

Hi buddy, where we wan to change this?

**Comment by unikitty37** [comment]
One important point to note when using it with modals (which took me quite a while to work out) is that the ref won't be visible until the next tick after you show the modal — so you need something like this:

```js
showModal () {
  this.loginModalActive = true
  this.$nextTick(() => {
    this.$refs.username.focus()
  })
}
```

If you call `this.$refs.username.focus()` immediately after `this.loginModalActive = true` you'll end up with a non-focused field and `TypeError: Cannot read property 'focus' of undefined` in your console.

**Comment by AxelConceicao** [comment]
> ```js
> this.$nextTick(() => {
>     this.$refs.username.focus()
>   })
> ```

Thanks u so much
