### ISSUE TITLE
Feature Request for buefy table component

### ISSUE THREAD

**Issue by rahulmehtasiemens** [buefy/buefy#2167]
**Our requirement for buefy table :**

- Selecting anywhere in the row should select the check box of row  : Resolved by jtommy – [Issue link ](https://github.com/buefy/buefy/issues/2130)
- Selecting another row should deselect earlier selection and select the current row : Resolved by Suggestion by jtommy – [Issue link](https://github.com/buefy/buefy/issues/2130)
- For multiple selection use checkbox. : Already handled by Buefy
- Select row and then press Shift + another row, All rows between these two rows should be selected. (Only handled for check box selection, not enable for row selection)
- Select row and then press Ctrl + another row, all selection should stay.(Not enabled by Buefy for both , check box and row selection) 

Basically to match with windows behavior.

**Feature Request to Buefy:**

1.	Multiple selections using Ctrl + row selection (Note : For IOS, it will be CMD + row selection)

2.	Multiple selections Shift + row selection

**Note :** 
1.	I checked the code [link](https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L794). Shift+ check box selection is handled in the code.
2.	But Shift + row selection is our requirement and as per you suggestion (add current row into checked-rows prop (.sync) when you want) I handled it and it is working which solve initial two requirement. 
3.	But need to handle Shift+ row selection for which event should be handle by either buefy or emit the event up to user level (Buefy API consumer) so I can handle at our end.
4.	Row selection with Shift and Ctrl control support, natively by buefy then it will be very helpful for all buefy consumer.

**Comment by jtommy** [comment]
@rahulmehtasiemens they are good new features and improvements to add :)

**Comment by rahulmehtasiemens** [comment]
@jtommy  Thanks for considering this requirement.

Can you please provide the **ETA** of above feature? So I will communicate the same within my team and adjust our work accordingly.

**Comment by rahulmehtasiemens** [comment]
@jtommy  Any update ?

**Comment by jtommy** [comment]
@rahulmehtasiemens I am happy to review a PR that adds this feature anytime, if you can't or are not willing to work on it I will add to my pipeline but I can't sign off on any time / eta
