### ISSUE TITLE
No translation possibilities on Buefy popups (confirm, dialog, prompt...)

### ISSUE THREAD

**Issue by teuk1** [buefy/buefy#2168]
### Overview of the problem
Hello everyone,
I can **easily use traduction** with [i18n](https://kazupon.github.io/vue-i18n) **on form-element** that are based on html **but not on advanced modal components** like dialogs.

### Description
Example of code that works fine on form-element components (e.g. like on a b-input & its placeholder) : 
`<b-input :placeholder="$t('searchData')" type="search" ref="value" icon="magnify" v-model.trim="value" validation-message="Reference only" @keyup.enter.native="fetchData(value)"></b-input>`

or see code below on an a:link : 
`<a v-if="totoGetHisto!=false" v-on:click="clearHistory()" class="floatR mdi mdi-delete colorfff" :title="$t('DeleteHist')">{{$t('DeleteHist')}}</a>`

but i can't find the way, if its possible, to do the same way on a fonction component (e.g. like a dialog and its title) : 
```javascript 
this.$buefy.dialog.confirm({
  :title: $t("DeleteHist"),
  message: "Are you sure you want to delete history?",
  cancelText: "No",
  confirmText: "Yes",
  type: "is-success",
  onConfirm: () =>
    this.$buefy.toast.open({
    message: "history has been deleted",
    position: "is-top",
    type: "is-success"
  }) 
  &
    this.$root.histo.splice(this.$root.histo.length - this.$root.histo.length) 
  &
    localStorage.setItem("histo", "") 
  &
    this.$router.push({ path: "/" }) 
  onCancel: () =>
    this.$buefy.toast.open({
    message: "history has not been deleted",
    position: "is-top",
    type: "is-info"
  })
});
```

### Required before starting
```javascript
//---------
// Install the packages Buefy & vue-i18n in a vue project
//---------
yarn add vue-i18n buefy
```

```javascript
//---------
// Locale configuration on the main.js
//---------
import Vue from "vue"

import Buefy from 'buefy'
import 'buefy/dist/buefy.min.css'
Vue.use(Buefy)

import VueI18n from 'vue-i18n'
Vue.use(VueI18n)

// Create VueI18n instance with options
export const i18n = new VueI18n({
  locale: "fr", // set locale
  fallbackLocale: 'en'
});

new Vue({
  data() {
    return {
    }
  },
  i18n,
  render: h => h(App)
}).$mount("#app");
```

this kind of tag before the template tag (in the .vue file)
`<i18n>
{
  "en": {
    "DeleteHist": "Delete history",
    "searchData": "Search..."
  },
  "fr": {
    "DeleteHist": "Supprimer l'historique",
    "searchData": "Recherche..."
  }
}
</i18n>`

### Why Buefy need this feature
I am working on application for multi language speakers and i want to translate the messages in the dialogs and other modal components. do you have any suggestions ?
Thank you .

**Comment by service-paradis** [comment]
Did you tried something like this:

```
this.$buefy.dialog.confirm({
  title: this.$i18n.translate("DeleteHist"),
  message: "Are you sure you want to delete history?",
  cancelText: "No",
  confirmText: "Yes",
  type: "is-success",
  onConfirm: () =>
    this.$buefy.toast.open({
    message: "history has been deleted",
    position: "is-top",
    type: "is-success"
  }) 
  &
    this.$root.histo.splice(this.$root.histo.length - this.$root.histo.length) 
  &
    localStorage.setItem("histo", "") 
  &
    this.$router.push({ path: "/" }) 
  onCancel: () =>
    this.$buefy.toast.open({
    message: "history has not been deleted",
    position: "is-top",
    type: "is-info"
  })
});
```

**Comment by teuk1** [comment]
No @service-paradis, i get an error :
[Vue warn]: Error in v-on handler: "TypeError: this.$i18n.translate is not a function"

found in

---> <History> at src/components/History.vue
       <App> at src/App.vue
         <Root> vue.runtime.esm.js:619
