### ISSUE TITLE
Table headers with identical labels are not shown 

### ISSUE THREAD

**Issue by altert** [buefy/buefy#2176]
#1535 # Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.11]
**OS/Browser**:
macOS Mojave/ Google Chrome 79.0.3945.130
### Description

If custom template for row is used, and some of columns have identical labels, only first one is rendered on page

### Steps to reproduce

Create table with custom template and give some columns identical names
https://codepen.io/altert/pen/povmgQd

### Expected behavior

All column headers are rendered

### Actual behavior

Only first header from set of identical labels is rendered

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/2161#issuecomment-578487435
