### ISSUE TITLE
Navbar classList.remove v0.8.10 Bug

### ISSUE THREAD

**Issue by cain** [buefy/buefy#2179]
<img width="657" alt="Screen Shot 2020-01-30 at 11 56 34 am" src="https://user-images.githubusercontent.com/15246256/73416410-ed975880-4368-11ea-8f17-b5cc82277854.png">
<img width="698" alt="Screen Shot 2020-01-30 at 11 56 55 am" src="https://user-images.githubusercontent.com/15246256/73416411-ed975880-4368-11ea-9639-4f57afffcb19.png">

### Overview of the problem
Not entirely sure what's going on here, but there seems to be a bug introduced in 0.8.10. `removeBodyClass` string is empty causing a native javascript error. This function requires a string not empty. (see screenshots)

I think this must have been introduced in this issue #1889 (let me know if im wrong)

When adding `spaced` or `fixed` it fixes the issue because an valid string is being used on the `removeBodyClass`

**Buefy** version: [0.8.10]
**Vuejs** version: [X.X.X]
**OS/Browser**: OSX/Chrome

### Steps to reproduce

1. Have a navbar without spaced or fixed.
2. Have the navbar component destroy()

**Comment by jtommy** [comment]
Already fixed https://github.com/buefy/buefy/issues/2160

**Comment by cain** [comment]
thanks @jtommy
