### ISSUE TITLE
Allow B-datetimepicker the availability to change the month's name as you can do with datepicker

### ISSUE THREAD

**Issue by taverasady** [buefy/buefy#2181]
Description:

Allow b-datetimepicker to change the months (by passing an array of strings) such as with b-datepicker :months-name prop.

**Comment by jtommy** [comment]
It's already available, just set it to `datepicker` prop or using Buefy constructor

**Comment by taverasady** [comment]
> It's already available, just set it to `datepicker` prop or using Buefy constructor

I've tried the following:
Html:

  <b-datetimepicker
                rounded
                placeholder="Click to select..."
                icon="calendar-today"
                :month-names="months"
                :datepicker="{ showWeekNumber }" 
                :timepicker="{ enableSeconds, hourFormat: format }">
  </b-datetimepicker>

Assume i have a array of strings named "months" ->  ['Enero','Febrero'] ( First two month's name in spanish).

Like i've stated it won't work, but if you change the component to : 

  <b-datepicker
                rounded
                placeholder="Click to select..."
                icon="calendar-today"
                :month-names="months"
                :datepicker="{ showWeekNumber }" 
                :timepicker="{ enableSeconds, hourFormat: format }">
  </b-datepicker>

It will work because this prop is available in the <b-datepicker> component but NOT in the <b-datetimepicker> component.

Regards.

**Comment by jtommy** [comment]
Please take a look at the docs.
```
<template>
    <section>
        <b-field grouped group-multiline>
            <div class="control">
                <b-switch v-model="showWeekNumber">Show week number</b-switch>
            </div>
            <div class="control">
                <b-switch v-model="formatAmPm">AM/PM</b-switch>
            </div>
            <div class="control">
                <b-switch v-model="enableSeconds">Enable seconds</b-switch>
            </div>
        </b-field>
        <b-field label="Select datetime">
            <b-datetimepicker
                rounded
                placeholder="Click to select..."
                icon="calendar-today"
                :datepicker="{ showWeekNumber }"
                :timepicker="{ enableSeconds, hourFormat: format }">
            </b-datetimepicker>
        </b-field>
    </section>
</template>

<script>
export default {
    data() {
        return {
            showWeekNumber: false,
            formatAmPm: false,
            enableSeconds: false
        }
    },
    computed: {
        format() {
            return this.formatAmPm ? '12' : '24'
        }
    }
}
</script>
```

**Comment by taverasady** [comment]
It seems like you're not understanding correctly, I am not trying to format the date  or time itself, the only thing I am trying to do with the b-datetimepicker is to change the names of the different months, which is not possible due to the fact that the b-datetimepicker component dosen't offer the :month-names prop, such as the b-datepicker does.

**Comment by jtommy** [comment]
Datetimepicker offers a prop called `datepicker` and it's an object that accepts all props that offers datepicker

**Comment by taverasady** [comment]
I got you ! thanks for the support jtommy.
