### ISSUE TITLE
Index number on paginated buefy table

### ISSUE THREAD

**Issue by mewcrazy** [buefy/buefy#2182]
Hello,

I'm trying to get the index number of buefy table row. But when my table is paginated, I get a wrong index. I'm on page 10 with 10 results each page, so I expect my index to be 90, not 9. (see the attached image) - Is there any way to get the actual index/cycle number of a row?

![image](https://user-images.githubusercontent.com/6299479/73485778-0a04b680-43a4-11ea-9c88-cc704fb5d97d.png)

**Comment by jtommy** [comment]
Index * page ?

**Comment by mewcrazy** [comment]
@jtommy that obviously worked ;) thanks.

**Comment by kavinmehta** [comment]
This is how I solved it:

index * page doesn't work because on page # 2, it goes 2, 4, 6, on page 3 it goes 3,6 ,9 etc (i.e. if I understand it the way I think it is)

YMMV depending upon your pagination per page.
```
//  currentPage is an attribute in data()
 return {
      currentPage: 1,
    }  
```
```
 <b-table 
        ref="table"
        :data="data"
        paginated
        per-page="10"
        :current-page.sync="currentPage"
      >
```
```
<b-table-column v-slot="props" scope="props" label="#" cell-class="valign">
      {{currentPage === 1 ? props.index + 1 : (currentPage - 1) * 10 + props.index + 1}}
</b-table-column>
```
