### ISSUE TITLE
undefined is not an object (evaluating 'this.carouselItems[this.activeItem].status')

### ISSUE THREAD

**Issue by Heartz66** [buefy/buefy#2189]
I'm not sure how these issues are caused and on which conditions but these errors are being reported to me:

`undefined is not an object (evaluating 'this.carouselItems[this.activeItem].status')`

**Comment by jtommy** [comment]
@nateleavitt can you replicate it ?

**Comment by service-paradis** [comment]
There are some places in the component code where we have this condition that surrounds access to carouselItems:
`if (this.activeItem < this.carouselItems.length)`
But, this condition is not everywhere (next, prev and changeItem functions for example). This issue can occurs if a previously visible items does not exist anymore (using `v-if` or something) and we try to access it. Kind of edge cases, but could be prevented using the above condition. This was made in steps and tabs component.

**Comment by jtommy** [comment]
@service-paradis sure, please add it :)
