### ISSUE TITLE
Remove margin on icon on empty content slot b-button

### ISSUE THREAD

**Issue by Heartz66** [buefy/buefy#2190]
When using `b-button` component with only using the `icon-left` or `icon-right` property (without content inside of it) there is a slight margin to the right or left. This margin should be disabled when there is no content inside of the component.

![881def04642e1c7ebac17032bb8ab261](https://user-images.githubusercontent.com/8833887/73583538-13b91780-4493-11ea-9c94-9e5c16da6369.png)

**Comment by a-kriya** [comment]
28e2e23 was reverted in 9b15e7c. Would that not cause this issue again?

**Comment by jtommy** [comment]
Yes, so i fixed with https://github.com/buefy/buefy/commit/454c206e73eee1236bc96e22a584a3ba10d91449

**Comment by a-kriya** [comment]
Ah, my bad.

**Comment by a-kriya** [comment]
I'd suggest using `git revert` command to revert changes, though, which would embed reference to the commit being reverted in the commit message and GH would update the original PR and commit with links to changes.

**Comment by jtommy** [comment]
Yes, my bad
