### ISSUE TITLE
number input placeholder="42" does not work?

### ISSUE THREAD

**Issue by neuronflow** [buefy/buefy#2197]
### Overview of the problem

**Buefy** version: [X.X.X] 0.8.10
**Vuejs** version: [X.X.X] 2.6.11
**OS/Browser**: OSX Chrome

### Description
placeholders for number inputs seem to have no effect. How to set it to 42?

### Steps to reproduce

```
            <b-field label="age">
              <b-numberinput
                name="age"
                class="form-control"
                id="age"
                placeholder="42"
                min="18"
                max="99"
                aria-required="true"
                required
              ></b-numberinput>
            </b-field>
```

### Expected behavior

paceholder shows 42

### Actual behavior

placeholder shows min value

**Comment by neuronflow** [comment]
Maybe I am doing it wrong, but the same syntax seems to work for text inputs and there is a placeholder attribute according to: https://buefy.org/documentation/numberinput/

**Comment by service-paradis** [comment]
Not sure `placeholder` are supported right now for `numberinput`. I dont see any props named `placeholder` in the [documentation at the end of the page](https://buefy.org/documentation/numberinput#api-view).

**Comment by neuronflow** [comment]
https://codepen.io/pen?&editable=true&editors=101
But it is used in the examples :)

**Comment by service-paradis** [comment]
You're right, but it looks like it was added by mistake since it does not work. This should probably be removed from the examples.

**Comment by neuronflow** [comment]
I respectfully disagree, I would prefer to make this a feature request then :)

**Comment by service-paradis** [comment]
Sure, I think we should remove them from the current docs since it could be misleading. But you can, for sure, ask for this behavior in a feature request :)

**Comment by neuronflow** [comment]
The original bulma supports it by the way..so for the moment I help myself using standard html tags and bulma css classes :/

**Comment by jtommy** [comment]
Original bulma? An example?

**Comment by service-paradis** [comment]
Buefy Input component is supporting `placeholder` like the original Bulma, but there is no `numberinput` in Bulma...

**Comment by neuronflow** [comment]
yes, you are right...the original bulma is just a text input without the nice buttons buefy provides..looks like I cannot have best of both worlds. sorry for the confusion. Do I need to create a feature request or is this bug report enough?

**Comment by service-paradis** [comment]
For the moment, you can use the type number using `b-input` (ex. `<b-input type="number" />`). 

For the Request, I think you can close this one and create another one which would be cleaner.

**Comment by jtommy** [comment]
@neuronflow It's a breaking change because at the moment the default value is 0 or `min` prop

**Comment by neuronflow** [comment]
I created the feature request as suggested:
https://github.com/buefy/buefy/issues/2214
