### ISSUE TITLE
b-table to prevent (or ignore) the click on specific columns

### ISSUE THREAD

**Issue by rogeriotaques** [buefy/buefy#2199]
### Description

A specific property for preventing the `click` event in some columns where buttons might be added to handle different actions alongside the implemented `click` handler for rows.

### Why Buefy need this feature

Having the `click` event bound for b-table is helpful to handle clicks in a row to perform some actions (e.g open a record for editing). However, in some cases, having more actions available to the user alongside the capacity for clicking in the row is required.

**Comment by jtommy** [comment]
@rogeriotaques currently click event is on row. We might send native event too so you should be able to call prevent default.
What do you think? What's a your use case?

**Comment by rogeriotaques** [comment]
Hi @jtommy , thanks for the quick reply!

Yeah, using the native events may help to implement the needed behaviour. Would you mind to give me an example of how would you implement that? I guess I've missed this from the docs!

**Comment by jtommy** [comment]
https://codepen.io/jtommy/pen/Poqopje?editable=true&editors=101

Take a look at button event `@click.stop`

**Comment by rogeriotaques** [comment]
That looks very clean! Kudos, @jtommy .

I did manage to implement it with `@click.native` for every `b-table-column`, but using the `@click.stop` on `b-button` seems way simpler and easy to maintain!

So, at this point, I don't feel that Buefy needs to implement this feature anymore, therefore, I'm closing the issue! But, feel free to re-open it if you disagree.

Cheers. 🍻
