### ISSUE TITLE
Color for "button.is-link" seems incorrect

### ISSUE THREAD

**Issue by jvtoomey** [buefy/buefy#2204]
Hi, this might've been mentioned in issue #1632, but it still seems like a mistake? The color for "button.is-link" is set to #7957d5 (purple, same as 'button.is-primary"), but I think it should be #3273dc (dark blue). All the others match up as shown on https://buefy.org/documentation/button.
Here's a picture showing the one purple oddity, and a pic of the buefy page:
![color in practice](https://user-images.githubusercontent.com/4951823/73881627-87518080-4815-11ea-920f-e19e7bb1d86e.png)
![buefy is-link color](https://user-images.githubusercontent.com/4951823/73881633-891b4400-4815-11ea-9e02-1a721dc4d400.png)

**Comment by jtommy** [comment]
You can customize it using sass/scss

**Comment by marianomd** [comment]
It seems to be a discrepancy originating on Bulma, but, documentation should reflect the default behaviour and not a customized one.

**Comment by marianomd** [comment]
More on this [here](https://bulma.io/2017/10/09/roses-are-red-links-are-blue/)

**Comment by asajadian** [comment]
I don't want to setup SASS to merely change is-link to original Bulma is-link color! It's weird that is-primary and is-link are the same by default, please change that.
