### ISSUE TITLE
Datepicker messed up in Safari on small screens/in narrow windows

### ISSUE THREAD

**Issue by tobiasmboelz** [buefy/buefy#2205]
### Overview of the problem

**Buefy** version: 0.8.10
**Vuejs** version: 2.6.11
**OS/Browser**: Safari 13.0.5 on macOS and Safari on iOS 13.3

### Description

Datepicker is messed up in Safari on small screens and in narrow windows.

### Steps to reproduce

1. Open https://buefy.org/documentation/datepicker in Safari on macOS.
2. Reduce window width to about 1024 px.

or

1. Open https://buefy.org/documentation/datepicker in Safari on iOS.

### Expected behavior

Datepicker is displayed correctly.

### Actual behavior

Some cells have the wrong height and the cell's content is misaligned.

<img width="1136" alt="Bildschirmfoto 2020-02-06 um 05 35 32" src="https://user-images.githubusercontent.com/641522/73906584-be6e7300-48a3-11ea-9647-7fa7895891d3.png">

![Simulator Screen Shot - iPhone SE - 2020-02-06 at 05 36 15](https://user-images.githubusercontent.com/641522/73906608-cdedbc00-48a3-11ea-8904-5de4e0d50c79.png)

**Comment by jtommy** [comment]
@tobiasmboelz Unfortunately i'm not able to test it on safari o iOS

**Comment by FlymeDllVa** [comment]
Same problem

**Comment by bender-a** [comment]
Seems to be a really weird bug in safari.
When the cells of the table get too small, safari aligns the text at the end of the cell and you have no control over the alignment anymore. 
Can be fixed with min-width on the table cells, but that doesn't really solve the problem...
