### ISSUE TITLE
Border on modal-card-head during animation

### ISSUE THREAD

**Issue by bviala** [buefy/buefy#2206]
### Overview of the problem

I don't want the default border bottom on modal card header.
I've set the bulma variable `$modal-card-head-border-bottom: none;`
It works fine when the modal is open, but the border still appears during opening and closing, resulting in a super ugly flash.
Since it's only during the animation and the elements are removed from the DOM when it's closed, I have no way to inspect and see what's going on.

**Buefy** version: [0.8.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Chrome / Firefox / macOS

### Description

https://gfycat.com/dismalhideoushamadryad

**Comment by service-paradis** [comment]
Do you get the same results using Bulma only?
Do you get the same results using `$modal-card-head-border-bottom: none !important;`?

**Comment by bviala** [comment]
Ok so I played a bit more with this and realized the appearing border isn't actually a border or a box shadow: it's the modal background. During the Buefy animation, modal header and body divs get separated, letting the background appear.  
It just doesn't show with the default border bottom cause it's the same color.  
Luckily enough the design I have to implement uses a very light opacity (0.15) which makes the flash almost not noticeable.

**Comment by service-paradis** [comment]
Could you customize the modal-background to have the same color as the modal content background?

**Comment by bviala** [comment]
@service-paradis You can but it will not look good, the goal of a modal background is to bring out the modal itself so you need contrast.  
Also, if you set a quite modal background with low opacity like I did, as soon as you have an element in the background that strongly contrasts with your modal background, you will have this ugly flash effect: 
https://gfycat.com/infatuatedenviousgrunion (take a look at the left purple button)

@jtommy Don't know why you close, you definitely have a styling issue if your animation only works with Bulma defaults.

**Comment by service-paradis** [comment]
I made an error in my last post. I wanted to know if you have the same issue if you style the background color for `modal-content` the same color as your modal card header or content (in your case, in white).

**Comment by bviala** [comment]
Putting a background color on `modal-card` class does work ! But then I also have to redefine my radiuses on this class instead of using the Bulma variables.
That's a good workaround tho, thanks !

**Comment by jtommy** [comment]
@bviala what Buefy should fix about it ?

**Comment by bviala** [comment]
As I said, I think the problem is that the buefy animation for modal somehow makes the `modal-card-header`, `modal-card-body`, and `modal-card-foot` divs separate from each other.

**Comment by jtommy** [comment]
@bviala I don't think it is related to Buefy, the transition groups all modal. Probably it's related to the browser
