### ISSUE TITLE
Making TagInput's Tag content  customisable

### ISSUE THREAD

**Issue by jacobgoh101** [buefy/buefy#2208]
### Description

The ability to make TagInput's Tag content customisable.

### Why Buefy need this feature

Use Case: 

To implement this design, I'll need to be able to edit the HTML content for each tag. I believe this would not be an uncommon design.

![image](https://user-images.githubusercontent.com/15951104/74002507-3f179700-49aa-11ea-996f-ffddcd20b503.png)

**Comment by jtommy** [comment]
4fdbf495
