### ISSUE TITLE
TabItems do not update isActive when their Tab index changes

### ISSUE THREAD

**Issue by GunnerGuyven** [buefy/buefy#2211]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.11]
**OS/Browser**: Chromium (Linux)

### Description

When Tab-Items are produced using `v-for` a Tab-Item's internal flag `isActive` is not recalculated if new tabs are introduced or removed.  This results in a doubling-up of the content of the current and previous tab occupying the parent `<b-tabs>` `activeTab` index.  If the selected tab was previously the last in the list (highest index) and a tab is removed this results in no tab selected, but the previous content still visible.  Visiting the tab that is displaying without being selected remedies the bad state.

### Steps to reproduce

1. `<b-tabs><b-tab-item v-for="i of tabItems"> {{ i.content }} </b-tab-item></b-tabs>`
    **note** `:key` has no affect on this issue that I can tell.
2. Manipulate the `tabItems` structure, adding or removing items.

### Expected behavior

I expect only one TabItem's content to display at a time, and I expect the selected tab to match the shown contents.

### Actual behavior

Additional TabItems' content can be engineered to display simultaneously when manipulating the number of tabs that exist.  Either one or zero tabs will be selected depending on the circumstances.  Navigation to the tab(s) whose content is incorrectly displaying corrects the problem.

### Imperfect Workaround

Adding a `watch` on the `tabItems` structure and adding `v-model="currentlySelectedTab"` to the parent `b-tabs` allows you to detect this situation and prevent the doubling up (or at least immediately fix it), but I haven't found a way that it can be done which avoids extra animations (if you have animations enabled) or flickering (if you don't).

#### Partial Example of Workaround:
```javascript
  watch: {
    tabItems(nv, ov) {
      const idx = this.currentlySelectedTab
      if (nv.length > ov.length) {
        if (ov[idx] && nv[idx] !== ov[idx]) {
          // this.tabAnimationEnabled = false
          setTimeout(() => {
            this.currentlySelectedTab += 1
            // setTimeout(() => (this.tabAnimationEnabled = true), 100)
          })
        }
      }
    }
  }
```
This will catch the situation of adding a lower index item causing the previously selected tab to remain on display.  Without the `setTimeout` the `currentlySelectedTab` is updated first, resulting in a _different_ two tabs doubling up.  With this solution in place, you see the animation of an extra tab's content being wiped off (or its appearance before flickering away if you disable animations).

### Proposed Solutions
* Perform better re-calculation of `isActive` for this scenario to avoid a TabItem maintaining `true` when it is no longer the selected tab.
  * It is unimportant to me which tab remains and which hides, only that **just one** tab shows.
* Expose a TabItem property to allow direct manipulation of `isActive` such as `content-visible`
  * I dislike this solution because it invites misuse.

**Comment by GunnerGuyven** [comment]
This is a more complete workaround.  Covers all the cases I have identified:
* Number of Tabs Increase or Decrease causing selected tab to change index
* Number of Tabs Decrease causing selected Tab to no longer exist
```javascript
watch: {
  tabItems(nv, ov) {
    const idx = this.currentSelectedTab
    const previousSelected = ov[idx]
    if (nv.length !== ov.length && nv[idx] !== ov[idx]) {
      if (nv.includes(previousSelected)) {
        setTimeout(() => {
          this.currentSelectedTab = nv.findIndex(v => v === previousSelected)
        })
      } else if (nv.length && idx >= nv.length) {
        setTimeout(() => {
          this.currentSelectedTab = nv.length - 1
        })
      }
    }
  }
}
```
This should be automatically handled by Buefy in my opinion.  Internal handling should additionally be able to avoid extraneously triggered animations (something I haven't solved yet).

**Comment by jtommy** [comment]
@GunnerGuyven probably you are right but what item should Buefy choose in this case ?

**Comment by GunnerGuyven** [comment]
There are some competing ideas there, I think.  It could try to maintain the original index, accommodating the fact that that index may no longer exist and selecting the next closest: [1,2,(3)] -> [1,(2)].  Or it could try to maintain the original tab selection: [2,(3)] -> [1,2,(3)] which is what I've done here because that is the most expedient thing I can do (I have to visit the lingering tab to correct the internal state).

The second idea is not likely to be viable for Buefy without changing the fact that what is being tracked is effectively an index in `b-tabs`.  I know my domain, so I can do the lookup to determine what the contents of the previous tab were `nv[idx] !== ov[idx]` in my example, where Buefy will only internally know the `idx` value at that level.  My expectation is to do anything other than attempting to preserve index, and changing it only when that index no longer exists, `b-tabs` would have to track a collection instead of being a thin-wrapper-ui element that has no concept of what its `b-tab-items` are showing.

In light of those, I propose this:  Try to maintain original selected index (even if that changes the shown tab contents), unless impossible in which case show tab with index (length - 1) unless length is 0 (set selected tab index to 0).  In my use, I never add or remove more than one tab at a time, so I don't know what the consequences of removing many at once may be.  The main desire is avoiding the visual garbage that my workaround produces.  Perhaps adding functionality to `b-tabs` that will defer pending animations until the target tab is known.  I'm not sure how that might work.

**Comment by jtommy** [comment]
There are too many possible use cases. In my opinion user should choose the right behavior by yourself

**Comment by GunnerGuyven** [comment]
The problem isn't choosing the right behavior.  The problem is that buefy misbehaves in a way that can only be partially mitigated as I have explained.  Your reason for ignoring is silly, just pick a behavior and support it.

**Comment by GunnerGuyven** [comment]
At the least give the implementer the ability to set `isActive` through an exposed property.

**Comment by service-paradis** [comment]
You can use `v-model` to set the desired tab.

**Comment by GunnerGuyven** [comment]
And I do in my workaround you will see.  The problem is that the tabs themselves are tracking isActive to display themselves, and they do not respect a single currently selected tab and allow more than one to be selected at once despite the tab controller having no such concept (it can only highlight one).

**Comment by service-paradis** [comment]
Can you create a codepen explaining your issue? You can use this as a baseline:
https://codepen.io/service-paradis/pen/VwLNqxp?editable=true&editors=101

**Comment by GunnerGuyven** [comment]
I don't even have to edit that to demonstrate it.

1. Select 'Games'
2. Click to deselect 'Show Music Item by using `v-if`'
3. Observe that now 'Games' and 'Comics' content are showing simultaneously
4. Select 'Videos'
5. Observe that now 'Videos' and 'Comics' content are showing.  'Comics' tab has to be visited to clear this lingering display.
6. Select 'Comics'
7. Observe that now only 'Comics' is content displaying
8. Select 'Games'
9. Observe that 'Comics' no longer lingers in the display, because we have finally visited it.

My observation is that the internal flag `isActive` controls display of these content divs but it is left in a stale state by the introduction or removal of tabs that change its index in the tab-list.  There is no upper limit to the number of tab contents you can trick into lingering in the display if you have total control over the tabs model.  The only way to clear the internal tracking state is by visiting each tab that lingers.

The problem with my workaround which attempts to automate this state fixup, is that the user can see it happening.  It results in extra animations, and with animations disabled it results in visible flickering.

Now, I can say that this is not an emergency problem for me, and I apologize for the snark of my initial retort.  I have chosen to design my application another way that does not use tabs due partially to this issue but also because I and my designers came up with a better way to communicate the content to the user.  I'm only trying to bring attention to an issue for which I don't consider my workaround to be very good.  Perhaps a better workaround can be published in the documentation.

**Comment by service-paradis** [comment]
Ok, I did not understand the problem correctly. I see that this is kind of disturbing to view the content of 2 tabs.
I maybe have a simple fix in mind which would look like this:
![captured (7)](https://user-images.githubusercontent.com/12817388/78287860-50cf7380-74ef-11ea-99e0-865fc6d9144b.gif)

Something along this should prevent having 2 tabs being active:
```
tabItems() {
            if (this.activeTab < this.tabItems.length) {
                let previous = this.activeTab
                this.tabItems.map((tab, idx) => {
                    if (tab.isActive) {
                        previous = idx
                        this.tabItems[idx].deactivate(this.activeTab, previous)
                    }
                })
                this.tabItems[this.activeTab].activate(this.activeTab, previous)
            }
        }
````

**Comment by jtommy** [comment]
@service-paradis ooh ok, thanks

**Comment by service-paradis** [comment]
Are you ok with the following fact:
> It does not select the previously displayed tab, but at least it is not displaying 2 tabs content.

**Comment by GunnerGuyven** [comment]
That does not bother me.  The big deal was keeping the interface clean in some way.

Keep in mind there is an opposite issue that can happen that can be demonstrated in the following way using the example listed above:

1. Click to enable 'Show books item (by adding / removing from the array)
2. Select 'Movies'
3. Click to unenable 'Show books item (by adding / removing from the array)
4. Observe that nothing is selected and nothing is shown
5. Click to reenable 'Show books item (by adding / removing from the array)
6. Observe that 'Movies' is selected again and its contents are shown

This is a problem caused by the same behavior that is somewhat less troublesome, but still represents a desync of the tab selection and the tab contents being displayed.

Now perform the above by using the 'Show Music Item (using `v-if`)' and note the difference in behavior.  I would encourage you to check this condition when designing your fix.  And I would recommend that some (single) tab remain selected and displayed except in the case that no tabs exist any longer.  It is likewise somewhat disturbing when all tabs cease to be selected due to a case like this.

**Comment by service-paradis** [comment]
Yes, I can reproduce this issue also where no tabs are being selected. Not exactly the same issue, but related for sure.
I will make a PR including a slightly modified version of the fix posted above. I will include in this PR a fix for the second issue when the last tab is selected.

**Comment by GunnerGuyven** [comment]
I appreciate everything.  I am sorry for my rudeness.

**Comment by service-paradis** [comment]
No problem
You can try my PR if you have some time:
https://github.com/buefy/buefy/pull/2374
