### ISSUE TITLE
Add native event to `b-table`s `@click` callback

### ISSUE THREAD

**Issue by apauly** [buefy/buefy#2212]
### Description

I'd like to add a click event to a `b-table` row and make the details open/toggle not only via the arrow but when clicking anywhere inside that row.
I know that a `b-table` does have a `@click` event which triggers for clicks on every row, but right now it seems that the native event is not passed to that callback.

However, my row does have some buttons so right now. Obviously, I don't want to click event to fire an a button click. Using the `b-table`s `@click` event, it seems there is currently no (non hacky) way to tell if the click happened on a button or not.

Maybe I do miss an obvious way to do this. If not, and you agree on this being useful, I could create a PR implementing this.

### Why Buefy need this feature

Allow people to build more custom UIs with `b-table`

**Comment by jtommy** [comment]
You might take a look at https://github.com/buefy/buefy/issues/2199.

**Comment by lgarczyn** [comment]
#2199 does not fix my problem, I want to add ctrl-click options to rows, but there is no way to get both the row and the native event.

Only way to do it is to add @click.native to every single row

**Comment by jtommy** [comment]
You can check the event parameters, for example event.ctrlKey

**Comment by lgarczyn** [comment]
Yes, but then I can't get the row, without adding an event listener on every single column

**Comment by lgarczyn** [comment]
But I don't get the event, because the buefy event doesn't transfer it to the user.

**Comment by ig1na** [comment]
Did  you find a solution to this ?

**Comment by lgarczyn** [comment]
We were still using native events as of two years ago. I have not worked on a buefy project since, so I don't know

**Comment by PierreMDL** [comment]
Did anybody find a way to get that event after all?
