### ISSUE TITLE
Carousel list - did you register the component correctly?

### ISSUE THREAD

**Issue by nigelwhite** [buefy/buefy#2213]
### Overview of the problem

**Buefy** version: [0.8.8]
**Vuejs** version: [@vue/cli 4.2.2] in Gridsome
**OS/Browser**: Chrome

### Description

One of the Buefy carousels throws an error in Vue Gridsome

### Steps to reproduce

copied code from https://buefy.org/documentation/carousel in the Carousel List segment.
Pasted this into a new single page component in Gridsome.
Look at this page in browser

### Expected behaviour
Carousel to display.
I tested the other flavours of Carousel at https://buefy.org/documentation/carousel, using the same process as above. They all worked fine.

### Actual behaviour

In browser, carousel controls are displayed, but not the carousel.
Viewed in browser Console.....
```
[Vue warn]: Unknown custom element: <b-carousel-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <Caropage> at src/pages/Caropage.vue
       <App> at node_modules/gridsome/app/fallbacks/App.vue
         <Root>
```

**Comment by jtommy** [comment]
@nigelwhite can you provide your code ? are you using bundle or individual components ?

**Comment by nigelwhite** [comment]
My bad. I just updated to Buefy 0.8.10 and the problem went away.

Thanks for a great plugin

**Comment by jtommy** [comment]
Nice to know you are using Buefy with Gridsome :)
