### ISSUE TITLE
add placeholder option to number inputs

### ISSUE THREAD

**Issue by neuronflow** [buefy/buefy#2214]
### Description

add placeholder to number inputs as suggested by examples
inspired by:
https://github.com/buefy/buefy/issues/2197

### Why Buefy need this feature
so users know which are typical inputs for the field

**Comment by jtommy** [comment]
It's a breaking change because at the moment the default value is 0 or min prop so it isn't possible to show placeholder

**Comment by kamaladenalhomsi** [comment]
any news on this?
