### ISSUE TITLE
Menu Bug?

### ISSUE THREAD

**Issue by mewcrazy** [buefy/buefy#2216]
Hello,

I just found a bug with the menu list? My markup looks as follows: I already tried removing the showJobs function to see if that's the reason for the thrown error, but it's not.

``
<b-menu>
	<b-menu-list>
		<b-menu-item class="mb-2 bg-purple" icon="user" label="Alle" @click="showJobs(0)"></b-menu-item>
		<b-menu-item class="mb-2 bg-transwhite80" icon="user" label="Freelancer.de"></b-menu-item>
		<b-menu-item class="mb-2 bg-transwhite80" icon="user" label="Interlance.de" @click="showJobs(2)"></b-menu-item>
	</b-menu-list>
</b-menu>
``
Vue: ^2.6.11
Buefy: ^0.8.10

**Comment by mewcrazy** [comment]
![image](https://user-images.githubusercontent.com/6299479/74125723-55a23600-4bd6-11ea-9642-6e61f0c64b86.png)

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/2094

**Comment by service-paradis** [comment]
Related to this Vue problem:
https://github.com/vuejs/vue/issues/10939

**Comment by mewcrazy** [comment]
Sounds relatively easy to solve though: Just remove the .native? :D I'm not even sure if they still work in Vue2, I tried to use them somewhere else and they did not.

**Comment by service-paradis** [comment]
Not that easy since the `.native` is needed when the tag used is not a `a`.

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/4a65d76a4d543f51b02acbd3457ed4a90d580ac1
