### ISSUE TITLE
Input Field with label "inside" and button add-on is not rounded

### ISSUE THREAD

**Issue by Lukasiniho** [buefy/buefy#2219]
### Overview of the problem

**Buefy** version: 0.8.10
**Vuejs** version: [X.X.X]
**OS/Browser**: Chrome on Windows 10

### Description

https://buefy.org/documentation/field#label-position 
The last example shows that the input field with the button add-on does not have rounded corners.

### Steps to reproduce

https://buefy.org/documentation/field#label-position See example in documentation

### Expected behavior

The input field has rounded corners

### Actual behavior

The input field does not have rounded corners

**Comment by yxngl** [comment]
Addons in Bulma don't support label. With label, the first child rule for radius breaks. Bulma suggests to use a separate field for normal label position. I think in this case the label position could be put at the end of the field with addons, as it is positioned absolutely.
