### ISSUE TITLE
Autocomplete with objects - store ID, display name

### ISSUE THREAD

**Issue by NoahStahl** [buefy/buefy#2220]
**Buefy** version: 0.8.10
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 80

Hi there, I'm trying to implement an autocomplete and having difficulty referencing the "id" property of the option as the value/model, while displaying the "name" property. Buefy seems to only want to use one or the other. I've tried multiple approaches with the @select or @input events to set manually, but can't get the component to cooperate with showing the name when the ID is the value. I've reviewed the source code and see there is an internal value, that is maintained separately from prop, so perhaps that is at issue?

Is there any method to achieve this?

**Comment by jtommy** [comment]
Can you reproduce your code?

**Comment by NoahStahl** [comment]
@jtommy Sure. I cloned the example codepen from docs and updated a bit:

https://codepen.io/noahstahl/pen/gOppXKb

The goal is to bind `selectedId` to the `id` value, not the name. Even setting the field prop to "id" and using a custom formatter to display the name, it still binds output of the formatter rather than the field. I would expect the formatter to format only for display purposes, not control the binding behavior. Any available approach here? Thanks!

**Comment by jtommy** [comment]
Yes, formatter is only for display.
The component emits select event so you can get the selected object and from it the id field.
What am I missing?

**Comment by NoahStahl** [comment]
Yet the formatter controls which value gets bound to the model. That's the question: is there a way to have v-model attach to the id property, which is not displayed?

**Comment by jtommy** [comment]
No v-model is related to the input. 
The selected Id is {{ selected.id }} in your case.

**Comment by NoahStahl** [comment]
Understood, thanks for your time!
