### ISSUE TITLE
b-dropdown autocomplete when typing

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#2226]
Hi, just wanna ask if it has a props for autocomplete for this dropdown, so that if the dropdown has many data, i just have to type it then it will select the data that is the same on what i typed, 

![image](https://user-images.githubusercontent.com/42717688/74293158-e9aa0400-4d74-11ea-8fb0-7ddab8338566.png)

![image](https://user-images.githubusercontent.com/42717688/74293499-ff6bf900-4d75-11ea-8e6d-8cf3a675e69a.png)

**Comment by jtommy** [comment]
No you should use autocomplete component

**Comment by kenichii** [comment]
What i mean is autocomplete like "b-select", every time I type the key that is in the select component, then it will automatically select it

**Comment by jtommy** [comment]
I don't understand well, you should use an input as trigger slot

**Comment by kenichii** [comment]
![Untitled](https://user-images.githubusercontent.com/42717688/74311251-f563ed80-4da9-11ea-8afd-294b4dfcc65b.png)

This is actually what im saying,

**Comment by kenichii** [comment]
instead of clicking dorothy, i just typed the first letter of the options then it will automatically selected

**Comment by kenichii** [comment]
i hope you'll understand what im trying to say 😄
