### ISSUE TITLE
There is no such support of getting rid of horizontal scroll bar while using buefy tabs

### ISSUE THREAD

**Issue by devendra-kumar1** [buefy/buefy#2229]
I am having requirement of showing multiple tabs horizontally. But it creates a horizontal scroll bar which looks ugly. Can you please help me out by how we can get rid of this.
 Please refer below link to see the example.

https://codepen.io/devendra-kumar157/pen/oNXjEOG?editable=true&editors=101

**Comment by devendra-kumar1** [comment]
Hi Jtommy,
 Thanks for quick turnaround. Can you please let me know in which version of buefy this will be available ?

**Comment by jtommy** [comment]
In the next 0.8.11
