### ISSUE TITLE
Option to output snackbar.message etc. safely without need to first sanitize

### ISSUE THREAD

**Issue by Leffe108** [buefy/buefy#2230]
### Background
This continues on from #2127 on the fact that some components have message/text properties that render using v-html and require the Buefy user to sanitize input.

### Description
I think it would be helpful to have a safe message/text attribute to snackbar etc. in Buefy that uses regular {{ message }} instead of v-html. A PHP framework I've used would in this case include an "encode" property which if true would use the safe/encoded output and if "encode" is false it would use the v-html equivalent. Ideally this encode property should be true by default although that would be a breaking change to Buefy.

Would it be a welcome framework addition to have an "encode" property (not sure what is the vue typical name of this property) or is it more vue-way to have two different message-properties?

### Why Buefy need this feature
Security by default. (if a breaking change is made to make the encoded output default)

But also simplifying usage of Buefy in that you don't have to make sure to sanitize the input yourself using third party solution when there is {{ message }} in core vue.

**Comment by jtommy** [comment]
Yes, you are right

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/aba999252e707e909bbe544a691eb5f3ab1cdd05
