### ISSUE TITLE
Input validation fails for password pattern if matched result is falsy (but still matches)

### ISSUE THREAD

**Issue by Colorfulstan** [buefy/buefy#2232]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.11]
**OS/Browser**: Chrome 80.0.3987.100

### Description
The input validation pattern deems an input invalid if the result is falsy. It should only do so if the match result is null.

Consider this pattern, here executed in the console:
`(?=.*[A-Z])(?=.*[0-9])(?=.{8,})`

The following screenshot shows that the regexp does return a match, but the index is 0 and the matched string is empty:
![image](https://user-images.githubusercontent.com/3855294/74388225-2caeba80-4dfb-11ea-8958-c4094ca0d035.png)

Nonetheless it is a valid match (otherwise the result would be `null`.

### Steps to reproduce

1. Create an input
2. use as pattern: `^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})`
3. use as input value: `sad123ASFsf123`

### Expected behavior

Validation succeeds

### Actual behavior

Validation fails unless changing the regExp to include an actual match-output i.e 
`^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(.{8,})` - `(.{8,})` instead of `(?=.{8,})`

**Comment by service-paradis** [comment]
Can you create a simple codepen where we can see the issue?
Does it work as expected if you use native input element?

**Comment by Colorfulstan** [comment]
huh, actually it's the same behaviour in the native inputs
