### ISSUE TITLE
Few requests to improve the library

### ISSUE THREAD

**Issue by FlorianChretien** [buefy/buefy#2233]
Hello,

First of all thank you for your work!

I have a few requests to improve the library and make it more complete. Would it be possible to make the following improvements (or if it's planned when will it be released?):

- Sticky Header
- Searchable with exclusion (!), Upper (>) and lower (<)
- Draggable Columns

These are features that we see everywhere (boostrap view, tablesorter ...) and which are really super practical for our customers ... it is very lacking to switch to 100% on buefy (on the table part).

Thank you very much !

**Comment by jtommy** [comment]
1 and 2 are good features but no so sure about 3

**Comment by FlorianChretien** [comment]
In the example of an ERP it can be appreciable for the user to personalize its interface

**Comment by jtommy** [comment]
@FlorianChretien Added sticky header a54e146840a0f4d5eb323317f907f97a5d78f88d.
About 2 you might use backend-filtering so you are able to filter using a custom comparator

**Comment by FlorianChretien** [comment]
Hi, 

Exemple of searchable with exclusion @jtommy 👼 

"Filter By Condition" 
https://revolist.github.io/revogrid/demo/ 

(And export on csv)

Still not convinced ? :) 

thanks for your return
Have good day
