### ISSUE TITLE
Prevent table columns from resizing when sorting

### ISSUE THREAD

**Issue by nathan-myhre** [buefy/buefy#2234]
### Description
Currently, table columns with the sorted prop enabled will resize when the sorted icon is added to the column header. It would be much preferred to have some padded space in the header so when the sorting icon is added on columns that contain data of the same length the column doesn't visibly resize. Column resizing can be seen in the gif below:

![resizing-columns](https://user-images.githubusercontent.com/29264264/74465185-c8ffae00-4e49-11ea-8d74-1b70e4b90d5e.gif)

The column would still be expected to resize if the sorted row content is wider than the unsorted row content.

### Why Buefy need this feature
We have had users complain that columns are resizing unexpectedly when being sorted and it's an unexpected result from other sortable tables on the web.

**Comment by service-paradis** [comment]
Will be fixed in the next release: https://github.com/buefy/buefy/pull/2223

**Comment by nathan-myhre** [comment]
That is great news! Thanks for the quick reply and we'll look forward to the next release.
