### ISSUE TITLE
CSS scoping accross the whole framework

### ISSUE THREAD

**Issue by rolandschuetz** [buefy/buefy#2235]
### Overview of the problem

**Buefy** version: all

### Description

CSS across the whole framework is scattered and creates unexpected behavior. 

Example one, buefy styles creep into non-buefy components:
https://codesandbox.io/s/buefy-css-creep-2edec

Example two, some in buefy defined clases do not work scoped:
https://codesandbox.io/s/buefy-scoped-css-2kb3i

**Comment by jtommy** [comment]
@rolandschuetz you're right, it needs some improvements

**Comment by cypressious** [comment]
Kinda related, if we install components individually instead of calling `Vue.use(Buefy)`, how can we set options like default values for toast position and so on?

**Comment by jtommy** [comment]
@cypressious individual component doesn't share a common config but I might add a constructor for each component plugin, for example:
```
Vue.use(Toast, {
defaultToastPosition: 'is-bottom'
})
```

What do you think ?

**Comment by cypressious** [comment]
@jtommy That would be awesome.

**Comment by jtommy** [comment]
@cypressious To be honest at the moment the Buefy config are common for all components, you might take a look at https://github.com/buefy/buefy/issues/1955#issuecomment-576144659

I could expose a BuefyConfig plugin in order to set custom options

**Comment by jtommy** [comment]
@cypressious take a look at https://github.com/buefy/buefy/issues/1955#issuecomment-616183794

**Comment by Tofandel** [comment]
@rolandschuetz there is nothing much you can do about example 2, this is an issue with how the vue scope works..

The scope in vue is not supposed to target subcomponents (yeah a bit weird I know)

**Comment by jtommy** [comment]
@rolandschuetz @Tofandel following the official docs https://vuejs.org/v2/style-guide/#Component-style-scoping-essential:

> Component libraries, however, should prefer a class-based strategy instead of using the scoped attribute.

**Comment by rolandschuetz** [comment]
@Tofandel Hmm... there's no way of moving this class into the scope?

@jtommy Targeting specific elements like BEM would do would fix the first example.

**Comment by Tofandel** [comment]
@jtommy Nope none, since it will be compiled like

.this-class-doesnt-work[data-v=scopeSomething] {

}

And the data attribute will never be on the subcomponent

However if you really really want to use scoped (which is not really recommended btw)

You could just have the class be on an element inside the template
```
<b-table-column class="this-class-does-not-work-in-scoped-scss" field="text" label="Text">{{ props.row.text }}</b-table-column>
```

**Comment by cypressious** [comment]
You can apply styles to subcomponents with the deep selector `>>>`: https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

For SCSS, use `::v-deep`

**Comment by Tofandel** [comment]
https://codesandbox.io/s/buefy-scoped-css-k2lrj

**Comment by rolandschuetz** [comment]
Ok, then this was just an error on my part. So only the other example matters ;)

**Comment by Tofandel** [comment]
@jtommy I see this as done on the roadmap, is it accurate?
@service-paradis Will overriding variables still be possible with the import into the component? I think it will break it and will need a workaround, tests needed

**Comment by jtommy** [comment]
Done -> the config component but nothing about css

**Comment by service-paradis** [comment]
@Tofandel
Nothing was made yet to scope styles. Importing style in components could be useful when people import only some Buefy components. As you said, we need to do more tests.

**Comment by jtommy** [comment]
@Tofandel I'm not sure that migrate to scope CSS it's a good solution and really applicable to be honest.

**Comment by wesdevpro** [comment]
Hello, from three years in the future 🤣 Does anyone know if I should just close this PR or should this still be a goal for Buefy v2?
@rolandschuetz @cypressious @Tofandel @jtommy @service-paradis @kikuomax @wesdevpro
