### ISSUE TITLE
Takes too long to destroy b-table

### ISSUE THREAD

**Issue by Humaots** [buefy/buefy#2236]
### Overview of the problem

**Buefy** version: [0.8.9]
**Vuejs** version: [2.6.11]
**OS/Browser**: windows 10/ chrome 80.0.3987.106

### Description

Thanks for your excellent work.
I'm newbie to buefy and using b-table to show data with 200 rows and 30 columns.
When I leaving the page that has the table, it takes about 30s for routing.
After I comment out the following code in table.js, it takes about 5s for routing.

```
  beforeDestroy: function beforeDestroy() {
    var _this2 = this;

    if (!this.$parent.visibleData.length) return;
    // if (this.$parent.$children.filter(function (vm) {
    //   return vm.$data._isTableColumn && vm.$data.newKey === _this2.newKey;
    // }).length !== 1) return;
    var index = this.$parent.newColumns.map(function (column) {
      return column.newKey;
    }).indexOf(this.newKey);

    if (index >= 0) {
      this.$parent.newColumns.splice(index, 1);
    }
  }
```

### Expected behavior

I can't understand the meaning of that commented out code. Is that any other way to improve the BTableColumn component destruction performance?

**Comment by jtommy** [comment]
@Humaots I'm working on it
