### ISSUE TITLE
Navbar's z-index is overlapping modals

### ISSUE THREAD

**Issue by nixxholas** [buefy/buefy#2238]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.11]
**OS/Browser**: macOS 10.13.3 / Brave Browser

### Description
Photo describes the issue i'm in, simply put the modal doesn't flow to the top index due to the navbars. The modal is under the first (First top, last bottom) navbar in the picture

[Codepen](https://codepen.io/nixxholas/pen/WNvxxra)

<img width="1240" alt="Screenshot 2020-02-15 at 11 31 27 AM" src="https://user-images.githubusercontent.com/4703269/74581221-f71af480-4fe7-11ea-8ae8-5cf047aa2bfd.png">

### Steps to reproduce
1. Create a couple of navbar (Left side with a text and right side with a button that launches a modal) + table components
2. Try seeing how the modal goes under the other navbars.

### Expected behavior

Modal should be at the top.

### Actual behavior

Modal is below the other navbars. It is definitely a z-index issue because these modals have a different behaviour distinctively for their overlapping. Try the codepen out to see how it goes.

**Comment by jtommy** [comment]
@nixxholas can you reproduce it on codepen or similar ?

**Comment by nixxholas** [comment]
@jtommy Apologies for the late response. Just got to see this. Updated the issue with the codepen.

**Comment by jtommy** [comment]
@nixxholas you should define modal before each navbar (btw not into the navbar)

**Comment by nixxholas** [comment]
@jtommy What if the modal and button are together (In a child component)

**Comment by jtommy** [comment]
No no, I mean that modal should be defined outside navbar

**Comment by nixxholas** [comment]
@jtommy Yes I get it. Its just that my child component is really deeply stuck lol, I have the button and modal together. So instead of seeing the 'Create' button and modal, its actually one component.

**Comment by jtommy** [comment]
It's ok but simply move it before navbar :)
