### ISSUE TITLE
spread in object literals can not be supported on firefox 55-

### ISSUE THREAD

**Issue by mzz2017** [buefy/buefy#2239]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.10]
**OS/Browser**: Firefox 45.0, Firefox 52.3

### Description

`SyntaxError: invalid property id` will be showed on firefox 55-. And after I add `transpileDependencies: ["buefy"]` in vue.config.js, it works.

### Expected behavior

buefy can support firefox 55-

**Comment by service-paradis** [comment]
Will need to see with @jtommy, But I think Buefy should support Stable version of major browsers. Firefox 55 is now 3 year old.
For older browsers, you can use Polyfills and the option to transpile dependencies like you have.

**Comment by jtommy** [comment]
Are you importing Buefy from src ?

**Comment by mzz2017** [comment]
@jtommy 
![image](https://user-images.githubusercontent.com/30586220/74677441-45e8aa00-51f3-11ea-8178-4179eea564ca.png)
I import it from node_modules.
