### ISSUE TITLE
Can't mount datetimepicker in mobile view

### ISSUE THREAD

**Issue by ManUtopiK** [buefy/buefy#2240]
### Overview of the problem

**Buefy** version: 0.8.10

### Description

In mobile view, component datetimepicker could be mounted.  
Error :
`Cannot read property '$forceUpdate' of undefined`

### Steps to reproduce

1- Add datetimepicker component
2- Toggle device in devtools (cmd+maj+M)
3- With mobile view, refresh your page
4- error.

### Expected behavior

No error.

### Error study
[Line 3](https://github.com/buefy/buefy/blob/dev/src/components/datetimepicker/Datetimepicker.vue#L3) there is a v-if that check if is mobile and display `b-input` instead of datetimepicker. [line 320](https://github.com/buefy/buefy/blob/dev/src/components/datetimepicker/Datetimepicker.vue#L320) the component mount with $refs.datepicker that doesn't exist.

**Comment by Garito** [comment]
Hi,
I have the same issue but not on mobile
I've checked the pull request modifications and instead to check if is mobile or not, you should wait for the nextTick to force the update
I'ven't tested this idea but the error is typical in vue (the refs aren't mounted yet in the mounted event of the parent)
In my case, it fails when the v-model value changes even to the today date that the picker sets if v-model starts with null
For more context, the same page with a datepicker works fine
