### ISSUE TITLE
Confirm on dialog alert triggers form.submit()

### ISSUE THREAD

**Issue by FabianHassert0407** [buefy/buefy#2241]
### Overview of the problem

**Buefy** version: [0.8.10]
**Vuejs** version: [2.5.13]
**OS/Browser**: Windows 10 / Chrome, Firefox

### Description

I use dialog alert with a confirm handler.
Pressing the OK-Button submits the sorrounding form.

### Steps to reproduce

Open the codepen link and use the alert dialog:
https://codepen.io/FabianHassert/pen/abOZyVq?editors=1010 

### Expected behavior

The alert should not trigger a form submit automatically.

### Actual behavior

Pressing the OK-Button submits the sorrounding form.

**Comment by jtommy** [comment]
@FabianHassert0407 add `type="button"` attribute to button tag
