### ISSUE TITLE
Menu item does not resolve named route but it works.

### ISSUE THREAD

**Issue by yangwao** [buefy/buefy#2243]
### Overview of the problem

**Buefy** version: 0.8.10
**Vuejs** version: 2.6.10
**OS/Browser**: OSX/Chrome

### Description

Router-link **works** with named route, but the link does not seem to be resolved, no error or warning involved, it works.

![image](https://user-images.githubusercontent.com/5887929/74853701-8f91db80-533e-11ea-8746-4979c417ccff.png)

🎥https://i.imgur.com/gE0wYUF.mp4

### Steps to reproduce

1. Use named routes in Menu component 
2. Hover over link
3. Link shows [object Object] 
4. Look on code https://github.com/vue-polkadot/apps/blob/b5ecf5f5425cbad84526a5e736d0efca38fa851f/dashboard/src/components/SidebarMenu.vue#L75

### Expected behaviour

Link should be resolved, for example, if there is `/accounts.`

### Actual behaviour

Link shows [object Object] but it will redirect to correct place.

**Comment by jtommy** [comment]
I'm running your project and it works well

**Comment by yangwao** [comment]
And it does resolve named route in hovered link well? You are in the
develop branch?

**Comment by jtommy** [comment]
@yangwao you're using href attribute too, please remove it :)

**Comment by yangwao** [comment]
@jtommy after removing **href**, it now does not pass [object Object] 

![image](https://user-images.githubusercontent.com/5887929/75165165-4072ee80-5722-11ea-8631-28abf0c3be77.png)

but default **a**, external links does not work now. (hover is over book icon, white coloured)

![image](https://user-images.githubusercontent.com/5887929/75165224-597b9f80-5722-11ea-90fa-0d1e301a85b0.png)
```
  {
    name: 'Github',
	icon: 'code-branch',
    to: 'https://github.com/vue-polkadot/apps',
  },
  {
    name: 'Wiki',
	icon: 'book',
    to: 'https://wiki.polkadot.network/',
	tag: 'a',
  },
```

By documentation, it should work even without tag, as 'a' is the default here https://buefy.org/documentation/menu

**Comment by jtommy** [comment]
To isn't correct for external link, in this case you have to use href

**Comment by yangwao** [comment]
@jtommy what's then best practice for single Menu combining router-links and external links? Like in my case and asking for others.

For now, I had to split lists for separate object and works 😇
