### ISSUE TITLE
After selecting year on the datepicker

### ISSUE THREAD

**Issue by kenichii** [buefy/buefy#2249]
Hi,
We encountered an issue on the datepicker after we selected a year, 
then after we select outside but when we try to choose or find the year, we can't find the following year that we already selected.

![date1](https://user-images.githubusercontent.com/42717688/75013686-ba576d80-54bf-11ea-89b6-eb8b181e1db0.png)
![date2](https://user-images.githubusercontent.com/42717688/75013687-bc213100-54bf-11ea-94a1-5cc3fdddc1b7.PNG)
![date3](https://user-images.githubusercontent.com/42717688/75013688-bcb9c780-54bf-11ea-8008-e551e4d278cc.png)

**Comment by jtommy** [comment]
You should change the default `yearsRange` prop (in the constructors too)
