### ISSUE TITLE
Autocomplete with Tag Input is broken (list not rendered)

### ISSUE THREAD

**Issue by Kaisirak** [buefy/buefy#2250]
### Overview of the problem

**Buefy** version: [0.8.11]
**Vuejs** version: [2.6.11] and [3.0.0]
**OS/Browser**: Chrome on Windows 7 and Android

### Description

The Autocomplete list doesn't render with Tag Inputs.
The dropdown opens but the list is blank.

The issue happens on both the Buefy documentation and on my own project, as well as this codesandbox.

https://buefy.org/documentation/taginput#autocomplete

https://codesandbox.io/s/relaxed-rgb-pq0lk?fontsize=14&hidenavigation=1&theme=dark

The issue #2156 still exists on this new version, and seems to now also happen on the Buefy documentation as well.

### Steps to reproduce

Use a Tag Input with Autocomplete

### Expected behavior

Autocomplete list renders data/text

### Actual behavior

Autocomplete list is blank

![taginputissue](https://user-images.githubusercontent.com/5866233/75016481-f0eda380-543f-11ea-981d-7a2a5a24dbb5.jpg)
![taginputissue2](https://user-images.githubusercontent.com/5866233/75016491-f5b25780-543f-11ea-818f-c17642e8b3e4.jpg)

**Comment by jtommy** [comment]
Please follow this https://github.com/buefy/buefy/issues/2014. I'll fix soon, thanks
