### ISSUE TITLE
Inline CSS cut-off after implementing

### ISSUE THREAD

**Issue by ChristopheVanassche** [buefy/buefy#2251]
### Overview of the problem

**Buefy** version: [0.8.11]
**Vuejs** version: [4.1.2]
**OS/Browser**: Chromium based browsers (Chrome in my case)

### Description

I've implemented Buefy as described. Everything works when using the CDN's, but I don't want to use those. When I implement it via the main.js file, the CSS gets cut off. (Seems like some kind of character limiting)
I'm not sure if this has to do with Buefy, or something with the Vue framework. I've tried the setup several times, but I get the same result every time.

Images:
- Image implementation:
![image](https://user-images.githubusercontent.com/7403959/75019051-7ef17a80-5490-11ea-9314-ac4d3fbe0b7e.png)
- Image issue:
![image](https://user-images.githubusercontent.com/7403959/75019080-8f095a00-5490-11ea-8a06-80dbd0c04db1.png)

### Steps to reproduce

1. Clean install vue.js
2. Implement full bundle Buefy via npm like described [here](https://buefy.org/documentation/start)

### Expected behavior

Expecting the Buefy CSS to load inline completely

### Actual behavior

The (minified) CSS gets cut-off after a certain # of characters

**Comment by jtommy** [comment]
Can you reproduce it on codesanbox?

**Comment by service-paradis** [comment]
I think it is only the Chrome developper tools who truncate the code in styles when it is large. The code should be there, but you cannot view it all in the console.

**Comment by ChristopheVanassche** [comment]
> I think it is only the Chrome developper tools who truncate the code in styles when it is large. The code should be there, but you cannot view it all in the console.

Well, that is what I was thinking at first. The problem though is that the part after the truncated code is not loaded. When I implement the buttons for example, the css doesn't get applied.

![image](https://user-images.githubusercontent.com/7403959/75038967-e3740000-54b7-11ea-85d7-90df5c052801.png)
![image](https://user-images.githubusercontent.com/7403959/75039115-41a0e300-54b8-11ea-8d95-3e66b693ee54.png)

I've downloaded firefox, and it seems al the css code is shown there. But the buttons still don't get styled. So there is some issue that prevents the css from being applied.

**Comment by ChristopheVanassche** [comment]
> Can you reproduce it on codesanbox?

I've tried the [sandbox ](https://codesandbox.io/s/epic-dawn-xyekn)environment, and it seems to work there! So I'm not actually sure what could be the problem, as I applied the same code.

**Comment by service-paradis** [comment]
It looks like there is something who prefixed every classes of the Buefy CSS file. `.Buefy_delete_25SPO` for example... Do you configure any CSS loader or something?
Looks like it comes from your configuration.

**Comment by ChristopheVanassche** [comment]
> It looks like there is something who prefixed every classes of the Buefy CSS file. `.Buefy_delete_25SPO` for example... Do you configure any CSS loader or something?
> Looks like it comes from your configuration.

Looks like you were right! I didn't notice it, but they got prefixed somehow indeed.
In my vue.config.js the `requireModuleExtension` got set to false, what gave me the error:

![image](https://user-images.githubusercontent.com/7403959/75040815-a7429e80-54bb-11ea-9ad8-63839812684b.png)

I've searched for quite some time on this, thanks for the help!
