### ISSUE TITLE
Feature Request (Tooltip): Use target property instead of wrapping on an element

### ISSUE THREAD

**Issue by jbienesdev** [buefy/buefy#2252]
### Description

Tooltip's current design is that it's wrapping the element that needs to show the message upon hovering.

I propose that the architecture should change or even just an additional functionality to the tooltip component that we have right now. Separating the tooltip and the element is a great design that I got from Bootstrap-Vue (https://bootstrap-vue.js.org/docs/components/tooltip/). They are binded together by using `target` (for the tooltip) and `id` (for the element).

### Proposed Design

We can make this backwards-compatible. So wrapping a certain element should also work. This is just an added prop.
```html
<b-tooltip target="btn-1" label="Simple text"></b-tooltip>
<b-button id="btn-1">Click Me</b-button>
```

### Why?

Given this scenario, we have 2 users in our system: `guest` and `admin`. 

Here's a button component that adds a user.
```html
<b-button>Add User</b-button>
```

We have a computed function to check if a user is an admin.
```js
computed: {
  isAdmin() {
    return this.role.is_admin
  }
}
```

For admin users, the button should look normal and clickable with no tooltips. For guest, the button should have a tooltip ("Admins can only add a user.") and it is `disabled`. I've come up to a markup that looks like this.
```html
<b-tooltip v-if="!isAdmin" label="Admins can only add a user">
  <b-button disabled>Add User</b-button>
</b-tooltip>
<b-button v-else @click="addUser">Add User</b-button>
```

So, the button is now duplicated because of the tooltip. If this feature request is being considered, it should look like this.
```html
<b-tooltip v-if="!isAdmin" label="Admins can only add a user" target="btn-add-user"></b-tooltip>
<b-button :disabled="!isAdmin" id="btn-add-user" @click="addUser">Add User</b-button>
```

**Comment by jtommy** [comment]
Yes, I need to refactor it in the next breaking version.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/f0cfa37b064b4aa43d4aa698ffdeffa30a85b0fd

You'll be able to use `content` slot in order to customise it
