### ISSUE TITLE
button with icon does not show icon

### ISSUE THREAD

**Issue by Leftyx** [buefy/buefy#2254]
### Overview of the problem

**Buefy** version: 0.8.11
**Vuejs** version: 2.6.11
**OS/Browser**: ALL

### Description

Latest version of Buefy breaks the rendering of a `b-button` with `b-icon` inside (I need a button without borders).

```
<b-button type="is-text">
     <b-icon icon="delete" type="is-success" />
</b-button> 
```

### Steps to reproduce

1. Open this [codepen](https://codepen.io/Leftyx/pen/oNXYXEV?editors=1010)
2. Reference latest buefy version 0.8.11 (https://unpkg.com/buefy@0.8.11/dist/buefy.min.js)
3. Render page

### Expected behavior

![image](https://user-images.githubusercontent.com/171024/75028517-4bb2e980-5498-11ea-82bb-a5c18d4b17ef.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/171024/75028714-b3693480-5498-11ea-96de-ed8e11a3e8df.png)

It was working fine until version **0.8.10**.

**Comment by service-paradis** [comment]
I had the same problem yesterday having a button that contains only a single HTML element.

```
<b-button>
  <span>{{ displayedText }}</span>
</b-button>
```
[codepen example](https://codepen.io/service-paradis/pen/OJVbMaG?editable=true&editors=101)

My workaround for those case right now is yo add another empty an not useful element...
```
<b-button>
  <span>{{ displayedText }}</span><span></span>
</b-button>
```

**Comment by Leftyx** [comment]
I can see there are loads of workarounds in place.
I am worried cause every time there is a new version something breaks.

**Comment by service-paradis** [comment]
There are 6 [workaround](https://github.com/buefy/buefy/issues?q=is%3Aissue+is%3Aopen+label%3Aworkaround) right now. Some of them are more related to Bulma than to Buefy. I dont think this is a lot.
Some of them (2 as I know) are already being checked out.

**Comment by jtommy** [comment]
@Leftyx I really apologize it was my fault during an internal test

**Comment by Leftyx** [comment]
> 
> 
> @Leftyx I really apologize it was my fault during an internal test

@jtommy That's ok. I was a little bit annoyed cause my client found the issue so I had to quickly revert the changes.

**Comment by jtommy** [comment]
@Leftyx I know, and i'm sorry but I'll fix it soon

**Comment by holtolee** [comment]
If you put content in your button with a slot or more complex things like transition it is broken too.

**Comment by jtommy** [comment]
Close 9b15e7c2c2d206c3dfab96f9fe6a1bd19063fbf6
