### ISSUE TITLE
Button icons not centered in v0.8.12

### ISSUE THREAD

**Issue by chris-doco** [buefy/buefy#2257]
### Overview of the problem

**Buefy** version: [0.8.12]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS 10.15.3/Google Chrome 79.0.3945.130

### Description

In the new version 0.8.12 if you have a button with just an icon: e.g.
`<b-button type="is-danger" icon-right="delete" />`
The button isn't centered anymore.
You can see it here: https://buefy.org/documentation/button/

### Steps to reproduce

Create a `b-button` with just an icon and no text or anything else.
`<b-button type="is-danger" icon-right="delete" />`
### Expected behavior

The icon inside the button should be centered.

### Actual behavior

The icon inside the button isn't centered. It is either on the left if you use `icon-left` or on the right if you use `icon-right`.

**Comment by jtommy** [comment]
At the moment you might put a b-icon into the button as workaround

**Comment by francoism90** [comment]
This is a bit breaking, I'm using `icon-right` a lot on buttons that only should display an icon.
What's the reason behind adding an extra span before the icon?

**Comment by jtommy** [comment]
Only a my fault, I'm sorry

**Comment by francoism90** [comment]
@jtommy No worries! I was just wondering if one should switch to the workaround as permanent solution. :)

I'll revert the upgrade and wait for a fix. (Y)

**Comment by jtommy** [comment]
No no, I'll restore it

**Comment by service-paradis** [comment]
There is an additional space before any content (ex. icons) as seen in the documentation:
![image](https://user-images.githubusercontent.com/12817388/75117860-52319480-5643-11ea-9387-fc679a84f4b2.png)

There is an empty span who should not be there:
![image](https://user-images.githubusercontent.com/12817388/75117892-902eb880-5643-11ea-89de-549422b8411f.png)


Needed to use a hack right now to solve buttons having single icon:
```
.button {
  > span {
    &:empty {
      display: none;

      + span {
        margin-left: -.5rem!important;
      }
    }
  }
}
```

**Comment by lmarciano9** [comment]
This might be causing the same misalignment if you center a column in a table because of the sorting arrow icon. Taken from the documentation page: 

![Screenshot_18](https://user-images.githubusercontent.com/48482588/75405312-19681880-58ec-11ea-979e-61f6eeb7f661.png)

**Comment by bender-a** [comment]
We could fix all of this with the updates to the vue-template-compiler, vue-loader etc.
We can try to handle it with the version we are currently on, but i could not get it to work
[See template-compiler options](https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options)

**Comment by sookoll** [comment]
This workaround doesn't seems to fix it. When we can hope for fixed release?

**Comment by emielmolenaar** [comment]
Fix is already in master (https://github.com/buefy/buefy/commit/454c206e73eee1236bc96e22a584a3ba10d91449) so expect a release anytime soon.
