### ISSUE TITLE
FR: Carousel that shows multiple slides

### ISSUE THREAD

**Issue by Christilut** [buefy/buefy#2258]
### Description

The carousel is really great but it would be nice if it could show multiple items at the same time. For example, I would like to show 3 items (out of many more) and they should move 1 at a time.

The same way Slick.js does it (multiple slides).

### Why Buefy need this feature

Seems like a common use of a carousel.

**Comment by Christilut** [comment]
Never mind! Of course the answer comes to me minutes after making an issue. This is totally possible with the `b-carousel-list`. I thought it was for image/text combination only at first.

Buefy rocks 💪

**Comment by yasin7044** [comment]
Yeah but in bcarouse list we can add dots functionality if there any way to add that then it world be awesome
