### ISSUE TITLE
Button - Text is not centered

### ISSUE THREAD

**Issue by Khazl** [buefy/buefy#2259]
### Overview of the problem

**Buefy** version: ^0.8.10
**OS/Browser**: Chrome latest

### Description

If you open a dialog prompt, the text of the control buttons are not centered.

### Steps to reproduce

1. Open a dialog prompt
2. Check text alignment

### Expected behavior

Button text should be centered.

### Actual behavior

Button text is not centered.

![Screenshot_31](https://user-images.githubusercontent.com/1067634/75114340-86ae4c00-5655-11ea-9100-7a9096ffb7df.jpg)

**Comment by service-paradis** [comment]
There is an additional space before any content (ex. icons) as seen in the documentation:
![image](https://user-images.githubusercontent.com/12817388/75117860-52319480-5643-11ea-9387-fc679a84f4b2.png)

**Comment by Khazl** [comment]
@service-paradis, this looks like a different issue.

**Comment by Khazl** [comment]
Closed with https://github.com/buefy/buefy/commit/5f012e040b49f33da827be596e4c0d61a1498548
