### ISSUE TITLE
"Required" field alert text doesn't play nice with field addons

### ISSUE THREAD

**Issue by jamespdaily** [buefy/buefy#226]
### Description

If I have a "required" input field with a button addon, the alert text for not filling in the required field causes text misalignment by trying to force the text to the right of the field box instead of below the actual field.  

This works fine without using button addons

### Steps to reproduce

      <b-field label="Full Name *">
          <b-field>
            <b-input
              v-model="full_name"
              required>
            </b-input>
            <p class="control" expanded>
              <button class="button is-danger is-outlined" @click="full_name = null">
                <b-icon icon="clear"></b-icon>
              </button>
            </p>
          </b-field>
        </b-field>

### Expected behavior

I'd expect the alert text for failing to fill in a required field to still appear below the field group.

### Actual behavior

![chrome_2017-08-07_10-05-27](https://user-images.githubusercontent.com/478289/29033740-f205e104-7b63-11e7-8b84-7f2cb1262216.png)

**Comment by jamespdaily** [comment]
I guess I'd also like to use this chance to ask if there is a way to get the length "Date" field to align with the rest of the fields above it

**Comment by rafaelpimpa** [comment]
This one is tricky, Bulma wants us to add the helper (message) on the field as you can see here: http://bulma.io/documentation/form/general/, but I'm thinking about moving it to the control itself (``b-input``), will prevent this kind of bug.

**Comment by jamespdaily** [comment]
I gotcha. Is there any way I can help test? I might dig in to the code and see about moving that manually in the meantime to provide some feedback

**Comment by abhinukala** [comment]
@jamespdaily @rafaelpimpa @jtommy  any workaround for this? I have similar kind of issue I am using vee-validate for validation instead of basic HTML5 validation. I have raised an issue #748 but no response yet. I want to reduce the number of lines of code. Any help would be greatly appreciated.

**Comment by KhoaDuongUQ** [comment]
Any solutions?

**Comment by Davaasurenx** [comment]
How fix this https://codepen.io/anon/pen/KExQPB?&editable=true&editors=101?

**Comment by service-paradis** [comment]
Related to #1226 with fix/hack proposal
