### ISSUE TITLE
Slider hover slot/tooltip?

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#2261]
### Description

Is it possible to have a hover tooltip on the slider component?
It would be great if the slider label would have a slot, so it can be customized.

### Why Buefy need this feature

It is already has a tooltip when clicking on a range, hovering would be nice to have. :)

Thanks.

**Comment by bender-a** [comment]
Could you please provide a codesandbox? 
I don't really get what you mean, because the slider thumb already has a tooltip on hover.

Could you maybe provide something visually or in a codesandbox?

**Comment by francoism90** [comment]
@bender-a I do mean when hovering the slider itself, not the thumb:
![image](https://user-images.githubusercontent.com/5028905/75604968-77f4e880-5ade-11ea-8c9e-8efabbdab66b.png)

I solved this by simple adding an extra parent:
```pug
nav(ref="slider" @mousemove="onSeekerHover" @mouseleave="onSeekerLeave")
   b-slider(ref="seeker" rounded lazy)
```
