### ISSUE TITLE
 should provider numberinput icon prop link 'icon-minus' 

### ISSUE THREAD

**Issue by Valar103769** [buefy/buefy#2262]
I mentioned the issue, the solution you gave me did not solve my problem, and the issue was closed by you.
I re-describe my question below   [issue](https://github.com/buefy/buefy/issues/2248)
1: I use b-numberinput instead of b-icon
2: Even if I set customIconPacks, it does not take effect intentionally,
### Description
correct <i class="iconfont if-minus"></i>
error <i class="iconfont minus"></i>

```vue
Vue.use(Buefy, {
    defaultIconPack: 'iconfont',
    defaultDialogConfirmText: '确认',
    customIconPacks:{
        internalIcons:{
            'if-minus':'minus',
            'minus':'if-minus'
        }
    }
});
```

Please, please do n’t close other people ’s issue, after all, it does n’t really solve it.

**Comment by jtommy** [comment]
Please provide me an example on codesansbox

**Comment by Valar103769** [comment]
> Please provide me an example on codesansbox

https://codepen.io/valar123/pen/gOpgMGL
