### ISSUE TITLE
b-input type="number" not working

### ISSUE THREAD

**Issue by frellan** [buefy/buefy#2267]
### Overview of the problem

**Buefy** version: [0.8.12]
**Vuejs** version: [2.6.11]
**OS/Browser**: Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

### Description

I am setting `type="number"` on the `b-input`-node but the HTML5 input is still rendered as `type="text"`.

Seems to have something to do with the `newType` variable that is still set to `text`. As soon as I edit the input the `model.firstObstacle` is converted from a `number` to a `string`. It is a `number` in the first place!

<img width="271" alt="Screenshot 2020-02-25 at 10 32 04" src="https://user-images.githubusercontent.com/8545521/75234023-1ec54600-57ba-11ea-990e-855ded9d4346.png">

I can't work it out since when looking at the code `newType` is set from the props, and the prop `type` is `number`.
<img width="294" alt="Screenshot 2020-02-25 at 10 43 52" src="https://user-images.githubusercontent.com/8545521/75234983-dd359a80-57bb-11ea-9993-7bc9802e55d6.png">

### Steps to reproduce

1. Add `type="number"` like this. (placeholder is in swedish).
```
<b-input v-if="model" v-model="model.firstObstacle" type="number" placeholder="Hur långt är det till första hindret?"/>
```
2. It is still rendered as `type="text"`
<img width="881" alt="Screenshot 2020-02-25 at 10 28 51" src="https://user-images.githubusercontent.com/8545521/75233742-a199d100-57b9-11ea-8d19-76cfe172d88f.png">

### Expected behavior

It should render an HTML5 `<input type="number">`.

### Actual behavior

It renders an HTML5 `<input type="text">` anyway.

**Comment by frellan** [comment]
I have two `b-input` with a `v-if` and another below it with a `v-else :loadling="true"`. I use it like that since I want the form to render when the model that the input is dependant on is fetching from the backend. I didn't have `type="number"` on the `v-else` input below it and when I added it onto that one, it works!

I thought those two were completely different components but it seems they share state somehow. Maybe more of a vue bug than a buefy bug, but it's freakin strange.

**Comment by yxngl** [comment]
Check Vue documentation for conditional rendering and key.

**Comment by soubenz** [comment]
If you're looking to rendering your input as number instead of a text , append `.number` to your ` v-model` .  So instead of `v-model` you would have ` v-model.number`.  
 This worked for me. Following the vuejs docs. 
https://vuejs.org/v2/guide/forms.html#number
