### ISSUE TITLE
Is it possible to increase the slider's focus?

### ISSUE THREAD

**Issue by francoism90** [buefy/buefy#2269]
### Description

I really like the slider, but sometimes it's hard to actually click somewhere on the slider without using the thumb especially on small sizes:

![image](https://user-images.githubusercontent.com/5028905/75261136-e68a2b80-57ea-11ea-857b-bb3f2f3314d4.png)

### Why Buefy need this feature

It would be great to allow a bit of threshold so a change can be triggered, even when the user isn't actually on the slider.

I'll try to take a look at the SCSS and make a PR if this isn't possible yet.

**Comment by yxngl** [comment]
Do you want to increase the width of the track or just make clickable region wider?

**Comment by francoism90** [comment]
@yxngl I would like to increase the last one, the clickable region.

**Comment by jtommy** [comment]
@francoism90 Probably you're right.
@yxngl @francoism90 a PR is welcome 👍

**Comment by melogustavo** [comment]
Hey @francoism90 I would like to help you out.

@yxngl did you already start working on a PR for this?

**Comment by jtommy** [comment]
@melogustavo make your PR :)

**Comment by yxngl** [comment]
What are your thoughts and approaches to this? I didn't start. My initial idea is not to change HTML.  For workaround in a single use case, increasing the height of the track and using color gradient to fake a thinner look of track and fill will do. But these are in SCSS, do you want an API for it?

**Comment by jtommy** [comment]
@yxngl if we can manage it with a prop why not ?

**Comment by melogustavo** [comment]
Hey @francoism90, Just opened a PR :)

**Comment by francoism90** [comment]
@melogustavo Thanks, great stuff!
