### ISSUE TITLE
Do not trigger custom animation(v-leave-active) in dropdown component 

### ISSUE THREAD

**Issue by Shahinyanm** [buefy/buefy#2273]
### Overview of the problem
V-enter-active working correctly, but v-leave-active doesn’t work

**Example**: [https://codepen.io/Shahinyanm/pen/QWbpMKx](https://codepen.io/Shahinyanm/pen/QWbpMKx)

**Buefy** version: [0.8.11]
**Vuejs** version: [2.6.10]
**OS/Browser**: Windows/Chrome

**Comment by jtommy** [comment]
You are right, I'll take a look soon

**Comment by jtommy** [comment]
I'm adding your animation in the core too ;)

**Comment by Shahinyanm** [comment]
Thank you dear :)
