### ISSUE TITLE
Select Fields for Dialog Prompts

### ISSUE THREAD

**Issue by Khazl** [buefy/buefy#2276]
### Description

 I would love to have dialog prompts with selects as input.
So if you set:
```js
inputAttrs: {
  type: 'select',
  placeholder: 'Select User',
  options: this.users
}
```
You will see a select element inside your prompt.

### Why Buefy need this feature

For more flexibility and cover more use cases.
![Bildschirmfoto 2020-02-26 um 15 42 48](https://user-images.githubusercontent.com/1067634/75355404-ba37e300-58ae-11ea-818e-3ef91dc29099.png)

**Comment by bender-a** [comment]
While this seems like something useful, you can always just build this by yourself using the modal, right?

**Comment by Khazl** [comment]
> While this seems like something useful, you can always just build this by yourself using the modal, right?

Yes, but I would like to use the already existing dialog API. And it would also perfectly fit into the dialog prompt semantic.

**Comment by Khazl** [comment]
So, is it something we want? I could implement it and open a PR
@jtommy

**Comment by jtommy** [comment]
@Khazl I agree with @bender-a .
You need of select but probably someone needs of other component so I don't think it's good put all on dialog
