### ISSUE TITLE
Password Reveal Default State

### ISSUE THREAD

**Issue by farshad-sadri** [buefy/buefy#2283]
### Description

In the input component, password type, there is a "password-reveal" feature which adds the functionality of revealing password. 

1. Password Reveal Default State: Visible/Hidden  -  I think adding a default state would help build better UX as in some forms it is trending to reveal passwords initially and upon user decision to hide it.
2. Reversing the reveal icon: Logically when password is hidden the icon eyes-off or eyes-slash makes more sense as you can not see it and when password is hidden it makes more sense to make it eye-slash.

### Why Buefy need this feature

I think it adds better UX to forms.

**Comment by service-paradis** [comment]
There is a [closed discussion about #2](https://github.com/buefy/buefy/issues/1355#issuecomment-525848525) with a solution to inverse the icons.
