### ISSUE TITLE
Datepickers close on click in shadow DOM

### ISSUE THREAD

**Issue by simonjodet** [buefy/buefy#2284]
### Overview of the problem

**Buefy** version: 0.8.12
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 80.0.3987.122 (MacOS 10.15.3)

### Description

When the Buefy app is inside a shadow DOM element, datepickers close on click. You can't change month for example.

### Steps to reproduce

Create a Vue/Buefy app inside a shadow DOM in order to isolate the app from the rest of the page. 

This is especially important when writing a widget that is going to be included in different websites. Bulma is not namespaced so shadow DOM is really useful in this usecase.

Here's a codepen that reproduces the issue : https://codepen.io/sjodet/pen/vYOJgYR

### Expected behavior

1. Open the datepicker
2. Click on next month button
3. The date picker stays open

### Actual behavior

1. Open the datepicker
2. Click on next month button
3. The date picker closes

**Comment by rahulnpadalkar** [comment]
would like to contribute.

**Comment by jtommy** [comment]
@rahulnpadalkar sure, thanks

**Comment by rlecellier** [comment]
I dont know if it could help but i feel like the `event.target` in `Dropdown.isInWhiteList()` doesn't match.
https://github.com/buefy/buefy/blob/dev/src/components/dropdown/Dropdown.vue#L219

Some doc tell us : https://javascript.info/shadow-dom-events
"Events that happen in shadow DOM have the host element as the target, when caught outside of the component."

**Comment by jtommy** [comment]
@rlecellier interesting! So is there a way to get it ?

**Comment by js1990** [comment]
@rlecellier at line https://github.com/buefy/buefy/blob/dev/src/components/dropdown/Dropdown.vue#L349

i'am able to use at least my shadowRoot to add the event listener
```
if (this.$root.$options.shadowRoot) {
  this.$root.$options.shadowRoot.removeEventListener('click', this.clickedOutside)
} else {
  document.removeEventListener('click', this.clickedOutside)
}
```

but at least this is only valid if you click inside the boundaries of the shadowDom ..

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2603

**Comment by simonjodet** [comment]
Why close this issue with discussion and investigation for a brand new one?

**Comment by jtommy** [comment]
Probably it has been fixed!

**Comment by simonjodet** [comment]
Where?

**Comment by jtommy** [comment]
Take a look at link in my comment "close"

**Comment by simonjodet** [comment]
Thanks! I'm on mobile, it wasn't obvious it was a PR link.
