### ISSUE TITLE
IE11: Navbar dropdown does not expand when clicked

### ISSUE THREAD

**Issue by a-kriya** [buefy/buefy#2285]
### Overview of the problem

**Buefy** version: 0.8.12
**OS/Browser**: IE11/Win7

### Description

Navbar dropdown does not open when clicked in IE11 due to JS error.

### Steps to reproduce

1. Load https://buefy.org/documentation/navbar in IE11.
2. In the example navbar on the page, click on the "Info" dropdown.
3. Notice that the dropdown does not expand.
4. Notice `"Object doesn't support property or method 'find'"` error in JS console of the browser.

### Expected behavior

Dropdown to expand and display items.

### Actual behavior

Clicking on navbar dropdown results in a JS error and does nothing:

![image](https://user-images.githubusercontent.com/26761352/75772587-3b411f80-5d72-11ea-95f0-759bed088a63.png)

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/2016.
Anyway I'm going to merge your PR
