### ISSUE TITLE
Datapicker with Multiple clears array on first select 

### ISSUE THREAD

**Issue by joaopedro** [buefy/buefy#2288]
**Buefy** version: [0.8.12]
**Vuejs** version: [2.5.17]
**OS/Browser**: MacOs / Chrome

### Description
When the datepicker component in binded with an array that already has elements in it, the existing dates are cleared on the first selection.

### Steps to reproduce

1. select a date

### Expected behaviour

The component should add the new date to the existing array

### Actual behaviour

Array contents are cleared and only the new date is added. 

[Screen Recording 2020-03-03 at 23.24.20.zip](https://github.com/buefy/buefy/files/4284126/Screen.Recording.2020-03-03.at.23.24.20.zip)

```<template>
  <div>
    <b-field label="Select a date">
      <b-datepicker
          placeholder="Click to select..."
          :focused-date="focusDate"
          v-model="dates"
          inline
          multiple>
      </b-datepicker>
    </b-field>
    <div>
      {{dates}}
    </div>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        focusDate: new Date('2020-05-18T00:00:00.000Z'),
        dates: [new Date('2020-03-18T00:00:00.000Z'), new Date('2020-03-13T00:00:00.000Z'), new Date('2020-03-20T00:00:00.000Z'), new Date('2020-04-08T23:00:00.000Z')]
      }
    }
  }
</script>

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/ae0328280e08b5350827c659fdf881cca5bbe00a
