### ISSUE TITLE
Consistent pagination layouts

### ISSUE THREAD

**Issue by jbardnz** [buefy/buefy#2289]
### Description

I noticed a small thing that would improve Buefy, at the moment the table component and pagination component have different layouts for the pagination numbers/arrows. Even with the different positioning options, it doesn't seem like it is possible for these to have the exact same layout, this can be confusing for users of sites made with Buefy. 

Taken directly from the docs, on the table layout the pagination numbers/arrows are left aligned:
![image](https://user-images.githubusercontent.com/1628446/75830010-8c095480-5e14-11ea-908c-6f3f1d2df618.png)

Whereas for the pagination component the arrows are on the opposite side of the page from the numbers: 
![image](https://user-images.githubusercontent.com/1628446/75830074-a7745f80-5e14-11ea-9277-94cd12442ddb.png)

It would be great to have an option on the `b-pagination` module to use the same layout currently used by `b-table`.

**Comment by jtommy** [comment]
@jbardnz you should simply wrap it into a level element
