### ISSUE TITLE
How can I customize functions when I clicked 'Login' button using a dropdown ?

### ISSUE THREAD

**Issue by RedmondLee** [buefy/buefy#2291]
### Description

Hi there, big love of your works.
Here's a question bothering me , I'm trying to create a login form with sample code in this link:
`https://buefy.org/documentation/dropdown/#content-and-position`
However every time I clicked login ,it automaticly refreshes the page instead of send some login query. I would like to customize login button ,bind it to a click event and then trigger a function in 'methods' ,if it is possible? Don't know how to gain that goal as a vue beginer ,could you please help me ?
thanks.

**Comment by jtommy** [comment]
What's your code? Btw it doesn't look a Buefy issue
