### ISSUE TITLE
Cannot read property 'extend' of undefined buefy Toast

### ISSUE THREAD

**Issue by rishabhbatra10** [buefy/buefy#2299]
### Overview of the problem

**Buefy** version: [0.8.12]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS, Chrome 80.0.3987.122

### Description
Vue version: 
Beufy version: 
On using Toast 
```javascript
import { ToastProgrammatic as Toast } from 'buefy'
Toast.open('Toasty!') // in a function
```
I get this error on the console 
Cannot read property 'extend' of undefined on line 76 toast.js

### Expected behavior

The browser should give a toast saying `Toasty!`

### Actual behavior

<img width="454" alt="Screenshot 2020-03-08 at 7 07 34 PM" src="https://user-images.githubusercontent.com/15319538/76163949-ab83e280-6170-11ea-84a8-2ec827171687.png">

**Comment by jtommy** [comment]
Are you importing the component or full bundle in the main?

**Comment by rishabhbatra10** [comment]
I was importing just the component, not the full bundle. Do I need to import anything else ?

**Comment by rishabhbatra10** [comment]
Yeah sure
<img width="391" alt="Screenshot 2020-03-12 at 2 25 40 AM" src="https://user-images.githubusercontent.com/15319538/76463189-02a3e480-6409-11ea-81df-70d1ef91b6b0.png">
<img width="430" alt="Screenshot 2020-03-12 at 2 26 06 AM" src="https://user-images.githubusercontent.com/15319538/76463200-05063e80-6409-11ea-919a-7746249a7f53.png">

**Comment by jtommy** [comment]
And the main.js ?

**Comment by rishabhbatra10** [comment]
I have not imported any thing related to buefy in main.js you can have a look. 

main.js 
```
import Vue from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify';
import 'material-design-icons-iconfont/dist/material-design-icons.css';

Vue.config.productionTip = false

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')

```

**Comment by jtommy** [comment]
You have to import Toast as Vue plugin.
`import { Toast } from 'buefy'`
And then
`Vue.use(Toast)`

**Comment by kissu** [comment]
Also, do not forget to import the CSS if you don't see any visual result. ^^

**Comment by danielclariondoor** [comment]
The documentation is incorrect then. 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/18540311/158206932-242f9c11-b9aa-4359-a9d3-5e6c4978ef42.png">

**Comment by kissu** [comment]
@danielclariondoor not sure why you're saying this.

**Comment by danielclariondoor** [comment]
The accepted solution is a different usage than the original bug. I am also experiencing the exact problem described in this bug. It should work, according to the docs, but it does not. The solution here does not solve the issue the programmatic implementation described in the docs.
