### ISSUE TITLE
Sticky headers not sticking in Codepen example

### ISSUE THREAD

**Issue by tomearly** [buefy/buefy#2311]
### Overview of the problem

**Buefy** version: 0.8.12
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS/Firefox

### Description

Sticky headers not sticking in Codepen example (when table width reduced to around 950px)

### Steps to reproduce

1. Visit the documentation for Table - Sticky headers at https://buefy.org/documentation/table#sticky-headers
2. View the Codepen link.
3. Change the screensize to around 950px (tablet sized)

### Expected behavior

Headers should stay in place

### Actual behavior

Headers scroll up out of view

**Comment by jtommy** [comment]
Already fixed
