### ISSUE TITLE
Add filter to data value on table

### ISSUE THREAD

**Issue by eagleera** [buefy/buefy#2313]
### Description
Hi! So looking at tables I found out that you can't add a filter(https://es.vuejs.org/v2/guide/filters.html) to a data value when using a table, I think we can implement a feature where a column gets a new prop called filters and that it could be an array where the data of that column can be converted to their asigned filters. 
Code Sample:
```
columns: [
 {
          field: "name",
          label: "Name",
          filter: "[capitalize, currency]"
 },
 {
          field: "payment",
          label: "Payment",
          filter: "[currency]"
 },
 {
          field: "payment_left",
          label: "Payment left",
          filter: "[currency]"
 }
];
```

### Why Buefy need this feature
I think Buefy needs it because it will make the tables more powerful and you can keep synchrony with how your data looks if you're using those kind of filters in another places of the app

**Comment by jtommy** [comment]
If you need use you should use default slot and table-column component

**Comment by service-paradis** [comment]
Filters will probably be deprecated in Vue 3 (https://github.com/vuejs/rfcs/blob/master/active-rfcs/0015-remove-filters.md). So I dont think it would be a good idea to support this right now.
