### ISSUE TITLE
Rewrite to Vue Composition API

### ISSUE THREAD

**Issue by nainardev** [buefy/buefy#2314]
Vue 3 is coming soon. We will need to convert to composition API. Vuetify is going to rewrite for their next major release.
What about us?

Add this to Milestone or something.
Also comment on what you think

**Comment by nainardev** [comment]
Let this issue be open until we do it. Now now but soon

**Comment by jtommy** [comment]
Better follow this https://github.com/buefy/buefy/issues/2505
