### ISSUE TITLE
Carousel List not using defaultIconPrev/Next

### ISSUE THREAD

**Issue by Christilut** [buefy/buefy#2317]
### Overview of the problem

**Buefy** version: 0.8.12
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

I have added this to my buefy config:
```
  defaultIconPack: 'cil',
  defaultIconPrev: 'chevron-left-alt',
  defaultIconNext: 'chevron-right-alt',
```

But the `b-carousel-list` did not show these icons.

After adding
```
    icon-prev='chevron-left-alt'
    icon-next='chevron-right-alt'
```
to the `b-carousel-list` component, the expected icons appear.

So it seems like the `b-carousel-list` does not use the defaultIconPrev and defaultIconNext.

**Comment by service-paradis** [comment]
Looks like it did use the default configuration (https://github.com/buefy/buefy/blob/dev/src/components/carousel/Carousel.vue#L147).
I will make some tests to see if I'm able to reproduce the issue and to see if there is something wrong.
