### ISSUE TITLE
Question: how does the Dialog component manage state?

### ISSUE THREAD

**Issue by alexmiddeleer** [buefy/buefy#2319]
Hi there, I was stopping by to ask a question about the implementation of the Dialog component. Feel free to ignore/close if you don't have time to answer, or would prefer to handle this somewhere else. We're build our own in house (unfortunately can't use Buefy since we need to support IE9). How does the programmatic Bulma mixin manage the open/closed state? I was reading https://github.com/buefy/buefy/blob/dev/src/components/dialog/index.js and https://github.com/buefy/buefy/blob/dev/src/components/dialog/Dialog.vue and I am missing the place where Vue mounts it. Thanks so much.

**Comment by jtommy** [comment]
On close it calls https://github.com/buefy/buefy/blob/8ade4f897bb91fd2791c6aa1472653cfcb0a1fc6/src/components/modal/Modal.vue#L184 because Dialog extends Modal
