### ISSUE TITLE
Tabs without headers

### ISSUE THREAD

**Issue by gierloff** [buefy/buefy#2321]
We are using Buefy for our project and it's great to see ongoing updates.

A couple of times we experienced the need for tabable content, e.g. tabs without tab headers, but just the tab content, the animation and then make custom tab headers outside tab component.

It would be possible if tab headers could be hidden, then use b-tabs and set up custom buttons any where in the vue app to swap the tabs.

Thinking a prop on the b-tabs that is bound to v-if on tab headers, e.g. show-headers or something.

**Comment by jtommy** [comment]
@gierloff you might hide them using CSS and change active tab by v-model or ref
