### ISSUE TITLE
Format function to table row

### ISSUE THREAD

**Issue by dalholm** [buefy/buefy#2322]
### Description
On my tables with buefy i use the columns property and i dont want to render html for simple tables. 
Sometimes you want to manipulate the data that reference to a specific column, it would be really nice if you could add a format method on the columns object.  

### Why Buefy need this feature
```javascript
{
    field: 'name',
    label: 'Name',
    format(row) {
         return row.firstname + ' ' + row.lastname;
    }
}
```

**Comment by jtommy** [comment]
It's similar to https://github.com/buefy/buefy/issues/2313#issuecomment-597879694
