### ISSUE TITLE
Datepicker - year selection type

### ISSUE THREAD

**Issue by P3trur0** [buefy/buefy#2323]
### Description

First of all, thank you for this awesome library!

The idea of this feature is to add a new datepicker type, namely `year`, to support the selection of dates by year only. For example, I have a use case scenario where users need to select only the year of a specific date. It seems Buefy misses this feature.

### Why Buefy need this feature

Because currently Datepicker has only a `month` selector type. Having the `year` option too might be useful in scenarios where users need only to select a year.

**Comment by jtommy** [comment]
@P3trur0 thanks ;)

Do you need the same UI to select an year? A select or a dropdown doesn't meet your need?
