### ISSUE TITLE
Autocomplete bug validation required

### ISSUE THREAD

**Issue by 4KDA** [buefy/buefy#2325]
In the Autocomplete component, if the required attribute is present, validation only works correctly when the second choice is made.

![2020-03-16-16-37-44-min](https://user-images.githubusercontent.com/38465364/76764234-8c570780-67a5-11ea-9183-1f610a658365.gif)

**Buefy** version: 0.8.10
**Vuejs** version: 2.6.11
**OS/Browser**: Windows 10 x64, Google Chrome 79.0

**Comment by 4KDA** [comment]
For myself, I solved the problem by validation through vee-validate

**Comment by jtommy** [comment]
@4KDA please post the code to help other users

**Comment by 4KDA** [comment]
Sandart usage vee-validate v2
