### ISSUE TITLE
Storybook implementation

### ISSUE THREAD

**Issue by DQvsRA** [buefy/buefy#2327]
### Description

Storybook

### Why Buefy need this feature

It's common way to inspect and try component implement by leaders on the industry, look at IBM Carbon DS: https://react.carbondesignsystem.com/

**Comment by jtommy** [comment]
@DQvsRA good idea

**Comment by codebender828** [comment]
I can help with setting this up next weekend. 👍

**Comment by jtommy** [comment]
@DQvsRA The first time I thought it was a good idea but the current docs already contains a lot of example and Codepen integration.
Why do you need it ?

**Comment by jtommy** [comment]
@DQvsRA at the moment i don't think to add it, but i'm avaiable to hear your reasons :wink:
