### ISSUE TITLE
Slider is positioned wrong when in scale transform

### ISSUE THREAD

**Issue by SupraSummus** [buefy/buefy#2328]
### Overview of the problem

**Buefy** version: 0.8.13
**Vuejs** version: 2.6.11
**OS/Browser**: linux/chromium 80

### Description

Slider component reads wrong mouse position when used in `transform: scale(..)` element.

### Steps to reproduce

https://codepen.io/suprasummus/pen/XWbYOVK

**Comment by jtommy** [comment]
Why do you need it?

**Comment by SupraSummus** [comment]
I'm using vue-panzoom to control a map in a turn-based strategic game. The map has some controls on it, including sliders. vue-panzoom (wrapper around [panzoom](https://github.com/anvaka/panzoom/)) sets scale transform for child elements to achieve zooming.
