### ISSUE TITLE
Tri State Filter Dropdown With Undefined Value

### ISSUE THREAD

**Issue by MannikJ** [buefy/buefy#2329]
### Overview of the problem

**Buefy** version: 0.8.3
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome

### Description

Please see this example code:

```html
<b-field label="Late">
    <b-dropdown v-model="filters.late"
                hoverable
                aria-role="list">
    <button class="button"
            slot="trigger">
        <span>Select</span>
        <b-icon icon="angle-down"
                type="is-primary"
                size="is-small"></b-icon>
    </button>

    <b-dropdown-item :value="undefined">-</b-dropdown-item>
    <b-dropdown-item :value="true">Yes</b-dropdown-item>
    <b-dropdown-item :value="false">No</b-dropdown-item>
    </b-dropdown>
</b-field>
```

### Expected behavior

Setting the `filters.late` property on the component to `undefined` should automatically select  thefirst option.

### Actual behavior

The `undefined` value is treated as `null` and therefor the option is not correctly selected.

**Comment by jtommy** [comment]
Out of curiosity, why undefined?

**Comment by MannikJ** [comment]
Because most popular query string libraries will leave out undefined values. So the distinction can be very helpful.

**Comment by MannikJ** [comment]
I just realized the comparison does not even work with null either. If a dropdown item is has `null` or `undefined` as value, it is never marked as selected.

See this example:
https://codesandbox.io/s/buefy-template-r9ldv

**Comment by jtommy** [comment]
@MannikJ it's no easy try a way to know if null value is delibarete (your need) or in case a user didn't set the value. You should set always a value, for example empty string
