### ISSUE TITLE
Datepicker grey out dates broken

### ISSUE THREAD

**Issue by tomjsalmon** [buefy/buefy#2331]
### Overview of the problem

**Buefy** version: [0.8.13]
**Vuejs** version: [2.6.10]
**OS/Browser**: macOS 10.15.3, Chrome 80.0.3987.132

### Description

Ordinals randomly appearing in datepicker and dates not matching up.

![image](https://user-images.githubusercontent.com/16036590/77217663-57b6b900-6ae1-11ea-8cc1-1ede55def151.png)
![image](https://user-images.githubusercontent.com/16036590/77217667-61402100-6ae1-11ea-9a18-c03a66888c70.png)
![image](https://user-images.githubusercontent.com/16036590/77217672-6ac98900-6ae1-11ea-9c90-077cafc3bd4d.png)

### Steps to reproduce

```
              <b-datepicker
                placeholder="Type or select a date..."
                icon="calendar-today"
                :date-formatter="(date) => date.toLocaleDateString('en-CA')"
                :max-date="today"
                v-model="formData.signatureDate"
                editable>
              </b-datepicker>
```

`today = new Date`

### Expected behavior

No ordinals (or all ordinals). Dates match how they should look on a calendar.

### Actual behavior

Ordinals appear for 2, 3, 4, 8, 10, 24, 25, 30. Greyed out dates seem to be random, sometimes update when month changed, sometimes not.

**Comment by jtommy** [comment]
@tomjsalmon i've just tried your code on codepen and i'm not able to see ordinals. Can you provide a codepen o similar ?
