### ISSUE TITLE
Load single Buefy components as async components

### ISSUE THREAD

**Issue by hellokvn** [buefy/buefy#2332]
### Description

Loading single Buefy components only when I need it instead of all (or some) Buefy components globally would make the own app more lightweight. That's important to apps who really needs to care about performance. Same counts for Buefy's css. Why loading the whole css if you need only 4 component for a specific view?

### Why Buefy need this feature

Other packages offers that as well.

### What I've tried (1)

**Code:** 
```ts
@Component({
  components: { 'b-button': () => import("buefy/dist/components/button") }
})
export default class Home extends Vue {
  // ...
}
```

**Error:**
```
Failed to mount component: template or render function not defined.
found in
---> <BButton> ....
```

### What I've tried (2)

* note: I tried to import { BButton } as well

**Code:** 
```ts
import { Button } from "buefy";
import "buefy/dist/buefy.css";

export default (Vue: any) => {
  Vue.use(Button);
};
```

**Error:**
```
ERROR in /Users/name/Workspace/n/web_mobile/src/common/boot/buefy.boot.ts(5,10):
5:10 Module '"../../../../../../../../Users/name/Workspace/n/web_mobile/node_modules/buefy/types"' has no exported member 'Button'. Did you mean to use 'import Button from "../../../../../../..
/../Users/doctorxdentist/Workspace/n/web_mobile/node_modules/buefy/types"' instead?
    3 | // import "buefy/dist/buefy.css";
    4 | // import '@/common/scss/_all.scss';
  > 5 | import { Button } from "buefy";
      |          ^
    6 | import "buefy/dist/buefy.css";
    7 | 
    8 | export default (Vue: any) => {
```

Versions:

Vue: latest
Buefy: latest

**Comment by jtommy** [comment]
@hellokvn you should import only the component, for example
`import { BButton } from 'buefy/dist/esm/button`

**Comment by slidenerd** [comment]
CSS I havent figured out but this is how I did it for the components

import Vue from 'vue'
import { Dropdown, Icon } from 'buefy'

Vue.use(Dropdown)
Vue.use(Icon)
