### ISSUE TITLE
UX Improvement: Dropdown items with has-link should not be focusable by default

### ISSUE THREAD

**Issue by luisjoserivera** [buefy/buefy#2333]
`<b-dropdown-item has-link>`

My logic is telling me that if I already declared that a dropdown item **has a link** the container should not be focusable by default.

By making this a logical default we can avoid:
- A lot of sites having links with double tab focus.
- Unnecessary additional attribute definition per item `focusable="false"`

**Comment by jtommy** [comment]
@luisjoserivera  you're right, when `has-link` then `focusable` will be false as default value
