### ISSUE TITLE
b-carousel-list not working when importing buefy with a seperate .scss file

### ISSUE THREAD

**Issue by lennycampino** [buefy/buefy#2337]
### Overview of the problem

**Buefy** version: 0.8.13
**Nuxt** version: 2.11.0
**OS/Browser**: Chrome

### Description

my main.scss file:
@import "~bulma/sass/utilities/functions";
@import "~bulma/bulma";

@import "~buefy/src/scss/buefy";

buefy then works but when I try to use the b-carousel-list component it does stack vertically and not horizontal. But if I directly use buefy.css in my global config everything works fine. Can you please help me?

**Comment by lennycampino** [comment]
Ok I fixed it.
It does not work if I import it from the style directly:
<style lang="scss" scoped>
 @import "~/assets/scss/main.scss";
</style>

But when I import the main.scss file in the nuxt.config.js as global style then it works.
Strange because bulma also works in the <stlye> import.

**Comment by slidenerd** [comment]
Same problem here @import "~buefy/src/scss/buefy"; if you add this line, it has no effect but if you import the entire css file inside plugins/buefy.js thats when it works, I am using Nuxt here
