### ISSUE TITLE
Fix table column behavior with long text

### ISSUE THREAD

**Issue by thedomeffm** [buefy/buefy#2338]
**Buefy** version: [0.8.10]
**Vuejs** version: [2.6.10]
**OS/Browser**: Linux Chrome

### Description

I gave all `<b-table-column class="w-30">...` a specified with.
If I have a long text inside of the cell, I want to truncate it, but it seems like this does not work:
![buefy_issue_table](https://user-images.githubusercontent.com/29406401/77330761-12cc9580-6d20-11ea-9337-0ce03b3ac0a2.png)

```
<b-table-column label="hello-buefy <3"
                class="w-30">
    <p class="is-medium truncate" v-if="props.row.eventGroup">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad architecto at autem, cupiditate eius eum fugit in iure modi molestiae quasi quibusdam sed soluta totam vitae? At ea hic nobis.
    </p>
</b-table-column>
```
Truncate class "wins" against table width (w-30 = width 30%)
```
.truncate {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
## but
if I add the class:
```
table.table {
    table-layout: fixed;
}
```
it is working as I want and expect.
![buefy_issue_table_solution](https://user-images.githubusercontent.com/29406401/77330788-1e1fc100-6d20-11ea-8f69-8f90492c946a.png)

So probably add the `table-layout: fixed;` as deafult in buefy?

related:
- https://github.com/buefy/buefy/pull/1827#issuecomment-547896419

**Comment by thedomeffm** [comment]
closed, see https://github.com/buefy/buefy/issues/2342

**Comment by binhtbhe130864** [comment]
> ##
> if I add the class:

oh well, it works, thanks
