### ISSUE TITLE
Dropdown clipping inside sticky table

### ISSUE THREAD

**Issue by Joebayld** [buefy/buefy#2340]
### Overview of the problem

**Buefy** version: [0.8.13]
**Vuejs** version: [2.6.11]

### Description

When placing a dropdown in a table row, the dropdown contents are clipped. This is really only an issue when having a dropdown at the bottom of the table. 

![image](https://user-images.githubusercontent.com/9399317/77369441-e1ea6180-6d1b-11ea-8659-e76768f0aca5.png)

### Steps to reproduce

1. Create a table row with `sticky-header` set. 
2. Create a table column with a dropdown button in it. 

### Expected behavior

The dropdown would be on a higher level so that it's not clipped by the tables overflow.

![image](https://user-images.githubusercontent.com/9399317/77369618-460d2580-6d1c-11ea-8d22-404c25dd6c78.png)

### Actual behavior

The contents is clipped.

**Comment by jtommy** [comment]
@Joebayld it's a common issue with dropdown into a container, a good improvement could be an option to append it to body

**Comment by Joebayld** [comment]
Ah gotcha. And totally. Or a prop to define where to append to. In this case I’m inside a modal.

**Comment by jtommy** [comment]
@Joebayld Added `append-to-body` prop https://github.com/buefy/buefy/commit/17cfe9713b4f293d24f649bddbfc1910e49d093b
