### ISSUE TITLE
Prop truncate (and width %) for b-table-column

### ISSUE THREAD

**Issue by thedomeffm** [buefy/buefy#2342]
I had issues with table columns and the width of them. I thought I solved this issue like I wrote here: https://github.com/buefy/buefy/issues/2338 - but this did not solve my issue 100%.

I want to truncate my `<p>` in table columns (`<td>`). 

I suggest a prop for `b-table-column` => `truncate-text`

### Description

I want to set the width of my table columns explicit, so I added classes for the width e.g.:
```
table {
    @media (min-width: 769px) {
        .w-10 {
            width: 10% !important;
        }
        .w-20 {
            width: 20% !important;
        }
       [...]
```
And what I do at the moment:
```
<b-table-column label="hello buefy <3"
                class="w-40 truncate-column">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam consequuntur corporis, culpa cupiditate dolore exercitationem fugit ipsa itaque labore magnam natus nulla, perspiciatis repellat, similique sint voluptas. Eaque, quae!
    </p>
</b-table-column>
```

```
td {
    &.truncate-column {
        @media (min-width: 769px) {
            max-width: 1px;
            p {
                width: 100%;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }
        }
    }
}
```

> Source: http://jsfiddle.net/7CURQ/64/ or https://stackoverflow.com/questions/5239758/css-truncate-table-cells-but-fit-as-much-as-possible#comment55103711_19342181 

What would be nice for all buefy users:
```
<b-table-column label="hello buefy <3" :width="40%" truncate-column>
   <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam consequuntur corporis, culpa cupiditate dolore exercitationem fugit ipsa itaque labore magnam natus nulla, perspiciatis repellat, similique sint voluptas. Eaque, quae!
    </p>
</b-table-column>
```

### Why Buefy need this feature

Would be easier to truncate table cell content.

**Comment by jtommy** [comment]
It's no easy to add at the moment, probably it's better allow user to make it using default slot

**Comment by IgnacioFigueroa** [comment]
Is possible to make this arrangement now? I have the same problem. Maybe just add a feature to fix the columns size

**Comment by luixal** [comment]
Wow. Not been able to fix columns size to truncate text has been a project killer for me. Didn't manage to replicate @thedomeffm solution (class passed to b-table-column is never set).

**Comment by thedomeffm** [comment]
> Wow. Not been able to fix columns size to truncate text has been a project killer for me. Didn't manage to replicate @thedomeffm solution (class passed to b-table-column is never set).

Buefy has a 'cell-class' and 'header-class' property on the column. Probably this solves your issue.
