### ISSUE TITLE
Import buefy core variables without re-defining them

### ISSUE THREAD

**Issue by user4i** [buefy/buefy#2345]
When importing **bulma** core variables
`@import "~bulma/sass/utilities/_all";`
and we can use _without re-defining_
`$gap` (from **bulma**)

How can I import the same **buefy** core variables  to use `$checkbox-size`  (from **buefy**) ?

When I re-define **buefy** variable e.g. 
`$checkbox-size: 20px`
it works for checkbox and I can use it in other css. But I don't want to re-define it, but to use default value.

Thanks!

**Comment by service-paradis** [comment]
When SASS implementations will support the use of `@use`. It will be possible to import only variables from a given component. If you're using Dart Sass in your project, you can already use `@use`:
https://sass-lang.com/documentation/at-rules/use

**Comment by jtommy** [comment]
@service-paradis good catch!

**Comment by service-paradis** [comment]
`sass-loader` strongly recommend to migrate on sass (dart-sass) since https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0.
