### ISSUE TITLE
clearable on b-autocomplete

### ISSUE THREAD

**Issue by giudicelli** [buefy/buefy#2346]
### Overview of the problem

**Buefy** version: 0.8.13
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 80.0.3987.132

### Description

The clear icon shows up, but nothing happens when clicked.

### Steps to reproduce

1.
<b-autocomplete :data="locations" v-model="locationName"
  :expanded="true"
  @typing="searchLocation" 
  :clearable="true" @select="selectLocation($event)">
  <template slot="empty">No location found</template>
  <template slot-scope="props">
    {{ props.option.name }}
  </template>
</b-autocomplete>

2. Select a value
3. Try to clear the value
4. Click event doesn't show up in Vue Devtools/Events
5. Autocomplete is not cleared

### Expected behavior

The input is not cleared

### Actual behavior

The input should be cleared

**Comment by jtommy** [comment]
@giudicelli can you provide the full code (better on codepen or similar) ?

**Comment by jtommy** [comment]
https://codepen.io/jtommy/pen/yLNwzEb?editable=true&editors=101
