### ISSUE TITLE
[Table] Is there a way to initialize value of searchable column filters?

### ISSUE THREAD

**Issue by marianomd** [buefy/buefy#2347]
I'm trying to persist columns filters between route changes.

I have a table, I filter by a column, then navigate to an item's detail (some other component) and when I return I want the columns to continue filtered.

I need to set filter values on component creation (page load) from the route query params, or from state in vuex, or something like that.

Is it possible?

**Comment by jtommy** [comment]
@marianomd at the moment there isn't an elegant way but this code should work:
`this.$refs.mytable.filters['firstName'] = 'xxx'`

**Comment by dalholm** [comment]
@jtommy initially it works fine, but it breaks the "trigger" for new search. I am using `backend-filtering` and `:debounce-search="300"`

**Comment by bodnarlajostibor** [comment]
I have the same issue as dalholm.

**Comment by bodnarlajostibor** [comment]
Well, I couldn't give up, and after some deadend I see this working with that config: 
`mounted: function() {
this.$set(this.$refs.BTable.filters, 'name', this.filter.name)
}`
That triggers the @filters-change event, so the new dataset is loaded.
