### ISSUE TITLE
Controlling icon size on input field?

### ISSUE THREAD

**Issue by jonas87** [buefy/buefy#2356]
Buefy seems to by default add the class "fa-lg" for FontAwesome icons on an input field, which makes the icons too large for my taste. While b-icon has a size prop, b-input has a prop to define the "icon-pack" and "icon" but it does not seem to have an option to control icon size.

Interestingly the FontAwesome example on the [documentation's input page](https://buefy.org/documentation/input#icons) has a large icon (css class "fa-lg") on it for the credit card but is default sized (no size controlling css class) for the email and search icons. There is nothing in the accompanying code example to suggest any control over icon size.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/pull/1776
