### ISSUE TITLE
modal min width and min width

### ISSUE THREAD

**Issue by id1385** [buefy/buefy#2359]
when set :width="400" to modal component its work but it set max-width="400px" style not min with so if modal content is small it not get 400px fix 

i think when we set with normal int number it must be fix to this number and get 100% with in touch device

**Comment by jtommy** [comment]
There isn't max-width prop

**Comment by id1385** [comment]
> There isn't max-width prop

when i set modal-has-card  modal dont scroll :| 
how can fix it ? i have an custom component in content of modal

**Comment by jtommy** [comment]
Please provide an example on codepen or similar

**Comment by id1385** [comment]
> Please provide an example on codepen or similar

tank you very much i found an example and its work and fixed problem

**Comment by hphil63** [comment]
I can confirm this behaviour. setting :width prop results in setting style="max-width" and not style="width" or style="min-width", which would be perhaps even better option. I'm using nuxt-buefy version 0.4.13
