### ISSUE TITLE
Table with lots of columns with long headers expands beyond 100% width even with 'scrollable' property

### ISSUE THREAD

**Issue by anti-destin** [buefy/buefy#2361]
### Overview of the problem

**Buefy** version: 0.8.13
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS Catalina 10.15.4/Chrome 80.0.3987.149

### Description

Adding to a table lots of columns with long headers (e.g., 'Residential property price per sqm', etc.) causes the table to expand beyond 100% width even if the 'scrollable' property is used.

### Steps to reproduce

1. Create two bulma columns, say, `is-4` and `is-8`.

2. In the second column, create a table with a high number (e.g., 20) of columns, each with a long header (e.g., 'Residential property price per sqm').

### Expected behavior

The maximum table width is 100% so that the table remains fully contained within the parent div.

### Actual behavior

The table expands beyond the width of the parent div and continues to expand as more columns are added.

**Comment by jtommy** [comment]
You should use width property on table column

**Comment by anti-destin** [comment]
Thanks for the suggestion.

I just tried adding the width property on the columns, but it did not fix the issue.

With a lot of columns, the table just expands.

**Comment by jtommy** [comment]
Are you able to reproduce it on codepen or similar?

**Comment by jtommy** [comment]
Take a look at: https://codepen.io/jtommy/pen/rNVPoxa?editable=true&editors=101

**Comment by anti-destin** [comment]
I found the issue, at least in our codebase.

Our page is structured as follows:

    <div class='column is-three-fifths'>
      <b-tabs>
        <b-tab-item>
          <b-table>
            table code
          </b-table>
        </b-tab-item>
      </b-tabs>
    </div>

Now, when too many columns are added, the table expands beyond the div.

But if we fix the width of the tab item as follow

        <b-tab-item style='max-width: 500px !important;'>

the issue disappears.

But note that using `max-width: 100% !important;` does not work.

Thoughts?

**Comment by anti-destin** [comment]
I investigated further and even disabled all of the custom CSS that we added, but I was unable to track down the issue or reproduce it in your codepen.

I ended up just wrapping the table inside of a div with a max-width.

This is a hacky workaround, as I need to use JavaScript to calculate and set the max-width on mount, but it works.

Of course, I would welcome a more elegant solution.
