### ISSUE TITLE
Built-In intellisense support for Vetur

### ISSUE THREAD

**Issue by nogic1008** [buefy/buefy#2363]
### Description

1. Create `tags.json` and `attributes.json` on publish automated.
1. Add `vetur` section to `package.json` like this.
    ```json
    {
      "vetur": {
        "tags": "dist/vetur/tags.json",
        "attributes": "dist/vetur/attributes.json"
      }
    }
    ```
1. Send PR that uses built-in json to [vuejs/vetur](https://github.com/vuejs/vetur)

### Why Buefy need this feature

Currently, intellisense support of buefy is provided via [buefy-helper-json](https://www.npmjs.com/package/buefy-helper-json).
However, it has not been updated since August 2018, and created in hand.
So we cannot take intellisense support for new features like [Navbar](https://buefy.org/documentation/navbar/).

### References
- [Framework Support | Vetur](https://vuejs.github.io/vetur/framework.html)
- [Implementation in Vetur](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/tagProviders/externalTagProviders.ts)
- vuejs/vetur#1365

**Comment by jtommy** [comment]
@nogic1008 thanks but before it I have to update this package adding missing new components and props, can you help me?

**Comment by nogic1008** [comment]
@jtommy Sure.
I will send a PR based on the current buefy version to [buefy-helper-json](https://github.com/buefy/buefy-helper-json).

**Comment by jtommy** [comment]
Awesome

**Comment by nogic1008** [comment]
Can I send PR for [/helper-json/*.json](https://github.com/buefy/buefy/tree/dev/helper-json) directly?
I want to improve them.

**Comment by jtommy** [comment]
It's ready but I'm waiting to release the new version before to send it

**Comment by jtommy** [comment]
@nogic1008 https://github.com/vuejs/vetur/pull/1866 is it ok for you ?

**Comment by nogic1008** [comment]
Excellent!
I'll close vuejs/vetur#1822 because it is a duplicate

**Comment by rubjo** [comment]
Is this broken? I coudn't see any dist/vetur folder in a project where Buefy was installed, and had to manually create and add the attributes.json and tags.json files.

**Comment by jtommy** [comment]
It's missing in the last release, I'll restore in the next one
