### ISSUE TITLE
Global registration of individual programmatic components (Snackbar)

### ISSUE THREAD

**Issue by YoKawaiiK** [buefy/buefy#2365]
How is it possible to register individual programmatic components as a plug-in so that you can access it from any Vue component?

The documentation has this way:
`import{ SnackbarProgrammatic as Snackbar } from 'buefy'`
`Snackbar.open('Look at me!')`

But this method does not work when connecting Snackbar as a plugin using:
`Vue.use(Snackbar)`.

I expect that approximately the use of a programmatic component in Vue components will be in the form:
`Vue.Snackbar.open('bla-bla');`.

What am I doing wrong and what may be the solution to my problem. Thanks.

**Comment by jtommy** [comment]
`import{ SnackbarProgrammatic as Snackbar } from 'buefy'` -> component (programmatic)
`import{ Snackbar } from 'buefy'` > plugin

Before to use `Snackbar.open('Look at me!')` you have to import Snackbar plugin, for example:

main.js

```
import{ Snackbar } from 'buefy' 
Vue.use(Snackbar)
```


component.vue
```
this.$buefy.snackbar.open('Look at me!')
```
or
```
import{ Snackbar } from 'buefy' 
Snackbar.open('Look at me!')
```
