### ISSUE TITLE
how to make clear icon of input conditionally ?

### ISSUE THREAD

**Issue by id1385** [buefy/buefy#2366]
` <b-field>
            <b-input expanded  :icon-right="{'close-circle' : true}"
                     icon-right-clickable
                     @icon-right-click="clearValue">
            </b-input>
        </b-field>`

this code get error because icon-right want icon name
**i want to set icon right visible when input has value**
how can do it ?

**Comment by jtommy** [comment]
The error is about type, you should pass a string

**Comment by id1385** [comment]
i think You don't understand what I mean
i have not error when i use normal icon name
i want visible clear icon when input has value not empty


![Capture](https://user-images.githubusercontent.com/28746285/78152713-6d1bd380-744f-11ea-8373-72217320615c.PNG)

**Comment by id1385** [comment]
> The error is about type, you should pass a string

can u help me ?

**Comment by jtommy** [comment]
`:icon-right=" mydata? 'close-circle' : ''"`
