### ISSUE TITLE
TagInput: pressing the enter key twice causes the last input to reappear

### ISSUE THREAD

**Issue by pacien** [buefy/buefy#2371]
### Overview of the problem

**Buefy** version: 0.8.15 (bug wasn't present in 0.8.12)
**Vuejs** version: 2.6.10
**OS/Browser**: Chromium

### Description

In some cases, pressing enter a second time in a TagInput causes the last input to reappear.

### Steps to reproduce

1. Go to https://buefy.org/documentation/taginput/#autocomplete
2. In the autocompleted TagInput field, enter "Tina"
3. Press the enter key: the tag is added as expected
4. Press the enter key again: __the last input reappears__.

### Expected behavior

The last input shouldn't reappear. This wasn't the case before 0.8.12 (included).

### Actual behavior

The last input reappears.

---
CC: @OzoneGrif

**Comment by jtommy** [comment]
You are right, I'll investigate about it
