### ISSUE TITLE
Column search input field placeholder

### ISSUE THREAD

**Issue by katjafi** [buefy/buefy#2372]
Hi, 

While using Buefy table (https://buefy.org/documentation/table/#searchable) for a project I noticed that it would be great to have a placeholder for search filter input field. Couldn't find a way to add it from your documentation, would it be possible to add this in the future? 

<img width="1325" alt="Screenshot 2020-04-02 at 20 50 22" src="https://user-images.githubusercontent.com/30377332/78281611-973ec580-7523-11ea-9549-278de24a3c78.png">

 

Related to #888

**Comment by jtommy** [comment]
If you want to customize it you should use header slot of table column component
