### ISSUE TITLE
Steps Component: How to block to pass next step if there is some error into actual step?

### ISSUE THREAD

**Issue by biapar** [buefy/buefy#2377]
Steps Component: How to block to pass next step if there is some error into actual step?

**Comment by service-paradis** [comment]
You can use custom pagination button. Check the first example in the doc. You can control the button `disabled`state.

**Comment by biapar** [comment]
Thanks. How to refer the next button ? Is't good to user ref?

**Comment by service-paradis** [comment]
No need to use ref. You only need to set the `:disabled` prop accordingly:

```
<b-pagination-button
                slot="previous"
                slot-scope="props"
                :page="props.page"
                :disabled="isPreviousDisabled">
                Previous
            </b-pagination-button>

            <b-pagination-button
                slot="next"
                slot-scope="props"
                :page="props.page"
                :disabled="isNextDisabled">
                Next
            </b-pagination-button>
```

**Comment by biapar** [comment]
How to intercept that the step is changed and in which step we are?

**Comment by service-paradis** [comment]
`v-model` to always have the displayed step index.
`@change` to know when a new step is selected.
