### ISSUE TITLE
Table Column headers not toggleable when data was empty

### ISSUE THREAD

**Issue by MelvinFrohike** [buefy/buefy#2379]
### Overview of the problem

**Buefy** version: [0.8.15]
**Vuejs** version: [2.6.11]
**OS/Browser**: macOS Catalina, Safari, Chrome

### Description
Table column headers cannot be toggled on/off when the table data has been empty at some point. The actual content's columns are toggled correctly thus rendering the content columns under the wrong header.

### Steps to reproduce
I've prepared a codepen with a [minimal example](https://codepen.io/melvinfrohike/pen/JjdQZmW?editors=1011)

1. (optional) Toggle some columns to see that toggling works correctly
2. Press the **Toggle Data** button to load an empty dataset, i.e. an empty array
3. Press the **Toggle Data** button again to load the original dataset
3. Toggle some columns to see that the content toggles as expected but the column headers are not affected.

**Comment by jtommy** [comment]
I'll take a look

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/2c8f06c1f8e68887ad034ee8b4ec0d2daf7f05e5
