### ISSUE TITLE
Detect click in text tag (taginput)

### ISSUE THREAD

**Issue by FlorianChretien** [buefy/buefy#2383]
Hi,
Is it possible to "click" an event on a tag (taginput)? Thank you very much again for seeing work!
Have a nice day

**Comment by jtommy** [comment]
What click event do you want to listen ?

**Comment by FlorianChretien** [comment]
To be able to detect the click on the text of the tag, to launch a method (which will execute a request and change the type)

**Comment by jtommy** [comment]
@FlorianChretien take a look at https://buefy.org/documentation/taginput#custom-selected

**Comment by FlorianChretien** [comment]
I cannot detect the click on the text to execute an axios request?

**Comment by FlorianChretien** [comment]
I did not succeed with the custom-tags :/

**Comment by jtommy** [comment]
@click.natve on tag ?

**Comment by FlorianChretien** [comment]
Perfect ! Thanks you !
