### ISSUE TITLE
parameters of $buefy.notification.open not accepted by Typescript

### ISSUE THREAD

**Issue by chloebrqt** [buefy/buefy#2385]
### Overview of the problem

**Buefy** version: [0.8.13]
**Vuejs** version: [2.6.11]
**OS/Browser**: Ubuntu/Firefox Developer Edition (76.0b1)

### Description

I want to open a notification if there's an error with my ajax request. I've copied and pasted what was in the documentation, that is :
```javascript
const notif = this.$buefy.notification.open({
    duration: 5000,
    message: `Something's not good, also I'm on bottom`,
    position: 'is-bottom-right',
    type: 'is-danger',
    hasIcon: true
})

notif.$on('close', () => {
    this.$buefy.notification.open('Custom notification closed!')
})
```

Problem is, I'm using Typescript (and I'm quiet new to it) and it seems the "open" property of "notification" isn't *recognized* as it should (I don't know how to express it right, I can't really explain it even in French). Please see below screenshot :

![Typescript Error](https://i.imgur.com/kUZyuyQ.png)

1. The green underlining is my IDE (Phpstorm) telling me : `Argument type {duration: number, hasIcon: boolean, position: string, message: string, type: string} is not assignable to parameter type number | undefined`. And why the "type number | undefined" and not "NotificationConfig | string" as it should be (I guess)... I quiet don't know, but when I Ctrl+Click on `open` it leads me to an "open" function in `/node_modules/@types/node/inspector.d.ts`. **However, even with this warning, notification works.**
2. The red underlining is TSlinter telling me : `TS2339: Property '$on' does not exist on type '{ close: () => any; }'.`, **and with this warning it doesn't compile.**

### Expected behavior
Not having any warning about parameter type, and the `$on` property to work.

### Actual behavior
I have a warning about parameter type, and the `$on` property doesn't work and makes compilation fail.

Maybe I'm missing something and it isn't a bug at all, if that's so, help would be welcomed. :)
Thanks in advance!

**Comment by service-paradis** [comment]
I will work on it. As a workaround until the new release, you can do the following:
```
(notif as any).$on('close', () => {
    this.$buefy.notification.open('Custom notification closed!')
})
```

**Comment by chloebrqt** [comment]
Thanks a lot for the fast answer and for the workaround, this is much appreciated. :)

**Comment by service-paradis** [comment]
Ça fait plaisir ;)
Bonne journée!

**Comment by chloebrqt** [comment]
Merci à toi aussi! :)
