### ISSUE TITLE
input fields in table

### ISSUE THREAD

**Issue by jonas87** [buefy/buefy#2388]
How would one go about setting input fields for specific columns with 2-way binding to the underlying table data object?

To clarify what I mean, here is a simple demonstration with 2 columns that have input fields in Vuetify:
[https://codepen.io/jonas87/pen/NWGWMdP](https://codepen.io/jonas87/pen/NWGWMdP)

I started applying this to one of the buefy examples but I'm not sure what variable to bind to:
[https://codepen.io/jonas87/pen/XWmWybv](https://codepen.io/jonas87/pen/XWmWybv)

**Comment by jtommy** [comment]
It's ok but `v-model` doesn't require `:`
