### ISSUE TITLE
Field : Add required property that would append an asterisk to label

### ISSUE THREAD

**Issue by foochris** [buefy/buefy#2389]
### Description
Add a property `required` (boolean, default: `false`), that when set to `true` would append an asterisk (or another user defined character by property) to the label. In addition, wrapping the asterisk in a `span` with either a custom or default class name would allow for ease of styling.

### Why Buefy need this feature
It would reduce the DRY that would be needed to implement such a feature on views that have multiple `b-field`. Currently, a template slot, with the label, would be needed to append the asterisk.

**Comment by jtommy** [comment]
There is already https://buefy.org/documentation/field#label-slot

**Comment by husstahn** [comment]
You are better off adding custom-class to your b-field. For example add custom-class="required". Then override field.scss.
```
.field {
  .label {
    &.required::after {
    	content: "*";
    	color: $danger;
    }
  }
}
```
