### ISSUE TITLE
Large size of library

### ISSUE THREAD

**Issue by Alfavio** [buefy/buefy#2391]
### Overview of the problem

**Buefy** version: `0.8.15`
**Vuejs** version: `2.6.11`
**OS/Browser**: Linux/Chrome

### Description

Library has large size. Vue GUI shows **633 kB** after build. Also CDN version has large size. 

- `buefy.min.js` has **226.5 kB**
- `buefy.min.css` has **209.6 kB**

![screenshot-localhost_8000-2020 04 10-17_45_53](https://user-images.githubusercontent.com/5478075/79003646-87863900-7b42-11ea-9cf1-bbbdb469b259.png)

In docs is mentioned different size:

> Even though this is gonna import ALL components to your application, Buefy full bundle is optimized and still pretty small:
> script is 32KB min+gzip
> style is 28KB min+gzip (with bulma included)

[[source]](https://buefy.org/documentation/start)

### Expected behavior

Expected **~60 kB** size in Vue GUI after build and

- `buefy.min.js` expected **32 kB**
- `buefy.min.css` expected **28 kB**

### Actual behavior

Vue GUI shows **633 kB**

- `buefy.min.js` has **226.5 kB**
- `buefy.min.css` has **209.6 kB**

**Comment by jtommy** [comment]
@Alfavio the docs is outdated about size but you can take a look at unpkg
![image](https://user-images.githubusercontent.com/8029488/79006055-94ae2280-7b58-11ea-9bdb-d7c119470a65.png)

**Comment by jtommy** [comment]
Gzip is about 48.5 and 38.8
