### ISSUE TITLE
Datetimepicker

### ISSUE THREAD

**Issue by dalholm** [buefy/buefy#2393]
### Overview of the problem

**Buefy** version: [2.6.11]
**Vuejs** version: [0.8.15]
**OS/Browser**:

### Description
When using datetimepicker i need to be able to parse the date but the method datetime-parser it's not triggered. 

datetime-formatter is working fine though

### Steps to reproduce

```<b-datetimepicker :datetime-parser="function"/>```

**Comment by jtommy** [comment]
As you can see it works https://codepen.io/jtommy/pen/zYvvOWW?editors=1011
