### ISSUE TITLE
Search does not work in IE11 in buefy table

### ISSUE THREAD

**Issue by Sarah-clariondoor** [buefy/buefy#2397]
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 2.6.11
**OS/Browser**: IE11 (version 11.719.18362.0)

### Description

Searching in a buefy table does not work in IE11 within vue app.

### Expected behavior

The list should update and show list of rows that match that search term.

### Actual behavior

Nothing. The list is the same as before.

The first part of the gif is in google chrome showing expected behavior, second part of the gif is in IE11 showing actual behavior on same website and page with same sample data as shown in https://buefy.org/documentation/table/#searchable
![buefy-table-search](https://user-images.githubusercontent.com/42549181/79167573-9405ce00-7d9c-11ea-83a7-3bf086006cf7.gif)

**Comment by service-paradis** [comment]
Just tried the docs on an old computer with IE11 (v. version 11.719.18362.0) and it works fine. Do you use any custom filters? Can you share your table config (maybe even create a codepen)?

**Comment by Sarah-clariondoor** [comment]
I set up a jsfiddle a while back, not sure if that helps since that's not available in IE, but here is the link: https://jsfiddle.net/sarah_at_clariondoor/261acesg/

No custom filters, literally just pasted the code from the buefy link above into my vue component then rendered the vue app.

**Comment by jtommy** [comment]
@Sarah-clariondoor I'm sorry but i'm not able to reproduce it. It works well on IE 11

**Comment by Sarah-clariondoor** [comment]
<img width="1028" alt="Screen Shot 2020-04-22 at 3 27 35 PM" src="https://user-images.githubusercontent.com/42549181/80040031-074ec480-84ae-11ea-9b22-e5bceb9ca98d.png">

I looked again more closely, and there seems to be an error coming from the buefy table component. My apologies for not noticing this before. This error appears for every letter I type in the filter. I am not using any custom filtering, just the normal filtering provided by the searchable attribute.

**Comment by service-paradis** [comment]
Do you use Webpack (or VueCli) to compile your app?
If so, you should add `transpileDependencies: ['buefy'],` in your `vue.config.js` file. It will use Babel polyfills for this.

**Comment by Sarah-clariondoor** [comment]
We are using vue cli.

**Comment by Sarah-clariondoor** [comment]
Thanks for taking the time to look at this. I'll try that and fix our babel setup.
