### ISSUE TITLE
Dropdown Multiple with Checkboxes

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#2398]
Currently the Dropdown multiple option works by highlighting selected menu items.

The component would be more intuitive to users if the checkboxes were provided for users to check.

**Comment by jtommy** [comment]
@kerbo you have to use `custom` prop to dropdow-item and you customize it as you want, for example https://codepen.io/jtommy/pen/NWGGaRP?editors=1011

**Comment by kerbo** [comment]
Thanks for example. I had gone down this path and decided it shouldn't be necessary. IMHO, checkboxes should be the default behavior for this component. Not sure anyone really wants the old shift-select UI.

**Comment by jtommy** [comment]
@kerbo i might add prop `checkbox` on dropdown-item in order to add a checkbox when dropdown is `multiple`

**Comment by kerbo** [comment]
Thanks, if you do this, be sure to support clicking the entire menu item. That is, when clicking the menu item outside of the checkbox, the checkbox should check/uncheck.
