### ISSUE TITLE
Is there any way to make few rows selectable in b-table ?

### ISSUE THREAD

**Issue by Aishmaheshwari** [buefy/buefy#2402]
"vue": "2.6.10",
"buefy": "0.8.12",

Is there any way to make only checked rows selectable? something similar to :is-row-checkable. 

I have a few rows non-checkable but still I can select the rows

**Comment by jtommy** [comment]
Do you mean multiple select or single select?

**Comment by Aishmaheshwari** [comment]
Single select. My requirement is as follows:
when I am using :selected.sync="selected" I can select any row in the table. But I need a conditional check so a few rows are disabled and cannot be selected.
