### ISSUE TITLE
How to use Buefy with Unicons?

### ISSUE THREAD

**Issue by NickeManarin** [buefy/buefy#2406]
I'm trying to use [Unicons ](https://iconscout.com/unicons?ref=vue-unicons) on my website, via [vue-unicons](https://antonreshetov.github.io/vue-unicons/).

I was able to display the icons on the page directly via the `<unicon>` tag by using this config:

```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import Buefy from "buefy";
import Unicon from 'vue-unicons'
import { uniDownloadAlt, uniImport, uniArrowRight, uniArrowLeft, uniExternalLinkAlt, uniHeart, uniBookAlt, uniEnvelopeAlt, uniScenery, uniArchiveAlt, uniCompactDisc, uniAngleRight, uniAngleLeft, uniRedditAlienAlt, uniLinkedinAlt, uniGithubAlt, uniTwitterAlt, uniPaypal } from 'vue-unicons/src/icons';

Unicon.add([uniDownloadAlt, uniImport, uniArrowRight, uniArrowLeft, uniExternalLinkAlt, uniHeart, uniBookAlt, uniEnvelopeAlt, uniScenery, uniArchiveAlt, uniCompactDisc, uniAngleRight, uniAngleLeft, uniRedditAlienAlt, uniLinkedinAlt, uniGithubAlt, uniTwitterAlt, uniPaypal]);

Vue.use(Unicon);
Vue.use(Buefy, {
  defaultIconComponent: 'vue-unicons',
  defaultIconPack: 'Unicon' //This is probably wrong.
});

Vue.config.productionTip = false;

new Vue({
  router,
  render: h => h(App)
}).$mount("#app");
```

```
<b-navbar-item tag="router-link" to="/downloads">
    <unicon name="download-alt"/>
    <p>Downloads</p>
</b-navbar-item>
```

The problem is that I'm not able to use the icons with Buefy elements, like this one:

```
<b-button size="is-medium" icon-left="download-alt">
    Download
</b-button>
```

Is there any way to use vue-unicons with Buefy?

**Comment by jtommy** [comment]
You can add CSS icons at the moment. You can use it but not using icon prop

**Comment by NickeManarin** [comment]
Ok, I can use directly the CSS from [Unicon](https://iconscout.com/unicons/getting-started/line) instead of [vue-unicon](https://antonreshetov.github.io/vue-unicons/).

I didn't understand your second sentence... 
Is it (the CSS version) going to work with the `icon-left` property?

**Comment by jtommy** [comment]
Sure! Take a look at https://buefy.org/documentation/icon#custom-icon-pack

**Comment by NickeManarin** [comment]
It works, with some issues.

I tried to @import the CSS on my App.vue, but it was not working, probably because it's a CSS and the style is set to SCSS?

@import "https://unicons.iconscout.com/release/v2.1.5/css/unicons.css";

Anyway, I had to add this line to the index.html file instead:

`<link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.5/css/unicons.css">`

**App.vue**:

```
const customIconConfig = {
    customIconPacks: {
        'unicons': {
            sizes: {
                'default': '',
                'is-small': 'is-small',
                'is-medium': 'is-medium',
                'is-large': 'is-large'
            },
            iconPrefix: 'uil-',
            internalIcons: {
                'check': 'check',
                'information': 'info-circle',
                'check-circle': 'check-circle',
                'alert': 'exclamation-triangle',
                'alert-circle': 'exclamation-circle',
                'arrow-up': 'arrow-up',
                'chevron-right': 'angle-right',
                'chevron-left': 'angle-left',
                'chevron-down': 'arrow-down',
                'eye': 'eye',
                'eye-off': 'eye-slash',
                'menu-down': 'angle-down',
                'menu-up': 'angle-up'
            }
        }
    }
}

//This one goes inside the "export default" part.
  created() {
    this.$buefy.config.setOptions(customIconConfig)
  },
```

Since I could not find any size definition in Unicon, I had to add this classes on the **App.vue** style section:

```
.icon .is-small{
  font-size: 0.75rem;
}

.icon .is-medium{
  font-size: 1.25rem;
}

.icon .is-large {
  font-size: 1.5rem;
}
```

**Comment by jtommy** [comment]
Well done

**Comment by NickeManarin** [comment]
I just noticed something strange. 

When using a button as is-medium or as regular size, the size applied to the icon is "is-small".
When using "is-large" it sets the icon to "is-medium".

What's happening, @jtommy ?
