### ISSUE TITLE
Toggle detailed rows with left/right arrow keys in focusable and selectable tables

### ISSUE THREAD

**Issue by timwoelfle** [buefy/buefy#2408]
It's already great that rows in focusable and selectable tables can be navigated by up/down arrow keys. It would be even nicer if detailed rows could be toggled with left/right arrow keys, which I find very intuitive as reminiscent of folder navigation in e.g. Windows Explorer / macOS Finder (especially when chevron icon is visible)!

I'm currently using a custom implementation, but maybe this is something for a next release?

```
<b-table ref="table" :selected.sync="selected"
      :has-detailed-visible="hasDetail(row)"
      @keyup.native.arrow-left="toggleArticle"
      @keyup.native.arrow-right="toggleArticle"
      detailed focusable>
```

```
toggleArticle: function () {
    if (this.hasDetail(this.selected)) {
        this.$refs.table.toggleDetails(this.selected)
    }
}
```

**Comment by jtommy** [comment]
@timwoelfle thanks!
 Your implementation is good but i don't think to add it in the core code becuase some other user might want to open detail by other key (enter, etc..)
