### ISSUE TITLE
Taginput doesn't show completion after deleting item or receiving focus programmatically

### ISSUE THREAD

**Issue by cypressious** [buefy/buefy#2411]
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 2.6.11
**OS/Browser**: Windows 10 / Firefox

### Description

`b-taginput` won't show the autocomplete dropdown after deleting an item and when it received focus programmatically through `taginput.focus()`.

When the component is in that state, clicking also doesn't help. Only after typing something, the dropdown will reappear.

See below GIFs:

#### After deleting an item
![delete](https://user-images.githubusercontent.com/1191816/79573778-70ee5d80-80bf-11ea-9977-957ad146aae8.gif)

#### After receiving focus programmatically
![focus](https://user-images.githubusercontent.com/1191816/79573793-73e94e00-80bf-11ea-9904-7e7e29d3c2fa.gif)

### Steps to reproduce

```vue
<template>
    <div style="width: 300px; height:300px">
        <BTaginput
                ref="taginput"
                v-model="values" autocomplete field="displayName"
                :data="filteredData" openOnFocus
                @typing="typed = $event"/>

        <button @click="$refs.taginput.focus()">Focus</button>
    </div>
</template>

<script>
export default {
    name: 'Foo',
    data() {
        return {
            values: [],
            typed: ''
        };
    },
    computed: {
        filteredData() {
            return [1, 2, 3].map(x => ({
                id: x,
                displayName: `${this.typed} ${x}`
            }));
        }
    }
};
</script>
```

### Expected behavior

Autocomplete dropdown appears in both cases.

### Actual behavior

Autocomplete dropdown doesn't appear.

**Comment by jtommy** [comment]
Thanks, but there is a same issue https://github.com/buefy/buefy/issues/2411

**Comment by jtommy** [comment]
@cypressious Fixed remove but for focus try `<button @click="$refs.taginput.$refs.autocomplete.focus()">Focus</button>`
