### ISSUE TITLE
Table: add additional row to the header

### ISSUE THREAD

**Issue by foochris** [buefy/buefy#2412]
### Description

An additional header row that displays a cell that spans several header cells below: (e.x. 'Type 1', 'Type 2'):

![image](https://user-images.githubusercontent.com/1527289/79579991-5784eb80-8096-11ea-99ca-ccba332f83cc.png)

The feature requested would be similar to Bootstrap Vue:

https://bootstrap-vue.js.org/docs/components/table/#adding-additional-rows-to-the-header

### Why Buefy need this feature

This feature does not currently exist in Buefy.

**Comment by service-paradis** [comment]
You can achieve this using `subheading` or `header` slot I think

**Comment by foochris** [comment]
@service-paradis The goal is the reverse of the current implementation of `subheadings`: the first row spans several of the cells in the second row. And your suggestion using the `subheading` slot will result in the subheadings prop:

https://github.com/buefy/buefy/issues/2292

https://buefy.org/documentation/table/#subheadings

**Comment by kerbo** [comment]
I've tried using Labels for the top and subheadings for the bottom and can't get it to work. One of the problems is you need to add colspan to the top row and there is no way to do that. In addition to colspan, you normally want to style things like having the text in the top row centered over the spanned columns.

**Comment by service-paradis** [comment]
@foochris 
Thanks for the additional info. You're right. This is not achievable right now, but could certainly be useful.

**Comment by mavyfaby** [comment]
Any updates?

**Comment by marianomd** [comment]
This would be a nice addition.

**Comment by von-maurus** [comment]
I just needed this feature I need to implement like two subheadings, its somehow possible right now?
