### ISSUE TITLE
How can I use just one Buefy component without install all Package

### ISSUE THREAD

**Issue by murilolivorato** [buefy/buefy#2413]
Hello , I want to use just these "Select" component -
https://buefy.org/documentation/select

But I dont want install all Buefy components .
There is any how to install just this component withou install all Buefy  Package  ?
Thanks , congratulation , nice job =)

**Comment by jtommy** [comment]
Sure https://buefy.org/documentation/start, individual components

**Comment by TorchSK** [comment]
What about styles? How to import them individually?
