### ISSUE TITLE
header-class property in b-table-column does not work

### ISSUE THREAD

**Issue by P3trur0** [buefy/buefy#2414]
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 2.6.11
**OS/Browser**: Ubuntu 18.04/Chrome

### Description
In Buefy tables, the application of the `header-class` property seems not working.

### Steps to reproduce

1. Define a `b-table`
2. Add a slot containing a list of `b-table-column`s like this:

```javascript

<template slot-scope="props">
    <b-table-column
        field="id"
        label="ID"
        header-class="has-text-centered"
        cell-class="has-text-left"> 
       {{ props.row.id }}
    </b-table-column>
...
</template>
```

### Expected behavior

The header of the column should be vertically aligned to the center.

### Actual behavior

Whatever CSS alignment class is added through `header-class`, it seems not being applied to the header itself.

**Comment by jtommy** [comment]
You should customize it with a custom class, for example
```
th-centered {
justify-content: center;
text-align: center;
display: flex;
}
```
