### ISSUE TITLE
Buefy styles are not getting applied

### ISSUE THREAD

**Issue by slidenerd** [buefy/buefy#2415]
### Overview of the problem

**Buefy** version: 0.8.15
**Nuxt** version: 2.12.2
**OS/Browser**:

Codesandbox.io

### Description
Buefy does not apply scss styles to imported components

### Steps to reproduce

- Create a nuxtjs codesandbox
- Install latest version of bulma
- Add node-sass and sass-loader as dev dependencies
- Import bulma scss files
- Install buefy
- Create buefy.js file under plugins import dropdown component
- Import buefy scss inside the app.scss file
- Add a dropdown in pages/index.vue
- Buefy styles are NOT applied on this dropdown

### Expected behavior

SCSS styles should be applied

### Actual behavior

Styles are not applied, if this was working the dropdown would be purple

[HERE](https://codesandbox.io/s/vigilant-lumiere-u7crc?file=/pages/index.vue) is the codesandbox

**Comment by jtommy** [comment]
Please take a look at https://buefy.org/documentation/customization
