### ISSUE TITLE
[Feature] Default slot component for b-upload

### ISSUE THREAD

**Issue by runyasak** [buefy/buefy#2416]
### Description
I have used `b-upload` with normal button, but cannot used with `b-button`.
I'm not sure that would be the bug to fix, or it be an intention to using with normal button.

```html
<!-- This is not working. -->
<b-upload v-model="file">
    <b-button
      type="is-primary"
      icon-left="upload">
        Click to upload
    </b-button>
</b-upload>
```

In my opinion, I suggest to make default button component for `b-upload`. So, we will no need to default button, but `default` slot still work.

```html
<b-upload
  v-model="file"
  type="is-primary">
</b-upload>
```

### Why Buefy need this feature
Users don't need to add ordinary button by themselves.

If you have any feedback or suggestion, please comment on this issue. 😁

**Comment by jtommy** [comment]
Why ? In this way you can use button or b-button or icon or as anything you want
