### ISSUE TITLE
How to put sidebar inside an element instead of body component?

### ISSUE THREAD

**Issue by okrymus** [buefy/buefy#2420]
I am trying to put sidebar inside a component instead of into body component. Is there anyway I can do it? Thank you for your help

**Comment by jtommy** [comment]
Did you try https://buefy.org/documentation/sidebar#static ?

**Comment by okrymus** [comment]
Thank you for your answer! But when I set position="static", the animation, fullheight and right do not work. Shouldn't I use the container? but I do not know how to set container

**Comment by jtommy** [comment]
@okrymus an example?

**Comment by jtommy** [comment]
@okrymus take a look at https://codepen.io/jtommy/pen/WNQppzv.
The sidebar is on the right, you can toggle it and the animation works and is fullheight
