### ISSUE TITLE
Taginput with open on focus, doesn't show autocomplete until you start typing

### ISSUE THREAD

**Issue by rudolph2907** [buefy/buefy#2422]
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 2.6.11
**OS/Browser**: Windows Chrome/Firefox

### Description

Taginput with open on focus, doesn't show autocomplete when you click on the component, it only show the autocomplete once you start typing. It does work if you click away and then click on the component afterwards. But not the first time.

### Steps to reproduce

1. Click on Tagsinput - nothing happens
2. Start typing, it shows the autocomplete
3. Click away
4. Click on the tagsinput again, then it shows the autocomplete immediately.

Video: https://www.loom.com/share/733960b2250e41a3ab85bbdc3eeef83d

### Expected behavior

It should show the autocomplete when you click on the tagsinput.

### Actual behavior

You need to start typing the first time you click on the tagsinput.

**Comment by jtommy** [comment]
Can you provide a codepen or similar?

**Comment by rudolph2907** [comment]
Sorry @tjommy. I've found my problem, thanks for reaching out.

**Comment by dalholm** [comment]
> Sorry @tjommy. I've found my problem, thanks for reaching out.

I have the same problem as you, how did you fix it? :)

**Comment by rudolph2907** [comment]
My problem was, I was only setting my :data variable in my @typing event, so that was why it was only showing after I typed the first time.

**Comment by rudolph2907** [comment]
> 
> 
> > Sorry @tjommy. I've found my problem, thanks for reaching out.
> 
> I have the same problem as you, how did you fix it? :)

@dalholm My problem was, I was only setting my :data variable in my @typing event, so that was why it was only showing after I typed the first time.

**Comment by dalholm** [comment]
@rudolph2907 ah ok... my problem is that on focus it sometimes opens and sometimes not. But it always opens on typing.

**Comment by rudolph2907** [comment]
@dalholm I think as long as the data bound :data is there, it should show up correctly.

**Comment by DmytroKuznyetsov** [comment]
Hey there, I have the same problem when I using vuex store and computed props.
https://codepen.io/dmytro-kuznetsov/pen/NWxMYNQ?editors=1010
Also after each selection dropdown list is closing when common data gets from computed

**Comment by DmytroKuznyetsov** [comment]
> Can you provide a codepen or similar?
 
added codepen link above
