### ISSUE TITLE
B-table data update unchecks the checkbox

### ISSUE THREAD

**Issue by Aishmaheshwari** [buefy/buefy#2426]
### Overview of the problem

**Buefy** version: 0.8.12
**Vuejs** version: 2.6.10
**OS/Browser**: Windows/Chrome

### Description
We have a b-table in out application where we are facing the below issue.
consider the below

`:data="data"
:checked-rows.sync="checkedRows"`
 where 
`data = [
  { id: 1, name: 'abc'},
  { id: 2, name: 'bcd'},
  { id: 3, name: 'cde'},
];

checkedRows = [
  { id: 2, name: 'bcd'},
  { id: 3, name: 'cde'},
]`

now if data changes as below
`data = [
  { id: 1, name: 'abc'},
  { id: 2, name: 'bcd', date: '21042020'},
  { id: 3, name: 'cde'},
];`

with the new data checked rows still remains same but checkbox for  { id: 2, name: 'bcd'} gets deselected.

As I understand this is happening because the two objects don't match but is there any way to override the behaviour so the objects are compared on the basis of id.

### Steps to reproduce

1. create a b-table with data binded from an data-array present is store.
2. check the checkboxes for a few rows
2. add a new property in one of the checked object in the data-array
4. check the checkbox for the changed item get deselected

### Expected behavior

the comparison between data-array and checkedRows should be key based and not direct object comparison

### Actual behavior

if a new object in rows array is added i.e. is a new row is added all the check boxes get deselected.

**Comment by jtommy** [comment]
Sure, using `custom-is-checked`. It's a function that compare the selected element with all visible rows
