### ISSUE TITLE
Custom dialog with multiple options

### ISSUE THREAD

**Issue by NickeManarin** [buefy/buefy#2427]
I need to display a dialog/modal with a custom content, two buttons, pointing to two methods on the parent component.

Basically:
User clicks on button.
Dialog appears, with a title + two buttons + a cancel button.
User clicks on Button2, the dialog closes and the method this.button2() gets called on the parent component.

Is there built in solution to solve this?
(I'm new to Buefy/Vue)

**Comment by jtommy** [comment]
Take a look at https://buefy.org/documentation/modal#component. You can listen close event too on the instance that you get calling open method.
