### ISSUE TITLE
Allow to modify activeStep onCancel

### ISSUE THREAD

**Issue by hiteshbhayani** [buefy/buefy#2428]
Currently, I am facing issues while resetting active steps to 0. I am not sure there is an issue with my code or it is intended behavior. change made to active step is not reflecting on Steps components, Though, when I see it from the vue dev tools, the value is changed for it.

**Comment by jtommy** [comment]
Can you share your code ?

**Comment by hiteshbhayani** [comment]
@jtommy  Please check this https://codesandbox.io/s/formsteps-kqxnm

**Comment by jtommy** [comment]
@hiteshbhayani it's no a buefy issue.. you have to add a watch to value prop to update activeStep variable or using directly it

**Comment by hiteshbhayani** [comment]
@jtommy Sorry, my bad. I got it. Thanks for your quick response.
