### ISSUE TITLE
Sidebar background not using $sidebar-background variable

### ISSUE THREAD

**Issue by beastmike1** [buefy/buefy#2429]
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 2.6.11
**OS/Browser**: All

### Description
Sidebar is not using the variable $sidebar-background in it's implementation

### Expected behavior
'buefy\src\scss\components\_sidebar.scss'
```
.b-sidebar {
    .sidebar-content {
        background-color: $sidebar-background;
```     

### Actual behavior
'buefy\src\scss\components\_sidebar.scss'
```
.b-sidebar {
    .sidebar-content {
        background-color: $background;
```

**Comment by jtommy** [comment]
Probably isn't a good name (i might change it) but you can change the background using type prop.
`$sidebar-background` is about overlay color
