### ISSUE TITLE
Feature request: Make steps more intuitive in mobile

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2434]
### Description

`_steps.scss` hides by default any non-active step in mobile:

![image](https://user-images.githubusercontent.com/8303937/80232686-35b6d600-864d-11ea-87c0-7fb3da23b2fa.png)

It will be nice to include some extra info by default (e.g. total of steps) or include the `before`/`after` lines only if there are more additional items.

We can also hide the step description in mobile and display only numbers as [Vuetify](https://vuetifyjs.com/en/components/steppers/#usage) does.

### Why Buefy need this feature

A better UI experience for mobile users.

**Comment by jtommy** [comment]
@fabiofdsantos sure! We can discuss about it @service-paradis

**Comment by service-paradis** [comment]
@fabiofdsantos 
I like the ideas! I just made a first draft of what could be done to improve the flexibility. What do you think?

![captured (1)](https://user-images.githubusercontent.com/12817388/80605613-4eced680-8a01-11ea-80a3-d19abe2db2c7.gif)

- minimalist: The current mobile look
- compact: Every markers, but details are shown only for the active one
- null: Would not apply any different style, so Steps will be the same as viewed on desktop

**Comment by fabiofdsantos** [comment]
@service-paradis 
I think that's a good approach. We just need to take into consideration some potential hidden steps (due to the lack of available space to display everything even in compact mode). As we navigate it could hide automatically the step from the opposite side as we display a new one?!

**Comment by jtommy** [comment]
@service-paradis that's great. I would like to add it in the last 0.8.x version ;)
