### ISSUE TITLE
Config Default Date Parser/ Default Date Formatter

### ISSUE THREAD

**Issue by fcandiani** [buefy/buefy#2436]
This is more of a question. I'm setting up the default formatters/parser for the datetimepicker and I came across the issue that I don't know the configuration set on the component, as used in the default formatters/parser within bulma

/components/datepicker/Datepicker.vue:324

`dateFormatter: {
    type: Function,
    default: (date, vm) => {
        if (typeof config.defaultDateFormatter === 'function') {
            return config.defaultDateFormatter(date)
        } else {
            return defaultDateFormatter(date, vm)
        }
    }
},
dateParser: {
    type: Function,
    default: (date, vm) => {
        if (typeof config.defaultDateParser === 'function') {
            return config.defaultDateParser(date)
        } else {
            return defaultDateParser(date, vm)
        }
    }
}`

the attribute `vm` is not an argument of the function call for `config.default`.

I'm missing something or this could be an argument?

Regards

**Comment by jtommy** [comment]
You don't need it, you should look at first param (date)
