### ISSUE TITLE
Datepicker - listOfYears is incorrectly calculated when advancing focusedDateData

### ISSUE THREAD

**Issue by Mattertorian** [buefy/buefy#2437]
Thank you for this great library!

I have encountered an issue regarding the datepicker component:

Expected behavior: when focuseddate, minDate, maxDate and yearRange props are set, moving to a new year (eg. from 2020 --> 2021 should still allow 2020 to be selected in the year dropdown (if it is greater than minDate).

Current behavior: when advancing the year (eg. 2020 --> 2021), previous year can no longer be selected. 

Locally I tested eliminating the '>' operation on line 498 (see below). This fixed the issue.

Same goes for the '<' operation on line 493

https://github.com/buefy/buefy/blob/2dfe56c7d51844c7e872aa28043116ef17ed6749/src/components/datepicker/Datepicker.vue#L491-L508

**Comment by jtommy** [comment]
@Mattertorian what prop values are you using ?

**Comment by Mattertorian** [comment]
In the test case:

focusedDate: Date(2020, 9, 1)
minDate: Date(2020, 4, 1)
maxDate: Date(2022, 4, 1)
yearRange: [0,3]

But I see the same behavior with other values as well.

**Comment by oldcastor** [comment]
> @Mattertorian what prop values are you using ?

even with documentation example
![1](https://user-images.githubusercontent.com/21212418/80382235-b7576f80-88aa-11ea-89ed-9a9e6dfcca21.png)
![2](https://user-images.githubusercontent.com/21212418/80382240-b7f00600-88aa-11ea-9841-cf7600be9d09.png)

**Comment by jtommy** [comment]
> In the test case:
> 
> focusedDate: Date(2020, 9, 1)
> minDate: Date(2020, 4, 1)
> maxDate: Date(2022, 4, 1)
> yearRange: [0,3]
> 
> But I see the same behavior with other values as well.

It's no about min and max but years-range prop and you idea doens't "fix" it

**Comment by Mattertorian** [comment]
I see. Tried removing the yearRange prop while keeping the min-date and max-date props. This fixes the issue. Perhaps it should be noted in the documentation that the two are incompatible.?

Anyway. Thanks for the help.
