### ISSUE TITLE
"destroy-on-hide" feature significantly changed behaviour of <b-modal>

### ISSUE THREAD

**Issue by vvlasovv** [buefy/buefy#2438]
### Overview of the problem

**Buefy** version: [0.8.16]

### Description

Latest changes of Modal.vue break the existing functionality of `<b-modal>`. `v-if="isActive"` was replaced with `v-show="isActive"`, so injected components are now rendered unconditionally by default. It's a breaking change for us, as we perform heavy API requests just only when the injected component is created. Please, confirm that this is an expected behaviour, but not a side effect of the feature.

[Feature commit](https://github.com/buefy/buefy/commit/1757aa3e721f39d74d09bad1f3ea4ef1b252805f)

### Steps to reproduce

```
<b-modal :active.sync="isModalActive">
    <injected-component></injected-component>
</b-modal>
```

### Expected behavior

`<injected-component>` is not created when `isModalActive === false`.

### Workaround

```
<b-modal :active.sync="isModalActive">
    <injected-component v-if="isModalActive"></injected-component>
</b-modal>
```

**Comment by jtommy** [comment]
I don't understand well, I think it's the same behaviour

**Comment by vvlasovv** [comment]
I've created two codepen examples to explain the exact difference, if it's still relevant:
1. [0.8.15](https://codepen.io/vvlasov/pen/XWmMLjw)
2. [0.8.16](https://codepen.io/vvlasov/pen/NWGpZvz)

Could you, please, share what to expect on this issue? We'd like to either stick to the previous minor version or change our code accordingly.

**Comment by jtommy** [comment]
I'm fixing it and i'm going to release 0.8.17

**Comment by jtommy** [comment]
@vvlasovv I apologise for the break but i recover all with new 0.8.17 https://github.com/buefy/buefy/releases/tag/v0.8.17

**Comment by vvlasovv** [comment]
Just confirming that the issue is resolved. Thank you for the quick fix, @jtommy.
