### ISSUE TITLE
Table Loading Slot

### ISSUE THREAD

**Issue by thedomeffm** [buefy/buefy#2439]
The buefy table should get a slot for loading.

There is a slot for empty that I am using like this:
```
<b-table :data="items"
         :loading="loading">
    [...]
    <template slot="empty">
        <table-empty />
    </template>
    [...]
</b-table>
```
So all my empty tables look the same.

Now we got the nice `<b-skeleton>` and it would be nice to have an slot for loading (that is used if b-table :loading=true) no matter if items is empty or not.
So I could build an "loading-table" component and use it like this:

```
<b-table :data="items"
         :loading="loading">
    [...]
    <template slot="loading">
        <table-loading-state />
    </template>
    [...]
</b-table>
```

**Comment by jtommy** [comment]
Sure it's a good idea

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/2c8f06c1f8e68887ad034ee8b4ec0d2daf7f05e5
