### ISSUE TITLE
Input tag via Field component error messages susceptible to XSS

### ISSUE THREAD

**Issue by CristinaSolana** [buefy/buefy#2444]
### Overview of the problem

**Buefy** version: 0.8.17
**Vuejs** version: 2.X.X
**OS/Browser**:

Input tag via field component error messages susceptible to XSS. The issue is the v-html used here: https://github.com/buefy/buefy/blob/dev/src/components/field/Field.vue#L35

![Screen Shot 2020-04-27 at 9 32 04 AM](https://user-images.githubusercontent.com/524896/80438351-f816af00-88d1-11ea-8037-69348a3d2030.png)

### Steps to reproduce

1. Go to https://buefy.org/documentation/input
2. Scroll down to Icons section
3. in the email field enter: "><img src=x onerror=alert(document.domain)>
4. Press Tab key

### Expected behavior

The error message should not parse HTML (or sanitize it firs) so that XSS is not possible

### Actual behavior

Error message parses HTML and allows XSS and therefore the alert pops with the document's domain

**Comment by jtommy** [comment]
What do you think if I add a message slots in order to use a custom content ?

**Comment by CristinaSolana** [comment]
Tbh, what I think would be great is if the message and the error were separate so you could have a custom message and custom error on the field. :)

But for the sake of not having an XSS by default on fields, I think a slot is a good compromise if it will eliminate the v-html.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/f0ff2ae65fee34e247e74e6ab4881c929928c066
