### ISSUE TITLE
Safari - Datepicker component isn't working properly

### ISSUE THREAD

**Issue by ikram-shah** [buefy/buefy#2447]
### Overview of the problem

**Buefy** version: [0.8.5]
**Vuejs** version: [2.6.10]
**OS/Browser**: Safari

### Description

Datepicker component is not working properly. It works fine with chrome and firefox.

<img width="590" alt="Screenshot 2020-04-28 at 8 50 44 PM" src="https://user-images.githubusercontent.com/17762967/80505725-57d48f00-8992-11ea-9982-fbe764d3634b.png">

### Steps to reproduce

Try to add datepicker in any component. This is my code

```
<b-datepicker
            editable
            v-model="$store.state.createPostFormData.date"
            position="is-top-right"
            icon="calendar-today"
></b-datepicker>
```

### Expected behavior

Similar to chrome and firefox.

<img width="364" alt="Screenshot 2020-04-28 at 8 55 34 PM" src="https://user-images.githubusercontent.com/17762967/80506017-b00b9100-8992-11ea-8495-61a1c999a5df.png">

### Actual behavior

<img width="392" alt="Screenshot 2020-04-28 at 8 50 44 PM" src="https://user-images.githubusercontent.com/17762967/80506114-c9acd880-8992-11ea-9991-baade9f2eda7.png">

**Comment by service-paradis** [comment]
I also just got a call from a client. Datepicker is displaying Nan everywhere. I'm not able to reproduce the issue using Safari on iPad on my side!

**Comment by ikram-shah** [comment]
As, in this case I am trying to load a date into the date picker component, when I tried to print the date when component is getting mounted, this is how it showed in 

**Chrome**
<img width="407" alt="Screenshot 2020-04-29 at 12 40 00 AM" src="https://user-images.githubusercontent.com/17762967/80527485-0b994700-89b2-11ea-8368-af43406eebd9.png">

**Safari**
<img width="234" alt="Screenshot 2020-04-29 at 12 40 09 AM" src="https://user-images.githubusercontent.com/17762967/80527590-37b4c800-89b2-11ea-938e-cf121cd188ef.png">

While loading the date I used`new Date(payload.created_time)`

**Comment by ikram-shah** [comment]
Finally, was able to reproduce the issue. When the timezone (offset from UTC time) is present in the date, it fails to render in the component. 

Currently: 
Works `2020-02-08T17:43:50`
Fails `2020-02-08T17:43:50+0000`

Have added it in [Codepen](https://codepen.io/ikramshah15/pen/NWGgoxK). Please try this **Safari** browser. 

Steps to reproduce:
1. Click on `INCORRECT | Set to 2020-02-08`
2. Click on the date picker component to see the NaN

**Comment by jtommy** [comment]
Thanks for the reproduce it. Btw it should depends on user and not about Buefy but eventually any PR is welcome

**Comment by amadoun** [comment]
Has this been fixed, I can see it on the Buefy website itself with version 0.9.5...
![buefy](https://user-images.githubusercontent.com/873688/113498646-c1331b00-94dc-11eb-8083-0d0825b99ebc.gif)
