### ISSUE TITLE
Table with sticky detailed section

### ISSUE THREAD

**Issue by mlapeyre3** [buefy/buefy#2448]
### Description

Hello,
I saw a few apps with very nice and smooth Table / Listview with sticky subheaders. Like this one below:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19735493/80529359-a9334d00-8997-11ea-940b-3fd3b5c67a86.gif)

Here is another example: http://polarblau.github.io/stickySectionHeaders/

### Why Buefy need this feature

Buefy does not have this feature but some already existing behavior that may be upgraded to support it. Let's say a combo between _Custom Detailed rows_ or _Subheadings_ and _Sticky Headers_

This is a very eye appealing way to display large amount of data in a table while keeping the table small and easy to navigate.

Cheers!

**Comment by jtommy** [comment]
It's nice but there isn't a similar component in Buefy at the moment or a similar behaviour using table
