### ISSUE TITLE
Snackbar - onAction return Promise

### ISSUE THREAD

**Issue by schulz3000** [buefy/buefy#2449]
In the Snackbar Options a function can be provided for onAction. At the moment it only takes synchronous functions. It would be great if we also could provide async functions there which returns a Promise.

In my case I want to call a webservice and this call is async.

```
this.$buefy.snackbar.open({
  onAction: this.myAsyncMethod()
});

myAsyncMethod(): Promise<void>{
   return callMyWebServiceAsync();
}
```

**Comment by jtommy** [comment]
Please check it https://github.com/buefy/buefy/issues/1953
