### ISSUE TITLE
add props show-overflow-tooltip to b-table 

### ISSUE THREAD

**Issue by Valar103769** [buefy/buefy#2452]
link [elementui](https://element.eleme.io/#/zh-CN/component/table)

Although you can use b-tooltip and text-overflow to achieve it yourself, but trouble, I hope that bulfy can provide props directly.
![image](https://user-images.githubusercontent.com/36926073/80558812-2ef1df80-8a0e-11ea-9780-14c11a68c18e.png)

**Comment by jtommy** [comment]
I rewrote tooltip and you can use it on table with append-to-body prop

**Comment by Valar103769** [comment]
> I rewrote tooltip and you can use it on table with append-to-body prop

I think that when setting a fixed width, text-overflow: ellipsis should be provided,
