### ISSUE TITLE
Feature request: custom-class in b-field applied as horizontal property

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2454]
### Description

I've applied a `custom-class` to an input and now I want to change the appearance of select elements. So, It would be nice to have the `custom-class` property for select elements as we have for inputs.

However, I've noticed that if we apply the `custom-class` to `b-field` div as its done for `horizontal` property, it will be easy to apply custom styles to most of elements (e.g. input, select, datetepicker, autocomplete, etc).

### Why Buefy need this feature

Offering more flexibility to manage custom styles in form controls.

**Comment by fabiofdsantos** [comment]
Hmm.. Why we don't apply `custom-class` to the same `div` as `is-horizontal`? It will allow to apply easily custom styles to any `b-field` (label + element).

**Comment by jtommy** [comment]
why do you need it ? you can apply the class attribute on field

**Comment by fabiofdsantos** [comment]
@jtommy 

Yes.. I solved my issue by using `class` attribute on `b-field` and targeting child elements: `input`, `select`, etc.

So, maybe allowing `class` attribute will be enough for `labels` too, instead of having a specific `custom-class` for them.
