### ISSUE TITLE
B-field message duplicated while using radio buttons with horizontal prop

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2456]
### Overview of the problem

**Buefy** version: 0.8.17
**OS/Browser**: macOS / Safari

### Description

Message is being duplicated while using radio buttons w/ `horizontal` property:

![image](https://user-images.githubusercontent.com/8303937/80611648-c9641a00-8a32-11ea-9b2a-089747a0eeff.png)

### Steps to reproduce

1. Wrap `b-radio-button` in `b-field`.
2. Add `message` and `horizontal` properties to `b-field`.

### Expected behavior

No duplication. 

### Actual behavior 

Message is being duplicated per button.

**Comment by service-paradis** [comment]
Can you show some code or create a codepen?
I think you should have a single `b-field` wrapping your `b-radio-button`

**Comment by fabiofdsantos** [comment]
@service-paradis 
You can use [this](https://codepen.io/pen?&editable=true&editors=101=https%3A%2F%2Fbuefy.org%2Fdocumentation%2Fradio) from docs.

Just append `message="x" horizontal` to `b-field`. It's related with `horizontal`.
