### ISSUE TITLE
Make the background of a step-detail in b-steps transparent

### ISSUE THREAD

**Issue by gutisalex** [buefy/buefy#2457]
### Description

The picture below shows the fist step of a Steps component. As you barely see the background of the text is set to white but the background of the page is whitesmoke. It will be more obvious if the background color of the page would be darker!

![image](https://user-images.githubusercontent.com/52527652/80675343-8054aa00-8ab4-11ea-972a-d02d776fd0f5.png)

### Why Buefy need this feature

Because it looks better!

**Comment by service-paradis** [comment]
The details background is defined as `$body-background-color` right now. I will make a PR to remove this.
