### ISSUE TITLE
Steps component not working with vee-validate

### ISSUE THREAD

**Issue by gutisalex** [buefy/buefy#2458]
### Overview of the problem

**Buefy** version: [0.8.17]
**Vuejs** version: [2.6.7]
**VeeValidate** version: [3.2.5]
**Windows 10 / Chrome 81.0.4044.129**:

### Description

Stepping forward using b-steps with vee-validate is not working! The reason is that the forms sitting in the inactive steps cannot be validated because they have not been filled out the time you press the forward button.

### Steps to reproduce

1. Create a validation observer with a form element
2. Create a step compenent with two steps inside the form element
3. Each step should have at least one input field with a validation provider and a rule like required
4. Use the forward button of the step navigation to trigger a function which should validate the form and increase the active step

[CodeSandbox](https://codesandbox.io/s/veevalidate-components-buefy-ivwrs?fontsize=14&hidenavigation=1&theme=dark)

### Expected behavior

The form should be validated and if the state is valid it should lead to the next step.

### Actual behavior

The form is validated but it doesnt lead to the next step.

The reason that does not work is the fact that the Step component uses v-show to show the step according to the activeStep variable. 

/components/steps/Steps.vue line 8:
`v-show="stepItem.visible"` 

To work around this you have to v-if the forms in the steps according to the activeStep otherwise the observer would prevent of going forward due to the fact the forms in the inactive steps are empty and could not be validated.

### Solution
Use v-if in the Steps.vue and it should work this way

**Comment by fabiofdsantos** [comment]
I'm using custom controls and a `ValidationObserver` inside each step.

**Comment by gutisalex** [comment]
> I'm using custom controls and a `ValidationObserver` inside each step.

Oh well yeah you could do that but this adds a lot of additional code. You would have to put the controls inside the forms as well...

**Comment by service-paradis** [comment]
@gutisalex Did you try the `destroy-on-hide` prop?

**Comment by jtommy** [comment]
@gutisalex I agree with @service-paradis. It should be the correct way for you

**Comment by mccombs** [comment]
@gutisalex or @service-paradis @jtommy - is there a working example here?
