### ISSUE TITLE
Improvement suggestion: scrollable b-dropdown

### ISSUE THREAD

**Issue by franciscoh017** [buefy/buefy#2461]
### Description

Right now, when using a b-dropdown with multiple items, the options list doesn't have a scrollbar, so for big lists of options the layout could be compromised.
![alt text](https://i.ibb.co/cDjF7BD/image.png "Preview: Infinite Dropdown Option List")

After a few tweaks on my code managed to make the component scrollable with a little css and would like to collab to implement this new feature with a new boolean property named "scrollable",
defaulted to false, that allows the users to enable the scrollbar, and  a string /numeric prop "max-height" to set a max-height for the .dropdown-content for all the screen breakpoints.

![alt text](https://i.ibb.co/wgGLg30/Annotation-2020-04-30-090757.png "Sample 1: Scrollable Dropdown Option List (Mobile)")
![alt text](https://i.ibb.co/ZGZxxyJ/Annotation-2020-04-30-090650.png "Sample 2: Scrollable Dropdown Option List (Desktop)")

### Why Buefy need this feature

This new feature would allow developers to take advantage of b-dropdown qualities to provide read-only lists with custom templates, as per now, using it for a great ammount of dropdown items could break the page layout.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/pull/2467#issuecomment-622365688
