### ISSUE TITLE
Feature request: Specify a multi-column *default* sort without actually using sortMultiple

### ISSUE THREAD

**Issue by wgordon17** [buefy/buefy#2462]
### Description

I would like to specify a _default_ multi-column sort.

### Why Buefy need this feature

Currently, I'm only able to find example of setting a single-column default sort, or examples of how to enable the _ability_ to turn on multi-column sort.

**Comment by jtommy** [comment]
@wgordon17 there isn't a way at the moment buy you can edit sortMultipleDataLocal data (by ref) pushing { field: string, order: boolean (asc = true) )

**Comment by wgordon17** [comment]
Thank you, I'll keep that in mind! I've updated the title now to reflect that this is instead a feature request :)

**Comment by jtommy** [comment]
@wgordon17 did you try setting the array prop `sortMultipleData` ?

**Comment by jtommy** [comment]
It will be available in the next version using the previous prop

**Comment by Thaurin** [comment]
Should this not be updated in [the documentation](https://buefy.org/documentation/table#api-view), which for the `sortMultipleData ` prop reads:

> Used in combination with backend-sorting

Took me a while to find this issue and figure it out.
