### ISSUE TITLE
Hover doesn't work on Sidebar

### ISSUE THREAD

**Issue by vikiival** [buefy/buefy#2466]
### Overview of the problem

**Buefy** version: [0.8.17]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS 10.13.6 / Chrome Version 84.0.4128.3

### Description

Sidebar on docs is able to make darker background if user hover on `<menu-item>` however this feature doesn't work on [vue-app](https://github.com/vikiival/buefy-sidebar) even codepen (from docs)

### Steps to reproduce

1. Clone repo or open codepen attached above

### Expected behavior

I expect that hovering on `menu-item` should make background darker and cursor should be pointer

As we see on image I hovered over `Info` item

<img width="283" alt="Screen Shot 2020-04-30 at 23 10 59" src="https://user-images.githubusercontent.com/22471030/80760431-306bf680-8b39-11ea-8211-db0f932662cf.png">

### Actual behavior

Only cursor is pointer

<img width="275" alt="Screen Shot 2020-04-30 at 23 21 41" src="https://user-images.githubusercontent.com/22471030/80760660-89d42580-8b39-11ea-9cae-f073bb70d6e5.png">

**Comment by jtommy** [comment]
It isn't an issue abotut sidebar but menu component, probably i'll check it in the next breaking change (soon)

**Comment by Sogl** [comment]
I have the same problem in last version. Any fix?
