### ISSUE TITLE
Feature request: Allow hover on tooltips in order to copy tooltip data

### ISSUE THREAD

**Issue by wgordon17** [buefy/buefy#2470]
### Description

Currently, when displaying a tooltip, if there is information stored that needs to be copied somewhere else, e.g., credit card number, account number, alternative ID, username, email address, you can't hover on the tooltip in order to be able to select/copy the data. Additionally, it's not possible to place a link in a tooltip and have it stay long enough to click the link.

### Why Buefy need this feature

There are valid use cases when you may not want to _always_ show information in a UI, but still make it available to the user when wanted. There _are_ other mediums that could work for this, modals probably comes to mind first. But for something as simple as showing a Customer Name, but also give you the option to see the customer's Account Number, a modal seems a bit heavy. Tooltips are great for this use case, but for example with the Account Number, I want to select/copy this number, and then paste it in another system. Or if I want to provide a _link_ in the Tooltip directly to another endpoint.

**Comment by jtommy** [comment]
You should be able to do it in the next breaking version that I'm developing :)
