### ISSUE TITLE
Newly installed Vuejs/Buefy App Fails to run

### ISSUE THREAD

**Issue by c-myers1** [buefy/buefy#2471]
### Overview of the problem

Used vue cli 3 to create a new app, CD'd into it and ran "npm install buefy." Resultant package.json except is as follows.
"dependencies": {
    "buefy": "^0.8.17",
    "core-js": "^3.6.4",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6",
    "vuex": "^3.1.3"
  }

Placed the materials icons css link in the public/index.html file and modified the app.vue to have some Buefy markup. Then ran npm run serve

### Description

First error:
` ERROR  Failed to compile with 1 errors                               4:34:20 PM

This dependency was not found:

* @/data/sample.json in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./nod
e_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./n
ode_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lan
g=js&

To install it, you can run: npm install --save @/data/sample.json`

Followed that instruction and got 2nd error:

`npm ERR! code ENOLOCAL
npm ERR! Could not install from "@C:\Program Files\Git\data\sample.json" as it d                                                                                                                oes not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2020-05-01T15_34_41_                                                                                                                216Z-debug.log
`
How do I get this running?

**Comment by jtommy** [comment]
Are using a sample data tha Buefy doesn't provide in the build
