### ISSUE TITLE
Buefy installation problem

### ISSUE THREAD

**Issue by c-myers1** [buefy/buefy#2472]
I have tried again using just CLI (not gui) and it shows the issue is with Buefy (app works before npm install buefy):

1. vue create app
2. CD app
3. npm run serve                 // dummy Vue app served without problems
4. npm install buefy            //long list of warnings given
5. npm run serve                

This gives error: 
` ERROR  Failed to compile with 1 errors                                                                                                                                               5:01:46 PM

This dependency was not found:

* core-js/modules/es.object.to-string in ./src/router/index.js

To install it, you can run: npm install --save core-js/modules/es.object.to-string
`

Trying to install this gives another error.

I'm not using any sample data.

**Comment by jtommy** [comment]
> This dependency was not found:
> 
> core-js/modules/es.object.to-string in ./src/router/index.js

??

Please ask on Discord
