### ISSUE TITLE
Is it able to use b-step-item in the components?

### ISSUE THREAD

**Issue by kitadakyou** [buefy/buefy#2475]
### Overview of the problem

Error when use `b-step-item` in the component.

**Buefy** version: [0.8.17]
**Vuejs** version: [2.6.11]
**Nuxt-Buefy** version: [0.3.28]
**Nuxt.js** version: [2.12.2]
**OS/Browser**: Windows 10, Google Chrome 81.0.4044.129（Official Build）

### Description

When use `b-step-item` in the component, error message will be displayed.

### Steps to reproduce

I created these two files.

`pages/index.vue`
```
<template>
  <b-steps v-model="activeStep">
    <step-item />
  </b-steps>
</template>

<script>
import StepItem from '~/components/StepItem';
export default {
  components: {
    StepItem,
  },
  data() {
    return {
      activeStep: 0,
    };
  },
};
</script>
```

`components/StepItem.vue`
```
<template>
  <b-step-item label="TestStep">
    Text Text
  </b-step-item>
</template>
```

Then access to `/`, error `You should wrap bStepItem on a bSteps` displayed.

### Expected behavior

`b-step-item` works correctly as below code.
(It works correctly)

`pages/index.vue`
```
<template>
  <b-steps v-model="activeStep">
      <b-step-item label="TestStep">
        Text Text
      </b-step-item>
  </b-steps>
</template>

<script>
export default {
  data() {
    return {
      activeStep: 0,
    };
  },
};
</script>
```

### Actual behavior

Error `You should wrap bStepItem on a bSteps` displayed.

It's because of [StepItem.vue L48](https://github.com/buefy/buefy/blob/dev/src/components/steps/StepItem.vue#L48).

```
    created() {
        if (!this.$parent.$data._isSteps) {
            this.$destroy()
            throw new Error('You should wrap bStepItem on a bSteps')
        }
        this.$parent.refreshSlots()
    },
```

I think it should check **not direct** parents.

**Comment by jtommy** [comment]
At the moment you can only create a component for each step item content but it's a common behaviour of all buefy sub items components
