### ISSUE TITLE
Customizable href for b-navbar-dropdown

### ISSUE THREAD

**Issue by ozgurg** [buefy/buefy#2477]
### Description

Customizable `href` (or `router-link`) for `<b-navbar-dropdown />`
Current `href` is `#`
I tried pass a method that contains `window.location.href ="..."` with `@click.prevent`, but it doesn't work.

### Why Buefy need this feature

I think dropdown lists should be clickable.

**Comment by jtommy** [comment]
Did you tried `@click.natve` ?

**Comment by ozgurg** [comment]
> Did you you tried `@click.natve` ?

Thank you, `@click.native` solved my issue for now but I still think this should be added.
