### ISSUE TITLE
Close prevention for Dialog component

### ISSUE THREAD

**Issue by denis-goncharenko** [buefy/buefy#2478]
### Description

It would be good to have a possibility to prevent closing dialog modal. For example, you would like to create a confirmation modal for delete action. In this dialog, you need to enter some word like 'DELETE' to confirm that you really want to delete a record.

![image](https://user-images.githubusercontent.com/52198869/80955126-58907980-8e07-11ea-91a7-0713a84660ee.png)

### Why Buefy need this feature

At the moment on onConfirm we can't prevent dialog closing if a user has entered the word that doesn't equal to 'DELETE'.

**Comment by fabiofdsantos** [comment]
Are you using `$buefy.dialog.prompt` with `canCancel` prop?

**Comment by jtommy** [comment]
Duplicated https://github.com/buefy/buefy/issues/1953
