### ISSUE TITLE
bug b-numberinput - controls

### ISSUE THREAD

**Issue by KonesoN** [buefy/buefy#2483]
controls="false" - not work

<b-field label="Small">
            <b-numberinput size="is-small" controls="false">
            </b-numberinput>
</b-field>

Test codepen: https://codepen.io/pen?&editable=true&editors=101=https%3A%2F%2Fbuefy.org%2Fdocumentation%2Fnumberinput

**Comment by jtommy** [comment]
It's a Boolean prop, you have to bind it : controls="false"

**Comment by KonesoN** [comment]
Oh, i dolbaeb, Thank you :)
