### ISSUE TITLE
Snackbar to stay open when the action button is pressed

### ISSUE THREAD

**Issue by bojko108** [buefy/buefy#2484]
### Description

Right now, the Snackbar component is closed after the action button is clicked. I'm working on an application in which the action button of the Snackbar needs to be pushed multiple times. The problem is that the first click closes the Snackbar. Would it be possible `onAction` method to return a boolean whether the snackbar should be closed or not? I'm thinking for something like this:
```js
// ...\src\components\snackbar\Snackbar.vue:
methods: {
   /**
    * Click listener.
    * Call action prop before closing (from Mixin).
    */
   action() {
      const stayOpen = this.onAction()
      if (!stayOpen) {
         this.close()
      }
   }
}
```
And in your component you can use it like this:
```js
this.snackbar = this.$buefy.snackbar.open({
   message: `Selected school is: ${payload.get('name')}`,
   type: 'is-warning',
   position: 'is-bottom',
   actionText: 'ZOOM TO',
   indefinite: true,
   onAction: () => {
      // some logic
      
      // return TRUE to leave the snakbar open 
      // or FALSE to close it:
      return true;
   },
});
```

### Why Buefy need this feature

This way, the Snackbar can stay open until the `close()` method is called or the duration expires. Existing applications will still work as expected as the default value for `stayOpen` is `false` so the Snackbar will stay open only if the result of `onAction()` is `true`.

**Comment by jtommy** [comment]
Same argument https://github.com/buefy/buefy/issues/1953
