### ISSUE TITLE
Box-shadow is missing on DateTime pickers

### ISSUE THREAD

**Issue by pinkplus** [buefy/buefy#2485]
### Overview of the problem

**Buefy** version: 0.8.17
**Vuejs** version: 2.6.11
**OS/Browser**: OS X Safari 13.1

### Description

The DateTime pickers don't have box-shadow, making them look a little different from normal inputs.

### Steps to reproduce

Check this codepen: https://codepen.io/yuxiaozeng/pen/xxwYoeX

![Screenshot](https://user-images.githubusercontent.com/1262758/81306803-df20b180-90ba-11ea-9d3d-df0876ab8a2b.png)
### Expected behavior

Datepicker should have the same box-shadow as normal input has.

### Actual behavior

Datepicker doesn't have box-shadow.

**Comment by jtommy** [comment]
@pinkplus because it's readonly then the shadow is disabled

**Comment by pinkplus** [comment]
@jtommy Right, the shadow is disabled because the input is readonly.

But my point is that, conceptually the datetime picker isn't readonly, so it shouldn't look like a "readonly input". Especially when we put the datetime picker in a form together with other normal inputs, the datetime picker would look different from other inputs. We are asking the user to provide values for all the inputs -- why should the datetime picker look like readonly?

**Comment by jtommy** [comment]
Because the input is read-only. 
I understand the issue I have to think how to "fix" it

**Comment by pinkplus** [comment]
I guess a straightforward way is to add a class and use the input shadow variables in Bulma?

    .datepicker-input {
        box-shadow: $input-shadow;

        &:focus,
        &.is-focused,
        &:active,
        &.is-active {
            box-shadow: $input-focus-box-shadow-size $input-focus-box-shadow-color
        }
    }

This looks working on my local machine.
