### ISSUE TITLE
Table: Once empty columns' header stay visible when hidden

### ISSUE THREAD

**Issue by dwhoop55** [buefy/buefy#2486]
### Overview of the problem
**Buefy** version: [0.8.17]
**Vuejs** version: [2.6.11]
**OS/Browser**: Chrome 81.0.4044.129, Safari 13.1, Firefox 76.0 (all latest on macOS 10.14.6)

### Description

The table component allow to dynamically hide and show columns via the `visible` property. This works as long as there is data in the table. As soon as the table is empty the reactivity of the column's header is gone. The columns are still hidden for the rows, but the header stays visible.

### Steps to reproduce

1. Have b-table with `data` and all columns visible
2. Replace b-table's `data` with `[]`
3. Give the table some `data` again
4. Hide a columns by setting `visible` `false` on the b-table-column
5. Row's columns are hidden, columns header still visible

Here is an example to click through: [Codepen](https://codepen.io/dwhoop55/pen/JjYLjwr)

### Expected behavior

The table column's header should be hidden

### Actual behavior

The table column's header is visible

#### I love buefy! Thank you everyone creating it!

**Comment by jtommy** [comment]
It will be fixed in the next breaking version 0.9.0 that as you can see in working in progress ;)
