### ISSUE TITLE
Buefy to work with vuejs/vite

### ISSUE THREAD

**Issue by ais-one** [buefy/buefy#2488]
### Description

Buefy to work with vuejs/vite, no bundler dev server. vite requires Vue 3 to work.

Refer to below issue and the vite repo

https://github.com/vuejs/vite/issues/83

### Why Buefy need this feature

Would be nice

**Comment by jtommy** [comment]
At the moment Buefy doesn't support Vue 3

**Comment by EyePulp** [comment]
Howdy;
I'm trying to get Buefy to work under a Vue 2 project running under Vite (which now supports vue 2).  If anyone's manged this (or knows 100% it can't work) I'd love to hear about it.

Thanks!

**Comment by wobsoriano** [comment]
any update @EyePulp ?

**Comment by EyePulp** [comment]
@wobsoriano Vite works fine with vue2 at this point, and thus, no special issues using buefy.  

**However --pay attention to which Vue version you're running:**

For Vue < v2.7 you need an [older vite plugin](https://github.com/underfin/vite-plugin-vue2)   

But if you're using vue 2.7, you can use the newer [official plugin](https://github.com/vitejs/vite-plugin-vue2).

**Comment by claide** [comment]
> @wobsoriano Vite works fine with vue2 at this point, and thus, no special issues using buefy.
> 
> **However --pay attention to which Vue version you're running:**
> 
> For Vue < v2.7 you need an [older vite plugin](https://github.com/underfin/vite-plugin-vue2)
> 
> But if you're using vue 2.7, you can use the newer [official plugin](https://github.com/vitejs/vite-plugin-vue2).

Is there a configuration that needs to be done when using buefy in laravel vite? 
I am currently switching from laravel mix to vite and some pages are using vue and buefy and I can't get it to work.
