### ISSUE TITLE
Allow 3 item array (year, month, day) as input for datepicker

### ISSUE THREAD

**Issue by pachiraDIG** [buefy/buefy#2490]
### Description

I have a use case where I have datepicking needs, but nothing to do with time or timezone at all. Using only a javascript date in the datepicker locks these in and is currently creating issues that I can't seem to solve.

For my case, the user selects a date, which naturally gets parsed into an ISO string with timezone like `'2021-04-15T00:00:00.000Z'`. This date gets sent to our Postgres database and comes back out in the same format. Once, it gets loaded on `created()` into the data v-modeled with the datepicker, the date (currently at this time of day) becomes `Wed Apr 14 2021 17:00:00 GMT-0700` -- a day behind. 

Any time a `new Date()` is created, there is an automatic UTC offset shift.

I'd like to suggest a simple 3 item array as a valid input for the v-model, `year`, `month`, and `day`.

### Why Buefy need this feature

I believe there must be many use cases like mine since it is a very simple problem.

Thanks.

**Comment by jtommy** [comment]
How do you get the date from API ? And how to convert it to date object?

**Comment by pachiraDIG** [comment]
I use `new Date()` to convert it, but only because it's required by the datepicker. I'd like to be able to parse it into an array.

**Comment by jtommy** [comment]
What do you mean? 
Can you reproduce an example?

**Comment by pachiraDIG** [comment]
I can but it's almost too simple of a problem:

1. User selects date.
2. V-modeled data reads:
`Thu Apr 15 2021 00:00:00 GMT-0700 (Mountain Standard Time)`
3. It gets parsed to ISOString for db storage:
`'2021-04-15T00:00:00.000Z'`
4. The string gets stored as Postgres data type, (which luckily comes back exactly the same).
5. Upon refresh, to load the ISO string as the current date in the datepicker, it must currently be done with: 
`new Date('2021-04-15T00:00:00.000Z')`, 
which outputs:
`Wed Apr 14 2021 17:00:00 GMT-0700 (Mountain Standard Time)`
So the datepicker is now displaying:
`'4/14/2021'`

The calculation is of course correct, when the time and timezone are factored in, but not for the date itself. I'm just thinking since this is a date (only) picker, it should be able to work outside the bounds of javascript dates.

**Comment by jtommy** [comment]
Are you using Date.parse to get Date Object ? Btw you can customize date formatter in order to fix your need.
