### ISSUE TITLE
wrong target on b-button click event

### ISSUE THREAD

**Issue by frankpuppa** [buefy/buefy#2494]
### Overview of the problem

**Buefy** version: [0.8.17]
**Vuejs** version: [2.5.2]
**OS/Browser**: google chrome

### Description
wrong event target passed to the function handler when using b-button component

### Steps to reproduce
simple example to copy and paste on code pen:
```javascript
<div id="app" class="container">
    <section>
        <div class="buttons">
            <b-button class="button is-medium is-primary" @click="alert($event)">
                Launch alert (default)
            </b-button>
        </div>
    </section>
</div>

const example = {
    methods: {
        alert(event) {
          console.log(event.target)
        },
    }
}

const app = new Vue(example)
app.$mount('#app')
```

### Expected behavior
In my opinion, the target should always be:
```
<button type="button" class="button button is-medium is-primary"></button>
```
since the event should be attached to the button. However, when clicking on the text inside the button, the target becomes :
```
<span>
Launch alert (default)
</span>
```
Works fine using <button> instead of <b-button>

**Comment by jtommy** [comment]
The component is dinamic and it attach the event on tag element
