### ISSUE TITLE
b-datepicker only allows selecting 3 years from selected year

### ISSUE THREAD

**Issue by serge1peshcoff** [buefy/buefy#2496]
### Overview of the problem

**Buefy** version: latest (can reproduce on your website)
**Vuejs** version: [X.X.X]
**OS/Browser**: Mac OS, Firefox/Opera

### Description

When selecting a year in datepicker, the year range goes from the current year to 3 years from now, and there's no way to select later years. I can reproduce it on my project but also I can reproduce it on your website so it doesn't seems like something my changes were affecting something. I can select later dates by selecting the last year multiple times (e.g. from 1970 -> 1973 -> 1976 -> 1979 etc.), but this is kinda annoying.

Not sure if that's OS-specific (I use Mac OS 10.14.x) but I can reproduce it both in Opera and Firefox (so shouldn't be browser-specific).

Can this be fixed/customized or this is done by design?

### Steps to reproduce

1) Go to https://buefy.org/documentation/datepicker/
2) Try to open a year selector

### Expected behavior
I am allowed to select dates later than 3 years from selected year

### Actual behavior
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1060257/81547431-82581c00-9384-11ea-81d5-79e13f82a543.png">

I can only select 3 years from the selected year (on the screenshot, the year previously selected was 2026, and I cannot select years later than 2029).

**Comment by Leffe108** [comment]
The component have a `years-range` property that allow you to configure the year range that should be visible.

The useful range depends on the type of application you create, so it is understandable that the defaults won't fit everyone.

**Comment by jtommy** [comment]
Thanks @Leffe108 for the support ;)

**Comment by serge1peshcoff** [comment]
I was going to mention it's not documented and it actually is, so my fault for not noticing it. Sorry :<
And thanks for the fast response!
