### ISSUE TITLE
[Tabs] Active tab: use an id rather than an index

### ISSUE THREAD

**Issue by Tofandel** [buefy/buefy#2498]
Related https://github.com/buefy/buefy/issues/1026, https://github.com/buefy/buefy/issues/2211

## Step to reproduce
1. Go to the [documentation for tabs](https://buefy.org/documentation/tabs#dynamic)
2. Click on the Video tab
3. Hide the Music item
4. Notice how the Tab changed from Video to Games

## Proposed solution
Using an unique id for each tab (Could be user defined since we need a unique id for the :key of the tab element anyways or automatically use the vue id of the element) in the v-model rather than the index position of the tab would make a lot more sense and solve a lot of problems I think

Backward compatibility could be partially kept by checking if the value passed is a number, and if it is then change it to the id of the vue component

Or fully kept by externally exposing the index, but internally using the id of the components so that when a rerender occurs because tabs where added or reordered, the index v-model can be updated to the correct value

**Comment by jtommy** [comment]
You are right, i'm going to add an Id prop on tab item
