### ISSUE TITLE
Display database entries in table

### ISSUE THREAD

**Issue by Kazuto** [buefy/buefy#250]
### Overview of the problem

**Buefy** version: [5.0]
**Vuejs** version: Don't know
**OS/Browser**: Chrome

### Description

I want display content from my database. I'm using laravel but I can't figure out how to display it properly. It shows everything in one large <tr>.

    <template scope="props">
    @foreach ($posts as $post)
    <b-table-column field="id" label="ID" width="40" sortable numeric>
        @{{ props.row.id }} {{ $post->id }}
    </b-table-column>

    <b-table-column field="{{ $post->title }}" label="Titel" sortable>
        @{{ props.row.title }} {{ $post->title }}
    </b-table-column>

    <b-table-column field="post.text" label="Inhalt" sortable>
        @{{ props.row.text }} {{ substr($post->text, 0, 200) }}{{ strlen($post->text) > 200 ? " ..." : "" }}
    </b-table-column>

    <b-table-column field="date" label="Datum" sortable centered>
        @{{ props.row.date }} {{$post->created_at->toFormattedDateString()}}
    </b-table-column>
    </template>

**Comment by rafaelpimpa** [comment]
> It shows everything in one large .

What you mean with that? Explain better what's happening please.

**Comment by sbtali** [comment]
please answer to this question, ho to use `foreach` in buefy table?
I want to get data from database in laravel and show it in my view, but can't.

**Comment by jtommy** [comment]
@sbtali You have to set data prop that is an array of objects
