### ISSUE TITLE
Search input scoped slot and custom template

### ISSUE THREAD

**Issue by andresespinosapc** [buefy/buefy#2503]
### Overview of the problem

**Buefy** version: [0.8.15]
**Vuejs** version: [2.6.11]
**OS/Browser**: Google Chrome

### Description

When using a custom template, custom search input is not working.

### Steps to reproduce

1. Create a b-table using custom template instead of the columns prop.
2. Set at least one input as searchable.
3. Add a search input with slot prop set to `searchable`, as shown in the documentation: https://buefy.org/documentation/table/#searchable

### Expected behavior

The search inputs should look like the one defined in step 3.

### Actual behavior

The search input looks like the default search input.

**Comment by jtommy** [comment]
Can you provide a codepen or similar?
