### ISSUE TITLE
Select multiple dates without jumping between months

### ISSUE THREAD

**Issue by iwasherefirst2** [buefy/buefy#2506]
### Description

In #1865 a feature has been added to allow adding multiple dates. 

However, when one selects a date of another months, the calender will jump back to the current month. 

I think it would be a nice feature, if the window does not jump back.

### Why Buefy need this feature

Imagine for example we have May 2020 and one wants to add 4 dates for May, June, November and December. One would do the following:

1. select date in May
2.  then go to June
3. select date 
4. Window jumps back to May,
5. Click to June,July,August,October,November
6. select date 
7- Window jumps back to May
8.  Click to June,July,August,October,November, December
9. select date
10 window jumps to may

Would be much easier without the jumping.

**Comment by jtommy** [comment]
@iwasherefirst2 you can avoid it setting focusedDate prop

**Comment by iwasherefirst2** [comment]
@jtommy thank you good hint.

I solved it like this:

```
<b-datepicker
       placeholder="Click to select..."
       v-model="dates"
       :focused-date = 'currentDate'
       multiple>
</b-datepicker>
```

```
computed:{
   currentDate() {
        if (typeof this.dates !== 'undefined' && this.dates.length > 0) {
            return this.dates[this.dates.length -1];
        }
        return new Date();
   }
}
```
