### ISSUE TITLE
Search filtering is lost after updating table data

### ISSUE THREAD

**Issue by VictorCazanave** [buefy/buefy#2509]
### Overview of the problem

**Buefy** version: 0.8.18
**Vuejs** version: 2.6.11
**OS/Browser**: All

### Description

After updating the data of the table, the filters are not applied on the new data.

### Steps to reproduce

1. Go to the [codesandbox demo](https://codesandbox.io/s/buefy-table-searchable-bug-7hpj5)
2. Filter the `Name` column (for example: type "J" to display only "Jesse" and "John")
3. Click on the `Refresh data` button (it just re-assigns `data`)
4. The filter is not applied anymore

### Expected behavior

I think the filters should be applied on the refreshed data.

### Actual behavior

The filters are not applied on the refreshed data.

I think I've found how to fix it, then I'll be glad to open a PR if needed.

**Comment by jtommy** [comment]
Sure, open a PR!
