### ISSUE TITLE
Not able to close notification programmatically

### ISSUE THREAD

**Issue by 30Capri-gif** [buefy/buefy#2510]
### Overview of the problem

**Buefy** version: ^[0.8.10]
**Vuejs** version:^ [2.6.10]
**OS/Browser**: Windows/Chrome

Not able to close notification programmatically

### Description
I am trying to close b-notification when some event is triggered. I have tried it doing **this.$buefy.notification.close({});**, but it is throwing me an error that it is not a function. 

I have read the documentation, but it doesn't say how to close it without clicking on the close icon. 
Is there something that I am doing wrong??

Code for reference:
```
watch:{
    updateCompleted: function(newval, oldval){
         if(newval){
            this.$buefy.toast.open({
                    message:"File Updated Successfully",
                    type:"is-success"
                });
            this.$buefy.notification.close({});
            
        }
    }
}
```

**Comment by jtommy** [comment]
@30Capri-gif you have to call `close` on the instance of toast:
```
const t = this.$buefy.toast.open({
                    message:"File Updated Successfully",
                    type:"is-success"
                });
           t.close();
```

**Comment by 30Capri-gif** [comment]
@jtommy  I dont want to close the toast. I have a notification that is shown when i land into the page and i need to close that notification and show a toast message. Is there a way we can reference that notification and close it ?

**Comment by jtommy** [comment]
In the same way if you opened it programmatically

**Comment by 30Capri-gif** [comment]
@jtommy i am not opening it programmatically., since there are a lot of customizations

**Comment by jtommy** [comment]
Plese share your code about notification

**Comment by 30Capri-gif** [comment]
This is my HTML. I want to display my notification in a particular way and place.
```
<template>
<div class="se-hoops--outofdate-notification">
     <div class="se-hoops--outofdate-notification--side" v-if="isMobile"></div>
     <div class="outofdate-notification">
           <b-notification type="is-white" :closable="false">
                <div :class="[updateInProgress ? 'notification--text-inprogress': 'notification--text-update']"> {{getNotificationText}} </div>
               <button v-if="!updateInProgress" class="button is-white is-small" @click="emitUpdate">UPDATE </button>
          </b-notification>
     </div>
     <div class="se-hoops--outofdate-notification--side" v-if="isMobile"></div>
</div
</template>
```
This is how am trying to close it. The watch is on a prop being passed from the parent component.

```
watch:{
    updateCompleted: function(newval, oldval){
        if(newval){
            this.$buefy.toast.open({
                    message:"File Updated Successfully",
                    type:"is-success"
                });
            this.$buefy.notification.close({});
            
        }
    }
},
```
In case I open up the Notification programmatically, will I be able to customize it?

**Comment by jtommy** [comment]
It doesn't make sense, Buefy doesn't store all notifications components rendered and in your case it isnt programmatic.
You can do it with a bus event or a centralized store (vuex) or other.
Please use Discord for this kind of question, thanks ;)
