### ISSUE TITLE
Change cursor style from "text" to "pointer" for non-editable datepicker

### ISSUE THREAD

**Issue by Lukasiniho** [buefy/buefy#2513]
### Overview of the problem

**Buefy** version: 0.8.17
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 81.0.4044.138 on Windows 10 

### Description

The cursor style for a non-editable datepicker component is "text". Since the user cannot edit the text in a non-editable datepicker, it would make more sense to change the cursor style to "pointer" in this scenario. I've received questions from my users as to why the mouse shows the text cursor style instead of the pointer. Additionally, since the non-editable datepicker actually opens a dropdown on click, adding a pointer style makes it more consistent with other dropdowns in Buefy (which all default to cursor style pointer). 

### Steps to reproduce

Use datepicker without editable prop and look at the cursor style.

### Expected behavior

The cursor style is "pointer"

### Actual behavior

The cursor style is "text"

**Comment by jtommy** [comment]
@Lukasiniho yes you're right, i'm adding it
