### ISSUE TITLE
Radio Button spacing issue in v0.8.18

### ISSUE THREAD

**Issue by adambiggs** [buefy/buefy#2514]
### Overview of the problem

**Buefy** version: 0.8.18
**Vuejs** version: 2.6.11
**OS/Browser**: Mac/Chrome

### Description

Before v0.8.18 radio buttons looked like this:
<img width="125" alt="Screen Shot 2020-05-15 at 11 47 43 AM" src="https://user-images.githubusercontent.com/857229/82085698-3ff34f80-96a2-11ea-949f-3b8cd662ac54.png">

But after updating to v0.8.18 there's now a weird looking gap between radio buttons:
<img width="150" alt="Screen Shot 2020-05-15 at 11 45 16 AM" src="https://user-images.githubusercontent.com/857229/82085798-61ecd200-96a2-11ea-9a4a-3788dc75d536.png">

[This can also be seen in the documentation](https://buefy.org/documentation/radio#radio-button).

**Comment by jtommy** [comment]
Yes, It's no correct
