### ISSUE TITLE
Ability to change tag for tooltip (use-case: ABBR with title tag)

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#2517]
### Description

I like making A11y web pages and this goes by choosing the right tags for the right content.
I needed the tooltip to explain a word, but realised the tooltip component had a span as root component. It would be nice to choose the root component, because in my case, to be A11y and semantic friendly, I need a **abbr** HTML tag.

### Why Buefy need this feature

Well, having components where markup can be chosen despite the look and feel, is part of Bulma's philosophy. Also, the best components are the ones that are the most flexible.

**Comment by jtommy** [comment]
@darkylmnx can you explain better your need ? why `abbr` ?

**Comment by darkylmnx** [comment]
As I said in my example, I'm adding a tooltip where it has ton explain an
abbreviated word.

The feature though is to be able to chose any kind of tag, because to day
my need is abbr, tomorrow it would be STRONG, EM or even SMALL HTML tag for
example.

Le dim. 17 mai 2020 à 09:54, Walter Tommasi <notifications@github.com> a
écrit :
