### ISSUE TITLE
Autocomplete will not open after getting focus upon clearing

### ISSUE THREAD

**Issue by lojza3d** [buefy/buefy#2518]
### Overview of the problem

**Buefy** version: [0.8.18]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS Mojave 10.14.6, Firefox 76.0.1, Safari 13.1, Google Chrome 81.0.4044.138.

### Description

The Autocomplete control will not open the option list when cleared with the clear button.

### Steps to reproduce

1. Use props **open-on-focus** together with **clearable** at an Autocomplete control.
2. Click to the field -> options will open.
3. Select an option or enter any text.
4. Click outside and use the clear button.
5. The field is cleared and gets focus, but the list of option is not displayed.

### Expected behavior

When clearing the field with the clear button, the field should get focus and display list of options if there's **open-on-focus** prop used.

### Actual behavior

When clearing the field with the clear button, the field will get focus, but won't display the list of options even if there's **open-on-focus** prop used.

**Comment by Lukasiniho** [comment]
I have the exact same issue!

**Comment by jtommy** [comment]
I'll take a look soon

**Comment by RonnyTod** [comment]
It`s not working still

Link: https://codesandbox.io/s/competent-archimedes-yko25?file=/src/components/HelloWorld.vue

**Comment by CobraClutch** [comment]
I'm also unable to get the autocomplete to re-open after clearing.
