### ISSUE TITLE
Change modal background(mask) color

### ISSUE THREAD

**Issue by asajadian** [buefy/buefy#2519]
### Description

It would be very continent if it was possible to set the modal background color. I find the default color too dark. Actually I was surprised it I can not do it, or can I? I'm just trying Buefy.

### Why Buefy need this feature

The default background color is too dark, different designs might need different opacities.

**Comment by jtommy** [comment]
@asajadian for each component I added a link to bulma docs, in your case https://bulma.io/documentation/components/modal/#variables

**Comment by FuckAnyProblem** [comment]
> @asajadian for each component I added a link to bulma docs, in your case https://bulma.io/documentation/components/modal/#variables

Hi, I'm just trying frame like Buefy, I don't know how to change the variable, could you tell how to use it?
