### ISSUE TITLE
MDI icons not available

### ISSUE THREAD

**Issue by albertovincenzi** [buefy/buefy#2522]
### Overview of the problem

**Buefy** version: [0.8.19]

### Description
I'm not able to use mdi icons. If I inspect the code, I see the `<i>` tag with the following classes:
`mdi mdi-mdi-check`

This is the snippet of the code:
`<b-icon icon="mdi-check"></b-icon>`

Of course, if I remove mdi- I'm able to see the icon.

**Comment by jtommy** [comment]
Yes you haven't add prefix mdi
