### ISSUE TITLE
Filters-change event in table doesn't work

### ISSUE THREAD

**Issue by jkbgntr94** [buefy/buefy#2524]
#Overview of the problem

**Buefy** version: [0.8.18]
**Vuejs** version: [2.6.10]
**OS/Browser**:  Firefox 76.0.1 (64-bit)

### Description

If i understand table filtering correctly, the filters-change event doesn't work. I've tested same scenario with sort event and everithing works as expected. If i only don't tho things in right way. It would be awesome if you can add some example of this to documentation. It would be greate if there is some way for access filter values too. Now there is no way how to reset filters with one button or on some action. Thank you so much. 

### Steps to reproduce

1. Open codepen with Searchable table (from documentation)
2. Add @filters-change="console.log('search')" to table
3. Type into filter input

### Expected behavior
Word 'Search' written in console

### Actual behavior

Nothing happend

**Comment by akicho8** [comment]
`console.log` and `alert` is, to be inconvenient, it seems can not be used directly.

`@filters-change="$buefy.toast.open('search')"`

Please try to change as above

**Comment by jkbgntr94** [comment]
I used console.log only for simplicity, i've tested it with calling my own method. I tried your approach in Searchable codepen from documentation and it does not work. When i do same with @sort on sortable table, everithing works as expected.

```
<b-table
            :data="data"
            @filters-change="$buefy.toast.open('search')"
            :columns="columns">
        </b-table>
```

**Comment by akicho8** [comment]
If look at the source code, filters-change event is called is just like when **backend-filtering is true**.

```
<b-table
  backend-filtering
  :data="data"
  @filters-change="$buefy.toast.open('search')"
  :columns="columns">
</b-table>
```

**Comment by jkbgntr94** [comment]
Thanks so much, now it works. 
It would be great to add this to documentation. 
Why can't be filter-change triggered even with client filtering (without backend-filtering option).
Is this really expected behaviour or it's a bug?

**Comment by akicho8** [comment]
I do not understand with respect to part of the design of the development.
However, I've found that there are other events.
Maybe, you might be able to substitute in this event.

https://github.com/buefy/buefy/blob/4cd31b1613358fe6cbd07ea9a96e3d749a3c75c4/src/components/table/Table.vue#L213

**Comment by alexsobolenko** [comment]
Hello everyone. I have the same issue in my project.

**Buefy version:** [0.9.2]
**Vuejs version:** [2.6.10]

```
<b-table
    :data="products"
    :per-page="perPage"
    :total="total"
    :current-page.sync="currentPage"
    :loading="loading"
    default-sort="name"
    sort-icon="sort-up"
    backend-filtering
    backend-pagination
    backend-sorting
    paginated
    narrowed
    hoverable
    @page-change="onPageChange"
    @sort="onSort"
    @filters-change="onFiltersChange"
>
...
</b-table>
```
`onPageChange` and `onSort` all works correctly, but not `onFiltersChange`.
I use `console.warn`, but I had not see any messages in console when I typed text into search input
```
onFiltersChange(filter) {
    console.warn('filter', filter);
},
```

**Comment by jtommy** [comment]
@alexsobolenko can you share your code in codepen?

**Comment by alexsobolenko** [comment]
@jtommy no, I can't. I can't share my job project. Meanwhile I am having difficulty implementing a similar situation in codepen

**Comment by alexsobolenko** [comment]
@jtommy I apologize for the time wasted. I cleared cache, updated buefy to 0.9.3. Filtering worked now :thumbsup:

**Comment by mcmule** [comment]
There's actually no answer from the devs regarding jkbgntr94's question, would it be possible to have one?

The question:
> Why can't be filter-change triggered even with client filtering (without backend-filtering option).
Is this really expected behaviour or it's a bug?

I need filters-change to be emitted, with client filtering, not backend. In its current state, the doc does tell me I can, even though I can't. 
So, is the doc wrong ? Or is this a bug, and filters-changed should be emitted with basic client filtering?

Thanks!
