### ISSUE TITLE
The size of the grouped inputs jumps when there is an error

### ISSUE THREAD

**Issue by FlorianChretien** [buefy/buefy#2527]
Hello !

I noticed that the grouped inputs change size when there is an error (with emails for example). In a modal that a little annoying. In gif an example : https://gyazo.com/a3249e28b03605e77239b5355db9558f

Thanks for your help !
Have a good day

**Comment by jtommy** [comment]
@FlorianChretien you can set a fixed width using `custom-class` or `withd` props
