### ISSUE TITLE
No sorting icons when using backend-sorting

### ISSUE THREAD

**Issue by luixal** [buefy/buefy#2533]
### Overview of the problem

Sorting icons not showing when using `backend-sorting` option.

**Buefy** version: [0.8.19]
**Vuejs** version: [2.6.11]
**MaterialDesignIcons** version: [5.2.45]
**OS/Browser**: Chrome 81.0.4044.138 (Build oficial) (64 bits) / Firefox 68.8.0esr (64-bit)

### Description

When using `backend-sorting` option in `b-table` component, sorting icons are not showing.

### Steps to reproduce

1. Get a working `b-table` (in my case, getting data from a server correctly)
2. Add the `backend-pagination` param to the tag.
3. Click on a column to sort

### Expected behavior

Sorting icon showing in column header.

### Actual behavior

No icon shown.

**Comment by jtommy** [comment]
@luixal can you reproduce it on codepen or similar?

**Comment by luixal** [comment]
Sure!

Here's the pen: https://codepen.io/luixal/pen/gOaqZNM

I just started out from the [Async Data example in b-table documentation](https://buefy.org/documentation/table/#async-data) and change the `b-table` tag params by adding:

```html
  bordered
  narrowed
  hoverable
  mobile-cards
  sort-multiple
```
so it looks like this:

```html
<b-table
  :data="data"
  :loading="loading"
  bordered
  narrowed
  hoverable
  mobile-cards

  paginated
  backend-pagination
  :total="total"
  :per-page="perPage"
  @page-change="onPageChange"
  aria-next-label="Next page"
  aria-previous-label="Previous page"
  aria-page-label="Page"
  aria-current-label="Current page"

  backend-sorting
  sort-multiple
  :default-sort-direction="defaultSortOrder"
  :default-sort="[sortField, sortOrder]"
  @sort="onSort">
```
As this, sorting icons are not shown but, if I remove `backed-sorting` or `sort-multiple`, they're back. So, maybe this is not only related to `backend-sorting`.

**Comment by jtommy** [comment]
@luixal have you already see this example ? https://buefy.org/documentation/table#sorting-multiple

**Comment by luixal** [comment]
Commenting just for making this useful for someone getting here:

The example linked by @jtommy is the one to follow when you want multiple sorting while fetching data from a backend service.

You have to use `backend-sorting` and `sort-multiple` params along with `@sort` and `@sorting-priority-removed` callbacks. Code from the example works like a charm :)

For me, it was a bit weird: i just wanted multiple sorting so I guessed I would get multiple `{field, order}` on the @sort event every time sorting was updated. This solution feels a little _boilerplate_ if don't need anything "custom".

Thanks @jtommy !

**Comment by jtommy** [comment]
Yes probably you are right, I'll take a look for the next breaking version
