### ISSUE TITLE
[Vue warn] Invalid prop: type check failed for prop "value". Expected Date, Array, got Date 

### ISSUE THREAD

**Issue by orafaelreis** [buefy/buefy#2536]
### Overview of the problem

**Buefy** version: 0.8.19
**Nuxt** version: 2.12.2
**OS/Browser**: Mac OS Catalina (10.15.4)

### Description
the Chrome Console shows 3 errors:

* [Vue warn]: Invalid prop: type check failed for prop "value". Expected Date, Array, got Date 
* [Vue warn]: Invalid prop: type check failed for prop "value". Expected Date, Array, got Date 
* [Vue warn]: Invalid prop: type check failed for prop "selectedDate". Expected Date, Array, got Date 

the stack shows each one of this error were found in ---> <BDatepicker>

### Steps to reproduce

1. Create a vue file with this code:

```
<template>
  <div>
    <form>
      <b-field label="Data Criação" horizontal>
        <b-datepicker
          v-model="form.created_date"
          placeholder="Clique para selecionar..."
          icon="calendar-today"
        />
      </b-field>
    </form>
  </div>
</template>
<script>
export default {
  name: 'Form',
  data () {
    return {
      form: this.getClearFormObject(),
    }
  },
  methods: {
    getClearFormObject () {
      return {
        id: null,
        title: null,
        text: null,
        created_date: new Date(),
        date: null,
      }
    },
  }
}
</script>
```
2. Open Chrome Console and See the errors ```found in ---> <BDatepicker>```

### Expected behavior
No Errors

### Actual behavior
See the Description section above

**Comment by jtommy** [comment]
Are you using Nuxt ?

**Comment by rafaelreis-hotmart** [comment]
Yes, I am.

**Comment by orafaelreis** [comment]
Yes, I am.

**Comment by jtommy** [comment]
https://github.com/buefy/nuxt-buefy/issues/36

**Comment by tutuca** [comment]
I'm not using nuxt and I'm facing this exact same issue. Most of my dates are already proper Date objects and I get no indication which is failing still...

I'll try to get it cornered into a reproducible case (too much code to trim down). But I get that it's not the same case as the nuxt one.
