### ISSUE TITLE
Why aria attributes have no default values in Buefy?

### ISSUE THREAD

**Issue by Juneezee** [buefy/buefy#2537]
### Description

Take the pagination
![image](https://user-images.githubusercontent.com/20135478/82667050-fcaf5880-9c2e-11ea-9231-43512f2b85c6.png)

and tag component for example,
![image](https://user-images.githubusercontent.com/20135478/82667248-5ca5ff00-9c2f-11ea-99df-fdfb631b7a4c.png)

Is there any particular reason that the aria labels are not set by default in Buefy?

### Why Buefy need this feature

Improve accessibility for screen readers

**Comment by jtommy** [comment]
@Juneezee To be honest there isn't a reason, do you prefer to see a default value ?

**Comment by Juneezee** [comment]
@jtommy Considering that Buefy is currently used by ~10.7k repositories and more, I think there is no harm in setting the aria attributes by default. In addition, it improves the accessibility of Buefy components too.

**Comment by service-paradis** [comment]
It could be a breaking change though. There are probably a lot of the 10.7k repository that are not in english. Buefy is (not entirely) kind of langage agnostic right now. It would need to have some way to change those easily (maybe as constructor options).

**Comment by wesdevpro** [comment]
Hello, from three years in the future 🤣 Does anyone know if I should just close this PR or should this still be a goal for Buefy v2?
@jtommy @service-paradis @kikuomax @wesdevpro
