### ISSUE TITLE
Making axios call or a get/post call on onConfirm in buefy dialog

### ISSUE THREAD

**Issue by pradeep-017** [buefy/buefy#2541]
Hi Team,
I was trying to submit a form in my project and am using dialog to let user confirm. I am using Dialog and wanted to make a post call on OnConfirm of Dialog. 
Sorry to place this as a feature request because I am not sure if we could actually do it this way. Any other approach would surely be appreciated. And yes I want the toast working too. Thats so cool.
Thanks in advance.
`<script>
Vue.config.devtools = true;

  var app = new Vue({
    el: '#app',
    data: {
     ....
    },
    methods: {
        go_to_item(item) {
          window.location.href = "/item/" + item.id 
        },
        confirmBid() {
            this.$buefy.dialog.confirm({
                title: 'Confirm Your Bid',
                message: `Bid Amount: <b>INR ${this.userBidValue} </b> <br>
                	To submit this bid, click the Submit Bid button.` ,
                
                confirmText: 'Submit Bid',
 
                onConfirm: (item) => {
                	const formData = new FormData();
                	formData.append('itemId', item.id);
                	formData.append('amount', userBidValue);
                	
                	axios.post('/bid/save', formData)
                		.then(response => {
                			this.posts = response.data
                			this.$buefy.toast.open('Bid Placed Successfully!')
                	    })
                	    .catch(e => {
                	      this.errors.push(e)
                	    })
                		console.log(error.toJSON());         	
                }
            })
        }
    }
   
  })
</script>
`

**Comment by jtommy** [comment]
I don't understand what do you need

**Comment by pradeep-017** [comment]
On click of confirm button in Buefy dialog, I want to make a post call with few parameters (like itemId, amount here) to my Springboot backend and if its successful I would toast with some message.
So how can I make a post call on click of confirm button in the dialog?

**Comment by jtommy** [comment]
You have to call a your method or add your code into onConfirm code
