### ISSUE TITLE
export 'BuefyProgrammatic' was not found in 'buefy'

### ISSUE THREAD

**Issue by Stetzon** [buefy/buefy#2544]
### Overview of the problem

**Buefy** version: [0.8.19]
**Vuejs** version: [2.6.11]
**OS/Browser**: OSX 10.13.6 / Chrome 81.0.4044.138

### Description

I am importing Buefy components individually to reduce bundle size.  Initially I was importing the full bundle:

```
import Buefy from 'buefy';
Vue.use(Buefy);
```

No drama there.  I also am using the `FontAwesome` components for icons.  I had this working like so:

```
Vue.use(Buefy, {
  defaultIconComponent: FontAwesome,
});
```

However, my new approach of importing all of the components individually, I am trying to set the same constructor options to use the `FontAwesome` component.  Following the [Individual Components instructions](https://buefy.org/documentation/constructor-options/) I am attempting to do:

```
import { BuefyProgrammatic } from 'buefy';

Vue.use(BuefyProgrammatic, {
    defaultIconComponent: FontAwesome,
});
```

However, I am getting the error:

`"export 'BuefyProgrammatic' was not found in 'buefy'`

during the build process.

### Steps to reproduce

1.  Follow the [constructor options instructions](https://buefy.org/documentation/constructor-options/) to import Buefy components individually.
2.  Attempt to import the `BuefyProgrammatic` component

### Expected behavior

The BuefyProgrammatic component should be imported.  Options should be set.

### Actual behavior

`"export 'BuefyProgrammatic' was not found in 'buefy'`

**Comment by jtommy** [comment]
Are you sure to use last version?

**Comment by Stetzon** [comment]
@jtommy just updated to latest v0.8.19, same issue.  Updated above

**Comment by jtommy** [comment]
Strange, try to clean npm canche and download it again

**Comment by Stetzon** [comment]
```
mbp:frontend stetzon$ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
mbp:frontend stetzon$ npm uninstall buefy; npm i buefy;
removed 2 packages and audited 1369 packages in 12.081s

44 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
+ buefy@0.8.19
added 2 packages from 2 contributors and audited 1371 packages in 15.358s

44 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
mbp:frontend stetzon$
```

same issue.  For reference, here is my `main.js`

```
import Vue from 'vue';

import {
  Field,
  Input,
  Select,
  Navbar,
  Button,
  Snackbar,
  Toast,
  BuefyProgrammatic,
} from 'buefy';

import App from './views/App.vue';
import router from './router';
import store from './store';

import './styles/_index.scss';

import FontAwesome from './lib/font-awesome';
Vue.component('font-awesome-icon', FontAwesome);

Vue.use(Field);
Vue.use(Input);
Vue.use(Select);
Vue.use(Navbar);
Vue.use(Button);
Vue.use(Snackbar);
Vue.use(Toast);
Vue.use(BuefyProgrammatic, {
  defaultIconComponent: FontAwesome,
});

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount('#app');
```

**Comment by jtommy** [comment]
Oh it's my fault.. 
```
import { ConfigProgrammatic } from 'buefy';

ConfigProgrammatic.setOptions({ ... })
```

**Comment by Stetzon** [comment]
Excellent! 

One thing to note, in order to get the FontAwesome component to work, I had to also include the `defaultIconPack` option:

```
ConfigProgrammatic.setOptions({
  defaultIconPack: 'far',
  defaultIconComponent: FontAwesome,
});
```

Thank you for the prompt responses. Appreciate your work on Buefy.
