### ISSUE TITLE
Move span file name in b-upload element?

### ISSUE THREAD

**Issue by iwasherefirst2** [buefy/buefy#2548]
### Description & Why Buefy need this feature

Currently, its recommended to put the file name in a `span` after the `b-upload` element. What is the reason behind it?

I noticed, that when use a `b-field` of class `column` + a `label` this creates a jump if one selects an image:
![image](https://user-images.githubusercontent.com/1765602/82784759-79297d80-9e61-11ea-913c-c738e72ca446.png)

![image](https://user-images.githubusercontent.com/1765602/82784783-834b7c00-9e61-11ea-9de3-2950a38dc11c.png)

This can be prevented if the span is moved in the `b-upload` element:

```
<b-field class="file column" label="Upload">
        <b-upload v-model="file">
            <a class="button is-primary">
                <b-icon icon="upload"></b-icon>
                <span>Click to upload</span>
            </a>
            <span class="file-name" v-if="file">
               {{ file.name }}
            </span>
        </b-upload>
    </b-field>
```

Should this be the default recommendation in the docs? 

Here is a codepan: https://codepen.io/iwasherefirst2/pen/dyYLYrZ

**Comment by jtommy** [comment]
@iwasherefirst2 it's only an example, in your case try to add a `b-field` into the current `b-field`
