### ISSUE TITLE
Is there any built in way to handle menu overflow in a navbar?

### ISSUE THREAD

**Issue by NickeManarin** [buefy/buefy#2550]
I'm having an issue when dealing with localization and the navbar menu items.

When using English, the navbar items (`nav-start` and `nav-end`)  fit nicely within the navbar and the navbar itself collapses into the hamburger menu when in the tablet or mobile breakpoints are hit.

    Left: BRAND + (menu items) + ('More' dropdown)
    Right: Language selector + Button

The problem starts when I switch to other languages, which have bigger words, causing the `nav-end` elements to bleed to the right of the page.

Is there any built in solution or workaround for this kind of problem?

(Automatically collapse to dropdown when no space left in `nav-start`)

**Comment by service-paradis** [comment]
Do you have the same problem using Bulma only?
Are you able to create a codepen where we can see the issue?

**Comment by NickeManarin** [comment]
> Do you have the same problem using Bulma only?
I haven't checked it.

> Are you able to create a codepen where we can see the issue?
Well, I have the website where I'm having the issue, but I ended adding a "hack" to try fixing that issue.

1. Visit: https://www.screentogif.com/downloads
2. Resize the browser window (or press F12 to open the dev tools to the side) until it almost reaches the touch breakpoint.
3. Using the language selector, switch to "PT - Portuguese".
4. Notice that the elements will bleed to the right of the viewport.
5. Resize the window 1px to the side.
6. Notice that the elements will be adjusted to fit (this is my hack).

My hack works when the overflow is detected when resizing the window. A navbar-item will be displayed in the "more" dropdown.

Here's the source of the website:
https://github.com/NickeManarin/ScreenToGif-Website/blob/master/src/components/Navigation.vue#L337

**Comment by NickeManarin** [comment]
Any news?
