### ISSUE TITLE
The Project cannot be built after overriding customize variables in Buefy Steps

### ISSUE THREAD

**Issue by thanapeace** [buefy/buefy#2552]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [3.1.3]

### Description
Project cannot be built when overriding customize variables in Buefy Steps. On the other hand, you delete those lines the project can be built normally.

![Capture2](https://user-images.githubusercontent.com/40425493/82895465-753f4d80-9f7e-11ea-8e26-526e35170efd.JPG)

### Expected behavior
There is no error and project can be completely built.

### Actual behavior
The errors show declare warning and lexical error after `npm run build`.

![1](https://user-images.githubusercontent.com/40425493/82895254-1e397880-9f7e-11ea-9cdc-882704deeaf3.JPG)
![Capture](https://user-images.githubusercontent.com/40425493/82895333-41fcbe80-9f7e-11ea-9d1d-dba1fbaef14d.JPG)

**Comment by jtommy** [comment]
1rem - #.. ?

**Comment by thanapeace** [comment]
@jtommy I don't know, this line isn't my code. I guess it came from Buefy repository.... I'm not sure yet.

**Comment by jtommy** [comment]
Can you share something?

**Comment by service-paradis** [comment]
There is an error in your variables definition. `$steps-divider-height` is supposed to be a size (default is `.2em`). You defined it as a color `rgb(85, 217, 194)`.

Since there are calculation using the divider height, it cause the error above.
