### ISSUE TITLE
Custom "trigger" slot for datepicker, datetimepicker, and clockpicker

### ISSUE THREAD

**Issue by 6XGate** [buefy/buefy#2553]
### Description

Since `BDatepicker`, `BDatetimepicker`, and `BTimepicker` are all implemented using a `BDropdown`, it would seem logical to add support for a custom trigger slot to these components rather than always being forced to use the `BInput` control.

### Why Buefy need this feature

This would provide further customization, especially in use-cases where the trigger would need to have a different look, but still function as a drop-down as it does now.  Having the user re-implementing this with the inline option seems big ask.

An exmple may be a regular solid color button:
```
<b-datepicker>
  <template #trigger>
    <b-button label="Pick date" type="is-primary"/>
  </template>
</b-datepicker>
```

**Comment by jtommy** [comment]
That isn't a bad idea!
