### ISSUE TITLE
Allow datetimepicker to receive an empty array as the bind value. 

### ISSUE THREAD

**Issue by taverasady** [buefy/buefy#2554]
In the datepicker component you need to use an empty array if you are going to be using the range prop, but if you try to use it on the datetimepicker it will say that it was expecting a new Date instead.

**Buefy** version: [0.8.15]
**Vuejs** version: [2.6.11]
**OS/Browser**: Google Chrome

### Description

Steps to reproduce:

1. Use a datetimepicker component
2. Add the range prop from the datepicker component.

 Expected behavior
 Be able to select range of dates within an specific hour (Starting date - HOUR, End date - HOUR).

### Actual behavior
Crashes because the v-model was expecting a new Date.

**Comment by jtommy** [comment]
It doesn't support range at the moment
