### ISSUE TITLE
Custom trigger event for dropdown component

### ISSUE THREAD

**Issue by Ridzhi** [buefy/buefy#2555]
### Description

The ability to change trigger event to activate dropdown component

### Why Buefy need this feature

This will expand the use of dropdown. For example I need to make context menu, but I cant, because only left mouse button, no posibility to change on right click

**Comment by jtommy** [comment]
It might be a good idea

**Comment by wobsoriano** [comment]
Is this doable with `b-dropdown-item` as well?

**Comment by kikuomax** [comment]
> Is this doable with `b-dropdown-item` as well?

@wobsoriano If this is simply a question, please post it to [Discussions > Q&A](https://github.com/buefy/buefy/discussions/categories/q-a). Or, do you have any specific problem with `b-dropdown-item`?
