### ISSUE TITLE
Taginput: Allow different tag types

### ISSUE THREAD

**Issue by apauly** [buefy/buefy#2556]
### Description

It is currently not possible to have different tag types within a taginput (correct me if I'm wrong - at least I didn't find a non wacky way to do this ;)).

When looking at the source, it should be relatively easy to add this feature. I'd be happy to provide a PR if you agree in this being useful.

### Why Buefy need this feature

It would be quite handy for validation purposes to only highlight a certain tag instead of marking the complete taginput with "is-danger".

**Comment by jtommy** [comment]
You can use tags slot :)
