### ISSUE TITLE
[Tabs] Improvement: Use provide/inject feature rather than direct ancestry properties 

### ISSUE THREAD

**Issue by Tofandel** [buefy/buefy#2557]
The idea is to replace the current tab registration behavior using provide inject rather than scanning the vnodes and using the `$parent` property in the tab item

This will allow to use the tab in a component and the tab item in another component

Eg:

App.vue
```html
<b-tabs v-else v-model="activeTab">
  <template v-for="group in groups">
    <Group :key="group.id" v-bind="group"/>
  </template>
</b-tabs>
```

Group.vue
```html
<b-tab-item :label="name">
  <div>Content</div>
</b-tab-item>
```

PR will follow

**Comment by jtommy** [comment]
As you can see in 0.9.0 branch there is small refactoring. Your idea is correct but if you want to make a PR you have to start from that branch please:)

**Comment by service-paradis** [comment]
Would be great to do this for every component using $parent (ex. Dropdown).

**Comment by jtommy** [comment]
Sure, I'm adding it to table component too

**Comment by Tofandel** [comment]
@jtommy I've had a look at the table component implementation and it's incomplete so it doesn't work, is it okay if I make a new PR to fix thatl?

**Comment by jtommy** [comment]
I was working on it. If you want help me you might take a look to roadmap or new feature requests in the issues list. Thanks

**Comment by Tofandel** [comment]
Okay then, I'll wait for the table, I have an improvement that I can PR now, basically the provide inject functionality I made a factory mixin wrapper for it, so it's super easy for any component to implement those features (Added it to dropdown as well)

I also made a super simple timeline component, it's clean enough, using bulma variables and lightweight enough to be added into buefy if you're interested (20 lines of vue and 30 lines of scss)

This is what it looks like on my dark theme
![image](https://user-images.githubusercontent.com/6115458/85327706-b5d3ad80-b4cf-11ea-8f67-782f9cb94a7b.png)
The circles are customizable b-icons

There isn't much left in the todo list for v1 but I can tackle #2214 and #2575 by removing the default value of the number input until user action on the input, I can also add a prop 'exponential' to increase the incrementation speed when button is left clicked as it's currently quite slow, it's something I did for one of my components

I can also do a few test units
