### ISSUE TITLE
"Import Individual Components" does not code split

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#2559]
In the docs, you say
> **Import and use Buefy** [...] Bundle [...] **or Individual Components**

With the following code:
```js
import Vue from 'vue'
import { Field, Input } from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Field)
Vue.use(Input)
```

This is a great idea on paper to only import what we need, but in your implementation, this does not work properly.

In your `package.json` you set **main** as `dist/cjs/index.js` and **module** as `dist/esm/index.js` which resolves buefy to one of these files.
The issue is that, in both files **you imported ALL components** which means, despite what we whitelist with the import curly braces, webpack or node's import system still imports the whole file.

Therefore, those fields are only "whitelisted" but all components are still imorted.

The docs should be updated to something like:
```js
import Vue from 'vue'
import Field from 'buefy/src/components/field'
import Input from 'buefy/src/components/input'
import 'buefy/dist/buefy.css'

Vue.use(Field)
Vue.use(Input)
```

This actual code would, indeed only import the listed components.
This brings some questions now, with a system like this, how can we:

### 1. how to add constructor options ?
Since we only import needed components, will the following code work:
```js
import ConfigComponent from 'buefy/src/utils/ConfigComponent.js'
ConfigComponent.setOptions({
    defaultIconPack: 'fas',
    defaultContainerElement: '#content',
    // ...
})
```
Will this work without re-importing everything based on your internals?

### 2. how to set Vue prototype functions?
Since we do not install buefy globally anymore, things like `this.$beufy.dialog.alert()` won't work anymore. Will the following code work and add the prototype correctly:
```js
import Vue from 'vue'
import Dialog from 'buefy/src/components/dialog'
import 'buefy/dist/buefy.css'

Vue.use(Dialog)

// somewhere in a Vue instance : this.$buefy.dialog.alert('hello');
```

Will this work without any side effects since there would be no more the global buefy?

### 3. What about CSS?
Now, let's say all goes well, what about the CSS? It is still fully imported even if we use a few components, and the thing is 330kb.

Would be interesting to have a **bulma way** to only import the CSS of buefy components we use + core CSS of course which many components may share.

That's all for me here. Hope this makes buefy better for the future. Buefy is really neat but adds a lot to the final bundle, and the example in the docs is confusing and may make us think it actually does code splitting, while it doesn't. That's why I had to raise this issue.

To illustrate, here's the analasys of my bundle despite I only imported a few components:
![image](https://user-images.githubusercontent.com/1426357/83091595-cbee7980-a09b-11ea-8bdf-21d3dba52375.png)

**Comment by jtommy** [comment]
@darkylmnx 
I don't know what is your configuration but individual components works well as described and the final project bundle is smaller than importing all Buefy.

1) No problem, it's ok.
2) You are importing the component and not the plugin so you have to set prototype manually. Using the individual components import as docs you don't have this issue.
3) About css it's no easy and there isn't an official way. Btw you might import only scss that you need importing them from src folder.

**Comment by darkylmnx** [comment]
@jtommy 
> individual components works well as described and the final project bundle is smaller than importing all Buefy.

Do you mean as described in the docs are as I described in my issue?

I've tried some stuff on a "bare project" with parcel.

Both of the following codes gave the same bundle size:
```js
import './index.scss';
import Vue from 'vue';
import { Button, Toast, ConfigProgrammatic } from 'buefy';
import App from './App.vue';

Vue.use(Button);
Vue.use(Toast);

ConfigProgrammatic.setOptions({
  defaultToastDuration: 4000,
});

new Vue({
  render: h => h(App) 
}).$mount('#app');
```

```js
import './index.scss';
import Vue from 'vue';
import Buefy from 'buefy';
import App from './App.vue';

Vue.use(Buefy, {
  defaultToastDuration: 4000,
});

new Vue({
  render: h => h(App) 
}).$mount('#app');

```

![image](https://user-images.githubusercontent.com/1426357/83203962-e92e5100-a14a-11ea-9755-3ebde1519130.png)

As you can see, both of the main.js builds is ~340 KB, which means doing like in the docs for individual actually improts all.

I then tried my individual assumption:
```js
import './index.scss';
import Vue from 'vue';
import Button from 'buefy/src/components/button';
import Toast from 'buefy/src/components/toast';
import ConfigProgrammatic from 'buefy/src/utils/ConfigComponent.js';
import App from './App.vue';

Vue.use(Button);
Vue.use(Toast);

ConfigProgrammatic.setOptions({
  defaultToastDuration: 4000,
});

new Vue({
  render: h => h(App) 
}).$mount('#app');
```
But it seems to fail because of some buefy internals:
![image](https://user-images.githubusercontent.com/1426357/83204784-f5b3a900-a14c-11ea-8a9e-294cb0f71e54.png)

For point 3. Yes I guess I could just import individual scss files.
Base on the previous example, will something like this be okay?
```scss
// inside index.scss
@import "utils/_all";

@import "components/_button";
@import "components/_toast";
```
The only thing is, there doesn't seem to be any button or toast scss file.

**Comment by jtommy** [comment]
I never tried with parcel but only with a Vue-cli project (webpack). I don't know well Parcel to help you.
3) Take a look at source code, there isn't a button scss (it all in bulma) and for road there is a general notification file

**Comment by darkylmnx** [comment]
@jtommy well I tried it with a regular Vue CLI project and:
```javascript
import './index.scss';
import Vue from 'vue';
import Button from 'buefy/src/components/button';
import Toast from 'buefy/src/components/toast';
import ConfigProgrammatic from 'buefy/src/utils/ConfigComponent';
import App from './App.vue';

Vue.use(Button);
Vue.use(Toast);

ConfigProgrammatic.setOptions({
  defaultToastDuration: 4000,
});

new Vue({
  render: (h) => h(App),
}).$mount('#app');

```
This seems to work.
![image](https://user-images.githubusercontent.com/1426357/83344851-9c927380-a30c-11ea-8e8f-a03edded5fa0.png)

What is funny though is that this:
```js
import './index.scss';
import Vue from 'vue';
import { Button, Toast, ConfigProgrammatic } from 'buefy';
import App from './App.vue';

Vue.use(Button);
Vue.use(Toast);

ConfigProgrammatic.setOptions({
  defaultToastDuration: 4000,
});

new Vue({
  render: (h) => h(App),
}).$mount('#app');
```
Is actually heavier than using the full build.
![image](https://user-images.githubusercontent.com/1426357/83344864-bf248c80-a30c-11ea-9e5e-05f0abf109a7.png)

Full build with `Vue.user(Buefy)`:
![image](https://user-images.githubusercontent.com/1426357/83344870-d5324d00-a30c-11ea-91ed-d807a51ba8b2.png)

I'll give a check to the CSS.
In any case, as I thought, doing `import { Button, Toast, ConfigProgrammatic } from 'buefy'` still imports the full buefy JS files so I feel this should be stated in the docs.
The proper way to code split (which is my first code snippet) should be mentionned too to help people.
Could splitting / component splittig is the path that Vue 3 is taking so I feel that Buefy should be the same and alow "only import to the code bundle what you use".

**Comment by jtommy** [comment]
@darkylmnx and removing ConfigProgrammatic ?

**Comment by darkylmnx** [comment]
@jtommy on which one? Here's a reproduction repo if you want to test: https://github.com/darkylmnx/reproduction-buefy-code-splitting

**Comment by jtommy** [comment]
All examples

**Comment by darkylmnx** [comment]
Well, it makes the `import { Button, Toast } from 'buefy';` go down to 77.89 KiB
![image](https://user-images.githubusercontent.com/1426357/83345223-f006c080-a310-11ea-98d8-7ad1f1dc5656.png)

And the complete independent import of Button and Toast by file stays at 107kb
![image](https://user-images.githubusercontent.com/1426357/83345233-0a409e80-a311-11ea-9c46-562bac75e49f.png)

How is that?

**Comment by jtommy** [comment]
Probably there is something wrong about exporting ConfigProgrammatic

**Comment by darkylmnx** [comment]
Okay, but why is the build of this (77kb):
```js
import { Button, Toast } from 'buefy';
```

much heavier than this (107kb)
```js
import Button from 'buefy/src/components/button';
import Toast from 'buefy/src/components/toast';
```
it's kind of weird

**Comment by jtommy** [comment]
Much heavier? Is 77kb heavier than 107kb ?

**Comment by darkylmnx** [comment]
Sorry I meant the inverse, why is the second example heavier than the first.

**Comment by jtommy** [comment]
Because the official way export all as esm module and the cli (webpack) is able to optimize the project bundle

**Comment by darkylmnx** [comment]
So despite this line: https://github.com/buefy/buefy/blob/dev/src/index.js#L28
Wepack is able to automatically treeshake the bundle? That's interesting.

In `buefy/dist/esm/index.js` there are things like:
```js
import Plugin$8 from './dialog.js';
export { default as Dialog, DialogProgrammatic } from './dialog.js';
import Plugin$9 from './dropdown.js';
export { default as Dropdown } from './dropdown.js';
import Plugin$a from './field.js';
export { default as Field } from './field.js';
import Plugin$b from './icon.js';
export { default as Icon } from './icon.js';
import Plugin$c from './input.js';
export { default as Input } from './input.js';
```
So I was wondering how the tree shake would work since everything here is imported.

**Comment by jtommy** [comment]
Probably I understand the issue with ConfigProgrammatic :)

**Comment by darkylmnx** [comment]
nice, keep me posted!
