### ISSUE TITLE
Cannot use component alone and set constructor prop

### ISSUE THREAD

**Issue by hchauvat** [buefy/buefy#2560]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: macOS Catalina, Chrome 83.0.4103.61
**TypeScript**: [3.7.4]
**Webpack**: [4.41.5]

### Description

I'm trying to use Buefy components individually. For now, Datepicker with the FontAwesome icon set.

#### 1. Import issues
In my `main.ts`:
```typescript
import { ConfigProgrammatic, Datepicker } from 'buefy'; 
// Raises 'Error TS2614: Module "../node_modules/buefy/types" has no exported member 'Datepicker'. Did you mean to use 'import Datepicker from "../node_modules/buefy/types" instead?'
```
```typescript 
import ConfigProgrammatic from 'buefy';
import Datepicker from 'buefy';
// No error is raised
```

### 2. setOptions issues
In my `main.ts`:
```typescript
import ConfigProgrammatic from 'buefy';
import Datepicker from 'buefy';
...
Vue.use(Datepicker);
ConfigProgrammatic.setOptions({
     defaultIconPack: 'fas',
});
// Raises 'Error TS2339: Property 'setOptions' does not exist on type '{ install(Vue: VueConstructor<Vue>, config: BuefyConfig): void; }'.'
```
```typescript
import Buefy from 'buefy';
...
Vue.use(Buefy, {
    defaultIconPack: 'fas',
});
// No error is raised
```

### Expected behavior

1. According to the [Start doc](https://buefy.org/documentation/start/), I feel like I should be able to import components individually
2. According to the [Constructor doc](https://buefy.org/documentation/constructor-options/), I feel like I should be able to use the `setOptions` method to set constructor props.

### Actual behavior

Whenever I tried to import and setup a component individually, I got TypeScript errors. In the end, I'm forced to import the entire Buefy module :/.

**Comment by jtommy** [comment]
@hchauvat 
please check the docs, your import should be something like:
`import { ConfigProgrammatic, Datepicker } from 'buefy';

**Comment by jtommy** [comment]
I'll add them in the next breaking 0.9.0 ;)

**Comment by asmaloney** [comment]
I realize this is an old (closed) issue, but I'm switching a vue 2 app to typescript and ran into this same import problem.

Is there a solution yet for importing individual components?

I don't see anything in the docs ([here](https://buefy.org/documentation/constructor-options)) about typescript at all.
