### ISSUE TITLE
Allow right click/open in new tab for Table row

### ISSUE THREAD

**Issue by AkramEld** [buefy/buefy#2561]
Currently you can add click events for a table row and do whatever you want there. There is allow user to right click on a row and be able to open in a new tab (go to a route). I tried wrapping the template with a router-link but got an error saying you need to have a column.

**Comment by jtommy** [comment]
You might listen context menu event on table component.

**Comment by AkramEld** [comment]
> You might listen context menu event on table component.

Yes but wont be able to give a "open on new tab" option

**Comment by jtommy** [comment]
You can listen it and show a context menu

**Comment by AkramEld** [comment]
> You can listen it and show a context menu

How? You have an example?
