### ISSUE TITLE
Disappearing pickers after clicking on select element in Web Component

### ISSUE THREAD

**Issue by dloranc** [buefy/buefy#2562]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS Catalina / Chrome 83.0.4103.61

### Description

In a Web Component selects in Datepicker or Timepicker are broken. When I open a Datepicker and click on select it disappears instantly without selecting anything. It behaves that way because clickedOutside method doesn't work for Shadow DOM. It receives web component in `event.target`.

The workaround we managed to solve this issue was to stop propagation by adding a hander for click event and using `event.stopPropagation` function.

### Steps to reproduce

1. Place a Datepicker anywhere in your app
2. Build a web component by using `vue-cli-service build --target wc --name [your-web-component-name] src/component/[that-component-you-want-to-build].vue`
3. Open `dist\demo.html`

Alternatively you can clone a repository:

1. Clone https://github.com/dloranc/buefy-web-component-bug repository
2. `yarn install`
3. `yarn build-wc`
4. Open `dist\demo.html`

### Expected behavior

After click on select in datepicker it should show option list. Datepicker should not close immediately.

### Actual behavior

After click on select in datepicker it shows an option list for a moment, but a whole component closes then, almost instantly.

**Comment by service-paradis** [comment]
I think this is related to #2284

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2603
