### ISSUE TITLE
Ability to add cutom events to the input in b-input / v-model.lazy

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#2565]
### Description
Add possibility to add custom events to the input element in **b-input**. Or add `v-model.lazy` modifier to the component.
Something like:
```vue
<b-input :input-events="{ ... }" />
<!-- or -->
<b-input @change="..." />
```
Which would be added to https://github.com/buefy/buefy/blob/dev/src/components/input/Input.vue#L15 with:
```vue
<input v-on="inputEvents" />
<!-- or take parent events directly that you merge with a computed -->
<input v-on="$listeners" />
```
Ressource about that: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

### Why Buefy need this feature

Well, I can't use `v-model.lazy` on b-input and I need to use that event to throttle some AJAX validation calls. But in any case, there are many cases where we need to add direct events to the input like **focus**, **blur** and more.

**Comment by jtommy** [comment]
You can listen all events using native modifier, for example` @change.native`

**Comment by darkylmnx** [comment]
@jtommy I tried and it didn't work, for a simple reason, it adds the event on the DIV and not on the input. https://github.com/buefy/buefy/blob/dev/src/components/input/Input.vue#L2
