### ISSUE TITLE
[Message] Add the possibility to have an empty message

### ISSUE THREAD

**Issue by Tofandel** [buefy/buefy#2568]
It is currently possible to have a message without title but not possible to have a message without body

It would be nice to add a check if the default slot is empty to not display the body and to have the header fully rounded

Effectively making a simple dismissable message

Current behavior
![image](https://user-images.githubusercontent.com/6115458/83548118-86023d00-a503-11ea-807c-6f3542d897ba.png)

Desired behavior
![image](https://user-images.githubusercontent.com/6115458/83547670-da58ed00-a502-11ea-97a4-6ad37e177300.png)

Bulma feature request for the message without body https://github.com/jgthms/bulma/issues/2978

In the meantime the notification component does the job but does not have the same style
![image](https://user-images.githubusercontent.com/6115458/83549899-4db02e00-a506-11ea-8eab-bc20b517c9b7.png)

**Comment by jtommy** [comment]
@Tofandel ok you can make a PR
