### ISSUE TITLE
 Draggable Columns

### ISSUE THREAD

**Issue by FlorianChretien** [buefy/buefy#2569]
Hello,

I tried without success to make the columns draggable. Would it be possible to do it? This is a big need for customers who want to customize their tables (like Draggable rows).

A huge thank you for your help!
Have a good day

**Comment by jtommy** [comment]
No you can't and to be honest it's not in my mind a similar feature at the moment.

**Comment by FlorianChretien** [comment]
thanks anyway !

**Comment by T0RAT0RA** [comment]
FYI: I just opened https://github.com/buefy/buefy/pull/3172 to add draggable columns.
