### ISSUE TITLE
Typings dont export any components.

### ISSUE THREAD

**Issue by MrJacz** [buefy/buefy#2571]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11

### Description
When using typescript I can't import individual components because the typings do not account for that, to clarify, in `buefy/index.js`, `export * from './components'` is done so all components are exported but when using typescript and if I do

```typescript
import { Icon } from "buefy";
```

it will say it doesn't exist because, in typescripts mind it doesnt, as `export * from './components'` does not exist in the typings. ofc that code will work but ts thinks it wont.

**Comment by jtommy** [comment]
Yes, at the moment there is a type for each component but only for programmatic

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/2057
