### ISSUE TITLE
The check-all header in checkable BTable should check all known rows in a paginated table

### ISSUE THREAD

**Issue by 6XGate** [buefy/buefy#2572]
### Description

When using a checkable, paginated, BTable, the check-all header should check all rows rather than only the viable. Currently, only the visible rows will be checked.

If this is not always desired, this could be a new boolean attribute.

### Why Buefy need this feature

In some or many use cases, a layman user may expect that the check-all header would check all rows, even those outside the current page.

**Comment by jtommy** [comment]
@6XGate and what about when `backend-pagination` ? Take a look at https://github.com/buefy/buefy/issues/2083

**Comment by 6XGate** [comment]
Based on the back-end case.  Maybe the BTable should have a few attributes to handle back-end or component consumer check state handling.

The main issue I'm running into right now is when a user relies on check-all header; it doesn't reflect the state of the whole table. Being checked when all items of the current page are checked.  The `@check-all` listener only provides me a means the change behavior, but not the header's feedback to the user.

**Comment by 6XGate** [comment]
It seems that BTable might need an `is-all-rows-checked: () => boolean` _prop_ to support our use-case.  We are trying to ensure that the _check-all_ header will be checked when every single row in the table is checked rather than just the current page. This should support both server side and client size pagination since the server would need to track that state too.

**Comment by jtommy** [comment]
I might add it but there is always a difference behaviour between client and backend

**Comment by 6XGate** [comment]
That should do just fine.
