### ISSUE TITLE
Why minLength wasn`t added in FormElementMixin?

### ISSUE THREAD

**Issue by RonnyTod** [buefy/buefy#2573]
### Description

In my project I got problem with lack of the minLength prop for input, because I need to call some methods only in case when length is more than 2. So I would ask you about reasons why minLength wasn`t added for this mixin and for b-autocomplete specifically.

### Why Buefy need this feature

Because I need to have min length for autocomplete activation (dropdown)

**Comment by jtommy** [comment]
Are you using it in async mode?
