### ISSUE TITLE
There is no way to validate if b-numberinput control is empty

### ISSUE THREAD

**Issue by shindesayalip** [buefy/buefy#2575]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

There is no way to validate if b-numberinput is made empty by the user when editable property is set to true.
### Steps to reproduce

1. Set min and max value for b-numberinput.
2. Keep editable property to true.
3. Bind a variable to the control with v-model.
4. Delete everything from the number control with backspace. Make it empty.
5. Check the value for v-model variable. It is set to min value. But user has no idea that control is still pointing to min value and is not empty.

### Expected behavior

Control should show the correct value it is bound to or should provide a mechanism to validate empty check.

### Actual behavior

Control is displayed as empty but it actually points to min value. This results in ambiguous operation being performed in consumer app.

**Comment by jtommy** [comment]
Similar to https://github.com/buefy/buefy/issues/2214
