### ISSUE TITLE
b-progress does not move when updated with window.requestAnimationFrame

### ISSUE THREAD

**Issue by lunfel** [buefy/buefy#2576]
### Overview of the problem

The b-progress does not seem to update when the values are updated frequently (via window.requestAnimationFrame for example). 

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: Chrome 83 on Ubuntu

### Description

When I animate a b-progress with `window.requestAnimationFrame` it does not seem to update visually until the value stops incrementing. I am willing to put a PR in to fix it, but I am not sure what is causing this behavior.

### Steps to reproduce

I have a JSFiddle that demonstrate the native progress and Bulma progress visually updates properly. But when using Buefy, the update state stays at 0.

http://jsfiddle.net/yqtw4nf0/26/

### Expected behavior

From the JSFiddle, the Buefy progress bar should have the same behavior than the other ones 

### Actual behavior

Value visually stays at 0 until the end

**Comment by service-paradis** [comment]
There is a weird known problem with `requestAnimationFrame` and Vue (or React). The solution is often the weird trick about _double requestAnimationFrame_ (ex. [https://medium.com/@owencm/one-weird-trick-to-performant-touch-response-animations-with-react-9fe4a0838116](One weird trick))

[Here](http://jsfiddle.net/n697bwk2/) is your updated jsfiddle.

Ref: https://www.google.com/search?q=%22double+requestanimationframe%22
