### ISSUE TITLE
Hide icon when setting b-field type for a b-input form element.

### ISSUE THREAD

**Issue by zevektor** [buefy/buefy#2577]
### Description

Currently when we set a type for a `b-field` wrapping a `b-input`, not only the input borders are colored, but also an icon is added to the right. 
I could not find a property, either in field or input, to disable such behavior.
Input's `icon` and `icon-right` seem to be ignored.

### Why Buefy need this feature

An icon is not always needed, sometimes a colored border can be enough.

**Actual behavior:**
![actual](https://user-images.githubusercontent.com/3817173/83938182-9f8cd880-a7d2-11ea-90a8-009966a66c7e.png)

**Desired behavior:**
![desired](https://user-images.githubusercontent.com/3817173/83938188-a9aed700-a7d2-11ea-8eb2-eea73a0c9ca2.png)

**Comment by jtommy** [comment]
@zevektor There isn't a way to disable it but you might workaround hiding the icon with css

**Comment by zevektor** [comment]
@jtommy surely I can hide it with a css rule, but a property might be better. 
I think icons should be made optional whenever possible, some users don't even load any icon font 🙂

**Comment by jtommy** [comment]
Sure!

**Comment by service-paradis** [comment]
As a workaround, you can set any invalid value to `icon-pack` (ex. `icon-pack="none"`).
It is more a hack than a real solution. Would be interesting to have a legit way to disable icons on components when needed.

**Comment by jtommy** [comment]
I'm going to add statusIcon prop on input and select and a global configuration
