### ISSUE TITLE
b-table custom-sort

### ISSUE THREAD

**Issue by Aeox85** [buefy/buefy#2578]
Hello,

Is it possible to be able to sort certain columns based on another hidden column?

So for example, the data in the hidden column will have a series of dates. However, the visible column will be displayed as "expired", "future", "today", "not set" etc. When the user clicks the column with these values i need to be able to sort based on the date that is in the hidden column and not by the column header that has been clicked on.

The issue i have at the moment is that the columns are generated by a "column" array:

`<template slot-scope="props">
            <template v-for="column in columns">
              <b-table-column :key="column.id" v-bind="column" :field="column.field">
                  <template>
                  </template>
              </b-table-column>
             </template>
</template>
`

**Comment by jtommy** [comment]
You have to use `custom-sort` prop of table column component. Take a look at API docs ;)
