### ISSUE TITLE
bug: TS7016 Could not find a declaration file for module

### ISSUE THREAD

**Issue by RokkerRuslan** [buefy/buefy#258]
### Overview of the problem

**Buefy** version: [0.4.6]
**Vuejs** version: [2.4.2]
**OS/Browser**: Ubuntu 16.04 (Version 60.0.3112.78 (Developer Build) (64-bit))

### Description
Output of command **`npm run dev`**:

> error TS7016: Could not find a declaration file for module 'buefy'. '/home/r/w/ale/client/node_modules/buefy/lib/index.js' implicitly has an 'any' type.
>   Try `npm install @types/buefy` if it exists or add a new declaration (.d.ts) file containing `declare module 'buefy';

And **`npm install @types/buefy`**:

> npm ERR! code E404
> npm ERR! 404 Not Found: @types/buefy@latest
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/r/.npm/_logs/2017-08-16T17_07_01_661Z-debug.log

### Steps to reproduce

> vue init webpack project
> add typescript support - https://github.com/vuejs-templates/webpack/pull/797
> npm install buefy
> npm run dev

### Expected behavior

Successfully started on localhost:8000

### Actual behavior

error: TS70016

### Temporary (ugly) solution:

> "noImplicitAny": false,

in tsconfig.json
OR
create file buefy.d.ts with that contents: "declare module 'buefy';"

**Comment by rafaelpimpa** [comment]
I haven't work with typescript yet, hope anyone can help with that.

**Comment by OzairP** [comment]
I'm not the best at TypeScript either but I have found a way to write the typings. There is probably a better way of doing this. There is a section on module augmentations but I'm not understanding it all that well.

buefy-augmentation.d.ts
```typescript
import {Vue} from "vue/types/vue";


interface Buefy extends Vue {
	$snackbar: {
		open(message: string): void
	}
}
```

app.ts
```typescript
const vue = new Vue({
	el: '#app'
}) as Buefy
```

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/pull/465
