### ISSUE TITLE
CodeSandbox for bug reports

### ISSUE THREAD

**Issue by Christilut** [buefy/buefy#2582]
Often I want to report a bug but reproducing it is just so much work to create/find the right online fiddle/sandbox for it. Adding dependencies is always super annoying. Recreating it online is about 90% of the work for me, the other 10% is the actual bug. That usually demotivates me to the point that I either don't report the bug or report it without reproducing...

It would be nice if the bug report template contains a link to a fiddle or codesandbox.io with the latest Buefy and just a very quick template to get started.

**Comment by jtommy** [comment]
It might be a good idea.
Would you like create one and make a PR?

**Comment by Christilut** [comment]
I made one here but I don't know how to edit the github templates and it would be nice if the CodeSandbox always used the latest buefy, but I don't know how to do that either.

https://codesandbox.io/s/buefy-template-1hmvy

**Comment by jtommy** [comment]
> For example, to specify acceptable version ranges up to 1.0.4, use the following syntax:
> 
> Patch releases: 1.0 or 1.0.x or ~1.0.4
> Minor releases: 1 or 1.x or ^1.0.4
> Major releases: * or x

About template you can edit https://github.com/buefy/buefy/blob/dev/.github/ISSUE_TEMPLATE/BUG_REPORT.md

**Comment by Christilut** [comment]
Done 👍

**Comment by jtommy** [comment]
Thanks
