### ISSUE TITLE
Carousel List: active item centered

### ISSUE THREAD

**Issue by berry807** [buefy/buefy#2583]
# Description

For my project I needed a simple carousel list, with each item having a year range like 2020 - 2021 (20-21). Now while I was implementing the carousel list I noticed one missing option to center the active item in the list. Currently the active item is always on the left side.

### Why Buefy need this feature

Most sliders/carousels have this basic feature implemented (for example [kenwheeler/slick](https://kenwheeler.github.io/slick)). I think there are many scenarios where this feature can be handy.

I would really like to start contributing but not sure where to look in order to built this feature. Tips are welcome 😄 

# Examples
I made a example screenshot just by manipulating the `is-active` class to the centered item:

### Currently:
<img width="1049" alt="Screenshot 2020-06-07 at 11 20 09" src="https://user-images.githubusercontent.com/8251304/83965285-d9cda700-a8b2-11ea-8826-164bd1e42447.png">

### Feature:
<img width="1043" alt="Screenshot 2020-06-07 at 11 20 33" src="https://user-images.githubusercontent.com/8251304/83965284-d9351080-a8b2-11ea-8f73-c2523c127d8a.png">

**Comment by berry807** [comment]
I did some research myself and thought of this calculation to get the center point of the carousel list:

Example: 
1. itemsToShow: 9
2. itemWidth: 114.667 (px)
3. total carousel width: 9 * 114.667 = 1032.002
4. centerpoint of carousel list: 1032.002 / 2 = 516.0015
5. activeItem: 6
6. current active item position: 6 * 114.667 = 688.002
7. centerpoint in carousel list for the active item: 688.002 - 516.0015 = 172.0005
8. But 172.0005 will be the left side/start of the active item
9. So: 114.667 / 2 = 57.3335
10. **Final center point: 172.0005 + 57.3335 = 229.334**

`translate = ((this.itemsToShow * this.itemWidth) / 2) - (this.activeItem * this.itemWidth) + (this.itemWidth / 2)`

```
transformStyle() {
    const translate = this.delta + 1 * (this.activeItem * this.itemWidth)
    const result = this.dragging ? -translate : -Math.abs(translate)
    return `transform: translateX(${result}px);`
},
```

**Comment by jtommy** [comment]
@berry807 you're right but i think the carousel will be refactored in the next breaking version or v1
