### ISSUE TITLE
Default sorting arrow not shown when backend sorting is enabled

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#2584]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: any

### Description

A `BTable` with `backend-sorting` enabled won't show the initial default sorting arrow.
The arrows do show up correctly when the user changes the default sorting.

### Steps to reproduce

Minimal working example:

```vue
<b-table :data="[{ }]"
         :default-sort="[ 'field1', 'asc' ]"
         :backend-sorting="false">
    <b-table-column label="Field1" field="field1" sortable>
        Value1
    </b-table-column>
    <b-table-column label="Field2" field="field2" sortable>
        Value2
    </b-table-column>
</b-table>
```

With `:backend-sorting="false"` the default sorting arrow is shown:

![sort1](https://user-images.githubusercontent.com/47509484/83976613-5edcae80-a8fb-11ea-8772-14ad7babf5c4.png)

With `:backend-sorting="true"` the arrow disappears (until the user changes the sorting):

![sort2](https://user-images.githubusercontent.com/47509484/83976616-68fead00-a8fb-11ea-8518-2dc1f1c4f7c1.png)

**Comment by lgarczyn** [comment]
Same issue, resolved using multi-sorting with a limit of 1 sort, unfortunately you cannot remove the '1' next to the chevron easily

**Comment by lgarczyn** [comment]
You can remove the '1' using css:

``` scss
.your-container /deep/ .is-sortable > div {
	color: transparent;
}
.your-container /deep/ .is-sortable > div > span{
	color: #363636;
}
```

The one advice that was given last time this was posted was to call 'defaultSort' after setting the prop, but it didn't work for everyone, even after waiting one frame
