### ISSUE TITLE
Upgrade to Bulma 0.9.0

### ISSUE THREAD

**Issue by cperrin88** [buefy/buefy#2586]
### Description

The new Bulma version is out and this project is several versions behind. 

### Why Buefy need this feature

Especially the new helpers for dark mode are very useful.

**Comment by moshepollak** [comment]
bulma 0.9.0 support RTL

**Comment by jtommy** [comment]
Yes! Buefy is going to skip bulma 0.8.x and goes to 0.9.0

**Comment by htlcode** [comment]
https://bulma.io/documentation/elements/image/
Responsive images with ratios (ex: image is-5by4) is a 0.9.0 feature?
It's not working on the current buetify

**Comment by Tofandel** [comment]
You might also wanna keep a lookout for what [I've been doing with css variables](https://github.com/jgthms/bulma/pull/2981) as well
Hoping it will ship in 0.9.x or 1.0

Since it will give a full support for themeing with classes (and yes themes can even be nested)

**Comment by francisfontoura** [comment]
How about having Bulma as peer dependency of Buefy? Is it possible?

**Comment by Tofandel** [comment]
It already is, in fact you can install your own version and compile the scss with the correct version by running `npm install bulma -D`
The only factor is some buefy's component may not be in sync if there is breaking changes, but there is likely none

**Comment by Tofandel** [comment]
@htlcode No that feature is quite old, likely 
0.7 so maybe you're doing something wrong

**Comment by kor3k** [comment]
hello, may i ask when approximately will buefy dump bulma version to 0.9+ ?

i noticed there are some missing classes, like `is-success` , `is-info` etc  with [tiles](https://bulma.io/documentation/layout/tiles/#example) for example.

**Comment by AggressivelyMeows** [comment]
In my personal testing Buefy can work with Bulma 0.9 however you have to force update Bulma to the latest. Oh and you also need to use the custom SCSS feature to ensure it builds right. Other than that, it should be a simple switch of the deps on your end.

**Comment by swaylock** [comment]
@AggressivelyMeows 

> you also need to use the custom SCSS feature to ensure it builds right.

Would you mind elaborating a bit on this? How does one do this?

**Comment by Tofandel** [comment]
@swaylock He means this https://buefy.org/documentation/customization
You need to import buefy.scss and bulma.scss

**Comment by jtommy** [comment]
Done in 0.9.0 branch (WIP)

**Comment by lance-anderson** [comment]
Hi @jtommy thanks for adding 0.9.0 support. Is there a general ETA for the next release? Days... weeks... months?

**Comment by jtommy** [comment]
Being a free time project I can't declare a ETA but I think to talk about weeks
