### ISSUE TITLE
Give focus to TagInput does not open dropdown, despite open-on-focus

### ISSUE THREAD

**Issue by mcmule** [buefy/buefy#2587]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.10]
**OS/Browser**: MacOS, Chrome 83

### Description

Programmatically giving focus to a TagInput, with this TagInput configured as "open-on-focus" and autocomplete, does not open the list of choices.

### Steps to reproduce

Go to this Codepen : https://codepen.io/mcmule/pen/ExPVZVV?editors=1010

Press the button.

### Expected behavior

I'd expect the same behavior you get when you click inside the input (it opens the choices, since we have open-on-focus prop.

### Actual behavior

If you press the button, the input gets focus, but does not open.

**Comment by service-paradis** [comment]
Just tried in the `dev` branch and it works. I think it will be ok in the next release. Can you confirm this @jtommy?

**Comment by jtommy** [comment]
Yes
