### ISSUE TITLE
BTable: Changing visibility of multiple columns causes header not to render

### ISSUE THREAD

**Issue by 6XGate** [buefy/buefy#2588]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 83 on Ubuntu 20.04

### Description

Changing the visibility of multiple columns in a BTable causes some header cells to not be rendered.

Please see this CodePen: https://codepen.io/6XGate/pen/BajopbE
Note that in some cases, this can randomly work and not work.

### Expected behavior

The column header will render for the visible columns.

### Actual behavior

Some headers are not rendered with their columns.

**Comment by jtommy** [comment]
I don't understand well your example. Can you try to add custom-key prop to all table column ?
Btw in the next release (0.9.0) table will be improved in order to fix similar issues

**Comment by 6XGate** [comment]
Okay, I tried that, and it did fix it at first, but there appears to be a race condition that is exposed when using Vuex to back the table.  Or at least when BTable is in another component that will proxy slot with columns to BTable.
