### ISSUE TITLE
Carousel does not continue to slide even pause-hover is false

### ISSUE THREAD

**Issue by tungtex-it** [buefy/buefy#2591]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10 1909/Firefox 77.0.1

### Description

I was following the documentation and created a carousel with autoplay = true, it was rolling smoothly except even pause-hover was set to false, the carousel stopped when mouse moved over it.

I wonder if I misunderstood anything in the guideline. Please refer to the example originally provided in the official guideline: https://codepen.io/pen?&editable=true&editors=101=https%3A%2F%2Fbuefy.org%2Fdocumentation%2Fcarousel%2F

Switch on Autoplay and leave Pause on Hover off.

### Expected behavior

Carousel continues rolling even mouse moves over it.

### Actual behavior

Carousel pauses when mouse moves over it.

**Comment by Tofandel** [comment]
I can confirm there is a bug, it always pauses on hover even if set to false

**Comment by Tofandel** [comment]
This is a simple fix but only made for the next major, so if it's urgent I could make a PR for a minor (it's only one function to rename in the template)

**Comment by jtommy** [comment]
You can make a breaking change if you want

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2619
