### ISSUE TITLE
Searching through the detailed row

### ISSUE THREAD

**Issue by me2mitesh** [buefy/buefy#2594]
Hi, Thanks for this buefy framework. Really loving it !

I have a searchable columns with detailed row feature. However, I am not able to search in the detailed row.

![image](https://user-images.githubusercontent.com/66727435/84258799-27f1dd00-ab35-11ea-9921-27ea3f93f65d.png)

As you can see the above screenshot, when i search for the content in the detailed row,
Eg : 'IDLE' in this case, i am not getting the result as the whole row which i was expecting.

I may be doing something wrong. Please tell if this feature is implemented. 
Thanks in advance !

**Comment by jtommy** [comment]
No, you don't but you can take a look at https://buefy.org/documentation/table#searchable (scoped slot)
