### ISSUE TITLE
It didn't work with old ios versions like ios 7, 8

### ISSUE THREAD

**Issue by varjose516** [buefy/buefy#2597]
I'm testing the Vue app across all devices and browsers.
The Vue app was not rendered in old ios versions when I added buefy to main.js

The following is my versions.
"buefy": "^0.8.20",
"vue": "^2.6.11"

**Comment by Tofandel** [comment]
Any errors in the console?

**Comment by varjose516** [comment]
I testing the vue app in the browserstack and it doesn't support me the devtools for ipad mini 2, 3.
So I can't see it right now.

**Comment by Tofandel** [comment]
Likely needs 
transpileDependencies: ['buefy'] in vue config
