### ISSUE TITLE
BTable - Columns not updating correctly when changing column array

### ISSUE THREAD

**Issue by ElmarRoberto** [buefy/buefy#2598]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.5.18]
**OS/Browser**:

### Description

I have the columns values ​​passed by a prop, but when I remove or add values, the table is not updated correctly. My code looks something like this:

```vue
<template>
  <b-table
    :data="data"
    ref="table"

    detailed
    :show-detail-icon="false"
  >

    <template slot-scope="props">
      <b-table-column field="expand" label="" v-if="value.length">
        <i @click="toggle(props.row)" class="icon" />
      </b-table-column>
        
      <template v-for="i in columns">
        <b-table-column :field="i.field" :label="i.label" :key="i.field" sortable>
          <span>{{ props.row[i.field] }}</span>
        </b-table-column>
      </template>
    </template>
  </b-table>
</template>

<script>
  // ...
  computed: {
    columns() {
      return this.value.map(column => ({
        field: column,
        label: column,
      }));
    },
    data() {
      return this.resultFromRequest.map(res =>
        this.value.reduce(
          (acc, curr) => ({ ...acc, [curr]: get(res, curr) }),
          {},
        ),
      );
    },
  },
// ...
</script>
```

The table works fine only when I use this solution https://github.com/buefy/buefy/issues/108#issuecomment-425547503. This is the expected behavior?

Maybe is related to this issue: https://github.com/buefy/buefy/issues/2588

### Steps to reproduce

You can reproduce the problem at this link: https://jsfiddle.net/Lehskjzu/. When I click to clear the columns, the headers remain.

### Expected behavior

The table component should correctly recalculate the column labels.

**Comment by jtommy** [comment]
Add :custom-key prop to table column

**Comment by ElmarRoberto** [comment]
The problem is when I try to remove a column. The table continues to show all headers, even if there is no more reference to them. Anyway, I will wait for the next release. Thank you! :)

**Comment by thefoxie** [comment]
Yeah same here, even with custom header.

**Comment by amhunt** [comment]
Having the same issue.

**Comment by jtommy** [comment]
@amhunt buefy version ? Can you reproduce on codepen o codesanbox ?

**Comment by ralphskie** [comment]
Having this same issue, here is a sample codepen.
https://codesandbox.io/s/r0sjh
When column(array count are the same it will be okay) but if different, It starts to mixed up.

**Comment by Aterr** [comment]
Facing the same issue (buefy 0.8.20). 
Is there a workaround somewhere ?
