### ISSUE TITLE
Ablity to add clickable buttons / icons to dropdown options via custom template

### ISSUE THREAD

**Issue by CromonMS** [buefy/buefy#2601]
### Description

Ability to be able to add a clickable button or icon without actually selecting the item you are clicking

### Why Buefy need this feature

Nice addition to allow editing of a dropdown object similar to the add new header / footer and trigger a modal or some other event of your choosing.

As you can see in the image if I click edit (for instance) it selects the dropdown item anyway.

![autocomplete-props](https://user-images.githubusercontent.com/5735921/84607685-8c4ecc80-aea6-11ea-8ee1-bcfd781ca243.jpg)

**Comment by jtommy** [comment]
Did you try using `@click.stop` on button ?

**Comment by CromonMS** [comment]
Sorry it was late I should have been more clear, it's on the autocomplete component not the regular Dropdown component. @click.stop does nothing and the autocomplete doesn't seem to have an API for each item (slot-scope="props") as per Dropdown API or if there is it's undocumented behaviour.

Here is an example of the code being used.

``` 
  <b-autocomplete
      v-model="selectedContributor"
      :data="filteredContributors"
      :keep-first="true"
      field="name"
      icon="users"
      size="is-small"
      placeholder="Select Contributor"
      @select="selectContributor"
    >
      <template
        v-if="allowNew"
        slot="header"
      >
        <a @click="addContributor()">
          <span class="has-text-danger"><b>Add New Contributor</b></span>
        </a> 
      </template>
      <template slot-scope="props">
        <div class="columns">
          <div class="column">
            {{ props.option.name }}
          </div>
          <div class="column">
            <button class="button is-info is-small">
              Edit
            </button>
          </div>
        </div>
      </template>
      <template slot="empty">
        No results for {{ selectedContributor }}
      </template>
    </b-autocomplete>
```

**Comment by jtommy** [comment]
Where are you putting click.stop ?

**Comment by CromonMS** [comment]
I tested it within this part
```
            <button
              class="button is-info is-small"
              @click.stop="edit"
            >
              Edit
            </button>
```

and just now tested it on
```
      <template
        slot-scope="props"
        @click.stop="edit"
      >
```

Neither registered the click and just selected the item as per normal behaviour.

**Comment by jtommy** [comment]
I don't undestand your issue.. https://codepen.io/jtommy/pen/WNrGejv?editable=true&editors=101%3Dhttps%3A%2F%2Fbuefy.org%2Fdocumentation%2Fautocomplete

**Comment by CromonMS** [comment]
Okay, sorry it's working now I was updating the wrong component in my code base doh!, seems this works fine now with that example!

Apologies for this!

Thank you for the help.
