### ISSUE TITLE
TagInput value wrong when allow-duplicates is disabled

### ISSUE THREAD

**Issue by darzove** [buefy/buefy#2608]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10/Chrome

### Description

When `allow-duplicates` is disabled (default), and autocomplete is enabled, entering a value twice will remove the tag from UI. 
However the variable bound with v-model is not updated. 

### Steps to reproduce

1. Navigate to https://buefy.org/documentation/taginput#autocomplete
2. Ensure `Allow new tags` is disabled
3. Enter `George`, press enter button
4. Repeat step 3
5. Variable bound to v-model still retains the data for George, but the tag is not present.

### Expected behavior

The variable bound in v-model to reflect what is indicated in the UI.

### Actual behavior

The data for George only disappears if more tags are added or removed - but the state is inconsistent unless action is taken.

**Comment by hjJunior** [comment]
Hello, y'all, I would like to work on this issue, may I?

**Comment by DmytroKuznyetsov** [comment]
Сaught the same issue

**Comment by marcebdev** [comment]
Same issue, I've written my own validator for the time being using `:before-adding`.

**Comment by Thaurin** [comment]
Yes, I've run into this as well. Trying to work around it like @marcebdev but hoping for an official fix soon!

**Comment by daniandl** [comment]
From my own findings, this also happens when you simply click on the already-selected option in the autocomplete again. This removes it from the UI but doesn't update the model or call any events (`input`/`remove`).

**Comment by Thaurin** [comment]
Crap, you're right. I thought I could catch the remove event for this, but it doesn't get fired at all. I'm wondering how fixed it using :before-adding, because I don't see how as it also doesn't get called upon second selection.

**Comment by daniandl** [comment]
> Interestingly, the model gets corrected when a different new value is added: the value that was removed from UI by the second add is then also removed from the model.

I think this is some sort of reactivity caveat, I don't really have time to inspect it any further at the moment sadly

**Comment by Thaurin** [comment]
Same here, so I'll live with this bug for now. There seem to be a few more issues with the TagInput component that I can't figure out getting mysterious "Duplicate keys" warnings from Vue, but am not yet sure if it's me or the component.

**Comment by Thaurin** [comment]
My other issue with the TagInput component mentioned above can be reproduced in [this CodeSandbox](https://codesandbox.io/s/buefy-sandbox-r84p1?file=/src/App.vue). I made a new issue for it: #2673.
