### ISSUE TITLE
Allow specifying position for template Notifications (and not just programmatic)

### ISSUE THREAD

**Issue by a-kriya** [buefy/buefy#2610]
### Description

Currently, the `position` parameter for Notification component only applies to notifications that are instantiated programmatically, as the docs say:

>`position` | Which position the notification will appear when programmatically [opened]

This limits the ability to write rich content for notifications that need to be affixed to one of the edges or corners, since programmatically opened notifications only take text/regular HTML as `message` prop. Being able to use Vue components is not possible, and writing any non-trivial HTML in strings is not ideal.

### Why Buefy need this feature

It is a rather common use-case to embed buttons in notifications to add some interactivity and allow users to take actions directly, and possibly even more complex input handling (think ability to reply within Slack notifications). There was a similar ticket filed earlier, #1739, that had some interest (thumbs-up from multiple people) but got closed by the stalebot.

As an aside, stalebot seems to cause a loss of work of people, duplicate issues (like this), or people trying to fight it to keep their tickets open. It may be better to have tickets tagged as stale, and not auto-close them.

**Comment by jtommy** [comment]
In the next release you'll able to add a slot into programmatic component too ;)
