### ISSUE TITLE
Make the card a scoped slot in b-table

### ISSUE THREAD

**Issue by dipodidae** [buefy/buefy#2611]
### Description

Currently the cards display of b-table is automatically generated and not customizable. I would really like to have the option to customize the display of the card.

### Why Buefy need this feature

This will ensure a maximum of customizability and be in line with the other scoped slots in b-table.

**Comment by jtommy** [comment]
@dipodidae what would you like to customize?

**Comment by dipodidae** [comment]
Right now, it looks like a table. It would be really nice to replace the whole table with a card, that you could compose yourself.

For example: we use the last column for an ellipsis-like dropdown menu. It's not really data; it's an interface element. In the card section, we would like to be able to put it in the bottom right corner of the card.

Our current solution works like this: v-if on the breakpoint; are we desktop? Show b-table. Are we mobile? Show a completely different component. It would be nice to just let b-table handle the breakpoint logic, and be able to compose the card in the way we like it to look.

**Comment by jtommy** [comment]
Surely the card template might be improved but I don't understand your need. If you want to show a completely different component you can hide the table (CSS or js media query) and show an other content.
