### ISSUE TITLE
[Date] Mobile range and multiple selection 

### ISSUE THREAD

**Issue by Tofandel** [buefy/buefy#2614]
**OS/Browser**: Chrome for Android 

### Description

The range and multiple options of the date picker component do not work on mobile, the browser opens the native date picker instead of the buefy one, which does not support those features 

### Steps to reproduce

Go to https://buefy.org/documentation/datepicker/#range
From a mobile device and open the range picker or the multiple date picker

### Expected behavior

Being able to select a range or multiple dates

### Actual behavior
It is not possible to select a range or multiple dates because the native browser date picker is opened
![Screenshot_20200621-223817](https://user-images.githubusercontent.com/6115458/85234744-eeac4d80-b40f-11ea-9f2c-2ab4005be8dc.jpg)

**Comment by jtommy** [comment]
Probably I shouldn't enable native picker when range or multiple because Web API doesn't support it. Btw you should set `mobile-native` to false

**Comment by user501254** [comment]
Setting `mobile-native` works. Had the same issue with Firefox mobile.
