### ISSUE TITLE
Allow hoverable=true and mobile-modal=true

### ISSUE THREAD

**Issue by matthewpull** [buefy/buefy#2616]
### Description

I would like to have a dropdown which is both hoverable and shows the modal on mobile. The desktop experience would have the hoverable behaviour, while the mobile experience would have the mobile modal behaviour. As mobile devices (typically) cannot hover, I see little overlap between the two cases.

### Why Buefy need this feature

There are many examples of where triggering a dropdown on hover is a good user experience on desktop (this is why the feature is supported). Similarly, the card modal is a good user experience on mobile (again, why the feature was added).

However, it is not currently possible to enable both experiences at once, short of creating two identical dropdowns and using media queries to `display: none` as appropriate (but this is highly inefficient).

**Comment by jtommy** [comment]
I don't think it's a good idea to open a modal on hover, it's very tricky to be honest

**Comment by matthewpull** [comment]
Ah sorry, I think I may have misrepresented it - it would only hover on desktop (not as a modal).

So, to be clear, there are two disjoint cases:

Mobile devices: touch input (so no hover), will display modal
Desktop devices: hover, will display standard dropdown

**Comment by service-paradis** [comment]
You are right. Dropdown will never be displayed as a modal on mobile fi it is hoverable.
https://github.com/buefy/buefy/blob/dev/src/components/dropdown/Dropdown.vue#L143

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/8c2f62a6a2a84c3a2c576e8583a1e3216ab7a8a2#diff-30bb15acbc5eeb9868ab0d2353db44dfL144
