### ISSUE TITLE
Possible B-step vertical startingPoint: is down activeStep: is last ?

### ISSUE THREAD

**Issue by teuk1** [buefy/buefy#2617]
Hi Buefy,

First of all, thank you for your work and your responsiveness to requests.
I have a little request that might improve Buefy Steps.

Would it be possible to implement the possibility to change the direction of the steps animations and starting point.
I quickly draw an example !

Now
● my birth
|
o my first computer
|
o my new vueJS application

Wishes
● my new vueJS application
|
● my first computer
|
● my birth

### Description
Invert the possibility of vertical b-steps default disposition.
(before : the first at top and the last at bottom | after, whith vertical-start-point-option : the first at bottom and the last at top)

Invert the activeStep possibility should be awesome too.
In the vertical (this option could be on horizontal way also), this to choose directly the last step is active instead of each time calculate the number of elements in the component before and assign this value to data return.

### Why Buefy need this feature
This feature would permit to read the last chronological event first.
ActiveStep on the last element is a very useful alter way to show graphically where you are and all the steps that have been done 

Thanks a lot!
;)

**Comment by teuk1** [comment]
@jtommy any interest for this?

**Comment by jtommy** [comment]
@service-paradis what do you think?
