### ISSUE TITLE
Modal: Display close button in mobile version

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2621]
### Overview of the problem

**Buefy** version: ^0.8.20
**OS/Browser**: Google Chrome 85.0.4173.2 (Official Build) dev (64-bit)

### Description
![image](https://user-images.githubusercontent.com/8303937/85458471-124ecf80-b599-11ea-954b-757363eb8825.png)

### Steps to reproduce

My custom component:
```html
<div class="modal-card" style="width: auto;">
    <section class="modal-card-body is-titleless">
        Content...
    </section>
</div>
```

Parent component:
```ts
this.$buefy.modal.open({
    parent: this,
    component: MyCustomComponent,
    hasModalCard: true,
    trapFocus: true,
})
```
Example in codepen:
https://codepen.io/fabiofdsantos/full/oNbWMPq

### Expected behavior

Display [x] button properly.

### Actual behavior

[x] is hidden in mobile version (e.g. 320x568).

**Comment by jtommy** [comment]
Please reproduce it on codepen or similar

**Comment by fabiofdsantos** [comment]
> Please reproduce it on codepen or similar

https://codepen.io/fabiofdsantos/full/oNbWMPq

**Comment by service-paradis** [comment]
The x is there, but white:
![image](https://user-images.githubusercontent.com/12817388/85470436-06551480-b57d-11ea-91eb-ece7f3ef3823.png)

Does it looks the same using Bulma's only modal?

**Comment by fabiofdsantos** [comment]
@service-paradis 
Seems to be related with `modal-card` usage.

I replaced:
```html
<div class="modal-card" style="width: auto;">
    <section class="modal-card-body is-titleless">
        Content...
    </section>
</div>
```

With: 
```html
<div class="modal-content">
    <div class="box">
        Content...
    </div>
</div>
```

Et voilá:
![image](https://user-images.githubusercontent.com/8303937/85528441-c71dd680-b603-11ea-8318-9a6bc792fa47.png)

**Comment by fabiofdsantos** [comment]
But.. It requires the following "hack" to fix modal margins in mobile version:
```sass
.modal-content {
  max-width: calc(100vw - #{$modal-card-spacing})
}
```

See: https://github.com/jgthms/bulma/issues/2387#issuecomment-631421234

**Comment by Tofandel** [comment]
It's because on the modal the 'x' is assumed to be displayed on the overlay which is black and the close is white, so if your content is white and arrives to the arrow, the arrow becomes invisible
In #2586 on card modals that x is not shown by default and you need to show it inside your card modal using a `<button class="delete">` which is the bulma way and will be visible

Btw clicking outside of the card also closes the modal

**Comment by Tofandel** [comment]
`.modal-close {
    mix-blend-mode: difference;
}`
Problem solved

**Comment by fabiofdsantos** [comment]
I think the normal behaviour should be `modal-card` acting as `modal-content`. Or use `modal-content` instead.
