### ISSUE TITLE
Make table column sorting three state (ascending, descending, none)

### ISSUE THREAD

**Issue by Saunved** [buefy/buefy#2622]
### Description

Buefy tables allow you to sort columns in ascending or descending order. However, once you click on sort for any column, there is no neutral or initial state. It either stays in ascending or descending order. There are ways to reset the sort key, but I propose that we have an option where the sorter goes from "ascending" to "descending" and back to a "neutral" state. This could be enabled by having a Boolean attribute like ```neutralSort``` on ```<b-table-column>``` component which defaults to ```true```.

Here's a quick example of how this would look (taken from the Angular Material page):
![](https://media.giphy.com/media/U7bTq8g8MiUEVExPOQ/giphy.gif)

### Why Buefy needs this feature

This is a common feature available in a lot of existing frameworks. You can see this behavior in the Angular material library [here](https://material.angular.io/components/table/overview#sorting). It's quite useful for getting to the original state of the table quickly instead of hitting refresh.

**Comment by EricRabil** [comment]
I'd like to note that though the Buefy docs get around this by including a `Reset Sorting` button, many users expect a three-state sorting system and as such this would feel less awkward than clicking a button to explicitly reset sorting.
