### ISSUE TITLE
[CarouselList] Bugs and improvements

### ISSUE THREAD

**Issue by Tofandel** [buefy/buefy#2625]
**Buefy** version: 0.8.9 - 0.8.20

This is a list of bugs of the carousel list that was introduced in 0.8.9, to be fixed by #2619 

# 1 Bounds
It allows for the list to go too far and to be dragged too far as well

### Actual
![image](https://user-images.githubusercontent.com/6115458/85626524-7ba01280-b66d-11ea-97c3-1a58f3ccb7e8.png)
![Peek 2020-06-24 23-00](https://user-images.githubusercontent.com/6115458/85627461-d128ef00-b66e-11ea-9209-9123e9a06f59.gif)

### Expected
![image](https://user-images.githubusercontent.com/6115458/85627632-19481180-b66f-11ea-8ea4-885b83077696.png)
![Peek 2020-06-24 23-01](https://user-images.githubusercontent.com/6115458/85627469-d5550c80-b66e-11ea-9fa2-01a208a23b0a.gif)

# 2 Breakpoints
The breakpoints were not using the correct settings for items-to-list and some other props

# 3 Config prop
The config prop is completely omitting vue's features and v-bind should have been used

# 4 Events
The dragstart event could be called multiple times and create multiple event handlers, those same events were also not cleared on item destroyed

# 5 Click and asIndicator
The click handler was not working correctly, it should also be possible to scroll through the list without having the item change

# 6 Scroll index
Should support floating values and scroll to the middle when clicked
![image](https://user-images.githubusercontent.com/6115458/85644593-b1f28780-b697-11ea-9857-ca906dabb589.png)

# 7 Refresh
The elements needs to be refreshed in a super less than ideal way when the bounding box of the element is updated externally (by class change for example)
This should be handled automatically with a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2619
