### ISSUE TITLE
Property "active" on "b-navbar-dropdown" is not applied

### ISSUE THREAD

**Issue by giudicelli** [buefy/buefy#2627]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.10
**OS/Browser**:  Chrome 83.0.4103.106

### Description

When activated the property "active" on a "b-navbar-dropdown" is not applied and has no effect.

### Steps to reproduce

`<b-navbar-dropdown :active="true">
  <template slot="label">
    Lorem Ipsum
  </template>
  <b-navbar-item tag="div">
    Dolor sit amet
  </b-navbar-item>
</b-navbar-dropdown>
`

### Expected behavior

The drop down "Lorem Ipsum" should appear active in the navbar.

### Actual behavior

The drop down "Lorem Ipsum" does not appear active in the navbar.

**Comment by service-paradis** [comment]
It does work:
https://codepen.io/service-paradis/pen/jOWLVPw?editable=true&editors=101%3Dhttps%3A%2F%2Fbuefy.org%2Fdocumentation%2Fnavbar

But it will close the moment you click outside the menu if the props `close-on-click` is true.

**Comment by giudicelli** [comment]
Ok, so it seems you have a documentation issue, because I would have expected b-navbar-dropdown's active property to have the same behavior as b-navbar-item's. Actually the documentation is exactly the same for both.
Which brings another question, imagine I have an active b-navbar-item inside a b-navbar-dropdown, how can I make the drop down link active in the meaning of b-navbar-item? Because right now my users have no clue which road is active, since it's hidden inside a drop down menu :)
