### ISSUE TITLE
Is there a way to use the pagination without the totals?

### ISSUE THREAD

**Issue by katlimruiz** [buefy/buefy#2628]
### Description

I have a costly entity to show the list for. I want to use Buefy table and pagination. However, I would like to have this:

Today
1-10 of 99 < >

I want only
< >

It should be possible to use the pagination to do that.

And we do not want to show the total, because is costly to calculate it (I know there other backend solutions to do it, but I would like to keep this on the front alone) (and also I know I can do the buttons myself).

### Why Buefy need this feature

More uses cases for the pagination. I would think this use case is common.

**Comment by jtommy** [comment]
You can hide it using CSS as workaround

**Comment by jtommy** [comment]
In the next breaking you can override pagination using a slot
