### ISSUE TITLE
Notification cannot find container element when opened inside a web component

### ISSUE THREAD

**Issue by SamVsCode** [buefy/buefy#2629]
#### Issue with the notification's container when opened inside a web-component

Notification/Toast Can take up a prop **container** to specify the parent element in which it should render.
As documented [here ](https://buefy.org/documentation/notification/#api-view)

> container - DOM element the toast will be created on. Note that this also changes the position of the toast from fixed to absolute. Meaning that the container should be fixed.

**ISSUE:** As per the code [here](https://github.com/buefy/buefy/blob/dev/src/utils/NoticeMixin.js#L114)
`this.parentTop = document.querySelector((this.newContainer ? this.newContainer : 'body') + '>.notices.is-top')`

This would be able to find the element if the notification is not rendered inside a web component. But if it is being used inside a web-component created through vue cli, it would **fail** as the document.querySelector won't be able to find the desired element as its a part of shadow dom.

### Why Buefy need this feature

To fix this issue we can add a statement to check if the notification is being opened inside a shadowRoot or not.
This would help use Buefy not break any notification/toast/snackbar when opened inside a web component and used with a container prop.

**Comment by codref** [comment]
Despite this being closed, I too had to find a workaround. Without patching the source a solution could be to use `b-notification` inside an element with a fixed position.  
Follows an example:  

```html
    <div style="position: fixed;bottom: 0; right: 0; margin: 1em; max-width: 40%; min-width: 20%">
      <b-notification
              v-model="notifyActive"
              :type="notifyType"
              has-icon
              position="is-bottom-right"
              :duration="5000"
              :auto-close="true"
              :message="notifyMessage"
              :closable="true" />
    </div>
``` 

This roughly replicates the behavior of a *snackbar* - although without patching the code and support `shadowRoot`, these components cannot be used from within a Web Component - when Buefy is adding new elements to the DOM at runtime.
