### ISSUE TITLE
Modal: Normalize position of footer buttons

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2632]
### Overview of the problem

**Buefy** version: ^0.8.20

### Description

The position of footer buttons differ between components.

Modal component:
https://buefy.org/documentation/modal#component

A dialog:
https://buefy.org/documentation/dialog#confirm

### Steps to reproduce

N/A

### Expected behavior

I think it's preferable to use the same behaviour of `modal-card-foot` for both Modals and Dialogs.. Instead of defining a `custom-class` all the time.

### Actual behavior

Modal:
`modal-card-foot` has buttons aligned to the left.

Dialog:
`modal-card-foot` has buttons aligned to the right.

**Comment by service-paradis** [comment]
There is no button in a basic Buefy Modal. This is only an example in the doc to show that we can use card content inside a modal. People can use display anything they want and change button position if they need to.

**Comment by fabiofdsantos** [comment]
Ok, agreed!
