### ISSUE TITLE
Dynamic label on <b-table-column> breaks table

### ISSUE THREAD

**Issue by wrabit** [buefy/buefy#2633]
### Overview of the problem

**Buefy** version: 8.2
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome / OSX latest

### Description

https://codepen.io/willabbott/pen/eYJGeaY?editors=1010

A dynamic label which updates when data is added to the table, adds an additional column with each change.

**Comment by robertmarney** [comment]
Add a key to table element

:key=roles.length
