### ISSUE TITLE
Form submission buttons don't allow icons

### ISSUE THREAD

**Issue by marcebdev** [buefy/buefy#2634]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS/any (FF, Chrome, Safari)

### Description

When making a `<b-button>` element as a form submission button with `tag="input"` and `native-type="submit"` icons aren't allowed. The `tag="input"` seems to be specifically what breaks this.

### Steps to reproduce

1. Make `<b-button>`
2. Add properties to set it up as a form input submission (via docs)

### Expected behavior

Icons should be allowed in form submission buttons. Otherwise, it seems you're left to finding hacks around this or using a regular button with `$refs` or something to submit forms.

### Actual behavior

Icon does not display. Something simple like.

```
<b-button
  tag="input"
  native-type="submit"
  value="Login"
  icon-right="login-variant"
/>
```

**Comment by service-paradis** [comment]
```
<b-button
  native-type="submit"
  value="Login"
  icon-right="login-variant"
/>
```
The above should work fine to submit.

input element with class `button` are not supported in Bulma (https://github.com/jgthms/bulma/issues/2407)

**Comment by marcebdev** [comment]
@jtommy Appreciate it, indeed removing the tag prop does return normal behavior. Appreciate the clarification as to how/why, in such case docs should be updated.

https://buefy.org/documentation/button/#tags
