### ISSUE TITLE
[Table] Add a delay between text input and the filter event for big tables

### ISSUE THREAD

**Issue by MauJFernandez** [buefy/buefy#2636]
I have a pretty large table (using a large per-page prop), so triggering a search is sluggish, maybe there can be a prop to set a delay to the filter-event until I can enter the full text I want to search.

EDIT: Typo, the --> there.

**Comment by Sc0ra** [comment]
Proposed solution:

- Implement the debounce function in src/utils
- Add a debounce props (number) to indicates the debounce time (in ms)
- Refactor the filters watch handler into a method: handleFiltersChange
- Use the debounce function in the watch handler if the props is defined

I can write a PR if the strategy is good for you @jtommy

**Comment by jtommy** [comment]
@Sc0ra sure
