### ISSUE TITLE
Possible to make tabs work with SSR in nuxt.js? 

### ISSUE THREAD

**Issue by patni1992** [buefy/buefy#2637]
Buefy version: 0.8.20
Nuxt version: 2.11.0

### Description
Possible to make tabs work with SSR in nuxt.js? 

The b-tabs is not rendered SSR in nuxt.js. I suppose it has to do with this code.

`   mounted() {
        this.activeTab = this.getIndexByValue(this.value || 0)
        if (this.activeTab < this.tabItems.length) {
            this.tabItems[this.activeTab].isActive = true
        }
        this.refreshSlots()
    }`

https://github.com/buefy/buefy/blob/dev/src/components/tabs/Tabs.vue#L184

### Steps to reproduce
Create a nuxt project.
Copyr b-tabs examples from the buefy documentation.

### Expected behavior
The markup should be rendered on the server. No flashes.

### Actual behavior
tabs rendered on the browser only.

**Comment by febrihidayan** [comment]
Hey @patni1992,
I use nuxt-buefy v0.3.28 and nuxt v2.12.2.
the tab component has no errors until now when I use.
all buefy components currently run smoothly on the version of nuxt v2.12.2.

**Comment by patni92** [comment]
If you place another component next to the tabs, it's more obvious to see it. You can see component X is being rendered on the server while the tabs flashes and render on the client-side.

**Comment by febrihidayan** [comment]
try checking the following link [https://nuxtjs.org/api/components-client-only/]( https://nuxtjs.org/api/components-client-only/)

**Comment by Tofandel** [comment]
The logic of tabs and other components having children was rewritten in 0.9, you'd need to check but I think the new logic fixes the issue
