### ISSUE TITLE
Duplicated modals with sliding animation

### ISSUE THREAD

**Issue by CobraClutch** [buefy/buefy#2642]
If you double-click a button that launches a modal with a 'slide-next' or 'slide-prev' animation, you can launch the modal multiple times. You have to click pretty fast to make it happen, but for those users that double-click on everything, this is a problem.

I've tried click.stop and click.prevent on the button, but no dice.

A possible hacky fix would an option to have the animation only apply to the modal content, and not the modal-background. But it would be nice if there was some way to keep the modal from triggering multiple times.

Codepen:
https://codepen.io/curtis_jigawatt/pen/GRoyNNz?editable=true&editors=101%3Dhttps%3A%2F%2Fbuefy.org%2Fdocumentation%2Fmodal

**Comment by service-paradis** [comment]
You can use something like this to be sure your modal is opened only once:
https://codepen.io/service-paradis/pen/rNeaWqp?editors=1011
