### ISSUE TITLE
Notification Close using Click

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#2645]
I'm using b-notification and on mobile, it's very difficult to close the notification using the close icon and your finger.

There should be an option to close a notification by clicking (or tapping) anywhere in the notification box vs. using the close icon.

**Comment by febrihidayan** [comment]
I made it in [ Programmatically opening](https://buefy.org/documentation/notification#programmatically-opening).
To set the default duration [Constructor options](https://buefy.org/documentation/constructor-options) -> defaultNotificationDuration or defaultNotificationPosition.
I hope this helps

**Comment by service-paradis** [comment]
I dont think there is a way to add custom events when using notification programmatically at the moment. Could be useful to add!

If you're using inline `b-notification` you can add an `@click.native` event:
```
<b-notification :active.sync="isActive" aria-close-label="Close notification" @click.native="isActive = false">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id fermentum quam. Proin sagittis, nibh id hendrerit imperdiet, elit sapien laoreet elit
</b-notification>
```

**Comment by kerbo** [comment]
click.native works...

Maybe this should be an option. Not sure you need a close button for a notification. Generally clicking anywhere in the window seems got work better especially on mobile since the button is hard to tap with the finger.

**Comment by service-paradis** [comment]
You can remove the close button with this prop: `:closable="false"`
