### ISSUE TITLE
Request Navbar slot in the middle

### ISSUE THREAD

**Issue by febrihidayan** [buefy/buefy#2646]
Hey,
Adding the Navbar slot in the middle might be silly. But this is very necessary if someone needs it.
I hope this will be available in the next Buefy version.
Thanks

**Comment by jtommy** [comment]
Can you explain better? Or describe your need?

**Comment by febrihidayan** [comment]
@jtommy 
I need a navbar in the middle. I was inspired by the Facebook navbar.
Take a look here [https://dev.to/nikhilroy2/facebook-navbar-design-57cn](https://dev.to/nikhilroy2/facebook-navbar-design-57cn)

**Comment by holtolee** [comment]
Or maybe jsut a is-centered prop ?
