### ISSUE TITLE
Maxlength for Numberinput

### ISSUE THREAD

**Issue by vanderb** [buefy/buefy#2651]
```html
<b-numberinput v-model="value" :min="min" :max="max" @input="onValueChanged"/>
```

``` javascript
onValueChanged(value) {
  this.$nextTick(() => {

    // Set maxlength based on char-length of max-attribute
    const maxlength = this.max.toString().length;
          
    // Restrict value to maxlength
    this.value = parseInt(value.toString().substr(0, maxlength));
  })
}
```

### Description

Implement a maxlength-attribute for numberinput-component.

### Why Buefy need this feature

I know native number-inputs do not have the maxlength attribute out of the box. 
But I think it could be a helpful to restrict the maximum not only with key up/down and plus/minus, but also with native input.

**Comment by jtommy** [comment]
Maxlenght ? Isn't max enough?

**Comment by 304NotModified** [comment]
I would also think max should be enough

- maxlength 1 => max 9,
- maxlength 2 => max 99,
- maxlength 3 => max 999

etc
