### ISSUE TITLE
Datepicker year selection max value limitation makes year selection too hard

### ISSUE THREAD

**Issue by madhukar4e** [buefy/buefy#2653]
When you click on the year dropdown of Datepicker, it limits the max value to current year + 3 years and it makes sense. But if I select an year 2000 and then open the year dropdown again to change it again, it limits the max years displayed to current selection + 3 years. So, in this case I would only see till 2003 and needs multiple selections to go back to an year like 2020.

This is more problematic if the input is disabled and the user has to rely on the dropdown only.

Can we please keep the max year to current year + 3 years always and not current selection + 3 years?

**Comment by jtommy** [comment]
You can edit the default behaviour using `years-range` prop
