### ISSUE TITLE
B-field: Message property is not placed below controls when has addons

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2658]
### Overview of the problem

**Buefy** version: ^0.8.20

### Description

Messages are not being placed below `b-field` main content when `has-addons` class is applied.

### Steps to reproduce

```html
<b-field position="is-centered" message="This is a random message">
    <b-input placeholder="Search..." type="search" icon="magnify"/>
    <p class="control"><button class="button is-info">Search</button></p>
</b-field>
```

### Expected behavior

The message should appear below controls.

### Actual behavior

![image](https://user-images.githubusercontent.com/8303937/86855147-afd5f300-c0b1-11ea-910b-7a3c0d535cf8.png)

**Comment by fabiofdsantos** [comment]
If you agree on adding `flex-wrap: wrap;` to `has-addons`, I can open a pull request.

**Comment by service-paradis** [comment]
There is a workaround at #1226
