### ISSUE TITLE
Wrong TypeScript declarations for BDialogConfig

### ISSUE THREAD

**Issue by giudicelli** [buefy/buefy#2659]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.10
**OS/Browser**: N/A

### Description

The TypeScript declaration of BDialogConfig does not match the JavaScript code, nor the documentation.

It should be:

export declare type BDialogConfig = {
**\-    onConfirm?: (value: string) => any;**
**+   onConfirm?: (value: string, dialog: BComponent) => any;**
(...)
**+   closeOnConfirm?: boolean;**
}

**Comment by service-paradis** [comment]
I think it is ok right now... Are you sure you use 0.8.20?

https://github.com/buefy/buefy/blob/dev/types/components.d.ts#L129
https://github.com/buefy/buefy/blob/dev/types/components.d.ts#L117
