### ISSUE TITLE
Segfault while deploying Buefy project to Now.sh

### ISSUE THREAD

**Issue by JesusCrow** [buefy/buefy#266]
### Overview of the problem
Segmentation fault (core dumped) while using on Nuxt.js project and deploying to Now.sh.
Works in localhost.
[Reproduction repo](https://github.com/JesusCrow/buefy-error-now)

**Buefy** version: [0.5.0]
**Vuejs** version: [2.4.2]
**Vuejs** version: [2.3.1]
**OS/Browser**: Windows 10

There is no `vue` in `package.json`, this is from `yarn.lock`

### Steps to reproduce
1. `vue init nuxt/starter buefy-test`
2. `cd buefy-test && yarn`
3. `yarn add buefy`
4. `yarn add node-sass sass-loader -D`
5. create file [`assets/css/main.scss`](https://github.com/JesusCrow/buefy-error-now/blob/master/assets/css/main.scss)
6. create file [`plugins/buefy.js`](https://github.com/JesusCrow/buefy-error-now/blob/master/plugins/buefy.js)
7. edit [`nuxt.config.js`](https://github.com/JesusCrow/buefy-error-now/blob/master/nuxt.config.js), add:
```
  css: ['@/assets/css/main.scss'],
  plugins: ['~plugins/buefy'],
```
8. deploy to now.sh with `now --public`
9. get error
```
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 13 main dependencies…
> ✓ Installed 990 modules [40s]
> ▲ npm run build
> > buefy-test@1.0.0 build /home/nowuser/src
> > nuxt build
> 2017-08-19T11:26:39.150Z nuxt:build Building...
> 2017-08-19T11:26:39.170Z nuxt:build App root: /home/nowuser/src
> 2017-08-19T11:26:39.170Z nuxt:build Generating /home/nowuser/src/.nuxt files...
> 2017-08-19T11:26:39.186Z nuxt:build Generating files...
> 2017-08-19T11:26:39.195Z nuxt:build Generating routes...
> 2017-08-19T11:26:39.228Z nuxt:build Building files...
> Segmentation fault (core dumped)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 139
> npm ERR! buefy-test@1.0.0 build: `nuxt build`
> npm ERR! Exit status 139
> npm ERR!
> npm ERR! Failed at the buefy-test@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging out
put above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-08-19T11_26_56_746Z-debug.log
```

**Comment by Tirke** [comment]
Quite possible that it's not an issue with Buefy. Must be on now.sh side. Low disk space can lead to segfault.

**Comment by asumranphan** [comment]
I have a same problem and will show my infomation below.

1. vue init nuxt-community/starter-template nuxt-starter
2. yarn add node-sass sass-loader --dev
3. yarn add foundation-sites
4. create new stylesheet app.scss and _settings.scss in ~assets/
````scss
// _settings.scss
$black: #000000;
````

````scss
// app.scss
@import 'settings';
@import '~foundation-sites/scss/foundation';

body {
  background: $black;
}
````
5. add some configs in nuxt.config.js
````javascript
{
  // ...
  css: [
    { src: '~assets/app.scss', lang: 'scss' }
  ]
}
````
6. try build package on local is normally but if deploy on now.sh. i got an errors when build package processing.
````
> 2017-09-29T17:41:46.849Z nuxt:build App root: /home/nowuser/src
> 2017-09-29T17:41:46.849Z nuxt:build Generating /home/nowuser/src/.nuxt files...
> 2017-09-29T17:41:46.854Z nuxt:build Generating files...
> 2017-09-29T17:41:46.859Z nuxt:build Generating routes...
> 2017-09-29T17:41:46.881Z nuxt:build Building files...
> Segmentation fault (core dumped)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 139
> npm ERR! nuxt-starter@1.0.0 build: `nuxt build`
> npm ERR! Exit status 139
> npm ERR!
> npm ERR! Failed at the nuxt-starter@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-09-29T17_41_52_210Z-debug.log
````
7. but if me disable import like this, it works!!
````scss
// app.scss
@import 'settings';
// @import '~foundation-sites/scss/foundation';

body {
  background: $black;
}
````
