### ISSUE TITLE
Allow "increment-minutes" option for Clockpicker

### ISSUE THREAD

**Issue by pachiraDIG** [buefy/buefy#2662]
### Description

I'd like to suggest to allow 4 different values: 5, 10, 15, 20 (maybe 20 isn't necessary?).
This way, devs can still control increments, just like the other picker components.

### Why Buefy need this feature

The clock picker is a very nice a & fancy tool, but I believe this option is simply missing.

Thank you!

**Comment by jtommy** [comment]
Yes, it might be a good addition

**Comment by ryo-gk** [comment]
This is nice.
But it looks like that this feature has already been developed and is just undocumented.

When I pass the `increment-minutes` props like this,
```
<template>
    <section>
        <b-field>
            <b-switch v-model="isAmPm">AM/PM</b-switch>
        </b-field>
        <b-field label="Select time">
            <b-clockpicker
                rounded
                placeholder="Click to select..."
                icon="clock"
                :increment-minutes="15"
                :hour-format="format">
            </b-clockpicker>
        </b-field>
    </section>
</template>
```

then Clock picker render like this.

![image](https://user-images.githubusercontent.com/62658104/91630021-0ce28b00-ea09-11ea-9d62-c1f76aa0d082.png)

Is it right..?
I'm sorry if I misunderstand this.
Thank you!

**Comment by jtommy** [comment]
And does it work?
I completely forgot it 👍

**Comment by ryo-gk** [comment]
Yes, it works!
May I write docs about this in "Clockpicker > API > Properties"?

**Comment by jtommy** [comment]
Ok, thanks
