### ISSUE TITLE
Autocomplete doesn't work with computed property listings

### ISSUE THREAD

**Issue by azmatzuberi** [buefy/buefy#2670]
### Overview of the problem

**Buefy** version: Nuxt-Buefy 0.3.27
**Vuejs** version: Nuxt 2.0
**OS/Browser**:
Chrome
### Description

When using computed property to derive timezones for autocompletion from moment js, autocompletes fails to work

### Expected behavior

Autocomplete should filter the listings

### Actual behavior

Autocomplete doesn't filter results and instead shows the entire list unfiltered

**Comment by jtommy** [comment]
Can you reproduce it on codepen or similar?
