### ISSUE TITLE
Taginput after each selection dropdown list is closing when common data gets from computed

### ISSUE THREAD

**Issue by DmytroKuznyetsov** [buefy/buefy#2672]
**Overview of the problem**
Buefy version: 0.8.20
Vuejs version: 2.6.11
OS/Browser: Windows Chrome/Firefox

**Description**
After each selection dropdown list is closing when common data gets from computed property.
Also when I using vuex store and computed props I should type something firstly for opening the dropdownlist  with open on focus attribute. 
https://codepen.io/dmytro-kuznetsov/pen/NWxMYNQ?editors=1010

**Steps to reproduce**
Click on Tagsinput - dropdown is not shown
Start typing, it shows the autocomplete
Click away
Click on the tagsinput again, then it shows the autocomplete immediately.
Select one item from dropdown list
Dropdown list hides

**Expected behavior**
It should show the dropdown list when you click on the tagsinput.
It should show the dropdown list when you select one of item.

**Actual behavior**
You need to start typing the first time you click on the tagsinput.
You need to click one more time for opening the dropdown list for selection one more item

**Comment by service-paradis** [comment]
You use `filteredTags` for your data and this property is only updated when watching `compData`. You will need to watch this property immediately if you want to have some initial data. That is the reason why the first click does not open the dropdown. You will need to change your watch function to this:
```
watch: {
  compData: {
    handler(val) {
      this.filteredTags = val 
    },
    immediate: true
  }
}
```
