### ISSUE TITLE
B-Table Columns Header Disappears 

### ISSUE THREAD

**Issue by taracha-r** [buefy/buefy#2674]
### Overview of the problem
A column header in b-table  disappears. 

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**:
Chrome Browser

### Description
If you have a paginated table with 2 only pages, a single column and the second page is less then the `per-page` value. 

### Steps to reproduce

1. Create a paginated b-table.
2. Have only one column.
3. Have a `per-page` that is a little more than 1/2 of the total data available.

### Expected behavior

Column header to be on both pages.

### Actual behavior

Column header disappears on the second page

https://codepen.io/Broatlas/pen/MWKBLgQ?editors=1010

![b-table](https://user-images.githubusercontent.com/7542220/87356493-29e1fe00-c530-11ea-9626-798a17739f3f.gif)

**Comment by jtommy** [comment]
Fixed in the next version

**Comment by taracha-r** [comment]
> Fixed in the next version

oops.


Sorry about that thanks :)
