### ISSUE TITLE
Ability to display number inside b-menu-item

### ISSUE THREAD

**Issue by lozitskiys** [buefy/buefy#2675]
### Description

It is often useful to display some number inside menu item. For example new incoming messages or other stuff.
Gmail example:
![image](https://user-images.githubusercontent.com/4169521/87414538-97e00100-c5d4-11ea-8370-087a88c49424.png)

### Why Buefy need this feature

Buefy already has super cool sidebar component, it would be great to add new simple prop to BMenuItem component.

**Comment by jtommy** [comment]
You can add it yourself into menu item slot, don't you ?
