### ISSUE TITLE
Header disappears when using custom header search scope slot

### ISSUE THREAD

**Issue by scriptburn** [buefy/buefy#2676]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome Browser Version 83.0.4103.116 (Official Build) (64-bit)

### Steps to reproduce

customize the search input using a scoped slot.

### Expected behavior

Header should be visible all time

### Actual behavior

if you enter some thing which returns the result header dissapears.
Try entering a first name from "data" , header will dissapear 
https://codepen.io/rajneeshojha123/pen/gOPdppP

**Comment by jtommy** [comment]
Please add a label and or custom-key to table column
