### ISSUE TITLE
B-step, do not hide other steps on mobile

### ISSUE THREAD

**Issue by wrabit** [buefy/buefy#2680]
To have an option not to hide inactive steps on mobile.

Because it doesn't look good in this situation:

![image](https://user-images.githubusercontent.com/5918271/87642427-cd5a2b00-c749-11ea-8d73-548a42632754.png)

**Comment by service-paradis** [comment]
There is a prop named `mobile-mode` where you can control the behavior on mobile.

**Comment by wrabit** [comment]
@service-paradis I had seen this but the outcome for me is not desirable.

**Comment by service-paradis** [comment]
@wrabit And you can do it by passing `null` to `mobile-mode`.
> minimalist: Only the active Step is displayed, compact: Step label is displayed only for the active, null: Will keep the same behavior as desktop

**Comment by wrabit** [comment]
@service-paradis super, thanks
