### ISSUE TITLE
B-datepicker: Different cell padding for mobile

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2682]
### Description

Reduce the padding of `.datepicker-cell` for mobile screens.

Before:

![image](https://user-images.githubusercontent.com/8303937/87679042-9a2c9180-c773-11ea-879e-a5329c87e21a.png)

After (an example of `padding: 0.3rem 0.4rem;`):

![image](https://user-images.githubusercontent.com/8303937/87679162-c0523180-c773-11ea-9fbb-20e53cb27585.png)

### Why Buefy need this feature

It will be nice to improve mobile compatibility without the need of `mobile-native` property.

**Comment by febrihidayan** [comment]
Hey @fabiofdsantos 
have you tried it on mobile?

**Comment by jtommy** [comment]
@fabiofdsantos did you try the same code but not into a modal ? I don't see any issues
