### ISSUE TITLE
Permanent lazy loading of tabs

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#2685]
### Description

Right now, `BTabs` has a `destroy-on-hide` prop that destroys the content of a `BTabItem` whenever it's hidden.
It would be useful to have a complementary mechanism (`create-on-open`?) that only renders tabs whenever they're opened but does not destroy them on hide.

Some similarities and differences:

<table>
  <tr>
    <td><code>destroy-on-hide</code></td>
    <td><code>create-on-open</code></td>
  </tr>
  <tr>
    <td>Tab contents are only rendered when the user opens the tab </td>
    <td>Tab contents are only rendered when the user opens the tab </td>
  </tr>
<tr>
<td>Tab contents are destroyed on hide</td>
<td>Tab contents are permanent (once they've been rendered)</td>
</tr>
<tr>
<td>At most one rendered tab at any given time</td>
<td>At least one rendered tab at any given time</td>
</tr>
</table>

### Why Buefy need this feature

Having `destroy-on-hide` enabled is useful to prevent eager initialization of multiple tabs at once (eg. tabs that initialize their data via XHR on mount), but also leads to unnecessary re-initializations (eg. tab A is open and initialized → tab B is open and tab A is destroyed → tab A is open again and needlessly re-initializes itself); having lazily loaded tabs would solve this problem.

**Comment by jtommy** [comment]
I understand need but you might do yourself without using destroy-on-hide
