### ISSUE TITLE
Table: Add way to update table filters programatically

### ISSUE THREAD

**Issue by Verdoso** [buefy/buefy#2689]
Hi there,

Hi there, Table filtering is working fine but I think it would be great to have some way to update the filters from another components. For example, I have a table of books and in a different component I have list of authors, so it would be nice that when someone selects an author in this second component, one could update the table filter to just display the books of that author using the already provided filters.

I know how to do it externally, just filtering the data for the table, but IMHO it would be nice to do it from the table.

As the filters are defined as inputs bound to an array that is watched, modifying the inputs directly does not work, and modifying the filters array directly in the table breaks the binding, and then changes to the array after that are not detected.

So, before getting into the "how to do it", do you also think it would be useful?

Thanks

**Comment by jtommy** [comment]
You can use header slot and write your implementation of search otherwise you might to update filters data by ref, this.$refs.table.filters['colname']

**Comment by Verdoso** [comment]
Hi,

As mentioned before, I already tried that and it does not work because if you create an entry in the filters array programatically, then the value is not bound/watched and modifying it afterwards does not activate the filters_change event any more.
