### ISSUE TITLE
Table: Header disappearing when one column + searching + pagination and results go down to one page

### ISSUE THREAD

**Issue by Verdoso** [buefy/buefy#2690]
Hi,

If you define a table with one column that is searchable and you are using pagination, if you filter your results to there is less than on page of them, the whole header disapperars and you can no longer see the column title & the filter; and you are stuck there as you cannot change the filter any more.

It is easily reproducible with current version 0.8.20.

Steps to reproduce:

- Go to Table - Pagination and sorting documentation sample: https://buefy.org/documentation/table#pagination-and-sorting
- Open the asociated codepen
- Edit the HTML and remove all the b-table-column elements except one (I've tried with the first and second)
- Make the remaining b-table-column searchable
- Go to the result and introduce a value in the input box so the results are down to 1 page

.- Tested with current Firefox and Chrome.
.- Tested with a regular table with no pagination, I was not able to reproduce it.
.- Tested with a backend-paginated table, bug is there. That's actually how I found about it.

Cheers,

**Comment by BALOTIAS** [comment]
Might relate to this #2613

**Comment by Verdoso** [comment]
Does that mean it is another symptom of #2613? Is this already fixed in an unspecified version?
Way to encourage participation.

**Comment by service-paradis** [comment]
It means it will be fixed in the next Breaking release (0.9.0)
