### ISSUE TITLE
None of the icons are loaded from the examples

### ISSUE THREAD

**Issue by Poltsi** [buefy/buefy#2692]
# Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: Linux/Firefox 78.0.2

### Description

When trying out any of the example codes at https://buefy.org/documentation/ the icons are missing.

Eg this:

            <b-button size="is-small"
                icon-left="github-circle">
                Add
            </b-button>

from the button example where a github icons is supposed to be.

Since the icons are visible on the example page itself, the probable cause is missing documentation on how to exactly set up the project so that given example code works.

### Steps to reproduce

1. Follow instructions on setting up a buefy project, add links to materialdesign and fontawesome stylesheets etc.
1. Install fontawesome components with npm
1. Copypaste example code to a component
1. Reload page containing the component

### Expected behavior

Example code (such as the button) including the icons visible on the page

### Actual behavior

Example code (such as the button) without the icons visible on the page.

**Comment by jtommy** [comment]
Please reproduce it on codepen

**Comment by Poltsi** [comment]
Standalone version: https://codepen.io/Poltsi/pen/RwrdPNj
NPM way: https://codepen.io/Poltsi/pen/QWyoyRJ

It seems pretty clear that the documentation fails to include all necessary imports and whatnot in order for the icons to actually work as in the examples.

FWIW the codepen does not seem to be that reliable. Here's the icon button example using includes suggested by codepen autocomplete CSS and JS: https://codepen.io/Poltsi/pen/ExPMgpY

For me this doesn't even render the buttons, just the button texts, ie:

   Add Add Add Add
   Delete Delete

**Comment by jtommy** [comment]
You aren't importing the icon pack, Buefy doesn't provide it!

**Comment by service-paradis** [comment]
It is the first instruction in the documentation:
https://buefy.org/documentation/start

**Comment by Poltsi** [comment]
> It is the first instruction in the documentation:
> https://buefy.org/documentation/start

Yes, why the preferences for the second example has this in it:

![image](https://user-images.githubusercontent.com/7220597/88456903-9511c580-ce8a-11ea-93e0-fd878d8ede53.png)

It adds the CSSs of the first instructions of the page to the codepen example. And yet the icons are missing.

**Comment by service-paradis** [comment]
In your examples above, you always miss to includes what is necessary.

1. You did not include any icons in your first example. https://codepen.io/Poltsi/pen/RwrdPNj should be: https://codepen.io/service-paradis/pen/JjGVVpV
2. You did not include Buefy Stylesheet at all in your second example. You also need to use valid icon name. `github-circle` was renamed `github` (https://github.com/Templarian/MaterialDesign/issues/4901#issuecomment-598880641). https://codepen.io/Poltsi/pen/QWyoyRJ should be https://codepen.io/service-paradis/pen/XWXQQxo.
