### ISSUE TITLE
Support for Vue 3.x

### ISSUE THREAD

**Issue by cjblomqvist** [buefy/buefy#2694]
More a question than a feature request: Does the current version have support for Vue 3.0 (currently in RC)? If it has, it should probably be stated clearly in the README to avoid more questions about it. If not, is there any plans to support it? 🙂

Thanks for your hard work!

**Comment by service-paradis** [comment]
There is an open issue about it:
https://github.com/buefy/buefy/issues/2505

**Comment by szvest** [comment]
I have just stumbled upon this error message...

`Invalid prop: type check failed for prop "data". Expected Array, got Function `

It took a long time before I realized that there is no support yet for Vue Composition API. Any updates @jtommy? Thanks a lot!

**Comment by jtommy** [comment]
@szvest what are you trying to do ?

**Comment by szvest** [comment]
I was migrating a bunch of fields from Options API to Composition API. The error was due to my mistake in converting computed properties into a function/method. That was fixed although I am stuck now with another error 

```TypeError: Cannot read property 'filter' of undefined```

Here is the code of a country autocomplete
```
const filteredDataObj = computed(
  () => countries.value.filter((option) => {
    return option.title
    .toString()
    .toLowerCase()
    .indexOf(countries.value.name.toLowerCase()) >= 0
  })
);
```

**Comment by jtommy** [comment]
Value is null or undefined

**Comment by szvest** [comment]
I am getting my list of countries from a json file

```
import countries from "@/api/countries.json";
```

With the following setup function...

```
setup(props, { root }) {
    const countries = reactive({countries})
    const filteredDataObj = computed(
      () => countries.value.filter((option) => {
            return option.title
            .toString()
            .toLowerCase()
            .indexOf(countries.value.name.toLowerCase()) >= 0
      })
     ....
    );
return { countries, filteredDataObj, ...}
}
```

I am suspecting my `computed` syntax is the culprit. Data cannot be undefined as you may see. It worked with options API.

**Comment by jtommy** [comment]
Probably but it's no a Buefy issue :)

**Comment by szvest** [comment]
I realize now that you are right. Thanks for your prompt assistance, @jtommy. Appreciated.
