### ISSUE TITLE
Feature request: "Lazy" option on b-input

### ISSUE THREAD

**Issue by 304NotModified** [buefy/buefy#2696]
### Description

As `v-model.lazy` doesn't work on b-input (and is confusing), see https://github.com/buefy/buefy/issues/401,
add the propery `lazy`, just like the Slider component (see https://github.com/buefy/buefy/issues/1647)

### Why Buefy need this feature

- easier to use
- no/less support questions why `v-model.lazy` doesn't work

**Comment by 304NotModified** [comment]
@jtommy, @rafaelpimpa

Is a PR accepted for this?

**Comment by jtommy** [comment]
What PR?

**Comment by 304NotModified** [comment]
If I would make a PR for this, will that one be accepted? (of course, dependent of the technical implementation)

**Comment by jtommy** [comment]
But you can replicate it with v-bind:value + v-on:change

**Comment by 304NotModified** [comment]
Yes, but that's not naturally and give some noise. It's also unfortunately that we need pass the model property twice (twice means it could be out of sync after e.g. refactor) - any way: https://github.com/buefy/buefy/issues/2696#issue-663131411 (Why Buefy need this feature)

**Comment by jtommy** [comment]
@304NotModified ok, make a PR

**Comment by 304NotModified** [comment]
Will do, Will be there probably end of the week.

**Comment by 304NotModified** [comment]
Unfortunately this will be next week

**Comment by shaozi** [comment]
@304NotModified - Is it done?

**Comment by 304NotModified** [comment]
Unfortunately no, it has been busier on work then expected

**Comment by 304NotModified** [comment]
I found time! It's here -> #2828
