### ISSUE TITLE
Allow better manipulation of the input's value on a suggestion selection

### ISSUE THREAD

**Issue by Zephyrrus** [buefy/buefy#2697]
Hello,

### Description
I was wondering if it would be possible to add something akin to `custom-formatter` on the `autocomplete` component. 
If present, this method is called in autocomplete instead of `this.getValue` on line https://github.com/buefy/buefy/blob/master/src/components/autocomplete/Autocomplete.vue#L297

Locally, I implemented it like 
```js
if (this.customSelector) {
    this.newValue = this.clearOnSelect ? '' : this.customSelector(this.selected, this.newValue);
} else {
    this.newValue = this.clearOnSelect ? '' : this.getValue(this.selected);
}
``` 
but I'm not sure if this is the best way to do it, and if it would fit everyone's needs

### Why Buefy needs this feature
This would allow users to have greater control over how the `this.nextValue` is computed. 

For example, when trying to implement a complex search as discord has, the autocomplete must be able to only replace the tag that is currently being constructed.
The current implementation does not allow an autocomplete like 
![image](https://user-images.githubusercontent.com/995982/88273326-b33cc180-cce2-11ea-83e7-3c3da7d5c90a.png)

because when `before` is clicked, there's no way to only manipulate the `nextValue` in such a way to only change the last part.

The only potential workaround is using a `custom-formatter` which manipulates the value in such a way that when `this.getValue(this.selected)` is called, it returns the value of all the previous entries and the selected option.

**Comment by jtommy** [comment]
It's no easy manipulate an input field.
You might try `b-taginput` and `selected` slot
