### ISSUE TITLE
b-input have has-counter margin collapse when invisible similar to validation-messages

### ISSUE THREAD

**Issue by marcebdev** [buefy/buefy#2698]
### Description

Building off #1719

A more reliable and nice way to have this work is similar to error messages. A `validation-message` is cleaner in that it doesn't keep a margin when it's invisible.

Similarly, having a counter shouldn't keep the margin when it isn't present, the logic is already there to allow `has-counter` to only show when focused so it's much more intuitive to provide a similar behavior to messages by default.

### Why Buefy need this feature

1) Realistically the only way around this would seem to be to use `$refs` in Vue to target the element and then check for focus. While not obnoxiously difficult, to keep things scoped you'd likely want to extend the `b-input` component (especially with forms with multiple inputs) which can cause maintainability issues in a project or lack of clarity. Imagine using a `<BInput>` everywhere instead to extend a non-specific feature.

2) It can mess up the format and/or consistency of the style of a form

3) provide cleaner behavior that is more consistent with that of `validation-message`.

**Comment by jtommy** [comment]
@marcebdev can you reproduce better your request ?

**Comment by marcebdev** [comment]
@jtommy Sure, please see this: https://codesandbox.io/s/bold-nobel-1h8g2?file=/src/App.vue

Error messages (in this case from `required` fields) only have a `margin-bottom` when they aren't showing. However, fields that have a counter will always keep the `margin-bottom` regardless if the field is focused and the counter is visible or not.

This simple example shows one case where this is very distracting, the email field can't be placed equidistant because the margin from the counter never goes away. I believe the preferred behavior would be for the excess margin to go away when the field isn't focused.

**Comment by jtommy** [comment]
Yes, you are right but there is a toggle effect every time you click on field (focus) and when you click to other field (blur)

**Comment by marcebdev** [comment]
I've looked into this issue a little more. I a simple "dirty" fix for users atm is for us to target something like and override it like so, which seems reasonable enough for now
```
.is-field .is-invisible {
  display: none;
}
```

**Comment by marcebdev** [comment]
I'm guessing you mean in regards to the actual UI, so if you move from one field to another the toggle effect isn't very nice?

Maybe a different way of going about this is having a counter option that shows inside the input where an icon would be, what do you think @jtommy?

The obvious issue is you can't use an icon and the inline-counter at the same time but I don't think someone would want to do that, and at that point, if necessary the dev always has the option of using a button addon if they must have a button and an inline counter.

**Comment by jtommy** [comment]
It could be a solution but a breaking change
