### ISSUE TITLE
Add .close() to Snackbar

### ISSUE THREAD

**Issue by chrisleyva** [buefy/buefy#2700]
### Description

Add `.close()` method to Snackbar object.

```javascript
// OPTION 1 - return reference to Snackbar
const snackbar = this.$buefy.snackbar.open({
    message: 'You have changes pending',
    indefinite: true,
    ...
});

snackbar.close();

// OPTION 2 - use Snackbar ID
this.$buefy.snackbar.open({
    id: 'pending-changes',
    indefinite: true,
    ...
});

this.$buefy.snackbar.close('pending-changes');

// OPTION 3 - You likely have a better idea 😀
// ??
```

### Why Buefy need this feature

It would be convenient to manually control the life of an indefinite Snackbar.

**My use case:**
I am using it to alert the user that they have changes pending (as you can see from the attached screenshot).

This is an `indefinite` Snackbar that will stay on the screen until the user clicks Save.
![image](https://user-images.githubusercontent.com/1437143/88196616-6805ae80-cc0f-11ea-85a7-394bd91564bb.png)

If the user clears the form/resets their changes, I would like to remove the Snackbar without them having to click the action button.

**Comment by chrisleyva** [comment]
I realize that this feature exists, I just hadn't seen it in the documentation.

**Comment by consciousnessdev** [comment]
![image](https://user-images.githubusercontent.com/30996656/117093989-b940f200-ad8c-11eb-969c-7aca116a9dc3.png)
But when i console.log(this.$buefy) there is no close method @chrisleyva :grimacing:

**Comment by chrisleyva** [comment]
@consciousnessdev I had noticed that too but if you check the source code, you'll see that the close method comes from [NoticeMixin.js](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/utils/NoticeMixin.js#L91)

Call the function `snackbar.open()` and `console.log` the result. You'll see that it should have the `close()` method. For the reason why, take a look at the [**open()** function](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/index.js#L34) and notice that it returns an extended Snackbar component, with the `close()` function from the mixin.

**Comment by consciousnessdev** [comment]
> @consciousnessdev I had noticed that too but if you check the source code, you'll see that the close method comes from [NoticeMixin.js](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/utils/NoticeMixin.js#L91)
> 
> Call the function `snackbar.open()` and `console.log` the result. You'll see that it should have the `close()` method. For the reason why, take a look at the [**open()** function](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/index.js#L34) and notice that it returns an extended [Snackbar.vue component](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/Snackbar.vue#L39), with the `close()` function from the mixin.

So, how do you make it close?

**Comment by chrisleyva** [comment]
> > @consciousnessdev I had noticed that too but if you check the source code, you'll see that the close method comes from [NoticeMixin.js](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/utils/NoticeMixin.js#L91)
> 
> > 
> 
> > Call the function `snackbar.open()` and `console.log` the result. You'll see that it should have the `close()` method. For the reason why, take a look at the [**open()** function](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/index.js#L34) and notice that it returns an extended [Snackbar.vue component](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/Snackbar.vue#L39), with the `close()` function from the mixin.
> 
> 
> 
> So, how do you make it close?
> 
> I Can't just call ```this.$buefy.snackbar.close()```

I can't fully remember right now but no, you can't do that.
You have to do this:

```
const snackbar = this.$buefy.snackbar.open()

// the return value of open() is a snackbar object
// with a close method
snackbar.close()
```

**Comment by consciousnessdev** [comment]
> > > @consciousnessdev I had noticed that too but if you check the source code, you'll see that the close method comes from [NoticeMixin.js](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/utils/NoticeMixin.js#L91)
> > 
> > 
> > > 
> > 
> > 
> > > Call the function `snackbar.open()` and `console.log` the result. You'll see that it should have the `close()` method. For the reason why, take a look at the [**open()** function](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/index.js#L34) and notice that it returns an extended [Snackbar.vue component](https://github.com/buefy/buefy/blob/7906c006df0dcb603e7848752579dc66341bc539/src/components/snackbar/Snackbar.vue#L39), with the `close()` function from the mixin.
> > 
> > 
> > So, how do you make it close?
> > I Can't just call `this.$buefy.snackbar.close()`
> 
> I can't fully remember right now but no, you can't do that.
> You have to do this:
> 
> ```
> const snackbar = this.$buefy.snackbar.open()
> 
> // the return value of open() is a snackbar object
> // with a close method
> snackbar.close()
> ```

Ok I'll try it Thanks
