### ISSUE TITLE
Table: column searchable doesn't work on a column with array objects

### ISSUE THREAD

**Issue by gbarte** [buefy/buefy#2704]
Given my column contains an array of strings for each row (example table attached) the searchable feature does not work. 
![image](https://user-images.githubusercontent.com/56682600/88366873-9360d880-cd8a-11ea-9881-ff2a383e87f4.png)

Any advice how to get around this issue?

**Comment by jtommy** [comment]
Can you reproduce your code on codepen?

**Comment by gbarte** [comment]
https://codepen.io/gbarte/pen/PoZvKPo?editors=1010

Here you can see that one column can be filtered and another one cannot. I've managed to go around this issue by turning the array into a string on my project.

ex:
`rows.forEach(el => el.employees = el..employees.join(', '));`

**Comment by Tofandel** [comment]
There is a js error there https://github.com/buefy/buefy/blob/e4774bc71f271bcce20ecdd3d4c8cf74a172c33a/src/components/table/Table.vue#L1095 because it only handles strings
