### ISSUE TITLE
Length of visible rows in table when using search

### ISSUE THREAD

**Issue by jkbgntr94** [buefy/buefy#2705]
Hi guys, i use table with pagination (on frontend) and searching. Is there any way how can i get length of filtered elements in table? When search used, table has some empty pages because original array length does not change. 

That will be really helpful if you can provide some method to programmatically clear filters on table. Only way i found for this is to reload whole component with table.

Thanks for help.

Using buefy v0.8.20

**Comment by jtommy** [comment]
Take a look at https://github.com/buefy/buefy/issues/2689
