### ISSUE TITLE
Request for new feature: icon size modifier in <b-menu-item>

### ISSUE THREAD

**Issue by cyberShaw** [buefy/buefy#2709]
### Description

An Option to Modify Icon Size in ```<b-menu-item>```

### Why Buefy need this feature

Under the Buefy Docs, there is no option to modify icon size in the Menu Component.
It would be really useful to add a customizable option to modify icon size 😄 

I'm also interested in working on this feature 😄

**Comment by jtommy** [comment]
Sure, you can add it!

**Comment by cyberShaw** [comment]
> Sure, you can add it!

Awesome! I'll work on it, and send a PR 🔥

**Comment by cyberShaw** [comment]
Added commits that reference this issue, in #2716

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2716#merged-event
