### ISSUE TITLE
How to change default icon component when importing individual components?

### ISSUE THREAD

**Issue by adriaanmeuris** [buefy/buefy#2713]
# Description
I'm able to change the default icon component following the docs:
```js
import MyIcon from '@/components/MyIcon.vue';
Vue.component('my-icon', MyIcon);
Vue.use(Buefy, {
  defaultIconComponent: 'my-icon',
  defaultIconPack: '',
});

```

However I only need 2 components:
```js
import { Button, Input } from 'buefy';
Vue.use(Button);
Vue.use(Input);
```

How can I change the default icon component when importing individual components?

**Comment by jtommy** [comment]
https://buefy.org/documentation/constructor-options
