### ISSUE TITLE
Set focus on inserted b-field / b-input / autocomplete

### ISSUE THREAD

**Issue by bodnarlajostibor** [buefy/buefy#2715]
I made a directive in my component: 
`    directives: {
      focusoncreate: {
        inserted: function (el) {
          el.focus()
        }
      }
    }`

I have a box container with v-for, so having multiple elements (partners), where the user can edit their data with different b-fields (name, email-address, etc.). 
The user can add a new partner with "Add" button, which adds a new empty element to the partner array, then thanks to Vue's reactive system, a new box appears with empty fields. 

I want the focus on the first field of the new box. 

If I use the directive on an input tag, it works fine:
`<input placeholder="Gimme the FOCUS" v-focusoncreate>`
If I use the directive on a b-button tag, it works fine:
`<b-button v-focusoncreate>Gimme the FOCUS</b-button>`

If I use it on a b-field, b-input, b-autocomplete, 
the magic don't happen.

**Comment by jtommy** [comment]
@bodnarlajostibor for b-input you should find the inner input because there is a div that wraps the native input

**Comment by bodnarlajostibor** [comment]
> @bodnarlajostibor for b-input you should find the inner input because there is a div that wraps the native input

Can you help me please, how can I find that inner input?

**Comment by jtommy** [comment]
Right!
