### ISSUE TITLE
Buefy overriding Vuetify styles

### ISSUE THREAD

**Issue by diamond95** [buefy/buefy#2718]
### Description
I tried to use Buefy tables for my project, where I currently use Vuetify.
Importing works fine, but when I use 
`import 'buefy/dist/buefy.css'` in my component, it breaks whole application. I also tried to import css like this:
`<style scoped  src="buefy/dist/buefy.css"></style>
` to make it scoped, but then that css is not applied on child component ( which is b-table ).
Is there any hack for this? 

### Expected behavior
Using b-table with current Buefy design like this: https://codepen.io/pen?&editable=true&editors=101=https%3A%2F%2Fbuefy.org%2Fdocumentation%2Ftable%2F

**Comment by jtommy** [comment]
Yes, migrate your project to Buefy 😄 
Btw it's difficult to avoid it due to bulma too
