### ISSUE TITLE
Bulma latest version support

### ISSUE THREAD

**Issue by shaozi** [buefy/buefy#2720]
Bulma is now on v 0.9.0, Buefy only has v0.7.5. When are we going to support a new Bulma version?

### Why Buefy need this feature

To take Bulma new feature such as spacing helper: `mx-2`, `py-3` etc

**Comment by jtommy** [comment]
Work in progress, take a look at dev branch

**Comment by shaozi** [comment]
Great! Any time frame on releasing?

**Comment by rognales** [comment]
+100 for this
