### ISSUE TITLE
Open AutoComplete on click after already having focus

### ISSUE THREAD

**Issue by NickeManarin** [buefy/buefy#2725]
### Description

I'm using the `OpenOnFocus` option to display the popup list of items when the `AutoComplete` receives focus.
The problem is that after receiving focus via `this.$refs.autoRef.focus()` the element won't display the popup until I leave the field and give focus again.

I propose a new option `OpenOnClick` or `OpenOnKeyDown` or at least a method to open via code.

### Why Buefy need this feature

Because we are unable to properly use the `AutoComplete` field when the element already has focus.

**Comment by jtommy** [comment]
I don't understand, are you setting focus on focused element ?

**Comment by NickeManarin** [comment]
I'm displaying some inputs side by side in a div (AutoComplete -> b-input -> button), after pressing the button, the focus is programmatically set to the first element (which is the AutoComplete), using this:

this.$refs.autoRef.focus()

I'm doing this to so the user can stay using the keyboard (with Tab and Enter keys), without needing to reach the mouse to switch inputs.

There's two issues that I'm facing:

1. Focus set via this.$refs.autoRef.focus() does not open the popup.
2. While focused, clicking on the auto complete will not open the popup.

![Focus](https://user-images.githubusercontent.com/14798947/89210459-81efab80-d596-11ea-86bc-bbb11ad4b36c.gif)

I understand that after receiving focus via `ref.focus()`, I can press ArrowDown (or start typing letters/numbers) to display the AutoComplete popup, but that's not clear for the user.

I should have opened bug ticket instead of a feature request. :/

**Comment by NickeManarin** [comment]
That was fast, thanks!
