### ISSUE TITLE
Allow custom colours for b-tag

### ISSUE THREAD

**Issue by unikitty37** [buefy/buefy#2728]
## Description

While the `<b-tag>` component can set the colour using the `type` prop, this limits it to the tags that have been defined in Sass's `$colors` list.

I'm writing something which allows the user to configure tag colours, and need to be able to display tags in those colours — but `<b-tag>` provides no way to set the foreground and background colours.

## What I would like to be able to do

```html
<b-tag :fgcolor="foregroundColour" :bgcolor="backgroundColour">Tagged</b-tag>
```

## What I currently have to do

```html
<span class="tag" :style="{ color: foregroundColour, backgroundColor: backgroundColour }">Tagged</span>
```

This is OK for a basic tag, but it loses all the benefits of Buefy, such as being able to use `closable` and `ellipsis`. i did try sticking a ref on the `<b-tag>` and manipulating its CSS at runtime, but I don't seem to be able to get at the DOM elements that way. Computed props can't be put into the `<style>` section, so I can't use a deep style to override the colours.

### Why Buefy needs this feature

Not every colour combination can be known in advance and injected into the Sass `$colors` list — some may need to be computed values that are generated at run-time. Buefy should be flexible enough to allow these to be used.

**Comment by jtommy** [comment]
You can create a custom class and apply it on `b-tag`

**Comment by unikitty37** [comment]
Thanks — I didn't realise that `style` and `class` were valid properties here.

Is it worth mentioning that in the docs?
