### ISSUE TITLE
Navbaritem's handleClickEvent falsely assumes parent's existence

### ISSUE THREAD

**Issue by truefusion** [buefy/buefy#2736]
https://github.com/buefy/buefy/blob/e830ba4b19bbd3b73210e5bbda56fae92fa9e019/src/components/navbar/NavbarItem.vue#L43

As a result, I get the following error:
```
Cannot read property '$data' of null
```

Possible solution:
```js
if (parent && parent.$data._isNavbarDropdown) this.closeMenuRecursive(parent, ['NavBar'])
```

**Comment by jtommy** [comment]
Can you share your code ?

**Comment by truefusion** [comment]
Sure (though it is under heavy development).
https://github.com/truefusion/manna-desktop/blob/master/src/views/Module.vue

**Comment by jtommy** [comment]
You have to use `navbar-item` into `navbar` component

**Comment by truefusion** [comment]
The navbar _component_ was undesirable for my design, so I stuck to just using classes. Indeed, it was more of a hassle than what it was worth. Besides, it is more proper to check for return values than to assume the variable will always be valid.

**Comment by jtommy** [comment]
Ok but you can't use navbar-item in this way
