### ISSUE TITLE
Allow custom CSS class for inner .table

### ISSUE THREAD

**Issue by madmath03** [buefy/buefy#2746]
### Description

Allow to specify CSS class for inner table.

https://github.com/buefy/buefy/blob/fc27891f5c4517c93778012b6266965c7d278bda/src/components/table/Table.vue#L45-L47

### Why Buefy need this feature

This could allow to customize the table's background, especially useful when working with "_dark_" themes.

**Comment by jtommy** [comment]
You can do it adding a class to b-table that update the style of inner native table element

**Comment by madmath03** [comment]
> You can do it adding a class to b-table that update the style of inner native table element

Tried it, doesn't work...

**Comment by jtommy** [comment]
A sample code ?

**Comment by madmath03** [comment]
@jtommy Sure!

```vue
<template>
    <b-table
      :data="tableData"
      class="my-table"
    >
      <template slot-scope="props">
        <b-table-column
          field="name"
          label="Resources"
        >
          <span
            :class="
              'tag has-text-dark ' +
                (props.row.type === 'required' ? 'is-warning' : 'is-success')
            "
          >{{ props.row.name }}</span>
        </b-table-column>
      </template>
    </b-table>
</template>

<script lang="ts">
export default {
  name: "Example",
  components: { },
  data() {
    return {
      tableData: [
        {
          name: "Required",
          type: "required",
        },
        {
          name: "Recommended",
          type: "recommended",
        },
      ],
    };
  },
};
</script>

<style lang="scss" scoped>
.my-table {
  margin: 2rem 0;

  table {
    background-color: black;
    color: white;
  }
}
</style>

```

I'm expecting here to see the inner table with a black background and white text, but result is not applied:
![image](https://user-images.githubusercontent.com/6967675/90314926-af821080-df17-11ea-8e53-6ed99b85c321.png)

Also tried using the CSS class for inner table (`.table`) or inner table CSS outside, still the same result.

Can you please reopen the issue?

**Comment by jtommy** [comment]
You are using s scoped style so you have to force it, for example adding `>>> table { ... }`.
It's no a Buefy issue anyway

**Comment by madmath03** [comment]
> You are using s scoped style so you have to force it, for example adding `>>> table { ... }`.

Using deep selector `>>>` does not work either...

> It's no a Buefy issue anyway

@jtommy how can you say that ??
I did not report a bug with Buefy, I created a Feature Request to be able to define additional CSS classes to apply to the inner table.

My request is to be able to do something like that:
```html
    <b-table
      :data="tableData"
      class="my-table"
      tableClass="inner-table-class
    >
 ```

This would benefit Buefy by not requiring hacks like deep selectors and be compatible with scoped styles.

I guess it could be achieved simply by adding a new prop `tableClass` to b-table and use it like that:
```js

    props: {
        // ...
        tableClass: {
            type: Function,
            default: () => ''
        },
        // ...
    },
    // ...
    computed: {
        // ...
        tableClasses() {
            return {
                'is-bordered': this.bordered,
                'is-striped': this.striped,
                'is-narrow': this.narrowed,
                'is-hoverable': (
                    (this.hoverable || this.focusable) &&
                    this.visibleData.length
                ),
                this.tableClass()
            }
        },
        // ...
    },
```

I do not mind sending a PR for that.

**Comment by madmath03** [comment]
@jtommy can you please reopen this Feature Request ?

**Comment by jtommy** [comment]
@madmath03 
```<style scoped>
.my-table {
  margin: 2rem 0;
}
.my-table >>> table {
    background-color: black !important;
    color: white !important;
}
</style>```

**Comment by madmath03** [comment]
...adding `!important` when using a deep selector does not change the result.

@jtommy Could you explain what's wrong with the proposed enhancement ?

**Comment by jtommy** [comment]
You can remove ! important, but it works only with css

**Comment by madmath03** [comment]
> You can remove ! important, but it works only with css

@jtommy I'm certainly not going to stop using SCSS just because of that.

What's wrong with adding a new props to specify additional class for the table ?

**Comment by jtommy** [comment]
Do you need scss in this part ?

**Comment by madmath03** [comment]
Yes. The example I put here is just for demonstration, my real use case requires SCSS.

**Comment by madmath03** [comment]
@jtommy can you please reopen this ? or, at least, would you accept a PR to add this property ?

**Comment by madmath03** [comment]
Up
