### ISSUE TITLE
RTL switcher

### ISSUE THREAD

**Issue by UtopiaBe** [buefy/buefy#2749]
Hello, I have just installed the latest version on nuxtjs.

I use i18n to translate my website, and i need to switch for RTL on specific lang.
Bulma now supports $RTL: true on global scss configure.

Is there a way to switch the $rtl: true|false with the buefy ?
or any other way?

thank you.

**Comment by jtommy** [comment]
Sure, in the same way that you change primary color

**Comment by UtopiaBe** [comment]
Can you provide some example to do it?
I have failed :(

**Comment by UtopiaBe** [comment]
There is nothing to show...
I just cant get how to change the global $rtl: true|false
on the default layout, or on the main.scss style (i tried with manual installation of bulma and buefy)

**Comment by jtommy** [comment]
https://buefy.org/documentation/customization

Set it after colours variables for example

**Comment by UtopiaBe** [comment]
I did. But if i switch back to LTR language.
the $RTL is true, and the layout breaks.

**Comment by jtommy** [comment]
What do you mean?

**Comment by UtopiaBe** [comment]
I have opened a ticked on Bulma.
But had no response...

[https://github.com/UtopiaBe/buefy-rtl]
Here is the nuxtjs project i created now.
I has 2 languages, and $RTL: true.

When i switch from Hebrew to English - the layout breaks because the $RTL: true.
can be found on the default.vue layout

**Comment by shmuel-web** [comment]
HI
@UtopiaBe 

$RTL is a SASS variable defined during build time 

it can not be changed after that in a simple way.

with that being said 

there are two optional solutions  

you can either 
track $RTL effects into the CSS and change them using js on the front-end 
or build a separate CSS for the RTL & LTR versions of the page 
and serve them from different routes 
so www.xyz.co.il would serve the RTL version 
and www.xyz.com would serve the LTR version 

pick the solution that best fits your use case
