### ISSUE TITLE
Buefy 0.9.0 - alerts stopped rendering message

### ISSUE THREAD

**Issue by T-PWK** [buefy/buefy#2750]
### Overview of the problem

**Buefy** version: 0.9.0
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS/Chrome

### Description

After migration to Buefy 0.9.0 from 0.8.20, alert message is not rendered and console renders error message as follows: _"You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build."_

![image](https://user-images.githubusercontent.com/2621535/90369810-4956d400-e064-11ea-90da-e7f57043107d.png)

Code:
```js
this.$buefy.dialog.alert('Some message ...')
```

Same behaviour is with 

```js
import { DialogProgrammatic as Dialog } from 'buefy'
Dialog.alert('Some message ...')
```

It looks like there was a change in https://github.com/buefy/buefy/blob/master/src/components/dialog/index.js file in version 0.9.0, which may have introduce that issue.

It does not looks like an expected behaviour, hence opening a new issue for that.

Can you please confirm this is a bug or there are some undocumented setting / workaround?

**Comment by task-k0414** [comment]
I got that same case.

- code

```
      this.$buefy.dialog.confirm({
        message: `ログアウトしますか？`,
        cancelText: 'キャンセル',
        confirmText: 'ログアウト',
        type: 'is-danger',
        ...
      })
```

- view

<img width="321" alt="Screen Shot 2020-08-17 at 16 46 17" src="https://user-images.githubusercontent.com/32471740/90371177-83969480-e0a9-11ea-9abf-b8347718451f.png">

**Comment by jacenre** [comment]
If you have a 'You are using the runtime-only build of Vue where the template compiler is not available' message in your browser, than this issue is fixed by enabling the [runtimeCompiler](https://cli.vuejs.org/config/#runtimecompiler) option in your vue.config.js

**Comment by fabiofdsantos** [comment]
Temporary workaround for Nuxt.js: https://github.com/nuxt/nuxt.js/issues/1142#issuecomment-317272538

**Comment by rrigby** [comment]
Same issue here. Nuxt website says using runtimeCompiler should be avoided if possible for performance reasons. Wondering why this feature worker fine <4.0 but now it needs runtimeCompiler?

**Comment by jtommy** [comment]
Yes there is that change.. I should find an alternative

**Comment by Dream-cake** [comment]
im getting this issue even though im not using nuxt.js

**Comment by fabiofdsantos** [comment]
@Dream-cake It's normal. Check this: https://github.com/buefy/buefy/issues/2750#issuecomment-674767887

It should be fixed on the next release.
