### ISSUE TITLE
Buefy 0.9.0 - Table props index wrong

### ISSUE THREAD

**Issue by nikolasdas** [buefy/buefy#2751]
### Overview of the problem

**Buefy** version: 0.9.0
**Vuejs** version: 2.6.11
**OS/Browser**: Windows/Chrome

### Description

props.index no longer provides the correct index of the row on a table

`<b-table-column v-slot="props">{{ props.index }}</b-table-column>`
[0.8.20 Sandbox](https://codesandbox.io/s/buefy-template-forked-68efq?file=/src/App.vue)
[0.9.0 Sandbox](https://codesandbox.io/s/buefy-template-forked-19tik?file=/src/App.vue)

**Comment by MartinX3** [comment]
I use now as a workaround
`this.array.indexOf(props.row)`

So I can still
`this.array.splice(this.array.indexOf(props.row), 1)`

**Comment by dreaminfo** [comment]
Til Fix
{{ data.indexOf(props.row) }}
