### ISSUE TITLE
0.9.0 update has a color property issue on sidenav

### ISSUE THREAD

**Issue by howzitcal** [buefy/buefy#2752]
`.menu-list a.is-active {
  background-color: #7957d5;
  color: findColorInvert(#7957d5);
}`

Buefy version 0.9.0
![Screenshot from 2020-08-17 15-34-17](https://user-images.githubusercontent.com/38749032/90402311-8f7d5900-e09f-11ea-84db-c6355b92f53d.png)

![Screenshot from 2020-08-17 15-38-13](https://user-images.githubusercontent.com/38749032/90402398-ac199100-e09f-11ea-9bcd-d67bf07d1740.png)

**Comment by tontonsb** [comment]
What would be the corerct import procedure when using this as suggested in the docs?

```
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Buefy)
```

I am having the same issue on tooltips.

**Comment by jtommy** [comment]
Fixed, new release soon
