### ISSUE TITLE
Allow Month/Range in Buefy Date Picker

### ISSUE THREAD

**Issue by basicallysteve** [buefy/buefy#2754]
### Description

Essentially, this feature would allow a user to select a number of months

```html
<b-datepicker type="month" range>
```

### Why Buefy need this feature

I think this feature would be good cause in some situations, the user doesn't want to select a number of dates, however wants to select a number of months and this would be a quicker interface.

![image](https://user-images.githubusercontent.com/22861039/90440545-665fc700-e0a5-11ea-8c5b-cdb13d0002c6.png)

**Comment by jtommy** [comment]
It could be a good feature
