### ISSUE TITLE
ToastProgrammatic throws error on 0.9.0

### ISSUE THREAD

**Issue by adriaanmeuris** [buefy/buefy#2758]
### Overview of the problem
**Buefy** version: 0.9.0
**Vue** version: 2.6.11
**Vue CLI** version: 4.5.4
**OS/Browser**: Mac/Chrome

### Description
Worked fine with Buefy `0.8.20`, broken since `0.9.0`:
https://buefy.org/documentation/toast#from-outside-vue-instance

Error triggered: `[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

Happens here:
<img width="495" alt="Screenshot 2020-08-18 at 13 23 42" src="https://user-images.githubusercontent.com/16230038/90507374-15f47200-e156-11ea-8548-d434c9f41179.png">

### Steps to reproduce
1. Setup project with Buefy `0.9.0`
2. Run this code:
```js
import { ToastProgrammatic as Toast } from 'buefy'
Toast.open('Toasty!')
```

### Expected behavior
The toast to appear

### Actual behavior
Error gets triggered (see above)

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/2750
