### ISSUE TITLE
0.9.0 Text color of primary button is off

### ISSUE THREAD

**Issue by aaldertdekker** [buefy/buefy#2760]
### Overview of the problem

**Buefy** version: 0.9.0
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome, Firefox

### Description

The text color of primary button should be white. Also `is-light` does not work when button type is `primary`.
![image](https://user-images.githubusercontent.com/54722895/90510539-73d78880-e15b-11ea-82c6-30545ac2b789.png)

### Steps to reproduce

1. Create new vue project and add buefy
2. Copy code from https://buefy.org/documentation/button/#types-and-states

### Expected behavior

![image](https://user-images.githubusercontent.com/54722895/90511224-7090cc80-e15c-11ea-8a83-947753640279.png)

### Actual behavior

See screenshot above. Tabs might be affected by this issue as well.

**Comment by service-paradis** [comment]
Thank you for this well-made issue. This will be solved in the next release (#2752).
