### ISSUE TITLE
Icon-pack being ignored by Table for pagination - Always mdi icons

### ISSUE THREAD

**Issue by SomethingNew71** [buefy/buefy#2765]
### Overview of the problem

**Buefy** version: [0.9.1]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS Chrome and Firefox

### Description

Implementing the Buefy Table ignores the `icon-pack` chosen and always defaults to the mdi icon set. I have confirmed Font Awesome icons are appearing properly across the rest of the site. 

Production example: https://classicminidiy.com/technical/torque

### Steps to reproduce

```html
<b-table
  :data="table.items"
  :columns="table.columns"
  :narrowed="true"
  :hoverable="true"
  :paginated="table.items.length >= 14 ? true : false"
  :per-page="10"
  :icon-pack="'fas'"
  :mobile-cards="false"
/>
```
### Expected behavior

For `fas` or any other font awesome icons to be rendered. 

### Actual behavior

No icons displayed as mdi icon set is not included in our application.

### Additional info
It looks like `iconPack` is not being correctly passed to the nested pagination component. Despite being set in the `b-table` element its still undefined in the `b-pagination` element.

**Comment by SomethingNew71** [comment]
I created a PR with a fix for this which I tested locally in my app. If you see anything I missed let me know and I can take care of those fixes.

**Comment by SomethingNew71** [comment]
@jtommy thanks for merging this. Any idea when the next release will be pushed?

**Comment by jtommy** [comment]
Max tomorrow
