### ISSUE TITLE
toVDom function on programmatic components is duplicating content on html tags

### ISSUE THREAD

**Issue by eagleera** [buefy/buefy#2767]
### Overview of the problem

**Buefy** version: [0.9.1]
**Vuejs** version: [2.6.11]
**OS/Browser**: Catalina / Chrome

### Description

When using an html template inside the message prop on NotificationProgrammatic, the html doesn't render well, the classes are ignored and some tags are duplicated (I think it has to do with the toVDom function

### Steps to reproduce

create a notification programmatic
in the message put `<div class="has-text-success">Something's</div> not good, also I'm on <b>bottom</b>`
You should see the "Something's" rendered twice

### Expected behavior

Instead of "Something's" being rendered twice, we should see "Something's" on a success color

### Actual behavior

the "Something's" is being rendered twice
![Screen Shot 2020-08-18 at 12 22 57](https://user-images.githubusercontent.com/17990400/90550729-8ea30080-e14d-11ea-9508-39e7323fc9b5.png)
![Screen Shot 2020-08-18 at 12 23 39](https://user-images.githubusercontent.com/17990400/90550795-a7131b00-e14d-11ea-9a6b-0ae33b218d9e.png)

**Comment by jtommy** [comment]
The main idea is to support simple message, but I'll try to fix it

**Comment by simeq** [comment]
Can this issue be related to https://codepen.io/simeq/pen/gOrwwPE (example from documentation) and this https://codepen.io/simeq/pen/yLOaaJJ?

**Comment by jtommy** [comment]
@simeq wrong docs, I'll fix it

**Comment by Tofandel** [comment]
@jtommy The toVDom function is originally not a good idea as it doesn't fix XSS at all, so many things could go wrong when you let a user display HTML (sure with a bit of validation but HTML nontheless, you could put an onload handler in there and execute JS or just display a full on body modal) don't give a false illusion of security and make two props available as suggested
'message' => All html is allowed, 'messageText' => All html is escaped

**Comment by jtommy** [comment]
Probably it's not a good parse but I don't think it's xss vulnerable because I attach only tag and text content

**Comment by Tofandel** [comment]
I don't really have the time, but I could easily make an attack demonstration if you want, since only tags are allowed you could make use of web components declared on the page (it's quite common with vue) they are not safe to be displayed as they will execute javascript when added to a page and you could for instance create a phishing modal given the right circumstances

Removing all attributes (eg: classes) also entirely defeats the point of allowing html in the message content you might as well just allow text
