### ISSUE TITLE
Dialog - Repeats the content, when message contains html

### ISSUE THREAD

**Issue by simeq** [buefy/buefy#2769]
### Overview of the problem

**Buefy** version: 0.9.1
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome 84.0.4147.125 / macOS 10.15.6

### Description

Dialog repeats the content, when message contains an html: https://codepen.io/simeq/pen/xxVEKzK

**Comment by service-paradis** [comment]
Duplicate of #2767.

Thanks for the Codepen!
