### ISSUE TITLE
"class" attribute on BTableColumn no longer has any effect

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#2770]
### Overview of the problem

**Buefy** version: [0.9.1]
**Vuejs** version: [2.6.1]
**OS/Browser**: any

### Description

Not quite a bug (I think) but more of an undocumented breaking change: in past versions of Buefy, applying a `class` attribute to `BTableColumn` caused the corresponding class to be added to the matching `<td>` element; this is no longer the case as of version 0.9.0.

Using the `cell-class` prop does achieve the same effect, but I think the change should be documented somewhere.

**Comment by jtommy** [comment]
I'll add in the changelog
