### ISSUE TITLE
row prop on BTable is undefined after 0.9.1 latest commits

### ISSUE THREAD

**Issue by billytunin** [buefy/buefy#2772]
### Overview of the problem
Buefy version: [0.9.1]
Vuejs version: [2.6.11]
OS/Browser: any

### Description
Seems like something broke on latest commits to `0.9.1` . A week ago, this was working completely fine. Now, when I try to access `props.rows` or just the `rows` property of the default slot `<template></template>`, I get undefined. This is only happening when the array I'm using for `data` starts as empty and then gets populated by an ajax call. If I give the data property an already populated array, it works fine. I'm guessing it might be related to reactivity? I also saw some other bugs regarding b-table and reactivity that appeared a couple of hours ago. So my guess is this has to do with it. In the example I provide below, if you change the `<script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>` and `<link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">` tags to a CDN that's pointing to 0.8.20 (like `https://cdnjs.cloudflare.com/ajax/libs/buefy/0.8.20/buefy.min.js` and `https://cdnjs.cloudflare.com/ajax/libs/buefy/0.8.20/buefy.min.css`) it works perfectly fine.

### Steps to reproduce
Just try it out on this HTML file. You'll see that tableData is actually populated... but `row` is undefined.

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- development version, includes helpful console warnings -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  <title>Buefy BTable Issue test</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  <!-- Buefy shit -->
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.5.94/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">
  <script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>
</head>

<body>
  <div id="app">
    <p>tableData:</p>
    <p>{{ tableData }}</p>
    <p v-if="tableLoading">Loading</p>
    <b-table  v-else
              :data="tableData">
      <template #default="{ row }">
        <b-table-column label="Message ID">
          {{ row ? row.message_id : 'Unknown message id' }}
        </b-table-column>
      </template>
    </b-table>
  </div>

  <script>
    let app = new Vue({
      el: '#app',
      data: {
        tableData: [],
        tableLoading: false
      },
      mounted(){
        this.initialTableSetup()
      },
      methods: {
        async initialTableSetup(){
          this.tableLoading = true
          const { data } = await axios({
            method: 'get',
            url: `https://catslab.herokuapp.com/bepibot/getContent?page_number=1`
          })
          this.tableData = data.data
          this.tableLoading = false
        }
      }
    })
  </script>
</body>

</html>
```

**Comment by jtommy** [comment]
You are wrong, pleased check the new syntax in the changelog or docs.
The slot is into each table column
