### ISSUE TITLE
Allow tooltip classes for `append-to-body`

### ISSUE THREAD

**Issue by jacenre** [buefy/buefy#2780]
### Overview of the problem

**Buefy** version: [0.9.1]

### Description

The Tooltip can dynamically insert a tooltip to the body, but due to this line
```
tooltipEl.classList.forEach((item) => tooltipEl.classList.remove(item))
```
all classes on `div.b-tooltip` (surrounding `.tooltip-content`) get removed. This removes the ability to add classes to the root tooltip `div`.

### Steps to reproduce

1. ```<b-tooltip class="just-a-tooltip" append-to-body>Hello World</b-tooltip>```

### Expected behavior
```
<div class="b-tooltip just-a-tooltip is-primary is-top is-medium" style="width: 0px; height: 0px;">
    <div class="tooltip-content">1</div>
</div>
```
### Actual behavior
```
<div class="b-tooltip is-primary is-top is-medium" style="width: 0px; height: 0px;">
    <div class="tooltip-content">1</div>
</div>
```

### Suggested solution
Remove the line of code that clears the classList, or create a prop `rootClasses` (or similar) that applies does classes.

**Comment by jtommy** [comment]
You are right, I'll append it always
