### ISSUE TITLE
Sorting arrows in b-table misplaced

### ISSUE THREAD

**Issue by thetractor** [buefy/buefy#2782]
### Overview of the problem

**Buefy** version: [0.9.1]
**Vuejs** version: [2.6.1]
**OS/Browser**: Mac OS 10.14.6  / Chrome 84.0.4147.125

### Description

The b-table component shows sorting arrows (even sorting is explicitly disabled on the b-table-column component) and they are positioned wrong.

### Steps to reproduce

1. Copy Sample from https://buefy.org/documentation/table#sandbox-with-custom-template 
2. Check Table

Here the snadbox: https://codesandbox.io/s/b-tablesortarrows-jqgk

Here a screen shot:
![Bildschirmfoto 2020-08-19 um 21 12 17](https://user-images.githubusercontent.com/22886611/90679798-fe55e000-e260-11ea-8ea0-71db1734af52.png)

<img width="896" alt="Bildschirmfoto 2020-08-19 um 23 08 43" src="https://user-images.githubusercontent.com/22886611/90690064-5a286500-e271-11ea-8862-ecb3b65b1fb5.png">

### Expected behavior
The table should not show any sorting arrows.

### Actual behavior
The table shows sorting arrows and they are misplaced.

**Comment by jtommy** [comment]
I don't understand your request

**Comment by thetractor** [comment]
@jtommy here a sandbox to reproduce the issue: https://codesandbox.io/s/b-tablesortarrows-jqgk4

here the issue in a screen shot:
<img width="896" alt="Bildschirmfoto 2020-08-19 um 23 08 43" src="https://user-images.githubusercontent.com/22886611/90689996-39f8a600-e271-11ea-91b5-a6e6dae22f7e.png">

I updated the issue above.

**Comment by jtommy** [comment]
You have to import all bulma classes (you are missing is-invisible for example), https://buefy.org/documentation/customization
