### ISSUE TITLE
Tooltip blocking action button redirect

### ISSUE THREAD

**Issue by Ralford23** [buefy/buefy#2783]
Action button not redirecting while nested inside b-tootip

**Buefy** version: [0.9.1]
**Vuejs** version: [2.6.1]
**Google Chrome**:

I am unable to use an action button nested inside a tooltip to redirect to a different page. The tooltip seems to be blocking the action event. You can have a regular button with a click event inside the tooltip and it will work fine, just not an action button with an href.

### Steps to reproduce
```
<b-table-column v-slot="props">
                        <b-tooltip type="is-primary"
                                   label="Edit">
                                <b-button type="is-primary"
                                          v-bind:href="www.google.com"
                                          tag="a"
                                          icon-left="pencil-square-o">
                                </b-button>
                        </b-tooltip>
</b-table-column>
```

### Expected behavior

Navigate to the next page.

### Actual behavior

Looks like it clicks the button but does not redirect.

**Comment by service-paradis** [comment]
I have the same problem with a checkbox label. It was working before. Now, clicking on the lable does not (un)check the checkbox.

```html
<b-checkbox>
  <b-tooltip label="Oh yeah, I'm Basic!">Basic</b-tooltip>
</b-checkbox>
```

Putting the tooltip around the checkbox is worst still we cannot even (un)check

```html
<b-tooltip label="Oh yeah, I'm Basic!">
  <b-checkbox>Basic</b-checkbox>
</b-tooltip> 
```
