### ISSUE TITLE
modal is not showing up with vue typescript

### ISSUE THREAD

**Issue by me2mitesh** [buefy/buefy#2786]
### Overview of the problem

**Buefy** version: 0.8.15
**Vuejs** version: 2.6.11
**OS/Browser**: Windows/Chrome

### Description

We are following the buefy documentation for modal. When we try the same code as in the documentation, the modal is not showing up. We are using typescript.

`<button class="button is-primary is-medium"
                @click="isModalActive = true">
                Launch modal
            </button>`

           `<b-modal v-model="isModalActive">
                <h1>Hello World<h1>            
        </b-modal>`

Also, we are able to run the other components (toast, dialog etc)

### Expected behavior

The popup should be displayed.

### Actual behavior

No popup is displayed

**Comment by service-paradis** [comment]
Should work fine! Are you able to reproduce the issue using Codepen or Codesandbox?
Is there any error shown in the Browser Console?

**Comment by me2mitesh** [comment]
Modal is working fine on codepen.
No error is shown in the browser console of the app where we are using buefy.

**Comment by jtommy** [comment]
Did you try to update Buefy version at least to 0.8.20 ?

**Comment by me2mitesh** [comment]
We tried after upgrading to 0.8.20.
It is still not working.

However, the programmatic modal is working.
Looks some issue with the b-modal.

**Comment by jtommy** [comment]
We need a code to understand better

**Comment by me2mitesh** [comment]
Code not working: 

`<button class="button is-primary is-medium" @click="isModalActive = true"> Launch modal </button>

       <b-modal v-model="isModalActive">
            <h1>Hello World<h1>            
    </b-modal>`


Code which is working:

`this.$buefy.modal.open({
                    parent: this,
                    component: ModalForm,
                    hasModalCard: true,
                    customClass: 'custom-class custom-class-2',
                    trapFocus: true
                })`

Just want to see if b-modal could work. Implementation of b-modal is easy as compared to the other one.

**Comment by jtommy** [comment]
You can use v-model only from 0.9.x

**Comment by me2mitesh** [comment]
Now it is working fine  after we updated the buefy package to 0.9.1 
Thanks a lot for your help !
