### ISSUE TITLE
Table - Nested filterable columns / multicolumns

### ISSUE THREAD

**Issue by Bran72** [buefy/buefy#2787]
### Description

Basically, this feature would bring filterable multicolumns to a Buefy table.  
So it would allow us:
- nesting cols into cols
- filter data and filter the nested data
- displaying dynamic data into this nested cols

### What I want
**I want to reproduce this table, developed with jQuery & [tablesorter](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html) (yeah)**

![wanted](https://user-images.githubusercontent.com/36424448/90774595-fe54ef00-e2f7-11ea-896d-5c33c4a3092b.png)
You can check for an example right here: [see example](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html) 

**In this table, we can:**
- show dynamic data (we can have much more cols next to "3" - as "4", "6", "8",...

> And with checkbox, we can show / hide cols next to "Prix Lots" in "0.75" for example

- each row / col is filterable (thanks to the arrows)

> By filtering on "0.75", "1.5",... I mean filtering the first nested col
<br />

### What I've done
**Concretely, I have this sample:** (yeah, it's ugly but the bordered rule is greater to debug)
![actual](https://user-images.githubusercontent.com/36424448/90776305-39f0b880-e2fa-11ea-9ef2-68ed7c376b60.png)

It was done with this code & data template:

> By the way, I'm using Buefy v0.9.1 & Bulma v.0.8.1

```
<b-table :data="tableDataSimple" striped>
	<b-table-column label="Année" v-slot="props">
		{{ props.row.year }}
	</b-table-column>
	<b-table-column
		v-for="(centil, index) in dataCentil"
		:label="centil"
		:key="index"
		v-slot="props">
		<b-table
			:data="props.row.data[centil]"
			bordered>
			<b-table-column
				v-for="(column, key) in columnsTemplate"
				:key="key"
				:label="props.row.year === '2019' ? column.label : ''"
				:visible="column.visible"
				v-slot="props">
				{{ props.row[column.field] }}
			</b-table-column>
		</b-table>
	</b-table-column>
</b-table>
```
```
let tableDataSimple = [
	{
		'year': '2019',
		'data': { '0.75': [ { 'stock': '5076', 'tarifbrut': '', 'place': '' } ] }
	},
	{
		'year': '2016',
		'data': {
			'1.5': [ { 'stock': '24', 'tarifbrut': '92', 'place': '' } ],
			'3': [ { 'stock': '33', 'tarifbrut': '225', 'place': '' } ]
		}
	}
]
const columnsTemplate = [
	{ label: 'Stock Dispo', field: 'stock', visible: true },
	{ label: 'Infocom', field: 'tarifbrut', visible: true },
	{ label: 'Date Place', field: 'place', visible: true }
]
const dataCentil = ['0.75', '1.5', '3']
```

But now, my problem is to nest the header as subdheading 

> for "stock dispo", "infocom",... -> Actually, it's a trick by displaying it only for the first year

I also want to keep the filter on the full table / cols / rows...
<br />

### Why Buefy need this feature

I've searched a looong time for an advanced VueJS table, but I never find what I want.  
But I think there's a lot of people in the same case, who want to create an advanced table with nested and filterable columns / multicolumns. And also with another VueJS compatible table, we don't have a table as advanced...

**Comment by von-maurus** [comment]
@jtommy Hi! this feature is available right now? Or do you have some other options to do this multicolumns feature?
