### ISSUE TITLE
Multiple sticky/fixed columns always visible

### ISSUE THREAD

**Issue by plakak** [buefy/buefy#2793]
### Description

Ability to have more than one sticky/fixed column visible. 

### Why Buefy need this feature

We usually use Ant Design Vue in our projects but this time we went to try something new and gave Buefy a chance. So far so good with one caveat - we need tables that have first two columns always visible and horizontal scroll for next columns. It's straightforward using Ant and there seems to be no way to recreate similar behavior in Buefy. Only one sticky column seems to be visible, they don't stack.

**Comment by dmcbrn** [comment]
Hi, any status update on this feature request?

**Comment by dmcbrn** [comment]
I have checked the code. I could add another parameter `left` to `TableColumn` component which would be analogous to `width` and it should update the `th` the same way the `width` parameter does.

The only difference would be that it would be applied to the `tr > td` as well and not just to the table header `th`. I need to check in more details how to do this first.

Can someone of the admins let me know would something like this be acceptable and if so I can submit a PR? Also I would reuse the `toCssWidth()` function which then might be renamed in the future to `toCssSpatialDimension()` or something similar.

**Comment by nprdservice3** [comment]
Hi @jtommy, any update on this feature request?
