### ISSUE TITLE
style: dropdown item is underlined inside a Bulma message component

### ISSUE THREAD

**Issue by frantic1048** [buefy/buefy#280]
### Overview of the problem

**Buefy** version: 0.5.0
**Vuejs** version: 2.4.2
**OS/Browser**: various

### Description

When put `b-dropdown` inside a Bulma message component, the dropdown item's text is underlined.

### Steps to reproduce

example code:

```jsx
<section class="message">
  <div class="message-header">
    <p>alalah</p>
  </div>
  <div class="message-body">
    <p>button ?</p>
    <b-dropdown hoverable>
        <button class="button is-primary" slot="trigger">
            <span>Click me!</span>
        </button>

        <b-dropdown-item>Action</b-dropdown-item>
        <b-dropdown-item>Another action</b-dropdown-item>
        <b-dropdown-item>Something else</b-dropdown-item>
    </b-dropdown>
  </div>
</section>
```

### Expected behavior

Dropdown items should not have `extra` underline style.

### Actual behavior

Dropdown items are applied with `extra` underline style.

### Reason

Bulma has [rules](https://github.com/jgthms/bulma/blob/1be49f2190db5585dfb268387dd4e1aa93661f95/sass/components/message.sass#L78-L79) like this:

```css
.message-body a:not(class="button") {
  text-decoration: underline;
}
```

One solution is to append a "button" class for `<a>` tag inside b-dropdown.

The other way could be modify the rule above in upstream(Bulma), to exclude `a[role="button"]`.

**Comment by rafaelpimpa** [comment]
Created an issue on Bulma: https://github.com/jgthms/bulma/issues/1130

**Comment by jtommy** [comment]
https://github.com/jgthms/bulma/commit/892c7e7d3beb1819be3a5c7fb821581f30cafdc9
