### ISSUE TITLE
Google Lighthouse indicates Autocomplete dropdown-content has too many elements

### ISSUE THREAD

**Issue by slidenerd** [buefy/buefy#2802]
### Description

- I am using the Buefy Autocomplete to complete user input suggestions
- My array is rather large say 3000 elements roughly
- Google Lighthouse gives me a warning about too many elements in the DOM
- I believe the reason is [THIS LINE in your code](https://github.com/buefy/buefy/blob/dev/src/components/autocomplete/Autocomplete.vue#L40)
- If you used a v-if it would cut down the number of hidden elements drastically
- Now of course not everyone would want this
- A suggestion is to let the user decide if they want to do a v-show or a v-if dynamically with a prop

### Why Buefy need this feature

- Improve Google Lighthouse ratings for a large autocomplete list by not having invisible elements on DOM
- Let the user control if they want to v-show or v-if the elements

**Comment by jtommy** [comment]
Do you really need to show 3k elements ?? Without a filters ?

**Comment by slidenerd** [comment]
@jtommy even after filters i get upto a 1000 elements when the person types only the first letter, it is only after say 3 letters when the results go down to 10 20

**Comment by service-paradis** [comment]
Could this be a good use case for https://buefy.org/documentation/autocomplete#async-with-infinite-scroll?
You could load only a limited set when filtering and load more if necessary when the user scroll the list.

**Comment by slidenerd** [comment]
@service-paradis unfortunately no, before you even start typing a symbol the user would expect all the symbols from a-z being present in the dropdown list, there are soo many symbols that they honestly go upto 3000, you type 'b' in the box, now you need to show btc bch etc etc all the ones that start with b at the least, so I am afraid this is one of those edge cases

**Comment by service-paradis** [comment]
The infinite scroll can be used like you said. Before you start typing a symbol, you display (for example) the 25 first items. If the user scroll the list, you display 25 more then 25 more until it reach the end (if your user scroll that far) where 3000 items would be displayed.

When he start typing, you keep the same behavior. If he types `b`, you display the 25 items and you load more if the user scrolls the list.

Sorry if I'm missing something and it cannot be used in your case.
