### ISSUE TITLE
Taginput watcher not going deep

### ISSUE THREAD

**Issue by thefoxie** [buefy/buefy#2804]
### Overview of the problem

**Buefy** version: [0.9.2]
**Vuejs** version: [2.6.12]
**OS/Browser**: Arch Linux, FF DE 80.0b8

### Description

If my v-model (array of objects so basically element - object) changes, the component won't change the value internally, thus the value gets overwritten when the internal value changes, i.e. when I add another tag (I guess it'd change on removal as well).

### Steps to reproduce

1. Change v-model's array element (object) `[{name: "lol"},{name: "topkek"}]`
2. Value changes only in parent  
3. Add another tag
4. Value in parent is overwritten

### Expected behavior

The v-model/value should be in sync.

### Actual behavior

Value not in sync.

### Possible solution

Add deep property to watcher.
```js
value: {
            deep: true,
            handler(value) {
                this.tags = Array.isArray(value) ? value.slice(0) : value || [];
            },
        },
```

**Comment by jtommy** [comment]
@thefoxie Can you reproduce on codepen ? Did you try setting the `v-model` using `this.$set(this.data, 'myvar', [...])` ?

**Comment by thefoxie** [comment]
What I do:

1. Search predictions from google maps
2. Select one option
3. Do some manipulation outside (getting the chosen value doing some stuff and changing v-model)

The component doesn't take into account that the object was modified.

Take a look.

This is in component's data
![image](https://user-images.githubusercontent.com/15309350/93097437-dc0b8280-f6a5-11ea-8654-5d2a92713850.png)

This is in its props
![image](https://user-images.githubusercontent.com/15309350/93097535-01988c00-f6a6-11ea-9aea-b2987a33c404.png)

```vue
 <b-taginput
            v-model="newLocations"
            v-debounce:1s="loadData"
            :data="data"
            autocomplete
            field="label"
            icon="label"
            placeholder="Search locations"
            debounce-events="typing"
            @input="getAddress"
            @remove="$emit('update', newLocations)"
        >
```
```js
async getAddress(event) {
         // ...
                    this.newLocations[index] = location;
                    this.$emit("update", this.newLocations);
        // ... 
        },
```
