### ISSUE TITLE
Timepicker margins are too big

### ISSUE THREAD

**Issue by Lukasiniho** [buefy/buefy#2805]
### Overview of the problem

**Buefy** version: 0.9.2
**OS/Browser**: Chrome 84.0.4147.135 on Windows 10

### Description

The new timepicker in Buefy 0.9.x is too big/the margins increased. 

### Steps to reproduce

See screenshots below.

### Actual behavior

This is the 0.9.2. timepicker:

![2020-08-24 20_57_19-Lerneinheiten _ Athenify](https://user-images.githubusercontent.com/24393662/91084832-dd203580-e64c-11ea-99d4-fb57bab70912.png)

### Expected  behavior

This is the 0.8.x timepicker. The margin has gotten bigger. It is particularly visible since I use a custom color (not white) for the background of the input fields ($input-background-color)

![2020-08-24 20_57_34-Lerneinheiten _ Athenify](https://user-images.githubusercontent.com/24393662/91084808-d72a5480-e64c-11ea-83e6-05bdf7396814.png)

**Comment by service-paradis** [comment]
Buefy use Bulma styling for most of the component. Since Bulma 0.8, controls height and padding are bigger. You can see it in the Bulma 0.8 release notes (https://github.com/jgthms/bulma/releases/tag/0.8.0). It mention how to revert this back in your project if you want.
