### ISSUE TITLE
<b-image> does not load internal images in a development environment

### ISSUE THREAD

**Issue by Lyefyre** [buefy/buefy#2810]
### Overview of the problem

**Buefy** version: 0.9.2
**Vuejs** version: 2.6.12
**OS/Browser**: Debian 10 / Firefox Quantum 68.11.0esr (64-bit)

### Description

When a vue project is in dev mode (using npm run serve), the src parameter of b-image will not work on internal assets, using either the relative or absolute filepath.

### Steps to reproduce

I could not make the CodeSandbox environment work due to a bunch of other issues. Instead, these steps were reproduced with a clean vue.js project, using the command line vue create and using the presets (babel, eslint).

1. Take a .png file and put it into a folder. ex. "/assets"
2. Create a vue file with the b-image tag
3. In the src parameter, use an internal image. (ex. src="./assets/logo.png")

### Expected behavior

The image loads normally and gives me access to all the comfort that comes with buefy.

### Actual behavior

Image does not load. If "alt" is specified, it will always show alt. Disabling lazy loading or defining an src-fallback did not solve this issue.

` <img alt="Vue logo" src="./assets/logo.png">`
`<HelloWorld msg="Welcome to Your Vue.js App"/>`
`<b-image src="./assets/logo.png" alt="A logo"></b-image>`

Here is a comparison of img and b-image on the page:
https://i.ibb.co/f42Gxqr/tag.png

According to the console, it does not load an img element as the vanilla img tag would and instead loads it as html document.
This is how the console looks like, comparing img and b-image, where the above entry is img and the one below is b-image.

https://i.ibb.co/QkyWQJg/console.png

**Comment by service-paradis** [comment]
Did you try somthing like `:src="require('@/assets/buefy.png')"`?

**Comment by Lyefyre** [comment]
This works! I didn't think about implementing image binding, to solve this issue. Thanks.

**Comment by service-paradis** [comment]
I think I will add an example in the doc for local image :)
