### ISSUE TITLE
Complex progress bar

### ISSUE THREAD

**Issue by eagleera** [buefy/buefy#2815]
### Description

I think Buefy needs a progress bar that allows multiple colors indicating different status, kind of what bootstrap-vue does:

<img width="880" alt="Screen Shot 2020-08-25 at 12 41 37" src="https://user-images.githubusercontent.com/17990400/91214457-52811a00-e6d0-11ea-9ef0-50630b1d6b82.png">

### Why Buefy need this feature

I think it makes the progress bar more dynamic!

**Comment by jtommy** [comment]
It's not a bad idea but the current component needs a full refactoring, what do you think @service-paradis ?

**Comment by service-paradis** [comment]
Love the idea. As you said, it would need a complete refactor since we're using the native `<progress>` element right now and multiple values are not supported. Adding the `improvements` label!
