### ISSUE TITLE
Empty template is not showing for Autocomplete component after 0.8.6

### ISSUE THREAD

**Issue by beejaz** [buefy/buefy#2819]
### Overview of the problem

I think something broke between version 0.8.6 and and 0.9.2 for autocomplete component "empty"-prop/template. Its not showing the empty template when no result is found.

**Buefy** version: 0.9.2
**Vuejs** version: 2.6.10
**OS/Browser**: Windows 10/Chrome 84.0.4147.125

### Description
Hi, when I upgraded from Buefy 0.8.6 to latest 0.9.2 it seems "empty" prop stopped working on autocomplete component. It doesn't work on my application and I tried to examples on autocomplete docs eg https://buefy.org/documentation/autocomplete#header and https://buefy.org/documentation/autocomplete#async-with-custom-template 

Both produces same "problem". It doesnt show the content from the empty template. The first only shows header-component with "Add new" example.

### Expected behavior

Content from empty-template should show when no result is found.
<template slot="empty">No results for {{name}}</template>

### Actual behavior

Template is not shown at all
![image](https://user-images.githubusercontent.com/9569157/91432205-af600a00-e861-11ea-9926-d3bceec51290.png)

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/pull/2818, will be available in the next version

**Comment by beejaz** [comment]
Sorry @jtommy, I tried to search for autocomplete & empty issues. Missed that one. Ill close this.

Thanks!
