### ISSUE TITLE
BTableMobileSort is not exported in esm build, not possible to import from `buefy/dist/esm/table`

### ISSUE THREAD

**Issue by seyfer** [buefy/buefy#2821]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: Mac Os, Chrome

### Description

It is not possible to use BTableMobileSort from esm build. This is not working.
```
import { BTableMobileSort as TableMobileSort } from 'buefy/dist/esm/table';
```

Because in the file `buefy/dist/esm/table` only 2 other components are exported

```
var Plugin = {
  install: function install(Vue) {
    registerComponent(Vue, Table);
    registerComponent(Vue, TableColumn);
  }
};
use(Plugin);

export default Plugin;
export { Table as BTable, TableColumn as BTableColumn };
```

`BTableMobileSort` is defined in this file on the top, lines 15-16

```
var script = {
  name: 'BTableMobileSort',
```

but never exported.

### Steps to reproduce

1. Install Buefy to Vue and configure it.
2. Try to import components from esm build
`  import { BTableColumn as TableColumn, BTable as Table } from 'buefy/dist/esm/table';`
it works
3. Try to import `BTableMobileSort`, and it is not possible.

### Expected behavior

```
import { BTableMobileSort as TableMobileSort } from 'buefy/dist/esm/table';
```
should work

### Actual behavior

```
import { BTableMobileSort as TableMobileSort } from 'buefy/dist/esm/table';
```
not exported

**Comment by jtommy** [comment]
Why do you need it? I don't want to export internal components at the moment.
