### ISSUE TITLE
b-dropdown-item is not working when using v-for loop

### ISSUE THREAD

**Issue by shieldcy** [buefy/buefy#2822]
### Overview of the problem

**Buefy** version: [0.8.2]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS / Safari

### Description

I am using b-dropdown to display some options. When it is static it is working fine.
But when I use a v-for loop on b-dropdown-item, then it returns no results.

### Steps to reproduce

1. Populate a simple array to use in a v-for loop

2. Add it in b-dropdown like below:
```
<template>
<b-dropdown
  class="nav-notification"
  aria-role="list"
  position="is-bottom-left"
>
  <ion-icon slot="trigger" name="notifications-outline" />

  <b-dropdown-item
    v-for="(notification, index) in notifications"
    :key="index" aria-role="listitem"
  >
    {{ notification.title }}
  </b-dropdown-item>
</b-dropdown>
</template>
```

### Expected behavior

"Notifications" is an array that contains a number of notifications.
I am using a v-for loop to loop through all of them and display them as a b-dropdown-item
The expected behavior was to actually display the notifications when using v-for loop in b-dropdown-item

### Actual behavior

When using v-for loop, it returns no results at all when I am using it within the b-dropdown-item (see code above)
It seems like the b-dropdown-item code breaks?

**Comment by ETS-Nathaniel** [comment]
@shieldcy you are missing a value property in your b-dropdown-item component.
 
```
 <b-dropdown-item
    v-for="(notification, index) in notifications"
    :key="index" aria-role="listitem"
    :value="index" //or notification.title, whatever value the item needs to represent
  >
```

**Comment by shieldcy** [comment]
Hello and thanks for your reply

even with the :value="notification.title" added, it won't work.
It is just empty and it prints no error.

```
                  <b-dropdown-item
                    v-for="(notification, index) in notifications"
                    :key="index"
                    :value="notification.title"
                    aria-role="listitem"
                  >
                    {{ notification.title }}
                  </b-dropdown-item>
```
