### ISSUE TITLE
the margin part of the b-table record is displayed in white on the smartphone

### ISSUE THREAD

**Issue by ntogawa07** [buefy/buefy#2824]
### Overview of the problem

**Buefy** version: [0.9.2]
**Vuejs** version: [2.6.11]
**OS/Browser**:chrome, safari, 

### Description

When setting the background color in the style of background-color in the html tag,
the margin part of the b-table record is displayed in white on the smartphone.

### Steps to reproduce

1. Write style to html 
  ```
  html {
    background-color: #aaaaaa;
  }
  ```
2. Write b-table to child node
  I use code from here.
  [https://buefy.org/documentation/table]()
3.  Launch the development server and check on your smartphone.

### Expected behavior

The margin of the b-table record is displayed with the background color set in the html tag.

### Actual behavior

The margin of the b-table record is overwritten with white.

<img width="226" alt="sp_b-table" src="https://user-images.githubusercontent.com/60598070/91537351-1e685c00-e951-11ea-8189-38252772606a.png">

**Comment by holtolee** [comment]
i think i fixed that in a project, i will look and if i can make a PR

**Comment by ntogawa07** [comment]
Thank you for your quick response!!!

**Comment by holtolee** [comment]
you're welcome but idk if the PR will be accepted i'm a new contributor. but you can overide your code with same css normally.

**Comment by ntogawa07** [comment]
thank you for the advice! I hope your PR is approved

**Comment by jtommy** [comment]
@ntogawa07 did you try setting the background color with bulma variable ? https://bulma.io/documentation/customize/variables/#generic-variables

**Comment by ntogawa07** [comment]
@jtommy 
I tried it like 
```scss
$body-background-color: #aaaaaa;
```
 but the result did not change
