### ISSUE TITLE
props.row access problem

### ISSUE THREAD

**Issue by AlexeySeySey** [buefy/buefy#2826]
**Buefy** version: [0.9.2]
**Vuejs** version: [2.6.10]
**OS/Browser**: Linux Ubuntu, Google Chrome

### Description

How can i access props.row and all of it properties? For example i need to set condition like on image, show column depending on any other property of props.row, that differs from props.row.name.

IMAGE: https://user-images.githubusercontent.com/38053682/91563390-6d10f880-e947-11ea-83f1-2f9d753f13cb.png

**Comment by jtommy** [comment]
It's no correct show ot hide a column depending on a value of a field in a row
