### ISSUE TITLE
Carousel list: element width wrongly calculated

### ISSUE THREAD

**Issue by AntoineChwat** [buefy/buefy#2830]
When using a carousel list in a card in a modal, the result of the computation [here](https://github.com/buefy/buefy/blame/dev/src/components/carousel/CarouselList.vue#L189) is wrong: it seems to account for the margin around the `card` element, and thus the last element of the list is slightly clipped. When resizing the window however the width of all elements in the list is correctly recalculated (although if I close the modal and open it again it is again miscalculated). That being said, `this.$el.clientWidth` returns the correct result at all times, so it might be better to use the result of this instead? Attached is a screen cap of the issue:
![image](https://user-images.githubusercontent.com/15050612/91640538-994b7880-ea1e-11ea-91e0-0604101a2dc5.png)

**Comment by jtommy** [comment]
What version?

**Comment by AntoineChwat** [comment]
Latest version (0.9.2), but I also noticed it in 0.8.20 before that, which prompted me to update to see if it was any better but nope, the width is calculated in the same way in both versions as far as I can tell

**Comment by jtommy** [comment]
@Tofandel do you agree with the proposal?

**Comment by Tofandel** [comment]
I don't think this is what's causing the bug, it comes from the fact that the item is within a modal which has a css transition when opening, it's a very frequent problem in everything that requires width computation

I think either a way to recompute when the animation is done or simply not need the width calculation is the way to go, If you trigger a window event resize after the transition is complete programmatically you can get a workaround but the best is just to add a refresh method and use it

@AntoineChwat can we see some code or reproduction to make sure?

**Comment by Tofandel** [comment]
Maybe adding this kind of listeners https://stackoverflow.com/questions/14796936/how-do-you-detect-when-css-animations-start-and-end-with-javascript

Otherwise we should just have a provider on any element having a <transition> in them and inject the elements that require width computation and listen for transition end and refresh the injected children

**Comment by Tofandel** [comment]
I just did some tests and the transition element of vue fires the event a bit differently than expected, so it needs another PR with more events
