### ISSUE TITLE
How to use/import only specific fonts from mdi?

### ISSUE THREAD

**Issue by Saunved** [buefy/buefy#2833]
I am using buefy with nuxt from the nuxt-buefy package. The @mdi/font library used has a very large footprint and it results in quite a large final build size. In reality, I am using less than 12-15 icons from the library, and I don't want the rest to show up in the final build since they are not required.
### Description
I looked into using @mdi/js. This is how I can import fonts using that library:

```vue
<template>
<div>
    <svg style="width:24px;height:24px" viewbox="0 0 24 24">
       <path fill="#000000" :d="mdiBikeFast" />    
   </svg>
</div>
</template>
<script>
import {mdiBikeFast} from '@mdi/js';
data(){
    return {
        mdiBikeFast
    }
}
</script>
<style></style>
```
I am able to render the icons as ```<svg>``` elements - but I lose the freedom to use them in ```<b-icon icon="some-icon"></b-icon>``` or other scenarios like ```<b-button icon-right="some-icon"></b-button>```
The number input ```+``` and ```-``` icons don't show up either for the same reason.

### What can be done?
If there was some way in which we could import only specific icons from the mdi library and be able to use them in buefy exactly the way we are using them currently, that would reduce the final build size of the project by quite a lot. I don't know if this is possible right now or this is something that requires a change in the library itself.

Thanks for the help!

**Comment by jtommy** [comment]
You have to create a custom component as proxy.
It's no MDI but you can find the main idea https://codesandbox.io/embed/buefy-vue-feather-dhtjd?codemirror=1

**Comment by Ratatinator97** [comment]
Hey I tried to replicate and understand the code [https://codesandbox.io/embed/buefy-vue-feather-dhtjd?codemirror=1](https://codesandbox.io/embed/buefy-vue-feather-dhtjd?codemirror=1)  but it's not working for me. I'm trying to have the lighter package possible that's why I'm importing Buefy's components one by one. Now I only want to import the icons I need. 
Here is my code, I don't know what I'm doing wrong:
```
import Vue from 'vue'

//  MDI imports
import 'vue-material-design-icons/styles.css';
import AccountIcon from 'vue-material-design-icons/Account.vue';
import InformationIcon from 'vue-material-design-icons/Information.vue';
import HomeIcon from 'vue-material-design-icons/Home.vue';
import AccountCircleIcon from 'vue-material-design-icons/AccountCircle.vue';
import CogIcon from 'vue-material-design-icons/Cog.vue';
import UploadIcon from 'vue-material-design-icons/Upload.vue';
import MessageIcon from 'vue-material-design-icons/Message.vue';
import DeleteIcon from 'vue-material-design-icons/Delete.vue';
import BackspaceIcon from 'vue-material-design-icons/Backspace.vue';
import ContentCopyIcon from 'vue-material-design-icons/ContentCopy.vue';
import AlertCircleIcon from 'vue-material-design-icons/AlertCircle.vue';

// Buefy imports
import {Input,Navbar,Button,Field,Modal,Notification,Dialog,Select,ConfigProgrammatic} from 'buefy'

// Use individual components
Vue.use(Input)
Vue.use(Navbar)
Vue.use(Button)
Vue.use(Field)
Vue.use(Modal)
Vue.use(Notification)
Vue.use(Dialog)
Vue.use(Select)

// Icon to Vue components 
Vue.component('account-icon', AccountIcon);
Vue.component('information-icon', InformationIcon);
Vue.component('home-icon', HomeIcon);
Vue.component('account-circle-icon', AccountCircleIcon);
Vue.component('cog-icon', CogIcon);
Vue.component('upload-icon', UploadIcon);
Vue.component('message-icon', MessageIcon);
Vue.component('delete-icon', DeleteIcon);
Vue.component('backspace-icon', BackspaceIcon);
Vue.component('content-copy-icon', ContentCopyIcon);
Vue.component('alert-circle-icon', AlertCircleIcon);
// Custom component to proxy 
ConfigProgrammatic.setOptions({
    //defaultIconComponent: "vue-material-design-icons",
    defaultIconPack: "mdip", // Do I have to give a custom name ?
    customIconPacks: {
      mdip: { // Same name that was declared earlier ?
        sizes: {
          default: "1.5x",
          "is-small": "1x",
          "is-medium": "2x",
          "is-large": "3x"
        },
        iconPrefix: "",
        internalIcons: {
          account: "account-icon",
          information: 'information-icon',
          home: "home-icon",
          accountCircle: "account-circle-icon",
          cog: "cog-icon",
          upload: "upload-icon",
          message: "message-icon",
          delete: "delete-icon",
          backspace: "backspace-icon",
          contentCopy: "content-copy-icon",
          alertCircle: "alert-circle-icon"
        }
      }
    }
});
```
