### ISSUE TITLE
Datepicker Rage shows current year instead of the max given year

### ISSUE THREAD

**Issue by re2005** [buefy/buefy#2837]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.12]
**OS/Browser**: All

### Description

When setting a limit to the datepicker the default YEAR selection shows the current year and not the MAX of the given date.

![buefy-datepicker-bug](https://user-images.githubusercontent.com/2920357/91843224-aef6b300-ec55-11ea-90d8-b922733b3923.gif)

Also if going to the max age, the options get reduced to a few and not till 2002.

<img width="534" alt="max-age" src="https://user-images.githubusercontent.com/2920357/91843693-760b0e00-ec56-11ea-9cc2-26903c92bfdf.png">

### Steps to reproduce

Set a mininum and max dates before the todays.
Lets say you asking user date of birth and you only accept user older than 18.
So maximum age is equal of today minus 18 years.

### Expected behavior

Expected the YEAR selector to be the MAX given year.

### Actual behavior

**Please check:**
https://codepen.io/re2005/pen/dyMzQjQ

By setting a date that is a few years before today, the year select will keep in 2020, what makes all days unselectable and thefore confusing.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2838
