### ISSUE TITLE
Upgrading from buefy@0.8.20 to buefy@0.9.2 - BIcon bug

### ISSUE THREAD

**Issue by yangwao** [buefy/buefy#2839]
### Overview of the problem

**Buefy** version: [0.9.2]
**Vuejs** version: [2.6.11]
**OS/Browser**: OSX/Chrome

### Description

Apparently <BIcon> component is broken or doesn't parse props properly?
Icons doesn't work in whole project. Not sure if some dependency is broken? We are using fontawesomeicon

### Steps to reproduce

1. clone https://github.com/vue-polkadot/apps/tree/f988a80603d6edecc826013e48f04957c7b4464e
2. yarn;yarn add buefy@0.9.2
3. yarn serve
4. localhost:9090

### Expected behaviour

See icons

### Actual behaviour
```
[Vue warn]: Error in render: "TypeError: Cannot convert undefined or null to object"

found in

---> <BIcon>
```

I think to start somewhere here https://github.com/vue-polkadot/apps/blob/f988a80603d6edecc826013e48f04957c7b4464e/dashboard/src/components/accounts/Accounts.vue

![image](https://user-images.githubusercontent.com/5887929/91851485-896ea700-ec5f-11ea-83f6-b5ce56b7faff.png)

**Comment by service-paradis** [comment]
Do you define any custom sizes for your icon like below:
```json
customIconPacks: {
  'fas': {
    sizes: {
      'default': '',
      'is-small': 'fa-xs',
      'is-medium': 'fa-lg',
      'is-large': 'fa-2x'
    }
  }
}
```
If so, be sure to use empty string instead of `null` if you customize something.

**Comment by yangwao** [comment]
@service-paradis thank you, yes, we are using null not sure why. Maybe some hack hack.
https://github.com/vue-polkadot/apps/blob/f988a80603d6edecc826013e48f04957c7b4464e/dashboard/src/main.ts#L31

Works well with 
```
customIconPacks: {
    fas: {
      sizes: {
        'default': '',
        'is-small': '1x',
        'is-medium': '2x',
        'is-large': '3x',
      },
    },
  },
```

Now it works! Thank you, closing.
