### ISSUE TITLE
BTable cell classes with v-slots

### ISSUE THREAD

**Issue by adrianrudnik** [buefy/buefy#2841]
### Overview of the problem

**Buefy** version: 0.9.2
**Vuejs** version: 2.6.12
**OS/Browser**: any

### Description

I'm unsure what changed from 0.8.x to 0.9.2 in BTableColumn but somehow this old approach does no longer work. Simple goal was to change the "state" column class to green/red based on a row value. This is how it looked:

```javascript
<b-table :data="...">
  <template slot-scope="props">
    <b-table-column>{{ props.row.id }}</b-table-column>
    <b-table-column :cell-class="'has-background-state-' + props.row.state"> ... </b-table-column>
  </template>
</b-table>
```

Now the examples all use `v-slot` directly on the BTableColumn and the old `slot-scope="props"` leads to an empty `props`. Also a combination of `v-slot="props" :cell-class="props.row.state"` leads to `Property or method "props" is not defined on the instance but referenced during render.`

Did we loose the functionality somehow or am I just bad at understanding v-slot on components? It's most likely latter, but I'm at a loss how to solve it.

### Steps to reproduce

Tried to create a working example with codesandbox.io and jsfiddle but both just show empty white pages in chrome right now. I'll try further to get it working.

**Comment by jtommy** [comment]
The old syntax wasn't good for internal use and above all it can bring to not correct use (for example hide a column checking a field of a row).
In your case you should wrap your table column content in container and add to it the custom class.

**Comment by wishinghand** [comment]
> In your case you should wrap your table column content in container and add to it the custom class.

By this, do you mean to wrap the entire `<b-table-column>` with a `div` or `span` and give that wrapping element a class?

**Comment by juanfabrega** [comment]
@wishinghand did you ever find a solution to this? I am facing the same issue at the moment.

**Comment by jtommy** [comment]
Try `td-class` prop
