### ISSUE TITLE
Switch Change Opposite Value

### ISSUE THREAD

**Issue by pagelyadam** [buefy/buefy#2846]
### Overview of the problem

**Buefy** version: 0.9.2
**Vuejs** version: 2.6.11
**OS/Browser**: Firefox Developer Edition

### Description

When using `:value` or `v-model` to set the default value of a switch using `true` or `boolean`, the default value is set correctly however, when clicking to the change the value, the opposite value is provided. If I remove the default value and let the switch default to false, then the value provided when changing the switch is correct.

### Steps to reproduce

Well, simple add the switch and use one of the props to set the default to true. Then, click the switch to change!

### Expected behavior

When the switch is clicked, provide the accurate value.

### Actual behavior

Please see description this is kind of redundant.

**Comment by jtommy** [comment]
A code example ?

**Comment by pagelyadam** [comment]
Apparently I need to use "@input" instead of "@click" or "@click.native". I really wish the documentation and examples were better. I know the framework is in its infancy and I would be more than happy to contribute.

<b-switch :value="user.admin" type="is-yellow" @input="doChangeAdmin"></b-switch>
