### ISSUE TITLE
Setting the current-page prop on a table with pagination has no effect

### ISSUE THREAD

**Issue by andrei-dracea** [buefy/buefy#2851]
### Overview of the problem

**Buefy** version: [0.9.0]
**Vuejs** version: [2.6.11]
**OS/Browser**: MacOS Mojave/Chrome

### Description

When modifying the value of `current-page` the table only gets updated once, after that setting the value has no effect.

### Steps to reproduce

Go to [table documentation page](https://buefy.org/documentation/table/#pagination-and-sorting), click the `Set to page 2` button, click another page afterwards, then try to click the button again. It does not do anything.

### Expected behavior

I expect the page to be set every time I change the value of `current-page`.

### Actual behavior

The page stays the same.

**Comment by re2005** [comment]
This happens because the value of the prop `currentPage` never changes again it keeps on "2"]

And Watch won't be trigged when the value is the same as before.

https://forum.vuejs.org/t/watch-doesnt-fire-if-value-is-same/38002/3
