### ISSUE TITLE
sidebar closes when date picker is placed inside buefy sidebar

### ISSUE THREAD

**Issue by hussain123** [buefy/buefy#2852]
I faced this issue when I implemented a filter form inside buefy sidebar,  this issue appeared when you select a date from the datepicker then it weirdly closes the sidebar.

**Comment by jtommy** [comment]
Can you reproduce it on codepen?

**Comment by datrinh** [comment]
Most likely related to https://github.com/buefy/buefy/issues/2853

**Comment by sheshadri** [comment]
Hi there,

There still seems to be some problem while selecting date from datepicker on which the sidebar automatically closes.

Here is the the codepen link 

https://codepen.io/sheshadri/pen/LYxQJzP
