### ISSUE TITLE
Add "outlined" attribute to upload inputs/ buttons

### ISSUE THREAD

**Issue by major-mayer** [buefy/buefy#2857]
### Description
It would be really cool if you could style your upload button a bit more:
For my usecase a "outlined" attribute would be very handy, so I don't have to style it with my own CSS.

something like this
```html
      <b-upload v-model="file" accept=".stl" expanded outlined>
        <a class="button is-primary is-fullwidth">
          <b-icon icon="upload"></b-icon>
          <span>Change Mesh</span>
        </a>
      </b-upload>
```

### Why Buefy need this feature
Buefy could benefit from it, because it users can consistenly style their normal buttons and their upload input field outlined.

**Comment by jtommy** [comment]
You can use `b-button` as slot with `outlined` prop

**Comment by major-mayer** [comment]
Many thanks, that sounds good, I will try it out next week. 
Would be a good addition to the docs I guess. At least I couldn't figure out myself how to do it.

**Comment by major-mayer** [comment]
If i change it to this:
```js
<b-upload @input="changeMesh" accept=".stl" expanded>
        <b-button type="is-primary" outlined expanded>
          <b-icon icon="upload"></b-icon>
          <span>Change Mesh</span>
        </b-button>
</b-upload>
```

The button is indeed outlined, but if i click on it nothing happens.
It only works when i manually change the z-index of the input tag to something over -1.
Any ideas @jtommy  ?

**Comment by jtommy** [comment]
Try using native-tag="a" too

**Comment by major-mayer** [comment]
Thanks, using `tag="a"` on the b-buttom component does the trick.
