### ISSUE TITLE
Table documentation still uses old slot syntax; cannot customise search slot

### ISSUE THREAD

**Issue by unikitty37** [buefy/buefy#2860]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]
**OS/Browser**: macOS 10.14.6 (18G6020) / Vivaldi 3.2.1967.47 (Stable channel) (64-bit)

### Description

With the syntax changes to tables in Buefy 0.9.0, attempting to customise the search slot fails. It is not possible to refer to the documentation to see how to do it, as the documentation still uses the old syntax..

The code I'm using is below:

```
      <b-table-column
        field="name"
        label="Name"
        searchable
      >
        <template v-slot:searchable="props">
          <b-input
            v-model="props.filters['name']"
            placeholder="Search…"
            icon="magnify"
            size="is-small"
          />
        </template>

        <template v-slot:default="props">
          {{ props.row.score > 0 ? '👍' : '😡' }}
          {{ props.row.name }}
        </template>
      </b-table-column>
```

### Steps to reproduce

1. Clone https://github.com/unikitty37/buefy-custom-search
2. `yarn install && yarn serve`
3. Click on "Custom Rows + Custom Searchable" at the top

### Expected behavior

The search box should be small, with placeholder text and a magnify icon.

https://buefy.org/documentation/table is using the current syntax in the example code.

### Actual behavior

The search box retains its default style.

https://buefy.org/documentation/table still uses `<template slot="searchable" slot-scope="props">`, which produces a compilation error complaining about mixed slot syntaxes.

(additionally, the "name" column should be flush left, as I did not specify `centered` :)

Unfortunately, I cannot use the CodeSandbox template as the output window just renders as blank no matter what I do, hence the repo showing the issue.

**Comment by unikitty37** [comment]
OK, this is a bit of a mystery, as I've refreshed the page today and it is now rendering correctly, so that *is* the way to do it 🤯

I'll leave the issue open as the docs are still referring to the old syntax, though; I'll tack on a PR with updates later.

**Comment by jtommy** [comment]
Your code is correct and docs too, probably not new 2.6 syntax but always valid

**Comment by christoph-werker** [comment]
You saved me a lot of headache 👍  Thanks
