### ISSUE TITLE
Autocomplete - Not holding focus on click

### ISSUE THREAD

**Issue by appfuse-io** [buefy/buefy#2863]
I am using an autocomplete where I update the :data on click, effectively the UI is:

- Customer types a State and it autocompletes the state
- Upon State selection the :data is updated with major cities
- << I need the downdown to remain open here but be updated (the update I have done but I have to click on the input again) >>

What I am asking for is for close-on-click = false to be possible on autocomplete please?

**Comment by jtommy** [comment]
Did you tried to simulate focus after first selection or calling toggle method by ref ?

**Comment by appfuse-io** [comment]
I've got ref and can select focus as the autocomplete but the key here is drop down closes even though it's focussed and has open on focus.

**Comment by jtommy** [comment]
A code example ?

**Comment by appfuse-io** [comment]
https://codepen.io/johnnyboyjohn/pen/WNwdExb

**Comment by jtommy** [comment]
Use `this.$nextTick(() => this.$refs.autocomplete.focus())`

**Comment by appfuse-io** [comment]
Thank you, that worked!  Do you have a beer fund I can donate to?

**Comment by jtommy** [comment]
No, i have PayPal (see my public email)

**Comment by appfuse-io** [comment]
Done. Enjoy your beer.

**Comment by jtommy** [comment]
Thanks 🎉
