### ISSUE TITLE
Date range - limit range dynamically based on first date selected in a range

### ISSUE THREAD

**Issue by seyfer** [buefy/buefy#2864]
# Description

Hello!

I need to limit the date range selection dynamically, based on the first date selected. 
Currently, it is not possible to do with `BDatepicker`. There are static restriction options `minDate` and `maxDate` but they are not reactive. 
I tried to use the range start and range end events to manipulate these properties on the range selection event, but the `BDatepicker` component does not react to dynamic changes of these properties.

If I set an initial restriction for 20 years in the past
```
      const today = new Date();
      const defaultMinDate = new Date(today.getFullYear() - 20, today.getMonth(), today.getDate());
      const defaultMaxDate = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());
      const minDate = ref<Date>(defaultMinDate);
      const maxDate = ref<Date>(defaultMaxDate);
```

and I use these reactive refs in `BDatepicker` properties
```
minDate: minDate.value,
maxDate: maxDate.value,
```

and I manipulate these dates values on events. at the start, I want to set a limit +- 3 months.
```
            'range-start': (date: Date) => {
              console.info(date);

              minDate.value = new Date(
                date.getFullYear(), date.getMonth() - 3, date.getDate(),
              );
              maxDate.value = new Date(
                date.getFullYear(), date.getMonth() + 3, date.getDate(),
              );

              console.log([minDate.value, maxDate.value]);
            },
```
in the end, I want to drop the limit to default one from above.
```
          'range-end': (date: Date) => {
              console.info(date);

              minDate.value = defaultMinDate;
              maxDate.value = defaultMaxDate;

              console.log([minDate.value, maxDate.value]);
            },
```

It does not work. Date range limit never changes from initially set limit. I can only conclude that inside `BDatepicker` maxDate and minDate properties are not used reactively.

![Screenshot 2020-09-07 at 10 51 58](https://user-images.githubusercontent.com/1483925/92369402-44cc8b00-f0f9-11ea-9e75-6410276f7b20.png)
![Screenshot 2020-09-07 at 10 52 07](https://user-images.githubusercontent.com/1483925/92369410-472ee500-f0f9-11ea-8ad6-7923e04d87d6.png)

**Expected:**

When I click on the first date in a range and an event code changes minDate and maxDate values, I should not be able to select a second date out of a dynamically set date range limit.

### Why Buefy need this feature

Dynamically setting date range limits is a common feature for any date range picker, like this one
https://innologica.github.io/vue2-daterange-picker/#example-playground
https://github.com/charliekassel/vuejs-datepicker
and many others.

If this feature is not present, users might be forced to use another date picker library with a better date range support.

**Comment by seyfer** [comment]
Additionally, I tried to use `selectableDays` property to list all the selectable dates in a range, but it seems like not reactive as well.

```
selectableDates: getDateRangeArray(minDate.value, maxDate.value),
```

does not lead to a dynamically changing range limit.

**Comment by jtommy** [comment]
Can you reproduce it on codepen or similar?

**Comment by seyfer** [comment]
@jtommy it works https://codepen.io/seyfer/pen/vYGpbEo?editors=1010

the problem was that we use Vue composition api and these ref variables were declared inside `render()` function and it was hard to spot it that it does not work. 🙈 

```
    return function render() {

const minDate = ref<Date>(defaultMinDate);
    const maxDate = ref<Date>(defaultMaxDate);
...
```

refs should be outside.
