### ISSUE TITLE
Specifying components will also determine the file size

### ISSUE THREAD

**Issue by febrihidayan** [buefy/buefy#2869]
### Description

How to use multiple components and the file size is also reduced. I've done it based on the existing documentation, but the file size remains the same.

### Why Buefy need this feature

specifying components will also determine the file size

**Comment by jtommy** [comment]
An example?

**Comment by febrihidayan** [comment]
Suppose I want to use all buefy components with a file size of 88KB. Then I want to use 8 of all buefy's components to reduce the file size. However, the file size remains the same even though I only use 8 buefy components

**Comment by jtommy** [comment]
Yes, but I need to see your code 😃

**Comment by febrihidayan** [comment]
Like this I do

```js
...

import {
    ConfigProgrammatic,
    Button,
    Input,
    Navbar,
    Table,
} from 'buefy'

Vue.use(Button)
Vue.use(Input)
Vue.use(Navbar)
Vue.use(Table)

ConfigProgrammatic.setOptions({
    defaultIconPack: 'fas',
    defaultSnackbarDuration: 5000,
    defaultToastDuration: 3000,
    defaultNoticeQueue: false
})
```

**Comment by jtommy** [comment]
What version are you using?

**Comment by febrihidayan** [comment]
version 0.8.20

**Comment by holtolee** [comment]
@febrihidayan is it working with the line by line method like this ? (i think i had similar problem with lodash)

import ConfigProgrammatic  from 'buefy/ConfigProgrammatic'
import Button  from 'buefy/Button'
import Input from 'buefy/Input'
import Navbar from 'buefy/Navbar'
import Table from 'buefy/Table'

**Comment by febrihidayan** [comment]
@holtolee  I've tried, but it doesn't work. But I will find an error like this
`Module not found: Error: Can't resolve 'buefy/Button' in ...`

**Comment by jtommy** [comment]
I think the problem is config programmatic, removing it should be ok.
You should try with 0.9.x, it has bee fixed (I hope 😃 )

**Comment by holtolee** [comment]
@jtommy our projects import all and never tried to import only what we used. Very nice if it's working in 0.9.x <3

**Comment by jtommy** [comment]
@holtolee it works with 0.8.x but i remember an issue using importing `ConfigProgrammatic`

**Comment by febrihidayan** [comment]
@jtommy Using version 0.9 makes me tired of fixing all table components. Could you please update it so that I can choose two options, the previous version and the newer version to use the table component. If that is done I will immediately use the current version

**Comment by jtommy** [comment]
You are right and I understand your need but I cannot maintain another (old) version.
My idea is to release a "bugless" version before a breaking but I cannot be sure about it.
