### ISSUE TITLE
B-image: srcset fallback for webp

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2870]
### Overview of the problem

**Buefy** version: 0.9.3
**OS/Browser**: Safari 13.1.2

### Description

If the webp fallback doesn't have the same filename, using the extension isn't just enough.

If we use the full url in `webp-fallback`, `srcset` remains unchanged with `.webp` files. In this case, Safari is trying to load `.webp` from `srcset` and ignores the `src` attribute.

### Steps to reproduce

```html
<b-image 
  src="https://picsum.photos/id/237/800/450.webp"
  webp-fallback="https://picsum.photos/id/1062/1600/900"
  srcset="https://picsum.photos/id/237/800/450.webp 400w, https://picsum.photos/id/237/800/450.webp 800w, https://picsum.photos/id/237/800/450.webp 1600w"
/>
```

Output:
```html
<img srcset="https://picsum.photos/id/237/800/450.webp 400w, https://picsum.photos/id/237/800/450.webp 800w, https://picsum.photos/id/237/800/450.webp 1600w" src="https://picsum.photos/id/1062/1600/900" width="548" sizes="548px" class="has-ratio">
```

### Actual behavior

![image](https://user-images.githubusercontent.com/8303937/92584663-d23fe480-f28b-11ea-811a-7ca213727feb.png)

### Potential solution

Allow to define a specific webp fallback for the srcset attribute?!

**Comment by service-paradis** [comment]
As a workaround, you can use `srcset-sizes` and `srcset-formatter`. The first argument received in `srcset-formatter` will be the `webp-fallback` if webp is not supported. This way, you will be able to build the `srcset` as you need.

Something like the following:
```
formatSrcset(src, size) {
  const ext = this.getExt(src)
  let name = src.split('.').slice(0, -1).join('.')
  if (ext !== 'webp') {
    name = 'another-file-name'
  }
  return `${name}-${size}.${ext}`
}
```
