### ISSUE TITLE
b-table searchable multiple sort criteria comma separeted for the same column

### ISSUE THREAD

**Issue by gelubt5** [buefy/buefy#2873]
Hi.Would be nice if we could filter the same column in b-table by multiple sort criteria !!!
Example: Column Name contains: Mihai , Gelu , Irina , Laurentiu........when in Column name textbox search i introduce Mihai,Irina ...then only table rows with name Mihai and Irina should be visible !!!

**Comment by jtommy** [comment]
Please open a correct issue with code example using codepen or similar, thanks
