### ISSUE TITLE
Carousel List: Make "items-to-show" responsive for device classes

### ISSUE THREAD

**Issue by major-mayer** [buefy/buefy#2878]
### Description
I would love to see the possibility to make the value "items-to-show" responsive.

I've hacked something together, using media queries from javascript side, but this is not very clean and lots of code to add.
Plus i don't know how to access to Buefys own SCSS variables, so i have to write them in a seperated .scss file and import them later.

Here is what I use now (just for reference, maybe it helps someone later): 
```js
    const isMobile = window.matchMedia(`(max-width: ${styling.tablet})`);
    const isTablet = window.matchMedia(`(min-width : ${styling.tablet}) and (max-width: ${styling.desktop})`);
    const isDesktop = window.matchMedia(`(min-width : ${styling.desktop}) and (max-width: ${styling.widescreen})`);
    const isWidescreen = window.matchMedia(`(min-width : ${styling.widescreen}) and (max-width: ${styling.fullhd})`);
    const aboveFullHd = window.matchMedia(`(min-width : ${styling.fullhd})`);

    if (isMobile.matches) {
      this.itemsToShow = 2.5;
    } else if (isTablet.matches) {
      this.itemsToShow = 3.5;
    } else if (isDesktop.matches) {
      this.itemsToShow = 4.5;
    } else if (isWidescreen.matches) {
      this.itemsToShow = 5.5;
    } else {
      this.itemsToShow = 7.5;
    }

    isMobile.onchange = () => {
      if (isMobile.matches) {
        this.itemsToShow = 2.5;
      }
    };
    isTablet.onchange = () => {
      if (isTablet.matches) {
        this.itemsToShow = 3.5;
      }
    };
    isDesktop.onchange = () => {
      if (isDesktop.matches) {
        this.itemsToShow = 4.5;
      }
    };
    isWidescreen.onchange = () => {
      if (isWidescreen.matches) {
        this.itemsToShow = 5.5;
      }
    };
    aboveFullHd.onchange = () => {
      if (aboveFullHd.matches) {
        this.itemsToShow = 7.5;
      }
    };
```

### Why Buefy need this feature
Depending on which device your are looking at the carousel list, the number of items that should be displayed can greatly vary.
For example: On any > Full HD monitor i would like to see 8 preview pictures, but on any smaller display the number should be reduced.

Edit: I just tried removing the items to show attribute and specifying a fixed width for each item.
```css
div.carousel-slide {
  width : 200px !important;
}
```
This is almost sufficient for my purposes, but now the height of each list item varies 😢 
Actually I'm not sure what's the best approach here...

**Comment by service-paradis** [comment]
Not a solution to your issue, but maybe an answer to a question. Buefy uses Bulma breakpoint. They are located in Bulma folder `sass/utilities/initial-variables.sass` and defaults are looking like this:
```
// Responsiveness
// The container horizontal gap, which acts as the offset for breakpoints
$gap: 32px !default
// 960, 1152, and 1344 have been chosen because they are divisible by both 12 and 16
$tablet: 769px !default
// 960px container + 4rem
$desktop: 960px + (2 * $gap) !default
// 1152px container + 4rem
$widescreen: 1152px + (2 * $gap) !default
$widescreen-enabled: true !default
// 1344px container + 4rem
$fullhd: 1344px + (2 * $gap) !default
$fullhd-enabled: true !default
```

If you want to access those variables in your code, you will need to export them or use something like https://github.com/service-paradis/bulma-variables-export that can do it for you.

**Comment by major-mayer** [comment]
Thanks for the tip, this helper seems really useful.
Even though I didn't get the "scoped" import to run 

```

This dependency was not found:

* bulma-variables-export/sass/initial-variables in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Editor/MeshGallery.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save bulma-variables-export/sass/initial-variables
```
Using just `import styling from "bulma-variables-export";` works tho, but I think the discussion would be a bit offtopic here ;)

**Comment by service-paradis** [comment]
@major-mayer Yeah, would be best to open an issue directly in the repo :)

**Comment by service-paradis** [comment]
I think it is possible using the `breakpoints` prop of the Carousel List:
```
breakpoints: {
  768: {
    hasGrayscale: false,
    itemsToShow: 4
  },
  960: {
    hasGrayscale: true,
    itemsToShow: 6
  }
}
```
You can take a look at this example:
https://buefy.org/documentation/carousel#custom-as-an-indicators

**Comment by major-mayer** [comment]
Yes seems to be working, thank you :) 
I must have somehow overlooked this in the first place.

This is how I do it now, if it helps someone:
```vue
<template>
 <b-carousel-list
            :items-to-show="itemsToShow"
            v-model="galleryModel"
            :breakpoints="galleryBreakpoints"
          > ... 
</b-carousel-list>
</template>
import styling from "bulma-variables-export/sass/initial-variables.scss";

<script>
 data() {
    return {
      galleryModel: 0,
      itemsToShow: 2.5,
      galleryBreakpoints: {
        [styling.tablet.slice(0, -2)]: {
          itemsToShow: 3.5,
        },
        [styling.desktop.slice(0, -2)]: {
          itemsToShow: 4.5,
        },
        [styling.widescreen.slice(0, -2)]: {
          itemsToShow: 5.5,
        },
        [styling.fullhd.slice(0, -2)]: {
          itemsToShow: 7.5,
        },
      },
    };
  },
</script>
```

Saves a lot of code in comparison to my first solution 👍
