### ISSUE TITLE
Datetimepicker a11y - keyboard focus trapped in month dates

### ISSUE THREAD

**Issue by jq-87** [buefy/buefy#2880]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome

### Steps to reproduce
1. Use tab key to access month dates
2. Try to exit month date focus with keyboard - you can not

### Expected behavior
Users need to navigate all controls with keyboard.
Example of suggested functionality is here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/datepicker-dialog.html

### Actual behavior
It is currently not possible to exit date selector area with keyboard.
https://buefy.org/documentation/datetimepicker/

**Comment by service-paradis** [comment]
I'm not sure to understand. When opening the month dropdown, we can navigate inside it without any trouble. Pressing enter on a date will select it. And pressing escape will close the dialog.

It looks to have the same behavior as the linked example.

**Comment by jq-87** [comment]
<img width="924" alt="Screen Shot 2021-02-25 at 3 59 13 PM" src="https://user-images.githubusercontent.com/609653/109217215-8f16f680-7783-11eb-9957-906d42b15854.png">

<img width="984" alt="Screen Shot 2021-02-25 at 4 05 28 PM" src="https://user-images.githubusercontent.com/609653/109217229-963e0480-7783-11eb-9367-8dbe6d0d9f01.png">

**Comment by service-paradis** [comment]
I understand now, sorry. The fix that were made in #3197 will solve your issue. It will works as expected in the next release.
