### ISSUE TITLE
Ability to set type/color for menus through an attribute

### ISSUE THREAD

**Issue by JoeRourke123** [buefy/buefy#2882]
Currently, you are able to set the type (colour) for almost all the buefy components - however menus do not have this option. You have to use the SCSS variables but this cannot be changed at runtime, which is something I really need for a colour customisation option in the . Can someone suggest to me a way which this can be done currently or if this could be added?

**Comment by jtommy** [comment]
You can editing bulma sass variables https://bulma.io/documentation/components/menu/#variables
