### ISSUE TITLE
Table not accepting array of objects anymore

### ISSUE THREAD

**Issue by rsoares88** [buefy/buefy#2883]
### Overview of the problem

**Buefy** version: ^0.9.3
**Vuejs** version: ^2.6.12
**OS/Browser**: Any

### Description
btable is broken when using array of objects, gives properties not set, when its working in older versions

### Steps to reproduce
Use an array of objects

### Expected behavior
Render the table without errors

### Actual behavior
gives properties not found errors

**Comment by jtommy** [comment]
An example on codepen?

**Comment by service-paradis** [comment]
Most of the example in the docs are using array of object (https://buefy.org/documentation/table).
As @jtommy said, can you reproduce your issue in a codepen so we can take a look at what is going on?

**Comment by rsoares88** [comment]
https://codepen.io/rsoares88/pen/NWNzZQa

**Comment by jtommy** [comment]
You are using the old syntax, please check the docs

**Comment by rsoares88** [comment]
i updated the codepen with the buefy example, still not working.

**Comment by jtommy** [comment]
@rsoares88 the code is right but you have to import Vue before Buefy on codepen
