### ISSUE TITLE
`canCancel` props shown in HTML dom

### ISSUE THREAD

**Issue by Heartz66** [buefy/buefy#2884]
it shows the `canCancel` props of the modal in the HTML dom.

![94e6b9275da1d09b5ba11945e227d1a2-png](https://user-images.githubusercontent.com/8833887/93199647-e766b880-f74e-11ea-9c4b-be462a589471.jpg)

**Comment by jtommy** [comment]
@Heartz66 can you provide a codepen ?

**Comment by Heartz66** [comment]
When you open the modal see the `form` tag on the modal itself, it will show the `can-cancel` prop. See: https://codepen.io/Heartz66/pen/bGpQagV
