### ISSUE TITLE
Sticky searchable table column

### ISSUE THREAD

**Issue by chrisrhymes** [buefy/buefy#2885]
### Description

It is currently possible to set the table headers to be sticky when you scroll vertically up and down using `<b-table stick-header>` and you can add a search box to the column with `<b-table-column searchable>` but is is possible to make the search box also stick to the header so it is always shown when scrolling vertically? 

### Why Buefy need this feature

If you have a long table you can update your search term to further filter/update results without having to scroll back to the top of the table.

**Comment by jtommy** [comment]
No at the moment but we can improve it

**Comment by diamond95** [comment]
+1

**Comment by movingcity** [comment]
This feature would be really useful.
In addition, searchable input cell displayed above sticky row / headers cell when scrolling. Maybe it's caused by z-index. And the background color of searchable cell should not be transparent?

**Comment by diamond95** [comment]
> This feature would be really useful.
> In addition, searchable input cell displayed above sticky row / headers cell when scrolling. Maybe it's caused by z-index. And the background color of searchable cell should not be transparent?

check https://github.com/x-extends/vxe-table/blob/HEAD/README.en.md if you need complex tables

**Comment by movingcity** [comment]
Thanks @diamond95 
I have tried vxe-table. I found that it could not meet my requirements which are not very complicated. For example, filter directly from the header; click the header text to sort.
I have also tried about a dozen Vue native table, but none of them can fully meet the requirements, until I found bulma and buefy.

**Comment by diamond95** [comment]
> Thanks @diamond95
> I have tried vxe-table. I found that it could not meet my requirements which are not very complicated. For example, filter directly from the header; click the header text to sort.
> I have also tried about a dozen Vue native table, but none of them can fully meet the requirements, until I found bulma and buefy.

Well, I did it with vxe table, everything you are asking for.

There is alot of examples there, https://x-extends.github.io/vxe-table/#/table/base/basic

**Comment by movingcity** [comment]
@diamond95 
Yes, there are so many examples and vxe-table is complex enough, but complexity does not mean perfect. I have seen all the examples of vxe-table, but I have not found one that meets my requirements. I even implemented one component of header filtering functions on vxe-table very painfully. The first requirement is '**filter directly from the header**'. Do you really find an example of it? Maybe I was not careful enough to find it. Could you please point me to that example?

**Comment by diamond95** [comment]
@movingcity  filter like this? https://x-extends.github.io/vxe-table/#/table/advanced/customSort

**Comment by movingcity** [comment]
@diamond95 
No, my friend. Like this https://buefy.org/documentation/table/#searchable
Please stop wasting time and do something meaningful.

**Comment by diamond95** [comment]
> @diamond95
> No, my friend. Like this https://buefy.org/documentation/table/#searchable
> Please stop wasting time and do something meaningful.

That's called search box on each header. facepalm

**Comment by diamond95** [comment]
Well, using one searchbox for table ( to filter data on multiple columns ) is kinda better these days. But it is possible to create multiple searchboxes, on each column. 
I've created example for you: https://codesandbox.io/s/vxe-table-wentiyanshi-forked-e4bt8?fontsize=14&hidenavigation=1&theme=dark&file=/src/main.js

good luck :)

**Comment by diamond95** [comment]
> @diamond95
> No, my friend. Like this https://buefy.org/documentation/table/#searchable
> Please stop wasting time and do something meaningful.

 Well, using one searchbox for table ( to filter data on multiple columns ) is kinda better these days. But it is possible to create multiple searchboxes, on each column. 
I've created example for you: https://codesandbox.io/s/vxe-table-wentiyanshi-forked-e4bt8?fontsize=14&hidenavigation=1&theme=dark&file=/src/main.js

good luck :)
