### ISSUE TITLE
Table with sticky-header and sortable clips sort icon

### ISSUE THREAD

**Issue by abroekhof** [buefy/buefy#2886]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.11
**OS/Browser**: OSX, Chrome

### Description

For tables with sticky-headers and sortable rows, part of the sort icon gets clipped by the next column. This is because sticky-headers applies a white background to the `th`, which goes on top of the icon. 

### Steps to reproduce

https://codepen.io/abroekhof/pen/BaKPRwM

### Actual behavior
![image](https://user-images.githubusercontent.com/3480381/93248150-525ec200-f744-11ea-8a5b-7c8329662664.png)

### Possible solutions

1. Apply the background color to the row instead of each cell individually
2. Increase the z value for the icon
3. Increase right padding in case of sortable and sticky-header

**Comment by bathyscaaf** [comment]
Having the same issue, had to override the CSS

**Comment by jtommy** [comment]
@bathyscaaf why don't you make a PR?
