### ISSUE TITLE
Improvements for selected slot and custom label for b-taginput

### ISSUE THREAD

**Issue by lukenofurther** [buefy/buefy#2887]
### Description

First off, I've been loving using Buefy, it's a great library. The new groups feature for taginput and autocomplete is brilliant, and I've just implemented a nice feature with it very easily and smoothly for the most part - great work whoever did that.

There were a couple of slightly cumbersome pieces of code I had to write for my use case that could be smoothed over with a couple of extra improvements

My use case is this - I have custom labels for the selected tags, labels that are more complex than a single path value. It's currently possible for me to achieve this using the #selected slot, which is [well-documented](https://buefy.org/documentation/taginput#custom-selected), so I won't repeat here. However, this solution requires me to template the entire list of tags, when all I want to do is change the text inside the tags.

The addition of an extra slot for a custom selected tag label would make this much cleaner and easier:

```vue
<b-taginput
    v-model="tags"
    :data="filteredTags"
    autocomplete
    @typing="getFilteredTags"
>

    <template slot="selected-label" slot-scope="{ tag }">
        <span>{{ tag.name }}</span><b-icon :icon="tag.group.icon" size="is-small" />
    </template>
</b-taginput>
```

Additionally, the info I want to include in the selected tag is actually from the group that the autocomplete option is nested in. This data isn't available in the slot-scope, so I had to add the group data onto a key of every option manually, as you can see in the above template `:icon=@tag.group.icon@`.

I imagine adding group data into the selected tags will be quite a common scenario once more people start using the new grouping feature. I don't know how difficult it would be to expose the group data to the slot-scope of the existing slot and/or the proposed new slot, but doing so would make sense for people wishing to include group data in their tags, so they could do something like:

```vue
<b-taginput
    v-model="selected"
    :data="filteredOptions"
    autocomplete
    @typing="updateFilteredOptions"
>
    <template slot="selected-label" slot-scope="{ tag, group }">
        <span>{{ tag.name }}</span><b-icon :icon="group.icon" size="is-small" />
    </template>
</b-taginput>
```

### Why Buefy need this feature

Adding a new slot for customising only the labels of selected tags will greatly simplify what users need to do to create a label that's more complex than a single path value. This scenario could be a common need for users using the new groups functionality and want to easily add group information to the label.

Adding the group data to the slot-scope of the existing slot or the new proposed slot will make it easier for users using the group functionality to incorporate group information into the selected tags.

**Comment by jtommy** [comment]
@lukenofurther thanks.
About new slots I might add it but the current selected slot covers it; probably it's verbose but give you freedom to choose what render as selected item.
About group you should save the information in your selected item, don't you ?

**Comment by lukenofurther** [comment]
@jtommy Re groups, yes I do save the info in my selected item. It feels like a workaround, that's all.
