### ISSUE TITLE
Tooltip with append-to-body stutters

### ISSUE THREAD

**Issue by plakak** [buefy/buefy#2889]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: Nuxt [2.14.0]
**OS/Browser**: MacOs/ Chrome

### Description
Tooltip appended to body constantly fires `mouseenter`/`mouseleave` while mouse is moved over the trigger area crating constant show/hide for the tooltip during each move.

### Steps to reproduce

1. Create tooltip with append-to-body prop.
2. Move mouse over its trigger element.

### Expected behavior

Tooltip shows once when mouse is over the trigger element. Hides when it's off the trigger element.

### Actual behavior

Codesandbox: https://codesandbox.io/s/buefy-playground-forked-u6bfl - move mouse slowly over the "test" button.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2940

**Comment by Dragoncall** [comment]
This is still happening when the container is a modal. The `.modal-content` is relatively positioned, resetting the z-index within the container. Due to this, the `z-index` of the trigger stays under the one of the tooltip.

**Comment by Dragoncall** [comment]
@jtommy Should this issue above be put in another one to make it more visible?

**Comment by icabbi-joegarlick** [comment]
We are currently experiencing the same issue in 0.9.7. Is there any updates on this?

https://i.gyazo.com/ca522f99f1888e627fc6674ec7fe124b.mp4

Thanks,
Joe

**Comment by icabbi-joegarlick** [comment]
Hey,

I have been working on this issue and found what was causing it. It looks to be the tooltipEl inside the Tooltip.vue. 

tooltipEl creates a box which covers the object being "tooltipped" this box is then used as a boundary for the actual tooltip. However when append-to-body is used and the trigger is hovered this box is revealed which sends the mouseleave event to the trigger as it is being blocked by this bounding box.

I managed to get it working for me locally by semi removing this box. I will paste the solution I used below however I am not happy with how clean the code, so I wont make a pull request, however it will work for me. I am sure someone can come up with a better solution now I have found the issue

`updateAppendToBody() {
            const tooltip = this.$refs.tooltip;
            const trigger = this.$refs.trigger;
            if (tooltip && trigger) {
                // update wrapper tooltip
                const tooltipEl = this.$data._bodyEl.children[0];
                tooltipEl.classList.forEach(item =>
                    tooltipEl.classList.remove(item)
                );
                if (
                    this.$vnode &&
                    this.$vnode.data &&
                    this.$vnode.data.staticClass
                ) {
                    tooltipEl.classList.add(this.$vnode.data.staticClass);
                }
                this.rootClasses.forEach(item => {
                    if (typeof item === "object") {
                        for (let key in item) {
                            if (item[key]) {
                                tooltipEl.classList.add(key);
                            }
                        }
                    } else {
                        tooltipEl.classList.add(item);
                    }
                });

                const rect = trigger.getBoundingClientRect();

                let top = rect.top + window.scrollY;
                let left = rect.left + window.scrollX;

                const quaterHeight = trigger.clientHeight / 2 / 2;

                switch (this.position) {
                    case "is-top":
                        tooltipEl.style.width = `${trigger.clientWidth}px`;
                        tooltipEl.style.height = `0px`;
                        top -= trigger.clientHeight - quaterHeight;
                        break;
                    case "is-bottom":
                        tooltipEl.style.width = `${trigger.clientWidth}px`;
                        tooltipEl.style.height = `0px`;
                        top += quaterHeight;
                        break;
                    case "is-left":
                        tooltipEl.style.width = `0px`;
                        tooltipEl.style.height = `${trigger.clientHeight}px`;
                        break;
                    case "is-right":
                        tooltipEl.style.width = `0px`;
                        tooltipEl.style.height = `${trigger.clientHeight}px`;
                        left += trigger.clientWidth;
                        break;
                }

                const wrapper = this.$data._bodyEl;
                wrapper.style.position = "absolute";
                wrapper.style.top = `${top}px`;
                wrapper.style.left = `${left}px`;
                wrapper.style.width = `0px`;
                wrapper.style.zIndex =
                    this.isActive || this.always ? "99" : "-1";
                this.triggerStyle = {
                    zIndex: this.isActive || this.always ? "100" : undefined
                };
            }
        },`
        
Let me know if anyone has any questions.

Thanks,
Joe

**Comment by gordondmacdougall** [comment]
Hi all,

So I had this issue along with an issue of orphaned components that I had to solve together, and Joe's above solution wasn't working for me, so below is how I managed to get it solved.

First, to deal with the issue of the stutter, I removed the setting of zIndex for the wrapper

`wrapper.style.zIndex = this.isActive || this.always ? '99' : '-1'`

I changed the createAbsoluteElement to add the tag name 'tooltip', though this would probably have to be made into something a bit more unique for edge cases where we want some tooltips to stay when creating new ones.

`createAbsoluteElement(el) {
            const root = document.createElement('tooltip')
            root.style.position = 'absolute'
            root.style.left = '0px'
            root.style.top = '0px'
            root.style.width = '100%'
            const wrapper = document.createElement('tooltip')
            root.appendChild(wrapper)
            wrapper.appendChild(el)
            document.body.appendChild(root)
            return root
        },`

I added a simple cleanup function to remove the orphaned elements, instead of just having them set to left/top = 0, as depending on the size of the dropdown list that you are making tooltips for, it can cause some serious slowness when components are destroyed as part of destroying main components on single page vues.

`cleanupTooltips() {
            _.forEach(document.getElementsByTagName('tooltip'), (tooltip) => {
                if (tooltip) {
                    this.removeElement(tooltip);
                }
            });
        },`

Finally, to pull all these together:

- Removed the code in Mounted, as we will be creating and removing the tooltip elements as required
- edited before destroy to use the cleanupTooltips function instead of `removeElement(this.$data._bodyEl)`
- updated open and close functions as below. This will ensure that you don't have overhanging tooltips and removes components that are no longer required.

`open() {
            this.cleanupTooltips();
            if (this.appendToBody) {
                this.$data._bodyEl = createAbsoluteElement(this.$refs.content);
                this.updateAppendToBody();
            }
            if (this.delay) {
                this.timer = setTimeout(() => {
                    this.isActive = true
                    this.timer = null
                }, this.delay)
            } else {
                this.isActive = true
            }
        },
        close() {
            this.cleanupTooltips();
            this._bodyEl = undefined;
            if (typeof this.autoClose === 'boolean') {
                this.isActive = !this.autoClose
                if (this.autoClose && this.timer) clearTimeout(this.timer)
            }
        },`

Just a note that this issue was specifically happening for me using tooltip along with dropdown, but since making my changes above, I've had no issues and the lack of extra components has helped speed things up.

Let me know if there are any questions.

Thanks,
Gordon

**Comment by ricardopolo** [comment]
Is it going to be fixed in the project? Or this workaround means I need to fork and modify my own version?

**Comment by priyam307** [comment]
@jtommy Can we incorporate the above change ?, tooltip flashy behaviour is evident when used with append-to-body flag.
