### ISSUE TITLE
Datepicker year select to honor max-date year

### ISSUE THREAD

**Issue by mikebschroeder** [buefy/buefy#2890]
### Description

From reviewing [Issue 873](https://github.com/buefy/buefy/issues/873) it appears that the Datepicker year select has an arbitrary future max date of 3 years.  Would it be possible for the Datepicker year select to use the year from max-date if it is specified? It appears that it already honors the min-date year, but not the max-date year.

```
  <b-datepicker
    v-model="selectedDate"
    @input="updateTargetDate"
    :date-formatter="dateFormatter"
    :date-parser="dateParser"
    :min-date="minDate"
    :max-date="maxDate"
    placeholder="YYYY-MM-DD"
    icon="calendar-today"
    editable
  ></b-datepicker>


  data() {
    return {
      minDate: new Date(2016, 0, 1),
      maxDate: new Date(2030, 1, 1)
    }
  },
```

![Screen Shot 2020-09-16 at 9 29 02 AM](https://user-images.githubusercontent.com/28902598/93365817-1f2d3900-f7ff-11ea-975d-14bea29a15da.png)

### Why Buefy need this feature

1. It would make the behavior of min-date and max-date consistent.
2. It would provide a way to override the current arbitrary 3 year future year.

**Comment by jtommy** [comment]
There is already a prop, it called years-range (take a look at docs)

**Comment by mikebschroeder** [comment]
Yes, I saw the prop, and I can do a workaround with that - the request was since minDate has a certain behaviour but maxDate does not have a corresponding behaviour.  I'll work with years-range.
