### ISSUE TITLE
DatePicker: changing Month or Year doesn't update the v-model date

### ISSUE THREAD

**Issue by kerbo** [buefy/buefy#2896]
When selecting the month or year ONLY in the DatePicker, the v-model date doesn't update. If you select a day, the v-model date WILL update.

This can be easily seen in the example docs.

**Comment by jtommy** [comment]
Datepicker updates v-model only when you select a date.
You can listen them `change-month` and `change-month` events

**Comment by kerbo** [comment]
I think this incorrect behavior. Changing the month/year on the picker changes the date and the v-model date should reflect the change. The v-model date should ALWAYS be in sync with the date shown on the picker.

With regard to detecting when a date is changed...tracking three events is a mess, The Input event should fire when the date changes, not when the day part of a date changes.

**Comment by jtommy** [comment]
It changes the focused date but not the selected date

**Comment by bikepunk** [comment]
I agree with @kerbo 
I think there is a serious UX question here

FYI the topic is discussed in an other project using buefy : 
https://framagit.org/framasoft/mobilizon/-/issues/649
