### ISSUE TITLE
datepicker "append-to-body" not working as expected or misleading docu

### ISSUE THREAD

**Issue by donmb1** [buefy/buefy#2898]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [X.X.X]
I am using **Nuxt** version: [2.14.5]
**OS/Browser**: Chrome 85.0.4183.102

### Steps to reproduce

```
<b-datepicker
     icon-pack="fas"
     v-model="date"
     :events="mappedEvents"
     :indicators="indicators"
     size="is-large"
     icon-prev="caret-left"
     icon-next="caret-right"
     :append-to-body="true"
     inline
/>
```

### Expected behavior

I expect the datepicker to append to body. Maybe I misunderstood the [docu](https://buefy.org/documentation/datepicker/) but "appending to body" for me would mean that it is "tied" to the body without shadows/modal etc.

### Actual behavior

The datepicker does not render at all. There are no console errors but some log is appearing

```
[HMR]  - ./node_modules/babel-loader/lib??ref--2-0!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/calendar/index.vue?vue&type=script&lang=js&
process-update.js?e135:127 [HMR]  - ./pages/calendar/index.vue?vue&type=script&lang=js&
process-update.js?e135:127 [HMR]  - ./pages/calendar/index.vue
process-update.js?e135:127 [HMR]  - ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/calendar/index.vue?vue&type=template&id=7b48bafa&scoped=true&
process-update.js?e135:127 
```

**When I remove `inline` its rendering fine but I don't see any difference between `:append-to-body="true"` and `:append-to-body="false"`**

**Comment by jtommy** [comment]
No, that prop append the content on body it's no a change on UI.
It is helpful using it in a modal or other containers

**Comment by donmb1** [comment]
ok but its not working with `inline`

**Comment by jtommy** [comment]
Why do you need it when inline ?

**Comment by donmb1** [comment]
Guess I still understand this prop then :D can you make a better example or use-case on when to use `append-to-body`
thanks

**Comment by jtommy** [comment]
I told you before, you should use it when datepicker is into a modal. 
It fixes a bulma issue using dropdown into a modal (datepicker uses dropdown internally to show as popup)

**Comment by donmb1** [comment]
okay
