### ISSUE TITLE
B-field: "Inside" label position in textarea elements

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2900]
### Overview of the problem

**Buefy** version: 0.9.3
**OS/Browser**: Safari 14

### Description

![image](https://user-images.githubusercontent.com/8303937/93598306-690b5000-f9b4-11ea-9cbf-68c51584e4d1.png)

The distance between label and content differs if the element is a textarea.

**Comment by jtommy** [comment]
I noticed it, probably you are right

**Comment by wesdevpro** [comment]
Closing this because it is no longer an issue in the latest versions of Buefy. 
From what I understand the layout of the label was changed to be positioned absolutely which no longer affects the text inside the text area.
