### ISSUE TITLE
Placeholder in b-image only shows up for the first time when adding more images dynamically

### ISSUE THREAD

**Issue by major-mayer** [buefy/buefy#2901]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.12
**OS/Browser**: Windows - Firefox

### Description
I have problems with using the placeholder slot of the b-image component.
I use it inside the card (b-) image of a carousel list, to which i add new items dynamically.
The items have indivudial images in their object and those images take a while to be generated.
These items get stored in vuex and are binded with the `...mapGetters` helper function to the vue component.

It looks something like this : 
```js
items = [ 
 {key: 124, image : "imageblob which takes a time to be there}, {key :125, image: "..."} ... 
]
```

The problem that i have is, that the placeholder works for the first image that is added to the carousel list, but on all other items that are added later it doesn't work anymore.
It's not that the image is not there, in fact it will appear after a when it loaded, just the skeleton placeholder is missing, before it gets loaded.

Here i have some code, maybe it helps understanding my problem:
```vue
<b-carousel-list :data="items" // from vuex >
    <template v-slot:item>
        <!-- Normal Previews -->
        <div class="card">
            <div class="card-image">
            <b-image class="image" :src="item.image" ratio="is-5by4">
                <b-skeleton slot="placeholder" :rounded="false" height="100%"></b-skeleton>
            </b-image>
            </div>
            <div class="card-content">
            ...
            </div>
            </div>
        </div>
    </template>
</b-carousel-list
```

### Steps to reproduce

1. Create a carousel list
2. Bind the items to an array in vuex store (don't know if that's required to reproduce, maybe local works too)
3. Bind the b-image of each card in the list to key in the array
4. Dynamically add more items to the list, postpone the loading of the images with something like setTimeout for testing

### Expected behavior
Placeholder will be shown for each image until it finished loading.

### Actual behavior
This is only the case for the first image in the list. Afte that placeholders are missing.

**Comment by service-paradis** [comment]
Hello,

Can you share more code? 

Did you style your skeleton as below:
```
.b-skeleton {
    height: 100%;
    position: absolute;
    top: 0;
}
```

Are you able to reproduce the issue using Codepen?

Looks to be working fine in this example:
https://codepen.io/service-paradis/pen/WNwLomy?editors=1111

**Comment by major-mayer** [comment]
Hmm actually i wasn't able to reproduce my problem in Codepen. It looks something like this:
https://codepen.io/major-mayer/pen/GRZzmWJ

The difference is that here when i add an item it is stored locally in the component, while in my application i store all the items in the vuex store.

Here is how it looks in my code : 
```
// Hook into the addMesh Vuex mutation and generate a preview when a new mesh is added
    this.$store.subscribe(async (mutation) => {
      if (mutation.type === "addMesh") {
          setTimeout(async () => {
            const preview = await createPreview.call(this, mutation.payload.url);
            this.$store.dispatch("setPreviewImage", {
              meshKey: mutation.payload.key,
              imageData: preview,
            });
          }, 5000);
        }
      }
    });
``` 
I subscribe to the addMesh Mutation to generate a preview image for my meshes afterwards.
The addMesh mutation does not commit a preview image itself, so the object looks like this:
![grafik](https://user-images.githubusercontent.com/17907799/94129763-0c98ac80-fe5c-11ea-9d80-30c2e26e7c6b.png)

When the setPreviewImage action is dispatched (for testing with 5000 ms delay) the object looks like this:
![grafik](https://user-images.githubusercontent.com/17907799/94129898-3e117800-fe5c-11ea-8b01-3d90a100f4fc.png)
As you can see, the preview image is now available as a base64 encoded png image. It eventually displays but the skelton will only show up for the first mesh that i add.

I know this is more likely a bug on my side, but if you have any ideas i would be very thankful
