### ISSUE TITLE
b-image throws "ReferenceError: HTMLImageElement is not defined" when server side rendered

### ISSUE THREAD

**Issue by quirkles** [buefy/buefy#2905]
I'm using buefy in a nuxt app and when i try to use the b-image tag in a server side rendered page, it fails with the error in the bug title

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]

mac, any browser

### Description

The issue is this line:

`nativeLazySupported: 'loading' in HTMLImageElement.prototype,` in the `data` method of the image component: src/components/image/Image.vue

When server side rendered, in a node environment, the DOM api item `HTMLImageElement`, doesn't exist and an error is thrown, i confirmed by replacing it with `nativeLazySupported: 'loading' in (HTMLImageElement || {}).prototype,` which renders (but obviously not a sustainable solution, also i get an error about the ssr DOM not matching the client side

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2866

**Comment by xperator** [comment]
I just encountered this exact same problem. I cannot render b-image in SSR.

So is this problem fixed, is in the works, or do I have to use a workaround like [this](https://github.com/buefy/nuxt-buefy/issues/72#issuecomment-687121994) one?

**Comment by quirkles** [comment]
@xperator FWIW that workaround isn't ideal, you'll see warnings about ssr and client not matching.

**Comment by xperator** [comment]
@quirkles I see... so do we wait for the next release?

**Comment by jtommy** [comment]
Yew
