### ISSUE TITLE
By default today date is selected - datepicker

### ISSUE THREAD

**Issue by cristinutza2k** [buefy/buefy#2907]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.12
**OS/Browser**: any

### Description

By default the today date is selected (.is-selected) in the datepicker. How can I change this? I don't need any date selected by default.
![selected-date](https://user-images.githubusercontent.com/5804947/93753258-8b95a700-fc08-11ea-8972-bbbda1022fc4.png)

**Comment by service-paradis** [comment]
Can you share the code you used for your datepicker?

**Comment by cristinutza2k** [comment]
<div id="app3" class="container">
				<b-datepicker v-model="date" 
					inline 
					range
					:first-day-of-week="1"
					:month-names="month_names"
					:day-names="day_names"
					:show-week-number="showWeekNumber">
				</b-datepicker>
			</div>

And:

// Inline
const example2 = {
    data() {
	const today = new Date()
        return {
            date: new Date(),
	    showWeekNumber: true,
	    month_names:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"],
	    day_names:["Su","Mo","Tu","We","Th","Fr","Sa"]
        }
    }
}

const app3 = new Vue(example2)
app3.$mount('#app3')

**Comment by service-paradis** [comment]
Today's date is selected because you use today's date as a default value.

You're using `v-model="date"` and you're defining `date` with the current date `date: new Date()`.

If you do not want to have a default date selected, you'll need to define date as undefined or null.

**Comment by cristinutza2k** [comment]
thank you!!
