### ISSUE TITLE
[Bug] rounded not work in Datetimepicker

### ISSUE THREAD

**Issue by biigpongsatorn** [buefy/buefy#2909]
Example: https://codepen.io/pen/define/
![image](https://user-images.githubusercontent.com/10693658/93769638-493e8b00-fc45-11ea-94ab-a7462e34b81c.png)

### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

**Comment by jtommy** [comment]
Ok, as you workaround you might set rounded:true on datepicker prop
