### ISSUE TITLE
Inside Label Overlapping Input Text

### ISSUE THREAD

**Issue by JoaoFSCruz** [buefy/buefy#2914]
### Overview of the problem

**Buefy** version: 0.9.3
**OS/Browser**: Firefox 80.0.1

### Description

When on mobile the label occupies two lines and overlaps the input text.

![image](https://user-images.githubusercontent.com/26048679/94020443-d2230700-fdaa-11ea-89ed-9e3ab56af074.png)

**Comment by service-paradis** [comment]
In your opinion, what would be the best solution for this?
Keeping the text on one line with an ellipsis for the overflowing text? Something like this:
![image](https://user-images.githubusercontent.com/12817388/94029551-ec4ced00-fd8a-11ea-91b4-489f1202c4b4.png)

This is what I used for the label in the above example:
```css
    white-space: nowrap;
    text-overflow: ellipsis;
    max-width: calc(100% - 2em);
    overflow: hidden;
```

**Comment by fabiofdsantos** [comment]
@jtommy @service-paradis 
Any additional thoughts on this one?

**Comment by service-paradis** [comment]
I'm not sure yet about the best solution for it. Conditional height depending on text length and resolution might be difficult and might be looking weird in some design. Cutting the text is not ideal since it can include important text. 
Do you have an opinion on it @fabiofdsantos?
I'm curious about @jtommy  position on this too?

**Comment by fabiofdsantos** [comment]
I see some alternatives:
 - Conditional height every time (make it optional?).
 - Apply conditional height only when the element is selected.
 - Display a tooltip if the text length is greater than the element.

**Comment by jtommy** [comment]
I prefer @service-paradis solution at the moment. 
@fabiofdsantos your ideas are cool but all need extra params (height, maxlenght characters, ..)

**Comment by fabiofdsantos** [comment]
We can go with @service-paradis approach. It's better than overlapping it 👍🏻
