### ISSUE TITLE
Cannot use Table after importing as individual component

### ISSUE THREAD

**Issue by elfjes** [buefy/buefy#2918]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.11
**OS/Browser**: Ubuntu/Firefox

### Description

After importing `Table` as an individual component, an error is raised  when trying to create a table: `TypeError: _chunk_bd4264c6_js__WEBPACK_IMPORTED_MODULE_2__.V is undefined` and the Table is not rendered.

### Steps to reproduce
1. create a new project using vue-cli 3
2. main.js:
```js
import Vue from 'vue';
import {Table} from 'buefy';
import App from './App.vue';
import 'buefy/dist/buefy.css';

Vue.use(Table);

new Vue({
  render: (h) => h(App),
}).$mount('#app');
```
App.vue
```vue
<template>
  <div id="app">
    <b-table :data="data" :columns="columns"></b-table>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      data: [
        { 'id': 1 },
      ],
      columns: [
        {
          field: 'id',
          label: 'ID',
          numeric: true
        },

      ]
    }
  }
}
</script>

```

**Comment by jtommy** [comment]
Did you try using table-column components instead of columns prop?

**Comment by elfjes** [comment]
right, this works:
```vue
<template>
  <div id="app">
    <b-table :data="data">
      <b-table-column :key="1" label="id" v-slot="props">
        {{ props.row.id }}
      </b-table-column>
    </b-table>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      data: [
        { 'id': 1 },
      ],
    }
  }
}
</script>
```

It is supposed to behave like that?

**Comment by elfjes** [comment]
So when I hack the `esm/table.js` to directly `import VueInstance from 'vue'` it works. The VueInstance that it requires there looks only to be set when importing Buefy as a whole. Could it be as simple as maybe checking whether the VueInstance is set, and otherwise, use the global Vue. This could then maybe be done through a `getVueInstance()` function?

**Comment by jtommy** [comment]
Yes you are right, I have to save Vue instance in the table plugin or find an other way to create component at runtime

**Comment by elfjes** [comment]
I can confirm that calling `setVueInstance(Vue)` in the plugin works
