### ISSUE TITLE
html5 validation on fields in addition to custom error messages?

### ISSUE THREAD

**Issue by quirkles** [buefy/buefy#2920]
I searched for this issue but didnt find an answer. What im trying to do is show any html5 validation messages if they are present, and if not, show any my own validation messages, if present. However, as i understand it, the api only supports either/or.

If i do this, then the html5 errors don't show, only the contents of `errors.email` where errors is a computed object with each field being an array of the error strings
```
              <b-field label="Email" :message="errors.email">
                <b-input
                  v-model="credentials.email"
                  type="email"
                  @input="handleFieldChange('email', $event)"
                ></b-input>
              </b-field>
```

And If i do this, omitting the message prop, then the html5 errors do show, but of course mine do not:
```
              <b-field label="Email">
                <b-input
                  v-model="credentials.email"
                  type="email"
                  @input="handleFieldChange('email', $event)"
                ></b-input>
              </b-field>
```

I feel like i must me missing something obvious? If i want to display my own custom errors do i have to forgo the html5 validation messages?

**Comment by jtommy** [comment]
You have to set https://github.com/buefy/buefy/blob/17fcc4ed166eccaaf5b0ee2597280a06c785f014/src/utils/FormElementMixin.js#L19 on input
