### ISSUE TITLE
Loading state on submit button don't work

### ISSUE THREAD

**Issue by dalholm** [buefy/buefy#2921]
### Overview of the problem
When loading is set to true on a button with `native-type="submit"` the button only gets blank

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chrome

### Steps to reproduce

```html
<b-button
  tag="input"
  native-type="submit"
  value="Submit input"
  :loading="loading"
/>
```

### Expected behavior

The default spinner should appear

**Comment by Zephyrrus** [comment]
This issue is caused by `tag="input"` which replaces the **button** tag with an **input** tag. 
The reason why this breaks is because of how the `:after` pseudo-element works. 
You can find a better explanation [here](https://stackoverflow.com/a/4660434)

**Comment by dalholm** [comment]
@Zephyrrus thanks for the explanation. @jtommy don't you think this should be noticed in the docs?
