### ISSUE TITLE
Slider calling input event/setter when updated programmatically

### ISSUE THREAD

**Issue by tontonsb** [buefy/buefy#2925]
**Buefy** version: 0.9.3
**Vuejs** version: 2.6.12
**OS/Browser**: Windows/Chrome

https://codesandbox.io/s/nervous-glade-k12y9?file=/src/App.vue

Interact with slider and observe single setter called and logged. Interact with the range input and observe setter called twice — once for each input.

**Comment by emeric254** [comment]
As of today this is still a thing, seems that updating the value of a slider when attached to a getter, it triggers a setter call
