### ISSUE TITLE
Custom table row 

### ISSUE THREAD

**Issue by valq7711** [buefy/buefy#2927]
Hi !
Can anyone provide an example of a table with a full custom row (including colspan), just like below (thanks in advance!):

![image](https://user-images.githubusercontent.com/11394363/94367288-66aca280-00e6-11eb-9ff7-cde5e73afcd7.png)

I just wasted a day trying to translate this:
![image](https://user-images.githubusercontent.com/11394363/94367574-3f56d500-00e8-11eb-84a8-a1d478901d7f.png)
 into code,  because `<template  v-slot = 'props'>` doesnt work anymore (props is `{}`) since [v0.9.0](https://github.com/buefy/buefy/releases/tag/v0.9.0)

**Comment by jtommy** [comment]
Please ask to Discord channel for this kind of request

**Comment by wobsoriano** [comment]
@valq7711 where you able to make this work?
