### ISSUE TITLE
[DatePicker][DateTimePicker][show-week-number] Clicking on the week number should emit an event

### ISSUE THREAD

**Issue by lgarczyn** [buefy/buefy#2928]
### Description

There are multiple features that could be implemented with this, like

* selecting the entire week in a date-range situation
* selecting the entire week in a multiple-date selection
* 'zooming in' said week

### Why Buefy need this feature

From the user side, there's currently no way to implement this without DOM manipulation

**Comment by jtommy** [comment]
So you need an event clicking on week cell with the week number, right?

**Comment by lgarczyn** [comment]
@jtommy on the week number that is displayed when using the show-week-number prop

**Comment by lgarczyn** [comment]
Thanks for the help!

One problem, the week number only is not enough to generate a date, and getting the current-year requires following the change-year event as well. That said, it works well enough.

**Comment by jtommy** [comment]
Oh you are right, I'll add it
