### ISSUE TITLE
Buefy Sidebar X not show

### ISSUE THREAD

**Issue by teuk1** [buefy/buefy#2933]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.11]
**OS/Browser**: all

### Description

The button doesn't show.
As explained in the documentation and in the similar issue #1571, no cross appears. There is no exemple on the website for it.
In the source : only escape and outside are in the array for default. No mentions about the close trigger.

### Expected behavior

adding 
:can-cancel="canCancel" on the sidebar component
and use 
canCancel: ["escape", "x", "outside"] in the props.

### Actual behavior

Nothing appears.
The source code seems not permit that.

**Comment by jtommy** [comment]
X doesn't exist, I'll remove it from docs
