### ISSUE TITLE
Method of b-table to sort simply

### ISSUE THREAD

**Issue by mk-startialab** [buefy/buefy#2937]
### Description

A method of b-table which sorts with argument like "default-sort" property (e.g. ['first_name', 'desc']).
Not "initSort", because I do not want to sort initially.

### Why Buefy need this feature

"initSort" needs "default-sort" property. This means the table will be sorted initially with "default-sort" value.
The new sort method bring us programmatic sorting freely.

**Comment by jtommy** [comment]
You can use sort method but it needs a ref of table column

**Comment by mk-startialab** [comment]
@jtommy Thanks.
like this?
```
this.$refs.somecolumn.sort('desc');
```

**Comment by jtommy** [comment]
No you have to se a ref to table and to a table column. Then `this.$refs.table.sort(this.$refs.mycolumn)` or get the column by `this.$refs.table.newColumns`

**Comment by mk-startialab** [comment]
@jtommy All right. Thanks a lot!

**Comment by wesdevpro** [comment]
I am closing this PR Because a "workaround" was found.
