### ISSUE TITLE
border-right is missing.

### ISSUE THREAD

**Issue by 332lfgb6** [buefy/buefy#2938]
![Snipaste_2020-10-01_15-25-22](https://user-images.githubusercontent.com/51245335/94780463-0aee5c00-03fb-11eb-9b01-307e503e54f6.png)

**Comment by service-paradis** [comment]
Thanks for reporting it. 
Please use the template when opening a new issue in the future!

**Comment by 332lfgb6** [comment]
> Thanks for reporting it.
> Please use the template when opening a new issue in the future!

OK
