### ISSUE TITLE
loading overlay - unexpected behavior outside of notification

### ISSUE THREAD

**Issue by adamgreenhall** [buefy/buefy#2941]
### Overview of the problem

**Buefy** version: 0.9.3 (current)
**Vuejs** version: 2.6.12 (current)
**OS/Browser**: MacOS/Chrome and codepen.io

### Steps to reproduce

Put an `b-loading` element outside of `b-notification` and set `is-full-page=false`.
https://codepen.io/adamgreenhall/pen/bGpPved
(see also a similar example, but [with loading inside notification](https://codepen.io/adamgreenhall/pen/JjXQpqM))

### Expected behavior

I would expect the loading element to be contained within the parent element (even if it's not a notification).

### Actual behavior

Instead, the loading element covers the full page.

I poked around to see if I could hack the parent element in some way to get things to work, but couldn't figure it out. Any tips on that would be super helpful.

**Comment by jtommy** [comment]
You have to set position: relative on parent element (or simply "is-relative" class)
