### ISSUE TITLE
Warning when specify an array to wrapper-class argument of b-navbar

### ISSUE THREAD

**Issue by akicho8** [buefy/buefy#2943]
### Overview of the problem

Warning when specify an array to wrapper-class argument of b-navbar

**Buefy** version: [0.9.3]
**Vuejs** version: [0.9.0]
**OS/Browser**: Google Chrome

### Description

I want to change from

`type: String`

to

`type: [String, Array, Object]`

### Steps to reproduce

bulma has `is-fluid` to the option of the `container` class.
I wrote as follows.

`b-navbar(:wrapper-class="['container', {'is-fluid': true}]")`

will move.
However, will get a warning.

### Expected behavior

Warning does not appear

### Actual behavior

Warning out

> VM31113:37 [Vue warn]: Invalid prop: type check failed for prop "wrapperClass". Expected String with value "container,[object Object]", got Array

**Comment by jtommy** [comment]
You can't use array, only a string

**Comment by akicho8** [comment]
class of other parts is in the `[String, Array, Object]`.
But only b-navbar has become a `String`.
b-navbar is there is no need to be a String.
