### ISSUE TITLE
Tab items disappear when using v-model, v-for, and header slot

### ISSUE THREAD

**Issue by Acccent** [buefy/buefy#2944]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.11]
**OS/Browser**: any

### Description

When using `v-model` on a `<b-tab>` component, and creating the inner `<b-tab-item>` components with a `v-for` loop and custom headers, the tabs disappear when cycling through them.

### Steps to reproduce

1. Create `<b-tabs v-model="activeTab"></b-tabs>` component
2. Add loop inside to generate tab items, like `<b-tab-item v-for="tabName in tabArray" :key="tabName"></b-tab-item>`
3. Create custom headers using `<template #header> Custom header here </template>`

### Expected behavior

Tabs behave normally, clicking on one makes it active and shows its content without impacting the others.

### Actual behavior

When clicking on any tab, all tabs to the right of the new active tab disappear during the transition.
(This also happens if the tabs are vertical, with the tabs below the new active one disappearing.)

https://codepen.io/Acccent/pen/bGebwew?editors=1010

**Comment by Kaisirak** [comment]
The activeId on <b-tabs> doesn't seem to be set by default either when no v-model is set, causing the first click on a tab to not have any animation.
The behavior seems to happen on the documentation too (https://buefy.org/documentation/tabs/#vertical)

**Comment by LuisHCK** [comment]
Adding a v-if may help
`<b-tabs v-if="myArray.length" v-model="activeTab">`

**Comment by yuchaosydney** [comment]
@Acccent 

Please try use `<template slot="header"> Custom header here </template>` to define custom header
