### ISSUE TITLE
Drag events fire on b-table when draggable prop is false.

### ISSUE THREAD

**Issue by robertmarney** [buefy/buefy#2949]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.12
**OS/Browser**: Windows 10 Pro / Brave

### Description

When b-table draggable prop is false dragging events are still fired if user selects text content and starts to drag. This can lead to unintended edits

### Steps to reproduce

Create table with text content, set draggable prop to false, select row content with cursor and start to drag.

### Expected behavior

When draggable is false no drag events fire.

**Comment by robertmarney** [comment]
@jtommy - sorry to disturb, do you have a rough eta on when the next release will be? Thanks!

**Comment by jtommy** [comment]
I hope max next week
