### ISSUE TITLE
Split button 

### ISSUE THREAD

**Issue by dalholm** [buefy/buefy#2950]
### Description

Splitt button feature like bootstrap has where you can have a default button and an icon button with dropdown menu.
this could be fixed like the input where you have "icon clickable" 

### Why Buefy need this feature

To complete the button component

**Comment by service-paradis** [comment]
It can work right now by grouping a button and a dropdown inside a field element. Something like:
```
<b-field grouped>
      <b-button>test</b-button>
        <b-dropdown aria-role="list">
            <b-button type="is-primary" slot="trigger" slot-scope="{ active }">
                <b-icon :icon="active ? 'menu-up' : 'menu-down'"></b-icon>
            </b-button>

            <b-dropdown-item aria-role="listitem">Action</b-dropdown-item>
            <b-dropdown-item aria-role="listitem">Another action</b-dropdown-item>
            <b-dropdown-item aria-role="listitem">Something else</b-dropdown-item>
        </b-dropdown>
    </b-field>
```
Since, it is not officially supported by Buefy, you will need to reset border-radius yourself (https://codepen.io/service-paradis/pen/dyXybWM).

Maybe, Buefy could add dropdown as a supported component in grouped field.

**Comment by dalholm** [comment]
@service-paradis thanks for the example, works perfect. I have solved it my self. I thought maybe the buefy team could do an official version of this to make it complete. :)

**Comment by service-paradis** [comment]
Well, my example was wrong! It is already working with Buefy current code. Only need to wrap elements in `.control`:
```
<b-field>
  <p class="control">
    <b-button>test</b-button>
  </p>
  <p class="control">
    <b-dropdown aria-role="list">
      <b-button type="is-primary" slot="trigger" slot-scope="{ active }">
        <b-icon :icon="active ? 'menu-up' : 'menu-down'"></b-icon>
      </b-button>

      <b-dropdown-item aria-role="listitem">Action</b-dropdown-item>
      <b-dropdown-item aria-role="listitem">Another action</b-dropdown-item>
      <b-dropdown-item aria-role="listitem">Something else</b-dropdown-item>
    </b-dropdown>
  </p>
</b-field>
```
I updated my Codepen example: https://codepen.io/service-paradis/pen/dyXybWM
