### ISSUE TITLE
Bulma 0.9.1

### ISSUE THREAD

**Issue by scheinercc** [buefy/buefy#2956]
### Description
Please upgrade to Bulma 0.9.1 https://github.com/jgthms/bulma/releases/tag/0.9.1

### Why Buefy need this feature

1. `p-0` and `m-0` added via https://github.com/jgthms/bulma/issues/3020
see also: https://github.com/jgthms/bulma/blame/master/sass/helpers/spacing.sass
    <img width="839" alt="image" src="https://user-images.githubusercontent.com/817856/95410535-fa486380-096f-11eb-8bb9-0094307d60bb.png">
2. It is in their documentation tagged as "since 0.9.0": https://bulma.io/documentation/helpers/spacing-helpers/ which makes it a bit confusing when the class doesn't work ;)

**Comment by jtommy** [comment]
We already upgraded it but it will be available in the next release. Btw you can already use it upgrading it in your package.json
