### ISSUE TITLE
b-icon using icon name "close" does not find associated icon

### ISSUE THREAD

**Issue by vilherda** [buefy/buefy#2958]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.11]
**OS/Browser**: Firefox 81.0 (64 bits)

### Description

It seems that there is not an icon associated to name "close"

### Steps to reproduce

Try to reproduce the example:

> <https://buefy.org/documentation/table/#checkable>

It uses `<b-icon icon="close"></b-icon>`

and when I reproduce this example on a local project the icon does not appears and I can see next message on web console of the browser:

> Could not find one or more icon(s) > Object { prefix: "fas", iconName: "close" }

### Expected behavior

The icon must appears

### Actual behavior

The icon does not appears

**Comment by jtommy** [comment]
It works well

**Comment by service-paradis** [comment]
Did you include icons from Fontawesome in your project? It might be why it was not found.
https://buefy.org/documentation/start#icons

**Comment by vilherda** [comment]
Is it necessary if I had included this dependencies on `package.json`?

> "@fortawesome/fontawesome-svg-core": "^1.2.32",
> "@fortawesome/free-brands-svg-icons": "^5.15.1",
> "@fortawesome/free-solid-svg-icons": "^5.15.1",
> "@fortawesome/vue-fontawesome": "^2.0.0",

An I had included the "typical" configuration on `main.js`?

> import { library } from '@fortawesome/fontawesome-svg-core'
> import { fas } from '@fortawesome/free-solid-svg-icons'
> import { fab } from '@fortawesome/free-brands-svg-icons'
> import { FontAwesomeIcon, FontAwesomeLayers, FontAwesomeLayersText } from '@fortawesome/vue-fontawesome'
> ...
> library.add(fas, fab)

> Vue.component('font-awesome-icon', FontAwesomeIcon)
> Vue.component('font-awesome-layers', FontAwesomeLayers)
> Vue.component('font-awesome-layers-text', FontAwesomeLayersText)
> Vue.use(Buefy, {
>> defaultIconComponent: 'font-awesome-icon',
>> defaultIconPack: 'fas',})

**Comment by lohithn4** [comment]
Yes I am also getting this error, with nuxtJS
```
ERROR  Could not find one or more icon(s) {   
  prefix: 'fas',
  iconName: 'close'
} {}

```
I guess the icon is not in the list, it throws a warning when i try to include manually in the list
```
nuxt.config.js

  buefy: {
    css: true,
    defaultIconPack: 'fas',
    defaultIconComponent: 'FontAwesomeIcon',
    materialDesignIcons: false,
  },
  // Font Awesome Configuration (https://github.com/nuxt-community/fontawesome-module)
  fontawesome: {
    icons: {
      solid: [
        'faHome',
        '...',
        'faClose',
        '...',
      ],
    },
  },

```
```
Warning in the console.
"export 'faClose' (imported as 'freeFasFaClose') was not found in '@fortawesome/free-solid-svg-icons'
```
