### ISSUE TITLE
Row click event firing when row is selected by arrow up and down key

### ISSUE THREAD

**Issue by smohsin83** [buefy/buefy#2964]
I have used a b-table and shows up details of the row in a side bar when the row is single clicked. For accessibility, I would like the user to select the rows via up/down key and press enter key to open the details in the sidebar. Currently, when the user select a row via arrow keys, the table single click even is being fired which opens up the side bar as the user navigates through the rows. Can we prevent the click event not to fire when row is selected by arrow key and fire only when user press the enter key?

**Comment by jtommy** [comment]
Can you provide a sample on codepen or similar?
