### ISSUE TITLE
[Feature request] Add dismiss button to SnackBar

### ISSUE THREAD

**Issue by NickeManarin** [buefy/buefy#2968]
### Description

It would be nice to have a dismiss button added to the opposite corner of the `Snackbar` action button, with a support for the `onDismissed` callback.

Something like, a simple <button class="delete"></button>:

![image](https://user-images.githubusercontent.com/14798947/95617180-65ae3600-0a41-11eb-8c6a-2cfccb50b12e.png)

Also, I believe this should be optional.

### Why Buefy need this feature

This is an expected/common feature. It's more challenging to add this feature from outside the lib.

**Comment by jtommy** [comment]
You can use notification component (programmatically)

**Comment by NickeManarin** [comment]
I guess that I will bump into the same issue, but now with the "Open" button.

How can I add the [Open] button and listen to the @click and access `this.MyProperty`?

**Comment by jtommy** [comment]
You can't.. snackbar, toast follow the base material design so there aren't additional buttons
