### ISSUE TITLE
Snackbar and toasts show only the first time when used alongside turbolinks and vue-turbolinks

### ISSUE THREAD

**Issue by mrdahbi** [buefy/buefy#2969]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]
**OS/Browser**: chrome

### Description

I'm using Buefy alongside [turbolinks](https://github.com/turbolinks/turbolinks) and [vue-turbolinks](https://github.com/jeffreyguenther/vue-turbolinks#mixin-option-1-global) in a Ruby on Rails app and it's been working great.

I'm now facing an issue where Snackbars and Toasts aren't shown the second and subsequent times they are triggered and there are no console errors.
Disabling `vue-turbolinks` restores the expected behavior, so the issue is most certainly in how turbolinks loads these components.

I have tried setting a container through the `container` option of `defaultContainerElement`constructor option but doesn't fix the issue. If the container element is inside the main element where vue is mounted, toasts never show.
I have also tried to use `ToastProgrammatic` without success.

Many thanks.

### Steps to reproduce

```html
<body>
    <div id="noticez"></div>
    <div class="app-container" data-behavior="vue">
        <my-component></my-component>
    </div>
</body>
```

```js
import Vue from 'vue/dist/vue.esm'
import TurbolinksAdapter from 'vue-turbolinks'
import Buefy from 'buefy'
import App from './app.vue'

Vue.use(TurbolinksAdapter)
Vue.use(Buefy, {
  defaultContainerElement: '#noticez'
})

document.addEventListener('turbolinks:load', () => {
  const app = new Vue({
    el: '[data-behavior="vue"]',
    data: () => {
      return {
        message: 'Can you say hello?',
      }
    },
    components: { App },
    created() {
      this.$buefy.snackbar.open({
        message: '1',
        // container: '#noticez',
      })
      this.$buefy.snackbar.open({
        message: '2',
        // container: '#noticez',
      })
    },
  })
})
```

### Expected behavior

The toasts and snackbars all appear one by one.

### Actual behavior

Only the first toast/snackbar appears; the remaining don't.

**Comment by jtommy** [comment]
Mmm if you close the first the second should be visible, no ?

**Comment by mrdahbi** [comment]
> Mmm if you close the first the second should be visible, no ?

no, also tried triggering toasts after a timeout or after a button click but nothing works.

**Comment by mrdahbi** [comment]
What seems bizarre is even with turbolinks activated, disabling vue-turbolinks [mixin](https://github.com/jeffreyguenther/vue-turbolinks/blob/master/index.js) makes the toasts and snackbars appear as expected.

I suspect that Buefy loses the reference to the body or container (if specified) DOM element when `vue-turbolinks` reloads the vue instance...

**Comment by mrdahbi** [comment]
After many trials and errors, I found a workaround by using vue-turbolinks as a mixin and not as a global plugin.

### [Mixin Option 2: Single Component](https://github.com/jeffreyguenther/vue-turbolinks#mixin-option-2-single-component)

``` javascript
import { turbolinksAdapterMixin } from 'vue-turbolinks';

document.addEventListener('turbolinks:load', () => {
  var vueapp = new Vue({
    el: "#hello",
    template: '<App/>',
    mixins: [turbolinksAdapterMixin],
    components: { App }
  });
});
```
