### ISSUE TITLE
Html tag shouldn't lose "is-clipped" class when a dialog is closed in a modal.

### ISSUE THREAD

**Issue by AxelConceicao** [buefy/buefy#2971]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chrome

### Description

When a b-dialog is closed in a b-modal, we can scroll the page while b-modal is still open.

### Steps to reproduce

https://codesandbox.io/s/bug-report-buefy-modals-issue-2ulh4

### Expected behavior

Html tag shouldn't lose "is-clipped" class when a dialog is closed in a modal.

### Actual behavior

https://codesandbox.io/s/bug-report-buefy-modals-issue-2ulh4

**Comment by service-paradis** [comment]
Also related to https://github.com/buefy/buefy/issues/893
