### ISSUE TITLE
B-Table searchable not working 

### ISSUE THREAD

**Issue by IbrahimIcgili** [buefy/buefy#2982]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: @vue/cli 4.5.4
**OS/Browser**: Windows 10 / Chrome latest version

### Description

I'm pulling my json data from an api and i show it in my table columns. When i add "searchable" attribute in my b-table-column tag it is not working.

![image](https://user-images.githubusercontent.com/15001720/96269076-8858c580-0fd2-11eb-968a-b69001b473c7.png)
![image](https://user-images.githubusercontent.com/15001720/96269107-9a3a6880-0fd2-11eb-9c17-64ddec9e587d.png)
![image](https://user-images.githubusercontent.com/15001720/96269134-a45c6700-0fd2-11eb-90f3-1cd57fc73024.png)

**Comment by jtommy** [comment]
Can you reproduce on codepen or similar?

**Comment by IbrahimIcgili** [comment]
I hope that is enough
https://codepen.io/ibrahimicgili/pen/bGewNXK

**Comment by jtommy** [comment]
It doesn't work, there are some syntax errors..
