### ISSUE TITLE
Modal - mobile positioning

### ISSUE THREAD

**Issue by jq-87** [buefy/buefy#2983]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome

### Steps to reproduce
1. View the modal in a mobile viewport
2. The default position is still center of viewport - this is not optimal on mobile

### Expected behavior
Anchoring modals to the bottom of the viewport on mobile instead of the center makes them easier to reach / use.
Example of suggested position is here:
https://twitter.com/steveschoger/status/1186330420671057921/photo/1

### Actual behavior
Modal on mobile is centered in viewport making it harder to reach / use than a bottom position.
https://buefy.org/documentation/modal/

**Comment by jtommy** [comment]
You might override the default style on mobile in order to position it on bottom.
