### ISSUE TITLE
b-tabs not rendering server side (nuxtjs)

### ISSUE THREAD

**Issue by GreenmeisterDavid** [buefy/buefy#2984]
### Overview of the problem

**nuxt-buefy** version: 0.4.3
**Vuejs** version: 2.6.12
**Nuxt** version: 2.14.6

### Description

Same as issues [#18](https://github.com/buefy/nuxt-buefy/issues/18) and [#478](https://github.com/buefy/buefy/issues/478), the b-tab component isn't being rendered server side, causing a jump in the layout.

### Steps to reproduce

1. Create a nuxt project.
2. Copy the [b-tabs example](https://buefy.org/documentation/tabs) from the buefy documentation.
3. Run it.

### Expected behavior

The tabs being rendered server side.

### Actual behavior

The tabs being rendered client side, causing the layout to jump.

**Comment by jtommy** [comment]
Can you reproduce it on codesanbox?

**Comment by GreenmeisterDavid** [comment]
I looked into it some more and it seems I came to the conclusion of the b-tabs not working properly a bit premature: when ran in dev (npm run dev) they load client side, but they seem to work fine when running in live (npm run build, npm run start). Here's a codesandbox link if you want to play around with it: https://codesandbox.io/s/proud-voice-4dmpr?file=/nuxt.config.js

I'll close this issue now.
