### ISSUE TITLE
Anchor tag on the menu doesn't close on click

### ISSUE THREAD

**Issue by Tragio** [buefy/buefy#2985]
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.12
**OS/Browser**: MacOS 10.13 / Brave

### Description

When there is an anchor tag on the menu, in other words, when you click and it scrolls to a certain place on the same page, it doesn't close the menu.

### Expected behavior

Close the menu whatever the `<a href>` is sending to the same page or not.

### Actual behavior

[https://streamable.com/nozhj4](https://streamable.com/nozhj4)

**Comment by jtommy** [comment]
Drop-down or menu ? A reproduction of your code ?

**Comment by Kulcanhez** [comment]
> Drop-down or menu ? A reproduction of your code ?

@jtommy yes, of course. You just need to run, resize your window for the hamburger menu to appear, and then click on the _Bug_ menu item. You will notice that the navbar will never close.

[beufy-anchor-bug.zip](https://github.com/buefy/buefy/files/5407006/beufy-anchor-bug.zip)

**Comment by Tragio** [comment]
@jtommy here is a simple one-page website so you can fully understand. You just need to open the menu and click any menu item and you notice that it never closes. [https://josepedromagalhaes.pt/](https://josepedromagalhaes.pt/)
