### ISSUE TITLE
Title/Header slot for message component

### ISSUE THREAD

**Issue by m4st3rm4tz3** [buefy/buefy#2986]
### Description
When using the message component with *bulma* it is possible to place a customized title element in the the `message-header`. But with the *buefy* `b-message` component it is only possible to place a title string in the header. 

It would be nice if there was a title `slot` to customize the message header.
### Example
A possible example would be including a `b-tag `:

***bulma* solution:**
```html
<article class="message is-info">
  <div class="message-header">
    <p>Opening Hours</p>
    <b-tag type="is-success">currently open</b-tag>
  </div>
  <div class="message-body">
    <!-- example code -->
  </div>
</article>
```
**wanted *buefy* behavior to get the same result:**
```html
<b-message type="is-info">
  <template #title>
    <p>Opening Hours</p>
    <b-tag type="is-success">currently open</b-tag>
  </template>
  <!-- example code -->
</b-message>
```
### Why Buefy need this feature
This will make the `b-message` component more flexible and applicable for more use cases. And it is possible to use a customized header with *bulma*, so *buefy* should support this, too.
___
I think it shouldn't be so hard to add this, so if you guys will accept a pr on this i would like to take this.

**Comment by jtommy** [comment]
@m4st3rm4tz3 sure, make a PR !!
