### ISSUE TITLE
Bulma tabs do not work in Buefy

### ISSUE THREAD

**Issue by kovachjk** [buefy/buefy#2989]
Using Buefy 0.9.3
Using Vue 2.6
I understood that I had access to all of Bulma's capabilities inside Buefy.  I need the functionality of the Bulma tabs component but it is completely non functional.  I do not know if this is a Bulma or Buefy issue, but I am using Buefy so I assume this team has a better chance of helping me. Plus I doubt the Bulma team would take responsibility if I'm using Buefy.
My starting code is simple:   
``   
Sorry about the single line.  The code display doesn't display html code it just displays the html results.
The expected action is to have a row of tabs with a line underneath with tab "two' highlighted. Instead I have a row with three words with no lines boxes or highlights  As shown on the [Bulma tabs page.](https://bulma.io/documentation/components/tabs/)
But instead it just displays the words "One", "Two", "Three".  I does recognize the <a> tag and change my cursor to a hand pointer.

**Comment by service-paradis** [comment]
Did you try to use Buefy Tabs Component?
https://buefy.org/documentation/tabs

**Comment by kovachjk** [comment]
@service-paradis 
I need a dynamically built(for-next type) tab based menu like component that I can attach click events to.  The Buefy tab component looks like a "page switcher" component. I need to have one page that I dynamically switch content on which will be controlled by the dynamically built tabs.  The code I wrote was just to show that I am unable to get a simple static component to display properly, much less trying to implement a more complex pattern.  Thanks for commenting

**Comment by service-paradis** [comment]
Really hard to help you out with it. Your example does not contain any complete nor valid HTML. Looks like the issue is not really related to Buefy.
Can you reproduce your issue using Codepen?
