### ISSUE TITLE
B-Table multi-sort on nested data fails, working in normal sort

### ISSUE THREAD

**Issue by robertmarney** [buefy/buefy#2990]
### Overview of the problem

**Buefy** version: Dist
**Vuejs** version: 2.Dist
**OS/Browser**: Brave

### Description

When using data more than one level deep the multi-sort fails where the normal sort works.

### Steps to reproduce

See Code Pen. In short have data more than one level deep and apply multi-sort, the columns with nested data fail to sort.

### Expected behavior

Sort to be applied

### Actual behavior

No sorting 

Codepen: https://codepen.io/RMCodes/pen/bGewgVb?editors=1010

**Comment by yuchaosydney** [comment]
This is indeed an issue. 

@jtommy should this be regarded a bug? Or improvement to be made in order to support "sorting on nested props"?

In addition, @robertmarney @jtommy , do you welcome any potential pull request to resolve this "bug" or "improvement" ?

**Comment by jtommy** [comment]
@yuchaosydney of course
