### ISSUE TITLE
Really hard to help you out with it. Your example does not contain any complete nor valid HTML. Looks like the issue is not really related to Buefy.

### ISSUE THREAD

**Issue by kovachjk** [buefy/buefy#2991]
Really hard to help you out with it. Your example does not contain any complete nor valid HTML. Looks like the issue is not really related to Buefy.
Can you reproduce your issue using Codepen?

_Originally posted by @service-paradis in https://github.com/buefy/buefy/issues/2989#issuecomment-712805428_
Please read initial post
"Sorry about the single line. The code display doesn't display html code it just displays the html results."
If I lack any html ability, it is the ability to get github to accept my html code as code and not display the results of the code

**Comment by service-paradis** [comment]
No need to open new issues. Please continue the discussion in #2989.

I saw that you were sorry about the single line, but being sorry does not let me help you out. Please reproduce the issue on https://codepen.io/ or something similar. There are no reason basic Bulma code does not work. But I can help you out if you just give me a single unformatted line of code.

**Comment by kovachjk** [comment]
> No need to open new issues. Please continue the discussion in #2989.
> 
> I saw that you were sorry about the single line, but being sorry does not let me help you out. Please reproduce the issue on https://codepen.io/ or something similar. There are no reason basic Bulma code does not work. But I can help you out if you just give me a single unformatted line of code.

Thank you for replying, I will do as you asked .  It will be a few hours before I can get to it though
