### ISSUE TITLE
Bulma tabs does not work in Buefy

### ISSUE THREAD

**Issue by kovachjk** [buefy/buefy#2993]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.11]
**Windows 10**:

### Description

When using the `<div class="tabs">` component from Bulma in Buefy I get an vertical unordered list instead of the expected horizontal set of tabs with underline.

### Expected behavior
Horizontal tabs

### Actual behavior
https://codepen.io/goldwinger/pen/KKMgyMV

**Comment by service-paradis** [comment]
Working fine if you include needed dependencies (https://codepen.io/service-paradis/pen/abZmgMK)
I added `buefy.min.js`, buefy.min.css` and `vue.min.js`. Just check them all in settings.
![image](https://user-images.githubusercontent.com/12817388/96724155-851c5b80-137d-11eb-927d-5f096d498095.png)
![image](https://user-images.githubusercontent.com/12817388/96724162-86e61f00-137d-11eb-8fda-28cdc4d1992c.png)
![image](https://user-images.githubusercontent.com/12817388/96724197-8fd6f080-137d-11eb-82de-0d5e4dafe31a.png)
