### ISSUE TITLE
Docs: Modal API inconsistency

### ISSUE THREAD

**Issue by n3ps** [buefy/buefy#2995]
### Overview of the problem
**Buefy** version: [0.9.0]

### Description
Documentation page: https://buefy.org/documentation/modal
Modal API says to use the `active` property but the above code examples use `v-modal`.

### Expected behavior
Consistent API and code example.

### Actual behavior
Took some time to figure out why copying the markup example didn't work. Then noticed the API mention `active` instead of `v-model`.

**Comment by jtommy** [comment]
You should be able to use both way.
Btw in the next breaking I'm going to restore the previous version
