### ISSUE TITLE
Can b-table mobile-card active in resolution less than 1024 px ?

### ISSUE THREAD

**Issue by biigpongsatorn** [buefy/buefy#2997]
Can b-table mobile-card active in resolution less than 1024 px ?

**Comment by jtommy** [comment]
Yes, setting https://github.com/buefy/buefy/blob/9e8e55b3b34971b85616b9a605a4d1d0eebc78c1/src/components/table/Table.vue#L530 to true watching media query by JavaScript

**Comment by biigpongsatorn** [comment]
@jtommy  I mean change breakpoint of `mobile-card` from '768px' to '1024px' ?

**Comment by jtommy** [comment]
At the moment it uses Bulma tablet variable so you should change it

**Comment by biigpongsatorn** [comment]
@jtommy Thanks.
I changed the breakpoint with this code.
```scss
.table-wrapper {
    &.has-mobile-cards {
        @include tablet-only {
            @include table-cards
        }
    }
}
```
