### ISSUE TITLE
Improving dropdown - add search for items

### ISSUE THREAD

**Issue by orenlande** [buefy/buefy#3000]
### Description
Hello, I'd like to suggest an improvement to Buefy - adding a search bar to the dropdown component.
I've already experimented with a local clone of Buefy dev, seems pretty viable and easy to implement.

Here demonstration of my mockup:
[Dropdown example gif](https://imgur.com/a/fVHhuCS) (Sorry, no clue how to get gif uploaded as plain .gif file and attach here)

My suggestion is to add the attribute :searchable="true" to the `<b-dropdown>` element, and adding attribute 
:search-term="one,two,..." terms into any element inside the dropdown, be `<b-dropdown-item>` or anything else.

I query the elements by searching the :search-terms attribute and using display:none; to hide the unmatched results.

The core functionality is already implemented in my cloned source; I'd be more than happy to contribute it and improve it by code review.

### Why Buefy need this feature

It would be a great addition, as I already implemented something similar in my company, to filter out countries from the dropdown. We found it very useful and slick, so I've thought it would be an easy and a great addition to the existing dropdown component.

**Comment by jtommy** [comment]
The idea and you implementation is very nice but I shouldn't add complexity to dropdown to be honest.

**Comment by orenlande** [comment]
> The idea and you implementation is very nice but I shouldn't add complexity to dropdown to be honest.

Actually I’ve implemented only one change to JS - around 20 liners to the watcher, and one input element. 

Would you like to review code example here?

**Comment by jtommy** [comment]
Probably it makes sense adding a data prop that shows items automatically but it adds other code.
We might to think to create a new component or something similar

**Comment by orenlande** [comment]
I find it quite useful to have a searchable dropdown. Either by modifying existing one or creating a new one - I guess it’s pretty much up to you and your team.

BTW sorry, not sure about the status of this thread - what the next steps here; would you like me to proceed with a PR? Pretty much new about contributing to buefy :)

**Comment by jtommy** [comment]
@service-paradis what's your opinion?

**Comment by service-paradis** [comment]
Hum... Good question! Surely looking good! Good job @orenlande 
If you dont want to add more advanced feature to dropdown, maybe, we can add a `header` slot. User would be free to add custom content as a searchbar. We could add an example with this kind of functionality. This way, it would be lightweight and more flexible. So it could be a good compromise.

**Comment by jtommy** [comment]
@service-paradis i agree with you.
@orenlande ok ?

**Comment by orenlande** [comment]
@service-paradis sounds interesting.
How would you suggest me to implement the functionality? 

We need some place where I can store the search value and match it against the elements inside the the dropdown list.

It means we need to instruct the user to mark the element he passing down as the source of search term. 

Let me know what you think

**Comment by service-paradis** [comment]
Just made a quick check for this. It is already something feasible if the dropdown items are created dynamically. Here is an example of it:
https://codepen.io/service-paradis/pen/wvzoGOM?editors=1010
Maybe we could add an example of this in the doc? I dont know...

**Comment by jtommy** [comment]
Sure, add it!

**Comment by orenlande** [comment]
Well in I guess then no reason to add this functionality to core component then?
