### ISSUE TITLE
Tooltip doesn't close after unfocused when triggered with focus option

### ISSUE THREAD

**Issue by mng78** [buefy/buefy#3003]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

With the new version of Buefy (0.9.3), for Tooltip using 'content' slot with the triggers options 'hover' and 'focus'. For accessibility testing, using the 'tab' key so when the link is focused, the tooltip appears correctly. However, when you continue (so link isn't focused anymore) the tooltip still shows until you hover over it, then it disappear. Would it be possible to have the tooltip close after it is unfocused?

### Expected behavior

Tooltip closes when unfocused happens

### Actual behavior

Tooltip stays open even when unfocused, need to hover over it to close it which isn't good for accessibility purposes.

**Comment by jtommy** [comment]
You are right, there isn't a check
