### ISSUE TITLE
B-datepicker: outline focus

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#3004]
`b-datepicker` is using `dropdown-item` class which has an outline on `focus`:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/8303937/97198767-1c7f1580-17a7-11eb-9540-8ea0ac38f799.png">

Is there any "UI best practice" behind this approach?

**Comment by jtommy** [comment]
Did you try `:focusable="false"`

**Comment by fabiofdsantos** [comment]
Sorry, didn't notice that property. It works, thanks!
