### ISSUE TITLE
Custom searchable string in b-table-column component

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#3007]
### Description

Custom searchable string in b-table component.

### Why Buefy need this feature

Currently you can add the `searchable` attribute to the column element to make it searchable. However, I'm using custom html in my `b-table-column` components and to populate it I'm using the `props.row.myObject` with some data in it. 

Would it be possible to define `searchable-string` attribute on the `b-column` as well so we can specify which string do we want to search through?

For example:

```
<b-table-column
    searchable
    :searchable-string="[props.row.myObject.name,props.row.myObject.surname].filter(i => i).join(' ')">
         ... 
</b-table-column>
```

**Comment by jtommy** [comment]
I might add a new prop `custom-search` that is a function to use as filter for the current column. 
What do you think?

**Comment by dmcbrn** [comment]
That would be nice yes, to keep it aligned with sort.

But I'm not sure how would you approach it. 

**VERSION 1:**

This could be simple (less aligned with sort) version: 

```
<b-table-column
  ...
  custom-search="myFunction()">
....
</b-table-column>
....
myFunction(propsRowMyObject) //accept props.row.myObject
{
  returns [propsRowMyObject.name,propsRowMyObject.surname].filter(i => i).join(' ')
}
...
```

This version would not require you to write down the search but just to modify your string before passing it down to existing search function.
This would be OK in my use scenario.

**VERSION 2**

If I need to write down complete search method then that might be tricky as I don't know how to do search properly.

I found [this](https://www.tutorialspoint.com/es6/es6_string_search.htm) tutorial and if this is working properly (I never know with JS anymore) then the version 2 below would be OK for my use case too (honestly, I don't know how this all works in the backend). 

Also this version would be much better aligned with sort which requires you to write the sort algorithm yourself. So sadly for me this seems like better approach :grin: 

```
<b-table-column
  ...
  custom-search="myFunction(myString)">
....
</b-table-column>
....
myFunction(propsRowMyObject, myString) //accept props.row.myObject
{
  let validKeys = [];
  for (let key in propsRowMyObject){
   if(propsRowMyObject.hasOwnProperty(key) && propsRowMyObject.search(myString) == -1){
     validKeys.push(validKeys);
   }
  }
  
  returns propsRowMyObject.filter((o,key) => validKeys.indexOf(key) > -1 )
}
...
```

Disclaimer: didn't check for syntax errors, and copied the object iterator from [here](https://reactgo.com/javascript-loop-through-object/).

So if 2nd option works, that seems to me as most intuitive/aligned expansion. Maybe worth adding simple examples for both `custom-sort` and `custom-search` in [documentation](https://buefy.org/documentation/table/).

**Comment by jtommy** [comment]
The prop accepts a function with two argument: row (object) and input (string) and it returns a boolean (true if the input match your rule based on one or more fields of the row)

**Comment by iesta** [comment]
Do you have an example on how to use this function?  I have tried many variants, but none is working. My row is an array of string (tags actually). And i need to match each of them with the "input". Thx in advance.

**Comment by alexfaus08** [comment]
@iesta did you ever find an example? I've been looking everywhere for one and I cannot figure out how to implement this custom search

**Comment by iesta** [comment]
> @iesta did you ever find an example? I've been looking everywhere for one and I cannot figure out how to implement this custom search

No :(

**Comment by MischaZihler** [comment]
@alexfaus08 @iesta 
found this https://codepen.io/Verdoso/pen/VwPoMZV?editors=1010, the title is "Buefy table custom-search problem reproduced" though...

**Comment by lownlazy** [comment]
Best solution I found for this is use the 'field' property of the b-table-column. 

For example in the below code snippet: 
I use operationStates array in the custom component AssemblyLights but this data throws an error if used for sorting.  So I created the property statesValue which is a sum of the values in operationStates array, this value can be used to sort the column. 

 I added this value on the server side but you could calculate and append it to the JSON data on the client side after loading and before setting the Table's data variable.  

```
 <b-table-column field="statesValue" label="Shaft, Shell, Sub." width="15%" v-slot="props" centered sortable >
                <AssemblyLights :states="props.row.operationStates" />
            </b-table-column>
```

input JSON data:
```
[
{statesValue: 6,
operationStates: {shaft: 2, shell: 2, sub: 2}
},
{...}]
```
