### ISSUE TITLE
Clockpicker: Blur Event Triggers after Clock Change

### ISSUE THREAD

**Issue by julzELO** [buefy/buefy#3011]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.11]
**OS/Browser**:

### Description

The blur event triggers when switching between hours and minutes via buttons. 

Datepicker.vue
![image](https://user-images.githubusercontent.com/73643910/97570830-e9779480-19e7-11eb-989f-8726599228d3.png)

If we compare it to the datepicker, the blur event is not fired because the input field lost focus.

### Steps to reproduce

1. Click on Input Field so the Dropdown appears
2. Change the Clock to Minutes

### Expected behavior

Should not trigger, as compared to the Datepicker component.
The event should only fire when the input field is left by tab or outside mouse click

### Actual behavior

[DateInput Blur vs Clockpicker Blur Event](https://codepen.io/julzelo/pen/QWEQzeQ)
Example explanation:
The number of blur events increases after selecting minutes

**Comment by julzELO** [comment]
Do you need more Information?

**Comment by jtommy** [comment]
I'll investigate about it btw you might create a PR to fix it

**Comment by julzELO** [comment]
Why is the Clockpicker not usable with the keyboard? The DatePicker is full usable with the keyboard but the clockpicker is not. Is there a reason for this?

If the DatePicker is not usable with the Keyboard there will be the same Problem with the blur Events. 

I looked at some of the components, but i think some of the "Veterans" need to investigate it.

**Comment by yuwu9145** [comment]
Hi @julzELO ,

Correct me if wrong. In the example code that is provided, when selecting a date fro datepicker, blur event will be triggered once while selecting a min in clock picker will trigger blur event twice. So both pickers trigger blur event.

What is the exact issue though? Would you mind providing more information (perhaps attaching a gif animation would better explain it)?

**Comment by julzELO** [comment]
Hi @yuwu9145,

thanks for answering!

That's the Problem the Timepicker schould only trigger the Blur Event once, not if i select something in the Dropdown. Here i cant  distinguish if the User is finished with picking or is still in the dropdown. On the datepicker is easy to catch the blur Event because its only Fired if the User is clicking outside the input or the dropdown field.

**Comment by yuwu9145** [comment]
@jtommy after digging inside the code, looks like two blur events from **ClockPicker** was made deliberately to cope with this issue ([2085](https://github.com/buefy/buefy/issues/2085)). Therefore I think it probably needs a discussion and a decision on how should blur events behave on **ClockPicker**

**Comment by jtommy** [comment]
I didn't remember about it to be honest but we can change it in order to maintain both two needs

**Comment by yuwu9145** [comment]
@jtommy yep we can do it. Sorry I was confused myself before, [issue 2085](https://github.com/buefy/buefy/issues/2085) is about `TimePicker` while this issue is about `ClockPicker`, they are different
