### ISSUE TITLE
Sidebar content wrapping during hover transition 

### ISSUE THREAD

**Issue by Stetzon** [buefy/buefy#3013]
### Overview of the problem

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]
**OS/Browser**: OSX, Chrome:

### Description

The sidebar component has a jarring transition effect when hovering to expand.  It looks like displaying the menu labels on hover causes the content to wrap temporarily, pushing the content down, before displaying correctly next to the icons. This happens very quickly.

### Steps to reproduce

1. Use static sidebar (Go to Codepen for https://buefy.org/documentation/sidebar/#static)
2. Collapse viewport until menu labels are hidden and menu is in "reduced" state
3. Enable Expand on Hover
4. Hover the sidebar

### Expected behavior

The menu labels should appears smoothly beside the icon with no jumping/moving of menu items

### Actual behavior

Sidebar content does not transition smoothly and content has a jumping effect

**Comment by Stetzon** [comment]
The current animation is fine, it's more of a problem with how the content inside the sidebar is getting shown before the sidebar has finished it's animation/transition. Without yet having the space, the menu labels get wrapped downwards

**Comment by jtommy** [comment]
Di you have the same problem without using menu ?

**Comment by Stetzon** [comment]
I haven't tried.  Though using menu would be preferred as that's what's in the docs

**Comment by jtommy** [comment]
I wanted to know if it's a strange effect with menu in general

**Comment by service-paradis** [comment]
We can see the mentionned effect more easily when we slow down the transition.

For exemple, focus on the `Administrator` label. When we hover the reduced menu, the label appear below the icon and switch to its left when there is enough space for it.
![chrome-capture](https://user-images.githubusercontent.com/12817388/98044507-03084a00-1df5-11eb-96ed-e9ca3ef458a0.gif)

**Comment by service-paradis** [comment]
A quick workaround would be to add 
```scss
.menu-list a {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
It would give something like this
![chrome-capture](https://user-images.githubusercontent.com/12817388/98045207-1bc52f80-1df6-11eb-8a2c-5bc43262399a.gif)

**Comment by jtommy** [comment]
Thanks @service-paradis.
I'm closing it because it's no a issue about sidebar itself but we'll update the example ;)

**Comment by Stetzon** [comment]
Thank you both, looks much better!
