### ISSUE TITLE
Integrate a b-dropdown option with b-tabs

### ISSUE THREAD

**Issue by stephencarico** [buefy/buefy#3016]
### Description

Provide an easy way for developers to include an ending `b-dropdown` to their `b-tabs`, similar to how Quasar does it: https://quasar.dev/vue-components/tabs 

<img width="618" alt="Screen Shot 2020-11-02 at 7 30 59 AM" src="https://user-images.githubusercontent.com/32233894/97888013-7ddf4100-1cdf-11eb-84af-1378118da40a.png">

```
      <q-tabs
        v-model="tab"
        inline-label
        class="bg-teal text-white shadow-2"
      >
        <q-tab name="mails" label="Mails" />
        <q-tab name="alarms" label="Alarms" />
        <q-btn-dropdown auto-close stretch flat label="More...">
          <q-list>
            <q-item clickable @click="tab = 'movies'">
              <q-item-section>Movies</q-item-section>
            </q-item>

            <q-item clickable @click="tab = 'photos'">
              <q-item-section>Photos</q-item-section>
            </q-item>
          </q-list>
        </q-btn-dropdown>
      </q-tabs>
```

### Why Buefy need this feature

As apps grow so do their tab lists; and in some cases, all the tabs are necessary to keep on the page but not upon first glance (i.e. the less used tab item options).

So if developers are able to stash the less used, but still necessary, tab options in a dropdown menu it would offer a painless solution for them to reduce the tab clutter.

**Comment by jtommy** [comment]
There is already a way, using `header` slot on tab item.
Probably you'll need to style it

**Comment by stephencarico** [comment]
@jtommy ok. i see what you mean with using the `header` slot. However, what would you say is the best way to prevent the user from getting navigated to that `b-tab-item` when they click the `b-dropdown` nested in that header? Since obviously we don't want to be navigating the user to any tab item section here. We wish to only provide a dropdown from where they can select the tab item section they actually wish to be navigated.

Here's a codepen I'm working in to get this to work: https://codepen.io/stephencarico/pen/dyXKbBM?editors=1010
