### ISSUE TITLE
hide tooltip in small medium (iphone) sizes of screen

### ISSUE THREAD

**Issue by ArielDavidHerrera** [buefy/buefy#3021]
### Overview of the problem

**Buefy** version: 0.7.10
**Vuejs** version: 2.6.11
**OS/Browser**: chrome

### Description

the ttooltip fails when the size of the screen is (375x664), the tooltip with the card hide the tooltip text when is a large text
![4](https://user-images.githubusercontent.com/39654239/98165610-32ca5700-1eb4-11eb-9585-3473c63948c8.png)

### Steps to reproduce

1. in a card introduce a tooltip, 
2. with chrome go to phones sizes (375x664) and 
3. reproduce the tooltip

### Expected behavior

adapt the tooltip for no hide (375x664)

### Actual behavior
the tooltip is hide with the small medium screen 
(375x664)
![4](https://user-images.githubusercontent.com/39654239/98165610-32ca5700-1eb4-11eb-9585-3473c63948c8.png)

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/3005
