### ISSUE TITLE
Horizontal Field Without Label

### ISSUE THREAD

**Issue by CromonMS** [buefy/buefy#3024]
### Description

Would be nice to have a way of disabling the padding that the Horizontal selector on Field ie. making the label optional, even if it's left blank it creates a big padding on the left of the Form Fields. By creation of a no-label or :has-label prop, something like that. Obviously you'd default it to true, but the ability to not have that element would be very handy.

For instance:

```vue
<b-field
  :has-label="false"
  no-label
  horizontal
>
  CONTENT
</b-field>

```

Current layout:

![current-horizontal](https://user-images.githubusercontent.com/5735921/98368165-cb84e200-202e-11eb-8419-766361cf0046.png)

### Why Buefy need this feature

Using grouped instead breaks the mobile view advantages of horizontal, and being able to remove the initial label would be a handy ability for the reasons you can see in the screenshots.

Currently this workaround works, but is a messy way to remove the padding:

```js
  mounted () {
    let els = window.document.getElementsByClassName('field is-horizontal')
    els.forEach(el => {
      el.removeChild(el.childNodes[0])
    })
}
```

Fixed layout:

![after-workaround-horizontal](https://user-images.githubusercontent.com/5735921/98368176-d2135980-202e-11eb-9652-30a357b7e1b2.png)

**Comment by StaffOfHades** [comment]
For now a workaround I use is adding custom-class with is hidden.

**Comment by CromonMS** [comment]
I've actually re-done the form with columns instead, so it works flawlessly on mobile and desktop (also fixes all the weird alignments!) So I'd put this one in nice to have if possible, rather than essential. Thanks.
