### ISSUE TITLE
Tables: column sort icon overlaps into next column

### ISSUE THREAD

**Issue by eleanorcox** [buefy/buefy#3034]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.12]
**OS/Browser**: Ubuntu/Chrome

### Description

![buefy_issue_sort_arrow](https://user-images.githubusercontent.com/23172137/98967888-e78ff400-2504-11eb-93a1-ed810e5fb8f2.gif)
For tables with sortable columns, sometimes the sort arrow overlaps into the next column label. This is because the column width doesn't take into account the width of the sort icon. This happens with tables with lots of columns, and is worse on screen sizes up to desktop (particularly between mobile and desktop sizes). This only affects columns where the label is the same width or wider than the data itself (i.e. not columns where the data takes up significantly more space than the label, as here the icon displays within the width of the column).

### Steps to reproduce

1. Create a table with lots of sortable columns (~10) and populate with data
2. Resize screen and observe. As columns get thinner, the arrow icon overlaps with the next column

### Expected behaviour

The width of the column you are sorting by should also include the width of the sort icon.

### Actual behaviour

The column width is calculated from the label and data alone, meaning the sort icon overlaps into the next column.

**Comment by jtommy** [comment]
I want to refactor table header classes, there is something weird

**Comment by kikuomax** [comment]
This seems to be related to:
- #2886
