### ISSUE TITLE
Modals with autocompletes: autocomplete options fill whole page

### ISSUE THREAD

**Issue by eleanorcox** [buefy/buefy#3035]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.12]
**OS/Browser**: Ubuntu/Chrome

### Description

This is an issue with modals with autocompletes. I have a modal with an autocomplete which has a dropdown that opens on focus. Previously to buefy 0.9.4 I used `append-to-body` to ensure this dropdown displayed correctly over the modal, with the key point being the dropdown could appear over the footer of a modal and didn't require scrolling the modal. This is shown below.
![buefy-issue-autocomplete-desired](https://user-images.githubusercontent.com/23172137/98970675-1d82a780-2508-11eb-93c3-3e1af6b3e575.gif)

Now, with `append-to-body` enabled the dropdown fills the width of the page, as below.
![buefy_issue_autocomplete_append](https://user-images.githubusercontent.com/23172137/98969148-77826d80-2506-11eb-9f4f-f2464a04ec30.gif)

If I remove `append-to-body` the dropdowns now require scrolling within the modal which is undesired.
![buefy_issue_autocomplete_no_append](https://user-images.githubusercontent.com/23172137/98969141-76e9d700-2506-11eb-8538-56e92e4c661a.gif)

### Steps to reproduce

1. Create a modal
2. Add autocomplete fields with `append-to-body` true
3. The autocomplete options will fill the whole page to the right of the option

### Expected behavior

The autocomplete options should only take up as much space as the autocomplete field.

### Actual behavior

The autocomplete options fill the whole page to the right of the field.

**Comment by jtommy** [comment]
Are you using expanded prop too ?

**Comment by eleanorcox** [comment]
No, and this happens with expanded on or off

**Comment by jtommy** [comment]
Can you reproduce on codepen or similar?

**Comment by eleanorcox** [comment]
Yep, here you go https://codepen.io/eleanor_LG/pen/ZEOwEZa

**Comment by jtommy** [comment]
@eleanorcox Waiting the release:
```
.dropdown-content {
  width: 100%
  min-width: 0;
}
```
