### ISSUE TITLE
Table: Sorted column shown in drop-down instead of indicated with sort icon

### ISSUE THREAD

**Issue by bhaeussermann** [buefy/buefy#3036]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: Firefox 82.0.3

### Description

My table won't indicate the sorted column with a sort icon as in the examples. Instead, it is indicated as a selection in a drop-down (see screenshot).

How do I make it show the sort icon on the sorted column and hide the drop-down?

![image](https://user-images.githubusercontent.com/7482216/98985913-e2469f80-252c-11eb-928b-e0a9743e619b.png)

Here is my mark-up:

```
<b-table
  :data="employees"
  default-sort="firstName"
  >
  <b-table-column field="firstName" label="First Name" sortable v-slot="props">
    {{ props.row.firstName }}
  </b-table-column>
  <b-table-column field="lastName" label="Last Name" sortable v-slot="props">
    {{ props.row.lastName }}
  </b-table-column>
  <b-table-column field="title" label="Title" sortable v-slot="props">
    {{ props.row.title }}
  </b-table-column>
  <b-table-column field="birthDate" label="Birth Date" sortable v-slot="props">
    {{ props.row.birthDate }}
  </b-table-column>
</b-table>
```

**Comment by jtommy** [comment]
Are you importing MDI or FA pack ?

**Comment by bhaeussermann** [comment]
Oooh. No, I didn't.

I installed `vue-fontawesome` now and added the following to main.ts:

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faArrowUp } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

...

library.add(faArrowUp);
Vue.component('font-awesome-icon', FontAwesomeIcon);
```

And specified the sort icon like so:

```
<b-table
  :data="employees"
  sort-icon="arrow-up"
  default-sort="firstName"
  >
```

It's still displaying the drop-down 🤔. What am I missing?

**Comment by jtommy** [comment]
https://buefy.org/documentation/icon#fontawesome
