### ISSUE TITLE
Dot/dots in field names

### ISSUE THREAD

**Issue by avatar13** [buefy/buefy#3038]
When column name has dot: "test.test" -> Cell value not displayed.
Problem itself:
![image](https://user-images.githubusercontent.com/1033458/99180498-c06d3880-2737-11eb-8850-f0cd19b15f0b.png)

**Comment by yuchaosydney** [comment]
Define column as follow:

![image](https://user-images.githubusercontent.com/5698884/99223564-d9114780-2838-11eb-8d71-91bbeadebe1a.png)

**Comment by jtommy** [comment]
You shouldn't define a field name with a dot inside
