### ISSUE TITLE
Improve Buefy "Customization" docs by adding the file location and a better explanation for Step 2

### ISSUE THREAD

**Issue by iamsanteri** [buefy/buefy#3039]
### Description

Improve Buefy [customization docs](https://buefy.org/documentation/customization/) for newbies like me by actually explaining the location of where variables can or should be customized.

### Why Buefy need this feature

The example you give here is great, but what is missing..? An explanation of where to actually best do this. Is it once somewhere globally, or is it within every component where I want customizations to apply? 

Look, I'm not familiar with Sass, and I'm not all that good with Vue either. What I think is missing here is the location and where the example under step number 2 should be done. 

This might be clear for some pros and experienced people, but if you want Buefy to be accessible and widely used by everyone it would be good that you explain this a bit better. 

Due to this documentation, I myself currently still do not know where to do this so that it globally affects my entire Vue application and cascades down the component tree. Googling around doesn't help too much either, and I can also see other people being confused with this, especially on the Nuxt side. For Nuxt however this has been explained more clearly in some Stackoverflow answers. 

Please consider to improve this part of the docs so people can work better with this amazing component library. I'm quite sure this would help out a lot of early Buefy adopters. 

Thank you and much appreciated!

**Comment by jtommy** [comment]
You might make a PR in order to improve it adding missing parts ☺️

**Comment by dhait** [comment]
@jtommy A PR would be easy to do IF we KNEW the answer!  

> Due to this documentation, I myself currently still do not know where to do this so that it globally affects my entire Vue application and cascades down the component tree. Googling around doesn't help too much either, and I can also see other people being confused with this, especially on the Nuxt side.

Maybe you can add brief instructions on this issue, and then one of us can submit the PR?
