### ISSUE TITLE
Value of multiple dropdown is directly mutated

### ISSUE THREAD

**Issue by VictorCazanave** [buefy/buefy#3040]
### Overview of the problem

When using `<b-dropdown mulitple :value="myArray" />` (without `v-model`) the array value is directly mutated by the Dropdown component.

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: Any

### Steps to reproduce

1. Create a multiple dropdown like [this example](https://codesandbox.io/s/buefy-dropdown-bug-sit6n?file=/src/App.vue)
2. Select/deselect options

### Expected behavior

Since there is no `v-model`, the bound value (`myArray`) should not be modified.

### Actual behavior

The bound value (`myArray`) is directly modified by the component.

I think the issue comes from here: https://github.com/buefy/buefy/blob/7b1b739504076fa405dec7d4f30bdaf90a18eb11/src/components/dropdown/Dropdown.vue#L200
Instead of using `push()` and `splice()`, which change the content of the array, it should emit a new array (probably something like `[...this.selected, value]` and `this.selected.filter(v => v !== value)`).

If this is really a bug, I'll be glad to try to fix it!

**Comment by jtommy** [comment]
Can you reproduce on codepen?

**Comment by VictorCazanave** [comment]
Thanks for your quick reply!

The example in codesandbox doesn't work? https://codesandbox.io/s/buefy-dropdown-bug-sit6n?file=/src/App.vue

The issue is that it doesn't follow the [one-way data flow](https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow) principle of Vue.
IMHO a component shouldn't mutate its props (even objects or arrays), but emit an event with the new value of the prop to use `v-model` or `.sync`.

In my current project, I created a wrapper component (that implements `v-model`) around Dropdown to customize it and I'd like to do something before emitting the new `value`:
```js
<b-dropdown
      :value="value"
      multiple
      aria-role="list"
      @change="doSomethingBeforeEmittingNewValue"
>
...
</b-dropdown>

...
methods: {
      doSomethingBeforeEmittingNewValue(value) {
            // Create new value
            const newValue = [...value]; // Do other things

            // Emit new value
           this.$emit('change', newValue) 
      }
}
```

Of course I could watch and clone my `value` prop, then pass the clone to Dropdown to fix this issue, but it feels like a "dirty" workaround.

**Comment by jtommy** [comment]
Yes, you have completely right
