### ISSUE TITLE
Datepicker icon position

### ISSUE THREAD

**Issue by thefoxie** [buefy/buefy#3042]
### Description
The datepicker allows icon on left only, but should be able to put the icon on right as well.

### Why Buefy need this feature
To make it easier to implement given UI designs. Like this one in the picture.
![obrázok](https://user-images.githubusercontent.com/15309350/99255885-de5c9b00-2814-11eb-9028-8ac9ba62b2be.png)

**Comment by darotar** [comment]
Hey @thefoxie

From what I currently see in local dev env, it has 'iconRight' prop, probably not well documented one
![image](https://user-images.githubusercontent.com/15818529/99296485-23012a00-2847-11eb-8af1-6e03620db1e9.png)
