### ISSUE TITLE
dropdown modal makes other components unclickable

### ISSUE THREAD

**Issue by GopherJ** [buefy/buefy#3044]
![image](https://user-images.githubusercontent.com/33961674/99383899-dfea9980-28ce-11eb-8fe1-e92b0bfef72e.png)

### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.10]
**OS/Browser**:

**Comment by GopherJ** [comment]
if I remove the following div, things go back to normal:

![image](https://user-images.githubusercontent.com/33961674/99384091-35bf4180-28cf-11eb-9ad1-980863abaee1.png)

**Comment by GopherJ** [comment]
casued by me!

**Comment by jtommy** [comment]
What? Can you explain better?

**Comment by GopherJ** [comment]
hi sorry It's a mistake in my code

I have:

. dropdown. background:
    z-index: 1000

**Comment by jtommy** [comment]
You can use append-to-body
