### ISSUE TITLE
Nested table is possible?

### ISSUE THREAD

**Issue by StratoKyke** [buefy/buefy#3045]
I plan to use the detailed tables to create a sort of tree.
Using this: https://buefy.org/documentation/table#detailed-rows.
But I can't figure out if there is a way to create something interactive without stopping at a single child.
For example:
`{
            "id": 2,
            "name": "item 1",
            "order": 0,
            "child": [
                {
                    "id": 3,
                    "name": "item 1.1",
                    "order": 0,
                    "child": [
                        {
                            "id": 5,
                            "name": "item 1.2",
                            "order": 0,
                            "child": [and other]
                        }
                    ]
                }
            ]
        },
        {
            "id": 4,
            "name": "item 2",
            "order": 0,
            "child": []
        }`
Do I have a way that allows me to do this with this component?

Thanks for the reply.

Example:

> <b-table :data="categoryList" :loading="loading" detailed custom-detail-row striped hoverable>
              <template slot-scope="props">
                <b-table-column field="id" label="ID" width="40" numeric>
                    {{ props.row.id }}
                </b-table-column>
                <b-table-column field="name" :label="name">
                    {{ $t(props.row.name) }}
                </b-table-column>
                <b-table-column label=" ">
                    <div class="buttons is-right">
                    </div>
                </b-table-column>
              </template>
              <template slot="detail" slot-scope="props">
                <tr v-for="child in props.row.child" :key="child.id">
                    <td></td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;{{ child.id }}</td>
                    <td>{{ $t(child.name) }}</td>
                    <td class="has-text-centered">
                      <div class="buttons is-right">
                      </div>
                    </td>
                </tr>
              </template>
          </b-table>

**Comment by jtommy** [comment]
What do you mean with "a way to create something interactive" ?

**Comment by markokos01** [comment]
I am also interested in nested table. With current table component I am limited to only one detailed level. It would be great if I can create "tree table" with multiple levels.
