### ISSUE TITLE
Datepicker components with select range/multiple date is not enable on smartphone layout

### ISSUE THREAD

**Issue by 1010real** [buefy/buefy#3048]
I found the behavior that the feature of selecting range/multiple dates on Datepicker component is not enable on smartphone.

![image](https://user-images.githubusercontent.com/3145781/99490307-f109d800-29ac-11eb-8415-83786f2e4034.png)

### Overview of the problem

**Buefy** version: [0.9.4]
**OS/Browser**: iOS 14.2/Chrome

### Steps to reproduce

Show https://buefy.org/documentation/datepicker on smartphone.

### Expected behavior

Can select range/multiple dates on smartphone.

### Actual behavior

Can pick a date.

Thanks.

**Comment by jtommy** [comment]
Because native picker doesn't provide it, you should disable native using `mobile-native="false"`
