### ISSUE TITLE
editing app.css

### ISSUE THREAD

**Issue by Jelbert** [buefy/buefy#3053]
Hello, Im using buefy/bulman but i want to edit the css, how can I do that?

![image](https://user-images.githubusercontent.com/5991069/99782312-eb022b80-2b53-11eb-927a-10fec894c5bf.png)

I want to take out the iframe on that code to make it like this.

![image](https://user-images.githubusercontent.com/5991069/99782398-0a00bd80-2b54-11eb-8cb2-e2009d650c3f.png)

I edited the css of bulma and buefy under node_modules but the app.css under public folder has no change. Please help! Thanks

**Comment by jtommy** [comment]
Please use Discord and take a look at docs. Thanks
