### ISSUE TITLE
ability to specify a column is a hyperlink

### ISSUE THREAD

**Issue by tansaku** [buefy/buefy#3054]
### Description

Apologies if there is already an obvious way to do this, but I'd like each row (or maybe some cells in each row) to hyperlink to other pages based on content in the row, e.g. an object id.  So for example, in a list of animals, clicking on a particular animals row could take you to another view with many more details on that particular animal.  I imagine something like:

```
<template>
  <div class="container">
    <b-table :data="animals" :columns="columns" :striped=true></b-table>
  </div>
</template>
```

```
            columns: [
                {
                    field: 'id',
                    label: 'ID',
                    width: '380',
                    numeric: false,
                    sortable: true,
                    linked: `/animal/${id}`
                },
```
that would at least make that cell be a hyperlink to another endpoint for more details about the animal.  Apologies if this sort of multiple page-ness is not really vue-y.  Open to suggestions for linking in a more SPA style ...

### Why Buefy need this feature

To make it easy for individual rows in a buefy table to have an action associated with them when you click on them ... apologies is this already supported in some way for column arrays ...

**Comment by jtommy** [comment]
You have to use default slot and table column component in order to customize single cell (take a look at sandbox example)

**Comment by tansaku** [comment]
ah thanks - that's this then is it? https://buefy.org/documentation/table#sandbox-with-custom-template
