### ISSUE TITLE
b-select 'multiple' prop doesn't seem to be working.

### ISSUE THREAD

**Issue by chad-l** [buefy/buefy#3055]
When using the "multiple" prop on a b-select, I am only able to select one at a time.

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.11]
**Windows Google Chrome**:

### Expected behavior

I expected to be able to select more than one value that would be placed in the list of selected values.

### Actual behavior

Only one value is placed in the list of selected values.

### CodePen
https://codepen.io/chadlafontaine1/pen/KKMjNBy?editors=101

**Comment by chad-l** [comment]
I was able to work around this issue by doing the following.

```
addOrRemoveFromList: function (value) {

            if (this.list.includes(value[0])) {
                let index = this.list.findIndex(x => x === value[0]);
                this.list.splice(index, 1);
            }
            else {
                this.list.push(
                    value[0]
                )
            }
        },
```

and
```
<div class="columns">
     <div class="column is-6">
          <b-field label="Elements To Select">
              <b-select :value="list"
                        @input="addOrRemoveFromList"
                        multiple>
                   <option v-for="item in availableItemslist"
                                 v-bind:value="item.value">
                                 {{item.Title}}
                   </option>
             </b-select>
         </b-field>
    </div>
</div>
```

**Comment by jtommy** [comment]
I've just tried and it works well like native select.
You don't need to add additional code

**Comment by chad-l** [comment]
> I've just tried and it works well like native select.
> You don't need to add additional code

I tried and it works on mobile chrome and safari on my iPhone but doesn't work on Mac OSX desktop safari or chrome browser.

**Comment by chad-l** [comment]
@jtommy 
![multiselectNotWorking](https://user-images.githubusercontent.com/60621759/100108251-32c4d380-2e30-11eb-8524-2342b3212f9c.gif)

**Comment by jtommy** [comment]
It's normal you have to press ctrl too

**Comment by chad-l** [comment]
@jtommy  Thanks, I did not know that, but maybe I should have known.
