### ISSUE TITLE
b-numberinput doesn't recover from invalid value even after value is valid

### ISSUE THREAD

**Issue by navmed** [buefy/buefy#3059]
### Overview of the problem
Validation message doesn't go away even after the value is corrected using buttons

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: Windows/Chrome

### Description

My b-numberinput has a range of -3 to 3. If I enter -5 manually and blur, it shows me an error as expected. But, if I increase the value using the + button to -3 which is valid or any valid value, the validation message doesn't go away. The only way to make it go away it so focus on the text input and 

### Steps to reproduce

1. Enter -5 in the text input
2. Click outside the text input - validation message is shown
3. Click the + button 3 times to make the number -2

### Expected behavior

Validation message should disappear

### Actual behavior

Validation message remains unless the text input is focused and blurred

https://codepen.io/navmed/pen/poyxZgo?editors=1010

**Comment by karoletrych** [comment]
Got similiar issue, when the input exceeds range specified by min max, the validation doesn't disappear.
https://codepen.io/morphix0/pen/pYYBgG?editors=1010

In my case it seems caused by additional element: <span class="centered-text">Number </span>, if i remove it, it works.

**Comment by mateussilva92** [comment]
This probably caused by `b-field` when using `b-numberinput` along side other element inside that b-field.
Here is another codepen.

https://codepen.io/cpn20/pen/VwbbPYY

**Comment by fabiofdsantos** [comment]
> This probably caused by `b-field` when using `b-numberinput` along side other element inside that b-field.
> Here is another codepen.
> 
> https://codepen.io/cpn20/pen/VwbbPYY

@jtommy @service-paradis Any idea? Thanks!

**Comment by milad-mirkarimi** [comment]
> > This probably caused by `b-field` when using `b-numberinput` along side other element inside that b-field.
> > Here is another codepen.
> > https://codepen.io/cpn20/pen/VwbbPYY
> 
> @jtommy @service-paradis Any idea? Thanks!

Have you tried updating to the latest version (0.9.8)?

**Comment by mateussilva92** [comment]
@milad-mirkarimi the last codepen provided is using the latest version of (0.9.8) and the issue is still replicable.
