### ISSUE TITLE
Table: Line checkboxes do not respond to spacebar

### ISSUE THREAD

**Issue by Minhyme** [buefy/buefy#3060]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chrome

### Description

Clicking on line item checkboxes fires `check` event but using spacebar to select checkboxes does not. Believe the problem lies on line 248 and 278.
```
@click.native.prevent.stop="checkRow(row, index, $event)"
```

Spacebar works properly on the checkAll checkbox which are on lines 64 and 141:
```
@change.native="checkAll"
```
### Steps to reproduce

1. Use tab or shift-tab to navigate to a checkbox.
1. Click spacebar.
If the checkbox is the checkall checkbox, the `check-all` event fires.
If the checkbox is a line checkbox, the `check` event does not fire.

### Expected behavior
Expect the `check` event to fire when using spacebar to click line checkboxes.

### Actual behavior
Only the `input` event from the b-checkbox component fires when using spacebar to check line item checkbox.

**Comment by marianayap** [comment]
@Minhyme Hello! I would like to work in this issue

**Comment by jtommy** [comment]
We need to investigate about it

**Comment by hashkazi00** [comment]
@marianayap are you on it? or should I? also can we collaborate in case you need help in this.

**Comment by marianayap** [comment]
@hashkazi00 I'm no longer working on it, you can take it :)
