### ISSUE TITLE
Add icon-left, icon-right options for <b-tab-item>

### ISSUE THREAD

**Issue by marcebdev** [buefy/buefy#3061]
### Description

`<b-tab-item>` currently only supports the basic `icon` property, it'd be nice if it instead had the more specific `icon-left` and `icon-right` properties similar to buttons.

### Why Buefy need this feature

Likely the same reason why buttons have them, it avoids having to slot in multiple lines just to achieve a label with an icon (on either side) and why the icon property exists for tab-items, to begin with.

Also consistency, buttons handle it this way and tabs are another place you might want icons on one side or the other (or both, who knows.)

**Comment by jtommy** [comment]
You can do it by yourself using header slot

**Comment by marcebdev** [comment]
Indeed, the intention of this is not that it can't be done, as was mentioned in *why*.

The reasoning is that:
1) reduce code clutter, if someone is using several right icons the result is quite a bit of additional clutter
or that they extend the `<b-tab-item>` component for the sole reason of adding this feature, at which point it seems something that's probably logical to have by default.

2) insert reasons as to why `<b-button>` has seperate `icon-left` and `icon-right` props

3) as far as I have found there isn't proper styling when using the header slot, this may be a Bulma issue in part, and I can open an issue for a Bulma feature request to link here

Styling issues include


Having a right icon makes the underline thicker for default `<b-tab-item>` labels
<img width="722" alt="Screen Shot 2020-12-05 at 2 16 22 PM" src="https://user-images.githubusercontent.com/20135668/101261435-24669980-3705-11eb-84ae-1a93e4c23190.png">

Right icons don't get highlighted
<img width="723" alt="Screen Shot 2020-12-05 at 2 16 11 PM" src="https://user-images.githubusercontent.com/20135668/101261458-49f3a300-3705-11eb-9e35-1edd8fe82dc1.png">

and as witnessed in either example the icon is not centered correctly. I'm sure -- at least in part -- this requires some additions/improvements to Bulma, or perhaps just improved documentation on how to slot the component if classes do currently exists. However, it's difficult to track if the issue is closed.
