### ISSUE TITLE
Tooltip not shown when b-field label position is on-border

### ISSUE THREAD

**Issue by askmrsinh** [buefy/buefy#3065]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: Version 86.0.4240.111 

### Description

Tool tip no longer works when when used within [label slot](https://buefy.org/documentation/field#label-slot) for `b-field` with `label-position="on-border"`.
I am seeing this behavior after updating to Buefy 0.9.4.

### Steps to reproduce

```
<b-field
   custom-class="is-medium"
   label-position="on-border">
   <template slot="label">
      With tooltip
      <b-tooltip type="is-dark" label="Help text here for explanation">
         <b-icon size="is-small" icon="help-circle-outline"></b-icon>
      </b-tooltip>
   </template>
   <b-input size="is-medium"></b-input>
</b-field>
```

### Expected behavior

Tooltip should show.

### Actual behavior

Tooltip doesn't show.

**Comment by jtommy** [comment]
@user501254 did you try using `append-to-body` prop to tooltip ?

**Comment by user501254** [comment]
I haven't, didn't need that prior to 0.9.4.
I will report back results soon.

**Comment by user501254** [comment]
Tried using `append-to-body` on the tooltip, doesn't work as expected. The tooltip now flickers on hover.
Side note, "Info" dropdown on the docs website is broken.

**Comment by jtommy** [comment]
@user501254 yes, i have to improve it
