### ISSUE TITLE
.dropdown-menu .dropdown-item ( with icon )

### ISSUE THREAD

**Issue by akalankavinda** [buefy/buefy#3069]
First of all, You guys are doing great job!
Love you all Buefy Developers!

i noticed a slight issue with dropdown-menu item with icon.
the issue is icon is not aligned with the text.
Please refer the image i have provided in the following link.

https://ibb.co/HdSg7Cq

thank you all!

**Comment by ankitverma2211** [comment]
@jtommy any one working on this

**Comment by jtommy** [comment]
No

**Comment by elmatou** [comment]
Hi,@ankitverma2211 please fill in with some code not only a screenshot.

I did notice something similar.
```
        <b-dropdown-item>
          <b-icon icon="selection-off" />
          Discard
        </b-dropdown-item>
```
produces
```
<a tabindex="0" class="dropdown-item">
  <span class="icon">
    <i class="mdi mdi-selection-off mdi-24px"></i>
  </span>
  Discard 
</a>
```

Bulma proposes for icons with:
```
<span class="icon-text">
  <span class="icon">
    <i class="fas fa-home"></i>
  </span>
  <span>Home</span>
</span>
```

a little codepen to illustrate the differences: https://codepen.io/elmatou/pen/poRQNgJ


@jtommy maybe a little prop in b-icon with the text would allow the render of the span with class `icon-text`.

**Comment by elmatou** [comment]
that would be something like
```
<b-icon icon="icon-name">the text to render</b-icon>
```
implemented like that:
```
<template>
<span v-bind:class="{ 'icon-text': hasDefaultSlot }">
    <span class="icon" :class="[newType, size]">
        <i
            v-if="!useIconComponent"
            :class="[newPack, newIcon, newCustomSize, customClass]"/>

        <component
            v-else
            :is="useIconComponent"
            :icon="[newPack, newIcon]"
            :size="newCustomSize"
            :class="[customClass]"/>
    </span>
<span><slot /></span>
</span>
</template>
.....
  computed: {
    hasDefaultSlot () {
      return !!this.$slots.default
    },
....}
```

**Comment by kikuomax** [comment]
I have extracted [@elmatou's solution ](https://github.com/buefy/buefy/issues/3069#issuecomment-824161982) as Issue #3947.

Wrapping `<b-icon>` + text with `<span class="icon-text">` may be a workaround until #3947 is addressed:
```vue
<b-dropdown-item>
    <span class="icon-text">
        <b-icon icon="account" />
        <span>Account</span>
    </span>
</b-dropdown-item>
```
