### ISSUE TITLE
Toast bugs on IE11

### ISSUE THREAD

**Issue by thommeo** [buefy/buefy#307]
### Overview of the problem

**Buefy** version: 0.5.2
**Vuejs** version: ??
**OS/Browser**: Windows/IE11

### Description

1. Toast is aligned on the top left, even when instructed to be at the top in the middle or on any other position.
2. Toast appears only once, even when called multiple times.

### Steps to reproduce

1. On Windows IE11
2. Go to https://buefy.github.io/#/documentation/toast
3. Click "Launch toast (default)". Toast shows on the left. 
4. Click "Launch toast (default)" once more. Toast doesn't appear.

### Expected behavior

It is expected that the toast behaves in IE11 the same way as in other browsers, e.g. in Chrome.
On step 3 it should appear a t the top in the middle.
On step 4 it should appear every time user clicks the button.

### Actual behavior

Described in the steps to reproduce.

**Comment by Tirke** [comment]
<img width="443" alt="capture d ecran 2017-09-08 a 17 53 40" src="https://user-images.githubusercontent.com/15009522/30220172-b34263a6-94be-11e7-92c2-ed338e617eb1.png">

**Comment by jtommy** [comment]
I've fixed some issues about IE undefined javascript functions.
However style might not work correctly at the moment but as you can see IE it's not completely supported
