### ISSUE TITLE
Integrate Buefy with custom SCSS Styles.

### ISSUE THREAD

**Issue by lucasdavidferrero** [buefy/buefy#3071]
Hi people. I'm having an issue when I try to integrate Buefy and my SCSS styles. I guess that's because Buefy uses SASS and mine is SCSS.
Here is the error that I get when I compile the Vue project. I'm using Vue CLI with Vue 2.
```bash
Failed to compile.

./src/App.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/style-resources-loader/lib??ref--8-oneOf-1-4!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: ../../node_modules/bulma/sass/utilities/functions.
        on line 1 of node_modules/buefy/src/scss/buefy-build.scss
        from line 31 of src/sass/vendors/_bulma.scss
        from line 1 of src/sass/vendors/_all.scss
        from line 3 of C:\Users\Lucas\Documents\repos\df-app\src\App.vue
>> @import "../../node_modules/bulma/sass/utilities/functions";
   ^
```
I just import my main SCSS file at the entry point of the app. That SCSS is importing all my styles and then the Buefy styles.
Any help?

**Comment by jtommy** [comment]
Buefy doesn't use SASS, please follow the docs https://buefy.org/documentation/customization

**Comment by lucasdavidferrero** [comment]
@jtommy Thanks. God bless you.

**Comment by rgulden** [comment]
@lucasdavidferrero  - do you have a example of importing the custom scss file? Im trying to override the primary color but smuggling to do so, thanks !

**Comment by lucasdavidferrero** [comment]
@rgulden Hi, sure I have. First you have to install `style-resources-loader` and configure it in your vue.config.js. 

Then, you just create a file that will overwrite Bulma's variables: 
```SCSS
@import "~bulma/sass/utilities/_all";
// You first import the utilities because you may use them to generate a value.
// set the new values
$primary: blue;
$warning: yellow;
$info: green;
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

Finally, make sure to import that file in your global SCSS file. Remember that vendors files are usually imported at the top: 
```SCSS
@charset "utf-8";
@import './helpers/all';
@import './vendors/all'; // Here will be your file. 
@import './base/all';
@import './views/all';
@import './components/all';
```
This way you have customized Bulma's variables in separete SCSS files. You can also overwrite SCSS variables per component since `style-resources-loader` makes it possible.
