### ISSUE TITLE
Autocomplete infinite scroll not working on some browser zoom levels

### ISSUE THREAD

**Issue by rotkelvin** [buefy/buefy#3073]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.12]
**OS/Browser**: Windows 10/Chrome 87.0.4280.66

### Description

Sometimes you can't reach the bottom of the scroll list when scrolling down in the result list of a b-autocomplete with browser zoom level set to 80%. This in turn leads to the infinite-scroll event not firing and no more posts being loaded.

### Steps to reproduce

1. Go to https://buefy.org/documentation/autocomplete/#async-with-infinite-scroll
2. Set browser zoom level to 80%
3. Search for "foo"
4. Scroll to the bottom of the result list
5. Note that no more results are loaded without having reached the actual end of the list (i.e. the message "That's it! No more movies found." is not shown) and that the arrow down button is not disabled.

### Expected behavior

Reach the end of the scroll, the arrow down button is temporarily grey and disabled, and the infinite-scroll event is fired.

### Actual behavior

Scroll is stuck seemingly just above the end of the list and you can't scroll down any further and no event is fired.

**Comment by shurth** [comment]
Just a note that I get the same behavior on the demo w/ zoom at 100% (no changes to zoom). Tried both "foo" and "Fight" with same behavior. Oddly enough, using "A" as a search term does trigger the scroll event.

Buefy version: [0.9.4]
Vuejs version: [2.6.12]
OS/Browser: Windows 10/Chrome 87.0.4280.88

**Comment by jtommy** [comment]
@mateuswetah 'll take a look ;)

**Comment by mateuswetah** [comment]
Hi @shurth, I'm sorry for the delay. 

Unfortunately, I couldn't reproduce this. Tried on both Linux and Windows with Firefox and Chrome. 

Since the error did not happened with the "A" string that you mentioned, could you try again and let us know if it still happens? I could not find a direct relation between it.

**Comment by luckasdc** [comment]
I just reproduced the issue. at 110%, new items at the end of the scrollbar won't be loaded (own project and even on the buefy documentation page). At 100%, it worked again. Could only reproduce it in Chrome on macOS.

**Comment by peaeater** [comment]
This issue appears to be (accidentally) fixed with the Sept 2022 commit for issue #3787 which adjusts the checkIfReachedTheEndOfScroll calculation.
