### ISSUE TITLE
Tag with close in tag list produces unwanted offset

### ISSUE THREAD

**Issue by elmatou** [buefy/buefy#3074]
### Overview of the problem

**Buefy** version: "^0.9.3"
**Vuejs** version:  "^2.6.12",
**OS/Browser**: Firefox 83, Chromium 87

### Description
in a taglist, if a tag is "attached", it is not aligned with other tags

### Steps to reproduce
```
      <b-taglist>
        <b-tag v-for="(tag, key) in tags" :key="key" :type="'is-' + key">{{
          tag
        }}</b-tag>
        <b-tag
          type="is-primary"
          close-type="is-primary"
          closable
          attached
          >Offline
        </b-tag>
      </b-taglist>
```

### Expected behavior
tag should be aligned with others even with an attached close icon.
as it already works with the "closable" when not "attached"
![image](https://user-images.githubusercontent.com/292021/100860227-85d20280-3490-11eb-8cde-d825f69ed7ff.png)

### Actual behavior
Tags are not aligned

![image](https://user-images.githubusercontent.com/292021/100860716-27595400-3491-11eb-8f81-a878dbbbab97.png)
![image](https://user-images.githubusercontent.com/292021/100860169-7488f600-3490-11eb-9118-0c6f29155eaf.png)

**Comment by nikhilkutinha** [comment]
Bluma adds a -0.5px margin to the last element within the tags class for some reason, a work around for this would be applying a "mb-0" class to your attached **<b-tag class="mb-0">** component until this is fixed.

**Comment by elmatou** [comment]
Indeed, much better than my custom class....

https://codepen.io/elmatou/pen/PoGzGjX?editors=101

but your are right ! it is not a buefy issue ! I'm gonna close this and open it upstream

**Comment by elmatou** [comment]
I might have gone to quick in closing this.

documentation do not explicitly allow nesting of "tags" class https://github.com/jgthms/bulma/issues/3209
This could be interpreted as a buefy issue then.

**Comment by jtommy** [comment]
Why buefy issue ?

**Comment by elmatou** [comment]
Because Buefy allows to nest any `b-tag` in a `b-taglist`, and when this `b-tag` has `attached` & `closable` prop, Buefy render it with nested `tags` class (one for the tag with `has-addon` the second for the list it self), which is not allowed by bulma (for now).

**Comment by Kashalls** [comment]
Still seems to be a present issue even almost 2 years later. Bulma does not wish to fix this.
