### ISSUE TITLE
validation error icon never goes away with field addons

### ISSUE THREAD

**Issue by foundryspatial-duncan** [buefy/buefy#3077]
### Overview of the problem

**Buefy** version: 0.9.1
**Vuejs** version: 0.9.4
**OS/Browser**: Ubuntu 18.04 / Chrome 87, Firefox 83

### Description

When a field has "addons", it never recovers from the validation error state (is-danger)

### Steps to reproduce

See this minimal reproduction:
https://codepen.io/foundryspatial-duncan/pen/PoGPBWy?editors=1010

1. Type an invalid email like "foobar" into a field with an addon
2. unfocus the field to trigger the html5 validation
3. field gets red border and the (!) icon
4. finish typing the address foobar@example.com

### Expected behavior

The red border and the (!) icon should vanish

### Actual behavior

The red border and the (!) icon remain, even with a valid input.
This doesn't happen with a plain v-input, but it starts happening only after adding "addons", see this demo:
https://codepen.io/foundryspatial-duncan/pen/PoGPBWy?editors=1010

**Comment by vitaliy-sk** [comment]
I guess the issue in computing.parentField (FormElementMixin.js)

The workaround is to set addon to false and wrap content field manually
E.g

```
 <b-field label="Domain">
            <p class="control">
              <span class="button is-static">https://</span>
            </p>
            <b-input
              expanded
              required
              minlength="4"
            />
            <p class="control">
              <span class="button is-static">.com</span>
            </p>
          </b-field>
```

Replace with

```
 <b-field :addons="false" label="Domain">
            <div class="field-body">
              <div class="field has-addons">
                <p class="control">
                  <span class="button is-static">https://</span>
                </p>
                <b-input
                  expanded
                  required
                  minlength="4"
                />
                <p class="control">
                  <span class="button is-static">.com</span>
                </p>
              </div>
            </div>
          </b-field>
```

**Comment by matt3188** [comment]
I can confirm this work around worked for me. Thanks! From what I've seen the message on the parent get's updated but the type doesn't.

**Comment by wymli** [comment]
Thanks! Works for me.  
add  `:addons="false" class="field has-addons" ` to the direct parent
