### ISSUE TITLE
Using router-link tag on a b-menu-item with children disables menu expansion

### ISSUE THREAD

**Issue by Starcross** [buefy/buefy#3078]
Using the router-link tag on menus with child items appears to override the click event listener in MenuItem.vue. The menu cannot be expanded to access the child menu item elements

It's possible to work around this putting the router link in a slot, but this introduces an extra wrapping <a> element as the default tag. This causes extra padding from the css

**Buefy** version: 0.9.3
**Vuejs** version: :2.6.11
**OS/Browser**: Linux / Chrome

### Steps to reproduce
```
<b-menu-item v-bind:tag="'router-link'"
                         v-bind:to="..."
                         v-bind:label="...">
  <b-menu-item></b-menu-item>
</b-menu-item>

```

**Comment by jtommy** [comment]
Did you try listening click event and pushing a new route on click instead of use router link ?

**Comment by Starcross** [comment]
I haven't tried adding an event listener. I'm not sure how this would help as the child method onClick needs to be called, and this isn't possible from the parent afaik
