### ISSUE TITLE
When append-to-body is set to true with b-dropdown, classes which are added to b-dropdown tag dynamically will not be reflected to dropdown-menu.

### ISSUE THREAD

**Issue by ginlime** [buefy/buefy#3082]
### Overview of the problem
When append-to-body is set to true with b-dropdown, classes which are added to b-dropdown tag dynamically will not be reflected to dropdown parent.

**Buefy** version: [0.9.4]
**Vuejs** version: [3.0.4]
**OS/Browser**:

### Description
The vue statement:
```html
<b-dropdown :append-to-body="true" class="class-a" :class="['class-b']"></b-dropdown>
```

Turned into:
```html
<!-- for dropdown-trigger -->
<div class="dropdown dropdown-menu-animation class-a class-b"></div>
<!-- for dropdown-menu -->
<div style="position: absolute; left: 0px; top: 0px;">
  <div class="dropdown dropdown-menu-animation class-a"></div>
</div>
```

The class dynamically added (class-b) is not reflected to dropdown-menu. 

### Steps to reproduce

Codes in "Description" can reproduce.

### Expected behavior

The class dynamically added will be reflected to dropdown-menu.
Or, any other prop will be provided.

### Actual behavior

Codes in "Description" will happen.

**Comment by jtommy** [comment]
You are right, I fixed it only on tooltip component https://github.com/buefy/buefy/blob/c0cc6cb1a6e04c5755c729c829cdb77bbb906fbf/src/components/tooltip/Tooltip.vue#L124
