### ISSUE TITLE
BModal doesn't show Scrollbar despite scroll="keep"

### ISSUE THREAD

**Issue by klaasstue** [buefy/buefy#3089]
Buefy really speeds up development because of its ready-mades. But sometimes it sucks because of not expected problems like this one: I utilize a modal to pop up detailed employee information, but the modal is not scrollable despite {scroll: "keep"} (firefox vuejs plugin shows scroll: "keep" for the modal). As the modal in centered vertically and fixed I can't see the bottom and top of the modal. The same problem occurs with dropdowns where the bottom stays hidden. I'm using Vuejs 2.6.4 in connection with Buefy v0.9.4. 

Is there any additional setting I have to provide?

Cheers Klaas

**Comment by klaasstue** [comment]
I had to apply "overflow: scroll; max-height: 90vh" to the card content div to get the expected/desired effect...

**Comment by jtommy** [comment]
@klaasstue can you reproduce it on codepen ?

**Comment by klaasstue** [comment]
You should find the snippets here: https://codepen.io/klaasstue/pen/poEPrLL

The card content div is part of the Card template in the js file. If you delete the mymodal class there, you will get the weird situation of a fixed modal with hidden overflow at the top and the bottom.

**Comment by jtommy** [comment]
Where is the modal in your sample??

**Comment by klaasstue** [comment]
Oh. You type  into the search field (A..) and the selected item shows up in a modal

**Comment by Baloneo** [comment]
same for me

**Comment by Baloneo** [comment]
.is-noscroll {
  overflow-y: auto;
}

my solution
