### ISSUE TITLE
B-Table | B-Table-Column | Header slot | Missing column header on mobile cards

### ISSUE THREAD

**Issue by EJGamer21** [buefy/buefy#3090]
### Overview of the problem

**Buefy** version: ^0.9.4
**Vuejs** version: 2.6.10
**OS/Browser**:

### Description

The header of the column is not showing when table is on mobile card and I'm using the header slot.

This is my code

``` 
<b-table
      ref="table"
      :data="orders.items"
      striped
      paginated
      icon-pack="fas"
      aria-next-label="Página siguiente"
      aria-previous-label="Página anterior"
      aria-page-label="Página"
      aria-current-label="Página actual"
      pagination-rounded
      backend-pagination
      backend-filtering
      :loading="isLoading"
      :per-page="filters.size"
      :total="orders.count"
      @page-change="onPageChange"
    >
      <b-table-column custom-key="cheque">
        <template v-slot:header>No. de cheque</template>
        <template v-slot="{ row }">{{ row.checkId}}</template>
      </b-table-column>

      <b-table-column v-slot="{ row }" label="No. de orden" numeric>
        {{ row.id }}
      </b-table-column>
       ...
</b-table>
```

**Image of result with not mobile cards**
![image](https://user-images.githubusercontent.com/18016256/102124837-232d1f00-3e1f-11eb-9fc6-15c5feed0479.png)

**Image of result with mobile cards**
![image](https://user-images.githubusercontent.com/18016256/102124630-ebbe7280-3e1e-11eb-9fdc-13fc39af31ae.png)

### Steps to reproduce

1. Use b-table component.
2. Add a b-table-column inside the b-table.
3. Add a header slot and default slot (see code above).

### Expected behavior

Show label on mobile cards.

### Actual behavior
Not showing label on mobile cards.

**Comment by jtommy** [comment]
I'll add in the docs but cards mode doesn't support header slot.

**Comment by EJGamer21** [comment]
Why? ):

**Comment by jtommy** [comment]
Because mobile cards is a only CSS "transformation" of a table to a list

**Comment by EJGamer21** [comment]
@jtommy Can you help me with this?

Make the label to the top and the content on the bottom without overflow.
For example: (
```
_________________
| *My label*    |
| My content    |
| is so long    |
| that it keeps |
| going down    |
_________________
```
![image](https://user-images.githubusercontent.com/18016256/102128136-cb44e700-3e23-11eb-89d4-8431028ebc6a.png)

**Comment by jtommy** [comment]
Mmm I'll investigate about it

**Comment by EJGamer21** [comment]
Try to implement it please. 🙏
