### ISSUE TITLE
Async table + checkable not working well when moving across pages

### ISSUE THREAD

**Issue by OrenLX** [buefy/buefy#3091]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: Chrome

### Description

Hello, Seems like Buefy doesn't support well checkable rows in an async table. The checked rows are not persisted - when I tick a row and moving on to a different page, and then back - the `checkedRows` still including the checked row, but it doesn't get ticked.

### Steps to reproduce

You can see it on live example provided in docs: https://codepen.io/pen?&editors=101
Simply add checkable attribute to the table.

### Expected behavior

Keep the ticked rows persists across pages.

**Comment by jtommy** [comment]
You have to use `custom-is-checked` in order to improve the compare function when async data and reloading them
