### ISSUE TITLE
Tab and Step components that support VueRouter

### ISSUE THREAD

**Issue by 6XGate** [buefy/buefy#3093]
### Description

Support for VueRouter in the existing BTab or BStep components, or maybe a new BRouted versions of these, would be great to support applications that need to associates router paths with tabs or steps.

### Why Buefy need this feature

Many produts such as AWS will associate URL paths to specific tabs in their UI for easy bookmarking. Support for a similar mechanic would be great.

We've had to implement this ourselves, but keeping that in sync with Beufy's implementation is a bit much.

**Comment by LeanKhan** [comment]
Hey @6XGate how did you implement this?

**Comment by 6XGate** [comment]
I can't share the code due to it being part of an employee's code base. But, there isn't much logic for this if you don't need all the Buefy tabs features.  The steps are another story. If you are familiar with Bulma and how to configure VueRouter or its RouterLink, you just need to put RouterLinks in the same markup as normal Bulma tabs. If you need all the feature. It's more involved.

**Comment by LeanKhan** [comment]
@6XGate okay that's fine. I have actually used the router links with Bulma tabs. It's the Steps that are another thing, like you said. I could use a separate step snippet then replace the buttons with router-link. But I like the look of BStep 😄

**Comment by 6XGate** [comment]
@LeanKhan, look at Buefy's code and CSS classes for steps and that will get you started.
