### ISSUE TITLE
Support for router-link in the autocomplete component 

### ISSUE THREAD

**Issue by nikhilkutinha** [buefy/buefy#3094]
### Description
Just wondering if the autocomplete component can be modified to support router-links as dropdown items. I'm happy to submit a PR is it's worthy enough.

### Why Buefy need this feature
Currently you can nest router-links inside the hardcoded anchor tags via slots https://github.com/buefy/buefy/blob/57da5adfa719dd9ed2bbbe04c817b8c5be77a5ea/src/components/autocomplete/Autocomplete.vue#L58 These tags are styled to add padding around itself which can be troublesome since clicking on them doesn't actually navigate to the router-link. Adding native router-link support would be useful when the component is used as way to navigate around a site, like I've done here.

![Capture](https://user-images.githubusercontent.com/61931921/102449532-7dfe8a80-405a-11eb-8365-3e021d5a4dd2.PNG)

**Comment by jtommy** [comment]
I might change a to div but in your case you can listen select event and use programmatically routing.
