### ISSUE TITLE
Column searchable, by default with exclusion and comparator ("!", ">", "<")

### ISSUE THREAD

**Issue by FlorianChretien** [buefy/buefy#3096]
Hi !

Thanks for implementing the custom-props ! On the other hand, it is a problem to have to put this function for all the columns of our dozens of tables ... it is possible to put by default in buefy:

- exclusion (with the sign "!") (for numerics and string)
- comparison (with the sign "<" or ">") '(for numerics)

Thank you a thousand times for your work and your courage!

Good day to you

**Comment by jtommy** [comment]
I understand but we cannot put so many props in component when you get full power using the new prop

**Comment by FlorianChretien** [comment]
I understand this concern. Yet it seems to me that it could be beneficial to everyone. This feature does not necessarily seem superfluous to me but hey .. Too bad !

Thank you
