### ISSUE TITLE
 Table with header cells in the top row and first column

### ISSUE THREAD

**Issue by renatomanalili** [buefy/buefy#3098]
Is it possible to implement this kind of table in the current version of b-table?

Thank you

![image](https://user-images.githubusercontent.com/35069469/102569558-a3ee6280-4120-11eb-83d8-81511038acb8.png)

**Comment by jtommy** [comment]
Yes, you can do it customizing default cell classes and thinking to have 5 columns withe first column empty.
Btw tabke component is great using it like data table
