### ISSUE TITLE
Table with checkboxes use a deprecated property syntax (Vue 3, breaking change)

### ISSUE THREAD

**Issue by didaquis** [buefy/buefy#3099]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS 10.15.6 Catalina

### Description

I have noticed that the recommended syntax in the documentation is `:checked-rows.sync="checkedRows"` but this syntax has been deprecated in Vue 3.

If we use the new syntax, the checkboxes in the table no longer work. Details about new syntax are explained here: https://v3.vuejs.org/guide/migration/v-model.html#migration-strategy

Vue 3 migration docs: https://v3.vuejs.org/guide/migration/v-model.html#v-model 

<img width="625" alt="Captura de pantalla 2020-12-18 a las 9 18 27" src="https://user-images.githubusercontent.com/6883041/102595218-8963bb80-4117-11eb-922e-7747888452dd.png">

**Comment by jtommy** [comment]
Yes, but Buefy at the moment doesn't support Vue 3.
I'll update it when it will be ready with new v-model syntax
