### ISSUE TITLE
Add a general search bar at the top

### ISSUE THREAD

**Issue by gasci** [buefy/buefy#3102]
### Description

We can have separate search fields for columns but we cannot have a general search bar for all columns. It would be great to have one like in this picture:
![alt text](https://i.stack.imgur.com/M6Uil.png)

### Why Buefy need this feature

I think it is one of the best vue front-end open source projects with great table support. This search bar exist in most of open source projects and it is quite aesthetic and easy to use by customers.

**Comment by jtommy** [comment]
You can do it separately, why do you need into table component ?
