### ISSUE TITLE
Carousel List Item width breaks when inside flexbox

### ISSUE THREAD

**Issue by kdaniel21** [buefy/buefy#3103]
### Overview of the problem

**nuxt-buefy** version: 0.4.4 (nuxt-buefy!)
**Nuxt** version: 2.14.11 (also tested with Vue)
**OS/Browser**: Ubuntu 20.04, Firefox 85

### Description

In case the items to show property is calculated based on the element width (and the presumed item width) it works, then suddenly breaks and the element widths become enormous (800 000+ px).

### Steps to reproduce

1. Open Codepen
2. Resize the window
3. To solve the issue: remove is-flex and is-flex-direction-column classes

### Expected behavior

It should've been resized normally.

### Actual behavior
The slide item widths become huge.
By removing the is-flex and is-flex-direction-column classes the problem disappears.

[Codepen](https://codepen.io/kdaniel21/pen/LYRjpyL)

**Comment by casnet1** [comment]
I have this problem too. i have tried to find which style is breaking it but i didn't find anything. 
A quick resolution is use porcents and media queries.
note: i'm still noob

**Comment by emrysr** [comment]
i still have this issue... once i drop the `<b-carousel-list>` in a bulma `.column` then all the styling for each item is off (1000s of px off!)
