### ISSUE TITLE
b-input lags when multiple inputs ( 100 inputs ) are loaded & same with b-autocomplete which happens if I dynamically add them ( over 7 to 8 )

### ISSUE THREAD

**Issue by highoncarbs** [buefy/buefy#3105]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 0.2.16
**OS/Browser**: Edge , Windows 10

### Description

So I upload multiple images around 10 to 20 , and then when I start to type in the inputs ( normal input , autocomplete )
the input takes time to reflect. There is a considerable lag when if number of images increases - sometimes around a minute or so.

### Steps to reproduce

The issue occurs here  
`<b-input v-modal="item.name" />`

But this is fixed when I use this -
` <b-input
              :value="item.name"
              @change.native="item.name = $event.target.value"
              placeholder="Enter Product Title"
            />
            `
             
 

### Expected behavior

No lags when typing in.
### Actual behavior

I started typing in at the start of the video , but it reflects almost 10 sec later - more prominent when I have more than 10 sets of fields.

https://user-images.githubusercontent.com/6228854/102744721-7acc0d00-4380-11eb-8e9f-6d41ec0b2001.mp4

So what would be my best bet here either wrapping all inputs with the workaround , or am I missing something else

**Comment by jtommy** [comment]
It's really strange. Are you able to use native input instead of b-input ?

**Comment by highoncarbs** [comment]
Yes , Also I think it's a pattern mistake on my end . Break my whole component into sub components ( each product attribute field ) , solved this issue. 
Can you confirm ?

**Comment by jtommy** [comment]
Ok, nice to know

**Comment by highoncarbs** [comment]
But I'm still not sure about autocomplete. If a form is long , should I also break them up ?
