### ISSUE TITLE
Date picker selects wrong date range when using keyboard

### ISSUE THREAD

**Issue by IgnacioFigueroa** [buefy/buefy#3107]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 3.0.4
**OS/Browser**: Google chrome

### Description

When the keyboard is used to select a range of dates (due to accessibility matters), the date is wrongly selected. 

### Steps to reproduce

1. Place a datepicker with range prop enabled.
2. Click on the datepicker main field
3. Use your keyboard to select the date range, for example Dec-21-2020 to Dec-29-2020

### Expected behavior

Selected range of dates would be Dec-21-2020 to Dec-29-2020

### Actual behavior

The selected range of dates is Dec-22-2020 to Dec-29-2020. If the difference of dates is a month or a year, the error get more evident.

https://user-images.githubusercontent.com/38017296/102809978-af03f580-43a1-11eb-991f-864e1a390dd5.mp4

**Comment by jtommy** [comment]
And using the mouse ?

**Comment by IgnacioFigueroa** [comment]
It works, but i need to work the keyboard due to accesibility for a blind person.

**Comment by jtommy** [comment]
It's strange but I'll take a look
