### ISSUE TITLE
XSS in b-table

### ISSUE THREAD

**Issue by iqbaltawakkal** [buefy/buefy#3108]
i found security flaw when injecting html into b-table. 

### Overview of the problem

**Buefy** version: v0.9.4
**Vuejs** version: v2.6.12
**OS/Browser**: Chrome

### Description

firing javascript on when inserting html that has js event

### Steps to reproduce

insert html tag that has js event into into props :data

### Expected behavior

string got escaped

### Actual behavior

https://codepen.io/iqbaltawakkal/pen/zYKdQWX?editors=1010

**Comment by jtommy** [comment]
I think I'll disable it so if you want to put html you have to use table column slot

**Comment by iqbaltawakkal** [comment]
my concern is that if the data is from user input

**Comment by Anyman552** [comment]
This should be fixed! Normally vue takes care of this: https://vuejs.org/v2/guide/security.html#HTML-content.

**Comment by wesdevpro** [comment]
@jtommy was this ever addressed?
