### ISSUE TITLE
b-numberinput incorrect handling of negative numbers between 0 and -1

### ISSUE THREAD

**Issue by satyavh** [buefy/buefy#3109]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: OSx / Firefox

### Description
It's impossible to enter negative numbers between 0 and -1 in b-numberinput.

### Steps to reproduce
1. Go to https://buefy.org/documentation/numberinput
2. Try entering -0.3, as soon as you hit the 0 key the negative sign will be removed and the number will be made positive

### Expected behavior
Starting a number with - should not mutate that number to positive.

### Actual behavior
Number becomes positive while it should be negative as the user started entering the number with a - sign

**Comment by yuwu9145** [comment]
I found this should be a vue issue: https://github.com/vuejs/vue/issues/11897
