### ISSUE TITLE
Column width not working

### ISSUE THREAD

**Issue by agungprabawa** [buefy/buefy#3112]
### Overview of the problem

**Buefy** version: ^0.9.4
**Vuejs** version: ~2.6.12
**OS/Browser**: Chrome

### Description
Hi I try to set width of every column on the table, but it's not working,
here is my code
`<b-table-column field="tanggal_valuta" width="200" label="Tanggal Valuta" sortable v-slot="props">
                {{ props.row.tanggal_valuta }}
              </b-table-column>`

and here is the result
the width still less than 100px
![image](https://user-images.githubusercontent.com/20855299/103128700-ef78b180-46c8-11eb-93ef-da07f7309d64.png)

**Comment by jtommy** [comment]
Using a string you have to specify the unit otherwise :width="200"

**Comment by agungprabawa** [comment]
I have try it, and still not working, the width still less than 100px
