### ISSUE TITLE
Append to body dropdown has positive z-index when inactive

### ISSUE THREAD

**Issue by Dragoncall** [buefy/buefy#3113]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: Chrome (but doesn't matter)

### Description

When using a dropdown with `append-to-body="true"`, the appended div has a positive z-index, making a part of the page unclickable as it is hidden behind this appended div.

### Steps to reproduce

1. Create a dropdown
2. Add the `append-to-body` prop to it
3. Open your page and you will see the div has no specified z-index.

### Expected behavior

The expectation would be that the div has no influence on the page while inactive.

### Actual behavior

The div has an unspecified z-index, letting it capture clicks while in an inactive state.

**Comment by jazzzz** [comment]
The issue is still present because the fix was reverted in #3257. I reproduce the bug with Buefy version 0.9.19.
