### ISSUE TITLE
mobile-cards breakpoint for table component

### ISSUE THREAD

**Issue by niklashaug** [buefy/buefy#3115]
### Description

Add Buefy variable to change the mobile-cards breakpoint of the Table component.
### Why Buefy need this feature

Being able to manually set the breakpoint in case you also want to use mobile-cards for tablets etc.

**Comment by jtommy** [comment]
There isn't a Buefy variable, you can change it by Bulma `mobile` variable https://bulma.io/documentation/overview/responsiveness/
