### ISSUE TITLE
Wrapper for "append-to-body" in a namespaced css

### ISSUE THREAD

**Issue by dmitry-gerasimov** [buefy/buefy#3116]
### Description

It would be great to add something like an "append-to-body-container-class" (string). So that you're able to set the namespace for the buefy css. If this option is set an additional wrapper with classes is created.

We use buefy in a large system where on a single page there could be components using buefy and components using other frameworks (we're gradually migrating to buefy/bulma). In order to make this work we had to prefix all buefy classes with a root class and apply buefy styles only to the component container. Using "append-to-body" is impossible as anything that is appended to body lacks styles.

### Why Buefy need this feature

To provide more flexibility for larger users.

**Comment by jtommy** [comment]
Probably is too complex and out of scope of the project given that Bulma itself doesn't provide an official way to prefix the classes

**Comment by didaquis** [comment]
In my opinion, the request @dmitry-gerasimov makes is really interesting. 
If you have multiple elements with the "append-to-body" option and you want to customize the styles independently you are going to have a lot of problems. However, adding something like what @dmitry-gerasimov indicates would solve it elegantly.
