### ISSUE TITLE
Importing individual components does not work as described in documentation

### ISSUE THREAD

**Issue by bhaeussermann** [buefy/buefy#3117]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11

### Description

I followed the steps on the ["Getting Started" page](https://buefy.org/documentation/start) for importing individual components, which don't work. I'm not sure if the problem is with the documentation or with Buefy itself.

### Steps to reproduce

1. Create a new Vue 2 app using Vue CLI, selecting Typescript for the language and "Class-style component syntax"
1. Import the buefy package: `npm install buefy --save`
1. Import individual components as on the ["Getting Started" page](https://buefy.org/documentation/start). My main.ts looks as follows:
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import { Table, Input } from "buefy";
import "buefy/dist/buefy.css";

Vue.config.productionTip = false;

Vue.use(Table);
Vue.use(Input);

new Vue({
  router,
  render: h => h(App)
}).$mount("#app");
```
4. Run `npm run build`

### Expected behavior

The build succeeds.

### Actual behavior

The build fails with the error `Module '"../node_modules/buefy/types"' has no exported member 'Table'. Did you mean to use 'import Table from "../node_modules/buefy/types"' instead?`

**Comment by fabiofdsantos** [comment]
See https://github.com/buefy/buefy/issues/2057

**Comment by bhaeussermann** [comment]
Thanks @fabiofdsantos, that explains it.
I don't know how to approach writing those typings, so I'm currently looking into finding a work-around to importing individual components in a typescript project.

To this end, I renamed main.ts to main.js, but the build then fails with the following error

```
This relative module was not found:

* ./src/main.ts in multi ./src/main.ts
```

Any idea how to configure babel to consider main.js as the entry-module instead of main.ts? I can't find that reference in the babel config.

**Comment by bhaeussermann** [comment]
Alright, I found the work-around:

I moved the code I had in main.ts into a new file startup.js, moving the statements into a function called `initialize()`:
```
// startup.js

import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import { Table, Input } from "buefy";
import "buefy/dist/buefy.css";

export function initialize() {
  Vue.config.productionTip = false;

  Vue.use(Table);
  Vue.use(Input);

  new Vue({
    router,
    render: h => h(App)
  }).$mount("#app");
}
```

And changed main.ts to the following:

```
// main.ts

const startup = require('./startup.js');
startup.initialize();
```

This effectively makes typescript ignore the fact that no type definitions exist for the components `Table` and `Input`. This work-around ought to be temporary and needed until said typings have been added.
