### ISSUE TITLE
Update material design icons url

### ISSUE THREAD

**Issue by sasaorasanin** [buefy/buefy#3122]
Seems like MDI changed CDN URLs, so you might want to update URL from https://cdn.materialdesignicons.com/5.0.45/css/materialdesignicons.min.css to https://dev.materialdesignicons.com/getting-started/webfont ?

**Comment by fabiofdsantos** [comment]
- https://github.com/buefy/buefy/pull/3020
- https://github.com/buefy/nuxt-buefy/pull/84
