### ISSUE TITLE
docs: not clear how to set defaults when using CDN

### ISSUE THREAD

**Issue by matthewdarwin** [buefy/buefy#3123]
### Overview of the problem

**Buefy** version: v0.9.4 
**Vuejs** version: v2.6.11
**OS/Browser**: Linux/Firefox

### Description

Documentation at https://buefy.org/documentation/constructor-options seems to indicate that the way to change defaults is to use `Vue.use(Buefy, {key: value});` but not how this is meant to work when using a CDN (as specified by #2 Standalone option on https://buefy.org/documentation/start)

### Steps to reproduce

1. Create a simple web page, using CDN for vue/buefy

```
<html>
<head>
...
</head>
<body>
<div id="app">
<button class="button is-medium is-primary" @click="hello">Launch</button>
<script>
        Vue.use(Buefy, {
          defaultDialogConfirmText: 'Ack!'
        });
        console.log(Buefy);
        new Vue({
          el: '#app',
          methods: {
            hello: function() {
               this.$buefy.dialog.confirm({
                 title: 'Hello',
                 message: 'What do you want to do?',
               });
            }
          }
        });
</script>
</div>
</body>
</html>
```

### Expected behavior

Expect the dialog box to show "Ack!" and "Cancel" buttons ("Ack!" coming from defaultDialogConfirmText)

### Actual behavior

The dialog box shows "Ok" and "Cancel" buttons (this is the default text)

**Comment by jtommy** [comment]
Try using `this.$buefy.config.setOptions({...})` non created hook of Vue instance
