### ISSUE TITLE
Cannot read property 'clientX' for carousel in mobile breakpoint

### ISSUE THREAD

**Issue by trdonnisedavid** [buefy/buefy#3131]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.9..6
**OS/Browser**: Chrome

### Description

In [Carousel](https://buefy.org/documentation/carousel/#custom-as-an-indicators) when switching my screen to mobile view and select one in the carousel list it shows an console error.

![Screen Shot 2021-01-07 at 9 25 18 AM](https://user-images.githubusercontent.com/46433499/103839762-17a1e080-50cb-11eb-8ccf-437ac05339d7.png)

![Screen Shot 2021-01-07 at 9 25 12 AM](https://user-images.githubusercontent.com/46433499/103839753-14a6f000-50cb-11eb-94c6-2d5c94e8d5a3.png)

### Steps to reproduce

1. Go to: https://buefy.org/documentation/carousel/#custom-as-an-indicators
2. Switch browser to mobile view / toggle device toolbar.
3. Select the *Custom as an indicators* example and click any of the image in the carousel list.

### Expected behavior
No console log error should be display.

### Actual behavior
Working as expected but console log error is showing.

**Comment by jtommy** [comment]
@Tofandel can you check it, please? 😉

**Comment by trdonnisedavid** [comment]
Hi @jtommy have you guys deployed this one?

**Comment by trdonnisedavid** [comment]
I want to check the version of the documentation but the dropdown is not working.

![Screen Shot 2021-01-11 at 10 51 29 AM](https://user-images.githubusercontent.com/46433499/104143592-1dfdc880-53fb-11eb-832d-c54c7d65bf32.png)

**Comment by jtommy** [comment]
No the new release isn't ready
