### ISSUE TITLE
Dynamic attribute on `<b-table-column>`

### ISSUE THREAD

**Issue by themodernpk** [buefy/buefy#3133]
### Overview of the problem

**Buefy** version: [0.94]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chrome

### Description

I am trying to set the attribute `data-id` based on `props` data. Review view the following code snippet:

### Steps to reproduce

```vue
<b-table :data="is_empty ? [] : data">
            <template  >
                <b-table-column v-slot="props" field="id"
                                :data-id="props.row.id" <---- I AM UNABLE TO SET THIS
                                label="ID"  >
                    {{ props.row.id }}
                </b-table-column>
            </template>
</b-table>
```

### Expected behavior

In the previous versions I was able to define `props` in the `template`  tag like `<template  slot-scope="props">` and based on this I was able to set the dynamic attribute to child tags.

### Actual behavior

Can you assist me, how to set these dynamic attributes?

**Comment by jtommy** [comment]
You cannot add it to native TD but you might create a div into table column with `data-id` and value

**Comment by themodernpk** [comment]
Hi @jtommy, Thank you for your response. I had a scenario where I need to hide the column based on the `props` data. Is there any workaround?

**Comment by jtommy** [comment]
There is `visible` prop
