### ISSUE TITLE
[BUG] Using Autocomplete with Observable Objects Results In The First Entry Being [object object]

### ISSUE THREAD

**Issue by Dan6erbond** [buefy/buefy#3137]
### Overview of the problem

**Buefy** version: 0.9.0
**Vuejs** version: 2.6.11
**OS/Browser**: Windows / Chrome

### Description

I have a project using VueJS, Apollo Client, Buefy which fetches some data from a NodeJS API running a GraphQL server. I'm using the autocomplete feature of the `<b-taginput>` to create a multi-select for car makes, which are fetched from the aforementioned API.

When searching and selecting elements, the first one will always be changed to `[object object]` instead of what it should be. Any consecutive objects are properly selected and displayed, I've also ran some tests using the `before-adding` event but noticed no differences between the data from the first selection vs later ones.

Now, I know VueJS maps these values to observables in order to be able to react to changes. I cannot say for certain, but it seems like this is the culprit to the issue. Any help is appreciated!

### Steps to reproduce

1. Clone [this](https://github.com/Dan6erbond/carmanagement) repo, make sure you're on the `bugs/buefy-autocomplete` branch.
2. Install the server and frontend packages.
3. Create an empty `server/tmp/db.sqlite` file.
4. Install Knex CLI globally and run `knex migrate:latest` as well as `knex seed:run`.
5. Start the server and client using `yarn dev` and `yarn serve` respectively.
6. Go to http://localhost:8080/cars in your browser and try adding a make to the selection.

### Expected behavior

Each selected make is added to the `<b-taginput>` and its name is properly displayed.

### Actual behavior

The first make only shows up as `[object object]` which breaks the entire flow.

**Comment by jtommy** [comment]
I am not able to see your code (client)

**Comment by Dan6erbond** [comment]
@jtommy did you make sure you were in the `bugs/buefy-autocomplete` branch?

**Comment by jtommy** [comment]
Oh you are right, I'll take a look
