### ISSUE TITLE
Tooltip doesn't multiline when its content is only a word

### ISSUE THREAD

**Issue by elC0mpa** [buefy/buefy#3138]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.12]
**OS/Browser**:

### Description
I want to show in a tooltip some checksum value, which has lot of chars. The problem is that my tooltip is not being multilined and I am setting this property to true. Is there any way to solve this? Maybe a property for content wrapping or something like that?
![image](https://user-images.githubusercontent.com/53531665/104114438-3975b000-52e3-11eb-9c11-f4034a901d88.png)

### Expected behavior
I expect the tooltip content to be wrapped inside it like in this case:
![image](https://user-images.githubusercontent.com/53531665/104114470-996c5680-52e3-11eb-8d0e-9b76113506a9.png)

### Actual behavior
The actual behavior is shown in the image placed on Description section

**Comment by fabiofdsantos** [comment]
Quick fix: `overflow-wrap: break-word;`

@jtommy Should we apply it if `multiline` property is used?

**Comment by elC0mpa** [comment]
@fabiofdsantos @jtommy something about this?
