### ISSUE TITLE
type="search" does not show a reset button in search input in cordova-ios

### ISSUE THREAD

**Issue by gasci** [buefy/buefy#3139]
### Overview of the problem

**Buefy** version: [0.9.1]
**Vuejs** version: [4.3.1]
**OS/Browser**: macOS, Chrome (cordova-ios)

### Description

type="search" does not show a reset button in search input on cordova-ios

### Expected behavior

type="search" should show a reset button in search input

**Comment by service-paradis** [comment]
Is the `x` button shown when using a native input with `type="search"`?

**Comment by gasci** [comment]
No, unfortunately it isn't.
________________________________

**Comment by service-paradis** [comment]
Hum, since we're using the native search feature, it looks like this is a problem with cordova-ios.
