### ISSUE TITLE
Customizing Buefy according to the docs leads to strange results

### ISSUE THREAD

**Issue by FlorianLoch** [buefy/buefy#3145]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: Windows 10/Opera (Though, should not matter)

### Description

I am sorry, I cannot get CSB to work with my example. I can try once more to make it work but perhaps someone can spot the issue without me doing so. I made the following sandbox, but it doesn't work (but I am not sure whether this is a limitation of CSB tbh): https://codesandbox.io/s/buefy-template-forked-4rmx6

When customizing buefy as documented the styles of ```b-modal``` break.

### Steps to reproduce

I am using plain ```b-modal```. It works fine, styles are applied - everything is nice. I have a ```styles.scss``` aside my ```main.js```. I import the former from the latter. The only line in ```styles.scss``` is ```@import "~buefy/dist/buefy.css";```. As I said - this works fine.

When I customize buefy as written in the [docs](https://buefy.org/documentation/customization) things break. I replace the single line from above in ```styles.scss``` with the code from the docs. Customization works, colors change. But the styles for the modal are broken.
I tried to understand how this can happen but I did not find out yet.

So using ```@import "~buefy/dist/buefy.css";``` works fine, using the following does not:

```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// // Set your colors
// $primary: #2f7aa5;
// $primary-light: findLightColor($primary);
// $primary-dark: findDarkColor($primary);
// $primary-invert: findColorInvert($primary);
// $twitter: #4099ff;
// $twitter-invert: findColorInvert($twitter);

// // Lists and maps
// $custom-colors: null !default;
// $custom-shades: null !default;

// // Setup $colors to use as bulma classes (e.g. 'is-twitter')
// $colors: mergeColorMaps(
//   (
//     "white": (
//       $white,
//       $black,
//     ),
//     "black": (
//       $black,
//       $white,
//     ),
//     "light": (
//       $light,
//       $light-invert,
//     ),
//     "dark": (
//       $dark,
//       $dark-invert,
//     ),
//     "primary": (
//       $primary,
//       $primary-invert,
//       $primary-light,
//       $primary-dark,
//     ),
//     "link": (
//       $link,
//       $link-invert,
//       $link-light,
//       $link-dark,
//     ),
//     "info": (
//       $info,
//       $info-invert,
//       $info-light,
//       $info-dark,
//     ),
//     "success": (
//       $success,
//       $success-invert,
//       $success-light,
//       $success-dark,
//     ),
//     "warning": (
//       $warning,
//       $warning-invert,
//       $warning-light,
//       $warning-dark,
//     ),
//     "danger": (
//       $danger,
//       $danger-invert,
//       $danger-light,
//       $danger-dark,
//     ),
//   ),
//   $custom-colors
// );

// // Links
// $link: $primary;
// $link-invert: $primary-invert;
// $link-focus-border: $primary;

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
@import "~bulma/sass/utilities/_all";
```

### Expected behavior
The styles to be applied correctly.
![image](https://user-images.githubusercontent.com/5587805/104615239-57e3fe80-5689-11eb-9944-c47afd4bf177.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/5587805/104615146-397e0300-5689-11eb-8091-8b288d61708f.png)

**Comment by 6XGate** [comment]
I've found that following the code in `buefy-build.scss` tends to work best.
```scss
/* Bulma utilities and initial variables. */
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/initial-variables";
@import "~buefy/src/scss/utils/all";

//
// Your customizations here.
//

// Bulma and Buefy finishing up.
@import "~bulma/bulma";
@import "~buefy/src/scss/utils/variables-ext";
@import "~buefy/src/scss/buefy";
```

Due to the way Bulma is coded, it doesn't play as nice with derivative CSS libraries as end-user code. This is mainly down to `~bulma/sass/utilities/derived-variables.sass` including all it's defaults there and then the color map generations.  Bulma should split itself at that point right before `$colors` is initialized.

**If** Bulma and Buefy both would be setup such that this was possible:
```scss
@import "~bulma/sass/initialize";
// Your customizations here.
@import "~bulma/sass/boot";
```
Then all Buefy would need is to do something similar and both could allow for derived libraries and end-user code to actually not have these oddities.
