### ISSUE TITLE
Feature[b-table]: return unchecked items on check-all event

### ISSUE THREAD

**Issue by kamaladenalhomsi** [buefy/buefy#3150]
### Description

currently, check-all is returning newly checked rows, but it returns an empty array when the user uncheck-all.
investigating the source code:
https://github.com/buefy/buefy/blob/bb2fb8d4fe77d8d67225b57a502c0756d4b364da/src/components/table/Table.vue#L903-L916
I found out that buefy is only passing the `newCheckedRow`
### Why Buefy need this feature
in case of adding checked items to an external list, it would make sense to remove them too.

I would be glad to submit a PR to solve this.

**Comment by jtommy** [comment]
Sure, submit your PR, thanks
