### ISSUE TITLE
During the second package, although the button is clicked, the value value will not be changed.

### ISSUE THREAD

**Issue by Valar103769** [buefy/buefy#3157]
[codepen](https://codepen.io/valar123/pen/qBawNYL?editors=1011)
I looked at the source code of the dev branch, and I don't know what the problem is.

### Expected behavior
use `v-model="page"`, the page  should can modify sync

**Comment by jtommy** [comment]
Pagination doesn't support v-model, please take at docs

**Comment by Valar103769** [comment]
Realize, I need to declare in custom
````js
    model: {
        prop: 'current',
        event: 'update:current'
    },
```
