### ISSUE TITLE
NumberInput can accept a letter "E"

### ISSUE THREAD

**Issue by ralphskie** [buefy/buefy#3162]
### Overview of the problem

**Buefy** version: latest version on buefy.org
**Vuejs** version: -
**OS/Browser**: Windows Chrome 87.0.4280.141

### Description

Said control can accept a letter "E" or "e" only. On testing it only accepts this letter.

### Steps to reproduce

1. Goto https://buefy.org/documentation/numberinput
2. Type "E" or "e" on the demo of the said control

### Expected behavior

Should only accept integer or decimals.

**Comment by jtommy** [comment]
Because the native number input accepts it.. it's exponential notation
