### ISSUE TITLE
b-tab-item value attribute not working in latest version

### ISSUE THREAD

**Issue by Waterloo** [buefy/buefy#3163]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows / Chrome

### Description

b-tab-item no longer using the supplied value attribute instead it uses tab index as value.

### Steps to reproduce

```
 <b-tabs v-model="activeTab">
            <b-tab-item label="Pictures" :value="100" >
               Expected Value 100, Current Value: {{activeTab}}
            </b-tab-item>
</b-tabs>
```

### Expected behavior

b-tab-item should use the value bound to it 

### Actual behavior
currently, it uses the index of the tab as a value
[https://codepen.io/chirpingsha/pen/poEXJKB](https://codepen.io/chirpingsha/pen/poEXJKB)

**Comment by jtommy** [comment]
You should use a string value, the number works with index
