### ISSUE TITLE
b-table pagination order prop

### ISSUE THREAD

**Issue by thefoxie** [buefy/buefy#3166]
### Description
There's no order prop for pagination.

### Why Buefy need this feature
To be able to center pagination and use `<b-pagination/>` at its full potential.

#### Workaround
```vue
<b-table
   :data="tableData"
   paginated
   :current-page="currentPage"
   >
        <template #pagination>
            <b-pagination
                v-model="currentPage"
                :per-page="20"
                order="is-centered"
                :total="tableData.length"
                @change="pageChanged"
           />
       </template>
</b-table>
```

**Comment by jtommy** [comment]
@thefoxie you might create a PR ;)

**Comment by thefoxie** [comment]
@jtommy I will. I've started the work on vue 3 branch as well but didn't have enough time as I expected initially.
