### ISSUE TITLE
Get the value filtered by a table with filters

### ISSUE THREAD

**Issue by foufrix** [buefy/buefy#3169]
### Description

Using a table with filter, i would like to know if it's possible to get the data filteredn either by an event which is triggered on filter, or with a methods callable to get the current data filtered

I have searched inside the API and did not found a solution for that

### Why Buefy need this feature

Can be useful for dashboard and exporting some state, for my use case as an example is a user want to filter some user and show them on a map.

I can help and do a merge request if needed if someone can point me into the right direction to achieve that

Thanks in advance 🙏 

And awesome work on buefy !

**Comment by jtommy** [comment]
I'm sorry but i didn't understand well your need.
Can you explain it with an example?

**Comment by foufrix** [comment]
of course, sorry if not clear ! 

Let's say i have 20 users that i load in a table, and when i apply filter like this : 
![image](https://user-images.githubusercontent.com/16646581/106398018-66137800-6408-11eb-9c34-4d50880be45d.png)
So there is only 2 users now on the table, is it possible to get only those 2 users with a methods or callback that provide only what i see on the table (meaning what's filtered)

**Comment by jtommy** [comment]
@foufrix you can get them using `this.$refs.table.newData`

**Comment by foufrix** [comment]
@jtommy awesome thank you very much !! is this somewhere in the docs that i missed ?

**Comment by Faisal-Munir-PK** [comment]
@jtommy Hi i'm very new with vuejs. 
can you help me understand how to use `this.$refs.table.newData` with same issue,

thanks in advance
