### ISSUE TITLE
Otherwise, it happens that a connection error occurs

### ISSUE THREAD

**Issue by rah-emil** [buefy/buefy#3175]
Please correct file "buefy/src/scss/buefy-build.scss":
```
@import "./node_modules/bulma/sass/utilities/functions";
@import "./node_modules/bulma/sass/utilities/initial-variables";
@import "utils/_all";
@import "./node_modules/bulma/bulma";
@import "utils/variables-ext";
@import "buefy";
```
Otherwise, it happens that a connection error occurs

**Comment by service-paradis** [comment]
I'm not able to reproduce.

Can you reproduce the issue using codepen or codesandbox?
Also, which version of Vue and which version of Buefy are you using?

**Comment by service-paradis** [comment]
You probably should not use `buefy-build.scss` file
It might be related to #3242
