### ISSUE TITLE
Fix duplicated sass code with Bulma 0.9.2 upgrade

### ISSUE THREAD

**Issue by scheinercc** [buefy/buefy#3186]
### Description

I was just curious if there are plans already in place to upgrade to Bulma 0.9.2?
https://github.com/jgthms/bulma/releases/tag/0.9.2

### Why Buefy need this feature

I was debugging code duplication in the generated CSS file, which led me to check Bulma's mixins file. I then found that exactly this issue had recently been looked after a change had been published: https://github.com/jgthms/bulma/pull/3216

**Comment by service-paradis** [comment]
Yes, the next Buefy release will use Bulma 0.9.2.

**Comment by scheinercc** [comment]
Fixed on 30.03. with https://github.com/buefy/buefy/releases/tag/v0.9.5
