### ISSUE TITLE
Row Grouping in Table

### ISSUE THREAD

**Issue by rognales** [buefy/buefy#3187]
### Description

To able to group row based on row attributes. example:-

![image](https://user-images.githubusercontent.com/28396330/107474568-82a07480-6bad-11eb-82fa-a88e8bd826bf.png)

### Why Buefy need this feature

This is just presentation layer. It would make buefy table solution complete.

**Comment by Dharmendra205111014** [comment]
Can we reopen this, this is a very much needed feature from table completeness point of view.
