### ISSUE TITLE
Tooltip with empty label stays active

### ISSUE THREAD

**Issue by oversome** [buefy/buefy#3189]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6]
**OS/Browser**:

### Description

`<b-tooltip>` is active even with an empty `label`.

### Expected behavior

In Buefy version 0.8.x, `<b-tooltip>` is not active if its label is empty.
Starting with version 0.9.0, this is no longer the case.

IMHO, hiding the tooltip when `label` is empty was the right thing to do: this way, we do not have to test `label` and set `active` accordingly.

I would love to have this behavior restored.

Thank you!

**Comment by jtommy** [comment]
I think you should set `active` prop, breaking or not is the correct way
