### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by tridcatij** [buefy/buefy#319]
Hello, trying to override some default bulma's variables.

> // Fonts
> @import url('https://fonts.googleapis.com/css?family=Rubik:400,500&subset=cyrillic');
> 
> // Import Bulma's core
> @import "~bulma/sass/utilities/_all";
> 
> **$family-sans-serif: "Rubik", "Roboto", sans-serif;**
> 
> // Set your colors
> $lightblue: #ecf5fe;
> $primary: #8c67ef;
> $primary-invert: findColorInvert($primary);
> $twitter: #4099FF;
> $twitter-invert: findColorInvert($twitter);
> 
> // Setup $colors to use as bulma classes (e.g. 'is-twitter')
> $colors: (
>     "white": ($white, $black),
>     "black": ($black, $white),
>     "light": ($light, $light-invert),
>     "dark": ($dark, $dark-invert),
>     "primary": ($primary, $primary-invert),
>     "info": ($info, $info-invert),
>     "success": ($success, $success-invert),
>     "warning": ($warning, $warning-invert),
>     "danger": ($danger, $danger-invert),
>     "twitter": ($twitter, $twitter-invert),
> );
> 
> // Links
> $link: $primary;
> $link-invert: $primary-invert;
> $link-focus-border: $primary;
> 
> // Import Bulma and Buefy styles
> @import "~bulma";
> @import "~buefy/src/scss/buefy";

All example variables working good, but for example `$family-sans-serif` or `$background-color` are not working at all.

Font family still default: `font-family: BlinkMacSystemFont, -apple-system, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif;`

**Comment by martinhbramwell** [comment]
I'm a newbie at Vue, Buefy, SCSS, etc, but have a lot of developer experience otherwise. 
Nevertheless, I am mystified by this task of customization.

I cloned, installed and ran **buefy-simple**, and saw the intended page in my browser, no problem.
I changed displayed text in App.vue and Hello.vue, and saw the changes in my browser moments later, no problem.
I changed the `<a>` tag color in Hello.vue, and saw the hyperlinks change color in my browser, no problem.

But, simple changes I made in the `<style lang="scss">` had no effect whatsoever!

I reverted everything back to the original clone and made a single change as shown ....

```diff
you@xubxentest:~/projects/buefy-simple$ git diff
diff --git a/src/App.vue b/src/App.vue
index be460f2..9f1e26c 100644
--- a/src/App.vue
+++ b/src/App.vue
@@ -66,7 +66,7 @@ export default {
   @import "~bulma/sass/utilities/_all";
 
   // Set your colors
-  $primary: #f1896f;
+  $primary: #67EF8D;
   $primary-invert: findColorInvert($primary);
   $twitter: #4099ff;
   $twitter-invert: findColorInvert($twitter);
you@xubxentest:~/projects/buefy-simple$ 
```
... but ... nothing!

Everything remained the same, yet commenting out any of the `@import` statements caused errors.

I don't get it! What is the secret to customization?

**Comment by wopian** [comment]
I haven't seen what Buefy Simple is, but from the code snippet, you may be missing the Buefy import after making your variable customisations.

E.g https://github.com/wopian/hibari/blob/new/src/styles/bulma.scss

**Comment by martinhbramwell** [comment]
Yeah, I think it's fair to say that this is a documentation bug.

**Specifically** for newbs like me the bottom line of [Buefy Documentation--> Customizing theme with Sass](https://buefy.github.io/#/documentation/customization) states ...

> If you're still not sure how to proceed, take a look at this [repository with a basic setup to customize Buefy](https://github.com/rafaelpimpa/buefy-simple).

So `buefy-simple` is the _official_ repo for learning how to customize Buefy, yet changing the primary color, as shown in the diff in my original post, does nothing at all,

**Comment by sstottelaar** [comment]
I'm also running into this issue that I can't change the default font through variables.  To simply put it:

> // Import Buefy
> @import "~bulma/sass/utilities/_all";
> 
> // Import custom fonts
> @import url('https://fonts.googleapis.com/css?family=Muli:400,700');
> 
> // Set variables to overwrite Buefy
> $family-sans-serif: "Muli", sans-serif;
> 
> // Import Bulma and Buefy styles
> @import "~bulma";
> @import "~buefy/src/scss/buefy";

This should overwrite the default font but it doesn't. Has anyone found a solution?

**Comment by sstottelaar** [comment]
I've found the solution that solved my problem. In the docs it says to load Bulma first, then make changes and then load Bulma and Buefy:

> // Import Bulma's core
> @import "~bulma/sass/utilities/_all";
> // Custom variables go here
> $family-sans-serif: "Roboto", sans-serif;
> // Import Bulma and Buefy styles
> @import "~bulma";
> @import "~buefy/src/scss/buefy";

This is incorrect, it needs to be like this:

> // Custom variables go here
> $family-sans-serif: "Roboto", sans-serif;
> // Import Bulma and Buefy styles
> @import "~bulma/sass/utilities/_all";
> @import "~bulma";
> @import "~buefy/src/scss/buefy";

I hope this gets fixed in the docs cause it may be confusing to new users like myself.

**Comment by williamabbott** [comment]
Same issue. Following as per instructions. Changes not taking effect.

// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors
$family-sans-serif: 'something';

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";

The css is not being imported elsewhere. If I move the utils line below my custom variables - it works - but then I can not reference any other vars or functions in my custom vars.

**Comment by danaia** [comment]
I want to override the Buefy's styles for a table. I am using a red color to test. Does Buefy use the Table variables for Bulma? Buefy's table does not reflect Bulma's table mods. Is that the case?

```#app {
@import "~bulma/sass/utilities/_all";

// Set your colors
$lightblue: #ecf5fe;
$primary: $info;
$primary-invert: findColorInvert($primary);
$twitter: #4099FF;
$twitter-invert: findColorInvert($twitter);
$table-color:  #FF0000;
$table-background-color: #FF0000;
$table-cell-heading-color: #FF0000;
$table-head-cell-color: #FF0000;
$table-foot-cell-color: #FF0000;
$table-head-background-color:  #FF0000;
$table-body-background-color:   #FF0000;
$table-foot-background-color: #FF0000;
$table-row-hover-background-color: #FF0000;
$table-row-active-background-color:  #FF0000;
$table-row-active-color: #FF0000;
$table-striped-row-even-background-color: #FF0000;
$table-striped-row-even-hover-background-color:  #FF0000;```

**Comment by danaia** [comment]
@jtommy I am using webpack but per the docs, I can customize bulma at the App.vue level here is my full code block: [https://gist.github.com/danaia/37735123c4b911329b24db077a415abb](url) ...i was bringing the CSS directly via main.js but the docs said I could do it this way as well...

**Comment by jtommy** [comment]
Yes you haven't to import css

**Comment by danaia** [comment]
@jtommy not sure what you mean? "haven't" to import the CSS?

**Comment by jtommy** [comment]
In your main.js you shouldn't import buefy.css if you want customize the style

**Comment by guruparanun** [comment]
If you want to customize, you must remove`import 'buefy/dist/buefy.css'` from 'main.js' file.

**Comment by GiorgosK** [comment]
To override the primary color you will need something like this 

`<style lang="scss">
@import "~bulma/sass/utilities/_all";
// Set your colors
$primary: #6356AB;
$primary-invert: findColorInvert($primary);

// Setup $colors to use as bulma classes (e.g. 'is-twitter')
$colors: (
    "primary": ($primary, $primary-invert),
);
@import "~bulma";
@import "~buefy/src/scss/buefy";

@import './assets/css/global.css';
</style>`

**Comment by bambalamm** [comment]
> ..., it needs to be like this:
> 
> // Custom variables go here
> $family-sans-serif: "Roboto", sans-serif;
> // Import Bulma and Buefy styles
> @import "~bulma/sass/utilities/_all";
> @import "~bulma";
> @import "~buefy/src/scss/buefy";

This works! Thank you.
To clarify it a bit for future readers:
```
// Import Non-Bulma stuff
@import url("https://fonts.googleapis.com/css?family=Roboto");
$family-sans-serif: "Roboto", sans-serif;

// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors etc..
$primary: #8c67ef;
$primary-invert: findColorInvert($primary);
$twitter: #4099FF;
$twitter-invert: findColorInvert($twitter);

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

**Comment by thebspin** [comment]
@bambalamm 

> This works! Thank you.
> To clarify it a bit for future readers:

Really? This doesn't work for me.. but this does:

```// Set your colors
$primary: #67400d;
//$primary-invert: findColorInvert($primary);

// Import Bulma and Buefy styles
@import "~bulma/sass/utilities/_all";
@import "~bulma";
@import "~buefy/src/scss/buefy";```

By putting it all at the end

**Comment by persi12** [comment]
Ok I made it works with this setup:
`
/ Import Bulma's core
@import "~bulma/sass/utilities/functions";

// Set your colors etc..
$primary: #8c67ef;
$primary-invert: findColorInvert($primary);
$twitter: #4099FF;
$twitter-invert: findColorInvert($twitter);

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
`

**Comment by sebastianks** [comment]
I found that the example in the documentation **is indeed working**, but the font family variable is called: `$family-primary`, and is the one used for the body. The documentation is a bit weird here, since there's 2 ways, apparently, of doing it. One that sets the sans-serif version, and one that sets the body font family.

You can see the `$family-primary` variable is used for the body family at the bottom of the documentation.

**Comment by slidenerd** [comment]
Do you have to @import "~buefy/src/scss/buefy"; import the whole buefy scss file? can you not import the scss needed only for a dropdown navbar and autocomplete?

**Comment by major-mayer** [comment]
For me also only the `$family-primary` worked to specify the font-family.
`$family-sans-serif` had no effect. Could be a bug on Bulma's side?

**Comment by turbopasi** [comment]
@thebspin 
> **Edit** I even found out i could leave away `@import "~bulma/sass/utilities/_all";` and it would still work. Whenever i import that before $primary it does not work for me.

Thanks ! After I removed `@import "~bulma/sass/utilities/_all";` all customized colors started to work. 
For example : `type="is-success"` on a tag would not use the $success variable I setup , but now it works.
