### ISSUE TITLE
[Feature] Optionally allow TagInput to create a tag on blur

### ISSUE THREAD

**Issue by Lucassifoni** [buefy/buefy#3194]
Hello,
Here's a feature request that I would be willing to implement if it's deemed useful to the project.

### Description

Add an option to the TagInput component that makes it transform its text input to a tag on blur.

### Why Buefy need this feature

Currently, and despite instructions, my clients sometimes forget to validate their input with <ENTER> while using the TagInput and creating a non-existent tag. I use TagInputs to allow them to choose an existing value or create a new one. If text is left in the field unvalidated, it is not added to the tags array, and I'm unable to process it in my backend.

What do you think ? Is that a library concern or something that should stay at the discretion of Buefy's users, maybe wrapping TagInputs ?

**Comment by jtommy** [comment]
There is already `before-adding` prop, did you check it?

**Comment by Lucassifoni** [comment]
Hello,
Maybe I don’t understand how it works, but could it be used to add the pending text input to the tag output array ? I’m talking about the case someone entered text but did not hit enter, I’d like to have on blur the same effect as pressing enter.
Sorry if this was an overlook on my part

**Comment by jtommy** [comment]
Ahh ok, i didn't understand well.
https://github.com/buefy/buefy/blob/262b405779650307bc5cd9df1c18d0a305c0f090/src/components/taginput/Taginput.vue#L303
We might change it, but I have a question for you.. how do you are sure that user entered a custom option and he/she didn't select an option correctly ?

**Comment by Lucassifoni** [comment]
Well, I’m using the tag input to allow my user to select many-to-many relationships by name.

1) If they select something existing, a struct like {id, name} goes into the array, on the backend I try to retrieve the model by its ID and associate.

2) If they just write something down, I get a string. On the backend I check for an existing item with the same name. If it exists, go to 1), else, go to 3)

3) For some simple models like tags it is handy to just create it on the fly with this string as a name, making a new future option.

For more complex models I disallow new entries and display an informative message if a string goes through.

It’s just that I have many users for this internal app and those small convenience features go a long way.

But I’m okay to do it in userland code if it’s outside of buefy’s scope.

**Comment by jtommy** [comment]
As I told we can add a prop to allow you to add a tag on blur using autocomplete too but in my opinion is a edge case.
Out of curiosity.. imagine to show a country list and the user enter "Fran", you won't find the correct country; do you add it ? Blur event might be dangerous in case the user forget to enter or select the option.

**Comment by Lucassifoni** [comment]
You’re right, it’s too specific. In my use case falsely added tags are less of a problem than tags not added because the user didn’t press enter, but that’s also an user training problem.
