### ISSUE TITLE
[Docs]: NavBar Dropdown missing label property

### ISSUE THREAD

**Issue by 6XGate** [buefy/buefy#3196]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: N/A
**OS/Browser**: N/A

### Description

NavBar Dropdown missing label property. It is using it in the example.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by service-paradis** [comment]
`label` property is used for `b-button` and `b-field` within the examples. There are no `label` prop for the dropdown nor the dropdown items.
