### ISSUE TITLE
b-input tag text align

### ISSUE THREAD

**Issue by VladMB** [buefy/buefy#3205]
### Description

Currently there is no easy way (that I have found, at least) to align text inside a b-input tag.

This could be solved if we had a text align attribute on the b-input tag, or bulma text align classes passed to input inside the component.

### Why Buefy need this feature

It's already implemented in bulma, and is hard to extend to this component.

**Comment by service-paradis** [comment]
You can use `custom-class` prop to apply classes to the input element. So something like the following should work:
```html
<b-input v-model="name" custom-class="has-text-centered" />
```
