### ISSUE TITLE
Problem in view when using appendToBody property

### ISSUE THREAD

**Issue by elC0mpa** [buefy/buefy#3207]
### Overview of the problem

**nuxt-buefy** version: 0.4.4
**Vuejs** version: 2.6.12
**OS/Browser**: Windows/Chrome 88.0.4324.150 (latest)

### Description
I had this problem when trying to use a tooltip in my project
![image](https://user-images.githubusercontent.com/53531665/108576032-d3754300-72fa-11eb-96cf-03ffec12c387.png)
So I decided to use the property ```appendToBody``` in order to solve it, and the problem was solved (partially)
Now my tooltip is not cropped by its parent
![image](https://user-images.githubusercontent.com/53531665/108576148-44b4f600-72fb-11eb-9784-4d9bbd3efe52.png)
But here is the problem that was generated
When the website is displayed on mobile view, modals aren't correctly being displayed
![image](https://user-images.githubusercontent.com/53531665/108576285-c60c8880-72fb-11eb-8b4a-bebbb4347218.png)
However, if I don't use the ```appendToBody``` property of the tooltips, modals are working as expected
![image](https://user-images.githubusercontent.com/53531665/108576355-12f05f00-72fc-11eb-85bb-56fc9aa9919d.png)

### Steps to reproduce
1. Use the ```appendToBody``` property of a tooltip and set it to ```True```
2. Display a modal in mobile view (it should display bigger than the screen)
3. Use the ```appendToBody``` property of a tooltip and set it to ```False```
4. Display a modal in mobile view (it should display correctly now)

### Expected behavior
I expect the modals to be correctly displayed when using the appendToBody property of the tooltip element

**Comment by jtommy** [comment]
Surely there is an issue, but can you provide a codepen or similar!

**Comment by elC0mpa** [comment]
Ok, I will try to, the thing is that this project is from my work, and I am not able to share it
Anyways, let me ask you something, is there any property tha makes tooltip to position without being cropped by parents? Somethimg like ```position="auto"```?
