### ISSUE TITLE
b-sidebar close animation broken when using :open prop

### ISSUE THREAD

**Issue by lukenofurther** [buefy/buefy#3208]
### Overview of the problem

**Buefy** version: current
**Vuejs** version: current
**OS/Browser**: Firefox / Chrome

### Description

When the b-sidebar open/close state is controlled by the `open` prop, and the value of the bound variable is controlled by a `v-model` on a b-switch component, the animation shown when closing the sidebar by switching the switch off goes the wrong way - i.e. away from the edge of the screen. This is the case whether the sidebar is on the left hand side or the right hand side.

### Steps to reproduce

Create a b-sidebar with its `open` prop set to a variable that is used as the `v-model` value on a b-switch component. Or see the codepen below.

### Expected behavior

The animation used when the sidebar closes should go towards the edge of the screen.

### Actual behavior
https://codepen.io/lukielew/pen/JjbyZBy?editors=101

**Comment by lukenofurther** [comment]
I've just discovered that setting the b-sidebar's `can-cancel` prop to `false` fixes this issue, presumably as it then doesn't use 2-way binding. Perhaps the default value of `can-cancel` should be false when `open` is used rather than `v-model`. Adding the incompatibility of  using the `open` prop with a non-false value of `can-cancel` to the documentation would be useful.

**Comment by Sogl** [comment]
@jtommy I have the same problem. Any ideas how to fix?

And also ca-cancel `outside` doesn't work on 1st page load, only `escape`.

**Comment by jtommy** [comment]
I'll investigate about it

**Comment by kerrigan614** [comment]
Was there ever any resolution to this issue? I'm running into the same problem.

**Comment by CUBOFIG** [comment]
I'm running into the same problem.
