### ISSUE TITLE
Missing space between date and time string in datetimepicker

### ISSUE THREAD

**Issue by cmaai** [buefy/buefy#3218]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: v2.6.12
**OS/Browser**:MacOS/Chrome (version:88.0.4324.192)
**OS Language**:Simplified Chinese

### Description
Missing space between date and time string in datetimepicker component, when setting locale to zn_CN and 24 hour format. 

### Steps to reproduce
here is an example on code pen to illustrate, it is taken from the Buify example
https://codepen.io/cmaai/pen/QWGBVvB

1. Set locale to zn_CN
2. Set hour format to 24
3. Select date and time

### Actual behavior

<img width="543"  src="https://user-images.githubusercontent.com/4726543/109920230-f3dacf80-7cf4-11eb-8a50-46aa78d3ee2c.png">

**Comment by service-paradis** [comment]
Hum... It is working fine for me...
![image](https://user-images.githubusercontent.com/12817388/110018016-dad21e80-7cf4-11eb-8f03-3695e7f968db.png)

**Comment by cmaai** [comment]
It is not working on OS language is Simplified Chinese.

**Comment by cmaai** [comment]
My OS language is Simplified Chinese, I think it's impacted by language setting.

**Comment by cmaai** [comment]
Thanks for your validation. My OS language is Simplified Chinese, I think it's impacted by language setting.
