### ISSUE TITLE
Date Picker is messed up.

### ISSUE THREAD

**Issue by JoshuaR503** [buefy/buefy#3220]
### Overview of the problem

**Buefy** version: [X.X.X] The same you use in the docs.
**Vuejs** version: [X.X.X] The same you use in the docs.
**OS/Browser**: Chrome, macOS Big Sur 1.11

### Description
When I go to the documentation [here](https://buefy.org/documentation/datetimepicker/), and I go to Granularity [here](https://buefy.org/documentation/datetimepicker/#granularity), I click the field that prompts the calendar and nothing happens. I click again and everything says "N/A" in the calendar.

### Steps to reproduce

Go to Granularity [here](https://buefy.org/documentation/datetimepicker/#granularity), click the field that prompts the calendar, nothing happens. Click again and everything says "N/A" in the calendar.

### Expected behavior

I would expect that something actually happened. Like the date I picked actually showed up.
### Actual behavior
The date doesn't show up in the first try and instead the calendar gets messed up.

No need to use this, you can do it yourself.

**Comment by jtommy** [comment]
It works well but probably I didn't understand well, can you share a video/gif ?

**Comment by JoshuaR503** [comment]
[Sure thing](https://drive.google.com/file/d/1wt8T3ZbjYGnLXD7r7w3jStMEGuyB1QD_/view?usp=sharing)

**Comment by jtommy** [comment]
Really strange.. what browser?

**Comment by JoshuaR503** [comment]
Chrome

**Comment by JoshuaR503** [comment]
Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by feryardiant** [comment]
> Really strange

Indeed.

It works fine on BrowserStack, but not on my local.

Browser: MS Edge 89.0.774 (Same Browser)
OS: Win 10 64bit (Same OS)

https://share.getcloudapp.com/p9ubl51O

**Comment by feryardiant** [comment]
Test again on my local machine, same browser & same OS, but now I select the *time* before I select the *date* and didn't experience any issue.

![mmkifYmLQd](https://user-images.githubusercontent.com/508665/113141440-e95c1900-9253-11eb-96ba-f433e0ca2b80.gif)

cc @JoshuaR503

**Comment by flipflopsimsommer** [comment]
> Really strange.. what browser?

same with firefox `87.0 (64-bit)`, on Ubuntu `20.04.2`. Its seems like the date-select is deactivated (grey) while no time is selected, but it still lets you select a date.
