### ISSUE TITLE
v-model can't work when using 'array' data creat tab-item and dynamic add new item

### ISSUE THREAD

**Issue by Fengtao1314520** [buefy/buefy#3222]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.11]
**OS/Browser**: any

### Description

I using tabs and the tab items data is an array. when i dynamic add new item into array, the v-model  data can't work after i change v-model data. the v-model  return "undefined"

### Steps to reproduce

1. First Step
set b-tabs:
` <b-tabs v-if="activesteps.length" v-model="activeTab" type="is-boxed" @input="changeTab">
      <b-tab-item v-for="(item, index) in activesteps" :key="index" :label="item.name" :value="item.id">
            {{ item.name }}
      </b-tab-item>
    </b-tabs>`
2. Second Step 
push new item into 'activesteps' by js code
`
    addNewOpenStep(step) {
      const diff = this.checkStepDiff(step, this.activesteps)
      if (diff !== true) {
        this.activesteps.push(step)
      }
      this.activeTab = step.id
    },`

### Expected behavior
the activeTab need changed and tab item need skip into I setted tab

### Actual behavior
the activeTab need changed and tab item can't skip into I setted tab, i add a function to checked when i set activeTab, the actual v-model value
`changeTab(value) {
      console.log(value)
    },`
console output 'undefined'

that's strange, as [example](https://buefy.org/documentation/tabs/), it's set activeTab and tab item can skip into setted tab.
or can i do it can be solove this issue?

**Comment by jtommy** [comment]
Did you try using a string as value of tab-item nstead of a number?

**Comment by service-paradis** [comment]
Array and object are not reactive by default in Vue (https://vuejs.org/v2/guide/reactivity.html#For-Arrays).
Can you try using `Vue.set` instead to see if it works?
It would be helpful if you could create a Codepen reproducing the issue soi we can check it out.
