### ISSUE TITLE
Table: Need transition effect for Detailed rows

### ISSUE THREAD

**Issue by volkanakkus** [buefy/buefy#3225]
### Overview of the problem

**Buefy** version: ```nuxt-buefy: 0.4.4```
**Vuejs** version: ```nuxtjs: 2.15.2```
**OS/Browser**: ```chrome```

### Description

I'm building my project with Buefy end serving my whole data with Buefy tables. Everything is fine, I redesigned the tables as cards, but I need to implement the transition effects to detailed rows open/close animations. But the ```<transititon>``` tags is not working in the table detailed slot:

```vue
<template #detail="props">
  <!-- <transition> -->
  <div :ref="props.row.id" class="item-content">
    <div class="columns">
      ...
    </div>
  </div>
  <!-- </transition> -->
</template>
```

You can check the [docs here](https://buefy.org/documentation/table#detailed-rows) and [this codepen link (#qBqQBeJ)](https://codepen.io/vivola/pen/qBqQBeJ) to check this bug. Even in the docs, unfortunately we don't have any transition for opening/closing the detailed row. 

### Steps to reproduce

1. Install Buefy
2. Paste the [code from docs](https://buefy.org/documentation/table#detailed-rows)
3. and that's it.

### Expected behavior

I expected to ```<transition>``` element would work and any kind a solution for transition animations. 

### Actual behavior

There's no transition effect as you [can see.](https://codepen.io/vivola/pen/qBqQBeJ)

**Comment by jtommy** [comment]
You can't do it, Buefy should provide it internally
