### ISSUE TITLE
reduce buefy bundle, buefy.css is too big

### ISSUE THREAD

**Issue by narendra087** [buefy/buefy#3232]
Hi
I have a project that uses buefy, but after I checked using the analyzer, I found out that buefy.css is too big.
Here is a screenshot

<img width="1440" alt="Screen Shot 2021-03-14 at 18 47 02" src="https://user-images.githubusercontent.com/19150149/111067238-f8259a80-84f5-11eb-9006-964d5938cad5.png">

Does anyone have the same problem? and how to reduce the size of that bundle?

**Comment by mmorainville** [comment]
I have the same issue, I'm just using Tabs and some other small components.
The cherry-picking for the JS part works fine, but we have to add all of Bulma's CSS in order for those components to work correctly.
It would be nice to have a way to cherry-pick CSS styles too.

The approach of https://github.com/oruga-ui/oruga is interesting in this manner, but it doesn't seem as mature as Buefy (although it seems to be a fork).
