### ISSUE TITLE
Why this sidebar still have class is-active when i move to another menu?

### ISSUE THREAD

**Issue by yvza** [buefy/buefy#3234]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: Windows 10 / Sidekick 88.8.43.7641 (Official Build)(64-bit)

### Description

Why this sidebar still have class is-active when i move to another menu?

### Steps to reproduce

Vue CLI fresh project with router already configured.
so i plan to use sidebar from buefy. everything is normal
but when i put menu into `<router-link>` class not work as i accepted

my code:
```
...
<b-menu-item icon="users-cog" label="Administrator">
  <router-link to="/admin/master-sasaran-organisasi">
    <b-menu-item icon="book" label="Master Sasaran Organisasi"></b-menu-item>
  </router-link>
  <router-link to="/admin/master-kegiatan">
    <b-menu-item icon="tasks" label="Master Kegiatan"></b-menu-item>
  </router-link>
  <router-link to="/admin/master-periode">
    <b-menu-item icon="calendar-day" label="Master Periode"></b-menu-item>
  </router-link>
</b-menu-item>
...
```

gif:
![sidebar](https://user-images.githubusercontent.com/25668079/111265972-769c4c80-865c-11eb-8ace-44da680ca1ca.gif)

### Expected behavior

menu has only one active class when i click on selected menu

### Actual behavior

every menu has is-active class and not removed after i move to another menu

**Comment by febrihidayan** [comment]
Kelihatannya itu terjadi disebabkan kesalahan konfigurasi komponen di Buefy, seharusnya Anda dapat melakukannya seperti ini
```js
<b-menu-item icon="users-cog" label="Administrator">
    <b-menu-item tag="router-link" to="/admin/master-sasaran-organisasi" icon="book" label="Master Sasaran Organisasi"/>
    ...
</b-menu-item>
```

**Comment by consciousnessdev** [comment]
> Kelihatannya itu terjadi disebabkan kesalahan konfigurasi komponen di Buefy, seharusnya Anda dapat melakukannya seperti ini
> 
> ```js
> <b-menu-item icon="users-cog" label="Administrator">
>     <b-menu-item tag="router-link" to="/admin/master-sasaran-organisasi" icon="book" label="Master Sasaran Organisasi"/>
>     ...
> </b-menu-item>
> ```

in english please...
pake bahasa inggris bro :sweat_smile:

**Comment by AniaKru95** [comment]
I have the same issue. Please fix this.
