### ISSUE TITLE
Snackbar with cancel has no cancel button

### ISSUE THREAD

**Issue by CodeSpent** [buefy/buefy#3239]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.11
**OS/Browser**: Firefox/Chrome on Mac OS Big Sur

### Description

When using the Snackbar with Cancel Button example from Buefy docs, the Snackbar that appears solely has an 'Ok' button, unlike the Snackbar that shows in the example.

Here is a [CodeSandbox](https://codesandbox.io/s/buefycancelsnackbarissue-tz2kz) with a reproduction of the issue.
https://codesandbox.io/s/buefycancelsnackbarissue-tz2kz

The code used is exactly copied from the [documentation](https://buefy.org/documentation/snackbar) as follows;

```javascript
this.$buefy.snackbar.open({
      indefinite: true,
      message: "Snackbar with a cancel button.",
      cancelText: "Cancel",
    });
```

### Steps to reproduce

1. Create a Vue application
2. Install Buefy & register on Vue instance
3. Open a Snackbar with provided `cancelText` property

### Expected behavior

A Snackbar will open with an "Ok" and "Cancel" button as demonstrated in the example in documentation.

### Actual behavior

A Snackbar opens with only an "Ok" button, but no "Cancel" button.

A CodePen reproduction using the template provided as well: https://codepen.io/AutonomousHC/pen/wvobyqv

**Comment by CodeSpent** [comment]
Looks like this was added in https://github.com/buefy/buefy/commit/f38adc26e4cf81a79d0d23f8f90989fc9b83c036 but hasn't yet been released.

**Comment by service-paradis** [comment]
As @CodeSpent said, it should works in the next release.
I cannot tell if @jtommy planned to make a new release soon.
