### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by jonorozcoc** [buefy/buefy#3243]
### Description

Instead of showing one single notification we should show the entire queue of notifications

![image](https://user-images.githubusercontent.com/8442497/111915814-159ebb00-8a46-11eb-95a5-c135e74c4314.png)

### Why Buefy need this feature

If we have many notifications and every one has a duration of 5 seconds (for example) we have to wait to know about the next notifications but with this we can have instant feedback

**Comment by jtommy** [comment]
You can do it setting `queue` to false
