### ISSUE TITLE
Attached tag has extra closing </a> tag inside closing part

### ISSUE THREAD

**Issue by miroslavgeorgiev** [buefy/buefy#3247]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: MacOS Catalina

### Description
Attached tag has an extra closing </a> tag inside closing part that is leading to incorrect DOM (we have `a` tag inside `a` tag)

### Steps to reproduce
You can check it in the [documentation](https://buefy.org/documentation/tag/#tag-list) (inspect the code in the "is-delete" part) and in the [source code](https://github.com/buefy/buefy/blob/dev/src/components/tag/Tag.vue#L30)

### Expected behavior

To have just one closing `a` tag

### Actual behavior
This bug is causing incorrect DOM (we have an extra `a` tag inside `a` tag)

**Comment by service-paradis** [comment]
Good catch! I will make a PR for this soon!

**Comment by miroslavgeorgiev** [comment]
Thanks @service-paradis 👍 
The PR looks good to me 😆
