### ISSUE TITLE
in the datepicker, the arrows should be around the month only

### ISSUE THREAD

**Issue by bikepunk** [buefy/buefy#3254]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**: firexox 78.9.0esr (64-bit) on Debian

@tcitworld most probably knows 

### Description

In the datepicker, the left/right arrows are affecting the month only. IMHO they should be around the month only, 
![](https://framagit.org/framasoft/mobilizon/uploads/5336414ceff7d431670b84f1b9d38c4a/Screenshot_from_2021-03-27_17-30-38.png)

discussed there : https://framagit.org/framasoft/mobilizon/-/issues/650

### Expected behavior

I mean, since the arrow change only the month, the current
<- / Month / year / ->
would make more sense displayed like
<- / Month /  -> / year /

**Comment by jtommy** [comment]
@bikepunk I don't think there is an absolute truth about it, there are a lot of ui libraries or datepicker lib with the same UX.
Anyway you can override it using `header` slot, https://buefy.org/documentation/datepicker#header

**Comment by von-maurus** [comment]
> @bikepunk I don't think there is an absolute truth about it, there are a lot of ui libraries or datepicker lib with the same UX. Anyway you can override it using `header` slot, https://buefy.org/documentation/datepicker#header

Hey can you help on showing the prev/next buttons for month selection when you override with header slot?
I don't know how to do it
