### ISSUE TITLE
Date picker modal opens on value change

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#3255]
### Overview of the problem

**Buefy** version: 0.9.5
**Vuejs** version: 2.6.12
**OS/Browser**: Chrom* 91

### Description

Changing the `value` of `BDatepicker` causes the modal to open.

### Steps to reproduce

[Minimal working example](https://codepen.io/tecaz/pen/bGgwXLa)

**Comment by vlazar** [comment]
@jtommy Any inside when is the next release? We've updated to 0.9.5 to fix an issue we had for a while, but now all pickers are opened on initial page load.
