### ISSUE TITLE
Tab Content / Tabpanel automatic focus / not respecting variables

### ISSUE THREAD

**Issue by robertmarney** [buefy/buefy#3258]
### Overview of the problem

**Buefy** version: 0.9.5
**Vuejs** version: 2.6.12
**OS/Browser**: Windows 10: Brave, Chrome

### Description

With Buefy 0.9.5 the tab-item is receiving a thick border on focus automatically. 

The border color does not respect the default 'none' value provided by the **_$tabs-focused-outline_** Variable, setting the variable has no effect.

**Work Around**

Add the following to your app.scss after import to remove focus outline:

```css
.tab-item:focus {
    outline: none;
}
[role=tabpanel]:focus { 
    outline: none; 
}
```

### Steps to reproduce

Create b-tab with b-tab-item and some content.
Click on content.

### Expected behavior

1. Maintain the default behavior Or 
2. Allow the user to opt-in or out of outline on the component.

### Actual behavior

https://codepen.io/RMCodes/pen/RwKKREO

**Comment by dyerjos** [comment]
I'm not sure if you are tracking this or if it's actually a bug but I'm on Buefy 0.9.10 and I still saw  tab-item is receiving a thick border on focus. My workaround was to add the code in the third image to my app.scss file.

![Screen Shot 2021-09-16 at 3 33 27 PM](https://user-images.githubusercontent.com/51426088/133682150-6d312247-5bd1-4e47-af42-893679095d95.png)
![Screen Shot 2021-09-16 at 3 33 55 PM](https://user-images.githubusercontent.com/51426088/133682154-70ce3d42-a90b-4686-a0df-ebbb7812b845.png)
![Screen Shot 2021-09-16 at 3 34 11 PM](https://user-images.githubusercontent.com/51426088/133682156-0f794fb2-e40b-4795-a363-81c39551df52.png)
