### ISSUE TITLE
Wrong mention in last release note

### ISSUE THREAD

**Issue by WTDuck** [buefy/buefy#3259]
Hi !
Just to let you know that there is a wrong mention in the 0.9.5 release note

- `Fix #3135: multiple fixed Navbar on the same page (thanks @fabiofdsantos)`

Not that I really care but this PR was actually mine 😅 

Anyway thanks for this update !

**Comment by service-paradis** [comment]
Sorry for this 😃 
Should be fixed now (https://github.com/buefy/buefy/commit/f846a6cf55de901895507bf38ef6ff371a3e4eda) Thank you for your work 🎉
