### ISSUE TITLE
Datepicker component is hidden when clicked

### ISSUE THREAD

**Issue by urielgi** [buefy/buefy#3261]
### Datepicker component is hidden when clicked

**Buefy** version: [0.9.5]
**Vuejs** version: [2.6.12]
**OS/Browser**: Windows 10 Pro 20H2 / Chrome 89.0.4389.114 and Firefox Developer 88.0b4

### Description
When clicking on the datepicker component, it hides / disappears and when clicking on the number of the day of the date, the modal does not close. 

![Datapicker](https://user-images.githubusercontent.com/67696586/113346031-27a31800-92e8-11eb-8c44-e3d1235afc74.gif)

By the way, when reviewing the HTML code, I noticed that it adds a style to the component, a z-index 

![carbon](https://user-images.githubusercontent.com/67696586/113347058-7a310400-92e9-11eb-9791-403ef4db9e7f.png)

Thank you in advance. 
Note: Sorry for my bad English

**Comment by service-paradis** [comment]
I reverted the change that created this issue in #3257. Should be fixed soon!
The workaround for now is to apply this:
```scss
.datepicker {
  z-index: 1 !important;
}
```

**Comment by urielgi** [comment]
Is there a way to fix not closing the modal when selecting the date?

Thank you very much.
