### ISSUE TITLE
First option in autocomplete is always selected when pre-filling available options

### ISSUE THREAD

**Issue by emielmolenaar** [buefy/buefy#3262]
### Overview of the problem

**Buefy** version: 0.9.5
**Vuejs** version: 2
**OS/Browser**: Independent

### Description

See https://codepen.io/emielmolenaar/pen/QWdpBJW .

First option in autocomplete is always selected when pre-filling available options. I use a tag input with the autocomplete feature and a pre-filled set of options to choose from. Since Buefy 0.9.5, the first option is always selected (even if you do not select any option form the autocomplete dropdown).

### Steps to reproduce

See https://codepen.io/emielmolenaar/pen/QWdpBJW . Try to remove the options, or to add no option at all.

### Expected behavior

When I don't click / select an option, the dropdown should just close and not append any option to the list.

### Actual behavior

The first option is always appended to the list.

I think this is caused by the change "Automatically select hovered option on blur for Autocomplete (thanks @fabiofdsantos)", or am I doing something wrong?

**Comment by fabiofdsantos** [comment]
Here's the issue:
https://github.com/buefy/buefy/blob/f846a6cf55de901895507bf38ef6ff371a3e4eda/src/components/taginput/Taginput.vue#L47

**Comment by emielmolenaar** [comment]
Thanks!

**Comment by Thaurin** [comment]
If I *want* the first option from autocomplete to be pre-selected, how do I achieve that now? Before, users could start typing and press enter, now they have to select it. I would like the old behavior back.

**Comment by Thaurin** [comment]
I've gone back to Buefy v0.9.5 for now, which fixes my issue. Would still like a solution.

**Comment by fabiofdsantos** [comment]
@jtommy Should we add a `keep-first` property to TagInput?

**Comment by Thaurin** [comment]
This probably has to do with `:append-to-body="true"` on the `tag-input`, I think. I kinda misunderstood the issue here, I had to switch to `:append-to-body="true"` and now the first item will *always* be added, even if I want to cancel by e.g. clicking outside of the suggestion box.

I'd still like to be able to add the first option by pressing enter, but for now I'll upgrade to 0.9.7 to make this usable again.
