### ISSUE TITLE
Clear autocomplete on invalid value after blur

### ISSUE THREAD

**Issue by andresespinosapc** [buefy/buefy#3263]
### Description

Actually, there is no way of clearing the input when it is invalid, because the blur event triggers before the select event. It would be nice to have a `close-on-blur` property that clears the input on blur if it's not a valid selectable option. Other possibility would be to adjust the events so it is possible to implement it myself, because I haven't figured out a workaround.

### Why Buefy need this feature

I think it's a pretty common use case that users can only select options that are on the dropdown. I think it's a poor UX that the text keeps showing after blurring the input if it's invalid, because the user can think it is valid.

**Comment by mattiapv** [comment]
If it's not a valid option it shouldn't be in the dropdown. If the user type a not valid option you can check it with blur event if it's valid, if is not valid you clear the autocomplete.

```vue
<b-autocomplete
    rounded
    v-model="name"
    :data="filteredDataArray"
    placeholder="e.g. jQuery"
    icon="magnify"
    clearable
    @select="option => selected = option"
    @blur="checkValid">
    <template #empty>No results found</template>
</b-autocomplete>
```

```javascript
methods: {
    checkValid() {
      var valid = false;
      this.data.forEach((element) => {
        if (element.toLowerCase() == this.name.toLowerCase()) valid = true;
      });
      if (!valid) this.name = ''; // clear autocomplete
    }
}
```

**Comment by jtommy** [comment]
@andresespinosapc i agree with @mattiapv
