### ISSUE TITLE
Timepicker- values are not consistent

### ISSUE THREAD

**Issue by hoiyitse** [buefy/buefy#3266]
### Overview of the problem

**Buefy v0.9.5
**Vue.js v2.6.12
**OS/Browser** Version 89.0.4389.82 

### Description

Time chosen and time shown are not the same for hour. 

### Steps to reproduce

<img width="643" alt="Screenshot 2021-04-05 at 12 16 20 AM" src="https://user-images.githubusercontent.com/72726753/113514960-2998ff80-95a4-11eb-9c85-28dc39bad816.png">
1. Go to https://buefy.org/documentation/timepicker/
2. Select time (hour and minute)

**Comment by service-paradis** [comment]
Fixed with #3257
Will be available in the next release.
