### ISSUE TITLE
Make Datepicker right icon clickable

### ISSUE THREAD

**Issue by rsacksteder** [buefy/buefy#3270]
### Description
Though not documented in the [Datepicker API](https://buefy.org/documentation/datepicker/#api-view) (perhaps it should be), Buefy 0.9.5 (and likely earlier versions) supports an `icon-right` prop, similar to that of the Input component. The Input component builds upon this further, by making the right icon clickable via the `icon-right-clickable` prop and allowing event handling with the `icon-right-click` event (added per https://github.com/buefy/buefy/issues/676). It would be nice if the right icon on the Datepicker could also be clickable with a custom event handler.

### Why Buefy Needs This Feature
One potential use case for this feature is the ability to clear the associated data from the component. The Input component does this today with the presence of a clear/reset icon that can be used together with a click handler. See an example at https://buefy.org/documentation/input#icons.

![image](https://user-images.githubusercontent.com/2262431/113943240-190ca300-97b7-11eb-9a94-fd94f8675e9a.png)

Within a group of form fields, an Input and standard Datepicker (with its own nested Input) can appear very similar. A user may reasonably expect to clear these fields the same way. It would be nice to provide a simple and consistent method of doing this for the end user, and one way to accomplish this would be to make the right icon clickable for the Datepicker component.

The image below illustrates the desired visual interface for two standard Inputs components and one Datepicker component.
![image](https://user-images.githubusercontent.com/2262431/113943556-d1d2e200-97b7-11eb-8df2-70017706a009.png)

While the Input component allows me to hook up an on-click listener to the right icon, I can't do this with the Datepicker component, thus I am unable to use the same interface and would need to resort to a separate interface for clearing the Datepicker data (such as is done at https://buefy.org/documentation/datepicker/#footer).

**Comment by geeksilva97** [comment]
It seems that this feature was already implemented 

https://buefy.org/documentation/datepicker

**Comment by luixal** [comment]
Hi,

The icon-right-clickable is not working for me. I'm setting it this way:

```html
<b-field label="">
    <b-datepicker
        v-model="filterDates"
        :first-day-of-week="1"
        range
        icon="calendar-today"
        icon-right="close-circle-outline"
        icon-right-clickable
        @icon-right-click="clearDates"
    >
    </b-datepicker>
</b-field>
```

I got the element rendered and works nice, but the button doesn't seem to get focus or something. Thing is, when you try to click the button, the calendar gets displayed, but the `icon-rigth-clik` doesn't get fired.

Weird thing: [the first example in the docs](https://buefy.org/documentation/datepicker/) showcases the right icon and it works but, I've just copy/pasted it and it doesn't seem to work in my project (I'm using Nuxt.js).

Any ideas?

**Comment by rsacksteder** [comment]
It's nice to see that this added as a new feature in buefy 0.9.9: https://github.com/buefy/buefy/blob/dev/CHANGELOG.md#099

I would agree with @luixal in saying that I don't necessarily want the datepicker to open up when clearing the input. Say I am using the datepicker as part of a series of search filters. Let's say I have a date or date range selected but wanted to clear that filter without specifying another date. This is one example where the current behavior is not ideal where clicking the right icon results in the datepicker opening.

**Comment by agersea** [comment]
The example doesn't work in Nuxt for me either.  I had to punt and go with a button addon.
