### ISSUE TITLE
b-tab-items not combining classes with class props

### ISSUE THREAD

**Issue by Minhyme** [buefy/buefy#3272]
### Overview of the problem

**Buefy** version: [0.9.6]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chrome, Edge

### Description

class props passed to b-tab-item overwrite the 'tab-item' class instead of being combined in the same way other components combine the props. Due to this class being missing, the behavior as seen in #3258 is still exhibited when a custom class is added to the b-tab-item.

### Steps to reproduce
See code pen:
https://codepen.io/minhyme/pen/YzNEVza

Inspect button class and see combined `class="button custom-button-class"`
Inspect tab item and see `class="custom-tab-item-class"`
Notice other b-tab-items have the `class="tab-item"`

### Expected behavior
Similar behavior to other components where the custom classes as combined with the default classes instead of overwriting the defaults.

### Actual behavior
Custom classes overwrite the default classes.

### Bandaid
For anyone experiencing this, it is easy to include the tab-item class in your custom class to revert back to the previous behavior. However, with respect to the behavior of other buefy components this is not expected and was not happening prior to 0.9.5.

**Comment by glumb** [comment]
The issue still persists in Buefy V9.22

**Comment by jtommy** [comment]
@glumb just fixed!
