### ISSUE TITLE
b-autocomplete: clear-on-select dispatches select event after having been cleared

### ISSUE THREAD

**Issue by QuentinGab** [buefy/buefy#3277]
### Overview of the problem

**Buefy** version: 0.9.6
**Vuejs** version: 2.6.12
**OS/Browser**:

### Description

The `clear-on-select` prop dispatches `select` event with null option.

I don't know if it's intentional, but that means that after a option is selected (and an event  is dispatched), a new `select`event with null is immediatly dispatched. Not optimal in my opnion

It is mainly because of this watcher:
```js
newValue(value) {
    this.$emit('input', value)
    // Check if selected is invalid
    const currentValue = this.getValue(this.selected)
    if (currentValue && currentValue !== value) {
        this.setSelected(null, false)
    }
    // Close dropdown if input is clear or else open it
    if (this.hasFocus && (!this.openOnFocus || value)) {
        this.isActive = !!value
    }
},
```
### Steps to reproduce

HERE: [Codepen](https://codepen.io/CRAKERSS/pen/BapxZgB)

### Expected behavior

b-autocomplete should not dispatch `select` after cleaning the selected value when `clear-on-select`is set to true.

**Comment by jtommy** [comment]
And how do you notify the clear selection?

**Comment by berry807** [comment]
@jtommy the latest release 0.9.10 breaks the clear on select function

**Comment by jtommy** [comment]
@berry807 can you reproduce it?
