### ISSUE TITLE
Numberinput Disable Fails

### ISSUE THREAD

**Issue by komodooo** [buefy/buefy#3280]
Numberinput + and - buttons still work even if disabled.

**Buefy** version: [0.9.6]
**Vuejs** version: [2.6.11]
**OS/Browser**: macOS High Sierra 10.13.6, Chrome Version 89.0.4389.114

The numberinput buttons should be disabled when the numberinput is set to disabled. v-model variable can still be changed even if the numberinput is disabled. 

1. Go to the buefy documentation https://buefy.org/documentation/numberinput and press + or - where the disabled numberinput is.

Buttons should be disabled and the user is not able to change the variable.

**Comment by jtommy** [comment]
You might hide controls using `:controls="false"`

**Comment by komodooo** [comment]
I guess that does solve it. Thanks for the hint!

**Comment by service-paradis** [comment]
> You might hide controls using `:controls="false"`

Good workaround for now, but I tend to agree that a disabled component should be disabled 😅

**Comment by jtommy** [comment]
I remember a discussion about it and we decided to show the controls

**Comment by service-paradis** [comment]
I agree to keep the controls, but I think they should also be disabled, no?

**Comment by jtommy** [comment]
Yes, probably you are right
