### ISSUE TITLE
Numberinput variable jumps to minimum value when negative

### ISSUE THREAD

**Issue by komodooo** [buefy/buefy#3281]
Numberinput variable jumps to minimum value when negative value is entered or if value is deleted via keyboard.

**Buefy** version: [0.9.6]
**Vuejs** version: [2.6.11]
**OS/Browser**: macOS High Sierra 10.13.6, Chrome Version 89.0.4389.114

If you choose a negative value for the minimum number of the numberinput, the value will jump to said value immediately on attempt to enter a negative number by keyboard staring with a minus (-)

1. Have this code
        <b-field label="Number">
            <b-numberinput min="-10" max="10">
            </b-numberinput>
        </b-field>

2. Select the field and try to enter a negative number (starting with -)
3.  The value of the field jumps to -10 immediately
4. If you try to remove the number by using backspace the value will jump back again to the min value once the minus is reached.

The value should not jump or change while entering a number.

**Comment by matt3188** [comment]
I'm having the same issue when deleting. It only seems to be an issue when the min/max value is a double figure for me.
