### ISSUE TITLE
Buefy Carousel List Fallback image

### ISSUE THREAD

**Issue by ZombieChibiXD** [buefy/buefy#3282]
### Description

Add an option to pass a prop of src_fallback to b-carousel-list.

### Why Buefy need this feature

Because it's an image, and if an image don't load for some reason, e.g. deleted from a server, or bad connection, there should be an option to show a fallback image when desired.

**Comment by service-paradis** [comment]
Thank you @ZombieChibiXD for your request.
Maybe we could use `b-image` inside `b-carousel-list` instead of a simple `img` tag.
We could bring `b-image` features to this component.

I will try to take a look at this soon!

**Comment by ZombieChibiXD** [comment]
@service-paradis @jtommy if I may give suggestion, why not give the option to modify the b-carousel-list template?

Like

```
<b-carousel 
 ...>
    <template #item=props>
            <b-image :src="props.image" :alt="props.alt" :title="props.title" :src-fallback="somevar" />
    </template>
</b-carousel-list>
```

Or is it a bad idea?
