### ISSUE TITLE
这个UI是我用过最差劲的一个vue UI

### ISSUE THREAD

**Issue by z790490122** [buefy/buefy#3283]
如标题所言:
如果不是甲方指定这个UI,我绝对不会用该UI.
我就列举一下我在使用中,很鸡肋的问题.
**如果你看不懂中文,去找个可以看懂中文的,请您好好深思我提的问题.**

**问题1.** 为什么表格组件,要区分前端数据和后台数据.这个简直不要太疯狂,两个写法完全不一样.
**问题1.** 为什么表格组件,要区分前端数据和后台数据.这个简直不要太疯狂,两个写法完全不一样.
**问题1.** 为什么表格组件,要区分前端数据和后台数据.这个简直不要太疯狂,两个写法完全不一样.
**### 重要的事要说三遍**

**问题2.** UI安全性非常差.几乎所有的组件自动解析html, 比如使用Toast组件,mesaage是<bbbbbbbbb,文字怎么也看不见
**问题2.** UI安全性非常差.几乎所有的组件自动解析html, 比如使用Toast组件,mesaage是<bbbbbbbbb,文字怎么也看不见
**问题2.** UI安全性非常差.几乎所有的组件自动解析html, 比如使用Toast组件,mesaage是<bbbbbbbbb,文字怎么也看不见
**### 重要的事要说三遍**

**问题3** 分页组件,可以输入跳转page都没有.

**Comment by alanyong91** [comment]
绝对赞同！！！哈哈哈哈哈哈哈哈
