### ISSUE TITLE
Datepicker day labels are wrong

### ISSUE THREAD

**Issue by deto1986** [buefy/buefy#3293]
### Overview of the problem

**Buefy** version: since 0.9.5
**Vuejs** version: 2.6.12
**OS/Browser**: Windows, Chrome v89.x, de-DE locale

### Description

The datepicket displays the labels for the days in die calender wrong. Today (20th April 2021) is displayed as Wednesday. If I change the first-day-of-week attribute from 0 to 1 (Monday, which is the real first day of week in Germany) the calender displays for the 20th April 2021 Monday as day which is also wrong.

### Steps to reproduce

Open datepicker example in documentation at buefy.org.

I attached screenshots of my browser. This happens in all browsers (Firefox ESR, MS Edge Chromium)

### Expected behavior

The day labels displayed correctly ;-)

The letters on the first screenshot have to be from left to right:

- M = Montag / Monday
- D = Dienstag / Tuesday
- M = Mittwoch / Wednesday
- D = Donnerstag / Thursday
- F = Freitag / Friday
- S = Samstag / Saturday
- S = Sonntag / Sunday

### Actual behavior

Each example in documentation on buefy.org are wrong, you can verify that there via the CodePen examples.

![2021-04-20 10_08_47-Datepicker _ Buefy](https://user-images.githubusercontent.com/3199863/115361100-89a4be00-a1c0-11eb-9028-68aa219a0c94.png)

![2021-04-20 10_08_34-Datepicker _ Buefy](https://user-images.githubusercontent.com/3199863/115361102-8a3d5480-a1c0-11eb-827e-097c39b5144f.png)

**Comment by deto1986** [comment]
Additional info, the error happens also with version 0.9.5. In version 0.9.4 it's correct.

**Comment by jtommy** [comment]
Already fixed https://github.com/buefy/buefy/pull/3289. Soon in the new release
