### ISSUE TITLE
 this.$buefy.* returns vm.extend is not a function

### ISSUE THREAD

**Issue by rsoares88** [buefy/buefy#3295]
### Overview of the problem

Cant use any $buefy method
All components work fine, just this.$buefy.* returns vm.extend is not a function.

**Buefy** version: [0.9.7]
**Vuejs** version: [0.9.2]

"cross-env": "^7.0.3",
"laravel-mix": "^6.0.18",
"postcss": "^8.2.10",
"resolve-url-loader": "^3.1.2",
"sass": "^1.32.11",
"sass-loader": "^11.0.1",
"vue-loader": "^15.9.6",
"vue-template-compiler": "^2.6.12",
"webpack": "^5.35.0",
"webpack-cli": "^4.6.0"

**OS/Browser**:
WIN 10 / Brave

### Description
All $buefy methods return vm.extend is not a function.
I tried to add single component but it gives an error for webpack:
buefy__WEBPACK_IMPORTED_MODULE_22__.default.alert is not a function

and this is the line where the error occours ni vendor.js:
    var vm = typeof window !== 'undefined' && window.Vue ? window.Vue : localVueInstance || _chunk_953eb524_js__WEBPACK_IMPORTED_MODULE_3__.V;
    var NotificationNoticeComponent = vm.extend(NotificationNotice);
    
### Steps to reproduce

Since it works on codepen i assume its an webpack compatibility issue ??

app.js 
import Buefy from 'buefy'
Vue.use(Buefy, { defaultIconPack: 'fas' });

main.vue
mounted() {
this.$buefy.dialog.alert('Hello World!');
}

### Expected behavior
To be able to use $buefy methods

### Actual behavior
Returns an vm.extend error when called

**Comment by jtommy** [comment]
Try removing Buefy from node_modules e reinstall it.
Something it happens

**Comment by rsoares88** [comment]
i did, error still persist, is buefy tested with "webpack": "^5.35.0", "webpack-cli": "^4.6.0" ???

**Comment by alikseva** [comment]
Hi. I have same problem. Any news ?

**Comment by alikseva** [comment]
> i did, error still persist, is buefy tested with "webpack": "^5.35.0", "webpack-cli": "^4.6.0" ???

Hi  rsoares88.
Have you solved this problem ?
