### ISSUE TITLE
Tooltip is partially hidden when inside Tab's custom header

### ISSUE THREAD

**Issue by rogeriotaques** [buefy/buefy#3301]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 0.9.2
**OS/Browser**: macOS/ Chrome Latest

### Description

When using the `b-tooltip` inside a `b-tab-item` ( custom `header` slot) the tooltip shows cut because of the `overflow` rule.

### Expected behavior

The tooltip is fully shown.

### Actual behavior

The tooltip is partially shown.

**Comment by jtommy** [comment]
Try using append-to-body prop

**Comment by rogeriotaques** [comment]
Thanks for the quick reply, @jtommy!

Using `append-to-body` does the job. Thanks. 

However, it looks like it's not documented on the [Docs](https://buefy.org/documentation/tooltip)! Can it be updated?

**Comment by rogeriotaques** [comment]
Closing this, since it's not actually a bug. 🙇‍♂️
