### ISSUE TITLE
Label position on-border/inside is rendered at the wrong position

### ISSUE THREAD

**Issue by Tharabas** [buefy/buefy#3304]
### Overview of the problem

**Buefy** version: [0.9.7]
**Vuejs** version: [2.6.12]
**OS/Browser**: MacOS 10.14.6, confirmed with Chrome 90, Firefox 87+1, Safari 14

### Description

When using a `b-field` with a label positioned `on-border` or `inside` on a `b-numberinput` with `controls-alignment` being `left` or `right`, the label is at the wrong position.

### Steps to reproduce

1. Create a `b-field` with a `label` and `label-position="on-border"`
2. Insert a `b-numberinput` with `controls-alignment="right"`

Result should look like this:

```html
<section class="my-form">
  <b-field label="Input for Reference" label-position="on-border">
    <b-input v-model="something" />
  </b-field>
  <b-field label="This should be left" label-position="on-border">
    <b-numberinput v-model="someNum" controls-alignment="right" />
  </b-field>
</section>
```

### Expected behavior

The on-border label should align with other on-border labels within the same form.

### Actual behavior

The label stays at the same position it had as with default `controls-alignment`:

![strange-indentation](https://user-images.githubusercontent.com/297185/116139606-7c169900-a6d6-11eb-9a8e-bdf4d78c1932.png)

See https://codepen.io/Tharabas/pen/wvgOpRq

### Workaround

Currently, at least for `on-border`, you can simply wrap the `b-numberinput` inside another `b-field` to get the expected behaviour, but It would be nice not having to do this.

---

Thanks for reading

**Comment by rogeriotaques** [comment]
👍

**Comment by rogeriotaques** [comment]
It has been almost a year already since this issue was reported. Any progress?

**Comment by rogeriotaques** [comment]
Hi, there! Has this issue been fixed?

**Comment by Tharabas** [comment]
Nope, still open, and now I doubt it will be fixed.

**Comment by rogeriotaques** [comment]
> Nope, still open, and now I doubt it will be fixed.

Why? I guess I'm missing something! 😐
