### ISSUE TITLE
Rowspan from td-attrs pushes cells outside of the b-table

### ISSUE THREAD

**Issue by ccmetz** [buefy/buefy#3306]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 2.6.12
**OS/Browser**: Alpine Linux (docker container) / Chrome

### Description

When using `td-attrs` to set the `rowspan` on a `b-table-column` component, the cells in the row underneath are pushed one column to the right.

### Steps to reproduce
1. Create a 2 column table using `b-table` and `b-table-column`
2. Use `td-attrs` on the first `b-table-column` and give the first cell a `rowspan` of 2

It's a little tough to explain so please see the example here: https://codepen.io/ccmetz/pen/YzNMqGW

### Expected behavior

I expected the cell in the second row of the first column to be hidden and for the rest of the table to maintain its format.

### Actual behavior

The second row is being pushed to the right and pushes the cell in the second column outside of the table

**Comment by jtommy** [comment]
I don't think it's possible to implement rowspan at the moment and in that's way

**Comment by ccmetz** [comment]
@jtommy That's understandable. I actually just realized that `rowspan` in a plain html table works the same way. A little unintuitive IMO but I was able to get around it by adding the `class` prop to the object returned by `td-attrs` and ensure that we are hiding the cell directly beneath the one being row-spanned.

**Comment by jtommy** [comment]
@jtommy we can discuss if you have a proposal to reach it
