### ISSUE TITLE
Horizontal field styling issue

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#3309]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 2.6.12
**OS/Browser**: any

### Description

Horizontal fields and addons don't seem to play well with each other.

### Steps to reproduce

[https://codepen.io/tecaz/pen/MWJdopg](https://codepen.io/tecaz/pen/MWJdopg)

The addon on the horizontal field is stylistically different from the one on the vertical field.

Wrapping field and control inside an inner `.field.has-addons` element (like [Bulma](https://bulma.io/documentation/form/general/#horizontal-form) does) seems to solve the problem.

**Comment by dlamblin** [comment]
Additional styling concerns with `is-horizontal`:
The validation message also doesn't seem to be able to be put inside a field-body.
and I'm getting right-alignment for some reason when trying to modify the first example on: https://buefy.org/documentation/input

```html
<div id="app" class="container">
    
    <section>
        <b-field label="Name"
                 class="is-horizontal"
                 custom-class="field-label">
            <b-input class="field-body" v-model="name"></b-input>
        </b-field>

        <b-field label="Email"
            class="is-horizontal"
            custom-class="field-label"
            type="is-danger"
            message="This email is invalid">
            <b-input type="email"
                class="field-body"
                value="john@"
                maxlength="30">
            </b-input>
        </b-field>

        <b-field label="Username"
            type="is-success"
            message="This username is available">
            <b-input value="johnsilver" maxlength="30"></b-input>
        </b-field>

        <b-field label="Password">
            <b-input type="password"
                value="iwantmytreasure"
                password-reveal>
            </b-input>
        </b-field>

        <b-field label="Message">
            <b-input maxlength="200" type="textarea"></b-input>
        </b-field>
    </section>

</div>
```
