### ISSUE TITLE
b-table sort-multiple & default-sort doesn't work

### ISSUE THREAD

**Issue by photogsy** [buefy/buefy#3311]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 2.6.12
**OS/Browser**: Chrome latest

### Description

I have a table with multiple columns. Data is all client-side sorted & paged. I added `sort-multiple` and `default-sort` to the table.
Clicking the headers works as expected, but when the page loads, the table is not sorted according to the specified default sort.

**Comment by fahdaddi** [comment]
I have the same issue, @photogsy did you find a solution?

**Comment by photogsy** [comment]
> I have the same issue, @photogsy did you find a solution?

I worked around the issue by saving the user's sort preferences in local storage and then restoring them after the table loads. It works well and it's actually a better ux than just setting a default sort.
