### ISSUE TITLE
Autocomplete with append-to-body do not stack well on z-index

### ISSUE THREAD

**Issue by elmatou** [buefy/buefy#3312]
While composing an UI which lake use of z-index (leafletjs map based) I do have some issue when I use append-to-body props on autocomplete.

append-to-body set the z-index on the element to an arbitrary 99, which is not enough for me. But as the z-index is set on the element :

 #https://github.com/buefy/buefy/blob/1cb7ba3937949e1a9d2246c3784fd73b8e8d169b/src/components/autocomplete/Autocomplete.vue#L563-L569

I'm not able to fine tune it with a css class.

would it be possible to have it set with a class, allowing us to tune it as we see fit ?

**Comment by fabiofdsantos** [comment]
A quick fix:
```css
.autocomplete .dropdown-menu {
    z-index: 999 !important;
}
```

**Comment by elmatou** [comment]
@fabiofdsantos I got it and it works if you do not have many `!important` declarations in the tree.
However it should be avoided because outcome is never certain with !important

**Comment by fabiofdsantos** [comment]
> However it should be avoided because outcome is never certain with !important

As a random "z-index" 😅
