### ISSUE TITLE
indefinite toast not working

### ISSUE THREAD

**Issue by knot22** [buefy/buefy#3321]
In a Vue project that was using Buefy 0.8.13 the indefinite toast was not working.  More specifically, the toast would disappear automatically after about 3 seconds.  After doing an `npm update buefy` in this project the toast behavior is still the same.  The package version is now 0.8.20.  Why is the toast not exhibiting the indefinite behavior?

Here is the .vue file containing the toast example.  It is basically the example from the docs.
[toast.zip](https://github.com/buefy/buefy/files/6427798/toast.zip)

**Comment by service-paradis** [comment]
This features is available since 0.9.5 as you can see in the [changelog](https://github.com/buefy/buefy/blob/dev/CHANGELOG.md#095)
