### ISSUE TITLE
[Question] Can you create a Carousel List with static content?

### ISSUE THREAD

**Issue by amura11** [buefy/buefy#3323]
I wanted to know if I can create a Carousel List out of a bunch of Carousel Items. For example:

```
<b-carousel-list>
	<b-carousel-item>
		<!-- Some static HTML here -->
	</b-carousel-item>
	
	<b-carousel-item>
		<!-- Some static HTML here -->
	</b-carousel-item>
	
	<b-carousel-item>
		<!-- Some static HTML here -->
	</b-carousel-item>
</b-carousel-list>
```

I want to show a static list of cards (I.E the number of cards and the content will rarely change) whose contents will be formatted a little differently from each other. I could just store raw HTML in the models but that seems a little dirty so I was hoping I could just put static HTML in the `b-carousel-list` and call it a day.

**Comment by xergic** [comment]
Yes, you absolutely can! It doesn't matter if it's costructed dynamically with `v-for` or with static content. Like [this](https://codepen.io/xergic/pen/PopwJmx).

**Comment by amura11** [comment]
@xergic thanks! That works great but is there a way to show multiple items at once with that method? I was hoping to display 3 or 4 cards at a time like [this ](https://buefy.org/documentation/carousel/#custom-with-card) example but with static content instead.

**Comment by xergic** [comment]
@amura11 Oh, sorry, I didn't notice the **list** part. I don't think it's possible without having HTML in `data`...

... or you could do a little "hack" - have some dummy `items` data and `v-if` your HTML in the template by `list.index`. [Something like this](https://codepen.io/xergic/pen/RwpNQaM). I'm not proud of this, it's stupid, but it kinda works.

**Comment by amura11** [comment]
Oh man that's pretty dirty...lol

Sounds like the best way will to just have an array of models with some raw HTML in it to use the Carousel List. Thanks!
