### ISSUE TITLE
Problem with spaces and supr in @input with B-Input component

### ISSUE THREAD

**Issue by mrtnzagustin** [buefy/buefy#3326]
### Overview of the problem

**Buefy** version: [0.9.7]
**Vuejs** version: [2.6.12]
**OS/Browser**: Linux + Chrome/Firefox

### Description

When i want to remove more than two spaces at the end of the input value (with, for example, some regex replace), the input event didn't update the value inside b-input component.

### Steps to reproduce
Add spaces at the end of the first input element https://codepen.io/mrtnzagustin/pen/ExWVaoM

### Expected behavior

To update properly the value inside component.

### Actual behavior
![image](https://user-images.githubusercontent.com/12588882/117695879-15de4b80-b197-11eb-898f-5eb2842ae456.png)

Value inside component is different than value outside component.

### Related

Maybe something to do with -> https://github.com/vuejs/vue/issues/8231?

**Comment by geeksilva97** [comment]
Investigating

**Comment by mrtnzagustin** [comment]
I see, thanks for that. Can you help me with this component? is where i real have the problem https://codesandbox.io/s/veevalidate-components-buefy-forked-465yl?file=/src/components/RefactoredForm.vue
