### ISSUE TITLE
BTable Checked State is cleared on Back navigation but the Checkbox is visually checked.

### ISSUE THREAD

**Issue by markovejnovic** [buefy/buefy#3329]
### Overview of the problem

**Buefy** version: [0.9.7]
**Vuejs** version: [2.5.17]
**OS/Browser**: Arch Linux / Chromium 90.0.4430.85 (Official Build) Arch Linux (64-bit)

### Description

In an enterprise application that I am working on I have noticed that Checkboxes on the Table component have erroneous output. Upon selecting some rows using the Checkboxes, navigating to a link and then navigating back, the Checkboxes that were previously selected keep their state, however, the `checked` state is empty.

[This article](https://stackoverflow.com/questions/299811/why-does-the-checkbox-stay-checked-when-reloading-the-page) shows the issue is not of Buefy but autocompletion.

### Steps to reproduce

1. Select a couple items.
After selecting the checkboxes:
![image](https://user-images.githubusercontent.com/15203893/118138763-fc433b00-b406-11eb-9bee-f8a8eba85f41.png)

This is as expected.

2. Visit a link on the same page and navigate back to the page with the table.

After navigating to a link and coming back to the same page, the state is cleared (`checkedRows.size === 0`), but the checkboxes remain visible.

![image](https://user-images.githubusercontent.com/15203893/118141208-678e0c80-b409-11eb-8b29-eb158977620e.png)

### Expected behavior

Either the state is updated on Back navigation or the checkboxes are not ticked (which I believe is easier to implement).

I will be making a PR implementing the latter solution.

**Comment by jtommy** [comment]
Are you using `custom-is-checked` prop ?

**Comment by markovejnovic** [comment]
Yes, I am, as so:
```js
      // ...
      :custom-is-checked="(a, b) => (a.id === b.id)"
      // ...
```

Both of my objects have id keys and they are unique. The issue seems to be one of autocompletion, as I have managed to fix it by forcing `autocomplete=off` on these checkboxes. I'll be making a PR in a couple minutes with that which might be a bit more insightful.
