### ISSUE TITLE
datepicker range does not work in iOS Safari

### ISSUE THREAD

**Issue by lukemiller** [buefy/buefy#3331]
### Overview of the problem

Datepicker will only select one date in range mode when using iOS Safari

### Description

Datepicker will only select one date in range mode when using iOS Safari

### Steps to reproduce

go to https://buefy.org/documentation/datepicker in Safari on any iOS device

### Expected behavior

should be able to select a date range

### Actual behavior

Only selects 1 date. 

![IMG_3296](https://user-images.githubusercontent.com/220137/118153816-8b366000-b3d3-11eb-9496-c5c4b69b38a9.PNG)

**Comment by jtommy** [comment]
If you need it you have to disable it by `mobile-native` prop
