### ISSUE TITLE
Buefy multiple datepicker jumps unnaturally to the latest value in the value array

### ISSUE THREAD

**Issue by mustafasezer** [buefy/buefy#3333]
### Overview of the problem

**Buefy** version: [0.9.2]
**Vuejs** version: [2.6.11]
**OS/Browser**: Ubuntu 20.04, Chrome 90.0.4430.93

### Description

The datepicker focuses in multiple selection mode to the latest value in the array. This causes unnatural jumps when values are changed. If you have multiple dates selected which are alternating between months, each time you change the latest value, you jump around the calendar. This makes it impossible to remove multiple dates next to each other, if the values in array are distributed.

### Steps to reproduce

For example

1. Select May 15, 2021.
2. Select June 15, 2021.
3. Select May 17, 2021.
4. Select June 17, 2021.
5. Select May 19, 2021.
6. Select June 19, 2021.
7. Now we want to remove all selected dates in June.
8. Remove June 19. -> calendar jumps to May. You have to change month manually to June.
9. Remove June 17. -> calendar jumps to May. You have to change month manually to June.
10. Remove June 15. -> calendar jumps to May. You have to change month manually to June.

### Expected behavior

Do not change focusedDate (which I guess controls the current month view) unless the user wants to do so (e.g. by a boolean variable to auto-jump to latest/earliest/last date)

### Actual behavior

Datepicker jumps to a different month each time you remove a date from the end of the array.

**Comment by jtommy** [comment]
You are right! Probably better maintain the current month

**Comment by mateusbw** [comment]
Hello, @mustafasezer do you want to work on it? If not, I would like to have a go on this one.

**Comment by mustafasezer** [comment]
@mateusbw Feel free to go for it ;) I am not familliar with the code
