### ISSUE TITLE
TypeError: vm.extend is not a function when using Toast

### ISSUE THREAD

**Issue by zmudzinski** [buefy/buefy#3338]
### Overview of the problem

**Buefy** version: [0.9.7]
**Vuejs** version: [2.6.12]
**OS/Browser**: Windows/chrome (Laravel App)

### Description

When using Buefy toast error occurred: 
`app.js:43843 [Vue warn]: Error in mounted hook: "TypeError: vm.extend is not a function"`

### Steps to reproduce

1. Install Vue and Buefy as it is in current docs
2. Use toast in component 
``` 
this.$buefy.toast.open({
        message: 'Something happened correctly!',
        type: 'is-success'
      })
```

### Expected behavior

Error occures

### Actual behavior

Show toast on webapp

**Comment by jtommy** [comment]
Can you reproduce on codepen or similar?

**Comment by zmudzinski** [comment]
The problem occurs in the dialog component as well.
I've created a gist with app.js, component, and package.json: https://gist.github.com/zmudzinski/6d42d0173d434d205651ddfd21975a6c
 Let me know If you need more info!

**Comment by ovsyan** [comment]
I solved this problem by downgrading the webpack version from 5 to 4

**Comment by alikseva** [comment]
HI.
I think the problem in this line:
var vm = typeof window !== 'undefined' && window.Vue ? window.Vue : localVueInstance || _chunk_652f2dad_js__WEBPACK_IMPORTED_MODULE_4__.V;

I have webpack5, i can't downgrading to 4. Has anybody any other decision ?

**Comment by alikseva** [comment]
> HI.
> I think the problem in this line:
> var vm = typeof window !== 'undefined' && window.Vue ? window.Vue : localVueInstance || _chunk_652f2dad_js__WEBPACK_IMPORTED_MODULE_4__.V;
> 
> I have webpack5, i can't downgrading to 4. Has anybody any other decision ?

I have solved this problem. 
In main entry point app.vue you can define: 
window.Vue = window.Vue.default;
