### ISSUE TITLE
iPad detection doesn't work anymore

### ISSUE THREAD

**Issue by lboecker** [buefy/buefy#3342]
Apple changed the user agent for the iPad [a while ago](https://support.google.com/analytics/answer/3223194?hl=en#user-agent) which breaks the iOS detection code in [src/utils/helpers.js](https://github.com/buefy/buefy/blob/dev/src/utils/helpers.js#L111-L116).

**Comment by jtommy** [comment]
@lboecker can you make a PR ?

**Comment by lboecker** [comment]
@jtommy I'm not sure what to do about that. Right now it seems people are testing if `navigator.platform` is "MacIntel" and if the device also supports touch. That obviously only works until Apple releases a touch-screen MacBook or something like that.

Here is one example that works like that (they all look pretty much the same): https://stackoverflow.com/a/58064481

Do you want me to add that to the iOS detection code?

**Comment by jtommy** [comment]
Sure
