### ISSUE TITLE
type attribute can't combine with is-light

### ISSUE THREAD

**Issue by ShuntaH** [buefy/buefy#3347]
## Overview of the problem
Buefy version: [0.9.4 & 0.9.7]
nuxt-buefy version: [0.3.31]
Vuejs version: [2.6.12]
Nuxtjs version: [2.15.4]
OS/Browser: Chrome89

### Description
type attribute of button and radio button components combines is-color (e.g. is-primary) with is-light, it won't work.
I tried type="is-warning-light" https://github.com/buefy/buefy/issues/2891. it also doesn't work.

Expected behavior
`<b-button type="is-warning is-light">
              Warning Light
            </b-button>`
<img width="171" alt="スクリーンショット 2021-05-27 18 37 33" src="https://user-images.githubusercontent.com/30917236/119804065-f7a87780-bf1a-11eb-9abc-3bbcc8e3ebfc.png">

Actual behavior
`<b-button type="is-warning is-light">
              Warning Light
            </b-button>`

<img width="211" alt="スクリーンショット 2021-05-27 18 41 43" src="https://user-images.githubusercontent.com/30917236/119804490-5c63d200-bf1b-11eb-952f-757e6f3533b6.png">

**Comment by service-paradis** [comment]
Working fine in the current documentation as seen at https://buefy.org/documentation/button#types-and-states
Can you reproduce the issue using Codepen or something similar?

**Comment by ShuntaH** [comment]
I think I know what caused it.
I am using Next.js in my project and installed nuxt-buefy. nuxt-buefy did not install the latest version of bulma, so I installed the latest version of buefy to use Spacing helpers in the past. It worked, so I thought there was no problem, but in fact the 0.3.31 version of nuxt-buefy was intertwined with the bulma 0.7.5 version. buefy by itself is fine.

https://codepen.io/ShuntaHosaka/pen/YzZrzea

<img width="255" alt="スクリーンショット 2021-05-28 9 49 16" src="https://user-images.githubusercontent.com/30917236/119914613-91176e00-bf9b-11eb-9d90-96e8e1871642.png">
