### ISSUE TITLE
Various Sass Deprecation Warning - When Setting Custom Themes

### ISSUE THREAD

**Issue by SomethingNew71** [buefy/buefy#3351]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 2.6.12
**OS/Browser**: N/A

### Description
With the use of the current versions of sass and importing buefy for custom theming as described in the docs various deprecation warnings are now present during application compile. According to Sass docs removal of deprecated sass functions is required to resolve. (which I believe will require Buefy to update their Sass version too).

Details about breaking change - https://sass-lang.com/documentation/breaking-changes/slash-div

### Steps to reproduce
1. Import vuefy styles as follows:
<img width="766" alt="Screen Shot 2021-05-28 at 4 09 57 PM" src="https://user-images.githubusercontent.com/4572799/120037267-59c2b480-bfcf-11eb-83dc-d4407230a9fe.png">

2. Build application

### Expected behavior

No deprecation warnings when using the current version of sass.

### Actual behavior
Deprecation Error:
<img width="917" alt="Screen Shot 2021-05-28 at 4 08 14 PM" src="https://user-images.githubusercontent.com/4572799/120037304-6c3cee00-bfcf-11eb-9019-55b5a642404d.png">

**Comment by service-paradis** [comment]
Buefy will need to change a few things for the next version, but we need a new version of Bulma that removes slash divisions. You can follow the discussion at https://github.com/jgthms/bulma/issues/3333

**Comment by SomethingNew71** [comment]
@service-paradis thanks for the update. It didnt even dawn on me that this might be further upstream than buefy.

**Comment by SomethingNew71** [comment]
Hey this isn't fully solved yet. While the ones caused by bulma are addressed, Buefy has some / division warnings in the functions util.

https://github.com/buefy/buefy/blob/dev/src/scss/utils/_functions.scss#L17

I am gonna toss up a PR later today to replace that.
