### ISSUE TITLE
Add size property to field when used for horizontal?

### ISSUE THREAD

**Issue by iwasherefirst2** [buefy/buefy#3352]
### Description

I have a horizontal form with names and emails side by side, looks like this:

![image](https://user-images.githubusercontent.com/1765602/120114946-d5646300-c181-11eb-94b1-fe5ec14dae36.png)

Thats the code for it:

```
 <div v-for="user in users">
          <b-field :horizontal="true" :label="user.name" >
            <b-input
                type="text"
                value=""
                placeholder="Enter email"
                required>
            </b-input>
          </b-field>
        </div>
```

I would be very happy if I could easily customize the distance between the rows, as well as telling the elemnt that the b-field should have size 50% (instead of 20% or what this is). I was thinking about something like this:

   <b-field :horizontal="true" :label="user.name" size="50%" >

### Why Buefy need this feature
I think there are many horizontal forms like what I described above.

**Comment by robinsandstrom** [comment]
```
.field-body {
 flex-grow: 5
}
```

Just use the css selectors for flex grow to whatever suits your needs, i.e. flex-grow: 2 or flex-grow: 3, etc. and you can achieve the desired result

**Comment by jtommy** [comment]
It's relative to Bulma
