### ISSUE TITLE
Autocomplete with 

### ISSUE THREAD

**Issue by cypressious** [buefy/buefy#3357]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: 2.6.13
**OS/Browser**: Windows 10, Firefox 89

### Description

An Autocomplete with `keep-first` will trigger `@select` for the currently selected element when clicking outside.

### Steps to reproduce

```vue
<template>
  <div id="app">
    <b-autocomplete
      :data="statuses"
      field="name"
      keep-first
      :open-on-focus="true"
      @select="selected = $event"
    >
      <template slot-scope="props">
        {{ props.option.name }}
      </template>
    </b-autocomplete>

    <div>
      Selected: {{selected}}
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      selected: null,
      statuses: [
        {
          status: "one",
          name: "One"
        },
        {
          status: "two",
          name: "Two"
        },
        {
          status: "three",
          name: "Three"
        },
        {
          status: "four",
          name: "Four"
        },
        {
          status: "five",
          name: "Five"
        }
      ]
    };
  }
};
</script>
```

Click on the Autocomplete, then click outside to close it.

### Expected behavior

`selected` stays `null`

### Actual behavior

`selected` becomes the last selected item.

**Comment by fabiofdsantos** [comment]
You can remove the `keep-first` property.

**Comment by elisamuelps** [comment]
We will soon be able to close this issue, I have added a new option which optionally disables the @select event when clicking outside.

See fa010a9
