### ISSUE TITLE
[Feature Request] Use Buefy components as standalone components

### ISSUE THREAD

**Issue by douglasg14b** [buefy/buefy#3359]
### Description

Use Buefy components in a standalone manner without polluting the global CSS space

### Why Buefy need this feature

So that it can be used alongside other frameworks, as opposed to having to drop buefy in order to utilize another framework due to conflicting css classes

**Comment by jtommy** [comment]
@douglasg14b Buefy was born with Bulma dependency so it follows Bulma UX and style (CSS).
In order to meet your need you might take a look at my other project https://oruga.io.
