### ISSUE TITLE
Possible invalid path in an @import in buefy-build.scss

### ISSUE THREAD

**Issue by dmcbrn** [buefy/buefy#3361]
### Overview of the problem

**Buefy** version: 0.9.7
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

Using with Laravel's `npm run prod` 

### Steps to reproduce

Try to compile assets using `npm run prod`: 

```
.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
  },
```

### Expected behavior

Compiles successfully.

### Actual behavior

Fails with error:
```
@import "../../node_modules/bulma/sass/utilities/functions";
^
      File to import not found or unreadable: ../../node_modules/bulma/sass/utilities/functions.
      in /home/vagrant/.../node_modules/buefy/src/scss/buefy-build.scss (line 1, column 1)
```

When I manually go to `buefy-build.scss` my IDE points me to the existing `functions.scss` file. However the file location is set as:

`@import "../../node_modules/bulma/sass/utilities/functions";`

But only after manually changing it to correct relative path:

`@import "../../../../node_modules/bulma/sass/utilities/functions";`

the `npm run prod` works.

So, as far as I can tell the relative path is wrong

**Comment by service-paradis** [comment]
Can you take a look at #3242 to see if it can help you?

**Comment by dmcbrn** [comment]
Thanks, I am indeed importing `buefy-build`. Beats me if I remember why anymore. 

Anyhow, changing from `@import '~buefy/src/scss/buefy-build';` to `@import '~buefy/src/scss/buefy';` gives me another error.

In `node_modules/buefy/src/scss/utils/_varialbes.scss`

```
....
$link-visited: $grey !default;
...
```

`$grey` is undefined.

Searching for `$grey` in the `node_modules/buefy` folder and I can't find where it should be defined.
