### ISSUE TITLE
[WTA] TagInput closable on selected item

### ISSUE THREAD

**Issue by 1aliff** [buefy/buefy#3365]
Hi Beufy team want to ask is it possible to custom taginput closable props for selected item?

For example i have pre-populated data coming from API  to be "Selected" by default and I need to set it to closable false.

But at the same time, I will give some options to select by user as well, but this option selected by user i want it to be closable true.

this is the sample use case : https://codesandbox.io/s/buefy-playground-forked-78ru5?file=/src/App.vue
Expected result would be : Opt 1 is not closable, and the rest whatever is selected will be closable.

Is it something possible to achieve?

I have done few ways for example using slots #selected
but since data [1] is already consider 'selected' so it does not affect the rest of data

Kindly advised, since i am quite new to Buefy as well. Thanks
Edit : typo

**Comment by jtommy** [comment]
Sure, there is selected slot, https://buefy.org/documentation/taginput

**Comment by 1aliff** [comment]
Hi @jtommy thanks for your response, i updated my codesandbox link code and use #selected props as documented, but somehow i still unable to disable the closable input for the first input tag, please advice thanks

**Comment by jtommy** [comment]
You should set closable to true only for the first index, for example
`:closable="index === 0"`

**Comment by 1aliff** [comment]
Works like a charm thanks !
