### ISSUE TITLE
Buefy website returns 404 on direct visit to non-homepage pages

### ISSUE THREAD

**Issue by gabrielchl** [buefy/buefy#3377]
### Overview of the problem

**OS/Browser**: Ubuntu 20.04.1 / Firefox 89.0.1

### Description

Buefy website returns 404 on a direct visit to non-homepage pages (probably due to incorrect server settings, not redirecting traffic to the handler?)

### Steps to reproduce

1. Go to https://buefy.org/documentation or any other pages other than buefy

### Expected behavior

The page is supposed to load

### Actual behavior

404

**Comment by jtommy** [comment]
I've just fixed, thanks
