### ISSUE TITLE
Not emit value when clear data from input number

### ISSUE THREAD

**Issue by MinhPhuPham** [buefy/buefy#3378]
### Overview of the problem

**Buefy** version: [0.9.4]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chrome

### Description

- When i clear input => it not emit value empty? So how can i check it? 

### Steps to reproduce

- See on Codepen: https://codepen.io/minh-ph/pen/poeBOdQ?editors=1011

### Expected behavior

- I want it emit value back.

**Comment by jtommy** [comment]
You are right it doesn't emit when value is empty
