### ISSUE TITLE
b-table sortable doesn't work with specific string format

### ISSUE THREAD

**Issue by amirbcer** [buefy/buefy#3379]
### Overview of the problem

**nuxt** version: [^2.14.6]
**nuxt-buefy** version: [^0.4.4]
**OS/Browser**: KDE neon/Chrome/Firefox

### Description
FRONT Sorting with b-table and b-table-column doesn't work when field's prop key use a dot.

### Steps to reproduce

Here is a simple example to reproduce using simple sortable props :

```
<template>
  <b-table
    :data="data"
    :loading="false"
    striped
    bordered
  >
    <b-table-column
      v-slot:default="{ row }"
      label="Activité"
      field="Activity.name"
      sortable
    >
      {{ row['Activity.name'] }}
    </b-table-column>

    <b-table-column
      v-slot:default="{ row }"
      label="Ordre"
      field="Activity.order"
      sortable
    >
      {{ row['Activity.order'] }}
    </b-table-column>
  </b-table>
</template>
```
data's array looks like this :

```
data() {
  return {
    data: [
      { 'Activity.name': 'Amir', 'Activity.order': 5478 },
      { 'Activity.name': 'Etienne', 'Activity.order': 3214 },
      { 'Activity.name': 'Jean', 'Activity.order': 9366 },
      { 'Activity.name': 'Zack', 'Activity.order': 9711 }
    ]
  }
},

```
### Expected  & Actual behavior

I need to sort on field "Activity.name" and "Activity.order", but this doesn't work.
If i replace data keys by Activity_name and Activity_order (in template too ofc), **it's work**.

My guess is field's prop for b-table-column doesn't like a certain type of format.

**Comment by jtommy** [comment]
Buefy doesn't support dot into field name because it reads it as a object into an object 
{ 'Activity': { 'order': 1} }
