### ISSUE TITLE
Autocomplete: show-all-on-open

### ISSUE THREAD

**Issue by tfeldmann** [buefy/buefy#3382]
### Description

On the first click on the autocomplete the full list of options should be visible - even if there is some input already. As soon as the user types something the list is filtered.

### Why Buefy need this feature

I'm missing this functionality for my website [fretty.app](https://fretty.app). For example you click on the tunings input and only see tunings like the default one because they are already filtered. You only see the full list when clearing the input.

Already filtered on open:
![Bildschirmfoto 2021-06-21 um 18 05 23](https://user-images.githubusercontent.com/385566/122793344-5fa07280-d2bb-11eb-8fab-fe642efde3c7.png)

What I would like to see:
![Bildschirmfoto 2021-06-21 um 18 05 27](https://user-images.githubusercontent.com/385566/122793347-6202cc80-d2bb-11eb-91db-7cd0b899249e.png)

**Comment by jtommy** [comment]
@tfeldmann are you using `open-on-focus` prop ?

**Comment by tfeldmann** [comment]
Yes, I'm currently using `open-on-focus` and `clearable`.

**Comment by jtommy** [comment]
Then it's a "problem" of your filter method because the component shows the `data` prop
