### ISSUE TITLE
How to hide column based on props as props scope is now change 

### ISSUE THREAD

**Issue by NitinJ88** [buefy/buefy#3384]
### Overview of the problem

**Buefy** version: [0.9.0]
**Vuejs** version: [2.6.10]
**OS/Browser**: Windows 10

### Description

How we can enable/disable b-table-column based on the data which is bind to b-table or props value.
<b-table-column
          v-slot="props"          
          class="users-table--b-table--user-type-label"          
          :label="UserType"
          **v-if="displayUserType(props.row) && !props.row.bGuestUser"**  // this is not working now
 >

**Comment by jtommy** [comment]
I don't understand your need.
The column visibility shouldn't depend on a single data of a row.
