### ISSUE TITLE
Not able to call change event in b-tabs when activeTab used in v-model is changed

### ISSUE THREAD

**Issue by RishikeshDhobale** [buefy/buefy#3386]
### Overview of the problem

**Buefy** version: [0.9.0]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10

### Description
I used activetabid in the v-model in b-tabs. However, the change event is not getting triggered when the value of activetabid is changed.

<b-tabs
    ref="tabdatas"
    v-model="activetabid"
    :animated="false"
    size="is-small"
    @change="onTabChange"
  >
 
Here, onTabChange is not getting triggered while the value of activetabid is changed.

**Comment by RishikeshDhobale** [comment]
@service-paradis did you get a chance to look into this? Also please let me know if any additional information is needed from my side to reproduce the issue.
Is there any workaround available to resolve this issue?
Thanks

**Comment by RishikeshDhobale** [comment]
Hi @service-paradis, [here](https://github.com/RishikeshDhobale/samplecode) is the sample code for our issue. Here, for the buefy version 0.8.20, if we switch the tab, then 'onTabChange' functoin gets called and the alert is shown. But, for the beufy versoin 0.9.0 the 'onTabChange' function is not getting called after changing the tab or activetabid.
Please let me know a workaround for this issue.
Thanks

**Comment by jtommy** [comment]
@RishikeshDhobale you can use `input` event

**Comment by RishikeshDhobale** [comment]
Hi @jtommy, ```input``` event is working fine while changing the tab. But, if we are going to remove (or close) a tab lower than the active tab id, ```display: none``` style is getting applied on the tab.

![image](https://user-images.githubusercontent.com/53400645/125309228-353c5500-e34f-11eb-8c1c-48624ebcb09f.png)

Is there any solution to avoid ```display: none```? Please let me know.

**Comment by jtommy** [comment]
You can use `destroy-on-hide` prop

**Comment by RishikeshDhobale** [comment]
Hi @jtommy, I tried using ```destroy-on-hide```. But, it does not resolve the issue. Any idea where the ```display: none``` is getting set? Do you think of any other direction where I need to check or investigate.

**Comment by jtommy** [comment]
Can you share your code? Btw looking tour screen it should be your custom code because into `.tab-content` element there is only a slot
