### ISSUE TITLE
Passing selected object to b-table not working

### ISSUE THREAD

**Issue by MarnitzRoux** [buefy/buefy#3388]
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.15.6]
**OS/Browser**: Windows 10, Chrome 91

### Description

I am building an app with Nuxt.js that requires a search, using a `<b-autocomplete>` component, of data that is in a `<b-table>` on the page below, and passes the selected item to that table to highlight it.

When reading through the selection part of the [Buefy table docs](https://buefy.org/documentation/table/#selection), it clearly shows that the index number of the data array can be passed to the table with the `selected` prop to 'pre-select' a row. But reproducing similar conditions as the docs doesn't yield the same results.

This is the `<b-table>` code in the `<template>` tags:

```
<b-table
  :data="data"
  :selected.sync="selected"
  sort-multiple
  :sort-multiple-data="[{field:'last',order:1},{field:'first',order:2}]"
  default-sort-direction="asc"
  striped>

  <b-table-column field="first" label="First Name" width="300" sortable v-slot="props">
    {{ props.row.first }}
  </b-table-column>
  
  <b-table-column field="last" label="Last Name" width="300" sortable v-slot="props">
    {{ props.row.last }}
  </b-table-column>

  <div>
    <pre>{{selected}}</pre>
  </div>
</b-table>
```

This is the code where the table gets its data:

```
export default {
  data() {
    const data = [
      { 'id': 1, 'first': 'Jesse', 'last': 'Simmons'},
      { 'id': 2, 'first': 'John', 'last': 'Jacobs'},
      { 'id': 3, 'first': 'Tina', 'last': 'Gilbert'},
      { 'id': 4, 'first': 'Clarence', 'last': 'Flores'},
      { 'id': 5, 'first': 'Anne', 'last': 'Lee'}]

    return {
      data,
      selected: data[0],
    }
  },
}
```

I thought it could be because the table loads before `selected` is set but I've done tests to change the selected index of `data[index]` to see if it makes a difference after the table loads but it doesn't update `selected` at all, so that leads me to think that it's not reactive for some reason, but I haven't spent a lot of time on reactivity in Vue.js so I'm not sure.

I had the same issue with the `checked` prop as well, where it doesn't recognise any objects passed into `checkedRows` but I got around that with `:custom-is-checked="(a,b)=> a.id === b.id"` but `selected` doesn't have anything like that, at least not as far as I know.

It'll be great to get this working as is, e.g. finding the index of the desired object and passing that to `data[object]`, but is it possible to be able to use the object that was selected in the `<b-autocomplete>` directly instead? It would be a much simpler way to work.

### Steps to reproduce

I made a [Codepen](https://codepen.io/MarnitzRoux/pen/MWmgEpq) example of my issue, hopefully this helps demonstrate what I'm struggling with

### Expected behaviour

This is the expected behaviour when passing an array index to `selected: data[0]` (reproduced manually by selecting the row in the table)

![table-selected-expected](https://user-images.githubusercontent.com/80182562/123369222-b3170700-d5c0-11eb-9d12-99fa116ef07c.PNG)

### Actual behaviour

However the actual behaviour doesn't select anything other than simply setting `selected`, as shown under the table.

Nuxt.js shows it has the latest version of Buefy, through the nuxt-buefy module,  so it doesn't seem like just an old version issue.

![table-selected](https://user-images.githubusercontent.com/80182562/123369081-603d4f80-d5c0-11eb-942a-5b629d1199c9.PNG)

**Comment by jtommy** [comment]
@MarnitzRoux you should reproduce it on codepen or codesandbox or similar.
It looks a really weird

**Comment by MarnitzRoux** [comment]
@jtommy I made a [Codepen](https://codepen.io/MarnitzRoux/pen/MWmgEpq) example you can have a look at.

**Comment by jtommy** [comment]
There is an issue using multiple sort otherwise it works well

**Comment by MarnitzRoux** [comment]
Okay, that makes sense. I'll make do for now and leave it to you guys to come up with a solution.
