### ISSUE TITLE
Cannot find element inside B-table from unit test case after upgradation of buefy to 0.9.0

### ISSUE THREAD

**Issue by vinod454** [buefy/buefy#3390]
### Overview of the problem

**Buefy** version: [0.9.0]
**Vuejs** version: [2.6.11]
**OS/Browser**:Windows 10

### Description

I used b-table in the vue component, under that I have one div block.
while calling div in unit test by class name it gives me an error

Vue componet ->

  <div class="share-dialog-table">
    <div class="share-dialog-table--user-list-outside">
    </div>
    <b-table>
      <b-table-column>
        <div class="share-dialog-table--user-list-inside">
        </div>
      </b-table-column>
    </b-table>
  </div>

![image](https://user-images.githubusercontent.com/30755400/123450364-4a4c8080-d5fa-11eb-9152-c816a34e7860.png)

Unit test(jest)->

test('test', () => {
    const wrapper = getWrapper();

    let divOutsideControl = wrapper.find('.share-dialog-table--user-list-outside');
    let divinsideControl = wrapper.find('.share-dialog-table--user-list-inside');
  });
![image](https://user-images.githubusercontent.com/30755400/123450458-63edc800-d5fa-11eb-810b-943bc39c0d24.png)

**the "divOutsideControl" get the correct output while  "divinsideControl"  get the error value**

Output->
**_divOutsideControl_** ->
Wrapper {rootNode: <accessor>, vnode: <accessor>, element: <accessor>, vm: <accessor>, options: <accessor>}
element (get):ƒ () { return element; }
element (set):ƒ () { return throwError('wrapper.element is read-only'); }
options (get):ƒ () { return frozenOptions; }
options (set):ƒ () { return throwError('wrapper.options is read-only'); }
rootNode (get):ƒ () { return vnode || element; }
rootNode (set):ƒ () { return throwError('wrapper.rootNode is read-only'); }
vm (get):ƒ () { return undefined; }
vm (set):ƒ () { return throwError('wrapper.vm is read-only'); }
vnode (get):ƒ () { return vnode; }
vnode (set):ƒ () { return throwError('wrapper.vnode is read-only'); }
__proto__:Object

![image](https://user-images.githubusercontent.com/30755400/123449624-7ddadb00-d5f9-11eb-94ef-3e4b71d0c716.png)

**_divinsideControl_**->
ErrorWrapper {selector: '.share-dialog-table--user-list-inside'}
selector:'.share-dialog-table--user-list-inside'
__proto__:Object

![image](https://user-images.githubusercontent.com/30755400/123449780-9e0a9a00-d5f9-11eb-85d1-453cc6965590.png)

### Steps to reproduce

this issue occure after updgrading the buefy to 0.9.0

### Expected behavior

**the "divinsideControl"   should give me correct value similar to "divOutsideControl"**

### Actual behavior

**the "divOutsideControl" get the correct output while  "divinsideControl"  get the error value**

**Comment by service-paradis** [comment]
There was some breaking changes for [0.9.0](https://github.com/buefy/buefy/releases/tag/v0.9.0)

**Comment by vinod454** [comment]
@service-paradis is there any way where I can find elements ( div eg."divOutsideControl" ) inside "b-table" ?

**Comment by service-paradis** [comment]
You will need to create a valid table with some data inside if you want the content of a column to be available. Right now, if you try the code for your table using Codepen or something similar, the inner div wont be displayed nor findable.

**Comment by vinod454** [comment]
we haven't used Codepen or something similar.
Here is code Snippet valid table with some data

![image](https://user-images.githubusercontent.com/30755400/123650653-63e30780-d848-11eb-82d5-f7f3c734514f.png)



here is the test where it fails to find "dropdown" element

![image](https://user-images.githubusercontent.com/30755400/123650707-752c1400-d848-11eb-8c87-37ce653aeacf.png)

**Comment by service-paradis** [comment]
Can you paste the code instead of screenshot so I can take a look more easily?
If you could also paste a minimal `users` data, it would be helpful.

**Comment by vinod454** [comment]
Below are the code snippets:
[vue_component.txt](https://github.com/buefy/buefy/files/6727117/vue_component.txt)
[test_and_userinfo.txt](https://github.com/buefy/buefy/files/6727273/test_and_userinfo.txt)

**Comment by service-paradis** [comment]
Hum... hard to tell. The code for the table is looking fine. Did you try awaiting for the `$nextTick` before trying to find the element?

**Comment by vinod454** [comment]
thank you @service-paradis, "$nextTick" worked for me.

**Comment by NitinJ88** [comment]
Here is another example where I face a similar problem after upgrading buefy version to 0.9.0. $nextTick is also not working here.
[samplecode](https://github.com/NitinJ88/sampletable.git)

**Comment by calebwaldner** [comment]
> Hum... hard to tell. The code for the table is looking fine. Did you try awaiting for the `$nextTick` before trying to find the element?

@service-paradis Thank you for this, after a bunch of research this little tip was all I needed.
