### ISSUE TITLE
BTable broken by <template #default>

### ISSUE THREAD

**Issue by 6XGate** [buefy/buefy#3391]
### Overview of the problem

**Buefy** version: 0.9.8
**Vuejs** version: 2.6.14
**OS/Browser**: Ubuntu 20.04/Chrome 91.0.4472.114

### Description

BTable will not render if columns are placed in a `<template #default> region.

### Steps to reproduce

1. Create a component that will contain a BTable.
2. Add a `<template #default></template>` region inside BTable markup.
3. Add BTableColumn components inside the `#default` region.

### Expected behavior

The table should render normally.

### Actual behavior

The table does not render any rows or columns.
See this [CodePen](https://codepen.io/6XGate/pen/OJmJjVq) for an example.

**Comment by waldeck-dev** [comment]
Hello,
The _default_ slot is not actually a named slot.
You don't need to specify `#default` as slot name. `<template></template>` is enough.
