### ISSUE TITLE
sticky-header does not work with height set as inherit

### ISSUE THREAD

**Issue by NitinJ88** [buefy/buefy#3397]
![image](https://user-images.githubusercontent.com/86343802/123919771-e8e23400-d9a2-11eb-8bd1-a63108a9ffe8.png)

### Overview of the problem

**Buefy** version: 0.9.0
**Vuejs** version: 2.6.11
**OS/Browser**: Windows 10

### Description

sticky-header property of b-table  does not work with height as "inherit" to inherit the height of it parent. this is best way to set height to support responsiveness.  Sticky heder works if we set the table hight to some specific value ex. 500px.

Not working.
![image](https://user-images.githubusercontent.com/86343802/123954236-c9a8ce00-d9c5-11eb-877e-9f19c4a32708.png)

working
![image](https://user-images.githubusercontent.com/86343802/123919873-044d3f00-d9a3-11eb-8dab-226695983f08.png)

### Expected behavior

The sticky header should work with any height ex. height = "inherit"

### Actual behavior

The sticky header not working with height = "inherit"

**Comment by jtommy** [comment]
No, you have to specify a height as described in the docs

**Comment by NitinJ88** [comment]
@jtommy : You are saying it will not work with "inherit" height for a table? it will only work when specific height is set to table? like 500 px or something.

**Comment by jtommy** [comment]
Exactly

**Comment by NitinJ88** [comment]
If we set a specific height to the table then it gives issues in responsive UI like mobile devices. Do you have any solution so it will work for "inherit" height?

**Comment by jtommy** [comment]
You can change it listening resize event or match media
