### ISSUE TITLE
Tooltip can't accept more than one space separated class without error

### ISSUE THREAD

**Issue by gordondmacdougall** [buefy/buefy#3406]
https://github.com/buefy/buefy/blob/7f15ab4bb3bd8a7291c620a0df931b405066f2d6/src/components/tooltip/Tooltip.vue#L125

Trying to pass in more than one staticClass into tooltip causes an error. I've attached the line in question and a fix for this could be:

` _.forEach(this.$vnode.data.staticClass.split(" "), (classItem) => {
                        tooltipEl.classList.add(classItem);
                    })`

**Comment by mouadTaoussi** [comment]
I think it can be better to show me the snippet of the tooltip that you wrote!

**Comment by gordondmacdougall** [comment]
I did add the code, my change was to replace the line in question with the code I have added

```
_.forEach(this.$vnode.data.staticClass.split(" "), (classItem) => { tooltipEl.classList.add(classItem); })
```

**Comment by mouadTaoussi** [comment]
So you want to pass more than one static class, then you cannot because it throws an error!

**Comment by mouadTaoussi** [comment]
```js 
this.$vnode.data.staticClass
``` 
returns undefined!
I'm trying to fix that problem  but I cannot understand the error quickly
