### ISSUE TITLE
Tabs :label HTML Support

### ISSUE THREAD

**Issue by alanyong91** [buefy/buefy#3411]
### Description

This is what I trying to do:

```
<b-tab-item
    v-for='(detail, index) of visibleInspReportPoints'
    :key='index'
    :label='<div>Title <span>(100)</span></div>'
>
...
</b-tab-item>
```

### Why Buefy need this feature

It should be able to support HTML in `:label` rather that just pure string type. The design could be more sophisticated just one string itself.

**Comment by jtommy** [comment]
There is header slot to show html content

**Comment by alanyong91** [comment]
how to apply that? i don't see that in buefy documentation.

**Comment by jtommy** [comment]
https://buefy.org/documentation/tabs#custom-headers

**Comment by alanyong91** [comment]
thanks~
