### ISSUE TITLE
Allow custom animation for carousel

### ISSUE THREAD

**Issue by arthur-clq** [buefy/buefy#3412]
Hi, I was using the `b-carousel` component and feel that allowing custom animation for the component could be a great feature.

Did some digging in the code and I think changing these few lines should do the trick:
CarouselItem.vue line 22-26 change to

```
if (this.parent.animated !== 'slide') {
    return this.parent.animated
} else if (this.parent.transition) {
    return 'slide-' + this.parent.transition
}     
```

Thoughts?

**Comment by Samiam519** [comment]
What would the corresponding HTML and CSS look like to match that?

**Comment by Samiam519** [comment]
the following classes can override the default slide animation with an `!important` property
```
.slide-next-enter-active,
.slide-next-leave-active {
    transition: transform 0.5s ease-in-out;
}
.slide-next-enter {
    transform: translate(100%);
}
.slide-next-leave-to {
    transform: translate(-100%);
}
.slide-prev-enter-active,
.slide-prev-leave-active {
    transition: transform 0.5s ease-in-out;
}
.slide-prev-enter {
    transform: translate(-100%);
}
.slide-prev-leave-to {
    transform: translate(100%);
}
```

**Comment by arthur-clq** [comment]
> the following classes can override the default slide animation with an `!important` property in the meantime
> 
> ```
> .slide-next-enter-active,
> .slide-next-leave-active {
>     transition: transform 0.5s ease-in-out;
> }
> .slide-next-enter {
>     transform: translate(100%);
> }
> .slide-next-leave-to {
>     transform: translate(-100%);
> }
> .slide-prev-enter-active,
> .slide-prev-leave-active {
>     transition: transform 0.5s ease-in-out;
> }
> .slide-prev-enter {
>     transform: translate(-100%);
> }
> .slide-prev-leave-to {
>     transform: translate(100%);
> }
> ```

Yes that is the current solution but I was hoping to not override the default because slide is still used in other components such as Tabs.
