### ISSUE TITLE
Cannot find element inside B-table from unit test case after upgradation of buefy to 0.9.0. $nextTick is also not working

### ISSUE THREAD

**Issue by NitinJ88** [buefy/buefy#3417]
### Overview of the problem

**Buefy** version: [0.9.0]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10

### Description

Unit test case failed while fiding the element inside the b-table using class.

### Steps to reproduce

[Sample code](https://github.com/NitinJ88/sampletable)
### Expected behavior

A unit test case should able to find elements inside the b-table using class.

### Actual behavior
A unit test case not able to find elements inside the b-table using class.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/3390

**Comment by NitinJ88** [comment]
@jtommy : The solution mention in #3390 is not working in this case. So this is a different issue. Please look at the sample code provided.

**Comment by NitinJ88** [comment]
@jtommy: can we have a short call to discuss this issue?
