### ISSUE TITLE
Toast breaks when Indefinite Toast opens and closes while another toast is active.

### ISSUE THREAD

**Issue by jdinh1** [buefy/buefy#3424]
### Overview of the problem
We encountered this issue on our app, and found out that it's also happening on the example on the website. This issue revolves around a regular Toast and an Indefinite Toast occurring almost at the same time. 

**Buefy** version: Latest
**Vuejs** version: [2.3.0]
**OS/Browser**: Windows/Edge

### Description
When a regular toast with some timeout (3000ms for example) is being displayed, and we display an Indefinite Toast and close it while the regular Toast is still active, it will break and won't allow us to create or open any new toast.

**This is reproducible with the current example on the website**

### Steps to reproduce
![image](https://user-images.githubusercontent.com/18290726/126398659-7202fe4c-e866-4051-9a81-d84a130fed56.png)
1. Navigate to the toast example https://buefy.org/documentation/toast/#from-inside-vue-instance
2. Hit the green `Launch Toast (custom)` button
3. While the toast is active, hit `Launch Toast (indefinite)` and then `Close Toast (indefinite)`, while the toast from step 2 is still active.
4. Observe that toast will stop working.

### Expected behavior
Toast to continue function as normal.

### Actual behavior
Toast stopped functioning. Cannot open new toast messages.

**Comment by geeksilva97** [comment]
I started working on it. Seems like a problem with the Notice queue from `NoticeMixin.js`.
