### ISSUE TITLE
custom-class props on all elements

### ISSUE THREAD

**Issue by recoiladam** [buefy/buefy#3426]
### Description

We are building an enterprise level web application using Buefy even though it does not support Vue 3 (yet). We have chosen to use Vue 2 because of the Buefy support plus the components and flexibility that Buefy offers however, we have noticed that some components have a `custom-class` prop while others do not. For example, I cannot pass a custom CSS class to a `b-checkbox` component but I can to an `b-input` component. It would be extremely beneficial if we could have a `custom-class` prop for all known HTML elements so that we can make changes to by applying custom styles to certain components within the application instead of application wide.

### Why Buefy need this feature

Providing the `custom-class` prop for all known HTML elements will provide even greater flexibility by allowing a developer to customize certain components on certain pages without the styles being applied application wide.

I do not think a screenshot is really required here but if you need one, please let me know. We ran into this issue because we wanted to be able to disabled a switch/checkbox but NOT have the text opacity changed. In order for this to work right now, we have to change the `opacity` to the `.is-disabled` CSS class application wide, which we would prefer not to do.

**Comment by jtommy** [comment]
You might use class prop and style the children from root element

**Comment by recoiladam** [comment]
Hm, I am not exactly sure what you're referring to. I have tried the following with no avail:

```
<b-switch class="className">Switch</b-switch>
<b-switch custom-class="className">Switch</b-switch>
<b-switch style="style:setting">Switch</b-switch>
```

In order to get the switch to look the way that we wanted it to when disabled, I had to overwrite the root styles which allowed the switch to be grayed out but the text to remain not grayed out.

```
.switch[disabled] > .check { opacity: .5 !important; }
.switch[disabled] { color:#202020; opacity:1 !important; }
```

But there are many other components that do not have a way to set a custom class either while some do. To me, it just makes more sense if we can apply a custom class to any component. Also, for tables. you can only have one `header-class` and / or one `cell-class`, you cannot even have two in the prop as only the first will be applied. This seems like a bug to me.
