### ISSUE TITLE
<b-menu-item> should allow tag="inertia-link"

### ISSUE THREAD

**Issue by miefos** [buefy/buefy#3427]
### Description

Currently, if I use Inertia with `<b-sidebar>`, I think the best way is to use `tag="inertia-link"`, e.g., `<b-menu-item tag="inertia-link" :href="$route('students')" label="Students"></b-menu-item>`. However, then console gives Vue warning: `app.js:49942 [Vue warn]: Invalid prop: custom validator check failed for prop "tag"`. 

**To avoid this warning, MenuItem's tag validator should pass, meaning that to config.js file should be added 
`defaultLinkTags: [
      ....,
     'inertia-link'
    ]`**

### Why Buefy need this feature

Because then Buefy will be more appealing to Inertia users and will not produce many irrelevant Vue warnings in console.

**Comment by service-paradis** [comment]
You can customize `defaultLinkTags`. Take a look at https://buefy.org/documentation/constructor-options
