### ISSUE TITLE
Allow page number input in pagination components

### ISSUE THREAD

**Issue by gabrielchl** [buefy/buefy#3428]
### Description

Currently, the pagination components only support page switching by clicking on the left or right buttons or the displayed page numbers. This new feature would add a number input at the left of the existing pagination component, allowing the user to explicitly browse a certain page.

### Why Buefy need this feature

It would improve the user experience.

**Comment by chadlafontaine** [comment]
I would also like to see this feature for both the b-pagination and the b-table components. There seems to be a desire for this, [https://github.com/buefy/buefy/issues/3274](url). Would this be okay to work on as a new feature?

**Comment by chadlafontaine** [comment]
@jtommy Would this feature be acceptable to work on?

**Comment by jtommy** [comment]
Sure, if you can I'll review jt

**Comment by gabrielchl** [comment]
(just to properly link the other issue) #3274

**Comment by chadlafontaine** [comment]
@jtommy I submitted the pull request. I accidentally linked my pull request #3640 to another pull request that was created without first checking if it was okay to be work on, but I fixed my mistake last night when I noticed. Let me know if I need to make any changes and I will get on it right away.

**Comment by jtommy** [comment]
Mmm there are two PR about the same issue.. what PR should I check?

**Comment by gabrielleecredera** [comment]
@jtommy #3640, thanks

**Comment by gabrielchl** [comment]
#3640 thanks

**Comment by chadlafontaine** [comment]
@jtommy Yes, please check #3640, Thank you.
