### ISSUE TITLE
b-field with has-addons : message disappear when input is blured

### ISSUE THREAD

**Issue by QuentinGab** [buefy/buefy#3429]
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.14]
**OS/Browser**: Edge, Chrome (lastest)

### Description

When a b-field has addons and a message, the message disappear when an input field is blured.

### Steps to reproduce

Here is a codepen: https://codepen.io/CRAKERSS/pen/bGWYOYW?editors=1000

**Comment by geeksilva97** [comment]
I'm investigating this ISSUE
