### ISSUE TITLE
Accessibility glitch: Keyboard does not trigger b-table checkbox change (click)

### ISSUE THREAD

**Issue by ghost** [buefy/buefy#3432]
### Overview of the problem

**Buefy** version: 0.9.8
**Vuejs** version: 2.6.14
**OS/Browser**: macOS Big Sur 11.2.2 / Safari 14.0.3

### Description

When checking a checkbox in a Buefy Table with Checkboxes __using the keyboard or a screen reader__ such as VoiceOver, the visual and "spoken" states of the checkbox update properly, but the __checkedRows__ property of the table does not change, and (or possibly because) the __click__ event is not fired.

### Steps to reproduce

1. Setup any Buefy Table example with checkboxes with which you can watch the checkedRows state somewhere;
2. Check/uncheck rows with the mouse. Works properly.
3. Focus a checkbox with the keyboard. Use space bar to toggle. checkedRows property does not update.
4. Turn on VoiceOver and navigate to a checkbox. Toggle the checkbox. It toggles, but checkedRows property does not update.

### Expected behavior

checkedRows property should update no matter the method of input. Would be good to have outline focus on keyboard focus on the checkboxes as well, but this can be added in CSS.

### Actual behavior

checkedRows not updating on keyboard/screen reader input.

### Workaround

I added the following to my updated() lifecycle hook, which has the onchange handler fire a click to its parent for each checkbox input on DOM update (__this assumes <b-table ref="table" ...__):

```js
updated() {
    const that = this
    const changeListener = (e) => {
                const event = new Event('click')
                e.target.parentNode.dispatchEvent(event)
            }
    this.$nextTick(() => {
        that.$refs.table.$el.querySelectorAll('input[type="checkbox"]').forEach(el => {
            if (el.onchange == null)
                el.onchange = changeListener
        })
    })
}
```

Essentially, screen readers and keyboards trigger the "input" and "change" events of input type="checkbox" elements, and ignore the span and label elements. To get around this, a bunch of ARIA roles etc. would need to be added to the visual elements. Would be better to just listen for changes on the input and allow them to trigger/fire a click event, probably better yet, to just call the component method to update state directly rather than having to fire another event, which I don't know if it would have weird side effects anywhere.

**Comment by chadlafontaine** [comment]
@jtommy I am experiencing this same issue when using the spacebar to select the checkbox. Would it be okay if I go ahead and fix this?

**Comment by jtommy** [comment]
@chadlafontaine you are welcome
