### ISSUE TITLE
Keyboard Navigation for Header and Footer Slots of Autocompletes

### ISSUE THREAD

**Issue by JDurman** [buefy/buefy#3437]
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chome and Edge

### Description
The Header and Footer slots of autocompletes can not be navigated to with the arrow keys. Currently, it can only be selected by a mouse. I believe this is incorrect and the option to use arrow keys should exist.

![no-keyboard-navigation-header](https://user-images.githubusercontent.com/6522739/127537678-0d3f7961-5002-41a4-b95a-ad4a624f64f7.gif)

### Steps to reproduce

1.Open an autocomplete with a header or footer slot.
2.Attempt to navigate to the header or footer slot.

### Expected behavior

I believe that the header and footer slots should be able to be navigated to with arrow keys. When the Keep-First option is selected the first result should still be the one hovered. However, the user should be able to hit the up arrow to navigate to the header item.

### Actual behavior
The ability to navigate to the header and footer slots is not present.

**Comment by jtommy** [comment]
@JDurman can you make a real example in order to understand your need ?

**Comment by JDurman** [comment]
We currently are using the header slot in the same way as the example in the attached gif. We use it to allow the user to add an option that may not currently exist in the set of results.

We have several users that use these "Toughbook laptops" which come with a very small mousepad. In order to make it easier for them we try our best to make it so that entire forms can be filled out with just a keyboard.

I too mostly just use a keyboard to fill out forms as well and this was the only form control so far that I have found an issue with using the keyboard to navigate through. 

I have attached a codepen with instructions to demonstrate the behavior I believe is missing.

https://codepen.io/JDurman/pen/GREgRjP

**Comment by jtommy** [comment]
I understand your need but header and footer are not items and keyboard navigation doesn't work on them.
Also what is your expectation using keep-first ? Focus on header or first item?

**Comment by JDurman** [comment]
I think in keeping with the spirit of `keep-first` it should hover on the first item of the results. The user could just navigate upwards if they need to select the header.

**Comment by slidenerd** [comment]
I came here to say I double this issue

- In my case I need to do a search when user inputs something other than the options available
- I added a template slot header which says Search "cat" as keyword and using the arrow key you should be able to navigate up and click on it

**Comment by jtommy** [comment]
Ok, there are good reasons to add this behaviour
