### ISSUE TITLE
customClass not working for Dialog

### ISSUE THREAD

**Issue by myteril** [buefy/buefy#3439]
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.14]
**OS/Browser**: Windows / Chrome

### Description

The `customClass` property is declared in BDialogConfig. But it is not working. The classes given as the value of the property is not applied on **Dialog** modal.

### Steps to reproduce

1. Create a button.
2. On click event, call one of the methods over a Vue component to create a **Dialog**: `$buefy.dialog.confirm`, `$buefy.dialog.alert` and `$buefy.dialog.prompt`.
3. Set a class name to the `customClass` property of **Dialog**.
4. Render and open the page on a browser.
5. Open the dialog by clicking the button.
6. Inspect the DOM with developer console.
7. Check if the class name that has been set is added into the class attribute of the **Dialog** element.

### Expected behavior

1. The class name given as the value of the `customClass` is added into the the class attribute of the **Dialog** element.

### Actual behavior

1. There is not the given class name anywhere in DOM.

To inspect the behaviour, please check this script: https://codepen.io/myteril/pen/xxdzRBM?editors=1010

**Comment by jtommy** [comment]
@myteril there isn't `customClass `prop on dialog

**Comment by myteril** [comment]
Actually it is declared in the types file. You can check it here: https://github.com/buefy/buefy/blob/322f7ef1d73d438389df811b3e35833fe659c184/types/components.d.ts

At the end of the BDialogConfig block, there is `customClass` prop. So there is. If the type declaration are invalid, then it should be fixed. If it is valid, then `customClass` is not working properly as explained in this issue.

**Comment by jtommy** [comment]
There is an error in the docs, you can add it or remove it from docs
