### ISSUE TITLE
Buefy is automatically applying the $link color to url text (any text with .com, .io, etc...) in Brave Mobile Browser.

### ISSUE THREAD

**Issue by pieroliviermarquis** [buefy/buefy#3441]
This is happening only in Brave Browser.  It can be seen here: https://www.stockgrid.io/privacy. It is probably Brave Mobile that is parsing text and applying the color to links rather than an issue with Buefy. Any suggestions on how to fix it would be appreciated.

**Comment by jtommy** [comment]
@pieroliviermarquis it looks like a Bulma issue, btw i am not expert about it
