### ISSUE TITLE
Check row on Table requires CSS to be added

### ISSUE THREAD

**Issue by syldor** [buefy/buefy#3443]
### Overview of the problem

**Buefy** version: v0.9.8
**Vuejs** version: v2.6.14

### Description

For Table, the behaviour of checking a row seems to require CSS to be loaded.

### Steps to reproduce

In the codepen of the documentation for Checkable Table https://buefy.org/documentation/table/#checkable it works fine, clicking a row adds it to the checkRows:

![buefy_ok](https://user-images.githubusercontent.com/4158062/128119618-1311fc7d-7a44-4a8c-9094-7689010406bc.gif)

But when removing the CSS, this behaviour is broken.

![buefy_nok](https://user-images.githubusercontent.com/4158062/128119662-bfaecdb4-7007-4bc8-8ff0-c5d1e4047aa6.gif)

### Expected behavior

Is there a way to make the feature work without adding the CSS?

Thanks

**Comment by jtommy** [comment]
Buefy works with Bulma and own CSS, in other words it needs CSS.
Take a look at https://github.com/oruga-ui/oruga, you'll find the same components but with a lite CSS to customize.
