### ISSUE TITLE
DateTimePicker can't be required

### ISSUE THREAD

**Issue by teuk1** [buefy/buefy#3447]
**Overview of the problem**
Buefy version: [0.9.3 / seen also on 0.9.8]
Vuejs version: [2.6.11]
OS/Browser: Windows 10 / Mozilla Firefox 90 & Google Chrome 92

**Description**
Inputs validation for datepicker works, but does not on datetimepicker . A simple attribute like "required" is ignored.

**Steps to reproduce**

1. Create a buefy datetimepicker component with attribute required or required="required"
2. Place cursor in input but do not type. Then click somewhere else.

**Expected behavior**
Error message appears, telling me to fill in the input.

**Actual behavior**
No error message.

When searching similar issue, the problem of Philnee can help to test
go to his codepen : https://codepen.io/philnee/pen/VwZawyM
and change the datepicker to datetimepicker
Result : no more validation messages

**Comment by geeksilva97** [comment]
Investigating

**Comment by geeksilva97** [comment]
You can do this using the `datepicker` property, which is to pass the `<b-datepicker>` properties.

```vue
<b-datetimepicker
    ref="datetimePicker"
    :debug="true"
    placeholder="Click to select..."
    v-model="selected2"
    icon="calendar-today"
    :datepicker="{required: true}"
    editable
    required>
</b-datetimepicker>
```
