### ISSUE TITLE
What locale are unit tests in? Date/time tests fail out of the box or I am doing something wrong...

### ISSUE THREAD

**Issue by ghost** [buefy/buefy#3458]
### Overview of the problem

**Buefy** version: 0.9.8 dev AND master branches
**Vuejs** version: 2.6.11
**OS/Browser**: jest

### Description

Running the unit tests on dev AND/OR master, I get a lot of errors like the following:
```
  ● BDatepicker › #dateFormatter › multiple › should format multiple dates passed via array

    expect(received).toEqual(expected)

    Expected value to equal:
      "2019-4-1, 2019-4-13, 2019-4-3"
    Received:
      "4/1/2019, 4/13/2019, 4/3/2019"

```

### Steps to reproduce

Run the unit tests on the dev branch.

### Expected behavior

Tests should pass, at least on master.

### Actual behavior

Am I missing something in the locale setting, or are the tests out of date? I've tried the following in Datepicker.spec.js, to no avail:

```js
...
        beforeEach(() => {
...
            wrapper = shallowMount(BDatepicker, {
                stubs: {
                    transition: false
                },
                propsData: {
                    locale: 'en-US' // en-CA, en-GB ...
                }
            })
...

```
but the specs keep generating dates in the format:
`4/1/2019`
instead of:
`2019-4-1`

What locale are the tests in, or do these need to be updated somehow?

**Comment by geeksilva97** [comment]
Same here. Can you help us @jtommy?
