### ISSUE TITLE
b-navbar-dropdown can not hoverable

### ISSUE THREAD

**Issue by Thaimay** [buefy/buefy#3468]
i try https://codepen.io/pen?&editors=101 and add "hoverable" propertise to "b-navbar-dropdown" but it can not be hoverable. I explore on source code. I think should be change from @mousenter to @ mouseover

![image](https://user-images.githubusercontent.com/11836057/130047021-32ed5c8d-000b-4c15-8e87-52af91d4670c.png)

**Comment by GMartigny** [comment]
Hi @Thaimay,
The codepen you link is empty, you need to save it first to you account before sharing.
I don't see any issue with the `hoverable` property, it works as expected for me.
https://codepen.io/GMartigny/pen/JjJjBRM

**Comment by jtommy** [comment]
Thanks @GMartigny for the support
