### ISSUE TITLE
 Autocomplete: make option for keep-first selects hovered option on blur

### ISSUE THREAD

**Issue by dauriata** [buefy/buefy#3469]
### Overview of the problem

I was about to post an issue about autocomplete with keep-first that select hovered option on blur but I found out that it was intended in issue  #3118 and then commit ff7d574   ( original commit f268fd5 )

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.14]

### Description

In my opinion, when clicking outside or blur it is common UX behavior to cancel the current action. 
here is a common scenario:  if I look for a name in an autocomplete field and the dropdown makes me propositions but I don t find what I was looking for, I click outside or blur and nothing should be selected.
If I find what I was looking for, `keep-first` make it easy to just it "Enter" or "Tab" to select.

The doc for keep-first has not been updated with commit ff7d574  :
`keep-first : The first option will always be pre-selected (easier to just hit enter or tab)`

### Steps to reproduce

https://codepen.io/zouloufr/pen/bGRbMPj

### Expected behavior

I would like this to be a configurable option. I am open to discussion but in my opinion behavior before commit ff7d574 should be the default

### Actual behavior

keep-first selects hovered option on blur

**Comment by fabiofdsantos** [comment]
The current behaviour was introduced to improve the UX in mobile devices.

The developer is still free to avoid the current behaviour by setting `keep-first` to false. Then creating a custom component which extends from the Autocomplete and adopt `@keyup.native.enter`.

Avoiding the current behaviour could also led to some confusion. For example, the user writes any option and it will provide a false-sense of selection:

![image](https://user-images.githubusercontent.com/8303937/130468654-20fe65a0-d5a4-49ad-bf55-fbcaa6d977f8.png)

**Comment by dauriata** [comment]
1. The workaround you propose is not exactly the same as the previous behavior because `keep-first` allowed to have the first option in an hovered style that made it look pre-selected.

2. the current implementation still provides a false sense of selection if the search value does not exist in option : 
![whatever](https://user-images.githubusercontent.com/16813527/130480690-58ac1083-49d3-4597-88d7-ee6af00886fe.gif)

3. This is plain bad UX to me and might be considered a bug : 
![notexists](https://user-images.githubusercontent.com/16813527/130480873-fcf90873-d4c2-4b23-bb03-02bf6fd9b64e.gif)

4. There is no way to dismiss or cancel a selection after started typing, even after clearing the search area (can use the right cross but you lose the current selection) :
![clear](https://user-images.githubusercontent.com/16813527/130480994-138029ca-62a5-46d9-84e7-a7d77ffe15b9.gif)


So I would still like to make the new behavior an option either the default or not, I am willing to write the PR if maintainers find it useful.

**Comment by jtommy** [comment]
@fabiofdsantos what do you think?

**Comment by dauriata** [comment]
looks like this is already work in progress with PR  #3403
bug number 3 is still there though when hitting Enter in this PR and it might be good to fix it in the meantime

**Comment by fabiofdsantos** [comment]
@dauriata Yes, we still have some bugs there.. :/

@jtommy I checked PR #3403 and it seems the way to go.

**Comment by elisamuelps** [comment]
Hi guys! I have been really busy over the last weeks and could not complete the PR #3403, basically what was left to do is to change the type checking with typeof, but as @dauriata mentioned, there might be small bugs in there if what we desire is good ux.

I'm still not 100% sure if type checking against bool is the right thing to do because it is known that some minifiers cannot work with advanced options when type checking with bools is done. For example if I use Google Closure compiler which makes type changes from bools to integers (1 | 0) the type checking fails and the code doesn't work anymore. Terser as well with advanced options fails. But I'll leave that decision to @jtommy 

I will have some free time this week as well, please hit me up if anything I can help with.

**Comment by jtommy** [comment]
@elisamuelps what do you mean with Boolean check?

**Comment by elisamuelps** [comment]
@jtommy doing something like this:

```javascript 
const myBool = false;

if (typeof myBool === "boolean") {
	//your code here		
}
```

the issue is that minifiers currently are not smart enough to detect the typeof check, and the code stays the same. At the end, the minifier will do something like this

```javascript
const a = 0;

if (typeof a === "boolean") {
	//exception
}
```

**Comment by elisamuelps** [comment]
I recall when I was about to do the type checking I was going to use typeof with booleans, found it! just checked my PR with git, it was with the function cancelOptions() line 152 on Dropdown.vue
