### ISSUE TITLE
Slide transition is jumpy

### ISSUE THREAD

**Issue by GMartigny** [buefy/buefy#3471]
### Overview of the problem

**Buefy** version: 0.9.8
**Vuejs** version: 2.6.14
**OS/Browser**: Chrome 92

### Description

When using Collapse component and using the slide transition, the animation is very jumpy. It slide on `100px` and then jump to completion.

### Steps to reproduce

https://codepen.io/GMartigny/pen/KKqKBjm

### Expected behavior

The animation should be smooth and cover the whole height of the component.

### Actual behavior

Animation is only on `100px` because this value is hardcoded on [`_animation.scss`](https://github.com/buefy/buefy/blob/dev/src/scss/utils/_animations.scss#L177).

**Comment by jtommy** [comment]
You are right, did you try overriding it with 100vh ?

**Comment by GMartigny** [comment]
> You are right, did you try overriding it with 100vh ?

This kind of works. But the transition is done between `0` and `100vh` (which is a lot) and moves very quickly.

The only solution I can see is using a CSS `clip-path`. The drawback is that the real element height is not animated.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2543511/130627315-428152d5-e333-4c0b-a7e9-1ac5cc42f2b2.gif)
> You can see the height jumping before and after animation is done

It would be possible to correctly animate height, but it would need to be computed first on the component, so the SCSS wouldn't be reusable.

**Comment by GMartigny** [comment]
With a bit of both, the transition is not that bad. It looks off at slow speed, but is ok when running at 150ms.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/2543511/130642734-62aadc10-8edc-4f0a-8038-fdeb16e74064.gif)
> The `max-height` lags behind when collapsing, and jump forwards when expanding.

**Comment by jtommy** [comment]
I'll try to find a solution but you might take a look at animate.css lib

**Comment by GMartigny** [comment]
I just looked at [Animate.css](https://animate.style/) and no animation is changing the element height.

I try playing with the element `margin-bottom`. With negative values, it's possible to retract following elements. Firstly, this is a weak solution as it only support column display. Secondly, this could have a lot of side effects and is really not performant.

**Comment by Sogl** [comment]
Run into the same problem. Still no solution for this?

In my previous project (Bootstrap) 4 collapse works fine.

**Comment by Sogl** [comment]
@wesdevpro Can you add this issue to ToDo list?

**Comment by wesdevpro** [comment]
@kikuomax what are your thoughts on this?

**Comment by kikuomax** [comment]
@wesdevpro @Sogl I have not understood the problem of overriding `max-height` with `100vh` as @jtommy suggested:
```css
.slide-enter-to,
.slide-leave {
    max-height: 100vh;
}
```
If one might feel the animation is too fast, `transition-duration` could also be overridden:
```css
.slide-enter-to,
.slide-leave-to {
    transition-duration: 300ms;
}
```

**Comment by wesdevpro** [comment]
> @wesdevpro @Sogl I have not understood the problem of overriding `max-height` with `100vh` as @jtommy suggested:
> 
> ```css
> .slide-enter-to,
> .slide-leave {
>     max-height: 100vh;
> }
> ```
> 
> If one might feel the animation is too fast, `transition-duration` could also be overridden:
> 
> ```css
> .slide-enter-to,
> .slide-leave-to {
>     transition-duration: 300ms;
> }
> ```

Sounds reasonable to me. I am now removing this issue from the To-Do List.
   Thank you
