### ISSUE TITLE
0.9.9 introduce duplication of attributes

### ISSUE THREAD

**Issue by Tovli** [buefy/buefy#3475]
### Overview of the problem

**Buefy** version: [0.9.9]
**Vuejs** version: [2.6.14]
**OS/Browser**:
Windows10/Vivaldi
### Description

On some conditions buefy duplicate an attribute.
my case is with `data-test-id` attribute

### Steps to reproduce

1 - create a template like the below:
```
<template>
		<b-navbar-dropdown
		data-test-id="localeSwitch"
    class="locale_switch"
    :label="$i18n.locale"
		collapsible
		hoverable
    >
		<b-navbar-item
		@click="switchLanguage"
		href="#"
		>
		en
		</b-navbar-item>
		<b-navbar-item
		data-test-id="localeHe"
		@click="switchLanguage"
		>
		he
		</b-navbar-item>
	</b-navbar-dropdown>
</template>
```

After building the bundle and serving there are two elements with `data-test-id="localeSwitch"`
The outer `div` under the `navbar-end` and the chosen `a` element under this `div`

![image](https://user-images.githubusercontent.com/14282692/131209199-70d92772-cb6c-4ce4-ad4b-17db57845ee1.png)

### Expected behavior
There is only one element with the `data-test-id="localeSwitch"` attribute and it is clickable

### Actual behavior

the attribute is duplicated and there is no one and only one clickable element with this attribute

**Comment by GMartigny** [comment]
Introduced by #3446. The component `b-navbar-dropdown` is missing a `inheritAttrs: false`. I'll do a PR this evening.

**Comment by jtommy** [comment]
@GMartigny thanks
