### ISSUE TITLE
Image size render too big from 768 - 1024 dimension

### ISSUE THREAD

**Issue by Thaimay** [buefy/buefy#3480]
I use buefy carousel. But i dont why image too big size when resize screen from 768px - 1024px.
Not only carousel. All tag img same problem

![image](https://user-images.githubusercontent.com/11836057/131974008-73699695-bf27-4009-bb0d-f61f645395cd.png)

------- From screen > 1024
![image](https://user-images.githubusercontent.com/11836057/131975027-4cf58cdf-0d6c-4f52-be67-4e7f08d2c248.png)
------- From screen < 768
![image](https://user-images.githubusercontent.com/11836057/131975177-71ec5068-d03d-469f-9040-d3345f96dab1.png)

Please help me. :(

**Comment by mouadTaoussi** [comment]
The first image size should be fixed

**Comment by Thaimay** [comment]
> Parts of the product in the Images doesn't show

Sorry. i dont understand. what do you mean?

**Comment by mouadTaoussi** [comment]
The product is not shown fully because the image is zoomed in that's the problem

**Comment by Thaimay** [comment]
@mouadTaoussi Thanks for your reply. The product get full infomation already. But if resize screen from 768px - 1024px all iamge using b-image will have large width. Do you have any solution?

**Comment by mouadTaoussi** [comment]
@Thaimay Sorry for the late, I Might took a look on that issue these days
