### ISSUE TITLE
Autocomplete focus bug with type 'textarea' (from 2019)

### ISSUE THREAD

**Issue by awakentrue** [buefy/buefy#3486]
### Overview of the problem

**Buefy** version: 0.9.10
**Vuejs** version: 2.6.14
**OS/Browser**: Windows 10 / Chrome

### Description

[Issue](https://github.com/buefy/buefy/issues/1260) returned from 2019 after [commit](https://github.com/buefy/buefy/commit/4ad9fd9738bc79281b3b308e6f1f5a65c36728bf#diff-bbecf789c900fd96da82fe890b43c8871372f7a9f43f304e5679a1d8872af9b7).
This commit added `type` property for `b-autocomplete`, but excludes any options other than `text`. If using type `textarea` in `b-input` it shows `<textarea />`, but in autocomplete many times used `$el.querySelector('input')`.

### Steps to reproduce

1) Focus on autocomplete

### Expected behavior

Autocomplete will be focused and shows items in dropdown

### Actual behavior

Console error: Error in v-on handler: "TypeError: Cannot read property 'select' of null"

**Comment by jtommy** [comment]
You are right but why should you use textarea?
It has been added to use it as test or search type
