### ISSUE TITLE
Can vue-awesome be customized to be used in Buefy?

### ISSUE THREAD

**Issue by onurusluca** [buefy/buefy#3487]
### Description

Would be great to have [vue-awesome](https://www.npmjs.com/package/vue-awesome) in buefy. 

### Why Buefy need this feature

Font-awesome is too much work and material-icons doesn't have a vue version. vue-awesome is small and fast.

**Comment by jtommy** [comment]
https://buefy.org/documentation/icon#fontawesome
Take a look at second example
