### ISSUE TITLE
Autocomplete with clear-on-select on doesn't update object ref

### ISSUE THREAD

**Issue by KuSh** [buefy/buefy#3489]
### Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: Firefox

### Description

Hi,

When using object ref with clear-on-select it seem to behave strangely and my object ref doesn't seem to be updated
Also calling v-model = null inside the onSelect handler with clear on select disabled doesn't seems to work neither

### Steps to reproduce

See https://codepen.io/kush-the-lessful/pen/dyRvWxZ

1. Select a value, the value is displayed after 'Selected:'
2. Clear and select a new value, the new value is displayed after 'Selected:'
3. Enable Clear on select switch
4. Select a new value, the selected text doesn't update
5. If you Disable Clear on select switch the Selected text is update with the previously selected value 

### Expected behavior

Same behaviour with and without clear on select

**Comment by KuSh** [comment]
Using `setTimeout(() => name['test'] = null)` inside the select handler seems to allow me to simulate "clear on select"

**Comment by jtommy** [comment]
Your example is quite strange but the problem is not Buefy.
It is a reactivity limit and you should use `this.$set(this.selected, 'test', option)`
