### ISSUE TITLE
TagInput with autocomplete and allow-new adds two tags at the same time

### ISSUE THREAD

**Issue by LonelyPlayer** [buefy/buefy#3490]
### Overview of the problem

**Buefy** version: [0.9.10]
**Vuejs** version: [X.X.X]
**OS/Browser**: Chrome

### Description

When the TagInput is used with autocomplete and allow-new enabled, and an item is selected via the arrow keys,
the item will be added via autocomplete as well as the InputField, resulting in two similar items in the TagList.

### Steps to reproduce
https://codepen.io/pen?&editors=101&prefill_data_id=ed91b42f-9e51-4ed1-b6e7-838edc605c4a

1. Activate Allow new tags button
2. select the input field
3. type something random
4. use the arrow keys to select an item from the autocomplete dropdown
5. press enter

### Expected behavior

Only one tag per selected input

### Actual behavior
Two tags per input

**Comment by calebwaldner** [comment]
I'm still getting this bug, using version 0.9.10.

**Comment by jtommy** [comment]
I have to release it yet
