### ISSUE TITLE
[Feature Request]: Make each attribute in new line 

### ISSUE THREAD

**Issue by mouadTaoussi** [buefy/buefy#3493]
### Description
Better to make each attribute in components examples the docs in new line for better UX approach.
it prevent the user to scroll to right or left for read the example. as well as reading component attributes easily! 

### Bad Approach
- Hard to read all the attributes and props for a beginner.
- Need to scroll left and right to read all the attributes.

![](https://firebasestorage.googleapis.com/v0/b/webcheck-fd169.appspot.com/o/Web%20capture_11-9-2021_212429_buefy.org.jpeg?alt=media&token=c4fcbc4f-db1c-4de8-82ec-90ab84a582de)

### Good Approach
- Easy to read any component's attributes and props.
- No need to scroll left and right.

![](https://firebasestorage.googleapis.com/v0/b/webcheck-fd169.appspot.com/o/Web%20capture_11-9-2021_21237_localhost.jpeg?alt=media&token=d5bc0103-7599-44c0-b1c0-7977a6f9e671)

### Why Buefy need this feature
Better UX experience while reading the examples and readability of component attributes

**Comment by jtommy** [comment]
Can you show me an example?

**Comment by mouadTaoussi** [comment]
forgot to include it 
### Bad Approach
- Hard to read all the attributes and props for a beginner.
- Need to scroll left and right to read all the attributes.

![](https://firebasestorage.googleapis.com/v0/b/webcheck-fd169.appspot.com/o/Web%20capture_11-9-2021_212429_buefy.org.jpeg?alt=media&token=c4fcbc4f-db1c-4de8-82ec-90ab84a582de)

### Good Approach
- Easy to read any component's attributes and props.
- No need to scroll left and right.

![](https://firebasestorage.googleapis.com/v0/b/webcheck-fd169.appspot.com/o/Web%20capture_11-9-2021_21237_localhost.jpeg?alt=media&token=d5bc0103-7599-44c0-b1c0-7977a6f9e671)
