### ISSUE TITLE
Input validation is triggered immediately

### ISSUE THREAD

**Issue by kremipn** [buefy/buefy#3498]
### Overview of the problem

**Buefy** version: 0.9.10
**Vuejs** version: 2.6.12
**OS/Browser**: Chrome, Firefox

### Description

When setting up a BInput element with a pattern and a validation message, validation is triggered on focus of the element instead of on blur. This results in the input showing error state before the user even had the chance to input anything.
### Steps to reproduce

1. Use a BInput element.
2. Supply a regex pattern for validation like `[a-z]+`
3. Click inside the field and observe the element immediately shows error.

Video is from the Buefy Documentation website:
https://user-images.githubusercontent.com/20395658/133424217-f649eeff-6701-4aa3-beeb-133678039e58.mov

### Expected behavior

Validation should only trigger on blur.

### Actual behavior

Validation triggers immediately, on focus of the input.

**Comment by fungiboletus** [comment]
Hello, this bug seems to be back after the #3577 fix.

**Comment by jtommy** [comment]
What version?
