### ISSUE TITLE
Draggable rows/columns on website not working

### ISSUE THREAD

**Issue by mweel1** [buefy/buefy#3501]
1.  Goto the Buefy website.
2. Select the table components
3. Go to the Draggable rows/columns section
4. Drag a column

### Expected behavior

The columns should change order when you complete the drag.

### Actual behavior

The columns do not change order

**Comment by geeksilva97** [comment]
From docs we have

> Use draggable/draggable-column prop to allow rows and columns to be draggable. **Manage** dragging using dragstart/columndragstart, dragover/columndragover and drop/columndrop events

This appears to be expected behavior. You must use these events and handle the position changes by yourself.
