### ISSUE TITLE
Impossible to listen to Autocomplete events in TagInput component

### ISSUE THREAD

**Issue by GMartigny** [buefy/buefy#3504]
### Overview of the problem

**Buefy** version: 0.9.9
**Vuejs** version: 2.6.14
**OS/Browser**: Chrome

### Description

The `TagInput` component is built upon the `Autocomplete` component, but it's not passing down the event listeners.

### Steps to reproduce

Use `Taginput` component and try to listen to `Autocomplete`'s events.

### Expected behavior

It's possible to listen to `icon-right-click` or `select-header` event for example.

### Actual behavior

Nothing happens.

https://codepen.io/GMartigny/pen/jOwZOKG?editors=1010

### Possible fix

Adding a `v-on="$listeners"` to the [`<b-autocomplete>` of `TagInput.vue`](https://github.com/buefy/buefy/blob/dev/src/components/taginput/Taginput.vue#L34)

**Comment by geeksilva97** [comment]
What is the correct listener, `right-icon-click`  or `icon-right-click`? In some parts of the code it is one and in other parts it is the other.

Well I tested it with `v-on ="$listeners"` but it broke. Every word I typed was split as shown below.

![print](https://user-images.githubusercontent.com/15680379/134070158-5db61970-2217-4ade-8878-05ab3d3de97a.png)

I noticed that in the `TagInput` the events are defined individually. Events like `@typing`, `@infinite-scroll` and so on.  So just added the event and it started working.

Check the PR https://github.com/buefy/buefy/pull/3509

**Comment by geeksilva97** [comment]
I have a question. When contributing should we avoid using `$listeners`? I'm asking because of this https://v3.vuejs.org/guide/migration/listeners-removed.html#_3-x-syntax

**Comment by GMartigny** [comment]
> What is the correct listener, right-icon-click or icon-right-click?

On [`Autocomplete.vue` it's `icon-right-click`](https://github.com/buefy/buefy/blob/dev/src/components/autocomplete/Autocomplete.vue#L621).

> So just added the event and it started working.

Yes, but it only works for `icon-right-click`. If I want to listen for the `select-header` event, you have to add yet another listener.

> When contributing should we avoid using $listeners?

Buefy doesn't support Vue 3 #2505.

**Comment by geeksilva97** [comment]
So the idea is make it work using `v-on="$listeners"`, right? I can try it.
