### ISSUE TITLE
Numberinput throws an error on increment/decrement after manual input 

### ISSUE THREAD

**Issue by evgenypanov** [buefy/buefy#3507]
### Overview of the problem

**Buefy** version: [0.9.10]
**Vuejs** version: [2.6.14]
**Linux/Firefox 92.0**:

### Description

Numberinput throws an error while trying to increment/decrement value after manually input the same number twice

### Steps to reproduce

1. Input a number
2. Click outside the Numberinput field
3. Input the same number again
4. Click "Increment" button

### Expected behavior

Value increased

### Actual behavior
TypeError: e.toFixed is not a function

Seems like computedValue is not properly validated and it actually can be a string. Expected behavior can be reached if cast computedValue to Number in get() method

**Comment by geeksilva97** [comment]
Same issue here. I will try to find the bug

**Comment by evgenypanov** [comment]
Looks like using ".number" modifier on b-input's v-model also fix the problem
