### ISSUE TITLE
B-Steps Validation on each step

### ISSUE THREAD

**Issue by dwaynedsouza** [buefy/buefy#3510]
I am trying to create a multi-step form and using <b-steps> and rendering different form components in <b-stem-item>
I am trying to disable the Next button if a field is not filled. While I can compute if the form is valid or not, I am not sure how to use the custom navigation to access the next.disabled property to sent it to true when my form is invalid.

Any help would be appreciated

**Comment by eliutgon** [comment]
@dwaynedsouza Can you provide sample code?
