### ISSUE TITLE
Tooltip does not display correctly in modal

### ISSUE THREAD

**Issue by akicho8** [buefy/buefy#3516]
### Overview of the problem

<img width="799" alt="スクリーンショット 2021-09-23 9 51 42" src="https://user-images.githubusercontent.com/808955/134441560-7c027d4e-38bd-4283-ae31-34d8787d9bcb.png">

**Buefy** version: 0.9.10
**Vuejs** version: 2.6.14
**OS/Browser**:  Google Chrome 91.0.4472.114

### Description

Tooltip is in modal-card content.
In modal content has higher priority than modal background.
But tooltip is hidden.

### Steps to reproduce

```html
<html>
  <head>
    <script src="https://unpkg.com/vue"></script>
    <link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">
    <script src="https://unpkg.com/buefy"></script>
  </head>
  <body>
    <div id="app"></div>
    <script>
      new Vue({
        el: "#app",
        mounted() {
          this.$buefy.modal.open({
            hasModalCard: true,
            component: {
              template: `
                <div class="modal-card">
                  <div class="modal-card-head">
                    <div class="modal-card-title">
                      <b-tooltip label="(label)" always>
                        (title)
                      </b-tooltip>
                    </div>
                  </div>
                </div>
              `,
            },
          })
        },
      })
    </script>
  </body>
</html>
```

Save above and open it in a browser.

### Expected behavior

Tooltip does not hide.

### Actual behavior

https://codepen.io/akicho8/pen/JjJBBOb

It may have a relationship #2139 #2940

**Comment by jtommy** [comment]
Try  using append-to-body
