### ISSUE TITLE
[Feature Request]: Support Remaining time progress in Notification (programmatically)

### ISSUE THREAD

**Issue by mouadTaoussi** [buefy/buefy#3532]
### Description
Since the progress bar displaying the remaining time in **Message** and **Notification** components is supported successfully,
**The feature is not yet supported in **Notification** that opens **Programmatically****

### Why Buefy need this feature
 Majority of users will use the Notification component programmatically because of the positioning, login fails ...etc

**Comment by mouadTaoussi** [comment]
@jtommy What do you think?

**Comment by jtommy** [comment]
It's ok for me, not with so high priority but free to add it
