### ISSUE TITLE
[DOCS] API Section: Missing docs about component events

### ISSUE THREAD

**Issue by geeksilva97** [buefy/buefy#3535]
### Description
Some Buefy components emit custom events. Components like Autocomplete emits @select-header and @select-footer when some props are passed as true.

There are some examples with these events in sample code, but there is no detail about these events in **API** section.

This also true for other components.

### Steps to reproduce
1. Open Buefy docs in TagInput
2. Go to API section
3. Note that there is no information about @select-header or @select-footer

### Expected behavior
In my opinion, this information should be clear to developers. Thus, they will extract the maximum power from each component. They will know what a component can do natively and what it cannot.

### Actual behavior
There is no docs.

**Comment by geeksilva97** [comment]
What do you think @jtommy @GMartigny ?

**Comment by jtommy** [comment]
You are right, free to add it

**Comment by geeksilva97** [comment]
> You are right, free to add it

Nice. I will start doing this.
