### ISSUE TITLE
BackTop Component

### ISSUE THREAD

**Issue by zhaojh329** [buefy/buefy#3548]
### Description

Backtop can be used when page content is very long and a shortcut is needed to go back to the top fluently. Usually placed at the right bottom of the page.

![image](https://user-images.githubusercontent.com/28673295/135721794-56dcd850-da52-4430-a0ef-c39c6dc99e5f.png)

**Comment by jtommy** [comment]
You can get inspiration from docs but it's only CSS and HTML
