### ISSUE TITLE
[Feature Request]: Add Buttons Group as Addons

### ISSUE THREAD

**Issue by mouadTaoussi** [buefy/buefy#3549]
### Description
The buttons group is supported in **bulma** but not in **buefy**, it is supposed to be in **buefy**?

![Web capture_5-10-2021_124440_bulma io](https://user-images.githubusercontent.com/50294614/136017180-3a490241-e1a8-4a43-8373-82db12333a5a.jpeg)

### Why Buefy need this feature
- It is exists in **Bulma**.
- Some buttons needs to be grouped like in the example above.

**Comment by mouadTaoussi** [comment]
@jtommy

**Comment by jtommy** [comment]
No, It's only CSS and HTML

**Comment by mouadTaoussi** [comment]
I Have closed it
