### ISSUE TITLE
[Accessibility] Fix keyboard navigation with navbar dropdowns

### ISSUE THREAD

**Issue by radex02** [buefy/buefy#3553]
### Description

Allow tab navigation in navbars' dropdowns. 

For hoverable dropdowns, adding ``tabindex="0"`` on the dropdown's ``a`` (in order for it to work even without a ``href``) seems to somewhat work, but for some reason the ``.is-hoverable`` class is dynamically added/removed which means it doesn't work unless it's been hovered before and not _exited_ since (if that makes sense).

For non hoverable dropdowns, we would also need to add ``tabindex="0"`` on the dropdown's ``a`` and we would have to trigger the dropdown on enter.

Another (probably better) way of doing this would be to allow direct _tabbing_ on the dropdowns inner links (which would require hidding it some other way than with ``display:none`` (which sounds like more like a Bulma problem).

### Why Buefy need this feature

I hope I don't have to justify basic accessibility features in 2021.

**Comment by jtommy** [comment]
@radex02 you are right, can you work on it and make a PR?

**Comment by radex02** [comment]
What I'm unsure about is whether to fix this using CSS at source in Bulma or here with js

**Comment by jtommy** [comment]
Try to make PE here

**Comment by tcitworld** [comment]
On the navbar dropdowns specifically, I partly fixed this in https://github.com/buefy/buefy/pull/3551

**Comment by sermo-de-arboribus** [comment]
When adding 'focus' to the triggers, the Dropdown menu opens when you use the tab key to select the Dropdown, so there is a basic accessibility to this element already.

`<b-dropdown aria-role="menu" :triggers="['click', 'focus']" >`

However, the dropdown items seem to be a problem that I couldn't figure out an accessible fix for. When the dropdown menu is open, I can also use the tab key to navigate through the items, but I can't select one with pressing the enter key, not even if I add an @keyup.enter event listener (which never gets triggered), e. g.:

`<b-dropdown-item aria-role="menuitem" v-for="title in documentationPageTitles" 
              :key="title" @click="documentationSelected(title)" @keyup.enter="documentationSelected(title)">`

I've also tried the @change-Listener on the parent <b-dropdown> component, but that one neither gets triggered when I press the enter key on any of the items.
Just from reading the pull request #3551 I don't see any handling of dropbox item selection, so it seems only to handle the toggling of the dropdown menu, not the selection of individual dropdown items. Without having tried that fix I think that this merge request might be incomplete when it comes to providing full accessibility of the dropdown.

**Comment by Spacarar** [comment]
I think that #3551 is the reason why #3443 is an issue. Datepicker uses dropdown under the hood, but this makes the datepicker require 2 tabs to get to the actual input.
