### ISSUE TITLE
Sidebar breakpoint hides menu item text

### ISSUE THREAD

**Issue by luistrcastro** [buefy/buefy#3556]
### Overview of the problem

- Between 768px and 960px (tablet breakpoint) the side bar is hiding the menu item label

**Buefy** version: 0.9.10
**Vuejs** version: 2.6.14
**OS/Browser**: Chrome

### Steps to reproduce

1. Open this codepen https://codepen.io/elingan/pen/mdVaYbK
2. Remove the reduce attribute, line 9 (HTML)
3. Resize your window

### Expected behavior

- The side bar should reduce or keep the labels.

### Actual behavior

- It keeps the width of a extended side bar but hides the menu item labels.

![Untitled](https://user-images.githubusercontent.com/64997284/137992676-6b314d8f-0c53-4abc-837e-e0f584266b2e.png)

**Comment by jtommy** [comment]
The menu is only a quick example, you should change that style
