### ISSUE TITLE
After selecting an older year in datepicker, cannot scroll back to the latest years 

### ISSUE THREAD

**Issue by aidnurs** [buefy/buefy#3574]
### Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: Chrome

### Description

After selecting an older year in datepicker, user cannot scroll back to the latest years. The problem occurs even in the [documentation](https://buefy.org/documentation/datepicker/)

<img width="140" alt="Screenshot 2021-11-05 at 16 49 48" src="https://user-images.githubusercontent.com/28778542/140499464-61dbb7d7-3aee-4b60-9381-47e2bc96ba8d.png">

### Steps to reproduce

1. choose 1950 for example
2. then try to find and select 2021

### Expected behavior

User should be able to scroll between years

### Actual behavior

User sees only ~10 years above and cannot scroll to the latest years

**Comment by jtommy** [comment]
There is `years-range` prop that you can change as you prefer!
