### ISSUE TITLE
Use Forkawesome instead of FontAwesome

### ISSUE THREAD

**Issue by InfoLibre** [buefy/buefy#3575]
### Description

Forkawesome is a fork of FontAwesome.
https://forkaweso.me

### Why Buefy need this feature

Forkawesome is better than FontAwesome. More icons, the project is more opened to the community requests.

**Comment by jtommy** [comment]
I don't know it but you can use customizing icon pack in your project https://buefy.org/documentation/icon#custom-icon-pack
