### ISSUE TITLE
Browser hangs when doing HTML validation of inputs

### ISSUE THREAD

**Issue by tcitworld** [buefy/buefy#3577]
### Overview of the problem

**Buefy** version: 0.9.11
**Vuejs** version: 2.6.14
**OS/Browser**: Firefox 94 & Chrome 95

### Description
Browser hangs when trying to perform validation. Disabling `use-html5-validation` fixes it.

Possibly related to #3498? Note that #3517 was closed but doesn't appear to be fixed. 

#### Required
* Add a  `required` prop https://codepen.io/tcitworld/pen/MWvVMmX?editors=1011
* Focus the input field (by clicking on it, for instance)

#### Pattern
* Add a `pattern` prop https://codepen.io/tcitworld/pen/qBXozNG?editors=1011
* Enter a special character not allowed

### Expected behavior

Ability to enter text

### Actual behavior

All browser hang **a lot** before validating the field.

**Comment by miroslavgeorgiev** [comment]
Agree with @tcitworld,
Our app broke after update to 0.9.11 due to this one..

**Comment by jtommy** [comment]
The PR only removed a check

**Comment by vetlevo** [comment]
Certain pages in our app broke as well that used input fields in the same way as described above.

**Comment by jtommy** [comment]
@tcitworld It looks a problem relative to `b-field`..

**Comment by jtommy** [comment]
Just released 0.9.12

**Comment by vetlevo** [comment]
> Just released 0.9.12

Thank you for fixing it so quickly!

**Comment by jtommy** [comment]
@vetlevo Also released 0.9.13, because there was an other bug.

**Comment by emielmolenaar** [comment]
Thanks a lot for the quick fix. We had some issues too last week by upgrading to 0.9.11; we are populating the field message via a vuex store (containing error messages) and for some reason (didn't spent too much time on it) the browser hung there too.

**Comment by jtommy** [comment]
@emielmolenaar I'm sorry I didn't check well the PR that added the issue 😞

**Comment by emielmolenaar** [comment]
@jtommy No worries! All good. I did not mean to offend you or something, no need to apologize. Thanks for the hard work!
