### ISSUE TITLE
Bulma modal max width conflict

### ISSUE THREAD

**Issue by amorimfilipe** [buefy/buefy#3585]
### Overview of the problem

**Buefy** version: 0.9.13
**Vuejs** version: 2.6.14
**OS/Browser**: Windows 10

### Description

Conflict with bulma modal container.

### Steps to reproduce

```html
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <!-- Any other Bulma elements you want -->
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>
```

### Expected behavior

modal-content: a horizontally and vertically centered container, with a maximum width of 640px, in which you can include any content 

### Actual behavior

If we create a modal using bulma classes instead of use buefy dialog component, the class `modal-content` has a width of 100% instead of max of 640px.

**Comment by jtommy** [comment]
You can remove `modal-content` using `has-modal-card="false"`
