### ISSUE TITLE
Datepicker range - can't select today if using `new Date()` as `min-date` prop

### ISSUE THREAD

**Issue by miroslavgeorgiev** [buefy/buefy#3595]
### Overview of the problem

**Buefy** version: [0.9.13]
**Vuejs** version: [2.6.14]
**OS/Browser**: MacOS

### Description
https://codepen.io/miroslavgeorgiev/pen/vYJMore
When I'm using datepicker component with some range set by `min-date` and `max-date` props 
I can't select today if it set on `min-date` as:
```
// Datepicker 1
new Date()
```
but can select it when it is set like this:
```
// Datepicker 2
new Date(
  today.getFullYear(),
  today.getMonth(),
  today.getDate()
)
```

Now let see the opposite example when `min-date` is set to be 5 days before today and `max-date` is set to be today.
Seems to work pretty well, no matter if `max-date` is set like:
```
// Datepicker 3
new Date()
```
or
```
// Datepicket 4
new Date(
  today.getFullYear(),
  today.getMonth(),
  today.getDate()
)
```

I'm using date helpers utils in my whole application like:
```
this.$utils.date.today.toDate()
```
so I prefer use it instead setting everytime:
```
new Date(
  today.getFullYear(),
  today.getMonth(),
  today.getDate()
)
```
when I have to set today on `min-date` prop as I don't have any issues when I have to set today on `max-date` prop with it.

### Expected behavior

I expect no matter if `min-date` is set as:
```
// Datepicker 1
new Date()
```
or
```
// Datepicker 2
new Date(
  today.getFullYear(),
  today.getMonth(),
  today.getDate()
)
```
to be able to select today.

### Actual behavior
I can't select today if `min-date` is set like:
```
// Datepicker 1
new Date()
```

### Steps to reproduce
https://codepen.io/miroslavgeorgiev/pen/vYJMore

**Comment by jtommy** [comment]
@miroslavgeorgiev probably it's a problem about time part

**Comment by miroslavgeorgiev** [comment]
@jtommy - I can't say what exactly is causing this and probably you're correct that it is something related to time part.

But I think in this situation the Datepicker component is not exactly working as intended.
Probably it needs at least some mentioning in the documentation describing this scenario and proposing solution with:
```
new Date(
  today.getFullYear(),
  today.getMonth(),
  today.getDate()
)
```
instead of just:
```
new Date()
```
if the user is facing issue with selecting today.

Feel free to close the ticket as I've made an workaround for my case but documentation update would be great.

**Comment by jtommy** [comment]
@miroslavgeorgiev min and max example already use `new Date(year, month, date)`, indeed it works well https://buefy.org/documentation/datepicker#range

**Comment by miroslavgeorgiev** [comment]
@jtommy - I see they use it in the exampe, but the docu is not mentioning that you should use date exactly this way, and not like just `new Date()`.
But I think you got the point - keep up the good work 👍

**Comment by jtommy** [comment]
@miroslavgeorgiev probably you are right, thanks!
