### ISSUE TITLE
Datepicker alignment problem

### ISSUE THREAD

**Issue by ismet** [buefy/buefy#360]
I have a `b-table` and the right-most column contains a `b-datepicker`. The table's width is 100% of window's width. If I click on the datepicker to select a date, the half of the date box cannot be seen, since it is not auto aligned.

How can I fix it?
![image](https://user-images.githubusercontent.com/109025/31306156-896afc96-ab52-11e7-9d67-6dbd9ff944a3.png)

**Comment by jtommy** [comment]
I think it's the same issue https://github.com/rafaelpimpa/buefy/issues/292.
We'll try to look about if Bulma doesn't fix it

**Comment by wanxe** [comment]
For the moment you can use a custom class for your element:
overflow: auto !important

**Comment by tanhs** [comment]
@jtommy 
I tried to put overflow: auto !important to test one by one from the most outter to inner tags without success.
eg.

<div class="datepicker control" style="! overflow: auto !important; ">

**Comment by wanxe** [comment]
@tanhs can you provide an fiddle or codepen with the simpliest example? Thanks :)

**Comment by jtommy** [comment]
Same https://github.com/buefy/buefy/issues/292
