### ISSUE TITLE
Table checkbox action slow response

### ISSUE THREAD

**Issue by ivolvicente** [buefy/buefy#3600]
Hello everyone, 

I have a table with at least 55 columns, and half of that columns have edit mode inline with datepickers, selectboxes and autocompletes.

With a few rows, there are no problem, but when the number of rows grow, the checkbox takes more than 1 second to change its state.

I made an example on codepen based on your documentation, it was required to add an absurd quantity of columns to replicate the behavior, but that shows a delay on mouse click and state change.

[CodePen template](https://codepen.io/ivolvicente/pen/rNzXBeB)

The columns are required to exist, some can be hidden to reduce the number of columns, but some users want to have all of them available.

Thanks

**Comment by jtommy** [comment]
@ivolvicente did you try to use Object.freeze?
You don't need reactivity on data array using table

**Comment by potraike** [comment]
Hello @jtommy, I work closely with @ivolvicente on this issue.
Thank you for your quick reply on this matter.
I tryied your suggestion to freeze the data array sent to the table but it didn't affect the behaviour.
Moreover, I took a performance snapshot when clicking on a checkbox and it execute the flushCallbacks from Vue, which in turn executes an enormous amount of functions which I don't understand fully.
Do you have more ideas?

Thanks for your support

**Comment by jtommy** [comment]
@potraike can you share your trace/snapshot?

**Comment by potraike** [comment]
[Profile-20211126T115236.zip](https://github.com/buefy/buefy/files/7608576/Profile-20211126T115236.zip)
I just saved from chrome dev tools in json format. 
Hope it helps!

**Comment by jtommy** [comment]
@potraike Surely table component needs an improvement about performance but your need is a little bit "extreme".
At the moment you should use a simple HTML table

**Comment by potraike** [comment]
ok thank you @jtommy, we will try other solutions before going to plain old HTML table.
Best Regards.

**Comment by ivolvicente** [comment]
Thanks @potraike for your follow up and shared more details about it.

Thanks @jtommy for your time on this subject.

Issue closed, no solution at this time.
