### ISSUE TITLE
Table row transistion on hover

### ISSUE THREAD

**Issue by AniaKru95** [buefy/buefy#3601]
Hi,

I would like to ask, is it possible to add a transition for specific row (increase font a bit and add shadow to row border) when row is hovered?

Please let me know.

**Comment by jtommy** [comment]
You should be able to do it applying a style to `tr`

**Comment by AniaKru95** [comment]
Thanks for your reply.
I used ::v-deep to add transition in a scope style.
```
<style scoped>
.b-table::v-deep tr{
    transition: font-size .2s, box-shadow 0.2s
}
.b-table::v-deep tr:hover{
  font-size: 17px;
  box-shadow:  0 0 3px 3px whitesmoke;
}
</style>
```
Above code works perfecty but it is applied for all <tr>.
I would like to use this style only for <tr> in <tbody>
How can I do that?

.b-table::v-deep tbody::v-deep tr:hover  <- add tbody selector does not work

**Comment by jtommy** [comment]
you can set a class to table in order to apply a style only its children

`<b-table class="myclass">`
