### ISSUE TITLE
Nuxt 3 problem.

### ISSUE THREAD

**Issue by qnkokurami** [buefy/buefy#3602]
### Overview of the problem

`Nuxt CLI v3.0.0-27296423.f3082ca                                                                                                                                                                     22:47:20
                                                                                                                                                                                                     22:47:20
  > Local:    http://localhost:3000/
  > Network:  http://192.168.0.92:3000/
  > Network:  http://172.28.64.1:3000/

i Vite warmed up in 1101ms                                                                                                                                                                           22:47:24

 WARN  [vite:css] @charset must precede all other statements                                                                                                                                         22:47:28
1  |  /*! Buefy v0.9.13 | MIT License | github.com/buefy/buefy */
2  |  @charset "UTF-8";
   |   ^
3  |  .is-noscroll {
4  |    position: fixed;

 WARN  [vite:css] @charset must precede all other statements                                                                                                                                         22:47:29  
1  |  /*! Buefy v0.9.13 | MIT License | github.com/buefy/buefy */
2  |  @charset "UTF-8";
   |   ^
3  |  .is-noscroll {
4  |    position: fixed; (x2)

√ Vite server built in 12519ms                                                                                                                                                                       22:47:35
√ Nitro built in 235 ms                                                                                                                                                                              22:47:36
__vite_ssr_import_0__.default.use is not a function
  at $id_79d75783 ([PATH}/.nuxt/dist/server/server.mjs:961:31)
  at async __instantiateModule__ ([PATH}/.nuxt/dist/server/server.mjs:21855:3)
__vite_ssr_import_0__.default.use is not a function
  at $id_79d75783 ([PATH}/.nuxt/dist/server/server.mjs:961:31)
  at async __instantiateModule__ ([PATH}/client/.nuxt/dist/server/server.mjs:21855:3)`

### Description

Error when using with Nuxt 3

### Expected behavior

To not get a error

**Comment by jtommy** [comment]
Buefy doesn't support Vue 3
