### ISSUE TITLE
Date picker unexpected behaviour

### ISSUE THREAD

**Issue by msravi16** [buefy/buefy#3603]
Hi,
Datepicker css is not working properly, I have included all css files properly

![image](https://user-images.githubusercontent.com/16087458/143734116-a7253308-1635-4ecf-a8d8-902c25046631.png)

I am not getting why it is behaving like this.
Is there any additional CSS file for date picker?

**Comment by jtommy** [comment]
You are missing something, please reproduce it condesandbox or similar

**Comment by msravi16** [comment]
Hi, 
Thanks for quick reply, I checked with sandbox example it is working fine.
I am developing a library component, when I include the datepicker in that component it is behaving like this.

In my index.html
![image](https://user-images.githubusercontent.com/16087458/143734455-586da56a-12e5-4006-9e35-5d8c053c62f2.png)

In Vue SFC

![image](https://user-images.githubusercontent.com/16087458/143734499-7fc82345-c8f2-4d98-b95c-3045cdf32a99.png)

Included all files correctly.

**Comment by jtommy** [comment]
Where is Buefy CSS?

**Comment by msravi16** [comment]
Hi jtommy,
Thanks for correcting me.
I was using only Bulma earlier, to simplify my work I started using Buefy. I missed it while adding buefy.

You guys have done wonderful work.
Buefy is very easy to start with minimal code.
