### ISSUE TITLE
b-upload HTML5 validation not working consistently

### ISSUE THREAD

**Issue by l1bra2013** [buefy/buefy#3605]
### Overview of the problem

**Buefy** version: 0.9.13
**Vuejs** version: 2.x

### Description

When using b-upload with the accept field, if an invalid file is selected, the input field is sometimes marked as valid despite being empty.

### Steps to reproduce

1. Setup b-upload component using parameters `required` and `accept`
2. Select an invalid file - doesn't work - despite file not being present, the form is still considered valid
3. Select a valid file - works properly - form can be submitted
4. Select an invalid file - works properly - form cannot be submitted

### Expected behavior

Invalid files don't allow form submission

### Actual behavior

Form is submitted despite having no file selected. Might be related to the value watcher (https://github.com/buefy/buefy/blob/dev/src/components/upload/Upload.vue#L82). Since the value doesn't change when the file is initially unset, the native input has a file set despite the Buefy input having no file set due to validation failure. Simple fix may be to always set value and ref input values to null here (https://github.com/buefy/buefy/blob/dev/src/components/upload/Upload.vue#L108).

**Comment by jtommy** [comment]
@l1bra2013 please make a PR 😉

**Comment by l1bra2013** [comment]
PR pushed - https://github.com/buefy/buefy/pull/3608
