### ISSUE TITLE
Steps component is always centered

### ISSUE THREAD

**Issue by howeguo** [buefy/buefy#3616]
### Description

I want to know if its possible to custom the position of steps component, for now its always center,
But in some cases, I want to leave the first step is on the left, and the last step is on the right
Thanks
![image](https://user-images.githubusercontent.com/3302533/146180654-419f6e4f-f345-4f7c-888f-d1ae1aea8e79.png)

**Comment by jtommy** [comment]
Did you try to edit the default classes?
