### ISSUE TITLE
Null values are always sorted to the bottom in the table

### ISSUE THREAD

**Issue by Ryan-Case-SingleStone** [buefy/buefy#3618]
### Overview of the problem

**Buefy** version: [0.9.13]
**Vuejs** version: [2]
**OS/Browser**: Chrome

### Description

When there are null values under a sortable column in a table, sorting the column always results in the null values remaining in their same position at the bottom of the table. The expected behavior would be that these values would be at the top when sorting in descending order and at the bottom when sorting in ascending order.

**Comment by geeksilva97** [comment]
Hi, @Ryan-Case-SingleStone. How can we reproduce this?

**Comment by Ryan-Case-SingleStone** [comment]
@geeksilva97 Here is a quick CodePen I spun up to reproduce the issue. Essentially, if you have a single sort column that has any null values in it, those values will always be at the bottom when the column is sorted.

https://codepen.io/ryan-case-singlestone/pen/xxXdWEx

**Comment by Ryan-Case-SingleStone** [comment]
I think the `sortBy` in the Table component needs to be modified to achieve this. These lines seem to be the root of the problem.
```
                    if (!newA && newA !== 0) return 1
                    if (!newB && newB !== 0) return -1
```
This could be changed to the below to resolve the issue.
```

                    if (newB && (!newA && newA !== 0)) return isAsc ? 1 :  -1
                    if (newA && (!newB && newB !== 0)) return isAsc ? -1 : 1
```

**Comment by jtommy** [comment]
@Ryan-Case-SingleStone please make PR

**Comment by Ryan-Case-SingleStone** [comment]
@jtommy there was a type with the `isNil` helper method, so this bug did not get resolved in the latest release. I just opened a PR to resolve it #3628
