### ISSUE TITLE
Table details data is mixed up with siblings (multiple rows opened, filtering table data)

### ISSUE THREAD

**Issue by mcmule** [buefy/buefy#3632]
### Overview of the problem

**Buefy** version: 0.9.14 (initially found using 0.9.4)
**Vuejs** version: 2.6.14 (initially found in 2.6.11)
**OS/Browser**: Chrome

### Description

Here is the context:
- you have a b-table, with detailed rows; let's say it's a table of persons.
- properties of a row are provided through table's data (in our example: the name of each person)
- but some properties displayed in details are only fetched when you unfold a row (in our example, it could be bank data, SSN, etc)
- you can filter the table's data, for instance by name.

To get the bug:
- unfold at least 2 rows
- filter data (table's data)
- the remaining detailed rows will contain the wrong data, in our example, detailed information (SSN) will be mixed between still displayed details

### Steps to reproduce

This can be easily seen in a CodePen I have created: https://codepen.io/mcmule/pen/oNGyRNa

1) Both rows are unfolded
2) Look at the random value generated in both rows (this random generation is here too make like "we have fetched unique data for this person in our backend when unfolding the row)
3) Uncheck the filter on top (it hides row with id = 1)
4) You will see only one row: it's the second one (John), the id is still ok **BUT it holds the random value of Jesss)**

### Expected behavior

I expect each component to still display its own data, and not the data of a sibling that has disappeared since.

### Actual behavior

Properties of my child component are maintained (the id and name), but not the data it has fetched itself.

----------

I guess this has to deal with some "re-use" of components, but I don't see how to workaround this.

This is causing a lot of issues in the application I'm working on. I'll gladly accept any help figuring out if this is indeed a bug, but also how to workaround it.

**Comment by mcmule** [comment]
Quick note: adding a `key` to the component helps, but this re-triggers `mounted`, which is a problem (it will fetch the data once again from the API, which is not an acceptable solution here)

**Comment by jtommy** [comment]
@mcmule https://github.com/buefy/buefy/blob/5a567365f9742a5c49c8d0c3df6ddbe36b47feb7/src/components/table/Table.vue#L298

The current code provides a `v-if` instead of `v-show` as you would prefer but I don't see it as a real issue, to be honest. 
You could avoid it using a local cache, for example, you call the API only the first time that the user opens the detail and the other times get data from the cache.
I might change it (it would be a breaking change) but I think there are a few workarounds that you can use 😉

**Comment by mcmule** [comment]
Thanks for the answer @jtommy !

I'm currently finishing a workaround based on caching data, it's just quite complex because I have nested components, and all these components have the same problem (asynchronously fetching data based on user id). So for each one I'm deciding whether to cache it, or to just use a key and have a forced reload. 

But this does the job! Happy to see you came to the same workaround.

Of course, I'd have been more happy with a magical solution based on a non documented property :trollface: 

> Also, detail-key prop doesn't exist but you should use custom-row-key.

Haha, nice one, I don't know how that ended up here ;)
