### ISSUE TITLE
class "b-tooltips" doesn't work with tooltips inside (Vue2)

### ISSUE THREAD

**Issue by floflo711** [buefy/buefy#3646]
Hello,

### Overview of the problem

**Buefy** version: [^0.9.13]
**Vuejs** version: [^2.6.11]
**OS/Browser**: Firefox 96.0.2 (64 bits)

### Description
I had the problem about 1 year ago, the problem is still there. It's not big issue but it's not normal it's not working.

So if I take the example from Buefy https://buefy.org/documentation/tooltip, the tooltips should be spaced like the class buttons with button. But they aren't spaced.

### Steps to reproduce

1. Copy and paste the example (or any from  [)](https://buefy.org/documentation/tooltip)
`
 <section class="b-tooltips">
        <b-tooltip label="Text is dashed" dashed>
            Simple text
        </b-tooltip>

        <b-tooltip label="Maybe you like a little animation"
            position="is-bottom"
            :animated="false">
            <b-button label="No animation" />
        </b-tooltip>

        <b-tooltip label="You prefer dark?"
            type="is-dark"
            position="is-bottom">
            <b-button label="Dark" />
        </b-tooltip>

        <b-tooltip label="Or light?"
            type="is-light"
            position="is-bottom">
            <b-button label="Light" />
        </b-tooltip>

        <b-tooltip label="I'm never closing" always>
            <b-button label="Always" />
        </b-tooltip>

        <b-tooltip label="I'm square"
            position="is-bottom"
            square>
            <b-button label="Square" />
        </b-tooltip>

        <b-tooltip label="You love the light variant, dont you?"
            type="is-primary is-light"
            position="is-bottom">
            <b-button label="Primary light variant" />
        </b-tooltip>
    </section>
`
2. Compile code
3. See that tooltips aren't spaced

### Expected behavior
Each tooltip must be spaced, between each, just like buttons

### Actual behavior
tooltips aren't spaced. The only way to space them is to put margin left or right (with Bulma class)

![image](https://user-images.githubusercontent.com/56739674/150934403-16c3d7c5-2c82-4c93-98f1-e0601bcb530d.png)

**Comment by jtommy** [comment]
You are right but probably it needs a full refactor or develop a directive to show a tooltip

**Comment by jtommy** [comment]
@floflo711 `b-tooltips` is in the doc code, you can copy and paste in your project
