### ISSUE TITLE
Autofill of inputs by browser is annoying, how to do?

### ISSUE THREAD

**Issue by floflo711** [buefy/buefy#3647]
Hello, from [here](https://laracasts.com/discuss/channels/vue/autocomplete-off-not-working), seems like the problem is still here

I am doing a project, and I have my inputs being autofilled by saved  credentials in the browser, which is annoying.

Like the link above said, seems like the browser detect something and autofill the input.

In my example, I have a user and i want to fill inputs with username, password.

Impossible to have my fields empty, they keep being filled by the browser. I tried changing the name of v-model, the name of the input, the id, changed the label, but nothing works.

When I add a user, my input username and password are filled, even when i name them differently and it's annoying

Autocomplete = off doesn't work at all.

Does anyone have a solution? I think that problem might not even be in Buefy only, but in general

Thanks

**Comment by floflo711** [comment]
[Here](https://support.iclasspro.com/hc/en-us/articles/218569268-How-Do-I-Disable-or-Clear-AutoFill-AutoComplete-Information-), it's not quite a solution we can control but the user must disable by itself the option.

I don't know what we can do from our side

**Comment by fabiofdsantos** [comment]
@floflo711

This issue isn't related with Buefy.

Check this: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
