### ISSUE TITLE
The Datepicker first day of the week should depend on locale

### ISSUE THREAD

**Issue by marcinkunert** [buefy/buefy#3648]
### Description

![image](https://user-images.githubusercontent.com/2963232/150951760-4a4fa883-5e70-4fbc-b478-6210a50f817f.png)

Currently, the default first day of the week is set to Sunday. This may be valid for some countries, but isn't for others. For me, it's always pretty confusing. 

### Why Buefy need this feature

According to [wiki:Week](https://en.wikipedia.org/wiki/Week) the ISO standard say the first day of the week is Monday but setting it would make the other half of the world unhappy. In my opinion, this should depend on the current locale. I'm aware that there is a `first-day-of-week` attribute, and it could be used to override the default value. This issue is about the default value in first place.

**Comment by NicoHood** [comment]
To me it looks like a pretty good support. At least for the most important browsers. Needing to hardcode it or adding a special setting would make the application using this library more confusing.
https://caniuse.com/mdn-javascript_builtins_intl_locale_weekinfo

**Comment by jtommy** [comment]
I can support it but only a few browser versions will use it

**Comment by NicoHood** [comment]
That'd be great! :)
