### ISSUE TITLE
Datetimepicker is resetting with time '23:59'

### ISSUE THREAD

**Issue by Mars073** [buefy/buefy#3649]
### Overview of the problem

**Buefy** version: 0.9.14
**Vuejs** version: 2.6.14
**OS/Browser**: Windows 10 - Firefox

### Description
I tried to put a date in a project and realised that the date was resetting, I thought it was a shadom dom bug, but the problem is also in the documentation.

### Steps to reproduce
1. Go on [datetimepicker](https://buefy.org/documentation/datetimepicker#editable-non-readonly)
2. Scroll to `Editable (non readonly) ` section
3. be sure to have a "locale" format with 24 hours
4. Select a date like the 14th fev 💘
5. set the time to 23:59
6. unfocus the component
7. the date disappears ✨

### Expected behavior
The date is still set to the value indicated

### Actual behavior
The date is reset after "change"

![image](https://user-images.githubusercontent.com/18756261/151165144-d1392ace-426a-4751-b710-2135bf6f64db.png)

**Comment by jtommy** [comment]
@Mars073 are you sure? Just tried but no issue (Windows 11 - Firefox)

https://user-images.githubusercontent.com/8029488/151514401-5053730b-b09e-403a-bbaf-45076dcab00e.mp4

**Comment by dagnelies** [comment]
I can reproduce it. If you pick it with the calendar, it's just fine, but the parsing of the date is somehow screwed ...and apparently it's just the tip of the iceberg!

Using the `fr-FR`, try to **type** or copy/paste:

=> `14/02/2022, 23:00` => OK
=> `14/02/2022, 23:59` => error
=> `11/02/2022, 23:00` => OK
=> `11/02/2022, 23:59` => `02/11/2022, 23:59` ?!?!? 😆 

...note that this occurs only and exactly for "23:59" ...not "23:58" or anything else. Definitely something fishy in the parsing.

**Comment by Mars073** [comment]
> @Mars073 are you sure? Just tried but no issue (Windows 11 - Firefox)
> 2022-01-28-09-37-26.mp4

I forgot to mention that since this was the "editable" mode, I changed it directly in the input and not on the dropdown
