### ISSUE TITLE
Tag Input with autocomplete, x-offset for dropdown increments if append-to-body set

### ISSUE THREAD

**Issue by oddjobz** [buefy/buefy#3651]
### Overview of the problem

**Buefy** version: [0.9.14]
**Vuejs** version: [2.6.11]
**OS/Browser**: Linux/Chrome (latest)

### Description

Create a taginput item with autocomplete "inside" a model dialog, as it's inside a dialog add "append-to-body" otherwise it will be cut-off;
```html
        <b-taginput
            append-to-body
            v-model="address_list"
            autocomplete
            max-height="25em"
            :data="addressBook"
            @add="tagInputAdd"
            @remove="tagInputDel"
            @typing="getEmailAutocomplete">
            <template v-slot="props">
                <b>{{props.option}}</b>
            </template>
            <template #empty>
                No matching addresses
            </template>
```
When you enter items normally, outside of a dialog and without "append-to-body", the drop-down always appears left justified to the left of the entry box, so you get the full width of the entry box for the drop-down. When append-to-body is added inside a dialog, the drop-down appears under the most recent tag, so you get a part of the width of the entry box for the width of the drop-down.  Depending on the tag width, you can end up with a drop-down that's only a few characters wide when the cursor approaches the right hand side of the entry box.

### Steps to reproduce

As described.

### Expected behavior

Drop down for autocomplete should always be the width of the entry box.

### Actual behavior

Dropdown width decreases as entries are added. Effective width is right hand margin - offset of most recent entry.

![dropdown](https://user-images.githubusercontent.com/7396121/151841168-ddc1a6bb-5b4e-45af-9da8-dc71e9a2c1b7.png)

**Comment by highoncarbs** [comment]
Any fix for this ?

**Comment by oddjobz** [comment]
My fix was to move the entry box to the top of the dialog and change the drop-down to it didn't extend beyond the bounds of dialog, then to remove the append-to-body. Probably not the fix you're looking for (!) but that was the only way I could get it to behave ...

**Comment by highoncarbs** [comment]
Yep , Doing the same thing for now. 🙃

@rafaelpimpa any suggestions
