### ISSUE TITLE
Field click event in Clockpicker does not close dropdown Datepicker

### ISSUE THREAD

**Issue by Uka4me** [buefy/buefy#3652]
### Overview of the problem

**Buefy** version: [0.9.14]
**Vuejs** version: [2.6.11]
**OS/Browser**: Win\Chrome, Firefox, Edge

### Description

If you install two separate Datepicker and Clockpicker components on the same page, then the Clockpicker component will not allow you to close the calendar when focus is lost.

### Steps to reproduce

1. Place two components on the page
2. Click on the Datepicker to open the dropdown
3. Click on the Clockpicker component. Dropdown Datepicker won't close.

If the steps are performed in reverse order, then everything works.

### Actual behavior
[CodePen template](https://codepen.io/uka4me/pen/jOaWRvM)

Recorded example of reproducing the problem:

![Анимация1](https://user-images.githubusercontent.com/4368590/151927437-6b423489-bea6-45c0-9a8a-5ebc05bb7630.gif)

**Comment by geeksilva97** [comment]
I can start an investigation and figure out what is happening.

**Comment by s-nesbigall** [comment]
Hi,
I think I know waht happens here:

- Date- and Clockpicker use a Dropdown.
- Dropdown registers a global click event to close, when user clicks outside: (document.addEventListener('click', this.clickedOutside))
- Clockpicker uses:  @click.native.stop="toggle(true)"

So if you click on the Clockpicker the dropdown appears, but the event gets stoped. The global click event listener will not trigger.
As far I could see it works for DatePicker because it has a local Method onInputClick (@click.native="onInputClick") and there it only aborts the event if the dropdown is already active.

**Comment by geeksilva97** [comment]
> Hi, I think I know what happens here:
> 
> * Date- and Clockpicker use a Dropdown.
> * Dropdown registers a global click event to close, when user clicks outside: (document.addEventListener('click', this.clickedOutside))
> * Clockpicker uses:  @click.native.stop="toggle(true)"
> 
> So if you click on the Clockpicker the dropdown appears, but the event gets stoped. The global click event listener will not trigger. As far I could see it works for DatePicker because it has a local Method onInputClick (@click.native="onInputClick") and there it only aborts the event if the dropdown is already active.

It makes sense. Would you like to open a Pull Request?

**Comment by s-nesbigall** [comment]
Hi,

sorry I can't:
- I forged the repo, but tests are failing
- I tried to commit changes, but pre-commit hooks are failing

My suggested changes are in Clockpicker.vue

`@click.native.stop="toggle(true)"` changed to `@click.native="onInputClick"`

And I added a component method:

        /*
         * Avoid dropdown toggle when is already visible
         */
        onInputClick(event) {
            if (this.$refs.dropdown.isActive) {
                event.stopPropagation()
            }
        }

These changes are made analogous to the DatePicker.vue.

**Comment by s-nesbigall** [comment]
Ok, I managed to do it directly in Github.
