### ISSUE TITLE
The unselectableDaysOfWeek option for DateTimePicker component is missing.

### ISSUE THREAD

**Issue by re2005** [buefy/buefy#3653]
Noticed that the `BDatepicker` has the option `unselectableDaysOfWeek`

But the same feature is missing on the `BDatetimepicker` component.

Would be great to have it there.

Thanks

**Comment by jtommy** [comment]
You can pass it to `datepicker` object prop

**Comment by re2005** [comment]
@jtommy sorry to ask this here, but I can't a way to limit the HOURS inside the select.

Lets, say only accept time from 9:00 to 17:00.

Thanks

<img width="418" alt="Screenshot 2022-02-04 at 10 20 10" src="https://user-images.githubusercontent.com/2920357/152536034-a5ccb21f-9486-4008-a61f-15c28455018e.png">

**Comment by re2005** [comment]
Actually found this:

https://user-images.githubusercontent.com/2920357/152540436-f061e4b6-3184-4d75-8b29-be0d65e4ef1e.mov

May be something wrong with my code, or anyone else also having the same issue.

**Comment by jtommy** [comment]
Do you mean the autoclose on first open?

**Comment by jtommy** [comment]
Check out `minDatetime` and `maxDatetime`
