### ISSUE TITLE
[documentation] CodePen links broken

### ISSUE THREAD

**Issue by scheinercc** [buefy/buefy#3662]
### Overview of the problem

**Buefy** version: 0.9.14

**OS/Browser**: tested with Firefox (98.0b2) and Chrome (stable)

### Description

Any CodePen link in the documentation ends up on https://codepen.io/pen?layout=right

### Steps to reproduce

1. Go to https://buefy.org/documentation/breadcrumb
2. On the first code example click on the CodePen link
3. In Chrome the new tab loads https://codepen.io/pen/define/ before redirecting to https://codepen.io/pen?layout=right, Firefox goes to https://codepen.io/pen?layout=right right from `about:blank`

### Expected behavior

The pen includes the code example.

### Actual behavior
An empty pen opens.

**Comment by jtommy** [comment]
It's not the first time, maybe a temporary issue by codepen

**Comment by scheinercc** [comment]
I'll keep an eye out!

**Comment by quezo** [comment]
We just released a bug fix for this on CodePen. All seems to be working again.

**Comment by jtommy** [comment]
@quezo cool, thanks
