### ISSUE TITLE
Add Search feature for the Docs

### ISSUE THREAD

**Issue by Chipsnet** [buefy/buefy#3667]
### Description

Add a search function to Buefy documents.

### Why Buefy need this feature

Buefy is a very useful and clean component, but the lack of search makes it very difficult to use.
For this reason, I would like to see a search box feature in the documentation.

Duplicate of #1893

**Comment by emielmolenaar** [comment]
Don't get me wrong, searching the docs would be great. But "very difficult to use" seems a bit exorbitant to me 😃

**Comment by foufrix** [comment]
this issue can be closed, there is now a search bar thanks to @Mars073 🙏

**Comment by Chipsnet** [comment]
Thanks for all contributors!
