### ISSUE TITLE
Add Font Awesome v6 support

### ISSUE THREAD

**Issue by rajkumartreads** [buefy/buefy#3668]
## Description

Currently, Buefy supports FontAwesome v4 and v5.
FontAwesome v6.0.0 was released on Feb 7, 2022.

## FontAwesome v6 overview [A few points from [documentation](https://fontawesome.com/docs/web/add-icons/how-to)]

Style | Availability | Style class | @font-face weight 
-- | -- | -- | -- | 
Solid | Free Plan | fa-solid | 900 
Regular | Pro Plans only | fa-regular | 400 
Light | Pro Plans only | fa-light | 300 
Thin | Pro Plans only | fa-thin | 100 
Duotone | Pro Plans only | fa-duotone | 900 
Brands | Free Plan | fa-brands | 400 

### Aliases
But we wanted to make sure not to break your existing code, so we made aliases for renamed icons to allow them to work with either the old or new names.

And you can use the old or new name for styles as well. So you can still use `fas`, `far`, `fal`, `fad`, `fab`, and have `fat` be the new Thin!

## Why Buefy need this feature

Adding official support to FontAwesome v6 would help new projects to adopt Buefy with ease.
Moreover, FontAwesome 6 contains 7000+ new icons with new style options.

**Comment by CobraClutch** [comment]
It seems like the sizing is wonky when using SVG+JS method. See pen here:
https://codepen.io/cobraclutch/pen/jOaKEmG

**Comment by fracz** [comment]
Ran into the same issue and even prepared a code sandbox before I saw this (closed??) issue. It may help, maybe.

https://codesandbox.io/s/buefy-sidebar-forked-x3yv38?file=/src/App.vue

**Comment by TheEvilCoder42** [comment]
Same issue, I solved it (temporarily) by setting the respective sass variables:
```
$icon-svg-width: 1rem
$icon-svg-height: 1rem
```
(Or `em` if that better suits you)

**Comment by scheinercc** [comment]
Related to this? https://github.com/FortAwesome/Font-Awesome/issues/18663#issuecomment-1160205450
