### ISSUE TITLE
DateTimePicker + FA6 is broken

### ISSUE THREAD

**Issue by rluisr** [buefy/buefy#3675]
### Overview of the problem

**Buefy** version: 0.9.16
**Vuejs** version: 2.6.14
**OS/Browser**: 98.0.4758.102

### Description

An icon sticks out from input after upgrade font awesome 6 and buefy v0.9.16.
Before the upgrade, no issue was found.

### Steps to reproduce

```html
<b-field>
  <b-datetimepicker
    icon="calendar-plus"
    icon-pack="fas"
  />
</b-field>
```

### Expected behavior

Fit with input like this.

![スクリーンショット 2022-02-21 3 13 09](https://user-images.githubusercontent.com/7776462/154857523-610dccf7-dded-426d-a982-876250145af1.png)

### Actual behavior

![スクリーンショット 2022-02-21 3 00 57](https://user-images.githubusercontent.com/7776462/154857534-73a125a3-56b5-4378-9b46-dd6dc463ed37.png)

I tried to implement it on CodePen to make things easier for you, but I couldn't find a CDN for fontawesome-svg-core.

**Comment by jtommy** [comment]
I added only the new icon pack, I don't think it broke something..

**Comment by sgarner** [comment]
The sizing of icons is affected in many places with FA6 + Buefy, and not specific to `DateTimePicker`.

See also https://github.com/buefy/buefy/issues/3668#issuecomment-1048133105

**Comment by erenbertr** [comment]
For now I "solved" this issue with:

`.icon svg {
  width: 1em;
  height: 1em;
  max-width: 80%;
  max-height: 80%;
}`
