### ISSUE TITLE
[Table] Default backend sort behaviour broken

### ISSUE THREAD

**Issue by emielmolenaar** [buefy/buefy#3676]
### Overview of the problem

**Buefy** version: [0.9.16]
**Vuejs** version: [2.6.14]
**OS/Browser**:

### Description

When using backend sorting, the payload of the @sort event always contains "asc" as sorting direction. The icons in the header are also broken.

### Steps to reproduce

1. Go to https://buefy.org/documentation/table/#async-data
2. Click the "Vote count" header a few times for example
3. The columns stays sorted in ascending order, and there is no icon

### Expected behavior

The data in the table should be ordered in ascending or descending order when clicking on the same header a few times.

### Actual behavior

The columns stays sorted in ascending order, and there is no icon.

**Comment by woodcoal** [comment]
我也发现了同样的问题，以前版本正常，升级到 0.9.15/16 都出现错误。
初略的看了下代码，应该是 Table.vue 中 sort 函数未设置 currentSortColumn 引起的。
后台排序时，点击排序后未将当前点击的列作为当前排序列，导致点击的列无法正确的识别升序还是降序

解决办法：
open `buefy/src/components/table/Table.vue` file
find line `sort` function about line **1006**

```
                if (!this.firstTimeSort) {
                    this.$emit('sort', column.field, this.isAsc ? 'asc' : 'desc', event)
                }
                if (!this.backendSorting) {
                    this.doSortSingleColumn(column)
                    this.currentSortColumn = column
                }
```

change to:
```
                if (!this.firstTimeSort) {
                    this.currentSortColumn = column
                    this.$emit('sort', column.field, this.isAsc ? 'asc' : 'desc', event)
                }
                if (!this.backendSorting) {
                    this.doSortSingleColumn(column)
                    this.currentSortColumn = column
                }
```

重新编译，问题解决，但是至于是不是会影响多列排序，暂时未调试，原则上应该没有问题。
