### ISSUE TITLE
Documentation: direct links are broken

### ISSUE THREAD

**Issue by Thaurin** [buefy/buefy#3678]
### Overview of the problem

**Buefy** version: -
**Vuejs** version: -
**OS/Browser**: Latest Chrome

### Description

Direct links to Buefy's documentation seem to be broken.

### Steps to reproduce

1. Go [buefy.org](https://www.buefy.org)
2. Click on Documentation on the right
3. Reload the page
4. Or simply [following this link](https://buefy.org/documentation/button)

### Expected behavior

See the documentation the URL is pointing to.

### Actual behavior

I get a 404, with a "Page not found" dialog:

> Page Not Found
> Looks like you've followed a broken link or entered a URL that doesn't exist on this site.
> Back to our site
> If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

**Comment by Thaurin** [comment]
I use the [I'm feeling lucky](https://chrome.google.com/webstore/detail/im-feeling-lucky/cnlabakikmdekpfaflaihcepfkjopgll?hl=en) Chrome extension and I used to simply hit Control-T, backslash, tab and type "Buefy button" to go straight to that page. This puts extra seconds to this workflow.

**Comment by jtommy** [comment]
Just fixed!

**Comment by Thaurin** [comment]
Thanks!
