### ISSUE TITLE
Better a11y: correct usage of role="tablist" and role="tab" for Tabs

### ISSUE THREAD

**Issue by mateuswetah** [buefy/buefy#3685]
### Overview of the problem

I've been doing some tests with the [Axe Dev Tools](https://www.deque.com/axe/devtools/) extension. It does a pretty good job on pointing accessibility errors. While I think Buefy has improved enormously in the last years regarding this topic, the reports shows that there are some misuse of Aria attributes, so we have some work to do! This is the third of a series of small issues that I am raising to cover the ones that I understand. I am by no means an expect on the topic, so would appreciate reviews and comments.

**Buefy** version: 0.9.17
**Vuejs** version: 2.6.3
**OS/Browser**: Chrome/Linux

### Description

The Tabs component has a `role="tablist"` in its `<nav>` wrapper and a `role="tab"` in the <a> link. This seems to be wrong, as the `<ul>` should be the `tablist` and its `<li>` children should be the tabs.

### Steps to reproduce
1. Install the [Axe Dev Tools](https://www.deque.com/axe/devtools/) extension. Sadly, only for Chrome...
2. Run it on the documentation page about the Tabs component: https://buefy.org/documentation/tabs
3. Check the issues panel. There shall be a series of ones regarding **Certain ARIA roles must contain particular children**

![image](https://user-images.githubusercontent.com/1184874/155577494-804c8c8c-7db6-47b5-a804-c99971dd8dd1.png)

### Expected behavior

As suggested, to remove the `role="tablist"` from `<nav>` to `<ul>` element, and  `role="tab"` from `<a>` to `<li>`. Should be a simple pull request ;)

**Comment by jtommy** [comment]
I am not so expert but I trust you, free to make a PR as previous
