### ISSUE TITLE
Question - make buefy table horizontal scrollable like in the docs

### ISSUE THREAD

**Issue by donmb1** [buefy/buefy#3690]
https://buefy.org/documentation/table/#sticky-headers-and-columns

In the first table here of the docs, the buefy table can be scrolled horizontal.
However, I am not able to reproduce this in my UI. My table is always "pressed" together even if there are countless columns.

I tried using `:sticky="true"` on the `<b-table-column` component but it has not effet.
The first table markups is the following:

```
<b-table
  :data="data"
  :columns="columns"
  :sticky-header="stickyHeaders"
></b-table>
```

which also gives no hints how to make the table scrollable.

So probably there is some CSS magic involved but in the codepen example, there is no custom css added.

So, how does this work?

**Comment by jtommy** [comment]
@donmb1 to be honest the example that you see in the example doesn't add any css
