### ISSUE TITLE
[NUXT] $axios undefined inside a modal

### ISSUE THREAD

**Issue by robingiraud** [buefy/buefy#3693]
Hi there,

I'm building an application using in Nuxt and Buefy in my frontend.
My issue is related to the context (this) inside a buefy modal component.

I'm using the nuxt package @nuxtjs/axios for fetching my API, and in any other component the function **this.$axios** is well defined.
But inside a modal component, launched with the function **$buefy.modal.open()**, the context doesn't seems to be defined the same way, as **this.$axios** is now **undefined**.

I tried to solve the problem, trying different versions, and changing my nuxt config, but nothing works.
Of course, I could import manually axios direclty, but it wouldn't be the same instance of axios, and I would lost my axios config.

But, I don't know if the problem comes directly from nuxt or from buefy.

Thank you for your answers

Rob 🤝 

"nuxt-buefy": "^0.4.13"
"@nuxtjs/axios": "^5.13.6"

**Comment by jtommy** [comment]
You have to pass `this` as `parent` in the modal options
