### ISSUE TITLE
can't get main content of css via cdn

### ISSUE THREAD

**Issue by k-brahma** [buefy/buefy#3696]
Hi, it looks like cdn delivery for Buefy v0.9.18 css doesn't work.  

NG

- https://unpkg.com/buefy/dist/buefy.min.css
- https://unpkg.com/buefy@0.9.18/dist/buefy.css
- https://unpkg.com/buefy@0.9.18/dist/buefy.min.css

OK

- https://unpkg.com/buefy/dist/buefy.min.js
- https://unpkg.com/buefy@0.9.18/dist/buefy.min.js [a]
- https://unpkg.com/buefy@0.9.18/dist/buefy.js
- https://unpkg.com/buefy@0.9.17/dist/buefy.min.css [b]
- https://unpkg.com/buefy@0.9.17/dist/buefy.css

***

for NG urls, I can get only the license notice below.

[code]/*! Buefy v0.9.18 | MIT License | github.com/buefy/buefy */[/code]

***

So for the time being I'll use 0.9.17 using [a] and [b] links.

Ping result ip for unpkg.com from both my local (Japan) and digitalocean Singapore server : 104.16.123.175  

regards,

**Comment by jtommy** [comment]
0.9.19
