### ISSUE TITLE
b-field with addons does not style input correctly

### ISSUE THREAD

**Issue by StaffOfHades** [buefy/buefy#3697]
### Overview of the problem

![Screenshot from 2022-03-04 21-43-28](https://user-images.githubusercontent.com/2804982/156866421-12f0fc69-7f73-4603-ab7c-3bdc071f15f0.png)

**Buefy** version: [0.9.19]
**Vuejs** version: [2.6.12]
**OS/Browser**: Chromium

### Description

When passing a type to a parent field, the child input will not be styled (borders, icons) if that parent field additionally has other controls - that is to say add-ons. The message however, will respect the type of the parent field.

### Steps to reproduce

1. Create a b-field with an b-input and control with a static button
2. Add a type to the b-field

### Expected behavior

The input is styled correctly

### Actual behavior

The input has no style applied, it uses default state

_Originally posted by @StaffOfHades in https://github.com/buefy/buefy/issues/2753#issuecomment-1059673384_

**Comment by StaffOfHades** [comment]
This issue was introduced by 094752d6cb01bad0c2349a9b0a63a9bfb7b0167e - which form what I gather was done to fix a separate behavior.

**Comment by jtommy** [comment]
@StaffOfHades you are right but i don't remember why i removed the line that set type prop, probably something from https://github.com/buefy/buefy/issues/3577#issuecomment-963874805

**Comment by StaffOfHades** [comment]
Is this resolved by 36e0dd1055eddd1c10034382434baa9a13da569a?

**Comment by jtommy** [comment]
Yes, it should be ok
