### ISSUE TITLE
Colorpicker 'input' or 'change' event does not fire when alpha is changed

### ISSUE THREAD

**Issue by Lixus** [buefy/buefy#3700]
### Overview of the problem

**Buefy** version: [0.9.16]
**Vuejs** version: [2.6.14]
**OS/Browser**: Chrome

### Description

When changing the alpha value, no input or change event is emitted by the Colorpicker component.

### Steps to reproduce

1. Change alpha value
2. Observe event timeline in Vue Dev Tools

### Expected behavior

The Colorpicker component should emit 'input' or 'change' on alpha change

**Comment by jtommy** [comment]
@Mars073 can you take a look?
