### ISSUE TITLE
Colorpicker rotation resets when selected color is white

### ISSUE THREAD

**Issue by Lixus** [buefy/buefy#3701]
### Overview of the problem

**Buefy** version: [0.9.16]
**Vuejs** version: [2.6.14]
**OS/Browser**: Chrome

### Description

When the selected color is #FFFFFF or #000000, the triangle rotates to it's default position (red). If i then try to set another color (e.g. yellow), it jumps right back to red. This makes it hard for the user to select a new color, especially if the default is set to #FFFFFF or #000000.

![Bildschirmaufnahme 2022-03-09 um 09 12 31](https://user-images.githubusercontent.com/2529169/157400314-733884bb-185f-4c03-b755-0f87b69a64ea.gif)

### Steps to reproduce

1. Select pure white
2. Select another color in the outer ring

### Expected behavior

Maybe the last selected color should be saved, so that the triangle does not rotate back.

**Comment by jtommy** [comment]
@Mars073 can you take a look?

**Comment by Mars073** [comment]
I will try to fix this. The problem is that the white does not belong to any hue and in my helper it is calculated at a zero angle
