### ISSUE TITLE
Colorpicker event name is not consistent with docs and other components

### ISSUE THREAD

**Issue by Lixus** [buefy/buefy#3702]
### Overview of the problem

**Buefy** version: [0.9.16]
**Vuejs** version: [2.6.14]
**OS/Browser**: Chrome

### Description

In the docs, the event is named 'input' but the Colorpicker component only emits 'change'.

### Steps to reproduce

1. Change color
2. Observe event timeline in Vue Dev Tools

### Expected behavior

I think the event name should be 'input' to be consistent with the docs and the other components.

**Comment by sgarner** [comment]
This bug also means that the component can't use `v-model`, only manual bindings to `:value` and `@change`.

**Comment by jtommy** [comment]
@Mars073 can you take a look?
