### ISSUE TITLE
b-input shows validation error on focus instead of blur

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#3705]
### Overview of the problem

**Buefy** version: [0.9.19]
**Vuejs** version: [2.6.14]
**OS/Browser**: Chrome

### Description

On focus of any input with "required" attribute, it immediately shows an error.
Even on the docs it happens: https://buefy.org/documentation/input#validation
On the field called "user handle".

### Steps to reproduce

Create a `<b-input required />` and focus it.

### Expected behavior

The message is suppose to show on blur, not on focus as stated in the docs.

### Actual behavior

https://jsfiddle.net/qfLtb70n/

**Comment by lucraraujo** [comment]
I find it annoying too, but there is a way to change this behavior. You can either:
Set the `defaultUseHtml5Validation` option to false on your constructor options to stop this behavior system wide or use the `use-html5-validation` attribute on your b-input element. Something like this:
```vue
<b-input 
:use-html5-validation="false"
required
/>
```

**Comment by darkylmnx** [comment]
@lucraraujo this doesn't work for me since I want the validations.
It is a bug since before in previous versions I had no issue with that, it did this on blur and not on focus.

**Comment by lucraraujo** [comment]
Yep! You're right! I just realized this. The problem is here: https://github.com/buefy/buefy/blob/deaa4a89ad8f0cb4e901d5e899e0b91e263943fa/src/utils/FormElementMixin.js#L117
I'm trying to find if there are other side effects is I remove this line.

**Comment by darkylmnx** [comment]
It seems to have been added in v0.9.9: https://github.com/buefy/buefy/blob/v0.9.9/src/utils/FormElementMixin.js

The commit tied to it was: https://github.com/buefy/buefy/commit/cb0868ba19735df593e43f7626ef4571bfb33bca

And I don't see how number validation and when the validation starts are related.

Can you enlighten us @fabiofdsantos ?

**Comment by fabiofdsantos** [comment]
I think it was related to https://github.com/buefy/buefy/issues/3059

**Comment by fabiofdsantos** [comment]
I think it was related to https://github.com/buefy/buefy/issues/3059 but maybe a bug has been introduced on the "fix".
