### ISSUE TITLE
Multiple values support in auto complete

### ISSUE THREAD

**Issue by html-helpers** [buefy/buefy#3718]
Hi Team,

Thank you for creating such a useful library...!!!

I want to have a multiple selection feature in auto complete, as like lagacy select control.

I really need this feature.

**Comment by jtommy** [comment]
@html-helpers thanks.

Did you try tagsinput?

**Comment by html-helpers** [comment]
No, I tried to implement auto complete control but I can't see any options in how to make it multiple selection of values from filtered result.

Thank you...!!!
