### ISSUE TITLE
<b-upload> to accept heic images

### ISSUE THREAD

**Issue by MsDacia** [buefy/buefy#3719]
`<b-upload
	v-model={this.uploadedImage}
	accept="*.heic"
	class="file-label"
	expanded
>`

### Description

<b-upload /> to accept *.heic images

### Why Buefy need this feature

Because it is a commonly used image source

**Comment by jtommy** [comment]
Sane problem with native input file?

**Comment by Mars073** [comment]
@MsDacia can you consider using the correct syntax defined by the w3c?
```diff
<b-upload
    v-model={this.uploadedImage}
-   accept="*.heic"
+   accept=".heic"
    class="file-label"
    expanded
/>
```
Note that if you want to be sure that users can choose the HEIC format (which is common only on Apple devices), you specify this mask to include it in the images: `image/*,.heic`, it may not be displayed in the web browser.
