### ISSUE TITLE
When I run the npm run dev it generates error

### ISSUE THREAD

**Issue by korlarday** [buefy/buefy#372]
**Buefy** version: [0.5.4]
**Vuejs** version: [2.1.10]
**OS/Browser**: Windows/chrome

Module build failed:     transition: opacity $speed $easing;                        ^      
 Undefined variable: "$speed".       in c:\Users\korlarday\newBlog\node_modules\buefy\src\scss\utils\_animations.scss (line 90, column 25)

**Comment by rafaelpimpa** [comment]
Did you install bulma? ``$speed`` comes from bulma.
