### ISSUE TITLE
Horizontal scrollable table ignores column width

### ISSUE THREAD

**Issue by donmb1** [buefy/buefy#3726]
### Overview of the problem

**Buefy** version: [0.9.17]
**Vuejs** version: [2.6.14]
**OS/Browser**: Chrome 100.0.4896.75 

### Description

When applying `width` to a table column it is being ignored on tables that overflow.

### Steps to reproduce

https://codepen.io/donmb1/pen/ExoReaq?editors=1010
Please check the computed `columns()` and the column `first_name` and `last_name`

### Expected behavior

Width should apply just as with non scrollable tables

### Actual behavior

The table column with the applied width is not expanding

**Comment by donmb1** [comment]
Hey folks. any comment on this?
Right now it makes my table really ugly. I want to manipulate the column width but it's not possible. Maybe it would work manually with the right css selector?

**Comment by Frankisgek** [comment]
Having the same issue, any progress on this issue?

**Comment by mouadTaoussi** [comment]
Hello! I'm about to understand your issue and might be fix it when I got it
can you explain me the pen you have shared ?

**Comment by donmb1** [comment]
@mouadTaoussi sure

The Pen is from the buefy documentation on horizontal scrollable tables.
Horizontal scroll works just fine

But in contrast to a default table, the `width` parameter on the table columns ins being ignored. In the Pen the `first_name` column has a `width` set to 300 but it's not applied. This makes the table unflexible and not good looking.

**Comment by donmb1** [comment]
correct

**Comment by donmb1** [comment]
@mouadTaoussi any findings? could you reproduce it?
