### ISSUE TITLE
Input with emoji don't show the right length

### ISSUE THREAD

**Issue by iplanwebsites** [buefy/buefy#3731]
### Overview of the problem

**Buefy** version: 0.9.19
**Vuejs** version: 2.x
**OS/Browser**:

### Description
 
Length of strings with Emoji in input isn't accurate.

![image](https://user-images.githubusercontent.com/787729/164255022-9ca70f7c-0999-406b-a73c-35ca366a91e2.png)

There's disparity between browser implementation, it'd be nice to have a solid way to validate length using the right function within Buefy directly.
 

### Expected behavior

1 emoji = 1 character

### Actual behavior
1 emoji = many

**Comment by joaoGabriel55** [comment]
I can take a look @iplanwebsites

**Comment by iplanwebsites** [comment]
Thanks @joaoGabriel55 !
