### ISSUE TITLE
WE REALLY NEED SUPPORT FOR VUE 3 PLEASE!!

### ISSUE THREAD

**Issue by mbonii** [buefy/buefy#3732]
### Description

In the company I am working on we are migrating from Vue 2 to 3 and we really need the version for Vue 3

**Comment by jtommy** [comment]
Do you think that is a good way to ask something?
Also, please remember that it is an open source project.

By the way https://github.com/buefy/buefy/issues/2505

**Comment by yooouuri** [comment]
It is not jet published to npm, but im gonna make a "successor" to Buefy

https://github.com/yooouuri/bulma-vue

Will have the same API as Buefy, made for Vue 3.
