### ISSUE TITLE
Dynamic table columns are not reactive

### ISSUE THREAD

**Issue by GMartigny** [buefy/buefy#3734]
### Overview of the problem

**Buefy** version: v0.9.20
**Vuejs** version: v2.6.14
**OS/Browser**: any

### Description

When I build a table with dynamic columns, changing the columns count don't refresh the view. What I mean by "dynamic columns" is having columns as an array and looping over `b-table-column` with a `v-for`.

### Steps to reproduce

 1. Have a `b-table`
 2. Set an array in a `computed`
 3. Define `b-table-column` that loop over the array
 4. Change the array length
 5. Observe that the number of columns hasn't change

### Expected behavior

It should be reactive and refresh accordingly. It might be due to the way cells are keyed.

### Actual behavior

The columns are updated, but not the column count.

[Playground](https://codepen.io/GMartigny/pen/RwxzZXQ)

**Comment by jtommy** [comment]
I think to understand the problem
