### ISSUE TITLE
BDatepicker Expected String, got Object

### ISSUE THREAD

**Issue by donmb1** [buefy/buefy#3736]
### Overview of the problem

**Buefy** version: [2.15.8]
**Vuejs** version: [2.6.14]
**OS/Browser**: Mac OS Montery 12.3.1 / Chrome Version 100.0.4896.127 (Official Build) (arm64)

### Description

Serving a Javascript `Date` Object to the Buefy Datepicker results in a console warn. The Datepicker works still fine as expected.

```
[Vue warn]: Invalid prop: type check failed for prop "type". Expected String, got Object 

found in

---> <BDatepicker>
       <BField>
         ...
```

### Steps to reproduce

```
<b-datepicker
        :value="parsedDate('2022-03-24T23:00:00.000Z')"
/>

methods: {
      parsedDate (value) {
          return new Date(value)
     }
}
```

### Expected behavior

No console warning because I pass a valid Date Object to the Datepicker.
When passing a Date String I get another error

```
TypeError: currentDate.getDate is not a function
    at VueComponent.updateInternalState (chunk-970672ce.js?9843:1690:1)
    at VueComponent.value (chunk-970672ce.js?9843:1539:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at Watcher.run (vue.runtime.esm.js?2b0e:4584:1)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4326:1)
    at Array.eval (vue.runtime.esm.js?2b0e:1989:1)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1915:1)
```

### Actual behavior
see above

**Comment by jtommy** [comment]
@donmb1 it accepts only `Date` object

**Comment by donmb1** [comment]
@jtommy 
Yes but I am passing a Date Object?
See above `new Date(value)`

**Comment by jtommy** [comment]
@donmb1 https://codepen.io/jtommy/pen/wvywWRM?editors=101&layout=right i'm not able to replicate it to be honest

**Comment by donmb1** [comment]
Me neither on your pen. I will investigate further. Thanks for helping
