### ISSUE TITLE
Color picker return bad value

### ISSUE THREAD

**Issue by coalacode-com** [buefy/buefy#3740]
Hello,
I have a problem with colorpicker, when I have a color in a nested structure it displays as an object.

{{ form }}

```
"form: {
  "price": {
        "color": {
          "$channels": {
            "0": 178,
            "1": 77,
            "2": 77,
            "3": 255
          },
          "red": 178,
          "green": 77,
          "blue": 77,
          "alpha": 255,
          "hue": 0,
          "saturation": 0.4,
          "lightness": 0.5
        },
  }
}
```

### Overview of the problem

**Buefy** "^0.9.20",
**Vuejs** version: 2.6.14
**OS/Browser** Firefox development:

### Description

When click thumb color and choose random color returned this object values

### Expected behavior

return HEX

**Comment by GMartigny** [comment]
Colorpicker component returns a `Color` object when updated. If you want to display it, you need to parse it to string using `toString`.

```vue
<b-colorpicker v-model="selectedColor" />
{{ selectedColor.toString() }}
```

**Comment by alqu** [comment]
Hm yes, would work. But I much prefer a config option for this color picker to get the same value out of the control as I am feeding into it - without the need of hooking into an update-hook and reformat stuff. Something like `valueType: 'hex'` as config option would be nice.
