### ISSUE TITLE
Question : Datepicker : how to show formatted date and save in diffrents formats ?

### ISSUE THREAD

**Issue by squarou** [buefy/buefy#3741]
Hi,

I use Datepicker to store a date in a form, which post to the DB. This is a "classic" html/php form that I'm using.

- I want my users to pick a date.
- Then, in the input field, the date might be like DD/MM/YYYY
- Then, when I submit the form, I'd like to save the date in YYYY/MM/DD HH:mm:ss in the database (don't want to handle a formatting function in the backend)

I'm using moment to format dates.

This is the code I'm using.

```
<template>
    <section>
        <b-field label="Select a date">
            <b-datepicker

                v-model="selected"

                :show-week-number="showWeekNumber"

                :date-formatter="dateToScreen"

                placeholder="jj/mm/aaaa"
                icon="calendar-today"
                :icon-right="selected ? 'close-circle' : ''"
                icon-right-clickable
                @icon-right-click="clearDate"
                :unselectable-days-of-week="[0, 6]"
                :first-day-of-week=1
                icon-pack="fas"
                trap-focus>
                    <b-button
                        label="Aujourd'hui"
                        type="is-primary"
                        icon-left="calendar-day"
                        @click="selected = new Date()" />

                    <b-button
                        label="Effacer"
                        type="is-danger"
                        icon-left="close"
                        outlined
                        @click="selected = null" />
            </b-datepicker>
        </b-field>
    </section>
</template>
```
This is the script part :
```
<script>
import moment from 'moment';
export default {
    props: {
        itemId: {
            type: String,
            default: 'date',
        },
    },
    data() {
        return {
            showWeekNumber: true,
            locale: undefined, // Browser locale
            selected: undefined,
        }
    },
    methods: {
        clearDate () {
            this.selected = null
        },

        dateToScreen(date) {
            
            return moment(date).format("YYYY/MM/DD HH:mm:ss");
        },



    },
    computed: {
        
    }
}
</script>
```

Is it possible to have a diplay format and a "behind" format to send to the request ?

Should I use date-formatter or date-parser or both ? 

Help appreciated ☺

**Comment by jtommy** [comment]
The function props that you mentioned are only for datepicker usage because it accepts only Date object.
It doesn't the format that toy receive and the format that you send, so you have to transform to Date object on get and transform it from Date object on post

**Comment by squarou** [comment]
Ok @jtommy thanks for your answer. Can you confirm that I can display a DD/MM/YYYY value and send the same date with a format in YYYY/MM/DD HH:mm:ss ?

**Comment by jtommy** [comment]
Sure, the function that you are using is only for display purpose. The date object always contains the time part too

**Comment by squarou** [comment]
Ok thanks, I'll continue to search how to pass the formated date object in my form, avoiding using hidden input fields ;-)
