### ISSUE TITLE
Multiple import

### ISSUE THREAD

**Issue by uacode** [buefy/buefy#3751]
### Overview of the problem

**Buefy** version: 0.9.21
**Vuejs** version: 2
**OS/Browser**: fc36 / Chrome latest

### Description

When I use import SnackbarProgrammatic in multiple files, I has an error
Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'extend')"

https://i.imgur.com/ipLWzDn.png
https://i.imgur.com/MoPofwz.png

### Steps to reproduce

Try to use in multiple vue files
```js
import { SnackbarProgrammatic as Snackbar } from 'buefy'
Snackbar.open('Look at me!')

```

**Comment by jtommy** [comment]
You have to import Snackbar plugin or the full bundle in the entry point
