### ISSUE TITLE
Taginput within table details will collapse details

### ISSUE THREAD

**Issue by regexj** [buefy/buefy#3755]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: Mint/Chrome

### Description
If you place a [taginput](https://buefy.org/documentation/taginput/) within the [detailed row of a table](https://buefy.org/documentation/table/#detailed-rows), each time you press enter to submit a new tag it will collapse the detail row.

### Steps to reproduce

1. Create a buefy table with detailed rows.
2. In the detailed row template use a taginput.
3. Now write a tag into the taginput and press enter to submit it.

### Expected behavior

To add the tag and the detailed row to remain open.

### Actual behavior

It adds the tag but closes the detailed row.

**Comment by jtommy** [comment]
You might to use `keypress.native.stop` or similar
