### ISSUE TITLE
horizontal b-field ignores CSS rule

### ISSUE THREAD

**Issue by knot22** [buefy/buefy#3758]
### Overview of the problem

**Buefy** version: 0.9.21
**Vuejs** version: 2.6.11
**OS/Browser**: Windows 11/Chrome 103.0.5060.114

### Description

When a horizontal `b-field` has a CSS rule applied to align the `field-body` text right, the rule is ignored.  When equivalent Bulma code has the same rule applied, that rule is honored.  This implies the behavior is related to the Buefy component.

### Steps to reproduce
1. in a Vue app use a horizontal `b-field` Buefy component and put some data in the label and in the field body
2. create a CSS rule that uses `.field-body` as the selector, then set text to align right and background color to lightgray

The Codepen that's linked below is an accurate reproduction of this issue.

### Expected behavior

Text in field body aligns to the right and background is lightgray.

### Actual behavior

Text in the field body remains left aligned (the default) and background is lightgray.

[https://codepen.io/knot22/pen/PoRjYwJ](https://codepen.io/knot22/pen/PoRjYwJ)

**Comment by projectmentor** [comment]
I can confirm this any progress on fix or workaround?

**Comment by kikuomax** [comment]
@knot22 @projectmentor The documentation states:
> Note: Each child element of a <b-field horizontal/> will be automatically wrapped inside a Field component.

However, `<b-field horizontal>` won't wrap the child element with `field` if it is a text node. You may do something like the following as a workaround:
```vue
<b-field horizontal label="Purchase price of lantern:">
  <span>{{ data.price }}</span>
</b-field>
```
