### ISSUE TITLE
selected option not working in b-select

### ISSUE THREAD

**Issue by zhaolinlau** [buefy/buefy#3761]
### Overview of the problem

**Buefy** version: [0.9.21]
**Vuejs** version: [2.7.8]
**OS/Browser**: Windows 11/Firefox

### Description

selected option not working in b-select

### Steps to reproduce

`<b-field>
  <b-select>
     <option value="vue">vue</option>
    <option value="bulma">bulma</option>
      <option  value="buefy" selected>buefy</option>  
</b-select>
</b-field>`

### Expected behavior

![image](https://user-images.githubusercontent.com/68846168/182777953-87d77f6b-45d4-4638-aa1b-b616fd14975a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/68846168/182778003-ddc9b173-fd54-44dc-b948-511e5f934e28.png)

**Comment by jtommy** [comment]
You should use binding (v-model or value)
