### ISSUE TITLE
Prop mobile-modal in datetimepicker not working

### ISSUE THREAD

**Issue by Tanny-Griz** [buefy/buefy#3771]
hi! The prop -> :mobile-modal='false' in datetimepicker not working (like in datepicker) I don’t want Modal in mobile screen. is there a solution?

"nuxt-buefy": "^0.4.23",
"vue": "^2.6.12",

**Comment by jtommy** [comment]
Try using `:datepicker="{ mobileModal: false }`

**Comment by Tanny-Griz** [comment]
> Try using `:datepicker="{ mobileModal: false }`

it works! thank you!
