### ISSUE TITLE
The attribute min-date of Datepicker is not working for ipad and iphone devices.

### ISSUE THREAD

**Issue by ASHWINIAJIT** [buefy/buefy#3772]
### Overview of the problem

**Buefy** version: [0.9.13]
**Vuejs** version: [2.6.11]
**OS/Browser**: Chrome

### Description

The attribute min-date of Datepicker is not working for ipad and iphone devices. 

However, it is working for android devices. Also it seems to be working fine for all devices when checked in browser stack.

**min-date for this particular scenario is 18-Aug-2022**
  
### **Android - Chrome**
![Android](https://user-images.githubusercontent.com/51357437/185397616-b1b0d322-2ae8-4b59-b16b-93519b98015f.jpeg)

### **iPhone - Safari**
![Safari](https://user-images.githubusercontent.com/51357437/185397875-66b2188d-c435-486a-9169-290a23e48840.jpeg)

### **iPhone - Chrome**
![Chrome](https://user-images.githubusercontent.com/51357437/185397898-4e77fab9-c83f-4c59-b29d-83e0fe65b71f.jpeg)

### **iPhone - Firefox**
![Firefox](https://user-images.githubusercontent.com/51357437/185397930-75ce1855-e392-42e5-8a91-76ee9eb6c527.jpeg)

**Comment by jtommy** [comment]
Native picker doesn't support it, you should disable it using `mobile-native` prop
