### ISSUE TITLE
Native support for using FontAwesome alongside Material Icons

### ISSUE THREAD

**Issue by vakrolme** [buefy/buefy#3774]
### Description

Make it easy to use both FontAwesome and Material Icons in one project.

So, components like `b-button` use `b-icon` internally, and it [takes](https://github.com/buefy/buefy/blob/adba1eb0c3bf0cc9779fe8ad2e2d19e239f04f7e/src/components/button/Button.vue#L53) `icon-pack` as a prop.

Within `b-icon`, there's a calculated property `useIconComponent`, and it seems like in order to make it work with a js-packaged FontAwesome icon set (e.g. `@fortawesome/pro-regular-svg-icons`), you have to point `defaultIconComponent` to the `@fortawesome/vue-fontawesome` component within your [constructor config](https://buefy.org/documentation/constructor-options/). 

However, once you do that, you can't use Material Icons inside any of your `b-button` components anymore, because `b-icon` will use a font-awesome-specific component. 

There seems to be a way to import FontAwesome as a "[custom icon set](https://buefy.org/documentation/icon/#custom-icon-pack)", but it's more difficult to set up and maintain.

A better approach would be to calculate `useIconComponent` based on the prefix (pack). The appropriate pairs can be hardcoded for `fa` and `mdi` sets, or they can as well be configurable within the constructor options. Or there can be an additional prop on every component that renders `b-icon` internally.

**Comment by vakrolme** [comment]
I found a better workaround. Create an intermediary component that would properly render either Material or FontAwesome icon based on its prefix, and set it as `defaultIconComponent` in the buefy constructor options. Then whenever `<b-icon>` is invoked, the props will get passed straight down to this agnostic component, which will in turn do the rendering of either FontAwesomeIcon, or `<i>` with a bunch of classes, just like [Icon.vue does](https://github.com/buefy/buefy/blob/fa847f36cf0a734c11fbbea30e988b7839dbce24/src/components/icon/Icon.vue) currently. In the snippet below I have it set up for my Nuxt.js app, but you can adjust it for any Vue.js project.

My setup will make all `<b-icon>` components use `mdi` icons by default, but you can specify `icon-pack="far"` and get a Font Awesome icon instead. I think you can rewrite it to work the other way around too.

**package.json**
```json
"dependencies": {
    "@mdi/font": "^7.0.96",
    "nuxt-buefy": "^0.4.23"
    ...
},
"devDependencies": {
    "@nuxtjs/fontawesome": "^1.1.2",
    "@fortawesome/free-brands-svg-icons": "^6.1.2",
    "@fortawesome/free-solid-svg-icons": "^6.1.2",
    ...
}
```

**plugins/agnostic_icon.js**
```javascript
import Vue from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

let component = Vue.component('AgnosticIcon', {
    props: {        
        icon: Array, // e.g. ['fas', 'fas-lock']
        size: String,
    },
    render(h){
        if(['fas', 'far', 'fal', 'fat', 'fad', 'fab'].includes(this.icon[0])){
            return h(FontAwesomeIcon, {props: {icon: this.icon, size: this.size, class: [this.classProp, { extraClass: true }]}});
        } else {
            return h('i', {class: [this.icon[0], this.icon[1], this.size, this.classProp]});
        }
    }
});

Vue.component('agnostic-icon', component);
```

**nuxt.config.js**
```javascript
 plugins: [
    '~/plugins/agnostic_icon.js'
  ],
  buildModules: [
    '@nuxtjs/fontawesome',
  ],
  fontawesome: {
    component: 'font-awesome-icon',
    suffix: false,
    addCss: true,
    icons:{
      regular: [
         'faBatteryBolt', 
         'faUserSecret', 
         'faPersonToPortal' 
      ],
      brands:[
        'faTwitter', 
        'faGoogle'
      ]
    },
  buefy: {
    materialDesignIcons: true,
    materialDesignIconsHRef: 'https://cdn.jsdelivr.net/npm/@mdi/font@7.0.96/css/materialdesignicons.min.css',
    defaultIconPack: 'mdi',
    defaultIconComponent: 'agnostic-icon',
  },
```
**login.vue (Usage example)**
```html
<b-button native-type="submit" icon-left="lock">Log in</b-button>
<!-- renders MDI -->
<b-button @click="oauth('google_oauth2')" icon-left="google" icon-pack="fab">Google</b-button>
<!-- renders FAB -->
```

**Comment by wesdevpro** [comment]
@vakrolme would love to collaborate to get this done. Could you please DM me over Buefy's discord. Thank you

**Comment by wesdevpro** [comment]
I am closing this PR because it is stale. Thank you for your Idea.
