### ISSUE TITLE
Integration with vue3 (nuxtjs 3) ? is Ok ?

### ISSUE THREAD

**Issue by titoff002** [buefy/buefy#3775]
Hello,

Do you have a date for the migration/use of buefy with **vue3** (preferably with **nuxtjs3**)?

If it's already done: do you have a tutorial for integration and use with nuxtjs 3?

Thank you.
Have a good day.

**Comment by jtommy** [comment]
There is no Vue 3 version but you might use Oruga + official theme https://github.com/oruga-ui/theme-bulma
