### ISSUE TITLE
Some domains on the expo page have expired or lead to broken websites

### ISSUE THREAD

**Issue by Hyperion2400** [buefy/buefy#3780]
### Description

This isn't really a bug with the framework but I don't know where else to report this. Several domains on the expo page https://buefy.org/expo have expired or lead to broken websites. They should probably be removed as it doesn't make a good impression on people who might be interested in using the framework.

Expired:

- https://crawly.app/
- https://yakety.co.uk/

Broken or not deployed anymore:

- https://wotel.dev/
- https://dogswelcome.in/
- https://www.okuna.io/
- https://voranalyse.salamander-garten.ch/ leads to the php admin page, the proper link is https://www.salamander-garten.ch/

**Comment by jtommy** [comment]
You can make a PR to delete theme
