### ISSUE TITLE
Landing on any website URL throws a 404

### ISSUE THREAD

**Issue by l4k5hm4n** [buefy/buefy#3783]
### Overview of the problem

Opening the website through a direct url throws 404

**OS/Browser**: Chrome/Safari

### Description

Website throws a 404 when tried to access through a direct link. Routing works as expected when you navigate to the desired page from homepage ( buefy.org )

### Steps to reproduce

1. visit https://buefy.org/documentation
2. you should see a 404 as in attached screenshot below

<img width="1889" alt="Screen Shot 2022-09-12 at 14 59 46 PM" src="https://user-images.githubusercontent.com/38096064/189620515-f6eab00b-1fa2-4ede-9ebf-b43ea59c1b5f.png">

### Expected behavior

Hyperlinks should show a working page when accessed either directly or through internal navigation

### Actual behavior

404 screen - probably because of a missing routing config on netlify

**Comment by neonanal** [comment]
Still happening -- each browser restart I get all 404 pages that were opened on Buefy docs website prior the restart.

**Comment by jtommy** [comment]
What pages?

**Comment by neonanal** [comment]
Every single one of them
