### ISSUE TITLE
Table subheading slot not working 

### ISSUE THREAD

**Issue by Moritz-Schmidt** [buefy/buefy#3791]
### Overview of the problem

The subheading slot of the b-table component is not being displayed.

**Buefy** version: [0.9.22]
**Vuejs** version: [2.7.10]
**OS/Browser**: Linux Arch (5.19.9-arch1-1) / Firefox (104.0.2)

### Description

When using the slot in the column element it works, but not in the table element.
According to the documentation the Table component should have a "subheading"-slot. Either the Documentation is wrong or this feature does not work.  

### Steps to reproduce

Codepen: https://codepen.io/moritzSchmidt/pen/LYmjZbM

### Expected behavior

![Bildschirmfoto am 2022-09-21 um 15 45 27](https://user-images.githubusercontent.com/88738242/191520826-e9c75958-7ac0-4fad-b1e6-eecc23e52292.png)

### Actual behavior

![Bildschirmfoto am 2022-09-21 um 15 43 30](https://user-images.githubusercontent.com/88738242/191520837-65085fc8-90a3-4577-a4cc-123c498af1db.png)

**Comment by Moritz-Schmidt** [comment]
same problem with the custom header slot

**Comment by geeksilva97** [comment]
I would like to investigate it.
