### ISSUE TITLE
Datepicker cause inifinite loop if change month by keyboard

### ISSUE THREAD

**Issue by cakecatz** [buefy/buefy#3792]
### Overview of the problem

**Buefy** version: 0.9.22
**Vuejs** version: 2.6.11
**OS/Browser**: MacOS/Chrome

### Description

https://github.com/buefy/buefy/blob/dev/src/components/datepicker/DatepickerTableRow.vue#L370
https://github.com/buefy/buefy/blob/dev/src/components/datepicker/DatepickerTableRow.vue#L166-L168

`changeFocus` check `nextDay` is selectable, but it always return `false` if nextDay will be next/prev month without `nearbySelectableMonthDays: true`. So it causes an infinite loop.

### Steps to reproduce

1. Select any day
2. press `up` or `down` key repeatedly

### Expected behavior

Change the current month without going not responsive.

### Actual behavior

https://user-images.githubusercontent.com/6136383/192745318-400998cb-3d16-4d1a-89fd-6251660d6b4a.mp4

**Comment by holtolee** [comment]
I reproduced this issue on one of my project, nice catch. +1

**Comment by kikuomax** [comment]
Please refer to #3876.
