### ISSUE TITLE
Dot inside input

### ISSUE THREAD

**Issue by komxvl** [buefy/buefy#3794]
Hi! Thanks for this amazing library. I have some problems with the input component. When I finish entering text and fast-clicking two spaces the dot append inside the input.
<img width="523" alt="Screenshot 2022-09-29 at 12 24 03" src="https://user-images.githubusercontent.com/29713494/192994284-a390b6e9-9b97-422f-8357-6a50da9eec52.png">

**Comment by jtommy** [comment]
Thanks!
It's not a Buefy issue, did you try using a native input?

**Comment by komxvl** [comment]
Thanks for your answer, the same behavior, it's so strange...
