### ISSUE TITLE
Full width sidebar doesn't have a close button

### ISSUE THREAD

**Issue by swarmukhdefault** [buefy/buefy#3802]
### Overview of the problem

**Buefy** version: [0.9.22]
**Vuejs** version: [3.2.40]
**OS/Browser**: Windows 11/Brave

### Description

Full width sidebar does not have a close button. It can be closed by pressing the `Esc` key however. This behaviour can confuse a user who is desperately trying to close the sidebar but is unable to find the close/exit button.

**Note:** As a controlled component, one can always add a button inside the sidebar to hide it. That is not the point of this bug report.

### Steps to reproduce

1. Navigate to `Sidebar` component in the website
2. Turn ON the `fullwidth` switch
3. Click the `Show` button
4. A user won't be able to close unless s/he hits the `Esc` key

### Expected behavior

Provide an internal default button and a default internal location for that `Close` button for the end-user to be able to close the `fullwidth`ed Sidebar

**Comment by Hyperion2400** [comment]
I would also expect the sidebar to close if a swipe left is detected on mobile (or swipe right if the sidebar is on the right).
At least for a default width sidebar. Not sure if it makes sense for a fullwidth sidebar from a UX perspective.
