### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by camohub** [buefy/buefy#3805]
What is going on with migration to Vue 3? Is there a hope Buefy will support Vue 3 or not?

**Comment by wesdevpro** [comment]
@camohub from my understanding, buefy will not be moved to support vue3. **However**, there is a buefy/bulma theme _being developed_ for Oruga UI. [oruga-ui/theme-bulma](https://github.com/oruga-ui/theme-bulma)

**Comment by camohub** [comment]
Its sad. Very sad.

**Comment by wesdevpro** [comment]
> Its sad. Very sad.

I totally agree. Buefy has a lot of potential and Buefy is awesome for turning around great static websites. Unfortunately I don't have enough understanding about buefy's setup. Otherwise I would contribute and make the upgrade to vue3 @camohub  @Tommy

**Comment by nmihaica** [comment]
It is hard to battle progessive nature of JS ecosystem.

I would like to thank contributors for the good quality of this open source package. It served me very well.

Vue2 plus buefy still does it for me.

**Comment by mpgalaxy** [comment]
Hi, I wanted to add somthing to this:
**Someone did port buefy to vue3** ( https://github.com/kikuomax/buefy ), maybe the core devs could help the author to maintain this, 99% of the work is already done! :)
This would be a win win for all.
@the-core-devs-of-buefy:  **Please consider this (!) :)**

**Comment by wesdevpro** [comment]
@mpgalaxy I believe @kikuomax was one of the earlier folks working on migrating Buefy to vue3. @kikuomaxcould you use any help? And what else do you have left to work on before you can get to a RC? I think if we migrate Buefy to vue3 the Buefy community my have to maintain the project

**Comment by wesdevpro** [comment]
> Hi, I wanted to add somthing to this:
> **Someone did port buefy to vue3** ( https://github.com/kikuomax/buefy ), maybe the core devs could help the author to maintain this, 99% of the work is already done! :)
> This would be a win win for all.
> @the-core-devs-of-buefy: **Please consider this (!) :)**

Thanks for letting the open source community know. I DM @jtommy about @kikuomaz port to vue3. Looking at it at the moment it looks great! However many things still need to be done including: refactoring the code for vue3 (not just migrating), docs need to be refactored (this includes the website, support vue2 will be ended by the official vue team (vue2 may already be at its EOF) so Buefy would no longer support vue2, and obviously the community and or an individual would need to maintain the project as @jtommy is busy with Oruga.

**Comment by wesdevpro** [comment]
If anyone is interested in gathering a team together I would be down to help out(ngl I have little to no experience on how to work on this project but I would love to learn.)

**Comment by wesdevpro** [comment]
https://github.com/buefy/buefy/pull/3400#issuecomment-1636509334

**Comment by wesdevpro** [comment]
Agreed! We have a lot of work to do. Some features/structures may break as we move everything to vue3. The biggest thing I am worried about is folks who are using vue2 and can't move to vue3 because of some other dependency required for their site. More then likely when we have a RC for Buefy v3 we will drop support for Buefy v2. @camohub Coffee donations are always welcomed☕!

**Comment by AvinashRavula** [comment]
For anyone looking for Vue 3 support, here is the latest update:

Support for Vue 3 is currently in progress #3861
