### ISSUE TITLE
progress bar won't update on Message 

### ISSUE THREAD

**Issue by feedanal** [buefy/buefy#3806]
Hello,
I'm using a simpliest example of Message w/ progress bar attached, and the bar does not seem to be updated. All styles and values are in place, but the progress value is not decreasing, console log is empty. I tried importing individual components and the whole Buefy -- same result. 

Non-working example:
https://codepen.io/feedanalytics/pen/YzvNVzN

Can it be related to https://github.com/buefy/buefy/pull/3754? If so, when can we expect it to be released?

Thanks!

**Buefy** version: [0.9.22]
**Vuejs** version: [2.7.13]
**OS/Browser**:
Monterey / Chrome

**Comment by kikuomax** [comment]
@feedanal `Message` currently won't start progress updates on mounted. It starts progress updates when its model value (`active`) turns `false` &rightarrow; `true`. As a workaround, you may allocate a flag in your component and bind it to `Message`, which is initially `false` and turns `true` on mounted.

**Comment by wesdevpro** [comment]
I am closing this PR because there is a workaround.
