### ISSUE TITLE
Buefy Date picker Max year range not following the max-datetime range given

### ISSUE THREAD

**Issue by Nutcracker52** [buefy/buefy#3817]
**Buefy** version: [0.9.0
**Vuejs** version: [2.6.10]
**OS/Browser**: windows 11

### Description

When set a max-datetime duration something above 10 years component does not show year range above 10 years there is a limitation in the components to cut down the years in future max upto 10 years. 

This bug shows in your example codes as well. I have attached screenshot below. 

### Expected behavior

default past years-range is 100 from current year and default future year-range is 10 this should be 100 as well. Other wise component behaviour is not same as past and future. 
once set the max-datetime to 50 years user suppose to see all those years not limited to 10 years from the current year by default. 

as per my knowledge setting up years-range:[-100, 100] by default this error could be easily handled. 
Component needs similar behavior when picking dates in past and future. 

![2022-12-20 10_48_50-Datepicker _ Buefy](https://user-images.githubusercontent.com/65933656/208572976-7cf96895-3845-45e2-bf96-8df2a00fceaa.png)
![2022-12-20 11_17_59-](https://user-images.githubusercontent.com/65933656/208573784-c2ea4e4d-96bd-4428-aacc-2d8fbba55b68.png)

**Comment by rahulcool1910** [comment]
Is there any specify reason, why the future dates are blocked to only 10 years?

**Comment by wesdevpro** [comment]
> Is there any specify reason, why the future dates are blocked to only 10 years?

I could not tell 🤷‍♂️@jtommy?

**Comment by jtommy** [comment]
No, bit you can edit as you prefer globally too

**Comment by wesdevpro** [comment]
Closing because there is a workaround. You can change the config in your setup to allow for this feature. If you need any further assistance feel free to reopen this issue.
