### ISSUE TITLE
new property Autocomplete.disable

### ISSUE THREAD

**Issue by flipflopsimsommer** [buefy/buefy#3819]
### Description

A new property for the [autocomplete](https://buefy.org/documentation/autocomplete#api-view) componentent to set it disable.

### Why Buefy need this feature

Consistence though all components. :balloon:

### Workarround ATM

use a wrapper component which will show a `b-inut.disabled`

**Comment by wesdevpro** [comment]
@flipflopsimsommer I don't quite understand why anyone would want to disable the autocomplete component, but I do understand that consistency is good. I leave most feature requests up to @jtommy ad my goal is just to maintain and fix bugs for Buefy v2

**Comment by flipflopsimsommer** [comment]
I use autocomplete as a searchable select. I'm fine with the feature lock, keep it stable :+1: .

**Comment by wesdevpro** [comment]
> I use autocomplete as a searchable select. I'm fine with the feature lock, keep it stable 👍 .

Sounds great thank you! Be on the lookout for Buefy Vue3(aka [buefy-next](https://github.com/ntohq/buefy-next)). When vue2 is deprecated Buefy Vue2 (aka. Buefy) will become unsupported but hopefully stable then buefy-next will become the latest version of Buefy.
