### ISSUE TITLE
b-field with additional p.control wont reset error state.

### ISSUE THREAD

**Issue by pfinkbeiner** [buefy/buefy#3842]
### Overview of the problem

**Buefy** version: [0.9.23]
**Vuejs** version: [2.6.x]
**OS/Browser**: OSX / Chrome

### Description

I experienced a weird behavior of b-input's validation that only appears if you have an additional HTML Element within.
For example, if I use this example from the documentation with `p.control` and add `required` to b-input like this:

```
 <b-field message="What a beautiful email!!">
    <b-input require placeholder="This is expanded" expanded></b-input>
     <p class="control">
         <span class="button is-static">@gmail.com</span>
     </p>
  </b-field>
```

Then I am able to reproduce this issue. 

1. Trigger validation with focus then blur. 
2. Focus again and fill in some text, error should be gone…

![Mar-07-2023 12-11-36](https://user-images.githubusercontent.com/722890/223407880-49e1f9f5-163f-48da-ba31-0e9400df2ee1.gif)

### Expected behavior

Error state should reset after input. 

### Actual behavior

Error state stays…

**Comment by wesdevpro** [comment]
#3752
