### ISSUE TITLE
Buefy <b-progress> animated not working.

### ISSUE THREAD

**Issue by mmanjarekar** [buefy/buefy#3849]
I have implemented buefy progressbar and want to show sliding animation (till the progress value) on page load.
But animation is not working. Please guide me how to do it?
Animated property is not working.
My code is as follows - 

<b-progress :value="total_daily_billcuts_count" :rounded="false" animated :max="total_daily_billcuts_maxcount" format="raw"  show-value> {{total_daily_billcuts_count}} of {{total_daily_billcuts_maxcount}}</b-progress>

**Comment by wesdevpro** [comment]
@mmanjarekar Is this actually a feature request or are you just asking for help? If you need help with something please send the details on our [discord](https://discordapp.com/invite/ZkdFJMr) or DM on discord `@wesdevpro`
