### ISSUE TITLE
Tag Input first option is no longer focused

### ISSUE THREAD

**Issue by glumb** [buefy/buefy#3851]
### Overview of the problem

**Buefy** version: 0.9.23
**Vuejs** version: 2.7
**OS/Browser**: all

### Description

Since Buefy 0.9.x the behavior of the taginput changed. Previously the first item was focused from the dropdown, so pressing enter was selecting ist. Now you have to manually focus on the results.

Maybe https://github.com/buefy/buefy/issues/3262 is related. Not sure.

### Steps to reproduce

1. click in taginput field with open-on-focus="true"

### Expected behavior

First item of results is focused, so it can be added.

Behavior Buefy 0.8.x:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3062564/233647911-9635a14a-06f6-4bf6-8657-49b97fc382d2.png">

### Actual behavior

No item is focused

Behavior Buefy 0.9.x
<img width="409" alt="image" src="https://user-images.githubusercontent.com/3062564/233647992-72df09e1-107c-4721-8aef-e42bbbcee552.png">

**Comment by jtommy** [comment]
Are you setting `keep-first`?

**Comment by glumb** [comment]
That works, thanks :)
Was not aware that its available on the taginput. 
Maybe it should be added to the docs? https://buefy.org/documentation/taginput

**Comment by jtommy** [comment]
There is an example but maybe we forgot to add in the props list. You might make a PR 😉
