### ISSUE TITLE
Click events in disabled pagination buttons are run

### ISSUE THREAD

**Issue by sermo-de-arboribus** [buefy/buefy#3852]
### Overview of the problem

**Buefy** version: 0.9.23
**Vuejs** version: 2.7.14
**OS/Browser**: Chrome on Windows, Firefox on Windows

### Description

In a setup with custom pagination buttons, button events are even triggered and run when the buttons are displayed as disabled. You can easily see that even on the official buefy.org documentation page for pagination:

### Steps to reproduce

1. Go to https://buefy.org/documentation/pagination/
2. Scroll down to the chapter "Custom pagination buttons"
3. Click on the buttom with the Roman numeral "I"
4. Note that the button labelled with "Previous" is now displayed as disabled
5. Click on the disabled "Previous" button
6. Note that your browser windows scrolls to the top and that the URL line in the address bar of the browser is now including the hash `#page0`. So clearly the click on the disabled "Previous" button has triggered the event as if the button were active.

Another example, this time on our own server:

1. Go to https://dehmel-digital.de/letters/b312969/1
2. Note that the "<" button is (correctly) displayed as disabled
3. Click the disabled "<" button
4. Notice that the page doesn't change and that the URL parameter is changed from 1 to 0 (https://dehmel-digital.de/letters/b312969/0), which doesn't make sense, as there is no page zero.
5. Click the ">" button to try getting back to page 1. It doesn't work, as the system on the whole seems to have gotten into an inconsistent state.

### Expected behavior

I would expect buttons, that are displayed as being disabled, to not trigger the same events that they would trigger if they were active.

**Comment by kikuomax** [comment]
@sermo-de-arboribus `BPaginationButton` tries to trap click events leading to disabled pages from happening. However, `router-link` overwrites this behavior by its own click handler.

As a workaround, you may switch `tag` between `a` and `router-link` according to `disabled` flag in `props.page`:
```vue
            <template #previous="props">
                <b-pagination-button
                    :page="props.page"
                    :tag="props.page.disabled ? 'a' : 'router-link'"
                    :to="`/documentation/pagination#page${props.page.number}`">
                    Previous
                </b-pagination-button>
            </template>
```

@wesdevpro I think we should update the example in docs.
