### ISSUE TITLE
Google Lighthouse issue with b-menu-item because links are not crawlable

### ISSUE THREAD

**Issue by Hyperion2400** [buefy/buefy#3853]
# Problem

b-menu-item only validates links like a, router-link, nuxt-link as a tag.
However not all menu items are links, especially not the ones that contain sub items like 'Administrator' in the example: https://buefy.org/documentation/menu/.

a tags without href are flagged by Google Lighthouse because the links are not crawlable https://developers.google.com/search/docs/crawling-indexing/links-crawlable?hl=en.
I don't know if that carries an SEO penalty but I don't really want to risk it.

it's possible to use something else like a div which I'm doing right now but then you get Vue validation errors.
I wish there was a way to resolve this cleanly. 

# Suggestion

preferrably div tags should be allowed because I don't see a reason why menu items should be restricted to link tags.
I think generally the framework should be SEO compliant.

**Comment by kikuomax** [comment]
@Hyperion2400 Sorry for the late reply. You can add `div` to the `defaultLinkTags` config option: <https://buefy.org/documentation/constructor-options>

**Comment by kikuomax** [comment]
@Hyperion2400 We are closing this issue because there is a workaround suggested. Please open the issue again if the workaround won't work.
