### ISSUE TITLE
Codepen example (bug)

### ISSUE THREAD

**Issue by simonhlee97** [buefy/buefy#3854]
On the documentation page, the [Table-Buefy Example](https://codepen.io/anon/pen/RBWMXE?editors=1010), at Codepen, appears to have a bug and does not properly display the table.

**Comment by wesdevpro** [comment]
Could you please elaborate on what the issue is? I could use some more details before digging into this problem. Also is your Codepen set up correctly? Feel free to reopen this issue when you have further information. Thank you
