### ISSUE TITLE
Progress bar in Notification component is not showing, when "Programmatically opening"

### ISSUE THREAD

**Issue by johnrusu** [buefy/buefy#3855]
Hello,
I'm using the notification with the progress bar and i noticed that if u use "Programmatically opening", the progress bar will not show

Non-working example:
```
this.$buefy.notification.open({
                    message: `I can show you a little progress bar displaying the remaining time!`,
                    duration: 5000,
                    progressBar: true,
                    type: 'is-primary',
                    pauseOnHover: true
                })
```

Thanks!

Buefy version: [0.9.23]
Vuejs version: [2.7.13]
OS/Browser:
Version 113.0.5672.93 (Official Build) (64-bit) Chrome
Version 113.0.1774.35 (Official build) (64-bit) Edge

![image](https://github.com/buefy/buefy/assets/25053517/0a5b2341-5839-4d22-a5db-83c6a2b01d96)

**Comment by guestisp** [comment]
Same here

**Comment by johnrusu** [comment]
@guestisp 
checked the code, apparently u need to use autoClose: true
in Notification.vue
```
 <b-progress
                v-if="autoClose && progressBar"
                class="auto-close-progress"
                :value="remainingTime - 1"
                :max="duration / 1000 - 1"
                :type="type"
                :rounded="false"/>
```

Try this:
```
this.$buefy.notification.open({
                message: `I can show you a little progress bar displaying the remaining time! asdasd`,
                duration: 5000,
                progressBar: true,
                type: "is-primary",
                pauseOnHover: true,
                autoClose: true
            });
```

**Comment by wesdevpro** [comment]
I believe I ran into this issue in the past as well. I will have to check to be sure but I was able to get it working. To be busy at the moment to test this but if you could send a code pen reducing the issue that would be awesome.

**Comment by johnrusu** [comment]
@wesdevpro @guestisp 
https://codesandbox.io/s/silent-architecture-67498s?file=/src/App.vue

**Comment by wesdevpro** [comment]
@johnrusu You have a working solution using the programmatic method 🤣Let me see what I can do to edit the documentation and remove `only not programmatic`

**Comment by guestisp** [comment]
I confirm that adding `autoClose: true` makes the progressbar visible

**Comment by wesdevpro** [comment]
Good deal! I think the best change will be to change the documentation.

**Comment by johnrusu** [comment]
Thx @wesdevpro

**Comment by wesdevpro** [comment]
@guestisp @johnrusu The changes have been made! However, they wont show until we make our next pull into `master` ("main").  I will eventually publish the new changes. Thank you!
