### ISSUE TITLE
.number css rule

### ISSUE THREAD

**Issue by TheTrigger** [buefy/buefy#3858]
Not sure if Buefy or Bulma problem;

I'm using vue-prism and noticed a strange style in numbers, the cause was the `.number` CSS rule

### Overview of the problem

**Buefy** version: `0.9.23`
**Vuejs** version: `2.6.12`
**OS/Browser**: `Chrome 114.0.5735.110`

### Steps to reproduce

1. Import Buefy
2. Import vue-prism-editor prismjs

```html
<div class="content container hero is-fullheight">
  <prism-editor
    class="editor"
    v-model="plainText"
    :highlight="highlighter"
    line-numbers
  ></prism-editor>
</div>
```

### Expected behavior

![image](https://github.com/buefy/buefy/assets/6072718/1387b566-fe1a-42e0-a8c1-7843e9089476)

### Actual behavior

![image](https://github.com/buefy/buefy/assets/6072718/a3552f70-83f4-41b3-a291-d0b409b6bdd1)

### Workaround

Use this between `import 'buefy/dist/buefy.min.css'` and prism import
```css
.editor .number {
  all: unset;
}
```

**Comment by jtommy** [comment]
It's a Bulma class!
