### ISSUE TITLE
Can't set size with Material Design

### ISSUE THREAD

**Issue by guestisp** [buefy/buefy#3866]
This is the component I use to display Material Design icons:
```
<template>
  <component :is="iconName" v-bind="iconProps"></component>
</template>
<script>
import WifiStrength1Alert from 'vue-material-design-icons/WifiStrength1Alert.vue'

export default {
  components: {
    WifiStrength1Alert,
  },
  props: ['icon', 'size'],
  computed: {
    iconPack: function () {
      return this.icon[0]
    },
    iconName: function () {
      return `${this.icon[1].replace(/-./g, x => x.toUpperCase()[1]).replace(/\b\w/g, c => c.toUpperCase())}`
    },
    iconProps: function () {
      return {
        size: parseInt(this.size) || 24
      }
    }
  }
}
</script>

<style lang="scss" scoped>
  .icon svg {
    vertical-align: middle;
  }
</style>
```

Configured in Vue with this:
```
import MaterialDesignIcon from '@/components/MaterialDesignIcon'
Vue.use(Buefy, {
  defaultIconComponent: MaterialDesignIcon,
  defaultIconPack: null
})
```

I'm able to reference a material design icon with something like this: `<b-icon class="is-justify-content-left" custom-size="26" :icon="'wifi-strength-1-alert")"></b-icon>

It works.

But i'm unable to specify the size, in example, this doesn't work:
```
<b-icon
                icon="wifi-strength-1-alert"
                size="is-large"
                type="is-success"
              ></b-icon>
```

I have to specify `customSize` in pixel, like this:
```
<b-icon
                icon="wifi-strength-1-alert"
                customSize="32"
                type="is-success"
              ></b-icon>
```
this breaks almost everything, as most of the time, sizes are specified in strings, ie 'is-large'
Also, even with `customSize` set to a number, i'm unable to set the size with programmatic functions, like the following:

```
    this._vm.$buefy.notification.open({
      message: 'TEST WARNING.',
      duration: 10 * 1000,
      autoClose: true,
      progressBar: true,
      type: 'is-warning',
      pauseOnHover: true,
      hasIcon: true,
      position: 'is-top',
      size: 'is-large',
      customSize: 64,
      iconSize: 64
    })
```

in the component i have nothing of `size`, `customSize` or `iconSize`

any idea on how to use Material Design Icons ?

**Comment by wesdevpro** [comment]
@guestisp  Do you think this is related to the font awesome issue?

**Comment by guestisp** [comment]
Which issue ? i don't use fontawesome so i don't know

**Comment by wesdevpro** [comment]
@guestisp see: https://stackoverflow.com/questions/72962337/large-font-awesome-icons-on-mobile-phone

**Comment by guestisp** [comment]
I don't think it's related, i can see the icon, but i can't set the size, only the default size is used.
Also, having to use `customSize` for components is not good from my point of view as this breaks most things thats rely on standard `size` attribute. (and programmatic calls doesn't work at all even with `customSize`)

**Comment by wesdevpro** [comment]
I will have to get with @kikuomax to discuss changing any properties names and see what we can do to fix this issue. Can you send a codpen? 

The biggest things to keep in mind is the current version of Buefy will eventually be discontinued. We are working right now to move Buefy to vue3. Once we have a working a RC with very little bugs and vue2 is no longer supported we will most likely discontinue Buefy V2. However, nothing is set in stone just yet. 

Some useful links regarding the migration to Buefy V3:
[buefy-next](https://github.com/ntohq/buefy-next/)
[Task for EOL Plan](https://github.com/orgs/ntohq/projects/12/views/1?pane=issue&itemId=33122739)

**Comment by guestisp** [comment]
For this current project i can't migrate to vue3 as this would mean a massive refactor. Everything is working as expected except this thing, hopefully i've almost finished this project and the newer ones would be vue3 (but honestly i prefere vue2, but this is just my personal opinion)

Providing a codepen would be difficult, as this is a massive project. But i've posted the full material design component and the part of the code that makes use of it.

**Comment by guestisp** [comment]
This is a codepen that show the issue:
https://codesandbox.io/s/sleepy-morning-t3hz5n?file=/src/App.vue

**Comment by wesdevpro** [comment]
Well we have until December 31st to fix all the issues with Buefy V2. If we can get them out of the way we can leave all Buefy V2 packages on NPM. This would prevent us from screwing everyone over who will be using vue2 out side of its support period.
If you want to reach out about anything else feel free to catch me on discord.

I will hopefully be able to get back with you about this issue. In one of my personal projects I actually didn't even use the b-icon component. I wonder if I had the same issue.

**Comment by wesdevpro** [comment]
Well we have until December 31st to fix all the issues with Buefy V2. If we can get them out of the way we can leave all Buefy V2 packages on NPM. This would prevent us from screwing everyone over who will be using vue2 out side of its support period.
If you want to reach out about anything else feel free to catch me on discord.

I will hopefully be able to get back with you about this issue. In one of my personal projects I actually didn't even use the b-icon component. I wonder if I had the same issue.

**Comment by wesdevpro** [comment]
> This is a codepen that show the issue: https://codesandbox.io/s/sleepy-morning-t3hz5n?file=/src/App.vue

Thank you so much!

**Comment by kikuomax** [comment]
@guestisp Could this be a workaround?
Configure Buefy like this:
```js
Vue.use(Buefy, {
    defaultIconComponent: MaterialDesignIncon,
    defaultIconPack: 'vue-mdi',
    customIconPacks: {
        'vue-mdi': {
            sizes: {
                'default': 24,
                'is-small': 18,
                'is-medium': 24,
                'is-large': 32
            },
            iconPrefix: ''
        }
    }
});
```

**Comment by wesdevpro** [comment]
Closing because there is a potential workaround. If you are unable to get this to work, please reopen this issue. Thank You!
