### ISSUE TITLE
how can change html validation error label in confirm dialog ?

### ISSUE THREAD

**Issue by id1385** [buefy/buefy#3869]
how can change it ?
![image](https://github.com/buefy/buefy/assets/28746285/22b16181-245a-4677-900f-1fbdd8af2f15)

`
    this.$buefy.dialog.prompt({
        title: 'enter key',
        message: 'plz fill it',
        type: 'is-danger',
        hasIcon: true,
        inputAttrs: {
          type: 'number',
          placeholder: 'enter key number',
           =========> here how can change it ? i think there is not way change it yeah ? 
        },

`

**Comment by wesdevpro** [comment]
@id1385 please try setting `validation-message` to your desired message. Thanks
