### ISSUE TITLE
Problem with Codepen demo from the documentation page

### ISSUE THREAD

**Issue by username1001** [buefy/buefy#3875]
This isn't related to buefy, per se, but on the [documentation page](https://buefy.org/documentation), there's a link to a [codepen](https://codepen.io/anon/pen/RBWMXE?editors=1010). This Codepen doesn't render, with `ReferenceError: Vue is not defined` being displayed in the console. 

It appears that someone (_Captain Anonymous_ :eyes:) forgot to include the libraries (e.g. https://unpkg.com/vue@2/dist/vue.min.js, and https://unpkg.com/buefy/dist/buefy.min.js).

**Comment by wesdevpro** [comment]
@username1001 I am unable to access the codpen at all
![image](https://github.com/buefy/buefy/assets/11604664/94c42594-1488-4b4a-ab5a-8f0ae8ee6b26)

**Comment by username1001** [comment]
@wesdevpro Ah, yikes. That's odd. Can you access it in Firefox? :thinking: 
![codepen](https://github.com/buefy/buefy/assets/11285175/1ce6fdd0-fa6d-4d31-821b-2c89bf2ee1f6)

The table is displayed when I include the CDNs:
![codepen1](https://github.com/buefy/buefy/assets/11285175/6c58ef59-db69-4e09-8c22-210720319bfb)

**Comment by kikuomax** [comment]
The following Codepen should work:
<https://codepen.io/kikuomax/pen/mdopZKj>

**Comment by username1001** [comment]
@kikuomax, @wesdevpro  might want to update the codepen link on this page https://buefy.org/documentation/ to point to that one :)

**Comment by wesdevpro** [comment]
> @kikuomax, @wesdevpro  might want to update the codepen link on this page https://buefy.org/documentation/ to point to that one :) 

We have updated the link here https://github.com/buefy/buefy/commit/6bceb43620a8579b8ab3b7c7c809d514868c420c

The changes will not be on the website until we publish v0.9.28
