### ISSUE TITLE
Datepicker keyboard navigation causes browser hangup

### ISSUE THREAD

**Issue by alerchedahl** [buefy/buefy#3876]
### Overview of the problem

**Buefy** version: 0.9.23
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome/Firefox Win11

### Description

Navigating outside the current month with the keyboard arrow keys in the datepicker component causes browser hangup/freeze.

### Steps to reproduce

1. Open datepicker
2. Press [TAB] until a date cell has focus
3. Navigate with keyboard arrow keys outside of the current month
4. Browser hangup/freeze ensues

### Expected behavior

- datepicker applies focus to a date cell
- browser does not freeze

### Actual behavior

Browser hangup/freeze

https://codepen.io/alerchedahl/pen/LYMNrNO

Looks like the problem is in DatepickerTableRow.vue in the changeFocus function at around line 370 where the while loop never exits.

**Comment by wesdevpro** [comment]
@alerchedahl I'm confused why a loop is even necessary for a key press event

**Comment by wesdevpro** [comment]
```javascript
      changeFocus(day, inc) {
            const nextDay = new Date(day.getTime())
            nextDay.setDate(day.getDate() + inc)
            while (
                (!this.minDate || nextDay > this.minDate) &&
                (!this.maxDate || nextDay < this.maxDate) &&
                !this.selectableDate(nextDay)
            ) {
                nextDay.setDate(day.getDate() + Math.sign(inc))
            }
            this.setRangeHoverEndDate(nextDay)
            this.$emit('change-focus', nextDay)
        }
```
[The code](https://github.com/buefy/buefy/blob/fb73795c47a7da43544531d60d1a2de1149d6b5e/src/components/datepicker/DatepickerTableRow.vue#L364-L376)

**Comment by alerchedahl** [comment]
> @alerchedahl I'm confused why a loop is even necessary for a key press event

Looks like the while loop is checking for a valid focus target and postponing/expediting the target date depending on validity.
There seems to be something going on in the **selectableDate** function that causes the validity to falsify and it keeps iterating forever.

**Comment by kikuomax** [comment]
@alerchedahl Thanks for catching this. I made a PR (#3877) to fix this issue.
