### ISSUE TITLE
Datepicker. Can't change color of prev/next month buttons and selected day.

### ISSUE THREAD

**Issue by Sogl** [buefy/buefy#3882]
### Overview of the problem

**Buefy** version: 0.9.23
**Vuejs** version: 2.7.14
**OS/Browser**: Ububtu Linux (laradock Docker container)

### Description

My code:
```js
<b-field
    :type="{ 'is-danger': formErrors?.birthDate }"
    :message="formErrors?.birthDate">
    <b-datepicker
        size="is-medium"
        placeholder="Дата рождения"
        :focused-date="new Date(1990, 0, 1, 0, 0, 0, 0)"
        locale="ru-RU"
        :first-day-of-week="1"
        icon="calendar-day"
        v-model="formBirthDate">
    </b-datepicker>
</b-field>
```

What I see after adding Datepicker component:
<img width="425" alt="image" src="https://github.com/buefy/buefy/assets/7556290/ba2a0559-8250-4f0f-9024-0ecd9e6d437d">

I usually use the `is-link` [color scheme](https://bulma.io/documentation/elements/tag/#colors) just by adding the appropriate prop (`type="is-link"` for example).

Just because `is-primary` is hardcoded in `Datepicker.vue`:
https://github.com/buefy/buefy/blob/dev/src/components/datepicker/Datepicker.vue#L74
https://github.com/buefy/buefy/blob/dev/src/components/datepicker/Datepicker.vue#L91

### Steps to reproduce

I don't know. I have `is-primary` scheme everywhere by default, which I change either in css or via props in Buefy.
Maybe somewhere I can set `is-link` as the primary color scheme?

### Expected behavior

Ability to change color as in Switch component:
https://buefy.org/documentation/switch#types

### Actual behavior

It is not possible to change the color scheme.

**Comment by wesdevpro** [comment]
@Sogl in your Expected behavior you link the switch component? Did you mean to link the Date Component?

**Comment by wesdevpro** [comment]
Technically the chevron buttons use the b-icon components

![image](https://github.com/buefy/buefy/assets/11604664/aede78db-4d8f-49ff-bc52-decaa088194b)

And according to this line it is set to primary
`type="is-primary is-clickable"`

You will either have to override the color being set by using some css and the keyword !important or you will need to change the css/sass var color for primary.

**Comment by Sogl** [comment]
> in your Expected behavior you link the switch component?

I gave an example of how this is implemented in Switch. The component with the problem is, of course, Datepicker.

> You will either have to override the color being set by using some css and the keyword !important or you will need to change the css/sass var color for primary.

It's a hack, not a solution to the problem. Why not make an option to specify color like in other components ( e.g. Switch)?

**Comment by wesdevpro** [comment]
> > in your Expected behavior you link the switch component?
> 
> I gave an example of how this is implemented in Switch. The component with the problem is, of course, Datepicker.
> 
> > You will either have to override the color being set by using some css and the keyword !important or you will need to change the css/sass var color for primary.
> 
> It's a hack, not a solution to the problem. Why not make an option to specify color like in other components ( e.g. Switch)?
 
It would have to be discussed whether to make this a feature or not. Because at the moment our biggest goal it to migrate to vue3. Therefore, we are not per-say able to accept every feature request. @kikuomax what are your thoughts?

**Comment by kikuomax** [comment]
@Sogl Would you suggest `Datepicker` have a `type` like prop? Unfortunately, `type` is already used by `Datepicker` for another purpose, though.

**Comment by kikuomax** [comment]
@wesdevpro @Sogl Changing the color of the prev/next buttons would be straightforward, but the color of selected dates should be a lot tougher as it is embedded in SCSS and has multiple states.
https://github.com/buefy/buefy/blob/8f3d72b310dc5c142f46f4e26e3ab7e22f0cceec/src/scss/components/_datepicker.scss#L10-L11
https://github.com/buefy/buefy/blob/8f3d72b310dc5c142f46f4e26e3ab7e22f0cceec/src/scss/components/_datepicker.scss#L123-L142
