### ISSUE TITLE
CDN link not working after update

### ISSUE THREAD

**Issue by aguskusmara** [buefy/buefy#3890]
Cdn link not working

https://unpkg.com/buefy@0.9.24/dist/buefy.min.js
Cannot  find "/dist/buefy.min.js" in buefy@0.9.24

**Buefy** version: [0.9.24]]

**Comment by glumb** [comment]
Also the NPM package is not working after the update 😕

this code
```js
import { ModalProgrammatic } from 'buefy'
```

throws the following error after updating to 0.9.24
```
Module not found: Error: Can't resolve 'buefy' in '/..../src/pages/backend'
```
