### ISSUE TITLE
Buefy is giving error when deploy 

### ISSUE THREAD

**Issue by albertomenen** [buefy/buefy#3893]
### Overview of the problem

**Buefy** version: [0.9.24]
**Vuejs** version: [2.6.11]
**OS/Browser**:

### Description

The system give me an error when I tried to deploy, all the versions give me the same error because is not able to found the dependencies specify below.

--------------------

#0 49.32  ERROR  Failed to compile with 2 errors7:38:13 AM
#0 49.32 
#0 49.32 These dependencies were not found:
#0 49.32 
#0 49.32 * buefy in ./src/main.ts
#0 49.32 * buefy/dist/buefy.css in ./src/main.ts
#0 49.32 
#0 49.32 To install them, you can run: npm install --save buefy buefy/dist/buefy.css
#0 49.32  ERROR  Build failed with errors.
#0 49.41 error Command failed with exit code 1.
#0 49.42 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:38
--------------------
  36 |     ARG password_offline
  37 |     RUN node generateOfflineCredentials $user_offline $password_offline
  38 | >>> RUN yarn build
  39 |     
  40 |     FROM nginx:stable-alpine

### Steps to reproduce

 change to any version of buefy 
2. Second Step --> making the yarn build is ok and its working 
3. Final step --> when you try to deploy and in terminal make sudo make or make, the error appears at the last step.
-->

### Expected behavior

 

the deploy should work 

### Actual behavior

 At the final step the system deployment system give me back that error

**Comment by alfred1000351** [comment]
Getting this same error have you found a fix for it?

**Comment by albertomenen** [comment]
Hello Alfred!

Nop, if you just removed buefy is fixed, but in my project we need it so
still waiting and try to solve it.

**Comment by wjsc** [comment]
+1 Same here

**Comment by alfred1000351** [comment]
As a bandaid solution what I did to just get it working is keep the last version that was working for me so these ones below and not let it force an upgrade on deploy

    "buefy": "0.9.4",
    "bulma-helpers": "0.3.12",

**Comment by muhammadawais93** [comment]
Getting the same issue and had to use a lower version, it is not compiling the module at v0.9.24, cant see the dist folder in Buefy.

**Comment by wesdevpro** [comment]
I want to say that this issue is related to https://github.com/buefy/buefy/issues/3890 and a PR exists with https://github.com/buefy/buefy/pull/3891

**Comment by albertomenen** [comment]
I dont know you guys but when I tried to get back to another version the
buefy collaps or either gave me the same error when deploying or remove all
the buefy from the page.

**Comment by wesdevpro** [comment]
@albertomenen have you tried the latest version (`v0.9.25`)?

**Comment by wesdevpro** [comment]
I am closing this issue as we believe we have fixed the issue pertaining to Buefy v0.9.24 (deprecated) by building the dust folder and publishing it as Buefy v0.9.25

**Comment by albertomenen** [comment]
Hello! Yes with the last version is already all fixed.

Thank you very much!
