### ISSUE TITLE
Issue on - postcss-import: @charset must precede all other statements

### ISSUE THREAD

**Issue by mary-josephine-1** [buefy/buefy#3912]
### Overview of the problem

**OS/Browser**: Ubuntu 22.04.3 LTS  - Firefox

**Packages**: package.json
> {
  "name": "testApp",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint:prettier": "prettier --check .",
    "lint": "npm run lint:js && npm run lint:prettier",
    "lintfix": "prettier --write --list-different . && npm run lint:js -- --fix"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/pwa": "^3.3.5",
    "core-js": "^3.25.3",
    "nuxt": "^2.15.8",
    "nuxt-buefy": "^0.4.24",
    "vue": "^2.7.10",
    "vue-server-renderer": "^2.7.10",
    "vue-template-compiler": "^2.7.10"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.19.1",
    "@nuxtjs/eslint-config": "^11.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "eslint": "^8.24.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-vue": "^9.5.1",
    "prettier": "^2.7.1"
  }
}

**Config**: nuxt.config.js

> export default {
  // Disable server-side rendering: https://go.nuxtjs.dev/ssr-mode
  ssr: false,
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'testApp',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [],
  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],
  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,
  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
  ],
  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/buefy
    'nuxt-buefy',
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
  ],
  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    // Workaround to avoid enforcing hard-coded localhost:3000: https://github.com/nuxt-community/axios-module/issues/308
    baseURL: '/',
  },
  // PWA module configuration: https://go.nuxtjs.dev/pwa
  pwa: {
    manifest: {
      lang: 'en',
    },
  },
  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},
}

### Description
Recently I created a Nuxt (v2) app with Buefy.

After creating the project and running it in development mode, found the following issue as per the screenshot.
Searched on google but couldn't find a solution.

### Steps to reproduce

Followed these steps - https://v2.nuxt.com/docs/get-started/installation/

### Actual behavior

![2023-12-07_06-41](https://github.com/buefy/buefy/assets/153145026/75776782-118c-4017-8fc7-e03a6c96be58)

**Comment by mary-josephine-1** [comment]
Thanks for the update.
Can you please guide how to perform this update in my existing projects?

**Comment by mary-josephine-1** [comment]
@wesdevpro 
Thank you. Will wait for the update. 

Hopefully, this update will make the necessary update in the package - `nuxt-buefy`.
We are working in Nuxt(v2).

**Comment by wesdevpro** [comment]
> Hopefully, this update will make the necessary update in the package - `nuxt-buefy`.
> We are working in Nuxt(v2).

You are correct we will also need to update that package (`nuxt-buefy`). Thank you for your patience.

**Comment by mary-josephine-1** [comment]
Hi, 
I hope these updates haven't been published yet.

No changes found in version - `"nuxt-buefy": "^0.4.26",`

**Comment by wesdevpro** [comment]
The project board's automation automatically pushed this issue as it should be listed as Pending Release.
