### ISSUE TITLE
Does Table draggable drag-n-drop work on touch screens?

### ISSUE THREAD

**Issue by kikuomax** [buefy/buefy#3916]
### Discussed in https://github.com/buefy/buefy/discussions/3623

<div type='discussions-op-text'>

<sup>Originally posted by **lownlazy** December 22, 2021</sup>
From what I can see it doesn't but I hope I am missing something. I am using Chrome on Android and using (for example) this site: https://codepen.io/yxngl/pen/oRzdQe  
With a desktop and mouse the rows turn purple when clicked and drag-n-drop as expected. 
In touch screens there seems to be no drag events fired at all, the table behaves as if 'draggable' is set to false. 

Is there some way to enable draggable on a touch screen?

Many thanks for your help with this and the excellent Buefy software.</div>

**Comment by wesdevpro** [comment]
@kikuomax I can confirm that this **code pen** does not work on IOS 16+ Chrome and Safari. Do we have an example of drag-n-drop @https://buefy.org?

**Comment by kikuomax** [comment]
@wesdevpro https://buefy.org/documentation/table/#draggable-rowscolumns

**Comment by wesdevpro** [comment]
@kikuomax I can also confirm that the example we give in the docs is not mobile friendly 😅

**Comment by kikuomax** [comment]
@wesdevpro I removed the `bug` tag from this issue because touch-enabled mobile devices do not support "drag" events. We have to simulate drag&drop with "touch" events. This will be a complete new feature.
