### ISSUE TITLE
unnecessary component duplication in navbar-item 

### ISSUE THREAD

**Issue by Tovli** [buefy/buefy#3939]
### Overview of the problem

**Buefy** version: [0.9.25]
**Vuejs** version: [2.7.15]
**OS/Browser**: Windows10/Vivaldi

### Description
It seems that Buefy creates two navbar-item element with the only difference is the `is-hidden-touch` or `is-hidden-desktop` classes

This cause an issue when getting tests to click the navbar-item as it duplicates the key

### Steps to reproduce
1 - create a navbar with an attribute on its navbar-item:
```
<b-navbar-item
		data-test-id="localeHe"
		@click="switchLanguage"
		>
		he
</b-navbar-item>
```

### Expected behavior

attribute exists only once in the DOM

### Actual behavior
There is a duplicate navbar-item that looks almost exactly the same

Look at the `data-test-id` attribute
![image](https://github.com/buefy/buefy/assets/14282692/bd947dbb-20ca-4362-b9ff-38853d13d5ef)

**Comment by kikuomax** [comment]
@Tovli @wesdevpro I think `<b-navbar-item>` has to be wrapped in a `<b-navbar-dropdown>` to reproduce your issue. For instance:
```vue
<b-navbar-dropdown label="language">
    <b-navbar-item data-test-id="item-lang-en">
        en
    </b-navbar-item>
    <b-navbar-item data-test-id="item-lang-ja">
        ja
    </b-navbar-item>
</b-navbar-dropdown>
```
