### ISSUE TITLE
Show how to install `@ntohq/buefy-next` on buefy.org

### ISSUE THREAD

**Issue by kikuomax** [buefy/buefy#3967]
### Description

Show how to install `@ntohq/buefy-next` on <https://buefy.org>.

### Why Buefy need this feature

While Buefy-next is not production-ready yet, I want to tell people that we are working hard to release it.

**Comment by wesdevpro** [comment]
Must be removed from the documentation add a link to v3.buefy.org?
![image](https://github.com/buefy/buefy/assets/11604664/f8bf8ed1-e76c-447b-9ebd-f11d892cc4b2)
