### ISSUE TITLE
Additional event for blur in autocompletes

### ISSUE THREAD

**Issue by spthiel** [buefy/buefy#4003]
### Description

It's common to clear an autocomplete on blur or to reset the value to the previously selected value. To complete this I'd like to propose an additional event for the autocomplete something like `@inactive`.

### Why Buefy need this feature

As per #3263 the currently suggested solution is to use `@blur` and just clear the element. This however has the unwanted sideeffect that the element is cleared before a selection is made if the dropdown is clicked on.

An example code would be this:
```js
<template>
    <b-autocomplete
        rounded
        v-model="name"
        :data="pretendFilteredData"
        placeholder="e.g. jQuery"
        icon="magnify"
        clearable
        @select="option => selected = option"
        @blur="checkValid">
        <template #empty>No results found</template>
    </b-autocomplete>
</template>
<script>
export default {
    data() {
        return {
            pretendFilteredData: ["foo", "bar", "baz"],
            name: "",
            selected: undefined
        }
    },
    methods: {
        checkValid() {
            let valid = false;
            this.pretendFilteredData.forEach((element) => {
                if (element.toLowerCase() == this.name.toLowerCase()) valid = true;
            });
            if (!valid) this.name = ''; // clear autocomplete
        },
    }
}
</script>
```
And here is the produce of this https://files.elspeth.xyz/file/MTcwNTkxNjMxMjg1OA==.mp4
The short flickering of the placeholder is definitely noticeable whenever you click on the dropdown.

With an event that fired whenever isActive is set to false in the component this could be avoided.

**Comment by wesdevpro** [comment]
https://github.com/buefy/buefy/assets/11604664/d571a7d3-f01b-4f1f-b612-fdec8898348e

**Comment by franciscoh017** [comment]
Why not add the desired logic on the end of your callback function for the @select event?

**Comment by spthiel** [comment]
@franciscoh017 I don't follow how that would help. The select event is not triggered on blur

**Comment by franciscoh017** [comment]
I see. @wesdevpro @spthiel I can make a PR for this if you OK with that.

**Comment by wesdevpro** [comment]
> I see. @wesdevpro @spthiel I can make a PR for this if you OK with that.

Absolutely! All contributions are welcome 🙏🏼 Feel free a PR however don’t pull any changes until they are approved by me or @kikuomax

**Comment by franciscoh017** [comment]
Deleted PR since it was based on a very old fork. However, while working on it and updating my fork, Saw that there's not need for this feature. Just need to use the `active` event that returns a boolean.

https://buefy.org/documentation/autocomplete#api-view

https://codepen.io/franciscoh017/pen/QWPBJGV

**Comment by spthiel** [comment]
Unfortunately after a few months I noticed `@active` does not work in this case either.

The two sideeffects `active` has:
1. Editing a value and pressing ESC will modify the value (one could argue this is intentional but the focus keeps in the element and if instead of resetting to an empty string on invalid you reset to any arbitrary value.)
2. Deleting all content from the field will trigger the event and causing the reset.

Both of these can be seen in this example: https://codepen.io/spthiel/pen/xxojKGQ
(To reproduce type "fo", press escape -> field will change to "value", then try to delete "value")

**Comment by spthiel** [comment]
@wesdevpro could we get this reopened since it was never actually completed?

**Comment by wesdevpro** [comment]
> @wesdevpro could we get this reopened since it was never actually completed?

Hey @spthiel! This issue was closed while @kikuomax and I were focusing on addressing only essential issues (e.g., bugs) before we officially ended maintenance and support for Buefy Vue2. This was due to our migration to Vue3 at the Vue3 fork @ntohq/buefy-next.
