### ISSUE TITLE
Release v0.9.28

### ISSUE THREAD

**Issue by kikuomax** [buefy/buefy#4009]
Steps in order:
- [x] Update `CHANGELOG.md` (#4010)
- [x] ~~Update `README.md` to navigate people to `@ntohq/buefy-next` for Vue 3 support~~ This is already done.
- [x] Rebase `dev` on top of `master`

  This is necessary due to my bad decision to use "rebase and merge" when merging `dev` to `master`

  Steps:

    ```sh
    git checkout master
    git pull
    git checkout dev
    git pull
    git rebase master
    git diff origin/dev..dev
    git push --force
    ```

  `git diff origin/dev..dev` must not show any diffs.
  We have to unlock the branch protection before `git push --force`. 

- [x] Make PR from `dev` to `master` for review (#4011)
- [x] Manually push `dev` to `master` via `git` command after approval (no relevant options on GitHub). More specifically:

    ```sh
    git checkout dev
    git pull
    git checkout master
    git pull
    git merge --ff-only dev
    git push
    ```

**Comment by kikuomax** [comment]
I am going to rebase `dev`.

**Comment by kikuomax** [comment]
Typo: `main` → `master`

**Comment by kikuomax** [comment]
I confirmed `git diff origin/dev..dev` did not output any diffs.

**Comment by kikuomax** [comment]
I unlocked the branch protection of `dev` only for me.

**Comment by kikuomax** [comment]
I force updated pushed to `dev` and enabled branch protection of `dev` again.

**Comment by kikuomax** [comment]
I am going to merge `dev` to `main`.

**Comment by wesdevpro** [comment]
> I am going to merge `dev` to ~`main`~ `master`.

Sounds good!

**Comment by kikuomax** [comment]
`master` is now v0.9.28!
