### ISSUE TITLE
Issues Installing Buefy with Vue2

### ISSUE THREAD

**Issue by torresmald** [buefy/buefy#4012]
**Buefy** version: 0.9.23
**Vuejs** version: [2.6.11]

Hi,

Im having some issues installing Buefy, if I comment the @import "~buefy/src/scss/buefy" in my main.scss all are installing fine;

**This is the error code:**

ERROR in ./src/styles/main.scss (./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./src/styles/main.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
3 │ $carousel-arrow-background: $scheme-main !default;
  │                             ^^^^^^^^^^^^
  ╵
  node_modules/buefy/src/scss/components/_carousel.scss 3:29  @import
  node_modules/buefy/src/scss/buefy.scss 4:9                  @import
  src/styles/main.scss 45:9                                   root stylesheet
 @ ./src/styles/main.scss 2:26-132
 @ ./src/plugins/buefy.client.js
 @ ./src/entry-client.js

**This is my main.scss file:**

$primary: #1fb9b1;
$radius: 0px;
$dark: #181818;
$white: #fff;

$shadow: initial;

@import "~bulma/sass/utilities/_all";

$input-focus-border-color: $primary;
$input-focus-box-shadow-size: 0px;
$input-hover-border-color: $primary;

$rate-color-active: $primary;

$snackbar-background-color: $white;
$snackbar-color: $dark;

$button-focus-box-shadow-size: 0em;

$pagination-current-background-color: $primary;
$pagination-current-border-color: $primary;
$pagination-focus-border-color: $primary;

// Custom colors
$primary-0: #DAF3F2;
$primary-40: #6AD0CB;
$primary-60:#1FB9B1;
$primary-90: #19948E;
$primary-100: #136F6A;

$neutral-10: #FBFBFB;
$neutral-20: #F3F3F3;
$neutral-30: #DBDBDB;
$neutral-40: #C2C2C2;
$neutral-70: #7A7A7A;
$neutral-80: #494949;
$neutral-100: #181818;

$warning-10: #FFDBC7;
$warning-80: #B43132;
$warning-90: #DD4C4D;

@import "~bulma";
@import "~buefy/src/scss/buefy";
@import "./medias";
....

I read the Documentation and all seems ok...

Thanks for the support

**Comment by torresmald** [comment]
![Screenshot from 2024-02-20 14-00-29](https://github.com/buefy/buefy/assets/111706896/6d2e3336-688a-4a0f-b92a-3c902cd80dac)

**Comment by wesdevpro** [comment]
Hey guys please see this issue https://github.com/ntohq/buefy-next/issues/208#issuecomment-2014242574

**Comment by jaybeecave** [comment]
use bulma 0.9.4
