### ISSUE TITLE
Tooltip - `AbortController` is not defined in SSR mode (Nuxt)

### ISSUE THREAD

**Issue by miroslavgeorgiev** [buefy/buefy#4017]
**Buefy** version: [0.9.28]
**Nuxt** version: [2.17.3]

### Description

In the last update of the **Tooltip** component - there is an addon to remove animation on `beforeDestroy` event.
The problem is that it is using `window.AbortController()` without checking are `window` and/or `AbortController` defined.
Both of them are not defined when using **Nuxt with SSR mode**.

### Code source
https://github.com/buefy/buefy/blob/a13d8445ec263cbb817820b45a7ac56b5e7f5648/src/components/tooltip/Tooltip.vue#L288
https://github.com/buefy/buefy/blob/a13d8445ec263cbb817820b45a7ac56b5e7f5648/src/components/tooltip/Tooltip.vue#L334

First - when `AbortController` is registered (row 288) in SSR mode it will be just undefined.
Second -  when using the `abort` method (row 334) without checking it is defined - is causing the error:
```
TypeError
Cannot read property 'abort' of undefined
```

### Expected behavior
Use `AbortController` only after check if `window` and/or `AbortController` are defined.

### Actual behavior

`AbortController` is used without checking for `window` object and/or `AbortController` instance which cause errors.

**Comment by IvayloWogi** [comment]
I have the same problem in my project.

**Comment by kikuomax** [comment]
@miroslavgeorgiev Thanks for reporting an issue. Could you do me a favor; locally build and test if [`fix-window-abort-controller` branch](https://github.com/buefy/buefy/tree/fix-window-abort-controller) resolves the problem? As I am not actively using Nuxt, I do not have an environment where I can quickly test it with Nuxt 2.

FYI: building `fix-window-abort-controller` branch:
```
git fetch https://github.com/buefy/buefy.git fix-window-abort-controller
git checkout FETCH_HEAD
npm ci
npm run build
```

**Comment by miroslavgeorgiev** [comment]
Sure - checking the PR :)
