### ISSUE TITLE
Browser tab freezes, unresponsive, plus possible memory leak with form in modal

### ISSUE THREAD

**Issue by SharkFourSix** [buefy/buefy#4018]
### Overview of the problem

**Buefy** version: 0.9.28
**Vuejs** version: 2.7.16
**OS/Browser**: Ubuntu 22, Firefox, Brave

### Description

Whenever the modal opens and captures focus or when you start typing into the form fields, the tab will freeze.

### Steps to reproduce

1. Navigate to https://jsbin.com/baluzoquvo/edit?html,output
2. Open your browser's "Task Manager". (If you can, mark the window to stay ontop of other windows for better access)
3. Click on "Launch card modal (Component)" button to open the modal
4. If you are lucky, the tab will immediately freeze. If not, simply just start typing into the input fields, pressing tab to advance to the next field. By the time you get to the "Phone" field, your tab will freeze. Another way is to click into any field the first time the modal is open. It seems like the issue has to do with field focus inside the modal?
5. Observe the CPU and memory usage of the tab. Clicking in the unresponsive fields will also increase the memory usage even higher. 

### Expected behavior

Tab should not lock up or have memory spike

### Actual behavior

Inspecting CPU usage in the browser's Task Manager shows memory usage growing rapidly and CPU usage stays at 100%

**Comment by wesdevpro** [comment]
@kikuomax could this be related to #3992?

**Comment by wesdevpro** [comment]
@kikuomax @SharkFourSix 

I was able to reproduce this issue under the following conditions:
OS: Windows 10
Browser: Chrome
@: https://jsbin.com/baluzoquvo/edit?html,output
Buefy version: 0.9.28
Vuejs version: 2.7.16

Before: 
![image](https://github.com/buefy/buefy/assets/11604664/676bd521-de51-4e04-a506-da7397ffcc95)

After(I had to select a form input to get the tab to freeze and start using more CPU than necessary):
![image](https://github.com/buefy/buefy/assets/11604664/d4a4426d-72e0-4d00-a312-f91b67468c4a)

**Comment by kikuomax** [comment]
@SharkFourSix @wesdevpro I was also able to reproduce the error on Safari and Chrome on my M1 mac.

**Comment by kikuomax** [comment]
@SharkFourSix @wesdevpro It seems the validation message on a horizontally grouped field is causing the problem.

**Comment by wesdevpro** [comment]
> @SharkFourSix @wesdevpro It seems the validation message on a horizontally grouped field is causing the problem.

Interesting

**Comment by SharkFourSix** [comment]
> @SharkFourSix @wesdevpro It seems the validation message on a horizontally grouped field is causing the problem.

I removed the ```grouped``` attribute and rearranged the form and the issue disappeared.

**Comment by kikuomax** [comment]
> Interesting. How were you able to pin it down to the grouped field?

@wesdevpro @SharkFourSix 
1. I found it froze when I focused the first or last name field and immediately moved the focus to another element. No validation message was shown before freeze.
2. If I removed `required` attributes from the first and last name fields, it no longer froze.
3. If I removed the `grouped` and `horizontal` attributes from the first and last name fields, and rearranged the form, like @SharkFourSix did, it did not freeze either.

**Comment by kikuomax** [comment]
@wesdevpro @SharkFourSix So `Modal` does not matter to this issue, the following is a kind of minimal reproduction code:
```vue
<template>
    <b-field grouped horizontal label="Name">
        <b-input placeholder="First name" required></b-input>
        <b-input placeholder="Last name" required></b-input>
    </b-field>
</template>
```

**Comment by kikuomax** [comment]
@wesdevpro @SharkFourSix I confirmed that the problem did not happen in [Buefy-next](https://github.com/ntohq/buefy-next) v0.1.2.

**Comment by kikuomax** [comment]
> I confirmed that the problem did not happen in [Buefy-next](https://github.com/ntohq/buefy-next) v0.1.2.

@wesdevpro @SharkFourSix I was wrong, it happens in Buefy-next v0.1.2 too. But the browser did not freeze thanks to Vue 3's detecting infinite updates.

**Comment by kikuomax** [comment]
The following `watch` got infinite updates:
https://github.com/buefy/buefy/blob/f3a964d984c9f5882567eee6f5677566cff657b6/src/components/field/Field.vue#L231-L240

**Comment by kikuomax** [comment]
The slot of the horizontally grouped `<b-field>` will be wrapped in `<b-field-body>` when it is rendered:
```vue
<div class="field is-horizontal">
    <b-field-body :message="formattedMessage" :type="newType">
        <b-input placeholder="First name" required></b-input>
        <b-input placeholder="Last name" required></b-input>
    </b-field-body>
</div>
```

`<b-field-body>` will wrap each `<b-input>` in `<b-field>` under a `<div>` element:
```vue
<div class="field is-horizontal">
    <div class="field-body">
        <b-field :message="formattedMessage" :type="newType">
            <b-input placeholder="First name" required></b-input>
        </b-field>
        <b-field :type="newType">
            <b-input placeholder="Last name" required></b-input>
        </b-field>
    </div>
</div>
```

Please note that the above snippets are simplified to make explanation easier.

Here are steps happening in the infinite updates:
1. When `<b-input>` reports a validation error, the error message is put into the `newMessage` data field of its immediate parent `<b-field>` (inner `<b-field>`).
2. The inner `<b-field>` puts the updated `newMessage` value into the `newMessage` data field of its parent `<b-field>` (outer `<b-field>`).
3. The outer `<b-field>` updates the `formattedMessage` computed when its `newMessage` data field is changed. `formattedMessage` produces a fresh new array every time it is updated.
4. The outer `<b-field>` supplies the updated `formattedMessage` to the `message` prop of the inner `<b-field>`.
5. The inner `<b-field>` updates its `newMessage` data field when the `message` prop is changed.
6. The inner `<b-field>` puts the updated `newMessage` value into the `newMessage` data field of the outer `<b-field>`.
7. The outer `<b-field>` updates the `formattedMessage` computed value because its `newMessage` data field is updated. Because `formattedMessage` produces a brand new array every time it is updated, the resulting `formattedMessage` is different from the previous one although containing the same message.
8. The outer `<b-field>` supplies the updated `formattedMessage` to the `message` prop of the inner `<b-field>`.
9. Repeat from Step 5

**Comment by SharkFourSix** [comment]
> 9. Repeat from Step 5

So how can the cycle be broken given that it's a property change event rather a function call?

**Comment by kikuomax** [comment]
> > 9. Repeat from Step 5
> 
> So how can the cycle be broken given that it's a property change event rather a function call?

@SharkFourSix @wesdevpro Possible solutions are
1. Let `watch` of the `message` prop make sure the contents of the updated value are different from those of `newMessage` before replacing `newMessage`:

   https://github.com/buefy/buefy/blob/f3a964d984c9f5882567eee6f5677566cff657b6/src/components/field/Field.vue#L224-L226

2. Let `formattedMessage` return `newMessage` as is (no new array) if `newMessage` is an array containing only `string`s:

   https://github.com/buefy/buefy/blob/f3a964d984c9f5882567eee6f5677566cff657b6/src/components/field/Field.vue#L158-L186

The first one needs deep comparison of two arbitrary values, which is [not as easy as people might think](https://stackoverflow.com/questions/1068834/object-comparison-in-javascript). However, `JSON.stringify` should be sufficient here. I like the second one, but it might be too "clever".

**Comment by kikuomax** [comment]
@SharkFourSix Btw, do you have any specific reason for combining `grouped` and `horizontal`? Simply removing `grouped` may work around the issue:
```vue
<b-field horizontal label="Name">
    <b-input placeholder="First name" required></b-input>
    <b-input placeholder="Last name" required></b-input>
</b-field>
```

I found Buefy was not designed to combine `grouped` and `horizontal`. Even if we fixed the infinite recursion issue, there would be another issue that once the validation error state is set, it won't be reset after correcting the value.

**Comment by SharkFourSix** [comment]
Well, for organizing the input fields.

I have since changed the layout because the issue would have stalled my progress 😁.

The problem along with its solution is worth a note though as I'm sure that someone else crazier than me will do the same thing at some point.
