### ISSUE TITLE
proxyMiddleware error

### ISSUE THREAD

**Issue by MovingW** [buefy/buefy#4032]
When I add proxytable in /config/index.js for dev environment, it pops out an error "TypeError: proxyMiddleware is not a function" in /build/dev-server.js: 48. Anyone knows how to fix it? Thanks a lot.

```
proxyTable: {
          '/api': {
              target: 'http://localhost:8000', 
              changeOrigin: true,
              pathRewrite: {
                  '^/api': '' 
              }
          }
      },
```

<img width="634" alt="image" src="https://github.com/buefy/buefy/assets/148598755/70a3e204-fdbd-4121-aad5-65931aee5d1f">

**Comment by kikuomax** [comment]
@MovingW 
I found [I bumped `http-proxy-middleware`](https://github.com/buefy/buefy/commit/1758e63fe0498b6562f25afd9f3565dbc1734ea3) without testing the `proxyTable` config in the build script. It used to depend on `http-proxy-middleware@0.17.3` but `@2.0.6` now. The interface of `http-proxy-middleware` changed from 0.17.3 to 2.0.6.

For now, could you
- Reinstall `http-proxy-middleware@0.17.3`,
- Or migrate the code in `/build/dev-server.js`?

**Comment by MovingW** [comment]
> @MovingW I found [I bumped `http-proxy-middleware`](https://github.com/buefy/buefy/commit/1758e63fe0498b6562f25afd9f3565dbc1734ea3) without testing the `proxyTable` config in the build script. It used to depend on `http-proxy-middleware@0.17.3` but `@2.0.6` now. The interface of `http-proxy-middleware` changed from 0.17.3 to 2.0.6.
> 
> For now, could you
> 
> * Reinstall `http-proxy-middleware@0.17.3`,
> * Or migrate the code in `/build/dev-server.js`?

Thanks. It worked after migrating the `dev-server.js`

```
const{createProxyMiddleware} = require('http-proxy-middleware')

Object.keys(proxyTable).forEach((context) => {
    const options = proxyTable[context]
    const proxyMiddlewareInstance = createProxyMiddleware(context, options)
    app.use(proxyMiddlewareInstance)
})
```

**Comment by kikuomax** [comment]
@MovingW We would appreciate if you could make a PR.
