### ISSUE TITLE
Types icons in input do not change when using the font-awesome pack

### ISSUE THREAD

**Issue by mikejavier** [buefy/buefy#442]
### Overview of the problem

**Buefy** version: [0.6.1]

### Description

![image](https://user-images.githubusercontent.com/5166571/33240617-97046ae2-d297-11e7-88a2-e0cb7a9dd04f.png)

Hey guys, when was doing this #441 I realized that even set the property `icon-pack="fa"` 
the types of icons (succes, error, warning) come in the MDI version. Is this the expected behavior?

**Comment by rafaelpimpa** [comment]
Did you use ``defaultIconPack`` ?

**Comment by mikejavier** [comment]
@rafaelpimpa No, i changed to use font-awesome

**Comment by rafaelpimpa** [comment]
You have to set ``defaultIconPack: 'fa'`` in your construction options: https://buefy.github.io/#/documentation/constructor-options
