### ISSUE TITLE
funky formatting on select input

### ISSUE THREAD

**Issue by gwvt** [buefy/buefy#45]
In Chrome, select inputs default to native formatting, and the downward caret is pushed to the far right. In Firefox, formatting of the select inputs behaves as expected, but the downward caret is still pushed to the far right.

Screenshots for Chrome&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* see caret pushed to right *
1:
<img width="953" alt="chrome 1" src="https://cloud.githubusercontent.com/assets/17604801/25446163/9d275fe0-2a7e-11e7-8e45-f2674097c131.png">
2:
<img width="963" alt="chrome 2" src="https://cloud.githubusercontent.com/assets/17604801/25446166/9f3a6a98-2a7e-11e7-92f9-f192df7a0fc4.png">

Screenshots for Firefox

1:
<img width="1160" alt="firefox 1" src="https://cloud.githubusercontent.com/assets/17604801/25446175/a750542c-2a7e-11e7-8f84-4c4ecf7c3292.png">
2:
<img width="1152" alt="firefox 2" src="https://cloud.githubusercontent.com/assets/17604801/25446178/a89555a8-2a7e-11e7-950c-b1731f7abb1a.png">

**Comment by rafaelpimpa** [comment]
How can I reproce it?

**Comment by gwvt** [comment]
Here's my full code:

```
        <b-field label="State">
          <p v-if="!editing">{{ profile.state }}</p>
          <b-select v-else :placeholder="updatedProfile.state ? `${updatedProfile.state} ` : 'Select state'" v-model="updatedProfile.state">
            <b-option v-for="state in listOfStates" :value="state" :key="state">
              {{ state }}
            </b-option>
          </b-select>
        </b-field>
```

But the effects are the same with this simplified, self-contained code:
```
        <b-field label="State">
          <b-select>
            <b-option v-for="state in ['VT', 'MA', 'OR', 'KS']" :value="state" :key="state">
              {{ state }}
            </b-option>
          </b-select>
        </b-field>
```

You can also see similar problems with the formatting (but not the caret) on the Buefy documentation page when viewed in Chrome.

**Comment by rafaelpimpa** [comment]
The ``b-select`` now uses the native select, that's why formatting looks different.
Gonna dig the caret bug.

**Comment by rafaelpimpa** [comment]
I tried different ways but couldn't reproduce the caret bug in any way. Is this happening to anyone else? Maybe it's bugging on mac only? Tried different browsers on different pages but nothing.

**Comment by gwvt** [comment]
Upgraded to 0.3.1/Vue 2.3.3 and still seeing the same issue in both Chrome and Firefox:

<img width="237" alt="screen shot 2017-05-16 at 11 56 44 am" src="https://cloud.githubusercontent.com/assets/17604801/26115758/fa77def8-3a2e-11e7-860e-1328f79ad7fb.png">
<img width="253" alt="screen shot 2017-05-16 at 11 56 56 am" src="https://cloud.githubusercontent.com/assets/17604801/26115761/fc2cb048-3a2e-11e7-8e78-1a32ac39fba0.png">
<img width="288" alt="screen shot 2017-05-16 at 11 57 13 am" src="https://cloud.githubusercontent.com/assets/17604801/26115763/fdc21fe2-3a2e-11e7-8912-3f8eb6051d97.png">

Then playing around this happens:

```
<b-field label="State">
    <b-select placeholder="select state">
      <option v-for="state in ['VT', 'MA', 'OR', 'KS']" :value="state" :key="state">
        {{ state }}
      </option>
    </b-select>
</b-field>
```

produces:

<img width="495" alt="screen shot 2017-05-16 at 12 20 39 pm" src="https://cloud.githubusercontent.com/assets/17604801/26116720/1ed89780-3a32-11e7-93ba-812afdf603f4.png">

Then changing the code to

```
<b-field label="State">
  <p>
    Select:
  </p>
  <div>
    <b-select placeholder="select state">
      <option v-for="state in ['VT', 'MA', 'OR', 'KS']" :value="state" :key="state">
        {{ state }}
      </option>
    </b-select>
  </div>
</b-field>
```

With hot reload of webpack dev server produces:

<img width="476" alt="screen shot 2017-05-16 at 12 22 45 pm" src="https://cloud.githubusercontent.com/assets/17604801/26116796/6615648e-3a32-11e7-8c79-8e8de1254416.png">

But without changing the code, refreshing the page from the browser produces:

<img width="251" alt="screen shot 2017-05-16 at 12 23 27 pm" src="https://cloud.githubusercontent.com/assets/17604801/26116829/7dd59b5c-3a32-11e7-93c7-c5c01adcb632.png">

Changing the code back to

```
<b-field label="State">
    <b-select placeholder="select state">
      <option v-for="state in ['VT', 'MA', 'OR', 'KS']" :value="state" :key="state">
        {{ state }}
      </option>
    </b-select>
</b-field>
```

hot reload of webpack dev server produces:

<img width="188" alt="screen shot 2017-05-16 at 12 25 09 pm" src="https://cloud.githubusercontent.com/assets/17604801/26116902/bb35d48a-3a32-11e7-9e72-069602e914ca.png">

And again, only refreshing the page produces:

<img width="475" alt="screen shot 2017-05-16 at 12 25 36 pm" src="https://cloud.githubusercontent.com/assets/17604801/26116915/cab582fc-3a32-11e7-87aa-36fd83e264e5.png">

**Comment by rafaelpimpa** [comment]
It's so weird because:
* I cannot reproduce this
* It's just an HTML select with Bulma style, nothing more

I'm in the blind spot for this issue TBH, will try again to repro this but can't guarantee 😞

**Comment by gwvt** [comment]
Thanks for your reply. Could there be any other dependencies in play, like the vue style loader? (I have 3.0.1 installed... I can post my complete list of node modules if that would be useful.)

**Comment by rafaelpimpa** [comment]
Sure, anything might be helpful!

**Comment by gwvt** [comment]
Here you go :-)
```

{
  // ...
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
  },
  "dependencies": {
    "buefy": "^0.3.1",
    "vue": "^2.3.3",
    "vue-resource": "^1.3.1",
    "vue-router": "^2.5.3"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.0",
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.0.0",
    "babel-plugin-istanbul": "^4.1.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.4.0",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.24.1",
    "chai": "^3.5.0",
    "chalk": "^1.1.3",
    "chromedriver": "^2.29.0",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.0",
    "cross-spawn": "^5.1.0",
    "css-loader": "^0.28.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb-base": "^11.2.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.3",
    "eslint-plugin-import": "^2.2.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.15.2",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "function-bind": "^1.1.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.4",
    "inject-loader": "^3.0.0",
    "json-loader": "^0.5.4",
    "karma": "^1.7.0",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sinon-chai": "^1.3.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.31",
    "karma-webpack": "^2.0.3",
    "lolex": "^1.6.0",
    "mocha": "^3.4.1",
    "nightwatch": "^0.9.15",
    "opn": "^5.0.0",
    "optimize-css-assets-webpack-plugin": "^1.3.1",
    "ora": "^1.2.0",
    "phantomjs-prebuilt": "^2.1.14",
    "rimraf": "^2.6.1",
    "selenium-server": "^3.4.0",
    "semver": "^5.3.0",
    "sinon": "^2.2.0",
    "sinon-chai": "^2.10.0",
    "url-loader": "^0.5.8",
    "vue-loader": "^12.0.4",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.3.3",
    "webpack": "^2.5.1",
    "webpack-bundle-analyzer": "^2.8.1",
    "webpack-dev-middleware": "^1.10.2",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by rafaelpimpa** [comment]
What's wrappint the select? Any ``.control`` or anything?

**Comment by gwvt** [comment]
No, only as above -- either <b-field> or <div>.

**Comment by gwvt** [comment]
Finally returned to this issue...

Adding this styling makes the caret display as expected:

`.b-select-fix-caret {
  width: auto;
  float: left;
}`

Yields:

<img width="123" alt="caret yay" src="https://user-images.githubusercontent.com/17604801/28922755-6c6d3836-7829-11e7-934d-d8dcc05f7248.png">
Applying the style to either <b-select> or the <b-field> wrapper works.

**Comment by rafaelpimpa** [comment]
I would love to know if there's anyone else with this issue.

**Comment by NightOwlPrgmr** [comment]
@rafaelpimpa I've just run into this same issue and the only way I've found to fix the missing caret is by adding the following CSS to either the specific element or to all inputs in general (which is what I did):

`position: unset`

Buefy applies a `position: relative` to all `.input` and `.select` classes, which mucks up the works for whatever reason. Hope this helps someone else.
