### ISSUE TITLE
Problem with  slot-scope="props" row (undefined) in b-table

### ISSUE THREAD

**Issue by phpedinei** [buefy/buefy#460]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.9]
**OS/Browser**: All

### Description

I'm using nuxt.
The below error is occurring when using scoped slot
[Vue warn]: Error in render function: "TypeError: Cannot read property 'row' of undefined"

### Steps to reproduce

I am using the first doc example: 
https://buefy.github.io/#/documentation/table

**Comment by p418** [comment]
I was getting same error and was able to resolve it by changing from `<template slot-scope="props">` to `<template scope="props">`

I dont really know why but it seems to work

**Comment by rafaelpimpa** [comment]
@p418 maybe becasue your vue version is <2.5

@phpedinei how's your code?

**Comment by jaybeecave** [comment]
Check your vue-template-compiler version also.

**Comment by LoneRifle** [comment]
For those of you reading this, ensure you update `vue-server-renderer` as well.

**Comment by breadadams** [comment]
@p418's solution fixed a _similar_ issue I was facing with scoped-slots. I'm on vue & vue-template-compiler versions `^2.5.13`. Using parcel for bundling.
