### ISSUE TITLE
content not destroyed after close modal

### ISSUE THREAD

**Issue by okmkey45** [buefy/buefy#466]
Hello. First time using this package and it is really nice.

I have a question. I am using the modal component to display some content but I need that this content keeps alive and it can´t be destroyed when I close the modal. Is there any way to accomplish this or maybe I didn´t read well the docs.

I hope you can help me. Thanks.

**Comment by rafaelpimpa** [comment]
If you use the ``<b-modal>`` component with the ``active`` prop to show/hide it should stay alive.

**Comment by okmkey45** [comment]
Hi. Sorry but I didn´t undestand completely. I will share my code because it seems it does not work.

```
<template>
    <div class="manager">
         <b-modal :active.sync="searchAvailabilityModal" has-modal-card>
             <search-appointment-availability></search-appointment-availability>
         </b-modal>
    </div>
</template>

<scrip>
export default {
    data() {
        return {
             searchAvailabilityModal: false
        }
    }
}
</script>
```

searchAvailabilityModal is the boolean controlling the modal. Inside my componente "search-appointment-availability" , I started to use "$parent.close()" and I guess that using this to close the modal is what you mean with "Programmatic"

Even in my parent component I have tried to manipulate the boolean to open and close the modal bit it continues destroying the modal.

**Comment by rafaelpimpa** [comment]
Actually, I forget that it uses ``v-if`` internally. Currently there's no way to keep modal alive, should use [bulma classes instead](https://bulma.io/documentation/components/modal/)

**Comment by okmkey45** [comment]
ok, thanks for the help. You might consider add some prop to let choose between v-if and v-show. It could be useful.

Great package.

**Comment by rafaelpimpa** [comment]
Sure, we going to make some changes to every modal/global component, will have this in mind :)

**Comment by connor11528** [comment]
Thanks @rafaelpimpa the docs for modals with vue bootstrap are very clean. Perhaps we could have similar behavior with Bulma? https://bootstrap-vue.js.org/docs/components/modal
