### ISSUE TITLE
+/- quantity spinner component

### ISSUE THREAD

**Issue by neovive** [buefy/buefy#473]
Feature request moved from the discussion in #458.

### Description
One small component I often use on projects is a quantity +/- spinner. It's commonly used in shopping carts and improves the UX (especially on mobile) anywhere users need to increase or decrease an integer value on a form input. It's typically built as a series of input fields with some props for min/max and a debounce.

Here's an example Vue component:

![spinner](https://user-images.githubusercontent.com/99479/33951912-43eafd5c-dffe-11e7-8590-b3e29c82fddc.png)

[GitHub source for an existing Vue spinner component](https://github.com/krystalcampioni/vue-number-input-spinner/)

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/87ed99d5c3e83854761e9d24552dc8773d65fc8e
