### ISSUE TITLE
AutoComplete default value

### ISSUE THREAD

**Issue by chris4dd** [buefy/buefy#476]
It's a nice-to-have feature that if we can set default value for AutoComplete.

I can manage this by setting default value when AutoComplete mounted using setSelected method, but there is a close dropdown animation which is annoying. Is it possible the watcher not trigger when I set default value for it?

**Comment by jtommy** [comment]
@chris4dd Yes at the moment is the only way to set a default value. Anyway could you provide us an example of dropdown animation (annoying) when you set a default value ?
