### ISSUE TITLE
Computed Data in table column no re-rendering properly

### ISSUE THREAD

**Issue by roni-estein** [buefy/buefy#484]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.8]
**OS/Browser**: MacOS High Sierra, Chrome

### Description

When using a buefy table. if Ihave some computed element, not straight text. When I splice the row out the computed sections don't refresh. Specifically, in my case I'm, using a font awesome icon check.

When I approve a line from the table it will disappear (i splice it out and update the dataset under the hood. All the data re-renders correctly, however, if I have a font awesome check in the row I splice out, And the row below it does not have a check, when the row below moves up it will somehow get the check even though the dataset shows it shouldn't.

If I refresh the page, the row is still missing as it's been updated in the backend, however all the checks move into the correct place.

Here are some illustrative screenshots, in this example user 7 has a check under the pen and user 8 does not

<img width="980" alt="screen shot 2017-12-19 at 4 36 17 am" src="https://user-images.githubusercontent.com/8517475/34153039-3b3ec72a-e476-11e7-83d6-05538a463c45.png">

After clicking the "verify button" (removing from the list) and updating the backend with axios, user 8 now has check, even though they shouldn't

<img width="904" alt="screen shot 2017-12-19 at 4 39 04 am" src="https://user-images.githubusercontent.com/8517475/34153127-9a701956-e476-11e7-9de2-c29b1cc2b225.png">

Doing a browser refresh on the data shows the following, the data is now back to normal, except for the update which has already happened. Notice also the same issue happened with user 11 loosing it's check as it moved up, yet after refresh it is correct again.

<img width="911" alt="screen shot 2017-12-19 at 4 41 18 am" src="https://user-images.githubusercontent.com/8517475/34153225-e61219ea-e476-11e7-8829-af7d542b6d91.png">

So somehow, there is a pollution but only from the icon rendering.

Here is the code that renders the data

```

<b-table
        :data="filteredData"
        :loading="isLoading"
        class="m-t-10"
>
    <template slot-scope="props" slot="header">

        <span class="has-text-centered" v-if="props.column.field === 'signature'"><i class="fa fa-pen-alt"></i></span>
        @{{props.column.label}}
    </template>
    <template slot-scope="props">
        <b-table-column field="id"
                        label="Order" width="40" sortable numeric
                        class="has-text-weight-bold is-size-8 has-text-centered">

            @{{ props.row.id }}
        </b-table-column>

.
.
.

<!-- the offending column -->
<b-table-column field="signature" label="">
    <i :class="props.row.signature !== null?'fa fa-check':''"></i>
</b-table-column>


```
I've tried v-if's and other hacks. I can get this to work using my own search table without difficulty, but I'm a bit new to vue, so using b-table is a great time saver.

It's also very slow to render on lists showing more than 150 items which has to be done on occasion. Sometimes 5-10 seconds, when the db seems to process the query in less than a millisecond.

### Expected behavior

I'd expect the row to disappear and not pollute the visual data.

### Actual behavior

The data is bleeding onto other rows.

Please let me know if I can share anything else that might help.

**Comment by jtommy** [comment]
@roni-estein I undestand the problem but it's no easy help you because we don't know what happen when you remove the row (splice) and "update the dataset ...". 
Could you provide us a quite complete example ?

**Comment by roni-estein** [comment]
Sure, I'll keep adding anything you, need. For paginated and smaller dataset tables this is awesome. Probably also for larger ones, and I'm just using it incorrectly :).
 
First, here is the function that gets the data.

```

updateResults: _.debounce(
    function () {
        this.isLoading = true;
        axios.get('/api/v1/verify/', {
            params: {
                api_token: this.api_token,
                show_verified: this.isVerified,
            }
        }).then((entries) => {

            this.tableData = entries.data;
            this.isLoading = false;
            //this.$emit('remove', id)
        }).catch((error) => {
            console.log('ERROR ' + error);
            this.isLoading = false;
        })
    }, 500

),

```

When this pulls from this PHP dataset in larave from mysql, returns about 200 rows in approx 1 ms:

```

public function getVerifyList(Request $request)
{
    $orders = DB::select(  'select 
                            o.id, o.created_at,o.took,o.owing,o.has_current_rx,o.prescriber_id,o.signature, o.has_card,
                            u.id as uid, concat(u.first_name,\' \',u.last_name) as username, u.gender_id, 
                            concat(substring(u.phone_number,1,3),\'-\',substring(u.phone_number,4,3),\'-\',substring(u.phone_number,7)) as phone, u.email,
                            c.abbr, p.number
                            from orders o
                            inner join users u on o.user_id = u.id
                            left join insurance_companies c on o.insurance_company_id = c.id
                            left join insurance_plans p on o.insurance_plan_id = p.id 
                            where 
                            verified = 0
                            and mark_for_investigation = 0
                            -- and has_card = 1
                            ');

    return response($orders,200);
}

```

and then here is the table itself

```

<b-table
                        :data="filteredData"
                        :loading="isLoading"
                        class="m-t-10"
                >
                    <template slot-scope="props" slot="header">

                        <span class="has-text-centered" v-if="props.column.field === 'signature'"><i class="fa fa-pen-alt"></i></span>
                        @{{props.column.label}}
                    </template>
                    <template slot-scope="props">
                        <b-table-column field="id"
                                        label="Order" width="40" sortable numeric
                                        class="has-text-weight-bold is-size-8 has-text-centered">

                            @{{ props.row.id }}
                        </b-table-column>

                        <b-table-column field="username"
                                        label="Name"
                        >

                            @{{ props.row.username}}
                        </b-table-column>


                        <b-table-column field="signature" label="">
                            <i :class="props.row.signature !== null?'fa fa-check':''"></i>
                        </b-table-column>

                        <b-table-column field="phone" label="Phone">
                            @{{ props.row.phone}}
                        </b-table-column>
                        <b-table-column field="email" label="Email">
                            @{{ props.row.email}}
                        </b-table-column>

                        <b-table-column field="owing" label="Owe" centered>
                            @{{ props.row.took}}
                        </b-table-column>

                        <b-table-column field="owing" label="Owe" centered>
                            @{{ props.row.owing}}
                        </b-table-column>


                        <b-table-column field="date" label="Registed On" sortable>
                            {{--<span class="tag is-success"></span>--}}
                                @{{ new Date(props.row.created_at).toLocaleDateString() }}

                        </b-table-column>

                        <b-table-column field="has_current_rx" label="Has Rx" centered>
                            <i :class="props.row.has_current_rx === 1?'fa fa-check':''"></i>
                        </b-table-column>

                        <b-table-column label="    ">
                            <a class="button is-purple has-text-weight-bold is-size-7">EDIT</a>
                        </b-table-column>

                        <b-table-column label=" ">
                            <a class="button is-orange has-text-weight-bold is-size-7" @click="verifyOrder(props.row.id,props.index)">VERIFY</a>
                        </b-table-column>

                    </template>
                    <template slot="empty">
                        <section class="section">
                            <div class="content has-text-grey has-text-centered p-t-30 p-b-75" v-if="isLoading">
                                <p>LOADING ...</p>
                            </div>
                            <div class="content has-text-grey has-text-centered" v-if="! isLoading">
                                <p>
                                    <i class="fal fa-frown fa-7x"></i>
                                </p>
                                <p>Nothing here.</p>
                            </div>
                        </section>
                    </template>
                </b-table>

```

and finally the update function

```

verifyOrder(order,index) {
    axios.get('/api/v1/verify-order',{
       params:{
           api_token: this.api_token,
           order_id: order,
           api_user: this.api_user
       }
    }).then((response) =>{
        this.filteredData.splice(index,1);
    });
},

```

Thanks for looking into this, it's a really nice and fast way to get a vue-table running.

**Comment by roni-estein** [comment]
A slight update, once I removed the functions to determine if the check should show or any other function, the table has vastly increased in speed and doesn't loose state, here is an example:

<img width="911" alt="screen shot 2017-12-19 at 4 41 18 am" src="https://user-images.githubusercontent.com/8517475/34169488-2dd0424e-e4ad-11e7-9d30-1bc33d41cf9b.png">

Now marking the user, now after marking user 7 verified,

<img width="904" alt="screen shot 2017-12-19 at 11 10 49 am" src="https://user-images.githubusercontent.com/8517475/34169544-59ad7d0a-e4ad-11e7-8ca7-1ffb22594f61.png">

State is as it should be with no reloads. And is the same speed or close enough as my own native vuetable component. It seems like the way I'm modifying the column data in my own vue table which appears to be weightless there, in this version is extremely heavy.

Can you perhaps look at how this could be accomplished in a better way? Perhaps add it in the tutorials section, of the tables as I'm sure it's very often spec'd to have icons and colours in reporting.

If I can assist further please advise.

**Comment by jtommy** [comment]
@roni-estein It's very strange... Just out of curiosity, did you try to use a method to check `props.row.signature` (I know that it isn't the best way because will be call for each rendering)  ? Or without using computed for `filteredData` ?
For example:
```
<i :class="hasSignature(props.row) ?'fa fa-check':''"></i>
```

**Comment by roni-estein** [comment]
@jtommy , it did originally. It seems to have a speed impact and didn't make any behavioural change. I haven't taken out the computed filtered data, it's a critical part of the spec:

<img width="910" alt="screen shot 2017-12-19 at 4 24 20 pm" src="https://user-images.githubusercontent.com/8517475/34181909-b02da656-e4d9-11e7-9a05-85c7a7c66f5d.png">

without the filter box, people would be looking through 200 similar items all the time. It's actually my primary reason for using a vue-table instead of just a html template. I can revisit the function concept and see if it makes a difference at this juncture and post the results.

We are transitioning a workflow, and I'm not a Vue guru yet, so I've been just making individual search tables. It's not that bad but using vue table is easily 3-4 times faster for me if not more. Plus you can column sort on the rare occasions. We have already 20 such reports and growing for different job types, so I'd hate to go back and transition every table to it's own entity. At least not until, we get to a revision stage.

Thanks for you input. Also if you see a way I could be doing things "better" please don't hesitate to comment.

**Comment by roni-estein** [comment]
Nope, didn't like it.

I implemented it as follows:

```
methods: {

  hasSignature(row){
      return row.signature != null;
  },
},

```
and this

```

<i :class="hasSignature(props.row) ?'fa fa-check':''"></i>


```

in the body. Same exact problem as the ternary statement and the load time dies.

**Comment by jtommy** [comment]
@roni-estein Yes of course, it's no a good practice.
It's no easy at the moment replicate your project.

**Comment by roni-estein** [comment]
hmm, I can get permission to put this on a public git repository, or I can make and seed a fake database and push the laravel files, and vue files or at least the few that you might need.

Let me know what the simplest solution might be for you.

**Comment by jtommy** [comment]
As you want. I'm only interested in taking a look to b-table to know if we can optimize it or other and I don't want complicate your life to public the source.

**Comment by roni-estein** [comment]
Here is every bit of code on that page:

The laravel stuff is more or less simple and unrelated. Below this code block is the API for the generating data call


```
@extends('layouts.staff-portal')
@section('title', 'Conferences')
@section('stylesheets')
    <link href="{{asset('css/tailwind.min.css')}}" rel="stylesheet">
    <style>
        table.is-hoverable tbody tr:not(.is-selected):hover {
            background-color: #FFF8A0!important;
        }
    </style>
@endsection
@section('nav')
    @include('segments.staff.portal.nav')
@endsection

@section('content')
    @if(session()->has('notification'))
        <div class="base container-fluid {{session('notification-class')}} has-text-centered has-text-weight-bold p-x-40 p-y-20">
            <p>{{session('notification')}}</p>
        </div>
    @endif

    <div id="vue-form">
        <div class="base-fullheight container-fluid is-light">
            <nav class="container level p-t-40">
                <div class="level-left">
                    <div class="level-item">
                        <h2 class="title is-size-6-mobile is-size-5-tablet">Verify Orders</h2>
                    </div>

                </div>
                <div class="level-right">
                    {{--<div class="level-item">--}}
                    {{--<a class="button is-primary has-text-weight-bold p-y-20" href="{{route('conference.create')}}"><i class="fa fa-plus-circle m-r-10 m-t-2"></i>Create a New Conference</a>--}}
                    {{--</div>--}}
                </div>
            </nav>


            <div class="container box proper-margins m-b-30">

                <p class="has-text-weight-bold">Instructions:</p>
                <p>For this step the job is to make sure that the order is not missing any personal detail that will
                    keep it from moving on. Specifically, the name of the person, if they are a primary insurance
                    holder,
                    do they have a phone listed, and email address and a doctor. Do we know what they have ordered?
                    In the case of a conference or an older client, did we leave them with anything?</p>
                <p class="m-t-8">The search box will filter by name if you type in letters, and by the <b>order
                        number</b> if you type
                    in a number.</p>
                <p class="m-t-8">To move the order on to the next step, all the information must be set. Also the
                    triggers are, that
                    the order has a "card" (a place to indicate they have an order and what they took), and has been
                    marked as verified.</p>

                <br>

                <hr class="p-t-1">
                <div class="level">
                    <div class="level-left">
                        <div class="level-item">
                            <div class="control">
                                <b-switch v-model="isVerified" true-value="1" false-value="0" class="m-l-10"
                                          @input="updateResults">Show Verified Orders (for look up purposes ONLY)
                                </b-switch>
                            </div>
                        </div>
                    </div>
                    <div class="level-right">
                        <div class="level-item">
                            <div class="field">
                                <div class="control has-icons-left has-icons-right">
                                    <input class="input" type="text" placeholder="search" name="search" id="search"
                                           v-model="search">
                                    <span class="icon is-small is-left"><i class="fa fa-search"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <br>
                <b-table
                        :data="filteredData"
                        :loading="isLoading"
                        class="m-t-10"
                        hoverable
                >
                    <template slot-scope="props" slot="header">

                        <span class="has-text-centered" v-if="props.column.field === 'signature'"><i class="fa fa-pen-alt"></i></span>
                        @{{props.column.label}}
                    </template>
                    <template slot-scope="props">
                        <b-table-column field="id"
                                        label="Order" width="40" sortable numeric
                                        class="has-text-weight-bold is-size-8 has-text-centered">

                            @{{ props.row.id }}
                        </b-table-column>

                        <b-table-column field="username"
                                        label="Name"
                        >

                            @{{ props.row.username}}
                        </b-table-column>


                        <b-table-column field="signature" label="">
                            <a :href="'/test/'+ props.row.signature" v-if="props.row.signature != null"><i class="fa fa-check"></i></a>
                            {{--<i :class="props.row.signature !== null?'fa fa-check':''"></i>--}}
                        </b-table-column>

                        <b-table-column field="phone" label="Phone">
                            @{{ props.row.phone}}
                        </b-table-column>
                        <b-table-column field="email" label="Email">
                            @{{ props.row.email}}
                        </b-table-column>

                        <b-table-column field="owing" label="took" centered>
                            @{{ props.row.took}}
                        </b-table-column>

                        <b-table-column field="owing" label="Owe" centered>
                            @{{ props.row.owing}}
                        </b-table-column>


                        <b-table-column field="date" label="Registed On" sortable>
                            {{--<span class="tag is-success"></span>--}}
                                @{{ new Date(props.row.created_at).toLocaleDateString() }}

                        </b-table-column>

                        <b-table-column field="has_current_rx" label="Has Rx" centered>
                            @{{ props.row.has_current_rx }}
                            {{--<i class="fa fa-check" v-if="props.row.has_current_rx"></i>--}}
                        </b-table-column>

                        <b-table-column label="    ">
                            <a class="button is-purple has-text-weight-bold is-size-7" :href="'/test/layout/bluecross/claim/' + props.row.id" target="_blank">PRINT</a>
                        </b-table-column>

                        <b-table-column label=" ">
                            <a class="button is-orange has-text-weight-bold is-size-7" @click="verifyOrder(props.row.id,props.index)">VERIFY</a>
                        </b-table-column>

                    </template>
                    <template slot="empty">
                        <section class="section">
                            <div class="content has-text-grey has-text-centered p-t-30 p-b-75" v-if="isLoading">
                                <p>LOADING ...</p>
                            </div>
                            <div class="content has-text-grey has-text-centered" v-if="! isLoading">
                                <p>
                                    <i class="fal fa-frown fa-7x"></i>
                                </p>
                                <p>Nothing here.</p>
                            </div>
                        </section>
                    </template>
                </b-table>
            </div> {{-- box --}}
        </div>
    </div>

@endsection

@section('scripts')
    <script>


        new Vue({
            el: '#vue-form',
            data() {
                return {
                    search: '',
                    isLoading: true,
                    isVerified: 1,
                    tableData: [],
                    csrf: document.head.querySelector('meta[name="csrf-token"]').content,
                    api_token: '{{Auth::user()->api_token}}',
                    api_user: '{{Auth::user()->id}}',

                }
            },
            computed: {
                filteredData() {
                    return this.tableData.filter(row => {

                        return row.username.toLowerCase().indexOf(this.search.toLowerCase()) > -1
                    });

                },
            },

            methods: {
                verifyOrder(order,index) {
                    axios.get('/api/v1/verify-order',{
                       params:{
                           api_token: this.api_token,
                           order_id: order,
                           api_user: this.api_user
                       }
                    }).then((response) =>{
                        this.filteredData.splice(index,1);
                    });
                },
                updateResults: _.debounce(
                    function () {
                        this.isLoading = true;
                        axios.get('/api/v1/verify/', {
                            params: {
                                api_token: this.api_token,
                                show_verified: this.isVerified,
                            }
                        }).then((entries) => {

                            this.tableData = entries.data;
                            this.isLoading = false;
                            //this.$emit('remove', id)
                        }).catch((error) => {
                            console.log('ERROR ' + error);
                            this.isLoading = false;
                        })
                    }, 500

                ),

            },
            mounted() {
                console.log('about to update...');
                this.updateResults();
                console.log('updated');
            }

        });
    </script>



@endsection


```

API endpoint, vary simple request response that seems to return in about a 1.5 millisecond. It's quite small.

```

public function getVerifyList(Request $request)
    {
        $orders = DB::select(  'select 
                                o.id, o.created_at,o.has_current_rx,o.prescriber_id, o.has_card,
                                u.id as uid, concat(u.first_name,\' \',u.last_name) as username,
                                
                                from orders o
                                inner join users u on o.user_id = u.id
                                left join prescribers p on o.prescriber_id = p.id
                                left join clinic c on o.clinic_id = c.id 
                                where 
                                verified = 0
                                and mark_for_investigation = 0
                                -- and has_card = 1
                                ');

        return response($orders,200);
    }

```

without the data checks it's pretty fast, it will slow down when I take v-model: search to nothing clear the field. then a regualr vue element that contains vue row elements will be much faster. I haven't tried but I could make this into a static example with tableData set up as a JSON feed and then see how it changes. IT seems the rendering decision making and the  re-rendering is causing the issues. (thats a guess only from observation, I haven't started looking at the b-table code)

**Comment by roni-estein** [comment]
Since I started looking at Safari, to check against it I noticed something else that may be important to you.. The date code which is directly from the Buefy site was showing "invalid date" I thought I had touched something so I went back to the buefy site in safari and saw this.

<img width="1022" alt="screen shot 2017-12-19 at 5 54 32 pm" src="https://user-images.githubusercontent.com/8517475/34184534-e4bc9d58-e4e5-11e7-96fc-5456277cc46b.png">

**Comment by jtommy** [comment]
@roni-estein Thanks about Safari issue..
A quick view into your last code.. Why in `verifyOrder` method, you update `filteredData` and not `tableData` ? The first is a computed property that depends on second one and so every update to `tableData` are listening by `filteredData`.

**Comment by roni-estein** [comment]
Hi Walter,

Thanks for your response. I think I may have changed back and forth several times while I was looking at options to increase it’s performance.

I don’t have it handy at the moment. But I believe that VueJS docs indicate that you aren’t supposed to touch a prop but rather the rendered data layer when making modifications. I’ve only been using vue for about a month. So I’m not a “best practices expert”this could be totally wrong.

**Comment by roni-estein** [comment]
Hey Walter, I changed it and doubled checked, the code, and remembered. Why I used the filtered data.

The splice method uses an array index to remove the desired object. So Even tough I am updating the value by id in the Dom I’m removing it by the index. If I use the since the table is filtered it’s getting values like 1-5 because the list is quite small, even though the index on the table data is is actually much higher. Meaning I’m updating the correct row int he DB but moving the wrong one of the DOM. Which lead of course to clicking it again and again, and then updating the wrong rows.

If I could isolate the tableData index instead of the filtered data index that would solve the problem. But I haven’t looked at how to accomplish that.


Roni Estein
roni.estein@gmail.com
204.963.5900

**Comment by jtommy** [comment]
@roni-estein You could use `indexOf` array function (or a own search function) to `tableData` with `props.row` and you have a correct index to use for `splice` array function.

**Comment by roni-estein** [comment]
Thanks, great catch!


verifyOrder(order) {

    let index = this.tableData.findIndex(row => row.id === order);

    axios.get('/api/v1/verify-order',{
       params:{
           api_token: this.api_token,
           order_id: order,
           api_user: this.api_user
       }
    }).then((response) =>{
        this.tableData.splice(index,1);
    });
},




Roni Estein
roni.estein@gmail.com
204.963.5900

**Comment by roni-estein** [comment]
Hey, did you ever find a solution? Should I update to a new version of buefy?

**Comment by jtommy** [comment]
I'm sorry i thought you was ok with last comment.

**Comment by roni-estein** [comment]
No, I just pulled the data out those items from the table. The good catch was on the index, thanks for that. But the error still persists. When I add it back in.

Is there anything I can build further for you? were you able to reproduce it?

**Comment by jtommy** [comment]
It's no easy to replicate all your project.. But that is an example with computed prop as `data` prop
https://jsfiddle.net/jo2nf7n2/ (it's very simple).
