### ISSUE TITLE
New feature: filterable columns

### ISSUE THREAD

**Issue by jpbecotte** [buefy/buefy#486]
### Overview of the problem

**Buefy** version: 0.5.4
**Vuejs** version: 2.5.2
**OS/Browser**: all

### Description

It would be nice to have a «filterable» feature for columns. Right now, I can accomplish this with the `header` slot. But this approach is a bit hacky. Ex:

````
      <template slot-scope="props" slot="header">
        <div class="header-control" v-if="props.column.field === 'orgName'" @click.stop>
          <v-select
            v-model.sync="selectedOwnership"
            placeholder="Filter by owner"
            :options="allOrgs"></v-select>
        </div>
        <div class="header-control" v-if="props.column.customKey === 'engines'">
          <v-select
            multiple
            v-model.sync="selectedEngines"
            placeholder="Filter by engines"
            :onChange="filter"
            :options="allEngines"></v-select>
        </div>
        {{ props.column.label }}
      </template>
````

Also, if I use this approach, the headers disappear when in mobile mode. The filters should be some how visible (like the sort still visible on its own).

Here's a picture on how it should look:
![capture d ecran 2017-12-19 a 11 40 09](https://user-images.githubusercontent.com/4622285/34168067-7b96cce2-e4b1-11e7-9d3a-1503106aa359.png)

**Comment by frantic1048** [comment]
I submitted a summary of issues(contains scenario about add filtering function in header slot) about table component at  #495. Welcome to join the discussion.

**Comment by dumptyd** [comment]
I need this in my app too. Currently, I'm doing something like

```html
<b-table-column label="ID" width="50" centered>
   <template v-if="props.index === 0">
     <b-input v-model.trim="someModel" size="is-small"></b-input>
   </template>
   <template v-else>
     <span>{{ props.row.id }}</span>
   </template>
</b-table-column>
```

and this works. However, if I use pagination, it throws off the total number of rows. Because for the above to work, I have to `unshift` a dummy value to the `data` array that I pass to `b-table`.

Now if only it was possible to insert static rows that are completely decoupled from `data` then implementing this would be a breeze.

**Comment by ErwanTouba** [comment]
in need of this feature too
