### ISSUE TITLE
Select component accessibility

### ISSUE THREAD

**Issue by joshikeerti** [buefy/buefy#489]
### Overview of the problem
Form components like select and input do not seem to have a good way to add for attributes for label and ids for inputs/selects to make them accessible.

**Buefy** version: 0.4.0
**Vuejs** version: 2.3.3
**OS/Browser**:

### Description

Currently if you are using the select component there does not seem to be a way to add id to the select tag and for to the label which are basic things needed to make the form fields accessible.
Is there any way to achieve this?

**Comment by jtommy** [comment]
@joshikeerti You have to update your Vue.js and Buefy version; in this way you can bind native attributes to native component. 
About label if you use `b-field` you might set `label-for` prop (since 0.5.3 version).
For example:
```
 <b-field label="Year" label-for="year">
       <b-select id="year" placeholder="Select a name">
            <option value="2018">2018</option>
            <option value="2017">2017</option>
     </b-select>
 </b-field>
```

**Comment by jorgepinon** [comment]
Phew, thanks. Almost abandoned all the work we've done with Buefy until I saw this (I am a little embarrassed that I didn't check label-input accessibility until weeks into it).

**Comment by jorgepinon** [comment]
Couple of things along this same line:

1. I'd like to see the docs encourage this a lot more (unlike most js frameworks). Labels without `for` attributes fail basic accessibility.

2. Adding support for the bulma class `.is-sr-only` on a field label would be really useful and may encourage people to use labels even when they don't want it to visually appear. I started work on this and can continue if you like the idea. My thought was to add an `sr-only-label` attribute on the field component.

**Comment by jtommy** [comment]
@jorgepinon You are free to update docs to improve accessibility. 
Same thing about 2, but try to develop a generic feature.
Thanks

**Comment by jorgepinon** [comment]
Thanks @jtommy. Here's the PR for the field attribute. I changed it to `label-sr-only` which seems a bit more clear. https://github.com/buefy/buefy/pull/1159
