### ISSUE TITLE
Using index for field in b-table-column 

### ISSUE THREAD

**Issue by amir20** [buefy/buefy#499]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**:

### Description

My json data from my server is returned in the form of 

```
[
 ['column1', 'column2', ...],
 [1, 2, ...],
 [2, 3, ...]
]
```

I split the table to 

```
let header = ['column1', 'column2', ...];
let tableData = [[1,2,...] , [2, 3, ...] ];
```

I want to use that data to create a table. I figure this is something simple. So I did this: 

### Steps to reproduce

```
   <b-table
            :data="tableData"            
            striped
            narrowed
            hoverable
            mobile-cards
            :loading="loading">
             <template slot-scope="props">
                <b-table-column :label="header" :field="index" v-for="(header, index) in header" :key="index" sortable numeric>
                    {{ props.row[index] }}
                </b-table-column>
            </template>            
        </b-table>    
```

This doesn't work because `:field="index"` is expected to be a string. `field="index"` also doesn't work as I thought "index" is a [prop](https://github.com/rafaelpimpa/buefy/blob/c1eef40a7d661a932d0e834ef8b3b452c6320e94/src/components/table/Table.vue#L88).  Clearly, I am misunderstanding what is happening. 

### Expected behavior

To be able to sort and use `array[index]` for field. 

### Actual behavior

Error is thrown if `:field` is used. 

> vendor.js:1690 [Vue warn]: Invalid prop: type check failed for prop "field". Expected String, got Number.

<img width="797" alt="screen shot 2017-12-28 at 5 18 36 pm" src="https://user-images.githubusercontent.com/260667/34427117-4b2f9cf2-ebf3-11e7-8507-cc1f2730acb1.png">

**Comment by jtommy** [comment]
@amir20 `field` -> Property of the object the column is attributed, used for sorting. So you can't set a not String value.
You can listen `sort` event and find the index of clicked column, for example:
```
<b-table 
            :data="tableData"            
            striped
            narrowed
            hoverable
            mobile-cards
            :loading="loading"             
            @sort="mySort">
              <template slot-scope="props">
                <b-table-column :label="header" :field="header" v-for="(header, index) in header" :key="index"  sortable numeric>
                    {{ props.row[index] }}
                </b-table-column>
            </template> 
</b-table>
..
methods: {
  sort(field, order) {
     const index = this.header.indexOf(field)
     // sort your tableData
  }
}

**Comment by amir20** [comment]
Hey @jtommy thanks for the quick response. I wonder if I could do 

     :field="`${index}`"


I was able to test it in Chrome and `temp = [10, 20]` works with `temp['0']`. 

<img width="316" alt="screen shot 2017-12-29 at 11 42 20 am" src="https://user-images.githubusercontent.com/260667/34446145-9ad5eee2-ec8d-11e7-8701-7a4b87406e25.png">

I haven't gotten a chance to test it yet.
