### ISSUE TITLE
[Feature request]Add single slot to loading component

### ISSUE THREAD

**Issue by re-fort** [buefy/buefy#504]
This is a feature request.
It seems useful to be able to change the default loading animation.(e.g. using [vue-spinner](https://github.com/greyby/vue-spinner) instead of it)
If this issue might vary from the philosophy of this project, please close it.
If not, I'll create a PR with adding a custom loading example to the doc.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/6ce1405e6847eed3b88064931a7167cdfa9f1d9d
