### ISSUE TITLE
Closeable snackbar

### ISSUE THREAD

**Issue by gbdematos** [buefy/buefy#505]
Would it be possible to add this behavior? (like Google Inbox, it has a "X" after the action button to close the snackbar).

Also a little bug I found, when the position was set to "is-bottom-left", the snackbar would become larger (600px, which is max width). I solved by reversing the style the bottom-right one has:

.snackbar.is-bottom-left {
    align-self: start;
}

**Comment by Herteby** [comment]
They already have an "OK" buttton by default which closes it. One limitation though is that they can only have one action. Maybe the ability to set multiple actions would be a good idea?

**Comment by rafaelpimpa** [comment]
We gonna "rewrite" snackbar/toast and some other components, will have this in mind.

**Comment by Leandros** [comment]
Would be great to have multiple actions on a snackbar!

**Comment by rhymes** [comment]
It would be great if snackbar could be closed programmatically.

A use-case: online/offline alert. When the user is detected to be offline the snackbar is shown, there's no way to make it disappear (unless I leave the close button) when the connection comes back

**Comment by jtommy** [comment]
`indefinite` prop allows to close programmatically

**Comment by jtommy** [comment]
`indefinite` prop + `close` method

**Comment by viral-vector** [comment]
Closed but had a simple solution for this, not pretty but hides the snackbar on action. 
`
onAction: () => {
       this.$buefy.snackbar.isActive = false;
}
`

**Comment by shibukk** [comment]
The return value of SnackbarProgrammatic is the component itself, so the component's `close()` method can close programmatically.

```js
import { SnackbarProgrammatic as Snackbar } from 'buefy'

const component = Snackbar.open({ message: 'Look at me!', indefinite: false })
// For example, mouseover events
document.querySelector('.snackbar').addEventListener('mouseover', () => {
  component.close()
})
```
