### ISSUE TITLE
Consider using SSR/Nuxt.js for docs

### ISSUE THREAD

**Issue by ishitatsuyuki** [buefy/buefy#516]
The documentation is not really indexed at all. We need some kind of server side rendering to make it searchable.

Result on Google: https://www.google.com/search?q=site%3Abuefy.github.io

**Comment by ishitatsuyuki** [comment]
A new option is available: [VuePress](https://vuepress.vuejs.org/).

**Comment by Cathy-ctr** [comment]
do you know any VPN software, using in Apple Phone

**Comment by AbidemiT** [comment]
Hello, I'm interested in taking this up... what are the steps to consider?

**Comment by jtommy** [comment]
Low priority at the moment
