### ISSUE TITLE
No scrollbar on modal in IE11

### ISSUE THREAD

**Issue by Youdaman** [buefy/buefy#519]
To make scrollbars appear on tall modals (where content is greater than the browser height) in Internet Explorer you have to make all parents of the modal 100% height as per https://stackoverflow.com/a/16813167

This is how I got scrollbars working for modals with tall content (for both popup and top element of standalone form/page):
```
html,
body,
#app,
#app > div,
.animation-content,
.animation-content > div,
.modal-card,
.modal-card-body {
  height: 100%;
}
```

**Comment by Youdaman** [comment]
Note, also needed to add "!important" to the "width: auto" to make the modal wide enough for forms with field groups (worked fine without "!important" in dev, but necessary for build/dist version):
```
.modal-card {
  width: auto !important;
}
```

**Comment by anthrogan** [comment]
Also you can use overflow: auto

```
html,
body,
#app,
#app > div,
.animation-content,
.animation-content > div,
.modal-card,
.modal-card-body {
  overflow: auto;
}
```
this way it will only show a scroll bar when needed. Instead of resizing all modals, its not ideal though as the scrollbars are on the outside of the modal. But helps if you have a mix of different sizes!

**Comment by jruizsulime** [comment]
Working great on IE11
