### ISSUE TITLE
[Feature Request] Add functionality to listen to mouseover for a table row

### ISSUE THREAD

**Issue by modstore** [buefy/buefy#520]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]

### Description

I want to be able to show/hide based on mouseover of a table row, is this possible at all?

Thanks in advance.

**Comment by rafaelpimpa** [comment]
Not currently

**Comment by modstore** [comment]
Updated to "feature request". Thanks for the great work so far.

**Comment by rafaelpimpa** [comment]
Have to test if there will be any performance downsides.

**Comment by service-paradis** [comment]
@jtommy 
I think we can close this issue
