### ISSUE TITLE
Tab content gets cut off in IE11

### ISSUE THREAD

**Issue by teryngull** [buefy/buefy#522]
### Overview of the problem

Buefy version: 0.6.2
Vuejs version: 2.5.13
OS/Browser: IE11

### Description

When using beufy's tabs (https://buefy.github.io/#/documentation/tabs), the tab content is getting cut off in IE 11. I was able to change a flex-basis CSS line for the content to fix the issue. It appears to work ok in all other browsers with this change.

.b-tabs .tab-content .tab-item {
    flex-basis: auto;
}

### Steps to reproduce

1. Copy the first section of sample code from the tab section of the documentation (the example that has content in it)
2. Open website in IE11 and observe that the content is getting cut off.
3. Add the above CSS
4. Observe that the content is not getting cut off now.

### Expected behavior

The tab content shouldn't be cut off. Note: this screenshot is from my own website, so the styling is different.

![2018-01-09_13-44-41](https://user-images.githubusercontent.com/27399690/34737162-54f88754-f543-11e7-94a4-fb9bc18fa989.png)

### Actual behavior

The tab content is getting cut off.

![2018-01-09_13-46-13](https://user-images.githubusercontent.com/27399690/34737210-7e8986cc-f543-11e7-8573-a53bb23a62da.png)

**Comment by xpuu** [comment]
Thanks for the fix, works for me!

**Comment by jwjcmw** [comment]
That was timely.  Your comment came in just as I was having this same issue, I might not have noticed the fix otherwise.  Worked for me!
