### ISSUE TITLE
V-for on labels

### ISSUE THREAD

**Issue by psweeting1** [buefy/buefy#524]
Buefy (v0.6.2)
Vue.js (2.5.13)
Mac OS / Google Chrome

### Description

Can't not get label to duplicate in a V-for when trying to make a reactive table. 

```

<template>
    <section>
        <b-table
            :data="isEmpty ? [] : tableDataSimple"
            :bordered="isBordered"
            :striped="isStriped"
            :narrowed="isNarrowed"
            :hoverable="isHoverable"
            :loading="isLoading"
            :mobile-cards="hasMobileCards">


            <template slot-scope="props">
                <b-table-column v-for="tableData, $index in tableDataSimple" :label="Object.keys(tableData)[$index]">
                    {{ props.row[Object.keys(tableData)[$index]] }}
              </b-table-column>

            </template>
            <template slot="empty">
                <section class="section">
                    <div class="content has-text-grey has-text-centered">
                        <p>No results found</p>
                    </div>
                </section>
            </template>
        </b-table>
    </section>
</template>

    export default {
      name: 'tt-table',
        data() {
            const tableDataSimple = [
                { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016-10-15 13:43:27', 'gender': 'Male' },
                { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016-12-15 06:00:53', 'gender': 'Male' },
                { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016-04-26 06:26:28', 'gender': 'Female' },
                { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016-04-10 10:28:46', 'gender': 'Male' },
                { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016-12-06 14:38:38', 'gender': 'Female' }
            ]

            return {
                tableDataSimple,
                isEmpty: false,
                isBordered: false,
                isStriped: true,
                isNarrowed: true,
                isHoverable: false,
                isLoading: false,
                hasMobileCards: true
            }
        }
    }

```

### Steps to reproduce

Step 1: create v-for="tableData, $index in tableDataSimple"  on b-table
Step 2: Bind label :label="Object.keys(tableData)[$index]"> {{ props.row[Object.keys(tableData)[$index]] }}
Step 3: Inside b-table create rows {{ props.row[Object.keys(tableData)[$index]] }}

I'm using the Buefy tableDataSimple.

### Expected behavior

Label should create headers for each of the row's I've created

### Actual behavior

Only creates one header

**Comment by psweeting1** [comment]
I managed to do a fix.

```
  <template slot-scope="props">
                <b-table-column v-for="tableData, $index in tableDataSimple" :label="Object.keys(tableData)[$index]" :custom-key="Object.keys(tableData)[$index]">
                    {{ props.row[Object.keys(tableData)[$index]] }}
              </b-table-column>
            </template>
```
It works but why isn't Label reactive? This feels like a hack just get it headers to work.

**Comment by davidwright** [comment]
I don't think this is Buefy's problem. You are looping through every row in the table to get the index of a field. So 5 rows only shows 5 fields. Extract the fields first and then build the columns based on that

const f = tableDataSimple.shift()
const fields = [];
for (var i in f) {
  if (f.hasOwnProperty(i)) {
    fields.push(i);
  }
}
add 'fields' to the return

and in the template

<b-table-column v-for="field in fields" :label="field" :key="field">
  {{ props.row[field] }}
</b-table-column>

**Comment by mateuswetah** [comment]
@psweeting1 , I might be wrong, but I think the `custom-key` attribute on column already solves this, check this issue:
https://github.com/buefy/buefy/commit/af61822dd7800f9c80bf198d2d359287d820f8df

If so, I would recommend to close this issue.
