### ISSUE TITLE
Table sorting doesnt correctly sort dates.

### ISSUE THREAD

**Issue by itsacorn** [buefy/buefy#529]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Windows 10 x64 / Firefox Quantum Developer Edition

### Description

b-table element sorting does not work correctly on LocaleString format ( M(M)/D(D)/YYYY, h(h):m(m):s(s) AM/PM ). Sorting seems random. <img src="https://acorn.got-no.life/d47af50a">

### Steps to reproduce

Create a table with a sortable column with dates in LocaleString format.
Sort the date column.
Rows will look randomly sorted.

### Expected behavior

Dates will be sorted according to... well... how dates should be sorted.

### Actual behavior

The sorting looks random.

EDIT: i just noticed that it works in random cases: <img style="max-height: 300px; height: 50%" src="https://acorn.got-no.life/25920ad7">

**Comment by itsacorn** [comment]
One way to fix this could be a `sort-value` bind on the column, in which you can pass for example a UNIX timestamp, and if that `sort-value` bind is present, it will override the normal sorting, instead the value of the `sort-value` bind is used for sorting. It would probably fix this issue.

**Comment by jtommy** [comment]
@itsacorn You could use `custom-sort` prop of `b-table-column`. In this way you can define a your custom sort function-

**Comment by rlightner** [comment]
Hooking on to this issue, it would be nice if the custom sort function passed in the column that was selected so that you could maintain one sort function vs one for each column.

**Comment by ravicheema** [comment]
I worked around this issue by using a custom sort function for a date column,

```
<b-table-column field="startDate" label="Start Date" sortable centered :custom-sort="sortByDate">
    {{ new Date(props.row.startDate).toLocaleDateString() }}
</b-table-column>`
```

```
methods: {
  sortByDate(a, b, isAsc) {
    if (isAsc) {
      return new Date(b.startDate).getTime() - new Date(a.startDate).getTime();
    } else {
      return new Date(a.startDate).getTime() - new Date(b.startDate).getTime();
    }
  }
}
```

**Comment by jtommy** [comment]
Yes, it is the right way.
