### ISSUE TITLE
Component modal props won't update

### ISSUE THREAD

**Issue by njanke96** [buefy/buefy#533]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.3.3
**OS/Browser**: Linux/Chromium (electron)

### Description

I'm trying to use a component modal to show progress of a task, I can't seem to update my `progress` property to update the progress bar. This is more likely not a bug but rather me using the `props` option correctly.

### Steps to reproduce

I have an EventEmitter (BSPFile) emitting a progress event when progress is made during a lengthy operation. The progress property within the ProgressModal component is bound to the value of my progress bar.

```javascript
// load bsp
  const bspFile = new BSPFile()

  // progress modal
  let modalProps = {
    title: `Loading ${vm.fileName} ...`,
    message: `Loading BSP data...`,
    progress: 0
  }

  vm.$modal.open({
    parent: vm,
    component: ProgressModal,
    hasModalCard: true,
    canCancel: false,
    props: modalProps
  })

  bspFile.on('loadProgress', (progress) => {
    console.log(progress)
    modalProps.progress = progress
  })

  // load bsp data
  await bspFile.load(filePath)
  bspFile.removeAllListeners('loadProgress')
```

ProgressModal.vue: 
```vue
<template>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">{{ title }}</p>
    </header>

    <section class="modal-card-body">
      <div class="container is-fluid">
        <h6 class="subtitle is-6">{{ message }}</h6>
        <progress class="progress is-primary" :value="progress" max="100"></progress>
      </div>
    </section>

  </div>
</template>

<script>
export default {
  name: 'ProgressModal',
  props: {
    title: {
      type: String,
      required: true
    },
    message: {
      type: String,
      required: true
    },
    progress: {
      type: Number,
      required: true
    }
  }
}
</script>

```

### Expected behavior

The progress property updates and the bound progress prop 'value' changes.

### Actual behavior

The bound progress prop 'value' does not change. I know the event fires because the console.log works.

**Comment by vinczebalazs** [comment]
I am having the exact same issue, the passed in props seem to lose reactivity.

**Comment by PayteR** [comment]
I want to acheive something similar, my solution is to update whole props param, in your case it would be something like this:
```
const bspFile = new BSPFile()

// progress modal
let modalProps = {
  title: `Loading ${vm.fileName} ...`,
  message: `Loading BSP data...`,
  progress: 0
}

let modalInstance = vm.$modal.open({
  parent: vm,
  component: ProgressModal,
  hasModalCard: true,
  canCancel: false,
  props: modalProps
})

bspFile.on('loadProgress', (progress) => {
  modalProps.progress = progress
  modalInstance.props = modalProps
})

// load bsp data
await bspFile.load(filePath)
bspFile.removeAllListeners('loadProgress')
```
It works, BUT it gives me this warning
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "props"

found in

---> <BModal>
       <Root>
```
It would be great to have some interface o update props

**Comment by jtommy** [comment]
@PayteR @njanke96 @vinczebalazs Did you try to call `$forceUpdate` after props update ?
For example:
```
const bspFile = new BSPFile()

// progress modal
let modalProps = {
  title: `Loading ${vm.fileName} ...`,
  message: `Loading BSP data...`,
  progress: 0
}

let modalInstance = vm.$modal.open({
  parent: vm,
  component: ProgressModal,
  hasModalCard: true,
  canCancel: false,
  props: modalProps
})

bspFile.on('loadProgress', (progress) => {
  modalProps.progress = progress
  modalInstance.$forceUpdate()
})

// load bsp data
await bspFile.load(filePath)
bspFile.removeAllListeners('loadProgress')
```

**Comment by PayteR** [comment]
@jtommy this is maybe solution for @njanke96, but in my case i need to update whole `props` parameter in my instantiated modal component. When i update props `modalInstance.props = modalProps` it works, but i get warning, is there solution for me how update props with "correct way"?

**Comment by jtommy** [comment]
If you try my code all props will be updated (all fields in modalProps)

**Comment by jacobgoh101** [comment]
wow.. this is pretty bad...

**Vue's props are reactive, period.**

If Buefy Modal's props are not reactive, either

- the name should change, it shouldn't be called props, or
- it should be made reactive

This is really confusing. Please re-open this issue.

**Comment by andrei-dracea** [comment]
@jtommy Any update on this? Is the manual prop update + forceUpdate the standard way we should update props? If so, we should document it

**Comment by gdevdeiv** [comment]
I'm having the same issue. Using `$forceUpdate` directly sounds wrong.

**Comment by gdevdeiv** [comment]
Update: I just fixed it in my particular case. It looks like Buefy passes `propsData` as is, so if your object is not reactive, it will not make it so. There are a couple ways to fix this: either you pass a prop that already existed in your `data()` function (prop already reactive) or you use events on your modal component to maintain a copy of the object and notify changes through events, for example:

```
export default {
    name: 'ModalComponent',
    props: {
        value: {}
    },
    data () {
        return {
            model: clone(this.value)
        }
    },
    watch: {
        value: {
            deep: true,
            immediate: true,
            handler (val) {
                this.model = clone(val)
            }
        },
        model: {
            deep: true,
            handler (val) {
                this.$emit('input', val)
            }
        }
    }
}
```
