### ISSUE TITLE
Adding a tooltip to a progress bar doesn't work

### ISSUE THREAD

**Issue by apocalyarts** [buefy/buefy#534]
Try this:
```html
<b-tooltip label="Tooltip top">
    <progress class="progress" value="15" max="100">15%</progress>
</b-tooltip>
```
The progress bar disappears. I'm on latest Buefy / Vue. Browser is Chrome on Windows 10.

**Comment by Krisseck** [comment]
I am using version 0.6.3, this seems to work okay!

**Comment by oller** [comment]
This still seems to be an issue with `0.7.0`

**Comment by oller** [comment]
Any thoughts @jtommy? this seems to have been present for quite a while.  Thanks!

**Comment by oller** [comment]
This appears to be a CSS issue.

In particular, the combination of the wrapping .tooltip being `display: inline-flex` and the child `.progress` element of having a `width:100%`.  

Set the width of the `.progress` element to an absolute value, i.e. 200px and you'll see everything behaves as expected.

Obviously, we want the tooltip to be `display:inline`, so wrapping an element in a tooltip does not affect the parent layout, so it seems the solution will have to be looking at the `.progress` class, which I know is coming from bulma, not buefy
