### ISSUE TITLE
Checking multiple table rows when "shift" key is held

### ISSUE THREAD

**Issue by nikazooz** [buefy/buefy#535]
First of all, I'd like to use this opportunity to thank you for sharing these amazing UI components. :)

I wanted to ask if checking multiple table rows when holding the shift key is something that would be possible to implement, either in parent component or as part of the table component.

I kinda need such feature and was wondering if you'd accept a PR for something like that if I manage to get it working?

Kind regards and thanks again!

**Comment by jbbr** [comment]
Still interested :)
