### ISSUE TITLE
Align label on top of attached components

### ISSUE THREAD

**Issue by johnmerced** [buefy/buefy#538]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Chrome

### Description
Can't align label on top (instead of the left) of attached components.

### Steps to reproduce
```
<b-field label="Send by email">
     <b-input placeholder="Search..." type="search" icon="magnify"></b-input>
     <p class="control">
          <button class="button is-info">Search</button>
     </p>
</b-field>
```

### Expected behavior
Align label and attached components vertically.

Screenshot: <br>
<img src="https://i.imgur.com/xXosfNc.png">

### Actual behavior
Seems like it's not possible. 

Screenshot: <br>
<img src="https://i.imgur.com/Fx3RQux.png">

**Comment by johnmerced** [comment]
Also, errors looks like this:
<img src="https://i.imgur.com/QqNXTtI.png">

**Comment by jtommy** [comment]
@johnmerced At the moment you might try that:
```
<b-field label="Send by email" type="is-danger" message="Please include...">
      <b-field>
     <b-input placeholder="Search..." type="search" icon="magnify"></b-input>
     <p class="control">
          <button class="button is-info">Search</button>
     </p>
        </b-field>
</b-field>
```
