### ISSUE TITLE
Methods called twice binding property of b-table-column

### ISSUE THREAD

**Issue by kunaime** [buefy/buefy#544]
**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.7]
**OS/Browser**: Ubuntu 17.10 / Chrome

Hello, i was trying to return a dinamically generated href of an `<a>` tag inside a` <b-table-column>` , using a method binded to the property instead of a computed because i need to pass a parameter. While debugging, i have discovered that he method is called twice. In order to make a simple test i have used the code in the "Table" -> "Row status" section of the docs, and added a simple property to one of the b-table-column tags like this

` <b-table-column :test="test()"> `

Using a console.log inside the test method, the string will be printed twice for each row of the table instead of once. Am i doing something wrong or is that actually an issue?

**Comment by jtommy** [comment]
@kunaime What's `test` ? `b-table-column` component doesn't except that prop.

**Comment by kunaime** [comment]
I know, it was just for testing purpose and to keep the code as simple as possible, i could have used another tag nested inside `b-table-column` to replicate what was happening with my actual code, but even if doesn't expose that prop the method is being called anyway (and the property rendered in the HTML as an empty one because the `test` method returns an empty string)

**Comment by jtommy** [comment]
@kunaime Ok. Could you provide us an example ?

**Comment by kunaime** [comment]
Sure, this is the code with the dynamic prop applied to a link tag to make it more realistic

`<template>
    <b-table
        :data="tableDataSimple"
        :row-class="(row, index) => row.id === 1 ? 'is-warning' : ''">

        <template slot-scope="props">
            <b-table-column label="ID" width="40" numeric>
                <a :href="test()">{{ props.row.id }}</a>
            </b-table-column>

            <b-table-column label="First Name">
                {{ props.row.first_name }}
            </b-table-column>

            <b-table-column label="Last Name">
                {{ props.row.last_name }}
            </b-table-column>

            <b-table-column label="Date" centered>
                {{ new Date(props.row.date).toLocaleDateString() }}
            </b-table-column>

            <b-table-column label="Gender">
                {{ props.row.gender }}
            </b-table-column>
        </template>
    </b-table>
</template>

<script>
    export default {
        data() {
            const tableDataSimple = [
                { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016-10-15 13:43:27', 'gender': 'Male' },
                { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016-12-15 06:00:53', 'gender': 'Male' },
                { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016-04-26 06:26:28', 'gender': 'Female' },
                { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016-04-10 10:28:46', 'gender': 'Male' },
                { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016-12-06 14:38:38', 'gender': 'Female' }
            ]

            return {
                tableDataSimple
            }
        },

        methods: {

            test() {
                console.log('called');
                return 'www.google.com'
            }
        }
    }
</script>

<style>
    tr.is-warning {
        background: hsl(48, 100%, 67%) !important;
    }
</style>`

**Comment by kunaime** [comment]
I am sorry but the editor keeps rendering the code in a wrong way. Baiscally it's the same example code used on the Buefy documentation mage about tables

[](https://buefy.github.io/#/documentation/table)

under the "Row Status" section. I have then added a dybamic `:href="test()"` property where `test()` makes a `console.log("Called")` and then returns `www.google.com`

**Comment by jtommy** [comment]
@kunaime Why do you need to call a method ? Does href depend on something that is not the same row ? Anyway methods are called where there is a rendering update and so it could be called different times.
