### ISSUE TITLE
Modal component removes scrolling from body

### ISSUE THREAD

**Issue by swstephe** [buefy/buefy#549]
### If your body is scrolling, opening up a modal dialog will remove the scrollbar.

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**: Windows 7 64-bit/Chrome

### Overview of the problem

Really quick problem, that I eventually figured out and solved, but thought I should mention it anyway.

### Description

On a page which shows many products, if you click on a product card, it opens up a modal dialog, (b-modal), like this:

```
<b-modal :active.sync="isActive" :onCancel='close' scroll='keep'>
   <p>...</p>
</b-modal>
```

The modal comes up fine, but when it closes, the scrollbar is missing on the body, so you can't scroll around on the main page anymore.

In the source, I found this line in the modal dialog:

`document.body.classList.toggle('is-noscroll', this.isActive)`

I confirmed that after close, "is-noscroll" was still on the main body, so I just added:

`document.body.classList.toggle('is-noscroll', false)`

In my onCancel method and that got rid of the problem.

### Expected behavior

I suppose it should save state when it is activated and restore on exit.

### Actual behavior

I haven't tested it on any other browser or mobile device yet.

**Comment by darkylmnx** [comment]
same problem here

**Comment by GarethTIGFreight** [comment]
Same problem. 

The method close() at Modal.vue Line 147 calls which triggers the watch isActive() (Line 98) which triggers handleScroll() (Line 103) is only run if it's programmatic.

Should be updated to run in all scenarios (?).

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/7ac5107750965a0e207013781ebf3fdc607f6dc5
