### ISSUE TITLE
[Feature Request] b-button

### ISSUE THREAD

**Issue by NemoAlex** [buefy/buefy#550]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: all
**OS/Browser**: all

### Description

I think it will be nice if we have a b-button component like:

```html
<b-button size="small" :loading="loading" :disabled="disabled" icon="fa-github"></b-button>
```

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/c73c5daa97dd2c028ead59adb0c29ca389737b4a
