### ISSUE TITLE
Autocomplete type (color) property

### ISSUE THREAD

**Issue by taylorhoward92** [buefy/buefy#560]
### Overview of the problem
**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.2]
**OS/Browser**: All

### Description
Would be great to be able to use the `type` property with autocomplete so that the color scheme can be set, the same as how it can be with form input, etc.

### Steps to reproduce
N/A

### Expected behavior
`<b-autocomplete type="is-danger"></b-autocomplete>`
This would result in a autocomplete input like this:
![image](https://user-images.githubusercontent.com/23712266/35470072-02613212-038e-11e8-9902-03fdf8a52b45.png)

### Actual behavior

`<b-autocomplete type="is-danger"></b-autocomplete>`
Currently results in no color change, like this:
![image](https://user-images.githubusercontent.com/23712266/35470084-3bc2f5f4-038e-11e8-8a71-39c40fb9a36f.png)

**Comment by dciancu** [comment]
+1

Looking forward to implement this.

**Comment by jtommy** [comment]
@taylorhoward92 You might add `b-autocomplete` into a `b-field` like `b-input` docs.

**Comment by alexnb** [comment]
> @taylorhoward92 You might add `b-autocomplete` into a `b-field` like `b-input` docs.

Sorry, I have the same problem and do not understand the proposed solution, would it be possible to have b-autocomplete behave like others when class/type="is-danger" is set?

**Comment by alexnb** [comment]
My current workaround is:

`<b-autocomplete :class="{ 'is-danger': !validateValue }"`

` <style>
    div.is-danger {
        border: 1px;
        border-color: red;
        border-style: solid;
    }
</style>`

**Comment by yxngl** [comment]
@alexnb The type is on b-field.
```
<b-field type="is-danger">
            <b-autocomplete></b-autocomplete>
</b-field>
```
