### ISSUE TITLE
unable to use @extend .has-text-info in scss

### ISSUE THREAD

**Issue by guruprasaad123** [buefy/buefy#566]
Am trying to use [Buefy](https://buefy.github.io/#/) 0.6.2 with [vue](https://vuejs.org/) 2.5.11 in my [Webpack](https://webpack.js.org/) project .I was trying to use `@extend` feature using scss but for some reason I am unable to use it any browser.Here's what I tried
```
@import url("https://unpkg.com/buefy/lib/buefy.min.css"); // importing buefy.min.css
span[class='of-blue']
{
 @extend .has-text-info  ;   // trying to use inheritance / extend
}
```
And am getting this Above error.
```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/sheets/style.scss
Module build failed:
 @extend .has-text-info  ;
        ^
      "#about-us p span[class='of-blue']" failed to @extend ".has-text-info".
The selector ".has-text-info" was not found.
Use "@extend .has-text-info !optional" if the extend should be able to fail.
      in D:\workspace\@vue\Gms-exports\gms-webpack\src\sheets\style.scss (line 107, column 10)
 @ ./src/sheets/style.scss 4:14-123 13:3-17:5 14:22-131
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js

```
But am sure that **.has-text-info** class exists in the _buefy.css_ which i have imported in .scss file.As mentioned by the [doc](https://buefy.github.io/#/documentation/layout) it inherits all the features of [Bulma](https://bulma.io/).so am expecting that **@extend** feature to  work correctly without prompting any error.

**Comment by anteriovieira** [comment]
Check out sass/node-sass#1469

Looks like this all stems from Sass.

**Comment by guruprasaad123** [comment]
i'll check it out @anteriovieira  , can look after this Issue [#584](https://github.com/rafaelpimpa/buefy/issues/584) am really struck on this.

**Comment by jtommy** [comment]
Thanks @anteriovieira
