### ISSUE TITLE
b-checkbox does not support `[required=true]`

### ISSUE THREAD

**Issue by FelixVicis** [buefy/buefy#567]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**:
  - Ubuntu 16.04
  - Chrome 63.0.3239.108

### Description

`b-checkbox` does not support the `required=true` attribute.

### Steps to reproduce

1. Create:
```html
<form>
   <b-checkbox required></b-checkbox>

   <input type="submit" />
</form>
```
2. Click submit
3. Notice submission is allowed without browser intervention

### Expected behavior

I expected that the a checkbox that has `required` but is not checked would be marked invalid in some way, like this:
![image](https://user-images.githubusercontent.com/6580094/35547091-f8cc11f0-052b-11e8-87a7-6f9473adfee0.png)

### Actual behavior

Submission was allowed, no issues.

### Cause

When applying `required` to the input element inside `b-checkbox` the following error occurred in the the browser console.

![image](https://user-images.githubusercontent.com/6580094/35546879-0c179d2a-052b-11e8-9d43-1451972935a8.png)

Following along that message, I found that lines:

https://github.com/rafaelpimpa/buefy/blob/a3cf6b8b0f22eb281abab946c6c60d07d3097e3c/src/scss/components/_checkbox.scss#L13-L14

is marking the checkbox as hidden, which the browser interprets as unavailable.

If there was a way to remove the need of hiding the checkbox while still applying the styling, then `b-checkbox`es can be assigned required.

**Comment by xpuu** [comment]
Here's my temporary fix... Also includes Radios and Switch... It works, but I'm not sure if my approach is correct. Any comments would be appreciated.
https://codesandbox.io/s/148rqz106j
