### ISSUE TITLE
How to change the format of date and limit the date can only selected started from today?

### ISSUE THREAD

**Issue by EeSien** [buefy/buefy#569]
![image](https://user-images.githubusercontent.com/26835915/35570050-f6f4466c-0608-11e8-91a9-53d172e06033.png)
i gone through the documentation but still dont know how to use.. can anyone teach me?

**Comment by EeSien** [comment]
![image](https://user-images.githubusercontent.com/26835915/35576019-f34664a4-0618-11e8-937c-31c8446b2f83.png)
it will show me this error and cannot use

**Comment by EeSien** [comment]
![image](https://user-images.githubusercontent.com/26835915/35576039-0241ae46-0619-11e8-8810-1aef00da1da9.png)
![image](https://user-images.githubusercontent.com/26835915/35576051-0a91250e-0619-11e8-9f9e-8856184fea96.png)
my code

**Comment by jtommy** [comment]
@EeSien It's very strange. Your code is like docs example. Are you sure that datepicker works without `min-date` props ?

**Comment by EeSien** [comment]
Yes, im using the latest version of Buefy and Vue..  how do i put the min-date props? i follow the docs example but unfortunately it cannot set the mindate

**Comment by jtommy** [comment]
As you can see in docs that prop works well. I think there is a issue in your project

**Comment by haphazardly** [comment]
Also experiencing the same issue, any luck @EeSien?

**Comment by haphazardly** [comment]
@EeSien I resolved this issue for myself try using this:
```javascript

Vue.use(Buefy, {
    defaultIconPack: 'fas',
})

var App = new Vue({
    el: '#app',
    data: {

    },
    computed: {
    	minDate: function() {
      	const today = new Date()
      	return new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5)
    	}
    }
})

```
