### ISSUE TITLE
Snackbar parent element is defaulting to position:absolute

### ISSUE THREAD

**Issue by htokuda10** [buefy/buefy#570]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.4.2]
**OS/Browser**: Chrome v.63.0.3239.132

### Description

Using the code provided in the Buefy documentation, when no 'container' prop is provided, the default parent element should be a div with the style position:fixed, however it is creating a div with the class 'has-custom-container' appended, resulting in the style position:absolute. I have reviewed the code and it should work. The created parent element is getting appended to the body as documented as the default
![screen shot 2018-01-30 at 11 43 56 am](https://user-images.githubusercontent.com/11944733/35584682-facb8d6e-05b2-11e8-932a-cc2ed2f35fd6.png)
(please fix the documentation, this is not a Toast component), which tells me that the 'newContainer' variable should be empty, but the "if(this.newContainer)" condition is being met, and the 'has-custom-container' class is being appended to the parent element's class.

### Steps to reproduce

1. Copied code directly from the Buefy code block:
```
this.$snackbar.open({
    message: 'Yellow button and positioned top-left',
    type: 'is-warning',
    position: 'is-top',
    actionText: 'Retry',
    queue: false,
    onAction: () => {
        this.$toast.open({
            message: 'Action pressed',
            queue: false
         })
      }
   })
```
2. Modified props
```
this.$snackbar.open({
    actionText: 'Retry',
    duration: 10000,
    message: 'Oops! Backstop failed to load.',
    position: 'is-top',
    queue: false,
    type: 'is-warning',
    onAction: () => {}
 });
```
2. Pasted function in an Axio/ajax callback
![screen shot 2018-01-30 at 11 31 48 am](https://user-images.githubusercontent.com/11944733/35584173-70f09dec-05b1-11e8-8f2e-361ce01e37c3.png)
3. Fired request
4. Looked at the Chrome developer tools to see the parent element created, which showed that the class 'has-custom-container' was appended
![screen shot 2018-01-30 at 11 32 42 am](https://user-images.githubusercontent.com/11944733/35584298-d37968c2-05b1-11e8-9054-24b416210acc.png)

### Expected behavior

Not providing the 'container' prop, should default the parent container style to position:fixed.

### Actual behavior

The Snackbar parent container is getting the 'has-custom-container' class appended to it, causing the style position: absolute, which is sticking the Snackbar at the top of the body.

**Comment by chrtz** [comment]
unfortunately, this is still an issue.

**Comment by ryanhightower** [comment]
I think I found the issue with this (as I was experiencing the same behavior). In the docs, the [Contructor Options](https://buefy.org/documentation/constructor-options) uses as an example 

```Vue.use(Buefy, {
    defaultIconPack: 'fas',
    defaultContainerElement: '#content',
    // ...
})```

The Snackbar (and other Notifications) look at the `defaultContainerElement` to see if it is set. If it is, it is considered to have a "custom container", and therefore adds the `.has-custom-container` class. This seems desirable because it will position your notifications relative to your container. If you don't need a `defaultContainerElement`, then remove that line and your notifications should work correctly.

**Comment by ryanhightower** [comment]
Also I think it should be added to the docs for Notifications that they will use the `defaultContainerElement` as a custom container since this wasn't immediately clear.

**Comment by jtommy** [comment]
@ryanhightower PR please

**Comment by htokuda10** [comment]
@ryanhightower As this bug was reported over a year ago, I don't recall exactly what I was reporting, but based on my comments, and in short, it appears that the issue was even when you _did not_ set the `container` prop, it was still applying the `has-custom-container` class to the `notices` DIV, which then applies the `position:fixed` CSS styling to that DIV. Please reference the "Steps to reproduce", "Expected behavior", and "Actual behavior" for an example.

Unless I am misunderstanding your resolution, this reported bug is a problem is with the component `container` property (reference the `container` prop in the API documentation for the Snackbar component, https://buefy.org/documentation/snackbar), not the Buefy configuration property for the `defaultContainerElement`. 😄

**Comment by ryanhightower** [comment]
@htokuda10 yep, I added an explanation to the Toast and Snackbar docs in my PR. It should go out next whenever the next release happens.

**Comment by htokuda10** [comment]
@ryanhightower Have you tested that this works when both of the values, `container` and `defaultContainerElement`, are not defined? Does it work as intended? The API docs for Snackbar `container` should also probably have `body || config.defaultContainerElement (if defined)`.

**Comment by ryanhightower** [comment]
I'm not sure I understand what you mean. If neither `container` or `defaultContainerElement` are defined, then the default behavior is to use `position:fixed`, which is the intended behavior, so yes, it works as intended. The Snackbar does not position itself to the `body` though. `position: fixed` positions it relative to the window, so I'm not sure what you suggestion is referring to.
