### ISSUE TITLE
Snackbar and Toast created elements are static on the DOM once created

### ISSUE THREAD

**Issue by htokuda10** [buefy/buefy#573]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.4.2]
**OS/Browser**: Chrome v.63.0.3239.132

### Description

The created parent element for the Snackbar and Toast components do not get moved to a new defined container when any subsequent Snackbar and Toast 'open' function calls are made. This is due to the first conditional statement in the 'setupContainer' function, located in the NoticeMixin.js.

Location - NoticeMixin.js
![screen shot 2018-02-01 at 9 43 00 am](https://user-images.githubusercontent.com/11944733/35691052-b9422c94-0734-11e8-9144-5ce72b4c4841.png)

### Steps to reproduce

1. Monitor the created element on the DOM through the developer tools
2. Open a Snackbar component on container one
```
this.$snackbar.open({
    actionText: 'Open Snackbar One',
    container: '#containerOne',
    duration: 5000,
    message: 'Test on container one',
    position: 'is-top',
    queue: false,
    type: 'is-warning',
    onAction: () => {}
});
```
3. Open a Snackbar component on container two
```
this.$snackbar.open({
    actionText: 'Open Snackbar Two',
    container: '#containerTwo',
    duration: 5000,
    message: 'Test on container two',
    position: 'is-top',
    queue: false,
    type: 'is-warning',
    onAction: () => {}
});
```
4. Note that both Snackbar notifications are opened on container one

### Expected behavior

The ability to open a Snackbar and Toast component in dynamic locations, on the DOM.

### Actual behavior

Once a Snackbar or Toast has been rendered on the DOM, the 'setupContainer' function in NoticeMixin.js will run a 'querySelector' for the classes 'notices' and both(separately) 'is-bottom' and 'is-top'. If they exist on the DOM, the 'setupContainer' function will return, preventing the ability of the Snackbar and Toast components from rendering in dynamically defined locations on the DOM.

**Comment by patrickabkarian** [comment]
Yeah this is an actual bug.

**Comment by chrtz** [comment]
unfortunately, this is still an issue (isn't it the same as https://github.com/buefy/buefy/issues/570, is it?)

**Comment by htokuda10** [comment]
@chrtz From my recollection when I reported this issue, and after reading both issue reports, they are not the same. This issue is preventing the Snackbar from redefining it's location, post initial render. Issue #570 is an issue where, 'has-custom-container' is automatically getting appended as an element class, whether or not the 'container' component property has been defined.

Even if you were to fix the automatic appending class 'has-custom-container', this would not fix that the Snackbar, once rendered, can not be relocated. This is caused by the block of code that I have screen shotted, titled 'Location - NoticeMixin.js'. I hope this answers your question.

**Comment by yxngl** [comment]
I will work on a fix.
