### ISSUE TITLE
Close autocomplete dropdown programatically?

### ISSUE THREAD

**Issue by taylorhoward92** [buefy/buefy#577]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome 64 on OS X

I am using the Autocomplete component for search suggestions. The idea is that a user can either select a suggestion from the autocomplete dropdown or can just do a free-text search. Then I use Vue router push to show the content for the suggestion, or a search results route for free-text search.

To allow submission of free-text search I am capturing the `@keydown.native.enter` event and taking appropriate action, including `blur()` on the input, but although the input gets deselected, the autocomplete dropdown menu still shows. I need a way to hide the dropdown menu or an alternate strategy for what I'm trying to achieve.

**Comment by jtommy** [comment]
@taylorhoward92 There isn't a method, maybe only `setSelected` but I think it isn't ok for you. 
Anyway you might set `isActive` data to false, `this.$refs.myAutocomplete.isActive = false`

**Comment by GarethTIGFreight** [comment]
I _sort of_ had a solution but with b-taginput with autocomplete but you should be able to adapt the code to work. See the *untested* code below. On the @typing event we filter the autocomplete results and append the filtered results with what you've typed. 

Alternatively you can use _ref_ on the autocomplete and directly access the inputted value (?). 

Good luck.

```
<template>
    <section>
        <b-field label="Insert a label">
            <b-taginput
                v-model="attr"
                :data="filteredTags"
                autocomplete
                placeholder="Insert a placeholder"
                @typing="getFilteredTags">
            </b-taginput>
        </b-field>
    </section>
</template>

<script>
    export default {
        name: 'meta-attribute-field',
        props: {
            def: {
                required: true
            },
            attr: {
                required: true
            }
        },
        data () {
            return {
                filteredTags: this.def.options,
                isSelectOnly: false
            }
        },
        methods: {
            getFilteredTags (text) {
                this.filteredTags = this.def.options.filter((option) => {
                    return option
                        .toString()
                        .toLowerCase()
                        .indexOf(text.toLowerCase()) >= 0
                })
                this.filteredTags.push(text)
            }
        }
    }
</script>
```

**Comment by williamabbott** [comment]
Would you accept a pull request to have something like "close-on-select" attribute?

**Comment by jtommy** [comment]
@williamabbott If ok, why not?
