### ISSUE TITLE
Am getting ReferenceError: keep is not defined on Production

### ISSUE THREAD

**Issue by guruprasaad123** [buefy/buefy#584]
Am using [Buefy](https://buefy.github.io/#/)[ **version : 0.6.2** ]  in my [vue-webpack project ](https://bitbucket.org/guru001/gms-webpack-buefy/src)[ **vue : 2.5.11** ].When working  in Development mode the site works fine.<br>
# Scenario
1._npm run dev_
The site works fine using webpack-dev-server.<br>
2._npm run build_
Build process is done successfully _without error_.<br>
3.opening the index.html in browser
Getting this unknown error below.<br>
![capture3](https://user-images.githubusercontent.com/19173193/35844614-31a0d966-0b30-11e8-9cea-f5b7dc0fe7be.PNG)
Please help me resolve this Issue.

**Comment by anteriovieira** [comment]
It's still not very clear to me. It looks like you have a variable called `keep` that is not defined.

**Comment by anteriovieira** [comment]
I need a minimal reproduction to help you.

**Comment by guruprasaad123** [comment]
You check this [repo](https://bitbucket.org/guru001/gms-webpack-buefy/src) ..!

**Comment by anteriovieira** [comment]
Sorry, I had not seen

**Comment by guruprasaad123** [comment]
first of all thanks for checking out ...
and its ok @anteriovieira have a clear look

**Comment by guruprasaad123** [comment]
Any updates? @anteriovieira

**Comment by anteriovieira** [comment]
Hi @guruprasaad123 , I'am sorry for the delay in replying.

The cause of the problem is: 

On line 364 you passed the value of the property as an expression instead of a string.

> <b-modal :active.sync="modal_cardamon" `:scroll="keep"`>

Change to

> <b-modal :active.sync="modal_cardamon" `scroll="keep"`>

**Comment by jtommy** [comment]
Thanks @anteriovieira
