### ISSUE TITLE
Transitionend not triggered on tab item after the content clicked

### ISSUE THREAD

**Issue by rizqyhi** [buefy/buefy#585]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome 64 on MacOS

### Description

I'm building a project which relies on `transitionend` event on tab item. If works fine if I don't click on the tab content. But after I click on the content, the event is not triggered anymore.

Demo: https://jsfiddle.net/rizqyhi/hmcmjne9/1/

### Steps to reproduce

1. Open the fiddle above and dev console
2. Navigate to tab 2 and back to tab 1, check console
3. Click on the tab 1 content
4. Navigate to tab 2

### Expected behavior

The transition event should triggered just like before.

### Actual behavior

The tab changed, but the `transitionend` is not triggered.

**Comment by rizqyhi** [comment]
Sorry to mention, @jtommy, can you have a look at this, please?

**Comment by rizqyhi** [comment]
Hi @rafaelpimpa could you please check out this issue. I haven't found any workaround for for a month. :)

**Comment by cwilby** [comment]
A workaround I'm using to get this and similar "when tab is active" features working is to store the active tab and only render `vue-infinite-loading` if the index is equal to the tabs index.

```vue
<template>
  <b-tab v-model="activeTab">
    <b-tab-item label="Sprockets">
      ...
      <vue-infinite-loading ... v-if="activeTab === 0" />
    </b-tab-item>
    <b-tab-item label="Ratchets">
      ...
      <vue-infinite-loading ... v-if="activeTab === 1" />
    </b-tab-item>
  </b-tab>
</template>

<script>
export default {
  ...

  data: () => ({
    activeTab: 0
  })
  
  ...
};
</script>
```
