### ISSUE TITLE
How to use multiline tooltips?

### ISSUE THREAD

**Issue by wsw70** [buefy/buefy#588]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.9.2
**OS/Browser**: Windows 10 / Chrome 64

### Description

I would like to format a tooltip so that it is multiline and force the newlines. 

### Steps to reproduce

An example is available at https://codepen.io/WoJWoJ/pen/qxqNrj

I tried `<br>` as the line delimiter, as well as `\n`

### Expected behavior

To get two lines in the tooltip

### Actual behavior

I got only one :)

_Note: I will use this opportunity to say THANK YOU for this excellent framework. It took me literally a few minutes to get what I needed (after having gone though a few of them before)._

**Comment by jtommy** [comment]
@wsw70 Thanks a lot! About `multiline`, by that prop automatically the text is multined. 
If you want to force, you might set `white-space: pre` to `tooltip ` class and use `\A` (equivalent HTML is `&#xa;`), for example https://codepen.io/anon/pen/bLBaKw

**Comment by Lolhomme** [comment]
Hey guys! I got the same issue:
my html:
`<b-tooltip class="history" :label="getHistory()" multilined>
                                <p>{{ event.history[0].action }} by {{ event.history[0].people }} on {{ event.history[0].date }}</p>
                            </b-tooltip>`

my method: return a string
`getHistory() {
        const ret = this.event.history.map(e => {
            return e.action+" by "+e.people+" on "+e.date
        })
        return ret.join()
    }`

Joining with `&#xa;` didn't worked the html code wasn't interpreted

**Comment by Lolhomme** [comment]
Found it! 
Without multilined props:
```html
<b-tooltip class="history" :label="getLabel()">
         Test
</b-tooltip>
```

On js side:
```js
getLabel() {
        return "Test\nTest"
}
```
And with your css code on above exemple!

**Comment by iaacek** [comment]
Hi, 

I used to use the code that Lolhomme described but it stopped working recently. I am not sure what is wrong but I can no longer force the new line in the b-tooltip label. 

Anybody else run into this?

**Comment by afwn90cj93201nixr2e1re** [comment]
```css
<style>
._abcd.b-tooltip:after {
    white-space: pre;
}
</style>
```


```html
<b-tooltip class="_abcd" :label="123\n456`" type="is-dark" position="is-bottom" animated multilined></b-tooltip>
```

@iaacek if you still need this

**Comment by xlcrr** [comment]
Simply adding `multilined` did it for me - thanks!

**Comment by bombxdev** [comment]
Try on this.
```
<b-tooltip position="is-bottom" type="is-dark" dashed multilined>
    <template v-slot:content>
        <div class="has-margin-15">
            <b-rate :value="3" icon="star" custom-text="Large" :max="3" :spaced="true" disabled></b-rate>
        </div>
        <div class="has-margin-15">
            <b-rate :value="2" icon="star" custom-text="Medium" :max="3" :spaced="true" disabled></b-rate>
        </div>
        <div class="has-margin-15">
            <b-rate :value="1" icon="star" custom-text="Low" :max="3" :spaced="true" disabled></b-rate>
        </div>
    </template>
    Tooltip Multilined
</b-tooltip>
```

**Comment by marchev** [comment]
> Try on this.
> [...]
> [Live Demo](https://codepen.io/bombxdev/pen/NWbLxzz)

Thank you @bombxdev! That's the best solution - no magic, no CSS trickery - just awesome :-)

**Comment by starmarek** [comment]
Only @bombxdev  solution is working. I am using buefy 0.9.4
