### ISSUE TITLE
Accordion? [req]

### ISSUE THREAD

**Issue by diomed** [buefy/buefy#592]
How come buefy doesn't have **accordion** option?

**Comment by jtommy** [comment]
@diomed Do you mean a `collapse` component wrapper ?

**Comment by diomed** [comment]
right. I usually use UIkit where it's called differently:
https://getuikit.com/docs/accordion

I see that bootstrap also has example of that. 
maybe you should add an example for it.

**Comment by ErwanTouba** [comment]
would appreciate a collapse component wrapper aswell

**Comment by DevGoslinga** [comment]
https://buefy.org/documentation/collapse

Since we have the component now I think this issue can be closed.
