### ISSUE TITLE
Autocomplete dropdown position (especially for mobile)

### ISSUE THREAD

**Issue by stackmont** [buefy/buefy#595]
### Overview of the problem
Would be nice if we could specify the dropdown position (top, bottom, left, right). I think it is automatically determined right now, which works good enough most of the time, but sometimes it is positioned inconvenient or outside the screen.

For a mobile/small screens: when the dropdown is active it would be more user friendly if it was positioned underneath the autocomplete input or even better, scrollable on mobile.

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X)

### Expected behavior

The dropdown positioned underneath the autocomplete input or scrollable on mobile.
 

### Actual behavior

The dropdown positioned above the autocomplete input and half of its content floats outside the screen.

![schermafbeelding 2018-02-09 om 15 53 14](https://user-images.githubusercontent.com/30037913/36034187-86e2da7a-0db3-11e8-9e29-1bd6ead466ea.png)

**Comment by jtommy** [comment]
@stackmont In the last version, `autocomplete` component has vertical scrollbar when height is greater than 200px.

**Comment by salihyasinseker** [comment]
It would be perfect if we could change the Autocomplete icon place (especially to right).

**Comment by frederic117** [comment]
Got the same issue: how to force it to be downside?

**Comment by yxngl** [comment]
Currently it is downward if there is space in the window, otherwise it shows upward.
For me, the dropdown is near the bottom and goes downward, but it is hidden by the footer.

We could have a prop to explicitly indicate the direction besides the current `isListInViewportVertically`

**Comment by shelru** [comment]
https://github.com/buefy/buefy/issues/1316#issuecomment-488126144

**Comment by dauriata** [comment]
This issue is marked as staled but I think unresolved.
If there is interest I am willing to submit a PR for either : 
- providing a prop to be able to select dropdown position : top, down, or calculated
- modify calculated behavior as now to show dropdown down when there is not enough room both up and down ( which usually happen on mobile when the virtual keyboard is shown)

**Comment by jtommy** [comment]
@dauriata ok!
