### ISSUE TITLE
Issue with sorting table and multiple opened detailed rows

### ISSUE THREAD

**Issue by hterrence** [buefy/buefy#596]
First of all, thanks for taking the time for developing this library.

### Description
Table sorting destroys proper order of the opened detailed rows (after sorting detailed rows should be still "attached" to its original row).

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: macOS High Sierra, reproduced on Chrome 63, Firefox 58 and Opera 51

### Steps to reproduce
1. Go to [CodePen](https://codepen.io/anon/pen/KQmKKo?editors=1010)
2. Expand first row
3. Expand last row
4. Click on _First Name_ to trigger sort

### Expected behavior
Component's data should correspond to props data after sorting

### Actual behavior
Looks like table and props are sorted, but custom components are not. Then after sorting, detailed component and table row don't match.
Before sorting:
![image](https://user-images.githubusercontent.com/32852656/36073722-6a8a924a-0f35-11e8-97cf-8181fb8e5e31.png)

After sorting:
![image](https://user-images.githubusercontent.com/32852656/36073700-120d5d50-0f35-11e8-8875-b1d2d376a427.png)

**Comment by jtommy** [comment]
@hterrence Thanks!
About your issue i think the problem is in your `person-details` component because you should use a `computed` prop and no a state variable (`data`) 
For example:
```
computed: {
  name: function() { 
       return `${this.person.user.first_name} ${this.person.user.last_name}`
}
```

**Comment by hterrence** [comment]
@jtommy the usage of data in this example was simplified, just to show the issue. Maybe more "real life" example will be better. So here is the website that I've started working on (https://cryptovibe.io): 
![image](https://user-images.githubusercontent.com/32852656/36101737-7cb4fe4e-100a-11e8-841f-b6c6f128fde0.png)

When you expand the row, data is being fetched from the server and you can change chart view inside detailed component (so state is needed there). Unfortunately when you have opened multiple detailed components after you change sorting, component's data stops corresponding to its row.

**Comment by jtommy** [comment]
@hterrence I'm looking your code and you are using an old row value. You should use  row prop of your component into template o watch that prop and update internal row variable that are you using into template.
