### ISSUE TITLE
watch in checkbox

### ISSUE THREAD

**Issue by diomed** [buefy/buefy#603]
https://github.com/rafaelpimpa/buefy/blob/161607032706b39a13474def7937f6efd6b2b739/src/components/checkbox/Checkbox.vue#L45

_watch is expensive and should be avoided.
That's a watch for every single form element you have with Buefy._

**Comment by jtommy** [comment]
@diomed We use `watch` because in this way the component update own internal state when `value` change (`v-model`).

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/c5e8899ccd307e1381d8204699b569da965df797
