### ISSUE TITLE
Suggestion: Versioned Documentation

### ISSUE THREAD

**Issue by jwahdatehagh** [buefy/buefy#607]
I have quite a few different Buefy installations running and they are getting a little difficult to maintain with only the current documentation version live.

Have you considered versioning the documentation (e.g. like bulma does: https://versions.bulma.io/)?
How can i help with this / would you be open to contributions for this?

**Comment by adrlen** [comment]
I know It's not ideal but if you didn't think about it already, you can clone the repo and checkout at the selected version to ru

**Comment by jwahdatehagh** [comment]
Thanks for the suggestion! I still think an online version would be reasonably helpful ;)

**Comment by Herteby** [comment]
Interesting idea: Since the documentation served straight from the repo by github.io, and is already properly tagged with version numbers in the repo, maybe it would be possible to do this automatically?

**Comment by raisou** [comment]
Hi,
I think too that an online version would be very helpfull :)
