### ISSUE TITLE
TagInput | Control field min-width

### ISSUE THREAD

**Issue by adrlen** [buefy/buefy#613]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: MacOS/Chrome64

### Description

When having multiple tags in TagInput, it can occur that the control field has a small width limiting what is visible.

### Steps to reproduce

Add multiple tags in tag input without having the control going back on the line

### Expected behavior

Have better vision on what is typed

### Actual behavior

![screen shot 2018-02-16 at 17 45 29](https://user-images.githubusercontent.com/1764097/36318856-5ac8e55e-1341-11e8-8b16-2521bf350254.png)

Just setting a `min-width` should resolve this. PR ?

**Comment by jtommy** [comment]
@adrlen Ok, we'll evaluate your PR, thanks!

**Comment by adrlen** [comment]
Would it be possible to add it in PR #604 ? What do you think of this improvement ?

**Comment by jtommy** [comment]
I prefer a new PR. I think it's a good idea!

**Comment by adrlen** [comment]
I noticed an other problem when a tag width > container width.

We can put `overflow-x: scroll` on the container but then we have the scrollbar even when not needed. It might need another issue.

**Comment by jtommy** [comment]
@adrlen I'm thinking an other solution about it, for example to show ".." when the word is too long.

**Comment by adrlen** [comment]
That's actually a way better idea, I don't know how to implement it without having only attached tags though. It definitely needs another issue.

**Comment by jtommy** [comment]
@adrlen I'll implement it later, don't worry.
