### ISSUE TITLE
Dropdown component css styling issues when used in navbar with color modifier

### ISSUE THREAD

**Issue by lunfel** [buefy/buefy#614]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Ubuntu/Chrome 64

### Description

Dropdown component breaks the bulma css styling when used in navbar with color modifier.

### Steps to reproduce

1. [Customise bulma theme](https://buefy.github.io/#/documentation/customization)
```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors
$primary: #3498D8; // Changed value
$primary-invert: findColorInvert($primary);
$twitter: #4099FF;
$twitter-invert: findColorInvert($twitter);

// Setup $colors to use as bulma classes (e.g. 'is-twitter')
$colors: (
        "white": ($white, $black),
        "black": ($black, $white),
        "light": ($light, $light-invert),
        "dark": ($dark, $dark-invert),
        "primary": ($primary, $primary-invert),
        "info": ($info, $info-invert),
        "success": ($success, $success-invert),
        "warning": ($warning, $warning-invert),
        "danger": ($danger, $danger-invert),
        "twitter": ($twitter, $twitter-invert)
);

// Links
$link: $primary;
$link-invert: $primary-invert;
$link-focus-border: $primary;

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
2. Change the `$primary` variable to `#3498D8;`
3. Create a navbar with a dropdown component. Here is what I did.

```
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="#">
                <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">
            </a>

            <div class="navbar-burger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item">Test</a>
                <b-dropdown position="is-bottom-left">
                    <a class="navbar-item" slot="trigger">
                        <span>Menu</span>
                        <b-icon icon="menu-down"></b-icon>
                    </a>

                    <b-dropdown-item custom>
                        <b>username</b>
                    </b-dropdown-item>
                </b-dropdown>
            </div>
        </div>
    </div>
</nav>            
```

### Expected behavior

I would expect that the font of the nav-item is white.
I would expect that the on-hover background would be a slightly darker blue

### Actual behavior

The font is dark grey and does not meld properly with the navbar color
The on-hover background is light-gray and does not meld properly with the navbar color

### Solution path

I can temporarily solve the problem when I edit [navbar.sass](https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass#L74) from Bulma. I need to change every `& > .navbar-item` occurences to `& .navbar-item`.

I do not want to edit vendor files and I am not comfortable enough with sass to send a fix for that issue.

**Comment by lunfel** [comment]
![buefy-css-issue](https://user-images.githubusercontent.com/1844873/36323408-da288390-131e-11e8-8925-a3b244b47aed.png)

Test is a standard a.navbar-item

Menu is a dropdown component with a.navbar-item within

**Comment by lunfel** [comment]
I got a quick fix for it

create a `custom.sass` file and put this in it

```
.navbar
  @each $name, $pair in $colors
    $color: nth($pair, 1)
    $color-invert: nth($pair, 2)
    &.is-#{$name}
      .navbar-brand
        & a.navbar-item,
        .navbar-link
          &:hover,
          &.is-active
            background-color: darken($color, 5%)
            color: $color-invert
        .navbar-link
          &::after
            border-color: $color-invert
      +desktop
        .navbar-start,
        .navbar-end
          & .navbar-item,
          .navbar-link
            color: $color-invert
          & a.navbar-item,
          .navbar-link
            &:hover,
            &.is-active
              background-color: darken($color, 5%)
              color: $color-invert
          .navbar-link
            &::after
              border-color: $color-invert
```

Then reference this fix after including buefy as so:

```
// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
@import "./assets/custom"; // This should be the path to the custom.sass file created earlier.
```

**Comment by jtommy** [comment]
@lunfel Did you open an issue in Bulma repository ?

**Comment by lunfel** [comment]
No because I think this is an issue with buefy only. The component nature of vue.js puts an additional div in the current context which breaks the sass rules of bulma. But technicaly Bulma has correct rules and Bulma should not be "aware" of Buefy.

**Comment by jtommy** [comment]
@lunfel Ok, anyway contributions are welcome.

**Comment by lunfel** [comment]
@jtommy Would you like to me to put a pull request with my proposed fix?

**Comment by jtommy** [comment]
@lunfel Ok, so we'll think it there is a best solution

**Comment by lunfel** [comment]
I'm trying to make a pull request to fix the issue and I am noticing that Bulma is using SASS and Buefy SCSS which seem incompatible. I tried to convert my SASS fix to SCSS, but it's a mess because of all the dependencies on the Bulma variables.

I think you were right @jtommy, the fix should be done in Bulma rather than in Buefy. I don't think it is possible to do it properly from Buefy unfortunately.

**Comment by jtommy** [comment]
@lunfel Did you open an issue or PR in Bulma repo ?
