### ISSUE TITLE
Provide slots in datepicker for customized year and month selection

### ISSUE THREAD

**Issue by dumptyd** [buefy/buefy#615]
`b-datepicker` uses HTML `select` for year and month selection, however I'd like to use `b-dropdown` or `b-autocomplete` for this instead.
Currently, there's no way to do this, it would be nice if there were slots to provide your own year and month selection UI.

**Comment by jtommy** [comment]
@dumptyd  We could add a `header` slot so you can customize all (selects and buttons)

**Comment by dumptyd** [comment]
Thank you!

**Comment by jtommy** [comment]
I think, I'll add an example about header slot and how to move date table
