### ISSUE TITLE
Datepicker - Unselectable all dates, except specific ones

### ISSUE THREAD

**Issue by gpassarelli** [buefy/buefy#617]
Hi there, first of all, thanks for this amazing project. It is awesome.

I was looking at the documentation for the Datepicker component, and I've found that I can specify the attribute "unselectable-dates" to pass an Array of unselectable dates. 
But what if I want to all dates by unselectable, except an array of selectable dates.

Is it possible to do this? If not, I could try to make a PR to allow this option if you think it makes sense.

Thanks again

**Comment by jtommy** [comment]
@gpassarelli Thanks!
What about `min` and `max` props ?

**Comment by gpassarelli** [comment]
@jommy, the problem is that I don't have a "range" of dates.
I'm working on a project that the user can choose the start date for a course, some courses start every Monday, others have specific dates, for example, April 1st, June 4th, and December 7th. And the date picker must have only these specific dates.

**Comment by jtommy** [comment]
@gpassarelli Ok, you are free to make a PR and we'll evaluate it.

**Comment by jtommy** [comment]
Closed https://github.com/buefy/buefy/pull/645
