### ISSUE TITLE
i wanna display none of section created by  b-tabs

### ISSUE THREAD

**Issue by dongugkim** [buefy/buefy#623]
![default](https://user-images.githubusercontent.com/25264202/36355403-09c9ef90-1526-11e8-9f34-cdd17011a4a7.PNG)

![12](https://user-images.githubusercontent.com/25264202/36355422-3c8bd1f0-1526-11e8-9887-0459c54cea80.PNG)

i wanna make from first pic to last pic

**Comment by jtommy** [comment]
@dongugkim You should force to reset "tab-content" class by your css
