### ISSUE TITLE
Ability to return autocomplete results under grouped headers

### ISSUE THREAD

**Issue by grebebird** [buefy/buefy#626]
### Description
I'm looking to use the autocomplete feature in combination with, conceptually, a grouped select list. I couldn't figure out if this was feasible within the available components today or if it would be a request for a new feature.

### Expected behavior
As a user types, the list of names matching would be returned _under their parent category header_ (such that only a sub-set of each category is being displayed). Category headers without matches would not be displayed. 

Added bonus # 1: Be able to search on category headers such that (in the use case below), searching for "Game of Thrones" would display all four names (to help the user find options more easily under a category header). 

Added bonus # 2: Allow, based on a toggle, the ability to select the _category header itself_ as an option (I could see use-cases for allowing or disallowing this). This isn't possible today with "select grouping" headers though, so it's a low priority.

![buefy-autocomplete-groupings1](https://user-images.githubusercontent.com/35107989/36438118-ebe9b214-1636-11e8-8b79-2c187ee4f7c5.png)
![buefy-autocomplete-groupings2](https://user-images.githubusercontent.com/35107989/36438137-f3ae839e-1636-11e8-9275-aff2f1c55300.png)

**Comment by jtommy** [comment]
@grebebird Did you try using default slot ?

**Comment by grebebird** [comment]
The default slot is singular though, correct? In theory, the search could return multiple hierarchy headers. For example, if I searched for "is" above, I'd get both "Breaking Bad > Heisenberg" and "Game of Thrones > 2 Lannister matches".

**Comment by jtommy** [comment]
Oh yes you are right! 
To be honest at the moment it isn't in our plan.

**Comment by grebebird** [comment]
Ok, no worries. Just another idea that we'd use if it was there - I wanted to be sure I wasn't missing another possible way to do this. :) I'm sure you already have plenty of ideas on your backlog, though.

**Comment by jonagoldman** [comment]
+1: Providing a slot for multiple items or some way to group items the same way its done in regular select elements. I am using autocomplete to search for products in a shop. Those products are grouped in categories: Food, Drinks, ...

**Comment by ohugonnot** [comment]
Same needs, this kind of feature can be very useful

**Comment by davidbkay** [comment]
So...I bit off more than I can chew and made something similar using Buefy components and computed properties. I'm sure someone can show me how to do this more elegantly.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/16613132/52305611-228dec80-295b-11e9-8fcf-4bb51d83a11e.png">

## The component

```html
<template>
  <b-dropdown>
    <b-input
      slot="trigger"
      v-model="search"
      expanded
      size="is-medium"
      icon="magnify"
      rounded
      placeholder="Search here..."
      type="search"
    />
    <b-dropdown-item custom class="has-text-left">
      <p class="title is-5 has-text-dark">
        State
      </p>
    </b-dropdown-item>
    <b-dropdown-item v-for="entity in filteredState" :key="entity.entityDisplayName" label="State">
      {{ entity.entityDisplayName }}
    </b-dropdown-item>
    <template v-if="filteredDistricts.length > 0">
      <hr class="dropdown-divider">
      <b-dropdown-item custom class="has-text-left">
        <p class="title is-5 has-text-dark">
          Districts
        </p>
      </b-dropdown-item>
      <b-dropdown-item v-for="entity in filteredDistricts" :key="entity.entityDisplayName">
        {{ entity.entityDisplayName }}
      </b-dropdown-item>
    </template>
    <template v-if="filteredDistricts.length > 0">
      <hr class="dropdown-divider">
      <b-dropdown-item custom class="has-text-left">
        <p class="title is-5 has-text-dark">
          Schools
        </p>
      </b-dropdown-item>
      <b-dropdown-item v-for="entity in filteredSchools" :key="entity.entityDisplayName">
        {{ entity.entityDisplayName }}
      </b-dropdown-item>
    </template>
  </b-dropdown>
</template>
```
### My computed properties

```javascript
computed() {
    filteredState() {
      return this.entities.filter(item => item.entityType === 'State')
    },
    filteredDistricts() {
      return this.entities.filter(item => (item.entityType === 'District' && item.entityDisplayName.toLowerCase().indexOf(this.search.toLowerCase()) > -1))
    },
    filteredSchools() {
      return this.entities.filter(item => (item.entityType === 'School' && item.entityDisplayName.toLowerCase().indexOf(this.search.toLowerCase()) > -1))
    }
}
```

**Comment by tpavlek** [comment]
While @davidbkay has a decent solution here, there's a LOT of extra implementation work there, especially if one wants to have groups in the autocomplete of a `tagsinput` - you basically have to reimplement the entire tag input functionality just to get the grouped headers.

This feature would be something that would be really great to see in buefy.

**Comment by rubjo** [comment]
A year later, I found this issue. Any plans to reconsider adding this? :)

**Comment by jtommy** [comment]
@rubjo it's no a bad idea but I would like to find a good way, for example group-key prop

**Comment by jtommy** [comment]
@rubjo ready for next release 0.9.2 😃 https://github.com/buefy/buefy/commit/2bcd553a2790822dd5f997e97cad87691b39778a
