### ISSUE TITLE
b-upload doesn't work with accept=".jpg"

### ISSUE THREAD

**Issue by Ben-Mack** [buefy/buefy#630]
`b-upload` work fine with attribute `accept="image/jpeg"`  but `accept=".jpg"` doesn't work.

Please see this codepen https://codepen.io/anon/pen/NyMrKy?editors=1010 (I only added `accept=".jpg"`)

**Comment by Ben-Mack** [comment]
Also, on latest chrome, when I move cursor over the text `Drop your files here or click to upload`, cursor changed back to `default` state instead of `pointer`. I fixed that by styling css input width height to 0

**Comment by jtommy** [comment]
@Ben-Mack Accept issue fixed https://github.com/buefy/buefy/issues/575.
