### ISSUE TITLE
How can I close a modal?

### ISSUE THREAD

**Issue by linuxfreak90** [buefy/buefy#633]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.7
**OS/Browser**: Firefox Developer Edition

### Description

In second example: `<button class="button" type="button" @click="$parent.close()">Close</button>`

I want to close the modal as given in the first example:

```
<button class="button" type="button" @click="$self.close()">Close</button>
<button class="button" type="button" @click="close()">Close</button>
<button class="button" type="button" @click="cancel(x)">Close</button>
```

### Steps to reproduce

1. Add close button to footer
2. Close the modal

### Expected behavior

1. Closing the modal

### Actual behavior

Remains open, but I'm must be doing something wrong.

Thanks.

**Comment by linuxfreak90** [comment]
`<button class="button" type="button" @click="isImageModalActive = false">Cancel</button>`

Maybe there is a better solution, thanks anyway. :)

**Comment by cwilby** [comment]
Had a similar issue, setting `active = false` wouldn't fire `onClose` event.

Solution is to create a ref to modal, then call `.close()` on the ref.

```vue
<template>
  <b-modal 
    ref="modal">
    <button @click="closeModal()">Close</button>
  </b-modal>
</template>

<script>
export default {
  methods: {
    closeModal() {
      this.$refs.modal.close()
    }
  }
};
</script>
```
