### ISSUE TITLE
Prevent snackbar from fading out

### ISSUE THREAD

**Issue by rcubitto** [buefy/buefy#634]
Is there a way to achieve this without doing something like `duration="100000"`?

**Comment by adrlen** [comment]
It's not possible at the moment.

**Comment by rcubitto** [comment]
Would you be interested in a PR for this? I could give it a try.

**Comment by timwis** [comment]
I'm interested in this too -- I typically store error messages in state and set a timer to remove them from state.

**Comment by jtommy** [comment]
@rcubitto We added a new prop `indefinite` to show a snackbar until it is dismissed (for example by action click)

**Comment by rcubitto** [comment]
That is awesome. Thanks for the hardwork!
