### ISSUE TITLE
Table - sort arrow on column header does not work when using "columns" property to define simple tables

### ISSUE THREAD

**Issue by alqu** [buefy/buefy#635]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**: Mac/Chrome

### Description

When using property "columns" to define table's columns the little sort arrow on the column header is not shown on the sorted column but stays on the first column.

### Steps to reproduce

1. Define a b-table only by using the new "columns" property. Use a data source that supports sorting of course.
2. Fill in 2 columns, e.g.
```js
...
sortcolumn: 'first_name',
columns: [
          {
            field: 'id',
            label: 'ID',
            width: '40',
            numeric: true
          }, {
            field: 'username',
            label: 'user name',
            sortable: true
          }, {
            field: 'first_name',
            label: 'First name',
            sortable: true
          }
]
```
3. Try it out by clicking on the column heads for sorting

### Expected behavior

The column header reflects the sorting state of the data by showing the sort direction arrow accordingly.

### Actual behavior

On initial load the sort arrow is set correctly.
After clicking on any other sortable column the arrow is only displayed on the first column, no matter if the first column is sortable or not.

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/3cfaf691bf14a5a2c6ad8601ae16f731569e7d3a
