### ISSUE TITLE
TagInput | Commas separated tags

### ISSUE THREAD

**Issue by adrlen** [buefy/buefy#636]
In the default implementation of the TagInput component, when pressing comma key it adds the tag automatically. But when pasting a string containing multiple words separated by commas, the tag is added as it is and not separated into multiple tags.

Do you think this should be a default behaviour ?

Should we be able to add commas in tags by default and have a props to specify separators that would also be handled when pasting a string ?

**Comment by adrlen** [comment]
I implemented this here :

https://github.com/adrlen/buefy/commit/f23c4db13a3272f0c56f814fd538513e92a929ee

**Comment by jtommy** [comment]
@adrlen The question is good! We could separate or get only the first word before comma (truncate). 
Anyway we should check if the word contains not comma key but any keys by `confirm-key-codes` prop, for example someone might change default keys.

**Comment by adrlen** [comment]
It seems difficult to handle dynamically the keys actually, because then you have to split the string with the char associated with the key code.

**Comment by jtommy** [comment]
Yes but comma couldn't be a separator key code

**Comment by adrlen** [comment]
If you check my commit above, this case is handled. I agree it's not ideal to implement it only for comma though.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/pull/795
