### ISSUE TITLE
BUG b-input with barcode scanner

### ISSUE THREAD

**Issue by brunoosilva** [buefy/buefy#640]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome 64.0.3282.167 

### Description

Problem with `v-model` of `b-input` using barcode scanner (put data fast and press key ENTER), has delay for get data of model. I also tested with `v-model.lazy`, but don't work! 

I tested with `<input v-model="" />` pure and it works normally.

### Steps to reproduce

1. Put data fast and press ENTER in input inside of form
2. Get data incomplete in method of submit

### Expected behavior

Expect receive: `PED1519398320465`

### Actual behavior

Return `PED151939832046`

### Screen

![bug_b_input](https://user-images.githubusercontent.com/3465257/36609995-772511de-18ad-11e8-8ab1-34ab8a2b80e8.gif)

**Comment by jtommy** [comment]
@brunoosilva `v-model.lazy` doesn't work with components but it's a sugar sintax of `:value="var" @change="($event) => var = $event.target.value"`. 
`b-input` doesn't emit change so you should bind native event, for example `@change.native="($event) => ..."`

**Comment by jtommy** [comment]
@brunoosilva Is it works ?

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy close this too, and maybe we should clear all old issues without feedback's?

**Comment by jtommy** [comment]
There are so many issues in the same status, btw thanks

**Comment by afwn90cj93201nixr2e1re** [comment]
Yeah, i know, this would be better for creating real roadmap issue's list. Without non-feedback.
