### ISSUE TITLE
How to use date-formatter to format output date

### ISSUE THREAD

**Issue by tanhs** [buefy/buefy#643]
### Overview of the problem

**Buefy** version: [5.6.0]
**Vuejs** version: [5.6.0]
**OS/Browser**: Chrome

### Description
Need guide to show different format of date output from datepicker.
How to use the date-formatter to format the date into "DD-MMM-YYYY"

### Steps to reproduce
```
<b-datepicker name="dob" id="dob"  v-model="dob" icon="today" 
                      placeholder="MM/DD/YYYY" :required=isRequiredDob :disabled=isDisabled
                      date-formatter=???????
                      :max-date="dobMaxDate"></b-datepicker>

....
<script type="text/javascript">
var App = new Vue({
    el: '#app',
    data: {
...
        mounted() {
          if("{{$patient->dob}}"!=""){
            this.dob = Vue.moment.utc("{{$user->dob}}", "YYYY-MM-DD H:mm:ss").toDate();
          }  
```
### Expected behavior

Output of date this format "DD-MMM-YYYY"

### Actual behavior

Default it show "MM/DD/YYYY"

**Comment by tanhs** [comment]
I got it fixed.

```
date-formatter="dobFormatter"
..
    methods: {
      dobFormatter(){
        return today.toLocaleDateString('en-GB', options);
      },

```

**Comment by cAstraea** [comment]
How did you get it work @tanhs ? I'm getting [Vue warn]: Invalid prop: type check failed for prop "dateFormatter". Expected Function, got String.

**Comment by stuartcusackie** [comment]
I'm getting same error using the date-formatter property on the field.

I'm using the global config instead:

`defaultDateFormatter: (date) => Moment(date).format("DD/MM/YYYY")`

**Comment by jtommy** [comment]
It's only an example but where is the issue ? https://codepen.io/anon/pen/dmPgwW?&editors=101

**Comment by stuartcusackie** [comment]
`<b-field><b-datepicker date-formatter="formatterFunction"></b-datepicker></b-field>`

I have the formatterFunction() declared in my methods but I get the error:
[Vue warn]: Invalid prop: type check failed for prop "dateFormatter". Expected Function, got String.

**Comment by jtommy** [comment]
You have to add : to date-formatter prop

**Comment by tanhs** [comment]
Hi,
Hope this help.

                    <b-datepicker name="dob" id="dob"  v-model="dob"
icon="today"
                      placeholder="DD-MMM-YYYY" :required=isRequiredDob
:disabled=isDisabled
                      :date-formatter="dateFormatter"
                      :max-date="dobMaxDate"></b-datepicker>

dateoptions = { year: 'numeric', month: 'short', day: 'numeric' };
...
    methods: {
      dateFormatter(dt){
        return dt.toLocaleDateString('en-GB', dateoptions);
      },
