### ISSUE TITLE
Set td colspan/rowspan depending on the data

### ISSUE THREAD

**Issue by MacedoRAC** [buefy/buefy#649]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13

### Description
There is any way to add **colspan** and/or **rowspan** attributes to a cell depending on the data?

**Comment by jtommy** [comment]
@MacedoRAC At the moment there is no way to add colspan or rowspan

**Comment by Davroniy** [comment]
Is there any update on rowspans and colspans?

**Comment by jtommy** [comment]
@Davroniy https://github.com/buefy/buefy/issues/2980
