### ISSUE TITLE
Releases are being tagged as "prerelease", so package managers are stuck at old versions

### ISSUE THREAD

**Issue by philipithomas** [buefy/buefy#650]
Buefy releases are not being promoted from "prelease", so package managers are not upgrading past v ~0.5.4. Please mark the release as prod!

**Comment by rafaelpimpa** [comment]
It's not updating automatically because it has breaking changes (0.5 to 0.6), it's not a pre-release.

**Comment by cldershem** [comment]
I haven't had the same problem as @philipithomas, but tagging every release as 'pre-release' does make it difficult to tell what's stable. When everything is 'pre-release' it loses all meaning. Is there a good reason for it?

**Comment by rafaelpimpa** [comment]
Was putting everything as pre-release since we're not at 1.0 yet, but I might change it for stable releases
