### ISSUE TITLE
Vertical scroll bar for b-table

### ISSUE THREAD

**Issue by as1s** [buefy/buefy#651]
Can we have a vertical scroll bar added to the b-table component?

**Comment by jtommy** [comment]
@as1s You might customize it by CSS, for example:
```
 <b-table class="my-table" ...

.my-table {
  max-height: 200px;
  overflow-y: auto;
}
```

**Comment by jwjcmw** [comment]
Will you not already get one by just setting a height on the table container?

**Comment by jwjcmw** [comment]
The answer by @jtommy popped in right as I hit comment...something like that would be the way to go, imo.

**Comment by as1s** [comment]
Yes,  that works. Thanks.
But I have the table in a tile and don't want it in fixed height but sized proportionally to the screen size.
How to determine what should be part of the component and what should be left out as custom style?

**Comment by jtommy** [comment]
@as1s We should see your code to understand well. Anyway it's no a Buefy issue.

**Comment by RaashVision** [comment]
> 
> 
> Yes, that works. Thanks.
> But I have the table in a tile and don't want it in fixed height but sized proportionally to the screen size.
> Also I want the header to be visible.
> How to determine what should be part of the component and what should be left out as custom style?

I have header and footer too. I followed as what @jtommy said and it works. I want the table to show 50% of height of screen so I did this change.
`
.my-table {
  max-height: 50vh;
  overflow-y: auto;
}
`
Check on this to know what is vh.
https://alligator.io/css/viewport-units/

It is very late reply, but might be helpful for others.
