### ISSUE TITLE
Suppress Autocomplete

### ISSUE THREAD

**Issue by apmontgomery** [buefy/buefy#658]
Is there anyway to suppress the autocomplete modal?  I'd like to be able to change the value of an autocomplete field without showing the autocomplete. 

Use case: restoring values from localstorage currently opens all autocompletes on a page.  That is visually jarring.  I would prefer to only show the autocomplete when the field is in focus.

**Comment by jtommy** [comment]
@apmontgomery Could you provide us your code or an example ?

**Comment by robertbakker** [comment]
For me it happens when the data of v-model gets changed inside ```mounted() {}```. The suggestions dropdown triggers, without the user focusing the input.
