### ISSUE TITLE
Add counters to the Tabs component

### ISSUE THREAD

**Issue by hetsketch** [buefy/buefy#659]
I've used `Tabs` component recently and I think it would be great to add counters. Something like github has. Here is a screen
<img width="280" alt="screen shot 2018-03-02 at 19 58 26" src="https://user-images.githubusercontent.com/3451694/36911327-439c3b56-1e54-11e8-9b1f-df0ddb4896b6.png">

**Comment by jwjcmw** [comment]
+1 to this...that use case is actually why I want I want #655, but having a prop for the count that could be bound would be even better.

**Comment by dumptyd** [comment]
Providing a slot for this would be a better solution IMO.

**Comment by jtommy** [comment]
@Yes, we are thinking to add a slot

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/f66604bb51ea53cff70a07d380b01b57024c8620

**Comment by skoncal** [comment]
Does this work?  When I try to use the example code nothing gets rendered in the tab
