### ISSUE TITLE
The b-icon component doesn't fire a click event.

### ISSUE THREAD

**Issue by francoislevesque** [buefy/buefy#660]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.2
**OS/Browser**: Windows 10/Chrome

### Description

The `b-icon` component doesn't fire a `click` event.

### Steps to reproduce

http://jsfiddle.net/aywkphtd/1/

### Expected behavior

An alert on click.

### Actual behavior

No alert on click.

**Comment by adrlen** [comment]
Use `@click.native`
