### ISSUE TITLE
The "maxlength" property is not working correctly

### ISSUE THREAD

**Issue by andrzejkupczyk** [buefy/buefy#662]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Ubuntu/Chrome

### Description

The `maxlength` property (character counter) is not working correctly when you add the number modifier to a `v-model` managed input:
```
<b-input type="number" v-model.number="foobar" maxlength="10"></b-input>
```
![zrzut ekranu z 2018-03-04 13-37-37](https://user-images.githubusercontent.com/11018286/36945635-a0687f62-1fb1-11e8-8357-188fa699a0da.png)
![zrzut ekranu z 2018-03-04 13-53-04](https://user-images.githubusercontent.com/11018286/36945792-66a06d10-1fb3-11e8-954c-f141b5075086.png)

It doesn't seem to work with big numbers as well (without the modifier this time):
```
<b-input type="number" v-model="foobar" maxlength="10"></b-input>
```
![zrzut ekranu z 2018-03-04 13-58-00](https://user-images.githubusercontent.com/11018286/36945841-2673abde-1fb4-11e8-8732-b81d36135feb.png)

**Comment by jtommy** [comment]
@andrzejkupczyk Maxlength attribute is ignored for number type. Please read that official docs https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength

**Comment by andrzejkupczyk** [comment]
Thanks a lot for pointing it out to me :+1: Nevertheless, counter shows up and it works until the "number" modifier is being used which is not compatible with the official documentation.

> For other control types, it is ignored. It can exceed the value of the size attribute. If it is not specified, the user can enter an unlimited number of characters

So, in my opinion, it **should count characters** OR **should not be visible** at all.

**Comment by andrzejkupczyk** [comment]
So why is this closed?

**Comment by jtommy** [comment]
@andrzejkupczyk Because maxlength is not a valid attribute for type number.

**Comment by andrzejkupczyk** [comment]
Well, we've already agreed, but the core question remains, @jtommy. Current behaviour is inconsistent. Personally I would like to use the counter regardless of the field type. In my case it should work correctly or shouldn't be visible at all. Shouldn't the counter work independently? What if I DON'T want to display counter when using the `maxlength` attribute?

Btw. I love Buefy. Thank you for your work.

**Comment by bombxdev** [comment]
Try on this
[](https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome)
