### ISSUE TITLE
Event not registering

### ISSUE THREAD

**Issue by kakulukia** [buefy/buefy#663]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Chrome

### Description

Im trying to register a click event to a b-input, but its not registered and i don't know why.

Here is the code:

    section.section
      .new-item
        b-field(label="Name", @click="addItem")
          b-input(v-model="form.name", @click="addItem")
          <b-input v-model="form.name" @click="addItem"></b-input>

        input(@click="addItem")

Vue is complaining when i use a non existent handler, but only the plain input below actually has a registered click handler when examined in Chrome dev tools.
I even added an html version of the b-input to see if pug is the problem, but even there v-model work, but no registered event.
What might cause this?

<img width="602" alt="bildschirmfoto 2018-03-05 um 10 30 31" src="https://user-images.githubusercontent.com/96352/36967629-8c2ff8f4-2060-11e8-8b13-2de6aa9a235a.png">

### Steps to reproduce

Use the code above.

### Expected behavior

Being able to click on the input and execute my addItem function.

### Actual behavior

Vue is complaining about missing functions if i deliberately use wrong handler names (so its trying to register the click handler), but using the right name the click handler is not registered.
Even tried with @keyup and @keydown - same behaviour.

**Comment by adrlen** [comment]
Use `@click.native`

**Comment by kakulukia** [comment]
It looks like i missed a whole page of the docs?
Why is this necessary?

**Comment by kakulukia** [comment]
Its working, but i still like to know why i have to do this with Buefy inputs?

**Comment by adrlen** [comment]
It is not buefy related https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components

**Comment by kakulukia** [comment]
thx
