### ISSUE TITLE
is-danger icon missing when set dynamically

### ISSUE THREAD

**Issue by kakulukia** [buefy/buefy#665]
**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Chrome

### Description

Im settings the is-danger type dynamically, which works for the red styling, but the danger icon does not appear. When set as type="is-danger" rather than dynamically the icon shows up.

### Steps to reproduce

    b-field(
        label="Name", :message="form.errors.get('name')",
        :type="{'is-danger': form.errors.has('name')}")
      b-input(v-model="form.name",
        @keyup.native.enter="addItem", @keydown.native="form.errors.clear('name')")

### Expected behavior

The input should be styled in red and contain the danger icon.

### Actual behavior

The input is red, but the icon is missing.

**Comment by kakulukia** [comment]
Okay, i found a solution. When creating a property which gives back the is-danger string it works.

Is there a more elegant way to do this?

**Comment by jtommy** [comment]
@kakulukia :type="form.errors.has('name') ? 'is-danger' : '' "

**Comment by kakulukia** [comment]
thx
