### ISSUE TITLE
Validations- How to validate different buefy components.

### ISSUE THREAD

**Issue by abhinukala** [buefy/buefy#666]
**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Windows 10/ Chrome

I have a few buefy components on my form and I am trying to do the required validation. There is not much documentation around it but I have found a [jsfiddle ](https://jsfiddle.net/rafaelpimpa/y6r57k2w/)example to validate b-input which worked like charm, however, I was not able to validate other components in my form. Any examples of validating different buefy components, customizing the default error messages, multiple checkbox validation(atleast one to be selected) etc would be greatly appreciated.

**Comment by jtommy** [comment]
@abhinukala We thought about an example in extension docs section with an external library (what library we have to decide yet)

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/f933ca2c0b450534639e5714ca2645932a948f8f
