### ISSUE TITLE
b-checkbox value is always set to "false"

### ISSUE THREAD

**Issue by kcop4uk** [buefy/buefy#668]
### Overview of the problem

**Buefy** version: v0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Win10, latest Chrome

### Description

b-checkbox input value attr is always set to false

### Steps to reproduce

https://jsfiddle.net/vc4kvoLn/6/

### Expected behavior

Expecting to be able to set a value attribute of an input element

### Actual behavior

Input element value is always set to "false".

**Comment by jtommy** [comment]
@kcop4uk What do you want to do? 
I think in your case you should use native-value prop instead of value.

**Comment by kcop4uk** [comment]
My bad. You're very right.
Thanks!
