### ISSUE TITLE
Buefy table sorting

### ISSUE THREAD

**Issue by fsfj** [buefy/buefy#669]
Hello,

![image](https://user-images.githubusercontent.com/11935862/37012643-b141b79c-2130-11e8-929a-59ebe2975dcc.png)

How to remove the dropdown box?

Thanks Buefy for the great work!

**Comment by stein212** [comment]
I believe you can do that by removing the b-select element.

If that does not work then It would be great if you could post a code snippet of the your table code.

**Comment by fsfj** [comment]
Here's my code

`  <b-table :data="data"
                     :paginated="isPaginated"
                     :per-page="perPage"
                     :current-page.sync="currentPage"
                     :pagination-simple="isPaginationSimple"
                     :default-sort-direction="defaultSortDirection"
                     default-sort="first_name">

                <template slot-scope="props">
                    <b-table-column field="control_no" label="Control No." width="100" sortable>
                        {{ props.row.control_no }}
                    </b-table-column>

                    <b-table-column field="company" label="Company" sortable>
                        {{ props.row.company }}
                    </b-table-column>

                    <b-table-column field="attention" label="Attention" sortable>
                        {{ props.row.attention }}
                    </b-table-column>

                    <b-table-column field="date_letter" label="Date of Letter" sortable centered>
                        <span class="tag is-success">
                            {{ new Date(props.row.date_letter).toLocaleDateString() }}
                        </span>
                    </b-table-column>
                </template>
            </b-table>`

**Comment by jtommy** [comment]
@fsfj You cannot remove it if you your columns are sortable. You might remove all sortable props to your columns or hide it by css

**Comment by fsfj** [comment]
I will try your suggestion.  Thank you.
