### ISSUE TITLE
Switch and Checkbox custom values do not return on form submit using DataForm().

### ISSUE THREAD

**Issue by mateuswetah** [buefy/buefy#672]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Linux Ubuntu 17.10, Firefox

### Description

When wrapped inside a [DataForm](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) object, `b-switch` and `b-checkbox`  do not contain custom values for their _true_ or _false_ state. When the value is _true_, it goes as _'on'_ for `switch` and _'true'_ for `checkbox`. When the value is the _false_ option, it doesn't even come in the object (which I believe it's a default behavior for `checkbox` native element).

### Steps to reproduce

1. Wrap elements inside a `form` and use `v-on:select.prevent` to handle submit action by yourself.
2. Inside the submit handle function, instantiate a `FormData` Object, using the form element.
3. Loop trough `FormData.entries()`, to see that values are different than expected.

CodePen modified from documentation of Switch (check the console):
https://codepen.io/anon/pen/NyQPyE?editors=1011

### Expected behavior

Just like the ways values are set in the `v-model`, values from `switch `or `checkbox` should be corresponded to the `true-value` or `false-value` passed via props.

### Actual behavior

The custom values for _true_ and _false_ are not returned after submit. I know this is a VERY particular case of using a form inside Vue, but I can't use only normal `v-model` binding here to access the form data, as I'm mixing some pure-html form in my form.

**Comment by jtommy** [comment]
Fix switch https://github.com/buefy/buefy/pull/683.
You should use native-value prop for switch and checkbox but of course when value is false option you'll have any values (as native element).

**Comment by mateuswetah** [comment]
Uhmmm ok, so the false effect was expected by native and the true one didn't worked before because the native-value binding wasn't happening on switch... that makes sense, thanks :)

**Comment by cAstraea** [comment]
What about dropdowns ? I'm not getting the data for them also. Had to add a name="" for b-inputs to be able to get the value but it didn't work for b-dropdowns

**Comment by mateuswetah** [comment]
@cAstraea,  I see your point, this is probably because the `b-dropdown-item` is not made of `input` types, such as `checkboxes`, but `<a>` tags. I suggest you to open an specific issue for that, it does makes it hard to use on forms, although I would go for `select` in most cases like this.
