### ISSUE TITLE
Preventing modal close

### ISSUE THREAD

**Issue by FrEaKmAn** [buefy/buefy#673]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 0.6.2
**OS/Browser**: Chrome

### Description

I'm trying to develop a solution where user opens a modal and enters some data. If user does a mistake and accidentally closes the modal, I want to catch before close and ask him to confirm modal close. 

Checking the docs, there are no specific events for modal provided by buefy. There is beforeDestroy which is part of the Vue, but hooking into this is too late. 

Are there any options to solve this problem? Would it make sense to provide additional hooks? Like adding additional parameter to canCancel settings to call method which returns true/false? Would it make sense to override close() method?

**Comment by jtommy** [comment]
@FrEaKmAn What about `can-cancel` prop ? You might set it to false and manage close in your moda as you prefer.

**Comment by FrEaKmAn** [comment]
Yes, I ended using canCancel: [] and manually handling close. But it doesn't show close button nor it works with ESC (which I can manually add).

Still, what others think? Is this something we could add? Like a preCancel callback?

**Comment by jtommy** [comment]
@FrEaKmAn We won't add somenthing like it. You could create a Modal component that extends `bModal` or a wrapper component and add your logic as you prefer.

**Comment by FrEaKmAn** [comment]
Ok, I will do as you suggested. Thank you,
