### ISSUE TITLE
Loading component spinner not centered vertically

### ISSUE THREAD

**Issue by fjelsted** [buefy/buefy#674]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [X.X.X]
**OS/Browser**: Chrome, Windows 10

### Description

Spinner is horizontally centered but not vertically. Vertically it is centered around the spinner's top point.

### Steps to reproduce

Easiest way to see it is to go here: https://buefy.github.io/#/documentation/loading
Then zoom in 500% and press "Launch loading"

**Comment by adrlen** [comment]
It's fixed with f42665a338b442f91bd5551174e3214796bd3ac8

**Comment by fjelsted** [comment]
Sorry about that. :) I'm still new to Github. @adrlen is there any way I could have found this out myself? Like, if you found out the centering was off, what would you do? I already searched for similar issues.

**Comment by adrlen** [comment]
Hmm actually, there is no way you could have found that because I fixed it while implementing another functionality and I don't think it was ever mentioned.

It's my fault, I should have write it down in my PR then it would have appeared in your search.

**Comment by fjelsted** [comment]
Well, no harm done. Thanks for the fix. :) 👍
