### ISSUE TITLE
Could `b-taginput` be the same size with `b-input`?

### ISSUE THREAD

**Issue by GopherJ** [buefy/buefy#677]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.2]
**OS/Browser**: chrome

### Description

`b-taginput` is not the same size with `b-input`

### Steps to reproduce
```
    <b-field>
      <b-input></b-input>
      <b-input></b-input>
      <b-taginput></b-taginput>
    </b-field>
```

### Expected behavior

the same size with `b-input`

### Actual behavior

size much more big

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/481
