### ISSUE TITLE
Detailed table rows only on some rows

### ISSUE THREAD

**Issue by marianomd** [buefy/buefy#678]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.14]
**OS/Browser**: Chrome

### Description

I need some way to disable detailed rows on some rows. I tried using v-if on the detail template but that just renders an empty detail row.

### Expected behavior

The chevron-right should not appear on rows that don't have details. There should be a way to enable or disable it on each row.

Thanks!!!

**Comment by jtommy** [comment]
@wanxe What do you think about? Could it be helpful or is there a workaround to enable or disable a single row?

**Comment by wanxe** [comment]
I think I can do it by checking the value of an additional property in the input data of the table. By example: `row.detailed`. But this means that we need to make some breaking changes to create a good solid pattern for all the cases, not only for false values.
What do you think? We can make any poll here for feature requests and decide? Wait for the next mejor version?

**Comment by jtommy** [comment]
@wanxe I don't like to make assumptions on data. What do you think about a solution like `openedDetail` (`disabledDetail` in this case) or `isRowCheckable` (`hasRowDetail` for example) ?

**Comment by wanxe** [comment]
@jtommy Yes I'm with you 100%. I can do a PR to do that :)

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/682
