### ISSUE TITLE
Expanded property on select component

### ISSUE THREAD

**Issue by drmule** [buefy/buefy#680]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2]
**OS/Browser**: Win 10 home

### Description
In b-select component:

[Vue warn]: Invalid prop: type check failed for prop "expanded". Expected Boolean, got String.

### Steps to reproduce

b-select id='xx' name="xx"
                    expanded=true,
                    v-model='xx'

### Error disappears with:
b-select id='xx' name="xx"
                    is-expanded=true,
                    v-model='xx'
But component no longer expanded.

**Comment by drmule** [comment]
****

**Comment by drmule** [comment]
Chrome vue debugger reports Prop as 'expanded:"true,"'

**Comment by adrlen** [comment]
`<b-select expanded>` or <b-select :expanded="true">

**Comment by drmule** [comment]
Thanks. I am relatively new to this.

Sent from Mail for Windows 10
