### ISSUE TITLE
programmatic modal - Method "isActive" has already been defined as a data property

### ISSUE THREAD

**Issue by connor11528** [buefy/buefy#681]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.15]
**OS/Browser**: Mac/Chrome

### Description

I have a list of companies. When the user clicks on a company I'd like to show a modal with the information about that company. I'm using Laravel as a backend data source.

In **companies.blade.php** I call a list item component:

```
<ul class="menu-list">
     @foreach($companies as $company)
           <company-list-item company="{{ $company }}"></company-list-item>
      @endforeach
</ul>
```

Then in that component I have a click handler to open the modal for the company:

```
<template>
    <div>
        <li>
            <a @click.prevent="launchModal()" href>{{ companyObj.name }}</a>
        </li>
    </div>
</template>

<script>
    import { ModalProgrammatic } from 'buefy'
    import CompanyModal from './CompanyModal'

    export default {
        props: {
            company: { required: true }
        },
        data(){
            return {
                modalActive: false,
                companyObj: JSON.parse(this.company)
            }
        },
        methods: {
            launchModal(){
                ModalProgrammatic.open({
                    active: true,
                    parent: this,
                    component: CompanyModal,
                    props: {
                        companyObj: this.companyObj
                    }

                })

            }
        }
    }
</script>
```

Then in the **CompanyModal.vue** file I define the modal:

```
<template>
    <div>
        <b-modal>
            <div class="card">
                <div class="card-content">
                    <h1>{{ companyObj.name }}</h1>
                </div>
            </div>
        </b-modal>
    </div>
</template>

<script>
    export default {
        props: {
            companyObj: { required: true }
        }

    }
</script>
```

When I click the name for a company a black screen appears with an X but the modal does not show. Instead I get an error in the console: 

```
app.js:30526 [Vue warn]: Method "isActive" has already been defined as a data property.

found in

---> <BModal>
       <CompanyListItem> at resources/assets/js/components/CompanyListItem.vue
         <Root>
```
![screen shot 2018-03-11 at 11 40 56 am](https://user-images.githubusercontent.com/3578908/37257062-22daab36-2521-11e8-821e-faaeebfee951.png)

What can I change to show the modal by clicking on the company list item?

**Comment by jtommy** [comment]
@connor11528 When you use programmatically mode, you shouldn't use an other modal into your component. Try for example to remove b-modal from CompanyModal.vue.

**Comment by connor11528** [comment]
Okay but if I am rendering a list of buttons that I'd like users to click in order to render a modal (like zillow.com home search), wouldn't there be a performance hit if I duplicated the modal code in every button?

It'd be cool to render a list and when you hit the button it passes the data and renders the modal with the data that is passed into it with no need to duplicate code for the modal

Let me know if that makes sense!

**Comment by jtommy** [comment]
Ok, but you should create a only one modal component and show/hide by active prop and no programitcally

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/466

**Comment by connor11528** [comment]
This was 100% my bad. I had isActive defined somewhere else in my application. That's what was throwing things off. Thanks for your help

**Comment by saikrishna15** [comment]
> Ok, but you should create a only one modal component and show/hide by active prop and no programitcally
Does this mean we cannot use two different modals in a same component? like one as html component and other programmatically or both as html component?
