### ISSUE TITLE
Dialog cancel button doesn't indicate focus

### ISSUE THREAD

**Issue by fjelsted** [buefy/buefy#686]
### Overview of the problem

**Buefy** version: 0.6.3
**OS/Browser**: Chrome v65

### Description

The cancel button has no indication of being in focus.

### Steps to reproduce

1. Go here https://buefy.github.io/#/documentation/dialog
2. Press "Launch confirm (default)"
3. Shift-tab to focus cancel button

### Expected behavior

Cancel button should light up or something.

### Actual behavior

Cancel button does nothing.

**Comment by jtommy** [comment]
@fjelsted It's a Bulma default style, you might customize it or we could remove 'is-light' style class

**Comment by fjelsted** [comment]
@jtommy You of course are totally right. :) I will take this up with Bulma then. All buttons should have a focus indication for accessibility.

May I suggest we change 'is-light' to 'is-text'?
