### ISSUE TITLE
Dialog: Have option to set focus ['cancel', 'confirm', 'none']

### ISSUE THREAD

**Issue by fjelsted** [buefy/buefy#687]
### Overview of the problem

**Buefy** version: 0.6.3
**OS/Browser**: Chrome v65

### Description

A user quick on the keys might confirm an unintended action. On the documentation page for dialogs, the example "Launch confirm (custom)"-button in red is a dialog to delete an account. A default focus on "Delete Account" would not be my first choice.

I propose to have three options for where to place the default focus: ['cancel', 'confirm', 'none']. The option of none would mean none of the buttons are in focus such that a quick enter-press does nothing, unless the user first tabs the buttons into focus.

Thoughts?

**Comment by jtommy** [comment]
@fjelsted We could add a new prop `focus-on` but about 'none' value I think it's no possibile set focus to dialog modal.

**Comment by fjelsted** [comment]
@jtommy If 'none' isn't possible then we just leave it out. :) But a `focus-on` prop would be great. 👍
