### ISSUE TITLE
Use context menu in row

### ISSUE THREAD

**Issue by brunoosilva** [buefy/buefy#688]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome 64

### Description

Problem add action in row, because the row(`tr`) don't editable. Work with `b-table-column`, but I have to repeat in all.

For example, the plugin https://github.com/vmaimone/vue-context-menu.

Do you have suggestions ?

**Comment by jtommy** [comment]
@brunoosilva At the moment we prefer don't add any dependencies.
You could check Sortable example and use an external pure javascript library or a your implementation.
