### ISSUE TITLE
Color change when build to production

### ISSUE THREAD

**Issue by prsolucoes** [buefy/buefy#689]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.15
**OS/Browser**: ALL (chrome, safari)

### Description

When i run my project in development mode:
https://github.com/prsolucoes/gohc-web-app

Using:
```
npm install
npm run start
```

It show everything in the correct color, as describe on sass file to change bulma colors:
https://github.com/prsolucoes/gohc-web-app/blob/master/src/scss/custom-bulma.scss

Example:
![image](https://user-images.githubusercontent.com/395096/37375868-70ff7f5e-2700-11e8-96d9-b406813a947f.png)

But when i build to production using:

```
npm install
npm run build
```

I get the colors in purple. Example:

![image](https://user-images.githubusercontent.com/395096/37375906-9be14f7c-2700-11e8-82f5-32a808193116.png)

Everything that was changed on scss file appear dont have any effect.

### Steps to reproduce

```
npm install
npm run start
```

### Expected behavior

Same color on dev and prod files.

### Actual behavior

Color is different on prod files.

**Comment by mgattelli** [comment]
My 2 cents...
Do you have `import 'buefy/lib/buefy.css'` in your main.js?
If so try to remove it, as the documentation suggests. (Point 3 of this part of [doc](https://buefy.github.io/#/documentation/customization))

**Comment by prsolucoes** [comment]
Yes, i had, but removed now:

https://github.com/prsolucoes/gohc-web-app/blob/master/src/main.js

But the problem persists.

Thanks.

**Comment by jtommy** [comment]
@prsolucoes I took a look at your repository and it's ok for me. Can you confirm it ?

**Comment by prsolucoes** [comment]
I made all changes to try make it work. But dont work. The problem still happening.

**Comment by jtommy** [comment]
I have just built and it's ok. No default purple color

**Comment by prsolucoes** [comment]
Hi,

The problem in only in production "npm run build" (dist files), not on dev (npm start).

**Comment by jtommy** [comment]
Yes, I deployed it in a server and it works

**Comment by prsolucoes** [comment]
Hi, you are correct, i think that can be cache files. Sorry and thanks. Can close.
