### ISSUE TITLE
b-switch fires @input when value changes

### ISSUE THREAD

**Issue by uptownhr** [buefy/buefy#690]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome

### Description

When using the b-switch with `:value` property, the `@input` event fires when the user has not typed any text but the value provided updates. 

### Expected behavior

I would expect that the @input only fires if the user has actually interacted with the component.

### Actual behavior

@input fires without user interaction and fires when the value is changed.

**Comment by jtommy** [comment]
I have tried to replicate your issue but for me it's ok, https://codepen.io/anon/pen/yKeQxW?editors=1010. 
What's the problem ?

**Comment by adrlen** [comment]
I think that's the behavior @uptownhr is explaining :
https://codepen.io/anon/pen/XEXORY?editors=1010

Use `@click.native` instead of `@input` to fire only when the user is clicking. You might want to use `v-model` instead of `:value` to update the data accordingly to your user actions.
Also, `@click.native` fires twice at the moment but will be fix with #671

**Comment by jtommy** [comment]
@uptownhr I'm sorry in don't understand well. 
We cannot limit `input` event due its nature and @adrlen solution is ok!

**Comment by cleverplatypus** [comment]
@jtommy what uptownhr means is that the input event is supposed to fire only upon user interaction and not when the input value changes programmatically. 

https://www.w3schools.com/tags/ev_oninput.asp
> The oninput attribute fires when an element gets **user input.**
(emphasis is mine)

Adding *.native* works but it's an undesirable patch.

**Comment by jtommy** [comment]
It fixed in 0.7.1 https://github.com/buefy/buefy/commit/1a9ffa6479e78c2258dfbf7e3ecf7b4b7ecb302e
