### ISSUE TITLE
B-table does not fit the 100% of the width in IE 11

### ISSUE THREAD

**Issue by mgattelli** [buefy/buefy#692]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**: IE 11

### Description

A b-table does not fit the 100% of the width, it overflows.

### Expected behavior

The table must fit the 100% of the width

### Actual behavior

![sin titulo](https://user-images.githubusercontent.com/14174626/37416250-9215d76c-27ad-11e8-85fb-d89929a4bcca.png)

**Comment by jtommy** [comment]
Did you try `.table-wrapper { overflow: auto; }` ?

**Comment by a-kriya** [comment]
Tables display okay on IE11 for me:

![image](https://user-images.githubusercontent.com/26761352/75754163-39fffa80-5d52-11ea-9a82-1f229fe0fc11.png)

@jtommy Ticket can perhaps be closed as stale.
