### ISSUE TITLE
Disable specific checkbox in b-table when use 'checkable'

### ISSUE THREAD

**Issue by oodzchen** [buefy/buefy#693]
Now I can only check or uncheck all rows in b-table when use 'checkable'. Is there any option to disable specific checkbox in table rows?

**Comment by rcubitto** [comment]
I believe it will be possible in the next release. There's a new `is-row-checkable` prop that receives a function, and applies that function to each row to add the `disabled` attr to the checkbox.

**Comment by jtommy** [comment]
Yes, in the next release!
