### ISSUE TITLE
b-dropdown values

### ISSUE THREAD

**Issue by cAstraea** [buefy/buefy#695]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

A bit confused about the :value 
Why can I have numeric values like so 

`<b-dropdown-item :value="1">Option1</b-dropdown-item>
`
but can't have custom values like 

`<b-dropdown-item :value="myvalue">Option1</b-dropdown-item>
`

**Comment by adrlen** [comment]
`:value` is used to bind dynamic properties.

Use `value` without `:` to have a static string value.
