### ISSUE TITLE
TagInput Autocomplete with allowNew separated by comma key in russian language

### ISSUE THREAD

**Issue by ShmatkoAndrey** [buefy/buefy#696]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.4.2]
**OS/Browser**: all

### Description

1. Most problem - in russian keyboard on comma key placed one of letter, and if I write some words with this character - it separated
2. Comma on russian keyboard placed on `SHIFT + /` button

### Steps to reproduce

![test](https://user-images.githubusercontent.com/6275848/37456776-d56db0de-2848-11e8-9e6b-77eeb41d4674.gif)

### Expected behavior

Not to separated russian words with "Б/б" character

### Actual behavior

`Работа`  transforms to `Ра` `ота`

**Comment by jtommy** [comment]
@ShmatkoAndrey What about `confirm-key-codes` prop? 
You might change key codes as you prefer

**Comment by ShmatkoAndrey** [comment]
@jtommy Thanks
