### ISSUE TITLE
Feature Request: Extra options on taginput

### ISSUE THREAD

**Issue by m0ngr31** [buefy/buefy#697]
I need to be able to confirm a user wants to remove something in the tag input before it actually removes in from the list. Would be great to have a canRemove option where I can throw up the dialog and give them a prompt first.

**Comment by m0ngr31** [comment]
I was able to hack around this, but it'd still be a nice option to have.

**Comment by jtommy** [comment]
@m0ngr31 The idea is no bad, what's your hack ?

**Comment by m0ngr31** [comment]
Essentially I have 2 arrays that store the same data. If something is added, listen to the `@add` event so it's added to the other. On the `@remove` event, I fire off a dialog asking if they'd like to confirm removing that item. If they cancel: `onCancel: () => this.altArr = [...this.arr]`.

Like I said, it's a hack.
