### ISSUE TITLE
Feature request: one-way binding for form controls (vuex support)

### ISSUE THREAD

**Issue by kdekooter** [buefy/buefy#698]
Currently data is bound to form controls with the `v-model` attribute, implying two-way binding.

Vuex requires one-way binding. When `v-model` is used vuex throws the following error:
```
Error: [vuex] Do not mutate vuex store state outside mutation handlers.
```

It would be great to have one-way binding supported by the Buefy components.

**Comment by adrlen** [comment]
Use `:value` and dispatch actions with events handlers to update your store.

**Comment by adrlen** [comment]
I think your issue is with `<b-radio>` ? I just tested with `<b-checkbox>` and `<b-switch>` and don't see any problems.

For `<b-radio>` I would set a data property in the `mounted` hook with your store value and then update the store with events handlers. If your store value is set asynchronously use a watcher to set the data property. Not sure if this is the more elegant way though.

**Comment by namero999** [comment]
Is it possible to provide an example of this, please? I'd like to handle the state change myself instead of relying on `v-model`.

**Comment by kdekooter** [comment]
Maybe this could help you: https://notestack.io/public/how-to-bind-radio-buttons-to-a-vuex-store/57ae2735-80b1-4249-923a-13179d4177b4

**Comment by namero999** [comment]
Thanks for the fast reply.

This is what I'd do (and what was indeed doing) before introducing Buefy, specifically, a `b-checkbox` column in a `b-table`.

My problem is to have something like this work with `b-checkbox`. It doesn't expose the `:checked` property and `@click` events seem to be stopped.

**Comment by kdekooter** [comment]
That's right: the click event is disabled, see https://github.com/buefy/buefy/blob/dev/src/components/checkbox/CheckboxButton.vue:18. And `checked` is not exposed. 

I am afraid you need to build this component yourself...
