### ISSUE TITLE
Allow Datepicker to be set with a string value

### ISSUE THREAD

**Issue by rcubitto** [buefy/buefy#700]
**Buefy** version: 0.6.3
**Vuejs** version: 2.5.7

### Description

I was trying to seed the datepicker with a stringy date like `2018-03-19` but it is failing.

According to the docs, the `v-model` property only accepts a `Date` type. Can we extend it to also accept Strings, and use the `date-parser` to convert it to a `Date` type?

If you are interested, I could give it a try and PR a solution. Thanks.

**Comment by agriboz** [comment]
It would be great in my opinion.

**Comment by jtommy** [comment]
@rcubitto Ok, but you have to pay attention about that function because its behaviour is to parse a string from input text and the pattern could be different from a start date (for example if it's coming from a server)

**Comment by rapidexact** [comment]
Hi. Is anyone working on this feature ?

**Comment by Sillanium** [comment]
Hi. Please check my solution https://github.com/buefy/buefy/pull/744

**Comment by davidosuna1987** [comment]
Hello, I have the same problem...when I pass the date from server (Y-m-d string) I'm getting the following error: Expected Date, got String.
I don't know how to solve it.

I try to use defaultDateParser but nothing happens and I get the same error message.

I'm just a begginer with Vue and Buefy and maybe is my mistake.

Thank you!

**Comment by rapidexact** [comment]
@davidosuna1987 Hi. You should pass instance of Date object instead of string to datapicker. Dateparser function only for parsing date that user typing.

**Comment by davidosuna1987** [comment]
@rapidexact thank you for your answer. Ok then, if in my database I'm storing date with Y-m-d date format, how can I retrieve this data into datepicker component? That is my real question...

I don't know how to do this dinamically.

**Comment by davidosuna1987** [comment]
@rapidexact But when the date fields are generated dinamically (I have a contacts table and the user can add more contacts uploading a csv file), I can't use a computed property, right?

That is the reason I would like to use database string dates into datepicker component...

Any idea?

Thank you again my friend!

**Comment by davidosuna1987** [comment]
@rapidexact Unfortunately the last days I have been trying to do it but I have not succeeded. Could you give me some guidelines on how to do it?

Thanks again.

**Comment by Sztukmistrz** [comment]
maybe it will help something...
    <b-datepicker
    :value='new Date(Date.parse("{{$datetimeField['value']->format('m-d-Y')}}"))'
        editable>
    </b-datepicker>

**Comment by johnpuddephatt** [comment]
As @davidosuna1987 says it currently doesn't seem straightforward to use the datepicker in combination with data loaded from a server when inputs are created programmatically.

Looking at PR [#745](https://github.com/buefy/buefy/pull/745), I think it makes sense to have a new function rather than using dateParser for two different things.

Would that work? Is naming the function then the only barrier to implementing this? It's hard to make these names completely unambiguous but something like 'dateInitializer' might be clear enough?

I'm happy to submit a new PR if this would be helpful but want to check first in case there are other thoughts/barriers to making this happen.

**Comment by jtommy** [comment]
@johnpuddephatt can you make an example? Why should I add it in the component?

**Comment by johnpuddephatt** [comment]
I think my use case isn't too unusual, it's just generating a form programmatically based on data pulled from the server (PHP/Laravel in this case but could be anything).

On the server side I might define an array of form fields like this (just two fields here for simplicity):

```
- fields
    - name: title
      label: Title
      type: b-input
    - name: created_at
      label: Date
      type: b-datetimepicker
```

My entry data then might look like this:
```
title: Hello world
date: 2020-02-08 22:28:18
```

On the server I combine the two so I can make an AJAX request in Vue that retrieves the following:

```
    - name: title
      label: Title
      type: b-input
      value: Hello world
    - name: created_at
      label: Date
      type: b-datetimepicker
      value: 2020-02-08 22:28:18
```

In Vue I then loop through this data to create my form fields. I can either do lots of if statements (`<b-datetimepicker v-if="field.type === 'b-datetimepicker'...`) or use v-is (`<component :is="field.type"`). It doesn't make too much difference which.

Either way I would then have the attribute `v-model="form.value"`, which is great for most Buefy inputs but then I'm passing in a string to datetimepicker.

Without something like [PR745](https://github.com/buefy/buefy/pull/745) I'm not too sure how I would convert the date string into a Javascript date. Perhaps make the AJAX call, then loop through each field and if it's either datetimepicker or datetime or timepicker then find the value and replace it with `new Date(${val})` before passing the data to Vue? That sort of looping through and modifying the data doesn't feel quite right to me, what do you think?

**Comment by jtommy** [comment]
I understand your need but probably you can apply a map function on results from server and other map function when you send data to server, don't you ?

**Comment by Rinux55** [comment]
I absolutely need this too. Can work around it, but it's not very intuitive. I am persisting my Vuex store, and I am unable to store non-primitive objects in the store. Every time i would directly apply the store value to the date input, I now need to write something to parse it... This should be the responsibility of the datepicker imho.

**Comment by rjborba** [comment]
Seems like a must-have feature for a datepicker

**Comment by Sogl** [comment]
I have the same problem. +1 for this feature

**Comment by elmatou** [comment]
:+1:  This is a must have really.
for now my workaround is a computed value:
```js
  computed: {
    curatedDate: {
      get() {
        return this.date
          ? new Date(this.date)
          : this.date;
      },
      set(value) {
        this.date = value;
      },
    },
  },
```
