### ISSUE TITLE
font awesome 5 in NUXT or SSR

### ISSUE THREAD

**Issue by nikugogoi** [buefy/buefy#703]
### Overview of the problem
Use font awesome 5 in NUXT or SSR
### Description
What is the correct way to use font awesome 5 in buefy when working in NUXT or SSR?

**Comment by anteriovieira** [comment]
Hi @nikugogoi , have you tried [nuxt-buefy](https://github.com/buefy/nuxt-buefy)?

**Comment by nikugogoi** [comment]
I did it so in a plugin
**/plugins/buefy.js**
```javascript
import Vue from 'vue'
import Buefy from 'buefy'

Vue.use(Buefy, {
	defaultIconPack: 'fas'
})
```
**/nuxt.config.js**
```javascript
module.exports = {
...
plugins: [
    { src: '~/plugins/buefy' },
    ...
],
...
}
```

**Comment by anteriovieira** [comment]
Hi @nikugogoi  Yes, this is a correct way.

**Comment by nikugogoi** [comment]
But i cant seem to use font-awesome 5 as specified in the docs

**Comment by anteriovieira** [comment]
Hi @nikugogoi sorry for the delay in answering, can you tell me which icon is having a problem?

**Comment by anteriovieira** [comment]
Remembering that Font Awesome 5 icons can use [4 different styles](https://fontawesome.com/how-to-use/web-fonts-with-css#additional-styling), each with its own prefix.

Then you should change the pack property depending on the icon.

```html
<b-icon icon="bus" pack="fas" />
<b-icon icon="vuejs" pack="fab" />
<b-icon icon="bell" pack="far" />
<b-icon icon="badge" pack="fal" />
```
