### ISSUE TITLE
Auto-complete is too laggy

### ISSUE THREAD

**Issue by ashitvora** [buefy/buefy#708]
### Overview of the problem
Auto-complete is too laggy

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.16
**OS/Browser**: Windows 10 / Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Description

I have an autocomplete with data having a size of 1500+ items.
It basically an array of contacts from Google Contacts.
When I type something in the text box, there's a lot of lag. Not sure if this is a known issue or not.

**Comment by jtommy** [comment]
@ashitvora Do you show all 1500+ contacts at once ?

**Comment by ashitvora** [comment]
Nope. Only top 5. But even the text box becomes laggy.
Here's what the data looks like - https://pastebin.com/raw/9DBBLcC1

**Comment by ashitvora** [comment]
Reducing the size of data array fixed the issue.
