### ISSUE TITLE
Table sort problem

### ISSUE THREAD

**Issue by huguesjoyal** [buefy/buefy#709]
### Overview of the problem
**Buefy** version: 0.6.3

Table sorting doesn't consider accented characters.

For example :

| Sort by default  | Should have |
| -------------| -------------|
| Educateur | Educateur |
| Remboureur | Électricien |
| Électricien | Remboureur |

### Possible solution
I think that the column sorting should be using the Javascript function localeCompare.

I'm currently creating custom-sort for each field I need to support French sorting.

For example, I've created this custom function to sort my name :
```es6
nameSort(a, b, isAsc) {
    return a.name.localeCompare(b.name) * (isAsc ? 1 : -1);
}
```

**Comment by jtommy** [comment]
@huguesjoyal I don't know if the best solution and so at the moment we prefer let you free to create a custom function
