### ISSUE TITLE
Latest 0.6.4 kill ssr (nuxt) - Edit: temp quick fix

### ISSUE THREAD

**Issue by Azeranex** [buefy/buefy#712]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.16
**OS/Browser**: Chrome 64 (Windows 10)

### Description

I got error message `ReferenceError: HTMLElement is not defined` after I updated buefy to 0.6.4. Disable ssr for buefy plugin fix the issue.

### Expected behavior

Buefy working on ssr mode

### Actual behavior

Buefy not working on ssr mode

**Comment by christopherdupont** [comment]
Same issue here 👎

**Comment by feryardiant** [comment]
Same issue

**Comment by anteriovieira** [comment]
@jtommy , the error refers to this line https://github.com/buefy/buefy/blob/731793c0b15da85833d762edb2bc8f88912dfd0a/src/components/loading/Loading.vue#L21

I think we can change the type to `Function`

**Comment by anteriovieira** [comment]
@Azeranex ,  the fix will be available in the next version.  But for you to continue your tasks add this line to your file nuxt.config.js

```js
// nuxt.config.js

global.HTMLElement = typeof window === 'undefined' ? Object : window.HTMLElement

...
```

**Comment by Azeranex** [comment]
@anteriovieira Thanks :)

**Comment by ais-one** [comment]
How I got mine to work

1. Create the project

```
vue init nuxt-community/starter-template n1
```

2. Changed nuxt version in package.json from 1.0.0 to 1.4.0

3. Follow instructions for Nuxt in [https://buefy.github.io/#/documentation/start](https://buefy.github.io/#/documentation/start). Use the **simple usage** example

The nuxt-buefy version I installed is 0.0.4

4. Added the following to nuxt.config.js

```
global.HTMLElement = typeof window === 'undefined' ? Object : window.HTMLElement

module.exports = {
   ...
]
```
