### ISSUE TITLE
Select option is not selected by default

### ISSUE THREAD

**Issue by sohailalam2** [buefy/buefy#716]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.2
**OS/Browser**: Windows/Chrome

### Description

Select option with *selected* property should be set as the default option, however, this is not the case with Buefy b-select component. 

### Steps to reproduce

Demo can be found here - 

https://jsfiddle.net/50wL7mdz/224358/

```
<h1 class="has-text-weight-bold">Select using Buefy (NOT WORKING)</h1>

  <b-select required>
    <option value="flint">Flint</option>
    <option value="silver" selected>Silver</option>
  </b-select>
  
  <h1 class="has-text-weight-bold">Select using HTML (WORKING)</h1>
  
  <select placeholder="Should have default selected" required>
      <option value="flint">Flint</option>
      <option value="silver" selected>Silver</option>
  </select>
```

### Expected behavior

Should select the default option

### Actual behavior

Default option is not selected, instead its blank.

**Comment by clementvp** [comment]
Yes i can relate the same issue.
+ when you loose focus the first time, the selected value is lost and the field came back to the placeholder content.
Very annoying.

**Comment by jtommy** [comment]
@clementvp Do you use `v-model`?

**Comment by clementvp** [comment]
@jtommy Oh! My apologies. It's work well with v-model.
My bad, thank you for the quick answer :)

But, careful the demo on the select page doesn't have a v-model on the b-select and the example looks broken.

**Comment by jtommy** [comment]
Yes, we have just fixed, thanks!

**Comment by jtommy** [comment]
@sohailalam2 You should use value attribute o two way binding

**Comment by sohailalam2** [comment]
I was trying to put different values for **:value** and the **option.name** and this did not work. However, if we keep the **value** and the **name** same then it works.

Doesent work - 
```
b-select(v-model="selectedOption")
    option(v-for="option in options", :value="option.value") {{option.name}}
```

Works - 
```
b-select(v-model="selectedOption")
    option(v-for="option in options", :value="option.name") {{option.name}}
```

**Comment by jtommy** [comment]
@sohailalam2 https://codepen.io/anon/pen/qoGzXj?&editors=101. Check it, it works.

**Comment by tkaria** [comment]
I'm probably missing something - agreed that the `selected` option is working but using a model and a placeholder seems to omit the placeholder. Example here - https://codepen.io/anon/pen/QxNNGL?editors=1010 forked from above.

**Comment by jtommy** [comment]
Null is the value to show the placeholder

**Comment by tkaria** [comment]
So is there a way to have he placeholder show when there’s a model attached?

**Comment by jtommy** [comment]
Yes, the value have to be null

**Comment by Tzahile** [comment]
v-model and null property are problematic for dynamic creation of variables;

I create an object with dynamic properties (they are added on the fly according to users' choices), so I can't really give those properties null value (instead it's undefined).
I can't bind them to some default value for clear reasons.

All the options values are set in my Vue data() property, so in this case it would be better to have this 'selected' available..

**Comment by Tzahile** [comment]
I think placeholder is good also with undefined

**Comment by kwekubright** [comment]
> placeholder="Should have default selected"

Removing the v-model in my case worked. Thanks @jtommy

**Comment by kwekubright** [comment]
> @clementvp Do you use `v-model`?

Removing the v-model solve the issue in my case. Thanks @jtommy
