### ISSUE TITLE
Suggestion: Top pagination for tables

### ISSUE THREAD

**Issue by tristan-shelton** [buefy/buefy#717]
I'm using Buefy for a small project and enjoying it quite a bit, but I noticed that the table component always places the pagination below the table. It would be nice if the default were above the table or if there were on option for placing it above the table so changing from a full page to a last page with only a few items is less jarring.

I would be happy to submit a pull request if you like the idea!

**Comment by nextgensparx** [comment]
If this does get implemented, it would also be nice to allow having pagination on both the top and bottom. 

This would be especially useful for long tables. If the user knows what they are looking for is not on the current page, they can easily cycle through the pages using the top pagination. If the user is scanning a page and then reaches the bottom, they can use the bottom pagination.

**Comment by jtommy** [comment]
@tristan-shelton Ok, we'll review it!

**Comment by service-paradis** [comment]
We can close this issue (#1525)

**Comment by jtommy** [comment]
Sure, thanks
