### ISSUE TITLE
tabItem: Custom Header not rendering

### ISSUE THREAD

**Issue by aim1909** [buefy/buefy#719]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.16
**OS/Browser**: Win Server 2012 R2 / Chrome 64.0.3282.186

### Description

The example from the docs generates an empty list skeleton.

### Steps to reproduce

```Vue
<template>
    <b-tabs type="is-boxed">
        <b-tab-item>
            <template slot="header">
                <b-icon icon="information-outline" />
                <span> Issues <b-tag rounded> 3 </b-tag> </span>
            </template>
        </b-tab-item>
        <b-tab-item>
            <template slot="header">
                <b-icon icon="source-pull" />
                <span> Pull Requests <b-tag rounded> 1 </b-tag> </span>
            </template>
        </b-tab-item>
    </b-tabs>
</template>
```

### Expected behavior

![2018-03-24 11_12_57-tabs - buefy](https://user-images.githubusercontent.com/28157366/37862872-97fec914-2f54-11e8-9ea6-fadfcba1f884.png)

### Actual behavior

![2018-03-24 11_14_13-csgo-ban-checker](https://user-images.githubusercontent.com/28157366/37862873-9d780e8c-2f54-11e8-94e9-200e96238dca.png)

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/249665d2119966378222dde23422114012c1558c
