### ISSUE TITLE
[Autocomplete] input event hits on selecting an option

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [buefy/buefy#721]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.16
**OS/Browser**: Mac OS 10.13.3, Safari 11.0.3

### Description

The input event hits on every change, which is fine ofcourse. But it will also hit when it's changed by selecting an option. And there is no way to know it's not hit by the user (the event object is not given).
When you use the autocomplete feature in combination of an ajax request this is really annoying. It will always do an extra call in the end, and you will see the loader spin.

### Steps to reproduce

1. Use the autocomplete component
2. Use the input event to log to the console

### Expected behavior

Do not hit the input event on selection. Or make it an option, to not do it.

### Actual behavior

Triggers input event on selection. As you can see below, the loading spinners runs one more time in the end.

[![https://gyazo.com/94d2c4e4161083f048257f209ea220e3](https://i.gyazo.com/94d2c4e4161083f048257f209ea220e3.gif)](https://gyazo.com/94d2c4e4161083f048257f209ea220e3)

**Comment by Dylan-DutchAndBold** [comment]
Forgotten to add that, for now I have found this solution.

I added an reference to the component and added these lines to the function that does the ajax call.
```js
if (! this.$refs['autocomplete'].isActive) {
    return;
}
```

**Comment by CyrilBellotti** [comment]
We also ran into that bug .... 

First is it a bug ? or should we change the way we handle our autocomplete, I did not notice any change in the documentation about that ?

Thanks for the workaround, I'll wait a little before upgrading to 0.6.3 or 0.6.4 hoping that it's fixed upstream.

**Comment by jtommy** [comment]
I think we might change it and maybe listen an other event to load async data, for example native keyup event.

**Comment by cycle337** [comment]
okay, actually, i was using `onkeyup.native.enter` for my input event when I should've been using `onkeydown.native.enter`. now it works as expected.

**Comment by jtommy** [comment]
@cycle337 Yes i think it's the right way.  Anyway `v-model` listen input event and so this behaviour ("double") it's normal.
