### ISSUE TITLE
has-addons class disappears in <b-field> with nested controls

### ISSUE THREAD

**Issue by rhymes** [buefy/buefy#725]
### Overview of the problem

**Buefy** version: [0.6.4]
**Vuejs** version: [2.5.16]
**OS/Browser**: Mac/Chrome 65

### Description

Given a field like this:

```html
<b-field>
  <p class="control">
    <button
      title="Clear selected image"
      class="button is-warning reset"
      @click="onClearImageClick">
      <b-icon icon="close" />
    </button>
  </p>

  <b-upload
    v-model="images"
    :accept="acceptedImages"
    :loading="uploading"
    @input="onImageSelect">
    <a class="button is-info choose-image">
      <span v-if="hasImage">
        {{ imageFile().name }}
      </span>
      <span v-else>{{ text }}</span>
    </a>
  </b-upload>
</b-field>
```

Buefy 0.6.3 [according to the documentation](https://buefy.github.io/#/documentation/field) (see addons property) produced the following HTML for the outer div:

```html
<div data-v-4a151b0b="" class="field has-addons">
```

This is the visual result:

![screen shot 2018-03-25 at 1 27 16 pm](https://user-images.githubusercontent.com/146201/37874507-b2f5ac56-3030-11e8-9d61-0c0cc3e2a38f.png)

Buefy 0.6.4 for the same identical source code produces:

```html
<div data-v-4a151b0b="" class="field">
```

Notice the lack of `has-addons` which means that controls are not attached to each other anymore. This is the result:

![screen shot 2018-03-25 at 1 32 00 pm](https://user-images.githubusercontent.com/146201/37874524-efa4bd0e-3030-11e8-8344-14bbbae75b78.png)

### Steps to reproduce

I don't know how to reproduce it. I tried on jsfiddle but the behavior doesn't happen: 

* buefy 0.6.3: https://jsfiddle.net/rhymes/1v94xkom/5/
* buefy 0.6.4: https://jsfiddle.net/rhymes/1v94xkom/6/

I suspect it has something to do with this commit but I'm not sure what that commit is for at all so I can't be sure: https://github.com/buefy/buefy/pull/632

Thanks

**Comment by adrlen** [comment]
Can you share the full component and its behaviour where this issue appear ? Thanks.

**Comment by rhymes** [comment]
@adrlen sure.

https://gist.github.com/rhymes/1b0658e891956287de5aff833a7815a6

**Comment by adrlen** [comment]
Thanks @rhymes. I reproduced the bug eventually, it occurred when the $slots were rendered dynamically. I can see that's what is happening in your code.

Should be fixed in next release.
