### ISSUE TITLE
Checkable headers don't work

### ISSUE THREAD

**Issue by psweeting1** [buefy/buefy#729]
In the latest version of Buefy clicking check all in the header doesn't check all the checkables in the table. I've fixed the issue and done a pull request.

```
 isRowChecked(row) {
                return indexOf(this.newCheckedRows, row, this.customIsChecked) >= 0
            },
```

and

```
   isAllChecked() {
                const isAllChecked = this.visibleData.some(currentVisibleRow => {
                    return indexOf(this.newCheckedRows, currentVisibleRow, this.customIsChecked) < 0
                })
                return !isAllChecked
            },
```

https://github.com/buefy/buefy/pull/728

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.2]

**Comment by jtommy** [comment]
@psweeting1 Could you replicate the issue ?
