### ISSUE TITLE
[b-collapse] Font Awesome 5 Icon Not Changing

### ISSUE THREAD

**Issue by j-651** [buefy/buefy#731]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.16
**OS/Browser**: Windows 10 / Google Chrome

### Description

When collapsing/expanding a `<b-collapse>` element, the `props.isOpen` event does not change, therefore leaving the icon the same.

### Steps to reproduce

1. Add a regular `<b-collapse>` card element to a page
2. For the icon, globally set `defaultIconPack: 'fas'` and use `angle-down` and `angle-up`
3. Click the "trigger" to collapse the element.

### Expected behavior

Upon clicking the `<b-collapse>` "trigger", the `props.isOpen` event is changed and the icon updates.

### Actual behavior

The update:open event is sent when expanded AND when collapsed, so the icon does not change.

## Screenshots
![image](https://user-images.githubusercontent.com/35548468/38031205-ae57280c-3268-11e8-9988-2707082f6725.png)
![image](https://user-images.githubusercontent.com/35548468/38032638-2659ebac-326c-11e8-8cda-1bc2e52585d5.png)
![image](https://user-images.githubusercontent.com/35548468/38031545-6f93f478-3269-11e8-9b44-ff046ec12d36.png)
![buefy vue b-collapse](https://user-images.githubusercontent.com/35548468/38032455-ae4542a6-326b-11e8-9d94-2bd220c8f664.gif)

**Comment by jtommy** [comment]
@j-651 You are wrong. The slot prop is `open`.

**Comment by j-651** [comment]
@jtommy Can you provide any reason as to why the icon is not changing?  _(I'm still relatively new to Vue)_

Thank you in advance.

**Comment by jtommy** [comment]
You have to use `props.open`

**Comment by j-651** [comment]
Thank you @jtommy however it is still not working on my end, even with `props.open`.  I have also retried using the example from the Buefy site ([https://buefy.github.io/#/documentation/collapse](url)] (with the appropriate icons) but to no avail.

**Comment by jtommy** [comment]
https://codepen.io/anon/pen/OvvQoa?&editors=101
I think you didn't import FA5 correctly.

**Comment by LeonRyan** [comment]
@j-651 You are probably using the Javascript/SVG version of Font Awesome 5. There seems to be a limitation with it where you can't re inject different SVGs after render. 

The solution for this would be to render both icons on load as separate tags, and have your conditional statements to show and hide the relevant icon.
