### ISSUE TITLE
Tooltips are partly cut off within Tab-Item components.

### ISSUE THREAD

**Issue by JorgenVatle** [buefy/buefy#736]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.13
**OS/Browser**: Windows 10 - Chrome

### Description

Tooltips at the edge of a `<b-tab-item>` component get partly cut off.
[![Screenshot from Gyazo](https://gyazo.com/26d228d515f754a75adb940a5e286a93/raw)](https://gyazo.com/26d228d515f754a75adb940a5e286a93)

The issue seems to have been touched upon in the Buefy roadmap #458 
Thought I'd make this issue regardless in case it isn't yet known about.
I believe the issue can be corrected by only applying the `overflow: hidden` style to the tab item when the slide transition animation is triggered.

### Steps to reproduce

Create a Buefy tabs group, add an element with a long tooltip within a `<b-tab-item>` component.
Ex: 
```
<div class="columns">
    <div class="column is-1">
        <b-tabs>
            <b-tab-item>
                <b-tooltip position="is-left" label="A very long label to show clipping behaviour.">
                    <button type="button" class="button">Test button</button>
                </b-tooltip>
             </b-tab-item>
       </b-tabs>
   </div>
</div>
```

### Expected behavior

The tooltip should be able to exit the container.

### Actual behavior

Tooltip clips at the edge of the `<b-tab-item>` component.

**Comment by ijse** [comment]
Here is a solution that using `position:fixed`
https://codepen.io/tihoni/pen/XjpZLj

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/956

**Comment by mickorj** [comment]
i see [heyui - tooptip](https://www.heyui.top/en/component/message/tooltip) the best for solution partly cut off.
