### ISSUE TITLE
Chrome warning on b-select

### ISSUE THREAD

**Issue by onx2** [buefy/buefy#741]
### Overview of the problem

**Buefy** version: 0.6.5
**Vuejs** version: 2.5.16
**Ubuntu 16 / Chrome**:

### Description
Select field is triggering Chrome warning when opened: 
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by jtommy** [comment]
@feelslike1929 Could you provide us an example?
