### ISSUE TITLE
Infinity loop when using b-datepicker> inside v-for list with :value and @input 

### ISSUE THREAD

**Issue by gierloff** [buefy/buefy#742]
### Overview of the problem

**Buefy** version: 0.6.4
**Vuejs** version: 2.5.13
**OS/Browser**: OS X High Sierra 10.13.3 / Chrome Version 65.0.3325.181 (Officiel version) (64-bit)

### Description

Infinity loop when using b-datepicker> inside v-for list with :value and @input 

### Steps to reproduce

1. Vuex store module with array of objects.
2. Getter to get array to component.
3. V-for for displaying each object in array in component in list.
4. <b-datepicker> with :value to property of object from v-for
5. <b-datepicker> @input="value => vuexMutation(value)"

### Expected behavior

That the updated value doesn’t trigger @input or some other way to update :value without triggering a loop.

### Actual behavior

When choosing a new date, mutation updates to object in vuex store, getter gets the new value, the new value triggers @input again, thus infinity loop.

I quite new here, so please ask if you need more information!

**.vue-file:**
``` 
<template>
    <div>    
        <ul>    
            <li v-for="period in getPeriods" 
                :key="period._id">    
                <b-datepicker    
                    :readonly="false"   
                     :value="period.start"    
                    @input="value => updatePeriod({period, property: 'start', value})">    
                </b-datepicker>    
            </li>    
        </ul>    
    </div>    
</template>


<script>
import { mapGetters, mapActions } from 'vuex';

export default {
    computed: {
        ...mapGetters([
            'getPeriods',
        ])
    },
    methods: {
        ...mapActions([
            'updatePeriod'
        ])
    }
}
</script>
```

**.js-store-module file:**
``` 
const state = {
    periods: [
        {
            _id: '5a760708369a2db2862017fc',
            start: undefined
        },
        {
            _id: '5a760708369a2db2862017ac',
            start: undefined
        }
    ]
}

const mutations = {
    UPDATE_PERIOD: (state, payload) => {
        const index = state.periods.findIndex(period => period._id === payload._id);
        if (index >= 0) {
            state.periods.splice(index, 1, payload)
        }
    }
}

const actions = {
   updatePeriod: ({dispatch, commit, state, rootState}, payload) => {
        let editedPeriod = payload.period;
            editedPeriod[payload.property] = payload.value;        
        commit('UPDATE_PERIOD', editedPeriod);   
    }
}
```

**Comment by jtommy** [comment]
@gierloff I think there is an issue in your code. Try that https://codepen.io/anon/pen/VXgVdJ?&editors=101

**Comment by gierloff** [comment]
Great, I looked at it and found that my problem comes from using luxon JS... 
We rely on using Luxon JS in our application and Buefy Datepicker needs an JSDate object, which can easily be provided from an Luxon DateTime object using `.toJSDate()`. And I can easily convert an JSDate object to an Luxon DateTime object with `DateTime.fromJSDate('JSDate Object')`.

But this triggers an infinity loop. Any idea how to get around this?
[https://codepen.io/gierloff/pen/jzodpe](url) <-- triggers infinity loop when choosing date

**Comment by jtommy** [comment]
@gierloff I think because isn't the same object so for `bDatepicker` is always a new value. You should work with Date obejct and convert to DateTime when you need it.

**Comment by gierloff** [comment]
Thank you for your answer.
I noticed that the datepicker now accepts a date string (not included in 0.6.5 so yet to come. Do you reckon that when feeding a string into :value in the date picker that It will create an infinity loop as well?

**Comment by jtommy** [comment]
@gierloff No, the datepicker at the moment doesn't accept String but we're thinking about. The issue of infinity loop is because binding value (`v-model` or `:value`) change when `input` event is emitted and so for the component is always a new value.

**Comment by jboarman** [comment]
@jtommy Is there a place I can follow the status of the datepicker accepting String?

I'm running into issues trying to use the `:value` / `@input` approach, and accepting a String model would really be helpful in my current situation.

**Comment by jtommy** [comment]
No at the moment I don't think to add that feature. You have to parse your string date to Date object.
