### ISSUE TITLE
defining theme color by user

### ISSUE THREAD

**Issue by ccc159** [buefy/buefy#743]
I know it is possible to define a primary color by setting `$primary` variable.

But from my experience, once it is compiled to CSS then we lose control of this variable.

My question is, how can we change the theme color from the frontend, i.e. by javascript on the fly? Or is it fundamentally not possible?

**Comment by feelslike1929** [comment]
I'm also very interested in this functionality -- So far I can only think of refreshing the page and setting the theme in some user configuration database.

It would be great to flip between themes without any flashing or page refreshing.

**Comment by ccc159** [comment]
@feelslike1929 That would be the ideal functionality.

But even by refreshing the page I don't have any clue how to realize it. As far as I understand, **sass** is *transpiled* by webpack into CSS. So the backend can't just simply set a variable somewhere without re-transpiled through webpack, which means refreshing the page won't help in any way. Or do you have an idea?

**Comment by feelslike1929** [comment]
@ccc159 

I'm fairly new to Webpack, but is it possible to to check the user's settings prior to importing in a particular theme.sass? Doing this may allow you to refresh the page, let Webpack transpile sass again, and show the new theme. Or perhaps using the hot-loading, one can update the variables associated with the theme and it will automatically detect a change and re-transpile?

I've not looked into this too far, so I'm open to any suggestions.

**Comment by ccc159** [comment]
@feelslike1929 thanks for your answer. But webpack is something producing the whole frontend files, instead of a sort of renderer as you thought. I will try to use vanilla CSS variable which is possible to associate with javascript. But don't know how it's gonna work.

**Comment by ccc159** [comment]
@jtommy Could you give a hint how we can achieve this?

**Comment by jtommy** [comment]
@ccc159 It's not possible change a variable in Javascript. You should change all occurrences about that variable in the css but it's quite heavy.

**Comment by ccc159** [comment]
@jtommy I see. So I will close the issue. Thanks!
