### ISSUE TITLE
DatePicker returns wrong date

### ISSUE THREAD

**Issue by jrpruitt** [buefy/buefy#746]
I really love how easy it is to select a date on your DatePicker, but in testing it on your doc page, I see it sometimes returns a wrong value.
https://buefy.github.io/#/documentation/datepicker
When I select 11/04/1968, it is correct, but any earlier date returns one day prior to what was selected.
11/03/1968 returns 11/02/1968 (at least that's what I'm seeing in the date box after I click the 3rd).

**Comment by jrpruitt** [comment]
Ok, I've verified it fails on both Chrome and Firefox in Windows, but on Linux Mint, it only fails (at that date point) in Chrome.  On Firefox, it starts failing at 04/24/1955 and earlier dates.

**Comment by natxocc** [comment]
The same in my case. I confirm this.

**Comment by jtommy** [comment]
Thanks. We'll try an other way to format a Date without any external library dependency

**Comment by jlsneto** [comment]
When will it become available?
