### ISSUE TITLE
b-upload shows input next to button

### ISSUE THREAD

**Issue by Kawue** [buefy/buefy#747]
Buefy version: 0.6.5
Vuejs version: 2.5.16
Win10 / Firefox 59.0.2

Instead of appearing overlapping the input button appears right next to ne upload button.

![grafik](https://user-images.githubusercontent.com/18120038/38317259-e8c86a86-382c-11e8-96f6-378b4a387c49.png)

**Comment by jtommy** [comment]
@Kawue Did you import Buefy style (css or scss) ?

**Comment by Kawue** [comment]
Oh man ... that was dumb. Totally forgot about this part.

Thanks for your help.
