### ISSUE TITLE
Used Vee-Validate with buefy for form validations and it worked well. Trying to minimize the redundant code written on each form element to do basic validation. 

### ISSUE THREAD

**Issue by abhinukala** [buefy/buefy#748]
**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.2]
**OS/Browser**: Windows/Chrome

### Description

Currently using vee-validate to do basic validation of forms. 
![code](https://user-images.githubusercontent.com/31191435/38333366-6712b5f6-3826-11e8-8b76-0ab5700786d0.PNG)

![text](https://user-images.githubusercontent.com/31191435/38332869-026e72bc-3825-11e8-9fe6-a7dd5bfd40d4.PNG)
The above code works perfectly fine. But the problem is the code to display the error message has to be written on every field which I want to avoid. 

Is there any way that I could achieve the same functionality using a simpler code. For Eg:
![code1](https://user-images.githubusercontent.com/31191435/38333413-8dd0016c-3826-11e8-976a-8df56970fc23.PNG)
I could customize b-input and wrap b-field around it to display the label. My question is how do I customize the validation part so I don't have to write it for every field and just giving the 'name' and v-validate="'required'" should achieve what I am able to do now. 

Bdw awesome work with the plugin. :-)

**Comment by jtommy** [comment]
@abhinukala I think there is no general solution. You should create a your input+field wrapper component.
