### ISSUE TITLE
accept attribute is not processed in drag & drop (upload field)

### ISSUE THREAD

**Issue by aquaminer** [buefy/buefy#750]
### Overview of the problem

**Buefy** version: last
**Vuejs** version: last
**OS/Browser**: Linux (Vivaldi)
### Description

accept attribute is not processed in drag and drop 
if you click on the field and select a file, you can not choose another, but if through drag and drop it accepts any files

```
        <b-upload v-model="dropFiles" drag-drop accept=".phar,.zip" @input="uploadFile()">
            <section class="section">
                <div class="content has-text-centered">
                    <p>
                    <b-icon
                        icon="upload"
                        size="is-large">
                    </b-icon>
                    </p>
                    <p>Drop plugin here or click to upload</p>
                </div>
            </section>
        </b-upload>
```

**Comment by jtommy** [comment]
@aquaminer What means "it accept any files"
Are they added into the array ?

**Comment by aquaminer** [comment]
@jtommy what array are you talking about? the file appears in the dropFiles array

**Comment by jtommy** [comment]
@aquaminer  I tryed your code and the array (drop files) is always 0 when the dragged files are not valid

**Comment by aquaminer** [comment]
@jtommy sorry, I made a mistake, sorry for wasting your time
