### ISSUE TITLE
BTimepicker with Clock

### ISSUE THREAD

**Issue by SharpSeeEr** [buefy/buefy#753]
### Overview of the problem

**Buefy** version: 0.6.5
**Vuejs** version: 2.5.13
**OS/Browser**: Windows 10/Chrome 65.0.3325.181

### Description

Would you be open to implementing a timepicker with a clock interface rather than number dropdowns?  Something like this:
![image](https://user-images.githubusercontent.com/4459909/38520763-f4665556-3c00-11e8-9e60-68eddf94bc81.png)
![image](https://user-images.githubusercontent.com/4459909/38520796-0b3386dc-3c01-11e8-8cbc-5c68c018fbe6.png)

(Images captured from [Vuetify.js Docs](https://vuetifyjs.com/en/components/time-pickers))

I have already been working on it for my own use, but would love to have it included in buefy.  If so I'll finish it up as a buefy component in my fork.

**Comment by SharpSeeEr** [comment]
My initial effort is committed on my fork in a clockpicker branch:
[Buefy Clockpicker](https://github.com/SharpSeeEr/buefy/tree/clockpicker)

Screen shot from the docs:
![image](https://user-images.githubusercontent.com/4459909/38649629-fc5056f8-3db4-11e8-8dcd-a303f9902549.png)

Inline:
![image](https://user-images.githubusercontent.com/4459909/38649691-63e0b6be-3db5-11e8-93e9-e91a58e93aef.png)

**Comment by rafaelpimpa** [comment]
@SharpSeeEr I like that! Mind creating a PR?

**Comment by SharpSeeEr** [comment]
Not at all!  I am still working on getting support for colors - `is-primary`, `is-info`, etc, and can create a pull request as is or after I get that in, whichever you prefer.

**Comment by rafaelpimpa** [comment]
Submit when you feel it's ready :) thanks a lot

**Comment by Ansty93** [comment]
Any update on this issue? I would rather to use a clockpicker on desktop version instead of dropdown.

**Comment by jtommy** [comment]
@Ansty93 I'll try to reuse the PR to add clockpicker

**Comment by SharpSeeEr** [comment]
@Ansty93 @jtommy I'll update the PR to the latest.  Maybe tonight, probably tomorrow (3/27).

**Comment by Ansty93** [comment]
@SharpSeeEr Sweet! Iam really looking forward to it

**Comment by SharpSeeEr** [comment]
I have updated the pull request - it's up to date with dev now.
