### ISSUE TITLE
Tooltip cut off when horizontal scrolling

### ISSUE THREAD

**Issue by carlosdevpereira** [buefy/buefy#754]
**Overview of the problem**
Buefy version: 0.6.5
Vuejs version: 2.5.13
OS/Browser: Windows 10/Chrome 65.0.3325.181

**Description**
When adding more columns to the table component, the table will start scrolling horizontally for responsive purposes. Within this scroll the tooltips of the table get cut off.
![tooltip bug](https://user-images.githubusercontent.com/24235108/38612632-40395abc-3d7f-11e8-8369-5ff6aaf53fb1.png)
(Image captured from codepen preview.)

**CodePen**
https://codepen.io/anon/pen/JLzvRq?editors=1010

**Comment by sammerro** [comment]
There is a hack for that: 
`.table-wrapper {
    padding-top: 4rem;
    margin-top: -4rem;
}`
in your stylesheet
