### ISSUE TITLE
[req] horizontal b-collapse

### ISSUE THREAD

**Issue by gardnerluke** [buefy/buefy#761]
Hi,

is it possible to add a horizontal b-collapse? I'd love to use the component as collapsible side nav.
Can't get my tries to work with a redraw.

If it's too much of a hassle no worries.

Cheers

**Comment by jtommy** [comment]
@gardnerluke No, it isn't possible.

**Comment by grebebird** [comment]
This would be awesome though - was thinking of something similar recently.
