### ISSUE TITLE
Autocomplete open-on-focus and !hasEmptySlot shows empty dropdown box

### ISSUE THREAD

**Issue by xpuu** [buefy/buefy#763]
### Overview of the problem

**Buefy** version: [0.6.5]
**Vuejs** version: [2.5.16]
**OS/Browser**: Every

### Description

Dropdown should be gone when !hasEmptySlot even while it has focus.

### Steps to reproduce

1. open-on-focus is true
2. "Empty" slot is not assigned.
3. Autocomplete field contains text, which can't be found in data. 

### Expected behavior

Dropdown menu will be hidden.

![right](https://user-images.githubusercontent.com/3930177/38754029-8f81b0d2-3f60-11e8-9c99-96116c09db81.png)

### Actual behavior

Blank remnants of dropdown menu are there, covering other controls.

![wrong](https://user-images.githubusercontent.com/3930177/38754030-8f9f7f9a-3f60-11e8-8320-6c7e939746f4.png)

**Comment by jtommy** [comment]
@xpuu What means _"Empty" slot is not assigned._ ?
In your last screenshot I think you're using `empty` slot without content.

**Comment by xpuu** [comment]
Sorry for false alarm. Can't reproduce it now. Seems it was a result of some invalid hot-reload. After I restarted webpack-devserver and reloaded whole page, problem is gone. Closing the issue now.
