### ISSUE TITLE
get tabitem 's isActive value

### ISSUE THREAD

**Issue by dfy167** [buefy/buefy#764]
i want to watch isActive value in tab . how can i to get i work.
1. ref  ugly
2. event TabItem have no event
3. ? is there any smooth way ?

**Comment by jtommy** [comment]
@dfy167 Why do you want to watch internal `isActive` ? You might use `v-model` of `bTabs` component.

**Comment by dfy167** [comment]
@jtommy 
there are some charts components in TabItem  and width is not fix.
i want to redraw then when this TabItem  is isactive

**Comment by jtommy** [comment]
I think my solution is ok for you, isn't it ? You might listen `input` event on `bTabs` or watch the property that you are binding by `v-model`.

**Comment by dfy167** [comment]
watch the property that you are binding by v-model
