### ISSUE TITLE
about taginput

### ISSUE THREAD

**Issue by vortechron** [buefy/buefy#765]
when i click/choose a tag from snippet suggestion, the snippet suggestion seems to auto close, is there any way to make snippet suggestion stay open even after i choose a tag? i dont want to start retype and make an api call to make snippet suggestion appear again...

**Comment by vortechron** [comment]
up

**Comment by service-paradis** [comment]
Should work if using `autocomplete` and `openOnFocus` (https://buefy.org/documentation/taginput#autocomplete)
