### ISSUE TITLE
Datepicker in Modal form showing Invalid prop: type check failed for prop "dateFormatter". Expected Function, got String

### ISSUE THREAD

**Issue by tanhs** [buefy/buefy#766]
### Overview of the problem

Buefy version: [5.6.0]
Vuejs version: [5.6.0]
OS/Browser: Chrome:

### Description
Getting error "Invalid prop: type check failed for prop "dateFormatter". Expected Function, got String."

### Steps to reproduce
    dateoptions = { year: 'numeric', month: 'short', day: 'numeric' };

    const ModalForm = {
        props: ['startDate', 'hasCounter', 'minDate', 'maxDate', 'dateFormatter'],
        template: `
            <form action="">
                <div class="modal-card" style="width: auto">
                    <header class="modal-card-head">
                        <p class="modal-card-title">Clinical Details</p>
                    </header>
                    <section class="modal-card-body">
                        <b-field label="Datetime" horizontal>
                          <b-datepicker
                              placeholder="Click to select..."
                              icon="calendar-today"
                              :min-date="minDate"
                              :max-date="maxDate"
                              :date-formatter="dateFormatter"
                              >
                          </b-datepicker>

            <b-field grouped group-multiline>
              <button id="btnAdd" class="button is-success" @click="isComponentModalActive = true">Add</button>

              <b-modal :active.sync="isComponentModalActive" has-modal-card>
                  <modal-form v-bind="formProps"></modal-form>
              </b-modal>
            </b-field>  

### Expected behavior
Able to show dd-MMM-YYYY

**Comment by jtommy** [comment]
@tanhs `dateFormatter` prop has to be a Function. It formats a Date Object to string
