### ISSUE TITLE
DatePicker Component weird default behaviour

### ISSUE THREAD

**Issue by pkganthali** [buefy/buefy#773]
In the Datepicker component `<b-datepicker>`

If we key in a 3 digit number like `786 `and tabs out, it auto populates with the value `1/1/786`

Similarly If we key in a 4 digit number like `2017 `and tabs out, it auto populates with the value `12/31/2016`

Why is this inconsistency in choosing between `12/31/{4-digit-year}` and `1/1/{3-digit-year}`?

**Comment by jtommy** [comment]
@pkganthali Default `date-parse` prop use `Date.parse()` function so please check docs https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Date/parse.
You should define a your function to parse string to date as `date-parse` prop

**Comment by pkganthali** [comment]
I am not able to understand how to modify the dafault parsing done by Buefy datepicker component.

Can You please share any code sample if you have..

**Comment by jtommy** [comment]
https://codepen.io/anon/pen/XqKBNb?editors=1010
It's a very simple example and you might add that function to [global options ](https://buefy.github.io/#/documentation/constructor-options). Furthermore you should add a `date-formatter` method to have a correct and same behaviour for your locale.
