### ISSUE TITLE
Can i hide arrow icon in table detail or change icon type to Fontawesome ?

### ISSUE THREAD

**Issue by biigpongsatorn** [buefy/buefy#776]
### Overview of the problem

**Buefy** version: [0.6.5]
**Vuejs** version: [2.5.2]
**OS/Browser**: Google Chrome

### Description

Can i hide arrow icon in table detail or change icon type to Fontawesome ?

Now my icon type is `Fontawesome` but default of arrow icon in table detail feature is `mdi`, Can i change arrow icon type to `fa` or hide it ?

![image](https://user-images.githubusercontent.com/10693658/39084968-099a0ee0-45a7-11e8-88c2-b94c72a5d0e4.png)

My code.
```

<b-table ref="table" :data="onGoingMatchs" :hoverable="true" :detailed="true" class="cs-pointer" detail-key="id" @select="expandRow" :opened-detailed="openedDetailed">

.
.
.

<template slot="detail" slot-scope="props">
     <article class="media">{{ props.row }}</article>
</template>

</b-table>

```

Thanks.

**Comment by wanxe** [comment]
You can hide the icon in certain rows by the prop `has-detailed-visible`. Check the documentation to see more.

But if you want hide all the icons, why use detailed prop?

**Comment by biigpongsatorn** [comment]
@wanxe  I want to expand each row but I don't know how to set arrow icon type to `fa`. So i want to hide it.

**Comment by biigpongsatorn** [comment]
I mean I want to hide column of arrow icon.

**Comment by biigpongsatorn** [comment]
Example

```html

<template>

<b-table :data="data" :detailed="true" detail-key="id" @select="expandRow" :opened-detailed="openedDetailed" :bordered="true" :has-detailed-visible="() => false">
.
.
.
<template slot="detail" slot-scope="props">
    <article class="media">ID : {{ props.row.id }}</article>
</template>

<b-table/>

</template>

<script>
export default {
  data () {
    return {
      openedDetailed: []
    }
  },
  methods: {
    expandRow (row) {
      this.openedDetailed = []
      this.openedDetailed.push(row.id)
    }
  }
}
</script>

```

Result
![image](https://user-images.githubusercontent.com/10693658/39087370-4cfa7274-45ca-11e8-95b5-cb9434eab756.png)

**Comment by wanxe** [comment]
Hmmm the example worked to me... 
In this codepen I'm using fontawesome:
[https://codepen.io/jnieto/pen/bMVwer](Example)

Feel free to change between to see that it works `mdi, fa, fas, far, fad`.

**Comment by biigpongsatorn** [comment]
@wanxe  OK thank you very much, I will try again. 🙂

**Comment by msonowal** [comment]
@wanxe 
@biigpongsatorn 
Can you share the code sample as the link is broken I also want to customize that?

**Comment by wanxe** [comment]
Hello @msonowal. The prop just accept a function that evaluates each row.

````handleDetailed (user) {
      return user.id !== 1;
    }`

**Comment by EmadBrown** [comment]
Hello @biigpongsatorn ,
I had the same problem. I solved by adding a class to the target row like below: 
You can check (buefy Table  properties).  
`<b-table
        :data="data"
        :columns="columns"
        :row-class="(row, index) => row.yourValue != 0 ? '': 'hide-arrow-icon-detail'">
 </b-table>

<style>
	.hide-arrow-icon-detail a[role='button'] {
		display: none;
	}
</style>
`
**row-class | Add a class to row (<tr> element) based on the return | Function (row: Object, index: Number)** 
[](https://buefy.github.io/#/documentation/table)
I hope it works 👍

**Comment by biigpongsatorn** [comment]
Hello @EmadBrown .

![image](https://user-images.githubusercontent.com/10693658/44310637-d75f3c00-a403-11e8-9543-3ec77293270e.png)

Actually i want to hide column of arrow, I just want to use collapse feature of `b-table`.
Now i solved this issue by use [b-collapse](https://buefy.github.io/#/documentation/collapse).
Thanks for your nice suggestion 🙂 .
