### ISSUE TITLE
Unable to set position="is-bottom-left" on dropdown

### ISSUE THREAD

**Issue by wellcaffeinated** [buefy/buefy#777]
### Overview of the problem

**Buefy** version: [0.6.5]
**Vuejs** version: [2.x]
**OS/Browser**:

### Description

Setting `position="is-bottom-left"` appears to have no effect on position of dropdown content.

**Comment by jtommy** [comment]
@wellcaffeinated It is the default position

**Comment by wellcaffeinated** [comment]
Sorry i meant "is-bottom-left". The positions aren't actually being applied. I've had to use css overrides.

**Comment by jtommy** [comment]
@wellcaffeinated https://codepen.io/anon/pen/NMxwex?&editors=101, what's it wrong ?

**Comment by wellcaffeinated** [comment]
Ahhh my mistake.
I was injecting bulma.scss directly instead of including it via buefy.css
Thanks
