### ISSUE TITLE
Taginput validation

### ISSUE THREAD

**Issue by GarethTIGFreight** [buefy/buefy#778]
### Overview of the problem

**Buefy** version: [0.6.5]
**Vuejs** version: [2.5.13]
**OS/Browser**: all

### Description
Taginput does not accept "required".

### Steps to reproduce
`<b-tag-input :required='true'>...</b-tag-input>`
Click into input then trigger native HTML 5 form validation (e.g. clicking off the input or hitting submit within a form).

### Expected behavior
The TagInput should replicate a select multiples parameters and the required field should trigger a browser validation messages.
`<select multiple required>...</select>`

### Actual behavior
No validation is triggered. Form submits without input.

### Solution
As this is a pseudo form input it's not simple.

We would insert a native input and have validation on that but I think it would be hacky.

Alternatively there is this.. [setCustomValidity](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Constraint_API%27s_element.setCustomValidity())

**Comment by jtommy** [comment]
@GarethTIGFreight I think it's no simple and we're avoiding add specifc validation into components.

**Comment by carloditan24** [comment]
Is there a way wherein an integrated VeeValidate can solve this issue?
