### ISSUE TITLE
Feature suggestiong

### ISSUE THREAD

**Issue by StanislavBerezin** [buefy/buefy#779]
I was thinking that it would be cool to have a ready to go navbar in buefy framework. I see that there are some stuff provided by bulma but its not really adapted to vuejs and requires you to create everything urself.
Here is the fine example, https://jsfiddle.net/tbonz/80jkq0Ls/  thought it would be nice if something like that included in your docs under navbar section

**Comment by jtommy** [comment]
@StanislavBerezin Navbar component is already in the [roadmap](https://github.com/buefy/buefy/issues/458). Stay tuned!
