### ISSUE TITLE
Update Bulma to 0.7.0

### ISSUE THREAD

**Issue by acidduck** [buefy/buefy#780]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.2]

### Description

I need to work with $card-header-background-color, $card-content-background-color and $card-footer-background-color that was added in Bulma 0.7.0. In general a lot has happened since Bulma 0.6.2.

**Comment by RumbleFrog** [comment]
So like this commit? https://github.com/buefy/buefy/commit/1a3794801a9a12525db00568eeff14f43c12c3da

**Comment by acidduck** [comment]
Oh great, didn't see that one. :-) But it hasn't been released yet, right?

**Comment by RumbleFrog** [comment]
Yeah, not yet.

**Comment by itsmatteomanf** [comment]
Any update on this?

**Comment by dinhngocvuong** [comment]
0.7.1 please

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/d869b4db97193ca9522563f4ca727e0fe16834d8
