### ISSUE TITLE
v-model date picker

### ISSUE THREAD

**Issue by BigWillie** [buefy/buefy#782]
When setting v-model on the date picker

`                <b-field label="Start Date">
                    <b-datepicker v-model="filters.startDate" placeholder="Start date..."  :max-date="maxDate"></b-datepicker>
                </b-field>`

In my app, use of the date picker is optional. However, the datepicker expects a date Object to exist on v-model. I can't have an empty v-model (empty string, null, false etc)

The ability to have an empty string on v-model would solve this.

**Comment by jtommy** [comment]
@BigWillie You have to set null your data.

**Comment by BigWillie** [comment]
I tried that before posting the issue... it didn't work... 

Only it does work. I needed to restart node... sorry... no issue here 👍 thanks
