### ISSUE TITLE
B-Select component placeholder doesnt display when v-model property is added to component

### ISSUE THREAD

**Issue by Olusiji** [buefy/buefy#784]
### Overview of the problem

**Buefy** version: [0.6.5]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome

### Description

The **placeholder** doesn't display in the **Select** component when there's a v-model property added to it 

### Steps to reproduce

1. First Step
Create a b-field component with a placeholder property
2. Second Step
Add a v-model property binding the selected option with the state
3. Third Step
Populate the select options using v-for
4. Fourth Step
View your component in the DOM. Placeholder doesn't show but everything else works fine.

### Code Sample
```
<b-field label="Select a Product" class="column">
     <b-select placeholder="Select" @change="switchOptions" v-model="product" expanded>
          <option v-for="product in products" :key="product.id"> {{ product.name  }</option>
    </b-select>
</b-field>
```

### Expected behaviour
The Placeholder specified for the Option component should show in the browser

### Actual behavior
The placeholder only shows when the v-model attribute is `removed`

**Comment by jtommy** [comment]
@Olusiji It works but `v-model` value has to be `null`.

**Comment by Olusiji** [comment]
Alright. Please is there another way I can bind the  selected value of the `b-select` component to a state variable if I have to set `v-model` to be `null`

**Comment by jtommy** [comment]
No. Why do you need to change default value of placeholder option?

**Comment by Olusiji** [comment]
I'm not sure I understand your question. I'd like to use a placeholder to guide the users of my app. Like I explained earlier when I use the component with a v-model binding selected option to the state the placeholder doesn't display at all. 
This is my code. am I doing something wrong?
```
<b-field label="Select a Product" class="column is-5" v-if=" selectedVendor != ''  ">
        <b-select placeholder="Select"  @change="switchOptions" v-model="product" expanded>
             <option v-for="product in products"
                            :value="product"
                            :key="product.id">
                            {{ product.name  }}
              </option>
       </b-select>
 </b-field>
```

**Comment by jtommy** [comment]
You have to set `null` value to `product`.

**Comment by ming-tsai** [comment]
Hi,
I got the error of Ventur, I'm using Typescript with Vue.
![image](https://user-images.githubusercontent.com/37890026/84334703-027ac880-ab61-11ea-9fc5-f440ddd71eb7.png)

**Comment by service-paradis** [comment]
@ming-tsai 
try:
`public selectedSecond: string | null = null;`

**Comment by ming-tsai** [comment]
@service-paradis thanks, its work.
