### ISSUE TITLE
File to import not found or unreadable: ~bulma.

### ISSUE THREAD

**Issue by Armanoide** [buefy/buefy#785]
Hi,

The customization [documentation](https://buefy.github.io/#/documentation/customization) about scss has wrong import about bulma causing:
 `File to import not found or unreadable: ~bulma.`

wrong:
```
// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
right: 
```
// Import Bulma and Buefy styles
@import "~bulma/bulma";
@import "~buefy/src/scss/buefy";
```

**Comment by jazoom** [comment]
Thanks mate. You just saved me some period of extended headache.

**Comment by jtommy** [comment]
@Armanoide What Bulma version are you using ?

**Comment by jazoom** [comment]
I can't speak for OP but mine was what automatically downloaded from NPM as the latest `nuxt-buefy`, (0.04) which has as its dependencies:

```
buefy@latest:
  version "0.6.5"
  resolved "https://registry.yarnpkg.com/buefy/-/buefy-0.6.5.tgz#84e76e9101085dbbc84e66e755aff75030078553"
  dependencies:
    bulma "^0.6.2"
```

**Comment by jtommy** [comment]
Are you using nuxt-buefy ?

**Comment by jazoom** [comment]
Yes
