### ISSUE TITLE
Feature request: Arbitary columns to tables

### ISSUE THREAD

**Issue by BigWillie** [buefy/buefy#786]
I need to add a custom button to the end of each row in my table.

This can be achieved very easily with a slot

```
<template slot-scope="props">
                <b-table-column field="editbutton" label="Edit" width="40" numeric>
                  <button>Edit</button>
                </b-table-column>
</template>
```

However, this doesn't work with dynamic data and dynamic columns. So I'm manipulating my data set so it includes a button. This feels kinda clunky.... it would be nice to be able to insert a column where needed.

**Comment by BigWillie** [comment]
ah... that doesn't work... The button I add via the data doesn't work. Any methods I attach are ignored

**Comment by BigWillie** [comment]
```
        <b-table :data="data">
          <template slot-scope="props">
            <template v-for="col in columns">
                <b-table-column  :field="col.field" :label="col.label">
                  {{ props.row[col.field] }}
                </b-table-column>
            </template>
            <b-table-column field="edit" custom-key="edit">
              <button v-on:click="editBttn()">Edit</button>
            </b-table-column>
          </template>
        </b-table>
```

columns is a computed property - I loop over the first Obj in the data array extracting the keys.

I then loop through the columns array (col in columns) to build out each slot... I then stick a slot on the end with the edit button. This works. So this feature request can be scrubbed. Might be useful to have this type of thing in the examples however,

**Comment by jtommy** [comment]
@BigWillie Yes it's the only way at the moment
