### ISSUE TITLE
Writing a generic wrapper to buefy tabs in VueJS

### ISSUE THREAD

**Issue by pkganthali** [buefy/buefy#793]
Not able to inject nested components(contents of b-tab-item) instance dynamically in the parent(b-tabs).
Facing this issue while trying to create a wrapper(Custom component) that models a buefy tabs/tabItems.

`Not able to push the right tab contents inside the <b-tab-item> dynamically.`

Usage(Wrapper):

```
<tabs>
    <tab label="Tab A">
        <label>First Name</label><input type="text" name="fName" />
    </tab>
    <tab label="Tab B">
        <label>Last Name</label><input type="text" name="lName" />
    </tab>
  </tabs>
```
Expected Output:
```
<b-tabs>
    <b-tab-item label="Tab A">
      <label>First Name</label>
      <input type="text" name="fName" />
    </b-tab-item>
    <b-tab-item label="Tab B">
      <label>Last Name</label>
      <input type="text" name="lName" />
    </b-tab-item>
  </b-tabs>
```
Whatever I have tried so far is in the Jsfiddle link below:
https://jsfiddle.net/nataraj_gnanavadivel/7bfxx9we/6/

**Comment by jtommy** [comment]
@pkganthali I think it's no easy because tabs components is "quite" complex component too
