### ISSUE TITLE
[QUESTION] how can I add a custom directive to a b-input ?

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#796]
### Description

How can I add a custom directive to **b-input** ? Because **b-input** is wrapped with a **div**, when I add a custom directive it goes on the **div** and not on the **input**.

Is there anyway to solve this ? It for a placeholder animation with typed.js but this use case could also be for : 
- auto-focus directive
- google analytis directive
- placeholder animation...

**Comment by jtommy** [comment]
@darkylmnx You have to select the inner input. Look this example https://buefy.github.io/#/extensions/cleavejs

**Comment by darkylmnx** [comment]
@jtommy that works when you create your own but I meant if I use a package that has a custom directive how do I do
