### ISSUE TITLE
Timepicker in inline mode and is-* field type doesn't work

### ISSUE THREAD

**Issue by daividh** [buefy/buefy#797]
### Overview of the problem

**Buefy** version: [0.6.5]
**Vuejs** version: [0.6.2]
**OS/Browser**: Chrome latest version / Firefox latest version

### Description

When using Timepicker in inline mode, field type is ignored

```
<div id="app">
  <!-- work as expected -->
  <b-field label="Heure de début*"
           :type="'is-danger'">
    <b-timepicker inline />
  </b-field>

    <!-- does not work -->
    <b-field label="Heure de début*"
             :type="'is-danger'">
    <b-timepicker />
  </b-field>
</div>
```

### Steps to reproduce

[See JSFiddle](https://jsfiddle.net/0y3mym4k/2/)

### Expected behavior

Field type not ignored when inline mode

### Actual behavior

Field type ignored when inline mode

**Comment by jtommy** [comment]
@daividh `type` prop is added only when input is visible.

**Comment by daividh** [comment]
Oh ! Understand !
Thanks for anwering.
So may be a feature request ?

**Comment by jtommy** [comment]
At the moment no, but you might customize you it adding a your class
