### ISSUE TITLE
Add components from bulma-extensions

### ISSUE THREAD

**Issue by ishitatsuyuki** [buefy/buefy#809]
### Description

[Bulma-Extensions](https://wikiki.github.io) are a set of additional components complementary to Bulma.

Direct use of it in Vue isn't ideal, because:

- You have to use the DOM manipulation based scripts
- You have to manually apply classes, which are different from what we do with Vue components

The good way here would be probably reusing only the CSS then reexport Vue components based on them.

**Comment by renemendoza** [comment]
this would greatly expand buefy components offering!

**Comment by renemendoza** [comment]
To use bulma-extensions bulma-steps i did this
```vue
<script>
import StepsWizard from 'bulma-steps/steps.js'
export default {
data: function() {
return {}
},
mounted() {
new StepsWizard( document.getElementById('stepsDemo') );
}
</script>
<style lang="css">
@import 'bulma-steps/bulma-steps.min.css'
</style>
```

**Comment by ambrt** [comment]
I second @ishitatsuyuki , it would be nice to have all extensions

**Comment by rakibulhaq** [comment]
thanks to @renemendoza i was having a problem with adding js in component level.

**Comment by kaankilic** [comment]
Would be great If there is an official way to import those extensions.

**Comment by service-paradis** [comment]
A first version have been added for Steps (based on Bulma Steps) in the latest Buefy release:
https://buefy.org/documentation/steps

**Comment by jtommy** [comment]
I think it's better rewrite in a Vue component and Steps is enough at the moment.
