### ISSUE TITLE
Tabs: option to disable headers

### ISSUE THREAD

**Issue by verdie-g** [buefy/buefy#810]
Hi,

I'm building a component that uses buefy tabs and I would like to navigate between them by clicking in buttons inside tab items. Therefore I don't need tab headers, and I would need an option to disable them.

My current workaround is the following:

```css
.tabs {
  display: none;
}
```

The option would be used like that:
```vue
<b-tabs v-model="activeTab" no-headers>
</b-tabs>
```
On _b-tabs_ or _b-tab-item_.

If you like the idea, I can create a pull request.

**Comment by jtommy** [comment]
@verdie-g Why tabs without headers ? An example ?

**Comment by verdie-g** [comment]
Take a look at this site : [https://www.welcometothejungle.co/jobs](https://www.welcometothejungle.co/jobs)

In the search panel (Univers - Contrat - ...), if you click on professions there is a dropdown. Inside, there is some kind of a tabs system, where each item will move you to a tab on click.

I don't think it is something possible to do with the custom headers of buefy 0.6.4. So I made a b-tabs with a b-tab-item for the headers and several b-tab-items for the tabs.

```vue
<b-tabs>
  <b-tab-item>
    <ul>
      <li>Admin</li>
      <li>Business</li>
      <!-- ... -->
    </ul>
  </b-tab-item>

  <b-tab-item>
    Admin tab
  </b-tab-item>

  <b-tab-item>
    Business tab
  </b-tab-item>

  <!-- ... -->
</b-tabs>
```

Should I not use tabs to build something like this ?

**Comment by jtommy** [comment]
You might use b-tabs so you have all tab logic but you should only change the style. For example https://codepen.io/anon/pen/GdGGLL?editors=1000

**Comment by verdie-g** [comment]
Ok, and if I want to have a headers in a column I should style _.tabs > ul_ ?

```
.tabs > ul {
  flex-direction: column;
}
```

Indeed, it is much simpler that removing headers :)
