### ISSUE TITLE
Radio button slightly off centre

### ISSUE THREAD

**Issue by ImreC** [buefy/buefy#817]
### Overview of the problem
The radio button selection is slightly off centre. 
![image](https://user-images.githubusercontent.com/9742684/40114131-0d2ba2b2-590c-11e8-8629-71127756cc6e.png)

nuxt-buefy 0.0.4
Nuxt1.0.0
Mozilla Firefox Quantum 59.0.3 (64-bit)
Confirmed for Chrome 66.0.3359.181 (Official Build) (64-bit)
Windows 10

**Comment by guanzo** [comment]
Sometimes it's a little more than "slightly off center"
https://i.gyazo.com/040794f6e59742e8bfe2825d2eccb60c.png

**Comment by timEulitz** [comment]
Having the same issue, the radio buttons look a bit like googly eyes :eyes: and it looks like they are all offset slightly differently.

**Comment by yxngl** [comment]
Platform, browser and zooming all seem to affect it. Using absolute positioning like in the [Bulma extension](https://wikiki.github.io/form/checkradio/) indeed works better in most cases.
