### ISSUE TITLE
Can't import Dialog, Snackbar and Toast component

### ISSUE THREAD

**Issue by PayteR** [buefy/buefy#823]
### Overview of the problem

**Buefy** version: 0.6.5
**Vuejs** version: 2.5.16
**OS/Browser**: Chrome, Firefox

### Description

Hi, i can't import this 3 components.
```
import Vue from 'vue';
import Buefy from 'buefy';

Vue.component(Buefy.Dialog.name, Buefy.Dialog);
Vue.component(Buefy.Snackbar.name, Buefy.Snackbar);
Vue.component(Buefy.Toast.name, Buefy.Toast);
```
Compilation runs fine, but in browser console i see this error

```
TypeError: __WEBPACK_IMPORTED_MODULE_1_buefy___default.a.Dialog is undefined
```
So either i don't have correct names of this components, or there is a bug. I couldn't find list of all components in documentation, it would be good to write all component initialisations somewhere. Thank you.

**Comment by jtommy** [comment]
@PayteR Programmatically component (dialog, toast, snackbar) are not in the export default.
You have to import for example:
```
import { Dialog } from 'buefy'
Vue.prototype.$dialog = Dialog
```
Anyway we are working on components build and in the next releases you'll able to import one or two components as Vue plugin.
