### ISSUE TITLE
Give the possibility to add events or bind href on the tab A or tab LI in tabs

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#827]
### Overview of the problem

**Buefy** version:^0.6.5
**Vuejs** version: ^2.5.13

### Description

I'm using the tabs system and I would like to show the tab depending on the URL.

I have a workaround today which I don't find very clean, then main problem is the fact that we cannot set an event on the tabs LI or tabs A directly.

This is what I do today approximately is

```vue
<template>
  <b-tabs v-model="index">
    <b-tab-item :label="A">Page A</b-tab-item>
    <b-tab-item :label="B">Page B</b-tab-item>
  <b-tabs>
</template>

<script>
const pageIndexes = {
 A: 0,
 B: 1,
 C: 2
}
const reversePageIndexes = {
 '0': 'A',
 '1': 'B',
 '2': 'C'
}

export default {
  data() {
    // set index based on current route of default to 0
    const page = pageIndexes[this.$route.params.page] 

    return {
      index: page ? page : 0
    }
  },

  watch: {
    index(newIndex) {
      this.$router.push({
        name: 'foo',
        params: { page: reversePageIndexes[newIndex] }
      })
    }
  }
}
</script>
```

I have to watch the index to dynamically change the route in the browser because I can't add and event to the tabs A or LI since you don't expose any api to access those elements.

### Api suggestion
Maybe something like `@onTabItemClicked` on the tab-item could solve this or even better, move `tabClick` to the LI and let the inner part of the LI be the slot, so we can add an A element if we want to and fallback to default A if we don't add a slot

**Comment by darkylmnx** [comment]
Let the A be the slotable element, unlike what is currently here
![image](https://user-images.githubusercontent.com/1426357/40432078-1819dbce-5ea9-11e8-95b0-872c3805bfa7.png)

What do you think ?

**Comment by jtommy** [comment]
@darkylmnx There is `change` event on `bTabs` too

**Comment by darkylmnx** [comment]
@jtommy even with the event, the solution is not ideal as I would rather prefer to directly a custom "A" element ou a router-link instead of calling `this.$router.push` programatically

**Comment by jtommy** [comment]
@darkylmnx We cannot let `a` tag be slotable because we have to manage internal state

**Comment by darkylmnx** [comment]
Mmmmh I see, I'll do some testing and submit a PR if I find a way then
because it's not ideal that we aren't able to use a router-link as a tab
IMO.

Maybe something with a renderless component is possible.

Le mer. 6 juin 2018 à 21:26, Walter Tommasi <notifications@github.com> a
écrit :

**Comment by jtommy** [comment]
Ok, PR is always welcome!
