### ISSUE TITLE
Support for user specific icons such as vue-awesome

### ISSUE THREAD

**Issue by sohailalam2** [buefy/buefy#828]
### Overview of the problem

**Buefy** version: 0.6.5
**Vuejs** version: 2.5.2
**OS/Browser**: Chrome

### Description

What are the plans for supporting custom svg icons and/or vue-awesome? 

Personally, I think the **icon** should be a slot with default fallbacks, so as a user I can choose my own set of icons and not load the entire library.

This question has been raised before, but there hasn't been any progress to support it? I was wondering if you have any sort of plans for this or not.

**Comment by duckness** [comment]
I'm not sure if there are any major ramifications, but here is how you can workaround/hack in an icon. This uses vue-awesome icons. One immediate downside is that hot reloading does not like it at all if I modify `Youricon.vue`

-------
`Inputbox.vue`
```vue
<template>
  <b-input placeholder="Search" icon="uniqueclassname">
</template>

<script>
import Vue from "vue";
import Youricon from "./Youricon.vue";

export default {
  name: "Inputbox",
  mounted() {
    this.$nextTick(() => {
      new Vue(Search).$mount(".fa-uniqueclassname");
    });
  }
};
</script>
```
-------
`Youricon.vue`
```vue
<template>
  <icon id="thisiconid" name="search"/>
</template>

<script>
import "vue-awesome/icons/search";

export default {
  name: "Search"
};
</script>

<style>
#thisiconid {
  width: 1.33333em; /*default size of "normal" icon*/
  height: 1.33333em;
}
</style>
```

**Comment by a-kriya** [comment]
I've been using [vue-material-design-icons](https://www.npmjs.com/package/vue-material-design-icons) where necessary instead of a full icon pack, but looks like it is not possible to inject those icons in certain places.  The use-case I ran into is the navigation arrows of the carousel component.

**Comment by subins2000** [comment]
The problem @a-kriya mentioned is in here : #1673 

My usecase is the arrow on sortable tables. Can't load the component from `vue-material-design-icons`
