### ISSUE TITLE
Add sequence numbers to table

### ISSUE THREAD

**Issue by ravenvn** [buefy/buefy#829]
How to add sequence numbers to the table 1,2,3,4.. and the order never changes when users sort other columns?

**Comment by ravenvn** [comment]
It's the back-end job. We just need add a key `serial` to the result and display it as a new b-table-column.
`$startSerial = ($request->page - 1) * $request->perPage + 1;
        $results->map(function (&$item) use (&$startSerial) {
            $item['serial'] = $startSerial++;
        });`
`<b-table-column field="serial" label="#" width="40" numeric>
                    {{ props.row.serial }}
                </b-table-column>`

**Comment by Yonaro** [comment]
ravenvn,

Try the following

`<b-table :data="data">`
    `  <template slot-scope="props">`
    `<b-table-column label="Nr.">`
      `{{props.index + 1}}`
    `</b-table-column>`
     `// Other table columns`
 `</template>`
`</b-table>`

**Comment by hansipete** [comment]
my solution 2021: `{{ data.indexOf(props.row) + 1 }}`

**Comment by kavinmehta** [comment]
This is how I solved it with only front-end, YMMV depending upon your pagination per page.:

index * page doesn't work because on page # 2, it goes 2, 4, 6, on page 3 it goes 3,6 ,9 etc (i.e. if I understand it the way I think it is)


```
//  currentPage is an attribute in data()
 return {
      currentPage: 1,
    }  
```
```
 <b-table 
        ref="table"
        :data="data"
        paginated
        per-page="10"
        :current-page.sync="currentPage"
      >
```
```
<b-table-column v-slot="props" scope="props" label="#" cell-class="valign">
      {{currentPage === 1 ? props.index + 1 : (currentPage - 1) * 10 + props.index + 1}}
</b-table-column>
```
