### ISSUE TITLE
Snackbar HTML & colors

### ISSUE THREAD

**Issue by Valensm** [buefy/buefy#832]
The **message** and **actionText** don't allow HTML strings in **snackbar** component, and in addition **actionText** does the upper case conversion.
The color of the **snackbar** is fixed, unlike the **toast**..
Would it be possible to support HTML content here? And to allow the type of the **snackbar**, similarly to toasts?

Than you.
Martin

**Comment by claide** [comment]
This kind of feature is what I'm looking for.
Creating your own snackbar to support HTML when you're using Buefy makes no sense.

**Comment by service-paradis** [comment]
@claide 
HTML is supported in Snackbar message. You can launch the third example from https://buefy.org/documentation/snackbar
