### ISSUE TITLE
Ability to tweak Tooltip font-size and padding

### ISSUE THREAD

**Issue by xpuu** [buefy/buefy#835]
### Overview of the problem

**Buefy** version: 0.6.5
**Vuejs** version: 2.5.16
**OS/Browser**: All

### Description

It would be great to have the ability to tweak Tooltip font-size and padding.

**Comment by MeikelLP** [comment]
Why not solve it via css? or a bulma variable?

**Comment by xpuu** [comment]
Ok, my bad. I had just a quick look into [_tooltip.scss](https://github.com/buefy/buefy/blob/v0.6.6/src/scss/components/_tooltip.scss). Playing with ```.tooltip``` didn't work, because it was affecting whole content of ```<b-tooltip>```. But you're right, I didn't realize you can adjust font-size and padding via. ```::after``` selector.
``` 
.tooltip::after {
  font-size: 100%;
  padding: 3px 8px;
}
```
