### ISSUE TITLE
Date and time pickers on safari

### ISSUE THREAD

**Issue by trronaldbasco** [buefy/buefy#836]
I have two date pickers for start and end date, as well as time pickers for start time and end time, I open the dropdown and it doesn't close when you open another picker on safari.

**Buefy** version: [0.6.5]
**Vuejs** version: [2.5.13]
**OS/Browser**:  macOS Sierra/Safari

### Steps to reproduce

1. Integrate 2 buefy date/time picker
2. Open 1 picker and open another 

### Expected behavior

Date/time picker recently open should close when opening another.

### Actual behavior
It doesn't hide the previously opened picker.

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/38c501705fed4bed4de5bf844b0b45bc492ae1e3
