### ISSUE TITLE
Select boxes chevron down changed color not corresponding to variables

### ISSUE THREAD

**Issue by ImreC** [buefy/buefy#837]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: Nuxt 1.4.0
**OS/Browser**: Firefox Quantum

### Description

After the last update, the down-pointing chevrons of a select box are in primary color by default. However, they are not in the custom primary color but in Buefy default primary color, therefore adding he is-primary modifier doesn't work because then you get your custom color outline with purple chevrons. 

Screenshot:
![image](https://user-images.githubusercontent.com/9742684/40907646-c6c06ac8-67e4-11e8-8708-4f6dbec707c5.png)

### Current resolution
Downgraded to 0.6.5

**Comment by jtommy** [comment]
@ImreC I have no issue about it. Could you provide us an example ?

**Comment by Christilut** [comment]
I just noticed this too. I've changed the `$primary` variable which seems to work but not in the `b-select`. Version 0.7.1, Vue 2.5.21 and using vue-cli3

**Comment by Christilut** [comment]
No not using Nuxt. 
I noticed it in other components too:
- `input:focus` has border and shadow in wrong color
- `button:focus` same

**Comment by jtommy** [comment]
Please look Bulma source https://github.com/jgthms/bulma/blob/master/sass/elements/form.sass#L21 and Bulma docs https://bulma.io/documentation/form/select/.
At the moment you have just add a `b-field` wrapper with `type="is-primary"`.
I'll think if add a `type` prop to select further

**Comment by Christilut** [comment]
Ah okay, but shouldn't they use the primary color by default? So if you don't add `is-primary` shouldn't they then be either primary color (whatever that may be changed to) or no color (grey) ?
