### ISSUE TITLE
Icon pack can't be dynamically changed

### ISSUE THREAD

**Issue by nextgensparx** [buefy/buefy#839]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS**: Solus 3.9999 (Linux)
**Browser**: Chrome

### Description

Changes to `b-icon`'s prop `pack` are ignored, preventing the pack from being dynamically changed. 

I believe this is because the internal `newPack` property is never updated to match `pack` ([see Icon.vue](https://github.com/buefy/buefy/blob/d869b4db97193ca9522563f4ca727e0fe16834d8/src/components/icon/Icon.vue#L23)).

Is this by design or simply an oversight?

If this is an issue, I would be happy to submit a pull request. Changing `newPack` to a computed property should work.

### Steps to reproduce

With the following file open, click 'Change'.

```vue
<template>
<div>
  <b-icon :pack="pack" :icon="icon"></b-icon>
  <button @click="change">Change</button>
</div>
</template>

<script>
export default {
  data() {
    return {
      pack: 'fa',
      icon: 'user',
    };
  },
  methods: {
    change() {
      this.pack = 'mdi';
      this.icon = 'account';
    },
  },
};
</script>
```

### Expected behavior

The icon pack should change to mdi

### Actual behavior

The icon pack does not change

**Comment by jtommy** [comment]
@nextgensparx Thanks! I was working on it but anyway PR are always welcome!
