### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by darkylmnx** [buefy/buefy#841]
Hi,

i'm having security concerns about this:
https://github.com/buefy/buefy/blob/7858c0f9fbe4e77ba9ff3f784cc492172a92468e/src/components/autocomplete/Autocomplete.vue#L47

If the datasource is gotten from the server and we use the autocomplete component like this, it's openbar for XSS.

I'd suggest to use regular template interpollation and leave the use of the slot if we want to add html to the item.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/1097
