### ISSUE TITLE
How to Close Autocomplete DropDown programmatical

### ISSUE THREAD

**Issue by SDJeff** [buefy/buefy#842]
How to close the dropdown selection of the autocomplete after entry was confirmed by the enter key without selecting an suggested value of the dropdown?

Any ideas? 

If i click with the mouse to the screen the it closes. Otherwise it still left open.

**Comment by jtommy** [comment]
@SDJeff You should change `isActive` internal value. For example https://codepen.io/anon/pen/mKWoWB?&editors=101
