### ISSUE TITLE
Remove tags in tag input programmatically

### ISSUE THREAD

**Issue by sabby62** [buefy/buefy#845]
How can I remove the tags programmatically from Tag Input ?
 ```
<b-taginput
                v-model="tags"
                ellipsis
                icon="label"
                placeholder="Add a tag">
            </b-taginput>
```

In my clear method, I am setting the this.tags = [], but I am getting following warning: 
```
 [Vue warn]: $listeners is readonly.

    found in

    ---> <BInput>
           <BAutocomplete>
             <BTaginput>
               <BField>
                 <Root>
```

**Comment by Dinuz** [comment]
@sabby62 check my old post I do think you can get inspired #https://github.com/buefy/buefy/issues/831

I changed the tags color programmatically using $ref, you should be able to do the same.

**Comment by jtommy** [comment]
@sabby62 For example a simple way: https://codepen.io/anon/pen/vrdXzN?&editors=101
