### ISSUE TITLE
Question - Checkbox check all 

### ISSUE THREAD

**Issue by YosefOberlander** [buefy/buefy#847]
### Overview of the problem

**Buefy** version: 0.5.4
**Vuejs** version: 2.5.3
**OS/Browser**: All browers

### Description

I'm new to Buefy.

I just have a question. I'm using b-checkbox and I want to make a b-checkbox what will select all b-checkbox in my v-for.

**Comment by jtommy** [comment]
@YosefOberlander You might listen `@input` event or `@change` event and update all elements into array
