### ISSUE TITLE
Table sort event data is not send properly

### ISSUE THREAD

**Issue by woodgates** [buefy/buefy#848]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description
Hi.
I'm implementing an ajax call to get the data from the table. The bug I found is the sort event is not properly sent by Table.vue.

Now this is the event:
```
this.$emit('sort', column.field, this.isAsc ? 'asc' : 'desc')
```

Although in Vue DevTools you see the payload as an array with both values, if you do a console.log(event) it will give you only column.field, and there is no way to pick the sort order. I you do console.log(event[1]) it gives you the second character of the column.field.

In order to get both values i suggest to wrap both values in an object, for example:
```
this.$emit('sort',{column:column.field,sort:this.isAsc ? 'asc' : 'desc'})
```

### Steps to reproduce

Create a function to handle the sort event in a table.

### Expected behavior

Get both values in an object: the field and the sort order.

### Actual behavior

You get only the field value.

**Comment by jtommy** [comment]
@woodgates Did you try to bind a method for example `onSort(column, sort)` on `sort `event ?

**Comment by woodgates** [comment]
@jtommy Hi Tommy I'm using  @sort="sortTableData". Should I use  @sort="(column, sort) => sortTableData" ?

**Comment by jtommy** [comment]
Your sortTableData method has to have two parameters. It's ok the first one

**Comment by woodgates** [comment]
@jtommy 

This worked:

@sort="(column,sort) => sortTableData (column,sort)"

    sortTableData(data){

      this.sorting={
        sort_field:data.column,
        sort_dir:data.sort
      }
   
      this.getItems();
   
    }
