### ISSUE TITLE
Class to hide columns in Table - Suggestion

### ISSUE THREAD

**Issue by woodgates** [buefy/buefy#849]
Hi.

I want to suggest to add a prop class for the TableColumn component.

This will be usefull for using 'is-hidden-mobile' for example.

**Comment by jtommy** [comment]
@woodgates You can add `class` attribute to `b-table-column` component.
For example (first_name and last_name are hidden when mobile): https://codepen.io/anon/pen/bKqzjr?editors=1010

**Comment by gierloff** [comment]
I just used vue-mq and defined the same breakpoints as bulma:

```
import VueMq from 'vue-mq';

Vue.use(VueMq, {
  breakpoints: {
    mobile: 769,
    tablet: 1025,
    widescreen: 1217,
    fullhd: Infinity
  }
})
```
https://alligator.io/vuejs/vue-media-queries/
