### ISSUE TITLE
Update of model state outside the component triggers input event

### ISSUE THREAD

**Issue by pcicman** [buefy/buefy#856]
### Overview of the problem

**Buefy** version: 0.6.3, latest
**Vuejs** version: N/A
**OS/Browser**: N/A

### Description

The `v-model` proxy strategy in various components (e.g. `v-switch`) leads to firing of the `input` event even when component was not touched. Problematic code:

```
        watch: {
            /**
             * When v-model change, set internal value.
             */
            value(value) {
                this.newValue = value
            },
            /**
             * Emit input event to update the user v-model.
             */
            newValue(value) {
                this.$emit('input', value)
            }
        }
```

### Steps to reproduce

1. Mount component with initial value, assign `@input` listener to it.
2. Change the model value (from the parent).
3. The `input` event get's fired, listener is invoked.

#### The following happens

1. `value(value)` method (watch) changes the `newValue`
2. `newValue(value)` method (watch) get's invoked due to `newValue` change and fires `input` event.

### Expected behavior

Input event shall not fire if the model was changed from outside => shall fire only if the value was changed from within the component.

### Actual behavior

Input event fires.

**Comment by hadleyrich** [comment]
This affects me also.
