### ISSUE TITLE
B-table-column + dynamic Array Inconsistency 

### ISSUE THREAD

**Issue by Weeez** [buefy/buefy#861]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Windows 10 / Google Chrome (67.0.3396.87)

### Description

My goal is to create a dynamic table with Buefy-Table. I want to generate the column-array in runtime by user interaction (JavaScript) . This array would contains static values, but the first part of it must be dynamic (for some reason :). A concept example: ['a', 'b', 'c', 'd', ..... 'n' , 'static1', 'static2']). 
If i use the basic _:data_ and _:columns_ attributes, there is no problem at all, everything works as intended.. but i want to customize some of the cells inside the table, so i chose to use b-table-columns and let the v-for attribute for iteration... and here is the problem begins.

### Steps to reproduce

1. Create a static array.
2. Create an empty dynamic array.
3. Fill the dynamic array with custom values by user.
4. Merge these 2 array into a third one (this will be the final-column-order).
5. Let the v-for process to re-rendering the component.
6. Add new values to the dynamic array.
7. Merge the 2 arrays.
8. Let the v-for process to re-rendering the component.
9. Remove some values from the dynamic array.
10. Merge the 2 arrays.
11. Let the v-for process to re-rendering the component.
12. Some inconsistency should appear.
+1. Be surprised. 

I created an example, so here is my proof off the issue:

```
<div id="app">
  <div class="test-row">    
    <template>
      <b-table
          ref="table"
          :data="mydata"
          
          >
          <!--:columns="columns"-->
          
          <!--
          for working version, put the template section below between 
          comments and move back :columns comment to the b-table tag as
          attribute
          -->
          
          <template slot-scope="props" >
            <b-table-column v-for="(item, index) in columns" 
            :key="index" 
            :label="item.label">
                {{props.row[item.field]}}                
            </b-table-column>
          </template>
          
      </b-table>
    </template>    
  </div>
```

I don't want to copy the whole work-around-code here, so follow the next link to try it yourself:
https://jsfiddle.net/weeez/86qLpcd5/

### Expected behavior

I expect the b-table shows as much column as the number of the generated column-array.

### Actual behavior

The b-table shows remaining values from the previous state of the column-array at random places.

**Comment by balintbabics** [comment]
bump

**Comment by jtommy** [comment]
Same issue https://github.com/buefy/buefy/issues/833
