### ISSUE TITLE
Potential bug with Programmatic Modal

### ISSUE THREAD

**Issue by Dinuz** [buefy/buefy#863]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: IOS High Sierra / Chrome

### Description

The modal onCancel function get fired also if cancel is not called.

### Steps to reproduce

I do have a form that get submitted with http post using vue-resource.
When I get back the response, a modal is triggered programmatically with a component:

  ```
toogleSuccessModal: function (token) {
      this.$modal.open({
        parent: this,
        component: SuccessfulSubmission,
        onCancel: this.outputMessage(),
        props: {
          token: token
        }
     })
  }
```

To test the behavior I defined a simple outputMessage function to just output to console a message:

```
outputMessage: function () {
      console.log('onCancel was called')
    }
```

As soon as the modal popup the message appears in the console. The modal stays on the screen, everything works as expected and I can keep the UX flow going on.
However the onCancel got fired without triggering anything - Not good:( 

Not good because after that, if I press x to close the modal or I do any other default closing action, the onCancel method doesn't get fired anymore.

### Expected behavior

I expect that the onCancel get called when a cancel action is performed, and consequently it fires the onCancel assigned function.

### Actual behavior

onCancel gets fired upon opening the modal, and that get registered as cancel too.

Am I doing something wrong?

**Comment by vjoao** [comment]
You are actually calling your function. You should pass a function to onCancel like this:

```toogleSuccessModal: function (token) {
    this.$modal.open({
      parent: this,
      component: SuccessfulSubmission,
      onCancel: () => this.outputMessage(), // note the arrow
      props: {
        token: token
      }
   })
}
```

**Comment by Dinuz** [comment]
@vjoa thank you:) my fault...going to try it immediately

**Comment by jtommy** [comment]
@dinuz @vjoao solution is the right way at the moment

**Comment by Dinuz** [comment]
@jtommy what that means? Which solution?

**Comment by vjoao** [comment]
@Dinuz `onCancel` expects a function. Functions are first-class citizens on Javascript, you can just pass them around. This is what happens when you call the $modal open function:
you pass an object as a parameter, the modal config. One of the key-value pairs is the `onCancel`, which expects a function. You are passing not a function, but the result of the function to `onCancel`, as you are indeed calling your function by accessing it with `( )`.

**Comment by vjoao** [comment]
This should work as well:
```
{
   ...
   onCancel: this.outputMessage
}
```

The problem is `outputMessage` will be executed on the context of the modal, where you lose the `this` scope. Using an arrow function, `outputMessage` is able to access `this`, which is a Vue instance.

**Comment by Dinuz** [comment]
@vjoao that sounds legit, and makes totally sense...thank you so much for the clarification:)
I used it as you suggested and works perfectly! your last comment highlighted everything!

Thanks again:)
