### ISSUE TITLE
 <b-input> native "size"

### ISSUE THREAD

**Issue by tanhs** [buefy/buefy#864]
Buefy version: 0.6.5
Vuejs version: 2.5.16
OS/Browser: All

### Description

How to use the <b-input> native "size".  I would like to manage the size by not using the "is-small" etc.

### Steps to reproduce
<b-input size="5em"> it shows as class="input 5em"..

### Expected behavior
I need the <input size="5em"

### Actual behavior
it shows as class="input 5em"

**Comment by service-paradis** [comment]
I think he want something like the prop `native-size` in `b-select`.

**Comment by jtommy** [comment]
Ok, free to make a PR ;)

**Comment by service-paradis** [comment]
Sure, I already check for it a little bit. Right now, I have a little problem. There is some css that apply `width: 100%` to every `input`.

I added this:
```
.input {
    &[size] {
        width: auto
    }
}
```

In this case, there are problems with right icons.

**Comment by jtommy** [comment]
You should apply it only on select

**Comment by service-paradis** [comment]
`native-size` already exists for `b-select` element.
I think he want to have the same behavior for `b-input`.

**Comment by jtommy** [comment]
Oh you're right!
There is already an opened issues in Bulma repo https://github.com/jgthms/bulma/issues/1955

**Comment by tanhs** [comment]
@service-paradis yes you are right <b-input>

**Comment by service-paradis** [comment]
@tanhs 
Great, but as you can see, it is not as easy as it looks. Bulma does not support it, and since Buefy is build on top of it, we need to overwrite some of the Bulma styles. Maybe, we will need to wait until Bulma fix the problem.

This is a branch in my Buefy fork where I tried to do it:
https://github.com/service-paradis/buefy/tree/fix-864

**Comment by tanhs** [comment]
@service-paradis Yes I can see the icon is out from the box.  Thanks for your effort.
