### ISSUE TITLE
b-radio cannot cope with an html-label

### ISSUE THREAD

**Issue by Gerarddus** [buefy/buefy#868]
### Overview of the problem

**Buefy** version: [0.6.6]

### Description

The b-radio does not work properly if you supply an html-label to the radio-button.
In my case, I'm using a v-for to generate the list of radiobuttons, so I need the label with a v-html attribute.

### Steps to reproduce

Pen created with first radiobutton filled with a label containing html
https://codepen.io/Gerarddus/pen/wXPVmP

### Expected behavior

It would be nice if you could still click on "Flint" and activate the corresponding radiobutton. But you can't. 

### Possible solution

I ended up creating my own radiobutton based on buefy's, using something along the lines of :
`<b-radio v-model="radio"
               :native-value="answer"
               :id="id">
          <label v-html="answer" :for="id"></label>
   </b-radio>`

and in Radio.vue:
`<input
            v-model="newValue"
            type="radio"
            :disabled="disabled"
            :name="name"
            :value="nativeValue"
            :id="id">`

**Comment by jtommy** [comment]
@Gerarddus Do you need a label tag? Try without it

**Comment by Gerarddus** [comment]
@jtommy Thanks, and yes, I've tried, but I need a v-for loop for the radiobuttons and then I get stuck: 
[codepen](https://codepen.io/Gerarddus/pen/QxapLv)
so thats why I resorted to a label. Is there another way?

**Comment by Gerarddus** [comment]
@jtommy thanks. In my original attempt I tried <label v-html"answer"></label> which doesn't work. However <span>, <div> and <p> (and probably others too) do work. I picked <label> because I figured semantically this would be correct. Maybe a sidenote to the docs would be helpful for others? I'll stick with <span> for buefy however. Thanks!
