### ISSUE TITLE
b-table can't render on iPhone

### ISSUE THREAD

**Issue by biigpongsatorn** [buefy/buefy#869]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.2]
**OS/Browser**: ios/All Browsers

### Description

I use b-table component for show my array data, It worked on desktop browser, Android but not work on IOS, b-table can't render data on iPhone, IPad. My code is.

```html
<b-table :data="myData">
 <template slot-scope="props">
   <b-table-column field="name" label="Name">
      {{ props.row.name }}
   </b-table-column>
   <b-table-column field="amount" label="amount">
      {{ props.row.amount }}
   </b-table-column>
 </template>
</b-table>

<script>
import { mapGetters } from 'vuex'
export default {
 computed () {
    ...mapGetters({
      myData: 'myModule/myData'
    }),
 }
}
</script>
```
If i have element `b-table-column` it will not work, And when i try to remove `b-table-column` and try to show `{{props.row}}` it will work. (This bug will happen on ios only).

```html
<b-table :data="myData">
 <template slot-scope="props">
   {{ props.row }}
 </template>
</b-table>

<script>
import { mapGetters } from 'vuex'
export default {
 computed () {
    ...mapGetters({
      myData: 'myModule/myData'
    }),
 }
}
</script>
```

**Comment by jtommy** [comment]
@biigpongsatorn Do you see official table docs?

**Comment by biigpongsatorn** [comment]
I don't know why this problem has been happen on some page of my app, It's not sensible, But now I resolve that by use another component instead.

Thank you for your support.
