### ISSUE TITLE
Some native events don't trigger for b-autocomplete when openOnFocus is set to true

### ISSUE THREAD

**Issue by Olusiji** [buefy/buefy#870]
### Overview of the problem
Some native events `@input.native` and `@change.native` don't trigger for `b-autocomplete` when `:open-on-focus = true`

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.16
**OS/Browser**: Chrome

### Description
This bug only occurs when openOnFocus attribute is set to true, otherwise the native events are triggered. Non-native events work fine, also  `@click.native` event works fine when openOnFocus is true.

### Steps to reproduce
Using the example in the documentation:

 ```
<b-field label="Find a movie">
            <b-autocomplete
                    v-model="name"
                    :data="data"
                    placeholder="e.g. Fight Club"
                    field="title"
                    :loading="isFetching"
                    @change.native="showAlert"
                    @input.native="showAlert"
                    :open-on-focus = true
                    @select="option => selected = option">

                <template slot-scope="props">
                    <div class="media">
                        <div class="media-left">
                            <img width="32" :src="`https://image.tmdb.org/t/p/w500/${props.option.poster_path}`">
                        </div>
                        <div class="media-content">
                            {{ props.option.title }}
                            <br>
                            <small>
                                Released at {{ props.option.release_date }},
                                rated <b>{{ props.option.vote_average }}</b>
                            </small>
                        </div>
                    </div>
                </template>
            </b-autocomplete>
        </b-field>
```

### Expected behavior
The `showAlert` method pops up an alert when called.

### Actual behavior
Nothing happens, the event is not triggered. The event is triggered and the alert pops up when `:open-on-focus` is removed.

**Comment by jtommy** [comment]
@Olusiji I'm trying but i don't see any issue about

**Comment by jtommy** [comment]
@Olusiji For example: https://codepen.io/anon/pen/ZRrOMK?&editors=101

**Comment by Olusiji** [comment]
@jtommy Sorry, it seems I misinterpreted the problem. It seems the event doesn't trigger when an option is selected without typing in an input. In your example code, if you set the mouse to focus on the input field and you don't input anything, the select options are displayed as is the expected behaviour when ` :open-on-focus = true`
The issue is that if you select an option directly, the event doesn't trigger.

**Comment by Olusiji** [comment]
@jtommy Okay, Thank you for your time
