### ISSUE TITLE
Datepicker displaying wrong day

### ISSUE THREAD

**Issue by mth3n** [buefy/buefy#872]
### Overview of the problem

**Buefy** version: [0.0.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Firefox/Chome

### Description

When every I select a date using the date picker it always selects the previous data. Ex. If I select 6/4 from the calendar 6/3 will be displayed. 
### Steps to reproduce

1. Use example code provided for datepicker in documentation

### Expected behavior

The day I click should be displayed in the input
### Actual behavior

The previous day is displayed in the input

![image](https://user-images.githubusercontent.com/2897199/41616594-e84de3ba-73c3-11e8-8742-be17a3aa7c16.png)

**Comment by jtommy** [comment]
@mth3n Could you provide us your code ? Because i can't reproduce it

**Comment by pablich** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/14059480/41622034-c5e9aea0-73e4-11e8-8566-fef47eb30e4e.png)

**Comment by mth3n** [comment]
I'm using the example code from https://buefy.github.io/#/documentation/datepicker.  The demos on buefy.github.io are also showing the wrong dates for me like in @pablich post above.

<template>
    <b-field label="Select a date">
        <b-datepicker
            placeholder="Click to select..."
            icon="calendar-today">
        </b-datepicker>
    </b-field>
</template>

![image](https://user-images.githubusercontent.com/2897199/41631892-cd05186a-73fc-11e8-9afa-734935d66016.png)

**Comment by mth3n** [comment]
This pull request appears to be for the issue I'm having -> https://github.com/buefy/buefy/pull/866.
