### ISSUE TITLE
Datepicker not displaying years after 2021

### ISSUE THREAD

**Issue by DespertaWeb** [buefy/buefy#873]
### Overview of the problem

**Buefy** version: "buefy": "^0.6.2",
**Vuejs** version: 2.9.1
**OS/Browser**: MAC OS & Chrome 

### Description
Datepicker doesn't show further than year 2021. I wonder if this is intendet or is a bug

If have this :
```
            <b-datepicker
                :first-day-of-week="1"
                v-model="toDate"
                placeholder="Click to select..."
                icon="calendar-today">
            </b-datepicker>
```

### Steps to reproduce

1. First Step
I can only navigate until 2021: 
![image](https://user-images.githubusercontent.com/13997454/41661547-4b73ac64-749f-11e8-8824-a71416b20417.png)

2. Second Step
If I use the arrow to get to 2022, it does not display 2022 in the dropdown year button:

![image](https://user-images.githubusercontent.com/13997454/41661613-6743413e-749f-11e8-8652-89f5bc48b221.png)

### Expected behavior

It doesn't display more years. (see 2nd pic)

### Actual behavior

Could this generate more years dynamically?

**Comment by jtommy** [comment]
@DespertaWeb It has been fixed since 0.6.3.

**Comment by DespertaWeb** [comment]
@jtommy I don't see this fixed in the documentation: 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/13997454/42049524-91e2b9b6-7b06-11e8-9877-28e473b384d7.png">

**Comment by maartengithub** [comment]
Is the 'increment year prop' due to be implemented? That would really help me out!!
