### ISSUE TITLE
Long modals open in the middle of the modal, not the top

### ISSUE THREAD

**Issue by philipithomas** [buefy/buefy#874]
### Overview of the problem

**Buefy** version: 0.6.6

### Description

When opening a long, clipped modal - I expect the top of the content to be at the top of the modal. Instead, it starts scrolling in the middle of the body.

### Steps to reproduce

Demo: https://imgur.com/a/XBYLkyF

```
    <b-modal :active.sync="modalOpen" has-modal-card>
      <div class="card new-job-card modal-card">
        <div class="card-content">
          <div class="content">
            <!-- just make it long -->
          </div>
        </div>
      </div>
    </b-modal>
```

**Comment by jtommy** [comment]
@
I think the structure of Bulma modal isn't correct. You should add `modal-card body` into `modal-card` or simply `modal-content`. For example: https://codepen.io/anon/pen/BVrPEe?editors=1010

**Comment by philipithomas** [comment]
@jtom
That seems to solve it, thanks. However, if I'm changing components in the modal, is there a way to scroll back to the top?

**Comment by jtommy** [comment]
What do you mean "changing component"?
