### ISSUE TITLE
how to add tooltip for a field label ?

### ISSUE THREAD

**Issue by dfy167** [buefy/buefy#876]
i 'd like to add tooltip for input label . how to do it. but in the field label is a string type

`<b-field label="Username"
            type="is-success"
            message="This username is available">
            <b-input value="johnsilver" maxlength="30"></b-input>
        </b-field>`

**Comment by bammoo** [comment]
Element-ui uses slot to support jsx type label.

**Comment by williamabbott** [comment]
+1

**Comment by service-paradis** [comment]
It can now be done since 0.7.6 using the label slot
@jtommy I think we can close this issue

**Comment by jtommy** [comment]
Right!
