### ISSUE TITLE
Dropdowns don't close when opening other dropdowns

### ISSUE THREAD

**Issue by garrynewman** [buefy/buefy#885]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.16
**OS/Browser**: Chrome / Windows 10

### Description

Dropdowns don't automatically close when opening other dropdowns

### Steps to reproduce

Click on a dropdown button
Click on another dropdown  button

### Expected behavior

First dropdown should close, new dropdown should open

### Actual behavior

Both dropdowns remain open

**Comment by gdutwyg** [comment]
@jtommy  Next release  will solve this question?

**Comment by gdutwyg** [comment]
if i want to solve this question in current release, how i should do?

**Comment by gdutwyg** [comment]
@jtommy

**Comment by jtommy** [comment]
Wait new release or try buefy@beta

**Comment by gdutwyg** [comment]
When do you plan to release the next version?

**Comment by jtommy** [comment]
New version has a new build system and we try to be sure that it's all ok but we think to be quite ready

**Comment by gdutwyg** [comment]
OK

**Comment by ricardopolo** [comment]
Do you have an ETA for relasing a new version?

**Comment by jtommy** [comment]
@entwicklerRepo Sure, try last version

**Comment by entwicklerRepo** [comment]
I'm on 0.7.0, but dropdowns are not closing, is there a way to trigger that manually? or at least do you have any hints where to look for a problem?

**Comment by jtommy** [comment]
See docs page, it's all ok.

**Comment by entwicklerRepo** [comment]
it's just not working, I copied code form docs examples.
[Screen Recording 2018-10-30 at 13.09.18.zip](https://github.com/buefy/buefy/files/2529547/Screen.Recording.2018-10-30.at.13.09.18.zip)

**Comment by jtommy** [comment]
@entwicklerRepo I should see your code, it's no easy in this way
