### ISSUE TITLE
Search Table: Feature Request

### ISSUE THREAD

**Issue by aligoren** [buefy/buefy#888]
### Overview of the problem

**Buefy** version: Latest
**Vuejs** version: 2.9.6
**OS/Browser**: GNU/Linux - Mozilla Firefox

### Description

Hi. when I was working in my company, I added a new feature to Buefy. Because I needed it. Our data was very large. We needed to search in the table. So, I did small modifications for Buefy tables.

All those modifications are very basic to use. There are three props for this feature. These are;

**search-table**: This prop is giving boolean value.

**search-location**: This prop is giving string value. The values must be `is-pulled-right` or `is-pulled-left`. The default value is `is-pulled-right`

**search-place-holder**: This prop is giving string value. If the developer wants to show placeholder. The default value is `Search...`

I added a gif to understand what I'm saying. If this feature seems useful, I can open pull request to dev branch.

### Animated Gif

![search-buefy](https://user-images.githubusercontent.com/4205423/42133928-d4ad01ee-7d3a-11e8-8d92-046da868ae5a.gif)

**Comment by aligoren** [comment]
@codegeek1001 No. I did not open PR yet. Because firstly, we need to talk about this with buefy's developers.

**Comment by nicostuhlfauth** [comment]
Having a search directly integrated into the table component would be really awesome. Until now only possible in quite complex ways...

**Comment by nicostuhlfauth** [comment]
It has already been discussed in #555. Someone posted a basic example of a searchable table using a computed variable: https://codepen.io/avrong/pen/KoQZor

**Comment by tonystonee** [comment]
I decided to fork this repo and make my own solution. This is what I came up with:

![search](https://user-images.githubusercontent.com/9577765/48146224-7c124c80-e282-11e8-8b6f-c622b7e5cf15.gif)

Repo:
[https://github.com/tonystonee/buefy/tree/SearchFilter](https://github.com/tonystonee/buefy/tree/SearchFilter)
I haven't made a PR yet because I haven't made a mobile solution for this feature. (It wasn't needed in my project).

If anyone wants to help out with the mobile side, feel free!

**Comment by TurboControl** [comment]
Vuetable-2 has the row filter feature and this is one critical piece before we can migrate to Buefy tables. We are using Buefy for the other components.

**Comment by Sogl** [comment]
Really need this feature 👍

**Comment by viralpatel380** [comment]
@aligoren Can please open PR ?

**Comment by jtommy** [comment]
@viralpatel380 it's already in review a PR

**Comment by aFluxx** [comment]
I like the initial feature, where there is one search box for the entire table. I can't seem to find how to do this in the docs. Only way I find is the single column search.

Is the full table search included?

**Comment by aFluxx** [comment]
Hey @aligoren , I'm curious how u made that search you showcased in your initial post. Do you mind posting the sourcecode?

**Comment by bzavalavaldivia** [comment]
> I decided to fork this repo and make my own solution. This is what I came up with:
> 
> ![search](https://user-images.githubusercontent.com/9577765/48146224-7c124c80-e282-11e8-8b6f-c622b7e5cf15.gif)
> 
> Repo:
> https://github.com/tonystonee/buefy/tree/SearchFilter
> I haven't made a PR yet because I haven't made a mobile solution for this feature. (It wasn't needed in my project).
> 
> If anyone wants to help out with the mobile side, feel free!

I would like to use that for mobile

**Comment by jtommy** [comment]
You can but without mobile cards

**Comment by lgarczyn** [comment]
I feel like this Issue should be reopened for mobile cards.
