### ISSUE TITLE
Unexpected behavior of datepicker component on mobile devices and chrome debugger

### ISSUE THREAD

**Issue by fermerino** [buefy/buefy#889]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Chrome 67.0.3396.79 

### Description

The datepickers selectors fails on mobile. Im using custom selectable dates on my datepickers its works fine on desktop // laptop but not in mobile.

In adition, this happen on the documentation.

### Steps to reproduce

1. Open debug mode on Chrome (and to simulate a mobile)
2. Go to https://buefy.github.io/#/documentation/datepicker 
3. Click on datepicker selector

![issue](https://user-images.githubusercontent.com/40423226/42212929-c49db34c-7eb7-11e8-97fd-c9a4b3591432.png)

### Expected behavior

It should open the modal with the selecteable dates

### Actual behavior

Chrome debugger: The styles fails and it has a strange behaviour.
On smartphone: The modal its showed but all dates are selecteable

Thanks!

**Comment by jtommy** [comment]
@fermerino `selectable-dates` props doesn't work on mobile because it will be open native datepicker but you can disable it using `:mobile-native=false`.
Anyway I don't see any issue with chrome debugger and the example page show me modal datepicker.

**Comment by fermerino** [comment]
Wow! It was that. I should have to read all documentation sorry. 

PD:
Anyways, in Chrome debugger (with the device tool set in "mobile"), the examples on your documentation show the mobile-native datepicker. Maybe you're interested in updating that?

On Firefox (with the device tool set in "mobile") yours examples works fine.


Thanks!!

**Comment by jtommy** [comment]
@fermerino Yes you're right but it's all ok.
