### ISSUE TITLE
Are the cookies installed by materialdesignicons.com really necessary?

### ISSUE THREAD

**Issue by jvmonjo** [buefy/buefy#890]
As a result of the new eurpean GDPR regulation, we need to have more control over the cookies in our sites.

I've noticed that 2 cookies are installed by materialdesignicons.com. Are they really necessary in a static site? How can I avoid them to be installed in my deployed site?

**Comment by jtommy** [comment]
Buefy lib doesn't provide material design icons so you can choose as you want
