### ISSUE TITLE
Multiple inputs for prompt

### ISSUE THREAD

**Issue by serge1peshcoff** [buefy/buefy#891]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Node.js 8.7.0, MacOS 10.13.5 x64

### Description

I have a proposal for dialog prompt improvement: it would be awesome to have the ability to set multiple inputs, not one.

I'm using Buefy in one of my projects and I needed to ask 2 inputs. And I couldn't use dialog for that and I needed to use custom modal for that. Using prompt would be easier

### Proposed API changes

My proposal is to update the dialog component that way:

- the `input` field can be both `Object` and `Array`
- if it's the array, multiple inputs are displayed and array of results is returned on `@selected`
- if it's the object, one input is displayed and one result is returned on `@selected`

I can implement it as a PR, but I want to ask your opinion on that.

**Comment by jtommy** [comment]
@serge1peshcoff Buefy prompt is a quick and simple way to create a native prompt.
We don't want to add complexity at the moment.
Anyway thanks!
