### ISSUE TITLE
@change triggered on change outside component

### ISSUE THREAD

**Issue by Heartz66** [buefy/buefy#896]
### Overview of the problem

**Buefy** version: 0.7.1
**Vuejs** version: 2.5.16
**OS/Browser**: Chrome 67.0.3396.99

### Description

Change event gets triggered when the v-model variable is changed outside the component.

### Expected behavior

For example: if I select an item from a dropdown, I want to have the change event only triggered once in this case.

However, it also gets triggered when the v-model variable is updated outside the component, which in my case made the change event trigger multiple times since I change the v-model variable in my own components if necessary, and also trigger an update function that modifies the v-model variable, but that function gets triggered twice since I also use it as change event function.

I won't be able to change/remove my update function, since I depend on it and the buefy change event is happens async, since it depends on watchers.

### Actual behavior

I only want the change event triggered when it gets changed inside the Buefy component, and not outside of it.

**Comment by adrlen** [comment]
If I'm not mistaken, i can't reproduce it, see above :

https://codepen.io/adrlen/pen/NBWNJP?editors=1011

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/6dc9886411aec2dabde6d344090c48a2fcb71748
