### ISSUE TITLE
Radio docs maybe can be better explained

### ISSUE THREAD

**Issue by daniheras** [buefy/buefy#901]
Hello,
In the docs appears as normal usage "v-model" instead of native "name" attribute in order to bind the radio name to a vue component property.
In my whole experience i wasnt need two way data binding with form controlls, but anyway, why are you explaining in the docs v-model instead of name as the normal way of usage?. Only curiosity.

PD: Sorry for my poor english 😬

**Comment by jtommy** [comment]
@daniheras Because it's a common way to develop project with Vue.
It isn't mandatory anyway.
