### ISSUE TITLE
Taginput - Reordering of Tags

### ISSUE THREAD

**Issue by nicostuhlfauth** [buefy/buefy#903]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Windows 10 / Chrome

### Description

Please add a new property for reordering tags using drag and drop.

Name: allowReordering
Description: Allows reordering of tags by drag and drop
Type: Boolean
Default: false

**Comment by jtommy** [comment]
@nicostuhlfauth No I'm sorry at the moment we aren't going to add it.
