### ISSUE TITLE
Table: Changing data object affects Sorting

### ISSUE THREAD

**Issue by nicostuhlfauth** [buefy/buefy#904]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Windows 10, tested using the latest Firefox and Chrome

### Description

The CurrentSortColumn value is set from empty to the first visible column once the data object changes.

### Steps to reproduce

Create a table:

`<b-table :data="users" :columns="columns" :checked-rows.sync="selectedRows" checkable></b-table>
`

Add or delete rows. Doesn`t matter if it's done programatically or using Vue Devtools.

### Expected behavior

CurrentSortColumn does not change.

### Actual behavior

CurrentSortColumn changes. Up arrow gets visible. See the screenshot below.

![screenshot_table](https://user-images.githubusercontent.com/17216829/42578147-39b06e8a-8526-11e8-8f0f-978bf3e15136.png)

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/833

**Comment by nicostuhlfauth** [comment]
Oh, haven't seen it. When will the update with the fixes be published?

**Comment by jtommy** [comment]
There is no a date but as soon as possible
