### ISSUE TITLE
datepicker doesn't close when focus moves to another datepicker input field

### ISSUE THREAD

**Issue by hqdo** [buefy/buefy#906]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Windows10/Chrome

### Description

With two datepicker inputs on a form, when you move the focus from one datepicker to the other datepicker input, the 1st datepicker drop down does not disappear. If the focus is lost in any other way, the 1st datepicker closes as expected.

The problem here is if there are two datepickers one after another

Picker 1
Picker 2

If you click on Picker 2, then click on Picker 1, the pick 1 overlaps on top of the picker 2 making a very confusing scenarios.

### Steps to reproduce

1. Create two date picker inputs.
2. Click on picker 1
3. Click on picker 2. Both Picker 1 and Picker 2 are shown

### Expected behavior

Picker 1 should close when Picker 2 opens.

### Actual behavior

Picker 1 remains open and Picker 2 is also open.

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/836

**Comment by Healios** [comment]
This has not been fixed in the latest version 0.7.5.
![Issue](https://user-images.githubusercontent.com/9387114/57184254-2cbb7a80-6eb9-11e9-8f6f-d2a276b33e74.jpg)

**Comment by maartengithub** [comment]
Saved in 3a3f19e26e874cf0be855a26b0ddd83fa2a83ce8 : latest version buefy

**Comment by jtommy** [comment]
Now It should be ok
