### ISSUE TITLE
Improvement: Filter columns of table

### ISSUE THREAD

**Issue by alexandrsmirnov93** [buefy/buefy#911]
**Buefy** version: [v0.6.6]
**Vuejs** version: 2.5.16]
**OS/Browser**: Everything

### Description

There is not opportunity to filter colums of b-table by additional input in this colum. Please, make the opportunity to filter by aditional input in head of table for filter this column in each colum.
![default](https://user-images.githubusercontent.com/20744846/42820328-8ddeb36a-89de-11e8-88d0-8ccf0557b0f1.png)

**Comment by jtommy** [comment]
@alexandrsmirnov93 You might implement it using `header` slot. 
At the moment we aren't going to add a similar behaviour into the component.
