### ISSUE TITLE
Don't select row on check row

### ISSUE THREAD

**Issue by koraniar** [buefy/buefy#916]
### Description

I have a list of devices within a b-table component, the header of the table is
```
<b-table
        :data="filteredData"
        hoverable
        :checked-rows.sync="checkedRows"
        mobile-cards
        checkable
        pagination-simple
        :paginated="pagination"
        :per-page="maxQuantity"
        :selected="current"
        default-sort="name"
        @select="selectedRow"
        @check="checkDevice">
```
the problem is that when I check a row, this row is become selected, 
What is the correct way to keep the same row selected regardless of which row is become checked?

### Expected behavior

On check any row, keep the same row selected

### Actual behavior

On check any row, this row is become selected

**Comment by jtommy** [comment]
@koraniar You might use `is-row-checkable` so you have a disabled checkbox or on select event when the row must to be selected push it into `checkedRows` every time

**Comment by koraniar** [comment]
@jtommy I don't want disable the checkbox in some rows, I want that the user can check all rows if he want, but when he check a row I don't want that row to be selected, I want that the row become selected when the user clicks the row and not in the checkbox of the row

**Comment by jtommy** [comment]
@koraniar Do you mean for example https://codepen.io/anon/pen/xJdwPY?&editors=101 ?

**Comment by koraniar** [comment]
@jtommy yeah, it will work, thank you!

**Comment by koraniar** [comment]
@jtommy I have a bug that I cannot resolve, if you first select a row and after it you check the same row, it breaks
