### ISSUE TITLE
Display event names in datepicker

### ISSUE THREAD

**Issue by apocalyarts** [buefy/buefy#917]
Please delete, if inappropriate :)

Just wanted to chime in that it would be great to pass events with a name attribute to a datepicker component and display the event names in a tolltip when hovering over the event date.

Is this something you'd consider?

**Comment by apocalyarts** [comment]
Well if it's "just a datepicker", then wouldn't the events property already be out of scope? :D

**Comment by jtommy** [comment]
Events are only markers but we should think if tooltip is a good solution about UI and in way not to weight the component.
