### ISSUE TITLE
Attempt to delete tab in b-tabs structure gives error

### ISSUE THREAD

**Issue by robogeek** [buefy/buefy#918]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.3.3]
**OS/Browser**: The code is running inside Electron 1.7.5 using Electron-Vue 1.0.6

### Description

I want to make an application with a tabbed interface, where the user can add and remove tabs at will.  In my test application I can add a new tab simply by pushing an item into the tabs array.

The code is below.  It includes a little form to add a new tab - it works by pushing the object into the tabs array.  

For deleting a tab, I added a button to the tab, and in the `@click` handler used `this.tabs.slice` to remove an element from the tabs array.  Okay, I see that I've since changed to use `this.$delete` because maybe this would have some additional compatibility.  Using `this.$delete` or `this.tabs.slice` should be the same.  I found this recommended in several places as the way to go.

This works except for removing the last tab.   For removing the last tab I get this error:

```
[Vue warn]: Error in callback for watcher "tabItems": "TypeError: Cannot set property 'isActive' of undefined"

found in

---> <BTabs>
       <LandingPage> at src/renderer/components/LandingPage.vue
         <Wsbrowse> at src/renderer/App.vue
           <Root>
warn @ vue.esm.js?efeb:591
logError @ vue.esm.js?efeb:1737
globalHandleError @ vue.esm.js?efeb:1732
handleError @ vue.esm.js?efeb:1721
run @ vue.esm.js?efeb:3235
flushSchedulerQueue @ vue.esm.js?efeb:2981
(anonymous) @ vue.esm.js?efeb:1837
flushCallbacks @ vue.esm.js?efeb:1758
vue.esm.js?efeb:1741 TypeError: Cannot set property 'isActive' of undefined
    at VueComponent.tabItems (/Volumes/Extra/akasha-tools/wsbrowse/node_modules/buefy/lib/index.js:1)
    at Watcher.run (vue.esm.js?efeb:3233)
    at flushSchedulerQueue (vue.esm.js?efeb:2981)
    at Array.eval (vue.esm.js?efeb:1837)
    at MessagePort.flushCallbacks (vue.esm.js?efeb:1758)
logError @ vue.esm.js?efeb:1741
globalHandleError @ vue.esm.js?efeb:1732
handleError @ vue.esm.js?efeb:1721
run @ vue.esm.js?efeb:3235
flushSchedulerQueue @ vue.esm.js?efeb:2981
(anonymous) @ vue.esm.js?efeb:1837
flushCallbacks @ vue.esm.js?efeb:1758
```

From reading the code I see the problem is in this watch function

```
tabItems() {
                if (this.tabItems.length) {
                    this.tabItems[this.activeTab].isActive = true
                }
            }
```

The variable `this.activeTab` probably has a value that is now beyond the end of the array, and therefore is getting an undefined, which throws the above error.

### Steps to reproduce

First - get the scaffold application:  `vue init simulatedgreg/electron-vue wsedit`

Second -- install Buefy: `npm install buefy --save`

Third, replace the content of LandingPage.vue with the following.

The result is an Electron app and you run using - `npm run dev`.  It should be possible to use a different method to initialize a simple Vue app and to use the following component definition there.  I do not think the issue is related to Electron.

```
<template>
  <div id="wrapper">
    <section>
        <b-tabs v-model="activeTab" type="is-boxed" ref="btabs">
          <b-tab-item  v-for="(item, index) in tabs" v-bind:key="index">
            <template slot="header">
                <b-icon icon="information-outline"></b-icon>
                <span> {{ item.label }}  </span>
                <button  class="button is-medium is-primary" @click="closeTab(index)">
                    <b-icon icon="close-box-outline"></b-icon>
                </button>
            </template>
            <span v-html="item.body"></span>
          </b-tab-item>
        </b-tabs>
    </section>
    <section class="newTabForm">
        <b-field label="id">
            <b-input v-model="newId"></b-input>
        </b-field>
        <b-field label="label">
            <b-input v-model="newLabel"></b-input>
        </b-field>
        <b-field label="body">
            <b-input maxlength="200" type="textarea" v-model="newBody"></b-input>
        </b-field>
        <button class="button is-medium is-primary"   @click="addNewTab">Add</button>
    </section>
  </div>
</template>


<script>

export default {
  name: 'landing-page',
  methods: {
      addNewTab() {
        this.tabs.push({
          id: this.newId,
          label: this.newLabel,
          body: this.newBody
        });
        this.newId = "";
        this.newLabel = "";
        this.newBody = "";
      },
      closeTab(event) {
        console.log(`LandingPage closeTab  ${event}`);
        
        let index2close = event;

        this.activeTab = 0;
        this.$delete(this.tabs, index2close);
      }

  },
  data() {
      return {
        activeTab: 0,
        newId: "",
        newLabel: "",
        newBody: "",
        tabs: [
          {
            id: "videos",
            label: "Videos",
            body: `Tab 1`
          },
          {
            id: "show-books",
            label: "Show Books",
            body: `Tab 2`
          },
          {
            id: "music",
            label: "Music",
            body: `Tab 3`
          },
          {
            id: "pictures",
            label: "Pictures",
            body: `Tab 4`
          }
        ]
      }
    }
}
</script>

<style>
.newTabForm {
  margin: 10px;
}
</style>

```

### Expected behavior

I am expecting a method for removing tabs from a `<b-tabs>` structure

According to documentation I've seen it should be possible to do so using `.slice`

### Actual behavior

See above for the error

**Comment by jtommy** [comment]
@robogeek You have to add `.stop` on click event because remove button is into tab and that event call your method and default `changeTab`.

**Comment by joris** [comment]
I think this truly is a bug.
I believe it should never _never_ be possible for `activeTab` to point to an undefined tab.

For example, **given the following template:**
```
<b-tabs>
  <b-tab-item v-for="persons in people" :key="person.id">
    {{ person.name }}
  </b-tab-item>
</b-tabs>
```
**and the following data:**
```
  data: function(){
    return {
      people: [{id: 1, name: "John"}, {id: 2, name: "James"}],
    }
  }
```
This will result in 2 tabs displayed (one for John and one for James).

**If I then:**
1) Click/activate the second tab, the `activeTab` will contain `1`, and then I:
2) Programmatically replace `people` with an array that contains only a single person (for example: `people = [{id: 3, name: "Amie"}]`)
then Buefy throws an error because the `activeTab` is still pointing to the second item in `people` which is now undefined. So basically every time the Buefy code accesses `this.tabItems[this.activeTab].some_attribute_or_function`, it will explode.

**Instead** I would expect Buefy to either reset the activeTab in a better way, or simply *never attempt to access* a tabItem that is undefined.

**Comment by jtommy** [comment]
@joris Maybe we might check before but anyway you should update the current selected tab.

**Comment by jtommy** [comment]
@joris Active tab index check added
