### ISSUE TITLE
"TypeError: Cannot read property 'toLowerCase' of undefined" in Nuxt project with only Buefy imported

### ISSUE THREAD

**Issue by danielhep** [buefy/buefy#919]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.16
**OS/Browser**: Mac OS High Sierra, Google Chrome

### Description

Using Nuxt JS and Nuxt Buefy (0.1.0). When I import the nuxt-buefy module I get the following error 
messages in the console when attempting to load the website:

`TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.<anonymous> (/Users/danielhep/Documents/GitHub/PineapplePad/node_modules/buefy/lib/index.js:1:43765)`
...

### Steps to reproduce

Install Nuxt using their [starter template](https://github.com/nuxt-community/starter-template). 
Install Nuxt-Buefy and Buefy.
Add modules: ["nuxt-buefy"] to the nuxt config. 

I've also found this occurs without Nuxt-Buefy if I just import the buefy plugin as a vue plugin: Vue.use(Buefy);

### Expected behavior

No errors, website to load properly.

**Comment by jtommy** [comment]
@danielhep What components are you using?

**Comment by danielhep** [comment]
I ended up just moving on from Nuxt. I think the issue was a conflict with AWS Amplify library, which doesn't really support SSR. I'm not sure why it caused Buefy to throw errors, but I'm pretty sure they were related.
