### ISSUE TITLE
add customization support via css variables

### ISSUE THREAD

**Issue by kmohrf** [buefy/buefy#920]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.16
**OS/Browser**: Chromium 67.0.3396.99 Arch Linux

### Description

Thank you for your work on Buefy. It’s a great addition to the vue ecosystem!

It would be nice if Buefy would support CSS variables for customization. Currently the recommended way of modifying colors or other internal variables is including the sass sources and overwriting the sass variables. While this might be sufficient for complex build chains or SASS users it’s a little bit much for those who don’t use SASS as preprocessor (given the fact that tools like vue-cli only allow for one preprocessor to be selected) or only want to drop in Buefy and change some colors.

There’s a neat little PostCSS plugin called [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) that generates properties with css variables + their appropriate fallback…
```css
# so that
background-color: var(--color-primary, #f00f00);
# becomes
background-color:  #f00f00;
background-color: var(--color-primary, #f00f00);
```

Given the fact that global support for CSS variables is somewhere around 87% it might even be feasible to switch to them for good.

**Comment by jtommy** [comment]
There was an official Bulma tweet about https://twitter.com/jgthms/status/1018425250390953984?s=20. 
We could introduce css variables if Bulma will add these.
