### ISSUE TITLE
styling each tag individually in taginput

### ISSUE THREAD

**Issue by yipcma** [buefy/buefy#921]
Not a bug report, but a feature request:

Right now the styling of tags is uniform. It'd be great to have the ability to style individually based on the data.

**Comment by jtommy** [comment]
@yipcma It's no a good idea styling tags by data. The idea is no bad we cannot make assumptions about data

**Comment by yipcma** [comment]
not sure why it's not feasible or desirable given it's been done here https://vuetifyjs.com/en/components/combobox
