### ISSUE TITLE
Check all rows buefy table

### ISSUE THREAD

**Issue by koraniar** [buefy/buefy#922]
### Description

I have a buefy table paginated, when I check the checkbox in the header it select all rows of the current page, not all rows (all pages),
I try to check all rows manually but I have not made it work, here is an example https://codepen.io/koraniar/pen/bjWwjr?editors=1010

### Expected behavior

Check all rows of all pages

### Actual behavior

Check only the rows of the current page

**Comment by jtommy** [comment]
@koraniar It's the default behaviour.
You might listen check-all event and add all rows to checkedRows

**Comment by koraniar** [comment]
@jtommy I described on the Codepen link that I am trying to check all rows manually listening `check-all` event and adding all rows to `this.checkedRows` but it doesn't work, however I had created an issue here https://github.com/buefy/buefy/issues/924 explaining better this issue
