### ISSUE TITLE
checked-rows.sync doesn't sync

### ISSUE THREAD

**Issue by koraniar** [buefy/buefy#924]
### Description

I have a buefy table paginated, when I check the checkbox in the header it select all rows of the current page, not all rows (all pages),
I try to check all rows **manually** but I have not made it work, here is the code https://codepen.io/koraniar/pen/bjWwjr?editors=1010

### Expected behavior

Check all rows of all pages on `this.checkedRows = this.data`

### Actual behavior

Only check the rows of the current page, no matter what data is on `checkedRows`

**Comment by jtommy** [comment]
@koraniar I've just seen your code and the component is ok but your update is overwritten by default prop update (sync).
You might remove sync modifier or use $nextTick to update https://codepen.io/anon/pen/qyjzpj?editors=1010

**Comment by rcoundon** [comment]
I'm trying to achieve the same but the @check-all event only includes the rows that were checked in the current page.  Is this intentional?  If so, what's the recommended way of determining what's clicked in subsequent pages when using searchable to filter the data?
