### ISSUE TITLE
Datepicker display date is off by one day

### ISSUE THREAD

**Issue by arunkarottu** [buefy/buefy#925]
<img width="548" alt="screen shot 2018-07-24 at 9 50 59 am" src="https://user-images.githubusercontent.com/2192225/43142806-3e79d126-8f27-11e8-8d50-f305bc7f3f0b.png">

### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**: Chrome 67.0.3396.99

### Description

The displayed date on datepicker seems to be a day off from the selected date. There is a closed issue on this from 2017 (#275).

### Steps to reproduce

You can reproduce it on the [datepicker demo page](https://buefy.github.io/#/documentation/datepicker). See screenshot above.

**Comment by wopian** [comment]
It has been fixed (https://github.com/buefy/buefy/issues/275#issuecomment-401095658), but there hasn't been a new release yet

**Comment by BigWillie** [comment]
When will this be released?

**Comment by jtommy** [comment]
As soon as possible. There is a beta version anyway buefy@beta

**Comment by jamesburrow23** [comment]
What is the status of this fix being released?

**Comment by jtommy** [comment]
@jamesburrow23 It's fixed since 0.6.7 version

**Comment by vasoft** [comment]
I am using 0.7.3 version, and still have this issue. This is my situation

`//Parent.vue
<template>
    <ChildComponent v-model="selectedDate" @input="change"></ChildComponent>
</template>
<script>
 data() {
            return {
                selectedDate: null
            }
        },
 methods: {
            change(){
                console.log(this.selectedDate)   // displays the selected date off by one day
            }
        },
</script>

//ChildComponent.vue
<template>
     <b-datepicker v-model="fieldValue" @input="change"></b-datepicker>
</template>
<script>
 data() {
            return {
                fieldValue: null
            }
        },
 methods: {
            change(){
                console.log(this.fieldValue)   // displays the selected date correctly
                this.$emit('input', this.fieldValue)
            }
        },
</script>`

**Comment by vasoft** [comment]
I am using 0.7.3 version, and still have this issue. This is my situation

```html
// Parent.vue
<template>
    <ChildComponent v-model="selectedDate" @input="change"></ChildComponent>
</template>
<script>
 data() {
            return {
                selectedDate: null
            }
        },
 methods: {
            change(){
                console.log(this.selectedDate)   // displays the selected date off by one day
            }
        },
</script>

// ChildComponent.vue
<template>
     <b-datepicker v-model="fieldValue" @input="change"></b-datepicker>
</template>
<script>
 data() {
            return {
                fieldValue: null
            }
        },
 methods: {
            change(){
                console.log(this.fieldValue)   // displays the selected date correctly
                this.$emit('input', this.fieldValue)
            }
        },
</script>```

**Comment by abacram** [comment]
Make sure your backend is configured with the same timezone because if not, your dates/datetimes will be converted. In my case my front is 1 hour plus my back timezone and when i send a datetime, back decrements 1 hour and by this cause, it saved a day off.

Hope it helps.
