### ISSUE TITLE
How do I custom the Form validator function?

### ISSUE THREAD

**Issue by yanlusu** [buefy/buefy#926]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.7]
**OS/Browser**:[Chrome, FireFox]

### Description
I found that form validator using html5 `checkValidity()` function in  `checkHtml5Validity()` of file `FormElementMixin.js`, but these inline rules are not satisfied, so I want to custom constraints, but how to do it?

not bug , just an enhance requirement.
### Steps to reproduce
none

### Expected behavior
I want to set validator of Form data, just provide an entrance to inject it.
### Actual behavior
`el.checkValidity()` in function `checkHtml5Validity()` can be replaced by custom validate function.

thank you.

**Comment by yanlusu** [comment]
now I using custom component and mixin Buefy.Input to get it, but it's not a good solution I think.
```javascript
Vue.component('ValidateInput', {
    mixins: [Buefy.Input],
    methods: {
        /**
         * Check HTML5 validation, set isValid property.
         * If validation fail, send 'is-danger' type,
         * and error message to parent if it's a Field.
         */
        checkHtml5Validity() {
            if (this.$refs[this.$data._elementRef] === undefined) return

            const el = this.$el.querySelector(this.$data._elementRef)

            let type = null
            let message = null
            let isValid = true
            if (!el.checkValidity()) {
                type = 'is-danger'
                message = 'Custom' + el.validationMessage
                isValid = false
            }
            this.isValid = isValid

            if (this.parentField) {
                // Set type only if not defined
                if (!this.parentField.type) {
                    this.parentField.newType = type
                }
                // Set message only if not defined
                if (!this.parentField.message) {
                    this.parentField.newMessage = 'Custom' + message
                }
            }

            return this.isValid
        }
    },
});
```

**Comment by jtommy** [comment]
@yanlusu https://github.com/buefy/buefy/issues/370
Buefy doesn't provide a validator library so you might use an external library.

**Comment by yanlusu** [comment]
No, Buefy has provide default validator using html5 default validate function.
I just want it to be customed.
OK, your pleasure.

**Comment by jtommy** [comment]
Yes but we didn't think to provide a way to customize. It's only a quick way to see a field with error style

**Comment by yanlusu** [comment]
ok, Got It!
Sorry to bother you.
