### ISSUE TITLE
Datepicker - feature request to allow the selection of a date range

### ISSUE THREAD

**Issue by acidjazz** [buefy/buefy#932]
Pretty simple, be able to select a range of dates, maybe even its own component Rangepicker

example:

https://flatpickr.js.org/examples/#range-calendar

**Comment by jtommy** [comment]
@acidjazz Contributions are welcome! Do you have a your implementation about it?

**Comment by acidjazz** [comment]
@jtommy no but i'm going to give it a shot!

**Comment by afifsohaili** [comment]
@acidjazz @jtommy I have made an attempt for this. 😁

**Comment by Dave3of5** [comment]
Any update on this seems most of the work is done ?

**Comment by service-paradis** [comment]
@jtommy 
Just wanted to know if you have any update about hte PR related to this issue, Woul really love to use it!

**Comment by service-paradis** [comment]
This can be closed (https://buefy.org/documentation/datepicker#select-a-range-of-dates)
Thanks to @afifsohaili

**Comment by jtommy** [comment]
Sure!
