### ISSUE TITLE
b-autocomplete - How to bind ID value but Display name value 

### ISSUE THREAD

**Issue by Olusiji** [buefy/buefy#934]
I know there must be a way to do this but i can't seem to figure it out. My data is an array of objects, each containing an integer ID and a String name. Like so
vendor : {
     name : 'Vendor Name',
     id: 1
}

Although documentation for b-autocomplete says that the field property for b-autocomplete 

> Property of the object (if data is array of objects) to use as display text, and to keep track of selected option

I would like to use the name property as the display text but the id as the selected option.

Any help will be appreciated.

Here is my code at the moment.
`<b-field label="Select Vendor" class='column is-5'>
          <b-autocomplete
                   name = "VENDOR"
                   v-model = "vendor_id"
                   :data = "vendors"
                   placeholder = "Select"
                   field = "id"
                   icon = "magnify"
                   :open-on-focus= true
                   @select="option => selected = option">
            </b-autocomplete>
 </b-field>`

**Comment by jtommy** [comment]
@Olusiji select event has a parameter and it's the selected object option

**Comment by Olusiji** [comment]
@jtommy I don't quite understand how to make it work as you have suggested. Please can you explain further.

I've created a pen here based on my understanding so far.
[](https://codepen.io/anon/pen/rrrYLx?editors=1011)

**Comment by jtommy** [comment]
@Olusiji `v-model` is a binding of text value (what do you see as option). You have to listen `select` event and save id from object but in other variable that you aren't using as `v-model`

**Comment by Olusiji** [comment]
@jtommy Okay. That makes sense. Thank you very much.

**Comment by lnb596844** [comment]
I'm also facing the same problem, is there any working fiddle?

**Comment by LarBearrr** [comment]
@Olusiji Did you ever figure this out? I'm having the same problem. See my issue #1204

I'm passing an array of objects from my backend. I need to display/search the value (Red, Green, Blue, etc.) but save the ID (1,2,3, etc.) to the database.

I checked out [your pen](https://codepen.io/anon/pen/rrrYLx?editors=1011) which helped some, but it still seems like the `v-model` value is what is actually submitted as part of the form.

Any help is appreciated. Thank you.

**Comment by MaxRadons** [comment]
`			
<b-autocomplete
    v-model="$v.color.$model"
    placeholder="choose colors"
    field="name"
    :data="colors"
    @select="option => form.color_id = option.id"
    >
</b-autocomplete>
`
Where colors = { { name : red , id = 1},  {name : green , id = 2} , ... } 
All variables in form get submitted to the server, the variable $v.color.$modell is only for verification with Vuelidate, it will be populated with the name, but form.color_id will be populated with the id.

**Comment by jtommy** [comment]
@MaxRadons put the selected Id in a input type hidden

**Comment by hosaka555** [comment]
I had same problems but I found the solution.

In `b-autocomplete tag`, you can use  `template tag` that has `slot-scope="props"`.

```js
        <b-field label="Find a movie">
            <b-autocomplete
                :data="data"
                placeholder="e.g. Fight Club"
                field="title"
                :loading="isFetching"
                @typing="getAsyncData"
                @select="option => selected = option">

                <template slot-scope="props">
                    <div class="media">
                        <div class="media-left">
                            <img width="32" :src="`https://image.tmdb.org/t/p/w500/${props.option.poster_path}`">
                        </div>
                        <div class="media-content">
                            {{ props.option.title }}
                            <br>
                            <small>
                                Released at {{ props.option.release_date }},
                                rated <b>{{ props.option.vote_average }}</b>
                            </small>
                        </div>
                    </div>
                </template>
            </b-autocomplete>
        </b-field>
```


> {{ props.option.title }}

In this example,
you cloud see `object title` in suggestion list on your display.

Please check [buefy documents](https://buefy.org/documentation/autocomplete/#async-with-custom-template) if you would like to know more.

Thank you.
