### ISSUE TITLE
Datepicker: Day shown in display is off by one day ( v-model value is ok )

### ISSUE THREAD

**Issue by compmeist** [buefy/buefy#937]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.X.X]
**OS/Browser**: Chrome, Firefox, Edge

### Description
Datepicker: Day shown in display is off by one day

### Steps to reproduce

Click on a day in calendar.

### Expected behavior

the select date shown in input element.

### Actual behavior

One day before is shown, but v-model date is correct.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/925
