### ISSUE TITLE
Checkable Table. Sync rows weird behaviour

### ISSUE THREAD

**Issue by akrz** [buefy/buefy#943]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.16
**OS/Browser**: Ubuntu / Chrome

### Description

If I initialize the table with a default columns array. It will not render the checked in the table but it will push it to the checked array.
I'm doing it this way because the data of the table will be fetched from an API but I want some values initialized without fetching an external resource.

![image](https://user-images.githubusercontent.com/1325627/44211829-4442af80-a140-11e8-9432-1667acbee0ce.png)
Codepen: https://codepen.io/anon/pen/NBZaqw?editors=1010

### Steps to reproduce

N/A

### Expected behavior

Checked values will be rendered in the table (checkbox checked)

### Actual behavior

The checked array doesn't render in the table

**Comment by jtommy** [comment]
@akrz You have to use `custom-is-checked` prop because they are different instances.
For example `:custom-is-checked="(a,b)=>a.id === b.id"`
