### ISSUE TITLE
B-Modal is-clipped/is-noscroll add by default IE 11

### ISSUE THREAD

**Issue by y-sanchez** [buefy/buefy#944]
### Overview of the problem

**Buefy** version: [0.6.6]
**Bulma** version: [0.7.1]
**Vuejs** version: [X.X.X]
**OS/Browser**: IE 11

### Description

In IE the b-modal component add by default the class is-clipped/is-noscroll  even if the model isnot active 

### Steps to reproduce

Bug present in this page: 
https://buefy.github.io/#/documentation/modal 

1) open : Programmatic -> Launch card modal ( Component )
2) close modal

The scrool bar does not appear

### Expected behavior

The scroll bar is visible

### Actual behavior

The scrool bar does not appear

**Comment by neyb** [comment]
IE11 does not support force argument on toggle : https://developer.mozilla.org/fr/docs/Web/API/DOMTokenList/toggle#Compatibilit%C3%A9_des_navigateurs

this is used here:
- https://github.com/buefy/buefy/blob/dev/src/components/modal/Modal.vue#L182
- https://github.com/buefy/buefy/blob/dev/src/components/modal/Modal.vue#L186

... And probably in other places.

**Comment by patrickabkarian** [comment]
https://github.com/jgthms/bulma/commit/19704daefd86c3cc9c69956b257f39256814bf3a

i think this fixed it.
