### ISSUE TITLE
Timepicker dropdown not closing onBlur

### ISSUE THREAD

**Issue by wontwon** [buefy/buefy#945]
### Overview of the problem
**Buefy** version: 0.6.6
**Vuejs** version: 2.5.16
**OS/Browser**: Chrome latest

### Description
Upon selecting hour and minutes in the time selector and clicking outside of the input, the timepicker dropdown does not close. The timepicker input is being used on top of "vue2-slideout-panel": "^0.10.0".

### Steps to reproduce

Add timepicker component onto slideout panel. Open panel, select time in timepicker. Only when clicking back onto the input, the timepicker dropdown will close.

### Expected behavior
After selecting time and clicking outside the input, the time selector dropdown should disappear

### Actual behavior
The time picker dropdown remains on screen

![2018-08-17 00 46 53](https://user-images.githubusercontent.com/3239936/44248281-a25ea980-a1b7-11e8-8871-d4a838ae6cfc.gif)

![2018-08-17 00 51 44](https://user-images.githubusercontent.com/3239936/44248309-cb7f3a00-a1b7-11e8-8eae-9f2bb76b44f8.gif)

**Comment by wontwon** [comment]
Bumping this

**Comment by wontwon** [comment]
Closing Issue - Got response from @jtommy in regards to this being fixed on next release

**Comment by jtommy** [comment]
Try buefy@beta, it will be the next official release. Anyway we think to release 0.6.7 soon

**Comment by wontwon** [comment]
Can't seem to figure how to use the close method in beta

**Comment by wontwon** [comment]
Can't seem to figure how to use the close method in beta
