### ISSUE TITLE
How to include html inside a b-table cell?

### ISSUE THREAD

**Issue by sinanerdem** [buefy/buefy#946]
I would like to insert html data inside a cell as:

Line 1 text <br /> Line 2 text.

When I enter data like this, the entire string is rendered as is inside table. Is there a way to properly include html tags inside a cell?

**Comment by jtommy** [comment]
@sinanerdem Could you provide us an example ?

**Comment by ovp87** [comment]
@jtommy This is an old issue, but i'm wondering about this myself.

In my case, id like one of the cells on each row to consist of an href. But the documentation isnt really clear on how i'd go about this.
