### ISSUE TITLE
Allow prompt dialog's input to be not required.

### ISSUE THREAD

**Issue by Ovyerus** [buefy/buefy#947]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.17]
**OS/Browser**: Windows 7/Firefox 61

### Description

It'd be nice to allow dialogs to be able to be not required, as some things may use it out of simplicity and not wanting to use a modal which can get complicated for simple things. I've tried various stuff with `inputAttrs` but to no avail.

**Comment by Ovyerus** [comment]
Please ignore this or smth. The view didnt properly reload until after I made this and now I look like an idiot 🙃

**Comment by alessandrobelli** [comment]
I came here because I didn't know the solution, but it's actually easy, just set 
`required: false` in inputAttrs, for example:
`inputAttrs: {
placeholder: '',
                maxlength: 20,
                required: false
            }`
