### ISSUE TITLE
Smaller breakpoint for mobile version of dropdown.

### ISSUE THREAD

**Issue by mateuswetah** [buefy/buefy#950]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.9.3]
**OS/Browser**: Firefox/Linux Ubuntu

### Description
The `mobile-modal` feature for drowpdowns is awesome, but it's breakpoint seems a bit "early" to me. I tested here and it goes popup from around 1088px. This resolution is surely enough for displaying small content dropdowns, such as menus. So I wonder if you could make it smaller (1024, 768?) or even better, set an option for the constructor so we can decide that by ourselves?

### Steps to reproduce

1. Open any dropdown (that hasn't had the `mobile-modal` feature disabled) on a screen smaller than 1088px; You can check that on Buefy's official codepen: https://codepen.io/pen?editors=1010

### Expected behavior
Feature available from a smaller breakpoint, such as 768px or 1024px;

### Actual behavior
Unnecessary popup version of small dropdowns on a large screen.

**Comment by service-paradis** [comment]
Buefy use the Bulma mixin `=touch` for the breakpoint. Using it, it will use the `$desktop` variable (`@media screen and (max-width: $desktop - 1px)`).

By customizing the `$desktop` variable, you can control the mobile dropdown breakpoint. Please note that this will also affect other component using this variable and the mixin.

We could maybe add a SASS variable like`$dropdown-mobile-breakpoint: $desktop - 1px !default;` so people would be able to customize the breakpoint if needed without being a breaking change.
