### ISSUE TITLE
Modal Close Event Handle

### ISSUE THREAD

**Issue by manofthefort** [buefy/buefy#951]
### Overview
I am attempting to "daisy chain" 2 modals.  What I mean by that is when modal number 1 closes the parent component will check some conditions against the state and if the conditions are true then open a second modal.

Perhaps I can use the modal close event but I am unsure on how to handle it from the parent component JS.

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.17]
**OS/Browser**: Chrome

### Description

Here is the parent component method that opens the first modal:

                // Open the Stage Location Modal
                this.$modal.open({
                    parent: this,
                    component: stageModal,
                    hasModalCard: true,
                    canCancel: false,
                    events: {
                        closeModal() {
                            console.log('Closing Stage Modal')
                            if (this.stageLocation.Location && this.stageLocation.PickByLoad) {
                                this.getLoads().then(() => {
                                    if (this.loads.length > 0) {
                                        // Open the Load Modal
                                        this.$modal.open({
                                            parent: this,
                                            component: loadModal,
                                            hasModalCard: true,
                                            canCancel: false
                                        })
                                    }
                                })
                            }
                        }
                    }

Here is the child modal component close method (setLocation is it specifically):

         methods: {
            ...mapActions({
                getScrapLocations: 'getScrapLocations',
                setStageLocation: 'setStageLocation'
            }),
            setLocation(location) {
                this.setStageLocation(location)
                this.$emit('close-modal')
                this.closeModal()
            },
            closeModal() {
                this.$emit('close')
            }
        },

**Comment by manofthefort** [comment]
I was able to handle the close event by simply replacing the custom "closeModal" with just "close".  Only issue is that anything inside the handler of the close event is not aware of "this" (it lost the component scope).

**Comment by brunokunace** [comment]
Hi Hi!

I try to make same thing, look:

```
  methods: {
    recipesModal () {
      this.$modal.open({
        parent: this,
        component: Recipes,
        props: {
          recipes: this.recipes,
          analized: this.analized
        },
        events: {
          recipeAnalized () {
            console.log(this)
            this.analized = true
          }
        }
      })
    }
  }
```
i receive correctly a event, but i dont have a bind of **this**, i cant change my data on parent (my data "analized" is the same on the prop)

have way to make it? v-model? sync?

Thanks!

**Comment by brunokunace** [comment]
*Update

i can use make a `const self = this` inside recipesModal() and self.analized. Its sounds ugly.

Have way to bind this inside events OR make way to use arrow?

**Comment by jtommy** [comment]
@brunokunace You might use arrow function for `events` prop
