### ISSUE TITLE
this.$toast is undefined

### ISSUE THREAD

**Issue by Vitorbnc** [buefy/buefy#955]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.17]
**OS/Browser**: Windows 10/Firefox 61
* Using Vuejs Webpack template

### Description
I am getting `TypeError: _this.$toast is undefined` in this function inside a Vue component:

```
export default {
    methods:{
        logout: ()=>{firebase.auth().signOut().then(
            (err)=>this.$toast.open({message:'Erro:'+err.message,type:'is-danger'}),
            ()=>this.$router.replace('login')
       )}
    }
}
```
The component is used inside App.vue. 

I imported Buefy in main.js: 

```
import Buefy from 'buefy'
Vue.use(Buefy,{
  defaultIconPack: 'fas'
})
```

**Comment by MeikelLP** [comment]
Could you please provide a [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/)? Currently I cannot reproduce your issue with [this pen](https://codepen.io/anon/pen/bxdwdM?editors=1111).

**Comment by Vitorbnc** [comment]
I am using the Vue Webpack Template with `npm run dev` 
 I created a new project and 2 gists to reproduce the error: [App.vue](https://gist.github.com/Vitorbnc/61a4436270c4e0a89be1d01f0a3a3130) and [main.js](https://gist.github.com/Vitorbnc/6cea64a781009d6df6d7d38d524da04d)

Full instructions:
* Open bash on Win 10 and install vue-cli (not the latest @vue/cli version)
* `mkdir buefy-test`
* `vue init buefy-test`
* Use my _App.vue_ and _main.js_
* `npm run dev`

**Comment by jtommy** [comment]
@Vitorbnc You shouldn't use an arrow function as method. 
For example: 
```
methods:{
    logout() {this.$toast.open({message:'Erro:'+err.message,type:'is-danger'})}
  }
```

**Comment by MeikelLP** [comment]
you can read more about it [here](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks)

**Comment by Vitorbnc** [comment]
Thanks! I did as you said and it is working now.

**Comment by dmhendricks** [comment]
> You shouldn't use an arrow function as method.

Oddly, I was having the opposite issue. It worked after I converted it _to_ an arrow function.

This didn't work:
```
myPromise().then(function() {
    // Whatever
}).catch(function(error) {
    this.$toast.add({detail: error}); // $toast is undefined
});
```

This worked for me:
```
myPromise().then(function() {
    // Whatever
}).catch((error) => {
    this.$toast.add({detail: error});
});
```

**Comment by MeikelLP** [comment]
When you use an arrow function in JS the context is not changed. Thus `this` still applies to the old context. 

On the other hand if you use a `function ()` JS defines a new context. So your `this` is now something else
