### ISSUE TITLE
Datepicker date selected

### ISSUE THREAD

**Issue by BigWillie** [buefy/buefy#957]
Datepicker returns the wrong date - the previous day at 23:00hrs

Eg - I select 22nd, and the console logs the 21st 

Date 2018-08-21T23:00:00.000Z

How would I make it return the 22nd at 00:00:00
eg: Date 2018-08-22T00:00:00.000Z

**Comment by jtommy** [comment]
It's a date object. The date is correct, you have to format and/or parse it using external lib or its get functions.

**Comment by BigWillie** [comment]
But it doesn't match? its a day out?

**Comment by jtommy** [comment]
Did you try buefy@beta?

**Comment by BigWillie** [comment]
No... didn't know it existed
