### ISSUE TITLE
Programmatic Modal Slot 

### ISSUE THREAD

**Issue by sentriz** [buefy/buefy#959]
**Buefy** version: 0.6.6
**Vuejs** version: 2.5.17
**OS/Browser**: Linux/Chrome

### Description

Hello, is it possible to pass a slot component to a programmatic modal?
say I had the following:
```javascript
this.$modal.open({
    parent: this,
    component: MyComponent,
})
```
in a method, where `MyComponent` has a `<slot></slot>`.
Would something like a `slot: MySlotComponent` make sense? Along side `parent` and `component`

Thank you

**Comment by bennysalewski** [comment]
I also need this feature. I have written a modal component with slots (one main slot, several names slots) so it can reused in my project but now I have to write a new modal component for every modal although they share similarities.

Something like this:

`this.$modal.open({
    parent: this,
    component: MyComponent,
    slots: {
        footer: '<<template code>>' | Component,
        default: '<<template code>>' | Component,
        title: '<<template code>>' | Component
    }
})`

**Comment by hbracy** [comment]
Was this ever implemented?
