### ISSUE TITLE
b-icon are not reactive for FontAwesome

### ISSUE THREAD

**Issue by lunfel** [buefy/buefy#960]
### Overview of the problem

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.16]
**OS/Browser**:  Ubuntu/Chrome 64

### Description

Buefy icons are not properly reactive. When using v-if or v-bind to change b-icon, FontAwesome will not render the icons properly

### Steps to reproduce

```
// Template section
<b-icon v-if="value === 0" pack="far" icon="circle" type="is-primary" />
<b-icon v-if="value === 1" pack="far" icon="sync" type="is-primary" />
<b-icon v-if="value === 2" pack="far" icon="check-circle" type="is-success" />

<button @click="value = (value + 1 % 3)">Change value</button>

// script section

export default {
    data () {
        return {
            value: 0
        }
    }
}
```

1. With a Buefy project and FontAwesome setup add the previous code to a component
2. Change the value of `value` and see the b-icon not rendering properly

### Expected behavior

Icons render properly and reactively

### Actual behavior

First visible icon renders ok and then others don't render properly

### Solution

FontAwesome provides a component to fix that problem that I think should be integrated in some way to the Buefy project: https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs

Related to this issue: https://github.com/FortAwesome/Font-Awesome/issues/12552

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/pull/1073
