### ISSUE TITLE
Dialog is broken in IE11

### ISSUE THREAD

**Issue by vladkosarev** [buefy/buefy#961]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: 2.5.17
**OS/Browser**: Win10/IE11

### Description

Dialog behaves in a strange way in IE11. Instead of just closing it scrolls down the page and removes vertical scroll.

### Steps to reproduce

1. Go to https://buefy.github.io/#/documentation/dialog in IE11
2. Click Launch Alert (default)
3. Click OK

### Expected behavior

Expected modal to close and nothing else

### Actual behavior

Page scrolls to the bottom and vertical scrollbar disappears

![buefydialogbug](https://user-images.githubusercontent.com/1223487/44685112-a640c600-aa18-11e8-971a-0ac7de92b928.gif)

**Comment by sn0rcha** [comment]
Confirmed here as well.
