### ISSUE TITLE
Datepicker selects the wrong date

### ISSUE THREAD

**Issue by zackgemmell** [buefy/buefy#966]
### Overview of the problem

**Buefy** version: 0.6.6
**Vuejs** version: Unknown
**OS/Browser**: MacOS/Chrome

### Description

Date selection is set to the day before the selected date.

### Steps to reproduce

Step 1: https://buefy.github.io/#/documentation/datepicker

Step 2: Select date from the first datepicker.

### Expected behavior

The correct date should be selected.

### Actual behavior

The day prior to the selected date displays in the input.

Selected: 8/22/2018
Displayed: 8/21/2018

![aug-30-2018 15-33-01](https://user-images.githubusercontent.com/6632499/44883063-b94ad480-ac6a-11e8-873f-f440fcb29a77.gif)

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/925
