### ISSUE TITLE
Columns group component for table

### ISSUE THREAD

**Issue by ghost** [buefy/buefy#967]
### Overview of the problem
Good afternoon guys, this is not a Buefy problem, I just want to know if is possible render a component that represents a group of column inside a column.
Here is my code:

```
<template slot-scope="props">
  <b-table-column
    label="ID"
    width="100"
  >{{ props.row.item.id }}
  </b-table-column>

  <b-table-column label="Name">
    <a @click.stop.prevent="openDetailByName(props.row)">
      {{ props.row.item.name }}
    </a>
  </b-table-column>

  <item-column v-if="order.situation.id < 6" :itemInfo="props.row"/>
</template>
```

ItemColumn Component:
```
<template>
<div>
  <b-table-column
    numeric
    label="Quantity"
    width="60"
  >{{ itemInfo.item.quantity }}
  </b-table-column>

  <b-table-column
    centered
    label="Unit"
    width="100"
  >{{ itemInfo.unit.name }}
  </b-table-column>
</div>
</template>
```

This is just an exemple, We diceded to do in that way because, we have 3 kids of users and more than six situations, each user in each situation will see something different, but we have some common columns group, so Can I do it in that way? I have try it but my need to wrap my column in a b-table, so when I try it, it does not render and I look at inspect it have a div-table inside my table.
Print inspect.

![inspect](https://user-images.githubusercontent.com/40780187/44947358-84618d80-ade2-11e8-8876-dec5403ba9bc.png)

Thank you guys and sorry for my English, I am not a native.

**Comment by jtommy** [comment]
Because default slot of table renders only table column without any wrapper (div)
