### ISSUE TITLE
A good thing to do.

### ISSUE THREAD

**Issue by edwardmelody** [buefy/buefy#970]
### Need more features

**Buefy** version: [0.6.6]
**Vuejs** version: [2.5.17]
**OS/Browser**: Windows 10 Pro/Chrome

### Description

1. Could you add autofocus for b-input?
2. attributes "type, message" in b-field, Can I use them like a class or style of VueJS? such as...

```javascript
 <b-field :type="{'is-danger': isError}" :message="{'Something went wrong': isError}">...</b-field>
```

now I use them like this

```javascript
<b-field :type="(() => (isError? '' : 'is-danger'))()>...</b-field>
```

It's worked but it's not easy to use with many conditions. 

I hope this is a good point to do. Thank you.

Best regrads
Sorasak Siangsanan
Poor Programmer

**Comment by jtommy** [comment]
@edwardmelody 
1) What do you mean autofocus ?
2) Yes, we could think to improve `type` and `message` props
