### ISSUE TITLE
Add Tooltip to Input Field

### ISSUE THREAD

**Issue by evyasonov** [buefy/buefy#972]
Hi

Can you please advise how can I add a tooltip to input field?

Thanks in advace

**Comment by oldcastor** [comment]
There is one problem - when tooltip is active the input field looses expanded property (if exists ofc).
But you can always attach tooltip to a lable, for example https://codepen.io/anon/pen/gBvzVx

**Comment by bfabbri** [comment]
I'm facing exactly this situation: I need a tooltip in an input field without label that has the extended property.

Is there any solution to that?

**Comment by jtommy** [comment]
I'll refactor it in the next version

**Comment by RonWalker22** [comment]
Updates?

**Comment by lifenautjoe** [comment]
Hi there. Any chances of this happening? We would be happy to sponsor a couple hours of work on this :-)

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/f0cfa37b064b4aa43d4aa698ffdeffa30a85b0fd

**Comment by tesis** [comment]
Hi,
I'm not sure if this is solved - or I understood the issues you experienced, but if I appended a tooltip to a b-field,
the input field shifts. So I ended up with something like that:

```
       <b-field
          horizontal
        >
          <template v-slot:label>
           A Name
            <b-tooltip
              position="is-right"
              multilined
              append-to-body
            >
              <b-icon icon="mdi mdi-information-outline" size="is-small" />
              <template v-slot:content>
                <b>Lorem ipsum dolor sit amet</b>, consectetur warning elit. <i>Fusce id fermentum quam</i>.
              </template>
            </b-tooltip>
          </template>
          <b-input v-model="form.name" :placeholder="Form Name" />
        </b-field>
```
