### ISSUE TITLE
CDN file is missing

### ISSUE THREAD

**Issue by C-Higgins** [buefy/buefy#976]
https://unpkg.com/buefy/lib/buefy.min.css
`Cannot find "/lib/buefy.min.css" in buefy@0.6.7`

This is breaking css in all sites which did not specify a version from the CDN. Urgent to fix.

**Comment by ubirajaramneto** [comment]
We have had the same issue now in production.
We were importing the css file, and it was giving us some error about not finding the css file.

This is what we had before updating:
`import 'buefy/dist/buefy.css';`

After updating, we have changed to:
`import 'buefy/dist/buefy.css';`

In your case, I would try changing "lib" to "dist".

**Comment by ubirajaramneto** [comment]
As I suspected, if you go to: https://unpkg.com/buefy@0.6.7/dist/buefy.min.css, the css file is there
