### ISSUE TITLE
datepicker of month type

### ISSUE THREAD

**Issue by allstar** [buefy/buefy#977]
Hi i'm using 
 "nuxt-buefy": "^0.0.4",
 "vuetify": "^1.0.0"
 "nuxt": "^1.4.1",

### Description

Is it possible to have a month picker when using the : 
https://buefy.github.io/#/documentation/datepicker 

Something like : 
https://codepen.io/pen/?&editors=101

Thanks

**Comment by jtommy** [comment]
@allstar The link is not valid, could you explain it ?

**Comment by jtommy** [comment]
Added in 0.7.7
