### ISSUE TITLE
Buefy docs missing icons

### ISSUE THREAD

**Issue by imageplus** [buefy/buefy#981]
### Overview of the problem

**DOCS** version: v0.6.7

### Description

Font awesome icons on docs broken

### Steps to reproduce

Load the docs.

### Expected behavior
See icons

### Actual behavior

squares

**Comment by hkd987** [comment]
Looks like version .6.7 of buefy broke all icons as when I load the font-awesome cdn into my project all the icons now work. I think this is the same issue as the documentation.

**Comment by Remeic** [comment]
@imageplus Are you referring to the icons page in the documentation? more precisely to the section that refers to the awesome fonts?

**Comment by jtommy** [comment]
Double https://github.com/buefy/buefy/issues/995
