### ISSUE TITLE
How do I impose a static width on dropdown buttons?

### ISSUE THREAD

**Issue by turukawa** [buefy/buefy#983]
### Overview of the problem

**Buefy** version: v0.6.6
**Vuejs** version: v2.5.17
**OS/Browser**: Windows 10/Firefox/Chrome

### Description

Apologies if this is the wrong forum to ask this question but I've been banging my head on this problem for most of the day.

I am attempting to align a number of dropdowns for a set of filters for a search form. I need the dropdowns to be of uniform width (i.e. to take up the full width of a column), and to maintain a static width. Instead, the dropdowns are of arbitrary width and change width to fit the contents (i.e. with every selection change).

While it is possible to revert to the standard Bulma dropdown (which does maintain constant width), that styling is not as good as the Buefy dropdown.

### Steps to reproduce

1. I copied the code from the [Dropdown ](https://buefy.github.io/#/documentation/dropdown)page.
2. Modified the dropdown as follows:
```
<div class="column is-one-quarter">
<div class="field is-expanded">
  <div class="control is-expanded">
	  <b-dropdown position="is-bottom-right">
		  <button class="button" slot="trigger">
			  <b-icon icon="mdi mdi-store"></b-icon>
			  <span>{{ businessText }}</span>
			  <b-icon icon="menu-down"></b-icon>
		  </button>
		  <b-dropdown-item
			v-for="c in businessChoices"
			:key="c.value"
			@click.native="onGenericSelect('business', businessDefault, c)">
			  {{ c.text }}
		  </b-dropdown-item>
	  </b-dropdown>
  </div>
</div>
</div>
```
Note: it makes no actual difference whether the class "field" and class "control" are present. I keep hoping it will. I have moved these classes into almost every possible configuration with the various elements without any noteable change.

3. I import the selection list from a json file.

```
{ "business": 
	{ "data": 
		{ "value": null,
		  "default": "Business type",
		  "options": [
			{"text": "Any business", "value": null},
			{"text": "Industrial", "value": "Industrial"},
			{"text": "Office", "value": "Office"},
			{"text": "Retail", "value": "Retail"},
			{"text": "Leisure", "value": "Leisure"}
		  ]
		}
	}
}
```
4. Some screenshots... selecting "Retail":

![image](https://user-images.githubusercontent.com/998523/45244186-98c7ed80-b2ee-11e8-8405-174bbceba340.png)

And, selecting "Any business":

![image](https://user-images.githubusercontent.com/998523/45244204-b5642580-b2ee-11e8-8344-b7892fb36ff2.png)

And I've no idea why it's doing this when I shrink the screen size. I'd expect the columns to wrap within the parent:

![image](https://user-images.githubusercontent.com/998523/45244222-d2005d80-b2ee-11e8-9a80-8a429a8c3228.png)

### Expected behavior

I would expect that some application of class "is-fullwidth" or "is-expanded" would permit the dropdown to maintain a static width.

Note, this is the actual behaviour for all the dropdowns on the [Field](https://buefy.github.io/documentation/field) page, however, that code appears to be a minor modification of boilerplate Bulma format:
```
<b-field label="Subject">
	<b-select placeholder="Select a subject">
		<option value="1">Option 1</option>
		<option value="2">Option 2</option>
	</b-select>
</b-field>
```

### Actual behavior

Standard dropdown always changes width to fit the selected text. 

I should also highlight that this behaviour appears entirely in conformance with all the demo options displayed in the documentation. I'm just hoping there is some mechanism of achieving the behaviour I'd like.

**Comment by tomearly** [comment]
Hi turukawa,

Did you find an answer to your question, as I am trying to work out the same thing.

Thanks,

Tom

**Comment by turukawa** [comment]
Hi @tomearly ... Nope, couldn't get it to work using Buefy and dropped back to boilerplate Bulma. You can see it in operation on the search filters on the site: https://sqwyre.com

**Comment by vnt-83** [comment]
Problem is actual
