### ISSUE TITLE
breaking changes to Dialog in 0.6.7

### ISSUE THREAD

**Issue by apmontgomery** [buefy/buefy#986]
### Overview of the problem

**Buefy** version: [0.6.7]
**Nuxt** version: [1.4.1]
**OS/Browser**: All

### Description

Previously you could ```import { Dialog } from 'buefy'``` in store, then call Dialog.confirm.  This throws an error as Dialog is not defined.

### Steps to reproduce

as above

### Expected behavior

to be able to launch a dialog from store actions

### Actual behavior

Dialog not available from import

**Comment by jtommy** [comment]
We added a real single components import.
You have to use it:
```
import Dialog from 'buefy/dist/components/dialog'
Vue.use(Dialog)
```
and then
`this.$dialog.alert('Example')`

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/commit/9e22a1dbf7165802192cfbd6342ab5ffbcf5c17e
