### ISSUE TITLE
extending components in 0.6.7

### ISSUE THREAD

**Issue by ais-one** [buefy/buefy#988]
### Overview of the problem

**Buefy** version: 0.6.7
**Vuejs** version: 2.5.17
**OS/Browser**: MacOS

### Description

The components that I override have error, this is probably due to the new way of loading Buefy components.

Is there something to get this working? Current the app crashes saying props cannot be found

```
// Used to work up till 0.6.6

import Vue from 'vue'
import Buefy from 'buefy'

Buefy.Tabs = {
  ...Buefy.Tabs,
  props: { ...Buefy.Tabs.props, ...{ animated: false } }
}

Vue.use(Buefy)
```

**Comment by jtommy** [comment]
@ais-one You should import components from source.
 For example `import Tabs from 'buefy/src/components/tabs/Tabs`, extend it and then set to `Vue.component(Tabs.name, Tabs)`.

**Comment by ais-one** [comment]
Thanks will try it out and feedback the result

**Comment by lsmith77** [comment]
I am still a bit fresh with Vue, is there a documentation to illustrate with an example how to extend a component?
