### ISSUE TITLE
Custom Class Name for Table Component? - Suggestion/Feature Request

### ISSUE THREAD

**Issue by hasyemiraws** [buefy/buefy#989]
Hi sorry if this might be duplicate since i can't find related to this one, but i just noticed there's no custom class prop for Table element, i just discovered this on Table Component, but maybe other components as well, not sure.

Would be nice if there's that props for that, so i can use it to modify the styling.

Or if there is any other way to do it, please let me know!

I'm using the latest version of Buefy and Vue btw.

**Comment by jtommy** [comment]
When you set class attribute to table that is applied on wrapper div but if you want customize table tag you have to create a class that change the internal table.
For example
```
.my-class {
   table {
      your code..
   }
}
```

**Comment by hasyemiraws** [comment]
Ah ok, sorry forgot to mention that i want to apply it directly to the table it self, not on the wrapper, but this works too, thanks!

But anyway I ended up using Vue Mixin, copy and modify the template so i can add more props and option to the component.
