### ISSUE TITLE
Named components import doesn't work anymore

### ISSUE THREAD

**Issue by daividh** [buefy/buefy#990]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [3.0.1]
**OS/Browser**: Windows 10 / Chrome 68
### Description

Since Buefy 0.6.7, importing Toast (and probably others like Dialog) doesn't work anymore.
Therefore, we're unable to do things like Toast.open(...)

### Steps to reproduce

With Buefy 0.6.6 :
import { Toast } from 'buefy'
console.log(Toast) <- OK

With Buefy 0.6.7 :
import { Toast } from 'buefy'
console.log(Toast) <- undefined

**Comment by jtommy** [comment]
Same issue https://github.com/buefy/buefy/issues/986

**Comment by daividh** [comment]
Prior to Buefy 0.6.7, I was able to do things like this without having a reference to Vue and 'this':

```
import { Toast } from 'buefy';

Toast.open({
  message: 'Success !',
  type: 'is-success',
});
```
Now with the new system, it seams components must be used with Vue :
```
import Toast from 'buefy/dist/components/toast'
Vue.use(Toast)
this.$toast.open(.....')
```
How can I use Toast without having a reference to Vue and therefore not have a reference to 'this' ?

**Comment by jtommy** [comment]
You have to import `buefy/src/components/toast/Toast` but you need a programmatic way take a look here https://github.com/buefy/buefy/blob/dev/src/components/toast/index.js

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/9e22a1dbf7165802192cfbd6342ab5ffbcf5c17e. 
Will be possible import only component.

**Comment by ArthurN** [comment]
For anyone using TypeScript, you'll want to declare the module. Here's an example with ModalProgrammatic, but it should be the same idea for Toast, Snackbar, etc.

```ts
// buefy.d.ts
declare module "buefy/dist/components/modal" {
  import { ModalProgrammatic as _ModalProgrammatic } from "buefy";
  export const ModalProgrammatic: typeof _ModalProgrammatic;
}
```

The typings were added via #465 but only to the root "buefy" module.
