### ISSUE TITLE
How to install programmatic components when "customizing"?

### ISSUE THREAD

**Issue by daanaerts** [buefy/buefy#993]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.17]
**OS/Browser**: Chrome/MacOS

### Description

Howdy, 

I've switched to component-specific registration after upgrading to 0.6.7. Thanks for adding!

```
import Vue from "vue";
import Buefy from "buefy";
Vue.component(Buefy.Dropdown.name, Buefy.Dropdown);
Vue.component(Buefy.Loading.name, Buefy.Loading);
// etc...
```
Works like a charm!

What I don't see in the docs is how to register components that need to be added to the Vue prototype. 

```

// How to install e.g. snackbar?
Vue.protoype['$snackbar'] = Buefy.Snackbar // snack bar isn't exported as component
Buefy.install('$snackbar') // I dunno dude
```

### Expected behaviour
Registering "programmatic" components  to be explained in docs

### Actual behaviour
Registering "programmatic" components not explained in docs

**Comment by jtommy** [comment]
Why are you importing all bundle and registering single components?

**Comment by daanaerts** [comment]
@jtommy thanks. 

RE:

> Why are you importing all bundle and registering single components?

because it's as demonstrated in your docs. 
https://buefy.github.io/#/documentation/customization

**Comment by jtommy** [comment]
@daanaerts I think you're reading old docs. Clean cache and see the start page
