### ISSUE TITLE
Table Header not shown when perPage value changes

### ISSUE THREAD

**Issue by pflirae** [buefy/buefy#994]
### Overview of the problem

When the value of perPage changes and the new value is smaller than the previous value, the header of the table is not show.

**Buefy** version: 0.6.7
**Vuejs** version: 2.5.17
**OS/Browser**: Window 10, Chrome 69 and Firefox 62

### Description

When the value of perPage changes and the new value is samller then the previous one, the header of the table is not show, if the new value is bigger, the header is shown.

### Steps to reproduce

Going from a perPage of 10 to a perPage of 5, the header is not shown. When going from a perPage of 5 to a perPage of 10, the header is show.
If the initial value is 5 and go to 10, the header is shown, and then back to 5, the header is not shown.

### Expected behavior

Expect to have the table header shown in all cases, that is, not depending on the new value of the perPage propertie.

### Actual behavior

Just an example, when the value of perPage is 10, we have the following screen:

![image](https://user-images.githubusercontent.com/9519459/45566003-c8fe1780-b82b-11e8-9279-baef98f793a1.png)

When it is chaged to 5, the screen is:

![image](https://user-images.githubusercontent.com/9519459/45566028-df0bd800-b82b-11e8-9ba2-608014fcc4ea.png)

As it is show, no header when going from a perPage of 10 to a perPage of 5. If you go back from 5 to 10, the header is shown again.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/992

**Comment by pflirae** [comment]
Thanks, the fix worked perfect. Didn't see the #992 issue before posting this one.

**Comment by kraucy** [comment]
This is still happening in 0.7.2.

**Comment by jtommy** [comment]
@kraucy can you provide an example?

**Comment by kraucy** [comment]
@jtommy ![tabledelete](https://user-images.githubusercontent.com/18158874/58275910-f603b200-7d4a-11e9-8ed9-db37c690a1a1.gif)
