### ISSUE TITLE
Icons are broken in new release.

### ISSUE THREAD

**Issue by MHassanSaqib** [buefy/buefy#995]
Hi, 

I am writing a code in Buefy and found that icons are broken in latest release. Even they are appearing broken on buefy website under different example codes etc. and on navbar also. Below is the reference link:

https://buefy.github.io/#/documentation/input  

Could you please help me to resolve the issue?

**Comment by davedoesdev** [comment]
Interesting, they were working earlier for me.
Maybe a static hosting site is down?

**Comment by MHassanSaqib** [comment]
@davedoesdev I have downloaded buefy and using it in my project. Icons are broken on machine too..

**Comment by davedoesdev** [comment]
Which URL is buefy on your machine trying to get icons from?

**Comment by MHassanSaqib** [comment]
buefy is using older version of fontawesome i think. How can I use different version of fontawesome? Any hints?

**Comment by MHassanSaqib** [comment]
for example: 
`                                <b-icon
                                    icon="facebook"
                                    size="is-large"
                                    type="is-white">
                                </b-icon>`

is rendering as follows:

`<i class="fas fa-facebook fa-3x"></i>`

while the newer version 5x renders it like` <i class="fab fa-facebook-f"></i>`

**Comment by davedoesdev** [comment]
I thought it used material design icons?
What does Chrome debugger say it's 404ing on?

**Comment by MHassanSaqib** [comment]
Chrome debugger is showing no error. Icons are just broken replaced with rectangles. I think, there is a fixable gap for 5.0 version. Even the icons are broken on buefy website as well.

**Comment by MHassanSaqib** [comment]
I temprary fixed the issues on my project-end by replacing <b-icon> component with plain code of fontawesome .

**Comment by MeikelLP** [comment]
On the docs side it because the cached images of github.io are broken. If you go `CTRL` + `F5` in your browser the icons should be there. It's probably because [Azure had some problems](https://azure.microsoft.com/en-us/status/history/) at the time buefy was deployed.

**Comment by ais-one** [comment]
I see these errors on the buefy site

```
GET https://buefy.github.io/static/fonts/materialdesignicons-webfont.5cdddea.woff2 net::ERR_ABORTED 404
GET https://buefy.github.io/static/fonts/fa-regular-400.915442a.woff2 net::ERR_ABORTED 404
GET https://buefy.github.io/static/fonts/fa-regular-400.5e3bdde.woff net::ERR_ABORTED 404
GET https://buefy.github.io/static/fonts/fa-regular-400.9dcd747.ttf net::ERR_ABORTED 404
```

Also I tried installing 0.6.7, I use webpack, there was an error about not being able to find the import 'buefy/lib/buefy.css'. I had to use 0.6.6

May the files from the machine I am accessing are corrupted?

**Comment by crickford** [comment]
@ais-one This is a known issue with the 0.6.7 release, see pr #997

The CSS file has moved to `buefy/dist/buefy.css`
