### ISSUE TITLE
How can I disable inputs validation?

### ISSUE THREAD

**Issue by jmaczan** [buefy/buefy#996]
### Overview of the problem

**Buefy** version: 0.6.7
**Vuejs** version: 2.5.17
**OS/Browser**: macOS High Sierrra, Chrome 69

### Description

How can I disable inputs validation? (https://buefy.github.io/documentation/input, section Validation)
I want to use different library to validation (Vee Validate) and currently Buefy prevents some desired behaviors in different library.

### Expected behavior

I expect that there will be some way to disable automatic HTML5 validation through Buefy.

**Comment by jtommy** [comment]
What's the problem? I use vee-validate and I have no problems, you shouldn't use html 5 validation attributes.

**Comment by jmaczan** [comment]
I am talking about error message 

> Please include an '@' in the email address. '' is missing an '@'

which appears on a short moment. This error message comes from enabled HTML 5 validation in Buefy. I want to be able to disable the default HTML 5 validation in order to to localize to my language all vee-validate error messages.

**Comment by jtommy** [comment]
I think it's no possible. At the moment you have to use text as type of the input.

**Comment by jmaczan** [comment]
Allright, thank you for quick response. Shall I create any feature request?

**Comment by jtommy** [comment]
Yes, i think..
