### ISSUE TITLE
Small documentation fixes on Datepicker and Timepicker

### ISSUE THREAD

**Issue by pflirae** [buefy/buefy#999]
### Overview of the problem
Some documentation on Datepicker and Timepicker are missleading, specifically the size property documentation, where it is says "Vertical size of input and picker, optional", but should say "Vertical size of input, optional", since the picker size is not afected.

It can be usefull to have a picker-size property that only afect the picker size, and maintain the size property only to the input field.

Also on Timepicker, the inline property documentation says "Datepicker is shown inline, input is removed", but should say "Timepicker is shown inline, input is removed".

**Buefy** version: 0.6.7

**Comment by jtommy** [comment]
@pflirae Thanks, you might make a PR of you want
